(function(){'use strict';
  var root=document.getElementById('adminApp'),members=[],stream=null,scanLoop=0,detector=null,scanning=false,checkinReady=true,messageUnread=0;
  function h(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function memberName(m){return String((m.first_name||'')+' '+(m.last_name||'')).trim()||'Member'}
  function adminDate(){try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date()).toUpperCase()}catch(e){return''}}
  function api(body){return fetch('/api/admin',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})}).then(async function(r){var j={};try{j=await r.json()}catch(e){}if(r.status===401){location.reload();throw new Error('Coach sign-in required.')}if(!r.ok)throw new Error(j.error||'Request failed.');return j})}
  function queryLink(path,member,extra){var q=new URLSearchParams(extra||{});if(member)q.set('member',member.id);return path+(q.toString()?'?'+q.toString():'')}
  function render(recent){
    var rows=(recent||[]).slice(0,7).map(function(x){var rm=members.find(function(y){return String(y.id)===String(x.member_id)});return'<div class="admin-recent-row"><b>'+h(rm?memberName(rm):'Member')+'</b><span>'+Math.max(0,Number(x.remaining_after)||0)+' left</span></div>'}).join('')||'<p class="admin-empty">No QR check-ins yet.</p>';
    root.className='admin-app';root.innerHTML='<section class="admin-topline" aria-label="FOB administration context"><span>FOB SYSTEMS</span><b>ADMIN</b><time>'+h(adminDate())+'</time></section><header class="admin-head"><i class="admin-head__diamond" aria-hidden="true"></i><h1>FOB ADMIN</h1><p>Manage members, inquiries, sessions, and FOB reporting.</p></header>'
      +'<section class="admin-canonical-entry"><div><span>COACHING</span><h2>MAHFITT COACH MODE</h2><p>Open Today, Clients, Messages, Resources, and client fitness.</p></div><a class="mf-canon-button" href="/mygym?entry=coach">OPEN COACH MODE <i aria-hidden="true">›</i></a></section>'
      +'<nav class="admin-core-links" aria-label="FOB business administration"><a class="mf-canon-button" href="/form-review">MAH INQUIRIES</a><a class="mf-canon-button" id="membersEdit" href="/fob-payment">MEMBERS EDIT</a><a class="mf-canon-button" id="fobreakdown" href="/report-cards.html?coach=1">FOBreakdown</a><a class="mf-canon-button admin-message-link" href="/mygym?entry=coach&amp;coachView=coach-inbox">COACH MESSAGES'+(messageUnread?'<i>'+Math.min(99,messageUnread)+'</i>':'')+'</a></nav>'
      +'<div class="admin-grid"><section class="admin-card admin-scan-card"><header class="admin-card-head"><div><span>SESSION CONTROL</span><h2>Check In</h2></div></header><p>Open the square scanner, point it at the member’s MAHFITT code, and one session is deducted once.</p><button id="adminScan" class="admin-scan mf-canon-button" type="button"'+(checkinReady?'':' disabled')+'>'+(checkinReady?'SCAN MEMBER QR':'QR SETUP REQUIRED')+'</button><div id="adminScanResult" class="admin-scan-result" role="status">'+(checkinReady?'':'Run Supabase migration 039 before the first check-in.')+'</div><div class="admin-recent"><h2>RECENT CHECK-INS</h2><div class="admin-recent-list">'+rows+'</div></div></section></div>'
      +'<section id="adminScanner" class="admin-scanner" hidden aria-label="Member QR scanner"><video id="adminScannerVideo" playsinline muted></video><div class="admin-scanner-shade" aria-hidden="true"></div><div class="admin-scanner-guide" aria-hidden="true"></div><button id="adminScannerClose" class="admin-scanner-close" type="button" aria-label="Close scanner"><span aria-hidden="true">×</span></button><button id="adminNativeHint" class="admin-scanner-native mf-canon-button" type="button" hidden>USE PHONE CAMERA INSTEAD</button><p id="adminScannerStatus" class="admin-scanner-status">PLACE THE MEMBER CODE INSIDE THE SQUARE</p></section>';
    document.getElementById('adminScan').onclick=openScanner;document.getElementById('adminScannerClose').onclick=closeScanner;
  }
  function parseToken(raw){var value=String(raw||'').trim(),uuid='[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}',match=value.match(new RegExp('(?:[?&]checkin=|FOB-CHECKIN:)('+uuid+')','i'));if(match)return match[1];if(new RegExp('^'+uuid+'$','i').test(value))return value;return''}
  async function consume(token,fromCamera){if(scanning)return;scanning=true;var status=document.getElementById('adminScannerStatus'),result=document.getElementById('adminScanResult');if(status)status.textContent='CHECKING MEMBER…';try{var j=await api({action:'scan',token:token});if(status)status.textContent=j.checkin.name+' · '+j.checkin.remaining+' SESSIONS LEFT';if(result)result.textContent=j.checkin.name+' checked in · '+j.checkin.remaining+' sessions left';if(navigator.vibrate)navigator.vibrate([50,45,90]);setTimeout(function(){closeScanner();boot(false)},fromCamera?750:1100)}catch(e){if(status)status.textContent=e.message;if(result)result.textContent=e.message;setTimeout(function(){scanning=false;if(status)status.textContent='PLACE THE MEMBER CODE INSIDE THE SQUARE'},1800)}}
  async function detectFrame(){if(!stream||!detector||scanning)return;var video=document.getElementById('adminScannerVideo');try{if(video&&video.readyState>=2){var hits=await detector.detect(video);if(hits&&hits[0]){var token=parseToken(hits[0].rawValue);if(token){consume(token,true);return}}}}catch(e){}scanLoop=requestAnimationFrame(detectFrame)}
  async function openScanner(){var layer=document.getElementById('adminScanner'),status=document.getElementById('adminScannerStatus'),hint=document.getElementById('adminNativeHint');if(!layer||!checkinReady)return;layer.hidden=false;document.body.style.overflow='hidden';scanning=false;hint.hidden=true;status.textContent='OPENING CAMERA…';try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1280}}});var video=document.getElementById('adminScannerVideo');video.srcObject=stream;await video.play();if('BarcodeDetector'in window){detector=new BarcodeDetector({formats:['qr_code']});status.textContent='PLACE THE MEMBER CODE INSIDE THE SQUARE';detectFrame()}else{status.textContent='THIS BROWSER USES THE PHONE CAMERA APP FOR QR CODES';hint.textContent='CLOSE · USE PHONE CAMERA';hint.hidden=false;hint.onclick=closeScanner}}catch(e){status.textContent='CAMERA ACCESS IS OFF — ALLOW CAMERA, THEN TRY AGAIN';hint.textContent='CLOSE';hint.hidden=false;hint.onclick=closeScanner}}
  function closeScanner(){cancelAnimationFrame(scanLoop);scanLoop=0;detector=null;scanning=false;if(stream){stream.getTracks().forEach(function(t){t.stop()});stream=null}var layer=document.getElementById('adminScanner');if(layer)layer.hidden=true;document.body.style.overflow=''}
  async function boot(showLoading){if(showLoading!==false){root.className='admin-loading'}try{var data=await api({action:'boot'});members=Array.isArray(data.members)?data.members:[];checkinReady=data.checkinReady!==false;messageUnread=Math.max(0,Number(data.messageUnread)||0);var q=new URLSearchParams(location.search);render(data.recent||[]);var token=parseToken(q.get('checkin'));if(token){history.replaceState(null,'',location.pathname);if(!checkinReady){var unavailable=document.getElementById('adminScanResult');if(unavailable)unavailable.textContent='Run Supabase migration 039 before scanning this member.';return}setTimeout(function(){var layer=document.getElementById('adminScanner');if(layer){layer.hidden=false;document.body.style.overflow='hidden';document.getElementById('adminScannerStatus').textContent='CHECKING MEMBER…'}consume(token,false)},120)}}catch(e){root.className='admin-fatal';root.innerHTML='<section><h1>ADMIN</h1><p>'+h(e.message)+'</p><button type="button" id="adminRetry">TRY AGAIN</button></section>';document.getElementById('adminRetry').onclick=function(){boot(true)}}}
  document.addEventListener('keydown',function(e){if(e.key==='Escape')closeScanner()});window.addEventListener('pagehide',closeScanner);boot(true);
}());
