(function(){'use strict';
  if(document.querySelector('.coach-shell'))return;
  var BRIDGE_KEY='fob.mygym.theme.active-account.v1';
  var COLLAPSE_KEY='fob.coach.crown.collapsed.v1';
  var RETURN_KEY='fob.mygym.globalToolReturn.v1';
  var collapsed=false,prefs=canonicalTheme()||{primary:'#0e1114',secondary:'#e9c98f',motion:true};
  try{collapsed=localStorage.getItem(COLLAPSE_KEY)==='1'}catch(e){}

  function canonicalTheme(){try{var x=JSON.parse(localStorage.getItem(BRIDGE_KEY)||'null'),t=x&&x.theme||x;if(t&&/^#[0-9a-f]{6}$/i.test(String(t.dark||''))&&/^#[0-9a-f]{6}$/i.test(String(t.accent||'')))return{primary:String(t.dark),secondary:String(t.accent),motion:t.motion!==false,canonical:true}}catch(e){}return null}
  function apply(){var c=canonicalTheme();if(c)prefs=c;var s=document.documentElement.style,p=prefs.primary||'#0e1114',q=prefs.secondary||'#e9c98f',panel='color-mix(in srgb,'+p+' 88%,#fff 12%)',panel2='color-mix(in srgb,'+p+' 82%,#fff 18%)',line='color-mix(in srgb,'+q+' 25%,transparent)',soft='color-mix(in srgb,'+q+' 13%,transparent)';
    [['--coach-surface',p],['--coach-panel',panel],['--coach-primary',q],['--coach-secondary',q],['--secondary',q],['--bright',q],['--admin-bg',p],['--admin-panel',panel],['--admin-panel-2','color-mix(in srgb,'+p+' 94%,#000 6%)'],['--admin-primary',q],['--admin-secondary',q],['--bg',p],['--ink',p],['--deep',p],['--tone-black',p],['--tone-deep','color-mix(in srgb,'+p+' 92%,#000 8%)'],['--ink-warm',panel],['--ink2',panel],['--ink3',panel2],['--panel',panel],['--panel2',panel2],['--panel-2',panel2],['--card',panel2],['--lock',panel],['--surface',panel],['--gold',q],['--gold-bright',q],['--gold-dim','color-mix(in srgb,'+q+' 72%,#777 28%)'],['--dim','color-mix(in srgb,'+q+' 72%,#777 28%)'],['--olive','color-mix(in srgb,'+q+' 72%,#777 28%)'],['--gold-line',line],['--gold-line-soft',soft],['--line',line],['--line2',soft],['--rule',soft],['--olive-deep','color-mix(in srgb,'+q+' 20%,transparent)'],['--cal-bg',p],['--cal-accent',q],['--mg-bg',p],['--mg-gold',q],['--mg-bright',q]].forEach(function(pair){s.setProperty(pair[0],pair[1])});
    document.documentElement.dataset.coachTheme='1';document.documentElement.classList.toggle('coach-motion-off',prefs.motion===false)
  }
  function icons(){return{
    wave:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12h2m1-4v8m2-11v14m2-9v4m2-8v12m2-15v18m2-13v8m2-10v12m2-7v2m1-1h2"/></svg>',
    ai:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 21 12 12 21 3 12Z"/><path d="m12 7 5 5-5 5-5-5Z"/><circle cx="12" cy="12" r="1.6"/></svg>',
    theme:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 19 8.4 10l3.2 4.7L15.5 8 21 19Z"/><path d="m14 10 1.5 2.2 1.3-1.7"/></svg>',
    message:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4.25 6.25h15.5v9.2H11.6l-4.35 2.8v-2.8h-3z"/><path d="m9.2 10.9 1.55 1.55 3.45-3.6"/></svg>'
  }}
  function rememberReturn(){try{var here=location.pathname+(location.search||'')+(location.hash||'');if(here&&here.charAt(0)==='/'&&here.slice(0,2)!=='//')sessionStorage.setItem(RETURN_KEY,here)}catch(e){}}
  function openCanonicalTool(kind){if(kind==='player'||kind==='theme')rememberReturn();var q='/mygym?entry=coach&audio='+encodeURIComponent(kind);if(kind==='player'||kind==='theme')q+='&externalTool=1';location.assign(q)}
  function mount(){if(document.querySelector('.coach-shell'))return;apply();document.body.classList.add('coach-shell-mounted');document.body.classList.toggle('coach-shell-collapsed',!!collapsed);var i=icons(),bar=document.createElement('aside');bar.className='coach-shell';bar.dataset.collapsed=collapsed?'1':'0';bar.setAttribute('aria-label','MAHFITT crown');bar.innerHTML='<div class="coach-shell__occlusion" aria-hidden="true"></div><div class="coach-shell__inner"><button type="button" class="coach-tool coach-shell__message" data-coach="messages" aria-label="Open Coach Messages">'+i.message+'</button><a class="coach-shell__admin" href="/admin">FOB ADMIN</a><div class="coach-shell__side coach-shell__side--left"><span class="coach-shell__label">PLAYER</span><div class="coach-shell__pair"><button type="button" class="coach-tool" data-coach="player" aria-label="Open MAH Player">'+i.wave+'</button><button type="button" class="coach-tool coach-tool__play" data-coach="player" aria-label="Open MAH Player transport"></button></div></div><a class="coach-shell__brand" href="/admin" aria-label="FOB Admin home"><span class="coach-shell__mark" aria-hidden="true"></span><span class="coach-shell__transport" aria-hidden="true"><i>◀◀</i><b></b><i>▶▶</i></span></a><div class="coach-shell__side coach-shell__side--right"><span class="coach-shell__label">THEME</span><div class="coach-shell__pair"><button type="button" class="coach-tool" data-coach="ai" aria-label="Open MAHFITT AI">'+i.ai+'</button><button type="button" class="coach-tool" data-coach="theme" aria-label="Open Theme Editor">'+i.theme+'</button></div></div><div class="coach-shell__utility" aria-hidden="true"><i class="coach-shell__volume"></i><div class="coach-shell__seek"><i></i><b></b></div><div class="coach-shell__effects"><span>VHS</span><em>REPLAY</em><span>REVERB</span></div></div><button type="button" class="coach-shell__collapse" data-coach="collapse" aria-label="'+(collapsed?'Expand':'Collapse')+' MAHFITT crown" aria-expanded="'+(collapsed?'false':'true')+'"><svg viewBox="0 0 16 10" aria-hidden="true"><path d="M2.5 7.5 8 2.5l5.5 5"/></svg></button></div>';document.body.prepend(bar);bar.addEventListener('click',click);paint()}
  function paint(){document.body.classList.toggle('coach-shell-collapsed',!!collapsed);var shell=document.querySelector('.coach-shell');if(shell){shell.dataset.collapsed=collapsed?'1':'0';var c=shell.querySelector('[data-coach="collapse"]');if(c){c.setAttribute('aria-expanded',collapsed?'false':'true');c.setAttribute('aria-label',(collapsed?'Expand':'Collapse')+' MAHFITT crown')}}}
  function click(e){var b=e.target.closest('[data-coach]');if(!b)return;var a=b.dataset.coach;if(a==='collapse'){collapsed=!collapsed;try{localStorage.setItem(COLLAPSE_KEY,collapsed?'1':'0')}catch(x){}paint();return}if(a==='player'){openCanonicalTool('player');return}if(a==='theme'){openCanonicalTool('theme');return}if(a==='ai'){openCanonicalTool('ai');return}if(a==='messages'){location.assign('/mygym?entry=coach&coachView=coach-inbox')}}
  window.addEventListener('storage',function(e){if(e.key===BRIDGE_KEY)apply()});window.addEventListener('pageshow',apply);window.addEventListener('focus',apply);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
}());
