(function(){'use strict';
if(window.FOBImageCrop)return;
var STYLE_ID='fobImageCropStyle';
function addStyles(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='\
.fobcrop{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.76);backdrop-filter:blur(13px);-webkit-backdrop-filter:blur(13px);font-family:inherit;color:#f7f4ee}.fobcrop__card{width:min(430px,100%);max-height:calc(100dvh - 36px);overflow:auto;border:1px solid rgba(var(--bright-rgb,233,201,143),.34);background:rgb(var(--ink-rgb,14,17,20));box-shadow:0 24px 80px rgba(0,0,0,.62),0 0 30px rgba(var(--bright-rgb,233,201,143),.08)}.fobcrop__head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 16px;border-bottom:1px solid rgba(var(--bright-rgb,233,201,143),.15)}.fobcrop__head span{font-size:10px;font-weight:750;letter-spacing:.2em;text-transform:uppercase;color:var(--bright,#e9c98f)}.fobcrop__x{width:32px;height:32px;border:0;background:transparent;color:#f7f4ee;font:300 24px/1 inherit}.fobcrop__body{padding:16px}.fobcrop__help{margin:0 0 12px;color:#8f969f;font-size:11px;line-height:1.5}.fobcrop__frame{position:relative;width:min(76vw,320px);aspect-ratio:1;margin:0 auto;overflow:hidden;touch-action:none;cursor:grab;background:#080a0c;box-shadow:inset 0 0 0 1px rgba(var(--bright-rgb,233,201,143),.42)}.fobcrop__frame:active{cursor:grabbing}.fobcrop__frame img{position:absolute;left:50%;top:50%;max-width:none;max-height:none;transform-origin:center;pointer-events:none;user-select:none;-webkit-user-drag:none;will-change:transform}.fobcrop__frame:after{content:"";position:absolute;inset:0;pointer-events:none;box-shadow:inset 0 0 0 1px rgba(255,255,255,.15),inset 0 0 28px rgba(0,0,0,.22)}.fobcrop__zoom{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;margin:16px 0}.fobcrop__zoom span{font-size:9px;letter-spacing:.14em;color:#8f969f}.fobcrop__zoom input{width:100%;accent-color:var(--bright,#e9c98f)}.fobcrop__actions{display:grid;grid-template-columns:1fr 1.35fr;gap:9px}.fobcrop__actions button{min-height:46px;border:1px solid rgba(var(--bright-rgb,233,201,143),.28);background:transparent;color:#f7f4ee;font:700 9px/1 inherit;letter-spacing:.16em;text-transform:uppercase}.fobcrop__actions .fobcrop__use{border-color:rgba(var(--bright-rgb,233,201,143),.65);background:var(--bright,#e9c98f);color:var(--accent-ink,#0e1114)}.fobcrop button{touch-action:manipulation}.fobcrop button:focus-visible,.fobcrop input:focus-visible{outline:2px solid var(--bright,#e9c98f);outline-offset:2px}@media(max-width:420px){.fobcrop{padding:10px}.fobcrop__card{max-height:calc(100dvh - 20px)}.fobcrop__body{padding:13px}.fobcrop__frame{width:min(82vw,310px)}}';document.head.appendChild(s)}
function fileName(file){var base=String(file&&file.name||'photo').replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'-').slice(0,60)||'photo';return base+'-cropped.jpg'}
function asFile(blob,name){try{return new File([blob],name,{type:'image/jpeg',lastModified:Date.now()})}catch(e){try{blob.name=name}catch(x){}return blob}}
function open(file,options){options=options||{};return new Promise(function(resolve,reject){
  if(!file||!/^image\//i.test(String(file.type||''))){reject(new Error('Choose an image file.'));return}
  addStyles();var priorOverflow=document.body.style.overflow,done=false,url=URL.createObjectURL(file),size=Math.max(256,Math.min(1600,Number(options.size)||768));
  var modal=document.createElement('div');modal.className='fobcrop';modal.innerHTML='<section class="fobcrop__card" role="dialog" aria-modal="true" aria-labelledby="fobCropTitle"><header class="fobcrop__head"><span id="fobCropTitle">'+String(options.title||'Crop photo').replace(/[&<>]/g,'')+'</span><button class="fobcrop__x" type="button" aria-label="Cancel crop">×</button></header><div class="fobcrop__body"><p class="fobcrop__help">Drag the photo to position it. Use the slider to zoom. The square shown here is exactly what will be saved.</p><div class="fobcrop__frame"><img alt="Crop preview"></div><label class="fobcrop__zoom"><span>FIT</span><input type="range" min="100" max="350" step="1" value="100" aria-label="Photo zoom"><span>ZOOM</span></label><div class="fobcrop__actions"><button class="fobcrop__cancel" type="button">Cancel</button><button class="fobcrop__use" type="button">Use photo</button></div></div></section>';
  document.body.appendChild(modal);document.body.style.overflow='hidden';
  var frame=modal.querySelector('.fobcrop__frame'),img=modal.querySelector('img'),zoom=modal.querySelector('input'),state={iw:0,ih:0,base:1,zoom:1,x:0,y:0,drag:null};
  function dimensions(){var r=frame.getBoundingClientRect();return{w:Math.max(1,r.width),h:Math.max(1,r.height)}}
  function clamp(){var d=dimensions(),scale=state.base*state.zoom,maxX=Math.max(0,(state.iw*scale-d.w)/2),maxY=Math.max(0,(state.ih*scale-d.h)/2);state.x=Math.max(-maxX,Math.min(maxX,state.x));state.y=Math.max(-maxY,Math.min(maxY,state.y))}
  function paint(){clamp();img.style.width=state.iw+'px';img.style.height=state.ih+'px';img.style.transform='translate(-50%,-50%) translate3d('+state.x+'px,'+state.y+'px,0) scale('+(state.base*state.zoom)+')'}
  function cleanup(error,result){if(done)return;done=true;URL.revokeObjectURL(url);document.body.style.overflow=priorOverflow;modal.remove();document.removeEventListener('keydown',escape);if(error)reject(error);else resolve(result)}
  function cancel(){var e=new Error('Photo crop cancelled.');e.cancelled=true;cleanup(e)}
  function escape(e){if(e.key==='Escape')cancel()}
  document.addEventListener('keydown',escape);modal.querySelector('.fobcrop__x').onclick=cancel;modal.querySelector('.fobcrop__cancel').onclick=cancel;
  img.onload=function(){state.iw=img.naturalWidth||1;state.ih=img.naturalHeight||1;var d=dimensions();state.base=Math.max(d.w/state.iw,d.h/state.ih);paint();modal.querySelector('.fobcrop__use').focus()};img.onerror=function(){cleanup(new Error('That image could not be opened.'))};img.src=url;
  zoom.addEventListener('input',function(){state.zoom=Math.max(1,(Number(zoom.value)||100)/100);paint()});
  frame.addEventListener('pointerdown',function(e){if(state.drag)return;state.drag={id:e.pointerId,x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};try{frame.setPointerCapture(e.pointerId)}catch(x){}e.preventDefault()},{passive:false});
  frame.addEventListener('pointermove',function(e){var d=state.drag;if(!d||d.id!==e.pointerId)return;state.x=d.ox+e.clientX-d.x;state.y=d.oy+e.clientY-d.y;paint();e.preventDefault()},{passive:false});
  function end(e){if(!state.drag||(e&&e.pointerId!==state.drag.id))return;state.drag=null}frame.addEventListener('pointerup',end);frame.addEventListener('pointercancel',end);frame.addEventListener('lostpointercapture',end);
  modal.querySelector('.fobcrop__use').onclick=function(){if(!state.iw)return;var d=dimensions(),scale=state.base*state.zoom,left=d.w/2-state.iw*scale/2+state.x,top=d.h/2-state.ih*scale/2+state.y,sx=Math.max(0,-left/scale),sy=Math.max(0,-top/scale),sw=Math.min(state.iw,d.w/scale),sh=Math.min(state.ih,d.h/scale),canvas=document.createElement('canvas');canvas.width=canvas.height=size;var ctx=canvas.getContext('2d');ctx.fillStyle=String(options.background||'#0E1114');ctx.fillRect(0,0,size,size);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,sx,sy,sw,sh,0,0,size,size);canvas.toBlob(function(blob){if(!blob){cleanup(new Error('That image could not be processed.'));return}cleanup(null,asFile(blob,fileName(file)))},'image/jpeg',Number(options.quality)||.9)};
});}
window.FOBImageCrop={open:open};
})();
