/* MAHFITT v415 — Month Wrapped statistics engine.
   Pure calculation only: no playback ownership, storage, network or DOM. */
(function(global){
  'use strict';
  function n(v){v=Number(v);return isFinite(v)?v:0}
  function text(v,f){v=String(v==null?'':v).trim();return v||String(f||'')}
  function monthParts(value){var m=/^(\d{4})-(\d{2})$/.exec(String(value||''));if(!m)return null;var y=+m[1],mo=+m[2];return y>=2000&&y<=2200&&mo>=1&&mo<=12?{year:y,month:mo,key:m[1]+'-'+m[2]}:null}
  function currentMonth(now){var d=now instanceof Date?now:new Date(now||Date.now());return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
  function monthLabel(key){var p=monthParts(key);if(!p)return'MONTH';return new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(p.year,p.month-1,1))}
  function shiftMonth(key,delta){var p=monthParts(key);if(!p)return currentMonth();var d=new Date(p.year,p.month-1+(Number(delta)||0),1);return currentMonth(d)}
  function seconds(row,key){return Math.max(0,n(row&&((row[key]!=null?row[key]:row[key.replace(/[A-Z]/g,function(c){return'_'+c.toLowerCase()})]))))}
  function val(row,camel,snake){return row&&row[camel]!=null?row[camel]:row&&row[snake]!=null?row[snake]:''}
  function add(map,key,seed,secondsValue){var x=map[key];if(!x)x=map[key]=Object.assign({},seed,{listenedSeconds:0,workoutSeconds:0,replays:0,starts:0,completions:0,skips:0});x.listenedSeconds+=secondsValue;x.workoutSeconds+=seconds(seed._row,'workoutSeconds');x.replays+=Math.max(0,n(val(seed._row,'replays','replays')));x.starts+=Math.max(0,n(val(seed._row,'starts','starts')));x.completions+=Math.max(0,n(val(seed._row,'completions','completions')));x.skips+=Math.max(0,n(val(seed._row,'skips','skips')));return x}
  function list(map){return Object.keys(map).map(function(k){var x=map[k];delete x._row;return x})}
  function top(rows,metric){return rows.slice().sort(function(a,b){var d=n(b[metric])-n(a[metric]);if(Math.abs(d)>.0001)return d;return n(b.listenedSeconds)-n(a.listenedSeconds)})[0]||null}
  function pct(part,total){return total>0?Math.max(0,Math.min(100,part/total*100)):0}
  function summarize(payload,now){
    payload=payload&&typeof payload==='object'?payload:{};now=now instanceof Date?now:new Date(now||Date.now());var key=monthParts(payload.month)&&payload.month||currentMonth(now),rows=Array.isArray(payload.rows)?payload.rows:[],days=Array.isArray(payload.days)?payload.days:[],hours=Array.isArray(payload.hours)?payload.hours:[];
    var tracks={},themes={},scenes={},total=0,workout=0,starts=0,completions=0,skips=0,replays=0,reverb=0,vhs=0,radio=0,pitch=0,speed=0,effectSamples=0;
    rows.forEach(function(r){var listened=seconds(r,'listenedSeconds');if(listened<=0&&!(n(r.starts)||n(r.replays)||n(r.completions)||n(r.skips)))return;var trackKey=text(val(r,'trackKey','track_key'),'unknown'),source=text(val(r,'sourceType','source_type'),'theme'),title=text(val(r,'title','title'),'MAHFITT Audio'),artist=text(val(r,'artist','artist'),''),themeKey=text(val(r,'themeKey','theme_key'),'theme:default'),themeLabel=text(val(r,'themeLabel','theme_label'),'MAHFITT Theme'),scene=text(val(r,'scene','scene'),'mesh');
      total+=listened;workout+=seconds(r,'workoutSeconds');starts+=Math.max(0,n(r.starts));completions+=Math.max(0,n(r.completions));skips+=Math.max(0,n(r.skips));replays+=Math.max(0,n(r.replays));reverb+=seconds(r,'reverbSeconds');vhs+=seconds(r,'vhsSeconds');radio+=seconds(r,'radioSeconds');pitch+=n(val(r,'pitchSeconds','pitch_seconds'));speed+=Math.max(0,n(val(r,'speedSeconds','speed_seconds')));effectSamples+=seconds(r,'effectSampleSeconds');
      add(tracks,trackKey+'|'+source,{key:trackKey,sourceType:source,title:title,artist:artist,_row:r},listened);
      add(themes,themeKey,{key:themeKey,label:themeLabel,_row:r},listened);
      add(scenes,scene,{id:scene,label:sceneName(scene),_row:r},listened);
    });
    var trackList=list(tracks),themeList=list(themes),sceneList=list(scenes),dayList=days.map(function(r){return{day:text(r.day,''),listenedSeconds:seconds(r,'listenedSeconds'),workoutSeconds:seconds(r,'workoutSeconds')}}).filter(function(r){return r.day&&r.listenedSeconds>0}),hourList=hours.map(function(r){return{hour:Math.max(0,Math.min(23,Math.round(n(val(r,'hour','hour_of_day'))))),listenedSeconds:seconds(r,'listenedSeconds'),workoutSeconds:seconds(r,'workoutSeconds')}}).filter(function(r){return r.listenedSeconds>0}),topTrack=top(trackList,'listenedSeconds'),trainingTrack=top(trackList,'workoutSeconds'),replayedTrack=top(trackList,'replays'),favoriteTheme=top(themeList,'listenedSeconds'),favoriteScene=top(sceneList,'listenedSeconds'),longestDay=top(dayList,'listenedSeconds'),favoriteHour=top(hourList,'listenedSeconds');
    var p=monthParts(key),isCurrent=key===currentMonth(now),isFuture=p?new Date(p.year,p.month-1,1)>new Date(now.getFullYear(),now.getMonth(),1):false,daysInMonth=p?new Date(p.year,p.month,0).getDate():31,progress=isCurrent?Math.max(0,Math.min(100,now.getDate()/daysInMonth*100)):isFuture?0:100;
    return{month:key,monthLabel:monthLabel(key),isCurrent:isCurrent,isFuture:isFuture,partial:isCurrent,totalSeconds:total,totalMinutes:Math.round(total/60),workoutSeconds:workout,workoutMinutes:Math.round(workout/60),workoutPercent:pct(workout,total),uniqueTracks:trackList.filter(function(x){return x.listenedSeconds>0}).length,activeDays:dayList.length,starts:starts,completions:completions,skips:skips,replays:replays,topTrack:topTrack,trainingTrack:trainingTrack&&trainingTrack.workoutSeconds>0?trainingTrack:null,replayedTrack:replayedTrack&&replayedTrack.replays>0?replayedTrack:null,favoriteTheme:favoriteTheme,favoriteScene:favoriteScene,longestDay:longestDay,favoriteHour:favoriteHour,averagePitch:effectSamples>0?pitch/effectSamples:0,averageSpeed:effectSamples>0?speed/effectSamples:1,reverbPercent:pct(reverb,total),vhsPercent:pct(vhs,total),radioPercent:pct(radio,total),progressPercent:progress,daysInMonth:daysInMonth,dayOfMonth:isCurrent?now.getDate():daysInMonth,hasData:!!(total>.05||starts||replays||completions||skips),tracks:trackList.sort(function(a,b){return b.listenedSeconds-a.listenedSeconds}),themes:themeList.sort(function(a,b){return b.listenedSeconds-a.listenedSeconds}),scenes:sceneList.sort(function(a,b){return b.listenedSeconds-a.listenedSeconds})};
  }
  function sceneName(id){return({mesh:'Color Haze',storm:'Thunderstorm',waterfall:'Waterfall',mountain:'Mountain',disco:'Disco',space:'Space'})[String(id||'').toLowerCase()]||'Color Haze'}
  function hourLabel(hour){hour=Math.max(0,Math.min(23,Math.round(n(hour))));var suffix=hour>=12?'PM':'AM',h=hour%12||12;return h+' '+suffix}
  function dayLabel(value){var m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value||''));if(!m)return'';return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(+m[1],+m[2]-1,+m[3]))}
  function shareText(s){if(!s||!s.hasData)return'MAHFITT Month Wrapped · '+text(s&&s.monthLabel,'This month');var parts=['MAHFITT Month Wrapped · '+s.monthLabel,s.totalMinutes+' min played'];if(s.topTrack)parts.push('Top track: '+s.topTrack.title);if(s.favoriteScene)parts.push('Scene: '+s.favoriteScene.label);if(s.workoutMinutes)parts.push(s.workoutMinutes+' workout min');return parts.join(' · ')}
  global.MahfittMMW={summarize:summarize,currentMonth:currentMonth,shiftMonth:shiftMonth,monthLabel:monthLabel,sceneName:sceneName,hourLabel:hourLabel,dayLabel:dayLabel,shareText:shareText};
})(window);
