/* MAHWORLD GAMEPLAY RUNTIME :: LOCAL AUTHORITATIVE DUEL HOST (Phase 5A lab + Phase 5B durable recovery — development only)
   ONE authority owns simulation time, actor identity, resource spending, cooldowns, form restrictions, duel state, damage resolution,
   spectator capacity, queue order, terminal result and development reward receipts. Clients submit INTENT envelopes (Protocol.js).
   Each fighter is a distinct gameplay world composed by the EXISTING composeGameplay (own mahloco, resource, kit, flight, progression);
   the DuelSession / SpectatorSystem / Call Next queue are shared and live on the host bus. Attacks run through the existing
   createAttackExecution ONCE (concentric impact + eccentric ticks); clients only display them.
   Arrival / order policy (recorded): commands execute immediately in host arrival order, stamped with the host tick; per session the seq
   must strictly increase; a resent command_id with the same payload returns the cached ack (idempotent), with a different payload it is a
   CONFLICT. Disconnects follow the named DEVELOPMENT strategy PAUSE_AND_WAIT_DEV (OD-29): pause at the tick boundary, reconnect window
   from dev tuning, OD-29 PARTIALLY APPROVED by the owner 2026-09-14: the disconnected fighter gets reconnect_window_s (10 s) on the host clock (which keeps
   running while gameplay is paused); a reconnect in time resumes the same committed state; expiry ends the duel as NO_CONTEST with NO winner and
   no winner-based Call Next. Rewards on NO_CONTEST: none — INTERIM development setting, not owner canon. Host restart stays RECOVERY_HELD_DEV. Movement uses a tiny host-side integrator on the canonical speed
   bands (BAND_MIN_SPEED_DEV): no physics, no feet, nothing claimed about anti-cheat.

   Phase 5B — COMMIT BEFORE ACKNOWLEDGE. Every state change is journaled through ONE store commit path (DurableStore):
   VALIDATE → STAGE (execute in memory) → DURABLE COMMIT (journal record + receipt rows in one transaction) → PUBLISH / ACK.
   A failed commit never publishes: the host goes FAULTED, the command is answered STORAGE_FAILURE and the staged memory change is not
   authoritative (recovery replays only committed records). Recovery = deterministic replay of the journal from the known start
   (accounts → sessions → commands with stored acks → ticks with periodic fingerprints → receipts restored as state, never re-awarded),
   then the match is HELD in the technical lifecycle state RECOVERY_HELD_DEV (outside mahloco, not a locomotion state): no time advance,
   no winner, no forfeit, no reward, until an explicit developer resume / close. Sessions come back as awaiting reconnection. */
import { createEventLog } from '../00_CORE/events.js';
import { createAttackExecution } from '../05_ECCENTRIC/EccentricRuntime.js';
import { createDuelSession } from '../07_DUEL/DuelSession.js';
import { createSpectatorSystem } from '../08_SPECTATOR/SpectatorSystem.js';
import { createDuelBot } from '../22_DEBUG_BOT/DuelBot.js';
import { validateEnvelope, payloadHash, PROTOCOL_VERSION } from './Protocol.js';
import { createReceiptLedger } from './RewardReceipts.js';
import { createMemoryStore } from './DurableStore.js';
import { createPlayMode, PLAY_ONLY_ACTIONS, PLAY_SHARED_ACTIONS } from './play/PlayMode.js';

export var SESSION_STATES = ['CONNECTING', 'READY', 'IN_DUEL', 'RECONNECTING', 'CLOSED'];
export var LIFECYCLE_STATES = ['LIVE', 'RECONSTRUCTING', 'RECOVERY_HELD_DEV', 'FAULTED'];
export var TARGETING_STRATEGIES = { SOFT_LOCK_IN_DUEL: { id: 'SOFT_LOCK_IN_DUEL', classification: 'EXPERIMENTAL_POLICY (OD-15)', resolve: function (attacker, duel) { if (!duel || duel.state() !== 'ACTIVE') return null; var f = duel.snapshot().fighters; return attacker === f.a ? f.b : (attacker === f.b ? f.a : null); } } };
export function hostIdentity(data) { var cfg = data.cfg; return { protocol: PROTOCOL_VERSION, tuning_version: cfg.raw.dev.tuning_version || null, defaults_classification: cfg.raw.defaults.classification || null, reward_rule_version: cfg.dev('local_authority.reward_rule_version'), store_schema: cfg.dev('local_authority.durable.store_schema_version') }; }
function envCore(env) { return { protocol: env.protocol, session_id: env.session_id, client_id: env.client_id, command_id: env.command_id, seq: env.seq, action: env.action, payload: env.payload === undefined ? {} : env.payload }; }
function ackHash(a) { return payloadHash(a); }

export function createDuelHost(deps) {
  var d = deps; var data = d.data; var cfg = data.cfg; var compose = d.composeHeadless; if (!data || typeof compose !== 'function') throw new Error('createDuelHost needs { data, composeHeadless }');
  var LA = cfg.dev('local_authority'); if (!LA || LA.environment !== 'DEVELOPMENT') throw new Error('local_authority config is not a DEVELOPMENT configuration — refusing to host (unknown / production configuration must fail clearly)');
  if (cfg.raw.dev.classification !== 'EXPERIMENTAL') throw new Error('dev tuning is not EXPERIMENTAL — refusing to host');
  var targeting = TARGETING_STRATEGIES[LA.targeting_strategy]; if (!targeting) throw new Error('unknown targeting strategy ' + LA.targeting_strategy + ' (OD-15)');
  var DUR = LA.durable || {}; var FP_EVERY = DUR.fingerprint_every_ticks || 10; var HOLD = DUR.recovery_hold_state || 'RECOVERY_HELD_DEV';
  var store = d.store || createMemoryStore(); if (!d.store) store.open({ identity: hostIdentity(data) }); if (!store.isOpen()) throw new Error('store must be open before hosting');
  var bus = createEventLog({ max: 20000 }); var receipts = createReceiptLedger(cfg, {});
  var H = { t: 0, tick: 0, version: 0, committedVersion: 0, arrival: 0, accounts: {}, sessions: {}, tokens: {}, fighters: { a: null, b: null }, duel: null, spectators: null, terminal: null, rewards: {}, paused: false, pauseReason: null, log: [], bot: null, sessionSeq: 0, duelSeq: 0, lateCallbacks: 0, lifecycle: 'LIVE', generation: store.generation(), reconstructing: false, fault: null, recovery: null, lastDuel: null, noContest: null, opened: d.opened || null };
  /* DEADLINE CLOCK (OD-29 timing): the reconnect window is measured on an injectable clock separate from simulation time. The live server
     injects a monotonic wall clock; the default is the tick clock (deterministic tests). Every reading that decides a deadline is journaled
     (TICK.dn, SESSION_DISCONNECT.deadline, RESUME / DEV_CLOSE.deadlines, SESSION_EXPIRED.clock_now) so reconstruction never reads a fresh clock. */
  var clock = d.clock || { kind: 'TICK_CLOCK_DEV', now: function () { return H.t; } }; H.replayNow = null; H.replayDeadlines = null;
  function dnow() { return (H.reconstructing && H.replayNow !== null) ? H.replayNow : clock.now(); }
  /* PLAY MODE (playable local sample, 2026-09-14): a delegated delta inside this host — rooms, tutorial, quest, guards, dashes, separate flight pool, skills. Same journal, same receipts, same tick. */
  /* rules 17–23: a new development match freezes the ruleset it was created under — journaled live (RULESET_FREEZE), consumed in order during replay; a journal without the record cannot reconstruct that match and reports RULESET_MISSING through the established inconsistency path */
  H.frozenRules = []; H.replayFrozen = [];
  function freezeRules(live) { if (H.reconstructing) { var f = H.replayFrozen.shift(); if (!f) { H.replayInconsistency = { kind: 'RULESET_MISSING', ruleset: live.ruleset_id }; return { ok: false, reason: 'RULESET_MISSING' }; } var tables = JSON.parse(f.tables); tables._skills_by_id = {}; tables.skills.forEach(function (x) { tables._skills_by_id[x.id] = x; }); return { ok: true, rules: tables }; } var snap = {}; Object.keys(live).forEach(function (k) { if (k !== '_skills_by_id') snap[k] = live[k]; }); var body = { ruleset_id: live.ruleset_id, hash: live._loaded_sha256, tables: JSON.stringify(snap) }; var c = commit('RULESET_FREEZE', body); if (!c.ok) return { ok: false, reason: 'STORAGE_FAILURE' }; var tables2 = JSON.parse(body.tables); tables2._skills_by_id = {}; tables2.skills.forEach(function (x) { tables2._skills_by_id[x.id] = x; }); rec('RULESET_FREEZE', { ruleset: live.ruleset_id, hash: live._loaded_sha256 }); return { ok: true, rules: tables2 }; }
  var play = LA.play ? createPlayMode({ cfg: cfg, H: H, LA: LA, rec: rec, bump: bump, receipts: receipts, isFighter: function (id) { return !!fighterOf(id); }, paused: function () { return H.paused; }, freezeRules: freezeRules }) : null;
  function expireSession(s, k, dn) { rec('RECONNECT_WINDOW_EXPIRED', { session: k, role: s.role, deadline: s.reconnect_deadline, clock_now: dn }); if (play) play.onSessionExpired(s.account_id, dn); if (s.role === 'FIGHTER' && H.duel && H.duel.inCombat()) { H.noContest = { match_id: matchId(), outcome: LA.disconnect_expiry_outcome || 'NO_CONTEST', reason: 'RECONNECT_WINDOW_EXPIRED', fighter: s.account_id, window_s: LA.reconnect_window_s, at_t: +H.t.toFixed(3), winner: null, rewards: 'NONE (INTERIM development setting — owner has not decided participation rewards)' }; closeDuel('NO_CONTEST — reconnect window (' + LA.reconnect_window_s + ' s) expired for ' + s.account_id + '; no winner (OD-29 owner decision 2026-09-14)'); H.lastDuel.result = 'NO_CONTEST'; rec('NO_CONTEST', H.noContest); } else if (s.role === 'SPECTATOR' && H.spectators) { H.spectators.leave(s.account_id); s.role = 'LOBBY'; s.locks = null; } s.state = 'CLOSED'; bump(); }
  function rec(kind, x) { H.log.push(Object.assign({ tick: H.tick, t: +H.t.toFixed(3), kind: kind, reconstructed: H.reconstructing || undefined }, x || {})); if (H.log.length > 6000) H.log.shift(); }
  function bump() { H.version++; }
  function duelState() { return H.duel ? H.duel.state() : null; }
  function matchId() { return H.duel ? 'MATCH_' + H.duelSeq : null; }   /* host-owned, journal-stable match identity (never the DuelSession's process-global id) */
  function fighterOf(accountId) { return H.fighters.a && H.fighters.a.account_id === accountId ? H.fighters.a : (H.fighters.b && H.fighters.b.account_id === accountId ? H.fighters.b : null); }
  function opponentOf(f) { return f === H.fighters.a ? H.fighters.b : H.fighters.a; }
  function fingerprint() { var snap = H.duel ? H.duel.snapshot() : null; var fs = [H.fighters.a, H.fighters.b].map(function (f) { return f ? [f.account_id, f.world.loco.form(), f.world.loco.snapshot().state, +f.world.resource.state().current.toFixed(3), +f.pos.x.toFixed(3), +f.pos.z.toFixed(3), f.exec ? f.exec.state().state : null, f.world.profile.xp] : null; }); return payloadHash({ v: H.version, t: +H.t.toFixed(4), duel: snap ? [snap.state, snap.health, snap.winner] : null, f: fs, term: H.terminal ? H.terminal.winner : null, play: play ? play.fingerprint() : null }); }
  /* ---- the ONE durable write path: nothing is authoritative until store.commit() returned ok ---- */
  function commit(kind, body, meta) {
    if (H.reconstructing) return { ok: true, replayed: true };
    var txn = { records: [Object.assign({ kind: kind, tick: H.tick, t: +H.t.toFixed(4), g: H.generation }, body || {})], receipts: receipts.drainPending() }; if (meta) txn.meta = meta;
    var r = store.commit(txn); if (!r.ok) { H.lifecycle = 'FAULTED'; H.fault = { reason: r.reason, detail: r.detail || null, kind: kind, tick: H.tick, version: H.version }; rec('STORAGE_FAILURE', H.fault); return r; }
    H.committedVersion = H.version; return r;
  }
  function applyDamage(attacker, target, amount, meta) {
    if (!H.duel || H.duel.state() !== 'ACTIVE' || H.terminal || H.paused) { H.lateCallbacks++; rec('LATE_CALLBACK_IGNORED', { attacker: attacker, target: target, amount: amount, duel: duelState() }); return { applied: 0, reason: 'DUEL_NOT_ACTIVE' }; }
    var tf = fighterOf(target); var a = amount; if (tf && tf.bot) a = tf.bot.incoming(amount, meta);
    if (play) { var gm = play.damageModifier(target, attacker, meta); if (gm.multiplier !== 1) { rec('GUARD_MODIFIER', { attacker: attacker, target: target, amount: a, multiplier: gm.multiplier, why: gm.why }); a = a * gm.multiplier; } }
    var r = H.duel.applyDamage(target, a, meta); bump(); return r;
  }
  function releaseFighter(f) { if (!f) return; if (f.exec) { f.exec.interrupt('duel over'); f.exec = null; } f.world.flight.setContext({ combat: false }); f.world.loco.move('STOP'); f.moveVec = { forward: 0, strafe: 0, run: false }; }
  function closeDuel(why) { if (!H.duel) return; if (H.duel.inCombat()) H.duel.cancel(why); if (/RESULT|POST_FIGHT/.test(H.duel.state())) H.duel.close(); releaseFighter(H.fighters.a); releaseFighter(H.fighters.b); Object.keys(H.sessions).forEach(function (k) { var s = H.sessions[k]; if (s.role === 'FIGHTER' && s.state === 'IN_DUEL') s.state = 'READY'; if (s.role === 'SPECTATOR') { s.role = 'LOBBY'; s.locks = null; s.released = true; } }); H.fighters = { a: null, b: null }; H.bot = null; H.paused = false; H.pauseReason = null; H.lastDuel = { id: matchId(), state: H.duel.state(), why: why }; H.duel = null; H.spectators = null; rec('DUEL_CLOSED', { why: why }); bump(); }
  /* terminal result → ONE development receipt per fighter through the ledger; during reconstruction APPLIED receipts only RESTORE progression */
  function settle() {
    if (!H.duel || H.terminal) return; var st = H.duel.state(); if (st !== 'RESULT' && st !== 'POST_FIGHT') return;
    var snap = H.duel.snapshot(); H.terminal = { duel_id: matchId(), winner: snap.winner, loser: snap.loser, result: snap.result, at_tick: H.tick, version: H.version };
    [H.fighters.a, H.fighters.b].forEach(function (f) { if (!f || f.bot) return; var won = snap.winner === f.account_id; var receipt = receipts.issue({ event: 'DUEL_RESULT', session_id: matchId(), recipient: f.account_id, outcome: won ? 'WIN' : 'LOSS', issued_at: H.t }); var r = receipts.apply(receipt, function () { return f.world.progression.duelReward(f.world.profile, won); }, { restore: H.reconstructing }); H.rewards[receipt.receipt_id] = { receipt: receipt, applied: r.applied, restored: !!r.restored, reason: r.reason || null }; rec(r.restored ? 'REWARD_RESTORED' : 'REWARD_RECEIPT', { receipt_id: receipt.receipt_id, recipient: f.account_id, applied: r.applied, restored: !!r.restored }); });
    [H.fighters.a, H.fighters.b].forEach(function (f) { if (f && f.exec) { f.exec.interrupt('duel over'); } }); bump();
  }
  function ack(session, env, accepted, body) {
    var a = Object.assign({ command_id: env.command_id, seq: env.seq, accepted: !!accepted, version: H.version, tick: H.tick, duplicate: false }, body || {});
    session.acks[env.command_id] = { hash: payloadHash(env.payload), ack: a }; session.last_ack = { command_id: env.command_id, seq: env.seq, accepted: !!accepted }; if (accepted) session.last_seq = env.seq; else if (env.seq > session.last_seq) session.last_seq = env.seq;
    var c = commit('CMD', { env: envCore(env), ack: a }); if (!c.ok) { delete session.acks[env.command_id]; return { accepted: false, reason: 'STORAGE_FAILURE', detail: c.reason, host: 'FAULTED', command_id: env.command_id, version: H.version }; }
    rec(accepted ? 'CMD_ACCEPTED' : 'CMD_REJECTED', { session: session.session_id, action: env.action, command_id: env.command_id, reason: a.reason || null }); return a;
  }
  function reject(session, env, reason, detail) { return ack(session, env, false, { reason: reason, detail: detail === undefined ? null : detail }); }
  function startDuel() {
    var a = H.fighters.a, b = H.fighters.b; H.noContest = null; H.duel = createDuelSession(cfg, bus, { fighter_a: a.account_id, fighter_b: b.account_id }); H.spectators = createSpectatorSystem(cfg, bus, { duel: H.duel, policies: a.world.policies }); H.terminal = null; H.duelSeq++;
    H.duel.challenge(); H.duel.accept(); var r = H.duel.lock(); if (!r.ok) return r; [a, b].forEach(function (f) { f.world.flight.setContext({ combat: true }); f.pos = { x: 0, z: f === a ? 3 : -3 }; }); if (play) play.onDuelStart(a, b); Object.keys(H.sessions).forEach(function (k) { var s = H.sessions[k]; if (s.role === 'FIGHTER' && s.state === 'READY') s.state = 'IN_DUEL'; }); rec('DUEL_STARTED', { duel: matchId(), a: a.account_id, b: b.account_id }); bump(); return { ok: true, duel: matchId() };
  }
  function integrate(f, dt) { if (!f || !f.moveVec || H.paused) return; var v = f.moveVec; var moving = v.forward !== 0 || v.strafe !== 0; if (!moving) return; var form = f.world.loco.form(); var PM = (LA.play && LA.play.movement) || {}; var band = cfg.speedRangeMps((form === 'FUSED' && PM.harmonize_fused_ground_to_split) ? 'SPLIT' : form, v.forward < 0 ? 'BACKWARD' : 'FORWARD');   /* PASS 4b (walk identity): the arena travels at the same harmonized band as the field */ var sp = (v.run || v.fast) ? band.max : band.min; var len = Math.sqrt(v.forward * v.forward + v.strafe * v.strafe) || 1; f.pos.x += (v.strafe / len) * sp * dt; f.pos.z -= (v.forward / len) * sp * dt; if (H.duel && H.duel.inCombat()) { var ok = H.duel.validatePosition(f.account_id, { x: f.pos.x, y: 0, z: f.pos.z }); if (ok.out_of_bounds) { var r = Math.sqrt(f.pos.x * f.pos.x + f.pos.z * f.pos.z); var lim = H.duel.boundaryM() / r; f.pos.x *= lim; f.pos.z *= lim; rec('BOUNDARY_CLAMP', { account: f.account_id }); } } }
  function commonSnapshot() { var snap = H.duel ? H.duel.snapshot() : null; return { protocol: PROTOCOL_VERSION, lifecycle: H.lifecycle, generation: H.generation, version: H.version, committed_version: H.committedVersion, t: +H.t.toFixed(3), tick: H.tick, paused: H.paused, pause_reason: H.pauseReason, match_id: snap ? matchId() : (H.lastDuel ? H.lastDuel.id : null), duel: snap ? { id: matchId(), state: snap.state, fighters: snap.fighters, health: snap.health, winner: snap.winner, loser: snap.loser, result: snap.result } : null, forms: { a: H.fighters.a ? H.fighters.a.world.loco.form() : null, b: H.fighters.b ? H.fighters.b.world.loco.form() : null }, positions: { a: H.fighters.a ? Object.assign({}, H.fighters.a.pos) : null, b: H.fighters.b ? Object.assign({}, H.fighters.b.pos) : null }, spectators: H.spectators ? H.spectators.count() : 0, spectator_max: cfg.spectatorMax(), queue: H.spectators ? H.spectators.queue.entries() : [], terminal: H.terminal ? { winner: H.terminal.winner, loser: H.terminal.loser, result: H.terminal.result } : null, last_duel: H.lastDuel || null, no_contest: H.noContest, recovery: H.recovery ? { generation: H.recovery.generation, committed_version: H.recovery.committed_version, records: H.recovery.records, unresolved: H.recovery.unresolved, previous_clean_shutdown: H.recovery.previous_clean_shutdown, terminal: H.recovery.terminal } : null, fault: H.fault, store: { kind: store.kind, persistent: !!store.persistent }, classification: 'DEVELOPMENT_LAB' }; }
  function snapshotFor(session) {
    var s = commonSnapshot(); s.session = { session_id: session.session_id, state: session.state, role: session.role, account_id: session.account_id, last_ack: session.last_ack, awaiting_reconnection: !!session.awaiting_reconnection, reconnect_deadline_t: session.reconnect_deadline === undefined ? null : session.reconnect_deadline, reconnect_remaining_s: (session.reconnect_deadline === null || session.reconnect_deadline === undefined) ? null : +(session.reconnect_deadline - dnow()).toFixed(2), deadline_clock: clock.kind };
    if (session.role === 'FIGHTER') { var f = fighterOf(session.account_id); if (f) { var w = f.world; var r = w.resource.state(); var ls = w.loco.snapshot(); s.me = { account_id: f.account_id, mahgic: +r.current.toFixed(2), mahgic_max: r.max, pattern: w.kit.selected(), patterns: w.kit.patterns(), mahloco: ls.state, form: w.loco.form(), transforming: !!ls.transforming, attack: f.exec ? { attack_id: f.exec.attack.attack_id, state: f.exec.state().state, dealt: f.exec.state().dealt } : null, xp: w.profile.xp, level: w.profile.level, position: Object.assign({}, f.pos) }; var o = opponentOf(f); s.opponent = o ? { account_id: o.account_id, form: o.world.loco.form(), mahloco: o.world.loco.snapshot().state, position: Object.assign({}, o.pos), attack: o.exec ? { attack_id: o.exec.attack.attack_id, state: o.exec.state().state } : null, bot: !!o.bot } : null; } }
    if (session.role === 'SPECTATOR') { s.spectator = { movement_authority: 'NONE_WHILE_SPECTATING', camera: { mode: 'FOLLOW_BOTH', classification: 'METADATA_ONLY' }, next_offer: H.spectators && H.spectators.nextChallenger ? H.spectators.nextChallenger() : null }; }
    if (play) { var ps = play.snapshotFor(session.account_id); if (ps) s.play = ps; }
    return s;
  }
  function heldReply(extra) { return Object.assign({ accepted: false, reason: H.lifecycle === 'FAULTED' ? 'HOST_FAULTED' : HOLD, lifecycle: H.lifecycle, detail: H.lifecycle === 'FAULTED' ? H.fault : 'recovered match held until an explicit developer resume / close', version: H.version }, extra || {}); }
  var api = {
    bus: bus, receipts: receipts, cfg: cfg, targeting: targeting, protocol: PROTOCOL_VERSION, store: store, clock: clock,
    lifecycle: function () { return H.lifecycle; }, generation: function () { return H.generation; }, recovery: function () { return H.recovery; }, fault: function () { return H.fault; },
    /* ---- developer fixture / lifecycle operations (never envelopes; NOT player actions) ---- */
    dev: {
      createAccount: function (accountId, o) { if (H.accounts[accountId]) throw new Error('account exists ' + accountId); var classId = (o && o.classId) || 'ATHLETE', sex = (o && o.sex) || 'F'; var w = compose(data, { classId: classId, sex: sex }); var acc = { account_id: accountId, world: w, classId: classId, sex: sex, token: 'dev-token-' + accountId + '-' + (++H.sessionSeq), unhook: w.bus.on(function (e) { if (/^(ATTACK_|TRANSFORM_TO_|MAHLOCO_STATE_ENTER|RESOURCE_SPENT|XP_REWARD|PATTERN_SELECTED|FLIGHT_STATE)/.test(e.name)) rec('ACTOR_EVENT', { account: accountId, name: e.name, state: e.payload && (e.payload.state || e.payload.to) || null, damage: e.payload && e.payload.damage !== undefined ? e.payload.damage : undefined }); }) }; H.accounts[accountId] = acc; H.tokens[accountId] = acc.token; var c = commit('ACCOUNT', { account_id: accountId, classId: classId, sex: sex }); if (!c.ok) throw new Error('STORAGE_FAILURE: ' + c.reason); return { account_id: accountId, token: acc.token, character_id: w.profile.character_id }; },
      addBotFighter: function (seed, opts) { if (H.fighters.a && H.fighters.b) return { ok: false, reason: 'DUEL_FULL' }; var id = 'SPARRING_BOT'; if (!H.accounts[id]) api.dev.createAccount(id, {}); var f = { account_id: id, world: H.accounts[id].world, exec: null, moveVec: { forward: 0, strafe: 0, run: false }, pos: { x: 0, z: 0 }, bot: null }; if (!H.fighters.a) H.fighters.a = f; else H.fighters.b = f; if (H.fighters.a && H.fighters.b) { var r = startDuel(); if (!r.ok) return r; } var sd = seed === undefined ? 7 : seed; f.bot = createDuelBot(f.world, { seed: sd, id: id, position: { x: f.pos.x, y: 0, z: f.pos.z }, createAttackExecution: createAttackExecution, resource: f.world.resource, applyDamage: function (target, amount, meta) { return applyDamage(id, target, amount, meta); } }); rec('BOT_FIGHTER', { slot: H.fighters.a === f ? 'a' : 'b', seed: sd }); bump(); var c = (opts && opts.skipJournal) ? { ok: true, skipped: true } : commit('BOT', { seed: sd }); if (!c.ok) return { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; return { ok: true, slot: H.fighters.a === f ? 'a' : 'b' }; },
      tokens: function () { return Object.assign({}, H.tokens); },
      reset: function () { closeDuel('dev reset'); Object.keys(H.accounts).forEach(function (k) { H.accounts[k].unhook(); }); H.accounts = {}; H.tokens = {}; H.sessions = {}; H.duel = null; H.spectators = null; H.terminal = null; H.rewards = {}; H.log = []; H.t = 0; H.tick = 0; H.lastDuel = null; if (play) play.reset(); bump(); var c = commit('RESET', {}); return c.ok ? { ok: true } : { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; },
      /* explicit developer lifecycle actions after recovery */
      resume: function () { if (H.lifecycle !== HOLD) return { ok: false, reason: 'NOT_HELD', lifecycle: H.lifecycle }; H.lifecycle = 'LIVE'; var dl = {}; Object.keys(H.sessions).forEach(function (k) { var s = H.sessions[k]; if (s.state === 'RECONNECTING' && (s.reconnect_deadline === null || s.reconnect_deadline === undefined)) { s.reconnect_deadline = (H.replayDeadlines && H.replayDeadlines[k] !== undefined) ? H.replayDeadlines[k] : dnow() + LA.reconnect_window_s; dl[k] = s.reconnect_deadline; } }); var anyFighterReconnecting = Object.keys(H.sessions).some(function (k) { var x = H.sessions[k]; return x.role === 'FIGHTER' && x.state === 'RECONNECTING'; }); if (H.duel && H.duel.inCombat()) { H.paused = anyFighterReconnecting; H.pauseReason = anyFighterReconnecting ? 'PAUSE_AND_WAIT_DEV: fighter reconnecting after recovery (OD-29)' : null; } bump(); var c = commit('RESUME', { from_version: H.committedVersion, deadlines: dl }); if (!c.ok) return { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; rec('DEV_RESUME', {}); return { ok: true, lifecycle: H.lifecycle, paused: H.paused, generation: H.generation }; },
      closeRecovered: function () { if (H.lifecycle !== HOLD) return { ok: false, reason: 'NOT_HELD', lifecycle: H.lifecycle }; var had = duelState(); var dl2 = {}; closeDuel('developer close after recovery — no result, no rewards (' + HOLD + ')'); Object.keys(H.sessions).forEach(function (k) { var s = H.sessions[k]; if (s.state === 'RECONNECTING' && (s.reconnect_deadline === null || s.reconnect_deadline === undefined)) { s.reconnect_deadline = (H.replayDeadlines && H.replayDeadlines[k] !== undefined) ? H.replayDeadlines[k] : dnow() + LA.reconnect_window_s; dl2[k] = s.reconnect_deadline; } }); H.lifecycle = 'LIVE'; bump(); var c = commit('DEV_CLOSE', { duel_state_was: had, deadlines: dl2 }); if (!c.ok) return { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; rec('DEV_CLOSE', { was: had }); return { ok: true, lifecycle: H.lifecycle, closed_duel_state: had, rewards_issued: false }; },
      failNextCommit: function () { if (store.testHooks) store.testHooks.failNextCommit = true; return { ok: !!store.testHooks }; },
      log: function () { return H.log.slice(); }, rewards: function () { return JSON.parse(JSON.stringify(H.rewards)); }, state: function () { return { t: H.t, tick: H.tick, version: H.version, committed_version: H.committedVersion, lifecycle: H.lifecycle, generation: H.generation, paused: H.paused, duel: duelState(), sessions: Object.keys(H.sessions).map(function (k) { var s = H.sessions[k]; return { session_id: k, client_id: s.client_id, account_id: s.account_id, role: s.role, state: s.state }; }), late_callbacks: H.lateCallbacks, listeners: Object.keys(H.accounts).length, fault: H.fault }; },
      forceDisconnect: function (sessionId) { return api.disconnect(sessionId); },
      play_internals: function () { return play; },   /* development introspection only (tests): never used by clients */
      play: function (op, args) { if (!play) return { ok: false, reason: 'PLAY_DISABLED' }; var r = play.devOp(op, args); if (!r.ok) return r; var c = commit('PLAY_DEV', r.record); if (!c.ok) return { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; delete r.record; return r; }
    },
    /* ---- connection lifecycle (transport-neutral) ---- */
    connect: function (req) {
      if (H.lifecycle === 'FAULTED') return heldReply({ ok: false }); if (!req || typeof req.client_id !== 'string' || typeof req.account_id !== 'string' || typeof req.token !== 'string') return { ok: false, reason: 'BAD_CONNECT_REQUEST' };
      if (H.tokens[req.account_id] !== req.token) return { ok: false, reason: 'BAD_DEV_BINDING' };
      var existing = Object.keys(H.sessions).map(function (k) { return H.sessions[k]; }).filter(function (s) { return s.account_id === req.account_id && s.state !== 'CLOSED'; })[0]; if (existing) return { ok: false, reason: 'ACCOUNT_ALREADY_CONNECTED', session_id: existing.session_id, hint: 'use reconnect' };
      var s = { session_id: 'S' + (++H.sessionSeq), client_id: req.client_id, account_id: req.account_id, role: 'LOBBY', state: 'READY', last_seq: -1, acks: {}, last_ack: null, created_t: H.t, last_seen_t: H.t, locks: null }; H.sessions[s.session_id] = s; bump(); var c = commit('SESSION_CONNECT', { session_id: s.session_id, client_id: s.client_id, account_id: s.account_id }); if (!c.ok) { delete H.sessions[s.session_id]; return { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; } rec('CONNECT', { session: s.session_id, account: s.account_id }); return { ok: true, session_id: s.session_id, client_id: s.client_id, state: s.state, version: H.version, snapshot: snapshotFor(s) };
    },
    disconnect: function (sessionId, replayDeadline) { if (H.lifecycle === 'FAULTED') return heldReply({ ok: false }); var s = H.sessions[sessionId]; if (!s || s.state === 'CLOSED') return { ok: false, reason: 'NO_SESSION' }; if (s.state === 'RECONNECTING') return { ok: true, already: true, state: s.state, reconnect_deadline_t: s.reconnect_deadline }; s.state = 'RECONNECTING'; s.reconnect_deadline = H.lifecycle === HOLD ? null : (replayDeadline !== undefined ? replayDeadline : dnow() + LA.reconnect_window_s); if (s.role === 'FIGHTER' && H.duel && H.duel.inCombat()) { H.paused = true; H.pauseReason = 'PAUSE_AND_WAIT_DEV: fighter ' + s.account_id + ' reconnecting (OD-29)'; } bump(); var c = commit('SESSION_DISCONNECT', { session_id: sessionId, deadline: s.reconnect_deadline }); if (!c.ok) return { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; if (play) play.onSessionDisconnect(s.account_id, s.reconnect_deadline); rec('DISCONNECT', { session: sessionId, role: s.role, strategy: LA.disconnect_strategy, deadline_t: s.reconnect_deadline }); return { ok: true, state: s.state, strategy: LA.disconnect_strategy, reconnect_deadline_t: s.reconnect_deadline, reconnect_window_s: LA.reconnect_window_s, deadline_clock: clock.kind }; },
    reconnect: function (req) {
      if (H.lifecycle === 'FAULTED') return heldReply({ ok: false }); if (!req || !req.session_id) return { ok: false, reason: 'BAD_RECONNECT_REQUEST' }; var s = H.sessions[req.session_id]; if (!s) return { ok: false, reason: 'NO_SESSION' }; if (s.client_id !== req.client_id || H.tokens[s.account_id] !== req.token) return { ok: false, reason: 'BAD_DEV_BINDING' };
      if (s.state === 'CLOSED') return { ok: false, reason: 'SESSION_EXPIRED', hint: 'connect again' };
      if (s.state === 'RECONNECTING' && s.reconnect_deadline !== null && s.reconnect_deadline !== undefined && dnow() >= s.reconnect_deadline) { var dnx = dnow(); expireSession(s, s.session_id, dnx); var cx = commit('SESSION_EXPIRED', { session_id: s.session_id, clock_now: +dnx.toFixed(4) }); if (!cx.ok) return { ok: false, reason: 'STORAGE_FAILURE', detail: cx.reason }; return { ok: false, reason: 'SESSION_EXPIRED', expired_on_reconnect: true, deadline: s.reconnect_deadline, clock_now: +dnx.toFixed(4), hint: 'the window had already passed when this reconnect was processed' }; }
      var was = s.state; if (s.state === 'RECONNECTING') { s.state = (s.role === 'FIGHTER' && H.duel && !H.terminal) ? 'IN_DUEL' : 'READY'; delete s.reconnect_deadline; s.awaiting_reconnection = false; }
      var anyReconnecting = Object.keys(H.sessions).some(function (k) { var x = H.sessions[k]; return x.role === 'FIGHTER' && x.state === 'RECONNECTING'; }); if (!anyReconnecting && H.paused && H.lifecycle !== HOLD) { H.paused = false; H.pauseReason = null; }   /* also during RECONSTRUCTING: the replay must mirror the live unpause; only the recovery hold keeps the pause */
      if (play && was === 'RECONNECTING') play.onSessionReconnect(s.account_id);
      s.last_seen_t = H.t; bump(); var c = commit('SESSION_RECONNECT', { session_id: s.session_id, client_id: s.client_id }); if (!c.ok) return { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason }; rec('RECONNECT', { session: s.session_id, from: was, to: s.state, duplicate: was !== 'RECONNECTING' });
      return { ok: true, session_id: s.session_id, state: s.state, duplicate: was !== 'RECONNECTING', lifecycle: H.lifecycle, generation: H.generation, version: H.version, committed_version: H.committedVersion, match_id: matchId() || (H.lastDuel ? H.lastDuel.id : null), last_ack: s.last_ack, last_seq: s.last_seq, snapshot: snapshotFor(s) };
    },
    snapshot: function (sessionId) { var s = H.sessions[sessionId]; if (!s) return { ok: false, reason: 'NO_SESSION' }; return Object.assign({ ok: true }, snapshotFor(s)); },
    /* ---- the only way a player changes anything ---- */
    submit: function (env) {
      var v = validateEnvelope(env, LA); if (!v.ok) { rec('CMD_INVALID', { reason: v.reason, detail: v.detail || null }); return { accepted: false, reason: v.reason, detail: v.detail === undefined ? null : v.detail, version: H.version }; }
      var s = H.sessions[env.session_id]; if (!s) return { accepted: false, reason: 'STALE_SESSION', version: H.version }; if (s.client_id !== env.client_id) return { accepted: false, reason: 'SESSION_CLIENT_MISMATCH', version: H.version };
      if (s.state === 'CLOSED' || (H.t - s.last_seen_t) > LA.session_ttl_s) { s.state = 'CLOSED'; return { accepted: false, reason: 'STALE_SESSION', version: H.version }; }
      var prev = s.acks[env.command_id]; if (prev) { if (prev.hash === payloadHash(env.payload)) { rec('CMD_DUPLICATE', { session: s.session_id, command_id: env.command_id }); return Object.assign({}, prev.ack, { duplicate: true }); } rec('CMD_CONFLICT', { session: s.session_id, command_id: env.command_id }); return { accepted: false, reason: 'COMMAND_ID_CONFLICT', command_id: env.command_id, version: H.version }; }
      if (env.seq <= s.last_seq) { rec('CMD_OUT_OF_ORDER', { session: s.session_id, seq: env.seq, last: s.last_seq }); return { accepted: false, reason: 'OUT_OF_ORDER', seq: env.seq, last_seq: s.last_seq, version: H.version }; }
      if (H.lifecycle === 'FAULTED' || H.lifecycle === HOLD) return heldReply({ command_id: env.command_id, seq: env.seq });   /* not journaled, not cached: nothing is accepted while held / faulted (reconnect + snapshot carry the resync) */
      if (s.state === 'RECONNECTING') return reject(s, env, 'SESSION_RECONNECTING');
      s.last_seen_t = H.t; H.arrival++; var p = v.payload; var f = fighterOf(s.account_id);
      var pa = play ? play.actorOf(s.account_id) : null; if (play && (PLAY_ONLY_ACTIONS.indexOf(env.action) >= 0 || (!f && pa && pa.room && PLAY_SHARED_ACTIONS.indexOf(env.action) >= 0))) return play.handle(s, env, p, f, ack, reject);
      switch (env.action) {
        case 'PING': return ack(s, env, true, { pong: true, lifecycle: H.lifecycle });
        case 'JOIN_DUEL': if (s.role === 'FIGHTER') return reject(s, env, 'ALREADY_FIGHTER'); if (s.role === 'SPECTATOR') return reject(s, env, 'SPECTATOR_ROLE', 'leave spectating first'); if (H.fighters.a && H.fighters.b) return reject(s, env, 'DUEL_FULL', 'two fighters only — SPECTATE instead'); var fr = { account_id: s.account_id, world: H.accounts[s.account_id].world, exec: null, moveVec: { forward: 0, strafe: 0, run: false }, pos: { x: 0, z: 0 }, bot: null }; if (!H.fighters.a) H.fighters.a = fr; else H.fighters.b = fr; s.role = 'FIGHTER'; var started = null; if (H.fighters.a && H.fighters.b) { started = startDuel(); if (!started.ok) return reject(s, env, 'DUEL_START_FAILED', started.reason); } bump(); return ack(s, env, true, { role: 'FIGHTER', slot: H.fighters.a === fr ? 'a' : 'b', duel: started ? started.duel : null, waiting_for_opponent: !started });
        case 'SPECTATE': if (s.role === 'FIGHTER') return reject(s, env, 'FIGHTER_CANNOT_SPECTATE'); if (!H.spectators) return reject(s, env, 'NO_DUEL_TO_SPECTATE'); var js = H.spectators.join(s.account_id); if (!js.ok) return reject(s, env, js.reason === 'SPECTATOR_CAP' ? 'SPECTATOR_CAPACITY' : js.reason, js.max); s.role = 'SPECTATOR'; s.locks = { movement_authority: 'NONE_WHILE_SPECTATING', camera: 'FOLLOW_BOTH' }; bump(); return ack(s, env, true, { role: 'SPECTATOR', locks: s.locks });
        case 'MOVE': if (!f) return reject(s, env, 'ROLE_NOT_FIGHTER'); if (H.paused) return reject(s, env, 'DUEL_PAUSED', H.pauseReason); f.moveVec = { forward: p.forward || 0, strafe: p.strafe || 0, run: !!p.run, fast: !!p.fast }; if (play) play.onFighterMove(s.account_id, p); var mv = f.world.loco.move((f.moveVec.forward || f.moveVec.strafe) ? ((f.moveVec.run || (f.moveVec.fast && f.world.loco.form() === 'SPLIT')) ? 'RUN' : 'MOVE') : 'STOP');   /* PASS 3 review: `+` (fast) reaches the arena too — band top speed; the RUN gait only where it is free (SPLIT), never an implicit transformation */ bump(); return ack(s, env, true, { mahloco: mv });
        case 'TRANSFORM': if (!f) return reject(s, env, 'ROLE_NOT_FIGHTER'); if (H.paused) return reject(s, env, 'DUEL_PAUSED', H.pauseReason); var want = p.to || (f.world.loco.form() === 'FUSED' ? 'SPLIT' : 'FUSED'); if (f.world.loco.transforming()) return reject(s, env, 'TRANSFORM_IN_PROGRESS', f.world.loco.snapshot().state); if (f.world.loco.form() === want) return ack(s, env, true, { transform: { accepted: true, already: want } }); var tr = want === 'SPLIT' ? f.world.loco.transformToSplit() : f.world.loco.transformToFused(); bump(); return tr.accepted ? ack(s, env, true, { transform: tr, to: want }) : reject(s, env, 'TRANSFORM_REFUSED', tr.reason);
        case 'SELECT_PATTERN': if (!f) return reject(s, env, 'ROLE_NOT_FIGHTER'); if (play && !play.patternEquipped(s.account_id, p.pattern_id)) return reject(s, env, 'PATTERN_NOT_EQUIPPED', p.pattern_id); var sp = f.world.kit.selectPattern(p.pattern_id); bump(); return sp.ok ? ack(s, env, true, { pattern: p.pattern_id }) : reject(s, env, sp.reason);
        case 'ATTACK': if (!f) return reject(s, env, 'ROLE_NOT_FIGHTER'); if (!H.duel || H.duel.state() !== 'ACTIVE') return reject(s, env, 'DUEL_NOT_ACTIVE', duelState()); if (H.paused) return reject(s, env, 'DUEL_PAUSED', H.pauseReason); var target = targeting.resolve(s.account_id, H.duel); if (!target) return reject(s, env, 'NO_TARGET'); var rr = f.world.kit.resolve(p.hint, f.world.loco.form(), { combat: true }); if (!rr.ok) return reject(s, env, rr.reason === 'COOLDOWN' ? 'COOLDOWN' : (/FORM|SPLIT|FUSED/.test(rr.reason) ? 'WRONG_FORM' : rr.reason), rr.attack_id || rr.pattern_id || null); if (play) { var aimr = play.duelAim(s.account_id, opponentOf(f), rr.attack); if (aimr && !aimr.ok) return reject(s, env, aimr.reason, aimr); } if (f.exec && !/COMPLETE|REFUSED|INTERRUPTED/.test(f.exec.state().state)) return reject(s, env, 'ATTACK_IN_PROGRESS', f.exec.attack.attack_id); var ex = createAttackExecution(cfg, f.world.bus, { attack: rr.attack, attacker: s.account_id, target: target, resource: f.world.resource, applyDamage: function (t2, amount, meta) { return applyDamage(s.account_id, t2, amount, meta); } }); var st = ex.start(); if (!st.ok) return reject(s, env, st.reason === 'INSUFFICIENT' || /INSUFF|NO_RESOURCE|LOCKOUT/.test(st.reason) ? 'INSUFFICIENT_MAHGIC' : st.reason, rr.attack.attack_id); f.exec = ex; f.world.kit.startCooldown(rr.attack); bump(); return ack(s, env, true, { attack_id: rr.attack.attack_id, target: target, tier: rr.attack.attack_tier });
        case 'CONCEDE': if (!f) return reject(s, env, 'ROLE_NOT_FIGHTER'); if (!H.duel || H.duel.state() !== 'ACTIVE') return reject(s, env, 'DUEL_NOT_ACTIVE', duelState()); var cr = H.duel.concede(s.account_id); bump(); return cr.ok ? ack(s, env, true, { conceded: true }) : reject(s, env, 'CONCEDE_REFUSED');
        case 'LEAVE': if (s.role === 'SPECTATOR') { H.spectators.leave(s.account_id); s.role = 'LOBBY'; s.locks = null; s.state = 'CLOSED'; bump(); return ack(s, env, true, { left: 'SPECTATOR', controls: 'RELEASED', movement_authority: 'RESTORED' }); } if (f) { var policy = LA.voluntary_exit_in_duel; var conceded = false; if (H.duel && H.duel.state() === 'ACTIVE') { if (policy !== 'CONCEDE_DEV') return reject(s, env, 'UNKNOWN_EXIT_POLICY', policy); H.duel.concede(s.account_id); conceded = true; } else if (H.duel && /RESULT|POST_FIGHT/.test(H.duel.state())) { closeDuel('fighter left after result'); } s.state = 'CLOSED'; bump(); return ack(s, env, true, { left: 'FIGHTER', conceded: conceded, policy: policy, controls: 'RELEASED' }); } s.state = 'CLOSED'; bump(); return ack(s, env, true, { left: 'LOBBY', controls: 'RELEASED', movement_authority: 'RESTORED' });
        case 'PRACTICE_DUEL': if (!play || !pa || pa.room !== 'PLAZA') return reject(s, env, 'PLAZA_REQUIRED'); if (s.role !== 'LOBBY') return reject(s, env, 'ALREADY_IN_ROLE', s.role); if (H.fighters.a || H.fighters.b || H.duel) return reject(s, env, 'DUEL_SLOT_BUSY'); var pf = { account_id: s.account_id, world: H.accounts[s.account_id].world, exec: null, moveVec: { forward: 0, strafe: 0, run: false }, pos: { x: pa.pos.x, z: pa.pos.z }, bot: null }; H.fighters.a = pf; s.role = 'FIGHTER'; var pb = api.dev.addBotFighter(p.seed === undefined ? 7 : p.seed, { skipJournal: true }); if (!pb.ok) { H.fighters = { a: null, b: null }; s.role = 'LOBBY'; return reject(s, env, 'PRACTICE_START_FAILED', pb.reason); } bump(); return ack(s, env, true, { role: 'FIGHTER', slot: 'a', practice: true, duel: matchId(), opponent: 'SPARRING_BOT', flight: 'DISABLED_IN_PVP' });
        case 'LEAVE_ARENA': if (s.role !== 'FIGHTER') return reject(s, env, 'ROLE_NOT_FIGHTER'); if (H.duel && H.duel.inCombat()) return reject(s, env, 'DUEL_ACTIVE', 'CONCEDE first'); if (H.duel) closeDuel('fighter ' + s.account_id + ' left the arena after the result'); s.role = 'LOBBY'; s.state = 'READY'; bump(); return ack(s, env, true, { left: 'ARENA', role: 'LOBBY', controls: 'RESTORED' });
        case 'CALL_NEXT': if (s.role !== 'SPECTATOR') return reject(s, env, 'SPECTATOR_ROLE_REQUIRED'); var cn = H.spectators.callNext(s.account_id); bump(); return cn.ok ? ack(s, env, true, { position: cn.position }) : reject(s, env, cn.reason, cn.position);
        case 'ACCEPT_NEXT': case 'DECLINE_NEXT': if (!H.terminal && H.noContest) return reject(s, env, 'NO_CONTEST_NO_WINNER', H.noContest.match_id); if (!f) return reject(s, env, 'ROLE_NOT_FIGHTER'); if (!H.terminal || H.terminal.winner !== s.account_id) return reject(s, env, 'WINNER_ONLY', H.terminal ? H.terminal.winner : null); if (!H.spectators) return reject(s, env, 'DUEL_CLOSED'); var off = H.spectators.offerNext(); if (!off.ok) return reject(s, env, off.reason); var res = env.action === 'ACCEPT_NEXT' ? H.spectators.accept() : H.spectators.decline(p.choice); bump(); return ack(s, env, true, Object.assign({ policy_classification: 'EXPERIMENTAL_POLICY (OD-02) — no winner policy declared' }, res));
      }
      return reject(s, env, 'UNKNOWN_ACTION');
    },
    /* ---- the ONLY scheduler: advances host time, fighter worlds, executions, duel, bot, terminal settlement, reconnect windows.
       No-op unless LIVE (or replaying): a HELD or FAULTED host never advances simulation time. Each tick is committed after it ran. ---- */
    tick: function (dt) {
      if (H.lifecycle !== 'LIVE' && H.lifecycle !== 'RECONSTRUCTING') return { ok: false, lifecycle: H.lifecycle };
      H.t += dt; H.tick++; bus.setTime(H.t); var dn = dnow();
      Object.keys(H.sessions).forEach(function (k) { var s = H.sessions[k]; if (s.state === 'RECONNECTING' && s.reconnect_deadline !== null && s.reconnect_deadline !== undefined && dn >= s.reconnect_deadline) expireSession(s, k, dn); });
      if (!H.paused) {
        [H.fighters.a, H.fighters.b].forEach(function (f) { if (!f) return; f.world.tick(dt, { form: f.world.loco.form(), speed_mps: 0, flying: false }); integrate(f, dt); if (f.exec) f.exec.tick(dt); });
        if (H.duel) { H.duel.tick(dt); [H.fighters.a, H.fighters.b].forEach(function (f) { if (f && f.bot) { var o = opponentOf(f); var snap = H.duel.snapshot(); f.bot.tick(dt, { id: o.account_id, position: { x: o.pos.x, y: 0, z: o.pos.z } }, H.duel.state(), snap.health[f.account_id]); } }); settle(); }
      }
      if (play) play.tick(dt);
      bump(); var body = { dt: dt, dn: +dn.toFixed(4) }; if (H.tick % FP_EVERY === 0) body.fp = fingerprint(); var c = commit('TICK', body); return c.ok ? { ok: true, tick: H.tick } : { ok: false, reason: 'STORAGE_FAILURE', detail: c.reason, lifecycle: H.lifecycle };
    },
    /* ---- recovery: deterministic replay of the committed journal, then HOLD ---- */
    recover: function () {
      if (H.tick !== 0 || Object.keys(H.accounts).length) return { ok: false, reason: 'HOST_NOT_FRESH' };
      var recs; try { recs = store.records(); } catch (e) { H.lifecycle = HOLD; H.recovery = { ok: false, reason: e.reason || 'CORRUPT_RECORD', detail: String(e.message || e), unresolved: true, records: 0, generation: H.generation, committed_version: 0, previous_clean_shutdown: H.opened ? H.opened.previous_clean_shutdown : null }; return H.recovery; }
      receipts.preload(store.receipts()); H.reconstructing = true; H.lifecycle = 'RECONSTRUCTING'; var inconsistencies = [];
      for (var i = 0; i < recs.length; i++) {
        var r = recs[i];
        try {
          switch (r.kind) {
            case 'ACCOUNT': api.dev.createAccount(r.account_id, { classId: r.classId, sex: r.sex }); break;
            case 'BOT': api.dev.addBotFighter(r.seed); break;
            case 'SESSION_CONNECT': api.connect({ client_id: r.client_id, account_id: r.account_id, token: H.tokens[r.account_id] }); break;
            case 'SESSION_DISCONNECT': api.disconnect(r.session_id, r.deadline === undefined ? undefined : r.deadline); break;
            case 'SESSION_EXPIRED': var sx = H.sessions[r.session_id]; if (sx && sx.state === 'RECONNECTING') expireSession(sx, r.session_id, r.clock_now); break;
            case 'SESSION_RECONNECT': var ss = H.sessions[r.session_id]; api.reconnect({ client_id: r.client_id, session_id: r.session_id, token: ss ? H.tokens[ss.account_id] : null }); break;
            case 'CMD': var got = api.submit(r.env); if (ackHash(got) !== ackHash(r.ack)) inconsistencies.push({ seq: r.seq, kind: 'CMD', command_id: r.env.command_id, expected: r.ack, actual: got }); if (H.replayInconsistency) { inconsistencies.push(Object.assign({ seq: r.seq }, H.replayInconsistency)); H.replayInconsistency = null; } break;
            case 'TICK': H.replayNow = r.dn === undefined ? r.t : r.dn; api.tick(r.dt); if (r.fp !== undefined && r.fp !== fingerprint()) inconsistencies.push({ seq: r.seq, kind: 'TICK', tick: H.tick, expected: r.fp, actual: fingerprint() }); break;
            case 'RESET': api.dev.reset(); break;
            case 'RESUME': H.replayDeadlines = r.deadlines || {}; Object.keys(H.replayDeadlines).forEach(function (k) { var sr = H.sessions[k]; if (sr && sr.state === 'RECONNECTING') sr.reconnect_deadline = H.replayDeadlines[k]; }); H.replayDeadlines = null; bump(); break;   /* lifecycle-only record: time did not advance while held; the live resume bumped the version once */
            case 'DEV_CLOSE': closeDuel('developer close (replayed from journal)'); var dlc = r.deadlines || {}; Object.keys(dlc).forEach(function (k) { var sc = H.sessions[k]; if (sc && sc.state === 'RECONNECTING') sc.reconnect_deadline = dlc[k]; }); bump(); break;
            case 'PLAY_DEV': if (!play || !play.replayRecord(r)) inconsistencies.push({ seq: r.seq, kind: 'PLAY_DEV', op: r.op }); break;
            case 'RULESET_FREEZE': H.replayFrozen.push(r); break;
            default: inconsistencies.push({ seq: r.seq, kind: 'UNKNOWN_RECORD', record_kind: r.kind });
          }
        } catch (e) { inconsistencies.push({ seq: r.seq, kind: 'REPLAY_ERROR', error: String(e && e.message || e) }); break; }
      }
      H.reconstructing = false; H.replayNow = null;
      Object.keys(H.sessions).forEach(function (k) { var s = H.sessions[k]; if (s.state !== 'CLOSED') { s.state = 'RECONNECTING'; s.reconnect_deadline = null; s.awaiting_reconnection = true; } });
      if (H.duel && H.duel.inCombat()) { H.paused = true; H.pauseReason = HOLD + ': recovered duel held until developer resume (no time advance, no result)'; }
      H.lifecycle = HOLD; H.committedVersion = H.version; H.log = H.log.filter(function (e) { return e.kind !== 'CMD_ACCEPTED' && e.kind !== 'CMD_REJECTED'; });
      H.recovery = { ok: inconsistencies.length === 0, records: recs.length, inconsistencies: inconsistencies, unresolved: inconsistencies.length > 0, generation: H.generation, committed_version: H.version, tick: H.tick, t: H.t, duel: duelState(), terminal: !!H.terminal, receipts_restored: receipts.stats().restored, previous_clean_shutdown: H.opened ? H.opened.previous_clean_shutdown : null, stale_lock_recovered: H.opened ? !!H.opened.stale_lock_recovered : false, sessions_awaiting: Object.keys(H.sessions).filter(function (k) { return H.sessions[k].state === 'RECONNECTING'; }).length };
      rec('RECOVERED', { records: recs.length, inconsistencies: inconsistencies.length }); return H.recovery;
    },
    shutdownClean: function () { var r = store.closeClean(); H.lifecycle = 'FAULTED'; H.fault = { reason: 'SHUT_DOWN', clean: !!r.ok }; return r; },
    time: function () { return H.t; }, version: function () { return H.version; }, state: function () { return api.dev.state(); }
  };
  return api;
}
