/* JOB B asset viewer: loads runtime GLB derivatives in headless Chrome with the game's vendored three.js + GLTFLoader, the day lighting
   (key 0xfff3dc, hemisphere, ACES 1.35 like play.js) and screenshots each from front / ¾ / side at a fitted distance — the
   "compare silhouette / material at the intended distance" proof. Optionally the raw SOURCE too (--source <glb>, heavy).
   node deploy/jobb/asset_view.mjs <out dir> <glb> [glb …] [--label text] [--dist-mult 1.0] */
import fs from 'node:fs'; import path from 'node:path'; import http from 'node:http'; import { fileURLToPath } from 'node:url';
import { launchChrome, sleep } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.resolve(HERE, '..', '..');
var argv = process.argv.slice(2); var out = path.resolve(argv[0]); fs.mkdirSync(out, { recursive: true }); var files = argv.slice(1).filter(function (a) { return !a.startsWith('--'); }).map(function (f) { return path.resolve(f); });
var distMult = argv.indexOf('--dist-mult') >= 0 ? parseFloat(argv[argv.indexOf('--dist-mult') + 1]) : 1.0;
var srv = http.createServer(function (req, res) { var u = decodeURIComponent(req.url.split('?')[0]); if (u === '/') { res.writeHead(200, { 'Content-Type': 'text/html' }); res.end(PAGE); return; } if (u.startsWith('/vendor/')) { var vp = path.join(LA, u); if (fs.existsSync(vp)) { res.writeHead(200, { 'Content-Type': 'application/javascript' }); fs.createReadStream(vp).pipe(res); return; } } if (u.startsWith('/glb/')) { var fp = files[parseInt(u.slice(5), 10)]; if (fp && fs.existsSync(fp)) { res.writeHead(200, { 'Content-Type': 'model/gltf-binary', 'Content-Length': fs.statSync(fp).size }); fs.createReadStream(fp).pipe(res); return; } } res.writeHead(404); res.end(); });
var PAGE = '<!doctype html><html><body style="margin:0;background:#9fc4e4"><canvas id="c" style="width:100vw;height:100vh"></canvas><script type="importmap">{"imports":{"three":"/vendor/three/three.module.min.js"}}</script><script type="module">import * as THREE from "three"; import { GLTFLoader } from "/vendor/three/GLTFLoader.js"; window.THREE = THREE; const c = document.getElementById("c"); const r = new THREE.WebGLRenderer({ canvas: c, antialias: true }); r.setSize(innerWidth, innerHeight, false); r.setPixelRatio(1); r.toneMapping = THREE.ACESFilmicToneMapping; r.toneMappingExposure = 1.35; r.outputColorSpace = THREE.SRGBColorSpace; const s = new THREE.Scene(); s.background = new THREE.Color(0x9fc4e4); const cam = new THREE.PerspectiveCamera(40, innerWidth / innerHeight, 0.01, 5000); s.add(new THREE.HemisphereLight(0xcfe4ff, 0x5c5f63, 1.15)); const key = new THREE.DirectionalLight(0xfff3dc, 2.35); key.position.set(26, 34, 14); s.add(key); const fill = new THREE.DirectionalLight(0xe8f0ff, 0.34); fill.position.set(-20, 10, 30); s.add(fill); const pm = new THREE.PMREMGenerator(r); const es = new THREE.Scene(); es.background = new THREE.Color(0x8fbde8); s.environment = pm.fromScene(es, 0.04).texture; const ground = new THREE.Mesh(new THREE.CircleGeometry(4, 48), new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.5, metalness: 0.84, envMapIntensity: 0.2 })); ground.rotation.x = -Math.PI / 2; s.add(ground); let root = null; const loader = new GLTFLoader(); window.load = (url) => new Promise((res, rej) => { if (root) { s.remove(root); root = null; } loader.load(url, (g) => { root = g.scene; s.add(root); const box = new THREE.Box3().setFromObject(root); const size = new THREE.Vector3(); box.getSize(size); const ctr = new THREE.Vector3(); box.getCenter(ctr); root.position.sub(ctr); root.position.y += size.y / 2; ground.scale.setScalar(Math.max(size.x, size.z) * 0.9 + 0.01); let tris = 0, calls = 0; root.traverse((m) => { if (m.isMesh) { calls++; tris += m.geometry.index ? m.geometry.index.count / 3 : m.geometry.attributes.position.count / 3; if (m.material) { m.material.envMapIntensity = 0.35; } } }); window.__info = { size: [size.x, size.y, size.z], tris, meshes: calls }; res(window.__info); }, undefined, rej); }); window.view = (yaw, pitch, mult) => { const box = new THREE.Box3().setFromObject(root); const size = new THREE.Vector3(); box.getSize(size); const R = Math.max(size.x, size.y, size.z) * 1.35 * (mult || 1); const ctr = new THREE.Vector3(); box.getCenter(ctr); cam.position.set(ctr.x + Math.sin(yaw) * Math.cos(pitch) * R, ctr.y + Math.sin(pitch) * R, ctr.z + Math.cos(yaw) * Math.cos(pitch) * R); cam.lookAt(ctr); r.render(s, cam); return r.info.render; }; window.ready = true;</script></body></html>';
await new Promise(function (r) { srv.listen(0, '127.0.0.1', r); }); var port = srv.address().port; var pg = await launchChrome({ width: 900, height: 700, gpu: true }); var report = [];
try {
  await pg.goto('http://127.0.0.1:' + port + '/'); for (var w = 0; w < 100; w++) { if (await pg.evaluate('!!window.ready')) break; await sleep(100); }
  for (var i = 0; i < files.length; i++) { var t0 = Date.now(); var info = await pg.evaluate('window.load("/glb/' + i + '").then(function(i){ return i; })'); var loadMs = Date.now() - t0; var base = path.basename(files[i]).replace(/\.glb$/, ''); var shots = {};
    for (var v of [['front', 0, 0.12], ['q34', 0.8, 0.28], ['side', Math.PI / 2, 0.08]]) { var ri = await pg.evaluate('window.view(' + v[1] + ',' + v[2] + ',' + distMult + ')'); await sleep(120); var f = path.join(out, base + '_' + v[0] + '.png'); await pg.screenshot(f); shots[v[0]] = path.basename(f); }
    var rec = { file: files[i], bytes: fs.statSync(files[i]).size, load_ms: loadMs, size_m: info.size.map(function (x) { return +x.toFixed(3); }), triangles: info.tris, meshes: info.meshes, shots: shots }; report.push(rec); console.log(base, 'tris', info.tris, 'size', rec.size_m.join('×'), 'load', loadMs + ' ms', Object.values(shots).join(' ')); }
} catch (e) { console.error(e); } finally { await pg.close(); srv.close(); }
fs.writeFileSync(path.join(out, 'asset_view.json'), JSON.stringify(report, null, 1));
