/* Owner next-pass 2026-09-20 §26 / §31 — the PLAYABLE LOOP in the real runtime (static demo, headless Chrome, GPU): walk into the west
   forest → a WILD Dogkie chases and bites (HUD health drops, the creature's attack aura) → lock + attack slot 1 until it drops (KO →
   dissolution) → stand in the pack until DEFEATED (the HUD state treatment) → RESPAWN at the safe point with HP restored → the phoenix /
   fish / horse states from p.wildlife. Screenshots + the host's own numbers. node deploy/jobb/combat_proof.mjs [out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var OUT = path.resolve(argv[0] || path.join(HERE, '..', 'probe_out', 'jobb', 'combat_proof')); fs.mkdirSync(OUT, { recursive: true });
var DIST = path.join(HERE, '..', 'static_dist'); var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1280, height: 800, gpu: true, unlockFps: true });
var report = { shots: [], notes: [], errors: [], console_errors: [] }; pg.on('Runtime.consoleAPICalled', function (p) { if (p.type !== 'error') return; var t = (p.args || []).map(function (a) { return a.value !== undefined ? String(a.value) : (a.description || ''); }).join(' '); if (/toNonIndexed/.test(t)) return; report.console_errors.push(t.slice(0, 400)); });
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function freeCam(from, at, fov) { await ev("var THREE=P.THREE; var r=P.rendererDebug(); if(!r.__orig){ r.__orig=r.render.bind(r); r.render=function(sc,cam){ if(window.__freecam){ r.__orig(sc, window.__freecam); } else r.__orig(sc,cam); }; } var c=new THREE.PerspectiveCamera(" + (fov || 45) + ", 1280/800, 0.1, 2400); c.position.set(" + from.join(',') + "); c.lookAt(" + at.join(',') + "); c.updateProjectionMatrix(); window.__freecam=c; return 1;"); }
async function shot(name, keepHud) { if (!keepHud) await ev("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;"); await sleep(220); await pg.screenshot(path.join(OUT, name + '.png')); await ev("document.querySelectorAll('body > *').forEach(function(e){ e.style.visibility=''; }); return 1;"); report.shots.push(name); console.log('shot', name); }
async function nearest() { return await ev("var p=P.snap().play; var me=p.position; var best=null, bd=1e9; (p.creatures||[]).forEach(function(c){ if (c.ko) return; var d=Math.hypot(c.position.x-me.x, c.position.z-me.z); if(d<bd){ bd=d; best=c; } }); return best ? { id: best.id, x: best.position.x, z: best.position.z, state: best.state, d: bd, hp: best.hp, max: best.max, ko: best.ko } : null;"); }
async function me() { return await ev("var p=P.snap().play; var r=p.rules; return { pos: p.position, hp: r ? r.me.hp : null, max: r ? r.me.max : null, ko: r ? r.me.ko : null, defeat: p.defeat || null, lock: r && r.me.lock ? r.me.lock.target : null };"); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(3000); await ev("P.hud.showGuide(false); return 1;");
  for (var i = 0; i < 240; i++) { var w = await ev("return P.world ? P.world().status : null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); } await sleep(2500);
  /* 1. into the west forest: the Dogkies wake and the nearest one comes for the player */
  await ev("return P.goTo(-40, -30, undefined, undefined, 60000);"); await ev("return P.goTo(-70, 0, undefined, undefined, 60000);"); await sleep(1500); var n0 = await nearest(); report.notes.push('nearest at arrival ' + JSON.stringify(n0));
  if (n0) { await ev("return P.goTo(" + (n0.x + 2.4) + ", " + (n0.z + 1.8) + ", undefined, undefined, 40000);"); }
  var bitten = null; for (var k = 0; k < 40; k++) { await sleep(300); var m = await me(); var n = await nearest(); if (m.hp !== null && m.hp < m.max - 1) { bitten = { me: m, n: n }; break; } }
  report.notes.push('bitten ' + JSON.stringify(bitten)); var n1 = await nearest(); if (n1) { await freeCam([n1.x + 3.4, 1.5, n1.z + 2.8], [n1.x, 0.8, n1.z], 45); await shot('01_dogkie_attacks_aura'); await ev("window.__freecam=null; return 1;"); } await shot('02_hud_health_after_bites', true);
  /* 2. fight back: lock the nearest and cast slot 1 until KO (the existing dispatcher) */
  var target = await nearest(); var casts = 0, kod = false; if (target) { await ev("return P.send('LOCK_TARGET', { aim_id: '" + target.id + "' });"); for (var c = 0; c < 40 && !kod; c++) { var t = await ev("var p=P.snap().play; var me=p.position; var t=(p.creatures||[]).filter(function(c){ return c.id==='" + target.id + "'; })[0]; if(!t) return null; var dx=t.position.x-me.x, dz=t.position.z-me.z, d=Math.hypot(dx,dz); return { d: d, yaw: Math.atan2(dx, -dz), hp: t.hp, ko: t.ko, x: t.position.x, z: t.position.z };"); if (!t) break; if (t.ko) { kod = true; break; } if (t.d > 1.9) { await ev("return P.goTo(" + (t.x) + ", " + (t.z) + ", undefined, undefined, 3000);"); continue; } await ev("P.send('MOVE', { forward: 0, strafe: 0, yaw: " + t.yaw.toFixed(3) + " }); return 1;"); await sleep(120); var r = await ev("return P.send('RULES_CAST', {});"); if (r && r.accepted) casts++; await sleep(950); } }
  var fin = await ev("var p=P.snap().play; var t=(p.creatures||[]).filter(function(c){ return c.id==='" + (target ? target.id : '') + "'; })[0]; return t ? { hp: t.hp, ko: t.ko, ko_ago: t.ko_ago_s, x: t.position.x, z: t.position.z } : null;"); report.notes.push('kill ' + JSON.stringify({ target: target && target.id, casts: casts, kod: kod, final: fin }));
  if (fin && fin.ko) { await freeCam([fin.x + 3.2, 1.6, fin.z + 2.6], [fin.x, 0.5, fin.z], 45); await shot('03_dogkie_defeated_dissolving'); await sleep(1200); await shot('04_dogkie_dissolved'); await ev("window.__freecam=null; return 1;"); }
  /* 3. the defeat loop: stay in the pack until HP 0, photograph the state, then the respawn */
  var defeated = null; for (var d = 0; d < 120; d++) { var m2 = await me(); if (m2.defeat) { defeated = m2; break; } var nn = await nearest(); if (nn && nn.d > 3) await ev("return P.goTo(" + (nn.x + 1.2) + ", " + (nn.z + 1.0) + ", undefined, undefined, 4000);"); else await sleep(400); }
  report.notes.push('defeated ' + JSON.stringify(defeated)); if (defeated) { await shot('05_defeated_state_hud', true); await sleep(3200); var m3 = await me(); report.notes.push('respawned ' + JSON.stringify(m3)); await shot('06_respawned_at_safe_point', true); report.respawn = { defeated_at: defeated.defeat.at, safe: defeated.defeat.safe, now: m3.pos, hp: m3.hp, max: m3.max, ko: m3.ko }; }
  report.host = await ev("var p=P.snap().play; return { creatures: (p.creatures||[]).map(function(c){ return c.id+':'+c.state+':'+c.hp; }), wildlife: (p.wildlife||[]).map(function(w){ return w.species+':'+w.state+':'+w.hp+'/'+w.max; }) };");
  report.modules = await ev("var d=P.world(); return d.modules ? { wildlife: d.modules.wildlife, creatures: d.modules.creatures } : null;"); report.errors = pg.errors.filter(function (e) { return !/404|favicon/.test(e); }).slice(0, 20);
} catch (e) { report.fatal = String(e && e.stack || e); console.error(e); } finally { fs.writeFileSync(path.join(OUT, 'combat_proof.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT combat_proof ' + (report.fatal ? 'FATAL' : 'OK') + ' shots ' + report.shots.length + ' errors ' + report.errors.length + ' console_errors ' + report.console_errors.length); report.notes.forEach(function (n) { console.log('  ' + n.slice(0, 300)); });
