/* Astra M3 rendered acceptance: the real NIGHT-first route, every environment standard, walked pass, and real MAH MATCH entry.
   Captures use dev placement only to frame distant route stages; the mountain pass and final approach use the real controller.
   node 26_LOCAL_AUTHORITY/deploy/jobb/probe_m3_night_route.mjs [static_dist] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var ROOT = path.resolve(HERE, '..', '..', '..');
var DIST = process.argv[2] ? path.resolve(process.argv[2]) : path.join(ROOT, '26_LOCAL_AUTHORITY', 'deploy', 'static_dist');
var OUT = path.join(ROOT, '25_HANDOFF', 'JOB_B', 'evidence', 'astra_m3'); fs.mkdirSync(OUT, { recursive: true });
var report = { generated_at: new Date().toISOString(), source: 'local static_dist (not packaged / not published)', capture_method: 'dev placement for distant composition; P.goTo real-controller traversal for pass and building approach', checks: [], screenshots: [], console_errors: [] };
var pass = 0, fail = 0; function ok(id, cond, detail) { (cond ? pass++ : fail++); var row = { id: id, pass: !!cond, detail: detail }; report.checks.push(row); console.log((cond ? 'PASS ' : 'FAIL ') + id + (detail === undefined ? '' : ' — ' + JSON.stringify(detail).slice(0, 900))); }
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1280, height: 800, dpr: 1.5, gpu: true, unlockFps: true });
async function ev(src) { return await pg.evaluate("(async function(){ var P=window.MAHWORLD_PLAY; " + src + " })()"); }
async function shot(name) { var f = path.join(OUT, name + '.png'); await pg.screenshot(f); report.screenshots.push(name + '.png'); return f; }
async function place(x, z, wait) { await ev("return P.devPlay('PLACE',{x:" + x + ",z:" + z + "});"); await sleep(wait || 800); }
async function face(x, z) { var p = await ev("return P.snap().play.position;"); var yaw = Math.atan2(x - p.x, -(z - p.z)); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:" + yaw.toFixed(4) + "}); P.camReset&&P.camReset('m3'); return 1;"); await sleep(800); }
async function waitReady() { for (var i = 0; i < 100; i++) { var q = await ev("var w=P.world(), s=P.warmState(); return {world:w&&w.status, warm:s&&s.world_done, err:s&&s.world_err, restore:P.restoreState().done};"); if (q.world === 'READY' && q.warm && q.restore) return q; await sleep(500); } return null; }

try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); var ready = await waitReady(); await sleep(1200); await ev("P.hud.showGuide(false); P.hud.setDev&&P.hud.setDev(false); return 1;"); ok('M3.1 world reaches READY with its warm gate complete', !!ready, ready);
  var reg = await ev("var r=P.worldLayer().registry(), q=r.quality_routes.list[0]; return {tod:r.sky.time_of_day, route:q, paths:r.paths.list.length, wayfinders:r.paths.wayfinders.length};"); var warm = await ev("var s=P.warmState(); return {world_done:s.world_done, states:s.time_states, tod:P.timeOfDay(), programs:P.rendererDebug().info.programs.length};"); report.registry = reg; report.warm = warm;
  ok('M3.2 a fresh page is NIGHT and the boot gate prewarmed DAY then NIGHT before restoring NIGHT', reg.tod.default === 'NIGHT' && reg.tod.preview === 'NIGHT' && warm.tod === 'NIGHT' && warm.states && warm.states.done && warm.states.states.join('|') === 'DAY|NIGHT' && warm.states.restored === 'NIGHT' && !warm.states.error, warm);
  ok('M3.3 route registry carries all seven standards and every referenced road exists in the rendered registry', reg.route.stages.length === 7 && reg.route.stages.map(function (s) { return s.standard; }).join('|') === 'FLOOR|ROAD|FOREST_RESOURCE|POND|MOUNTAIN|BUILDING|SKY' && reg.route.path_ids.length === 7 && reg.wayfinders >= 23, { stages: reg.route.stages, paths: reg.paths, wayfinders: reg.wayfinders });
  var dbg = await ev("return P.worldLayer().debug();"); report.world_debug = dbg;
  ok('M3.4 full world standard is live: terrain/roads, forest, water, mountain macro, atmosphere, signage and named building modules', dbg.terrain && dbg.terrain.paths.CAUSEWAY >= 1 && dbg.terrain.paths.REGIONAL >= 1 && dbg.forest && dbg.forest.trees > 100 && dbg.water && dbg.water.rivers >= 4 && dbg.macro && dbg.macro.ridges.length >= 2 && dbg.atmosphere && dbg.atmosphere.on && dbg.signage && dbg.signage.buildings >= 10 && dbg.matchHall && dbg.matchHall.building, { terrain: dbg.terrain, forest: dbg.forest, water: dbg.water, macro: dbg.macro, atmosphere: dbg.atmosphere, signage: dbg.signage, match: dbg.matchHall });

  await place(0, 4); await face(38, 38); await ev("P.cam(2.7,0.18,12,1.8); return 1;"); await shot('01_night_civic_forecourt'); await ev("P.menu.open('MAP'); return 1;"); await sleep(500); await shot('02_route_map_overlay'); await ev("P.menu.close('m3-probe'); return 1;");
  await place(70, 70); await face(94, 88); await ev("P.cam(2.9,0.2,13,2); return 1;"); await shot('03_tower_class_road');
  await place(116, 168); await face(124, 165); await ev("P.cam(2.5,0.16,10,1.7); return 1;"); await sleep(900); var fr = await ev("var p=P.snap().play, n=(p.nodes||[]).filter(function(x){return x.patch==='RB_NE_PATH';})[0], d=P.worldLayer().debug(); return {node:n, trees:d.forest.trees, region:d.terrain.regions};"); report.forest_resource = fr; ok('M3.5 forest stage has the live host-owned RB_NE_PATH node and the rendered tree population', fr.node && fr.node.id && !fr.node.broken && fr.trees > 100, fr); await shot('04_titan_forest_resource');
  await place(150, 126); await face(149, 104); await ev("P.cam(3.0,0.24,14,2.2); return 1;"); await sleep(1200); var pond = await ev("var p=P.snap().play, W=P.worldLayer(), w=W.debug().water, r=W.registry(), m=r.water.rivers.filter(function(x){return x.id==='TITAN_LAKE';})[0]; return {water:w, meta:m, fish:(p.wildlife||[]).filter(function(x){return x.species==='FISH';}).length, surface_mesh:w.meshes.indexOf('WATER_SURFACE')>=0, shore_ground:P.groundAt(149,124,10)};"); report.pond = pond; ok('M3.6 TITAN LAKE renders as real water with four walkable shores/wade metadata and live fish ecology', pond.water && pond.water.rivers >= 4 && pond.meta && pond.meta.pond && pond.meta.shore_w >= 4 && pond.meta.wade_y < pond.meta.surface_y && pond.surface_mesh && pond.fish > 0 && pond.shore_ground >= 0, pond); await shot('05_titan_lake_pond');
  await place(150, 83); await face(150, 40); await ev("P.cam(3.1416,0.14,11,1.8); return 1;"); await shot('06_moon_pass_approach'); var passGround = await ev("return {north:P.groundAt(150,79,10),top:P.groundAt(150,62,10),south:P.groundAt(150,43,10),off:P.groundAt(150,36,10)};"); var walk = await ev("return await P.goTo(150,41,150,30,26000);"); var posAfter = await ev("return P.snap().play.position;"); report.pass_traversal = { ground: passGround, walk: walk, final: posAfter };
  ok('M3.7 the controller walks the collision-backed Moon Pass from approach to descent; support rises to 2.8 m and returns to ground', walk && walk.reached && passGround.top === 2.8 && passGround.north > 0 && passGround.north < 2.8 && passGround.south > 0 && passGround.south < 2.8 && passGround.off === 0, report.pass_traversal); await place(150, 62); await face(150, 35); await ev("P.cam(3.1416,0.2,14,2.4); return 1;"); await shot('07_moon_pass_top');
  await place(96, 34); var approach = await ev("return await P.goTo(84,6,98,6,24000);"); await face(98, 6); await shot('08_match_forecourt'); var doorWalk = await ev("return await P.goTo(95.2,6,98,6,12000);"); var enter = await ev("return P.send('ENTER_ROOM',{room:'MATCH_HALL'});"); await sleep(3200); var room = await ev("return {room:P.snap().play.room, trx:P.transaction()};"); report.building = { approach: approach, door_walk: doorWalk, enter: enter, room: room };
  ok('M3.8 final regional road reaches the MAH MATCH forecourt and the real MATCH_DOOR enters its named bespoke hall', approach && approach.reached && doorWalk && doorWalk.reached && enter && enter.accepted && room.room === 'MATCH_HALL', report.building); await shot('09_match_hall_interior');
  await place(0, 19.4); var exit = await ev("return P.send('ENTER_ROOM',{room:'FIELD'});"); await sleep(3200); var exitedRoom = await ev("return P.snap().play.room;"); ok('M3.9 the hall EXIT returns to the same warm playable field', exit && exit.accepted && exitedRoom === 'FIELD', { exit: exit, room: exitedRoom });

  await place(150, 62); var prog0 = await ev("return P.rendererDebug().info.programs.length;"); var day = await ev("return P.timeOfDay('DAY');"); await sleep(700); var progD = await ev("return P.rendererDebug().info.programs.length;"); await face(150, 35); await shot('10_day_state_prewarmsafe'); var night = await ev("return P.timeOfDay('NIGHT');"); await sleep(700); var progN = await ev("return P.rendererDebug().info.programs.length;"); report.day_night = { before: prog0, day: progD, night: progN, day_state: day, final_state: night };
  ok('M3.10 DAY and NIGHT switch live after prewarm and the route finishes restored to NIGHT without a second shader-program surge', day === 'DAY' && night === 'NIGHT' && progD - prog0 <= 3 && progN - prog0 <= 3, report.day_night); await shot('11_night_route_final');
  var unexpected = pg.errors.filter(function (e) { return !/favicon\.ico|athlete_m_preview\/dev_0\.(?:1|2|3|4|5|6|7|9|10|11|12|13)\/manifest\.json/.test(e); }); report.console_errors = pg.errors.slice(); report.expected_probe_404s = pg.errors.length - unexpected.length; ok('M3.11 rendered route has no unexpected runtime/console errors', unexpected.length === 0, unexpected.slice(0, 8));
} catch (e) { ok('M3.probe_exception', false, String(e && e.stack || e)); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'm3_night_route_report.json'), JSON.stringify(report, null, 1));
console.log('M3 rendered route probe: ' + pass + ' pass / ' + fail + ' fail → ' + OUT); await pg.close(); srv.close(); process.exit(fail ? 1 : 0);
