/* JOB B REDIRECT real-runtime proof (owner package 2026-09-19 §21): the static demo boots in headless Chrome (GPU), the world layer reports READY,
   and a FREE inspection camera (the page renderer draws with the probe camera for the capture; the game camera / collision untouched) photographs:
   overview (high plan) · ground + path close-up (causeway frame / core, shards, region tint) · tree lock (platinum trunk, crystal extremities) ·
   water + a fish breach (summoned; the school also breaches on its own timer) · the horse on the open range · the golden phoenix (summoned; rare
   on its own timer) · the fairy guide beside the player · a PHONE-size frame (393 × 852 portrait, EMULATED — never iPhone acceptance) · the MAP.
   Also records module debug (wildlife rigs / positions / states, terrain counts, sky wind) and console errors. node deploy/jobb/redirect_proof.mjs [out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var OUT = path.resolve(argv[0] || path.join(HERE, '..', 'probe_out', 'jobb', 'redirect_proof')); fs.mkdirSync(OUT, { recursive: true });
var DIST = path.join(HERE, '..', 'static_dist'); var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1280, height: 800, gpu: true, unlockFps: true });   /* part 1; part 2 relaunches */
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function freeCam(from, at, fov) { await ev("var THREE=P.THREE; var r=P.rendererDebug(); if(!r.__orig){ r.__orig=r.render.bind(r); r.render=function(sc,cam){ if(window.__freecam){ r.__orig(sc, window.__freecam); } else r.__orig(sc,cam); }; } var c=new THREE.PerspectiveCamera(" + (fov || 45) + ", 1280/800, 0.1, 2400); c.position.set(" + from.join(',') + "); c.lookAt(" + at.join(',') + "); c.updateProjectionMatrix(); window.__freecam=c; return 1;"); }
async function shot(name, keepHud) { if (!keepHud) await ev("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;"); await sleep(260); await pg.screenshot(path.join(OUT, name + '.png')); await ev("document.querySelectorAll('body > *').forEach(function(e){ e.style.visibility=''; }); return 1;"); report.shots.push(name); console.log('shot', name); }
var report = { shots: [], errors: [], notes: [], console_errors: [] };
function tapConsole(page) { page.on('Runtime.consoleAPICalled', function (p) { if (p.type !== 'error') return; var t = (p.args || []).map(function (a) { return a.value !== undefined ? String(a.value) : (a.description || ''); }).join(' '); if (/toNonIndexed/.test(t)) return; report.console_errors.push(t.slice(0, 400)); }); }   /* console.error (three's shader errors) counts — a silent shader failure is not a pass */
tapConsole(pg);
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(3000); await ev("P.hud.showGuide(false); return 1;");
  for (var i = 0; i < 240; i++) { var w = await ev("return P.world ? P.world().status : null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); }
  for (var w0 = 0; w0 < 120; w0++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); } await sleep(2500);
  report.world_status = await ev("return P.world().status;"); report.build = await ev("return window.MAHWORLD_BUILD_INFO || null;");
  /* 1. OVERVIEW: high plan from the south-west, the whole mainland + the near sea / islets */
  await freeCam([-260, 240, -260], [0, 0, 120], 55); await shot('01_overview_high');
  await freeCam([0, 130, -330], [0, 0, 100], 50); await shot('02_overview_south_coast');
  /* 2. GROUND + PATHS: the gym causeway leaving the plaza (frame + core), shards + the purple forest tint at the west edge */
  await freeCam([-50, 3.2, 44], [-70, 0.3, 66], 50); await shot('03_ground_causeway_gym');
  await freeCam([-72, 2.4, 20], [-90, 0.2, 12], 55); await shot('04_ground_forest_path_shards');
  await freeCam([-118, 6, -14], [-120, 3, 0], 50); await shot('05_monolith_umbral');
  /* 2b. MACRO elevation: the west crown terrace from the west bridge landing (ramp, lip, trees standing on the plateau) and from above */
  await freeCam([-100, 2.4, 236], [-130, 1.2, 262], 55); await shot('05b_terrace_west_from_bridge'); await freeCam([-60, 26, 220], [-120, 0.5, 270], 50); await shot('05c_terrace_west_high');
  /* 3. TREE LOCK: an L0 tree from 9 m (trunk metal, crystal at the extremities), and a mid-distance band */
  var tree = await ev("var pl=P.worldLayer().ctx.forestPlacement; var t=null; for (var i=0;i<pl.length;i++){ if (pl[i].zone==='FOREST_W' && pl[i].x>-100 && pl[i].z>-10 && pl[i].z<20){ t=pl[i]; break; } } return t;"); report.tree = tree;
  if (tree) { await ev("return P.goTo(" + (tree.x + 7) + ", " + (tree.z + 6) + ", undefined, undefined, 60000);"); await sleep(1500); await freeCam([tree.x + 8, 5, tree.z + 7], [tree.x, 6.5, tree.z], 50); await shot('06_tree_lock_L0'); await freeCam([tree.x + 24, 9, tree.z + 30], [tree.x - 10, 7, tree.z - 10], 50); await shot('07_tree_lock_band'); }
  /* 4. WATER + FISH: the south school; summon a breach and photograph the arc + splash from the beach */
  await ev("return P.goTo(0, -40, undefined, undefined, 60000);"); await sleep(1500); var schools = await ev("var wl=P.worldLayer().wildlife(); return wl ? wl.schools() : [];"); report.schools = schools; var S = schools.filter(function (s) { return s.id === 'S'; })[0] || schools[0];
  if (S) { await ev("return P.devPlay('WILDLIFE_SUMMON', { species: 'FISH' });"); await sleep(120); var fp = await ev("var L=P.snap().play.wildlife||[]; for (var i=0;i<L.length;i++){ var w=L[i]; if (w.species==='FISH' && (w.state==='RISE'||w.state==='BREACH')) return { id: w.id, x: w.position.x, z: w.position.z, hx: -Math.sin(w.facing), hz: -Math.cos(w.facing), y0: w.y, state: w.state }; } return null;"); report.notes.push('breacher ' + JSON.stringify(fp));
    if (fp) { var apx = fp.x + fp.hx * 4.2, apz = fp.z + fp.hz * 4.2; var px = -fp.hz, pz = fp.hx;   /* the apex ≈ 4 m along the heading; the camera stands 13 m off to the side of the arc */ await freeCam([apx + px * 13, 1.9, apz + pz * 13], [apx, 1.0, apz], 50); await ev("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;"); var delays = [700, 300, 300, 350, 400]; for (var f = 0; f < 5; f++) { await sleep(delays[f]); await pg.screenshot(path.join(OUT, '08_fish_breach_' + f + '.png')); report.shots.push('08_fish_breach_' + f); var fq = await ev("var L=P.snap().play.wildlife||[]; var w=L.filter(function(x){ return x.id==='" + fp.id + "'; })[0]; return w ? [+w.position.x.toFixed(1), +w.y.toFixed(2), +w.position.z.toFixed(1), w.state] : null;"); report.notes.push('breach frame ' + f + ' fish at ' + JSON.stringify(fq)); } await ev("document.querySelectorAll('body > *').forEach(function(e){ e.style.visibility=''; }); return 1;"); }
    await freeCam([S.x + 30, 4, S.z + 26], [S.x, -0.5, S.z], 45); await shot('09_fish_school_surface'); }
  /* 5. HORSE on the open range */
  await ev("return P.goTo(60, 4, undefined, undefined, 60000);"); await ev("return P.goTo(90, 60, undefined, undefined, 60000);"); await sleep(1500); var horse = await ev("var wl=P.worldLayer().wildlife(); var d=wl.debug(); var H=d.species.HORSE; return H && H.positions.length ? { p: H.positions[0], st: H.states[0], all: H.positions } : null;"); report.horse = horse;
  if (horse && horse.p) { await freeCam([horse.p[0] + 6, 2.2, horse.p[2] + 5], [horse.p[0], 1.0, horse.p[2]], 45); await shot('10_horse_range'); await sleep(2500); horse = await ev("var wl=P.worldLayer().wildlife(); var d=wl.debug(); var H=d.species.HORSE; return { p: H.positions[0], st: H.states[0] };"); await freeCam([horse.p[0] - 5, 1.8, horse.p[2] + 6], [horse.p[0], 1.0, horse.p[2]], 45); await shot('11_horse_range_' + horse.st.toLowerCase()); }
  /* 6. PHOENIX: summon; wait until it is over the crown anchor; photograph from below-behind and from the side */
  var ph = null; for (var k = 0; k < 60; k++) { await sleep(1000); ph = await ev("var wl=P.worldLayer().wildlife(); var d=wl.debug(); var X=d.species.PHOENIX; return X && X.positions.length ? { p: X.positions[0], st: X.states[0] } : null;"); if (ph && ph.p && Math.hypot(ph.p[0] - 60, ph.p[2] - 330) < 200) break; }
  report.phoenix = ph; if (ph && ph.p) { await freeCam([ph.p[0] + 16, ph.p[1] - 6, ph.p[2] + 14], [ph.p[0], ph.p[1], ph.p[2]], 45); await shot('12_phoenix_flight'); await sleep(1200); ph = await ev("var wl=P.worldLayer().wildlife(); var d=wl.debug(); var X=d.species.PHOENIX; return { p: X.positions[0], st: X.states[0] };"); await freeCam([ph.p[0] - 12, ph.p[1] + 3, ph.p[2] + 10], [ph.p[0], ph.p[1], ph.p[2]], 45); await shot('13_phoenix_' + ph.st.toLowerCase()); await freeCam([0, 4, 200], [ph.p[0], ph.p[1], ph.p[2]], 60); await shot('14_phoenix_from_ground'); }
  report.modules_part1 = await ev("var d=P.world(); return d.modules ? { wildlife: d.modules.wildlife, terrain: d.modules.terrain, sky: d.modules.sky, forest: d.modules.forest, coast: d.modules.coast } : null;");
} catch (e) { report.part1_error = String(e && e.stack || e); console.error('part 1', e); }
/* part 2 (fairy / sky / map) runs on a FRESH page so a renderer death in part 1 (headless Chrome on a loaded machine) never costs the rest of the proof */
try { await pg.close(); } catch (e) { } pg = await launchChrome({ width: 1280, height: 800, gpu: true, unlockFps: true }); tapConsole(pg);
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(3000); await ev("P.hud.showGuide(false); return 1;");
  for (var i2 = 0; i2 < 240; i2++) { var w2 = await ev("return P.world ? P.world().status : null;"); if (w2 === 'READY' || w2 === 'FAILED') break; await sleep(500); } await sleep(2500);
  /* 7. FAIRY guide beside the player (species motion: hover / drift / settle) — in the real rear camera and a close inspection */
  await ev("window.__freecam=null; return P.goTo(0, 60, undefined, undefined, 60000);"); await sleep(600); await ev("var g=P.worldLayer().guides(); g.setGuide('MRS'); g.setVisible(true); return 1;"); await sleep(4500);
  var gd = await ev("var g=P.worldLayer().guides(); return g.debug();"); report.guide = gd; await shot('15_fairy_rear_camera', true); if (gd.pos) { await freeCam([gd.pos[0] + 1.7, gd.pos[1] + 0.3, gd.pos[2] + 1.5], gd.pos, 45); await shot('16_fairy_close'); }
  await ev("window.__freecam=null; return 1;"); await ev("return P.goTo(0, 40, undefined, undefined, 30000);"); await sleep(1200); gd = await ev("var g=P.worldLayer().guides(); return g.debug();"); report.guide_moving = gd; await shot('17_fairy_travel', true);
  /* 8. SKY: clouds + mist from the temple roof height */
  await freeCam([0, 40, 100], [0, 120, 400], 60); await shot('18_sky_layers');
  /* 9. MAP */
  await ev("window.__freecam=null; P.menu.open('MAP'); return 1;"); await sleep(900); await shot('19_map', true); await ev("P.menu.close('probe'); return 1;");
  report.modules = await ev("var d=P.world(); return d.modules ? { wildlife: d.modules.wildlife, terrain: d.modules.terrain, sky: d.modules.sky, forest: d.modules.forest, coast: d.modules.coast, guides: d.modules.guides } : null;");
  report.errors = pg.errors.filter(function (e) { return !/404|favicon/.test(e); }).slice(0, 20);
} catch (e) { report.fatal = String(e && e.stack || e); console.error(e); } finally { fs.writeFileSync(path.join(OUT, 'redirect_proof.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
/* PHONE-size frame: a second, portrait session (393 × 852 @2, mobile emulation) — the real HUD over the world, fairy on; EMULATED touch, never iPhone acceptance */
try { var srv2 = await serveStatic(DIST); var pg2 = await launchChrome({ width: 393, height: 852, dpr: 2, mobile: true, gpu: true }); await pg2.goto(srv2.origin + PLAY_PATH + '?field=1'); await waitForGame(pg2, 120000); await sleep(3000); for (var j = 0; j < 200; j++) { var ws = await pg2.evaluate("(function(){ var P=window.MAHWORLD_PLAY; return P.world ? P.world().status : null; })()"); if (ws === 'READY' || ws === 'FAILED') break; await sleep(500); } await sleep(2500); await pg2.evaluate("(function(){ var P=window.MAHWORLD_PLAY; var g=P.worldLayer().guides(); g.setGuide('MRS'); g.setVisible(true); return 1; })()"); await sleep(3500); await pg2.screenshot(path.join(OUT, '20_phone_portrait_emulated.png')); report.phone = { frame: '393x852@2 EMULATED (Chrome mobile emulation) — not iPhone acceptance', errors: pg2.errors.filter(function (e) { return !/404|favicon/.test(e); }).slice(0, 10) }; await pg2.close(); srv2.close(); fs.writeFileSync(path.join(OUT, 'redirect_proof.json'), JSON.stringify(report, null, 1)); } catch (e) { console.error('phone frame', e); }
console.log('RESULT redirect_proof ' + (report.fatal ? 'FATAL' : 'OK') + ' shots ' + report.shots.length + ' errors ' + report.errors.length + ' console_errors ' + report.console_errors.length + ' world ' + report.world_status);
