/* JOB B redirect rig proof: loads a species derivative with the game's vendored three.js, applies lab/world/creatureRig.js
   (bind-pose re-base + the geometric classifier), draws bone markers, and photographs REST / a test pose (fish undulation, bird
   flap, quadruped stride) from the side and the front. Prints the classification report — the honest evidence that the heuristic rig
   pivots at the joints and that the procedural motion reads. node deploy/jobb/rig_view.mjs <out dir> FISH|BIRD|QUADRUPED <glb> */
import fs from 'node:fs'; import path from 'node:path'; import http from 'node:http'; import { fileURLToPath } from 'node:url';
import { launchChrome, sleep } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.resolve(HERE, '..', '..');
var argv = process.argv.slice(2); var out = path.resolve(argv[0]); fs.mkdirSync(out, { recursive: true }); var KIND = argv[1]; var file = path.resolve(argv[2]);
var MIME = { '.js': 'application/javascript', '.glb': 'model/gltf-binary', '.html': 'text/html' };
var srv = http.createServer(function (req, res) { var u = decodeURIComponent(req.url.split('?')[0]); if (u === '/') { res.writeHead(200, { 'Content-Type': 'text/html' }); res.end(PAGE); return; } if (u === '/glb') { res.writeHead(200, { 'Content-Type': 'model/gltf-binary', 'Content-Length': fs.statSync(file).size }); fs.createReadStream(file).pipe(res); return; } var fp = path.join(LA, u); if (fp.startsWith(LA) && fs.existsSync(fp) && !fs.statSync(fp).isDirectory()) { res.writeHead(200, { 'Content-Type': MIME[path.extname(fp)] || 'application/octet-stream' }); fs.createReadStream(fp).pipe(res); return; } res.writeHead(404); res.end('nf ' + u); });
var PAGE = '<!doctype html><html><body style="margin:0;background:#9fc4e4"><canvas id="c" style="width:100vw;height:100vh"></canvas><script type="importmap">{"imports":{"three":"/vendor/three/three.module.min.js"}}</script><script type="module">\n' +
  'import * as THREE from "three"; import { GLTFLoader } from "/vendor/three/GLTFLoader.js"; import * as RIG from "/lab/world/creatureRig.js"; window.THREE = THREE; window.RIG = RIG;\n' +
  'const c = document.getElementById("c"); const r = new THREE.WebGLRenderer({ canvas: c, antialias: true }); r.setSize(innerWidth, innerHeight, false); r.setPixelRatio(1); r.toneMapping = THREE.ACESFilmicToneMapping; r.toneMappingExposure = 1.35; r.outputColorSpace = THREE.SRGBColorSpace;\n' +
  'const s = new THREE.Scene(); s.background = new THREE.Color(0x9fc4e4); const cam = new THREE.PerspectiveCamera(35, innerWidth / innerHeight, 0.01, 100); s.add(new THREE.HemisphereLight(0xdde8ff, 0x556070, 1.1)); const key = new THREE.DirectionalLight(0xfff3dc, 2.2); key.position.set(3, 5, 2); s.add(key);\n' +
  'const grid = new THREE.GridHelper(4, 16, 0x335577, 0x557799); s.add(grid); let root = null, spec = null, markers = null, size = 1;\n' +
  'window.load = (kind) => new Promise((res, rej) => { new GLTFLoader().load("/glb", (g) => { root = g.scene; s.add(root); const rb = RIG.rebaseFromBind(THREE, root); const logs = []; const log = (m) => logs.push(m); spec = kind === "FISH" ? RIG.classifyFish(THREE, root, log) : kind === "BIRD" ? RIG.classifyBird(THREE, root, log) : RIG.classifyQuadruped(THREE, root, log);\n' +
  '  root.updateMatrixWorld(true); const box = spec.box; const ctr = box.getCenter(new THREE.Vector3()); size = box.getSize(new THREE.Vector3()).length(); root.position.set(-ctr.x, -box.min.y, -ctr.z); root.rotation.y = spec.fix; root.updateMatrixWorld(true);\n' +
  '  /* bone markers (attached to the bones so they follow the pose) */ const mg = new THREE.SphereGeometry(size * 0.012, 8, 6); const mm = new THREE.MeshBasicMaterial({ color: 0xff3366, depthTest: false }); markers = []; spec.bones.forEach((b) => { const m = new THREE.Mesh(mg, mm); m.renderOrder = 10; b.add(m); markers.push(m); });\n' +
  '  let tris = 0; root.traverse((o) => { if (o.isMesh && o.geometry) tris += (o.geometry.index ? o.geometry.index.count : o.geometry.attributes.position.count) / 3; });\n' +
  '  res({ rebase: rb, report: spec.report, logs, tris, size_m: box.getSize(new THREE.Vector3()).toArray() }); }, undefined, rej); });\n' +
  'window.view = (yaw, pitch, mult) => { const d = size * 1.5 * (mult || 1); cam.position.set(Math.sin(yaw) * Math.cos(pitch) * d, size * 0.45 + Math.sin(pitch) * d, Math.cos(yaw) * Math.cos(pitch) * d); cam.lookAt(0, size * 0.3, 0); r.render(s, cam); return true; };\n' +
  'window.markers = (v) => { markers.forEach((m) => m.visible = v); return true; };\n' +
  'const set = RIG.makePoser(THREE);\n' +
  'window.pose = (kind, t) => { if (!spec) return false; if (kind === "FISH") { const n = spec.spine.length; spec.spine.forEach((sp, i) => { const k = i / Math.max(1, n - 1); set(sp.bone, sp, 0, 0.55 * k * k * Math.sin(t * 6.28 * 1.4 - k * 2.6), 0); }); spec.fins.forEach((f) => { f.specs.forEach((sp, i) => set(sp.bone, sp, 0.25 * Math.sin(t * 6.28 * 2.2 + (f.side === "L" ? 0 : 3.1)), 0, 0)); }); }\n' +
  '  else if (kind === "BIRD") { const fl = Math.sin(t * 6.28 * 1.1); [[spec.wingL, 1], [spec.wingR, -1]].forEach(([w, sg]) => w.forEach((sp, i) => set(sp.bone, sp, 0, 0, sg * (0.55 * fl * (i === 0 ? 1 : 0.6) + 0.15)))); spec.tailL.forEach((sp) => set(sp.bone, sp, 0.1 * fl, 0.15, 0)); spec.tailR.forEach((sp) => set(sp.bone, sp, 0.1 * fl, -0.15, 0)); if (spec.head) set(spec.head.bone, spec.head, 0.1 * Math.sin(t * 3), 0, 0); }\n' +
  '  else { const ph = t * 6.28 * 1.6; const A = 0.35; const L = spec.legs; const sw = (k, s, f) => { if (!L[k]) return; set(L[k].top.bone, L[k].top, -A * s, 0, 0); set(L[k].mid.bone, L[k].mid, 0.5 * Math.max(0, f), 0, 0); }; sw("FL", Math.sin(ph), Math.cos(ph)); sw("BR", Math.sin(ph), Math.cos(ph)); sw("FR", -Math.sin(ph), -Math.cos(ph)); sw("BL", -Math.sin(ph), -Math.cos(ph)); if (spec.neck) set(spec.neck.bone, spec.neck, 0.08 * Math.sin(2 * ph), 0, 0); spec.tail.forEach((sp) => set(sp.bone, sp, 0, 0.2 * Math.sin(ph), 0)); }\n' +
  '  root.updateMatrixWorld(true); return true; };\n' +
  'window.ready = true;</script></body></html>';
await new Promise(function (r) { srv.listen(0, '127.0.0.1', r); }); var port = srv.address().port; var pg = await launchChrome({ width: 900, height: 640, gpu: true }); var report = null;
try {
  await pg.goto('http://127.0.0.1:' + port + '/'); for (var w = 0; w < 100; w++) { if (await pg.evaluate('!!window.ready')) break; await sleep(100); }
  var info = await pg.evaluate('window.load("' + KIND + '")'); var base = path.basename(file).replace(/\.glb$/, ''); var shots = {};
  console.log(base, 'rebase', JSON.stringify(info.rebase), 'tris', info.tris, 'size', info.size_m.map(function (v) { return v.toFixed(3); }).join('×')); info.logs.forEach(function (l) { console.log('  ' + l); });
  for (var v of [['rest_side', Math.PI / 2, 0.1, true, null], ['rest_front', 0, 0.12, true, null], ['rest_q34', 0.8, 0.25, false, null], ['pose_a_side', Math.PI / 2, 0.1, false, 0.18], ['pose_b_side', Math.PI / 2, 0.1, false, 0.55], ['pose_a_front', 0, 0.12, false, 0.18], ['pose_b_q34', 0.8, 0.25, false, 0.55]]) {
    await pg.evaluate('window.markers(' + v[3] + ')'); if (v[4] !== null) await pg.evaluate('window.pose("' + KIND + '",' + v[4] + ')'); await pg.evaluate('window.view(' + v[1] + ',' + v[2] + ',1)'); await sleep(80); var f = path.join(out, base + '_' + v[0] + '.png'); await pg.screenshot(f); shots[v[0]] = path.basename(f); }
  report = { file: file, kind: KIND, rebase: info.rebase, report: info.report, triangles: info.tris, size_m: info.size_m, shots: shots, console_errors: pg.errors.slice() }; console.log('report', JSON.stringify(info.report)); if (pg.errors.length) console.log('console errors', pg.errors);
} catch (e) { console.error(e); } finally { await pg.close(); srv.close(); }
if (report) fs.writeFileSync(path.join(out, path.basename(file).replace(/\.glb$/, '') + '_rig.json'), JSON.stringify(report, null, 1));
