"""World revamp (brief §29-35): no grid floor — polished platinum/chromium surface with sweeping curved seams, embedded diamond geometry,
metallic-blue details and pathway inlays (one authored 2048² canvas over the field, never tiled); the TREE ELEVATOR landmark (branching
platinum structure, crystal joints, luminous conduits, pods, upper platform); residential pod cluster; expanded field (112 m)."""
import os, json
HERE = os.path.dirname(os.path.abspath(__file__))
def patch(name, pairs):
    p = os.path.join(HERE, name); s = open(p, encoding='utf-8').read()
    for old, new in pairs:
        assert s.count(old) == 1, (name, old[:70], s.count(old)); s = s.replace(old, new)
    open(p, 'w', encoding='utf-8').write(s)

patch('fieldScene.js', [
 ("var floor = new THREE.Mesh(new THREE.PlaneGeometry(size, size), new THREE.MeshStandardMaterial({ color: NIGHT ? 0x2a3444 : 0x1b2230, roughness: NIGHT ? 0.22 : 0.35, metalness: NIGHT ? 0.9 : 0.6 })); floor.rotation.x = -Math.PI / 2; group.add(floor);   /* premium chromium ground: glossy but readable, reflections from the environment map */\n      var grid = new THREE.GridHelper(size, size / 4, 0x4fa3ff, 0x24405f); grid.position.y = 0.012; grid.material.transparent = true; grid.material.opacity = NIGHT ? 0.22 : 0.55; group.add(grid);",
  """/* FLOOR (S09 §31): one authored platinum / chromium surface — sweeping curved seams around the plaza, embedded diamond inlays, metallic-blue
         detail bands and directional pathway inlays toward the four entrances and the tree elevator. No grid, no checker. The map is painted once
         (2048², sRGB) and stretched over the whole field so nothing repeats. */
      var floorTex = canvasTex(2048, 2048, function (g, w, h) { var cx = w / 2, cz = h / 2, k = w / size;   /* k px per metre */
        var base = g.createRadialGradient(cx, cz, 10, cx, cz, w * 0.72); base.addColorStop(0, NIGHT ? '#3a4557' : '#2b3446'); base.addColorStop(0.55, NIGHT ? '#2a3444' : '#202838'); base.addColorStop(1, NIGHT ? '#1a2230' : '#151b28'); g.fillStyle = base; g.fillRect(0, 0, w, h);
        /* brushed platinum grain */ g.globalAlpha = 0.07; for (var i = 0; i < 900; i++) { var ang = Math.random() * Math.PI * 2, r0 = Math.random() * w * 0.75, len = 40 + Math.random() * 220; g.strokeStyle = Math.random() < 0.5 ? '#dfe7f0' : '#0b1220'; g.lineWidth = 1 + Math.random() * 2; g.beginPath(); g.moveTo(cx + Math.cos(ang) * r0, cz + Math.sin(ang) * r0); g.lineTo(cx + Math.cos(ang + 0.004) * (r0 + len), cz + Math.sin(ang + 0.004) * (r0 + len)); g.stroke(); } g.globalAlpha = 1;
        /* sweeping curved seams */ [12, 19, 27, 36, 46].forEach(function (rm, i) { g.strokeStyle = i % 2 ? 'rgba(191,230,255,0.28)' : 'rgba(120,150,190,0.35)'; g.lineWidth = i % 2 ? 3 : 5; g.beginPath(); g.arc(cx, cz, rm * k, 0, Math.PI * 2); g.stroke(); g.strokeStyle = 'rgba(8,14,26,0.45)'; g.lineWidth = 2; g.beginPath(); g.arc(cx, cz, rm * k + 5, 0, Math.PI * 2); g.stroke(); });
        for (var sw = 0; sw < 6; sw++) { g.strokeStyle = 'rgba(160,200,240,0.18)'; g.lineWidth = 4; g.beginPath(); g.arc(cx + Math.cos(sw * 1.05) * 30 * k, cz + Math.sin(sw * 1.05) * 30 * k, 22 * k, sw * 1.05 + 2.2, sw * 1.05 + 3.9); g.stroke(); }
        /* directional pathway inlays: plaza -> entrances and -> tree elevator (soft luminous guides) */ [[-17, 0], [0, -19.5], [18, 0], [1, 20], [30, 40], [-30, 30]].forEach(function (pt) { var gx = cx + pt[0] * k, gz = cz + pt[1] * k; var d = Math.hypot(gx - cx, gz - cz); var gr = g.createLinearGradient(cx, cz, gx, gz); gr.addColorStop(0, 'rgba(120,170,220,0)'); gr.addColorStop(0.35, 'rgba(120,170,220,0.22)'); gr.addColorStop(1, 'rgba(191,230,255,0.42)'); g.strokeStyle = gr; g.lineWidth = 2.6 * k; g.lineCap = 'round'; g.beginPath(); g.moveTo(cx + (gx - cx) * (11 * k) / d, cz + (gz - cz) * (11 * k) / d); g.lineTo(gx, gz); g.stroke(); });
        /* embedded diamonds along the seams */ g.fillStyle = 'rgba(223,243,255,0.55)'; for (var dm = 0; dm < 48; dm++) { var a2 = dm / 48 * Math.PI * 2, rr2 = (dm % 2 ? 19 : 27) * k; var dx = cx + Math.cos(a2) * rr2, dz = cz + Math.sin(a2) * rr2; g.beginPath(); g.moveTo(dx, dz - 9); g.lineTo(dx + 5, dz); g.lineTo(dx, dz + 9); g.lineTo(dx - 5, dz); g.closePath(); g.fill(); }
        /* metallic-blue detail bands near the walls */ g.strokeStyle = 'rgba(70,120,190,0.35)'; g.lineWidth = 14; g.beginPath(); g.arc(cx, cz, 52 * k, 0, Math.PI * 2); g.stroke(); });
      var floor = new THREE.Mesh(new THREE.PlaneGeometry(size, size), new THREE.MeshStandardMaterial({ map: floorTex, color: 0xffffff, roughness: NIGHT ? 0.2 : 0.3, metalness: NIGHT ? 0.88 : 0.6 })); floor.rotation.x = -Math.PI / 2; group.add(floor);
      var grid = { visible: false };   /* the grid floor is gone (S09) */"""),
 # tree elevator + pods rendered from their colliders
 ("        if (s.type === 'CYLINDER') { var cyl = new THREE.Mesh(new THREE.CylinderGeometry(s.r, s.r * 1.15, s.h, 24), chrome);",
  "        if (s.landmark && s.landmark.kind === 'TREE_ELEVATOR') { city.treeElevator(s, shapes); return; }\n        if (s.pod) { city.pod(s); return; }\n        if (s.rim) return;   /* platform rims are invisible guards (the platform edge lip is drawn by treeElevator) */\n        if (s.walkable) return;   /* the walkable platform is drawn by the landmark */\n        if (s.type === 'CYLINDER') { var cyl = new THREE.Mesh(new THREE.CylinderGeometry(s.r, s.r * 1.15, s.h, 24), chrome);"),
])
# fieldScene.tick: move elevator pods
patch('fieldScene.js', [("    tick: function (dt, t) { var em = group.getObjectByName('MAH_EMBLEM'); if (em) { em.rotation.y += dt * 0.35; em.position.y = 9.5 + 0.25 * Math.sin(t * 0.7); } },",
  "    tick: function (dt, t) { var em = group.getObjectByName('MAH_EMBLEM'); if (em) { em.rotation.y += dt * 0.35; em.position.y = 9.5 + 0.25 * Math.sin(t * 0.7); } var tr = group.getObjectByName('TREE_ELEVATOR'); if (tr && tr.userData.pods) tr.userData.pods.forEach(function (pd, i) { var ph = (t * 0.12 + i * 0.5) % 1; var yy = 0.6 + (tr.userData.platformH - 1.2) * (0.5 - 0.5 * Math.cos(ph * Math.PI * 2)); pd.position.y = yy; pd.children[1].material.emissiveIntensity = 1.2 + 0.8 * Math.abs(Math.sin(ph * Math.PI * 2)); }); },")])

patch('cityScene.js', [
 ("    materials: M\n  };", """    /* TREE ELEVATOR (brief §33): a technological tree — chamfered platinum trunk, branching structural beams, diamond joints, cool luminous
       conduits, elevator pods on their shafts, an upper platform (the walkable collider) with a lit edge lip and a crystalline crown. */
    treeElevator: function (s, shapes) { var g = new THREE.Group(); g.name = 'TREE_ELEVATOR'; var L = s.landmark; var H = s.h, PH = L.platform_h || 9, PR = L.platform_r || 7.5;
      var trunk = new THREE.Mesh(new THREE.CylinderGeometry(s.r * 0.72, s.r, H, 24, 1), M.platinum); trunk.position.set(s.x, H / 2, s.z); g.add(trunk);
      var flare = new THREE.Mesh(new THREE.CylinderGeometry(s.r * 1.6, s.r * 2.3, 0.9, 32), M.chrome); flare.position.set(s.x, 0.45, s.z); g.add(flare);
      for (var c = 0; c < 4; c++) { var cond = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.07, H * 0.92, 6), M.trim); cond.position.set(s.x + Math.cos(c * Math.PI / 2) * s.r * 0.86, H * 0.5, s.z + Math.sin(c * Math.PI / 2) * s.r * 0.86); g.add(cond); }
      var nB = L.branches || 6; for (var b = 0; b < nB; b++) { var ang = b / nB * Math.PI * 2 + 0.3; var y0 = PH * 0.42 + (b % 2) * 1.4; var len = PR * 0.95; var beam = new THREE.Mesh(new THREE.CylinderGeometry(0.22, 0.34, len, 10), M.platinum); beam.position.set(s.x + Math.cos(ang) * len * 0.5, y0 + (PH - y0) * 0.5, s.z + Math.sin(ang) * len * 0.5); beam.lookAt(s.x + Math.cos(ang) * len, PH - 0.3, s.z + Math.sin(ang) * len); beam.rotateX(Math.PI / 2); g.add(beam);
        var joint = new THREE.Mesh(new THREE.OctahedronGeometry(0.42, 0), M.diamond); joint.scale.set(1, 1.5, 1); joint.position.set(s.x + Math.cos(ang) * len * 0.5, y0 + (PH - y0) * 0.5, s.z + Math.sin(ang) * len * 0.5); g.add(joint);
        var twig = new THREE.Mesh(new THREE.CylinderGeometry(0.1, 0.16, len * 0.55, 8), M.chrome); twig.position.set(s.x + Math.cos(ang + 0.5) * len * 0.62, PH * 0.78, s.z + Math.sin(ang + 0.5) * len * 0.62); twig.lookAt(s.x + Math.cos(ang + 0.5) * len * 0.98, PH - 0.2, s.z + Math.sin(ang + 0.5) * len * 0.98); twig.rotateX(Math.PI / 2); g.add(twig); }
      var plat = new THREE.Mesh(new THREE.CylinderGeometry(PR, PR * 0.94, 0.6, 48), M.platinum); plat.position.set(s.x, PH - 0.3, s.z); g.add(plat);
      var lip = new THREE.Mesh(new THREE.TorusGeometry(PR - 0.1, 0.09, 8, 64), M.trim); lip.rotation.x = Math.PI / 2; lip.position.set(s.x, PH + 0.02, s.z); g.add(lip);
      var rail = new THREE.Mesh(new THREE.TorusGeometry(PR - 0.35, 0.05, 8, 64), M.chrome); rail.rotation.x = Math.PI / 2; rail.position.set(s.x, PH + 1.0, s.z); g.add(rail);
      for (var p2 = 0; p2 < 24; p2++) { var pa = p2 / 24 * Math.PI * 2; var post = new THREE.Mesh(new THREE.CylinderGeometry(0.035, 0.035, 1.0, 6), M.chrome); post.position.set(s.x + Math.cos(pa) * (PR - 0.35), PH + 0.5, s.z + Math.sin(pa) * (PR - 0.35)); g.add(post); }
      var crown = new THREE.Mesh(new THREE.OctahedronGeometry(1.4, 0), M.diamond); crown.scale.set(1, 1.8, 1); crown.position.set(s.x, H + 2.4, s.z); g.add(crown); var halo = new THREE.Mesh(new THREE.TorusGeometry(2.6, 0.07, 8, 64), M.trim); halo.rotation.x = Math.PI / 2; halo.position.set(s.x, H + 1.2, s.z); g.add(halo);
      /* two shaft pods on the plaza side (the interactable side, -x) */ var pods = []; [-1, 1].forEach(function (sg, i) { var pod = new THREE.Group(); var shell = new THREE.Mesh(new THREE.CapsuleGeometry(0.55, 1.0, 6, 14), M.chrome); shell.position.y = 1.0; pod.add(shell); var glass = new THREE.Mesh(new THREE.CapsuleGeometry(0.4, 0.7, 6, 14), M.trimWarm.clone()); glass.material.transparent = true; glass.material.opacity = 0.55; glass.position.y = 1.0; pod.add(glass); pod.position.set(s.x - s.r - 1.1, 0.6, s.z + sg * 1.4); g.add(pod); pods.push(pod); var shaft = new THREE.Mesh(new THREE.CylinderGeometry(0.05, 0.05, PH, 6), M.trim); shaft.position.set(s.x - s.r - 1.1 - 0.7, PH / 2, s.z + sg * 1.4); g.add(shaft); });
      var mat2 = new THREE.Mesh(new THREE.CircleGeometry(2.4, 32), M.trimWarm.clone()); mat2.material.transparent = true; mat2.material.opacity = 0.18; mat2.rotation.x = -Math.PI / 2; mat2.position.set(s.x - s.r - 1.4, 0.02, s.z); g.add(mat2);
      var label = nameSprite(L.name || 'Tree Elevator'); label.position.set(s.x, H + 4.2, s.z); g.add(label); g.userData.pods = pods; g.userData.platformH = PH; group.add(g); return g; },
    /* residential pod: a rounded platinum shell with a luminous seam and a soft door light */
    pod: function (s) { var g = new THREE.Group(); var body = new THREE.Mesh(new THREE.SphereGeometry(s.r, 24, 16, 0, Math.PI * 2, 0, Math.PI * 0.55), M.platinum); body.scale.y = s.h / s.r * 0.75; body.position.set(s.x, 0, s.z); g.add(body); var seam = new THREE.Mesh(new THREE.TorusGeometry(s.r * 0.98, 0.05, 8, 40), M.trim); seam.rotation.x = Math.PI / 2; seam.position.set(s.x, s.h * 0.45, s.z); g.add(seam); var door = new THREE.Mesh(roundedBox(1.1, 2.0, 0.3, 0.4), M.doorway); door.position.set(s.x, 0, s.z + s.r - 0.1); g.add(door); var dm = new THREE.Mesh(new THREE.CircleGeometry(1.2, 24), M.trimWarm.clone()); dm.material.transparent = true; dm.material.opacity = 0.16; dm.rotation.x = -Math.PI / 2; dm.position.set(s.x, 0.02, s.z + s.r + 1.0); g.add(dm); group.add(g); return g; },
    materials: M
  };"""),
])
# dress(): extend the pathways to the tree + pods; skip the far ridge inside the bigger field (ridge distance stays 150+)
patch('cityScene.js', [("var entrances = [[-17, 0, -1, 0], [0, -19.5, 0, -1], [18, 0, 1, 0], [1, 20, 0, 1]];   /* x, z, dir x, dir z */",
  "var entrances = [[-17, 0, -1, 0], [0, -19.5, 0, -1], [18, 0, 1, 0], [1, 20, 0, 1]];   /* x, z, dir x, dir z */\n      /* secondary streets (S09 §32): plaza -> tree elevator (NE) and plaza -> residential pods (NW): lit kerbs + bollards on the diagonal */\n      [[30, 40, 21], [-30, 30, 19]].forEach(function (dst) { var ang = Math.atan2(dst[1], dst[0]); var L2 = Math.hypot(dst[0], dst[1]) - dst[2] - 4; var mid = 13 + L2 / 2; var cxp = Math.cos(ang) * mid, czp = Math.sin(ang) * mid; var path = new THREE.Mesh(new THREE.PlaneGeometry(L2, 2.6), M.trimWarm.clone()); path.material.transparent = true; path.material.opacity = 0.09; path.rotation.x = -Math.PI / 2; path.rotation.z = -ang; path.position.set(cxp, 0.012, czp); group.add(path); for (var k3 = 0; k3 < 5; k3++) { var t4 = 13 + (k3 + 0.5) / 5 * L2; [-1, 1].forEach(function (sg) { if (np >= 32) return; var qx = Math.cos(ang) * t4 - Math.sin(ang) * sg * 2.4, qz = Math.sin(ang) * t4 + Math.cos(ang) * sg * 2.4; pq.identity(); pm.compose(pv.set(qx, 0.55, qz), pq, ps.set(1, 1.1, 1)); pylons.setMatrixAt(np, pm); pq.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2); pm.compose(pv.set(qx, 1.15, qz), pq, ps.set(1, 1, 1)); rings.setMatrixAt(np, pm); np++; }); } });")])
# instanced pylon capacity 32 -> 56
patch('cityScene.js', [("var pylons = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.07, 0.1, 1, 8), M.chrome, 32); var rings = new THREE.InstancedMesh(new THREE.TorusGeometry(0.22, 0.035, 6, 20), M.trim, 32);", "var pylons = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.07, 0.1, 1, 8), M.chrome, 56); var rings = new THREE.InstancedMesh(new THREE.TorusGeometry(0.22, 0.035, 6, 20), M.trim, 56);"), ("[-1, 1].forEach(function (sg) { if (np >= 32) return; var qx = px + (dx ? 0 : sg * 2.7)", "[-1, 1].forEach(function (sg) { if (np >= 56) return; var qx = px + (dx ? 0 : sg * 2.7)")])
# secondary street bollards were declared before `np`... ensure ordering: the new block references pylons/np declared earlier — it is inserted after the `entrances` var (declared after pylons) — fine.
# field size 80 -> 112 in dev_tuning
p = os.path.join(HERE, '..', '..', '00_CORE', 'dev_tuning.dev.json'); t = json.load(open(p, encoding='utf-8')); t['local_authority']['play']['rooms']['FIELD']['size_m'] = 112; t['local_authority']['play']['rooms']['FIELD']['label'] = 'MAHWORLD SAMPLE CITY — plaza, four authored buildings, residential pods and the TREE ELEVATOR landmark (S09)'; json.dump(t, open(p, 'w', encoding='utf-8'), indent=1)
print('ok')
