/* MAHWORLD :: SAMPLE CITY DRESSING (presentation only; every solid it draws is one authoritative collider from the field layout)
   Building language: rounded / softened blocks, chromium + platinum, controlled glass bands, curved entrances, diamond accents, cool
   blue-white light — never a box with a pointed roof. Ground: premium chromium with restrained reflections and diamond inlays. Vegetation:
   laser-plant stalks with square-diamond leaves. All materials are shared and geometry is instanced or merged where it repeats, so a phone
   pays for a handful of draw calls per building. Lighting is a TEMPLATE meant to generalise to future character packages: one cool key,
   one hemisphere, an environment map for specular, emissive trims for local light (no per-lamp point lights). */
import { HALO_LAYOUT, HALO_PLAY_LAYOUT } from '../play/haloLayout.js';
import { mergeGeometries } from '../vendor/three/BufferGeometryUtils.js';
import { defaultTextureCap } from './texCap.js'; import { applySurface, applyCrystal } from './world/surfaceDetail.js'; import { createFacadeKit, profileFor, addCivicBuilding } from './world/facadeKit.js';
export function createCityScene(THREE, group, helpers) {
  var roundedBox = helpers.roundedBox, canvasTex = helpers.canvasTex; var DAY = helpers.night === false;
  var M = {
    /* JOB B palette (owner 2026-09-19 §4): PLATINUM facades (a mid-light cool grey with a restrained sky sheen — never white), CHROMIUM domes / trims, GRAPHITE recesses */
    platinum: new THREE.MeshStandardMaterial({ color: 0xb4bcc7, roughness: 0.42, metalness: 0.62, envMapIntensity: 0.6 }),   /* WORLD PIVOT PASS 3: satin anodised platinum panels (the mirror-metal facades read as flat sky reflections in daylight) */
    chrome: new THREE.MeshStandardMaterial({ color: 0xa4aeb9, roughness: (DAY ? 0.32 : 0.24), metalness: (DAY ? 0.92 : 0.98), envMapIntensity: (DAY ? 0.55 : 0.7) }),   /* M8: brushed, not a sky mirror, by day */
    dark: new THREE.MeshStandardMaterial({ color: 0x1d2229, roughness: 0.5, metalness: 0.75 }),
    glass: new THREE.MeshStandardMaterial({ color: 0x9aa6b8, roughness: 0.06, metalness: 0.55, transparent: true, opacity: 0.78, emissive: 0x1c2233, emissiveIntensity: (DAY ? 0.3 : 0.9), envMapIntensity: 1.0 }),   /* WORLD PIVOT PASS 3 + colour law: smoked neutral curtain-wall glass (was the civic cyan band) */
    trim: new THREE.MeshStandardMaterial({ color: 0xe6ecf6, emissive: 0xdfe8ff, emissiveIntensity: (DAY ? 0.45 : 1.7), roughness: 0.3, metalness: 0.2 }),   /* M8: daylight trims read by contrast, not by a white glow (was 0.95) */   /* B7 §7: the tier ledges / portholes read as recessed cyan energy seams */
    trimWarm: new THREE.MeshStandardMaterial({ color: 0xe9edf3, emissive: 0xdfeeff, emissiveIntensity: (DAY ? 0.3 : 1.2), roughness: 0.3, metalness: 0.1 }),
    diamond: new THREE.MeshStandardMaterial({ color: 0xe2e9f4, roughness: 0.05, metalness: 0.6, emissive: 0xd6e0ff, emissiveIntensity: (DAY ? 0.5 : 0.9), flatShading: true }),   /* B7 §7: the roof diamond is a cyan crystal, not a white cap */
    doorway: new THREE.MeshStandardMaterial({ color: 0x10141c, roughness: 0.9, metalness: 0.1, emissive: 0xd7dce8, emissiveIntensity: (DAY ? 0.32 : 0.7) }),   /* colour law: the doorway recess glows clean white light (was cyan) */
    stone: new THREE.MeshStandardMaterial({ color: 0x3a3f4a, roughness: 0.62, metalness: 0.28, envMapIntensity: 0.35 }),   /* WORLD PIVOT PASS 3: graphite stone plinths / roof plant */
    leaf: new THREE.MeshStandardMaterial({ color: 0xe4e9f2, emissive: 0xffc862, emissiveIntensity: (DAY ? 0.495 : 1.1), roughness: 0.3, metalness: 0.3, flatShading: true, side: THREE.DoubleSide }),
    stalk: new THREE.MeshStandardMaterial({ color: 0xe8edf5, emissive: 0xdfe8ff, emissiveIntensity: (DAY ? 0.405 : 0.9), roughness: 0.4, metalness: 0.2 }),
    puddle: new THREE.MeshStandardMaterial({ color: 0x1a2432, roughness: 0.02, metalness: 1.0, transparent: true, opacity: 0.85 }),
    /* M8E: wall families — a satin platinum skin, a neutral architectural composite, a honed stone cladding for heavy bases */
    skin: new THREE.MeshStandardMaterial({ color: 0xa3abb5, roughness: 0.46, metalness: 0.58, envMapIntensity: 0.55 }),
    composite: new THREE.MeshStandardMaterial({ color: 0xa7abb1, roughness: 0.6, metalness: 0.1, envMapIntensity: 0.4 }),
    cladding: new THREE.MeshStandardMaterial({ color: 0x5f6671, roughness: 0.68, metalness: 0.1, envMapIntensity: 0.35 })
  };
  /* M8 MATERIAL REALISM: the civic families get world-space structural surface logic (lab/world/surfaceDetail.js) — facade panel grid with
     inset seams and a trim band per 3.6 m storey, brushed chrome, panelled graphite structure, stone grain. Value / roughness only (no hue). */
  var SDT = helpers.surfaceTier || 'HIGH'; applySurface(THREE, M.platinum, 'FACADE', SDT); applySurface(THREE, M.chrome, 'BRUSHED', SDT); applySurface(THREE, M.dark, 'STRUCTURE', SDT); applySurface(THREE, M.stone, 'STONE', SDT); applySurface(THREE, M.glass, 'GLAZING', SDT); applyCrystal(THREE, M.diamond, { tier: SDT }); applySurface(THREE, M.skin, 'FACADE_PLAIN', SDT); applySurface(THREE, M.composite, 'COMPOSITE', SDT); applySurface(THREE, M.cladding, 'CLADDING', SDT);   /* M8C: roof / entrance diamonds are cut crystal (facets, depth, grazing rim) */
  /* M8E ARCHITECTURAL REALISM: one facade kit for every civic building (windows with rooms behind them, frames, bay piers, interrupted slab
     edges, service bays, corner glazing, a balcony, integrated light) — built once after the last building (dress), 4 draws in total */
  var SHOW = false; try { SHOW = typeof location !== 'undefined' && /[?&]show=1/.test(location.search); } catch (e) { }
  var kit = createFacadeKit(THREE, { tier: SDT, night: !DAY, show: SHOW }), kitBuilt = false;
  function skinsFor(prof, tiers) { var out = []; for (var i = 0; i < tiers; i++) out.push(prof === 'TOWER' ? (i === 0 ? M.cladding : (i === tiers - 1 ? M.composite : M.skin)) : (prof === 'HALL' ? (i === 0 ? M.composite : M.skin) : M.composite)); return out; }   /* heavy base · platinum body · composite crown */
  function nameSprite(text) { var tex = canvasTex(512, 96, function (g, w, h) { g.clearRect(0, 0, w, h); g.font = '600 46px "Segoe UI", Arial, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.shadowColor = '#f3e6c8'; g.shadowBlur = 18; g.fillStyle = '#f7f9ff'; g.fillText(text.toUpperCase(), w / 2, h / 2); }); var sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: tex, transparent: true, depthWrite: false, fog: false })); sp.scale.set(7.5, 1.4, 1); return sp; }
  function tier(cx, cz, w, d, y0, h, r, mat) { var m = new THREE.Mesh(roundedBox(w, h, d, r), mat); m.position.set(cx, y0, cz); return m; }   /* roundedBox is extruded from y0 upward (see fieldScene.roundedBox) */
  /* WORLD PIVOT PASS 3 (owner 2026-09-25: premium, believable architecture — structure first, light second). Every addition stays inside the
     collider footprint or above head height (≥ 3.4 m), so visuals and collision keep parity: a graphite plinth, thin floor cornices every
     3.6 m (readable human scale), a cantilevered entrance canopy with a white-light underside, and a roof-plant cluster (condensers, a
     tank, a mast with a white beacon, a tilted solar array). Merged per material: 2 extra draws per building. */
  function premiumDress(g, cx, cz, w, d, tiers, hEach, topY, B) {
    var stoneParts = [], trimParts = [], chromeParts = []; function rb(W, H, D, R, x, y, z) { var q = roundedBox(W, H, D, R); q.translate(x, y, z); return q; }
    stoneParts.push(rb(w + 0.1, 0.85, d + 0.1, Math.min(w, d) * 0.24, cx, 0, cz));   /* plinth */
    /* M8E: the all-around 3.6 m cornice rings are gone — the facade kit draws slab edges per bay, interrupted at every pier */
    if (B.entrance) { var e = B.entrance, horiz = e.side === '+z' || e.side === '-z', sx = e.side === '+x' ? 1 : e.side === '-x' ? -1 : 0, sz = e.side === '+z' ? 1 : e.side === '-z' ? -1 : 0, cy = e.height + 0.35, ow = e.width * 1.9, od = 2.3;
      stoneParts.push(rb(horiz ? ow : od, 0.22, horiz ? od : ow, 0.08, e.x + sx * (od / 2 - 0.2), cy, e.z + sz * (od / 2 - 0.2)));
      trimParts.push(rb(horiz ? ow - 0.3 : 0.1, 0.04, horiz ? 0.1 : ow - 0.3, 0.02, e.x + sx * (od - 0.35), cy - 0.03, e.z + sz * (od - 0.35))); }
    /* M8C CONSTRUCTION LANGUAGE (base / shaft / crown): graphite structural PIERS close every straight wall run (where the rounded corner
       begins), standing on the first-floor cornice (≥ 3.6 m) on the ground tier and on the tier ledge above it; a deep EAVE FASCIA under
       each tier's light reveal (the roofline has thickness); a louvred SERVICE BAY on the top storey's rear face (the plant needs air); a
       glazed TRANSOM over the entrance canopy with tension rods carrying the canopy back to the wall. Everything is ≥ 3.4 m above the
       ground (the host collider keeps the wall face), merged per material: +2 draws per building. */
    var frameParts = [], glazeParts = []; function bx(W, H, D, x, y, z) { var q = new THREE.BoxGeometry(W, H, D); q.translate(x, y + H / 2, z); return q; }   /* exact (unbevelled) box, base at y */
    for (var t3 = 0; t3 < tiers; t3++) { var k3 = 1 - t3 * 0.09, w3 = w * k3, d3 = d * k3, r3 = Math.min(w3, d3) * 0.24, y3 = t3 * hEach, pb = t3 ? y3 + 0.08 : 3.6, pt = y3 + hEach - 0.42;
      if (pt - pb > 1.2) [-1, 1].forEach(function (a) { [-1, 1].forEach(function (b) {
        frameParts.push(rb(0.16, pt - pb, 0.2, 0.04, cx + a * (w3 / 2 - r3), pb, cz + b * (d3 / 2 + 0.05)));
        frameParts.push(rb(0.2, pt - pb, 0.16, 0.04, cx + b * (w3 / 2 + 0.05), pb, cz + a * (d3 / 2 - r3))); }); });
      if (y3 + hEach - 0.4 >= 3.4) chromeParts.push(rb(w3 + 0.44, 0.24, d3 + 0.44, r3 + 0.22, cx, y3 + hEach - 0.4, cz)); }
    var kT = 1 - (tiers - 1) * 0.09, wT = w * kT, dT = d * kT, rT = Math.min(wT, dT) * 0.24, yT = (tiers - 1) * hEach, es = B.entrance ? B.entrance.side : '+z';
    var rear = { '+x': '-x', '-x': '+x', '+z': '-z', '-z': '+z' }[es] || '-z', rx = rear === '+x' ? 1 : rear === '-x' ? -1 : 0, rz = rear === '+z' ? 1 : rear === '-z' ? -1 : 0;
    var run = (rz ? wT : dT) - 2 * rT, LW = Math.min(4.2, run * 0.5), LH = 1.5, ly = yT + hEach * 0.74 - LH / 2, fx = cx + rx * (wT / 2), fz = cz + rz * (dT / 2);
    if (run > 2.4 && ly >= 3.4 && ly + LH < yT + hEach - 0.5) {
      frameParts.push(bx(rz ? LW + 0.24 : 0.12, LH + 0.24, rz ? 0.12 : LW + 0.24, fx + rx * 0.04, ly - 0.12, fz + rz * 0.04));   /* the louvre frame */
      for (var sl = 0; sl < 7; sl++) { var slat = new THREE.BoxGeometry(rz ? LW : 0.2, 0.04, rz ? 0.2 : LW); if (rz) slat.rotateX(-rz * 0.55); else slat.rotateZ(rx * 0.55); slat.translate(fx + rx * 0.14, ly + 0.14 + sl * (LH - 0.2) / 6, fz + rz * 0.14); chromeParts.push(slat); } }
    if (B.entrance) { var en = B.entrance, hz = en.side === '+z' || en.side === '-z', ex = en.side === '+x' ? 1 : en.side === '-x' ? -1 : 0, ez = en.side === '+z' ? 1 : en.side === '-z' ? -1 : 0, cY = en.height + 0.35, oW = en.width * 1.9, oD = 2.3;
      if (cY + 1.9 < hEach - 0.5) { var TW = en.width * 1.25, TH = 1.3, ty = cY + 0.42;
        glazeParts.push(bx(hz ? TW : 0.04, TH, hz ? 0.04 : TW, en.x + ex * 0.06, ty, en.z + ez * 0.06));
        [[0, -0.07, TW + 0.14], [TH, 0, TW + 0.14]].forEach(function (m) { frameParts.push(bx(hz ? m[2] : 0.12, 0.07, hz ? 0.12 : m[2], en.x + ex * 0.08, ty + m[0] + m[1], en.z + ez * 0.08)); });
        [-0.5, -1 / 6, 1 / 6, 0.5].forEach(function (u) { frameParts.push(bx(hz ? 0.07 : 0.12, TH, hz ? 0.12 : 0.07, en.x + (hz ? u * TW : ex * 0.08), ty, en.z + (hz ? ez * 0.08 : u * TW))); }); }
      var aY = Math.min(cY + 2.4, hEach - 0.5); if (aY > cY + 0.9) [-1, 1].forEach(function (sg) { var lat = sg * oW * 0.42, p0 = new THREE.Vector3(en.x + ex * (oD - 0.3) + (hz ? lat : 0), cY + 0.2, en.z + ez * (oD - 0.3) + (hz ? 0 : lat)), p1 = new THREE.Vector3(en.x + ex * 0.08 + (hz ? lat : 0), aY, en.z + ez * 0.08 + (hz ? 0 : lat));
        var dir = p1.clone().sub(p0), rod = new THREE.CylinderGeometry(0.035, 0.035, dir.length(), 6); rod.applyQuaternion(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 1, 0), dir.clone().normalize())); rod.translate((p0.x + p1.x) / 2, (p0.y + p1.y) / 2, (p0.z + p1.z) / 2); chromeParts.push(rod); }); }
    var k2 = 1 - tiers * 0.09, rw = w * k2 * 0.62, rd = d * k2 * 0.62, ry = topY + 0.5;   /* roof plant on the cap */
    for (var u = 0; u < 3; u++) stoneParts.push(rb(rw * 0.22, 0.9, rd * 0.18, 0.1, cx - rw * 0.3 + u * rw * 0.3, ry, cz - rd * 0.28));
    var tank = new THREE.CylinderGeometry(Math.min(rw, rd) * 0.12, Math.min(rw, rd) * 0.12, 1.6, 20); tank.translate(cx + rw * 0.28, ry + 0.8, cz + rd * 0.22); chromeParts.push(tank);
    var mast = new THREE.CylinderGeometry(0.05, 0.08, 4.2, 6); mast.translate(cx - rw * 0.32, ry + 2.1, cz + rd * 0.26); chromeParts.push(mast);
    var tip = new THREE.OctahedronGeometry(0.2, 0); tip.translate(cx - rw * 0.32, ry + 4.3, cz + rd * 0.26); trimParts.push(tip);
    for (var pnl = 0; pnl < 2; pnl++) { var pg = roundedBox(rw * 0.28, 0.06, rd * 0.34, 0.02); pg.rotateX(-0.35); pg.translate(cx - rw * 0.02 + pnl * rw * 0.3, ry + 0.55, cz + rd * 0.18); stoneParts.push(pg); }
    [[stoneParts, M.stone, 'PREMIUM_STONE'], [chromeParts, M.chrome, 'PREMIUM_CHROME'], [trimParts, M.trim, 'PREMIUM_LIGHT'], [frameParts, M.dark, 'PREMIUM_FRAME'], [glazeParts, M.glass, 'PREMIUM_GLAZE']].forEach(function (P) { if (!P[0].length) return; var mg = mergeGeometries(P[0].map(function (q) { return q.index ? q.toNonIndexed() : q; }), false); P[0].forEach(function (q) { q.dispose(); }); if (!mg) return; var mesh = new THREE.Mesh(mg, P[1]); mesh.name = (g.name || 'BUILDING') + '_' + P[2]; g.add(mesh); });
  }
  function diamond(x, y, z, s) { var o = new THREE.Mesh(new THREE.OctahedronGeometry(s, 0), M.diamond); o.position.set(x, y, z); o.scale.set(1, 1.6, 1); return o; }
  function entrance(bx, bz, e) {   /* e: {side:'+x'|'-x'|'+z'|'-z', x, z, width, height}: a curved recessed opening on that face, a light arch, a landing strip */
    var g = new THREE.Group(); var horiz = e.side === '+z' || e.side === '-z'; var sx = e.side === '+x' ? 1 : e.side === '-x' ? -1 : 0; var sz = e.side === '+z' ? 1 : e.side === '-z' ? -1 : 0;
    if (e.glazed) {   /* M8E: the flat door slab, leaves and light arch give way to the kit's storefront entrance; the lit lintel and the landing stay */
      var lint = new THREE.Mesh(roundedBox(horiz ? e.width * 1.15 : 0.3, 0.16, horiz ? 0.3 : e.width * 1.15, 0.05), M.trimWarm); lint.position.set(e.x + sx * 0.45, e.height * 0.98 + 0.34, e.z + sz * 0.45); if (e.height * 0.98 + 0.34 >= 3.4) g.add(lint);
      [1.2, 2.1].forEach(function (rr, i) { var ring = new THREE.Mesh(new THREE.RingGeometry(rr - 0.05, rr, 40), i ? M.trim : M.trimWarm); ring.rotation.x = -Math.PI / 2; ring.position.set(e.x + sx * 2.4, 0.03, e.z + sz * 2.4); g.add(ring); });
      /* M10 THRESHOLD (owner: entrances / thresholds / drainage-edge logic): a darker honed-stone APRON before the doors, a SLOT DRAIN across it
         just outside the threshold with brushed-metal edges — how a real entrance meets a plaza. Flush (≤ 2 cm), merged city-wide in dress(). */
      (function () { var W = e.width + 2.4, D = 3.2, tx = horiz ? 1 : 0, tz = horiz ? 0 : 1; function slab(along, out, lenA, lenO, h, list) { var bg = new THREE.BoxGeometry(tx ? lenA : lenO, h, tx ? lenO : lenA); bg.translate(e.x + sx * out + tx * along, h / 2, e.z + sz * out + tz * along); list.push(bg); }
        slab(0, 0.08 + D / 2, W, D, 0.012, THRESH.stone); slab(0, 0.72, W - 0.4, 0.16, 0.016, THRESH.drain); [-1, 1].forEach(function (sg) { slab(0, 0.72 + sg * 0.1, W - 0.4, 0.035, 0.018, THRESH.edge); });
        for (var gi = 0; gi < Math.floor((W - 0.6) / 0.09); gi++) slab(-(W - 0.6) / 2 + gi * 0.09 + 0.045, 0.72, 0.022, 0.15, 0.018, THRESH.edge); })();   /* the drain's grating bars */
      return g; }
    var depth = 0.9; var door = new THREE.Mesh(roundedBox(horiz ? e.width : depth, e.height, horiz ? depth : e.width, Math.min(e.width, e.height) * 0.42), M.doorway); door.position.set(e.x + sx * (depth / 2 - 0.35), 0, e.z + sz * (depth / 2 - 0.35)); g.add(door);
    var arch = new THREE.Mesh(new THREE.TorusGeometry(e.width * 0.52, 0.09, 8, 32, Math.PI), M.trim); arch.position.set(e.x + sx * 0.3, e.height * 0.62, e.z + sz * 0.3); if (!horiz) arch.rotation.y = Math.PI / 2; g.add(arch);
    /* door: two platinum leaves set into the recess with a vertical light seam, a lit lintel above, concentric landing rings on the ground */
    var leafW = e.width * 0.44, leafH = e.height * 0.86; [-1, 1].forEach(function (sg) { var leaf = new THREE.Mesh(roundedBox(horiz ? leafW : 0.12, leafH, horiz ? 0.12 : leafW, 0.14), M.platinum); leaf.position.set(e.x + (horiz ? sg * (leafW / 2 + 0.05) : sx * 0.12), 0.04, e.z + (horiz ? sz * 0.12 : sg * (leafW / 2 + 0.05))); g.add(leaf); });
    var seam = new THREE.Mesh(roundedBox(horiz ? 0.06 : 0.16, leafH * 0.9, horiz ? 0.16 : 0.06, 0.02), M.trim); seam.position.set(e.x + sx * 0.14, 0.08, e.z + sz * 0.14); g.add(seam);
    var lintel = new THREE.Mesh(roundedBox(horiz ? e.width * 1.15 : 0.3, 0.16, horiz ? 0.3 : e.width * 1.15, 0.05), M.trimWarm); lintel.position.set(e.x + sx * 0.45, e.height * 0.98, e.z + sz * 0.45); g.add(lintel);
    [1.2, 2.1].forEach(function (rr, i) { var ring = new THREE.Mesh(new THREE.RingGeometry(rr - 0.05, rr, 40), i ? M.trim : M.trimWarm); ring.rotation.x = -Math.PI / 2; ring.position.set(e.x + sx * 2.4, 0.03, e.z + sz * 2.4); g.add(ring); });
    var mat = new THREE.Mesh(new THREE.PlaneGeometry(horiz ? e.width * 1.1 : 4.5, horiz ? 4.5 : e.width * 1.1), M.trimWarm); mat.rotation.x = -Math.PI / 2; mat.position.set(e.x + sx * 2.4, 0.02, e.z + sz * 2.4); mat.material = M.trimWarm.clone(); mat.material.transparent = true; mat.material.opacity = 0.22; g.add(mat);
    return g;
  }
  var THRESH = { stone: [], drain: [], edge: [] };   /* M10: entrance aprons / slot drains, merged once in dress() */
  var api = {
    /* one authored building from its collider (BOX or CYLINDER) + `building` block */
    building: function (s) {
      var B = s.building; var g = new THREE.Group(); g.name = s.id; var cx, cz, w, d;
      if (s.type === 'CYLINDER') { cx = s.x; cz = s.z; w = d = s.r * 2; } else { cx = (s.x1 + s.x2) / 2; cz = (s.z1 + s.z2) / 2; w = s.x2 - s.x1; d = s.z2 - s.z1; }
      var tiers = Math.max(1, B.tiers || 1); var hEach = s.h / tiers; var y = 0;
      if (B.dome) {
        var base = new THREE.Mesh(new THREE.CylinderGeometry(s.r, s.r * 1.04, s.h * 0.55, 48), M.platinum); base.position.set(cx, s.h * 0.275, cz); g.add(base);
        var dome = new THREE.Mesh(new THREE.SphereGeometry(s.r * 0.98, 48, 24, 0, Math.PI * 2, 0, Math.PI / 2), M.chrome); dome.scale.y = (s.h * 0.45) / (s.r * 0.98); dome.position.set(cx, s.h * 0.55, cz); g.add(dome);
        var ring1 = new THREE.Mesh(new THREE.TorusGeometry(s.r * 1.0, 0.1, 8, 64), M.trim); ring1.rotation.x = Math.PI / 2; ring1.position.set(cx, s.h * 0.55, cz); g.add(ring1);
        g.add(diamond(cx, s.h + 1.1, cz, 0.9));
      } else {
        var PROF = profileFor(s.id, tiers), skins = skinsFor(PROF, tiers);
        for (var i = 0; i < tiers; i++) { var k = 1 - i * 0.09; var tw = w * k, td = d * k; var r = Math.min(tw, td) * 0.24; g.add(tier(cx, cz, tw, td, y, hEach, r, skins[i])); y += hEach; }   /* M8E: base / body / crown wall families; the continuous glass band + light ring are gone (real windows + interrupted strips instead) */
        var cap = new THREE.Mesh(roundedBox(w * (1 - tiers * 0.09) * 0.7, 0.5, d * (1 - tiers * 0.09) * 0.7, Math.min(w, d) * 0.2), M.chrome); cap.position.set(cx, y, cz); g.add(cap);
        g.add(diamond(cx, y + 1.4, cz, 0.7));
      }
      /* M8E: the uniform chrome fins, the dark inset strips, the glowing tier-base rings and the portholes are replaced by the facade kit:
         bays of varied width between piers, framed windows per floor (rooms behind the glass), interrupted slab edges, service bays, corner
         glazing and a balcony on towers, integrated light strips */
      addCivicBuilding(kit, THREE, s);   /* M8E: windows, frames, piers, slab edges, service bays, corner glazing, balcony, storefront entrance, light (lab/world/facadeKit.js) */
      if (B.entrance) g.add(entrance(cx, cz, Object.assign({}, B.entrance, { glazed: true })));   /* M8E: lintel + landing; the kit draws the storefront */
      if (!B.dome) premiumDress(g, cx, cz, w, d, tiers, hEach, y, B);
      var label = nameSprite(B.name || s.id); label.position.set(B.entrance ? B.entrance.x : cx, (B.entrance ? B.entrance.height : 4) + 1.6, B.entrance ? B.entrance.z : cz); g.add(label);
      group.add(g); return g;
    },
    /* ground and dressing: chrome floor with diamond inlays, puddle accents, laser plants; nothing blocks movement */
    dress: function (size) {
      if (!kitBuilt) { kitBuilt = true; try { kit.build(group); } catch (e) { if (helpers.log) helpers.log('facade kit failed: ' + (e && e.message || e)); } }
      if (THRESH.stone.length) { var tStone = M.cladding.clone(); tStone.color.setHex(0x4c525c); tStone.roughness = 0.58; tStone.polygonOffset = true; tStone.polygonOffsetFactor = -1; var tDrain = new THREE.MeshStandardMaterial({ color: 0x101318, roughness: 0.85, metalness: 0.2 });
        [[THRESH.stone, tStone, 'CITY_ENTRANCE_APRONS'], [THRESH.drain, tDrain, 'CITY_SLOT_DRAINS'], [THRESH.edge, M.chrome, 'CITY_DRAIN_EDGES']].filter(function (T) { if (SDT === 'LOW' && T[2] === 'CITY_DRAIN_EDGES') { T[0].forEach(function (q) { q.dispose(); }); return false; } return true; }).forEach(function (T) { var mg = mergeGeometries(T[0].map(function (q) { return q.toNonIndexed(); }), false); T[0].forEach(function (q) { q.dispose(); }); var mm = new THREE.Mesh(mg, T[1]); mm.name = T[2]; mm.userData.noMerge = true; mm.receiveShadow = true; group.add(mm); }); THRESH.stone = []; THRESH.drain = []; THRESH.edge = []; }
      var seed = 9; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }
      /* diamond inlays: thin flat octahedra in a ring around the plaza */
      var inlay = new THREE.InstancedMesh(new THREE.OctahedronGeometry(0.55, 0), new THREE.MeshStandardMaterial({ color: 0xe8f4ff, roughness: 0.1, metalness: 0.9, emissive: 0x3a86c8, emissiveIntensity: 0.35, flatShading: true }), 24); var mtx = new THREE.Matrix4(); var q = new THREE.Quaternion(); var sc = new THREE.Vector3(1, 0.06, 1);
      for (var i = 0; i < 24; i++) { var a = i / 24 * Math.PI * 2; var rr = 11.5 + (i % 2) * 1.2; q.setFromAxisAngle(new THREE.Vector3(0, 1, 0), a); mtx.compose(new THREE.Vector3(Math.cos(a) * rr, 0.03, Math.sin(a) * rr), q, sc); inlay.setMatrixAt(i, mtx); } inlay.instanceMatrix.needsUpdate = true; group.add(inlay);
      /* JOB B PLAZA CLEANUP (owner directive 2026-09-19 §5 — registry zone PLAZA_CLEAR): the central plaza keeps its lanes, forecourts and landing
         clearance; the decorative puddles and laser-plant clusters move out of the axis lanes / forecourts to the plaza's south perimeter beds (r ≈ 44–50 m,
         away from the tree elevator (30, 40) and the pods (−30, 26)). Landmarks, pathways, pylons and the emblem stay. Nothing here blocks movement. */
      /* puddles: three flat mirror accents at the south forecourt corners (out of every lane) */
      [[-31, -31, 2.0], [31, -31, 1.8], [-45, -20, 1.5]].forEach(function (p) { var pd = new THREE.Mesh(new THREE.CircleGeometry(p[2], 24), M.puddle); pd.rotation.x = -Math.PI / 2; pd.position.set(p[0], 0.015, p[1]); pd.scale.x = 1.35; group.add(pd); });
      /* laser plants: instanced stalks + square-diamond leaves in clusters near the buildings' flanks */
      var spots = [[-40, -38], [40, -38], [-47, -9], [47, -9], [-14, -48], [14, -48], [-28, -46], [28, -46], [-48, 8], [48, 8], [-44, -26], [44, -26]];   /* perimeter planting beds (south half + flanks), was: 12 clusters inside r 27 m of the plaza centre */
      var stalks = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.03, 0.05, 1, 5), M.stalk, spots.length * 5); var leaves = new THREE.InstancedMesh(new THREE.PlaneGeometry(0.42, 0.42), M.leaf, spots.length * 5 * 3); var n1 = 0, n2 = 0; var v = new THREE.Vector3();
      spots.forEach(function (sp) { for (var k = 0; k < 5; k++) { var x = sp[0] + (rnd() - 0.5) * 2.2, z = sp[1] + (rnd() - 0.5) * 2.2; var h = 1.1 + rnd() * 1.5; var tilt = (rnd() - 0.5) * 0.35; q.setFromEuler(new THREE.Euler(tilt, rnd() * 6.28, (rnd() - 0.5) * 0.35)); mtx.compose(v.set(x, h / 2, z), q, new THREE.Vector3(1, h, 1)); stalks.setMatrixAt(n1++, mtx);
        for (var l = 0; l < 3; l++) { var ly = h * (0.45 + l * 0.22); q.setFromEuler(new THREE.Euler(0.2, rnd() * 6.28, Math.PI / 4)); mtx.compose(v.set(x + (rnd() - 0.5) * 0.3, ly, z + (rnd() - 0.5) * 0.3), q, new THREE.Vector3(1 - l * 0.2, 1 - l * 0.2, 1)); leaves.setMatrixAt(n2++, mtx); } } });
      stalks.instanceMatrix.needsUpdate = true; leaves.instanceMatrix.needsUpdate = true; group.add(stalks); group.add(leaves);
      /* MOTION PRECISION PASS I — readable pathways: low light strips from the plaza ring to each entrance, lit kerbs, light pylons at
         intervals (instanced), and the MAHWORLD emblem over the plaza centre. Presentation only: nothing here blocks movement. */
      var entrances = [[-17, 0, -1, 0], [0, -19.5, 0, -1], [18, 0, 1, 0], [1, 20, 0, 1]];   /* x, z, dir x, dir z */
      var pylons = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.07, 0.1, 1, 8), M.chrome, 56); var rings = new THREE.InstancedMesh(new THREE.TorusGeometry(0.22, 0.035, 6, 20), M.trim, 56); var np = 0; var pm = new THREE.Matrix4(), pq = new THREE.Quaternion(), pv = new THREE.Vector3(), ps = new THREE.Vector3();
      entrances.forEach(function (en) { var ex = en[0], ez = en[1], dx = en[2], dz = en[3]; var start = 12.5, len = Math.hypot(ex, ez) - start - 2.6; if (len < 2) return; var cxp = ex - dx * (start + len / 2 + 2.6) * 0 + (-dx) * (len / 2 + 2.6) , czp = ez + (-dz) * (len / 2 + 2.6);
        var path = new THREE.Mesh(new THREE.PlaneGeometry(dx ? len : 2.4, dx ? 2.4 : len), M.trimWarm.clone()); path.material.transparent = true; path.material.opacity = 0.10; path.rotation.x = -Math.PI / 2; path.position.set(cxp, 0.012, czp); group.add(path);
        [-1, 1].forEach(function (sg) { var kerb = new THREE.Mesh(new THREE.PlaneGeometry(dx ? len : 0.08, dx ? 0.08 : len), M.trim); kerb.rotation.x = -Math.PI / 2; kerb.position.set(cxp + (dx ? 0 : sg * 1.3), 0.02, czp + (dx ? sg * 1.3 : 0)); group.add(kerb); });
        for (var k2 = 0; k2 < 4; k2++) { var t3 = (k2 + 0.5) / 4; var px = cxp + (dx ? (t3 - 0.5) * len : 0), pz = czp + (dx ? 0 : (t3 - 0.5) * len); [-1, 1].forEach(function (sg) { if (np >= 56) return; var qx = px + (dx ? 0 : sg * 2.7), qz = pz + (dx ? sg * 2.7 : 0); pq.identity(); pm.compose(pv.set(qx, 0.55, qz), pq, ps.set(1, 1.1, 1)); pylons.setMatrixAt(np, pm); pq.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2); pm.compose(pv.set(qx, 1.15, qz), pq, ps.set(1, 1, 1)); rings.setMatrixAt(np, pm); np++;   /* bollard lights at the kerb edge: short, off the walking line */ }); } });
      /* secondary streets (S09 §32): plaza -> tree elevator (NE) and plaza -> residential pods (NW): lit kerbs + bollards on the diagonal */
      [[30, 40, 21], [-30, 30, 19]].forEach(function (dst) { var ang = Math.atan2(dst[1], dst[0]); var L2 = Math.hypot(dst[0], dst[1]) - dst[2] - 4; var mid = 13 + L2 / 2; var cxp = Math.cos(ang) * mid, czp = Math.sin(ang) * mid; var path = new THREE.Mesh(new THREE.PlaneGeometry(L2, 2.6), M.trimWarm.clone()); path.material.transparent = true; path.material.opacity = 0.09; path.rotation.x = -Math.PI / 2; path.rotation.z = -ang; path.position.set(cxp, 0.012, czp); group.add(path); for (var k3 = 0; k3 < 5; k3++) { var t4 = 13 + (k3 + 0.5) / 5 * L2; [-1, 1].forEach(function (sg) { if (np >= 32) return; var qx = Math.cos(ang) * t4 - Math.sin(ang) * sg * 2.4, qz = Math.sin(ang) * t4 + Math.cos(ang) * sg * 2.4; pq.identity(); pm.compose(pv.set(qx, 0.55, qz), pq, ps.set(1, 1.1, 1)); pylons.setMatrixAt(np, pm); pq.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2); pm.compose(pv.set(qx, 1.15, qz), pq, ps.set(1, 1, 1)); rings.setMatrixAt(np, pm); np++; }); } });
      pylons.count = np; rings.count = np; pylons.instanceMatrix.needsUpdate = true; rings.instanceMatrix.needsUpdate = true; group.add(pylons); group.add(rings);
      var emblem = new THREE.Group(); var oct = new THREE.Mesh(new THREE.OctahedronGeometry(1.1, 0), M.diamond); oct.scale.set(1, 1.7, 1); emblem.add(oct); var halo = new THREE.Mesh(new THREE.TorusGeometry(1.9, 0.05, 8, 48), M.trim); halo.rotation.x = Math.PI / 2; emblem.add(halo); emblem.position.set(0, 9.5, 0); emblem.name = 'MAH_EMBLEM'; group.add(emblem); var lbl = nameSprite('MAHWORLD PLAZA'); lbl.position.set(0, 12.2, 0); group.add(lbl); api.emblem = emblem;
      /* The old 26-cone ridge was the actual owner of the enormous blue planar shard in the M7 owner view: on the district build its
         34–94 m seven-sided cones were merged before the registry macro/far-world layers loaded.  Keep the bounded fallback for the small
         standalone field, but do not stack it behind the full world where macro.js + farWorld.js already own the unreachable horizon. */
      var ridge = new THREE.MeshStandardMaterial({ color: DAY ? 0x6f8196 : 0x9aa6b4, roughness: DAY ? 0.85 : 0.55, metalness: DAY ? 0.35 : 0.75, flatShading: true }); var mg = new THREE.Group(); mg.name = 'MAHWORLD_LEGACY_HORIZON_RIDGE';
      var ringR = (helpers && helpers.horizonRadius) || 150; if (ringR <= 200) { for (var m = 0; m < 26; m++) { var ang = m / 26 * Math.PI * 2 + rnd() * 0.15; var dist = ringR + rnd() * 60; var hh = 22 + rnd() * 40; var cone = new THREE.Mesh(new THREE.ConeGeometry(18 + rnd() * 22, hh, 12), ridge); cone.position.set(Math.cos(ang) * dist, hh / 2 - 6, Math.sin(ang) * dist); cone.rotation.y = rnd() * 3; cone.scale.set(1, 0.7, 1.35); mg.add(cone); } group.add(mg); api.legacyRidge = 'SMALL_FIELD_FALLBACK'; } else api.legacyRidge = 'SUPPRESSED_FULL_WORLD';
    },
    /* M7 HALO SCALE/ACCESS — re-authored at the single canonical 10× arrival / 18× dome result.  The city, base, actors and furniture stay
       human scale; only the vertical civic trunk, structural deck and enclosed upper realm use the authorised dimensions. */
    treeElevator: function (s, shapes) { var g = new THREE.Group(); g.name = 'TREE_ELEVATOR'; g.userData.noMerge = true; var PH = HALO_LAYOUT.arrival_height_m, PR = HALO_LAYOUT.structural_deck_radius_m, DR = HALO_LAYOUT.shell_radius_m; var FAMS_RIM = ['#e6c36a', '#f08ab8', '#8f6ad8', '#3f78e8', '#d4344a'];   /* M10: the deck's sector order (gold · pink · purple · blue · red), for the rim planting */
      var glassCore = M.glass.clone(); glassCore.color.setHex(0xd4def0); glassCore.opacity = DAY ? 0.16 : 0.24; glassCore.depthWrite = false; glassCore.side = THREE.DoubleSide; glassCore.emissiveIntensity = DAY ? 0.24 : 0.48;
      var darkGlass = M.doorway.clone(); darkGlass.transparent = true; darkGlass.opacity = 0.82;
      var floorMat = M.platinum.clone(); floorMat.roughness = 0.32; floorMat.metalness = 0.92; floorMat.envMapIntensity = 0.72;
      function tube(points, radius, mat, tubular, radial) { var curve = new THREE.CatmullRomCurve3(points); var mesh = new THREE.Mesh(new THREE.TubeGeometry(curve, tubular || 40, radius, radial || 10, false), mat); g.add(mesh); return mesh; }
      function gradientRing(inner, outer, y, stops, opacity) { var seg = 128, pos = [], col = [], ind = []; for (var i = 0; i <= seg; i++) { var t = i / seg, a = t * Math.PI * 2, f = t * stops.length, si = Math.min(stops.length - 1, Math.floor(f)), sj = (si + 1) % stops.length, u = f - Math.floor(f), sm = u * u * (3 - 2 * u), c0 = new THREE.Color(stops[si]), c1 = new THREE.Color(stops[sj]), cc = c0.clone().lerp(c1, sm); [inner, outer].forEach(function (r) { pos.push(s.x + Math.cos(a) * r, y, s.z + Math.sin(a) * r); col.push(cc.r, cc.g, cc.b); }); if (i < seg) { var k = i * 2; ind.push(k, k + 1, k + 2, k + 1, k + 3, k + 2); } } var geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); geo.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); geo.setIndex(ind); var mat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.28, metalness: 0.68, emissive: 0x111827, emissiveIntensity: DAY ? 0.12 : 0.28, transparent: opacity < 1, opacity: opacity, side: THREE.DoubleSide }); var mesh = new THREE.Mesh(geo, mat); g.add(mesh); return mesh; }
      function gradientSpoke(angle, inner, outer, width, y, c0, c1) { var seg = 40, pos = [], col = [], ind = [], ax = Math.cos(angle), az = Math.sin(angle), sx = -az, sz = ax, A = new THREE.Color(c0), B = new THREE.Color(c1); for (var i = 0; i <= seg; i++) { var t = i / seg, sm = t * t * (3 - 2 * t), r = inner + (outer - inner) * t, cc = A.clone().lerp(B, sm); [-1, 1].forEach(function (side) { pos.push(s.x + ax * r + sx * width * side, y, s.z + az * r + sz * width * side); col.push(cc.r, cc.g, cc.b); }); if (i < seg) { var k = i * 2; ind.push(k, k + 1, k + 2, k + 1, k + 3, k + 2); } } var geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); geo.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); geo.setIndex(ind); var mat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.3, metalness: 0.72, emissive: 0x141827, emissiveIntensity: DAY ? 0.14 : 0.32, transparent: true, opacity: DAY ? 0.48 : 0.62, side: THREE.DoubleSide }); var mesh = new THREE.Mesh(geo, mat); g.add(mesh); return mesh; }
      /* WORLD PIVOT PASS 4 (owner 2026-09-25: the HALO is a signature landmark, not an empty dome). The deck is ONE opaque top to the
         glass sky-walk (GLASS_IN): a plan-drawn canvas pattern in the circular-platform language — satin platinum stone, concentric paving
         seams, luminous white inlay rings, five class sectors deepening toward the rim, a segmented light-ring medallion at the elevator
         arrival — with a matching emissive map for the inlays. Texture size follows the tier cap (1024 on phones). */
      var GLASS_IN = 128;
      function deckTextures(R) { var cap = (function () { try { var tc = defaultTextureCap(); return tc ? tc.maxEdge() : 2048; } catch (e) { return 2048; } })(); var N = Math.min(2048, cap || 2048); var k = N / (2 * R);
        function canvas() { var c = document.createElement('canvas'); c.width = c.height = N; return c; } var cc = canvas(), ce = canvas(), g2 = cc.getContext('2d'), ge = ce.getContext('2d'); var C0 = N / 2;
        var FAMS = ['#e6c36a', '#f08ab8', '#8f6ad8', '#3f78e8', '#d4344a'];   /* gold · pink · purple · blue · red around the deck (colour law) */
        var bg = g2.createRadialGradient(C0, C0, 0, C0, C0, C0); bg.addColorStop(0, DAY ? '#aab0ba' : '#2c3140'); bg.addColorStop(0.7, DAY ? '#98a0ab' : '#232835'); bg.addColorStop(1, DAY ? '#858d9a' : '#1b1f2a');   /* PASS 2b: a mid-value satin stone by day so the white inlays and class sectors carry (was near-white under the 3.0 key) */ g2.fillStyle = bg; g2.fillRect(0, 0, N, N); ge.fillStyle = '#000'; ge.fillRect(0, 0, N, N);
        for (var sct = 0; sct < 5; sct++) { var a0 = sct / 5 * Math.PI * 2 + 0.22, a1 = a0 + Math.PI * 2 / 5; var gr = g2.createRadialGradient(C0, C0, R * 0.2 * k, C0, C0, R * k); gr.addColorStop(0, 'rgba(0,0,0,0)'); gr.addColorStop(1, FAMS[sct] + '66'); g2.fillStyle = gr; g2.beginPath(); g2.moveTo(C0, C0); g2.arc(C0, C0, R * k, a0, a1); g2.closePath(); g2.fill(); }
        for (var band2 = 0; band2 < R; band2 += 12) { g2.fillStyle = (band2 / 12) % 2 ? (DAY ? 'rgba(255,255,255,0.09)' : 'rgba(255,255,255,0.03)') : (DAY ? 'rgba(20,26,40,0.09)' : 'rgba(0,0,0,0.08)'); g2.beginPath(); g2.arc(C0, C0, Math.min(R, band2 + 12) * k, 0, Math.PI * 2); g2.arc(C0, C0, band2 * k, 0, Math.PI * 2, true); g2.fill(); }   /* alternating stone bands */
        g2.lineWidth = Math.max(1, 0.1 * k); g2.strokeStyle = DAY ? 'rgba(52,60,78,0.18)' : 'rgba(140,150,190,0.14)'; for (var rr = 6; rr < R; rr += 6) { g2.beginPath(); g2.arc(C0, C0, rr * k, 0, Math.PI * 2); g2.stroke(); }   /* paving seams */
        for (var sp = 0; sp < 40; sp++) { var sa = sp / 40 * Math.PI * 2 + 0.22; g2.beginPath(); g2.moveTo(C0 + Math.cos(sa) * 18 * k, C0 + Math.sin(sa) * 18 * k); g2.lineTo(C0 + Math.cos(sa) * R * k, C0 + Math.sin(sa) * R * k); g2.stroke(); }
        /* M9 HALO ZONES (owner: a signature location, not an empty plate; everything flush — nothing may stand on the walkable deck without a
           collider): a PROMENADE of darker honed stone slabs with curbs just inside the glass sky-walk, and five GARDEN TERRACES — one planting
           bed per class sector (dark soil, fine crystal glints in the sector's class colour that glow faintly at night) inside a platinum curb,
           the class spokes kept clear as paths. Drawn into the deck's plan texture: no geometry, no draw. */
        (function () { var rnd = (function (sd) { return function () { sd = (sd * 16807) % 2147483647; return sd / 2147483647; }; })(90210);
          g2.fillStyle = DAY ? 'rgba(52,58,72,0.30)' : 'rgba(10,12,20,0.35)'; g2.beginPath(); g2.arc(C0, C0, 126 * k, 0, Math.PI * 2); g2.arc(C0, C0, 108 * k, 0, Math.PI * 2, true); g2.fill();   /* promenade band */
          g2.lineWidth = Math.max(1, 0.08 * k); g2.strokeStyle = DAY ? 'rgba(30,36,50,0.35)' : 'rgba(150,160,200,0.18)'; for (var pr = 111; pr < 126; pr += 3) { g2.beginPath(); g2.arc(C0, C0, pr * k, 0, Math.PI * 2); g2.stroke(); }
          for (var pj = 0; pj < 300; pj++) { var pa = pj / 300 * Math.PI * 2, off = (pj % 2) * 1.5; g2.beginPath(); g2.moveTo(C0 + Math.cos(pa) * (108 + off) * k, C0 + Math.sin(pa) * (108 + off) * k); g2.lineTo(C0 + Math.cos(pa) * 126 * k, C0 + Math.sin(pa) * 126 * k); g2.stroke(); }   /* staggered radial slab joints */
          [108, 126].forEach(function (cr) { g2.lineWidth = 0.35 * k; g2.strokeStyle = DAY ? 'rgba(236,240,248,0.85)' : 'rgba(200,210,235,0.5)'; g2.beginPath(); g2.arc(C0, C0, cr * k, 0, Math.PI * 2); g2.stroke(); });   /* curbs */
          for (var sct2 = 0; sct2 < 5; sct2++) { var a0 = sct2 / 5 * Math.PI * 2 + 0.22, a1 = a0 + Math.PI * 2 / 5, am = (a0 + a1) / 2, famC = FAMS[sct2];
            var ra = 75, rb = 93, half = 0.34;   /* between the 72 m and 96 m inlay rings */   /* an ARC terrace bed: an annular sector between the spokes, with rounded ends (the deck's circular language) */
            function P(r, a) { return [C0 + Math.cos(a) * r * k, C0 + Math.sin(a) * r * k]; }
            g2.beginPath(); var q0 = P(rb, am - half); g2.moveTo(q0[0], q0[1]); g2.arc(C0, C0, rb * k, am - half, am + half); var ec = P((ra + rb) / 2, am + half); g2.arc(ec[0], ec[1], (rb - ra) / 2 * k, am + half, am + half + Math.PI); g2.arc(C0, C0, ra * k, am + half, am - half, true); var sc2 = P((ra + rb) / 2, am - half); g2.arc(sc2[0], sc2[1], (rb - ra) / 2 * k, am - half + Math.PI, am - half); g2.closePath();
            g2.fillStyle = DAY ? '#4a4c52' : '#15161c'; g2.fill(); g2.lineWidth = 0.45 * k; g2.strokeStyle = DAY ? 'rgba(232,236,244,0.95)' : 'rgba(190,200,230,0.6)'; g2.stroke();   /* the bed and its platinum curb */
            g2.lineWidth = 0.18 * k; g2.strokeStyle = DAY ? 'rgba(232,236,244,0.55)' : 'rgba(190,200,230,0.3)'; [0.33, 0.66].forEach(function (f2) { g2.beginPath(); g2.arc(C0, C0, (ra + (rb - ra) * f2) * k, am - half, am + half); g2.stroke(); });   /* stepping-stone paths through the bed */
            for (var gl = 0; gl < 1400; gl++) { var rr3 = ra + 1 + rnd() * (rb - ra - 2), aa3 = am - half + rnd() * half * 2, gp = P(rr3, aa3), gs = (0.12 + rnd() * 0.22) * k;   /* crystal glints scattered through the bed */
              g2.fillStyle = famC; g2.globalAlpha = 0.55 + rnd() * 0.4; g2.fillRect(gp[0] - gs / 2, gp[1] - gs / 2, gs, gs); if (rnd() < 0.35) { ge.fillStyle = famC; ge.globalAlpha = 0.35; ge.fillRect(gp[0] - gs / 2, gp[1] - gs / 2, gs, gs); } }
            g2.globalAlpha = 1; ge.globalAlpha = 1; }
        })();
        [24, 48, 72, 96, 120].forEach(function (ir, ii) { ge.lineWidth = g2.lineWidth = (ii === 4 ? 0.9 : 0.55) * k; ge.strokeStyle = 'rgba(255,255,255,0.95)'; g2.strokeStyle = DAY ? 'rgba(250,251,255,0.95)' : 'rgba(220,226,255,0.9)'; [g2, ge].forEach(function (ctx2) { ctx2.beginPath(); ctx2.arc(C0, C0, ir * k, 0, Math.PI * 2); ctx2.stroke(); }); });   /* luminous white inlay rings */
        for (var sb = 0; sb < 5; sb++) { var ba = sb / 5 * Math.PI * 2 + 0.22; [g2, ge].forEach(function (ctx2) { ctx2.strokeStyle = FAMS[sb]; ctx2.lineWidth = 0.35 * k; ctx2.beginPath(); ctx2.moveTo(C0 + Math.cos(ba) * 24 * k, C0 + Math.sin(ba) * 24 * k); ctx2.lineTo(C0 + Math.cos(ba) * R * k, C0 + Math.sin(ba) * R * k); ctx2.stroke(); }); }   /* the five class spokes */
        var ax = (HALO_LAYOUT.upper_dock.x - s.x) * k + C0, az = (HALO_LAYOUT.upper_dock.z - s.z) * k + C0;   /* arrival medallion: segmented light ring (reference 3) */
        for (var seg2 = 0; seg2 < 30; seg2++) { var q0 = seg2 / 30 * Math.PI * 2, q1 = q0 + Math.PI * 2 / 30 * 0.72, colr = seg2 % 3 === 0 ? FAMS[(seg2 / 3) % 5] : '#ffffff'; [g2, ge].forEach(function (ctx2) { ctx2.strokeStyle = colr; ctx2.lineWidth = 0.7 * k; ctx2.beginPath(); ctx2.arc(ax, az, 9 * k, q0, q1); ctx2.stroke(); }); }
        [g2, ge].forEach(function (ctx2) { ctx2.strokeStyle = 'rgba(255,255,255,0.9)'; ctx2.lineWidth = 0.22 * k; [5.5, 12].forEach(function (mr) { ctx2.beginPath(); ctx2.arc(ax, az, mr * k, 0, Math.PI * 2); ctx2.stroke(); }); });
        var tMap = new THREE.CanvasTexture(cc), tGlow = new THREE.CanvasTexture(ce); [tMap, tGlow].forEach(function (t) { t.colorSpace = THREE.SRGBColorSpace; t.anisotropy = 8; t.generateMipmaps = true; t.minFilter = THREE.LinearMipmapLinearFilter; }); return { map: tMap, glow: tGlow }; }
      function deckSurface(radius, y) { var T = deckTextures(radius); var geo = new THREE.CircleGeometry(radius, 192); geo.rotateX(-Math.PI / 2); geo.translate(s.x, y, s.z);
        var mat = new THREE.MeshStandardMaterial({ map: T.map, emissiveMap: T.glow, emissive: 0xffffff, emissiveIntensity: DAY ? 0.42 : 0.95, roughness: DAY ? 0.6 : 0.36, metalness: DAY ? 0.18 : 0.45, envMapIntensity: DAY ? 0.42 : 0.6 });   /* M10: honed, less metallic by day — the Sun no longer washes the eye-level deck white */ applySurface(THREE, mat, 'DECK', SDT);   /* M8: honed deck stone with a 3 m slab grid under the plan-drawn rings */ var mesh = new THREE.Mesh(geo, mat); mesh.name = 'HALO_DECK_SINGLE_TOP'; mesh.userData.noMerge = true; g.add(mesh); return mesh; }
      /* the glass SKY-WALK: the deck annulus GLASS_IN..PR is glass (a separate area owner, never an overlay), so the rim — 16.8 m of it inside
         the playable radius — looks straight down 240 m over MAHWORLD; a merged platinum mullion grid carries it, a glass balustrade marks
         the playable edge. The underside disc stops at GLASS_IN, and the boughs below stay visible through the glass. */
      function glassSkywalk(rIn, rOut, y) { var gg = new THREE.RingGeometry(rIn, rOut, 192, 1); gg.rotateX(-Math.PI / 2); gg.translate(s.x, y, s.z);
        var gm = new THREE.MeshStandardMaterial({ color: 0xe9eefb, transparent: true, opacity: DAY ? 0.24 : 0.32, roughness: 0.05, metalness: 0.25, envMapIntensity: 1.1, depthWrite: false, side: THREE.DoubleSide }); var glass = new THREE.Mesh(gg, gm); glass.name = 'HALO_DECK_GLASS_SKYWALK'; glass.renderOrder = 3; glass.userData.noMerge = true; g.add(glass);
        var parts = []; for (var m = 0; m < 72; m++) { var ma = m / 72 * Math.PI * 2, bx = new THREE.BoxGeometry(rOut - rIn, 0.1, 0.16); bx.translate((rIn + rOut) / 2, 0, 0); bx.rotateY(-ma); bx.translate(s.x, y + 0.02, s.z); parts.push(bx); }
        [rIn + 0.1, rIn + 6, rIn + 12, HALO_LAYOUT.playable_radius_m + 0.15, rOut - 0.15].forEach(function (mr) { var tr = new THREE.TorusGeometry(mr, 0.1, 5, 192); tr.rotateX(Math.PI / 2); tr.translate(s.x, y + 0.03, s.z); parts.push(tr); });
        var rail = new THREE.TorusGeometry(HALO_LAYOUT.playable_radius_m + 0.15, 0.075, 6, 192); rail.rotateX(Math.PI / 2); rail.translate(s.x, y + 1.1, s.z); parts.push(rail);
        for (var p = 0; p < 96; p++) { var pa = p / 96 * Math.PI * 2, post = new THREE.CylinderGeometry(0.035, 0.045, 1.1, 5); post.translate(s.x + Math.cos(pa) * (HALO_LAYOUT.playable_radius_m + 0.15), y + 0.55, s.z + Math.sin(pa) * (HALO_LAYOUT.playable_radius_m + 0.15)); parts.push(post); }
        var mg = mergeGeometries(parts.map(function (q) { return q.index ? q.toNonIndexed() : q; }).map(function (q) { ['uv', 'normal'].forEach(function (k2) { if (!q.attributes[k2]) q.computeVertexNormals(); }); return q; }), false); parts.forEach(function (q) { q.dispose(); });
        var frame = new THREE.Mesh(mg, M.chrome); frame.name = 'HALO_SKYWALK_FRAME'; frame.userData.noMerge = true; g.add(frame);
        var bal = new THREE.Mesh(new THREE.CylinderGeometry(HALO_LAYOUT.playable_radius_m + 0.15, HALO_LAYOUT.playable_radius_m + 0.15, 1.05, 192, 1, true), gm.clone()); bal.material.opacity = DAY ? 0.18 : 0.26; bal.name = 'HALO_SKYWALK_BALUSTRADE'; bal.position.set(s.x, y + 0.55, s.z); bal.renderOrder = 3; bal.userData.noMerge = true; g.add(bal); }
      /* compact civic root and the one normal boarding door */
      var root = new THREE.Mesh(new THREE.CylinderGeometry(HALO_LAYOUT.base_radius_m, 6.6, 0.7, 64), darkGlass); root.position.set(s.x, 0.35, s.z); g.add(root); var rootRim = new THREE.Mesh(new THREE.TorusGeometry(6.15, 0.12, 10, 64), M.trimWarm); rootRim.rotation.x = Math.PI / 2; rootRim.position.set(s.x, 0.72, s.z); g.add(rootRim);
      var entry = new THREE.Mesh(new THREE.CapsuleGeometry(1.25, 1.5, 8, 24), darkGlass); entry.position.set(HALO_LAYOUT.ground_dock.x + 0.5, 1.75, HALO_LAYOUT.ground_dock.z); entry.rotation.z = Math.PI / 2; g.add(entry); var pad = new THREE.Mesh(new THREE.RingGeometry(1.65, 2.25, 48), M.trim.clone()); pad.material.transparent = true; pad.material.opacity = 0.38; pad.rotation.x = -Math.PI / 2; pad.position.set(HALO_LAYOUT.ground_dock.x, 0.75, HALO_LAYOUT.ground_dock.z); g.add(pad);
      /* tall engineered trunk with continuous platinum load path; base footprint remains local */
      var profile = [[6.2, 0.7], [5.6, 7], [4.7, PH * 0.22], [4.15, PH * 0.58], [4.6, PH * 0.82], [7.5, PH - 18], [15, PH - 3.2]].map(function (p) { return new THREE.Vector2(p[0], p[1]); }); var trunkMat = new THREE.MeshStandardMaterial({ color: 0xb4bcc7, roughness: 0.42, metalness: 0.62, envMapIntensity: 0.6 }); applySurface(THREE, trunkMat, 'TOWER', SDT); var trunk = new THREE.Mesh(new THREE.LatheGeometry(profile, 64), trunkMat);   /* M8: tall 7.2 m tower panels with a thin storey band (the facade grid read as tiling on a 240 m monument) */ trunk.position.set(s.x, 0, s.z); trunk.geometry.computeVertexNormals(); g.add(trunk);
      (function () {   /* M9 GROUNDING (owner: no rigid tree object stuck through the floor): one continuous load path — ROOTS flush in the plaza paving,
        twelve structural RIBS up the trunk into the twelve boughs, flush UPLIGHTS and a night light-wash on the lower trunk. Host-safe: below
        3.4 m every rib stands ≤ 5 cm beyond the r 6.2 m trunk collider, roots are 12 mm floor inlays, the dock side (west) stays clear. */
        var PRF = profile.map(function (v) { return [v.x, v.y]; }); function trunkR(y) { for (var i = 1; i < PRF.length; i++) if (y <= PRF[i][1]) { var a = PRF[i - 1], b = PRF[i], t = (y - a[1]) / (b[1] - a[1]); return a[0] + (b[0] - a[0]) * Math.max(0, Math.min(1, t)); } return PRF[PRF.length - 1][0]; }
        var CR = HALO_LAYOUT.base_radius_m, dockA = Math.atan2(HALO_LAYOUT.ground_dock.z - s.z, HALO_LAYOUT.ground_dock.x - s.x), Y3 = 3.4, TOP = PH * 0.56;
        function offDock(a) { return Math.abs(Math.atan2(Math.sin(a - dockA), Math.cos(a - dockA))) > 0.42; }
        function dd(y) { if (y < Y3) return CR + 0.05 - trunkR(y); var t = Math.min(1, (y - Y3) / 6); t = t * t * (3 - 2 * t); var top = 1 - Math.max(0, Math.min(1, (y - (TOP - 18)) / 18)); return ((CR + 0.05 - trunkR(Y3)) * (1 - t) + 0.45 * t) * top; }
        var ribPos = [], ys = []; for (var yy = 0.72; yy < 12; yy += 0.6) ys.push(yy); for (yy = 12; yy <= TOP; yy += 4) ys.push(yy);
        var ribAngles = []; for (var b = 0; b < 12; b++) { var ang = b / 12 * Math.PI * 2 + 0.13; if (offDock(ang)) ribAngles.push(ang); }
        ribAngles.forEach(function (ang) { var ca = Math.cos(ang), sa = Math.sin(ang), tx = -sa, tz = ca, prev = null;
          ys.forEach(function (y) { var r0 = trunkR(y) - 0.05, r1 = trunkR(y) + dd(y), wI = 0.58, wO = 0.4 + 0.14 * Math.min(1, dd(y) / 0.45);
            var q = [[r0, -wI], [r1, -wO], [r1, wO], [r0, wI]].map(function (c) { return [s.x + ca * c[0] + tx * c[1], y, s.z + sa * c[0] + tz * c[1]]; });
            if (prev) [[0, 1], [1, 2], [2, 3]].forEach(function (e) { var A = prev[e[0]], B = prev[e[1]], C = q[e[1]], D = q[e[0]]; ribPos.push.apply(ribPos, A.concat(B, C, A, C, D)); }); prev = q; }); });
        var rg = new THREE.BufferGeometry(); rg.setAttribute('position', new THREE.Float32BufferAttribute(ribPos, 3)); rg.computeVertexNormals(); var ribs = new THREE.Mesh(rg, M.chrome); ribs.name = 'TREE_TRUNK_RIBS'; ribs.userData.noMerge = true; g.add(ribs);
        /* roots: tapered, gently curving ribbons flush in the paving, continuing each rib outward, some forking */
        var rootPos = [], rnd = (function (sd) { return function () { sd = (sd * 16807) % 2147483647; return sd / 2147483647; }; })(4711), YF = 0.012;
        function ribbon(a0, r0, len, w0, w1, drift) { var n = 14, pts = []; for (var i = 0; i <= n; i++) { var t = i / n, rr = r0 + len * t, aa = a0 + drift * t * t, w = w0 + (w1 - w0) * t; var px = s.x + Math.cos(aa) * rr, pz = s.z + Math.sin(aa) * rr, nx = -Math.sin(aa), nz = Math.cos(aa); pts.push([px + nx * w / 2, pz + nz * w / 2, px - nx * w / 2, pz - nz * w / 2]); }
          for (var j = 0; j < n; j++) { var P = pts[j], Q = pts[j + 1]; rootPos.push(P[0], YF, P[1], Q[0], YF, Q[1], P[2], YF, P[3], P[2], YF, P[3], Q[0], YF, Q[1], Q[2], YF, Q[3]); } return pts; }
        ribAngles.forEach(function (ang) { var len = 6 + rnd() * 6, drift = (rnd() - 0.5) * 0.35; ribbon(ang, CR - 0.1, len, 1.05, 0.14, drift); if (rnd() < 0.65) { var fr = CR + len * (0.35 + rnd() * 0.2), fa = ang + drift * 0.3, sg = rnd() < 0.5 ? -1 : 1; ribbon(fa, fr, 2.5 + rnd() * 3, 0.5, 0.08, sg * (0.25 + rnd() * 0.2)); } });
        var rootG = new THREE.BufferGeometry(); rootG.setAttribute('position', new THREE.Float32BufferAttribute(rootPos, 3)); rootG.computeVertexNormals(); var rootMat = M.stone.clone(); rootMat.color.setHex(0x2a2f38); rootMat.roughness = 0.34; rootMat.metalness = 0.55; rootMat.polygonOffset = true; rootMat.polygonOffsetFactor = -2; rootMat.polygonOffsetUnits = -2; rootMat.side = THREE.DoubleSide;
        var roots = new THREE.Mesh(rootG, rootMat); roots.name = 'TREE_ROOT_INLAYS'; roots.userData.noMerge = true; g.add(roots);
        /* flush uplights between the ribs and a warm-white light wash on the lower trunk at night (practical light: the trunk is lit from its base) */
        var upParts = []; ribAngles.forEach(function (ang, i) { var aa = ang + Math.PI / 12, d = new THREE.CircleGeometry(0.28, 16); d.rotateX(-Math.PI / 2); d.translate(s.x + Math.cos(aa) * (CR + 0.45), 0.014, s.z + Math.sin(aa) * (CR + 0.45)); upParts.push(d); });
        var ups = new THREE.Mesh(mergeGeometries(upParts, false), M.trimWarm); upParts.forEach(function (q) { q.dispose(); }); ups.name = 'TREE_UPLIGHTS'; ups.userData.noMerge = true; g.add(ups);
        var washG = new THREE.CylinderGeometry(trunkR(16) + 0.08, CR + 0.08, 15.3, 64, 8, true); washG.translate(0, 0.7 + 7.65, 0); var wc = [], wp = washG.attributes.position; for (var wi = 0; wi < wp.count; wi++) { var hy = (wp.getY(wi) - 0.7) / 15.3, k = Math.pow(1 - hy, 2.2); wc.push(k, k, k); } washG.setAttribute('color', new THREE.Float32BufferAttribute(wc, 3)); washG.translate(s.x, 0, s.z);
        var wash = new THREE.Mesh(washG, new THREE.MeshBasicMaterial({ color: 0xfff1dc, vertexColors: true, transparent: true, opacity: 0.32, blending: THREE.AdditiveBlending, depthWrite: false, fog: true })); wash.name = 'TREE_UPLIGHT_WASH'; wash.userData.noMerge = true; wash.visible = !DAY; g.add(wash); g.userData.nightWash = wash;
      })();
      var core = new THREE.Mesh(new THREE.CylinderGeometry(1.05, 1.35, PH - 2.0, 32), glassCore); core.position.set(s.x, PH * 0.5, s.z); g.add(core); var recess = new THREE.Mesh(new THREE.CylinderGeometry(1.5, 1.75, PH - 4, 32, 1, true, Math.PI * 0.72, Math.PI * 0.56), darkGlass); recess.position.set(s.x, PH * 0.5, s.z); recess.rotation.y = Math.PI * 0.86; g.add(recess);
      for (var c = 0; c < 3; c++) { var aa = c / 3 * Math.PI * 2; tube([new THREE.Vector3(s.x + Math.cos(aa) * 3.9, 2, s.z + Math.sin(aa) * 3.9), new THREE.Vector3(s.x + Math.cos(aa) * 4.3, PH * 0.48, s.z + Math.sin(aa) * 4.3), new THREE.Vector3(s.x + Math.cos(aa) * 6.4, PH - 5, s.z + Math.sin(aa) * 6.4)], 0.13, M.trim, 72, 8); }
      var spiralPts = []; for (var sp = 0; sp <= 96; sp++) { var st = sp / 96, sa = st * Math.PI * 5.5 + 0.7, sr = 5.1 - st * 0.4; spiralPts.push(new THREE.Vector3(s.x + Math.cos(sa) * sr, 2 + st * (PH - 6), s.z + Math.sin(sa) * sr)); } tube(spiralPts, 0.16, M.trim, 128, 8);
      /* twelve primary boughs and twenty-four secondary ribs make the enlarged disc visibly load-bearing */
      for (var b = 0; b < 12; b++) { var ang = b / 12 * Math.PI * 2 + 0.13, ca = Math.cos(ang), sa2 = Math.sin(ang), side = b % 2 ? 1 : -1; var pts = [new THREE.Vector3(s.x + ca * 4.8, PH * 0.56, s.z + sa2 * 4.8), new THREE.Vector3(s.x + ca * 28 - sa2 * side * 5, PH * 0.72, s.z + sa2 * 28 + ca * side * 5), new THREE.Vector3(s.x + ca * 82, PH - 16, s.z + sa2 * 82), new THREE.Vector3(s.x + ca * (PR - 5), PH - 2.1, s.z + sa2 * (PR - 5))]; tube(pts, 2.05, b % 2 ? M.chrome : M.platinum, 72, 12); var joint = new THREE.Mesh(new THREE.SphereGeometry(2.35, 18, 12), M.chrome); joint.position.copy(pts[3]); g.add(joint); }
      for (var srib = 0; srib < 24; srib++) { var ar = srib / 24 * Math.PI * 2, crx = Math.cos(ar), crz = Math.sin(ar); tube([new THREE.Vector3(s.x + crx * 25, PH - 28, s.z + crz * 25), new THREE.Vector3(s.x + crx * 78, PH - 15, s.z + crz * 78), new THREE.Vector3(s.x + crx * (PR - 2), PH - 1.7, s.z + crz * (PR - 2))], 0.56, M.chrome, 48, 8); }
      /* upper structural deck plus broad, shared-endpoint class gradients */
      var under = new THREE.Mesh(new THREE.CylinderGeometry(PR, PR * 0.92, 3.2, 128, 1, true), darkGlass); under.name = 'HALO_DECK_SIDE_SKIRT'; under.position.set(s.x, PH - 1.6, s.z); g.add(under); var underside = new THREE.Mesh(new THREE.CircleGeometry(GLASS_IN - 1.2, 128), darkGlass); underside.name = 'HALO_DECK_UNDERSIDE'; underside.rotation.x = Math.PI / 2; underside.position.set(s.x, PH - 3.2, s.z); g.add(underside); deckSurface(GLASS_IN, PH); glassSkywalk(GLASS_IN, PR, PH);   /* one opaque floor owner: the former two coincident cylinder caps and transparent full-area overlays are gone */
      [48, 96, HALO_LAYOUT.playable_radius_m].forEach(function (rr, ri) { var ring = new THREE.Mesh(new THREE.TorusGeometry(rr, ri === 2 ? 0.22 : 0.12, 10, 128), ri === 2 ? M.trim : M.chrome); ring.rotation.x = Math.PI / 2; ring.position.set(s.x, PH + 0.11, s.z); g.add(ring); });
      /* sealed two-sided hemisphere and human-scale frame rhythm */
      var domeGlass = new THREE.ShaderMaterial({ transparent: true, depthWrite: false, side: THREE.DoubleSide, uniforms: { uDay: { value: DAY ? 1 : 0 } },   /* WORLD PIVOT PASS 4: iridescent fresnel glass — clear face-on, lavender / blue / rose sheen at grazing angles (the glass-ribbon reference) */
        vertexShader: 'varying vec3 vN; varying vec3 vV; varying vec3 vW; void main() { vec4 w = modelMatrix * vec4(position, 1.0); vW = w.xyz; vN = normalize(mat3(modelMatrix) * normal); vV = normalize(cameraPosition - w.xyz); gl_Position = projectionMatrix * viewMatrix * w; }',
        fragmentShader: 'uniform float uDay; varying vec3 vN; varying vec3 vV; varying vec3 vW; void main() { float f = pow(1.0 - abs(dot(normalize(vN), normalize(vV))), 2.6); float ph = 0.5 + 0.5 * sin(vW.y * 0.035 + atan(vN.z, vN.x) * 3.0); vec3 iri = mix(mix(vec3(0.74, 0.84, 1.0), vec3(0.84, 0.74, 1.0), ph), vec3(1.0, 0.8, 0.93), f * 0.6); float a = mix(uDay > 0.5 ? 0.035 : 0.06, uDay > 0.5 ? 0.46 : 0.58, f); vec3 c = iri * mix(uDay > 0.5 ? 1.05 : 0.55, uDay > 0.5 ? 1.25 : 0.9, f); gl_FragColor = vec4(c, a);\n#include <colorspace_fragment>\n}' });
      var dome = new THREE.Mesh(new THREE.SphereGeometry(DR, 96, 40, 0, Math.PI * 2, 0, Math.PI / 2), domeGlass); dome.position.set(s.x, PH, s.z); dome.renderOrder = 4; g.add(dome);
      (function () { var parts = [], MER = 24;   /* WORLD PIVOT PASS 4: a fine merged lattice (24 meridians + 6 parallels + a crown ring, ONE draw) replaces 16 heavy ribs + 4 rings */
        for (var rb = 0; rb < MER; rb++) { var ra = rb / MER * Math.PI * 2, pts = []; for (var q = 0; q <= 16; q++) { var th = q / 16 * (Math.PI / 2 - 0.03), rr = DR * Math.cos(th) - 0.12; pts.push(new THREE.Vector3(s.x + Math.cos(ra) * rr, PH + DR * Math.sin(th), s.z + Math.sin(ra) * rr)); } parts.push(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts), 40, rb % 3 === 0 ? 0.3 : 0.17, 5, false)); }
        [0.16, 0.32, 0.48, 0.63, 0.77, 0.89].forEach(function (f) { var th = Math.asin(f), rr = DR * Math.cos(th) - 0.12, t2 = new THREE.TorusGeometry(rr, 0.15, 5, 160); t2.rotateX(Math.PI / 2); t2.translate(s.x, PH + DR * f, s.z); parts.push(t2); });
        [4.6, 9.8].forEach(function (hT) { var t4 = new THREE.TorusGeometry(Math.sqrt(DR * DR - hT * hT) - 0.12, 0.09, 5, 200); t4.rotateX(Math.PI / 2); t4.translate(s.x, PH + hT, s.z); parts.push(t4); });   /* M10: two transoms low on the shell — the bare 23 m of glass above the deck gets a human-scale rhythm (on the shell: beyond reach) */
        var crown = new THREE.TorusGeometry(DR * 0.2, 0.34, 6, 96); crown.rotateX(Math.PI / 2); crown.translate(s.x, PH + DR * Math.sin(Math.acos(0.2)), s.z); parts.push(crown);
        var lat = new THREE.Mesh(mergeGeometries(parts.map(function (q) { return q.index ? q.toNonIndexed() : q; }), false), M.chrome); parts.forEach(function (q) { q.dispose(); }); lat.name = 'HALO_DOME_LATTICE'; lat.userData.noMerge = true; g.add(lat);
        /* M9 LATTICE NODES: a cast joint at every meridian × parallel crossing (and on the crown ring) — structure by day; at night a quiet
           architectural node light that joins the plaza's class sequence during the show (kit.showMaterial). On the shell (the flight
           boundary): nothing inside the playable volume. One instanced draw. */
        var nodeM = [], nm4 = new THREE.Matrix4(), nq = new THREE.Quaternion(), nv = new THREE.Vector3(), ns = new THREE.Vector3(0.75, 0.75, 0.75);
        [0.16, 0.32, 0.48, 0.63, 0.77, 0.89].forEach(function (f) { var th = Math.asin(f), rr = DR * Math.cos(th) - 0.12; for (var mi = 0; mi < MER; mi++) { var ma = mi / MER * Math.PI * 2; nv.set(s.x + Math.cos(ma) * rr, PH + DR * f, s.z + Math.sin(ma) * rr); nodeM.push(nm4.compose(nv, nq, ns).clone()); } });
        var cr2 = DR * 0.2; for (var ci2 = 0; ci2 < 12; ci2++) { var ca3 = ci2 / 12 * Math.PI * 2; nv.set(s.x + Math.cos(ca3) * cr2, PH + DR * Math.sin(Math.acos(0.2)), s.z + Math.sin(ca3) * cr2); nodeM.push(nm4.compose(nv, nq, ns).clone()); }
        var nodes = new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1, 0), kit.showMaterial(M.trim, { cx: s.x, cz: s.z }), nodeM.length); nodeM.forEach(function (m, i) { nodes.setMatrixAt(i, m); }); nodes.instanceMatrix.needsUpdate = true; nodes.computeBoundingSphere(); nodes.name = 'HALO_LATTICE_NODES'; nodes.userData.noMerge = true; g.add(nodes); })();
      (function () {   /* WORLD PIVOT PASS 4: the RIM COLONNADE — 40 slender platinum columns between the playable edge (144.8 m) and the shell, meeting the
        glass at ~20 m, each with an inner white-light strip and a capital, a chrome cornice ring on top: the circular promenade gets a
        human-scale rhythm. Beyond the host limit, so nothing here can be walked or flown into. Merged: 3 draws. */
        var RC = HALO_LAYOUT.playable_radius_m + 1.4, H2 = Math.sqrt(Math.max(1, DR * DR - RC * RC)) - 0.6, colP = [], litP = [], corP = [];
        for (var cI = 0; cI < 40; cI++) { var ca2 = cI / 40 * Math.PI * 2 + 0.04, cx2 = s.x + Math.cos(ca2) * RC, cz2 = s.z + Math.sin(ca2) * RC;
          var col = new THREE.CylinderGeometry(0.36, 0.52, H2, 10); col.translate(cx2, PH + H2 / 2, cz2); colP.push(col); var pl = new THREE.CylinderGeometry(0.8, 0.9, 0.5, 10); pl.translate(cx2, PH + 0.25, cz2); colP.push(pl);
          var strip2 = new THREE.BoxGeometry(0.07, H2 * 0.82, 0.07); strip2.translate(s.x + Math.cos(ca2) * (RC - 0.42), PH + H2 * 0.5, s.z + Math.sin(ca2) * (RC - 0.42)); litP.push(strip2);
          var capG = new THREE.CylinderGeometry(0.75, 0.4, 0.55, 10); capG.translate(cx2, PH + H2 - 0.2, cz2); litP.push(capG); }
        var cor = new THREE.TorusGeometry(RC, 0.34, 6, 200); cor.rotateX(Math.PI / 2); cor.translate(s.x, PH + H2, s.z); corP.push(cor);
        [[colP, M.platinum, 'HALO_RIM_COLONNADE'], [litP, kit.showMaterial(M.trim, { cx: s.x, cz: s.z }), 'HALO_RIM_LIGHTS'], [corP, M.chrome, 'HALO_RIM_CORNICE']].forEach(function (P) { var mg = mergeGeometries(P[0].map(function (q) { return q.index ? q.toNonIndexed() : q; }), false); P[0].forEach(function (q) { q.dispose(); }); var mm = new THREE.Mesh(mg, P[1]); mm.name = P[2]; mm.userData.noMerge = true; g.add(mm); }); })();
      (function () {   /* M10 RIM GARDEN (owner: the HALO at eye level is flat — edge treatment, planted transitions, built-in wall features,
        ambience; no walk-through solids). The band between the host's reach (playable 144.8 m + body 0.45 m) and the shell becomes a built
        edge: a honed-stone PLINTH with a planter bed, a recessed neutral LIGHT COVE at its foot, and low CRYSTAL PLANTING in each sector's
        class colour (the deck spokes' sectors), faintly lit at night. Everything lies beyond RI > 145.25 m — nothing here can be walked or
        flown into; the colonnade plinths stand in the bed. 4 draws; planting tiered (HIGH 700 shrubs ≈ 28 k tris · MED 0.6 · LOW 0.35). */
        var RI = HALO_LAYOUT.playable_radius_m + HALO_LAYOUT.body_radius_m + 0.25, RO = DR - 0.12, HP = 0.72, qS = SDT === 'LOW' ? 0.35 : (SDT === 'MED' ? 0.6 : 1);
        var prof = [[RI + 0.1, 0], [RI + 0.1, 0.06], [RI + 0.04, 0.08], [RI + 0.04, HP - 0.14], [RI + 0.1, HP - 0.12], [RI + 0.1, HP - 0.06], [RI - 0.06, HP - 0.06], [RI - 0.06, HP], [RI + 0.34, HP], [RI + 0.34, HP - 0.1], [RO - 0.08, HP - 0.1], [RO - 0.08, HP + 0.06], [RO, HP + 0.06], [RO, 0]].map(function (q) { return new THREE.Vector2(q[0], q[1]); });
        var plG = new THREE.LatheGeometry(prof, 240); plG.translate(s.x, PH, s.z); var plM = M.cladding.clone(); plM.color.setHex(0x6a717c); var plinth = new THREE.Mesh(plG, plM); plinth.name = 'HALO_RIM_PLINTH'; plinth.userData.noMerge = true; g.add(plinth);
        var soG = new THREE.RingGeometry(RI + 0.34, RO - 0.08, 240, 1); soG.rotateX(-Math.PI / 2); soG.translate(s.x, PH + HP - 0.12, s.z); var soil = new THREE.Mesh(soG, new THREE.MeshStandardMaterial({ color: 0x23262d, roughness: 0.95, metalness: 0.0 })); soil.name = 'HALO_RIM_BED'; soil.userData.noMerge = true; g.add(soil);
        var coG = new THREE.TorusGeometry(RI + 0.075, 0.03, 4, 240); coG.rotateX(Math.PI / 2); coG.translate(s.x, PH + HP - 0.1, s.z); var coM = M.trim.clone(); coM.emissiveIntensity = DAY ? 0.35 : 2.2; var cove = new THREE.Mesh(coG, coM); cove.name = 'HALO_RIM_COVE_LIGHT'; cove.userData.noMerge = true; cove.userData.dayNight = function (n) { coM.emissiveIntensity = n ? 2.2 : 0.35; }; g.add(cove);   /* neutral white practical light in the reveal under the coping — high enough to clear the playable-edge ring, the rim's night line */
        var blades = [], bq = new THREE.Quaternion(), bm = new THREE.Matrix4(), bs = new THREE.Vector3(), bp = new THREE.Vector3(), eu = new THREE.Euler();
        for (var bI = 0; bI < 5; bI++) { var bg = new THREE.OctahedronGeometry(1, 0), bh = 0.3 + (bI % 3) * 0.08; bg.scale(0.16, bh, 0.1); bg.translate(0, bh * 0.85, 0); eu.set((bI % 3 - 1) * 0.3, bI * 0.9, (bI % 2 ? 1 : -1) * (0.18 + (bI % 4) * 0.06)); bg.applyMatrix4(bm.makeRotationFromEuler(eu)); var ba2 = bI / 5 * 6.283; bg.translate(Math.cos(ba2) * 0.2 * (bI % 2 ? 1 : 0.5), 0, Math.sin(ba2) * 0.2 * (bI % 2 ? 1 : 0.5)); blades.push(bg.toNonIndexed()); }   /* a bushy crystal shrub ≈ 0.7 m across, 0.5–0.8 m tall */
        var shrubG = mergeGeometries(blades, false); blades.forEach(function (q) { q.dispose(); }); shrubG.computeVertexNormals();
        var shrubM = new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.28, metalness: 0.35, flatShading: true }), uGlow = { value: DAY ? 0.06 : 0.42 };
        shrubM.onBeforeCompile = function (sh) { sh.uniforms.uRimGlow = uGlow; sh.fragmentShader = 'uniform float uRimGlow;\n' + sh.fragmentShader.replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n#ifdef USE_COLOR\n totalEmissiveRadiance += vColor.rgb * uRimGlow;\n#endif'); }; shrubM.customProgramCacheKey = function () { return 'halo_rim_shrub'; };
        var nSh = SDT === 'LOW' ? 0 : Math.round(700 * qS), shrubs = new THREE.InstancedMesh(shrubG, shrubM, Math.max(1, nSh)), sc = new THREE.Color(), silver = new THREE.Color(0xc9d0da), rr0 = (function (sd) { return function () { sd = (sd * 16807) % 2147483647; return sd / 2147483647; }; })(4471);
        for (var sI = 0; sI < nSh; sI++) { var sa = (sI + rr0() * 0.6) / nSh * Math.PI * 2, srad = RI + 0.55 + rr0() * (RO - RI - 0.85), sk = 0.75 + Math.pow(rr0(), 1.6) * 0.55;
          bp.set(s.x + Math.cos(sa) * srad, PH + HP - 0.12, s.z + Math.sin(sa) * srad); bq.setFromAxisAngle(new THREE.Vector3(0, 1, 0), rr0() * 6.283); bs.set(sk, sk * (0.75 + rr0() * 0.35), sk);   /* tops stay under eye height (plinth 0.72 + shrub ≤ 0.85): the view out over the rim is kept */ shrubs.setMatrixAt(sI, bm.compose(bp, bq, bs));
          var sec = Math.floor((((sa - 0.22) % (Math.PI * 2)) + Math.PI * 2) % (Math.PI * 2) / (Math.PI * 2 / 5)) % 5;   /* the plan's sector (canvas axes = world x / z) */ sc.set(FAMS_RIM[sec]).lerp(silver, 0.35 + rr0() * 0.3); shrubs.setColorAt(sI, sc); }   /* the sector's class colour, restrained toward silver */
        shrubs.instanceMatrix.needsUpdate = true; if (shrubs.instanceColor) shrubs.instanceColor.needsUpdate = true; shrubs.computeBoundingSphere(); shrubs.name = 'HALO_RIM_PLANTING'; shrubs.userData.noMerge = true; shrubs.userData.dayNight = function (n) { uGlow.value = n ? 0.42 : 0.06; }; if (nSh > 0) g.add(shrubs); else { shrubG.dispose(); shrubM.dispose(); }   /* M10 LOW: no planting draw */
        g.userData.rimGarden = { inner_r: RI, outer_r: RO, plinth_h: HP, shrubs: nSh }; })();
      (function () {   /* M10 GARDEN LIGHT (owner: HALO lighting / ambience at eye level). Over each of the five class garden terraces a soft column of
        LIGHT rises from a flush floor emitter ring — the same language as the city's sky-energy conduits: light, not a solid (nothing to walk or
        fly into). It gives the empty deck five mid-distance landmarks in the sector's class colour — faint by day, a quiet glow at night — and a
        flush light pool on the deck around it. 3 draws (beams, emitter rings, pools). */
        var bc = document.createElement('canvas'); bc.width = 8; bc.height = 128; var bx2 = bc.getContext('2d'), bgr = bx2.createLinearGradient(0, 0, 0, 128); bgr.addColorStop(0, 'rgba(255,255,255,0)'); bgr.addColorStop(0.55, 'rgba(255,255,255,0.22)'); bgr.addColorStop(0.9, 'rgba(255,255,255,0.75)'); bgr.addColorStop(1, 'rgba(255,255,255,1)'); bx2.fillStyle = bgr; bx2.fillRect(0, 0, 8, 128);
        var bt = new THREE.CanvasTexture(bc); bt.colorSpace = THREE.SRGBColorSpace;
        var pc = document.createElement('canvas'); pc.width = pc.height = 64; var px2 = pc.getContext('2d'), pgr = px2.createRadialGradient(32, 32, 1, 32, 32, 32); pgr.addColorStop(0, 'rgba(255,255,255,0.9)'); pgr.addColorStop(0.35, 'rgba(255,255,255,0.35)'); pgr.addColorStop(1, 'rgba(255,255,255,0)'); px2.fillStyle = pgr; px2.fillRect(0, 0, 64, 64); var pt = new THREE.CanvasTexture(pc); pt.colorSpace = THREE.SRGBColorSpace;
        var bG = new THREE.CylinderGeometry(1, 1, 1, 18, 1, true); bG.translate(0, 0.5, 0); var bM = new THREE.MeshBasicMaterial({ map: bt, transparent: true, opacity: DAY ? 0.14 : 0.32, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide, fog: false });
        var eG = new THREE.TorusGeometry(1, 0.035, 4, 64); eG.rotateX(Math.PI / 2); var eM = new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: DAY ? 0.5 : 1.8, roughness: 0.3, metalness: 0.2 });
        var pG = new THREE.CircleGeometry(1, 40); pG.rotateX(-Math.PI / 2); var pM = new THREE.MeshBasicMaterial({ map: pt, transparent: true, opacity: DAY ? 0.08 : 0.42, depthWrite: false, blending: THREE.AdditiveBlending, fog: false, polygonOffset: true, polygonOffsetFactor: -2 });
        var beams2 = new THREE.InstancedMesh(bG, bM, 5), rings2 = new THREE.InstancedMesh(eG, eM, 5), pools2 = new THREE.InstancedMesh(pG, pM, 5), m5 = new THREE.Matrix4(), q5 = new THREE.Quaternion(), v5 = new THREE.Vector3(), s5 = new THREE.Vector3(), c5 = new THREE.Color();
        for (var gI = 0; gI < 5; gI++) { var gA = gI / 5 * Math.PI * 2 + 0.22 + Math.PI / 5, gx = s.x + Math.cos(gA) * 84, gz = s.z + Math.sin(gA) * 84;   /* the deck plan's canvas axes are world x / z (as the arrival medallion) */ c5.set(FAMS_RIM[gI]);
          beams2.setMatrixAt(gI, m5.compose(v5.set(gx, PH + 0.02, gz), q5, s5.set(1.2, 60, 1.2))); beams2.setColorAt(gI, c5);
          rings2.setMatrixAt(gI, m5.compose(v5.set(gx, PH + 0.006, gz), q5, s5.set(1.2, 1, 1.2))); rings2.setColorAt(gI, c5.clone().lerp(new THREE.Color(0xffffff), 0.45));   /* flush: the ring tops out 4 cm above the deck */
          pools2.setMatrixAt(gI, m5.compose(v5.set(gx, PH + 0.012, gz), q5, s5.set(8, 1, 8))); pools2.setColorAt(gI, c5); }
        [[beams2, 'HALO_GARDEN_LIGHT_BEAMS', function (n) { bM.opacity = n ? 0.32 : 0.14; }], [rings2, 'HALO_GARDEN_EMITTERS', function (n) { eM.emissiveIntensity = n ? 1.8 : 0.5; }], [pools2, 'HALO_GARDEN_LIGHT_POOLS', function (n) { pM.opacity = n ? 0.42 : 0.08; }]].filter(function (B, bi) { if (SDT === 'LOW' && bi > 0) { B[0].geometry.dispose(); B[0].material.dispose(); return false; } return true; }).forEach(function (B) { B[0].instanceMatrix.needsUpdate = true; if (B[0].instanceColor) B[0].instanceColor.needsUpdate = true; B[0].computeBoundingSphere(); B[0].name = B[1]; B[0].userData.noMerge = true; B[0].userData.dayNight = B[2]; B[0].renderOrder = 5; g.add(B[0]); });
        rings2.renderOrder = 0; })();   /* M10 LOW: the beams only (no emitter rings / pools) */
      (function () {   /* WORLD PIVOT PASS 4: three suspended CELESTIAL RINGS high above the centre (reference: elegant luminous rings) — white light with a
        lavender core, slowly counter-rotating (fieldScene.tick), visible from the deck and from the ground through the dome glass. Decorative,
        never solid. */
        var rg = new THREE.Group(); rg.name = 'HALO_CELESTIAL_RINGS'; rg.userData.noMerge = true; rg.position.set(s.x, PH + 95, s.z);
        var rm = new THREE.MeshStandardMaterial({ color: 0xf2f0ff, emissive: 0xe4d8ff, emissiveIntensity: DAY ? 0.85 : 1.6, roughness: 0.25, metalness: 0.4 });
        [[26, 0.42, 0.18], [34, 0.3, -0.26], [42, 0.52, 0.34]].forEach(function (R3, i) { var t3 = new THREE.Mesh(new THREE.TorusGeometry(R3[0], R3[1], 8, 220), rm); t3.rotation.x = Math.PI / 2 + R3[2]; t3.rotation.y = i * 0.7; t3.userData.spin = (i % 2 ? -1 : 1) * (0.025 + i * 0.01); rg.add(t3); });
        g.add(rg); })();
      var zenith = new THREE.Mesh(new THREE.OctahedronGeometry(1.3, 1), M.diamond); zenith.scale.y = 1.45; zenith.position.set(s.x, HALO_LAYOUT.apex_height_m + 0.4, s.z); g.add(zenith);
      /* civic programme at human scale: arrival court, overlooks, rest bays, guide focus */
      for (var bn = 0; bn < 12; bn++) { var ba = bn / 12 * Math.PI * 2 + 0.12, br = bn % 2 ? 104 : 57; var bench = new THREE.Mesh(roundedBox(2.0, 0.42, 0.62, 0.2), M.platinum); bench.position.set(s.x + Math.cos(ba) * br, PH + 0.22, s.z + Math.sin(ba) * br); bench.rotation.y = -ba + Math.PI / 2; g.add(bench); var lamp = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.1, 1.3, 8), M.chrome); lamp.position.set(s.x + Math.cos(ba + 0.035) * (br + 2.1), PH + 0.65, s.z + Math.sin(ba + 0.035) * (br + 2.1)); g.add(lamp); }
      for (var bay = 0; bay < 5; bay++) { var bya = bay / 5 * Math.PI * 2 + 0.35, bx = s.x + Math.cos(bya) * 126, bz = s.z + Math.sin(bya) * 126; var court = new THREE.Mesh(new THREE.CylinderGeometry(6.2, 6.5, 0.24, 48), M.chrome); court.position.set(bx, PH + 0.12, bz); g.add(court); var courtRing = new THREE.Mesh(new THREE.TorusGeometry(6.05, 0.11, 8, 48), M.trim); courtRing.rotation.x = Math.PI / 2; courtRing.position.set(bx, PH + 0.31, bz); g.add(courtRing); var marker = new THREE.Mesh(new THREE.OctahedronGeometry(0.95, 1), M.diamond); marker.position.set(bx, PH + 1.55, bz); g.add(marker); for (var pc = 0; pc < 4; pc++) { var pa = bya + pc / 4 * Math.PI * 2 + 0.38, crystal = new THREE.Mesh(new THREE.OctahedronGeometry(0.62 + (pc % 2) * 0.18, 1), pc % 2 ? M.diamond : M.trim); crystal.scale.y = 1.7 + (pc % 3) * 0.28; crystal.position.set(bx + Math.cos(pa) * 4.25, PH + 1.0, bz + Math.sin(pa) * 4.25); g.add(crystal); } for (var pb = -1; pb <= 1; pb += 2) { var pocketBench = new THREE.Mesh(roundedBox(1.8, 0.4, 0.58, 0.18), M.platinum); pocketBench.position.set(bx + Math.cos(bya + Math.PI / 2) * pb * 3.1, PH + 0.22, bz + Math.sin(bya + Math.PI / 2) * pb * 3.1); pocketBench.rotation.y = -bya + Math.PI / 2; g.add(pocketBench); } }
      var HL = HALO_PLAY_LAYOUT, sport = new THREE.Group(); sport.name = 'HALO_VOLLEY_COURT'; sport.userData.noMerge = true; var courtMat = M.platinum.clone(); courtMat.color.setHex(0x8496a9); courtMat.roughness = 0.34; var sportDeck = new THREE.Mesh(roundedBox(HL.half_length_m * 2, 0.12, HL.half_width_m * 2, 0.28), courtMat); sportDeck.position.set(HL.center.x, PH + 0.06, HL.center.z); sport.add(sportDeck); var lineMat = M.trim.clone(); lineMat.emissiveIntensity *= 0.72; [[0, 0, 0.055, HL.half_width_m * 2], [-HL.half_length_m, 0, 0.08, HL.half_width_m * 2], [HL.half_length_m, 0, 0.08, HL.half_width_m * 2], [0, -HL.half_width_m, HL.half_length_m * 2, 0.08], [0, HL.half_width_m, HL.half_length_m * 2, 0.08]].forEach(function (ln) { var lm = new THREE.Mesh(roundedBox(ln[2] || 0.06, 0.035, ln[3] || 0.06, 0.02), lineMat); lm.position.set(HL.center.x + ln[0], PH + 0.135, HL.center.z + ln[1]); sport.add(lm); }); for (var np = -1; np <= 1; np += 2) { var post = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.09, HL.net_height_m + 0.28, 12), M.chrome); post.position.set(HL.center.x, PH + (HL.net_height_m + 0.28) / 2, HL.center.z + np * (HL.half_width_m + 0.12)); sport.add(post); } var netMat = glassCore.clone(); netMat.opacity = DAY ? 0.22 : 0.34; netMat.wireframe = true; var net = new THREE.Mesh(new THREE.PlaneGeometry(HL.half_width_m * 2, HL.net_height_m, 18, 6), netMat); net.rotation.y = Math.PI / 2; net.position.set(HL.center.x, PH + HL.net_height_m / 2, HL.center.z); sport.add(net); HL.targets.forEach(function (tt) { var tm = new THREE.Mesh(new THREE.TorusGeometry(tt.radius_m, 0.055, 8, 40), tt.id === 'CENTER' ? M.trimWarm : M.trim); tm.rotation.x = Math.PI / 2; tm.position.set(tt.x, PH + 0.17, tt.z); sport.add(tm); }); var sportLabel = nameSprite('MAH HALO · VOLLEY / SERVE LAB'); sportLabel.position.set(HL.entry.x, PH + 2.7, HL.entry.z - 2.8); sportLabel.scale.set(8.8, 1.2, 1); sport.add(sportLabel); var sportBall = new THREE.Mesh(new THREE.SphereGeometry(HL.ball_radius_m, 20, 14), M.diamond); sportBall.name = 'HALO_VOLLEY_BALL'; sportBall.visible = false; sport.add(sportBall); var ballShadow = new THREE.Mesh(new THREE.CircleGeometry(0.3, 24), new THREE.MeshBasicMaterial({ color: 0x07101d, transparent: true, opacity: 0.34, depthWrite: false })); ballShadow.name = 'HALO_VOLLEY_BALL_SHADOW'; ballShadow.rotation.x = -Math.PI / 2; ballShadow.visible = false; sport.add(ballShadow); g.add(sport); g.userData.sport = { group: sport, ball: sportBall, shadow: ballShadow };
      var focus = new THREE.Mesh(new THREE.OctahedronGeometry(0.8, 1), M.diamond); focus.position.set(HALO_LAYOUT.guide.x, PH + 1.35, HALO_LAYOUT.guide.z); g.add(focus); var focusHalo = new THREE.Mesh(new THREE.TorusGeometry(1.25, 0.055, 8, 40), M.trim); focusHalo.rotation.x = Math.PI / 2; focusHalo.position.set(HALO_LAYOUT.guide.x, PH + 0.72, HALO_LAYOUT.guide.z); g.add(focusHalo);
      /* One finished human-scale walk-in cabin. Its group origin is the floor/host
         carrier origin, so the passenger and car consume the exact same pose. */
      var cabin = new THREE.Group(); cabin.name = 'MAH_ASCENT_CABIN'; cabin.userData.noMerge = true; var cabFloor = new THREE.Mesh(new THREE.CylinderGeometry(1.72, 1.72, 0.16, 40), M.platinum); cabFloor.position.y = 0.08; cabin.add(cabFloor); var cabCeil = new THREE.Mesh(new THREE.CylinderGeometry(1.72, 1.64, 0.18, 40), M.chrome); cabCeil.position.y = 3.12; cabin.add(cabCeil); var cabWallMat = glassCore.clone(); cabWallMat.opacity = DAY ? 0.25 : 0.34; var cabWall = new THREE.Mesh(new THREE.CylinderGeometry(1.68, 1.68, 2.84, 40, 1, true, Math.PI * 0.12, Math.PI * 1.76), cabWallMat); cabWall.position.y = 1.62; cabin.add(cabWall); for (var cp = 0; cp < 4; cp++) { var cpa = cp / 4 * Math.PI * 2 + Math.PI / 4, rail = new THREE.Mesh(new THREE.CylinderGeometry(0.055, 0.07, 2.92, 10), M.chrome); rail.position.set(Math.cos(cpa) * 1.58, 1.62, Math.sin(cpa) * 1.58); cabin.add(rail); } var cr = new THREE.Mesh(new THREE.TorusGeometry(1.62, 0.075, 8, 40), M.trim); cr.rotation.x = Math.PI / 2; cr.position.y = 0.2; cabin.add(cr); var cr2 = cr.clone(); cr2.position.y = 3.0; cabin.add(cr2); var doorMat = cabWallMat.clone(), doorL = new THREE.Mesh(roundedBox(0.74, 2.54, 0.075, 0.1), doorMat), doorR = doorL.clone(); doorL.position.set(-0.4, 1.48, 1.61); doorR.position.set(0.4, 1.48, 1.61); cabin.add(doorL); cabin.add(doorR); var cabinGem = new THREE.Mesh(new THREE.OctahedronGeometry(0.28, 1), M.diamond); cabinGem.position.y = 3.47; cabin.add(cabinGem); cabin.position.set(HALO_LAYOUT.ground_dock.x, 0, HALO_LAYOUT.ground_dock.z); g.add(cabin);
      var shaft = new THREE.Mesh(new THREE.CylinderGeometry(0.055, 0.055, PH - 0.4, 8), M.trim); shaft.position.set(cabin.position.x - 0.92, PH / 2, s.z); g.add(shaft); var dockHalo = new THREE.Mesh(new THREE.RingGeometry(2.2, 3.8, 64), M.trim.clone()); dockHalo.material.transparent = true; dockHalo.material.opacity = 0.28; dockHalo.rotation.x = -Math.PI / 2; dockHalo.position.set(HALO_LAYOUT.upper_dock.x, PH + 0.08, HALO_LAYOUT.upper_dock.z); g.add(dockHalo);
      for (var dp = -1; dp <= 1; dp += 2) { var dockPylon = new THREE.Mesh(new THREE.CylinderGeometry(0.16, 0.22, 3.1, 12), M.chrome); dockPylon.position.set(HALO_LAYOUT.upper_dock.x + dp * 1.75, PH + 1.55, HALO_LAYOUT.upper_dock.z + 2.0); g.add(dockPylon); } var dockLintel = new THREE.Mesh(roundedBox(3.8, 0.24, 0.32, 0.12), M.platinum); dockLintel.position.set(HALO_LAYOUT.upper_dock.x, PH + 3.05, HALO_LAYOUT.upper_dock.z + 2.0); g.add(dockLintel); var dockGem = new THREE.Mesh(new THREE.OctahedronGeometry(0.42, 1), M.diamond); dockGem.position.set(HALO_LAYOUT.upper_dock.x, PH + 3.7, HALO_LAYOUT.upper_dock.z + 2.0); g.add(dockGem);
      var label = nameSprite('MAH ASCENT · RETURN'); label.position.set(HALO_LAYOUT.upper_dock.x, PH + 3.45, HALO_LAYOUT.upper_dock.z + 1.8); label.scale.set(7.4, 1.25, 1); g.add(label);
      g.userData.cabin = cabin; g.userData.cabinGlass = cabWallMat; g.userData.cabinDoors = [doorL, doorR]; g.userData.platformH = PH; g.userData.baseY = 0; g.userData.floorOwners = { visible_top: 'HALO_DECK_SINGLE_TOP', top_y_m: PH, full_area_opaque_owners: 1, transparent_full_area_overlays: 0, side_open_ended: true }; g.userData.treeAscentEnvelope = { contract: HALO_LAYOUT.contract, base_radius_m: HALO_LAYOUT.base_radius_m, trunk_height_m: PH, deck_height_m: PH, realm_radius_m: HALO_LAYOUT.playable_radius_m, structural_deck_radius_m: PR, playable_radius_m: HALO_LAYOUT.playable_radius_m, dome_radius_m: DR, dome_diameter_m: HALO_LAYOUT.shell_diameter_m, dome_apex_m: HALO_LAYOUT.apex_height_m, boarding_x: cabin.position.x, boarding_z: s.z, cabin_half_width_m: HALO_LAYOUT.carrier.half_width_m, cabin_half_depth_m: HALO_LAYOUT.carrier.half_depth_m, cabin_clear_height_m: HALO_LAYOUT.carrier.clear_height_m, elevator_only: true };
      group.add(g); return g; },
    /* residential pod: a rounded platinum shell with a luminous seam and a soft door light */
    pod: function (s) { var g = new THREE.Group(); var body = new THREE.Mesh(new THREE.SphereGeometry(s.r, 24, 16, 0, Math.PI * 2, 0, Math.PI * 0.55), M.platinum); body.scale.y = s.h / s.r * 0.75; body.position.set(s.x, 0, s.z); g.add(body); var seam = new THREE.Mesh(new THREE.TorusGeometry(s.r * 0.98, 0.05, 8, 40), M.trim); seam.rotation.x = Math.PI / 2; seam.position.set(s.x, s.h * 0.45, s.z); g.add(seam); var door = new THREE.Mesh(roundedBox(1.1, 2.0, 0.3, 0.4), M.doorway); door.position.set(s.x, 0, s.z + s.r - 0.1); g.add(door); var dm = new THREE.Mesh(new THREE.CircleGeometry(1.2, 24), M.trimWarm.clone()); dm.material.transparent = true; dm.material.opacity = 0.16; dm.rotation.x = -Math.PI / 2; dm.position.set(s.x, 0.02, s.z + s.r + 1.0); g.add(dm); group.add(g); return g; },
    materials: M,
    /* M8E: the live time-of-day toggle and the frame clock reach the facades (windows light up at night; the plaza light show) */
    setNight: function (n) { kit.setNight(n); group.traverse(function (o) { if (o.name === 'TREE_UPLIGHT_WASH') o.visible = !!n; if (o.userData.dayNight) o.userData.dayNight(!!n); }); },   /* M9: the trunk's practical light wash follows the live time of day */ tick: function (dt, t) { kit.tick(dt, t); }, facadeInfo: function () { return Object.assign({ audit: kit.audit() }, kit.info()); }
  };
  return api;
}
