/* MAHWORLD :: SAMPLE CITY DRESSING (presentation only; every solid it draws is one authoritative collider from the field layout)
   Building language: rounded / softened blocks, chromium + platinum, controlled glass bands, curved entrances, diamond accents, cool
   blue-white light — never a box with a pointed roof. Ground: premium chromium with restrained reflections and diamond inlays. Vegetation:
   laser-plant stalks with square-diamond leaves. All materials are shared and geometry is instanced or merged where it repeats, so a phone
   pays for a handful of draw calls per building. Lighting is a TEMPLATE meant to generalise to future character packages: one cool key,
   one hemisphere, an environment map for specular, emissive trims for local light (no per-lamp point lights). */
import { HALO_LAYOUT, HALO_PLAY_LAYOUT } from '../play/haloLayout.js';
import { mergeGeometries } from '../vendor/three/BufferGeometryUtils.js';
import { defaultTextureCap } from './texCap.js'; import { applySurface } from './world/surfaceDetail.js';
export function createCityScene(THREE, group, helpers) {
  var roundedBox = helpers.roundedBox, canvasTex = helpers.canvasTex; var DAY = helpers.night === false;
  var M = {
    /* JOB B palette (owner 2026-09-19 §4): PLATINUM facades (a mid-light cool grey with a restrained sky sheen — never white), CHROMIUM domes / trims, GRAPHITE recesses */
    platinum: new THREE.MeshStandardMaterial({ color: 0xb4bcc7, roughness: 0.42, metalness: 0.62, envMapIntensity: 0.6 }),   /* WORLD PIVOT PASS 3: satin anodised platinum panels (the mirror-metal facades read as flat sky reflections in daylight) */
    chrome: new THREE.MeshStandardMaterial({ color: 0xa4aeb9, roughness: (DAY ? 0.32 : 0.24), metalness: (DAY ? 0.92 : 0.98), envMapIntensity: (DAY ? 0.55 : 0.7) }),   /* M8: brushed, not a sky mirror, by day */
    dark: new THREE.MeshStandardMaterial({ color: 0x1d2229, roughness: 0.5, metalness: 0.75 }),
    glass: new THREE.MeshStandardMaterial({ color: 0x9aa6b8, roughness: 0.06, metalness: 0.55, transparent: true, opacity: 0.78, emissive: 0x1c2233, emissiveIntensity: (DAY ? 0.3 : 0.9), envMapIntensity: 1.0 }),   /* WORLD PIVOT PASS 3 + colour law: smoked neutral curtain-wall glass (was the civic cyan band) */
    trim: new THREE.MeshStandardMaterial({ color: 0xe6ecf6, emissive: 0xdfe8ff, emissiveIntensity: (DAY ? 0.45 : 1.7), roughness: 0.3, metalness: 0.2 }),   /* M8: daylight trims read by contrast, not by a white glow (was 0.95) */   /* B7 §7: the tier ledges / portholes read as recessed cyan energy seams */
    trimWarm: new THREE.MeshStandardMaterial({ color: 0xe9edf3, emissive: 0xdfeeff, emissiveIntensity: (DAY ? 0.3 : 1.2), roughness: 0.3, metalness: 0.1 }),
    diamond: new THREE.MeshStandardMaterial({ color: 0xe2e9f4, roughness: 0.05, metalness: 0.6, emissive: 0xd6e0ff, emissiveIntensity: (DAY ? 0.5 : 0.9), flatShading: true }),   /* B7 §7: the roof diamond is a cyan crystal, not a white cap */
    doorway: new THREE.MeshStandardMaterial({ color: 0x10141c, roughness: 0.9, metalness: 0.1, emissive: 0xd7dce8, emissiveIntensity: (DAY ? 0.32 : 0.7) }),   /* colour law: the doorway recess glows clean white light (was cyan) */
    stone: new THREE.MeshStandardMaterial({ color: 0x3a3f4a, roughness: 0.62, metalness: 0.28, envMapIntensity: 0.35 }),   /* WORLD PIVOT PASS 3: graphite stone plinths / roof plant */
    leaf: new THREE.MeshStandardMaterial({ color: 0xe4e9f2, emissive: 0xffc862, emissiveIntensity: (DAY ? 0.495 : 1.1), roughness: 0.3, metalness: 0.3, flatShading: true, side: THREE.DoubleSide }),
    stalk: new THREE.MeshStandardMaterial({ color: 0xe8edf5, emissive: 0xdfe8ff, emissiveIntensity: (DAY ? 0.405 : 0.9), roughness: 0.4, metalness: 0.2 }),
    puddle: new THREE.MeshStandardMaterial({ color: 0x1a2432, roughness: 0.02, metalness: 1.0, transparent: true, opacity: 0.85 })
  };
  /* M8 MATERIAL REALISM: the civic families get world-space structural surface logic (lab/world/surfaceDetail.js) — facade panel grid with
     inset seams and a trim band per 3.6 m storey, brushed chrome, panelled graphite structure, stone grain. Value / roughness only (no hue). */
  var SDT = helpers.surfaceTier || 'HIGH'; applySurface(THREE, M.platinum, 'FACADE', SDT); applySurface(THREE, M.chrome, 'BRUSHED', SDT); applySurface(THREE, M.dark, 'STRUCTURE', SDT); applySurface(THREE, M.stone, 'STONE', SDT);
  function nameSprite(text) { var tex = canvasTex(512, 96, function (g, w, h) { g.clearRect(0, 0, w, h); g.font = '600 46px "Segoe UI", Arial, sans-serif'; g.textAlign = 'center'; g.textBaseline = 'middle'; g.shadowColor = '#f3e6c8'; g.shadowBlur = 18; g.fillStyle = '#f7f9ff'; g.fillText(text.toUpperCase(), w / 2, h / 2); }); var sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: tex, transparent: true, depthWrite: false, fog: false })); sp.scale.set(7.5, 1.4, 1); return sp; }
  function tier(cx, cz, w, d, y0, h, r, mat) { var m = new THREE.Mesh(roundedBox(w, h, d, r), mat); m.position.set(cx, y0, cz); return m; }   /* roundedBox is extruded from y0 upward (see fieldScene.roundedBox) */
  function band(cx, cz, w, d, y, h, r) { var b = new THREE.Mesh(roundedBox(w + 0.12, h, d + 0.12, r), M.glass); b.position.set(cx, y, cz); return b; }
  function strip(cx, cz, w, d, y, r, mat) { var s = new THREE.Mesh(roundedBox(w + 0.2, 0.08, d + 0.2, r), mat || M.trim); s.position.set(cx, y, cz); return s; }
  /* WORLD PIVOT PASS 3 (owner 2026-09-25: premium, believable architecture — structure first, light second). Every addition stays inside the
     collider footprint or above head height (≥ 3.4 m), so visuals and collision keep parity: a graphite plinth, thin floor cornices every
     3.6 m (readable human scale), a cantilevered entrance canopy with a white-light underside, and a roof-plant cluster (condensers, a
     tank, a mast with a white beacon, a tilted solar array). Merged per material: 2 extra draws per building. */
  function premiumDress(g, cx, cz, w, d, tiers, hEach, topY, B) {
    var stoneParts = [], trimParts = [], chromeParts = []; function rb(W, H, D, R, x, y, z) { var q = roundedBox(W, H, D, R); q.translate(x, y, z); return q; }
    stoneParts.push(rb(w + 0.1, 0.85, d + 0.1, Math.min(w, d) * 0.24, cx, 0, cz));   /* plinth */
    for (var t = 0; t < tiers; t++) { var k = 1 - t * 0.09, tw = w * k, td = d * k, y0 = t * hEach; for (var fy = y0 + 3.6; fy < y0 + hEach - 0.8; fy += 3.6) { if (fy < 3.4) continue; chromeParts.push(rb(tw + 0.34, 0.12, td + 0.34, Math.min(tw, td) * 0.24, cx, fy, cz)); } }
    if (B.entrance) { var e = B.entrance, horiz = e.side === '+z' || e.side === '-z', sx = e.side === '+x' ? 1 : e.side === '-x' ? -1 : 0, sz = e.side === '+z' ? 1 : e.side === '-z' ? -1 : 0, cy = e.height + 0.35, ow = e.width * 1.9, od = 2.3;
      stoneParts.push(rb(horiz ? ow : od, 0.22, horiz ? od : ow, 0.08, e.x + sx * (od / 2 - 0.2), cy, e.z + sz * (od / 2 - 0.2)));
      trimParts.push(rb(horiz ? ow - 0.3 : 0.1, 0.04, horiz ? 0.1 : ow - 0.3, 0.02, e.x + sx * (od - 0.35), cy - 0.03, e.z + sz * (od - 0.35))); }
    var k2 = 1 - tiers * 0.09, rw = w * k2 * 0.62, rd = d * k2 * 0.62, ry = topY + 0.5;   /* roof plant on the cap */
    for (var u = 0; u < 3; u++) stoneParts.push(rb(rw * 0.22, 0.9, rd * 0.18, 0.1, cx - rw * 0.3 + u * rw * 0.3, ry, cz - rd * 0.28));
    var tank = new THREE.CylinderGeometry(Math.min(rw, rd) * 0.12, Math.min(rw, rd) * 0.12, 1.6, 20); tank.translate(cx + rw * 0.28, ry + 0.8, cz + rd * 0.22); chromeParts.push(tank);
    var mast = new THREE.CylinderGeometry(0.05, 0.08, 4.2, 6); mast.translate(cx - rw * 0.32, ry + 2.1, cz + rd * 0.26); chromeParts.push(mast);
    var tip = new THREE.OctahedronGeometry(0.2, 0); tip.translate(cx - rw * 0.32, ry + 4.3, cz + rd * 0.26); trimParts.push(tip);
    for (var pnl = 0; pnl < 2; pnl++) { var pg = roundedBox(rw * 0.28, 0.06, rd * 0.34, 0.02); pg.rotateX(-0.35); pg.translate(cx - rw * 0.02 + pnl * rw * 0.3, ry + 0.55, cz + rd * 0.18); stoneParts.push(pg); }
    [[stoneParts, M.stone, 'PREMIUM_STONE'], [chromeParts, M.chrome, 'PREMIUM_CHROME'], [trimParts, M.trim, 'PREMIUM_LIGHT']].forEach(function (P) { if (!P[0].length) return; var mg = mergeGeometries(P[0].map(function (q) { return q.index ? q.toNonIndexed() : q; }), false); P[0].forEach(function (q) { q.dispose(); }); if (!mg) return; var mesh = new THREE.Mesh(mg, P[1]); mesh.name = (g.name || 'BUILDING') + '_' + P[2]; g.add(mesh); });
  }
  function diamond(x, y, z, s) { var o = new THREE.Mesh(new THREE.OctahedronGeometry(s, 0), M.diamond); o.position.set(x, y, z); o.scale.set(1, 1.6, 1); return o; }
  function entrance(bx, bz, e) {   /* e: {side:'+x'|'-x'|'+z'|'-z', x, z, width, height}: a curved recessed opening on that face, a light arch, a landing strip */
    var g = new THREE.Group(); var horiz = e.side === '+z' || e.side === '-z'; var sx = e.side === '+x' ? 1 : e.side === '-x' ? -1 : 0; var sz = e.side === '+z' ? 1 : e.side === '-z' ? -1 : 0;
    var depth = 0.9; var door = new THREE.Mesh(roundedBox(horiz ? e.width : depth, e.height, horiz ? depth : e.width, Math.min(e.width, e.height) * 0.42), M.doorway); door.position.set(e.x + sx * (depth / 2 - 0.35), 0, e.z + sz * (depth / 2 - 0.35)); g.add(door);
    var arch = new THREE.Mesh(new THREE.TorusGeometry(e.width * 0.52, 0.09, 8, 32, Math.PI), M.trim); arch.position.set(e.x + sx * 0.3, e.height * 0.62, e.z + sz * 0.3); if (!horiz) arch.rotation.y = Math.PI / 2; g.add(arch);
    /* door: two platinum leaves set into the recess with a vertical light seam, a lit lintel above, concentric landing rings on the ground */
    var leafW = e.width * 0.44, leafH = e.height * 0.86; [-1, 1].forEach(function (sg) { var leaf = new THREE.Mesh(roundedBox(horiz ? leafW : 0.12, leafH, horiz ? 0.12 : leafW, 0.14), M.platinum); leaf.position.set(e.x + (horiz ? sg * (leafW / 2 + 0.05) : sx * 0.12), 0.04, e.z + (horiz ? sz * 0.12 : sg * (leafW / 2 + 0.05))); g.add(leaf); });
    var seam = new THREE.Mesh(roundedBox(horiz ? 0.06 : 0.16, leafH * 0.9, horiz ? 0.16 : 0.06, 0.02), M.trim); seam.position.set(e.x + sx * 0.14, 0.08, e.z + sz * 0.14); g.add(seam);
    var lintel = new THREE.Mesh(roundedBox(horiz ? e.width * 1.15 : 0.3, 0.16, horiz ? 0.3 : e.width * 1.15, 0.05), M.trimWarm); lintel.position.set(e.x + sx * 0.45, e.height * 0.98, e.z + sz * 0.45); g.add(lintel);
    [1.2, 2.1].forEach(function (rr, i) { var ring = new THREE.Mesh(new THREE.RingGeometry(rr - 0.05, rr, 40), i ? M.trim : M.trimWarm); ring.rotation.x = -Math.PI / 2; ring.position.set(e.x + sx * 2.4, 0.03, e.z + sz * 2.4); g.add(ring); });
    var mat = new THREE.Mesh(new THREE.PlaneGeometry(horiz ? e.width * 1.1 : 4.5, horiz ? 4.5 : e.width * 1.1), M.trimWarm); mat.rotation.x = -Math.PI / 2; mat.position.set(e.x + sx * 2.4, 0.02, e.z + sz * 2.4); mat.material = M.trimWarm.clone(); mat.material.transparent = true; mat.material.opacity = 0.22; g.add(mat);
    return g;
  }
  var api = {
    /* one authored building from its collider (BOX or CYLINDER) + `building` block */
    building: function (s) {
      var B = s.building; var g = new THREE.Group(); g.name = s.id; var cx, cz, w, d;
      if (s.type === 'CYLINDER') { cx = s.x; cz = s.z; w = d = s.r * 2; } else { cx = (s.x1 + s.x2) / 2; cz = (s.z1 + s.z2) / 2; w = s.x2 - s.x1; d = s.z2 - s.z1; }
      var tiers = Math.max(1, B.tiers || 1); var hEach = s.h / tiers; var y = 0;
      if (B.dome) {
        var base = new THREE.Mesh(new THREE.CylinderGeometry(s.r, s.r * 1.04, s.h * 0.55, 48), M.platinum); base.position.set(cx, s.h * 0.275, cz); g.add(base);
        var dome = new THREE.Mesh(new THREE.SphereGeometry(s.r * 0.98, 48, 24, 0, Math.PI * 2, 0, Math.PI / 2), M.chrome); dome.scale.y = (s.h * 0.45) / (s.r * 0.98); dome.position.set(cx, s.h * 0.55, cz); g.add(dome);
        var ring1 = new THREE.Mesh(new THREE.TorusGeometry(s.r * 1.0, 0.1, 8, 64), M.trim); ring1.rotation.x = Math.PI / 2; ring1.position.set(cx, s.h * 0.55, cz); g.add(ring1);
        var gband = new THREE.Mesh(new THREE.CylinderGeometry(s.r * 1.02, s.r * 1.02, s.h * 0.12, 48, 1, true), M.glass); gband.position.set(cx, s.h * 0.30, cz); g.add(gband);
        g.add(diamond(cx, s.h + 1.1, cz, 0.9));
      } else {
        for (var i = 0; i < tiers; i++) { var k = 1 - i * 0.09; var tw = w * k, td = d * k; var r = Math.min(tw, td) * 0.24; g.add(tier(cx, cz, tw, td, y, hEach, r, i % 2 ? M.chrome : M.platinum)); g.add(band(cx, cz, tw, td, y + hEach * (B.glass_band || 0.45) - 0.35, 0.7, r)); g.add(strip(cx, cz, tw, td, y + hEach - 0.12, r)); y += hEach; }
        var cap = new THREE.Mesh(roundedBox(w * (1 - tiers * 0.09) * 0.7, 0.5, d * (1 - tiers * 0.09) * 0.7, Math.min(w, d) * 0.2), M.chrome); cap.position.set(cx, y, cz); g.add(cap);
        g.add(diamond(cx, y + 1.4, cz, 0.7));
      }
      /* MOTION PRECISION PASS I — façade depth: vertical chrome fins along each tier's long faces (instanced), a recessed dark window strip
         behind the glass band, a light ledge at every tier base, round portholes on the upper tiers — authored, restrained, coherent */
      if (!B.dome) { var finCount = 0; var faces = []; var yy = 0; for (var t2 = 0; t2 < tiers; t2++) { var kk = 1 - t2 * 0.09; faces.push({ y: yy, h: hEach, w: w * kk, d: d * kk }); yy += hEach; }
        var finsPer = faces.reduce(function (a, f) { return a + 2 * (Math.floor(f.w / 1.6) + Math.floor(f.d / 1.6)); }, 0); var fins = new THREE.InstancedMesh(new THREE.BoxGeometry(0.16, 1, 0.34), M.chrome, Math.max(1, finsPer)); var fm = new THREE.Matrix4(), fq = new THREE.Quaternion(), fv = new THREE.Vector3(), fs = new THREE.Vector3();
        faces.forEach(function (f) { var fh = f.h * 0.78; var nx = Math.floor(f.w / 1.6), nz = Math.floor(f.d / 1.6);
          for (var i2 = 0; i2 < nx; i2++) { var px = cx - f.w / 2 + (i2 + 0.5) * (f.w / nx); [-1, 1].forEach(function (sg) { fq.identity(); fm.compose(fv.set(px, f.y + f.h * 0.5, cz + sg * (f.d / 2 + 0.08)), fq, fs.set(1, fh, 1)); if (finCount < fins.count) fins.setMatrixAt(finCount++, fm); }); }
          for (var j2 = 0; j2 < nz; j2++) { var pz = cz - f.d / 2 + (j2 + 0.5) * (f.d / nz); [-1, 1].forEach(function (sg) { fq.setFromAxisAngle(new THREE.Vector3(0, 1, 0), Math.PI / 2); fm.compose(fv.set(cx + sg * (f.w / 2 + 0.08), f.y + f.h * 0.5, pz), fq, fs.set(1, fh, 1)); if (finCount < fins.count) fins.setMatrixAt(finCount++, fm); }); }
          var ledge = new THREE.Mesh(roundedBox(f.w + 0.5, 0.06, f.d + 0.5, Math.min(f.w, f.d) * 0.24), M.trimWarm); ledge.position.set(cx, f.y + 0.02, cz); g.add(ledge);
          var inset = new THREE.Mesh(roundedBox(f.w + 0.02, 0.9, f.d + 0.02, Math.min(f.w, f.d) * 0.24), M.dark); inset.position.set(cx, f.y + f.h * (B.glass_band || 0.45) - 0.45, cz); g.add(inset); });
        fins.instanceMatrix.needsUpdate = true; if (helpers.fins !== false) g.add(fins);
        if (tiers >= 2) { var top = faces[faces.length - 1]; for (var pi2 = 0; pi2 < 3; pi2++) { [-1, 1].forEach(function (sg) { var ring = new THREE.Mesh(new THREE.TorusGeometry(0.42, 0.06, 8, 24), M.trim); ring.position.set(cx - top.w * 0.3 + pi2 * top.w * 0.3, top.y + top.h * 0.62, cz + sg * (top.d / 2 + 0.1)); g.add(ring); var disc = new THREE.Mesh(new THREE.CircleGeometry(0.4, 20), M.glass); disc.position.copy(ring.position); if (sg < 0) disc.rotation.y = Math.PI; g.add(disc); }); } } }
      if (B.entrance) g.add(entrance(cx, cz, B.entrance));
      if (!B.dome) premiumDress(g, cx, cz, w, d, tiers, hEach, y, B);
      var label = nameSprite(B.name || s.id); label.position.set(B.entrance ? B.entrance.x : cx, (B.entrance ? B.entrance.height : 4) + 1.6, B.entrance ? B.entrance.z : cz); g.add(label);
      group.add(g); return g;
    },
    /* ground and dressing: chrome floor with diamond inlays, puddle accents, laser plants; nothing blocks movement */
    dress: function (size) {
      var seed = 9; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }
      /* diamond inlays: thin flat octahedra in a ring around the plaza */
      var inlay = new THREE.InstancedMesh(new THREE.OctahedronGeometry(0.55, 0), new THREE.MeshStandardMaterial({ color: 0xe8f4ff, roughness: 0.1, metalness: 0.9, emissive: 0x3a86c8, emissiveIntensity: 0.35, flatShading: true }), 24); var mtx = new THREE.Matrix4(); var q = new THREE.Quaternion(); var sc = new THREE.Vector3(1, 0.06, 1);
      for (var i = 0; i < 24; i++) { var a = i / 24 * Math.PI * 2; var rr = 11.5 + (i % 2) * 1.2; q.setFromAxisAngle(new THREE.Vector3(0, 1, 0), a); mtx.compose(new THREE.Vector3(Math.cos(a) * rr, 0.03, Math.sin(a) * rr), q, sc); inlay.setMatrixAt(i, mtx); } inlay.instanceMatrix.needsUpdate = true; group.add(inlay);
      /* JOB B PLAZA CLEANUP (owner directive 2026-09-19 §5 — registry zone PLAZA_CLEAR): the central plaza keeps its lanes, forecourts and landing
         clearance; the decorative puddles and laser-plant clusters move out of the axis lanes / forecourts to the plaza's south perimeter beds (r ≈ 44–50 m,
         away from the tree elevator (30, 40) and the pods (−30, 26)). Landmarks, pathways, pylons and the emblem stay. Nothing here blocks movement. */
      /* puddles: three flat mirror accents at the south forecourt corners (out of every lane) */
      [[-31, -31, 2.0], [31, -31, 1.8], [-45, -20, 1.5]].forEach(function (p) { var pd = new THREE.Mesh(new THREE.CircleGeometry(p[2], 24), M.puddle); pd.rotation.x = -Math.PI / 2; pd.position.set(p[0], 0.015, p[1]); pd.scale.x = 1.35; group.add(pd); });
      /* laser plants: instanced stalks + square-diamond leaves in clusters near the buildings' flanks */
      var spots = [[-40, -38], [40, -38], [-47, -9], [47, -9], [-14, -48], [14, -48], [-28, -46], [28, -46], [-48, 8], [48, 8], [-44, -26], [44, -26]];   /* perimeter planting beds (south half + flanks), was: 12 clusters inside r 27 m of the plaza centre */
      var stalks = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.03, 0.05, 1, 5), M.stalk, spots.length * 5); var leaves = new THREE.InstancedMesh(new THREE.PlaneGeometry(0.42, 0.42), M.leaf, spots.length * 5 * 3); var n1 = 0, n2 = 0; var v = new THREE.Vector3();
      spots.forEach(function (sp) { for (var k = 0; k < 5; k++) { var x = sp[0] + (rnd() - 0.5) * 2.2, z = sp[1] + (rnd() - 0.5) * 2.2; var h = 1.1 + rnd() * 1.5; var tilt = (rnd() - 0.5) * 0.35; q.setFromEuler(new THREE.Euler(tilt, rnd() * 6.28, (rnd() - 0.5) * 0.35)); mtx.compose(v.set(x, h / 2, z), q, new THREE.Vector3(1, h, 1)); stalks.setMatrixAt(n1++, mtx);
        for (var l = 0; l < 3; l++) { var ly = h * (0.45 + l * 0.22); q.setFromEuler(new THREE.Euler(0.2, rnd() * 6.28, Math.PI / 4)); mtx.compose(v.set(x + (rnd() - 0.5) * 0.3, ly, z + (rnd() - 0.5) * 0.3), q, new THREE.Vector3(1 - l * 0.2, 1 - l * 0.2, 1)); leaves.setMatrixAt(n2++, mtx); } } });
      stalks.instanceMatrix.needsUpdate = true; leaves.instanceMatrix.needsUpdate = true; group.add(stalks); group.add(leaves);
      /* MOTION PRECISION PASS I — readable pathways: low light strips from the plaza ring to each entrance, lit kerbs, light pylons at
         intervals (instanced), and the MAHWORLD emblem over the plaza centre. Presentation only: nothing here blocks movement. */
      var entrances = [[-17, 0, -1, 0], [0, -19.5, 0, -1], [18, 0, 1, 0], [1, 20, 0, 1]];   /* x, z, dir x, dir z */
      var pylons = new THREE.InstancedMesh(new THREE.CylinderGeometry(0.07, 0.1, 1, 8), M.chrome, 56); var rings = new THREE.InstancedMesh(new THREE.TorusGeometry(0.22, 0.035, 6, 20), M.trim, 56); var np = 0; var pm = new THREE.Matrix4(), pq = new THREE.Quaternion(), pv = new THREE.Vector3(), ps = new THREE.Vector3();
      entrances.forEach(function (en) { var ex = en[0], ez = en[1], dx = en[2], dz = en[3]; var start = 12.5, len = Math.hypot(ex, ez) - start - 2.6; if (len < 2) return; var cxp = ex - dx * (start + len / 2 + 2.6) * 0 + (-dx) * (len / 2 + 2.6) , czp = ez + (-dz) * (len / 2 + 2.6);
        var path = new THREE.Mesh(new THREE.PlaneGeometry(dx ? len : 2.4, dx ? 2.4 : len), M.trimWarm.clone()); path.material.transparent = true; path.material.opacity = 0.10; path.rotation.x = -Math.PI / 2; path.position.set(cxp, 0.012, czp); group.add(path);
        [-1, 1].forEach(function (sg) { var kerb = new THREE.Mesh(new THREE.PlaneGeometry(dx ? len : 0.08, dx ? 0.08 : len), M.trim); kerb.rotation.x = -Math.PI / 2; kerb.position.set(cxp + (dx ? 0 : sg * 1.3), 0.02, czp + (dx ? sg * 1.3 : 0)); group.add(kerb); });
        for (var k2 = 0; k2 < 4; k2++) { var t3 = (k2 + 0.5) / 4; var px = cxp + (dx ? (t3 - 0.5) * len : 0), pz = czp + (dx ? 0 : (t3 - 0.5) * len); [-1, 1].forEach(function (sg) { if (np >= 56) return; var qx = px + (dx ? 0 : sg * 2.7), qz = pz + (dx ? sg * 2.7 : 0); pq.identity(); pm.compose(pv.set(qx, 0.55, qz), pq, ps.set(1, 1.1, 1)); pylons.setMatrixAt(np, pm); pq.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2); pm.compose(pv.set(qx, 1.15, qz), pq, ps.set(1, 1, 1)); rings.setMatrixAt(np, pm); np++;   /* bollard lights at the kerb edge: short, off the walking line */ }); } });
      /* secondary streets (S09 §32): plaza -> tree elevator (NE) and plaza -> residential pods (NW): lit kerbs + bollards on the diagonal */
      [[30, 40, 21], [-30, 30, 19]].forEach(function (dst) { var ang = Math.atan2(dst[1], dst[0]); var L2 = Math.hypot(dst[0], dst[1]) - dst[2] - 4; var mid = 13 + L2 / 2; var cxp = Math.cos(ang) * mid, czp = Math.sin(ang) * mid; var path = new THREE.Mesh(new THREE.PlaneGeometry(L2, 2.6), M.trimWarm.clone()); path.material.transparent = true; path.material.opacity = 0.09; path.rotation.x = -Math.PI / 2; path.rotation.z = -ang; path.position.set(cxp, 0.012, czp); group.add(path); for (var k3 = 0; k3 < 5; k3++) { var t4 = 13 + (k3 + 0.5) / 5 * L2; [-1, 1].forEach(function (sg) { if (np >= 32) return; var qx = Math.cos(ang) * t4 - Math.sin(ang) * sg * 2.4, qz = Math.sin(ang) * t4 + Math.cos(ang) * sg * 2.4; pq.identity(); pm.compose(pv.set(qx, 0.55, qz), pq, ps.set(1, 1.1, 1)); pylons.setMatrixAt(np, pm); pq.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2); pm.compose(pv.set(qx, 1.15, qz), pq, ps.set(1, 1, 1)); rings.setMatrixAt(np, pm); np++; }); } });
      pylons.count = np; rings.count = np; pylons.instanceMatrix.needsUpdate = true; rings.instanceMatrix.needsUpdate = true; group.add(pylons); group.add(rings);
      var emblem = new THREE.Group(); var oct = new THREE.Mesh(new THREE.OctahedronGeometry(1.1, 0), M.diamond); oct.scale.set(1, 1.7, 1); emblem.add(oct); var halo = new THREE.Mesh(new THREE.TorusGeometry(1.9, 0.05, 8, 48), M.trim); halo.rotation.x = Math.PI / 2; emblem.add(halo); emblem.position.set(0, 9.5, 0); emblem.name = 'MAH_EMBLEM'; group.add(emblem); var lbl = nameSprite('MAHWORLD PLAZA'); lbl.position.set(0, 12.2, 0); group.add(lbl); api.emblem = emblem;
      /* The old 26-cone ridge was the actual owner of the enormous blue planar shard in the M7 owner view: on the district build its
         34–94 m seven-sided cones were merged before the registry macro/far-world layers loaded.  Keep the bounded fallback for the small
         standalone field, but do not stack it behind the full world where macro.js + farWorld.js already own the unreachable horizon. */
      var ridge = new THREE.MeshStandardMaterial({ color: DAY ? 0x6f8196 : 0x9aa6b4, roughness: DAY ? 0.85 : 0.55, metalness: DAY ? 0.35 : 0.75, flatShading: true }); var mg = new THREE.Group(); mg.name = 'MAHWORLD_LEGACY_HORIZON_RIDGE';
      var ringR = (helpers && helpers.horizonRadius) || 150; if (ringR <= 200) { for (var m = 0; m < 26; m++) { var ang = m / 26 * Math.PI * 2 + rnd() * 0.15; var dist = ringR + rnd() * 60; var hh = 22 + rnd() * 40; var cone = new THREE.Mesh(new THREE.ConeGeometry(18 + rnd() * 22, hh, 12), ridge); cone.position.set(Math.cos(ang) * dist, hh / 2 - 6, Math.sin(ang) * dist); cone.rotation.y = rnd() * 3; cone.scale.set(1, 0.7, 1.35); mg.add(cone); } group.add(mg); api.legacyRidge = 'SMALL_FIELD_FALLBACK'; } else api.legacyRidge = 'SUPPRESSED_FULL_WORLD';
    },
    /* M7 HALO SCALE/ACCESS — re-authored at the single canonical 10× arrival / 18× dome result.  The city, base, actors and furniture stay
       human scale; only the vertical civic trunk, structural deck and enclosed upper realm use the authorised dimensions. */
    treeElevator: function (s, shapes) { var g = new THREE.Group(); g.name = 'TREE_ELEVATOR'; g.userData.noMerge = true; var PH = HALO_LAYOUT.arrival_height_m, PR = HALO_LAYOUT.structural_deck_radius_m, DR = HALO_LAYOUT.shell_radius_m;
      var glassCore = M.glass.clone(); glassCore.color.setHex(0xd4def0); glassCore.opacity = DAY ? 0.16 : 0.24; glassCore.depthWrite = false; glassCore.side = THREE.DoubleSide; glassCore.emissiveIntensity = DAY ? 0.24 : 0.48;
      var darkGlass = M.doorway.clone(); darkGlass.transparent = true; darkGlass.opacity = 0.82;
      var floorMat = M.platinum.clone(); floorMat.roughness = 0.32; floorMat.metalness = 0.92; floorMat.envMapIntensity = 0.72;
      function tube(points, radius, mat, tubular, radial) { var curve = new THREE.CatmullRomCurve3(points); var mesh = new THREE.Mesh(new THREE.TubeGeometry(curve, tubular || 40, radius, radial || 10, false), mat); g.add(mesh); return mesh; }
      function gradientRing(inner, outer, y, stops, opacity) { var seg = 128, pos = [], col = [], ind = []; for (var i = 0; i <= seg; i++) { var t = i / seg, a = t * Math.PI * 2, f = t * stops.length, si = Math.min(stops.length - 1, Math.floor(f)), sj = (si + 1) % stops.length, u = f - Math.floor(f), sm = u * u * (3 - 2 * u), c0 = new THREE.Color(stops[si]), c1 = new THREE.Color(stops[sj]), cc = c0.clone().lerp(c1, sm); [inner, outer].forEach(function (r) { pos.push(s.x + Math.cos(a) * r, y, s.z + Math.sin(a) * r); col.push(cc.r, cc.g, cc.b); }); if (i < seg) { var k = i * 2; ind.push(k, k + 1, k + 2, k + 1, k + 3, k + 2); } } var geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); geo.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); geo.setIndex(ind); var mat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.28, metalness: 0.68, emissive: 0x111827, emissiveIntensity: DAY ? 0.12 : 0.28, transparent: opacity < 1, opacity: opacity, side: THREE.DoubleSide }); var mesh = new THREE.Mesh(geo, mat); g.add(mesh); return mesh; }
      function gradientSpoke(angle, inner, outer, width, y, c0, c1) { var seg = 40, pos = [], col = [], ind = [], ax = Math.cos(angle), az = Math.sin(angle), sx = -az, sz = ax, A = new THREE.Color(c0), B = new THREE.Color(c1); for (var i = 0; i <= seg; i++) { var t = i / seg, sm = t * t * (3 - 2 * t), r = inner + (outer - inner) * t, cc = A.clone().lerp(B, sm); [-1, 1].forEach(function (side) { pos.push(s.x + ax * r + sx * width * side, y, s.z + az * r + sz * width * side); col.push(cc.r, cc.g, cc.b); }); if (i < seg) { var k = i * 2; ind.push(k, k + 1, k + 2, k + 1, k + 3, k + 2); } } var geo = new THREE.BufferGeometry(); geo.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); geo.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); geo.setIndex(ind); var mat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.3, metalness: 0.72, emissive: 0x141827, emissiveIntensity: DAY ? 0.14 : 0.32, transparent: true, opacity: DAY ? 0.48 : 0.62, side: THREE.DoubleSide }); var mesh = new THREE.Mesh(geo, mat); g.add(mesh); return mesh; }
      /* WORLD PIVOT PASS 4 (owner 2026-09-25: the HALO is a signature landmark, not an empty dome). The deck is ONE opaque top to the
         glass sky-walk (GLASS_IN): a plan-drawn canvas pattern in the circular-platform language — satin platinum stone, concentric paving
         seams, luminous white inlay rings, five class sectors deepening toward the rim, a segmented light-ring medallion at the elevator
         arrival — with a matching emissive map for the inlays. Texture size follows the tier cap (1024 on phones). */
      var GLASS_IN = 128;
      function deckTextures(R) { var cap = (function () { try { var tc = defaultTextureCap(); return tc ? tc.maxEdge() : 2048; } catch (e) { return 2048; } })(); var N = Math.min(2048, cap || 2048); var k = N / (2 * R);
        function canvas() { var c = document.createElement('canvas'); c.width = c.height = N; return c; } var cc = canvas(), ce = canvas(), g2 = cc.getContext('2d'), ge = ce.getContext('2d'); var C0 = N / 2;
        var FAMS = ['#e6c36a', '#f08ab8', '#8f6ad8', '#3f78e8', '#d4344a'];   /* gold · pink · purple · blue · red around the deck (colour law) */
        var bg = g2.createRadialGradient(C0, C0, 0, C0, C0, C0); bg.addColorStop(0, DAY ? '#aab0ba' : '#2c3140'); bg.addColorStop(0.7, DAY ? '#98a0ab' : '#232835'); bg.addColorStop(1, DAY ? '#858d9a' : '#1b1f2a');   /* PASS 2b: a mid-value satin stone by day so the white inlays and class sectors carry (was near-white under the 3.0 key) */ g2.fillStyle = bg; g2.fillRect(0, 0, N, N); ge.fillStyle = '#000'; ge.fillRect(0, 0, N, N);
        for (var sct = 0; sct < 5; sct++) { var a0 = sct / 5 * Math.PI * 2 + 0.22, a1 = a0 + Math.PI * 2 / 5; var gr = g2.createRadialGradient(C0, C0, R * 0.2 * k, C0, C0, R * k); gr.addColorStop(0, 'rgba(0,0,0,0)'); gr.addColorStop(1, FAMS[sct] + '66'); g2.fillStyle = gr; g2.beginPath(); g2.moveTo(C0, C0); g2.arc(C0, C0, R * k, a0, a1); g2.closePath(); g2.fill(); }
        for (var band2 = 0; band2 < R; band2 += 12) { g2.fillStyle = (band2 / 12) % 2 ? (DAY ? 'rgba(255,255,255,0.09)' : 'rgba(255,255,255,0.03)') : (DAY ? 'rgba(20,26,40,0.09)' : 'rgba(0,0,0,0.08)'); g2.beginPath(); g2.arc(C0, C0, Math.min(R, band2 + 12) * k, 0, Math.PI * 2); g2.arc(C0, C0, band2 * k, 0, Math.PI * 2, true); g2.fill(); }   /* alternating stone bands */
        g2.lineWidth = Math.max(1, 0.1 * k); g2.strokeStyle = DAY ? 'rgba(52,60,78,0.18)' : 'rgba(140,150,190,0.14)'; for (var rr = 6; rr < R; rr += 6) { g2.beginPath(); g2.arc(C0, C0, rr * k, 0, Math.PI * 2); g2.stroke(); }   /* paving seams */
        for (var sp = 0; sp < 40; sp++) { var sa = sp / 40 * Math.PI * 2 + 0.22; g2.beginPath(); g2.moveTo(C0 + Math.cos(sa) * 18 * k, C0 + Math.sin(sa) * 18 * k); g2.lineTo(C0 + Math.cos(sa) * R * k, C0 + Math.sin(sa) * R * k); g2.stroke(); }
        [24, 48, 72, 96, 120].forEach(function (ir, ii) { ge.lineWidth = g2.lineWidth = (ii === 4 ? 0.9 : 0.55) * k; ge.strokeStyle = 'rgba(255,255,255,0.95)'; g2.strokeStyle = DAY ? 'rgba(250,251,255,0.95)' : 'rgba(220,226,255,0.9)'; [g2, ge].forEach(function (ctx2) { ctx2.beginPath(); ctx2.arc(C0, C0, ir * k, 0, Math.PI * 2); ctx2.stroke(); }); });   /* luminous white inlay rings */
        for (var sb = 0; sb < 5; sb++) { var ba = sb / 5 * Math.PI * 2 + 0.22; [g2, ge].forEach(function (ctx2) { ctx2.strokeStyle = FAMS[sb]; ctx2.lineWidth = 0.35 * k; ctx2.beginPath(); ctx2.moveTo(C0 + Math.cos(ba) * 24 * k, C0 + Math.sin(ba) * 24 * k); ctx2.lineTo(C0 + Math.cos(ba) * R * k, C0 + Math.sin(ba) * R * k); ctx2.stroke(); }); }   /* the five class spokes */
        var ax = (HALO_LAYOUT.upper_dock.x - s.x) * k + C0, az = (HALO_LAYOUT.upper_dock.z - s.z) * k + C0;   /* arrival medallion: segmented light ring (reference 3) */
        for (var seg2 = 0; seg2 < 30; seg2++) { var q0 = seg2 / 30 * Math.PI * 2, q1 = q0 + Math.PI * 2 / 30 * 0.72, colr = seg2 % 3 === 0 ? FAMS[(seg2 / 3) % 5] : '#ffffff'; [g2, ge].forEach(function (ctx2) { ctx2.strokeStyle = colr; ctx2.lineWidth = 0.7 * k; ctx2.beginPath(); ctx2.arc(ax, az, 9 * k, q0, q1); ctx2.stroke(); }); }
        [g2, ge].forEach(function (ctx2) { ctx2.strokeStyle = 'rgba(255,255,255,0.9)'; ctx2.lineWidth = 0.22 * k; [5.5, 12].forEach(function (mr) { ctx2.beginPath(); ctx2.arc(ax, az, mr * k, 0, Math.PI * 2); ctx2.stroke(); }); });
        var tMap = new THREE.CanvasTexture(cc), tGlow = new THREE.CanvasTexture(ce); [tMap, tGlow].forEach(function (t) { t.colorSpace = THREE.SRGBColorSpace; t.anisotropy = 8; t.generateMipmaps = true; t.minFilter = THREE.LinearMipmapLinearFilter; }); return { map: tMap, glow: tGlow }; }
      function deckSurface(radius, y) { var T = deckTextures(radius); var geo = new THREE.CircleGeometry(radius, 192); geo.rotateX(-Math.PI / 2); geo.translate(s.x, y, s.z);
        var mat = new THREE.MeshStandardMaterial({ map: T.map, emissiveMap: T.glow, emissive: 0xffffff, emissiveIntensity: DAY ? 0.42 : 0.95, roughness: DAY ? 0.5 : 0.36, metalness: DAY ? 0.3 : 0.45, envMapIntensity: DAY ? 0.42 : 0.6 }); applySurface(THREE, mat, 'DECK', SDT);   /* M8: honed deck stone with a 3 m slab grid under the plan-drawn rings */ var mesh = new THREE.Mesh(geo, mat); mesh.name = 'HALO_DECK_SINGLE_TOP'; mesh.userData.noMerge = true; g.add(mesh); return mesh; }
      /* the glass SKY-WALK: the deck annulus GLASS_IN..PR is glass (a separate area owner, never an overlay), so the rim — 16.8 m of it inside
         the playable radius — looks straight down 240 m over MAHWORLD; a merged platinum mullion grid carries it, a glass balustrade marks
         the playable edge. The underside disc stops at GLASS_IN, and the boughs below stay visible through the glass. */
      function glassSkywalk(rIn, rOut, y) { var gg = new THREE.RingGeometry(rIn, rOut, 192, 1); gg.rotateX(-Math.PI / 2); gg.translate(s.x, y, s.z);
        var gm = new THREE.MeshStandardMaterial({ color: 0xe9eefb, transparent: true, opacity: DAY ? 0.24 : 0.32, roughness: 0.05, metalness: 0.25, envMapIntensity: 1.1, depthWrite: false, side: THREE.DoubleSide }); var glass = new THREE.Mesh(gg, gm); glass.name = 'HALO_DECK_GLASS_SKYWALK'; glass.renderOrder = 3; glass.userData.noMerge = true; g.add(glass);
        var parts = []; for (var m = 0; m < 72; m++) { var ma = m / 72 * Math.PI * 2, bx = new THREE.BoxGeometry(rOut - rIn, 0.1, 0.16); bx.translate((rIn + rOut) / 2, 0, 0); bx.rotateY(-ma); bx.translate(s.x, y + 0.02, s.z); parts.push(bx); }
        [rIn + 0.1, rIn + 6, rIn + 12, HALO_LAYOUT.playable_radius_m + 0.15, rOut - 0.15].forEach(function (mr) { var tr = new THREE.TorusGeometry(mr, 0.1, 5, 192); tr.rotateX(Math.PI / 2); tr.translate(s.x, y + 0.03, s.z); parts.push(tr); });
        var rail = new THREE.TorusGeometry(HALO_LAYOUT.playable_radius_m + 0.15, 0.075, 6, 192); rail.rotateX(Math.PI / 2); rail.translate(s.x, y + 1.1, s.z); parts.push(rail);
        for (var p = 0; p < 96; p++) { var pa = p / 96 * Math.PI * 2, post = new THREE.CylinderGeometry(0.035, 0.045, 1.1, 5); post.translate(s.x + Math.cos(pa) * (HALO_LAYOUT.playable_radius_m + 0.15), y + 0.55, s.z + Math.sin(pa) * (HALO_LAYOUT.playable_radius_m + 0.15)); parts.push(post); }
        var mg = mergeGeometries(parts.map(function (q) { return q.index ? q.toNonIndexed() : q; }).map(function (q) { ['uv', 'normal'].forEach(function (k2) { if (!q.attributes[k2]) q.computeVertexNormals(); }); return q; }), false); parts.forEach(function (q) { q.dispose(); });
        var frame = new THREE.Mesh(mg, M.chrome); frame.name = 'HALO_SKYWALK_FRAME'; frame.userData.noMerge = true; g.add(frame);
        var bal = new THREE.Mesh(new THREE.CylinderGeometry(HALO_LAYOUT.playable_radius_m + 0.15, HALO_LAYOUT.playable_radius_m + 0.15, 1.05, 192, 1, true), gm.clone()); bal.material.opacity = DAY ? 0.18 : 0.26; bal.name = 'HALO_SKYWALK_BALUSTRADE'; bal.position.set(s.x, y + 0.55, s.z); bal.renderOrder = 3; bal.userData.noMerge = true; g.add(bal); }
      /* compact civic root and the one normal boarding door */
      var root = new THREE.Mesh(new THREE.CylinderGeometry(HALO_LAYOUT.base_radius_m, 6.6, 0.7, 64), darkGlass); root.position.set(s.x, 0.35, s.z); g.add(root); var rootRim = new THREE.Mesh(new THREE.TorusGeometry(6.15, 0.12, 10, 64), M.trimWarm); rootRim.rotation.x = Math.PI / 2; rootRim.position.set(s.x, 0.72, s.z); g.add(rootRim);
      var entry = new THREE.Mesh(new THREE.CapsuleGeometry(1.25, 1.5, 8, 24), darkGlass); entry.position.set(HALO_LAYOUT.ground_dock.x + 0.5, 1.75, HALO_LAYOUT.ground_dock.z); entry.rotation.z = Math.PI / 2; g.add(entry); var pad = new THREE.Mesh(new THREE.RingGeometry(1.65, 2.25, 48), M.trim.clone()); pad.material.transparent = true; pad.material.opacity = 0.38; pad.rotation.x = -Math.PI / 2; pad.position.set(HALO_LAYOUT.ground_dock.x, 0.75, HALO_LAYOUT.ground_dock.z); g.add(pad);
      /* tall engineered trunk with continuous platinum load path; base footprint remains local */
      var profile = [[6.2, 0.7], [5.6, 7], [4.7, PH * 0.22], [4.15, PH * 0.58], [4.6, PH * 0.82], [7.5, PH - 18], [15, PH - 3.2]].map(function (p) { return new THREE.Vector2(p[0], p[1]); }); var trunkMat = new THREE.MeshStandardMaterial({ color: 0xb4bcc7, roughness: 0.42, metalness: 0.62, envMapIntensity: 0.6 }); applySurface(THREE, trunkMat, 'TOWER', SDT); var trunk = new THREE.Mesh(new THREE.LatheGeometry(profile, 64), trunkMat);   /* M8: tall 7.2 m tower panels with a thin storey band (the facade grid read as tiling on a 240 m monument) */ trunk.position.set(s.x, 0, s.z); trunk.geometry.computeVertexNormals(); g.add(trunk);
      var core = new THREE.Mesh(new THREE.CylinderGeometry(1.05, 1.35, PH - 2.0, 32), glassCore); core.position.set(s.x, PH * 0.5, s.z); g.add(core); var recess = new THREE.Mesh(new THREE.CylinderGeometry(1.5, 1.75, PH - 4, 32, 1, true, Math.PI * 0.72, Math.PI * 0.56), darkGlass); recess.position.set(s.x, PH * 0.5, s.z); recess.rotation.y = Math.PI * 0.86; g.add(recess);
      for (var c = 0; c < 3; c++) { var aa = c / 3 * Math.PI * 2; tube([new THREE.Vector3(s.x + Math.cos(aa) * 3.9, 2, s.z + Math.sin(aa) * 3.9), new THREE.Vector3(s.x + Math.cos(aa) * 4.3, PH * 0.48, s.z + Math.sin(aa) * 4.3), new THREE.Vector3(s.x + Math.cos(aa) * 6.4, PH - 5, s.z + Math.sin(aa) * 6.4)], 0.13, M.trim, 72, 8); }
      var spiralPts = []; for (var sp = 0; sp <= 96; sp++) { var st = sp / 96, sa = st * Math.PI * 5.5 + 0.7, sr = 5.1 - st * 0.4; spiralPts.push(new THREE.Vector3(s.x + Math.cos(sa) * sr, 2 + st * (PH - 6), s.z + Math.sin(sa) * sr)); } tube(spiralPts, 0.16, M.trim, 128, 8);
      /* twelve primary boughs and twenty-four secondary ribs make the enlarged disc visibly load-bearing */
      for (var b = 0; b < 12; b++) { var ang = b / 12 * Math.PI * 2 + 0.13, ca = Math.cos(ang), sa2 = Math.sin(ang), side = b % 2 ? 1 : -1; var pts = [new THREE.Vector3(s.x + ca * 4.8, PH * 0.56, s.z + sa2 * 4.8), new THREE.Vector3(s.x + ca * 28 - sa2 * side * 5, PH * 0.72, s.z + sa2 * 28 + ca * side * 5), new THREE.Vector3(s.x + ca * 82, PH - 16, s.z + sa2 * 82), new THREE.Vector3(s.x + ca * (PR - 5), PH - 2.1, s.z + sa2 * (PR - 5))]; tube(pts, 2.05, b % 2 ? M.chrome : M.platinum, 72, 12); var joint = new THREE.Mesh(new THREE.SphereGeometry(2.35, 18, 12), M.chrome); joint.position.copy(pts[3]); g.add(joint); }
      for (var srib = 0; srib < 24; srib++) { var ar = srib / 24 * Math.PI * 2, crx = Math.cos(ar), crz = Math.sin(ar); tube([new THREE.Vector3(s.x + crx * 25, PH - 28, s.z + crz * 25), new THREE.Vector3(s.x + crx * 78, PH - 15, s.z + crz * 78), new THREE.Vector3(s.x + crx * (PR - 2), PH - 1.7, s.z + crz * (PR - 2))], 0.56, M.chrome, 48, 8); }
      /* upper structural deck plus broad, shared-endpoint class gradients */
      var under = new THREE.Mesh(new THREE.CylinderGeometry(PR, PR * 0.92, 3.2, 128, 1, true), darkGlass); under.name = 'HALO_DECK_SIDE_SKIRT'; under.position.set(s.x, PH - 1.6, s.z); g.add(under); var underside = new THREE.Mesh(new THREE.CircleGeometry(GLASS_IN - 1.2, 128), darkGlass); underside.name = 'HALO_DECK_UNDERSIDE'; underside.rotation.x = Math.PI / 2; underside.position.set(s.x, PH - 3.2, s.z); g.add(underside); deckSurface(GLASS_IN, PH); glassSkywalk(GLASS_IN, PR, PH);   /* one opaque floor owner: the former two coincident cylinder caps and transparent full-area overlays are gone */
      [48, 96, HALO_LAYOUT.playable_radius_m].forEach(function (rr, ri) { var ring = new THREE.Mesh(new THREE.TorusGeometry(rr, ri === 2 ? 0.22 : 0.12, 10, 128), ri === 2 ? M.trim : M.chrome); ring.rotation.x = Math.PI / 2; ring.position.set(s.x, PH + 0.11, s.z); g.add(ring); });
      /* sealed two-sided hemisphere and human-scale frame rhythm */
      var domeGlass = new THREE.ShaderMaterial({ transparent: true, depthWrite: false, side: THREE.DoubleSide, uniforms: { uDay: { value: DAY ? 1 : 0 } },   /* WORLD PIVOT PASS 4: iridescent fresnel glass — clear face-on, lavender / blue / rose sheen at grazing angles (the glass-ribbon reference) */
        vertexShader: 'varying vec3 vN; varying vec3 vV; varying vec3 vW; void main() { vec4 w = modelMatrix * vec4(position, 1.0); vW = w.xyz; vN = normalize(mat3(modelMatrix) * normal); vV = normalize(cameraPosition - w.xyz); gl_Position = projectionMatrix * viewMatrix * w; }',
        fragmentShader: 'uniform float uDay; varying vec3 vN; varying vec3 vV; varying vec3 vW; void main() { float f = pow(1.0 - abs(dot(normalize(vN), normalize(vV))), 2.6); float ph = 0.5 + 0.5 * sin(vW.y * 0.035 + atan(vN.z, vN.x) * 3.0); vec3 iri = mix(mix(vec3(0.74, 0.84, 1.0), vec3(0.84, 0.74, 1.0), ph), vec3(1.0, 0.8, 0.93), f * 0.6); float a = mix(uDay > 0.5 ? 0.035 : 0.06, uDay > 0.5 ? 0.46 : 0.58, f); vec3 c = iri * mix(uDay > 0.5 ? 1.05 : 0.55, uDay > 0.5 ? 1.25 : 0.9, f); gl_FragColor = vec4(c, a);\n#include <colorspace_fragment>\n}' });
      var dome = new THREE.Mesh(new THREE.SphereGeometry(DR, 96, 40, 0, Math.PI * 2, 0, Math.PI / 2), domeGlass); dome.position.set(s.x, PH, s.z); dome.renderOrder = 4; g.add(dome);
      (function () { var parts = [], MER = 24;   /* WORLD PIVOT PASS 4: a fine merged lattice (24 meridians + 6 parallels + a crown ring, ONE draw) replaces 16 heavy ribs + 4 rings */
        for (var rb = 0; rb < MER; rb++) { var ra = rb / MER * Math.PI * 2, pts = []; for (var q = 0; q <= 16; q++) { var th = q / 16 * (Math.PI / 2 - 0.03), rr = DR * Math.cos(th) - 0.12; pts.push(new THREE.Vector3(s.x + Math.cos(ra) * rr, PH + DR * Math.sin(th), s.z + Math.sin(ra) * rr)); } parts.push(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts), 40, rb % 3 === 0 ? 0.3 : 0.17, 5, false)); }
        [0.16, 0.32, 0.48, 0.63, 0.77, 0.89].forEach(function (f) { var th = Math.asin(f), rr = DR * Math.cos(th) - 0.12, t2 = new THREE.TorusGeometry(rr, 0.15, 5, 160); t2.rotateX(Math.PI / 2); t2.translate(s.x, PH + DR * f, s.z); parts.push(t2); });
        var crown = new THREE.TorusGeometry(DR * 0.2, 0.34, 6, 96); crown.rotateX(Math.PI / 2); crown.translate(s.x, PH + DR * Math.sin(Math.acos(0.2)), s.z); parts.push(crown);
        var lat = new THREE.Mesh(mergeGeometries(parts.map(function (q) { return q.index ? q.toNonIndexed() : q; }), false), M.chrome); parts.forEach(function (q) { q.dispose(); }); lat.name = 'HALO_DOME_LATTICE'; lat.userData.noMerge = true; g.add(lat); })();
      (function () {   /* WORLD PIVOT PASS 4: the RIM COLONNADE — 40 slender platinum columns between the playable edge (144.8 m) and the shell, meeting the
        glass at ~20 m, each with an inner white-light strip and a capital, a chrome cornice ring on top: the circular promenade gets a
        human-scale rhythm. Beyond the host limit, so nothing here can be walked or flown into. Merged: 3 draws. */
        var RC = HALO_LAYOUT.playable_radius_m + 1.4, H2 = Math.sqrt(Math.max(1, DR * DR - RC * RC)) - 0.6, colP = [], litP = [], corP = [];
        for (var cI = 0; cI < 40; cI++) { var ca2 = cI / 40 * Math.PI * 2 + 0.04, cx2 = s.x + Math.cos(ca2) * RC, cz2 = s.z + Math.sin(ca2) * RC;
          var col = new THREE.CylinderGeometry(0.36, 0.52, H2, 10); col.translate(cx2, PH + H2 / 2, cz2); colP.push(col); var pl = new THREE.CylinderGeometry(0.8, 0.9, 0.5, 10); pl.translate(cx2, PH + 0.25, cz2); colP.push(pl);
          var strip2 = new THREE.BoxGeometry(0.07, H2 * 0.82, 0.07); strip2.translate(s.x + Math.cos(ca2) * (RC - 0.42), PH + H2 * 0.5, s.z + Math.sin(ca2) * (RC - 0.42)); litP.push(strip2);
          var capG = new THREE.CylinderGeometry(0.75, 0.4, 0.55, 10); capG.translate(cx2, PH + H2 - 0.2, cz2); litP.push(capG); }
        var cor = new THREE.TorusGeometry(RC, 0.34, 6, 200); cor.rotateX(Math.PI / 2); cor.translate(s.x, PH + H2, s.z); corP.push(cor);
        [[colP, M.platinum, 'HALO_RIM_COLONNADE'], [litP, M.trim, 'HALO_RIM_LIGHTS'], [corP, M.chrome, 'HALO_RIM_CORNICE']].forEach(function (P) { var mg = mergeGeometries(P[0].map(function (q) { return q.index ? q.toNonIndexed() : q; }), false); P[0].forEach(function (q) { q.dispose(); }); var mm = new THREE.Mesh(mg, P[1]); mm.name = P[2]; mm.userData.noMerge = true; g.add(mm); }); })();
      (function () {   /* WORLD PIVOT PASS 4: three suspended CELESTIAL RINGS high above the centre (reference: elegant luminous rings) — white light with a
        lavender core, slowly counter-rotating (fieldScene.tick), visible from the deck and from the ground through the dome glass. Decorative,
        never solid. */
        var rg = new THREE.Group(); rg.name = 'HALO_CELESTIAL_RINGS'; rg.userData.noMerge = true; rg.position.set(s.x, PH + 95, s.z);
        var rm = new THREE.MeshStandardMaterial({ color: 0xf2f0ff, emissive: 0xe4d8ff, emissiveIntensity: DAY ? 0.85 : 1.6, roughness: 0.25, metalness: 0.4 });
        [[26, 0.42, 0.18], [34, 0.3, -0.26], [42, 0.52, 0.34]].forEach(function (R3, i) { var t3 = new THREE.Mesh(new THREE.TorusGeometry(R3[0], R3[1], 8, 220), rm); t3.rotation.x = Math.PI / 2 + R3[2]; t3.rotation.y = i * 0.7; t3.userData.spin = (i % 2 ? -1 : 1) * (0.025 + i * 0.01); rg.add(t3); });
        g.add(rg); })();
      var zenith = new THREE.Mesh(new THREE.OctahedronGeometry(1.3, 1), M.diamond); zenith.scale.y = 1.45; zenith.position.set(s.x, HALO_LAYOUT.apex_height_m + 0.4, s.z); g.add(zenith);
      /* civic programme at human scale: arrival court, overlooks, rest bays, guide focus */
      for (var bn = 0; bn < 12; bn++) { var ba = bn / 12 * Math.PI * 2 + 0.12, br = bn % 2 ? 104 : 57; var bench = new THREE.Mesh(roundedBox(2.0, 0.42, 0.62, 0.2), M.platinum); bench.position.set(s.x + Math.cos(ba) * br, PH + 0.22, s.z + Math.sin(ba) * br); bench.rotation.y = -ba + Math.PI / 2; g.add(bench); var lamp = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.1, 1.3, 8), M.chrome); lamp.position.set(s.x + Math.cos(ba + 0.035) * (br + 2.1), PH + 0.65, s.z + Math.sin(ba + 0.035) * (br + 2.1)); g.add(lamp); }
      for (var bay = 0; bay < 5; bay++) { var bya = bay / 5 * Math.PI * 2 + 0.35, bx = s.x + Math.cos(bya) * 126, bz = s.z + Math.sin(bya) * 126; var court = new THREE.Mesh(new THREE.CylinderGeometry(6.2, 6.5, 0.24, 48), M.chrome); court.position.set(bx, PH + 0.12, bz); g.add(court); var courtRing = new THREE.Mesh(new THREE.TorusGeometry(6.05, 0.11, 8, 48), M.trim); courtRing.rotation.x = Math.PI / 2; courtRing.position.set(bx, PH + 0.31, bz); g.add(courtRing); var marker = new THREE.Mesh(new THREE.OctahedronGeometry(0.95, 1), M.diamond); marker.position.set(bx, PH + 1.55, bz); g.add(marker); for (var pc = 0; pc < 4; pc++) { var pa = bya + pc / 4 * Math.PI * 2 + 0.38, crystal = new THREE.Mesh(new THREE.OctahedronGeometry(0.62 + (pc % 2) * 0.18, 1), pc % 2 ? M.diamond : M.trim); crystal.scale.y = 1.7 + (pc % 3) * 0.28; crystal.position.set(bx + Math.cos(pa) * 4.25, PH + 1.0, bz + Math.sin(pa) * 4.25); g.add(crystal); } for (var pb = -1; pb <= 1; pb += 2) { var pocketBench = new THREE.Mesh(roundedBox(1.8, 0.4, 0.58, 0.18), M.platinum); pocketBench.position.set(bx + Math.cos(bya + Math.PI / 2) * pb * 3.1, PH + 0.22, bz + Math.sin(bya + Math.PI / 2) * pb * 3.1); pocketBench.rotation.y = -bya + Math.PI / 2; g.add(pocketBench); } }
      var HL = HALO_PLAY_LAYOUT, sport = new THREE.Group(); sport.name = 'HALO_VOLLEY_COURT'; sport.userData.noMerge = true; var courtMat = M.platinum.clone(); courtMat.color.setHex(0x8496a9); courtMat.roughness = 0.34; var sportDeck = new THREE.Mesh(roundedBox(HL.half_length_m * 2, 0.12, HL.half_width_m * 2, 0.28), courtMat); sportDeck.position.set(HL.center.x, PH + 0.06, HL.center.z); sport.add(sportDeck); var lineMat = M.trim.clone(); lineMat.emissiveIntensity *= 0.72; [[0, 0, 0.055, HL.half_width_m * 2], [-HL.half_length_m, 0, 0.08, HL.half_width_m * 2], [HL.half_length_m, 0, 0.08, HL.half_width_m * 2], [0, -HL.half_width_m, HL.half_length_m * 2, 0.08], [0, HL.half_width_m, HL.half_length_m * 2, 0.08]].forEach(function (ln) { var lm = new THREE.Mesh(roundedBox(ln[2] || 0.06, 0.035, ln[3] || 0.06, 0.02), lineMat); lm.position.set(HL.center.x + ln[0], PH + 0.135, HL.center.z + ln[1]); sport.add(lm); }); for (var np = -1; np <= 1; np += 2) { var post = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.09, HL.net_height_m + 0.28, 12), M.chrome); post.position.set(HL.center.x, PH + (HL.net_height_m + 0.28) / 2, HL.center.z + np * (HL.half_width_m + 0.12)); sport.add(post); } var netMat = glassCore.clone(); netMat.opacity = DAY ? 0.22 : 0.34; netMat.wireframe = true; var net = new THREE.Mesh(new THREE.PlaneGeometry(HL.half_width_m * 2, HL.net_height_m, 18, 6), netMat); net.rotation.y = Math.PI / 2; net.position.set(HL.center.x, PH + HL.net_height_m / 2, HL.center.z); sport.add(net); HL.targets.forEach(function (tt) { var tm = new THREE.Mesh(new THREE.TorusGeometry(tt.radius_m, 0.055, 8, 40), tt.id === 'CENTER' ? M.trimWarm : M.trim); tm.rotation.x = Math.PI / 2; tm.position.set(tt.x, PH + 0.17, tt.z); sport.add(tm); }); var sportLabel = nameSprite('MAH HALO · VOLLEY / SERVE LAB'); sportLabel.position.set(HL.entry.x, PH + 2.7, HL.entry.z - 2.8); sportLabel.scale.set(8.8, 1.2, 1); sport.add(sportLabel); var sportBall = new THREE.Mesh(new THREE.SphereGeometry(HL.ball_radius_m, 20, 14), M.diamond); sportBall.name = 'HALO_VOLLEY_BALL'; sportBall.visible = false; sport.add(sportBall); var ballShadow = new THREE.Mesh(new THREE.CircleGeometry(0.3, 24), new THREE.MeshBasicMaterial({ color: 0x07101d, transparent: true, opacity: 0.34, depthWrite: false })); ballShadow.name = 'HALO_VOLLEY_BALL_SHADOW'; ballShadow.rotation.x = -Math.PI / 2; ballShadow.visible = false; sport.add(ballShadow); g.add(sport); g.userData.sport = { group: sport, ball: sportBall, shadow: ballShadow };
      var focus = new THREE.Mesh(new THREE.OctahedronGeometry(0.8, 1), M.diamond); focus.position.set(HALO_LAYOUT.guide.x, PH + 1.35, HALO_LAYOUT.guide.z); g.add(focus); var focusHalo = new THREE.Mesh(new THREE.TorusGeometry(1.25, 0.055, 8, 40), M.trim); focusHalo.rotation.x = Math.PI / 2; focusHalo.position.set(HALO_LAYOUT.guide.x, PH + 0.72, HALO_LAYOUT.guide.z); g.add(focusHalo);
      /* One finished human-scale walk-in cabin. Its group origin is the floor/host
         carrier origin, so the passenger and car consume the exact same pose. */
      var cabin = new THREE.Group(); cabin.name = 'MAH_ASCENT_CABIN'; cabin.userData.noMerge = true; var cabFloor = new THREE.Mesh(new THREE.CylinderGeometry(1.72, 1.72, 0.16, 40), M.platinum); cabFloor.position.y = 0.08; cabin.add(cabFloor); var cabCeil = new THREE.Mesh(new THREE.CylinderGeometry(1.72, 1.64, 0.18, 40), M.chrome); cabCeil.position.y = 3.12; cabin.add(cabCeil); var cabWallMat = glassCore.clone(); cabWallMat.opacity = DAY ? 0.25 : 0.34; var cabWall = new THREE.Mesh(new THREE.CylinderGeometry(1.68, 1.68, 2.84, 40, 1, true, Math.PI * 0.12, Math.PI * 1.76), cabWallMat); cabWall.position.y = 1.62; cabin.add(cabWall); for (var cp = 0; cp < 4; cp++) { var cpa = cp / 4 * Math.PI * 2 + Math.PI / 4, rail = new THREE.Mesh(new THREE.CylinderGeometry(0.055, 0.07, 2.92, 10), M.chrome); rail.position.set(Math.cos(cpa) * 1.58, 1.62, Math.sin(cpa) * 1.58); cabin.add(rail); } var cr = new THREE.Mesh(new THREE.TorusGeometry(1.62, 0.075, 8, 40), M.trim); cr.rotation.x = Math.PI / 2; cr.position.y = 0.2; cabin.add(cr); var cr2 = cr.clone(); cr2.position.y = 3.0; cabin.add(cr2); var doorMat = cabWallMat.clone(), doorL = new THREE.Mesh(roundedBox(0.74, 2.54, 0.075, 0.1), doorMat), doorR = doorL.clone(); doorL.position.set(-0.4, 1.48, 1.61); doorR.position.set(0.4, 1.48, 1.61); cabin.add(doorL); cabin.add(doorR); var cabinGem = new THREE.Mesh(new THREE.OctahedronGeometry(0.28, 1), M.diamond); cabinGem.position.y = 3.47; cabin.add(cabinGem); cabin.position.set(HALO_LAYOUT.ground_dock.x, 0, HALO_LAYOUT.ground_dock.z); g.add(cabin);
      var shaft = new THREE.Mesh(new THREE.CylinderGeometry(0.055, 0.055, PH - 0.4, 8), M.trim); shaft.position.set(cabin.position.x - 0.92, PH / 2, s.z); g.add(shaft); var dockHalo = new THREE.Mesh(new THREE.RingGeometry(2.2, 3.8, 64), M.trim.clone()); dockHalo.material.transparent = true; dockHalo.material.opacity = 0.28; dockHalo.rotation.x = -Math.PI / 2; dockHalo.position.set(HALO_LAYOUT.upper_dock.x, PH + 0.08, HALO_LAYOUT.upper_dock.z); g.add(dockHalo);
      for (var dp = -1; dp <= 1; dp += 2) { var dockPylon = new THREE.Mesh(new THREE.CylinderGeometry(0.16, 0.22, 3.1, 12), M.chrome); dockPylon.position.set(HALO_LAYOUT.upper_dock.x + dp * 1.75, PH + 1.55, HALO_LAYOUT.upper_dock.z + 2.0); g.add(dockPylon); } var dockLintel = new THREE.Mesh(roundedBox(3.8, 0.24, 0.32, 0.12), M.platinum); dockLintel.position.set(HALO_LAYOUT.upper_dock.x, PH + 3.05, HALO_LAYOUT.upper_dock.z + 2.0); g.add(dockLintel); var dockGem = new THREE.Mesh(new THREE.OctahedronGeometry(0.42, 1), M.diamond); dockGem.position.set(HALO_LAYOUT.upper_dock.x, PH + 3.7, HALO_LAYOUT.upper_dock.z + 2.0); g.add(dockGem);
      var label = nameSprite('MAH ASCENT · RETURN'); label.position.set(HALO_LAYOUT.upper_dock.x, PH + 3.45, HALO_LAYOUT.upper_dock.z + 1.8); label.scale.set(7.4, 1.25, 1); g.add(label);
      g.userData.cabin = cabin; g.userData.cabinGlass = cabWallMat; g.userData.cabinDoors = [doorL, doorR]; g.userData.platformH = PH; g.userData.baseY = 0; g.userData.floorOwners = { visible_top: 'HALO_DECK_SINGLE_TOP', top_y_m: PH, full_area_opaque_owners: 1, transparent_full_area_overlays: 0, side_open_ended: true }; g.userData.treeAscentEnvelope = { contract: HALO_LAYOUT.contract, base_radius_m: HALO_LAYOUT.base_radius_m, trunk_height_m: PH, deck_height_m: PH, realm_radius_m: HALO_LAYOUT.playable_radius_m, structural_deck_radius_m: PR, playable_radius_m: HALO_LAYOUT.playable_radius_m, dome_radius_m: DR, dome_diameter_m: HALO_LAYOUT.shell_diameter_m, dome_apex_m: HALO_LAYOUT.apex_height_m, boarding_x: cabin.position.x, boarding_z: s.z, cabin_half_width_m: HALO_LAYOUT.carrier.half_width_m, cabin_half_depth_m: HALO_LAYOUT.carrier.half_depth_m, cabin_clear_height_m: HALO_LAYOUT.carrier.clear_height_m, elevator_only: true };
      group.add(g); return g; },
    /* residential pod: a rounded platinum shell with a luminous seam and a soft door light */
    pod: function (s) { var g = new THREE.Group(); var body = new THREE.Mesh(new THREE.SphereGeometry(s.r, 24, 16, 0, Math.PI * 2, 0, Math.PI * 0.55), M.platinum); body.scale.y = s.h / s.r * 0.75; body.position.set(s.x, 0, s.z); g.add(body); var seam = new THREE.Mesh(new THREE.TorusGeometry(s.r * 0.98, 0.05, 8, 40), M.trim); seam.rotation.x = Math.PI / 2; seam.position.set(s.x, s.h * 0.45, s.z); g.add(seam); var door = new THREE.Mesh(roundedBox(1.1, 2.0, 0.3, 0.4), M.doorway); door.position.set(s.x, 0, s.z + s.r - 0.1); g.add(door); var dm = new THREE.Mesh(new THREE.CircleGeometry(1.2, 24), M.trimWarm.clone()); dm.material.transparent = true; dm.material.opacity = 0.16; dm.rotation.x = -Math.PI / 2; dm.position.set(s.x, 0.02, s.z + s.r + 1.0); g.add(dm); group.add(g); return g; },
    materials: M
  };
  return api;
}
