/* MAHWORLD :: GRANULAR CRYSTALLINE DUST (owner assignment 2026-09-18 §8 — ORIGINAL CANDIDATE presentation language, not an owner specification)
   Many sharply directed, glitter-like crystalline particles, dense enough to form readable temporary waves / volumes while still looking granular.
   One pooled THREE.Points emitter per effect; per-particle life / velocity / size / glint phase in typed arrays; coherent flow authored per FORMATION:
     GATHER  — particles gather along a limb segment (hand ← forearm) and FOLLOW it (they live in the limb's frame), with a mild swirl; a localized
               contact burst on impact; a short fading wake — never a detached ranged weapon (physical MAHGIC).
     WAVE    — a compact travelling front at a projectile head: a crescent of particles moving with the head plus trailing directional filaments;
               terminates where the authoritative entity terminates (hit / obstacle / range) and breaks up there (offensive special MAHGIC push).
     CURTAIN — a descending curtain / bounded column over the aimed target area: particles born above the area fall with an inward spiral and break
               into dust at the floor (offensive special MAHGIC vertical pull — the owner's explicit example).
     BURST   — the terminal scatter at an impact point (consumed on contact, then dissipates).
   Glints are coherent: only a bounded fraction of particles glints at a time, each glint lasts several frames (phase-driven, never per-frame random),
   so nothing reads as aliasing or pixel noise. Colour = the caster's class energy (Athlete gold). Budget = base counts × the quality tier's particle
   factor; ring buffers, no allocation per frame, no per-particle physics beyond one integration step. */
export function createDustSystem(THREE, opts) {
  var o = opts || {}; var qualityRef = o.quality || null; var TEX = null; var POOL = []; var LIVE = []; var MAX_LIVE = o.max_live || 14;
  function tex() { if (TEX) return TEX; var c = document.createElement('canvas'); c.width = c.height = 32; var g = c.getContext('2d'); g.clearRect(0, 0, 32, 32);
    /* a small facet: a bright rotated square core with four short spikes — reads as a crystalline grain, not a soft ball */
    g.save(); g.translate(16, 16); g.rotate(Math.PI / 4); var grd = g.createRadialGradient(0, 0, 0, 0, 0, 7); grd.addColorStop(0, 'rgba(255,255,255,1)'); grd.addColorStop(0.55, 'rgba(255,255,255,0.75)'); grd.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = grd; g.fillRect(-7, -7, 14, 14); g.restore();
    g.strokeStyle = 'rgba(255,255,255,0.9)'; g.lineWidth = 1.2; g.beginPath(); g.moveTo(16, 2); g.lineTo(16, 30); g.moveTo(2, 16); g.lineTo(30, 16); g.stroke();
    TEX = new THREE.CanvasTexture(c); TEX.minFilter = THREE.LinearFilter; TEX.magFilter = THREE.LinearFilter; return TEX; }
  function factor() { var T = qualityRef && qualityRef.get ? qualityRef.get() : null; return T && T.particles ? T.particles : 1; }
  function make(n) { var geo = new THREE.BufferGeometry(); var pos = new Float32Array(n * 3), col = new Float32Array(n * 3), siz = new Float32Array(n); geo.setAttribute('position', new THREE.BufferAttribute(pos, 3)); geo.setAttribute('color', new THREE.BufferAttribute(col, 3)); geo.attributes.position.setUsage(THREE.DynamicDrawUsage); geo.attributes.color.setUsage(THREE.DynamicDrawUsage);
    var mat = new THREE.PointsMaterial({ map: tex(), size: 0.09, vertexColors: true, transparent: true, opacity: 1, depthWrite: false, blending: THREE.AdditiveBlending, sizeAttenuation: true }); var pts = new THREE.Points(geo, mat); pts.frustumCulled = false; pts.userData.vfx = true;
    return { n: n, pts: pts, pos: pos, col: col, vel: new Float32Array(n * 3), life: new Float32Array(n), age: new Float32Array(n), seed: new Float32Array(n), alive: new Uint8Array(n), head: 0, count: 0 }; }
  function acquire(n) { for (var i = 0; i < POOL.length; i++) if (POOL[i].n === n) return POOL.splice(i, 1)[0]; return make(n); }
  function release(em) { em.count = 0; em.alive.fill(0); if (em.pts.parent) em.pts.parent.remove(em.pts); if (POOL.length < 12) POOL.push(em); else { em.pts.geometry.dispose(); em.pts.material.dispose(); } }
  function spawn(em, x, y, z, vx, vy, vz, life, seed) { var i = em.head; em.head = (em.head + 1) % em.n; if (em.alive[i]) em.count--; em.alive[i] = 1; em.count++; em.pos[i * 3] = x; em.pos[i * 3 + 1] = y; em.pos[i * 3 + 2] = z; em.vel[i * 3] = vx; em.vel[i * 3 + 1] = vy; em.vel[i * 3 + 2] = vz; em.life[i] = life; em.age[i] = 0; em.seed[i] = seed === undefined ? Math.random() : seed; }
  var C = new THREE.Color(); var V = new THREE.Vector3(), W = new THREE.Vector3(), U = new THREE.Vector3();
  /* one integration + glint pass; `flow(i, dt)` lets a formation steer live particles (coherent motion), `floorY` breaks falling particles into dust */
  function step(fx, dt) { var em = fx.em; var col = fx.color; var f = fx.form; var base = f.brightness || 1; var t = fx.t; var glintFrac = 0.14; var live = 0;
    for (var i = 0; i < em.n; i++) { if (!em.alive[i]) { em.pos[i * 3 + 1] = -1e3; em.col[i * 3] = 0; em.col[i * 3 + 1] = 0; em.col[i * 3 + 2] = 0; continue; }
      em.age[i] += dt; if (em.age[i] >= em.life[i]) { em.alive[i] = 0; em.count--; em.pos[i * 3 + 1] = -1e3; em.col[i * 3] = 0; em.col[i * 3 + 1] = 0; em.col[i * 3 + 2] = 0; continue; } live++;
      if (f.flow) f.flow(fx, i, dt);
      em.pos[i * 3] += em.vel[i * 3] * dt; em.pos[i * 3 + 1] += em.vel[i * 3 + 1] * dt; em.pos[i * 3 + 2] += em.vel[i * 3 + 2] * dt;
      if (f.gravity) em.vel[i * 3 + 1] -= f.gravity * dt; if (f.drag) { var k = Math.max(0, 1 - f.drag * dt); em.vel[i * 3] *= k; em.vel[i * 3 + 1] *= k; em.vel[i * 3 + 2] *= k; }
      if (f.floorY !== undefined && em.pos[i * 3 + 1] < f.floorY) { em.pos[i * 3 + 1] = f.floorY; if (em.vel[i * 3 + 1] < 0) { var sp = Math.abs(em.vel[i * 3 + 1]); var a = em.seed[i] * Math.PI * 2; em.vel[i * 3] = Math.cos(a) * sp * 0.5; em.vel[i * 3 + 2] = Math.sin(a) * sp * 0.5; em.vel[i * 3 + 1] = 0; em.life[i] = Math.min(em.life[i], em.age[i] + 0.35); } }   /* the column breaks into dust at the floor */
      var u = em.age[i] / em.life[i]; var fade = u < 0.15 ? u / 0.15 : (1 - u) / 0.85; var ph = (t * (2.4 + em.seed[i] * 3.2) + em.seed[i] * 17) % 1; var glint = ph < glintFrac ? (1 + 2.2 * Math.sin(Math.PI * ph / glintFrac)) : 1;   /* a glint lasts ~glintFrac of its own period (several frames), phase-driven */
      var b = base * fade * glint * (0.55 + 0.45 * em.seed[i]); em.col[i * 3] = col.r * b; em.col[i * 3 + 1] = col.g * b; em.col[i * 3 + 2] = col.b * b; }
    em.pts.geometry.attributes.position.needsUpdate = true; em.pts.geometry.attributes.color.needsUpdate = true; return live; }
  var api = {
    /* emit(kind, params) → handle; params: { color, parent (Object3D), count } + kind-specific; the handle is updated with api.update(dt) each frame */
    emit: function (kind, p) { var n = Math.max(6, Math.round((p.count || 60) * factor())); var em = acquire(n); (p.parent || o.scene).add(em.pts); em.pts.position.set(0, 0, 0); em.pts.material.size = p.size || (kind === 'WAVE' ? 0.16 : kind === 'CURTAIN' ? 0.15 : kind === 'BURST' ? 0.14 : 0.12);   /* presence at gameplay distance: a grain is ~15 cm of glinting facet, still granular */
      var fx = { kind: kind, em: em, t: 0, color: new THREE.Color(p.color === undefined ? 0xffc34d : p.color), form: { brightness: p.brightness || 1.7 }, p: p, done: false, emitting: true, stopT: -1, live: 0 };
      if (kind === 'GATHER') { fx.form.drag = 3.5; fx.local = new Float32Array(n * 3); fx.anchor = new THREE.Vector3(); fx.dir = new THREE.Vector3(0, -1, 0); fx.prevAnchor = null; fx.rate = p.rate || 160; fx.acc = 0; fx.form.flow = function (F, i, dt2) { /* particles live in the limb frame: offset = local (along + radial + swirl) re-expressed from the current anchor each frame; the swirl advances the local angle */ var L = F.local; var a = L[i * 3] += dt2 * 6.0; var r = L[i * 3 + 1]; var s = L[i * 3 + 2]; var dx = Math.cos(a) * r, dz = Math.sin(a) * r; var ax = F.anchor.x + F.dir.x * s, ay = F.anchor.y + F.dir.y * s, az = F.anchor.z + F.dir.z * s; var em2 = F.em; em2.pos[i * 3] += (ax + dx - em2.pos[i * 3]) * Math.min(1, dt2 * 18); em2.pos[i * 3 + 1] += (ay - em2.pos[i * 3 + 1]) * Math.min(1, dt2 * 18); em2.pos[i * 3 + 2] += (az + dz - em2.pos[i * 3 + 2]) * Math.min(1, dt2 * 18); }; }
      if (kind === 'WAVE') { fx.form.drag = 1.2; fx.head = new THREE.Vector3(); fx.heading = 0; fx.rate = p.rate || 420; fx.acc = 0; fx.width = p.width || 0.7; fx.shape = p.shape || 'crescent'; }   /* shapes: crescent (the vector front), rod (a dense arm-length lance behind the head), ring (a flat expanding clap disc) */
      if (kind === 'CURTAIN') { fx.form.gravity = 9.0; fx.form.drag = 0.6; fx.form.floorY = p.floorY !== undefined ? p.floorY : 0.03; fx.center = new THREE.Vector3(p.x || 0, p.floorY || 0, p.z || 0); fx.radius = p.radius || 1.0; fx.top = p.top || 2.8; fx.rate = p.rate || 520; fx.acc = 0; fx.form.flow = function (F, i, dt2) { /* inward spiral: the fall curls toward the column axis */ var em2 = F.em; var dx = em2.pos[i * 3] - F.center.x, dz = em2.pos[i * 3 + 2] - F.center.z; var d = Math.hypot(dx, dz) || 1e-4; var tang = 1.6; em2.vel[i * 3] += (-dx / d * 1.1 - dz / d * tang) * dt2; em2.vel[i * 3 + 2] += (-dz / d * 1.1 + dx / d * tang) * dt2; }; }
      if (kind === 'BURST') { fx.form.gravity = 4.0; fx.form.drag = 2.2; fx.form.floorY = p.floorY !== undefined ? p.floorY : 0.03; var cnt = n; var dirx = p.dirx || 0, dirz = p.dirz || 0; for (var k = 0; k < cnt; k++) { var a = Math.random() * Math.PI * 2, el = (Math.random() - 0.3) * 1.2; var sp = (p.speed || 3.2) * (0.5 + Math.random()); var vx = Math.cos(a) * Math.cos(el) * sp + dirx * sp * 0.8, vz = Math.sin(a) * Math.cos(el) * sp + dirz * sp * 0.8, vy = Math.sin(el) * sp + 1.2; spawn(em, p.x || 0, p.y || 1, p.z || 0, vx, vy, vz, 0.28 + Math.random() * 0.3); } fx.emitting = false; }
      LIVE.push(fx); if (LIVE.length > MAX_LIVE) { var old = LIVE.shift(); api.dispose(old); } return fx; },
    /* GATHER: the limb frame this frame — anchor = the hand's world position, dir = unit vector hand → forearm (the segment the dust lives on) */
    gather: function (fx, hand, elbow, amount) { if (fx.kind !== 'GATHER' || fx.done) return; fx.anchor.copy(hand); fx.dir.subVectors(elbow, hand); var len = fx.dir.length() || 0.25; fx.dir.multiplyScalar(1 / len); fx.segLen = Math.min(len, 0.34); fx.amount = amount === undefined ? 1 : amount; },
    /* WAVE: the projectile head this frame */
    wave: function (fx, head, heading) { if (fx.kind !== 'WAVE' || fx.done) return; fx.head.copy(head); fx.heading = heading; },
    stop: function (fx) { if (!fx || fx.done) return; fx.emitting = false; fx.stopT = fx.t; },
    /* the terminal scatter of a GATHER (contact) or a WAVE (hit / obstacle / range): stop emitting and throw the live grains outward from `at` */
    scatter: function (fx, at, dirx, dirz, speed) { if (!fx || fx.done) return; api.stop(fx); var em = fx.em; for (var i = 0; i < em.n; i++) { if (!em.alive[i]) continue; var a = Math.random() * Math.PI * 2, el = (Math.random() - 0.2) * 1.0; var sp = (speed || 2.6) * (0.4 + Math.random()); em.vel[i * 3] = Math.cos(a) * Math.cos(el) * sp + (dirx || 0) * sp * 0.7; em.vel[i * 3 + 1] = Math.sin(el) * sp + 0.8; em.vel[i * 3 + 2] = Math.sin(a) * Math.cos(el) * sp + (dirz || 0) * sp * 0.7; em.life[i] = Math.min(em.life[i], em.age[i] + 0.22 + Math.random() * 0.2); } fx.form.gravity = 4.0; fx.form.drag = 2.0; fx.form.flow = null; },
    update: function (dt) { dt = Math.min(0.25, Math.max(0, dt));   /* grains age by wall-clock (a stalled frame does not stretch a trail) */ for (var i = LIVE.length - 1; i >= 0; i--) { var fx = LIVE[i]; fx.t += dt; var em = fx.em;
        if (fx.emitting) { if (fx.kind === 'GATHER' && fx.segLen) { fx.acc += fx.rate * (fx.amount || 1) * dt; while (fx.acc >= 1) { fx.acc -= 1; var s = Math.random() * fx.segLen, r = 0.02 + Math.random() * 0.05, a = Math.random() * Math.PI * 2; var j = em.head; spawn(em, fx.anchor.x + fx.dir.x * s + Math.cos(a) * r, fx.anchor.y + fx.dir.y * s, fx.anchor.z + fx.dir.z * s + Math.sin(a) * r, 0, 0, 0, 0.32 + Math.random() * 0.25); fx.local[j * 3] = a; fx.local[j * 3 + 1] = r; fx.local[j * 3 + 2] = s; } }
          else if (fx.kind === 'WAVE') { fx.acc += fx.rate * dt; var fwdx = Math.sin(fx.heading), fwdz = -Math.cos(fx.heading); var rx = -fwdz, rz = fwdx; while (fx.acc >= 1) { fx.acc -= 1; if (fx.shape === 'rod') { var sb = Math.random() * 0.9, ur = (Math.random() * 2 - 1) * fx.width; spawn(em, fx.head.x - fwdx * sb + rx * ur, fx.head.y + (Math.random() - 0.5) * 0.08, fx.head.z - fwdz * sb + rz * ur, fwdx * 0.6, 0, fwdz * 0.6, 0.10 + Math.random() * 0.08); continue; } if (fx.shape === 'x') { var ud = (Math.random() * 2 - 1) * fx.width, dg = Math.random() < 0.5 ? 1 : -1; var latx = ud * 0.7071, upx = ud * 0.7071 * dg; spawn(em, fx.head.x + rx * latx - fwdx * 0.06 * Math.abs(ud), fx.head.y + upx, fx.head.z + rz * latx - fwdz * 0.06 * Math.abs(ud), fwdx * 0.5 + rx * ud * 0.4, upx * 0.4, fwdz * 0.5 + rz * ud * 0.4, 0.11 + Math.random() * 0.08); continue; }   /* B8 §12 A: the X — grains born along the two diagonals of the plane facing the travel */ if (fx.shape === 'ring') { var ar = Math.random() * Math.PI * 2, rr2 = fx.width * (0.85 + Math.random() * 0.3), lat2 = Math.cos(ar) * rr2, up2 = Math.sin(ar) * rr2; spawn(em, fx.head.x + rx * lat2, fx.head.y + up2, fx.head.z + rz * lat2, fwdx * 0.3 + rx * lat2 * 0.8, up2 * 0.8, fwdz * 0.3 + rz * lat2 * 0.8, 0.12 + Math.random() * 0.08); continue; } var u = (Math.random() * 2 - 1); var lat = u * fx.width; var back = 0.18 * u * u;   /* crescent: the wings trail the centre */ var tail = Math.random() < 0.28; var sp = tail ? -(0.5 + Math.random() * 1.0) : (0.2 + Math.random() * 0.6); spawn(em, fx.head.x + rx * lat - fwdx * back, fx.head.y + (Math.random() - 0.5) * 0.28, fx.head.z + rz * lat - fwdz * back, fwdx * sp + rx * u * 0.6, (Math.random() - 0.5) * 0.4, fwdz * sp + rz * u * 0.6, tail ? 0.10 + Math.random() * 0.10 : 0.12 + Math.random() * 0.08); } }   /* front grains are re-born at the head every frame, so a short life keeps the wave compact (≈ 0.2 s × head speed behind) */   /* the filaments are short-lived so the front stays compact at projectile speed */
          else if (fx.kind === 'CURTAIN') { fx.acc += fx.rate * dt; while (fx.acc >= 1) { fx.acc -= 1; var ang = Math.random() * Math.PI * 2, rr = fx.radius * Math.sqrt(Math.random()); spawn(em, fx.center.x + Math.cos(ang) * rr, fx.center.y + fx.top + Math.random() * 0.5, fx.center.z + Math.sin(ang) * rr, (Math.random() - 0.5) * 0.3, -(2.0 + Math.random() * 1.5), (Math.random() - 0.5) * 0.3, 1.1 + Math.random() * 0.5); } } }
        fx.live = step(fx, dt); if (fx.kind === 'WAVE' && fx.emitting) { var fwx = Math.sin(fx.heading), fwz = -Math.cos(fx.heading); var maxTrail = fx.p.max_trail_m || 3.0; for (var q = 0; q < em.n; q++) { if (!em.alive[q]) continue; var proj = (em.pos[q * 3] - fx.head.x) * fwx + (em.pos[q * 3 + 2] - fx.head.z) * fwz; if (proj < -maxTrail) { em.alive[q] = 0; em.count--; em.pos[q * 3 + 1] = -1e3; } } }   /* the wave is BOUNDED: whatever the frame rate, no grain trails more than max_trail_m behind the head */ if (!fx.emitting && fx.live === 0 && fx.t - (fx.stopT < 0 ? 0 : fx.stopT) > 0.05) { fx.done = true; release(em); LIVE.splice(i, 1); } } },
    dispose: function (fx) { if (!fx || fx.done) return; fx.done = true; release(fx.em); var k = LIVE.indexOf(fx); if (k >= 0) LIVE.splice(k, 1); },
    stats: function () { var live = 0, grains = 0; LIVE.forEach(function (f) { live++; grains += f.live || 0; }); return { effects: live, grains: grains, pooled: POOL.length, max_live: MAX_LIVE }; },
    live: function () { return LIVE.slice(); }
  };
  return api;
}
