/* MAHWORLD :: FAR WORLD (convergence PASS 2b — sky / far-background scale illusion, owner addendum 2026-09-17)
   Three readable depth layers around the playable district, in the MAHWORLD language (platinum, crystal, diamond-family prisms, cool sky):
     · MID  (230–330 m from the plaza, the empty southern / lateral sectors only): a few elevated crystal walkway arcs between low platforms and
            mid-distance prism towers — lit, fogged naturally, real geometry (MeshStandard, flat shading).
     · FAR  (620–860 m): a ring of crystalline massifs and a few world-scale spires (up to 260 m) — unlit silhouettes with baked facet tones,
            colours MIXED toward the horizon haze by distance (atmospheric perspective authored per vertex, fog OFF: the structure stays readable).
     · HAZE (250–890 m): a flat platinum-haze plain so the district ground never ends at a hard edge below the massifs.
   Everything is merged (3 draw calls), static, no colliders (far outside the 600 m room), inside the 900 m camera far plane.
   Nothing here copies a reference asset; no near-field clutter is added. createFarWorld(THREE, { night, seed }) -> THREE.Group */
export function createFarWorld(THREE, opts) {
  var o = opts || {}; var NIGHT = !!o.night; var seed = o.seed || 91; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }
  var group = new THREE.Group(); group.name = 'MAHWORLD_FAR_WORLD'; group.userData.noMerge = true;   /* already merged: the static-world merger leaves it alone */
  var haze = new THREE.Color(NIGHT ? 0x2a4363 : 0x8fb0d0), plat = new THREE.Color(NIGHT ? 0x3b4c66 : 0x5f7893), crystal = new THREE.Color(NIGHT ? 0x4a6390 : 0x7fa0c2);   /* owner B7 §8 / §10 F (2026-09-20): a DEPTH HIERARCHY — darker steel / sapphire bases, mixed toward the atmosphere's horizon haze by distance AND by height (thicker air low), so the massifs step back in blue-grey silhouettes instead of flat white cutouts */
  var sunDir = new THREE.Vector3(26, 34, 14).normalize();
  /* ---------- helpers: merge cone / prism pieces into one geometry with vertex colours ---------- */
  function pushGeo(acc, geo, matrix, color, facet, hazeTop) { geo = geo.toNonIndexed(); geo.applyMatrix4(matrix); geo.computeVertexNormals(); var p = geo.attributes.position, n = geo.attributes.normal; var tmpC = hazeTop ? new THREE.Color() : null; for (var i = 0; i < p.count; i++) { var tone = 1; if (facet) { var lam = n.getX(i) * sunDir.x + n.getY(i) * sunDir.y + n.getZ(i) * sunDir.z; tone = 0.8 + 0.18 * Math.max(0, lam) + (n.getY(i) > 0.8 ? 0.04 : 0); }   /* never brighter than the horizon sky: a far massif is a SILHOUETTE in blue-grey */ var c = color; if (hazeTop) { var hy = Math.max(0, Math.min(1, p.getY(i) / hazeTop)); c = tmpC.copy(color).lerp(haze, 0.42 * (1 - hy)); }   /* aerial perspective by height: the base of a massif sits in thicker air than its peak */ acc.pos.push(p.getX(i), p.getY(i), p.getZ(i)); acc.col.push(c.r * tone, c.g * tone, c.b * tone); if (acc.nrm) acc.nrm.push(n.getX(i), n.getY(i), n.getZ(i)); } }
  function finish(acc, material) { var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(acc.pos, 3)); g.setAttribute('color', new THREE.Float32BufferAttribute(acc.col, 3)); if (acc.nrm) g.setAttribute('normal', new THREE.Float32BufferAttribute(acc.nrm, 3)); g.computeBoundingSphere(); var m = new THREE.Mesh(g, material); m.frustumCulled = false; m.matrixAutoUpdate = false; return m; }
  var M4 = new THREE.Matrix4(), Q = new THREE.Quaternion(), S = new THREE.Vector3(), T = new THREE.Vector3(); var Y = new THREE.Vector3(0, 1, 0);
  function place(x, y, z, ry, sx, sy, sz) { Q.setFromAxisAngle(Y, ry); S.set(sx, sy, sz); T.set(x, y, z); return M4.compose(T, Q, S); }
  /* ---------- FAR: crystalline massifs + world-scale spires (unlit silhouettes, colours mixed toward the haze by distance) ---------- */
  var far = { pos: [], col: [] }; var N = 40;
  for (var k = 0; k < N; k++) { var ang = k / N * Math.PI * 2 + (rnd() - 0.5) * 0.12; var dist = 620 + rnd() * 240; var mix = 0.3 + 0.4 * (dist - 620) / 240;   /* farther = closer to the haze colour (authored atmospheric perspective; the forms stay readable, never fogged out) */
    var base = plat.clone().lerp(crystal, rnd() * 0.5).lerp(haze, mix); var cx = Math.cos(ang) * dist, cz = Math.sin(ang) * dist; var pieces = 2 + Math.floor(rnd() * 4);
    for (var j = 0; j < pieces; j++) { var h = 60 + rnd() * 140; var r = 28 + rnd() * 40; var ox = (rnd() - 0.5) * 90, oz = (rnd() - 0.5) * 90; var sides = 8 + Math.floor(rnd() * 3), squash = 0.82 + rnd() * 0.48, ry = rnd() * 3; var pc = base.clone().multiplyScalar(0.94 + rnd() * 0.07); pushGeo(far, new THREE.CylinderGeometry(r * 0.68, r, h * 0.64, sides, 2), place(cx + ox, h * 0.32 - 8, cz + oz, ry, 1, 1, squash), pc, true, h * 0.9); pushGeo(far, new THREE.ConeGeometry(r * 0.68, h * 0.36, sides), place(cx + ox, h * 0.82 - 8, cz + oz, ry, 1, 1, squash), pc.clone().lerp(crystal, 0.1), true, h * 0.9); }
    if (k % 7 === 3) { var sh = 190 + rnd() * 70; pushGeo(far, new THREE.ConeGeometry(14 + rnd() * 8, sh, 6), place(cx, sh / 2 - 6, cz, rnd() * 3, 1, 1, 1), base.clone().lerp(crystal, 0.35), true);   /* a world-scale spire: a diamond monument on the horizon */ pushGeo(far, new THREE.OctahedronGeometry(18, 0), place(cx, sh - 2, cz, rnd() * 3, 1, 1.9, 1), crystal.clone().lerp(haze, mix * 0.8), true); }
  }
  var farMat = new THREE.MeshBasicMaterial({ vertexColors: true, fog: false, toneMapped: false }); var farMesh = finish(far, farMat); farMesh.name = 'FAR_MASSIFS'; farMesh.renderOrder = -5; group.add(farMesh);
  /* ---------- MID: elevated crystal walkway arcs + prism towers in the empty sectors (lit, fogged naturally) ---------- */
  var mid = { pos: [], col: [], nrm: [] }; var sectors = [Math.PI * 0.62, Math.PI * 0.85, Math.PI * 1.05, Math.PI * 1.28, Math.PI * 1.5, Math.PI * 1.72];   /* bearings (atan2 x,z): the north half holds the temple / market / gym / tower — mid forms stay south, east and west */
  var midPlat = new THREE.Color(NIGHT ? 0x55657e : 0x9fb0c2), midCrystal = new THREE.Color(NIGHT ? 0x5d7aa6 : 0xb4cde6);   /* B7 §10 F: the mid forms a step darker than the far ring — three readable depth steps */
  sectors.forEach(function (b, i) { var dist = 230 + rnd() * 100; var cx = Math.sin(b) * dist, cz = Math.cos(b) * dist;
    var hT = 55 + rnd() * 55, towerR = 10 + rnd() * 6; pushGeo(mid, new THREE.CylinderGeometry(towerR * 0.34, towerR, hT, 9, 2), place(cx, hT / 2, cz, rnd() * 3, 1, 1, 1), midPlat, true);   /* a shouldered prism tower, not a single cheap spike */
    pushGeo(mid, new THREE.OctahedronGeometry(7, 0), place(cx, hT + 4, cz, rnd() * 3, 1, 1.8, 1), midCrystal, true);   /* its crystal crown */
    if (i % 2 === 0) { /* one continuous distant arch with two grounded piers; the old chain of boxes read as a broken half-bridge */ var b2 = sectors[(i + 1) % sectors.length]; var d2 = 230 + rnd() * 100; var ex = Math.sin(b2) * d2, ez = Math.cos(b2) * d2; var curve = new THREE.QuadraticBezierCurve3(new THREE.Vector3(cx, 22, cz), new THREE.Vector3((cx + ex) * 0.5, 50, (cz + ez) * 0.5), new THREE.Vector3(ex, 22, ez)); pushGeo(mid, new THREE.TubeGeometry(curve, 28, 2.5, 7, false), new THREE.Matrix4(), midPlat.clone().multiplyScalar(0.9), true); [0.18, 0.82].forEach(function (u) { var pp = curve.getPoint(u), ph = Math.max(8, pp.y); pushGeo(mid, new THREE.CylinderGeometry(1.7, 3.0, ph, 8), place(pp.x, ph * 0.5, pp.z, 0, 1, 1, 1), midPlat.clone().multiplyScalar(0.82), true); }); }
  });
  var midMat = new THREE.MeshStandardMaterial({ vertexColors: true, flatShading: true, roughness: 0.5, metalness: 0.55 }); var midMesh = finish(mid, midMat); midMesh.name = 'MID_WALKWAYS'; group.add(midMesh);
  /* ---------- HAZE plain: the ground fades into a platinum haze beyond the district instead of ending at an edge ---------- */
  var ring = new THREE.RingGeometry(250, 890, 48, 1); ring.rotateX(-Math.PI / 2); var rc = []; var rp = ring.attributes.position; var inner = new THREE.Color(NIGHT ? 0x141a24 : 0x2a3341), outer = haze.clone().lerp(new THREE.Color(NIGHT ? 0x1e2c42 : 0xb9c8d6), 0.5);
  for (var v = 0; v < rp.count; v++) { var rr = Math.hypot(rp.getX(v), rp.getZ(v)); var t = Math.max(0, Math.min(1, (rr - 300) / 590)); var c = inner.clone().lerp(outer, Math.pow(t, 0.6)); rc.push(c.r, c.g, c.b); }
  ring.setAttribute('color', new THREE.Float32BufferAttribute(rc, 3)); var hazeMesh = new THREE.Mesh(ring, new THREE.MeshBasicMaterial({ vertexColors: true, fog: false, toneMapped: false })); hazeMesh.position.y = -0.02;   /* just under the district floor (y −0.005) so the floor edge at 300 m shows no seam */ hazeMesh.name = 'HAZE_PLAIN'; hazeMesh.renderOrder = -6; hazeMesh.frustumCulled = false; group.add(hazeMesh);
  group.userData.info = { far_pieces: far.pos.length / 3, mid_pieces: mid.pos.length / 3, draw_calls: 3, far_ring_m: [620, 860], mid_ring_m: [230, 330], spires: Math.floor(N / 7) };
  return group;
}
