import { applyGeology } from './world/surfaceDetail.js'; import { softBox, taperShaft, orb, energyTip } from './world/formKit.js'; import { RIDGE_DIP } from './world/ridgeSculpt.js';
/* MAHWORLD :: FAR WORLD (convergence PASS 2b — sky / far-background scale illusion, owner addendum 2026-09-17)
   Three readable depth layers around the playable district, in the MAHWORLD language (platinum, crystal, diamond-family prisms, cool sky):
     · MID  (230–330 m from the plaza, the empty southern / lateral sectors only): a few elevated crystal walkway arcs between low platforms and
            mid-distance prism towers — lit, fogged naturally, real geometry (MeshStandard, flat shading).
     · FAR  (620–860 m): a ring of crystalline massifs (M20: the six world-scale primitive spires are gone) — unlit silhouettes with baked facet tones,
            colours MIXED toward the horizon haze by distance (atmospheric perspective authored per vertex, fog OFF: the structure stays readable).
     · HAZE (250–890 m): a flat platinum-haze plain so the district ground never ends at a hard edge below the massifs.
   Everything is merged (3 draw calls), static, no colliders (far outside the 600 m room), inside the 900 m camera far plane.
   Nothing here copies a reference asset; no near-field clutter is added. createFarWorld(THREE, { night, seed }) -> THREE.Group */
export function createFarWorld(THREE, opts) {
  var o = opts || {}; var NIGHT = !!o.night; var seed = o.seed || 91; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }
  var group = new THREE.Group(); group.name = 'MAHWORLD_FAR_WORLD'; group.userData.noMerge = true;   /* already merged: the static-world merger leaves it alone */
  var haze = new THREE.Color(NIGHT ? 0x2a4363 : 0x8fb0d0), plat = new THREE.Color(NIGHT ? 0x3b4c66 : 0x5f7893), crystal = new THREE.Color(NIGHT ? 0x4a6390 : 0x7fa0c2);   /* owner B7 §8 / §10 F (2026-09-20): a DEPTH HIERARCHY — darker steel / sapphire bases, mixed toward the atmosphere's horizon haze by distance AND by height (thicker air low), so the massifs step back in blue-grey silhouettes instead of flat white cutouts */
  var sunDir = new THREE.Vector3(26, 34, 14).normalize();
  /* WORLD PIVOT PASS 2b: BOTH palettes are baked (index 0 = day, 1 = night) and the vertex colours are swapped live by group.userData.setNight —
     the in-game time toggle never rebuilds the field, and these unlit, fog-free silhouettes kept their daylight caps glowing in a night sky. */
  var PAL = [{ haze: 0x8fb0d0, pHaze: 0x9899ae, rockLit: 0x777b8a, rockShade: 0x33374a, cap: 0xdde1ea, base: 0x2c3040,   /* M9: cool blue-grey aerial perspective, clearly darker than the horizon sky (the warm near-white read as paper / glass); M19: rock a step darker again so the snow reads against it */ midPlat: 0xaab0b8, midCrystal: 0xb4cde6, ringIn: 0x2a3341, ringOut: 0xb9c8d6, midGlass: 0x3b4558, midLit: 0xdfe5ee },
             { haze: 0x2a4363, pHaze: 0x2b3143, rockLit: 0x4d5263, rockShade: 0x1e212d, cap: 0x767d8c, base: 0x171a23, midPlat: 0x55657e, midCrystal: 0x5d7aa6, ringIn: 0x141a24, ringOut: 0x1e2c42, midGlass: 0x8e97ab, midLit: 0xe8e4d8 }];   /* M9: night — the glazing bands and deck-edge lines are lit (neutral practical light) */   /* M20 smoothing (lead: the far ring still read as pale ice under the storm-light sky — hue ≈ 214°, a cold blue off the grey-violet horizon): by day the massif haze is the horizon's own lavender-grey (S ≈ 0.12, a step darker than the sky behind it), the rock graphite (S ≤ 0.18) and a snowline a little lower on the flatter crowns — rock and snow under air, one family with the NEAR / MID ridges; the night palette is unchanged */   /* M20 (owner 2026-09-27, distant world: "better atmosphere, fewer crude shapes … SUPPORT the foreground"): the massif rock a step darker and the snow a touch less paper-white by day, so the ring reads as rock and snow under air instead of pale glass icebergs a shade off the sky; the night rock / snow / haze leave the violet (hue ≈ 245°, the edge of VISIONARY's window) for a deep blue-grey — no purple wash on the horizon. Review fix (that blue-grey sat inside TITAN's blue window, HSL S ≈ 0.39 on the haze): every night tone eased 45 % toward its equal-channel grey (S 0.09–0.22) — a graphite night horizon under the moonlight, not a blue wash */
  function pair(k) { return [new THREE.Color(PAL[0][k]), new THREE.Color(PAL[1][k])]; } function pmap(p2, fn) { return [fn(p2[0].clone(), 0), fn(p2[1].clone(), 1)]; }
  var hazeP = pair('haze');
  /* ---------- helpers: merge cone / prism pieces into one geometry with vertex colours ---------- */
  function pushGeo(acc, geo, matrix, colorP, facet, hazeTop, smooth) { geo = geo.toNonIndexed(); geo.applyMatrix4(matrix); if (!smooth || !geo.attributes.normal) geo.computeVertexNormals();   /* DESIGN DNA: smooth = keep the source's smooth normals (turned bodies), else flat facets (crystals, massifs) */ var p = geo.attributes.position, n = geo.attributes.normal; var tmpC = new THREE.Color(); for (var i = 0; i < p.count; i++) { var tone = 1; if (facet) { var lam = n.getX(i) * sunDir.x + n.getY(i) * sunDir.y + n.getZ(i) * sunDir.z; tone = 0.8 + 0.18 * Math.max(0, lam) + (n.getY(i) > 0.8 ? 0.04 : 0); }   /* never brighter than the horizon sky: a far massif is a SILHOUETTE in blue-grey */ var hy = hazeTop ? Math.max(0, Math.min(1, p.getY(i) / hazeTop)) : 1; for (var s2 = 0; s2 < 2; s2++) { var c = tmpC.copy(colorP[s2]); if (hazeTop) c.lerp(hazeP[s2], 0.42 * (1 - hy)); (s2 ? acc.colN : acc.colD).push(c.r * tone, c.g * tone, c.b * tone); }   /* aerial perspective by height: the base of a massif sits in thicker air than its peak */ acc.pos.push(p.getX(i), p.getY(i), p.getZ(i)); if (acc.nrm) acc.nrm.push(n.getX(i), n.getY(i), n.getZ(i)); } }
  function finish(acc, material) { var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(acc.pos, 3)); var cD = new Float32Array(acc.colD), cN = new Float32Array(acc.colN); g.setAttribute('color', new THREE.Float32BufferAttribute(NIGHT ? cN.slice() : cD.slice(), 3)); g.userData.colDay = cD; g.userData.colNight = cN; if (acc.nrm) g.setAttribute('normal', new THREE.Float32BufferAttribute(acc.nrm, 3)); g.computeBoundingSphere(); var m = new THREE.Mesh(g, material); m.frustumCulled = false; m.matrixAutoUpdate = false; return m; }
  var M4 = new THREE.Matrix4(), Q = new THREE.Quaternion(), S = new THREE.Vector3(), T = new THREE.Vector3(); var Y = new THREE.Vector3(0, 1, 0);
  function place(x, y, z, ry, sx, sy, sz) { Q.setFromAxisAngle(Y, ry); S.set(sx, sy, sz); T.set(x, y, z); return M4.compose(T, Q, S); }
  /* ---------- FAR: rocky massifs + world-scale spires. WORLD PIVOT PASS 2 (owner 2026-09-25: premium world, no flat paper mountains):
     every peak is a noise-displaced cone (12 × 6) with BAKED facet light from the registry Sun direction — warm light-stone on lit faces,
     cool lavender-grey in shadow, pale crystal-white caps on the high upward faces — then aerial perspective toward the daylight horizon
     haze by distance and by height (thicker air low). Neutral rock only (colour law); still unlit, fog-free and ONE merged draw call. */
  var FPX = o.tier !== 'LOW', far = { pos: [], colD: [], colN: [], nrm: FPX ? [] : null };   /* M20: FPX — the ring's Sun light per pixel (see farMat below); LOW keeps the per-vertex bake */ var N = 40; var FAR_SEG = o.tier === 'LOW' ? 10 : (o.tier === 'MED' ? 16 : 22), FAR_ROWS = o.tier === 'LOW' ? 5 : (o.tier === 'MED' ? 8 : 11);   /* M9: tiered massif resolution (HIGH ≈ 97 k tris for the ring, MED ≈ half); M19: LOW 10 × 5 (was 12 × 6, −30 %) */
  var pSun = new THREE.Vector3(26, 19, 14).normalize(); var pHaze = pair('pHaze');
  var rockLit = pair('rockLit'), rockShade = pair('rockShade'), capCol = pair('cap'), baseCol = pair('base');
  function hsh(n) { var v = Math.sin(n * 127.1 + 311.7) * 43758.5453; return v - Math.floor(v); }
  function vnoise(x, y, z) { var ix = Math.floor(x), iy = Math.floor(y), iz = Math.floor(z), fx = x - ix, fy = y - iy, fz = z - iz; fx = fx * fx * (3 - 2 * fx); fy = fy * fy * (3 - 2 * fy); fz = fz * fz * (3 - 2 * fz);
    function h(a, b, c) { return hsh(a * 1.0 + b * 57.0 + c * 113.0); } function lx(a, b, t) { return a + (b - a) * t; }
    return lx(lx(lx(h(ix, iy, iz), h(ix + 1, iy, iz), fx), lx(h(ix, iy + 1, iz), h(ix + 1, iy + 1, iz), fx), fy), lx(lx(h(ix, iy, iz + 1), h(ix + 1, iy, iz + 1), fx), lx(h(ix, iy + 1, iz + 1), h(ix + 1, iy + 1, iz + 1), fx), fy), fz); }
  function fbm(x, y, z) { return vnoise(x, y, z) * 0.55 + vnoise(x * 2.07, y * 2.07, z * 2.07) * 0.3 + vnoise(x * 4.3, y * 4.3, z * 4.3) * 0.15; }
  function smooth01(v) { v = Math.max(0, Math.min(1, v)); return v * v * (3 - 2 * v); }
  function rockPeak(cx, cz, r, h, ry, squash, mix, sd) {
    /* M9 (owner: the far ring read as translucent glass pyramids): a denser cone (SEG × ROWS) displaced by RIDGED noise and a few ARÊTES —
       sharp spurs running from the summit down the flanks with gullies between — so each massif has an irregular silhouette and real
       light / shadow structure instead of a regular pyramid. */
    var g = new THREE.ConeGeometry(r, h, FAR_SEG, FAR_ROWS, true); g.translate(0, h / 2, 0); var P = g.attributes.position, apexShift = (hsh(sd) - 0.5) * r * 0.55;
    var nA = 3 + Math.floor(hsh(sd * 1.7) * 3), aPh = hsh(sd * 2.3) * 6.283;
    /* M10 (owner: less giant-triangle silhouette): a cone's outline is a triangle whatever its radial noise, so the PROFILE changes —
       a foot that spreads, full shoulders and a broad crown, stepped SHOULDERS (rock shelves that show in the outline), and a
       broken summit: the top rows rise and fall round the peak, so the apex becomes one or two broad, uneven summits with a saddle, not one point. */
    var nT = 2.2 + hsh(sd * 3.1) * 1.8, tPh = hsh(sd * 4.7), sPk = 0.45 + hsh(sd * 5.3) * 0.45, apexY = h * (0.965 + 0.02 * hsh(sd * 6.1)), cAx = hsh(sd * 8.3) * Math.PI, eL = 0.36 + 0.3 * hsh(sd * 9.1), tilt = (hsh(sd * 10.7) - 0.5) * 0.12;
    function prof(tt) { tt = Math.max(0, Math.min(1, tt)); return Math.pow(1 - tt, 0.58) * (1 - 0.18 * smooth01(tt / 0.3)); }   /* a spreading foot, full shoulders and a broad crown (a cone is 1 − t); M20 smoothing: its top is capped by the apex fix below instead of a crater of teeth */
    function softRidge(v) { var q = 2 * v - 1; return 1.2 - Math.sqrt(q * q + 0.04); }   /* 1 − |2v − 1| with its crease rounded (the ridged noise printed knife creases into every flank) */
    var cav = new Float32Array(P.count);   /* M19: the relief deviation per vertex (spur +, gully −) → baked cavity light */
    /* M20 SMOOTHING (owner 2026-09-28: "too sharp, too angular, too old-gen … sculpted and premium, not jagged and retro"; lead: the far massifs read
       as faceted pyramids — V02 / V11 / TS1). The crown of every cone was a ring of 22 spikes: the summit noise lifted or dropped the top rows by up to
       ± 0.14 h round a ring ≈ 17 m across, and the apex sat below them (a crater of teeth). Same cone, same triangles (the ring is pinned per tier):
       the rows crowd toward the crown (where the outline is), the crown is drawn out along a crest axis (a massif, not a spike: its top rows squash
       across the axis), its summits are one or two smooth rises along that crest and a tilt (one shoulder higher), the ridged terms lose their
       creases, the shoulder steps are gentler and the apex caps the crown. The spurs, gullies, shelves, snow and haze stay; the day palette leaves
       the icy blue (below, PAL). */
    for (var i = 0; i < P.count; i++) { var x = P.getX(i), y = P.getY(i), z = P.getZ(i), tu = y / h, t = 1 - Math.pow(1 - Math.max(0, Math.min(1, tu)), 1.35), rad = Math.hypot(x, z);   /* rows crowd toward the crown */
      if (rad > 1e-4) { var th = Math.atan2(z, x); y = t * h; x *= (1 - t) / Math.max(1e-3, 1 - tu); z *= (1 - t) / Math.max(1e-3, 1 - tu); var n = fbm(x * 0.045 + sd, y * 0.05, z * 0.045 - sd), rn = softRidge(fbm(x * 0.022 - sd, y * 0.03, z * 0.022 + sd));
        var arete = Math.pow(Math.abs(Math.cos((th * nA + aPh + (n - 0.5) * 1.6) * 0.5)), 3.0);   /* spurs: ridgelines from the top down the flanks */
        var tf = t * nT + tPh, fr = tf - Math.floor(tf), tStep = t + ((fr * 0.3 + 0.7 * smooth01((fr - 0.6) / 0.34)) - fr) / nT * 0.5;   /* shelves: steep band, then a setback (M20: gentler — the steps notched the outline) */
        var kp = prof(tStep) / Math.max(1e-3, 1 - t), crn = smooth01((t - 0.3) / 0.6), sq = 1 - eL * crn * Math.pow(Math.sin(th - cAx), 2);   /* the crown drawn out along its crest axis */
        var dev = (n - 0.5) * 0.7 + (rn - 0.55) * 0.4 + (arete - 0.35) * 0.5 * (1 - 0.3 * crn), k = (1 + dev * (1 - t * 0.5)) * kp * sq; x *= k; z *= k; cav[i] = dev;
        var pk = smooth01(vnoise(Math.cos(th) * sPk + sd, Math.sin(th) * sPk - sd, sd * 0.37) * 1.4 - 0.2);   /* one or two smooth summits round the top (wraps: circle coordinates) */
        y += (fbm(x * 0.03, y * 0.03 + sd, z * 0.03) - 0.5) * h * 0.1 * (1 - t) + (rn - 0.5) * h * 0.04 * t + ((pk - 0.5) * 0.13 + tilt * Math.cos(th - cAx)) * h * smooth01((t - 0.5) / 0.45) - h * 0.03 * crn * (1 - sq); }
      else continue;   /* the apex row is set below, on the crown */
      x += apexShift * t * t; P.setXYZ(i, x, Math.max(0, y), z); }
    (function () { var W1 = FAR_SEG + 1, ax = 0, ay = 0, az = 0; for (var q = 0; q < FAR_SEG; q++) { ax += P.getX(W1 + q); ay += P.getY(W1 + q); az += P.getZ(W1 + q); } ax /= FAR_SEG; ay /= FAR_SEG; az /= FAR_SEG; ay = Math.max(ay + h * 0.012, apexY - h * 0.03);
      for (var q2 = 0; q2 < W1; q2++) P.setXYZ(q2, ax, ay, az); })();   /* the apex caps the dome: the top ring's centre, a touch above its mean (it used to sit below the ring — a crater of teeth) */
    /* M19 (owner 2026-09-27: "less obvious giant polygon faceting … softer distant mountains; atmospheric depth"): the baked light now reads
       SMOOTH normals of the displaced cone (its seam and summit rows welded) — the flanks shade as continuous rock instead of flat facets —
       plus a cavity term (the gullies between the arêtes darker, the spurs lighter) and a sky term (upward faces a touch brighter, overhangs darker). Snow lies on the high, flatter
       ground under a seeded, ragged snowline instead of a flat cap, and the air thickens toward each massif's foot (a soft haze skirt), so
       the ring steps back in depth without a white-out. Same merged draw, same silhouettes. */
    g.setAttribute('cav', new THREE.BufferAttribute(cav, 1)); g.applyMatrix4(place(cx, -6, cz, ry, 1, 1, squash)); g.computeVertexNormals(); var NA = g.attributes.normal, W1 = FAR_SEG + 1, sn = new THREE.Vector3();
    for (var jr = 0; jr <= FAR_ROWS; jr++) { var i0 = jr * W1, i1 = i0 + FAR_SEG; sn.set(NA.getX(i0) + NA.getX(i1), NA.getY(i0) + NA.getY(i1), NA.getZ(i0) + NA.getZ(i1)).normalize(); NA.setXYZ(i0, sn.x, sn.y, sn.z); NA.setXYZ(i1, sn.x, sn.y, sn.z); }   /* the cone's UV seam column shares one normal */
    sn.set(0, 0, 0); for (var ja = 0; ja < W1; ja++) sn.x += NA.getX(ja), sn.y += NA.getY(ja), sn.z += NA.getZ(ja); sn.normalize(); for (ja = 0; ja < W1; ja++) NA.setXYZ(ja, sn.x, sn.y, sn.z);   /* ... and the summit row (row 0) one normal */
    g = g.toNonIndexed(); (function (G) { var Pp = G.attributes.position, Nn = G.attributes.normal, a = new THREE.Vector3(), b = new THREE.Vector3(), c = new THREE.Vector3(), fn = new THREE.Vector3(), m = new THREE.Vector3(); for (var f3 = 0; f3 < Pp.count; f3 += 3) { a.fromBufferAttribute(Pp, f3); b.fromBufferAttribute(Pp, f3 + 1); c.fromBufferAttribute(Pp, f3 + 2); fn.subVectors(c, b).cross(a.clone().sub(b)).normalize(); for (var q = 0; q < 3; q++) { m.fromBufferAttribute(Nn, f3 + q).lerp(fn, FPX ? 0 : 0.22).normalize(); Nn.setXYZ(f3 + q, m.x, m.y, m.z); } } })(g);   /* softened facets: 55 % smooth / 45 % flat — the rock keeps its cut planes, the giant-facet edges melt; M20: 78 % smooth — the planes now come from the geology shader's fracture facets (soft creases), so the mesh's own triangles no longer print as glass facets */ var p = g.attributes.position, nm = g.attributes.normal, cv = g.attributes.cav, c = new THREE.Color(), snowL = 0.66 + 0.14 * hsh(sd * 7.9);
    for (var v = 0; v < p.count; v++) { var cdx = p.getX(v) - cx, cdz = p.getZ(v) - cz, cdl = Math.hypot(cdx, cdz) || 1; sn.set(cdx / cdl * h, r, cdz / cdl * h).normalize().multiplyScalar(0.45).addScaledVector(new THREE.Vector3(nm.getX(v), nm.getY(v), nm.getZ(v)), 0.55).normalize(); var lam = sn.dot(pSun), ny = nm.getY(v);   /* M20: the Sun light reads a normal eased 45 % toward the massif's own cone (a lit side and a shadow side), so the per-vertex light no longer prints the mesh's triangles; the relief comes from the cavity term and the shader's fracture planes */ var yy = p.getY(v) + 6, tt = yy / h, sl = snowL + (fbm(p.getX(v) * 0.02, sd, p.getZ(v) * 0.02) - 0.5) * 0.22;
      for (var s2 = 0; s2 < 2; s2++) { c.copy(rockShade[s2]).lerp(rockLit[s2], smooth01(lam * 1.25 + 0.18)); var dv = cv ? Math.max(-0.4, Math.min(0.4, cv.getX(v))) : 0; c.multiplyScalar((0.92 + 0.14 * ny) * (1 + (FPX ? 0.3 : 0.42) * dv));   /* gullies between the arêtes sit in their own shadow, the spurs catch more sky */ c.lerp(baseCol[s2], (1 - smooth01(tt * 2.2)) * 0.4);   /* M9: a firmer lit / shadow split — the massif has a sunlit side and a shadow side */
        if (tt > sl - 0.25 * Math.max(0, -dv) && ny > 0.5) c.lerp(capCol[s2], smooth01((tt - sl + 0.25 * Math.max(0, -dv)) / 0.14) * smooth01((ny - 0.5) / 0.28) * (1 - 0.6 * Math.max(0, dv) / 0.4) * (0.55 + 0.45 * Math.max(0, lam)));   /* M10 / M19: snow on the high, flatter faces under a ragged snowline, a little lower in the gullies, thinner on the exposed arêtes; M20: a higher snowline and flatter ground only — the steep faces stay rock (the snow-capped cones read as white glass) */
        c.lerp(pHaze[s2], Math.min(0.8, mix * 0.56 + (1 - smooth01(tt * 1.4)) * 0.26)); (s2 ? far.colN : far.colD).push(c.r, c.g, c.b); }   /* M9: less haze wash (the forms were dissolving into near-white); M19: a thicker haze skirt at the foot */
      far.pos.push(p.getX(v), p.getY(v), p.getZ(v)); if (far.nrm) far.nrm.push(sn.x, sn.y, sn.z); }
    g.dispose(); }
  for (var k = 0; k < N; k++) { var ang = k / N * Math.PI * 2 + (rnd() - 0.5) * 0.12; var dist = 620 + rnd() * 240; var mix = 0.18 + 0.36 * (dist - 620) / 240;   /* farther = closer to the haze colour; forms stay readable, never fogged out */
    var cx = Math.cos(ang) * dist, cz = Math.sin(ang) * dist; var pieces = 3 + Math.floor(rnd() * 4); var main = 110 + rnd() * 150;
    for (var j = 0; j < pieces; j++) { var h = j === 0 ? main : main * (0.35 + rnd() * 0.45); var r = h * (0.42 + rnd() * 0.22); var ox = (rnd() - 0.5) * 120, oz = (rnd() - 0.5) * 120; rockPeak(cx + ox, cz + oz, r, h, rnd() * 3, 0.78 + rnd() * 0.5, mix, k * 13 + j * 3.7); }
    if (k % 7 === 3) { rnd(); rnd(); rnd(); rnd(); }   /* M20 (owner: distant world "fewer crude shapes … the final world can have FEWER elements"): the six world-scale spires (a 6-sided cone under an octahedron, a primitive on the horizon) are REMOVED. The first cut rebuilt them as rock horns; the review read those as dithered grey stumps floating behind the MID ridge (MX / MA), no less crude. Their four random draws are still consumed, so every massif keeps its seeded place */
  }
  var farMat = new THREE.MeshBasicMaterial({ vertexColors: true, fog: false, toneMapped: false }); applyGeology(THREE, farMat, { lit: false, strata: 19, joint: 26, ledge: 0.14, fracture: 0.25, cleft: 0.9, macro: 0.16, grain: 0, bump: 0, lod: [500, 2500], dip: o.tier === 'LOW' ? null : RIDGE_DIP, soft: o.tier === 'LOW' ? 0 : 0.65, facets: o.tier === 'HIGH' ? [64, 40, 0.42, 2600] : null, facetSun: [26, 19, 14], bend: o.tier === 'HIGH' ? 12 : 0, polarUV: o.tier !== 'LOW', reliefPolar: [0, 0, 740] });   /* M20: the ridges' fracture planes (as baked Sun light: the ring is unlit) and bent, broken beds carry on into the far ring — rock planes at varied angles instead of glass facets; LOW keeps the M18 far shader. Review fix: the ring takes the ridges' polar along-face axis (bearing × 740 m), so the planes and beds run continuously round every massif instead of switching x ↔ z from triangle to triangle; the planes and beds on HIGH only (at 700 m on a phone they cost ≈ 56 noise lookups a pixel for detail under a pixel — MED keeps the per-pixel Sun below) */   /* M19: the ridges' regional dip / faults carry on into the far ring (one geology), and the thin bed lines soften at this range; LOW keeps the M18 far shader exactly (M19 review fix: no dip / fault trig or lithology on LOW) */   /* M9: broader, calmer beds (fine 11 m strata aliased into glassy stripes at 700 m) */   /* M8C: the same geology as value only — the baked facets gain strata, joints and clefts */ if (FPX) (function () { var prevF = farMat.onBeforeCompile, prevK = farMat.customProgramCacheKey, SUN = 'vec3(' + [pSun.x, pSun.y, pSun.z].map(function (v) { return v.toFixed(4); }).join(', ') + ')', FN = 'float fwL(float l) { return 0.2 + 0.8 * smoothstep(0.0, 1.0, clamp(l * 1.25 + 0.18, 0.0, 1.0)); }';
    /* M20 PER-PIXEL SUN on the far ring (owner: "far massifs are faceted glass-like pyramids"): the ring's light was baked per vertex, so every
       22 × 11 cone printed its triangles as flat glass facets. The bake stays (day / night palettes, snow, haze, the live swap), but the
       Sun term is re-evaluated per pixel from the interpolated lighting normal: colour × L(pixel) / L(vertex) — Gouraud becomes Phong,
       the flanks turn continuously from the lit to the shadow side, and the geology shader's fracture planes carry the cut rock. Normals
       (+ 12 B per vertex) on MED / HIGH only; LOW keeps the M19 bake and shader. */
    farMat.onBeforeCompile = function (sh, r) { if (prevF) prevF.call(this, sh, r); sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nvarying vec3 vFwN; varying float vFwL;\n' + FN).replace('#include <project_vertex>', '#include <project_vertex>\nvFwN = normalize(mat3(modelMatrix) * normal); vFwL = fwL(dot(vFwN, ' + SUN + '));');
      sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nvarying vec3 vFwN; varying float vFwL;\n' + FN).replace('#include <color_fragment>', '#include <color_fragment>\ndiffuseColor.rgb *= clamp(fwL(dot(normalize(vFwN), ' + SUN + ')) / max(vFwL, 0.05), 0.55, 1.8);'); };
    farMat.customProgramCacheKey = function () { return (prevK ? prevK.call(this) : '') + '|mahworld-far-pxsun'; }; farMat.needsUpdate = true; })();
  var farMesh = finish(far, farMat); farMesh.name = 'FAR_MASSIFS'; farMesh.renderOrder = -5; group.add(farMesh);
  /* ---------- MID: elevated crystal walkway arcs + prism towers in the empty sectors (lit, fogged naturally) ---------- */
  var FT = o.tier || 'HIGH', mid = { pos: [], colD: [], colN: [], nrm: [] }; var sectors = [Math.PI * 0.62, Math.PI * 0.85, Math.PI * 1.05, Math.PI * 1.28, Math.PI * 1.5, Math.PI * 1.72];   /* bearings (atan2 x,z): the north half holds the temple / market / gym / tower — mid forms stay south, east and west */
  var midPlat = pair('midPlat'), midCrystal = pair('midCrystal');   /* B7 §10 F: the mid forms a step darker than the far ring — three readable depth steps */
  /* M9 (audit: the mid layer read as white pipes and plain obelisks): towers become three stepped tiers with setbacks, dark glazing bands
     between them (lit at night) and a pale cap ring per tier; the walkway arcs become real BRIDGES — a deck slab, a darker girder under it,
     parapets, a thin practical light line along each deck edge by night, piers with caps. Same six sectors, same seeded layout. */
  var midGlass = pair('midGlass'), midLit = pair('midLit'), UPV = new THREE.Vector3(0, 1, 0);
  function sweep(curve, n, w, h, yOff, lat) { var pos = [], idx = []; for (var q = 0; q <= n; q++) { var t = q / n, P = curve.getPoint(t), T = curve.getTangent(t), S = new THREE.Vector3().crossVectors(T, UPV).normalize();
      var bv = Math.min(0.3, h / 3, w / 3); [[-w / 2 + bv, 0], [w / 2 - bv, 0], [w / 2, -bv], [w / 2, -h + bv], [w / 2 - bv, -h], [-w / 2 + bv, -h], [-w / 2, -h + bv], [-w / 2, -bv]].forEach(function (c) { pos.push(P.x + S.x * (c[0] + (lat || 0)), P.y + yOff + c[1], P.z + S.z * (c[0] + (lat || 0))); }); }   /* DESIGN DNA: a chamfered section (8 edges) — deck, girder and parapets have rolled arrises */
    for (q = 0; q < n; q++) { var a = q * 8, b2 = a + 8; [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 0]].forEach(function (e) { idx.push(a + e[0], b2 + e[0], b2 + e[1], a + e[0], b2 + e[1], a + e[1]); }); }
    var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.setIndex(idx); return g; }
  sectors.forEach(function (b, i) { var dist = 230 + rnd() * 100; var cx = Math.sin(b) * dist, cz = Math.cos(b) * dist;
    var hT = 55 + rnd() * 55, towerR = 10 + rnd() * 6, yaw = rnd() * 3, y0 = 0, frac = [0.46, 0.33, 0.21];
    frac.forEach(function (f, k) { var th = hT * f, rB = towerR * (1 - k * 0.24), rT = rB * 0.9; pushGeo(mid, new THREE.CylinderGeometry(rT, rB, th - 2.4, 28, 1), place(cx, y0 + (th - 2.4) / 2, cz, yaw, 1, 1, 1), midPlat, true, 0, true);   /* a tier (DESIGN DNA: turned smooth, was 9-sided) */
      pushGeo(mid, new THREE.CylinderGeometry(rT * 0.97, rT * 0.97, 1.8, 28, 1), place(cx, y0 + th - 2.4 + 0.9, cz, yaw, 1, 1, 1), midGlass, true, 0, true);   /* its glazing band (lit at night) */
      pushGeo(mid, new THREE.TorusGeometry(rT * 1.0, 0.34, FT === 'HIGH' ? 8 : 5, FT === 'HIGH' ? 40 : 24), new THREE.Matrix4().makeRotationX(Math.PI / 2).premultiply(place(cx, y0 + th - 0.4, cz, yaw, 1, 1, 1)), midLit, true, 0, true);   /* the rim: a rolled lit bead (was a flat ring) */
      var rN = k < 2 ? towerR * (1 - (k + 1) * 0.24) : rT * 0.5; pushGeo(mid, new THREE.LatheGeometry([new THREE.Vector2(rT * 0.98, 0), new THREE.Vector2(rT * 0.95, 0.35), new THREE.Vector2(rT * 0.84, 0.75), new THREE.Vector2((rT * 0.84 + rN) / 2, 1.05), new THREE.Vector2(rN * 1.0, 1.25), new THREE.Vector2(rN * 0.98, 1.6)], 28), place(cx, y0 + th - 0.2, cz, yaw, 1, 1, 1), midPlat, true, 0, true);   /* DESIGN DNA: a rolled shoulder carries each setback into the tier above (was a hard step) */
      /* M11 (owner: structures that still read as plain white obelisks): FLOORS — a thin dark glazing ring every 4.2 m up each tier; FINS — a
         slender vertical fin on each of the nine edges; so the tower reads as an occupied building from 150–300 m. Same merged mesh. */
      for (var fy = y0 + 3.2; fy < y0 + th - 3.4; fy += 4.2) { var ft = (fy - y0) / (th - 2.4), rf = rB + (rT - rB) * ft; pushGeo(mid, new THREE.CylinderGeometry(rf * 1.008, rf * 1.008, 1.05, FT === 'HIGH' ? 28 : 20, 1, true), place(cx, fy, cz, yaw, 1, 1, 1), midGlass, true, 0, true); }   /* open bands (their caps sat inside the tower) */
      for (var fe = 0; fe < 9; fe++) { var fa = yaw + fe / 9 * Math.PI * 2 + Math.PI / 2, rm = (rB + rT) / 2 * 1.02, fin = new THREE.BoxGeometry(0.55, th - 2.6, 0.9); pushGeo(mid, fin, place(cx + Math.sin(fa) * rm, y0 + (th - 2.4) / 2, cz + Math.cos(fa) * rm, fa, 1, 1, 1), midPlat, true); }
      y0 += th; });
    pushGeo(mid, taperShaft(THREE, 0.9, 0.35, 14, FT), place(cx, y0, cz, yaw, 1, 1, 1), midPlat, true, 0, true); pushGeo(mid, orb(THREE, 0.62, FT), place(cx, y0 + 14.1, cz, yaw, 1, 1, 1), midLit, true, 0, true); pushGeo(mid, energyTip(THREE, 0.5, 4.6, 0xffffff, FT), place(cx, y0 + 14.5, cz, yaw, 1, 1, 1), midLit, true, 0, true);   /* M11 crown mast, DESIGN DNA: a tapered mast, an orb joint and an energy tip (was a 6-sided pole and an octahedron) */
    pushGeo(mid, new THREE.OctahedronGeometry(7, 0), place(cx, hT + 4, cz, yaw, 1, 1.8, 1), midCrystal, true);   /* its crystal crown */
    if (i % 2 === 0) { var b2 = sectors[(i + 1) % sectors.length]; var d2 = 230 + rnd() * 100; var ex = Math.sin(b2) * d2, ez = Math.cos(b2) * d2; var curve = new THREE.QuadraticBezierCurve3(new THREE.Vector3(cx, 22, cz), new THREE.Vector3((cx + ex) * 0.5, 50, (cz + ez) * 0.5), new THREE.Vector3(ex, 22, ez));
      pushGeo(mid, sweep(curve, 36, 7, 0.9, 0.45), new THREE.Matrix4(), midPlat, true);   /* the deck slab */
      pushGeo(mid, sweep(curve, 36, 4.2, 1.8, -0.45), new THREE.Matrix4(), pmap(midPlat, function (c) { return c.multiplyScalar(0.6); }), true);   /* the girder under it */
      [-1, 1].forEach(function (sg) { pushGeo(mid, sweep(curve, 36, 0.35, 1.1, 1.55, sg * 3.3), new THREE.Matrix4(), pmap(midPlat, function (c) { return c.multiplyScalar(1.05); }), true);   /* parapets */
        pushGeo(mid, sweep(curve, 36, 0.3, 0.22, -0.3, sg * 3.62), new THREE.Matrix4(), midLit, true); });   /* the deck-edge light line */
      [0.18, 0.82].forEach(function (u) { var pp = curve.getPoint(u), ph = Math.max(8, pp.y - 2.25); pushGeo(mid, taperShaft(THREE, 3.2, 1.9, ph, FT, { belly: 0.03 }), place(pp.x, 0, pp.z, 0, 1, 1, 1), pmap(midPlat, function (c) { return c.multiplyScalar(0.82); }), true, 0, true); pushGeo(mid, softBox(THREE, 6, 1.2, 6, 1.2, FT), place(pp.x, ph + 0.6, pp.z, 0, 1, 1, 1), pmap(midPlat, function (c) { return c.multiplyScalar(0.7); }), true, 0, true); });   /* piers with caps (DESIGN DNA: tapered on a rolled foot, filleted caps) */
      /* M11 CABLE-STAYED (owner: visual support logic — a 150+ m deck on two thin piers did not read as carried): each pier gets a hammerhead
         crossbeam, twin pylons beside the deck joined by a crossbeam at the top, and a fan of stays to both deck edges — forestays toward
         mid-span, backstays toward the tower. Everything new starts on the pier cap (≥ 8 m up) or above the deck; same merged mesh. */
      var pylC = pmap(midPlat, function (c) { return c.multiplyScalar(0.86); }), stayC = pmap(midPlat, function (c) { return c.multiplyScalar(1.12); });
      var strut = function (A, B, r, col) { var d = new THREE.Vector3().subVectors(B, A), L = d.length(); if (L < 0.01) return; var q = new THREE.Quaternion().setFromUnitVectors(UPV, d.multiplyScalar(1 / L)); pushGeo(mid, new THREE.CylinderGeometry(r, r, L, 4, 1), new THREE.Matrix4().compose(new THREE.Vector3().addVectors(A, B).multiplyScalar(0.5), q, new THREE.Vector3(1, 1, 1)), col, true); };
      [0.18, 0.82].forEach(function (u, ui) { var pp = curve.getPoint(u), T = curve.getTangent(u); T.y = 0; T.normalize(); var S = new THREE.Vector3().crossVectors(T, UPV).normalize(), capY = Math.max(8, pp.y - 2.25) + 1.2, top = pp.y + 24, dirIn = ui === 0 ? 1 : -1;
        var yawS = Math.atan2(S.x, S.z);
        pushGeo(mid, softBox(THREE, 11, 1.4, 3.2, 0.6, FT), place(pp.x, capY - 0.7, pp.z, yawS - Math.PI / 2, 1, 1, 1), pylC, true, 0, true);   /* hammerhead under the deck */
        pushGeo(mid, softBox(THREE, 9.6, 1.2, 2.2, 0.5, FT), place(pp.x, top - 0.9, pp.z, yawS - Math.PI / 2, 1, 1, 1), pylC, true, 0, true);   /* the top crossbeam */
        [-1, 1].forEach(function (sg) { var mx = pp.x + S.x * sg * 4.6, mz = pp.z + S.z * sg * 4.6; pushGeo(mid, taperShaft(THREE, 1.15, 0.7, top - capY, FT, { flare: 1, belly: 0.04 }), place(mx, capY, mz, 0, 1, 1, 1), pylC, true, 0, true);
          pushGeo(mid, orb(THREE, 0.62, FT), place(mx, top + 0.55, mz, 0, 1, 1, 1), midLit, true, 0, true);   /* an aircraft-warning light on each pylon (lit at night): a polished orb */
          for (var k = 1; k <= 6; k++) [u + dirIn * k * 0.045, u - dirIn * k * 0.03].forEach(function (uu) { if (uu <= 0.02 || uu >= 0.98) return; var dp = curve.getPoint(uu), Td = curve.getTangent(uu); Td.y = 0; Td.normalize(); var Sd = new THREE.Vector3().crossVectors(Td, UPV).normalize();
            strut(new THREE.Vector3(mx, top - 2 - k * 0.7, mz), new THREE.Vector3(dp.x + Sd.x * sg * 3.45, dp.y + 0.5, dp.z + Sd.z * sg * 3.45), 0.16, stayC); }); }); }); }
  });
  var midMat = new THREE.MeshStandardMaterial({ vertexColors: true, flatShading: false, roughness: 0.42, metalness: 0.55 });   /* DESIGN DNA: per-vertex normals — turned bodies shade smooth, crystals keep their facets (their normals are flat) */ var midMesh = finish(mid, midMat); midMesh.name = 'MID_WALKWAYS'; group.add(midMesh);
  /* ---------- HAZE plain: the ground fades into a platinum haze beyond the district instead of ending at an edge ---------- */
  var ring = new THREE.RingGeometry(250, 890, 48, 1); ring.rotateX(-Math.PI / 2); var rc = []; var rp = ring.attributes.position; var inner = pair('ringIn'), outer = pmap(hazeP, function (c, i) { return c.lerp(new THREE.Color(PAL[i].ringOut), 0.5); }), rcN = [];
  for (var v = 0; v < rp.count; v++) { var rr = Math.hypot(rp.getX(v), rp.getZ(v)); var t = Math.max(0, Math.min(1, (rr - 300) / 590)); var c = inner[0].clone().lerp(outer[0], Math.pow(t, 0.6)), cn = inner[1].clone().lerp(outer[1], Math.pow(t, 0.6)); rc.push(c.r, c.g, c.b); rcN.push(cn.r, cn.g, cn.b); }
  ring.userData.colDay = new Float32Array(rc); ring.userData.colNight = new Float32Array(rcN); ring.setAttribute('color', new THREE.Float32BufferAttribute(NIGHT ? ring.userData.colNight.slice() : ring.userData.colDay.slice(), 3)); var hazeMesh = new THREE.Mesh(ring, new THREE.MeshBasicMaterial({ vertexColors: true, fog: false, toneMapped: false })); hazeMesh.position.y = -0.02;   /* just under the district floor (y −0.005) so the floor edge at 300 m shows no seam */ hazeMesh.name = 'HAZE_PLAIN'; hazeMesh.renderOrder = -6; hazeMesh.frustumCulled = false; group.add(hazeMesh);
  group.userData.night = NIGHT; group.userData.setNight = function (n) { n = !!n; if (n === group.userData.night) return; group.userData.night = n; [farMesh, midMesh, hazeMesh].forEach(function (m) { var gd = m.geometry, a = gd.attributes.color; if (!gd.userData.colDay) return; a.array.set(n ? gd.userData.colNight : gd.userData.colDay); a.needsUpdate = true; }); };
  group.userData.info = { far_pieces: far.pos.length / 3, mid_pieces: mid.pos.length / 3, draw_calls: 3, far_ring_m: [620, 860], mid_ring_m: [230, 330], spires: 0 };
  return group;
}
