/* MAHWORLD PLAYABLE SAMPLE :: FIELD SCENE (development view) — compact retro-futuristic practice area built FROM the authoritative
   collider layout the host publishes (rules.colliders): every visible solid is one of those shapes, so visuals and collision cannot
   drift apart. Chromium / platinum surfaces, cool blue-white lighting, dark sky, rounded barriers, pillars, ramps, clean grid floor.
   Also provides local camera collision (pull-in against the same shapes) — presentation only, the host never uses this file. */
import { createCityScene } from './cityScene.js'; import { createFarWorld } from './farWorld.js'; import { GLTFLoader } from '../vendor/three/GLTFLoader.js';
import { mergeGeometries } from '../vendor/three/BufferGeometryUtils.js'; import { createMahgicTreeFamily } from './mahgicTree.js';
import { defaultTextureCap } from './texCap.js'; import { applySurface, zonedPaving, createPavingZones } from './world/surfaceDetail.js'; import { createWorldB } from './world/worldB.js'; import { worldColliders } from './world/worldLayout.js';   /* JOB B (2026-09-19): the registry-driven world layer (forest, water + bridges, fixtures, sun / moon, props, match hall, guides, creatures) */
export function createFieldScene(THREE, scene, fsOpts) {
  var QUALITY = fsOpts && fsOpts.quality ? fsOpts.quality : null; var RENDERER = fsOpts && fsOpts.renderer ? fsOpts.renderer : null; var sun = null; var pmremTex = null; var qGet = function () { return QUALITY && QUALITY.get ? QUALITY.get() : { clouds: 22, city_fins: true, fog_far_scale: 1, lod_far_m: 220 }; }; var lods = []; var fogFarBase = 720; var pavingZones = createPavingZones(THREE), pavingHalo = null;   /* M8B: one zone state shared by the plaza + district floors (filled from the layout now and the registry when it lands) */ var sdTier = function () { try { return QUALITY && QUALITY.tier ? QUALITY.tier() : 'HIGH'; } catch (e) { return 'HIGH'; } };   /* M8: surface-detail tier (LOW keeps tone / roughness only) */ var animated = { emblem: null, elevator: null };
  /* Spec A static-world LOD: corrected imported heroes use manifest-pinned, source-derived near/far GLBs. Legacy landmarks without an authored
     far tier retain the bounded runtime grid fallback. THREE.LOD switches with hysteresis at the lesser of the asset threshold and quality tier. */
  /* Spec A static-world merge: after the procedural field + city are built, every static opaque mesh that shares a material with another
     is baked (world transform applied) into ONE mesh per material per 120 m chunk. Draw calls at spawn fall from ~390 to a few dozen while
     chunking keeps frustum culling coarse-grained. Excluded: animated subtrees (MAH_EMBLEM, TREE_ELEVATOR pods), instanced / skinned meshes,
     sprites / points / lines, transparent materials (their sort order matters), meshes flagged userData.noMerge, and the landmarks (they load
     asynchronously later and carry their own LOD). Original geometries are disposed only when no remaining mesh still uses them. */
  var mergeInfo = { merged_meshes: 0, into: 0, skipped: 0, vertices: 0 };
  function mergeStatic(rootGroup, chunkM) { var CH = chunkM || 120; rootGroup.updateMatrixWorld(true); var inv = rootGroup.matrixWorld.clone().invert(); var cands = []; var keep = new Set();
    (function walk(o, frozen) { if (o !== rootGroup && (o.name === 'MAH_EMBLEM' || o.name === 'TREE_ELEVATOR' || o.name === 'MAHWORLD_SKY' || (o.userData && o.userData.noMerge))) frozen = true; if (o.isMesh) { var m = o.material; var ok = !frozen && !o.isInstancedMesh && !o.isSkinnedMesh && !Array.isArray(m) && m && !m.transparent && o.geometry && o.geometry.attributes.position && o.visible && o.renderOrder === 0 && !Object.prototype.hasOwnProperty.call(o, 'onBeforeRender'); if (ok) cands.push(o); else if (o.geometry) keep.add(o.geometry); } for (var i = 0; i < o.children.length; i++) walk(o.children[i], frozen); })(rootGroup, false);
    var groups = {}; cands.forEach(function (o) { var wp = new THREE.Vector3().setFromMatrixPosition(o.matrixWorld); var key = o.material.uuid + '|' + Math.floor(wp.x / CH) + ',' + Math.floor(wp.z / CH); (groups[key] = groups[key] || []).push(o); });
    Object.keys(groups).forEach(function (key) { var list = groups[key]; if (list.length < 2) { list.forEach(function (o) { keep.add(o.geometry); mergeInfo.skipped++; }); return; }
      var attrs = null, compatible = true; list.forEach(function (o) { var names = Object.keys(o.geometry.attributes).sort().join(); if (attrs === null) attrs = names; else if (names !== attrs) compatible = false; });
      if (!compatible || attrs.indexOf('position') < 0) { list.forEach(function (o) { keep.add(o.geometry); mergeInfo.skipped++; }); return; }
      var allIndexed = list.every(function (o) { return !!o.geometry.index; }); var parts = []; var verts = 0;
      list.forEach(function (o) { var g = o.geometry.clone(); if (!allIndexed && g.index) g = g.toNonIndexed(); var rel = new THREE.Matrix4().multiplyMatrices(inv, o.matrixWorld); g.applyMatrix4(rel); if (g.attributes.normal) g.normalizeNormals(); parts.push(g); verts += g.attributes.position.count; });
      var merged = null; try { merged = mergeGeometries(parts, false); } catch (e) { merged = null; } parts.forEach(function (g) { g.dispose(); });
      if (!merged) { list.forEach(function (o) { keep.add(o.geometry); mergeInfo.skipped++; }); return; }
      merged.computeBoundingSphere(); merged.computeBoundingBox(); var mm = new THREE.Mesh(merged, list[0].material); mm.name = 'MERGED_' + key; mm.frustumCulled = true; rootGroup.add(mm);
      list.forEach(function (o) { if (o.parent) o.parent.remove(o); }); mergeInfo.merged_meshes += list.length; mergeInfo.into++; mergeInfo.vertices += verts; });
    /* dispose originals nobody uses any more (geometries can be shared by several meshes, some of which may stay) */
    var disposed = 0; cands.forEach(function (o) { if (!o.parent && !keep.has(o.geometry)) { o.geometry.dispose(); keep.add(o.geometry); disposed++; } }); mergeInfo.disposed = disposed; return mergeInfo; }
  function simplifyGrid(geo, cell) { var pos = geo.attributes.position; var idx = geo.index ? geo.index.array : null; var n = pos.count; var rep = new Int32Array(n); var cells = new Map(); for (var i = 0; i < n; i++) { var k = Math.round(pos.getX(i) / cell) + ',' + Math.round(pos.getY(i) / cell) + ',' + Math.round(pos.getZ(i) / cell); var r = cells.get(k); if (r === undefined) { cells.set(k, i); r = i; } rep[i] = r; } var out = []; var tri = idx ? idx.length / 3 : n / 3; for (var t = 0; t < tri; t++) { var a = rep[idx ? idx[t * 3] : t * 3], b = rep[idx ? idx[t * 3 + 1] : t * 3 + 1], c = rep[idx ? idx[t * 3 + 2] : t * 3 + 2]; if (a === b || b === c || a === c) continue; out.push(a, b, c); } var g2 = new THREE.BufferGeometry(); Object.keys(geo.attributes).forEach(function (name) { g2.setAttribute(name, geo.attributes[name]); }); g2.setIndex(out); g2.boundingSphere = geo.boundingSphere; g2.boundingBox = geo.boundingBox; return { geometry: g2, tris: out.length / 3, from: tri }; }
  /* Astra M3 NIGHT-FIRST: URL override → saved player choice → NIGHT for a first visit. DAY remains a full live state. */
  var NIGHT = (function () { try { if (typeof location !== 'undefined' && /[?&]sky=night/.test(location.search)) return true; if (typeof location !== 'undefined' && /[?&]sky=day/.test(location.search)) return false; var st = localStorage.getItem('mahworld-time'); if (st === 'NIGHT') return true; if (st === 'DAY') return false; } catch (e) { } return false; })();
  var TIME_STATE = { sizeM: 30, prewarm: { started: false, done: false, states: [], restored: null, ms: null, error: null } };
  var group = new THREE.Group(); scene.add(group); var built = null; var shapes = []; var lights = []; var env = null; var hidden = { on: false, saved: null, scene: null };
  /* JOB B world layer: created per field build under `group` (hidden / disposed with the field), fed by lab/assets/world/world_registry_v1.json; its solids join the camera boom through zone groups (the same grouping as the host) */
  var WORLD_ON = !(fsOpts && fsOpts.world === false); var worldB = null; var worldInfo = { status: WORLD_ON ? 'OFF' : 'DISABLED' }; var worldReg = null; var worldShapes = []; var groundMats = []; var landmarkGroups = {};
  /* M5 owner correction — one key, one stable celestial direction. world/sky.js computes bounded cloud transmission and
     world/celestial.js forwards it here; this scene remains the sole owner of the DirectionalLight and its shadow camera. */
  var CELESTIAL_KEY = { kind: NIGHT ? 'moon' : 'sun', direction: [0, 1, 0], base_intensity: NIGHT ? 1.15 : 2.35, transmission: 1, key_transmission: 1, coverage: 0, tau: 0 };
  function normalizedDirection(d, fallback) { d = Array.isArray(d) && d.length === 3 ? d : fallback; var x = +d[0] || 0, y = +d[1] || 0, z = +d[2] || 0, n = Math.hypot(x, y, z) || 1; return [x / n, y / n, z / n]; }
  function moonDirection() { var M = worldReg && worldReg.celestial && worldReg.celestial.moon || {}; var yaw = isFinite(+M.yaw_rad) ? +M.yaw_rad : 0.35, el = isFinite(+M.elevation_rad) ? +M.elevation_rad : 0.28; return normalizedDirection([-Math.sin(yaw) * Math.cos(el), Math.sin(el), -Math.cos(yaw) * Math.cos(el)], [-0.329, 0.276, -0.903]); }
  function positionCelestialKey(x, z) { if (!sun) return; var d = CELESTIAL_KEY.direction, reach = 54; sun.target.position.set(x, 0, z); sun.position.set(x + d[0] * reach, d[1] * reach, z + d[2] * reach); sun.target.updateMatrixWorld(); }
  function applyCelestialLight(s) { if (!s || !sun || !!s.night !== NIGHT) return; CELESTIAL_KEY.kind = s.kind || (NIGHT ? 'moon' : 'sun'); CELESTIAL_KEY.direction = normalizedDirection(s.direction, CELESTIAL_KEY.direction); CELESTIAL_KEY.transmission = Math.max(0, Math.min(1, isFinite(+s.transmission) ? +s.transmission : 1)); CELESTIAL_KEY.key_transmission = Math.max(0, Math.min(1, isFinite(+s.key_transmission) ? +s.key_transmission : CELESTIAL_KEY.transmission)); CELESTIAL_KEY.coverage = Math.max(0, Math.min(1, isFinite(+s.coverage) ? +s.coverage : 0)); CELESTIAL_KEY.tau = isFinite(+s.tau) ? +s.tau : 0; sun.intensity = CELESTIAL_KEY.base_intensity * CELESTIAL_KEY.key_transmission; var p = fsOpts && fsOpts.playerPos ? fsOpts.playerPos() : { x: 0, z: 0 }; positionCelestialKey((p && +p.x) || 0, (p && +p.z) || 0); sun.userData.mahworldCelestial = CELESTIAL_KEY; }
  function applyLandmarkLook(bld, id) { var look = worldReg && worldReg.landmark_looks ? worldReg.landmark_looks[id] : null; if (!look) return; bld.traverse(function (o) { if (!o.isMesh || !o.material) return; var m = o.material; if (look.color !== undefined && !m.userData.jobb_tinted) { m.userData.jobb_tinted = true; m.color.multiply(new THREE.Color(look.color)); }   /* a platinum / graphite tint on top of the derivative's base colour (never a flat repaint) */ if (look.envMapIntensity !== undefined) m.envMapIntensity = look.envMapIntensity; if (look.emissive !== undefined) { m.emissive = new THREE.Color(look.emissive); m.emissiveIntensity = look.emissiveIntensity || 0.06; } m.needsUpdate = true; }); }
  var districtFloor = null;
  /* JOB B water: the opaque district floor is cut over every river band (a ShapeGeometry with rectangular holes, UVs identical to the plane's) so the canal (surface, bed, bank walls) is a real channel below ground, never a flood */
  function cutFloorForWater(reg) { if (!districtFloor || !reg) return; var S = districtFloor.size, h = S / 2; var shape = new THREE.Shape(); var co = reg.coast && reg.coast.outline;
    if (co) { var r0 = Math.min(co.corner_r || 0, (co.x2 - co.x1) / 2, (co.z2 - co.z1) / 2); var X1 = co.x1, X2 = co.x2, Y1 = -co.z2, Y2 = -co.z1;   /* plane y = −world z */ shape.moveTo(X1 + r0, Y1); shape.lineTo(X2 - r0, Y1); shape.absarc(X2 - r0, Y1 + r0, r0, -Math.PI / 2, 0, false); shape.lineTo(X2, Y2 - r0); shape.absarc(X2 - r0, Y2 - r0, r0, 0, Math.PI / 2, false); shape.lineTo(X1 + r0, Y2); shape.absarc(X1 + r0, Y2 - r0, r0, Math.PI / 2, Math.PI, false); shape.lineTo(X1, Y1 + r0); shape.absarc(X1 + r0, Y1 + r0, r0, Math.PI, Math.PI * 1.5, false); shape.closePath(); }   /* owner note 2026-09-19: the mainland is ONE island — its floor ends at the coast, the beach ring + sea continue (lab/world/coast.js) */
    else { shape.moveTo(-h, -h); shape.lineTo(h, -h); shape.lineTo(h, h); shape.lineTo(-h, h); shape.closePath(); }
    ((reg.water && reg.water.rivers) || []).forEach(function (r) { var x1 = Math.max(-h, r.x1), x2 = Math.min(h, r.x2); var y1 = -Math.min(h, r.z2), y2 = -Math.max(-h, r.z1);   /* plane y = −world z */ var hole = new THREE.Path(); hole.moveTo(x1, y1); hole.lineTo(x2, y1); hole.lineTo(x2, y2); hole.lineTo(x1, y2); hole.closePath(); shape.holes.push(hole); });
    var g = new THREE.ShapeGeometry(shape, 12); var pos = g.attributes.position, uv = g.attributes.uv; for (var i = 0; i < pos.count; i++) uv.setXY(i, (pos.getX(i) + h) / S, (pos.getY(i) + h) / S); uv.needsUpdate = true; g.computeVertexNormals();
    var old = districtFloor.mesh.geometry; districtFloor.mesh.geometry = g; if (old) old.dispose(); districtFloor.cut = ((reg.water && reg.water.rivers) || []).length; districtFloor.coast = !!co; }
  function applyGroundPolicy() { var g = worldReg && worldReg.ground ? (NIGHT ? worldReg.ground.night : worldReg.ground.day) : null; if (!g) return; groundMats.forEach(function (m) { if (g.roughness !== undefined) m.roughness = g.roughness; if (g.metalness !== undefined) m.metalness = g.metalness; if (g.envMapIntensity !== undefined) m.envMapIntensity = g.envMapIntensity; }); } var botany = null; var botanyInfo = { status: 'OFF' };   /* P7 (master §14): the MAHGIC tree family — prototype instances from lab/assets/botany/prototype_v1.json; the old laser plants stay until Jah's verdict */
  function metal(color, rough, metalness) { return new THREE.MeshStandardMaterial({ color: color, roughness: rough === undefined ? 0.28 : rough, metalness: metalness === undefined ? 0.85 : metalness, envMapIntensity: 1 }); }
  /* ---- S11 DISTRICT LANDMARKS: runtime derivatives (Blender-decimated copies, originals never served) placed with the SAME transform the collider
     builder used (translation . yaw . uniform scale . bottom-centre offset). Materials stay as exported (metallic 0 / roughness 0.5: the base colour
     depicts metal and glass; a blanket metallic=1 would also hit signs, windows and plants). The client copy of the proxies feeds the camera boom + map. ---- */
  var districtInfo = { loaded: [], manifest: null, colliders: 0, failed: [] }; var districtGroups = []; var districtGeneration = 0;   /* client copy of the building proxies, grouped by envelope (broad phase for the camera boom / ground read-out); generation invalidates late GLB callbacks after a rebuild */
  function pointBlocked(cx, cy, cz, r) { var list = shapesNear(cx, cz, 0.5 + r); for (var k = 0; k < list.length; k++) { var s = list[k]; if (s.type === 'RAMP' || s.walkable || s.rim) continue;   /* decks (walkable) and platform-edge guards (rim) are ground / body rules, not walls — the host's blockedAt skips them the same way; the deck top still floors the camera through groundAt */ if (cy > s.h + r) continue; if (s.y0 !== undefined && cy < s.y0 - r) continue; if (s.type === 'BOX') { if (cx >= s.x1 - r && cx <= s.x2 + r && cz >= s.z1 - r && cz <= s.z2 + r) return s; } else if (s.type === 'CYLINDER') { if (Math.hypot(cx - s.x, cz - s.z) < s.r + r + 0.05) return s; } } return null; }   /* returns the blocking shape (truthy) or null */
  var NEAR = []; function shapesNear(x, z, pad) { var out = shapes, n = 0; for (var i = 0; i < districtGroups.length; i++) { var e = districtGroups[i]; if (x >= e.x1 - pad && x <= e.x2 + pad && z >= e.z1 - pad && z <= e.z2 + pad) { if (n === 0) { NEAR.length = 0; for (var a = 0; a < shapes.length; a++) NEAR.push(shapes[a]); out = NEAR; } for (var b = 0; b < e.shapes.length; b++) NEAR.push(e.shapes[b]); n++; } } return out; }   /* one reused list (no concat per query: cameraDistance asks ~50× per frame) — callers never keep the result across calls */
  function prepareDistrictAsset(inner, b) {
    try { var tcD = defaultTextureCap(); if (tcD) tcD.capRoot(inner); } catch (e) { }
    var sb = b.source_bounds, cx, cz, baseY;
    if (sb && sb.center_xz) { cx = sb.center_xz[0]; cz = sb.center_xz[1]; baseY = sb.base_y; }
    else { var box = new THREE.Box3().setFromObject(inner); var c = box.getCenter(new THREE.Vector3()); cx = c.x; cz = c.z; baseY = box.min.y; }
    inner.position.set(-cx * b.scale, -baseY * b.scale, -cz * b.scale); inner.scale.setScalar(b.scale);
    inner.traverse(function (o) { if (!o.isMesh) return; o.frustumCulled = true; o.castShadow = false; o.receiveShadow = true;   /* landmarks receive the key shadow but do not double the phone shadow triangle cost */
      var mats = Array.isArray(o.material) ? o.material : (o.material ? [o.material] : []); mats.forEach(function (m) { var look = b.look || {}; m.side = look.side === 'front' ? THREE.FrontSide : THREE.DoubleSide; m.envMapIntensity = look.envMapIntensity !== undefined ? Math.max(0.5, look.envMapIntensity) : 0.55; if (look.emissive !== undefined && m.emissive) { m.emissive = new THREE.Color(look.emissive); m.emissiveIntensity = look.emissiveIntensity || 0.4; } ['map', 'normalMap', 'roughnessMap', 'metalnessMap', 'aoMap'].forEach(function (k) { if (m[k] && m[k].anisotropy < 8) m[k].anisotropy = 8; }); if (m.roughness !== undefined) m.roughness = Math.max(0.18, Math.min(0.68, m.roughness)); m.needsUpdate = true; }); });
    return inner;
  }
  function addLegacyDistrictLods(inner, b, lodInfo) { var bigMeshes = []; inner.traverse(function (o) { if (o.isMesh && o.geometry && o.geometry.attributes.position.count >= 2000) bigMeshes.push(o); }); bigMeshes.forEach(function (o) { try { var simp = simplifyGrid(o.geometry, 1.4 / b.scale); if (simp.tris < simp.from * 0.85) { var lod = new THREE.LOD(); lod.autoUpdate = true; var farMesh = new THREE.Mesh(simp.geometry, o.material); farMesh.frustumCulled = true; var parent = o.parent; lod.position.copy(o.position); lod.quaternion.copy(o.quaternion); lod.scale.copy(o.scale); o.position.set(0, 0, 0); o.quaternion.identity(); o.scale.set(1, 1, 1); lod.addLevel(o, 0); lod.addLevel(farMesh, qGet().lod_far_m * 1); lod.userData.baseDistance = Infinity; if (lod.levels[1]) lod.levels[1].hysteresis = 0.08; parent.add(lod); lods.push(lod); lodInfo.full += simp.from; lodInfo.far += simp.tris; } } catch (e) { districtInfo.failed.push(b.id + ' lod: ' + (e && e.message)); } }); }
  var DISTRICT_TEXTURE_SLOTS = ['map', 'normalMap', 'roughnessMap', 'metalnessMap', 'emissiveMap', 'aoMap', 'alphaMap', 'bumpMap', 'displacementMap', 'lightMap'];
  function materialCompatible(a, b) { if (!a || !b || a === b || !a.name || a.name !== b.name || a.type !== b.type) return false; var scalars = ['transparent', 'opacity', 'side', 'metalness', 'roughness', 'emissiveIntensity', 'vertexColors', 'flatShading']; for (var i = 0; i < scalars.length; i++) if (a[scalars[i]] !== b[scalars[i]]) return false; if (a.color && b.color && a.color.getHex() !== b.color.getHex()) return false; if (a.emissive && b.emissive && a.emissive.getHex() !== b.emissive.getHex()) return false; if (a.normalScale && b.normalScale && (a.normalScale.x !== b.normalScale.x || a.normalScale.y !== b.normalScale.y)) return false; for (i = 0; i < DISTRICT_TEXTURE_SLOTS.length; i++) if (a[DISTRICT_TEXTURE_SLOTS[i]] !== b[DISTRICT_TEXTURE_SLOTS[i]]) return false; try { if (a.customProgramCacheKey() !== b.customProgramCacheKey()) return false; } catch (e) { return false; } return true; }
  function shareDistrictMaterials(near, far) { var nm = [], fm = []; near.traverse(function (o) { if (o.isMesh) nm.push(o); }); far.traverse(function (o) { if (o.isMesh) fm.push(o); }); if (nm.length !== fm.length) return { shared: 0, disposed: 0 }; var shared = 0, disposed = new Set(); for (var i = 0; i < nm.length; i++) { var na = Array.isArray(nm[i].material) ? nm[i].material : [nm[i].material], fa = Array.isArray(fm[i].material) ? fm[i].material : [fm[i].material]; if (na.length !== fa.length) continue; var out = fa.slice(), changed = false; for (var j = 0; j < na.length; j++) if (materialCompatible(na[j], fa[j])) { out[j] = na[j]; disposed.add(fa[j]); shared++; changed = true; } if (changed) fm[i].material = Array.isArray(fm[i].material) ? out : out[0]; } disposed.forEach(function (m) { try { m.dispose(); } catch (e) { } }); return { shared: shared, disposed: disposed.size }; }
  function disposeLooseDistrictRoot(root) { if (!root) return; var geos = new Set(), mats = new Set(), texs = new Set(), skeletons = new Set(); root.traverse(function (o) { if (o.geometry) geos.add(o.geometry); if (o.skeleton && o.skeleton.dispose) skeletons.add(o.skeleton); var ml = Array.isArray(o.material) ? o.material : (o.material ? [o.material] : []); ml.forEach(function (m) { mats.add(m); }); }); mats.forEach(function (m) { Object.keys(m).forEach(function (k) { var v = m[k]; if (v && v.isTexture) texs.add(v); }); if (m.uniforms) Object.keys(m.uniforms).forEach(function (k) { var u = m.uniforms[k]; if (u && u.value && u.value.isTexture) texs.add(u.value); }); }); var tc = defaultTextureCap(); texs.forEach(function (t) { var im = t.image; if (tc && tc.releaseTexture) tc.releaseTexture(t); try { t.dispose(); } catch (e) { } if (im && typeof im.close === 'function') try { im.close(); } catch (e) { } }); skeletons.forEach(function (s) { try { s.dispose(); } catch (e) { } }); geos.forEach(function (g) { try { g.dispose(); } catch (e) { } }); mats.forEach(function (m) { try { m.dispose(); } catch (e) { } }); }
  function loadDistrict(layout) {
    var key = layout.version, generation = ++districtGeneration; districtInfo = { loaded: [], manifest: null, colliders: 0, failed: [], key: key, generation: generation };
    function active() { return generation === districtGeneration && built && built.indexOf(key) === 0; }
    fetch('assets/buildings/district_v1.json').then(function (r) { return r.json(); }).then(function (man) {
      if (!active()) return; districtInfo.manifest = man; var loader = new GLTFLoader();
      man.buildings.forEach(function (b) { if (b.enabled === false || !b.scale) return;
        loader.load(b.runtime.replace('lab/', ''), function (g) {
          if (!active()) { disposeLooseDistrictRoot(g.scene); return; }
          var bld = new THREE.Group(); bld.name = 'DISTRICT_' + b.id.toUpperCase(); bld.position.set(b.position[0], b.position[1] || 0, b.position[2]); bld.rotation.y = (b.yaw_deg || 0) * Math.PI / 180;
          var near = prepareDistrictAsset(g.scene, b), sw = Math.min(b.lod_switch_m || Infinity, qGet().lod_far_m || Infinity); if (!isFinite(sw)) sw = 220;
          var lodInfo = { id: b.id, full: b.runtime_triangles || 0, far: b.lod_runtime_triangles || 0, authored_expected: !!b.lod_runtime, authored: false, far_status: b.lod_runtime ? 'LOADING' : 'LEGACY', switch_m: b.lod_runtime ? sw : null, shared_materials: 0, disposed_far_materials: 0 }, lod = null;
          if (b.lod_runtime) { lod = new THREE.LOD(); lod.autoUpdate = true; lod.addLevel(near, 0); lod.userData.baseDistance = b.lod_switch_m || Infinity; lods.push(lod); bld.add(lod); }
          else { addLegacyDistrictLods(near, b, lodInfo); bld.add(near); }
          group.add(bld); landmarkGroups[b.id] = bld; applyLandmarkLook(bld, b.id);
          var rec = { id: b.id, scale: b.scale, tris: b.runtime_triangles, lod: lodInfo, source_sha256: b.provenance && b.provenance.source_sha256 }; districtInfo.loaded.push(rec);
          if (fsOpts && fsOpts.onLandmark) { try { fsOpts.onLandmark(bld, b.id); } catch (e) { } }
          if (!b.lod_runtime) return;
          loader.load(b.lod_runtime.replace('lab/', ''), function (fg) {
            if (!active() || !bld.parent) { disposeLooseDistrictRoot(fg.scene); return; }
            var far = prepareDistrictAsset(fg.scene, b); applyLandmarkLook(far, b.id); var sh = shareDistrictMaterials(near, far); far.visible = false; lod.addLevel(far, sw); if (lod.levels[1]) lod.levels[1].hysteresis = 0.08;
            lodInfo.authored = true; lodInfo.far_status = 'READY'; lodInfo.shared_materials = sh.shared; lodInfo.disposed_far_materials = sh.disposed;
          }, undefined, function (e) { if (!active()) return; lodInfo.far_status = 'FAILED'; districtInfo.failed.push(b.id + ' authored lod: ' + (e && e.message)); });
        }, undefined, function (e) { if (active()) districtInfo.failed.push(b.id + ': ' + (e && e.message)); });
      });
    }).catch(function (e) { if (active()) districtInfo.failed.push('manifest: ' + (e && e.message)); });
    fetch('../play/rules1723/district_v1_colliders.json').then(function (r) { return r.json(); }).then(function (col) { if (!active()) return; if (col && col.shapes) { var g = {}; col.shapes.forEach(function (sh) { var e = g[sh.district] = g[sh.district] || { x1: 1e9, z1: 1e9, x2: -1e9, z2: -1e9, shapes: [] }; e.shapes.push(sh); e.x1 = Math.min(e.x1, sh.x1); e.z1 = Math.min(e.z1, sh.z1); e.x2 = Math.max(e.x2, sh.x2); e.z2 = Math.max(e.z2, sh.z2); }); districtGroups = Object.keys(g).map(function (k) { return g[k]; }); districtInfo.colliders = col.shapes.length; } }).catch(function (e) { if (active()) districtInfo.failed.push('colliders: ' + (e && e.message)); });
  }
  function clear() {
    districtGeneration++;
    if (worldB) { try { worldB.dispose && worldB.dispose(); } catch (e) { } } worldB = null; worldShapes = []; groundMats = []; landmarkGroups = {}; districtFloor = null; districtGroups = []; lods = []; worldInfo = { status: WORLD_ON ? 'OFF' : 'DISABLED' };
    var geos = new Set(), mats = new Set(), texs = new Set(), skeletons = new Set();
    while (group.children.length) { var c = group.children[group.children.length - 1]; group.remove(c); c.traverse(function (o) { if (o.geometry) geos.add(o.geometry); var ml = Array.isArray(o.material) ? o.material : (o.material ? [o.material] : []); ml.forEach(function (m) { mats.add(m); }); if (o.skeleton && o.skeleton.dispose) skeletons.add(o.skeleton); }); }
    mats.forEach(function (m) { Object.keys(m).forEach(function (k) { var v = m[k]; if (v && v.isTexture) texs.add(v); }); if (m.uniforms) Object.keys(m.uniforms).forEach(function (k) { var u = m.uniforms[k]; if (u && u.value && u.value.isTexture) texs.add(u.value); }); });
    var tcClear = defaultTextureCap(); texs.forEach(function (t) { var im = t.image; if (tcClear && tcClear.releaseTexture) tcClear.releaseTexture(t); try { t.dispose(); } catch (e) { } if (im && typeof im.close === 'function') { try { im.close(); } catch (e) { } } }); skeletons.forEach(function (s) { try { s.dispose(); } catch (e) { } }); mats.forEach(function (m) { try { m.dispose(); } catch (e) { } }); geos.forEach(function (g) { try { g.dispose(); } catch (e) { } });
    lights.forEach(function (l) { scene.remove(l); }); lights = []; if (env) { scene.environment = null; env.dispose(); env = null; }
  }   /* M5 owner correction: generation-safe async teardown and Set-deduplicated texture/material/geometry disposal for shared authored LODs. */
  function roundedBox(w, h, d, r) { var shape = new THREE.Shape(); var x = -w / 2, y = -d / 2; shape.moveTo(x + r, y); shape.lineTo(x + w - r, y); shape.quadraticCurveTo(x + w, y, x + w, y + r); shape.lineTo(x + w, y + d - r); shape.quadraticCurveTo(x + w, y + d, x + w - r, y + d); shape.lineTo(x + r, y + d); shape.quadraticCurveTo(x, y + d, x, y + d - r); shape.lineTo(x, y + r); shape.quadraticCurveTo(x, y, x + r, y); var g = new THREE.ExtrudeGeometry(shape, { depth: h, bevelEnabled: true, bevelThickness: 0.08, bevelSize: 0.08, bevelSegments: 3, steps: 1 }); g.rotateX(-Math.PI / 2); return g; }
  /* ---------------- MAHWORLD NIGHT SKY (presentation only: no collider, no host state; everything lives in `group` so clear() disposes it) ----------------
     stars (2 Points draw calls) · dimensional clouds (1 merged quad batch, slow drift) · distant cloud-skyland on the horizon (1 batch) · large cratered
     moon from a procedural canvas texture (1 call) + halo (1 call). Sky materials ignore the scene fog and sit inside the 400 m camera far plane. */
  function canvasTex(w, h, draw) { var c = document.createElement('canvas'); c.width = w; c.height = h; draw(c.getContext('2d'), w, h); var t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; return t; }
  function moonTexture() { return canvasTex(512, 512, function (g, w, h) { var cx = w / 2, cy = h / 2, R = w * 0.48; g.clearRect(0, 0, w, h); var base = g.createRadialGradient(cx - R * 0.35, cy - R * 0.35, R * 0.1, cx, cy, R); base.addColorStop(0, '#f4f1e6'); base.addColorStop(0.55, '#d9d6cc'); base.addColorStop(0.85, '#a9a8a4'); base.addColorStop(1, '#6d6f74'); g.fillStyle = base; g.beginPath(); g.arc(cx, cy, R, 0, Math.PI * 2); g.fill();
      var seed = 7; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }
      g.save(); g.beginPath(); g.arc(cx, cy, R, 0, Math.PI * 2); g.clip();
      for (var i = 0; i < 26; i++) { var a = rnd() * Math.PI * 2, d = Math.sqrt(rnd()) * R * 0.92, r = R * (0.03 + rnd() * rnd() * 0.16); var x = cx + Math.cos(a) * d, y = cy + Math.sin(a) * d; g.fillStyle = 'rgba(90,92,100,' + (0.35 + rnd() * 0.35) + ')'; g.beginPath(); g.arc(x, y, r, 0, Math.PI * 2); g.fill(); g.fillStyle = 'rgba(60,62,72,' + (0.25 + rnd() * 0.3) + ')'; g.beginPath(); g.arc(x + r * 0.15, y + r * 0.15, r * 0.72, 0, Math.PI * 2); g.fill(); g.strokeStyle = 'rgba(245,242,230,' + (0.35 + rnd() * 0.4) + ')'; g.lineWidth = Math.max(1, r * 0.14); g.beginPath(); g.arc(x, y, r, Math.PI * 1.05, Math.PI * 1.95); g.stroke(); }
      for (var j = 0; j < 90; j++) { var a2 = rnd() * Math.PI * 2, d2 = Math.sqrt(rnd()) * R * 0.95, r2 = R * (0.006 + rnd() * 0.02); g.fillStyle = 'rgba(80,82,92,' + (0.2 + rnd() * 0.35) + ')'; g.beginPath(); g.arc(cx + Math.cos(a2) * d2, cy + Math.sin(a2) * d2, r2, 0, Math.PI * 2); g.fill(); }
      /* maria: a few large dark plains */ for (var m = 0; m < 4; m++) { var a3 = rnd() * Math.PI * 2, d3 = rnd() * R * 0.5, r3 = R * (0.14 + rnd() * 0.2); g.fillStyle = 'rgba(70,74,86,0.28)'; g.beginPath(); g.ellipse(cx + Math.cos(a3) * d3, cy + Math.sin(a3) * d3, r3, r3 * (0.6 + rnd() * 0.4), rnd() * Math.PI, 0, Math.PI * 2); g.fill(); }
      g.restore(); var limb = g.createRadialGradient(cx, cy, R * 0.8, cx, cy, R); limb.addColorStop(0, 'rgba(0,0,0,0)'); limb.addColorStop(1, 'rgba(10,14,28,0.55)'); g.fillStyle = limb; g.beginPath(); g.arc(cx, cy, R, 0, Math.PI * 2); g.fill(); }); }
  function haloTexture() { return canvasTex(256, 256, function (g, w, h) { var r = g.createRadialGradient(w / 2, h / 2, w * 0.18, w / 2, h / 2, w * 0.5); r.addColorStop(0, 'rgba(180,205,255,0.55)'); r.addColorStop(0.45, 'rgba(120,160,255,0.16)'); r.addColorStop(1, 'rgba(60,90,200,0)'); g.fillStyle = r; g.fillRect(0, 0, w, h); }); }
  function cloudTexture() { return canvasTex(256, 128, function (g, w, h) { g.clearRect(0, 0, w, h); var seed = 3; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; } for (var i = 0; i < 30; i++) { var x = w * (0.12 + rnd() * 0.76), y = h * (0.3 + rnd() * 0.45), r = w * (0.06 + rnd() * 0.13); var gr = g.createRadialGradient(x, y, 0, x, y, r); gr.addColorStop(0, NIGHT ? 'rgba(255,255,255,0.32)' : 'rgba(255,255,255,0.55)'); gr.addColorStop(0.55, NIGHT ? 'rgba(210,225,255,0.12)' : 'rgba(236,242,250,0.22)'); gr.addColorStop(1, 'rgba(160,190,255,0)'); g.fillStyle = gr; g.beginPath(); g.arc(x, y, r, 0, Math.PI * 2); g.fill(); } }); }
  function skylandTexture() { return canvasTex(512, 192, function (g, w, h) { g.clearRect(0, 0, w, h); var seed = 11; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; } var base = h * 0.59; /* Long, low atmospheric bank: connected soft shoulders avoid the old row of bright circular stamps. */ var body = g.createLinearGradient(0, h * 0.2, 0, h * 0.88); body.addColorStop(0, NIGHT ? 'rgba(166,182,207,0.72)' : 'rgba(232,238,244,0.76)'); body.addColorStop(0.52, NIGHT ? 'rgba(85,105,137,0.62)' : 'rgba(183,198,215,0.7)'); body.addColorStop(1, 'rgba(35,49,75,0)'); g.fillStyle = body; g.beginPath(); g.moveTo(w * 0.035, base); for (var i = 0; i <= 22; i++) { var x = w * (0.04 + i * 0.042); var shoulder = (i % 5 === 2 ? 0.12 : 0.055) + rnd() * 0.045; var y = base - h * shoulder; g.quadraticCurveTo(x - w * 0.012, y - h * 0.025, x, y); } g.lineTo(w * 0.965, base + h * 0.055); g.quadraticCurveTo(w * 0.72, h * 0.79, w * 0.47, h * 0.72); g.quadraticCurveTo(w * 0.22, h * 0.79, w * 0.035, base); g.closePath(); g.fill(); /* quiet moonlit top edge, never a white horizontal slab */ g.globalCompositeOperation = 'source-atop'; var rim = g.createLinearGradient(0, h * 0.28, 0, h * 0.68); rim.addColorStop(0, NIGHT ? 'rgba(195,210,235,0.18)' : 'rgba(255,252,242,0.28)'); rim.addColorStop(0.62, 'rgba(160,185,218,0.04)'); rim.addColorStop(1, 'rgba(0,0,0,0)'); g.fillStyle = rim; g.fillRect(0, 0, w, h); /* dissolve all four edges into atmospheric depth */ g.globalCompositeOperation = 'destination-out'; var edge = g.createLinearGradient(0, 0, w, 0); edge.addColorStop(0, 'rgba(0,0,0,1)'); edge.addColorStop(0.14, 'rgba(0,0,0,0)'); edge.addColorStop(0.86, 'rgba(0,0,0,0)'); edge.addColorStop(1, 'rgba(0,0,0,1)'); g.fillStyle = edge; g.fillRect(0, 0, w, h); var vertical = g.createLinearGradient(0, 0, 0, h); vertical.addColorStop(0, 'rgba(0,0,0,0.3)'); vertical.addColorStop(0.28, 'rgba(0,0,0,0)'); vertical.addColorStop(0.76, 'rgba(0,0,0,0)'); vertical.addColorStop(1, 'rgba(0,0,0,0.88)'); g.fillStyle = vertical; g.fillRect(0, 0, w, h); }); }
  /* one merged batch of camera-agnostic quads, each facing the field centre (the camera never leaves the field) */
  function quadBatch(items, material) { var pos = [], uv = [], col = [], idx = []; var up = new THREE.Vector3(0, 1, 0); items.forEach(function (q, i) { var c = new THREE.Vector3(q.x, q.y, q.z); var n = c.clone().negate().normalize(); var r = new THREE.Vector3().crossVectors(up, n).normalize(); var u = new THREE.Vector3().crossVectors(n, r).normalize(); var hw = q.w / 2, hh = q.h / 2; [[-hw, -hh, 0, 0], [hw, -hh, 1, 0], [hw, hh, 1, 1], [-hw, hh, 0, 1]].forEach(function (k) { var v = c.clone().addScaledVector(r, k[0]).addScaledVector(u, k[1]); pos.push(v.x, v.y, v.z); uv.push(k[2], k[3]); col.push(q.c[0], q.c[1], q.c[2]); }); var b = i * 4; idx.push(b, b + 1, b + 2, b, b + 2, b + 3); }); var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2)); g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); g.setIndex(idx); var m = new THREE.Mesh(g, material); m.frustumCulled = false; return m; }
  /* DAYLIGHT IMAGE-BASED LIGHT. The field's chromium / platinum surfaces are metalness 0.6-0.95; a metal with no environment reflects
     nothing and stays black however many lamps you add, which is why the night build could only ever look like night. A tiny procedural
     sky cube (six 32 px faces, one PMREM the renderer builds itself) gives them a sky to reflect. This is LIGHTING, not paint: no material
     colour, roughness or metalness is touched anywhere. */
  /* DAY environment for reflections: a sky sphere (zenith blue → pale horizon → graphite below), a sun of ~12× white on the key light's axis,
     filtered by PMREM so roughness selects the right blur — gold and chrome show a hot highlight plus a soft sky wrap, like the owner's Tripo
     turntable, instead of the flat 32-px gradient cube used at night. */
  function pmremSky(nightSky) { var es = new THREE.Scene(); var R0 = 50; var geo = new THREE.SphereGeometry(R0, 48, 24); var pos = geo.attributes.position; var col = new Float32Array(pos.count * 3); var zen = new THREE.Color(nightSky ? 0x0b1830 : 0x4a86c9), hor = new THREE.Color(nightSky ? 0x27405c : 0xd8e8f4), grd = new THREE.Color(nightSky ? 0x161a20 : 0x4c5157), tmp = new THREE.Color();   /* B8 §20: the NIGHT environment is the same PMREM kind as the day's (a cube-texture environment would flip every material's ENVMAP define and recompile ≈ 80 programs on the live switch) */ for (var i = 0; i < pos.count; i++) { var y = pos.getY(i) / R0; if (y >= 0) tmp.copy(hor).lerp(zen, Math.pow(Math.min(1, y * 1.4), 0.75)); else tmp.copy(hor).lerp(grd, Math.min(1, -y * 3)); col[i * 3] = tmp.r; col[i * 3 + 1] = tmp.g; col[i * 3 + 2] = tmp.b; } geo.setAttribute('color', new THREE.BufferAttribute(col, 3)); es.add(new THREE.Mesh(geo, new THREE.MeshBasicMaterial({ vertexColors: true, side: THREE.BackSide }))); var sdL = (worldReg && worldReg.celestial && worldReg.celestial.sun && worldReg.celestial.sun.direction) || [26, 19, 14]; var sunDir = new THREE.Vector3(sdL[0], sdL[1], sdL[2]).normalize(); var sunM = new THREE.Mesh(new THREE.SphereGeometry(2.4, 16, 12), new THREE.MeshBasicMaterial({ color: new THREE.Color(12, 10.5, 8.5) })); sunM.position.copy(sunDir).multiplyScalar(44); es.add(sunM); var glow = new THREE.Mesh(new THREE.SphereGeometry(7, 16, 12), new THREE.MeshBasicMaterial({ color: new THREE.Color(1.6, 1.45, 1.25), transparent: true, opacity: 0.55 })); glow.position.copy(sunDir).multiplyScalar(45); es.add(glow); var gen = new THREE.PMREMGenerator(RENDERER); var rt = gen.fromScene(es, 0.04, 0.5, 100); gen.dispose(); geo.dispose(); return rt.texture; }   /* everything sits inside the PMREM cube camera's far plane (100) */
  function skyEnvironment() {
    function face(draw) { var c = document.createElement('canvas'); c.width = c.height = 32; draw(c.getContext('2d'), 32); return c; }
    function vertical(g, n) { var grad = g.createLinearGradient(0, 0, 0, n); if (NIGHT) { grad.addColorStop(0, '#16304f'); grad.addColorStop(0.5, '#243c58'); grad.addColorStop(1, '#3a4652'); } else { grad.addColorStop(0, '#2f5680'); grad.addColorStop(0.55, '#5a7a96'); grad.addColorStop(1, '#78868f'); }   /* deliberately well below the visible sky: enough reflection to read as metal in daylight, not enough to turn the graphite into a white mirror */ g.fillStyle = grad; g.fillRect(0, 0, n, n); }
    var side = [face(vertical), face(vertical), face(vertical), face(vertical)];
    var up = face(function (g, n) { g.fillStyle = NIGHT ? '#122842' : '#23405e'; g.fillRect(0, 0, n, n); });
    var down = face(function (g, n) { g.fillStyle = '#26292f'; g.fillRect(0, 0, n, n); });   /* the platform bounce: neutral graphite, so the gold is not tinted */
    var tex = new THREE.CubeTexture([side[0], side[1], up, down, side[2], side[3]]); tex.colorSpace = THREE.SRGBColorSpace; tex.needsUpdate = true; return tex;
  }
  function buildLights(nt) { var sizeM = TIME_STATE.sizeM; lights.forEach(function (l) { if (l.parent) l.parent.remove(l); if (l.target && l.target.parent) l.target.parent.remove(l.target); if (l.shadow && l.shadow.map) { try { l.shadow.map.dispose(); } catch (e) { } } }); lights.length = 0; sun = null;
    if (nt) {
      /* NIGHT LIGHTING TEMPLATE (generalises to future character packages): a cool blue-white moon key with clear direction, a soft cool rim from the opposite side, hemisphere sky/ground bounce kept neutral (no yellow contamination), environment map for specular definition on chrome/crystal, darker exposure, restrained fog. Local light comes from emissive trims, not point lights. */
      scene.background = new THREE.Color(0x070c16); scene.fog = new THREE.Fog(0x0b1424, 80, sizeM > 200 ? 620 : 240);
      CELESTIAL_KEY.kind = 'moon'; CELESTIAL_KEY.direction = moonDirection(); CELESTIAL_KEY.base_intensity = 1.15; CELESTIAL_KEY.transmission = CELESTIAL_KEY.key_transmission = 1; CELESTIAL_KEY.coverage = CELESTIAL_KEY.tau = 0;
      var keyN = new THREE.DirectionalLight(0xcfe0ff, CELESTIAL_KEY.base_intensity); keyN.name = 'MAHWORLD_CELESTIAL_KEY'; scene.add(keyN); scene.add(keyN.target); lights.push(keyN); sun = keyN; positionCelestialKey(0, 0); var TN = qGet(); if (TN.shadows && TN.shadows !== 'off' && RENDERER) { keyN.castShadow = true; keyN.shadow.mapSize.set(TN.shadow_map || 1024, TN.shadow_map || 1024); var reachN = TN.shadow_reach_m || 24; keyN.shadow.camera.left = -reachN; keyN.shadow.camera.right = reachN; keyN.shadow.camera.top = reachN; keyN.shadow.camera.bottom = -reachN; keyN.shadow.camera.near = 2; keyN.shadow.camera.far = 160; keyN.shadow.bias = -0.0006; keyN.shadow.normalBias = 0.03; keyN.shadow.radius = 2; }   /* same shadow configuration as DAY keeps stable program defines; only direction/intensity uniforms change with the Moon/cloud state */ var rimN = new THREE.DirectionalLight(0x8fb8ff, 0.7); rimN.position.set(22, 12, 18); scene.add(rimN); lights.push(rimN); var hemiN = new THREE.HemisphereLight(0x7fa6e0, 0x1a1e26, 0.75); scene.add(hemiN); lights.push(hemiN); var fillN = new THREE.DirectionalLight(0xdfe8ff, 0.22); fillN.position.set(0, 20, 30); scene.add(fillN); lights.push(fillN);
    } else {
      /* DAYTIME: a warm sun with a clear direction, cool sky fill from above, bounce from the platform below. World pivot PASS 1 (owner sky
         direction 2026-09-25): more light-to-shadow separation for a bright fantasy daylight — a stronger warm key, a cooler lavender rim,
         a lower but bluer sky fill and a warm ground bounce, so lit faces glow gold-white and shaded faces stay sky-blue instead of grey. */
      scene.background = new THREE.Color(0x9fc4e4); fogFarBase = sizeM > 200 ? 1050 : 260; scene.fog = new THREE.Fog(0xb9cddd, sizeM > 200 ? 75 : 110, fogFarBase * qGet().fog_far_scale);
      var sdR = (worldReg && worldReg.celestial && worldReg.celestial.sun && worldReg.celestial.sun.direction) || [26, 19, 14]; CELESTIAL_KEY.kind = 'sun'; CELESTIAL_KEY.direction = normalizedDirection(sdR, [26, 19, 14]); CELESTIAL_KEY.base_intensity = 3.0; CELESTIAL_KEY.transmission = CELESTIAL_KEY.key_transmission = 1; CELESTIAL_KEY.coverage = CELESTIAL_KEY.tau = 0;
      var key = new THREE.DirectionalLight(0xffecc8, CELESTIAL_KEY.base_intensity); key.name = 'MAHWORLD_CELESTIAL_KEY'; scene.add(key); scene.add(key.target); lights.push(key); sun = key; positionCelestialKey(0, 0);   /* the Sun disc, atmosphere lobe, shadows and key all share this registry direction */
      var T0 = qGet(); if (T0.shadows && T0.shadows !== 'off' && RENDERER) { key.castShadow = true; key.shadow.mapSize.set(T0.shadow_map || 1024, T0.shadow_map || 1024); var reach = T0.shadow_reach_m || 24; key.shadow.camera.left = -reach; key.shadow.camera.right = reach; key.shadow.camera.top = reach; key.shadow.camera.bottom = -reach; key.shadow.camera.near = 2; key.shadow.camera.far = 160; key.shadow.bias = -0.0006; key.shadow.normalBias = 0.03; key.shadow.radius = 2; }
      var rim = new THREE.DirectionalLight(0xcfc8ff, 0.5); rim.position.set(-18, 10, -16); scene.add(rim); lights.push(rim); var hemi = new THREE.HemisphereLight(0xbcd4ff, 0x6c655c, 0.8); scene.add(hemi); lights.push(hemi); var fill = new THREE.DirectionalLight(0xe8f0ff, 0.2); fill.position.set(0, 18, 30); scene.add(fill); lights.push(fill);
    } }
  /* B8 §20 LIVE TIME OF DAY: the two stable states switch without a rebuild — lights, background / fog, the legacy dome pieces (stars, moon, halo, sun disc), the ground policy, the environment map and every JOB B module's setNight */
  function setNight(n, options) { options = options || {}; n = !!n; if (n === NIGHT && TIME_STATE.applied && !options.force) return NIGHT; NIGHT = n; TIME_STATE.applied = true; try { buildLights(NIGHT); } catch (e) { } try { applyGroundPolicy(); } catch (e) { } try { var fw = group.getObjectByName('MAHWORLD_FAR_WORLD'); if (fw && fw.userData.setNight) fw.userData.setNight(NIGHT); } catch (e) { }   /* world pivot: the unlit far silhouettes swap their baked day / night palettes live */ var celOn = !!(worldB && worldB.modules && worldB.modules().celestial && !worldB.modules().celestial.failed), worldSkyOn = !!(worldB && worldB.modules && worldB.modules().sky && !worldB.modules().sky.failed); var sky = group.getObjectByName('MAHWORLD_SKY'); if (sky) sky.traverse(function (o) { if (o.name === 'MAHWORLD_SKY_STARS') o.visible = NIGHT; if (o.name === 'MAHWORLD_SKY_MOON' || o.name === 'MAHWORLD_SKY_MOON_HALO') o.visible = NIGHT && !celOn; if (o.name === 'MAHWORLD_SKY_SUN') o.visible = !NIGHT && !celOn; }); var legacyClouds = group.getObjectByName('MAHWORLD_SKY_LEGACY_CLOUDS'); if (legacyClouds) legacyClouds.visible = !worldSkyOn;   /* one cloud clock: registry sky owns moving sheets and celestial attenuation whenever it is ready */ try { if (NIGHT && !TIME_STATE.envNight && RENDERER && THREE.PMREMGenerator) { try { TIME_STATE.envNight = pmremSky(true); } catch (e) { TIME_STATE.envNight = null; } } scene.environment = NIGHT ? (TIME_STATE.envNight || TIME_STATE.envDay || env) : (TIME_STATE.envDay || env); } catch (e) { } if (worldB) { try { worldB.setNight(NIGHT); } catch (e) { } } if (options.persist !== false) { try { localStorage.setItem('mahworld-time', NIGHT ? 'NIGHT' : 'DAY'); } catch (e) { } } return NIGHT; }
  /* Compile both stable lighting/material states without exposing a day frame or changing the player's saved choice. The initial state is restored before the next render. */
  function prewarmTimeStates(renderer, camera) { var S = TIME_STATE.prewarm; if (S.done || S.started) return S; S.started = true; var t0 = performance.now(), initial = NIGHT; try { [false, true].forEach(function (n) { setNight(n, { persist: false, force: true }); if (renderer && renderer.compile) renderer.compile(scene, camera); S.states.push(n ? 'NIGHT' : 'DAY'); }); setNight(initial, { persist: false, force: true }); S.restored = initial ? 'NIGHT' : 'DAY'; S.done = true; S.ms = +(performance.now() - t0).toFixed(1); } catch (e) { S.error = String(e && e.message || e); try { setNight(initial, { persist: false, force: true }); } catch (e2) { } S.restored = initial ? 'NIGHT' : 'DAY'; } return S; }
  function buildSky() {
    var sky = new THREE.Group(); sky.name = 'MAHWORLD_SKY'; group.add(sky); var skyFixed = new THREE.Group(); skyFixed.name = 'MAHWORLD_SKY_FIXED'; skyFixed.userData.noMerge = true; group.add(skyFixed);   /* PASS 3 review: only the dome / sun / stars ride with the viewer; clouds and the cloud-skyland stay world-fixed so they pass overhead and parallax against the far ring */
    /* DAYTIME (2026-09-15 rig-motion repair): a gradient dome carries the sky instead of a flat dark clear colour; everything below is
       retuned for day — the terrain, colliders, camera collision and the build/clear lifecycle are untouched. */
    var R_DOME = 1300;   /* PASS 2b: a deep sky — the dome FOLLOWS the viewer (see follow()) and sits inside the 1400 m camera far plane; the world-fixed far massifs (620–860 m) stand in front of it from anywhere in the room */ var domeGeo = new THREE.SphereGeometry(R_DOME, 32, 20); var dpos = domeGeo.attributes.position; var dcol = []; var zen = new THREE.Color(NIGHT ? 0x050a16 : 0x2f6fc4), mid = new THREE.Color(NIGHT ? 0x0d1c33 : 0x8fbde8), hor = new THREE.Color(NIGHT ? 0x2a4363 : 0xdde8f0);
    for (var di = 0; di < dpos.count; di++) { var hgt = Math.max(0, Math.min(1, (dpos.getY(di) / R_DOME) * 0.5 + 0.5)); var cc = hgt > 0.52 ? mid.clone().lerp(zen, Math.min(1, (hgt - 0.52) / 0.42)) : hor.clone().lerp(mid, Math.max(0, hgt - 0.1) / 0.42); dcol.push(cc.r, cc.g, cc.b); }
    domeGeo.setAttribute('color', new THREE.Float32BufferAttribute(dcol, 3));
    var dome = new THREE.Mesh(domeGeo, new THREE.MeshBasicMaterial({ vertexColors: true, side: THREE.BackSide, fog: false, depthWrite: false, toneMapped: false }));   /* sky colours are authored in display space: no filmic curve on them */ dome.renderOrder = -20; dome.frustumCulled = false; dome.name = 'MAHWORLD_SKY_DOME'; sky.add(dome);   /* JOB B atmosphere.js replaces this material with the scattering shader (B7 §8) */
    var seed = 5; function rnd() { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }
    /* stars: two point clouds on the upper hemisphere (faint many + bright few) */
    [[1800, 1.6, 0.35, 0.8], [220, 2.6, 0.75, 1.0]].forEach(function (cfg) {   /* night: many faint + a few bright; day: one faint sparkle set */ var n = cfg[0], p = [], c = []; for (var i = 0; i < n; i++) { var el = Math.asin(rnd()) * 0.98 + 0.02, az = rnd() * Math.PI * 2, r = 370; p.push(Math.cos(el) * Math.sin(az) * r, Math.sin(el) * r, Math.cos(el) * Math.cos(az) * r); var b = cfg[2] + rnd() * (cfg[3] - cfg[2]); var tint = rnd(); c.push(b * (tint < 0.2 ? 0.85 : 1), b * (tint < 0.2 ? 0.9 : 1), b * (tint > 0.8 ? 0.9 : 1)); } var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(p, 3)); g.setAttribute('color', new THREE.Float32BufferAttribute(c, 3)); var pts = new THREE.Points(g, new THREE.PointsMaterial({ size: cfg[1], sizeAttenuation: false, vertexColors: true, transparent: true, opacity: 0.10, fog: false, depthWrite: false }));   /* barely there in daylight */ pts.frustumCulled = false; pts.name = 'MAHWORLD_SKY_STARS'; pts.visible = NIGHT; sky.add(pts); });   /* B8 §20: the star clouds always exist; they show in the NIGHT state */
    /* moon: ahead of the default spawn view (camera yaw 0.35 looks toward -sin/-cos), low above the horizon so it is in frame without looking up */
    var dir = new THREE.Vector3(-Math.sin(0.35), 0, -Math.cos(0.35)); var moonEl = 0.085;   /* ~5 deg: the disc straddles the horizon so its upper half is in frame even at the default downward camera pitch */ var moonPos = dir.clone().multiplyScalar(Math.cos(moonEl) * 330); moonPos.y = Math.sin(moonEl) * 330;
    { var moonMat = new THREE.MeshBasicMaterial({ map: moonTexture(), transparent: true, opacity: 0.92, fog: false, depthWrite: false }); var moon = quadBatch([{ x: moonPos.x, y: moonPos.y, z: moonPos.z, w: 84, h: 84, c: [1, 1, 1] }], moonMat); moon.renderOrder = -8; moon.name = 'MAHWORLD_SKY_MOON'; moon.visible = NIGHT; sky.add(moon); }
    { /* DAY: the sun sits where the key light comes from (26,34,14): a warm core with a wide soft glow, additive so it reads through the dome */ var sunDir = new THREE.Vector3(26, 34, 14).normalize().multiplyScalar(330); var sunMat = new THREE.MeshBasicMaterial({ toneMapped: false, map: canvasTex(256, 256, function (g, w, h) { g.clearRect(0, 0, w, h); var gr = g.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, w / 2); gr.addColorStop(0, 'rgba(255,250,232,1)'); gr.addColorStop(0.12, 'rgba(255,246,214,0.95)'); gr.addColorStop(0.3, 'rgba(255,238,200,0.35)'); gr.addColorStop(1, 'rgba(255,230,190,0)'); g.fillStyle = gr; g.fillRect(0, 0, w, h); }), transparent: true, fog: false, depthWrite: false, blending: THREE.AdditiveBlending }); var sun = quadBatch([{ x: sunDir.x, y: sunDir.y, z: sunDir.z, w: 150, h: 150, c: [1, 1, 1] }], sunMat); sun.renderOrder = -8; sun.name = 'MAHWORLD_SKY_SUN'; sun.visible = !NIGHT; sky.add(sun); }
    { var haloMat = new THREE.MeshBasicMaterial({ map: haloTexture(), transparent: true, fog: false, depthWrite: false, blending: THREE.AdditiveBlending }); var halo = quadBatch([{ x: moonPos.x * 1.02, y: moonPos.y * 1.02, z: moonPos.z * 1.02, w: 120, h: 120, c: [0.5, 0.52, 0.55] }], haloMat); halo.renderOrder = -9; halo.name = 'MAHWORLD_SKY_MOON_HALO'; halo.visible = NIGHT; sky.add(halo); }
    /* distant cloud-skyland: a floating land mass of clouds on the horizon, off to the side of the moon and behind the spawn; far outside the field, no collider */
    var landMat = new THREE.MeshBasicMaterial({ map: skylandTexture(), transparent: true, opacity: NIGHT ? 0.62 : 0.78, fog: false, depthWrite: false, vertexColors: true, toneMapped: false }); var lands = []; [[0.35 + 0.9, 340, 190, 34, 0.055, [0.58, 0.66, 0.78]], [0.35 - 0.75, 350, 160, 29, 0.045, [0.54, 0.63, 0.77]], [0.35 + Math.PI, 345, 230, 38, 0.05, [0.56, 0.64, 0.76]]].forEach(function (L) { var d = new THREE.Vector3(-Math.sin(L[0]), 0, -Math.cos(L[0])); var el = L[4]; lands.push({ x: d.x * Math.cos(el) * L[1], y: Math.sin(el) * L[1] + L[3] * 0.18, z: d.z * Math.cos(el) * L[1], w: L[2], h: L[3], c: L[5] }); }); var land = quadBatch(lands, landMat); land.name = 'MAHWORLD_SKY_DISTANT_BANKS'; land.renderOrder = -7; skyFixed.add(land);
    /* dimensional clouds: layered translucent sheets around the horizon with a faint blue-violet glow, drifting slowly (driven from onBeforeRender: no per-frame hook needed elsewhere) */
    var cloudMat = new THREE.MeshBasicMaterial({ map: cloudTexture(), transparent: true, fog: false, depthWrite: false, vertexColors: true, toneMapped: false, opacity: NIGHT ? 0.5 : 0.82, blending: NIGHT ? THREE.AdditiveBlending : THREE.NormalBlending });   /* fallback only: world/sky.js disables this independent wall-clock layer once its registry wind/optics system is ready */ var clouds = []; for (var i = 0; i < (NIGHT ? 14 : qGet().clouds); i++) { var az = rnd() * Math.PI * 2, el = 0.06 + rnd() * 0.22, r = 250 + rnd() * 90, w = 90 + rnd() * 120, h = w * (0.3 + rnd() * 0.25); var violet = rnd(); clouds.push({ x: Math.cos(el) * Math.sin(az) * r, y: Math.sin(el) * r, z: Math.cos(el) * Math.cos(az) * r, w: w, h: h, c: violet < 0.4 ? [1, 0.99, 0.96] : [0.93, 0.95, 0.99] }); } var cloudMesh = quadBatch(clouds, cloudMat); cloudMesh.name = 'MAHWORLD_SKY_LEGACY_CLOUDS'; cloudMesh.renderOrder = -6; cloudMesh.onBeforeRender = function () { var t = performance.now() * 0.001; cloudMesh.rotation.y = t * 0.004; cloudMat.opacity = (NIGHT ? 0.5 : 0.86) + 0.08 * Math.sin(t * 0.3); }; skyFixed.add(cloudMesh);
  }
  /* P8: an INTERIOR environment (PMREM of a small procedural studio: light ceiling panels, mid walls, dark floor) so metallic bodies and chrome keep their reflections inside a hall
     (the field's sky PMREM is disposed with the field; without any environment a metallic character renders black). Built once per renderer, cached, never disposed by clear(). */
  var roomEnvTex = null; function roomEnvironment() { if (roomEnvTex) return roomEnvTex; if (!RENDERER || !THREE.PMREMGenerator) return null; var es = new THREE.Scene(); var W = 20, Hh = 6; var mk = function (w, h, d, col, x, y, z, emis) { var m = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), new THREE.MeshStandardMaterial({ color: col, emissive: emis || 0x000000, emissiveIntensity: emis ? 1 : 0, roughness: 0.6, metalness: 0.2, side: THREE.BackSide })); m.position.set(x, y, z); es.add(m); return m; }; mk(W, Hh, W, 0x8d96a3, 0, Hh / 2, 0);   /* the room shell seen from inside */ for (var i = -2; i <= 2; i++) { var panel = new THREE.Mesh(new THREE.PlaneGeometry(1.2, W * 0.8), new THREE.MeshBasicMaterial({ color: new THREE.Color(3.2, 3.4, 3.8) })); panel.rotation.x = Math.PI / 2; panel.position.set(i * 3.6, Hh - 0.05, 0); es.add(panel); } var fl = new THREE.Mesh(new THREE.PlaneGeometry(W, W), new THREE.MeshBasicMaterial({ color: 0x141a24 })); fl.rotation.x = -Math.PI / 2; fl.position.y = 0.02; es.add(fl); es.add(new THREE.HemisphereLight(0xffffff, 0x223, 1.2)); var gen = new THREE.PMREMGenerator(RENDERER); var rt = gen.fromScene(es, 0.04, 0.3, 60); gen.dispose(); roomEnvTex = rt.texture; return roomEnvTex; }
  var api = {
    roomEnvironment: roomEnvironment,
    build: function (layout, sizeM) {
      var key = layout ? layout.version + ':' + layout.shapes.length : 'none'; if (built === key) return; built = key; clear(); shapes = layout ? layout.shapes : [];
      var worldSize = sizeM || 30; var size = Math.min(worldSize, 112);   /* S11: the authored plaza floor stays 112 m; the district ground (below) covers the whole field */ var city = createCityScene(THREE, group, { surfaceTier: sdTier(), roundedBox: roundedBox, canvasTex: canvasTex, horizonRadius: worldSize > 200 ? 380 : 150, night: NIGHT, fins: qGet().city_fins }); /* FLOOR (S09 §31): one authored platinum / chromium surface — sweeping curved seams around the plaza, embedded diamond inlays, metallic-blue
         detail bands and directional pathway inlays toward the four entrances and the tree elevator. No grid, no checker. The map is painted once
         (2048², sRGB) and stretched over the whole field so nothing repeats. */
      var GROUND_PX = (function () { var tc = defaultTextureCap(); return tc ? Math.min(2048, tc.maxEdge()) : 2048; })();   /* B8 P0: the two ground canvases follow the tier's texture edge (1024 on the phone) */ var floorTex = canvasTex(GROUND_PX, GROUND_PX, function (g, w, h) { var cx = w / 2, cz = h / 2, k = w / size;   /* k px per metre */
        var base = g.createRadialGradient(cx, cz, 10, cx, cz, w * 0.72); base.addColorStop(0, NIGHT ? '#2a3140' : '#8e939b'); base.addColorStop(0.55, NIGHT ? '#1a2029' : '#7b8089'); base.addColorStop(1, NIGHT ? '#0e1219' : '#6a6f78');   /* S11: blackened platinum at night; WORLD PIVOT PASS 2: a light platinum-stone plaza by day (graphite seams, grain and inlays stay) */ g.fillStyle = base; g.fillRect(0, 0, w, h);
        /* brushed platinum grain */ g.globalAlpha = 0.07; for (var i = 0; i < 900; i++) { var ang = Math.random() * Math.PI * 2, r0 = Math.random() * w * 0.75, len = 40 + Math.random() * 220; g.strokeStyle = Math.random() < 0.5 ? '#dfe7f0' : '#0b1220'; g.lineWidth = 1 + Math.random() * 2; g.beginPath(); g.moveTo(cx + Math.cos(ang) * r0, cz + Math.sin(ang) * r0); g.lineTo(cx + Math.cos(ang + 0.004) * (r0 + len), cz + Math.sin(ang + 0.004) * (r0 + len)); g.stroke(); } g.globalAlpha = 1;
        /* sweeping curved seams */ [12, 19, 27, 36, 46].forEach(function (rm, i) { g.strokeStyle = i % 2 ? 'rgba(191,230,255,0.28)' : 'rgba(120,150,190,0.35)'; g.lineWidth = i % 2 ? 3 : 5; g.beginPath(); g.arc(cx, cz, rm * k, 0, Math.PI * 2); g.stroke(); g.strokeStyle = 'rgba(8,14,26,0.45)'; g.lineWidth = 2; g.beginPath(); g.arc(cx, cz, rm * k + 5, 0, Math.PI * 2); g.stroke(); });
        for (var sw = 0; sw < 6; sw++) { g.strokeStyle = 'rgba(160,200,240,0.18)'; g.lineWidth = 4; g.beginPath(); g.arc(cx + Math.cos(sw * 1.05) * 30 * k, cz + Math.sin(sw * 1.05) * 30 * k, 22 * k, sw * 1.05 + 2.2, sw * 1.05 + 3.9); g.stroke(); }
        /* directional pathway inlays: plaza -> entrances and -> tree elevator (soft luminous guides) */ [[-17, 0], [0, -19.5], [18, 0], [1, 20], [30, 40], [-30, 30]].forEach(function (pt) { var gx = cx + pt[0] * k, gz = cz + pt[1] * k; var d = Math.hypot(gx - cx, gz - cz); var gr = g.createLinearGradient(cx, cz, gx, gz); gr.addColorStop(0, 'rgba(120,170,220,0)'); gr.addColorStop(0.35, 'rgba(120,170,220,0.22)'); gr.addColorStop(1, 'rgba(191,230,255,0.42)'); g.strokeStyle = gr; g.lineWidth = 2.6 * k; g.lineCap = 'round'; g.beginPath(); g.moveTo(cx + (gx - cx) * (11 * k) / d, cz + (gz - cz) * (11 * k) / d); g.lineTo(gx, gz); g.stroke(); });
        /* embedded diamonds along the seams */ g.fillStyle = 'rgba(223,243,255,0.55)'; for (var dm = 0; dm < 48; dm++) { var a2 = dm / 48 * Math.PI * 2, rr2 = (dm % 2 ? 19 : 27) * k; var dx = cx + Math.cos(a2) * rr2, dz = cz + Math.sin(a2) * rr2; g.beginPath(); g.moveTo(dx, dz - 9); g.lineTo(dx + 5, dz); g.lineTo(dx, dz + 9); g.lineTo(dx - 5, dz); g.closePath(); g.fill(); }
        /* metallic-blue detail bands near the walls */ g.strokeStyle = 'rgba(70,120,190,0.35)'; g.lineWidth = 14; g.beginPath(); g.arc(cx, cz, 52 * k, 0, Math.PI * 2); g.stroke(); });
      var floor = new THREE.Mesh(new THREE.PlaneGeometry(size, size), new THREE.MeshStandardMaterial({ map: floorTex, color: 0xffffff, roughness: NIGHT ? 0.22 : 0.5, metalness: NIGHT ? 0.86 : 0.88, envMapIntensity: NIGHT ? 1 : 0.16 })   /* JOB B: the registry ground policy (OPAQUE platinum, reflected-light prominence ~0.15 via roughness / metalness / env, never opacity) re-tunes this when the registry arrives */   /* daylight: the black platinum floor keeps a soft sky sheen, not a pale mirror (the PMREM sky is bright at the horizon) */); floor.rotation.x = -Math.PI / 2; floor.position.y = 0.012; floor.receiveShadow = true; group.add(floor); shapes.forEach(function (s0) { if (s0.landmark && s0.landmark.kind === 'TREE_ELEVATOR') pavingHalo = { x: s0.x, z: s0.z, r: 18 }; }); pavingZones.setFromRegistry(worldReg, { halo: pavingHalo }); zonedPaving(THREE, floor.material, pavingZones, { tier: sdTier() });   /* M8 → M8B: zoned paving language (rings at the hub and the HALO base, district families, threshold courses, soft ecology patches) */
      if (worldSize > size + 1) { var farWorld = createFarWorld(THREE, { night: NIGHT }); group.add(farWorld);   /* PASS 2b: three depth layers beyond the district (mid walkways / far crystalline massifs / haze plain) — the sky and far background scale illusion, no colliders */ }
      if (worldSize > size + 1) { /* S11 DISTRICT GROUND: dark graphite / blackened platinum with soft silver reflections and cool metallic-blue route inlays (radial routes plaza -> each landmark), no grid */
        var dSize = worldSize; var dTex = canvasTex(GROUND_PX, GROUND_PX, function (g, w, h) { var cx = w / 2, cz = h / 2, k = w / dSize; var base2 = g.createRadialGradient(cx, cz - 60 * k, 20, cx, cz, w * 0.7); base2.addColorStop(0, NIGHT ? '#1a1f28' : '#767b83'); base2.addColorStop(0.5, NIGHT ? '#111519' : '#656970'); base2.addColorStop(1, NIGHT ? '#090b0f' : '#55595f');   /* WORLD PIVOT PASS 2: warm platinum-stone district ground by day */ g.fillStyle = base2; g.fillRect(0, 0, w, h);
          g.globalAlpha = 0.06; for (var i = 0; i < 1400; i++) { var ang = Math.random() * Math.PI * 2, r0 = Math.random() * w * 0.7, len = 60 + Math.random() * 300; g.strokeStyle = Math.random() < 0.55 ? '#cfd8e2' : '#05070b'; g.lineWidth = 1 + Math.random() * 2; g.beginPath(); g.moveTo(cx + Math.cos(ang) * r0, cz + Math.sin(ang) * r0); g.lineTo(cx + Math.cos(ang + 0.003) * (r0 + len), cz + Math.sin(ang + 0.003) * (r0 + len)); g.stroke(); } g.globalAlpha = 1;
          var routes = (layout.landmarks || []).map(function (l) { return [l.x, l.z]; }); routes.forEach(function (pt) { var gx = cx + pt[0] * k, gz = cz + pt[1] * k; var gr = g.createLinearGradient(cx, cz + 56 * k, gx, gz); gr.addColorStop(0, 'rgba(120,170,220,0.05)'); gr.addColorStop(0.6, 'rgba(120,170,220,0.16)'); gr.addColorStop(1, 'rgba(191,230,255,0.30)'); g.strokeStyle = gr; g.lineWidth = 4.5 * k; g.lineCap = 'round'; g.beginPath(); g.moveTo(cx, cz + 56 * k); g.lineTo(gx, gz); g.stroke(); g.strokeStyle = 'rgba(180,200,225,0.22)'; g.lineWidth = 0.5 * k; g.beginPath(); g.arc(gx, gz, 44 * k, 0, Math.PI * 2); g.stroke(); });
          var temple = routes[0]; if (temple) { g.strokeStyle = 'rgba(70,120,190,0.30)'; g.lineWidth = 2.2 * k; g.beginPath(); g.arc(cx + temple[0] * k, cz + temple[1] * k, 48 * k, 0, Math.PI * 2); g.stroke(); g.strokeStyle = 'rgba(200,215,230,0.14)'; g.lineWidth = 0.6 * k; g.beginPath(); g.arc(cx + temple[0] * k, cz + temple[1] * k, 60 * k, 0, Math.PI * 2); g.stroke(); } });
        var dFloor = new THREE.Mesh(new THREE.PlaneGeometry(dSize, dSize), new THREE.MeshStandardMaterial({ map: dTex, color: 0xffffff, roughness: NIGHT ? 0.26 : 0.5, metalness: NIGHT ? 0.82 : 0.84, envMapIntensity: NIGHT ? 1 : 0.2 })); dFloor.rotation.x = -Math.PI / 2; dFloor.position.y = -0.005; dFloor.name = 'DISTRICT_GROUND'; zonedPaving(THREE, dFloor.material, pavingZones, { tier: sdTier() }); dFloor.userData.noMerge = true; group.add(dFloor); groundMats.push(floor.material, dFloor.material); districtFloor = { mesh: dFloor, size: dSize };
        loadDistrict(layout); }
      var grid = { visible: false };   /* the grid floor is gone (S09) */
      var ring = new THREE.Mesh(new THREE.RingGeometry(size * 0.46, size * 0.47, 64), new THREE.MeshBasicMaterial({ color: 0xdfe8ff, transparent: true, opacity: 0.25, side: THREE.DoubleSide, polygonOffset: true, polygonOffsetFactor: -1, polygonOffsetUnits: -2 })); ring.rotation.x = -Math.PI / 2; ring.position.y = 0.015; group.add(ring);
      var chrome = metal(NIGHT ? 0xb8c2cc : 0xaab3be, NIGHT ? 0.34 : 0.3, NIGHT ? 0.95 : 0.9), platinum = metal(NIGHT ? 0xcdd4dc : 0xbfc6d0, NIGHT ? 0.48 : 0.42, NIGHT ? 0.8 : 0.62),   /* WORLD PIVOT PASS 3: by day the plaza proxies are satin platinum / brushed chrome (full-env mirror metal read as white sky cut-outs) */   /* night: a little rougher so chrome never clips to white */ trim = new THREE.MeshStandardMaterial({ color: 0xe6ecf6, emissive: 0xd6e0ff, emissiveIntensity: 0.9, roughness: 0.4, metalness: 0.2 }); var plinthStone = platinum; if (!NIGHT) { chrome.envMapIntensity = 0.7; platinum.envMapIntensity = 0.62; plinthStone = new THREE.MeshStandardMaterial({ color: 0x3a3f4a, roughness: 0.6, metalness: 0.3, envMapIntensity: 0.4 }); trim.emissiveIntensity = 0.4; }   /* M8: by day the white light trims glow at 0.4 (0.9 stacked a white halo on every ledge and pad) */
      applySurface(THREE, chrome, 'BRUSHED', sdTier()); applySurface(THREE, platinum, 'STRUCTURE', sdTier()); if (plinthStone !== platinum) applySurface(THREE, plinthStone, 'STONE', sdTier());
      shapes.forEach(function (s) {
        if (s.building) { city.building(s); return; }
        if (s.landmark && s.landmark.kind === 'TREE_ELEVATOR') { city.treeElevator(s, shapes); return; }
        if (s.pod) { city.pod(s); return; }
        if (s.rim) return;   /* platform rims are invisible guards (the platform edge lip is drawn by treeElevator) */
        if (s.walkable) return;   /* the walkable platform is drawn by the landmark */
        if (s.type === 'BOX') { var w = s.x2 - s.x1, d = s.z2 - s.z1; var m; if (s.rounded) { m = new THREE.Mesh(roundedBox(w, s.h, d, Math.min(w, d) * 0.45), platinum); } else { m = new THREE.Mesh(new THREE.BoxGeometry(w, s.h, d), chrome); m.position.y = s.h / 2; } m.position.x = (s.x1 + s.x2) / 2; m.position.z = (s.z1 + s.z2) / 2; if (s.rounded) m.position.y = 0; group.add(m); if (!s.rounded && s.h >= 2.5) { var strip = new THREE.Mesh(new THREE.BoxGeometry(w + 0.02, 0.06, d + 0.02), trim); strip.position.set(m.position.x, s.h - 0.4, m.position.z); group.add(strip); } if (s.rounded) { var glow = new THREE.Mesh(new THREE.BoxGeometry(w * 0.9, 0.04, 0.04), trim); glow.position.set(m.position.x, s.h + 0.05, m.position.z); group.add(glow); } }
        if (s.type === 'CYLINDER') { var cyl = new THREE.Mesh(new THREE.CylinderGeometry(s.r, s.r * 1.15, s.h, 24), chrome); cyl.position.set(s.x, s.h / 2, s.z); group.add(cyl); var cap = new THREE.Mesh(new THREE.TorusGeometry(s.r * 1.05, 0.05, 8, 32), trim); cap.rotation.x = Math.PI / 2; cap.position.set(s.x, s.h - 0.3, s.z); group.add(cap); var base = new THREE.Mesh(new THREE.CylinderGeometry(s.r * 1.5, s.r * 1.6, 0.15, 24), plinthStone); base.position.set(s.x, 0.075, s.z); group.add(base); }
        if (s.type === 'RAMP') { var w2 = s.x2 - s.x1, d2 = s.z2 - s.z1; var hi = Math.max(s.h0, s.h1), lo = Math.min(s.h0, s.h1); var geo = new THREE.BufferGeometry(); var risingX = s.axis === 'x'; var x1 = s.x1, x2 = s.x2, z1 = s.z1, z2 = s.z2; var hA = s.h0, hB = s.h1; /* h0 at x1 (or z1), h1 at x2 (or z2) */
          var v = risingX ? [x1, hA, z1, x2, hB, z1, x2, hB, z2, x1, hA, z2, x1, 0, z1, x2, 0, z1, x2, 0, z2, x1, 0, z2] : [x1, hA, z1, x2, hA, z1, x2, hB, z2, x1, hB, z2, x1, 0, z1, x2, 0, z1, x2, 0, z2, x1, 0, z2];
          var idx = [0, 2, 1, 0, 3, 2, 4, 5, 6, 4, 6, 7, 0, 1, 5, 0, 5, 4, 1, 2, 6, 1, 6, 5, 2, 3, 7, 2, 7, 6, 3, 0, 4, 3, 4, 7]; geo.setAttribute('position', new THREE.Float32BufferAttribute(v, 3)); geo.setIndex(idx); geo.computeVertexNormals(); var ramp = new THREE.Mesh(geo, platinum); group.add(ramp); var edge = new THREE.Mesh(new THREE.BoxGeometry(risingX ? w2 : 0.05, 0.04, risingX ? 0.05 : d2), trim); edge.position.set((x1 + x2) / 2, hi + 0.03, risingX ? z1 : (z1 + z2) / 2); group.add(edge); }
      });
      city.dress(size);
      /* P8 door thresholds: every ENTER interactable of the layout gets a lit pad + a doorway frame at its point (the contextual prompt appears inside the pad's range) */
      (layout && layout.interactables ? layout.interactables : []).filter(function (it) { return it.kind === 'ENTER'; }).forEach(function (it) { var pad = new THREE.Mesh(new THREE.RingGeometry(Math.max(0.8, (it.range_m || 3) - 0.12), (it.range_m || 3), 48), trim); pad.rotation.x = -Math.PI / 2; pad.position.set(it.x, 0.03, it.z); pad.userData.noMerge = true; group.add(pad); var lamp = new THREE.Mesh(new THREE.CylinderGeometry(0.09, 0.12, 2.6, 10), chrome); lamp.position.set(it.x, 1.3, it.z); group.add(lamp); var cap = new THREE.Mesh(new THREE.SphereGeometry(0.16, 12, 10), trim); cap.position.set(it.x, 2.72, it.z); group.add(cap); });
      mergeInfo = { merged_meshes: 0, into: 0, skipped: 0, vertices: 0 }; if (!(fsOpts && fsOpts.merge === false)) { try { mergeStatic(group, 120); } catch (e) { mergeInfo.error = e && e.message; } }
      /* P7 BOTANICAL PROTOTYPE (master §14.5): one specimen + one small cluster placed from the registry AFTER the static merge (instanced, noMerge). Reversible: ?botany=0 or fsOpts.botany === false. A rebuild disposes and re-places — instances never accumulate (U14). */
      if (!(fsOpts && fsOpts.botany === false)) { try { botany = createMahgicTreeFamily(THREE, { night: NIGHT }); group.add(botany.group); botanyInfo = { status: 'LOADING' }; var bkey = key;
        fetch('assets/botany/prototype_v1.json').then(function (r) { return r.json(); }).then(function (reg) { if (built !== bkey || !botany) return; botany.place(reg.instances || []); botanyInfo = { status: 'PLACED', registry: reg.version, registry_status: reg.status }; }).catch(function (e) { botanyInfo = { status: 'REGISTRY_FAILED', error: String(e && e.message || e) }; }); } catch (e) { botany = null; botanyInfo = { status: 'FAILED', error: String(e && e.message || e) }; } }
      /* JOB B WORLD LAYER (after the static merge — the layer is noMerge and instanced): registry → landmark looks / ground policy → modules; its host-equivalent solids join the camera boom */
      if (WORLD_ON && worldSize > size + 1 && layout) { try { worldInfo = { status: 'LOADING' }; var wkey = key; var wb = createWorldB(THREE, group, { night: NIGHT, quality: QUALITY, renderer: RENDERER, playerPos: fsOpts && fsOpts.playerPos, cameraPos: fsOpts && fsOpts.cameraPos, playerHeading: fsOpts && fsOpts.playerHeading, playerHand: fsOpts && fsOpts.playerHand, playerSocket: fsOpts && fsOpts.playerSocket, applyCelestialLight: applyCelestialLight, log: fsOpts && fsOpts.log }); worldB = wb;
        fetch('assets/world/world_registry_v1.json').then(function (r) { return r.json(); }).then(function (reg) { if (built !== wkey || worldB !== wb) return; worldReg = reg; try { pavingZones.setFromRegistry(reg, { halo: pavingHalo }); } catch (e) { } try { var sdA = reg.celestial && reg.celestial.sun && reg.celestial.sun.direction; CELESTIAL_KEY.direction = NIGHT ? moonDirection() : normalizedDirection(sdA, [26, 19, 14]); positionCelestialKey(0, 0); var lsun = group.getObjectByName('MAHWORLD_SKY_SUN'); if (lsun && sdA) { var sdv = new THREE.Vector3(sdA[0], sdA[1], sdA[2]).normalize().multiplyScalar((reg.celestial.sun && reg.celestial.sun.distance_m) || 900); lsun.position.copy(sdv); } } catch (e) { }   /* registry direction reaches both the active key and the legacy fallback; Moon/cloud will then drive the same key through the bounded hook */ Object.keys(landmarkGroups).forEach(function (id) { applyLandmarkLook(landmarkGroups[id], id); }); applyGroundPolicy(); try { cutFloorForWater(reg); } catch (e) { worldInfo.floor_cut_error = String(e && e.message || e); } var lms = (layout.landmarks || []).map(function (l) { return l.envelope; }); worldShapes = worldColliders(reg, lms); var zg = {}; worldShapes.forEach(function (sh) { var e = zg[sh.zone] = zg[sh.zone] || { x1: 1e9, z1: 1e9, x2: -1e9, z2: -1e9, shapes: [], world: true }; e.shapes.push(sh); var bx1 = sh.type === 'CYLINDER' ? sh.x - sh.r : sh.x1, bx2 = sh.type === 'CYLINDER' ? sh.x + sh.r : sh.x2, bz1 = sh.type === 'CYLINDER' ? sh.z - sh.r : sh.z1, bz2 = sh.type === 'CYLINDER' ? sh.z + sh.r : sh.z2; e.x1 = Math.min(e.x1, bx1); e.z1 = Math.min(e.z1, bz1); e.x2 = Math.max(e.x2, bx2); e.z2 = Math.max(e.z2, bz2); }); districtGroups = districtGroups.filter(function (g) { return !g.world; }).concat(Object.keys(zg).map(function (k) { return zg[k]; })); worldInfo = { status: 'BUILDING', registry: reg.version };
          return wb.build(layout, reg).then(function () { if (built !== wkey || worldB !== wb) return; worldInfo = { status: 'READY', registry: reg.version }; var cel = wb.modules().celestial, wsky = wb.modules().sky; if (cel && !cel.failed) { ['MAHWORLD_SKY_SUN', 'MAHWORLD_SKY_MOON', 'MAHWORLD_SKY_MOON_HALO'].forEach(function (nm) { var o = group.getObjectByName(nm); if (o) o.visible = false; }); } var lc = group.getObjectByName('MAHWORLD_SKY_LEGACY_CLOUDS'); if (lc && wsky && !wsky.failed) lc.visible = false;   /* one celestial and one cloud clock: registry modules replace every legacy counterpart */ }); }).catch(function (e) { worldInfo = { status: 'FAILED', error: String(e && e.message || e) }; }); } catch (e) { worldInfo = { status: 'FAILED', error: String(e && e.message || e) }; worldB = null; } }
      TIME_STATE.sizeM = sizeM || 30; buildLights(NIGHT);
      /* WORLD PIVOT (checkpoint 7): the legacy inline light rig that used to follow here was written as `if (false) { NIGHT } else { DAY }` —
         so its DAY branch ALWAYS ran after buildLights() and stacked a second daylight rig (key 2.35 + hemi 1.15 + rim + fill, and it
         re-pointed `sun`) until the first time-state prewarm / toggle rebuilt the lights. buildLights() alone owns background, fog and rig. */
      env = skyEnvironment(); if (RENDERER && THREE.PMREMGenerator) { try { var pm = pmremSky(false); if (pm) { pmremTex = pm; if (!NIGHT) env = pm; } } catch (e) { } } scene.environment = env; TIME_STATE.envDay = pmremTex || env; TIME_STATE.envNight = null;   /* NIGHT-first must still own the same PMREM/CubeUV-kind DAY environment: late-loaded materials can then reuse their NIGHT shader on the first live DAY frame instead of compiling a second raw-cube variant. */
      buildSky();
      for (var i = 0; i < 4; i++) { var beacon = new THREE.Mesh(new THREE.SphereGeometry(0.18, 10, 8), new THREE.MeshBasicMaterial({ color: 0x9fd0ff })); beacon.position.set(i < 2 ? -14 : 14, 3.2, i % 2 ? -14 : 14); group.add(beacon); }
    },
    /* local camera collision: shorten the camera boom until the camera point is outside every solid (presentation only) */
    setQuality: function (T) { lods.forEach(function (l) { if (l.levels[1]) l.levels[1].distance = Math.min(l.userData.baseDistance || Infinity, T.lod_far_m || Infinity); }); if (scene.fog && !NIGHT) scene.fog.far = fogFarBase * (T.fog_far_scale || 1); if (sun && RENDERER) { var on = T.shadows && T.shadows !== 'off'; if (sun.castShadow !== on) { sun.castShadow = on; RENDERER.shadowMap.needsUpdate = true; } if (on) { var reach = T.shadow_reach_m || 24; sun.shadow.camera.left = -reach; sun.shadow.camera.right = reach; sun.shadow.camera.top = reach; sun.shadow.camera.bottom = -reach; sun.shadow.camera.updateProjectionMatrix(); if (sun.shadow.map && sun.shadow.mapSize.x !== (T.shadow_map || 1024)) { sun.shadow.map.dispose(); sun.shadow.map = null; sun.shadow.mapSize.set(T.shadow_map || 1024, T.shadow_map || 1024); } } } },
    follow: function (x, z) { positionCelestialKey(x, z); },   /* the shadow box follows the player while its normalized Sun/Moon direction stays fixed */
    lightSet: function (o) { o = o || {}; lights.forEach(function (l) { if (l.isHemisphereLight) { if (o.hemi !== undefined) l.intensity = o.hemi; } else if (l === sun) { if (o.key !== undefined) { CELESTIAL_KEY.base_intensity = o.key; l.intensity = o.key * CELESTIAL_KEY.key_transmission; } } else if (l.isDirectionalLight && o.fill !== undefined && Math.abs(l.intensity - 0.34) < 0.2) l.intensity = o.fill; }); if (o.envIntensity !== undefined) scene.traverse(function (m) { if (m.isMesh && m.material && m.material.envMapIntensity !== undefined && !m.material.userData.mw) m.material.envMapIntensity = o.envIntensity; }); return lights.map(function (l) { return { type: l.type, intensity: +l.intensity.toFixed(2) }; }); },
    skyFollow: function (x, z) { var sk = group.getObjectByName('MAHWORLD_SKY'); if (sk) sk.position.set(x, 0, z); },   /* the dome + sun disc (+ stars) ride with the viewer like a skybox: never clipped off-centre; clouds / skyland are in MAHWORLD_SKY_FIXED (world-fixed) */
    sunInfo: function () { return sun ? { shadows: !!sun.castShadow, map: sun.shadow.mapSize.x, reach: sun.shadow.camera.right, env: pmremTex ? 'pmrem' : 'cube' } : null; },   /* live: LOD reach + fog; clouds / fins apply on the next build */
    lodInfo: function () { return lods.map(function (l) { return { level: l.getCurrentLevel(), distances: l.levels.map(function (x) { return x.distance; }) }; }); },
    mergeInfo: function () { return mergeInfo; },
    botany: function () { var o = { status: botanyInfo.status, registry: botanyInfo.registry || null, registry_status: botanyInfo.registry_status || null, error: botanyInfo.error || null }; if (botany) { var i = botany.info(); Object.keys(i).forEach(function (k) { o[k] = i[k]; }); } return o; },   /* P7 read-out: placed instances (identity / position / crown top), draw calls, tri budget, energy state, the scale record */
    botanyEnergy: function (on) { if (botany) botany.setEnergy(on); return botany ? botany.energy() : null; },
    botanyVisible: function (on) { if (botany) botany.group.visible = on !== false; return botany ? botany.group.visible : null; },   /* matched workload measurement in ONE page load (family hidden / shown, same camera) */   /* effects off = the physical silhouette only (master §14.2 item 6) */
    world: function () { return worldB; }, worldInfo: function () { var o = { status: worldInfo.status, registry: worldInfo.registry || null, error: worldInfo.error || null, shapes: worldShapes.length, floor_cut: districtFloor ? (districtFloor.cut || 0) : null, floor_cut_error: worldInfo.floor_cut_error || null }; if (worldB && worldInfo.status === 'READY') o.modules = worldB.debug(); return o; }, worldShapes: function () { return worldShapes; }, worldRegistry: function () { return worldReg; },   /* JOB B read-outs (map, dev, evidence probes) */
    night: function () { return NIGHT; }, setNight: setNight, prewarmTimeStates: prewarmTimeStates, timePrewarmState: function () { return Object.assign({}, TIME_STATE.prewarm, { states: TIME_STATE.prewarm.states.slice() }); }, timeOfDay: function () { return NIGHT ? 'NIGHT' : 'DAY'; }, debugShapes: function (x, z) { return { built: shapes.length, groups: districtGroups.length, near: shapesNear(x, z, 3).slice(0, 12).map(function (s) { return { type: s.type, x1: s.x1, x2: s.x2, z1: s.z1, z2: s.z2, x: s.x, z: s.z, r: s.r, y0: s.y0, h: s.h }; }) }; },
    blockingShape: function (x, y, z, r) { var s = pointBlocked(x, y, z, r || 0.3); return s ? { id: s.id, type: s.type, h: s.h, y0: s.y0, x1: s.x1, x2: s.x2, z1: s.z1, z2: s.z2, x: s.x, z: s.z, r: s.r, district: s.district } : null; },   /* dev / evidence: which layout shape blocks a point (the camera boom's own test) */
    cameraDistance: function (target, yaw, pitch, wanted, radius) { var r = radius || 0.3; var blocked = function (d) { var cx = target.x + Math.sin(yaw) * Math.cos(pitch) * d, cz = target.z + Math.cos(yaw) * Math.cos(pitch) * d, cy = target.y + Math.sin(pitch) * d; return !!pointBlocked(cx, cy, cz, r); }; for (var d = 1.1; d < wanted; d += (d < 12 ? 0.2 : 0.75)) { if (blocked(d)) { if (d <= 1.1 + 1e-6) { for (var f = 0.9; f >= 0.55; f -= 0.1) if (!blocked(f)) return f; return 0.5; } return Math.max(1.0, d - 0.2); } } return blocked(wanted) ? Math.max(1.0, wanted - 0.2) : wanted; },   /* a boom blocked at the very first sample walks back to the first CLEAR point (0.9 … 0.55 m) instead of a fixed 1.0 m that may sit inside the obstacle */   /* Spec B spring-arm probe: a sphere of `radius` swept along the boom; the first blocked sample ends the boom just short of it */
    pointBlocked: function (x, y, z, r) { return pointBlocked(x, y, z, r || 0); },
    probeSolids: function (list) { if (list && list.length) { if (!hidden.saved) hidden.saved = { shapes: shapes, groups: districtGroups }; shapes = list.slice(); districtGroups = []; } else if (hidden.saved) { shapes = hidden.saved.shapes; districtGroups = hidden.saved.groups; hidden.saved = null; } else if (!built) { shapes = []; } },   /* P8: an interior's wall boxes stand in for the layout while the field is HIDDEN (camera boom only); the field's own shapes come back with it */
    /* P8 single-owner scene transaction: entering a hall HIDES the built field (group, lights, sky, fog, environment kept aside) instead of disposing it, so the EXIT back is warm — no GLB reload, no 2 s wait — and nothing is duplicated (build() is keyed and never rebuilds a built layout) */
    setHidden: function (h) { if (h) { if (hidden.on) return true; hidden.on = true; hidden.scene = { background: scene.background, fog: scene.fog, environment: scene.environment }; group.visible = false; lights.forEach(function (l) { l.visible = false; }); return true; } if (!hidden.on) return false; hidden.on = false; group.visible = true; lights.forEach(function (l) { l.visible = true; }); if (hidden.scene) { scene.background = hidden.scene.background; scene.fog = hidden.scene.fog; scene.environment = hidden.scene.environment; } hidden.scene = null; return false; },
    hidden: function () { return !!hidden.on; },   /* is a point (with radius r) inside any solid, or below the ground it stands over? — used by the Spec B "zero frames inside geometry" probe */
    groundAt: function (x, z, fromY) { var best = 0; var list = shapesNear(x, z, 0); for (var k = 0; k < list.length; k++) { var s = list[k]; if (s.district && !s.walkable) continue; /* a building's solid pieces are not ground; its deck slabs are */ var top = s.h; if (fromY !== undefined && top > fromY + 0.05) continue; if (s.type === 'BOX') { if (x >= s.x1 && x <= s.x2 && z >= s.z1 && z <= s.z2 && top > best) best = top; } else if (s.type === 'CYLINDER') { if (Math.hypot(x - s.x, z - s.z) <= s.r && top > best) best = top; } else if (s.type === 'RAMP' && s.x1 !== undefined) { if (x >= s.x1 && x <= s.x2 && z >= s.z1 && z <= s.z2) { var u = s.axis === 'x' ? (x - s.x1) / Math.max(1e-6, s.x2 - s.x1) : (z - s.z1) / Math.max(1e-6, s.z2 - s.z1); var ry = (s.h0 || 0) + ((s.h1 || 0) - (s.h0 || 0)) * u; if (ry > best && ry <= (fromY === undefined ? 1e9 : fromY + 0.05)) best = ry; } } } return best; },   /* real support surface under (x,z): the highest collider top at or below fromY, else the arena floor (0) — used by the beam endpoints, never by the host */
    /* development read-out for the lighting evidence probe (presentation only; reads nothing the host owns) */
    district: function () { return districtInfo; },
    debug: function () { var sky = group.getObjectByName('MAHWORLD_SKY'); var dome = sky && sky.children[0]; var cA = dome && dome.geometry.attributes.color; var top = null, bot = null;
      if (cA) { var hi = 0, lo = 0, pA = dome.geometry.attributes.position; for (var i = 0; i < pA.count; i++) { if (pA.getY(i) > pA.getY(hi)) hi = i; if (pA.getY(i) < pA.getY(lo)) lo = i; } top = [+cA.getX(hi).toFixed(3), +cA.getY(hi).toFixed(3), +cA.getZ(hi).toFixed(3)]; bot = [+cA.getX(lo).toFixed(3), +cA.getY(lo).toFixed(3), +cA.getZ(lo).toFixed(3)]; }
      return { built: built, background: scene.background && scene.background.getHexString ? '#' + scene.background.getHexString() : String(scene.background), fog: scene.fog ? { color: '#' + scene.fog.color.getHexString(), near: scene.fog.near, far: scene.fog.far } : null,
        lights: lights.map(function (l) { return { name: l.name || null, type: l.type, intensity: l.intensity, color: '#' + l.color.getHexString(), visible: l.visible }; }), celestial_key: { kind: CELESTIAL_KEY.kind, direction: CELESTIAL_KEY.direction.slice(), base_intensity: CELESTIAL_KEY.base_intensity, intensity: sun ? sun.intensity : null, transmission: CELESTIAL_KEY.transmission, key_transmission: CELESTIAL_KEY.key_transmission, coverage: CELESTIAL_KEY.coverage, tau: CELESTIAL_KEY.tau },
        sky_children: sky ? sky.children.length : 0, dome: dome ? { visible: dome.visible, renderOrder: dome.renderOrder, side: dome.material.side, vcol_top: top, vcol_bottom: bot } : null,
        scene_lights: (function () { var n = []; scene.traverse(function (o) { if (o.isLight) n.push(o.type + ':' + (+o.intensity.toFixed(2)) + (o.visible ? '' : ':HIDDEN')); }); return n; })(),
        tone: null }; },
    tick: function (dt, t, play) { if (worldB) { try { worldB.tick(dt, t, play || null); } catch (e) { } } if (botany) botany.tick(dt, t); if (!animated.emblem) animated.emblem = group.getObjectByName('MAH_EMBLEM') || false; var em = animated.emblem; if (em) { em.rotation.y += dt * 0.35; em.position.y = 9.5 + 0.25 * Math.sin(t * 0.7); } if (animated.haloRings === undefined) animated.haloRings = group.getObjectByName('HALO_CELESTIAL_RINGS') || false; if (animated.haloRings) animated.haloRings.children.forEach(function (rn) { rn.rotation.z += dt * (rn.userData.spin || 0); });   /* WORLD PIVOT PASS 4: the HALO celestial rings turn slowly */ if (!animated.elevator) animated.elevator = group.getObjectByName('TREE_ELEVATOR') || false; var tr = animated.elevator;
      if (tr && tr.userData.cabin) { var cabin = tr.userData.cabin, q = play && play.transit && /^ELEVATOR_/.test(play.transit.id) ? play.transit : null; if (q && q.carrier_pose) { cabin.position.set(q.carrier_pose.x, q.carrier_pose.y, q.carrier_pose.z); tr.userData.cabinDock = q.carrier_pose.y; tr.userData.carrierPhase = q.phase; tr.userData.relativeDriftM = q.relative_drift_m; } else { cabin.position.y = tr.userData.baseY + (tr.userData.cabinDock || 0); tr.userData.carrierPhase = 'DOCKED'; tr.userData.relativeDriftM = 0; } var doorOpen = q ? (q.door_open01 || 0) : 1; if (tr.userData.cabinDoors) { tr.userData.cabinDoors[0].position.x = -0.4 - doorOpen * 0.52; tr.userData.cabinDoors[1].position.x = 0.4 + doorOpen * 0.52; } if (tr.userData.cabinGlass) tr.userData.cabinGlass.emissiveIntensity = (NIGHT ? 0.92 : 0.5) + (q ? 0.28 : 0.08) * Math.sin(t * 2.2);
        var sg = tr.userData.sport, sp = play && play.sport; if (sg && sg.ball) { sg.ball.visible = !!(sp && sp.active && sp.ball); sg.shadow.visible = sg.ball.visible; if (sg.ball.visible) { sg.ball.position.set(sp.ball.x, sp.ball.y, sp.ball.z); sg.ball.rotation.x += dt * 4.2; sg.ball.rotation.z += dt * 2.7; sg.shadow.position.set(sp.ball.x, (sp.court && sp.court.center ? sp.court.center.altitude_m : 240) + 0.15, sp.ball.z); var h = Math.max(0, sp.ball.y - 240), ss = Math.max(0.45, Math.min(1, 1 - h / 12)); sg.shadow.scale.setScalar(ss); sg.shadow.material.opacity = 0.34 * ss; } }
      }
    },   /* The carrier and passenger consume the same host pose; the client no longer reconstructs a second elevator timeline. */
    treeAscentInfo: function () { var tr = group.getObjectByName('TREE_ELEVATOR'); if (!tr) return null; return { envelope: tr.userData.treeAscentEnvelope || null, floor_owners: tr.userData.floorOwners || null, cabin_y: tr.userData.cabin ? +tr.userData.cabin.position.y.toFixed(3) : null, cabin_x: tr.userData.cabin ? +tr.userData.cabin.position.x.toFixed(3) : null, cabin_z: tr.userData.cabin ? +tr.userData.cabin.position.z.toFixed(3) : null, cabin_dock_m: +(tr.userData.cabinDock || 0).toFixed(3), carrier_phase: tr.userData.carrierPhase || 'DOCKED', relative_drift_m: tr.userData.relativeDriftM || 0, sport_visible: !!(tr.userData.sport && tr.userData.sport.ball && tr.userData.sport.ball.visible), legacy_large_ridge: group.getObjectByName('MAHWORLD_LEGACY_HORIZON_RIDGE') ? 'PRESENT_SMALL_FIELD_ONLY' : 'SUPPRESSED_FULL_WORLD' }; },
    clear: function () { if (botany) { botany.dispose(); botany = null; botanyInfo = { status: 'OFF' }; } if (hidden.on) { group.visible = true; hidden.on = false; hidden.scene = null; } if (hidden.saved) { shapes = hidden.saved.shapes; districtGroups = hidden.saved.groups; hidden.saved = null; } clear(); built = null; shapes = []; districtGroups = []; lods = []; animated.emblem = null; animated.elevator = null; animated.haloRings = undefined; scene.fog = null; },
    dispose: function () { clear(); scene.remove(group); }
  };
  /* read-only development handle for the lighting evidence probe; exposes nothing but the debug read-out */
  try { if (typeof window !== 'undefined') { (window.MAHWORLD_DEV = window.MAHWORLD_DEV || {}).fieldScene = { debug: api.debug }; } } catch (e) { /* no window: nothing to expose */ }
  return api;
}
