/* MAHWORLD PLAYABLE SAMPLE :: COMPACT GAME HUD (development view layer; never simulates)
   ONE control tree over the authoritative snapshot, built to leave the character and the environment most of the screen.
   Permanent: compact vitals (top-left) · state / lock pill (top-centre) · THREE attack modes (top-right dock with ONE drawer; an edge
   handle slides the whole dock toward the right edge to collapse it and back inward to reopen) · FLY / LAND + guards + MORE (right column).
   On touch the stick and the HOLD ATTACK / HOLD DASH modifiers live in touchControls.js; on desktop a small bottom bar carries
   ATTACK / DASH / LOCK for mouse users. MORE is a bottom sheet that slides up / down (drag handle or tap) with three tabs:
   ACTIONS (practice, reset, separate / fuse, interact, help, guide, dev, unlock) · LOADOUT (4 / 2 / 2 equip slots per attack mode,
   real host data, confirmed results, honest empty / locked states) · EMOTES (wave, nod, ready — cosmetic). Class testing, fixtures and the
   diagnostics inspector sit in the DEV panel (F3). EMOTES stay out of the permanent combat HUD: ≡ EMOTES is the hub (grouped
   collection SOCIAL / DANCE / EXERCISE / FLEX / EXPRESSION / PARTNER with requirement badges, ★ favourite assignment, TO: social target
   chip, STOP, invitations); a LONG PRESS on MORE opens the six-favourite RADIAL directly (centre = CANCEL / STOP, BROWSE entry; hold-drag-
   release selects, releasing on the centre or off a slot cancels); desktop key I (bound in play.js) toggles it; V is the attack. Exactly one secondary
   panel (drawer / sheet / details / radial) may be open; a tap outside it is
   CONSUMED by #g-dismiss and only closes it. Every button activates from the pointer-down-remembered element on pointer-up, so a label
   re-rendered by the snapshot tick can never lose a tap (the MORE root cause). Selection never fires or spends; touch, mouse, keyboard and
   scripts all go through selectMove(). */
export function createGameHud(deps) {
  var $ = deps.$, send = deps.send, log = deps.log, act = deps.act || {}; var DOCK = !!(document.body && document.body.classList.contains('hud-dock'));   /* phase B (owner interjection 2026-09-18 §3–§4): the island layout is the default; ?hud=dock restores the PASS 3 dock + LOCKED panel */ var st = { delegated: [], holds: {}, built: false, key: null, dev: false, guide: false, guideStep: 0, lastP: null, pressTimer: null, pressSlot: null, detailSlot: null, detailSkill: null, suppressUntil: 0, toast: null, toastT: 0, drawerOpen: false, drawerKey: null, moreOpen: false, moreTab: 'actions', moreCloseTimer: null, dockCollapsed: false, minimal: false, loadSlot: null, loadKey: null, emoteKey: null, cueUntil: 0, lastResult: null, ev: [], radial: { open: false, drag: false, id: null, hover: null, moved: false }, moreLong: null, favorites: null, favPick: null, socialTarget: null, socialIdx: -1, pendingInvite: null, defaults: null, emoteRenderKey: null };
  try { st.minimal = localStorage.getItem('mahworld-hud-mode') === 'MINIMAL'; } catch (e) { st.minimal = false; }
  if (document.body) document.body.classList.toggle('hud-minimal', st.minimal);   /* M4/M5: the owner's HUD preference changes presentation only; gameplay state, controls and NIGHT restoration are untouched */
  /* presentation defaults: ONE canonical file (lab/presentation_defaults.json); the embedded values below are only the boot fallback until it loads and mirror that file */
  var DEF = { favorites_default: ['WAVE', 'NOD', 'APPLAUD', 'THUMBS_UP', 'MAH_GROOVE', 'DOUBLE_BICEPS'], long_press_ms: 450, radial_radius_px: 96, cancel_radius_px: 30, invite_range_m: 3.0 };
  try { fetch('./presentation_defaults.json').then(function (r) { return r.json(); }).then(function (j) { if (j && j.emotes) { DEF = Object.assign({}, DEF, j.emotes); st.defaults = j; if (!st.favLoaded) loadFavorites(); } }).catch(function () { /* fallback stays */ }); } catch (e) { /* fallback stays */ }
  /* emote catalogue: the host publishes play.emote_catalog; until it does, this mirror of the master-prompt list (same ids / groups / icons) keeps the hub usable */
  var CATALOG_FALLBACK = [
    { id: 'WAVE', name: 'Wave', group: 'SOCIAL', form: 'ANY', partner: false, directed: true, icon: '👋' }, { id: 'NOD', name: 'Respect Nod', group: 'SOCIAL', form: 'ANY', partner: false, directed: true, icon: '🙇' }, { id: 'APPLAUD', name: 'Applaud', group: 'SOCIAL', form: 'ANY', partner: false, directed: true, icon: '👏' }, { id: 'THUMBS_UP', name: 'Thumbs Up', group: 'SOCIAL', form: 'ANY', partner: false, directed: true, icon: '👍' }, { id: 'BECKON', name: 'Playful Beckon', group: 'SOCIAL', form: 'ANY', partner: false, directed: true, icon: '🫴' }, { id: 'READY', name: 'Ready', group: 'SOCIAL', form: 'ANY', partner: false, directed: false, icon: '🛡' },
    { id: 'MAH_GROOVE', name: 'MAH Groove', group: 'DANCE', form: 'ANY', partner: false, directed: false, loop: true, icon: '🕺' }, { id: 'SIDE_GLIDE', name: 'Side Glide', group: 'DANCE', form: 'ANY', partner: false, directed: false, loop: true, icon: '🎵' },
    { id: 'UPRIGHT_ROW_DEMO', name: 'Upright Row', group: 'EXERCISE', form: 'ANY', partner: false, directed: false, loop: true, icon: '🏋' }, { id: 'HORIZONTAL_PUSH_DEMO', name: 'Horizontal Push', group: 'EXERCISE', form: 'ANY', partner: false, directed: false, loop: true, icon: '🤜' }, { id: 'HIP_HINGE_DEMO', name: 'Hip Hinge', group: 'EXERCISE', form: 'ANY', partner: false, directed: false, loop: true, icon: '🙆' }, { id: 'SQUAT_DEMO', name: 'Squat', group: 'EXERCISE', form: 'SPLIT', partner: false, directed: false, loop: true, icon: '🦵' },
    { id: 'DOUBLE_BICEPS', name: 'Double Biceps', group: 'FLEX', form: 'ANY', partner: false, directed: false, icon: '💪' }, { id: 'FRONT_LAT_SPREAD', name: 'Front Lat Spread', group: 'FLEX', form: 'ANY', partner: false, directed: false, icon: '🔱' }, { id: 'SIDE_CHEST', name: 'Side Chest', group: 'FLEX', form: 'ANY', partner: false, directed: false, icon: '🏆' }, { id: 'BACK_LAT_SPREAD', name: 'Back Lat Spread', group: 'FLEX', form: 'ANY', partner: false, directed: false, icon: '🦅' },
    { id: 'SHRUG', name: 'Shrug', group: 'EXPRESSION', form: 'ANY', partner: false, directed: false, icon: '🤷' }, { id: 'QUIET_LAUGH', name: 'Quiet Laugh', group: 'EXPRESSION', form: 'ANY', partner: false, directed: false, icon: '😄' },
    { id: 'FIST_BUMP', name: 'Fist Bump', group: 'PARTNER', form: 'ANY', partner: true, directed: true, icon: '👊' }, { id: 'HIGH_FIVE', name: 'High Five', group: 'PARTNER', form: 'ANY', partner: true, directed: true, icon: '🙏' }, { id: 'PAIRED_GROOVE', name: 'Paired Groove', group: 'PARTNER', form: 'ANY', partner: true, directed: true, loop: true, icon: '👯' }
  ];
  var GROUPS = ['SOCIAL', 'DANCE', 'EXERCISE', 'FLEX', 'EXPRESSION', 'PARTNER'];
  function catalog() { var p = st.lastP; var c = p && Array.isArray(p.emote_catalog) && p.emote_catalog.length ? p.emote_catalog : CATALOG_FALLBACK; return c; }
  function emoteById(id) { return catalog().filter(function (e) { return e.id === id; })[0] || null; }
  function loadFavorites() { st.favLoaded = true; var f = null; try { f = JSON.parse(localStorage.getItem('mahworld-emote-favorites') || 'null'); } catch (e) { f = null; } st.favorites = Array.isArray(f) && f.length === 6 ? f : DEF.favorites_default.slice(0, 6); }
  function saveFavorites() { try { localStorage.setItem('mahworld-emote-favorites', JSON.stringify(st.favorites)); } catch (e) { /* optional */ } }
  function favorites() { if (!st.favorites) loadFavorites(); return st.favorites; }
  function socialCandidates() { var p = st.lastP; if (!p || !p.position) return []; var out = []; var me = p.position; var rng = DEF.invite_range_m || 3; (p.npcs || []).forEach(function (n) { if (!n || !n.position) return; var d = Math.hypot(n.position.x - me.x, n.position.z - me.z); if (d <= rng * 2) out.push({ id: n.id, name: String(n.name || n.id).replace(/_/g, ' '), kind: 'npc', d: d, near: d <= rng }); }); (p.presence || []).forEach(function (o) { if (!o || !o.position) return; var d2 = Math.hypot(o.position.x - me.x, o.position.z - me.z); if (d2 <= rng * 2) out.push({ id: o.account_id, name: String(o.account_id).replace(/_/g, ' '), kind: 'player', d: d2, near: d2 <= rng }); }); out.sort(function (a, b) { return a.d - b.d; }); return out; }
  function socialTarget() { if (!st.socialTarget) return null; var c = socialCandidates().filter(function (x) { return x.id === st.socialTarget; })[0]; if (!c) { st.socialTarget = null; return null; } return c; }
  function emoteRefusalText(id, res, tgt) { var reason = String(res && res.reason || 'REFUSED'); var det = res && res.detail && typeof res.detail === 'object' ? res.detail : {}; var e = emoteById(id); var nm = e ? e.name.toUpperCase() : id; if (reason === 'FORM_REQUIRED') return (det.form === 'FUSED' ? 'FUSE FIRST' : 'SEPARATE FIRST') + ' (≡ SETTINGS → ' + (det.form === 'FUSED' ? 'FUSE' : 'SEPARATE') + ')'; if (reason === 'TARGET_OUT_OF_RANGE' || reason === 'OUT_OF_RANGE') return 'MOVE CLOSER TO ' + (tgt ? tgt.name.toUpperCase() : 'YOUR PARTNER'); if (reason === 'NOT_FACING') return 'FACE ' + (tgt ? tgt.name.toUpperCase() : 'YOUR PARTNER') + ' FIRST'; if (reason === 'TARGET_BUSY' || reason === 'PARTNER_BUSY') return (tgt ? tgt.name.toUpperCase() : 'THEY') + ' IS BUSY RIGHT NOW'; if (reason === 'TARGET_DOWN') return (tgt ? tgt.name.toUpperCase() : 'THEY') + ' IS DOWN'; if (reason === 'INVITATION_EXPIRED' || reason === 'INVITATION_WITHDRAWN' || reason === 'NO_INVITATION') return 'THAT INVITATION IS GONE'; if (reason === 'PARTNER_EMOTE') return nm + ' NEEDS A PARTNER — PICK SOMEONE (TO: chip)'; if (reason === 'NOT_PARTNER_EMOTE' || reason === 'NOT_DIRECTED') return nm + ' — NOT A PARTNER EMOTE'; if (reason === 'BAD_TARGET' || reason === 'TARGET_REQUIRED' || reason === 'NO_TARGET') return 'PICK SOMEONE NEARBY (TO: chip)'; if (reason === 'COOLDOWN' || reason === 'EMOTE_COOLDOWN') return nm + ' — COOLING DOWN'; if (/COMBAT|CAST|BUSY|IN_ROUND|ATTACK/.test(reason)) return 'NOT DURING AN ATTACK'; if (/TRANSFORM/.test(reason)) return 'WAIT FOR THE FORM CHANGE'; if (reason === 'BAD_EMOTE' || reason === 'UNKNOWN_EMOTE' || reason === 'NOT_REGISTERED') return nm + ' — NOT ON THIS HOST YET'; if (reason === 'BUSY_PAIRED' || reason === 'ALREADY_PAIRED') return 'FINISH THE CURRENT EMOTE FIRST'; return nm + ' — ' + reason.replace(/_/g, ' '); }
  function evlog(kind, e, extra) { st.ev.push({ t: +performance.now().toFixed(0), k: kind, id: e && e.pointerId, type: e && e.pointerType, tgt: e && e.target ? (e.target.id || (e.target.closest && e.target.closest('[data-do]') ? 'do:' + e.target.closest('[data-do]').getAttribute('data-do') : e.target.tagName)) : null, x: extra }); if (st.ev.length > 60) st.ev.splice(0, st.ev.length - 60); }
  var FALLBACK_MODES = [{ id: 'PHYSICAL', label: 'PHYSICAL', category: 'PHYSICAL' }, { id: 'PHYSICAL_MAHGIC', label: 'PHYS MAHGIC', category: 'PHYSICAL_MAGIC' }, { id: 'SPECIAL_MAHGIC', label: 'SPECIAL MAHGIC', category: 'SPECIAL_MAGIC' }];
  var CLASS_TINT = { ATHLETE: '#39c5ff', TITAN: '#ff9a3c', BAGE: '#ff8fd6', VISIONARY: '#8cff9c', LEAN: '#ff5e5e' };
  var EMOTES = [{ id: 'WAVE', label: 'WAVE', hint: 'X · shoulder → elbow → wrist' }, { id: 'NOD', label: 'NOD', hint: 'a calm yes' }, { id: 'READY', label: 'READY', hint: 'confident stance' }];
  function esc(s) { return String(s === undefined || s === null ? '' : s).replace(/</g, '&lt;'); }
  function pct(c, m) { return m > 0 ? Math.max(0, Math.min(1, c / m)) : 0; }
  function guideSeen() { try { return localStorage.getItem('mahworld-guide-seen') === '4'; } catch (e) { return true; } }
  function markGuide() { try { localStorage.setItem('mahworld-guide-seen', '4'); } catch (e) { /* optional */ } }
  function modes(r) { return r && r.me && r.me.attack_modes && r.me.attack_modes.length === 3 ? r.me.attack_modes : FALLBACK_MODES; }
  function modeOfCat(r, cat) { return modes(r).filter(function (x) { return x.category === cat; })[0] || null; }
  function setHtml(el, html) { if (!el) return; if (el.__h !== html) { el.__h = html; el.innerHTML = html; } }   /* idempotent label updates: no DOM churn under a pressing finger */
  function twoLine(label) { var parts = label.split(' '); return parts.length > 1 ? '<b>' + esc(parts[0]) + '</b><b>' + esc(parts.slice(1).join(' ')) + '</b>' : '<b>' + esc(label) + '</b><b>&nbsp;</b>'; }
  function gestureText(s, touch) { var g = s && s.gesture ? String(s.gesture).toUpperCase() : ''; var arrow = { UP: '↑ up', DOWN: '↓ down', LEFT: '← left', RIGHT: '→ right' }[g]; if (arrow) return touch ? 'tap its slot, or swipe ' + arrow + ' from the slot' : 'V, or its slot key (swipe ' + arrow + ' from the slot on touch)'; return touch ? 'tap its slot' : 'V, or its slot key'; }   /* owner hotfix 2026-09-19 §5: the slots 1–4 ARE the attack controls — no generic ATTACK button exists to hold */
  function loadoutOf(r) { return r && r.me && r.me.loadout ? r.me.loadout : null; }
  function equippedCount(lo, cat) { var c = lo && lo[cat]; if (!c || !c.equipped) return null; return { n: c.equipped.filter(function (x) { return !!x; }).length, cap: c.capacity }; }
  /* the guide: one step at a time, real BACK / NEXT / START controls, a gesture glyph per step (touch and mouse variants) */
  var GUIDE = [
    { g: '◉ ⇔', t: 'MOVE · LOOK', touch: 'Left thumb: move (you walk where you push). Right thumb: turn the camera. Pinch: zoom.', mouse: 'W A S D moves (Shift runs). Mouse drag turns the camera. Wheel zooms.' },
    { g: '⇡ ✊', t: 'ATTACK', touch: 'The numbered slots 1–4 are your attacks: tap a slot to perform that move where you face, or swipe from it in the arrow direction shown on the slot. Each slot shows its move, category and cooldown. Tap an enemy to lock on; the small label is the category (tap = next); ⚔ lists every move.', mouse: 'V performs the armed movement pattern where you face. 1-4 recall a pattern of the current category, Z cycles categories, ⚔ / Q → COMBAT lists every move. Click an enemy to lock on (Esc clears).' },
    { g: '⇢ ✦', t: 'DASH · GUARD · FLY', touch: 'Hold DASH + swipe to dash. GUARD: tap = guard, hold = magic guard. FLY takes off / lands. ✦ appears when something can be used.', mouse: 'B dashes. G guards (Shift+G = magic guard). F flies / lands. Enter interacts. H separates / fuses. Tab opens emotes.' }
  ];
  function build() {
    if (st.built) return; st.built = true; var root = $('ghud');
    root.innerHTML =
      '<div id="g-dismiss"></div>' +
      '<div id="g-top">' +
        '<div id="g-vitals">' +
          '<div class="gl"><span class="dia">HEALTH<b id="g-lv"></b></span><span id="g-hp">—</span></div><div class="gb hp"><i></i></div>' +
          '<button id="g-mahguide" data-do="mahguide" title="MAH GUIDE companion: tap = show / hide (Mr. or Mrs. Mah — pick in ≡ SETTINGS)">✧ GUIDE</button>' +   /* JOB A (owner 2026-09-19): the tiny GUIDE toggle under Health drives the JOB B guide layer */
          '<div id="g-gear" style="display:none"><div class="gb charge" title="GUIDE CHARGE — fills only from damage dealt through manifested dumbbell / barbell extensions; full = Mrs. Mah dispenses MAHGIC refills"><i></i></div>' +
            '<div class="grow"><button data-do="gear" data-kind="DUMBBELL" data-count="1" title="manifest ONE dumbbell (tap it to hold: ×1.8 physical)">DB<small></small></button><button data-do="gear" data-kind="DUMBBELL" data-count="2" title="manifest TWO dumbbells (floating = X-WAVE / CLAMP specials)">DB×2<small></small></button><button data-do="gear" data-kind="DUMBBELL" data-count="3" title="a THIRD dumbbell needs higher magic affinity">DB×3<small></small></button><button data-do="gear" data-kind="BARBELL" data-count="1" title="manifest the barbell on the ground (PLATE SHOT)">BAR<small></small></button><button data-do="gear" data-kind="BAND" data-count="1" title="manifest the resistance band (no special mapped yet — owner decision)">BAND<small></small></button><button data-do="gear-dismiss" title="reclaim every manifested item">↓</button></div>' +
            '<button id="g-refill" data-do="refill" title="stored MAHGIC refills — tap to restore Combat MAHGIC">◆ <b>0</b> USE</button></div>' +   /* owner B8 §10–§13: the fairy equipment control (manifest counts / kinds are DATA: costs + affinity from dev_tuning), the guide charge and the refill inventory */
        '</div>' +
      '</div>' +
      '<div id="g-vitals-r">' +   /* owner interjection 2026-09-18 §3.1: HEALTH upper-left; COMBAT + FLIGHT MAHGIC upper-right in the space the attack selector freed — bare bars, no card */
        '<div class="gl"><span class="dia">COMBAT MAHGIC</span><span id="g-cm">—</span></div><div class="gb cm"><i></i></div>' +
        '<div class="gl"><span class="dia">FLIGHT MAHGIC</span><span id="g-fm">—</span></div><div class="gb fm"><i></i></div>' +
      '</div>' +
      '<div id="g-center"><div id="g-state">FREE ROAM · HARMLESS</div>' + (DOCK ? '<div id="g-target" style="display:none"><div class="gl"><span id="g-tname">TARGET</span><span id="g-thp">—</span></div><div class="gb thp"><i></i></div><div id="g-tnote"></div></div>' : '') + '<div id="g-sport" style="display:none"></div><div id="g-warn" style="display:none"></div><div id="g-toast" style="display:none"></div><div id="g-dialog" style="display:none"></div></div>' +   /* §3: no LOCKED panel — the lock lives on the target's world tag (adapter.tag) and in ⚔ COMBAT */
      '<div id="g-dock" class="gp" style="display:none"><div id="g-dockhandle" data-do="dock-toggle" title="slide the attack dock away / back"><b>⟩</b></div><div id="g-dockbody"><div id="g-cats"></div><div id="g-summary"><span id="g-sel">—</span><button class="gbtn sm" data-do="info-sel" title="how to perform">?</button></div><div id="g-cast"></div><div id="g-drawer" style="display:none"><div id="g-drawhead"></div><div id="g-chips"></div></div></div></div>' +
      '<div id="g-acts"><div id="g-utils"><button class="gbtn round" data-do="map" id="g-mapbt" title="Map (one tap)">MAP</button><button class="gbtn round" data-do="speed" id="g-speed" title="faster travel (toggle) — sustained, not a dash">+<br><small>SPEED</small></button><button class="gbtn round" data-do="camreset" id="g-camreset" title="camera reset: back behind him (Backspace · middle click)">⟲<br><small>CAM</small></button></div><div id="g-erty-t" class="gerty touchonly"></div><div class="row"><button class="gbtn round act" data-do="sword" id="g-swordbt" title="COMBAT · skills · stats · loadout">⚔</button><button class="gbtn round act" data-do="menu" id="g-menubt" title="MAHWORLD menu · long-press: favourite emotes">≡<br><small class="key">Q</small></button></div>' +
        '<div id="g-cluster"><div class="gcell" id="g-cell-dash"></div>' +
        '<button class="gbtn round fly" data-do="fly" id="g-fly">FLY</button>' +
        '<button class="gbtn round hold" data-do="guard" id="g-guard" title="tap: guard · hold: magic guard">GUARD</button>' +
        '<button class="gbtn round act" data-do="mahgic" id="g-mahgic" title="cast the ready MAHGIC">MAHGIC</button></div>' +
        '<div class="row"><button class="gbtn act" data-do="interact" id="g-ctx" style="display:none">✦</button></div>' +
      '</div>' +
      '<div id="g-catlbl" style="display:none"><button class="gcat-arrow" data-do="cat-prev" title="previous category">◂</button><button id="g-cattext" data-do="cat-cycle" title="armed category · tap or swipe: next / previous">—</button><button class="gcat-arrow" data-do="cat-next" title="next category">▸</button></div>' +
      '<div id="g-desk" class="gp"><button class="gbtn" data-do="attack">ATTACK<small class="key">V</small></button><span id="g-erty" class="gerty"></span><button class="gbtn" data-do="mahgic">MAHGIC<small class="key">M</small></button><button class="gbtn" data-do="dash">DASH<small class="key">B</small></button><button class="gbtn" data-do="lock" id="g-lockbtn">LOCK<small>click enemy</small></button></div>' +
      '<div id="g-more" class="gp sheet" style="display:none">' +
        '<div id="g-morehandle" data-do="more-close" title="tap or drag down to close"><i></i><span>MENU · tap or drag down to close</span></div>' +
        '<div id="g-moretabs"><button class="gtab" data-do="tab-actions" id="g-tab-actions">ACTIONS</button><button class="gtab" data-do="tab-loadout" id="g-tab-loadout">LOADOUT</button><button class="gtab" data-do="tab-emotes" id="g-tab-emotes">EMOTES</button></div>' +
        '<div id="g-moreacts" class="gtabbody">' +
          '<button class="gbtn" data-do="practice" id="g-practice">PRACTICE BATTLE<small>damage on dummy</small></button><button class="gbtn" data-do="reset">RESET PRACTICE<small class="key">O</small></button>' +
          '<button class="gbtn" data-do="transform" id="g-form">SEPARATE<small class="key">H</small></button><button class="gbtn" data-do="interact" id="g-interact">INTERACT<small class="key">Enter</small></button>' +
          '<button class="gbtn" data-do="tab-emotes">EMOTES<small>hold ≡ for favourites<span class="key"> · Tab</span></small></button><button class="gbtn" data-do="help">HELP<small>controls</small></button>' +
          '<button class="gbtn" data-do="guide">TUTORIAL<small>6 steps</small></button><button class="gbtn" data-do="mahguide-pick" id="g-mahguide-pick">MAH GUIDE<small id="g-mahguide-who">Mrs. Mah</small></button><button class="gbtn" data-do="time" id="g-time" title="B8 §20: time of day — two stable states (DAY / NIGHT), switched live">TIME<small id="g-time-state">DAY</small></button><button class="gbtn" data-do="hudmode" id="g-hudmode" title="show only essential vitals and controls, or restore the full HUD">HUD: FULL<small>minimal · F2</small></button><button class="gbtn" data-do="dev">DEV PANEL<small class="key">F3</small></button><button class="gbtn" data-do="unlock" id="g-unlockbtn" style="display:none">UNLOCK<small>clear target</small></button>' +
          '<div class="about" id="g-about"></div>' +
        '</div>' +
        '<div id="g-loadout" class="gtabbody" style="display:none"></div>' +
        '<div id="g-emotes" class="gtabbody" style="display:none"></div>' +
      '</div>' +
      '<div id="g-detail" class="gp" style="display:none"></div>' +
      '<div id="g-radial" style="display:none"><div id="g-radial-ring"></div><button id="g-radial-cancel" data-do="emote-cancel" title="cancel / stop">CANCEL</button><div id="g-radial-to"></div></div>' +
      '<div id="g-invite" style="display:none"></div>' +
      '<div id="g-cue"><b>⇠ ⇡ ⇢</b>tap a slot 1–4 · swipe from it in its arrow direction</div>' +
      '<div id="g-guide" style="display:none"><div class="gp"><b class="dia">HOW TO PLAY</b><div id="g-guidebody"></div></div></div><div id="g-confirm"><div class="gp"><b class="dia" id="g-confirm-title"></b><div id="g-confirm-body"></div><div class="crow"><button class="gbtn sm" data-do="confirm-no">CANCEL</button><button class="gbtn sm" data-do="confirm-yes" id="g-confirm-yes">ENTER</button></div></div></div><div id="g-catalog"><div class="gp"><b class="dia" id="g-catalog-title"></b><div id="g-catalog-body"></div><div class="crow"><button class="gbtn sm" data-do="catalog-close">CLOSE</button></div></div></div>' +
      '<div id="g-dev" class="gp" style="display:none"><b class="dia">DEV (F3)</b><div id="g-devbody"></div><div id="g-diag"></div></div>';
    var chipOf = function (e) { var t = e.target && e.target.closest ? e.target.closest('.gchip') : null; return t && !t.classList.contains('empty') ? parseInt(t.getAttribute('data-slot'), 10) : null; };
    var on = function (ev, fn, opts) { root.addEventListener(ev, fn, opts); st.delegated.push([ev, fn, opts]); };   /* PASS 3 review: the same delegation is bound to the ≡ menu body when a utility tab is mounted there (the menu lives outside #ghud and stops propagation at its root) */
    on('pointerdown', function (e) { if (e.target && e.target.closest && e.target.closest('#g-dialog')) { e.preventDefault(); api.dialogNext(); return; } if (e.target && e.target.closest && e.target.closest('[data-do="info"]')) return; var slot = chipOf(e); if (slot === null || api.suppressed()) return; e.preventDefault(); st.pressSlot = slot; st.pressX = e.clientX; st.pressY = e.clientY; st.pressTimer = setTimeout(function () { st.pressTimer = null; api.openDetail(slot); }, 350); });
    on('pointermove', function (e) { if (st.catSwipe && st.catSwipe.id === e.pointerId && !st.catSwipe.done) { var cdx = e.clientX - st.catSwipe.x; if (Math.abs(cdx) > 28 && Math.abs(cdx) > Math.abs(e.clientY - st.catSwipe.y)) { st.catSwipe.done = true; if (st.pressBtn && st.pressBtn.id === e.pointerId) st.pressBtn.consumed = true; api.doButton(cdx > 0 ? 'cat-next' : 'cat-prev'); evlog('cat-swipe', e, cdx > 0 ? 'next' : 'prev'); } }   /* JOB A: a horizontal swipe on the category strip steps the category (the strip owns its pointer: never a camera drag, never an attack) */
      if (st.moreLong && st.pressBtn && st.pressBtn.id === e.pointerId && Math.hypot(e.clientX - st.pressBtn.x, e.clientY - st.pressBtn.y) > 14) { clearTimeout(st.moreLong); st.moreLong = null; } if (st.slotPress && st.slotPress.id === e.pointerId) { var sdx = e.clientX - st.slotPress.x, sdy = e.clientY - st.slotPress.y; if (Math.hypot(sdx, sdy) >= 24) st.slotPress.dir = Math.abs(sdx) > Math.abs(sdy) ? (sdx > 0 ? 'RIGHT' : 'LEFT') : (sdy > 0 ? 'DOWN' : 'UP'); }
      if (st.radial.open && st.radial.drag && st.radial.id === e.pointerId) { if (Math.hypot(e.clientX - st.radial.x0, e.clientY - st.radial.y0) > 14) st.radial.moved = true; var under = document.elementFromPoint(e.clientX, e.clientY); var slot = under && under.closest ? under.closest('[data-do="emote-slot"],[data-do="emote-cancel"],[data-do="emote-browse"]') : null; var hv = slot ? (slot.getAttribute('data-emote') || slot.getAttribute('data-do')) : null; if (hv !== st.radial.hover) { st.radial.hover = hv; api.renderRadial(); } return; }   /* hold-and-drag: the slot under the finger is the live choice */
      if (st.pressBtn && st.pressBtn.id === e.pointerId && st.pressBtn.drag) { var dx = e.clientX - st.pressBtn.x, dy = e.clientY - st.pressBtn.y; if (st.pressBtn.drag === 'dock' && Math.abs(dx) >= 24 && Math.abs(dx) > Math.abs(dy)) { api.dockCollapse(dx > 0, 'drag'); st.pressBtn = { consumed: true, id: e.pointerId }; return; } if (st.pressBtn.drag === 'sheet' && dy >= 24 && dy > Math.abs(dx)) { api.closePanels('sheet-drag'); st.pressBtn = { consumed: true, id: e.pointerId }; return; } }   /* a handled drag CONSUMES its pointer: the release must never re-activate whatever slid under the finger */   /* handles: a real slide gesture on the handle collapses / closes; direction is the meaning */
      if (st.pressSlot === null && !st.pressTimer) return; if (Math.hypot(e.clientX - st.pressX, e.clientY - st.pressY) > 10) { if (st.pressTimer) { clearTimeout(st.pressTimer); st.pressTimer = null; } st.pressSlot = null; } });   /* a scroll inside the drawer is never a tap */
    on('pointerdown', function (e) { evlog('down', e); var b = e.target && e.target.closest ? e.target.closest('[data-do],button.gmode') : null; if (!b) return; var drag = b.id === 'g-dockhandle' ? 'dock' : (b.id === 'g-morehandle' ? 'sheet' : null); st.pressBtn = { el: b, id: e.pointerId, x: e.clientX, y: e.clientY, t: performance.now(), drag: drag }; st.lastPressT = performance.now(); try { b.setPointerCapture(e.pointerId); } catch (err) { /* optional */ }
      if (b.id === 'g-fly' && act.flyPress && !b.classList.contains('off')) { st.holds[e.pointerId] = 'fly'; act.flyPress(true); }   /* JOB A: ONE FLY control — press starts the climb after the tap window, release holds the altitude, a tap descends / stops (play.js flyPress) */
      if (b.id === 'g-catlbl' || (b.parentNode && b.parentNode.id === 'g-catlbl')) st.catSwipe = { id: e.pointerId, x: e.clientX, y: e.clientY, done: false };   /* O4: FLY and DOWN are HOLD controls — the press starts the climb / descent, the release holds the attained altitude (never a tap-toggle that keeps climbing) */
      if (b.id === 'g-menubt' && !st.radial.open) { if (st.moreLong) clearTimeout(st.moreLong); var pid = e.pointerId; st.moreLong = setTimeout(function () { st.moreLong = null; if (st.pressBtn && st.pressBtn.id === pid && st.pressBtn.el && st.pressBtn.el.id === 'g-menubt') { st.pressBtn.consumed = true; evlog('long-press', null, 'menu'); api.openEmotes({ drag: true, pointerId: pid }); } }, DEF.long_press_ms); }   /* LONG PRESS on ≡ = favourites radial (finger may stay down and drag to a slot); a quick tap opens the menu (PASS 3: MORE folded into the ≡ utility sheet) */
      var dd = b.getAttribute('data-do') || ''; if (/^direct-[0-3]$/.test(dd)) st.slotPress = { id: e.pointerId, slot: parseInt(dd.slice(7), 10), x: e.clientX, y: e.clientY, dir: null };   /* owner hotfix 2026-09-19 §5: the numbered slot IS the attack control — a tap executes it, a swipe from it is that move's own gesture; no arming step, no generic ATTACK button */
      if (b.getAttribute('data-do') === 'emote-slot' || b.getAttribute('data-do') === 'emote-cancel' || b.getAttribute('data-do') === 'emote-browse') st.radial.hover = b.getAttribute('data-emote') || b.getAttribute('data-do'); });   /* a re-rendered label can never lose the tap: activation is resolved from the remembered button on pointerup */
    var up = function (e) { evlog('up', e, st.pressBtn && st.pressBtn.el ? (st.pressBtn.el.id || st.pressBtn.el.getAttribute('data-do')) : (st.pressBtn ? 'consumed' : null)); var t = e.target; if (st.moreLong) { clearTimeout(st.moreLong); st.moreLong = null; } if (st.slotPress && st.slotPress.id === e.pointerId) { var spx = st.slotPress; st.slotPress = null; if (spx.dir) { st.pressBtn = null; evlog('slot-swipe', e, spx.slot + ':' + spx.dir); if (!api.suppressed() && act.directAttack) act.directAttack(spx.slot, 'swipe', spx.dir); return; } }   /* a swipe from a quick slot = that slot's gesture → ONE dispatch (directAttack); a plain release falls through to the ordinary tap dispatch below */
      if (st.radial.open && st.radial.drag && st.radial.id === e.pointerId) { var under = document.elementFromPoint(e.clientX, e.clientY); var slot = under && under.closest ? under.closest('[data-do="emote-slot"],[data-do="emote-cancel"],[data-do="emote-browse"]') : null; var choice = slot ? (slot.getAttribute('data-emote') || slot.getAttribute('data-do')) : null; st.pressBtn = null; st.pressSlot = null; st.radial.drag = false; st.radial.id = null; evlog('radial-release', e, choice || (st.radial.moved ? 'off-slot' : 'still')); if (choice === 'emote-cancel') { api.doButton('emote-cancel'); return; } if (choice === 'emote-browse') { api.doButton('emote-browse'); return; } if (choice) { api.performEmote(choice, 'radial-drag'); api.closeEmotes('picked'); return; } if (st.radial.moved) { api.closeEmotes('released-off-slot'); return; } api.renderRadial(); return; }   /* released without moving: the radial stays open for a tap */ if (st.holds[e.pointerId]) { var hk = st.holds[e.pointerId]; delete st.holds[e.pointerId]; if (st.pressBtn && st.pressBtn.id === e.pointerId) st.pressBtn = null; evlog('hold-release', e, hk); releaseHold(hk); return; }   /* a HOLD is keyed by its own pointer: another finger on 1–4 / DOWN / GUARD never orphans it */ if (st.pressBtn && st.pressBtn.consumed && st.pressBtn.id === e.pointerId) { st.pressBtn = null; evlog('drag-consumed', e); return; } if (st.pressBtn && st.pressBtn.id === e.pointerId) { var pb = st.pressBtn; st.pressBtn = null; if (Math.hypot(e.clientX - pb.x, e.clientY - pb.y) <= 14) { t = pb.el; } else { evlog('moved-off', e, Math.round(Math.hypot(e.clientX - pb.x, e.clientY - pb.y))); t = null; } }   /* native click semantics: a press activates on release however long it was held, unless the finger moved off (> 14 px) */ if (st.pressTimer) { clearTimeout(st.pressTimer); st.pressTimer = null; if (!api.suppressed()) { api.selectMove(null, st.pressSlot, 'pointer'); st.drawerOpen = false; api.renderDock(); syncDismiss(); } st.pressSlot = null; return; }   /* arming closes the drawer AND releases the dismiss layer: the next world tap must reach the world (was swallowed once) */ st.pressSlot = null; if (api.suppressed() || !t || !t.closest) return; var md = t.closest('button.gmode'); if (md) { e.preventDefault(); api.tapMode(md.getAttribute('data-mode'), 'pointer'); return; } var b = t.closest('[data-do]'); if (b) { e.preventDefault(); var doId = b.getAttribute('data-do'); if (doId === 'guard') doId = (st.lastPressT && performance.now() - st.lastPressT >= DEF.long_press_ms) ? 'guardm' : 'guardp';   /* ONE guard button: tap = physical guard, hold = magic guard */ evlog('do', e, doId); api.doButton(doId, b); } else evlog('nobtn', e, api.suppressed() ? 'suppressed' : 'no-target'); };
    function releaseHold(kind) { if (kind === 'fly' && act.flyPress) act.flyPress(false); }
    var cancel = function () { evlog('cancel', null); Object.keys(st.holds).forEach(function (k) { releaseHold(st.holds[k]); delete st.holds[k]; }); if (st.moreLong) { clearTimeout(st.moreLong); st.moreLong = null; } st.slotPress = null; if (st.radial.open && st.radial.drag) { st.radial.drag = false; st.radial.id = null; } if (st.pressTimer) { clearTimeout(st.pressTimer); st.pressTimer = null; } st.pressSlot = null; st.pressBtn = null; };
    on('pointerup', up); on('pointercancel', cancel); addEventListener('blur', cancel); addEventListener('orientationchange', cancel); document.addEventListener('visibilitychange', function () { if (document.hidden) cancel(); });
    on('change', function (e) { if (!e.target) return; if (e.target.id === 'classpick') send('RULES_CLASS', { class: e.target.value }); if (e.target.id === 'levelpick' && act.levelFixture) act.levelFixture(parseInt(e.target.value, 10)); if (e.target.id === 'avatarpick' && act.switchAvatar) act.switchAvatar(e.target.value); });
    /* nothing inside a HUD panel reaches the world controls; the dismiss layer consumes the closing tap */
    ['g-dock', 'g-more', 'g-detail', 'g-dev', 'g-acts', 'g-desk', 'g-vitals', 'g-vitals-r', 'g-guide', 'g-radial', 'g-invite'].forEach(function (id) { var n = $(id); if (!n) return; ['wheel', 'touchstart', 'touchmove', 'touchend', 'mousedown', 'mouseup', 'click', 'contextmenu'].forEach(function (ev) { n.addEventListener(ev, function (e) { e.stopPropagation(); }, { passive: ev !== 'contextmenu' }); }); });   /* pointer events keep bubbling to the HUD root (delegated handling); the touch layer is a sibling, never an ancestor */
    var dis = $('g-dismiss'); ['pointerdown', 'pointerup', 'touchstart', 'touchend', 'mousedown', 'mouseup', 'click'].forEach(function (ev) { dis.addEventListener(ev, function (e) { e.stopPropagation(); if (e.cancelable) e.preventDefault(); if (ev === 'pointerdown') { api.closePanels('outside-tap'); } }, { passive: false }); });
    if (!guideSeen()) api.showGuide(true);
  }
  function anyPanel() { return st.drawerOpen || st.moreOpen || st.detailSlot !== null || st.radial.open || !!st.confirm || !!st.catalog; }
  function syncDismiss() { var d = $('g-dismiss'); if (d) d.style.display = anyPanel() ? 'block' : 'none'; }
  function sheetShow(open) { var m = $('g-more'); if (!m) return; if (st.moreCloseTimer) { clearTimeout(st.moreCloseTimer); st.moreCloseTimer = null; } if (open) { m.style.display = 'flex'; m.classList.remove('open'); void m.offsetHeight; m.classList.add('open'); } else { m.classList.remove('open'); st.moreCloseTimer = setTimeout(function () { st.moreCloseTimer = null; if (!st.moreOpen) m.style.display = 'none'; }, 200); } }
  function resultToast(action, res) { if (!res) return; st.lastResult = { action: action, accepted: !!res.accepted, reason: res.reason || null, at: performance.now() }; if (res.accepted) return; api.toast(action + ' REFUSED: ' + String(res.reason || 'unknown').replace(/_/g, ' ') + (res.detail && typeof res.detail === 'string' ? ' — ' + res.detail : ''), 2200); }
  var api = {
    suppressed: function () { return performance.now() < st.suppressUntil; },
    active: function () { return !!(st.lastP && st.lastP.rules); },
    dev: function () { return st.dev; },
    toggleDev: function (on) { st.dev = on === undefined ? !st.dev : !!on; document.body.classList.toggle('devinfo', st.dev); var d = $('g-dev'); if (d) d.style.display = st.dev ? 'block' : 'none'; log('dev panel ' + (st.dev ? 'ON (F3 hides)' : 'OFF (F3 shows)')); },
    showGuide: function (on, step) { st.guide = !!on; if (on) st.guideStep = step === undefined ? 0 : step; var g = $('g-guide'); if (g) g.style.display = st.guide ? 'flex' : 'none'; if (st.guide) api.renderGuide(); if (!st.guide) { markGuide(); st.suppressUntil = performance.now() + 400; if (document.body.classList.contains('touch')) st.cueUntil = performance.now() + 7000; } },
    guideOpen: function () { return st.guide; },
    guideState: function () { return { open: st.guide, step: st.guideStep, steps: GUIDE.length }; },
    renderGuide: function () { var b = $('g-guidebody'); if (!b) return; var touch = document.body.classList.contains('touch'); var i = Math.max(0, Math.min(GUIDE.length - 1, st.guideStep)); var s = GUIDE[i]; b.innerHTML = '<div class="gstep"><span class="gglyph">' + s.g + '</span><div><b>' + (i + 1) + ' / ' + GUIDE.length + ' · ' + esc(s.t) + '</b><p>' + esc(touch ? s.touch : s.mouse) + '</p></div></div><div class="gdots">' + GUIDE.map(function (_, k) { return '<i class="' + (k === i ? 'on' : '') + '"></i>'; }).join('') + '</div><div class="grow"><button class="gbtn sm" data-do="guide-prev"' + (i === 0 ? ' disabled' : '') + '>◀ BACK</button>' + (i < GUIDE.length - 1 ? '<button class="gbtn sm" data-do="guide-next">NEXT ▶</button>' : '') + '<button class="gbtn sm gold" data-do="guide-close">' + (i < GUIDE.length - 1 ? 'SKIP — START' : 'GOT IT — START') + '</button></div>'; },
    toast: function (text, ms) { st.toast = text; st.toastT = performance.now() + (ms || 1800); },
    flashSlot: function (slot) { st.flashSlot = slot; st.flashT = performance.now() + 260; },
    /* DEMO QUEST NPC dialog: a small card under the centre state line (lines tap through; auto-closes) — no quest system, the interaction architecture */
    dialog: function (who, title, lines) { st.dialog = { who: who, title: title, lines: lines || [], i: 0, t: performance.now() }; },
    dialogOpen: function () { return !!st.dialog; }, dialogClose: function () { st.dialog = null; },
    /* P8: the contextual CONFIRM (master §16.2 "explicit contextual confirm") — a modal that owns input; resolves true / false; Enter / Escape or the two buttons */
    confirm: function (title, lines, yesLabel) { return new Promise(function (res) { if (st.confirm) st.confirm.res(false); st.confirm = { res: res }; var c = $('g-confirm'); if (!c) { st.confirm = null; return res(false); } setHtml($('g-confirm-title'), esc(title || 'ENTER?')); setHtml($('g-confirm-body'), (lines || []).map(function (l) { return '<p>' + esc(l) + '</p>'; }).join('')); setHtml($('g-confirm-yes'), esc(yesLabel || 'ENTER')); c.classList.add('on'); }); },
    confirmOpen: function () { return !!st.confirm; }, confirmAnswer: function (yes) { if (!st.confirm) return false; var r = st.confirm.res; st.confirm = null; var c = $('g-confirm'); if (c) c.classList.remove('on'); r(!!yes); st.suppressUntil = performance.now() + 300; return true; },
    /* P8: the zero-stock catalog panel (master §17): the registry's finished empty state — no items, no prices, no purchase control */
    catalog: function (shop) { var c = $('g-catalog'); if (!c) return false; st.catalog = shop || { label: 'CATALOG' }; setHtml($('g-catalog-title'), esc(shop && shop.label ? shop.label : 'CATALOG')); var es = shop && shop.empty_state ? shop.empty_state : { title: 'CATALOG', line: 'NO STOCK YET', detail: '' }; var n = shop && shop.catalog ? shop.catalog.length : 0; setHtml($('g-catalog-body'), n === 0 ? '<div class="cempty"><b>' + esc(es.title) + '</b>' + esc(es.line) + ' · 0 items<br><small>' + esc(es.detail || '') + '</small></div><p><small>status ' + esc(shop && shop.status ? shop.status : 'UNKNOWN') + ' · purchase ' + esc(shop && shop.purchase ? shop.purchase.replace(/_/g, ' ').toLowerCase() : 'disabled') + '</small></p>' : '<p>' + n + ' items</p>'); c.classList.add('on'); return true; },
    catalogOpen: function () { return !!st.catalog; }, catalogClose: function () { st.catalog = null; var c = $('g-catalog'); if (c) c.classList.remove('on'); st.suppressUntil = performance.now() + 300; },
    dialogNext: function () { if (!st.dialog) return false; st.dialog.i++; st.dialog.t = performance.now(); if (st.dialog.i >= st.dialog.lines.length) st.dialog = null; return true; },
    lastResult: function () { return st.lastResult; },
    eventLog: function (n) { return st.ev.slice(-(n || 12)); },
    panelOpen: function () { return anyPanel(); },
    hudMode: function (on) { if (on === undefined) return { mode: st.minimal ? 'MINIMAL' : 'FULL', minimal: st.minimal, persisted: true }; st.minimal = typeof on === 'string' ? String(on).toUpperCase() === 'MINIMAL' : !!on; if (document.body) document.body.classList.toggle('hud-minimal', st.minimal); try { localStorage.setItem('mahworld-hud-mode', st.minimal ? 'MINIMAL' : 'FULL'); } catch (e) { /* preference remains valid for this page */ } var hb = $('g-hudmode'); if (hb) setHtml(hb, 'HUD: ' + (st.minimal ? 'MINIMAL' : 'FULL') + '<small>' + (st.minimal ? 'show full' : 'show minimal') + ' · F2</small>'); return { mode: st.minimal ? 'MINIMAL' : 'FULL', minimal: st.minimal, persisted: true }; },
    closePanels: function (why) { var was = anyPanel(); st.drawerOpen = false; if (st.moreOpen) { st.moreOpen = false; sheetShow(false); } st.loadSlot = null; st.favPick = null; if (st.radial.open) { st.radial.open = false; st.radial.drag = false; st.radial.id = null; st.radial.hover = null; var rd = $('g-radial'); if (rd) rd.style.display = 'none'; } if (st.detailSlot !== null) { st.detailSlot = null; st.detailSkill = null; $('g-detail').style.display = 'none'; } if (was) st.suppressUntil = performance.now() + 350; api.renderDock(); syncDismiss(); return was; },
    openMore: function (tab) { if (act.menu) { act.menu((tab || st.moreTab || 'actions').toUpperCase()); return; } var open = !!(!st.moreOpen || (tab && tab !== st.moreTab)); api.closePanels('more'); st.moreOpen = open; if (tab) st.moreTab = tab; if (open) { sheetShow(true); api.renderMore(); } syncDismiss(); },
    moreTab: function (tab) { if (tab) { st.moreTab = tab; st.loadSlot = null; if (st.moreOpen) api.renderMore(); } return st.moreTab; },
    dockCollapse: function (on, why) { st.dockCollapsed = on === undefined ? !st.dockCollapsed : !!on; var d = $('g-dock'); if (d) d.classList.toggle('collapsed', st.dockCollapsed); var h = $('g-dockhandle'); if (h) setHtml(h, '<b>' + (st.dockCollapsed ? '⟨' : '⟩') + '</b>'); if (st.dockCollapsed && st.drawerOpen) { st.drawerOpen = false; api.renderDock(); syncDismiss(); } return st.dockCollapsed; },
    /* ---- ONE selection function: mode (canonical id or legacy category) + slot; selection never fires ---- */
    selectMove: function (mode, slot, source) { var r = st.lastP && st.lastP.rules; var p = {}; if (mode) { var m = modes(r).filter(function (x) { return x.id === mode || x.category === mode; })[0]; if (!m) { log('unknown attack mode ' + mode); return Promise.resolve({ accepted: false, reason: 'BAD_MODE' }); } p.mode = m.id; } if (slot !== undefined && slot !== null) p.slot = slot; if (!p.mode && p.slot === undefined) return Promise.resolve({ accepted: false, reason: 'NOTHING_TO_SELECT' }); return send('RULES_SELECT', p); },
    tapMode: function (mode, source) { var r = st.lastP && st.lastP.rules; var m = modes(r).filter(function (x) { return x.id === mode || x.category === mode; })[0]; if (!m) return; if (st.dockCollapsed) api.dockCollapse(false, 'mode-tap'); var active = r && r.me.attack_mode === m.id; var wasOpen = st.drawerOpen; if (st.moreOpen) { st.moreOpen = false; sheetShow(false); } if (st.detailSlot !== null) { st.detailSlot = null; st.detailSkill = null; $('g-detail').style.display = 'none'; } if (active) st.drawerOpen = !wasOpen; else { st.drawerOpen = true; api.selectMove(m.id, undefined, source); } api.renderDock(); syncDismiss(); },
    cycleMode: function () { var r = st.lastP && st.lastP.rules; if (!r) return; var list = modes(r); var i = list.findIndex(function (x) { return x.id === r.me.attack_mode; }); return api.selectMove(list[(i + 1) % list.length].id, undefined, 'key'); },
    layout: function () { return DOCK ? 'dock' : 'island'; },
    drawerState: function () { var r = st.lastP && st.lastP.rules; var m = $('g-more'); return { layout: DOCK ? 'dock' : 'island', open: st.drawerOpen, more: st.moreOpen, more_tab: st.moreTab, more_visible: !!(m && m.style.display !== 'none' && m.classList.contains('open')), detail: st.detailSlot !== null, dock_collapsed: st.dockCollapsed, mode: r ? r.me.attack_mode : null, category: r ? r.me.category : null, selection: r ? r.me.selection : null, selected_skill: r ? r.me.selected_skill : null, drawers: document.querySelectorAll('#g-drawer').length, modes: document.querySelectorAll('#g-cats button.gmode').length, dismiss_visible: $('g-dismiss') ? $('g-dismiss').style.display === 'block' : false, guide: st.guide, load_slot: st.loadSlot, radial: st.radial.open }; },
    selectedSkill: function () { var r = st.lastP && st.lastP.rules; if (!r) return null; var list = r.skills[r.me.category] || []; return list[r.me.selection[r.me.category] || 0] || null; },
    openDetail: function (slot) { if (st.moreOpen) { st.moreOpen = false; sheetShow(false); } st.detailSlot = slot; st.detailSkill = null; api.renderDetail(); syncDismiss(); },
    closeDetail: function () { st.detailSlot = null; st.detailSkill = null; $('g-detail').style.display = 'none'; st.suppressUntil = performance.now() + 400; syncDismiss(); },
    detailOpen: function () { return st.detailSlot !== null; },
    doButton: function (d, el) { var p = st.lastP; switch (d) {
      case 'attack': if (act.attack) act.attack('button'); break; case 'lock': if (act.lockButton) act.lockButton(); break; case 'dash': if (act.dash) act.dash(); break;
      case 'guardp': if (act.guard) act.guard('PHYSICAL'); break; case 'guardm': if (act.guard) act.guard('MAGICAL'); break; case 'fly': if (act.fly) act.fly(); break; case 'land': if (act.land) act.land(); break; case 'descend': break; case 'camreset': if (act.camReset) act.camReset(); break; case 'map': if (act.map) act.map(); break; case 'speed': if (act.speed) act.speed(); break; case 'mahgic': if (act.mahgic) act.mahgic('button'); break;
      case 'transform': if (p && p.transforming) { api.toast('ALREADY CHANGING FORM', 1200); break; } Promise.resolve(send('TRANSFORM')).then(function (res) { resultToast('TRANSFORM', res); }); break;   /* duplicate taps during a change never re-charge: the host rule is non-cancellable and the second request is refused, the HUD just says so */
      case 'practice': if (p && p.rules) Promise.resolve(send('FIELD_PRACTICE', { on: !p.rules.practice })).then(function (res) { resultToast('PRACTICE', res); }); break; case 'reset': Promise.resolve(send('PRACTICE_RESET')).then(function (res) { resultToast('RESET', res); }); break; case 'interact': if (act.interact) act.interact(); break;
      case 'sport-start-volley': send('HALO_SPORT_START', { mode: 'VOLLEY' }); break; case 'sport-start-practice': send('HALO_SPORT_START', { mode: 'PRACTICE' }); break;
      case 'sport-hit-loft': case 'sport-hit-drive': { var ht = el && el.getAttribute('data-target') || 'CENTER'; send('HALO_SPORT_HIT', { style: d === 'sport-hit-drive' ? 'DRIVE' : 'LOFT', zone: ht, lane: ht === 'LEFT' ? -1 : (ht === 'RIGHT' ? 1 : 0) }); break; }
      case 'sport-replay': send('HALO_SPORT_REPLAY'); break; case 'sport-leave': send('HALO_SPORT_LEAVE'); break;
      case 'emote': { var em = el && el.getAttribute('data-emote') ? el.getAttribute('data-emote') : 'WAVE'; api.performEmote(em, 'button'); break; }
      case 'emote-slot': { var es = el && el.getAttribute('data-emote'); if (es) { api.performEmote(es, 'radial'); api.closeEmotes('picked'); } break; }
      case 'emote-cancel': { if (p && p.emote) { Promise.resolve(send('EMOTE_STOP', {})).then(function (res) { if (res && res.accepted === false) api.toast(emoteRefusalText(p.emote, res, null), 1600); }); } api.closeEmotes('cancel'); break; }
      case 'emote-browse': api.closeEmotes('browse'); api.openMore('emotes'); break;
      case 'emote-stop': Promise.resolve(send('EMOTE_STOP', {})).then(function (res) { if (res && res.accepted === false) api.toast(emoteRefusalText(p && p.emote, res, null), 1600); st.pendingInvite = null; api.renderMore(); }); break;
      case 'fav-pick': { st.favPick = st.favPick === (el && el.getAttribute('data-emote')) ? null : (el && el.getAttribute('data-emote')); api.renderMore(); break; }
      case 'fav-set': { if (!el) break; var fi = parseInt(el.getAttribute('data-slot'), 10); var fe = el.getAttribute('data-emote'); var fv = favorites(); if (fe && fi >= 0 && fi < 6) { var dup = fv.indexOf(fe); if (dup >= 0 && dup !== fi) fv[dup] = fv[fi]; fv[fi] = fe; saveFavorites(); api.toast('★ ' + (emoteById(fe) ? emoteById(fe).name.toUpperCase() : fe) + ' → FAVOURITE ' + (fi + 1), 1400); } st.favPick = null; api.renderMore(); break; }
      case 'social-cycle': { var cands = socialCandidates(); if (!cands.length) { st.socialTarget = null; api.toast('NOBODY NEARBY', 1200); } else { var ci = cands.findIndex(function (x) { return x.id === st.socialTarget; }); var ni = ci + 1; st.socialTarget = ni >= cands.length ? null : cands[ni].id; } api.renderMore(); api.renderRadial(); break; }
      case 'invite-join': { var inv = p && p.invite; if (inv) Promise.resolve(send('EMOTE_JOIN', { from: inv.from })).then(function (res) { if (res && res.accepted === false) api.toast(emoteRefusalText(inv.emote_id, res, null), 1800); }); break; }
      case 'invite-cancel': { st.pendingInvite = null; Promise.resolve(send('EMOTE_STOP', {})).then(function () { api.renderMore(); }); break; }
      case 'more': if (act.menu) act.menu('ACTIONS'); break; case 'more-close': api.closePanels('sheet-handle'); break; case 'tab-actions': api.moreTab('actions'); break; case 'tab-loadout': api.moreTab('loadout'); break; case 'tab-emotes': api.moreTab('emotes'); break;
      case 'dock-toggle': api.dockCollapse(undefined, 'handle-tap'); break;
      case 'dev': api.closePanels('dev'); api.toggleDev(); break; case 'help': api.closePanels('help'); $('menu').classList.toggle('open'); break; case 'guide': api.closePanels('guide'); api.showGuide(true, 0); break; case 'guide-close': api.showGuide(false); break; case 'confirm-yes': api.confirmAnswer(true); break; case 'confirm-no': api.confirmAnswer(false); break; case 'catalog-close': api.catalogClose(); break; case 'guide-next': st.guideStep = Math.min(GUIDE.length - 1, st.guideStep + 1); api.renderGuide(); break; case 'guide-prev': st.guideStep = Math.max(0, st.guideStep - 1); api.renderGuide(); break; case 'detail-close': api.closeDetail(); break;
      case 'menu': if (act.menu) act.menu(); break; case 'sword': if (act.menu) act.menu('COMBAT'); break;
      case 'cat-cycle': case 'cat-next': case 'cat-prev': { var rc = p && p.rules; if (rc) { var lc = modes(rc); var ic = lc.findIndex(function (x) { return x.id === rc.me.attack_mode; }); var nx = lc[(ic + (d === 'cat-prev' ? lc.length - 1 : 1)) % lc.length]; api.selectMove(nx.id, undefined, 'label'); api.toast('CATEGORY → ' + nx.label, 900); } break; }
      case 'gear': { var gk = el && el.getAttribute('data-kind'), gc = parseInt(el && el.getAttribute('data-count') || '1', 10) || 1; if (gk) Promise.resolve(send('EQUIP_MANIFEST', { kind: gk, count: gc })).then(function (res) { if (res && res.ok) api.toast((res.kind || gk) + (gc > 1 ? ' ×' + gc : '') + ' MANIFESTING · −' + (res.cost || 0) + ' MAHGIC', 1400); else if (res) api.toast(res.reason === 'INSUFFICIENT_COMBAT_ENERGY' ? 'NOT ENOUGH COMBAT MAHGIC (need ' + (res.needed || '?') + ')' : (res.reason === 'MAGIC_AFFINITY_GATE' ? 'THIRD DUMBBELL NEEDS AFFINITY ' + (res.detail ? res.detail.third_dumbbell_needs : 2) : (res.reason === 'AIRBORNE' ? 'LAND TO MANIFEST' : (res.reason === 'GUIDE_CASTING' ? 'MRS. MAH IS STILL CASTING' : 'CANNOT MANIFEST (' + res.reason + ')'))), 1600); }); break; }
      case 'gear-dismiss': Promise.resolve(send('EQUIP_DISMISS', {})).then(function (res) { if (res && res.ok) api.toast('EQUIPMENT RECLAIMED', 1100); }); break;
      case 'refill': Promise.resolve(send('USE_REFILL', {})).then(function (res) { if (res && res.ok) api.toast('+' + (res.amount || '') + ' COMBAT MAHGIC (' + (res.inventory !== undefined ? res.inventory : '?') + ' stored)', 1400); else if (res) api.toast(res.reason === 'NO_REFILLS' ? 'NO REFILLS STORED — break a crystal bush' : (res.reason === 'MAHGIC_FULL' ? 'COMBAT MAHGIC IS FULL' : 'CANNOT REFILL (' + res.reason + ')'), 1400); }); break;
      case 'time': if (act.timeOfDay) { var ts = act.timeOfDay('toggle'); api.toast('TIME · ' + ts, 1200); var tsEl = $('g-time-state'); if (tsEl) tsEl.textContent = ts; } break;
      case 'hudmode': { var hm = api.hudMode(!st.minimal); api.toast('HUD · ' + hm.mode, 900); break; }
      case 'mahguide': if (act.mahGuide) act.mahGuide('toggle'); break; case 'mahguide-pick': if (act.mahGuide) act.mahGuide('pick'); break;
      case 'direct-0': case 'direct-1': case 'direct-2': case 'direct-3': if (act.directAttack) act.directAttack(parseInt(d.slice(7), 10), 'button'); break;
      case 'info': if (el) api.openDetail(parseInt(el.getAttribute('data-slot'), 10)); break; case 'info-sel': { var r0 = p && p.rules; if (r0) api.openDetail(r0.me.selection[r0.me.category] || 0); break; }
      case 'load-slot': { if (!el) break; var cat = el.getAttribute('data-cat'); var sl = parseInt(el.getAttribute('data-slot'), 10); st.loadSlot = st.loadSlot && st.loadSlot.cat === cat && st.loadSlot.slot === sl ? null : { cat: cat, slot: sl }; api.renderMore(); break; }
      case 'load-pick': case 'load-clear': { if (!el) break; var lc = el.getAttribute('data-cat'); var ls = parseInt(el.getAttribute('data-slot'), 10); var sk = d === 'load-clear' ? null : el.getAttribute('data-skill'); Promise.resolve(send('RULES_LOADOUT', { category: lc, slot: ls, skill_id: sk })).then(function (res) { resultToast('EQUIP', res); if (res && res.accepted) { api.toast((sk ? 'EQUIPPED ' + (el.getAttribute('data-name') || sk) : 'SLOT EMPTIED') + ' · ' + lc.replace(/_/g, ' ') + ' slot ' + (ls + 1), 1600); st.loadSlot = null; } api.renderMore(); }); break; }
      case 'niche': if (p && p.rules) send('RULES_NICHE', { on: !p.rules.me.niche }); break; case 'm1': if (act.quickMatch) act.quickMatch(1); break; case 'm2': if (act.quickMatch) act.quickMatch(2); break; case 'm3': if (act.quickMatch) act.quickMatch(3); break; case 'mend': send('TEAM_MATCH', { op: 'END' }); break; case 'mabort': send('TEAM_MATCH', { op: 'ABORT' }); break;
      case 'ally': if (p && p.rules) send('FIELD_ALLY', { op: p.rules.others.some(function (o) { return o.id === 'PRACTICE_ALLY'; }) ? 'REMOVE' : 'SPAWN' }); break; case 'mixed': send('FIELD_INCOMING', { kind: 'MIXED' }); break; case 'incp': send('FIELD_INCOMING', { kind: 'PHYSICAL' }); break; case 'incm': send('FIELD_INCOMING', { kind: 'MAGIC' }); break;
      case 'unlock': send('LOCK_TARGET', { aim_id: null }); break;
    } },
    /* ---- emotes: perform / radial / social target ---- */
    performEmote: function (id, source) { var p = st.lastP; var e = emoteById(id); var tgt = socialTarget(); if (e && e.form && e.form !== 'ANY' && p && p.form && p.form !== e.form) { api.toast(emoteRefusalText(id, { reason: 'FORM_REQUIRED', detail: { form: e.form } }, tgt), 2000); st.lastResult = { action: 'EMOTE ' + id, accepted: false, reason: 'FORM_REQUIRED', at: performance.now() }; return Promise.resolve({ accepted: false, reason: 'FORM_REQUIRED', client: true }); }   /* the host is authoritative; this only spares a round trip and words the requirement the same way */
      if (e && e.partner) { if (!tgt) { api.toast('PICK SOMEONE NEARBY (TO: chip) FOR ' + e.name.toUpperCase(), 2000); return Promise.resolve({ accepted: false, reason: 'TARGET_REQUIRED', client: true }); } return Promise.resolve(send('EMOTE_INVITE', { emote_id: id, to: tgt.id })).then(function (res) { st.lastResult = { action: 'EMOTE_INVITE ' + id, accepted: !!(res && res.accepted), reason: res && res.reason || null, at: performance.now() }; if (res && res.accepted) { st.pendingInvite = { emote_id: id, target_id: tgt.id, name: tgt.name, at: performance.now() }; api.toast('INVITED ' + tgt.name.toUpperCase() + ' · ' + e.name.toUpperCase(), 1600); } else api.toast(emoteRefusalText(id, res, tgt), 2200); api.renderMore(); return res; }); }
      var payload = { emote_id: id }; if (tgt && e && e.directed) payload.to = tgt.id; return Promise.resolve(send('EMOTE', payload)).then(function (res) { st.lastResult = { action: 'EMOTE ' + id, accepted: !!(res && res.accepted), reason: res && res.reason || null, at: performance.now() }; if (res && res.accepted) api.toast((e ? e.name.toUpperCase() : id) + (payload.to ? ' → ' + tgt.name.toUpperCase() : ''), 900); else api.toast(emoteRefusalText(id, res, tgt), 2200); return res; }); },
    openEmotes: function (opts) { var o = opts || {}; api.closePanels('emotes'); st.radial.open = true; st.radial.drag = !!o.drag; st.radial.id = o.pointerId === undefined ? null : o.pointerId; st.radial.hover = null; st.radial.moved = false; if (o.drag && st.pressBtn) { st.radial.x0 = st.pressBtn.x; st.radial.y0 = st.pressBtn.y; } var rd = $('g-radial'); if (rd) rd.style.display = 'block'; api.renderRadial(true); syncDismiss(); },
    closeEmotes: function (why) { if (!st.radial.open) return false; st.radial.open = false; st.radial.drag = false; st.radial.id = null; st.radial.hover = null; var rd = $('g-radial'); if (rd) rd.style.display = 'none'; st.suppressUntil = performance.now() + 250; syncDismiss(); return true; },
    emotesOpen: function () { return !!st.radial.open; },
    toggleEmotes: function () { if (st.radial.open) { api.closeEmotes('toggle'); return false; } api.openEmotes({ drag: false }); return true; },
    emoteState: function () { var p = st.lastP; return { radial: st.radial.open, drag: st.radial.drag, hover: st.radial.hover, favorites: favorites().slice(), social_target: st.socialTarget, candidates: socialCandidates().map(function (c) { return c.id; }), catalog_source: p && Array.isArray(p.emote_catalog) && p.emote_catalog.length ? 'host' : 'fallback', catalog: catalog().length, groups: GROUPS.slice(), playing: p ? p.emote || null : null, pending_invite: st.pendingInvite, invite: p ? p.invite || null : null, paired: p ? p.paired || null : null, fav_pick: st.favPick, defaults: { long_press_ms: DEF.long_press_ms, radial_radius_px: DEF.radial_radius_px, cancel_radius_px: DEF.cancel_radius_px } }; },
    setSocialTarget: function (id) { st.socialTarget = id || null; if (st.socialTarget && !socialTarget()) st.socialTarget = null; api.renderMore(); api.renderRadial(); return st.socialTarget; },   /* null = NOBODY; only ids among the nearby candidates stick */
    setFavorite: function (slot, id) { var fv = favorites(); if (slot >= 0 && slot < 6 && emoteById(id)) { fv[slot] = id; saveFavorites(); return true; } return false; },
    renderRadial: function (place) { var rd = $('g-radial'); if (!rd || !st.radial.open) return; var p = st.lastP; var R = DEF.radial_radius_px, C = DEF.cancel_radius_px; var small = innerWidth < 400 || innerHeight < 480; if (small) R = Math.min(R, Math.round(Math.min(innerWidth, innerHeight) * 0.24));
      if (place) { var mb = $('g-menubt'); var br = mb ? mb.getBoundingClientRect() : { left: innerWidth - 80, top: innerHeight - 80, width: 58, height: 58 }; var cx = br.left + br.width / 2 - R - 30, cy = br.top + br.height / 2 - R * 0.55; var m = R + 34; cx = Math.max(m, Math.min(innerWidth - m, cx)); cy = Math.max(m + 40, Math.min(innerHeight - m, cy)); rd.style.left = cx + 'px'; rd.style.top = cy + 'px'; st.radial.cx = cx; st.radial.cy = cy; }
      var fv = favorites(); var items = fv.map(function (id, i) { var e = emoteById(id); return { kind: 'slot', id: id, name: e ? e.name : id, icon: e ? e.icon : '•', idx: i, e: e }; }); items.push({ kind: 'browse', id: 'emote-browse', name: 'BROWSE', icon: '⋯' }); var n = items.length; var key = JSON.stringify([fv, p ? p.form : null, p ? p.emote : null, st.socialTarget, R, st.radial.hover]);
      if (rd.__k !== key) { rd.__k = key; var ring = $('g-radial-ring'); ring.innerHTML = items.map(function (it, i) { var a = -Math.PI / 2 + (i / n) * Math.PI * 2; var x = Math.round(Math.cos(a) * R), y = Math.round(Math.sin(a) * R); var req = it.e && it.e.form && it.e.form !== 'ANY' && p && p.form && p.form !== it.e.form ? (it.e.form === 'SPLIT' ? 'SEPARATE FIRST' : 'FUSE FIRST') : (it.e && it.e.partner ? 'PARTNER' : ''); var hov = st.radial.hover === (it.kind === 'browse' ? 'emote-browse' : it.id); return '<button class="gslotr' + (hov ? ' hov' : '') + (req ? ' req' : '') + '" style="left:' + x + 'px;top:' + y + 'px" data-do="' + (it.kind === 'browse' ? 'emote-browse' : 'emote-slot') + '"' + (it.kind === 'slot' ? ' data-emote="' + esc(it.id) + '"' : '') + ' title="' + esc(it.name) + '"><i>' + it.icon + '</i><b>' + esc(it.name) + '</b>' + (req ? '<small>' + req + '</small>' : '') + '</button>'; }).join('');
        var cb = $('g-radial-cancel'); cb.style.width = cb.style.height = (C * 2) + 'px'; cb.style.marginLeft = cb.style.marginTop = (-C) + 'px'; setHtml(cb, p && p.emote ? 'STOP' : 'CANCEL'); cb.classList.toggle('hov', st.radial.hover === 'emote-cancel'); cb.classList.toggle('stop', !!(p && p.emote)); var tgt = socialTarget(); setHtml($('g-radial-to'), tgt ? 'TO: ' + esc(tgt.name.toUpperCase()) : ''); } },
    /* ---- the MORE sheet: tabs ---- */
    /* PASS 3 (O3): one utility sheet — the ≡ menu hosts ACTIONS / LOADOUT / EMOTES; the MORE sheet's bodies are moved into the menu body while its tab is active */
    mountTab: function (tab, container) { var t = String(tab || '').toLowerCase(); var body = $(t === 'actions' ? 'g-moreacts' : (t === 'loadout' ? 'g-loadout' : 'g-emotes')); if (!body || !container) return false; if (container !== $('ghud') && !container.__hudBound) { container.__hudBound = true; st.delegated.forEach(function (d) { container.addEventListener(d[0], d[1], d[2]); }); } st.moreOpen = true; st.moreTab = t; if (body.parentNode !== container) container.appendChild(body); body.style.display = t === 'loadout' ? 'block' : 'flex'; api.renderMore(); return true; },
    unmountTabs: function () { var sheet = $('g-more'); ['g-moreacts', 'g-loadout', 'g-emotes'].forEach(function (id) { var el = $(id); if (el && sheet && el.parentNode !== sheet) sheet.appendChild(el); if (el) el.style.display = 'none'; }); st.moreOpen = false; },
    renderMore: function () { if (!st.moreOpen) return; var p = st.lastP; var r = p && p.rules; ['actions', 'loadout', 'emotes'].forEach(function (t) { var tb = $('g-tab-' + t); if (tb) tb.classList.toggle('sel', st.moreTab === t); }); ['g-moreacts', 'g-loadout', 'g-emotes'].forEach(function (id) { var el = $(id); if (!el) return; var mine = (id === 'g-moreacts' && st.moreTab === 'actions') || (id === 'g-loadout' && st.moreTab === 'loadout') || (id === 'g-emotes' && st.moreTab === 'emotes'); el.style.display = mine ? (id === 'g-loadout' ? 'block' : 'flex') : 'none'; });
      if (st.moreTab === 'emotes') { var cat = catalog(); var fv = favorites(); var tgt = socialTarget(); var cands = socialCandidates(); var inv = p && p.invite; var out = p && p.invite_out; if (out && st.pendingInvite && st.pendingInvite.emote_id !== out.emote_id) st.pendingInvite = null; if (!out && st.pendingInvite && performance.now() - st.pendingInvite.at > 9000) st.pendingInvite = null; var ek = JSON.stringify([cat.length, fv, p ? p.form : null, p ? p.emote : null, st.socialTarget, cands.map(function (c) { return c.id + (c.near ? '+' : '-'); }), st.favPick, inv ? inv.from + inv.emote_id : null, out ? out.to + out.emote_id : (st.pendingInvite ? st.pendingInvite.emote_id : null), p ? (p.paired ? p.paired.id : null) : null]); if (st.emoteKey !== ek) { st.emoteKey = ek;
        var head = '<div class="gehead"><button class="gbtn sm gto" data-do="social-cycle" title="who a social emote addresses (never an enemy lock)">TO: <b>' + (tgt ? esc(tgt.name.toUpperCase()) + (tgt.near ? '' : ' (FAR)') : 'NOBODY') + '</b> ▸' + (cands.length ? '<small>' + cands.length + ' nearby</small>' : '<small>nobody nearby</small>') + '</button>' + (p && p.emote ? '<button class="gbtn sm gstop" data-do="emote-stop">■ STOP ' + esc((emoteById(p.emote) || { name: p.emote }).name.toUpperCase()) + '</button>' : '') + '</div>';
        if (inv && inv.from) head += '<div class="geinvite"><span>' + esc(String(inv.from).replace(/_/g, ' ').toUpperCase()) + ' invites you · ' + esc((emoteById(inv.emote_id) || { name: inv.emote_id }).name.toUpperCase()) + '</span><button class="gbtn sm gold" data-do="invite-join">JOIN</button></div>'; else if ((out || st.pendingInvite) && !(p && p.paired)) { var wn = out ? String(out.to).replace(/_/g, ' ') : st.pendingInvite.name; var we = out ? out.emote_id : st.pendingInvite.emote_id; head += '<div class="geinvite"><span>WAITING FOR ' + esc(wn.toUpperCase()) + ' · ' + esc((emoteById(we) || { name: we }).name.toUpperCase()) + '…</span><button class="gbtn sm" data-do="invite-cancel">CANCEL</button></div>'; } else if (p && p.paired) head += '<div class="geinvite"><span>PAIRED · ' + esc((emoteById(p.paired.id) || { name: p.paired.id }).name.toUpperCase()) + ' with ' + esc(String(p.paired.partner_id || '').replace(/_/g, ' ').toUpperCase()) + '</span><button class="gbtn sm" data-do="emote-stop">LEAVE</button></div>';
        var body = GROUPS.map(function (g) { var list = cat.filter(function (e) { return e.group === g; }); if (!list.length) return ''; return '<div class="gegroup" data-group="' + g + '"><div class="glh"><b>' + g + '</b><span>' + list.length + '</span></div><div class="gelist">' + list.map(function (e) { var favIdx = fv.indexOf(e.id); var req = e.form && e.form !== 'ANY' && p && p.form && p.form !== e.form ? (e.form === 'SPLIT' ? 'SEPARATE FIRST' : 'FUSE FIRST') : (e.partner ? 'PARTNER' : (e.directed ? 'to: ' + (tgt ? tgt.name : 'anyone') : '')); var playing = p && p.emote === e.id; return '<div class="gem' + (playing ? ' playing' : '') + '"><button class="gemb' + (req && /FIRST/.test(req) ? ' req' : '') + '" data-do="emote" data-emote="' + esc(e.id) + '"><i>' + (e.icon || '•') + '</i><b>' + esc(e.name) + '</b><small>' + esc(req || (e.loop ? 'loop · STOP ends it' : '')) + '</small></button><button class="gstar' + (favIdx >= 0 ? ' on' : '') + (st.favPick === e.id ? ' pick' : '') + '" data-do="fav-pick" data-emote="' + esc(e.id) + '" title="assign to a favourite slot">' + (favIdx >= 0 ? '★' + (favIdx + 1) : '☆') + '</button>' + (st.favPick === e.id ? '<div class="gfavrow"><span>favourite slot:</span>' + [0, 1, 2, 3, 4, 5].map(function (k) { return '<button class="gbtn sm' + (fv[k] === e.id ? ' on' : '') + '" data-do="fav-set" data-slot="' + k + '" data-emote="' + esc(e.id) + '">' + (k + 1) + '</button>'; }).join('') + '</div>' : '') + '</div>'; }).join('') + '</div>'; }).join('');
        $('g-emotes').innerHTML = head + body + '<div class="about">Cosmetic only: never a buff, never a workout, never bypasses a restriction. Long-press ≡ for the six favourites (★); V on desktop. Partner emotes invite the TO: target and wait for them to JOIN.</div>'; } }
      if (st.moreTab === 'loadout') { var lo = loadoutOf(r); var el = $('g-loadout'); if (!r) { setHtml(el, '<div class="gnone">NO RULES ROOM — loadout lives in the rules field</div>'); return; } if (!lo) { setHtml(el, '<div class="gnone">LOADOUT DATA NOT PUBLISHED BY THIS HOST</div><div class="about">The host snapshot has no rules.me.loadout block, so nothing can be equipped from here. Attack modes still work with the host defaults.</div>'); return; }
        var key = JSON.stringify([lo, st.loadSlot, r.me.class, r.me.level]); if (st.loadKey === key) return; st.loadKey = key; var html = '<div class="glhead">' + esc(r.me.class) + ' · level ' + r.me.level + ' · tap a slot, then a move · ◇ = empty slot (valid)</div>';
        modes(r).forEach(function (m) { var c = lo[m.category]; if (!c) { html += '<div class="gload"><div class="glh"><b>' + esc(m.label) + '</b><span>not published</span></div></div>'; return; } var eq = c.equipped || []; var n = eq.filter(function (x) { return !!x; }).length; html += '<div class="gload"><div class="glh"><b>' + esc(m.label) + '</b><span>' + n + ' / ' + c.capacity + ' equipped</span></div><div class="glslots">';
          for (var i = 0; i < c.capacity; i++) { var id = eq[i] || null; var pe = id && c.pool ? c.pool.filter(function (x) { return x.skill_id === id; })[0] : null; var open = st.loadSlot && st.loadSlot.cat === m.category && st.loadSlot.slot === i; html += '<button class="gslot' + (open ? ' sel' : '') + (id ? '' : ' empty') + '" data-do="load-slot" data-cat="' + m.category + '" data-slot="' + i + '"><b>' + (i + 1) + '</b>' + (id ? esc(pe && pe.name ? pe.name : id) : '◇ empty') + '</button>'; }
          html += '</div>'; if (st.loadSlot && st.loadSlot.cat === m.category) { var pool = c.pool || []; var sl = st.loadSlot.slot; html += '<div class="glpool"><div class="glh"><span>slot ' + (sl + 1) + ' · pick a move</span></div>'; if (!pool.length) html += '<div class="gnone">NO MOVES IN THIS POOL FOR ' + esc(r.me.class) + '</div>'; pool.forEach(function (s) { var inSlot = eq.indexOf(s.skill_id); var ok = s.eligible !== false; html += '<button class="gpool' + (ok ? '' : ' locked') + (inSlot >= 0 ? ' eq' : '') + '" data-do="load-pick" data-cat="' + m.category + '" data-slot="' + sl + '" data-skill="' + esc(s.skill_id) + '" data-name="' + esc(s.name || s.skill_id) + '"' + (ok ? '' : ' disabled') + '><b>' + esc(s.name || s.skill_id) + '</b><small>' + (ok ? (inSlot >= 0 ? 'equipped in slot ' + (inSlot + 1) : 'eligible') : esc(String(s.reason || 'locked').replace(/_/g, ' ').toLowerCase())) + '</small></button>'; }); html += '<button class="gpool clear" data-do="load-clear" data-cat="' + m.category + '" data-slot="' + sl + '"><b>◇ leave slot ' + (sl + 1) + ' empty</b><small>an empty slot is valid</small></button></div>'; }
          html += '</div>'; });
        setHtml(el, html); } },
    /* ---- the dock: three mode buttons (with equipped counts), the single drawer, compact readout ---- */
    renderDock: function () {
      var p = st.lastP; var r = p && p.rules; var dock = $('g-dock'); if (!dock) return; if (!DOCK || !r) { dock.style.display = 'none'; st.key = null; return; } dock.style.display = 'flex'; var touch = document.body.classList.contains('touch'); var lo = loadoutOf(r);
      var list = modes(r); var mkey = list.map(function (m) { var ec = equippedCount(lo, m.category); return m.id + ':' + m.label + ':' + (ec ? ec.n + '/' + ec.cap : '-'); }).join('|'); if (st.key !== mkey) { st.key = mkey; $('g-cats').innerHTML = list.map(function (m) { var ec = equippedCount(lo, m.category); return '<button class="gcat gmode" data-mode="' + m.id + '" data-cat="' + m.category + '" title="' + esc(m.label) + (ec ? ' · ' + ec.n + ' of ' + ec.cap + ' equipped' : '') + '">' + twoLine(m.label) + (ec ? '<small class="cnt">' + ec.n + '/' + ec.cap + '</small>' : '') + '</button>'; }).join(''); }
      Array.prototype.forEach.call($('g-cats').querySelectorAll('button.gmode'), function (b) { b.classList.toggle('sel', b.getAttribute('data-mode') === r.me.attack_mode); b.classList.toggle('open', st.drawerOpen && b.getAttribute('data-mode') === r.me.attack_mode); });
      var cat = r.me.category; var skills = r.skills[cat] || []; var sel = skills[r.me.selection[cat] || 0] || null;
      var statusWord = sel ? (sel.availability === 'READY' ? 'READY' : (sel.availability === 'COOLDOWN' ? 'COOLDOWN ' + sel.cooldown_remaining_s.toFixed(1) + 's' : (sel.availability === 'LOW_ENERGY' ? 'LOW MAHGIC' : (sel.availability === 'UNVERIFIED_MAPPING' ? 'NOT MAPPED — owner decision' : 'UNAVAILABLE')))) : '';
      var glyph = sel ? ({ UP: '⇡', DOWN: '⇣', LEFT: '⇠', RIGHT: '⇢' }[String(sel.gesture || '').toUpperCase()] || '•') : ''; var summary = sel ? '<b class="gg" title="' + esc(gestureText(sel, touch)) + '">' + glyph + '</b> <b>' + esc(sel.stack && sel.stack.resolved_name ? sel.stack.resolved_name : sel.name) + '</b> · ' + esc(statusWord) : 'no move armed'; if (p.guard) summary += ' · <b>GUARD ' + p.guard + '</b>'; var stt = r.me.statuses.map(function (x) { return x.kind + (x.magnitude && x.kind === 'SLOW' ? ' ' + Math.round(x.magnitude * 100) + '%' : '') + ' ' + x.remaining_s.toFixed(1) + 's'; }); if (r.me.invisible) stt.push('INVISIBLE'); if (r.me.immune) stt.push('IMMUNE'); if (r.me.discord) stt.push('DISCORD MARK'); if (stt.length) summary += ' · <span class="st">' + esc(stt.join(' · ')) + '</span>'; setHtml($('g-sel'), summary);
      setHtml($('g-cast'), r.me.cast ? '<div class="gcast"><i style="transform:scaleX(' + Math.min(1, r.me.cast.progress) + ')"></i><b>' + esc(r.me.cast.presentation && r.me.cast.presentation.display_name ? r.me.cast.presentation.display_name : r.me.cast.skill) + ' · ' + (r.me.cast.phase === 'STARTUP' ? 'WINDING UP' : 'RECOVERING') + '</b></div>' : '');
      var drawer = $('g-drawer'); drawer.style.display = st.drawerOpen ? 'block' : 'none'; if (!st.drawerOpen) return;
      var m = modeOfCat(r, cat); var ecm = equippedCount(lo, cat); $('g-drawhead').textContent = (m ? m.label : cat) + ' · ' + r.me.class + ' · level ' + r.me.level + (ecm ? ' · ' + ecm.n + ' / ' + ecm.cap + ' equipped' : '') + ' · tap a move to arm it · ⓘ = how to perform';
      var cap = ecm ? ecm.cap : 4; var dkey = cat + '#' + r.me.class + '#' + touch + '#' + cap + '#' + skills.map(function (s) { return s ? s.id + ':' + (s.stack ? s.stack.attack_stack_id : '-') : '-'; }).join(',');
      if (st.drawerKey !== dkey) { st.drawerKey = dkey; var rows = ''; var any = false; var slotKeys = touch ? ['1', '2', '3', '4'] : ['E', 'R', 'T', 'Y'];   /* G20: on touch the drawer chips carry the 1–4 slot numbers of the bottom row, never keyboard letters */ for (var i = 0; i < Math.max(cap, skills.length); i++) { var s = skills[i]; if (!s) { rows += '<div class="gchip empty" data-slot="' + i + '"><b class="gkey off">' + (slotKeys[i] || (i + 1)) + '</b><span class="pn">◇ empty slot · ≡ LOADOUT</span></div>'; continue; } any = true; var unassigned = s.movement_pattern_id === 'UNASSIGNED_PATTERN_DEV'; rows += '<div class="gchip" data-slot="' + i + '"><b class="gkey">' + (slotKeys[i] || (i + 1)) + '</b><span class="pn">' + esc(unassigned ? (s.stack && s.stack.resolved_name ? s.stack.resolved_name : s.name) : s.pattern_name) + '</span><span class="an">' + esc(unassigned ? '' : (s.stack && s.stack.resolved_name ? s.stack.resolved_name : s.name)) + '</span><i id="g-chip' + i + '"></i><button class="ginfo" data-do="info" data-slot="' + i + '" title="details" aria-label="details">ⓘ</button></div>'; } $('g-chips').innerHTML = any ? rows : '<div class="gnone">NO MOVE EQUIPPED — ≡ LOADOUT</div>'; }
      Array.prototype.forEach.call($('g-chips').querySelectorAll('.gchip'), function (ch) { var i = parseInt(ch.getAttribute('data-slot'), 10); var s = skills[i]; if (!s) return; ch.classList.toggle('sel', !!s.selected); ch.classList.toggle('cd', s.availability !== 'READY'); var info = $('g-chip' + i); if (info) { var status = s.selected && s.availability === 'READY' ? 'ARMED' : (s.availability === 'COOLDOWN' ? 'COOLDOWN ' + s.cooldown_remaining_s.toFixed(1) + 's' : (s.availability === 'LOW_ENERGY' ? 'LOW MAHGIC' : (s.availability === 'READY' ? 'READY' : 'UNAVAILABLE NOW' + (s.availability_why ? ' (' + String(s.availability_why).replace(/_/g, ' ').toLowerCase() + ')' : '')))); info.textContent = gestureText(s, touch) + ' · ' + (s.cost ? s.cost + ' MAHGIC' : 'no cost') + ' · ' + status; } });
    },
    /* ---- per-tick ---- */
    render: function (p, ctx) {
      build(); st.lastP = p; var root = $('ghud'); if (!p) { root.style.display = 'none'; return; } root.style.display = 'block'; var r = p.rules; var c = ctx || {}; if (r && CLASS_TINT[r.me.class]) document.documentElement.style.setProperty('--class', CLASS_TINT[r.me.class]);
      var hp = r ? r.me.hp : (p.field ? p.field.health : null), hpMax = r ? r.me.max : 100; $('g-hp').textContent = hp === null || hp === undefined ? '—' : Math.round(hp) + ' / ' + hpMax; var lvEl = $('g-lv'); if (lvEl) setHtml(lvEl, r && r.me.level ? 'LV ' + r.me.level : (p.character && p.character.level ? 'LV ' + p.character.level : '')); $('g-vitals').querySelector('.gb.hp i').style.transform = 'scaleX(' + pct(hp || 0, hpMax) + ')'; $('g-vitals').querySelector('.gb.hp').classList.toggle('low', pct(hp || 0, hpMax) <= 0.25);
      var cm = r ? r.me.combat_energy : p.combat_mahgic; $('g-cm').textContent = Math.round(cm.current) + ' / ' + cm.max; $('g-vitals-r').querySelector('.gb.cm i').style.transform = 'scaleX(' + pct(cm.current, cm.max) + ')'; $('g-vitals-r').querySelector('.gb.cm').classList.toggle('low', pct(cm.current, cm.max) <= 0.25);
      $('g-fm').textContent = Math.round(p.flight_mahgic.current) + ' / ' + p.flight_mahgic.max + (p.flight.powered && p.flight.remaining_s !== null ? ' · ' + p.flight.remaining_s.toFixed(0) + 's' : ''); $('g-vitals-r').querySelector('.gb.fm i').style.transform = 'scaleX(' + pct(p.flight_mahgic.current, p.flight_mahgic.max) + ')'; $('g-vitals-r').querySelector('.gb.fm').classList.toggle('warn', !!p.flight.warning);
      var stateEl = $('g-state'); var stText, stCls; if (p.sport && p.sport.active) { stText = p.sport.mode === 'VOLLEY' ? 'MAH HALO VOLLEY · FIRST TO 7' : 'MAH HALO SERVE LAB · 5 ATTEMPTS'; stCls = 'practice'; } else if (r && r.context === 'MATCH') { stText = 'MAH MATCH — DAMAGE ACTIVE'; stCls = 'match'; } else if (r && r.context === 'PRACTICE') { stText = 'PRACTICE BATTLE'; stCls = 'practice'; } else if (p.in_duel) { stText = 'DUEL — DAMAGE ACTIVE'; stCls = 'match'; } else { var wildNear = null; var mePos = p.position || { x: 0, z: 0 }; var scan = function (c) { if (!c || c.ko || !c.position) return; var st = c.state || ''; var fighting = /CHASE|BITE|ATTACK|SWIRL|LAUNCH|RISE|WINDUP|DIVE|SNORT|FEINT/.test(st) || (c.fight === true); if (!fighting) return; var d = Math.hypot(c.position.x - mePos.x, c.position.z - mePos.z); if (d < 30 && (!wildNear || d < wildNear.d)) wildNear = { d: d, species: c.species || 'WILD' }; }; (p.creatures || []).forEach(scan); (p.wildlife || []).forEach(scan);   /* owner next-pass 2026-09-20: wild creatures are real enemies — the state treatment says so while one is on the player */ if (wildNear) { stText = 'WILD ENCOUNTER · ' + wildNear.species; stCls = 'practice'; } else { stText = 'FREE ROAM'; stCls = 'free'; } } stateEl.textContent = stText; stateEl.className = stCls;
      var hs = $('g-sport'), hsPrompt = (p.prompts || []).filter(function (x) { return x.intent === 'HALO_PLAY' && x.eligible; })[0] || null; document.body.classList.toggle('halo-sport', !!(p.sport && p.sport.active)); if (hs) { var sh = ''; if (p.sport && p.sport.active) { var sv = p.sport, score = sv.mode === 'VOLLEY' ? ('YOU ' + sv.score.player + ' · ' + sv.score.bot + ' BOT') : ('TARGETS ' + sv.practice.hits + ' / ' + sv.practice.attempts + ' OF ' + sv.practice.total); sh = '<b>' + esc(score) + '</b><span>' + esc(String(sv.phase).replace(/_/g, ' ')) + (sv.point ? ' · ' + esc(String(sv.point.why).replace(/_/g, ' ')) : '') + '</span><div class="sport-actions">'; if (sv.phase === 'SERVE_READY' || sv.phase === 'RALLY' || sv.phase === 'IN_FLIGHT') { if (sv.mode === 'PRACTICE') sh += '<button data-do="sport-hit-loft" data-target="LEFT">LEFT</button><button data-do="sport-hit-loft" data-target="CENTER">CENTER</button><button data-do="sport-hit-loft" data-target="RIGHT">RIGHT</button>'; else sh += '<button data-do="sport-hit-loft" data-target="CENTER">LOFT · V</button><button data-do="sport-hit-drive" data-target="CENTER">DRIVE · R</button>'; } if (sv.phase === 'RESULT') sh += '<button data-do="sport-replay">REPLAY · P</button>'; sh += '<button data-do="sport-leave">LEAVE · ESC</button></div>'; } else if (hsPrompt) sh = '<b>MAH HALO COURT</b><span>real ball contact · no combat rewards</span><div class="sport-actions"><button data-do="sport-start-volley">BOT MATCH · V</button><button data-do="sport-start-practice">SERVE LAB · P</button></div>'; var key = sh; if (hs.getAttribute('data-key') !== key) { hs.setAttribute('data-key', key); setHtml(hs, sh); } hs.style.display = sh ? 'flex' : 'none'; }
      var tg = $('g-target'); var lk = r && r.me.lock; if (tg && lk) { var o = r.others.filter(function (x) { return x.id === lk.target; })[0]; tg.style.display = 'block'; $('g-tname').textContent = 'LOCKED: ' + (o ? o.id.replace(/_/g, ' ') : lk.target); $('g-thp').textContent = o ? Math.round(o.hp) + ' / ' + o.max : '—'; tg.querySelector('.gb.thp i').style.transform = 'scaleX(' + (o ? pct(o.hp, o.max) : 0) + ')'; $('g-tnote').textContent = lk.visible === false ? 'behind cover — lock drops in 1.5 s' : (lk.out_of_range ? 'too far — lock drops in 2 s' : (c.touch ? '≡ SETTINGS → UNLOCK clears' : 'Esc clears the lock')); tg.classList.toggle('faded', lk.visible === false); } else if (tg) tg.style.display = 'none';
      var ub = $('g-unlockbtn'); if (ub) ub.style.display = lk ? '' : 'none'; var lb = $('g-lockbtn'); if (lb) { setHtml(lb, lk ? 'UNLOCK<small>Esc</small>' : 'LOCK<small>click enemy</small>'); lb.classList.toggle('on', !!lk); }
      var w = $('g-warn'); var wt = null; if (p.flight.forced_landing) wt = p.flight.falling ? 'FALLING' : ((p.flight_mahgic && p.flight_mahgic.current > 0.5) ? 'FORCED LANDING — flight MAHGIC ran out, landing first' : 'FLIGHT MAHGIC EMPTY — LANDING'); else if (p.flight.warning) wt = 'LOW FLIGHT MAHGIC — landing soon'; else if (p.defeat) wt = 'DEFEATED — returning to the sanctuary in ' + Math.ceil(p.defeat.respawn_in_s) + ' s';   /* owner next-pass 2026-09-20 §20: the demo defeat loop (host-authoritative respawn at the safe point) */ else if (r && r.me.ko) wt = 'KNOCKED OUT — ≡ SETTINGS → RESET PRACTICE'; else if (r && r.match && r.match.paused) wt = 'MATCH PAUSED — a player is missing (10 s)'; else if (r && r.match && r.match.outcome) wt = 'MATCH ' + r.match.outcome + (r.match.winner ? ' — team ' + r.match.winner : ''); else if (c.lockRefused && performance.now() < c.lockRefused.until) wt = 'LOCK REFUSED: ' + c.lockRefused.text; else if (c.castRefused && performance.now() < c.castRefused.until) wt = c.castRefused.text; w.style.display = wt ? 'block' : 'none'; w.textContent = wt || '';
      var to = $('g-toast'); if (st.toast && performance.now() < st.toastT) { to.style.display = 'block'; to.textContent = st.toast; } else to.style.display = 'none';
      /* E R T Y direct-attack strip: compact, beside ATTACK on desktop; four direct slot buttons on touch. Inactive when the slot is empty / not ready. */
      var erty = $('g-erty'), ertyT = $('g-erty-t'); if ((erty || ertyT) && r) { var list = r.skills[r.me.category] || []; var html = '', htmlT = ''; for (var qi = 0; qi < 4; qi++) { var qs = list[qi]; var ready = qs && qs.availability === 'READY'; var flash = st.flashSlot === qi && performance.now() < st.flashT; var unverified = qs && qs.availability === 'UNVERIFIED_MAPPING'; var cls = 'gbtn gq' + (qs ? (ready ? '' : (unverified ? ' off unverified' : ' cd')) : ' off') + (flash ? ' hit' : '');   /* owner B8 §23: an unverified mapping never looks READY — the slot is visibly disabled */ var body = '<small>' + esc(qs ? (qs.pattern_label || qs.pattern_name || qs.name) : '—') + '</small></button>';   /* G20: the authored short form (ruleset hud_label), never a sliced name */ var open = '<button class="' + cls + '" data-do="direct-' + qi + '" ' + (qs ? 'title="' + esc(qs.pattern_name || qs.name) + '"' : 'disabled') + '>'; html += open + '<b>' + ['E', 'R', 'T', 'Y'][qi] + '</b>' + body; htmlT += open + '<b>' + (qi + 1) + '</b>' + body; } if (erty) setHtml(erty, html); if (ertyT) setHtml(ertyT, htmlT); }
      var dg = $('g-dialog'); if (dg) { if (st.dialog && performance.now() - st.dialog.t < 9000) { var dl = st.dialog; setHtml(dg, '<div class="dwho">' + esc(dl.who.replace(/^NPC_/, '').replace(/_/g, ' ')) + ' · ' + esc(dl.title) + '</div><div class="dline">' + esc(dl.lines[dl.i] || '') + '</div><div class="dnext">' + (dl.i < dl.lines.length - 1 ? 'tap · next' : 'tap · close') + '</div>'); dg.style.display = 'block'; } else { if (st.dialog) st.dialog = null; dg.style.display = 'none'; } }
      var cue = $('g-cue'); if (cue) cue.style.display = performance.now() < st.cueUntil && !anyPanel() ? 'block' : 'none';
      if (r) { var dkey = r.classes.join(',') + '|' + (c.avatars || []).join(','); if ($('g-devbody').getAttribute('data-key') !== dkey) { $('g-devbody').setAttribute('data-key', dkey); $('g-devbody').innerHTML = 'class <select id="classpick">' + r.classes.map(function (x) { return '<option' + (x === r.me.class ? ' selected' : '') + '>' + x + '</option>'; }).join('') + '</select> level <select id="levelpick"><option>1</option><option>12</option><option>13</option><option>20</option></select> avatar <select id="avatarpick">' + (c.avatars || []).map(function (x) { return '<option' + (x === c.avatar_id ? ' selected' : '') + '>' + x + '</option>'; }).join('') + '</select><br><button class="gbtn sm" data-do="niche">niche</button> <button class="gbtn sm" data-do="m1">1v1</button><button class="gbtn sm" data-do="m2">2v2</button><button class="gbtn sm" data-do="m3">3v3</button><button class="gbtn sm" data-do="mabort">abort match</button> <button class="gbtn sm" data-do="ally">ally</button> <button class="gbtn sm" data-do="mixed">incoming mixed</button><button class="gbtn sm" data-do="incp">incoming phys</button><button class="gbtn sm" data-do="incm">incoming magic</button> <button class="gbtn sm" data-do="unlock">unlock</button><div id="g-devline"></div><div id="g-devline2"></div><div id="g-devline3"></div>'; var cp = $('classpick'); if (cp) cp.onchange = function () { send('RULES_CLASS', { class: cp.value }); }; }
        var dl = $('g-devline'); if (dl) dl.textContent = r.me.class + ' L' + r.me.level + ' ' + r.me.band + ' · stacks rev ' + r.me.stacks_revision + ' · context ' + r.context + ' · colliders ' + (r.colliders ? r.colliders.version : '—') + ' · ' + r.ruleset + ' · dummy ' + (r.others[0] ? Math.round(r.others[0].hp) : '—'); var dl2 = $('g-devline2'); if (dl2) dl2.textContent = (r.match ? 'MATCH ' + r.match.id + ' ' + r.match.state + ' team ' + (r.match.my_team || '—') : 'no team match') + ' · lock ' + (lk ? lk.target : 'none') + ' · cam yaw ' + (c.camYawDeg === undefined ? '—' : c.camYawDeg + '°') + ' · avatar ' + (c.avatar || '') + (r.me.cast && r.me.cast.stack ? ' · cast stack ' + r.me.cast.stack.attack_stack_id : ''); var dl3 = $('g-devline3'); if (dl3) dl3.textContent = c.avatarNote || ''; var dg = $('g-diag'); if (dg && st.dev) dg.textContent = c.diag || ''; }
      api.renderDock();
      var catL = $('g-catlbl'); if (catL) { var mmode = r ? modes(r).filter(function (x) { return x.id === r.me.attack_mode; })[0] : null; var catT = $('g-cattext'); if (catT) setHtml(catT, mmode ? '<b>' + esc(mmode.label) + '</b>' : '—'); var showCat = !!(r && !DOCK); if ((catL.style.display !== 'none') !== showCat) catL.style.display = showCat ? 'block' : 'none'; }   /* §3: the armed category is a small label above PRIMARY (tap = next) — the top-right category card is gone */
      var cls = (r && r.me && r.me.class) || 'ATHLETE'; if (document.body.dataset.class !== cls) document.body.dataset.class = cls;   /* O9: the LOCAL player's class picks the HUD tokens (never a remote player or an environment tint) */
      var spB = $('g-speed'); if (spB) { var spOn = !!(ctx && ctx.speedMode); spB.classList.toggle('selected', spOn); spB.title = spOn ? 'faster travel ON (tap to stop)' : 'faster travel (toggle) — sustained, not a dash'; } var mgB = $('g-mahgic'); if (mgB) { var anyMagic = r && ['SPECIAL_MAGIC', 'PHYSICAL_MAGIC'].some(function (k) { return (r.skills[k] || []).some(function (x) { return x && x.availability === 'READY'; }); }); mgB.classList.toggle('disabled', !anyMagic); var cdMagic = r && !anyMagic && ['SPECIAL_MAGIC', 'PHYSICAL_MAGIC'].some(function (k) { return (r.skills[k] || []).some(function (x) { return x && x.availability === 'COOLDOWN'; }); }); mgB.classList.toggle('cooldown', !!cdMagic); }
      var cl = $('g-cluster'); if (cl) cl.classList.toggle('air', !!p.flight.powered);
      var fb = $('g-fly'); var inMatch = !!(r && r.match && (r.match.state === 'ACTIVE' || r.match.state === 'PAUSED')) || p.in_duel; if (inMatch) { setHtml(fb, 'NO<br>FLIGHT'); fb.classList.add('off'); fb.classList.remove('on'); fb.title = 'no flight in a MAH MATCH'; } else if (p.flight.forced_landing && !p.flight.falling) { setHtml(fb, 'LANDING<br><small>required</small>'); fb.classList.add('off'); fb.classList.remove('on'); fb.title = 'flight MAHGIC ran out: the landing completes first'; } else if (p.flight.powered) { var descending = p.flight.intent < 0 && !p.flight.exiting; setHtml(fb, descending ? 'FLY<br><small>▼ tap: hold</small>' : 'FLY<br><small>▲ hold · tap ▼</small>'); fb.classList.add('on'); fb.classList.remove('off'); fb.title = descending ? 'descending — tap: stop and hold · hold: climb' : 'hold: climb · release: hold altitude · tap: descend'; } else { setHtml(fb, 'FLY<br><small>hold ▲</small>'); fb.classList.remove('on'); fb.classList.remove('off'); fb.title = 'hold: take off and climb · release: hold altitude · tap: lift and hover'; }   /* JOB A: one FLY control, no DOWN / LAND buttons — descending to the support IS the landing */
      var tf = $('tc-form'); if (tf) { var isSplit = p.form === 'SPLIT'; var want = (isSplit ? 'FUSE' : 'SEPARATE') + '<small>' + (p.transforming ? '…' : 'tap · H') + '</small>'; if (tf.getAttribute('data-l') !== want) { tf.setAttribute('data-l', want); tf.innerHTML = want; } tf.classList.toggle('on', isSplit); }   /* JOB A: the SEPARATE / FUSE button shows the transition it will perform */
      var gr = $('g-gear'); if (gr) { var eqv = p.equipment; var showGear = !!(eqv && p.room === 'FIELD' && !st.dockCollapsed); gr.style.display = showGear ? 'block' : 'none'; if (showGear) { var cmN = cm ? cm.current : 0; var held = eqv.held; var costs = eqv.costs || {}; gr.querySelectorAll('button[data-do="gear"]').forEach(function (b) { var k = b.getAttribute('data-kind'), n = parseInt(b.getAttribute('data-count'), 10) || 1; var cost = k === 'DUMBBELL' ? ((costs.DUMBBELL || [])[n - 1]) : costs[k]; var gated = k === 'DUMBBELL' && n === 3 && (eqv.affinity || 1) < 2; var have = (eqv.manifested || []).filter(function (it) { return it.kind === k && it.state !== 'RECLAIMING'; }).length; b.querySelector('small').textContent = gated ? 'LOCK' : (cost !== undefined ? '−' + cost : ''); b.classList.toggle('on', have > 0 && (k !== 'DUMBBELL' || have === n)); b.classList.toggle('dim', gated || (cost !== undefined && cmN < cost)); }); gr.querySelector('.gb.charge i').style.transform = 'scaleX(' + Math.max(0, Math.min(1, eqv.guide_charge || 0)) + ')'; gr.querySelector('.gb.charge').classList.toggle('full', (eqv.guide_charge || 0) >= 0.999); var rf = $('g-refill'); if (rf) { rf.querySelector('b').textContent = eqv.refills || 0; rf.classList.toggle('dim', !(eqv.refills > 0)); } gr.classList.toggle('held', !!held); } }   /* B8: the gear row reads the host equipment view only (costs, affinity gate, charge, inventory) */
      var mg = $('g-mahguide'); if (mg && act.mahGuideState) { var mgs = act.mahGuideState(); mg.classList.toggle('on', !!(mgs && mgs.visible)); mg.textContent = '✧ ' + (mgs && mgs.visible ? (mgs.who === 'MR' ? 'MR. MAH' : 'MRS. MAH') : 'GUIDE'); var mgw = $('g-mahguide-who'); if (mgw) mgw.textContent = mgs && mgs.who === 'MR' ? 'Mr. Mah' : 'Mrs. Mah'; } var tsE = $('g-time-state'); if (tsE && act.timeOfDay) tsE.textContent = act.timeOfDay(); var hmE = $('g-hudmode'); if (hmE) setHtml(hmE, 'HUD: ' + (st.minimal ? 'MINIMAL' : 'FULL') + '<small>' + (st.minimal ? 'show full' : 'show minimal') + ' · F2</small>');   /* M5 minimal/full is a reversible view preference; O4: the descent / landing affordance exists only while airborne */
      var gg = $('g-guard'); if (gg) { gg.classList.toggle('on', !!p.guard); setHtml(gg, p.guard === 'MAGICAL' ? 'GUARD<br><small>magic</small>' : (p.guard === 'PHYSICAL' ? 'GUARD<br><small>on</small>' : 'GUARD')); }
      /* contextual INTERACT: only when the host offers an eligible prompt (door, quest, practice, incoming); the label is the prompt's verb */
      var gi = $('g-ctx'); if (gi) { var pr0 = (p.prompts || []).filter(function (x) { return x.eligible && /ENTER|TRANSIT|TALK|QUEST|DUEL|BROWSE|HALO_PLAY/.test(String(x.intent)); })[0] || null;   /* O3: no permanent USE — the contextual button exists only for a WORLD interaction in reach (doors, lifts, talk, quests, duels); practice / incoming fixtures live in the utility sheet */ if (pr0) { var verb = /ENTER/.test(pr0.intent) ? 'ENTER' : /TRANSIT/.test(pr0.intent) ? 'LIFT' : /TALK/.test(pr0.intent) ? 'TALK' : /QUEST/.test(pr0.intent) ? 'QUEST' : /DUEL/.test(pr0.intent) ? 'DUEL' : /HALO_PLAY/.test(pr0.intent) ? 'PLAY' : /INCOMING/.test(pr0.intent) ? 'SPAR' : 'USE'; setHtml(gi, verb + '<br><small>✦</small>'); gi.style.display = 'inline-flex'; gi.title = pr0.label; } else gi.style.display = 'none'; }
      var fo = $('g-form'); setHtml(fo, (p.form === 'SPLIT' ? 'FUSE' : 'SEPARATE') + '<small>H' + (p.transforming ? ' · changing…' : '') + '</small>'); if (fo) fo.classList.toggle('busy', !!p.transforming);
      var ib = $('g-interact'); if (ib) { var pr0 = (p.prompts || []).filter(function (x) { return x.eligible; })[0] || (p.prompts || [])[0]; setHtml(ib, 'INTERACT<small>' + esc(pr0 ? pr0.label : 'Enter · nothing nearby') + '</small>'); ib.classList.toggle('dimmed', !pr0); }
      var pb = $('g-practice'); if (r) { setHtml(pb, (r.practice ? 'PRACTICE: ON' : 'PRACTICE BATTLE') + '<small>' + (r.practice ? 'dummy takes damage' : 'enable damage on dummy') + '</small>'); pb.classList.toggle('on', !!r.practice); }
      var ab = $('g-about'); if (ab && c.about && ab.textContent !== c.about) ab.textContent = c.about;
      if (st.moreOpen) api.renderMore();
      if (st.radial.open) api.renderRadial(false);
      if (st.pendingInvite && (performance.now() - st.pendingInvite.at > 12000 || (p.paired && p.paired.id))) st.pendingInvite = null;
      var ip = $('g-invite'); if (ip) { var inv2 = p.invite; if (inv2 && inv2.from && !st.moreOpen) { ip.style.display = 'flex'; setHtml(ip, '<span>' + esc(String(inv2.from).replace(/_/g, ' ').toUpperCase()) + ' · ' + esc((emoteById(inv2.emote_id) || { name: inv2.emote_id }).name.toUpperCase()) + '</span><button class="gbtn sm gold" data-do="invite-join">JOIN</button>'); } else ip.style.display = 'none'; }
      if (st.detailSlot !== null) api.renderDetail();
    },
    renderDetail: function () { var p = st.lastP; var r = p && p.rules; var d = $('g-detail'); var s = r && (r.skills[r.me.category] || [])[st.detailSlot]; if (!s) { d.style.display = 'none'; return; } d.style.display = 'block'; var touch = document.body.classList.contains('touch');
      if (st.detailSkill !== s.id) { st.detailSkill = s.id; d.innerHTML = '<b class="dia">' + esc(s.stack && s.stack.resolved_name ? s.stack.resolved_name : s.name) + '</b> <span class="dim">' + esc(s.attack_mode_label || s.category) + (s.movement_pattern_id !== 'UNASSIGNED_PATTERN_DEV' ? ' · movement ' + esc(s.pattern_name) : '') + '</span><br><b>How:</b> ' + esc(gestureText(s, touch)) + '<br>' + esc(s.effect.replace(/_/g, ' ').toLowerCase()) + (s.mode ? ' (' + esc(String(s.mode).toLowerCase()) + ')' : '') + '<br>cost ' + (s.cost || 'none') + ' · cooldown ' + s.cooldown_s + ' s <span id="g-dcd"></span><br>wind-up ' + s.startup_s + ' s · recovery ' + s.recovery_s + ' s · range ' + s.range_m + ' m<br><span class="dim">tap = arm · ATTACK performs it</span> <button class="gbtn sm" data-do="detail-close">CLOSE</button>'; }
      var cd = $('g-dcd'); if (cd) cd.textContent = s.cooldown_remaining_s ? '(' + s.cooldown_remaining_s.toFixed(1) + ' s left)' : ''; }
  };
  return api;
}
