/* MAHWORLD PLAYABLE SAMPLE :: PRESENTATION ADAPTER (development only)
   ONE contract between the authoritative runtime snapshot and whatever renders a character. This file ships the code-generated
   TEMPORARY PREVIEW implementation: an articulated humanoid (head, neck, torso, shoulders, upper / lower arms, hands) on a fused
   MAHWORLD lower-body silhouette, with attack poses driven by the host's attack phases, category-coloured magic, contact flashes,
   floor rings, hit reactions, KO / invisible / immune / discord flags and the four-corner lock marker. It is NOT the finished Athlete:
   no Astra asset, GLB or final animation is used. A reviewed asset replaces the factory and keeps the same mount / update / remove /
   dispose surface. The adapter never simulates: visuals follow the host's published state; visual callbacks never decide damage. */
import { createRigAnimator } from './RigAnimator.js';
import { createBeamFx } from './BeamFx.js';
import { createMuscleLayer } from './MuscleLayer.js';
import { springStep } from './cameraMath.js';
var CLASS_ENERGY = { ATHLETE: 0xffc34d, TITAN: 0x4da3ff, BAGE: 0xff8fd6, VISIONARY: 0x8cff9c, LEAN: 0xff5e5e };   /* class energy palette (iris_color_by_class canon): beams + seam trace */
export var PRESENTATION_CONTRACT = {
  version: 'PRESENT_DEV_0.2.0',
  units: 'metres, seconds', axes: '+Y up; facing yaw in radians about +Y; yaw 0 faces −Z; positive yaw turns toward +X (Three.js right-handed)',
  scale: { FUSED_height_m: 1.8, SPLIT_height_m: 1.4, split_offset_m: 0.35 },
  view_state: ['position{x,y,z}', 'facing', 'form(FUSED|SPLIT)', 'mahloco(state string)', 'transforming', 'guard(PHYSICAL|MAGICAL|null)', 'guard_sheet{frac,broken}|null (the sheet integrity — owner §15)', 'dash{dir,t,dur,airborne}|null', 'flight{powered,warning,forced}', 'attack{attack_id,state,category?,progress?,profile{id,tint,style,display_name}?}|null', 'emote|null', 'health01', 'in_duel', 'label', 'self', 'ko', 'invisible', 'immune', 'discord', 'hit_ago_s', 'touch_ago_s'],
  required_clips: ['IDLE', 'WALK', 'RUN', 'DASH', 'GUARD_PHYSICAL', 'GUARD_MAGICAL', 'ATTACK_CONTACT', 'ATTACK_MANIFESTATION', 'TRANSFORM_TO_SPLIT', 'TRANSFORM_TO_FUSED', 'FLY_IDLE', 'FLY_MOVE', 'LAND', 'LAND_FORCED', 'HIT', 'KO'],
  optional_clips: ['EMOTE_WAVE', 'IDLE_VARIANT_*', 'TAUNT', 'VICTORY'],
  sockets: ['ROOT', 'HEAD', 'CHEST', 'HAND_L', 'HAND_R', 'FEET'],
  ownership: 'the adapter owns every scene object it creates; remove(id) and dispose() release geometry, materials and textures; callers never touch adapter internals',
  fallback: 'if a reviewed asset fails to load, the adapter must fall back to this preview so the sample stays playable',
  never: ['simulate', 'change facing from the camera', 'read input', 'own gameplay state', 'decide damage or timing from animation callbacks']
};
import { createDustSystem } from './dustFx.js';
export function createPresentationAdapter(THREE, scene, opts) {
  var o = opts || {}; var ents = {}; var CLASS_COLOR = { ATHLETE: 0x39c5ff, TITAN: 0xff9a3c, BAGE: 0x9cff5e, VISIONARY: 0xd08cff, LEAN: 0xfff35e };
  /* CLASS-COLOUR AUTHORITY (brief §20): every aura / MAHGIC emission of a class resolves through CLASS_ENERGY — ATHLETE = GOLD for PHYSICAL,
     PHYSICAL_MAGIC and SPECIAL_MAGIC alike. No per-category palette exists any more. */
  function energyOf(classId) { return CLASS_ENERGY[classId] || CLASS_ENERGY.ATHLETE; }
  /* soft radial glow texture shared by every sprite (aura shots, flashes, hand glows, floor light) — never a hard-edged primitive */
  var SOFT_TEX = null; function softTex() { if (SOFT_TEX) return SOFT_TEX; var c = document.createElement('canvas'); c.width = c.height = 128; var g = c.getContext('2d'); var gr = g.createRadialGradient(64, 64, 2, 64, 64, 64); gr.addColorStop(0, 'rgba(255,255,255,1)'); gr.addColorStop(0.25, 'rgba(255,255,255,0.75)'); gr.addColorStop(0.6, 'rgba(255,255,255,0.22)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 128, 128); SOFT_TEX = new THREE.CanvasTexture(c); return SOFT_TEX; }
  var STREAK_TEX = null; function streakTex() { if (STREAK_TEX) return STREAK_TEX; var c = document.createElement('canvas'); c.width = 256; c.height = 64; var g = c.getContext('2d'); var gr = g.createLinearGradient(0, 0, 256, 0); gr.addColorStop(0, 'rgba(255,255,255,0)'); gr.addColorStop(0.55, 'rgba(255,255,255,0.55)'); gr.addColorStop(0.85, 'rgba(255,255,255,1)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 256, 64); var v = g.createLinearGradient(0, 0, 0, 64); v.addColorStop(0, 'rgba(0,0,0,1)'); v.addColorStop(0.5, 'rgba(0,0,0,0)'); v.addColorStop(1, 'rgba(0,0,0,1)'); g.globalCompositeOperation = 'destination-out'; g.fillStyle = v; g.fillRect(0, 0, 256, 64); STREAK_TEX = new THREE.CanvasTexture(c); return STREAK_TEX; }
  function glowSprite(color, size, opacity) { var sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: softTex(), color: color, transparent: true, opacity: opacity === undefined ? 0.8 : opacity, depthWrite: false, blending: THREE.AdditiveBlending })); sp.scale.set(size, size, 1); return sp; }
  /* owner 2026-09-18 §15 — SHIELD = a body-silhouette protective SHEET: the guard is drawn on the character's OWN meshes (a second SkinnedMesh
     bound to the same skeleton, a child of each body mesh so it inherits the transform, morphs shared) pushed 3 cm out along the skinned normal,
     as an additive fresnel film (strong at the silhouette, faint on the facing surfaces — never an opaque bubble, never hiding the body).
     Integrity (host guard_sheet.frac) dims and flickers it; a BREAK expands and fades it in 0.35 s (no particles decide anything). */
  function sheetMaterial() { var m = new THREE.MeshStandardMaterial({ color: 0x000000, emissive: 0xdfe6ee, emissiveIntensity: 1, roughness: 1, metalness: 0, envMapIntensity: 0, transparent: true, opacity: 1, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.FrontSide });
    m.onBeforeCompile = function (sh) { sh.uniforms.uOffset = { value: 0.03 }; sh.uniforms.uPow = { value: 2.4 }; sh.uniforms.uAlpha = { value: 0.75 }; sh.uniforms.uFill = { value: 0.08 }; sh.uniforms.uT = { value: 0 }; m.userData.shader = sh;
      sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nuniform float uOffset; varying float vWy;').replace('#include <skinning_vertex>', '#include <skinning_vertex>\ntransformed += objectNormal * uOffset;').replace('#include <worldpos_vertex>', '#include <worldpos_vertex>\nvWy = (modelMatrix * vec4(transformed, 1.0)).y;');
      sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nuniform float uPow; uniform float uAlpha; uniform float uFill; uniform float uT; varying float vWy;').replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n{ float fres = pow(1.0 - clamp(abs(dot(normalize(vNormal), normalize(vViewPosition))), 0.0, 1.0), uPow); float band = 0.85 + 0.15 * sin(vWy * 9.0 - uT * 2.2); totalEmissiveRadiance = emissive * (uFill + fres * 1.5) * band; diffuseColor.a = clamp(uFill * 0.6 + fres, 0.0, 1.0) * uAlpha; }'); };
    m.customProgramCacheKey = function () { return 'mahworld_guard_sheet'; }; return m; }
  function buildSheet(e) { if (e.sheet.built) return; e.sheet.built = true; var mat = e.sheet.mat; var group = e.fused && e.fused.group; if (!group) return; var targets = []; group.traverse(function (o) { if ((o.isSkinnedMesh || o.isMesh) && !o.userData.guardSheet && !o.isSprite && o.geometry && o.geometry.attributes && o.geometry.attributes.position && o.geometry.attributes.position.count > 200 && !(o.material && o.material.transparent && o.material.opacity < 0.5)) targets.push(o); });
    targets.forEach(function (o) { var sm; if (o.isSkinnedMesh) { sm = new THREE.SkinnedMesh(o.geometry, mat); sm.bindMode = o.bindMode; sm.bind(o.skeleton, o.bindMatrix); } else { sm = new THREE.Mesh(o.geometry, mat); } sm.userData.guardSheet = true; sm.frustumCulled = false; sm.castShadow = false; sm.receiveShadow = false; sm.renderOrder = (o.renderOrder || 0) + 1; sm.visible = false; if (o.morphTargetInfluences) { sm.morphTargetInfluences = o.morphTargetInfluences; sm.morphTargetDictionary = o.morphTargetDictionary; } o.add(sm); e.sheet.meshes.push(sm); }); }
  function mat(color, extra) { return new THREE.MeshStandardMaterial(Object.assign({ color: color, roughness: 0.5, metalness: 0.25 }, extra || {})); }
  function labelSprite(text, color, w) { var c = document.createElement('canvas'); c.width = 512; c.height = 64; var g = c.getContext('2d'); g.font = 'bold 26px system-ui, sans-serif'; var tw = Math.min(500, g.measureText(text).width + 24); g.fillStyle = 'rgba(8,12,20,0.6)'; g.beginPath(); g.roundRect(256 - tw / 2, 12, tw, 40, 8); g.fill(); g.fillStyle = color || '#e8f4ff'; g.textAlign = 'center'; g.fillText(text, 256, 40); var tx = new THREE.CanvasTexture(c); var sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: tx, depthTest: false, transparent: true })); sp.scale.set(w || 2.6, 0.325, 1); sp.userData.tex = tx; return sp; }   /* background only behind the text (measured), not a full-width box */
  /* articulated preview humanoid — returns { group, parts } ; heights in metres for a 1.8 m fused body */
  function humanoid(color, h, fused) { var k = h / 1.8; var g = new THREE.Group(); var skin = mat(0xe9d4c0, { roughness: 0.6 }); var suit = mat(color, { roughness: 0.45, metalness: 0.35 }); var dark = mat(0x1a2230, { roughness: 0.6, metalness: 0.4 });
    var lower = new THREE.Mesh(fused ? new THREE.CylinderGeometry(0.16 * k, 0.30 * k, 0.86 * k, 14) : new THREE.CapsuleGeometry(0.2 * k, 0.5 * k, 4, 10), fused ? dark : suit); lower.position.y = 0.45 * k; g.add(lower);   /* fused lower-body silhouette (tapered single support) */
    if (fused) { var fin = new THREE.Mesh(new THREE.ConeGeometry(0.32 * k, 0.2 * k, 14), suit); fin.position.y = 0.92 * k; fin.rotation.x = Math.PI; g.add(fin); var ring = new THREE.Mesh(new THREE.TorusGeometry(0.22 * k, 0.03 * k, 8, 24), mat(0x9fd0ff, { emissive: 0x3388ff, emissiveIntensity: 0.9 })); ring.rotation.x = Math.PI / 2; ring.position.y = 0.2 * k; g.add(ring); }
    var torso = new THREE.Group(); torso.position.y = 0.95 * k; g.add(torso); var chest = new THREE.Mesh(new THREE.BoxGeometry(0.46 * k, 0.5 * k, 0.26 * k), suit); chest.position.y = 0.25 * k; torso.add(chest); var emblem = new THREE.Mesh(new THREE.CircleGeometry(0.07 * k, 16), mat(0xffffff, { emissive: color, emissiveIntensity: 1.2 })); emblem.position.set(0, 0.3 * k, -0.135 * k); torso.add(emblem);
    var neck = new THREE.Mesh(new THREE.CylinderGeometry(0.06 * k, 0.07 * k, 0.1 * k, 10), skin); neck.position.y = 0.55 * k; torso.add(neck); var headG = new THREE.Group(); headG.position.y = 0.72 * k; torso.add(headG); var head = new THREE.Mesh(new THREE.SphereGeometry(0.15 * k, 16, 12), skin); headG.add(head); var visor = new THREE.Mesh(new THREE.BoxGeometry(0.2 * k, 0.05 * k, 0.05 * k), mat(0x101820, { emissive: color, emissiveIntensity: 0.7 })); visor.position.set(0, 0.02 * k, -0.13 * k); headG.add(visor);
    var arms = {}; [['L', -1], ['R', 1]].forEach(function (side) { var sgn = side[1]; var shoulder = new THREE.Group(); shoulder.position.set(sgn * 0.3 * k, 0.45 * k, 0); torso.add(shoulder); var cap = new THREE.Mesh(new THREE.SphereGeometry(0.09 * k, 10, 8), suit); shoulder.add(cap); var upper = new THREE.Mesh(new THREE.CapsuleGeometry(0.06 * k, 0.26 * k, 4, 8), suit); upper.position.y = -0.18 * k; shoulder.add(upper); var elbow = new THREE.Group(); elbow.position.y = -0.36 * k; shoulder.add(elbow); var fore = new THREE.Mesh(new THREE.CapsuleGeometry(0.055 * k, 0.24 * k, 4, 8), skin); fore.position.y = -0.16 * k; elbow.add(fore); var hand = new THREE.Mesh(new THREE.SphereGeometry(0.07 * k, 10, 8), skin); hand.position.y = -0.34 * k; elbow.add(hand); var glow = new THREE.Mesh(new THREE.SphereGeometry(0.16 * k, 12, 10), new THREE.MeshBasicMaterial({ color: 0x9fd0ff, transparent: true, opacity: 0 })); glow.position.y = -0.34 * k; elbow.add(glow); arms[side[0]] = { shoulder: shoulder, elbow: elbow, hand: hand, glow: glow }; });
    return { group: g, parts: { torso: torso, head: headG, arms: arms, lower: lower }, sockets: { ROOT: g, HEAD: headG, CHEST: torso, HAND_L: arms.L.hand, HAND_R: arms.R.hand, FEET: lower } }; }
  var STYLE_AMP = { HEAVY: 1.3, QUICK: 0.8, FLOW: 1.0, PRECISE: 0.9, BALANCED: 1.0 };   /* class presentation profiles: cosmetic amplitude / timing only (no gameplay effect) */
  var STRIKE_TIMING = { QUICK: { release: 0.13, recover: 0.32 }, HEAVY: { release: 0.24, recover: 0.62 }, PRECISE: { release: 0.17, recover: 0.46 }, FLOW: { release: 0.21, recover: 0.56 }, BALANCED: { release: 0.18, recover: 0.5 } };   /* fallback preview only; skinned exercise rigs use RigAnimator's progress envelopes */
  function pose(fig, name, t, p, style) { /* p = phase progress 0..1 ; poses are presentation only */ var A = fig.parts.arms, T = fig.parts.torso; var ease = function (x) { return x < 0.5 ? 2 * x * x : 1 - Math.pow(-2 * x + 2, 2) / 2; }; var amp = STYLE_AMP[style] || 1; var pe = ease;
    var restL = { sx: 0.15, sz: 0.1, ex: -0.35 }, restR = { sx: 0.15, sz: -0.1, ex: -0.35 }; var set = function (arm, sx, sz, ex) { arm.shoulder.rotation.x = sx; arm.shoulder.rotation.z = sz; arm.elbow.rotation.x = ex; };
    T.rotation.set(0, 0, 0); fig.parts.head.rotation.set(0, 0, 0);
    if (name === 'STRIKE_STARTUP') { var q = ease(p); set(A.R, 0.6 * q * amp, -0.2, -1.8 * q); set(A.L, -0.3 * q, 0.25 * amp, -0.6); T.rotation.y = 0.5 * q * amp; T.rotation.x = 0.08 * q * amp; if (style === 'PRECISE') fig.parts.head.rotation.y = -0.2 * q; if (style === 'FLOW') T.rotation.z = 0.08 * q; }   /* anticipation: chamber the striking arm, wind the torso, plant */
    else if (name === 'STRIKE_RELEASE') { var drive = ease(Math.min(1, p / (style === 'QUICK' ? 0.3 : 0.4))), hold = 1 - ease(Math.max(0, (p - 0.68) / 0.32)), q2 = drive * hold; set(A.R, -1.48 * q2 + 0.58 * (1 - q2), -0.15, -0.18); set(A.L, 0.2, 0.3, -0.82); T.rotation.y = (0.48 - 0.96 * q2) * amp; T.rotation.x = -0.1 * q2 * amp; }   /* broader drive, readable impact hold, clean tail — host timing remains authoritative */
    else if (name === 'STRIKE_RECOVER') { var q3 = ease(p); set(A.R, -1.4 * (1 - q3) + 0.15 * q3, -0.1, -0.35 * q3 - 0.15 * (1 - q3)); set(A.L, 0.15, 0.1, -0.35); T.rotation.y = -0.5 * (1 - q3); T.rotation.x = -0.12 * (1 - q3); }
    else if (name === 'CAST_STARTUP') { var q4 = ease(p); set(A.R, -1.1 * q4, -0.35 * amp, -0.5); set(A.L, -1.1 * q4, 0.35 * amp, -0.5); T.rotation.x = 0.1 * q4; fig.parts.head.rotation.x = -0.15 * q4; if (style === 'FLOW') { A.R.shoulder.rotation.z -= 0.35 * q4; A.L.shoulder.rotation.z += 0.35 * q4; } }   /* readable cast pose: both hands gather in front of the chest */
    else if (name === 'CAST_RELEASE') { set(A.R, -1.5, -0.2, -0.1); set(A.L, -1.5, 0.2, -0.1); T.rotation.x = -0.08; }
    else if (name === 'GUARD_PHYSICAL') { set(A.R, -0.9, -0.5, -2.0); set(A.L, -0.9, 0.5, -2.0); T.rotation.x = 0.12; }
    else if (name === 'GUARD_MAGICAL') { set(A.R, -1.3, -0.9, -0.4); set(A.L, -1.3, 0.9, -0.4); }
    else if (name === 'FLY') { set(A.R, 0.4, -0.5, -0.2); set(A.L, 0.4, 0.5, -0.2); T.rotation.x = 0.35; }
    else if (name === 'HIT') { var q5 = 1 - ease(p); set(A.R, 0.4 * q5, -0.4, -0.9); set(A.L, 0.4 * q5, 0.4, -0.9); T.rotation.x = -0.35 * q5; fig.parts.head.rotation.x = -0.25 * q5; }
    else if (name === 'WAVE') { set(A.R, -2.6, -0.3 + 0.3 * Math.sin(t * 10), -0.3); set(A.L, restL.sx, restL.sz, restL.ex); }
    else { var b = Math.sin(t * 2.2) * 0.05; set(A.R, restR.sx + b, restR.sz, restR.ex); set(A.L, restL.sx - b, restL.sz, restL.ex); T.rotation.x = 0.02 * Math.sin(t * 2.2); } }
  var rigsAnimated = 0; var TURN = { hz: 1.6, cap_dps: 800, snap_hz: 5, snap_cap_dps: 1800 };   /* 1.6 Hz critically damped: a 180° turn peaks at ≈ 660 °/s (below the 800 cap, so the spring shapes the turn: ease-in, ease-out), settles in ≈ 0.45 s */   /* displayed turn spring (PASS 2b); live in the Control Lab (MOTION group) */
  var qualityRef = o.quality || null; var dust = createDustSystem(THREE, { scene: scene, quality: qualityRef, max_live: 14 }); var DV1 = new THREE.Vector3(), DV2 = new THREE.Vector3();   /* granular crystalline dust (owner 2026-09-18 §8): GATHER on physical-MAHGIC limbs, WAVE at special projectiles, CURTAIN over aimed areas, BURST at terminals */ function particleN(n) { var T = qualityRef && qualityRef.get ? qualityRef.get() : null; return T ? Math.max(3, Math.round(n * (T.particles || 1))) : n; }   /* Spec A tier budget */
  /* Spec A effect recycling: a finished point set goes back to a pool keyed by its count instead of being disposed — the next burst of the
     same size reuses the geometry + material (no GPU re-upload, no program lookup on a fresh material). Positions and opacity are reset,
     velocities re-rolled, so the burst looks exactly as a fresh one. */
  var PTS_POOL = {}; var PTS_POOL_MAX = 8;
  function handObject(e, bone) { var rig = e.fused && e.fused.rig; var b = rig && rig.bones && rig.bones[bone]; if (b) return b; var side = /_L$/.test(String(bone || '')) ? 'L' : 'R'; return e.parts && e.parts.arms && e.parts.arms[side] ? e.parts.arms[side].hand : null; }
  function socketWorld(e, bone, outPos, outQuat, outScale) { var b = handObject(e, bone); if (!b) return null; b.updateWorldMatrix(true, false); if (outPos) { b.getWorldPosition(outPos); var rig = e.fused && e.fused.rig, side = /_L$/.test(String(bone || '')) ? 'L' : 'R', finger = rig && rig.bones && rig.bones['FINGERS_' + side]; if (finger) { finger.updateWorldMatrix(true, false); finger.getWorldPosition(DV2); outPos.lerp(DV2, 0.38); } } if (outQuat) b.getWorldQuaternion(outQuat); if (outScale) b.getWorldScale(outScale); return b; }
  function handWorld(e, bone, out) { var b = handObject(e, bone); if (!b) return null; b.updateWorldMatrix(true, false); b.getWorldPosition(out); return out; }   /* VFX retains the hand-joint anchor; equipment sockets use the source rig's hand→finger span to land at the visible palm centre. */
  function releaseParticles(ps) { var n = ps.vel.length; var arr = PTS_POOL[n] = PTS_POOL[n] || []; if (arr.length >= PTS_POOL_MAX) { ps.pts.geometry.dispose(); ps.pts.material.dispose(); return; } ps.pts.visible = false; arr.push(ps); }
  function spawnParticles(root, color, n, spread, life) { n = particleN(n); var ps = PTS_POOL[n] && PTS_POOL[n].length ? PTS_POOL[n].pop() : null; var pts, vel, pos;
    if (ps) { pts = ps.pts; vel = ps.vel; pos = pts.geometry.attributes.position.array; pts.material.color.set(color); pts.material.size = 0.12; pts.material.opacity = 0.95; pts.visible = true; pts.position.set(0, 0, 0); pts.rotation.set(0, 0, 0); }
    else { var geo = new THREE.BufferGeometry(); pos = new Float32Array(n * 3); vel = []; for (var k = 0; k < n; k++) vel.push({ x: 0, y: 0, z: 0 }); geo.setAttribute('position', new THREE.BufferAttribute(pos, 3)); geo.attributes.position.setUsage(THREE.DynamicDrawUsage); pts = new THREE.Points(geo, new THREE.PointsMaterial({ color: color, size: 0.12, transparent: true, opacity: 0.95, depthWrite: false })); pts.frustumCulled = false; }
    for (var i = 0; i < n; i++) { pos[i * 3] = 0; pos[i * 3 + 1] = 0; pos[i * 3 + 2] = 0; vel[i].x = (Math.random() - 0.5) * spread; vel[i].y = Math.random() * spread * 0.8; vel[i].z = (Math.random() - 0.5) * spread; } pts.geometry.attributes.position.needsUpdate = true; root.add(pts); return { pts: pts, vel: vel, life: life, t: 0 }; }
  /* Spec A effect roots: PROJECTILE / ZONE / IMPACT roots are recycled by kind + radius + class colour — a strike or a cast no longer builds
     five fresh materials and geometries (the first draw of a fresh set cost ~35 ms in the headless harness, every strike). remove() parks the
     root (particles released to their pool, label sprite dropped); the next mount of the same key re-dresses it: colours, opacities, scales, t. */
  var FX_POOL = {}; var FX_POOL_MAX = 6;
  function fxKey(d) { return d.kind + '|' + (d.kind === 'PROJECTILE' ? '' : (d.radius || 1)) + '|' + (d.class_id || '') + '|' + (GEAR_FORM[d.formation] || d.formation === 'CLAMP' ? d.formation : ''); }   /* B8 §12: the gear formations carry their own geometry, so they pool apart */
  function releaseEffect(e) { var key = e.poolKey; var arr = FX_POOL[key] = FX_POOL[key] || []; if (e.dustFx) { if (e.kind === 'PROJECTILE') dust.scatter(e.dustFx, e.lastHead, Math.sin(-e.root.rotation.y), -Math.cos(-e.root.rotation.y), 2.4); else dust.stop(e.dustFx); e.dustFx = null; }   /* terminal: stop emission, throw the live grains, they dissipate in ≤ 0.4 s — nothing travels on */ (e.particles || []).forEach(function (ps) { e.root.remove(ps.pts); releaseParticles(ps); }); if (e.particles) e.particles = []; if (e.wake) { e.root.remove(e.wake.pts); releaseParticles(e.wake); e.wake = null; } if (e.label) { e.root.remove(e.label); if (e.label.userData.tex) e.label.userData.tex.dispose(); e.label.material.dispose(); e.label = null; } if (arr.length >= FX_POOL_MAX) return false; arr.push(e); return true; }
  /* ---- B8 §12 GEAR FORMATIONS (owner-authorized specials of the floating equipment) ----
     X_WAVE = the two crossed dumbbells release a moving X-shaped granular blade: two crossed blade ribbons standing in the plane that faces the
     target (±45°), a tight core, the dust WAVE in the 'x' shape. PLATE_SHOT = a barbell plate flies end-on: a dark disc with a class-energy rim,
     spinning about the travel axis; while the second plate is still ARMED (launch_in_s > 0) it hovers at the bar and its rim pulses = the telegraph.
     CLAMP = an IMPACT on the locked target: two dumbbell-silhouette protection sheets close from the sides and shatter (the BURST). */
  var GEAR_FORM = { X_WAVE: 1, PLATE_SHOT: 1, PRESS_THROW: 1 };
  function dumbbellSheetTex() { if (dumbbellSheetTex.t) return dumbbellSheetTex.t; var c = document.createElement('canvas'); c.width = 256; c.height = 128; var g = c.getContext('2d'); g.clearRect(0, 0, 256, 128); var gr = g.createLinearGradient(0, 0, 0, 128); gr.addColorStop(0, 'rgba(255,255,255,0)'); gr.addColorStop(0.5, 'rgba(255,255,255,0.9)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(96, 44, 64, 40);   /* the handle */ [[36, 20, 44, 88], [176, 20, 44, 88], [24, 30, 12, 68], [220, 30, 12, 68]].forEach(function (r) { var gg = g.createLinearGradient(r[0], 0, r[0] + r[2], 0); gg.addColorStop(0, 'rgba(255,255,255,0.15)'); gg.addColorStop(0.5, 'rgba(255,255,255,0.95)'); gg.addColorStop(1, 'rgba(255,255,255,0.15)'); g.fillStyle = gg; g.fillRect(r[0], r[1], r[2], r[3]); });   /* the plates */ dumbbellSheetTex.t = new THREE.CanvasTexture(c); dumbbellSheetTex.t.colorSpace = THREE.SRGBColorSpace; return dumbbellSheetTex.t; }
  function mountGearProjectile(root, d, id) { var col = energyOf(d.class_id); var e = { kind: 'PROJECTILE', gear: d.formation, root: root, t: 0, dustFx: null, lastHead: new THREE.Vector3(), poolKey: fxKey(d), parts: [], core: null, halo: null, ribs: [], wake: null };
    if (d.formation === 'X_WAVE') { var core = glowSprite(0xffffff, 0.24, 0.95); core.material.color.setHex(col).lerp(new THREE.Color(0xffffff), 0.55); root.add(core); e.core = core; var bm = new THREE.MeshBasicMaterial({ map: streakTex(), color: col, transparent: true, opacity: 0.9, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide }); var b1 = new THREE.Mesh(new THREE.PlaneGeometry(1.5, 0.16), bm); b1.rotation.z = Math.PI / 4; root.add(b1); var b2 = new THREE.Mesh(new THREE.PlaneGeometry(1.5, 0.16), bm.clone()); b2.rotation.z = -Math.PI / 4; root.add(b2);   /* the blades stand in the plane facing the travel (local XY), crossed at ±45° = the X */ e.parts = [b1, b2]; e.dustFx = dust.emit('WAVE', { color: col, count: 280, width: 0.72, rate: 900, size: 0.15, shape: 'x' }); }
    else if (d.formation === 'PLATE_SHOT') { var plate = new THREE.Group(); var disc = new THREE.Mesh(new THREE.CircleGeometry(0.23, 28), new THREE.MeshStandardMaterial({ color: 0x1a1f26, roughness: 0.45, metalness: 0.8, side: THREE.DoubleSide })); plate.add(disc); var rimP = new THREE.Mesh(new THREE.RingGeometry(0.2, 0.25, 32), new THREE.MeshBasicMaterial({ color: col, transparent: true, opacity: 0.95, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide })); rimP.position.z = 0.005; plate.add(rimP); var hub = new THREE.Mesh(new THREE.RingGeometry(0.03, 0.06, 16), rimP.material); hub.position.z = 0.006; plate.add(hub); root.add(plate); e.plate = plate; e.rim = rimP; var halo = glowSprite(col, 0.5, 0.25); root.add(halo); e.halo = halo; e.dustFx = dust.emit('WAVE', { color: col, count: 150, width: 0.24, rate: 520, size: 0.12, shape: 'ring' }); }
    else return null;
    ents[id] = e; scene.add(root); return root; }
  function updateGearProjectile(e, v, dt) { e.root.position.set(v.position.x, v.position.y || 1.1, v.position.z); e.root.rotation.y = -(v.heading || 0); var armed = typeof v.launch_in_s === 'number' && v.launch_in_s > 0;
    if (e.gear === 'X_WAVE') { var pz = 1 + 0.1 * Math.sin(e.t * 24); if (e.core) e.core.scale.set(0.5 * pz, 0.5 * pz, 1); e.parts.forEach(function (b, i) { b.material.opacity = 0.8 - 0.15 * Math.sin(e.t * 19 + i); b.scale.set(1, 1 + 0.25 * Math.sin(e.t * 13 + i * 1.6), 1); }); }
    else if (e.gear === 'PLATE_SHOT') { e.plate.visible = true; if (armed) { e.plate.rotation.y = Math.PI / 2 * Math.min(1, (0.6 - Math.min(0.6, v.launch_in_s)) / 0.6);   /* the bar turns: the plate swings from side-on to END-ON during the telegraph */ e.plate.rotation.z = 0; e.rim.material.opacity = 0.35 + 0.6 * Math.abs(Math.sin(e.t * 9)); if (e.halo) { e.halo.material.opacity = 0.18 + 0.2 * Math.abs(Math.sin(e.t * 9)); e.halo.scale.set(0.5, 0.5, 1); } return; }   /* ARMED: hovering at the bar, the rim pulses = the telegraph; no wave dust until it leaves */ e.plate.rotation.y = 0; e.plate.rotation.z += dt * 14; e.rim.material.opacity = 0.95; if (e.halo) { e.halo.material.opacity = 0.3; e.halo.scale.set(0.6, 0.6, 1); } }
    if (e.dustFx) { e.lastHead.copy(e.root.position); dust.wave(e.dustFx, e.root.position, v.heading || 0); } }
  function mountClampSheets(root, zc) { var tex = dumbbellSheetTex(); var mk = function (side) { var m = new THREE.Mesh(new THREE.PlaneGeometry(1.1, 0.55), new THREE.MeshBasicMaterial({ map: tex, color: zc, transparent: true, opacity: 0.85, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide })); m.position.set(side * 1.15, 1.05, 0); m.rotation.y = side * Math.PI / 2; m.userData.side = side; root.add(m); return m; }; return { sheets: [mk(-1), mk(1)], shattered: false }; }
  function updateClampSheets(e, v) { var C = e.clamp; var k = Math.min(1, e.t / 0.22); var ease = 1 - Math.pow(1 - k, 3); C.sheets.forEach(function (m) { m.position.x = m.userData.side * (1.15 - 1.0 * ease); m.material.opacity = k < 1 ? 0.85 : Math.max(0, 0.85 - (e.t - 0.22) / 0.2); m.visible = m.material.opacity > 0.02; }); if (k >= 1 && !C.shattered) { C.shattered = true; dust.emit('BURST', { color: energyOf(e.classId), count: 120, x: v.position.x, y: 1.05, z: v.position.z, speed: 3.8 }); } }   /* the sheets close around the target over 0.22 s (mirroring the adduction), meet, and SHATTER */
  function redressEffect(e, d, id) { var zc = energyOf(d.class_id); e.t = 0; e.root.position.set(0, 0, 0); e.root.rotation.set(0, 0, 0);
    if (e.kind === 'PROJECTILE' && e.gear) { if (e.core) { e.core.scale.set(0.5, 0.5, 1); e.core.material.opacity = 0.95; } if (e.rim) e.rim.material.opacity = 0.95; return; }
    if (e.kind === 'PROJECTILE') { e.core.scale.set(0.42, 0.42, 1); e.core.material.opacity = 0.95; e.core.material.color.setHex(zc).lerp(new THREE.Color(0xffffff), 0.45); e.halo.scale.set(0.9, 0.9, 1); e.halo.material.opacity = 0.35; e.halo.material.color.setHex(zc); e.ribs[0].material.opacity = 0.85; e.ribs[0].material.color.setHex(zc); e.wake = spawnParticles(e.root, zc, 10, 0.6, 1.2); e.wake.pts.material.size = 0.07; e.wake.pts.material.opacity = 0.5; return; }
    e.rim.rotation.z = 0; e.rim.scale.setScalar(1); e.rim.material.opacity = e.kind === 'ZONE' ? 0.35 : 0.0; e.rim.material.color.setHex(zc); e.disc.material.opacity = 0.22; e.disc.material.color.setHex(zc); e.harmless = !!d.harmless;
    if (e.kind === 'IMPACT') { e.crit = d.cause === 'CRITICAL'; e.flash.scale.set(1.1, 1.1, 1); e.flash.material.opacity = 0.95; e.flash.material.color.setHex(zc).lerp(new THREE.Color(0xffffff), 0.5); e.spread.scale.set(0.4, 0.4, 1); e.spread.material.opacity = 0.55; e.spread.material.color.setHex(zc); e.particles = [spawnParticles(e.root, zc, d.harmless ? 10 : 22, 3.5, 0.5)]; e.particles[0].pts.position.y = 1.0; }
    else { var zl = labelSprite(d.label || id, '#d9c7ff', 2.4); zl.position.y = 1.0; e.root.add(zl); e.label = zl; } }
  function stepParticles(e, dt) { if (!e.particles) return; e.particles = e.particles.filter(function (ps) { ps.t += dt; var arr = ps.pts.geometry.attributes.position.array; for (var i = 0; i < ps.vel.length; i++) { arr[i * 3] += ps.vel[i].x * dt; arr[i * 3 + 1] += ps.vel[i].y * dt - 2.5 * dt * ps.t; arr[i * 3 + 2] += ps.vel[i].z * dt; } ps.pts.geometry.attributes.position.needsUpdate = true; ps.pts.material.opacity = Math.max(0, 1 - ps.t / ps.life); if (ps.t >= ps.life) { e.root.remove(ps.pts); releaseParticles(ps); return false; } return true; }); }
  /* RIGID figure support (development character preview from a GLB with no rig): whole-body procedural motion only - the root leans, twists, lunges, rises and recoils; limbs and legs cannot articulate. Reported honestly through capabilities(). */
  function rigidPose(f, e, name, t, p, style) { var g = f.group; var ease = function (x) { return x < 0.5 ? 2 * x * x : 1 - Math.pow(-2 * x + 2, 2) / 2; }; var amp = STYLE_AMP[style] || 1; g.rotation.set(0, 0, 0); g.position.set(0, 0, 0);
    if (name === 'STRIKE_STARTUP') { var q = ease(p); g.rotation.y = 0.38 * q * amp; g.rotation.x = 0.06 * q; g.position.z = 0.06 * q; }
    else if (name === 'STRIKE_RELEASE') { var q2 = ease(Math.min(1, p * (style === 'QUICK' ? 3 : 2.2))); g.rotation.y = (0.38 - 0.85 * q2) * amp; g.rotation.x = -0.16 * q2 * amp; g.position.z = -0.28 * q2 * amp; }
    else if (name === 'STRIKE_RECOVER') { var q3 = ease(p); g.rotation.y = -0.47 * amp * (1 - q3); g.rotation.x = -0.16 * amp * (1 - q3); g.position.z = -0.28 * amp * (1 - q3); }
    else if (name === 'CAST_STARTUP') { var q4 = ease(p); g.position.y = 0.1 * q4; g.rotation.x = 0.07 * q4; }
    else if (name === 'CAST_RELEASE') { g.position.y = 0.06; g.position.z = -0.1; g.rotation.x = -0.05; }
    else if (name === 'GUARD_PHYSICAL') { g.rotation.x = 0.13; g.position.y = -0.05; }
    else if (name === 'GUARD_MAGICAL') { g.position.y = 0.05; g.rotation.x = -0.04; }
    else if (name === 'FLY') { g.rotation.x = 0.12; }
    else if (name === 'HIT') { var q5 = 1 - ease(p); g.rotation.x = -0.28 * q5; g.position.z = 0.16 * q5; }
    else if (name === 'WAVE') { g.rotation.z = 0.08 * Math.sin(t * 8); }
    else { g.rotation.x = 0.015 * Math.sin(t * 2.2); g.position.y = 0.01 * Math.sin(t * 2.2); } }
  var lastCaps = null; var DEF = o.defaults || {};
  /* effects that depend on the viewer: the fingertip trail disappears beyond rig_profile.fingertip_trail.visible_max_m */
 var beamFx = o.beams !== false ? createBeamFx(THREE, scene, Object.assign({ pulse_s: (DEF.gait && DEF.gait.support_pulse_s) || 0.22, camera: o.camera || null }, DEF.beams || {})) : null;
  if (beamFx && beamFx.setCamera && o.camera) beamFx.setCamera(o.camera); var snd = o.sound || null; var groundAt = o.groundAt || function () { return 0; }; var _a = new THREE.Vector3(), _b = new THREE.Vector3(), _c = new THREE.Vector3(), _d = new THREE.Vector3();
  var _e = new THREE.Vector3(), _f = new THREE.Vector3(), _g = new THREE.Vector3(), _h = new THREE.Vector3(), _i = new THREE.Vector3(), _j = new THREE.Vector3(), _k = new THREE.Vector3(), _l = new THREE.Vector3();
  var api = {
    /* DEV ONLY (stills / inspection): freeze one entity's animator so a transient pose can be photographed; the host keeps running */
    holdPose: function (id, on) { var e = ents[id]; if (!e) return false; e.holdPose = !!on; return true; },
    contract: PRESENTATION_CONTRACT, implementation: o.implementation || 'TEMPORARY PREVIEW (code-generated articulated humanoid, fused lower body)', capabilities: function () { return o.characterFactory ? (lastCaps && lastCaps.skinned ? { figure: lastCaps.v2 ? 'SKINNED_GLB_DERIVATIVE_RIG_V2' : 'SKINNED_GLB_DERIVATIVE_RIG', limbs: true, joints: lastCaps.joints, legs_separate: !!lastCaps.split_legs, packed_morph: !!lastCaps.packed_morph, face_bones: lastCaps.face_bones || [], finger_bones: lastCaps.finger_bones || [], morphs: !!lastCaps.packed_morph, eyes: lastCaps.emissive_eyes ? 'K3_EMISSIVE_MASK (blink via uniform; no lid geometry)' : false, beams: !!beamFx, clips: [] } : { figure: 'RIGID_GLB', limbs: false, legs_separate: false, morphs: false, clips: [] }) : { figure: 'ARTICULATED_STANDIN', limbs: true, legs_separate: 'silhouette only', morphs: false, clips: [] }; },
    mount: function (id, desc) {
      if (ents[id]) api.remove(id); var d = desc || {}; var root = new THREE.Group(); root.name = 'ent:' + id;
      if (d.kind === 'TARGET') { var body = new THREE.Mesh(new THREE.CapsuleGeometry(0.45, 1.0, 4, 10), mat(0xc84b4b, { emissive: 0x3a0d0d })); body.position.y = 1.0; root.add(body); var lbl = labelSprite(d.label || id, '#ffb3b3'); lbl.position.y = 2.55; root.add(lbl); ents[id] = { kind: 'TARGET', root: root, label: lbl, t: 0 }; scene.add(root); return root; }
      if ((d.kind === 'PROJECTILE' || d.kind === 'ZONE' || d.kind === 'IMPACT') && FX_POOL[fxKey(d)] && FX_POOL[fxKey(d)].length) { var re = FX_POOL[fxKey(d)].pop(); redressEffect(re, d, id); re.dustDone = false; re.classId = d.class_id; re.formation = d.formation || null; re.category = d.category || null; re.radius = d.radius || 1; re.curtainStop = undefined; if (re.kind === 'PROJECTILE' && re.gear) { re.dustFx = re.gear === 'X_WAVE' ? dust.emit('WAVE', { color: energyOf(d.class_id), count: 280, width: 0.72, rate: 900, size: 0.15, shape: 'x' }) : dust.emit('WAVE', { color: energyOf(d.class_id), count: 150, width: 0.24, rate: 520, size: 0.12, shape: 'ring' }); } else if (re.kind === 'PROJECTILE') { re.dustFx = (d.formation === 'WAVE' || d.category === 'SPECIAL_MAGIC') ? dust.emit('WAVE', { color: energyOf(d.class_id), count: 240, width: 0.8, rate: 900, size: 0.16 }) : null; if (re.halo) re.halo.scale.set(0.42, 0.42, 1); } if (re.clamp) { re.clamp.shattered = false; re.clamp.sheets.forEach(function (m) { m.visible = true; m.material.opacity = 0.85; m.position.x = m.userData.side * 1.15; }); } if (re.spread) re.spread.visible = true; ents[id] = re; scene.add(re.root); return re.root; }   /* Spec A: recycled effect (see releaseEffect) */
      if (d.kind === 'PROJECTILE' && GEAR_FORM[d.formation]) { var gp = mountGearProjectile(root, d, id); if (gp) return gp; }
      if (d.kind === 'PROJECTILE') { /* MAHGIC RELEASE: a directed energy streak in the caster's class colour — a bright soft core, two crossed gradient ribbons trailing behind it, and a faint wake of soft points. No sphere, no cone. */
        var col = energyOf(d.class_id); var core = glowSprite(0xffffff, 0.2, 0.95); core.material.color.setHex(col).lerp(new THREE.Color(0xffffff), 0.45); root.add(core); var halo = glowSprite(col, 0.42, 0.22); root.add(halo);   /* §8: a tight kernel, not a smooth ball — the readable mass is the granular WAVE front */
        var ribM = new THREE.MeshBasicMaterial({ map: streakTex(), color: col, transparent: true, opacity: 0.85, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide }); var rib1 = new THREE.Mesh(new THREE.PlaneGeometry(1.4, 0.14), ribM); rib1.rotation.y = -Math.PI / 2; rib1.position.z = 0.75; root.add(rib1); var rib2 = rib1.clone(); rib2.rotation.x = Math.PI / 2; rib2.rotation.y = -Math.PI / 2; root.add(rib2);
        var fmS = d.formation === 'LANCE' ? 'rod' : (d.formation === 'CLAP' ? 'ring' : 'crescent'); var waveFx = (d.formation === 'WAVE' || d.formation === 'LANCE' || d.formation === 'CLAP' || d.category === 'SPECIAL_MAGIC') ? dust.emit('WAVE', { color: col, count: fmS === 'rod' ? 200 : 260, width: fmS === 'rod' ? 0.10 : (fmS === 'ring' ? 0.55 : 0.8), rate: fmS === 'rod' ? 700 : 900, size: fmS === 'rod' ? 0.13 : 0.16, shape: fmS }) : null; if (fmS === 'ring') { rib1.visible = false; rib2.visible = false; } if (fmS === 'rod') { rib1.scale.set(1.6, 0.7, 1); rib2.scale.set(1.6, 0.7, 1); }   /* phase E formations: LANCE = a dense rod behind a thin kernel (the arm-to-fingertip release), CLAP = a flat ring with no ribbons */ ents[id] = { kind: 'PROJECTILE', root: root, t: 0, core: core, halo: halo, ribs: [rib1, rib2], wake: null, dustFx: waveFx, fmS: fmS, lastHead: new THREE.Vector3(), poolKey: fxKey(d) }; scene.add(root); return root; }
      if (d.kind === 'ZONE' || d.kind === 'IMPACT') { var rr = d.radius || 1; var zc = energyOf(d.class_id); var disc = new THREE.Mesh(new THREE.PlaneGeometry(rr * 2.4, rr * 2.4), new THREE.MeshBasicMaterial({ map: softTex(), color: zc, transparent: true, opacity: 0.22, depthWrite: false, blending: THREE.AdditiveBlending })); disc.rotation.x = -Math.PI / 2; disc.position.y = 0.03; root.add(disc); var rim = new THREE.Mesh(new THREE.RingGeometry(rr * 0.92, rr * 1.0, 48), new THREE.MeshBasicMaterial({ map: softTex(), color: zc, transparent: true, opacity: d.kind === 'ZONE' ? 0.35 : 0.0, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide })); rim.rotation.x = -Math.PI / 2; rim.position.y = 0.05; root.add(rim);   /* zone edge = a soft luminous seam, not a hard torus; impacts use the aura spread instead */ var e0 = { kind: d.kind, root: root, rim: rim, disc: disc, t: 0, particles: [], poolKey: fxKey(d), harmless: !!d.harmless, crit: d.cause === 'CRITICAL', classId: d.class_id, formation: d.formation || null, category: d.category || null, radius: d.radius || 1, dustDone: false }; if (d.kind === 'IMPACT' && d.formation === 'CLAMP') { e0.clamp = mountClampSheets(root, zc); } if (d.kind === 'IMPACT') { var flash = glowSprite(zc, 1.1, 0.95); flash.material.color.lerp(new THREE.Color(0xffffff), 0.5); flash.position.y = 1.0; root.add(flash); e0.flash = flash; var spread = glowSprite(zc, 0.4, 0.55); spread.position.y = 1.0; root.add(spread); e0.spread = spread; }   /* the old round aura spread + random points gave way to the granular BURST (emitted on the first placed frame) */ else { var zl = labelSprite(d.label || id, '#d9c7ff', 2.4); zl.position.y = 1.0; root.add(zl); e0.label = zl; } ents[id] = e0; scene.add(root); return root; }
      if (d.kind === 'TRAP') { var tr = new THREE.Mesh(new THREE.ConeGeometry(0.35, 0.5, 4), mat(0xffd15e, { emissive: 0xffa620, emissiveIntensity: 0.8 })); tr.position.y = 0.25; root.add(tr); var tring = new THREE.Mesh(new THREE.TorusGeometry(d.radius || 0.8, 0.03, 6, 32), mat(0xffd15e, { emissive: 0xffa620, emissiveIntensity: 0.5, transparent: true, opacity: 0.6 })); tring.rotation.x = Math.PI / 2; tring.position.y = 0.04; root.add(tring); ents[id] = { kind: 'TRAP', root: root, cone: tr, t: 0 }; scene.add(root); return root; }
      if (d.kind === 'MARKER') { var ring2 = new THREE.Mesh(new THREE.TorusGeometry(d.radius || 1.5, 0.06, 8, 32), mat(d.color || 0x66ffcc, { emissive: d.color || 0x66ffcc, emissiveIntensity: 0.7 })); ring2.rotation.x = Math.PI / 2; ring2.position.y = 0.05; root.add(ring2); var pole = new THREE.Mesh(new THREE.CylinderGeometry(0.04, 0.04, 2.2, 6), mat(d.color || 0x66ffcc, { emissive: d.color || 0x66ffcc, emissiveIntensity: 0.5 })); pole.position.y = 1.1; root.add(pole); var ml = labelSprite(d.label || id, '#c9fff0'); ml.position.y = 2.5; root.add(ml); ents[id] = { kind: 'MARKER', root: root, ring: ring2, label: ml, t: 0 }; scene.add(root); return root; }
      if (d.kind === 'NAV_MARKER') { /* destination mark (owner 2026-09-18 §4.3): restrained, class-coloured — a thin flat ring, a small core, a short tick; an AIR waypoint sits at its altitude with a faint plumb line to the ground. Not a HUD control. */ var nc = energyOf(d.class_id);   /* class energy authority: Athlete gold */ var ringN = new THREE.Mesh(new THREE.RingGeometry(0.34, 0.42, 40), new THREE.MeshBasicMaterial({ color: nc, transparent: true, opacity: 0.85, depthWrite: false, side: THREE.DoubleSide })); ringN.rotation.x = -Math.PI / 2; ringN.position.y = 0.04; root.add(ringN); var core = new THREE.Mesh(new THREE.CircleGeometry(0.09, 20), new THREE.MeshBasicMaterial({ color: nc, transparent: true, opacity: 0.9, depthWrite: false })); core.rotation.x = -Math.PI / 2; core.position.y = 0.05; root.add(core); var tick = new THREE.Mesh(new THREE.CylinderGeometry(0.02, 0.02, 0.5, 6), new THREE.MeshBasicMaterial({ color: nc, transparent: true, opacity: 0.7, depthWrite: false })); tick.position.y = 0.3; root.add(tick); var plumb = new THREE.Mesh(new THREE.CylinderGeometry(0.012, 0.012, 1, 4), new THREE.MeshBasicMaterial({ color: nc, transparent: true, opacity: 0.28, depthWrite: false })); plumb.visible = false; root.add(plumb); ents[id] = { kind: 'NAV_MARKER', root: root, ring: ringN, core: core, tick: tick, plumb: plumb, t: 0, y: null }; scene.add(root); return root; }
      if (d.kind === 'LOCK_MARKER') { /* four inward-pointing corner arrows around the target's body bounds; bright theme colour with a dark outline; billboarded */ var col2 = d.color || 0xffe066; var corners = new THREE.Group(); var mk = function (sx, sy) { var g = new THREE.Group(); var tri = new THREE.Shape(); tri.moveTo(0, 0); tri.lineTo(-0.28, 0.1); tri.lineTo(-0.1, 0.28); tri.lineTo(0, 0); var outline = new THREE.Mesh(new THREE.ShapeGeometry(tri), new THREE.MeshBasicMaterial({ color: 0x0a0e16, transparent: true, opacity: 0.9, depthTest: false })); outline.scale.set(1.35, 1.35, 1); var fill = new THREE.Mesh(new THREE.ShapeGeometry(tri), new THREE.MeshBasicMaterial({ color: col2, transparent: true, opacity: 1, depthTest: false })); fill.position.z = 0.01; g.add(outline); g.add(fill); g.scale.set(sx, sy, 1); g.userData.fill = fill; g.userData.outline = outline; return g; }; var ul = mk(-1, -1), ur = mk(1, -1), ll = mk(-1, 1), lr = mk(1, 1); [ul, ur, ll, lr].forEach(function (c) { corners.add(c); }); root.add(corners); ents[id] = { kind: 'LOCK_MARKER', root: root, corners: corners, arrows: [ul, ur, ll, lr], t: 0, acquired: 0 }; scene.add(root); return root; }
      var color = d.self ? (CLASS_COLOR[d.class_id] || 0x39c5ff) : (CLASS_COLOR[d.class_id] ? CLASS_COLOR[d.class_id] : 0xb0b8c8); var rigid = null; var fused, s1, s2, split = new THREE.Group();
      if (o.characterFactory) { rigid = (o.factoryFor && o.factoryFor(d.body_key || d.class_id)) ? o.factoryFor(d.body_key || d.class_id)({ tint: color, class_id: d.class_id, self: !!d.self }) : o.characterFactory({ tint: color, class_id: d.class_id, self: !!d.self }); var hl = glowSprite(energyOf(d.class_id), 0.55, 0);   /* hand energy: a soft class-coloured glow, not a sphere */ hl.position.set(rigid.sockets.HAND_L.x, rigid.sockets.HAND_L.y, rigid.sockets.HAND_L.z); var hr = glowSprite(energyOf(d.class_id), 0.55, 0); hr.material = hl.material.clone(); hr.position.set(rigid.sockets.HAND_R.x, rigid.sockets.HAND_R.y, rigid.sockets.HAND_R.z); rigid.group.add(hl); rigid.group.add(hr); fused = { group: rigid.group, rigid: true, rig: rigid, parts: null, glows: [hl, hr] }; s1 = s2 = null; lastCaps = rigid.capabilities || null;
        if (beamFx && beamFx.attachMaterial && rigid.group) {   /* effect A: the class-coloured gradient over the lower shin lives in the character's own material */
          var seenMat = new Map(), mi = 0;
          rigid.group.traverse(function (m) {
            if (!m.isMesh || !m.material || Array.isArray(m.material)) return;
            var had = seenMat.get(m.material);
            if (had) { m.material = had; return; }                                   /* body and split legs share one instance: attach once, reuse the result */
            var got = beamFx.attachMaterial(id + ':' + (mi++), m.material);
            if (got && got.material) { seenMat.set(m.material, got.material); m.material = got.material; }   /* SkeletonUtils.clone shares materials, so a second character gets a clone back — keep it */
          });
        }
        if (rigid.skinned && rigid.bones.HAND_L && rigid.bones.HAND_R) { /* SKINNED derivative rig: hand effects ride the animated HAND bones; seam / propulsion emitters ride PELVIS and TAIL3; the RigAnimator articulates from authoritative state */ var inv = 1 / rigid.scale; [hl, hr].forEach(function (s, i) { rigid.group.remove(s); s.scale.setScalar(s.isSprite ? 0.30 * inv : inv); s.position.set(0, -0.03, 0); rigid.bones[i === 0 ? 'HAND_L' : 'HAND_R'].add(s); }); var seam = new THREE.Mesh(new THREE.TorusGeometry(0.115, 0.012, 8, 32), new THREE.MeshBasicMaterial({ color: 0x9fe8ff, transparent: true, opacity: 0, depthWrite: false })); seam.visible = false;   /* motion precision pass G: the transformation ring is REMOVED — the seam energy now lights the fusion line on the body itself (GlbCharacter setSeam) */ var emit = new THREE.Mesh(new THREE.SphereGeometry(0.045, 10, 8), new THREE.MeshBasicMaterial({ color: 0x66ccff, transparent: true, opacity: 0, depthWrite: false })); emit.position.set(0, -0.02, 0); rigid.bones.TAIL3.add(emit); var tips = [-1, 1].map(function (sgn) { var tp = new THREE.Mesh(new THREE.SphereGeometry(0.025, 8, 6), new THREE.MeshBasicMaterial({ color: 0x66ccff, transparent: true, opacity: 0, depthWrite: false })); tp.position.set(sgn * 0.045, -0.02, 0); rigid.bones.TAIL3.add(tp); return tp; }); rigid.seed = ((id.split('').reduce(function (a, c) { return (a * 31 + c.charCodeAt(0)) % 1000003; }, 7)) % 1000) / 1000; fused.animator = createRigAnimator(THREE, rigid, { defaults: DEF, animData: o.animData || null, classId: d.class_id || 'ATHLETE', seed: rigid.seed, profile: o.profile || null }); fused.seam = seam; fused.emit = emit; fused.tips = tips; fused.muscle = createMuscleLayer(THREE, rigid, {}); fused.emotes = o.animData && o.animData.EMOTES ? o.animData.EMOTES : null; if (rigid.materials) rigid.materials.forEach(function (mt) { var U = mt.userData && mt.userData.mw; if (U) { U.uAuraColor.value.setHex(energyOf(d.class_id)); U.uSeamColor.value.setHex(energyOf(d.class_id)).lerp(new THREE.Color(0xffffff), 0.35); } });   /* the body aura and the seam energy speak the CLASS colour (Athlete: gold) */ fused.classId = d.class_id || 'ATHLETE'; if (beamFx) { beamFx.mount(id, { color: CLASS_ENERGY[d.class_id] || 0x66ccff }); seam.material.color.setHex(CLASS_ENERGY[d.class_id] || 0x9fe8ff); emit.visible = false; tips.forEach(function (tp) { tp.visible = false; }); } if (rigid.setForm) rigid.setForm(d.form === 'SPLIT' ? 0 : 1, d.form === 'SPLIT'); } }
      else { fused = humanoid(color, 1.8, true); s1 = humanoid(color, 1.4, false); s2 = humanoid(color, 1.4, false); s1.group.position.x = -PRESENTATION_CONTRACT.scale.split_offset_m; s2.group.position.x = PRESENTATION_CONTRACT.scale.split_offset_m; split.add(s1.group); split.add(s2.group); }
      split.visible = false; var figure = new THREE.Group(); figure.add(fused.group); figure.add(split); root.add(figure);
      var guard = new THREE.Group(); guard.visible = false; root.add(guard);   /* the ring presentation is REMOVED (owner §15): the guard is the silhouette SHEET built lazily on the body meshes (buildSheet) */
      var glow = new THREE.Mesh(new THREE.RingGeometry(0.3, 0.75, 24), new THREE.MeshBasicMaterial({ color: 0x66ccff, transparent: true, opacity: 0.7, side: THREE.DoubleSide })); glow.rotation.x = -Math.PI / 2; glow.position.y = 0.05; glow.visible = false; root.add(glow);
      var shadow = new THREE.Mesh(new THREE.CircleGeometry(0.5, 20), new THREE.MeshBasicMaterial({ color: 0x000000, transparent: true, opacity: 0.35 })); shadow.rotation.x = -Math.PI / 2; shadow.position.y = 0.01; scene.add(shadow);
      var strike = glowSprite(energyOf(d.class_id), 0.9, 0.9); strike.visible = false; root.add(strike);   /* contact flash: a soft gold sprite, no sphere */
      var floorRing = new THREE.Mesh(new THREE.PlaneGeometry(2.2, 2.2), new THREE.MeshBasicMaterial({ map: softTex(), color: energyOf(d.class_id), transparent: true, opacity: 0, depthWrite: false, blending: THREE.AdditiveBlending })); floorRing.rotation.x = -Math.PI / 2; floorRing.position.y = 0.02; root.add(floorRing);   /* soft reflected floor light at contact, not a hard ring */
      var trail = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.3, 1.6), new THREE.MeshBasicMaterial({ color: color, transparent: true, opacity: 0.35 })); trail.visible = false; trail.position.y = 0.9; root.add(trail);
      var shell = new THREE.Mesh(new THREE.SphereGeometry(1.15, 16, 12), new THREE.MeshBasicMaterial({ color: 0x9fd0ff, transparent: true, opacity: 0.18, wireframe: true })); shell.position.y = 1.0; shell.visible = false; root.add(shell); var mark = new THREE.Mesh(new THREE.SphereGeometry(0.12, 8, 8), mat(0xff4d4d, { emissive: 0xff2222, emissiveIntensity: 1.6 })); var hk = d.height_k || 1; mark.position.y = 2.3 * hk; mark.visible = false; root.add(mark);
      var bar2 = new THREE.Mesh(new THREE.PlaneGeometry(1.4, 0.1), new THREE.MeshBasicMaterial({ color: 0x55ff88, depthTest: false })); bar2.position.y = 2.08 * hk; bar2.visible = false; root.add(bar2);
      var lbl2 = labelSprite(String(d.label || id).replace(/_/g, ' ').replace(/ \(ATHLETE · DUMMY\)/, ''), d.self ? '#dff5ff' : '#e6e6e6'); lbl2.position.y = 2.62 * hk; lbl2.visible = !d.self; root.add(lbl2); var tag = new THREE.Group(); root.add(tag);   /* no development disclaimer floats over the play view (About / dev panel carry the limitations); the player's own name is not shown */
      /* sun shadow casters: the player always; other rigs only on the HIGH tier (each rig is ~25k triangles, and the shadow pass draws every caster inside the shadow box again — on the phone tier that doubled the frame's triangles) */ var castAll = false;   /* every rig casting (soft 2048) cost +4.9 ms p95 on the desktop route; the player alone carries the sun's contact shadow */ if (fused && fused.group) fused.group.traverse(function (m) { if (m.isMesh) m.castShadow = id === 'me' || castAll; });
      ents[id] = { kind: 'CHARACTER', rigid: !!rigid, skinned: !!(rigid && rigid.skinned), prevCur: null, vel: { x: 0, y: 0, z: 0 }, root: root, figure: figure, fused: fused, split: split, splitFigs: rigid ? [] : [s1, s2], guard: guard, sheet: { built: false, mat: sheetMaterial(), meshes: [], prevGuard: null, prevFrac: 1, burstT: -1 }, glow: glow, shadow: shadow, strike: strike, floorRing: floorRing, trail: trail, shell: shell, mark: mark, bar: bar2, label: lbl2, tag: tag, hk: hk, cur: null, blend: 1, t: 0, lastAttack: null, impactT: -1, particles: [], color: color }; scene.add(root); if (d.self && rigid && rigid.skinned) { try { buildSheet(ents[id]); } catch (e) { } }   /* STABILITY 2026-09-20: the player's guard sheet exists (hidden) from the start so the world warm-up compiles its program */ return root;
    },
    update: function (id, v, dt) {
      var e = ents[id]; if (!e || !v) return; e.t += dt; stepParticles(e, dt);
      if (e.kind === 'TARGET') { e.root.position.set(v.position.x, v.position.y || 0, v.position.z); e.root.visible = !v.down; return; }
      if (e.kind === 'MARKER') { e.root.position.set(v.position.x, 0, v.position.z); e.ring.rotation.z += dt * 0.6; e.ring.material.emissiveIntensity = v.active ? 1.4 + 0.5 * Math.sin(e.t * 6) : 0.5; return; }
      if (e.kind === 'PROJECTILE' && e.gear) { updateGearProjectile(e, v, dt); return; }
      if (e.kind === 'PROJECTILE') { e.root.position.set(v.position.x, v.position.y || 1.1, v.position.z); e.root.rotation.y = -(v.heading || 0); if (e.core) {   /* same host → three.js yaw sign as the characters (local forward −Z) */ var pz = 1 + 0.12 * Math.sin(e.t * 26); e.core.scale.set(0.42 * pz, 0.42 * pz, 1); var hs = e.fmS === 'ring' ? 1.6 : (e.fmS === 'rod' ? 0.45 : 1); e.halo.scale.set((0.9 + 0.15 * Math.sin(e.t * 9)) * hs, 0.9 * hs, 1); e.ribs.forEach(function (rb, i) { rb.material.opacity = 0.7 - 0.15 * Math.sin(e.t * 21 + i); }); if (e.dustFx) { e.lastHead.copy(e.root.position); dust.wave(e.dustFx, e.root.position, v.heading || 0); } } return; }
      if (e.kind === 'ZONE' || e.kind === 'IMPACT') { e.root.position.set(v.position.x, 0, v.position.z); e.rim.rotation.z += dt * (e.kind === 'ZONE' ? 0.8 : 4); if (e.kind === 'IMPACT' && !e.dustDone) { e.dustDone = true; var ic = energyOf(e.classId); if (v.formation === 'CURTAIN' || e.formation === 'CURTAIN') { var cur = dust.emit('CURTAIN', { color: ic, count: 260, radius: (e.radius || 1) * 0.9, top: 2.6, x: v.position.x, z: v.position.z, floorY: 0.03, rate: 1300 }); e.dustFx = cur; e.curtainStop = e.t + 0.32; } dust.emit('BURST', { color: ic, count: e.harmless ? 24 : (e.category === 'PHYSICAL' ? 22 : 96), x: v.position.x, y: 0.9, z: v.position.z, speed: e.harmless ? 1.8 : (e.category === 'PHYSICAL' ? 2.4 : 3.4) });   /* harmless = a wall / obstacle dissolve (no success feedback): small and slow */   /* PHYSICAL contact = restrained feedback (a small puff); MAHGIC contacts break up fully */ if (e.spread) { e.spread.visible = false; } }   /* §9.1: impact remnants stay localized and cosmetic, then fade promptly */ if (e.kind === 'IMPACT' && e.dustFx && e.curtainStop !== undefined && e.t > e.curtainStop) { dust.stop(e.dustFx); e.dustFx = null; } if (e.kind === 'IMPACT' && e.clamp) updateClampSheets(e, v); if (e.kind === 'IMPACT') { var k = Math.min(1, e.t / 0.45); var cm = e.crit ? 1.6 : 1;   /* owner next-pass 2026-09-20 §17: a CRITICAL reads a little larger and brighter (flash × 1.6, the rim seam visible), never obnoxious */ e.disc.material.opacity = 0.4 * (1 - k) * (e.crit ? 1.4 : 1); e.rim.scale.setScalar((0.4 + 1.2 * k) * cm); if (e.crit) e.rim.material.opacity = 0.5 * (1 - k); if (e.flash) { var fk = Math.min(1, e.t / 0.18); e.flash.scale.setScalar((0.5 + 0.9 * fk) * cm); e.flash.material.opacity = 0.95 * (1 - fk); } if (e.spread) { e.spread.scale.setScalar(0.4 + 3.2 * k); e.spread.material.opacity = 0.55 * (1 - k) * (1 - k); } }   /* gold flash (0.18 s) then a brief aura spread — no rim ring */ else { e.disc.material.opacity = 0.18 + 0.08 * Math.sin(e.t * 3); if (o.camera && e.label) e.label.quaternion.copy(o.camera.quaternion); } return; }
      if (e.kind === 'TRAP') { e.root.position.set(v.position.x, 0, v.position.z); e.cone.rotation.y += dt * 1.5; return; }
      if (e.kind === 'NAV_MARKER') { var ty = v.position.y || 0; if (e.y === null) { e.y = ty; e.born = e.t; } e.root.position.set(v.position.x, ty, v.position.z); var life = Math.min(1, (e.t - (e.born || 0)) / 0.18); var pulse = 1 + 0.08 * Math.sin(e.t * 5.5); var sc = life * (v.settling ? 0.7 : pulse); e.ring.scale.set(sc, sc, sc); e.core.scale.set(sc, sc, sc); e.ring.material.opacity = 0.85 * life; e.core.material.opacity = 0.9 * life; e.tick.material.opacity = 0.7 * life; e.ring.rotation.z += dt * 0.8; if (v.air && ty > 0.3) { e.plumb.visible = true; e.plumb.scale.y = ty; e.plumb.position.y = -ty / 2; } else e.plumb.visible = false; return; }
      if (e.kind === 'LOCK_MARKER') { /* follows the target's collision bounds (root + smoothed), never the animation; pulses once on acquire; fades when not visible */ var tgt = { x: v.position.x, y: (v.position.y || 0) + 1.0, z: v.position.z }; if (!e.cur) { e.cur = tgt; e.acquired = e.t; } e.cur.x += (tgt.x - e.cur.x) * Math.min(1, dt * 18); e.cur.y += (tgt.y - e.cur.y) * Math.min(1, dt * 18); e.cur.z += (tgt.z - e.cur.z) * Math.min(1, dt * 18); e.root.position.set(e.cur.x, e.cur.y, e.cur.z); if (o.camera) e.root.quaternion.copy(o.camera.quaternion); var pulse = Math.max(0, 1 - (e.t - e.acquired) / 0.35); var w = 0.75 + 0.35 * pulse, h = 1.05 + 0.35 * pulse; var op = v.visible === false ? 0.25 + 0.15 * Math.sin(e.t * 10) : 1; e.arrows[0].position.set(-w, h, 0); e.arrows[1].position.set(w, h, 0); e.arrows[2].position.set(-w, -h, 0); e.arrows[3].position.set(w, -h, 0); e.arrows.forEach(function (a) { a.userData.fill.material.opacity = op; a.userData.outline.material.opacity = 0.9 * op; }); return; }
      /* ---------------- CHARACTER ---------------- */
      var tgt2 = { x: v.position.x, y: v.position.y || 0, z: v.position.z }; if (!e.cur || v.snap) { e.cur = { x: tgt2.x, y: tgt2.y, z: tgt2.z }; e.ibuf = null; }
      var IDL = (DEF.presentation && DEF.presentation.interp_delay_s) || 0; var HT = v.host_t;
      if (IDL > 0 && typeof HT === 'number' && isFinite(HT)) {
        /* PASS 5 (Spec E / addendum smoothness): SNAPSHOT INTERPOLATION — the host ticks at 20 Hz and is polled every ~60 ms, so the raw
           target jumps 18–36 cm at walking pace; an exponential filter left a ±10 % speed ripple. The root now renders `interp_delay_s`
           behind an estimated host clock (latest host_t + wall time since it arrived) by linear interpolation between the two bracketing
           samples: constant host velocity → constant displayed velocity. A teleport (> 6 m between samples) or `snap` resets the buffer;
           when the clock runs past the newest sample (the host stopped ticking) the newest sample is held. */
        var b = e.ibuf || (e.ibuf = { s: [], lastHT: null, recv: 0, off: null }); var nowMs = (typeof performance !== 'undefined' ? performance.now() : Date.now()); var wall = nowMs / 1000;
        if (b.lastHT === null || HT > b.lastHT + 1e-6) { var prevS = b.s[b.s.length - 1]; if (prevS && Math.hypot(tgt2.x - prevS.x, tgt2.z - prevS.z) > 6) { b.s.length = 0; b.off = null; } b.s.push({ t: HT, x: tgt2.x, y: tgt2.y, z: tgt2.z }); if (b.s.length > 10) b.s.shift(); b.lastHT = HT; b.recv = nowMs; var offNow = HT - wall; b.off = b.off === null ? offNow : b.off + (offNow - b.off) * 0.15; }   /* the host-clock offset is filtered (≈ 7 polls): bunched host ticks never re-base the render clock in one step */
        else if (HT < b.lastHT - 1e-6) { b.s.length = 0; b.s.push({ t: HT, x: tgt2.x, y: tgt2.y, z: tgt2.z }); b.lastHT = HT; b.recv = nowMs; b.off = HT - wall; }   /* host clock went backwards (room change / reset) */
        var rt = wall + b.off - IDL; var S = b.s; var px = tgt2.x, py = tgt2.y, pz = tgt2.z;
        if (S.length === 1 || rt >= S[S.length - 1].t) { var L = S[S.length - 1]; px = L.x; py = L.y; pz = L.z; }
        else if (rt <= S[0].t) { px = S[0].x; py = S[0].y; pz = S[0].z; }
        else { for (var si = S.length - 2; si >= 0; si--) { if (rt >= S[si].t) { var A = S[si], B = S[si + 1]; var u = (rt - A.t) / Math.max(1e-6, B.t - A.t); px = A.x + (B.x - A.x) * u; py = A.y + (B.y - A.y) * u; pz = A.z + (B.z - A.z) * u; break; } } }
        e.cur.x = px; e.cur.y = py; e.cur.z = pz;
      } else { var kk = Math.min(1, dt * (v.dash ? 22 : 12)); e.cur.x += (tgt2.x - e.cur.x) * kk; e.cur.y += (tgt2.y - e.cur.y) * Math.min(1, dt * 10); e.cur.z += (tgt2.z - e.cur.z) * kk; }
      e.root.position.set(e.cur.x, e.cur.y, e.cur.z); e.shadow.position.set(e.cur.x, 0.01, e.cur.z); e.shadow.scale.setScalar(Math.max(0.3, 1 - e.cur.y * 0.08));
      /* FULL-BODY orientation: the root follows the authoritative facing (= travel heading, or the resolved combat direction). Rate-limited so
         rapid input reversals read as a turn, not a flicker: exponential 16/s (~90° in 0.15 s) with a 900°/s cap; an attack's first frames and
         a dash snap harder (36/s) so the strike leaves along the body. The animator adds chest/pelvis lead + counter-motion on top. */
      var yaw = v.facing || 0; /* host convention: forward(φ) = (sin φ, −cos φ), +φ turns right. The body's local forward is −Z, and three.js R_y(θ)·(0,0,−1) = (−sin θ, −cos θ), so the DISPLAYED yaw is −φ (PASS 2 review: the old +φ mirrored his facing across Z — the camera 'behind' him saw his face at ±90° headings) */ var dispYaw = -yaw; var cy = e.root.rotation.y; var dy = Math.atan2(Math.sin(dispYaw - cy), Math.cos(dispYaw - cy)); var snapTurn = (v.attack && /STARTUP|CONCENTRIC/.test(String(v.attack.state || ''))) || v.dash;
      /* PASS 2b (connected movement): the displayed turn is a critically damped spring on the yaw error — it accelerates into the turn and eases out (no exponential snap, no overshoot), rate-capped at TURN.cap_dps (attacks / dash turn faster). A 180° turn settles in ≈ 0.45 s. */ var wT = 2 * Math.PI * (snapTurn ? TURN.snap_hz : TURN.hz); var sT = springStep(dy, -(e.yawVel || 0), wT, dt); var stepT = dy - sT[0]; var velT = -sT[1]; var capT = (snapTurn ? TURN.snap_cap_dps : TURN.cap_dps) * Math.PI / 180 * dt; if (Math.abs(stepT) > capT) { stepT = Math.sign(stepT) * capT; velT = Math.sign(stepT) * (snapTurn ? TURN.snap_cap_dps : TURN.cap_dps) * Math.PI / 180; } e.root.rotation.y = cy + stepT; e.yawVel = velT;
      var wantForm = v.form === 'SPLIT' ? 'SPLIT' : 'FUSED'; var target = wantForm === 'SPLIT' ? 0 : 1; e.blend += (target - e.blend) * Math.min(1, dt * (v.transforming ? 2.2 : 8)); if (e.rigid) { e.fused.group.visible = true; e.split.visible = false; } else { e.fused.group.visible = e.blend > 0.5; e.split.visible = e.blend <= 0.5; }   /* a rigid GLB cannot show the SPLIT form: the fused silhouette stays (limitation reported in the dev panel) */ var pulse2 = v.transforming ? 1 + 0.06 * Math.sin(e.t * 18) : 1; e.figure.scale.setScalar(pulse2 * (0.85 + 0.15 * Math.abs(e.blend - 0.5) * 2)); if (e.skinned) e.figure.scale.setScalar(1);
      var moving = /GLIDE|RUN|WALK|MOVE|DASH|GAIT|SPRINT/.test(String(v.mahloco || '')); var fly = v.flight && v.flight.powered; e.figure.position.y = fly ? 0.15 * Math.sin(e.t * 2.5) : (moving ? Math.abs(Math.sin(e.t * 9)) * 0.05 : 0); e.figure.rotation.x = fly ? 0.2 : (moving ? 0.06 : 0); e.figure.rotation.z = moving ? 0.03 * Math.sin(e.t * 9) : 0; if (e.skinned) { e.figure.position.y = fly ? 0.08 * Math.sin(e.t * 2.1) : 0; e.figure.rotation.set(0, 0, 0); }   /* skinned: the body itself leans / breathes / hovers through its bones, not through a rigid bob */
      /* pose from authoritative phases (never the other way round) */
      var at = v.attack; var poseName = 'IDLE', pp = 0; var hitAgo = v.hit_ago_s === null || v.hit_ago_s === undefined ? 99 : v.hit_ago_s; var attackStyle = at && at.profile && at.profile.style || 'BALANCED', strikeTiming = STRIKE_TIMING[attackStyle] || STRIKE_TIMING.BALANCED; if (at && at.category === 'PHYSICAL_MAGIC') strikeTiming = { release: strikeTiming.release * 1.12, recover: strikeTiming.recover * 1.1 };
      if (v.ko) poseName = 'KO'; else if (hitAgo < 0.35) { poseName = 'HIT'; pp = hitAgo / 0.35; } else if (at && /CONCENTRIC|STARTUP/.test(at.state)) { poseName = at.category === 'SPECIAL_MAGIC' ? 'CAST_STARTUP' : 'STRIKE_STARTUP'; pp = at.progress === undefined ? 0.6 : at.progress; e.lastAttack = at.attack_id; e.impactT = -1; } else if (at && /PEAK|ECCENTRIC|RECOVERY/.test(at.state)) { if (e.impactT < 0 && (at.progress === undefined || at.progress >= 0.22)) {   /* the contact flash / grains fire when the animator's whip reaches the force arc (recovery p ≈ 0.25), not at the host phase change 0.09–0.26 s earlier — the impact frame = pose + VFX together (tempo audit 2026-09-20) */ e.impactT = e.t; if (at.category === 'PHYSICAL') { var pt = energyOf(e.fused && e.fused.classId); e.particles.push(spawnParticles(e.root, pt, at.profile && at.profile.style === 'HEAVY' ? 12 : 8, at.profile && at.profile.style === 'HEAVY' ? 2.6 : 2.2, 0.3)); }   /* PHYSICAL: the body delivers the contact — a restrained puff only */ if (e.dustGather) { var hp = handWorld(e, 'HAND_R', DV1); var fwdx = Math.sin(-e.root.rotation.y), fwdz = -Math.cos(-e.root.rotation.y); dust.scatter(e.dustGather, hp, fwdx, fwdz, at.category === 'PHYSICAL_MAGIC' ? 3.2 : 2.0); e.dustGather = null; }   /* the gathered grains burst at the contact and die within ~0.4 s — a short wake, never a projectile */ if (e.dustCurtain) { dust.stop(e.dustCurtain); e.dustCurtain = null; } } var since = e.t - e.impactT, relS = strikeTiming.release, recS = strikeTiming.recover; poseName = at.category === 'SPECIAL_MAGIC' ? 'CAST_RELEASE' : (since < relS ? 'STRIKE_RELEASE' : 'STRIKE_RECOVER'); pp = since < relS ? since / relS : Math.min(1, (since - relS) / recS); } else if (v.guard === 'PHYSICAL') poseName = 'GUARD_PHYSICAL'; else if (v.guard === 'MAGICAL') poseName = 'GUARD_MAGICAL'; else if (fly) poseName = 'FLY'; else if (v.emote) poseName = 'WAVE';
      var castLive = at && /CONCENTRIC|STARTUP/.test(at.state) && !v.ko; if (castLive && at.category === 'PHYSICAL_MAGIC') { if (!e.dustGather) e.dustGather = dust.emit('GATHER', { color: energyOf(e.fused && e.fused.classId), count: 130, rate: 320, parent: scene }); var hingeG = /HINGE/.test(String(at.attack_id || '')), loadG = /CONCENTRIC|STARTUP/.test(at.state); var hw = handWorld(e, hingeG && loadG ? 'PELVIS' : 'HAND_R', DV1), ew = handWorld(e, hingeG ? (loadG ? 'TAIL1' : 'PELVIS') : 'FOREARM_R', DV2); if (hw && ew) dust.gather(e.dustGather, hw, ew, 0.5 + 0.5 * (at.progress === undefined ? 0.6 : at.progress)); }   /* PHYSICAL MAHGIC: the grains gather along the striking hand → forearm and FOLLOW it (anchored after this frame's final pose); the HINGE gathers at the hips during the load and runs pelvis → hand on the drive (owner 2026-09-18 §8: MAHGIC hurled from the hip drive) */ else if (castLive && at.category === 'SPECIAL_MAGIC') { if (!e.dustGather) e.dustGather = dust.emit('GATHER', { color: energyOf(e.fused && e.fused.classId), count: 90, rate: 200, parent: scene }); var hw2 = handWorld(e, 'HAND_R', DV1), ew2 = handWorld(e, 'FOREARM_R', DV2); if (hw2 && ew2) dust.gather(e.dustGather, hw2, ew2, 0.4 + 0.6 * (at.progress === undefined ? 0.6 : at.progress)); if (/CHEST_FLY/.test(String(at.attack_id || ''))) { if (!e.dustGather2) e.dustGather2 = dust.emit('GATHER', { color: energyOf(e.fused && e.fused.classId), count: 90, rate: 200, parent: scene }); var hl2 = handWorld(e, 'HAND_L', DV1), el2 = handWorld(e, 'FOREARM_L', DV2); if (hl2 && el2) dust.gather(e.dustGather2, hl2, el2, 0.4 + 0.6 * (at.progress === undefined ? 0.6 : at.progress)); }   /* the CHEST FLY gathers on BOTH hands: the clap brings the two charges together */ if (at.profile && at.profile.formation === 'CURTAIN' && at.point && !e.dustCurtain) { e.dustCurtain = dust.emit('CURTAIN', { color: energyOf(e.fused && e.fused.classId), count: 260, radius: 0.9, top: 2.8, x: at.point.x, z: at.point.z, floorY: 0.03, rate: 600 }); } }   /* SPECIAL: a charge gathers at the casting hand; a CURTAIN-formation cast starts its descending column over the aimed point during the pull, so the impending area is readable from the motion itself */ else if (e.dustGather && !at) { dust.stop(e.dustGather); e.dustGather = null; if (e.dustGather2) { dust.stop(e.dustGather2); e.dustGather2 = null; } if (e.dustCurtain) { dust.stop(e.dustCurtain); e.dustCurtain = null; } }   /* interrupted / ended without a commit: the grains just fade */
      var prof = at && at.profile ? at.profile : null; var tint = prof && typeof prof.tint === 'string' && /^#[0-9a-f]{6}$/i.test(prof.tint) ? parseInt(prof.tint.slice(1), 16) : null; var style = attackStyle;
      var figs = e.rigid ? [e.fused] : (e.fused.group.visible ? [e.fused] : e.splitFigs); var view = null; if (e.skinned) { if (!e.prevCur) e.prevCur = { x: e.cur.x, y: e.cur.y, z: e.cur.z }; var idt = 1 / Math.max(dt, 1e-3); var nv = { x: (e.cur.x - e.prevCur.x) * idt, y: (e.cur.y - e.prevCur.y) * idt, z: (e.cur.z - e.prevCur.z) * idt }; e.prevCur = { x: e.cur.x, y: e.cur.y, z: e.cur.z }; var kv = Math.min(1, dt * 10); e.vel.x += (nv.x - e.vel.x) * kv; e.vel.y += (nv.y - e.vel.y) * kv; e.vel.z += (nv.z - e.vel.z) * kv; var sp = Math.hypot(e.vel.x, e.vel.z); var fwd = { x: Math.sin(yaw), z: -Math.cos(yaw) }; var along = sp > 0.05 ? (e.vel.x * fwd.x + e.vel.z * fwd.z) / sp : 1; var rightV = { x: Math.cos(yaw), z: Math.sin(yaw) }; var lateral = sp > 0.3 ? (e.vel.x * rightV.x + e.vel.z * rightV.z) / sp : 0;   /* signed sideways share of travel, +1 = the character's right */ var tdir = null; if (v.emote_target_pos && v.emote) { var ang = Math.atan2(v.emote_target_pos.x - e.cur.x, -(v.emote_target_pos.z - e.cur.z)); tdir = Math.atan2(Math.sin(ang - yaw), Math.cos(ang - yaw)); } view = { speed01: Math.min(1, sp / 5.5), speed_mps: sp, backward: along < -0.35 && !!v.locked, lateral: lateral, locked: !!v.locked, yaw: yaw, vz: e.vel.y, moving: moving || sp > 0.3, fly: !!fly, braking: !!(v.flight && v.flight.braking), brake_seq: v.flight && v.flight.brake_seq ? v.flight.brake_seq : 0, brake_x: v.flight && v.flight.brake_x ? v.flight.brake_x : 0, fly_cruise: v.flight && v.flight.cruise_mps ? v.flight.cruise_mps : null, altitude: Math.max(0, e.cur.y - (v.ground || 0)), dash: v.dash, attack: at, guard: v.guard, hitAgo: hitAgo, hitDir: v.hit_dir || 0, ko: !!v.ko, emote: v.emote, emote_at: v.emote_at, emote_target_dir: tdir, paired: v.paired || null, host_t: v.host_t, outcome: v.outcome || null, mahloco: v.mahloco, transforming: !!v.transforming, form: v.form }; }
      /* Spec A animator LOD: the player's own rig animates every frame; other rigs animate at a rate set by their distance to the camera
         (≤ 22 m every frame · ≤ 50 m every 2nd · ≤ 100 m every 4th · beyond every 8th), carrying the skipped time so motion speed is unchanged */
      var camP = o.camera && o.camera.position; var lodStep = 1; if (!v.self_view && camP) { var ddx = e.root.position.x - camP.x, ddz = e.root.position.z - camP.z; var dd = ddx * ddx + ddz * ddz; lodStep = dd < 30 * 30 ? 1 : (dd < 60 * 60 ? 2 : 3); }   /* never stop-motion: a far rig still animates at ≥ 1/3 of the frame rate (owner: no glitchy characters) */ e.animAcc = (e.animAcc || 0) + dt; e.animTick = (e.animTick || 0) + 1; if (e.animPhase === undefined) e.animPhase = (Object.keys(ents).length * 7) & 7; var runAnim = lodStep === 1 || ((e.animTick + e.animPhase) % lodStep) === 0; var animDt = runAnim ? e.animAcc : 0; if (runAnim) { e.animAcc = 0; rigsAnimated++; } var animStep = lodStep === 1 ? 0 : Math.min(1 / 15, lodStep / 30);   /* per-entity phase spreads the skipped work over frames; distant rigs integrate in one larger sub-step instead of 2/4/8 × 1/30 s */
      if (view) view.groundAt = groundAt;   /* the world-space support hold reads the beam's foot height under a held point */
      figs.forEach(function (f) { if (f.animator) { if (!e.holdPose && runAnim) f.animator.animate(view, animDt, animStep);   /* the figure group keeps LAST frame's lift / drive while the animator runs (the world-space hold reads the hip through it), then is rebuilt below */ f.group.rotation.set(0, 0, 0); f.group.position.set(0, 0, 0);
          /* S07 ROOT DRIVE — the body sells the attack: a presentation-only lunge/drive along the facing during the force arc, returned to the
             authoritative root through the recovery (hit cones, projectiles and the capsule stay on the authority). Per exercise family:
             PUSH lunges forward and rises, PULL settles back and drops, HINGE snaps forward and up, SQUAT drops then drives up,
             ROTATION whips the figure's yaw past the strike line, CAST leans in. */
          var arc = f.animator.attackArc ? f.animator.attackArc() : null; if (arc && at) { var fwd2 = { x: Math.sin(yaw), z: -Math.cos(yaw) }; var L = arc.load, R = arc.release, W = arc.whip; var dx = 0, dy2 = 0, ry = 0; var roA = f.animator.rootOffset ? f.animator.rootOffset() : null; var pfH = (roA && (Math.abs(roA.z) > 0.02 || Math.abs(roA.y) > 0.02)) ? 0 : 1;   /* when the planted-feet offset is live (split, standing), the pattern's own drop / settle-back is replaced by it */
            if (arc.pat === 'PUSH') { dx = -0.08 * L + 0.30 * R; dy2 = -0.06 * L + 0.10 * R; } else if (arc.pat === 'PULL') { dx = 0.18 * L - 0.26 * R; dy2 = -0.04 * L - 0.08 * R; } else if (arc.pat === 'UPRIGHT_ROW') { dx = 0.06 * L + 0.12 * R; dy2 = -0.08 * L + 0.14 * R; } else if (arc.pat === 'HINGE') { dx = -0.16 * L * pfH + 0.30 * R; dy2 = -0.08 * L * pfH + 0.14 * R; }   /* split + standing: the planted-feet offset already puts the hips back and down; fused keeps the settle-back */ else if (arc.pat === 'SQUAT') { dx = 0.05 * R; dy2 = -0.26 * L * pfH + 0.20 * R; } else if (arc.pat === 'ROTATION') { ry = 0.45 * L - 0.85 * R; dx = 0.16 * R; } else { dx = -0.06 * L + 0.16 * R; }
            f.group.position.set(0, dy2, -dx); f.group.rotation.y = ry;   /* the drive is a LOCAL offset under the rotated root: forward is local −Z (the old world-vector offset was only right at yaw 0) */ e.driveSeen = arc; if (!arc.startup && W > 0.6 && !e.impactPulsed) { e.impactPulsed = true; e.impactPulseT = e.t; if (o.onImpact) o.onImpact(id, { position: { x: e.cur.x + fwd2.x * 0.9, z: e.cur.z + fwd2.z * 0.9 }, pattern: arc.pat, heavy: style === 'HEAVY' }); } if (arc.startup) e.impactPulsed = false; } var roF = f.animator.rootOffset ? f.animator.rootOffset() : null; if (roF && (roF.y || roF.z)) { f.group.position.y += roF.y; f.group.position.z += roF.z; }   /* planted feet (owner interjection 2026-09-18 §8): a hinge / squat keeps the feet on the ground — the root moves, the feet do not */   /* dev hold: the last composed pose stays on the bones (still capture only) */ var sm = f.animator.seam(); var au = f.animator.aura ? f.animator.aura() : 0; var pr = f.animator.propulsion(); if (arc) { var isMagic = at && at.category !== 'PHYSICAL'; var pre = isMagic ? 0.16 : 0.07; au = Math.max(au, pre * arc.load + (isMagic ? 0.34 : 0.16) * arc.whip); }   /* MAHGIC pipeline 1-3-6: body PRE-GLOW builds through the load, the aura peaks at the release and dissipates back into the character */ f.seam.material.opacity = 0; if (f.rig.setSeam) f.rig.setSeam(sm, au); if (f.muscle) f.muscle.update(dt, f.rig.bones, { arc: arc, emote: f.animator.emoteState ? f.animator.emoteState() : null, emotes: f.emotes }); f.emit.material.opacity = 0.55 * pr.central * (moving || fly ? 1 : 0.6); f.tips.forEach(function (tp) { tp.material.opacity = 0.7 * pr.tips; });
          var fm = f.animator.form(); if (f.rig.setForm) f.rig.setForm(fm.packed, fm.showLegs); if (f.rig.group) { f.rig.group.position.y += (fm.hoverLift || 0); }   /* hover lift ADDS to the root drive (the old assignment wiped the attack's vertical drive every frame) */   /* separated hover: a presentation lift on the figure only — host height and capsule untouched */ var fc = f.animator.face(); if (f.rig.setBlink) f.rig.setBlink(fc.blink); e.face = fc; e.form_state = fm;
          if (beamFx) { e.root.updateMatrixWorld(true); var bi = f.animator.beams(); var gt = f.animator.gait(); var haveTips = !!(f.rig.bones.TIP_L && f.rig.bones.TIP_R); var aF = f.rig.anchorWorld('TAIL3', _a); var aL = haveTips ? f.rig.anchorWorld('TIP_L', _b) : null; var aR = haveTips ? f.rig.anchorWorld('TIP_R', _c) : null; if (!aL && aF) { aL = _b.copy(aF); aL.x -= 0.06; aR = _c.copy(aF); aR.x += 0.06; } var blend = fm.transforming ? 1 - fm.packed : (fm.showLegs ? 1 : 0); var gY = aF ? groundAt(aF.x, aF.z, aF.y) : 0; var gL = aL ? groundAt(aL.x, aL.z, aL.y) : gY; var gR = aR ? groundAt(aR.x, aR.z, aR.y) : gY; var alt = aF ? Math.max(0, aF.y - gY) : 0; var seamA = f.rig.anchorWorld('PELVIS', _d) || aF;
            gt.events.forEach(function (ev) { beamFx.pulse(id, ev.side, ev.strength); if (snd && snd.stepPulse) snd.stepPulse(id, ev.side, ev.strength, ev.side === 'L' ? -0.5 : 0.5); });
            /* the beams point along the limb that emits them, not straight down: direction is the emitter's own axis
               (knee → tip when separated, lower spine → tip when fused). Fingertip trails need the finger bones AFTER the
               pose has been written, which is here. The shin-light fade length is the measured shin segment. */
            var dL2 = null, dR2 = null, dF2 = null, shinLen = 0;
            if (haveTips) {
              var kL = f.rig.anchorWorld('SHIN_L', _e), kR = f.rig.anchorWorld('SHIN_R', _f);
              if (kL && aL) { _g.copy(aL).sub(kL); shinLen = _g.length(); if (shinLen > 1e-4) dL2 = _g.multiplyScalar(1 / shinLen); }
              if (kR && aR) { _h.copy(aR).sub(kR); var lr = _h.length(); if (lr > 1e-4) { dR2 = _h.multiplyScalar(1 / lr); if (!shinLen) shinLen = lr; } }
            }
            var tail2 = f.rig.anchorWorld('TAIL2', _i);
            if (tail2 && aF) { _j.copy(aF).sub(tail2); var lf = _j.length(); if (lf > 1e-4) dF2 = _j.multiplyScalar(1 / lf); }
            var fgL = f.rig.anchorWorld('FINGERS_L', _k), fgR = f.rig.anchorWorld('FINGERS_R', _l);
            beamFx.update(id, { dirs: { fused: dF2, L: dL2, R: dR2 }, fingers: { L: fgL, R: fgR }, shinLength: shinLen || undefined, cameraPos: o.camera ? o.camera.position : undefined, form: fm.showLegs ? 'SPLIT' : 'FUSED', blend: blend, anchors: { fused: aF, L: aL, R: aR }, intensity: { fused: bi.fused, L: bi.L, R: bi.R }, seam: 0, seamAnchor: seamA, groundY: gY, groundL: gL, groundR: gR, altitude_m: alt, velocity: { x: e.vel.x, z: e.vel.z }, airborne: gt.airborne, brace: bi.brace }, dt);
            if (snd && snd.propulsion && (v.self_view || o.npcAudio)) snd.propulsion(id, { form: fm.showLegs ? 'SPLIT' : 'FUSED', intensity: { fused: bi.fused, L: bi.L, R: bi.R }, speed01: view.speed01, airborne: gt.airborne, effort01: bi.brace }); if (snd && snd.landing && e.wasAirborne && !gt.airborne) snd.landing(id, 0.6); e.wasAirborne = gt.airborne; } } else if (f.rigid) rigidPose(f, e, poseName, e.t, pp, style); else pose(f, poseName, e.t, pp, style); });
      /* physical MAHGIC gathers on the striking hand and travels with it; special magic glows both hands */
      var glowOn = at && (at.category === 'PHYSICAL_MAGIC' || at.category === 'SPECIAL_MAGIC'); figs.forEach(function (f) { ['L', 'R'].forEach(function (s) { var gm = f.rigid ? f.glows[s === 'L' ? 0 : 1].material : f.parts.arms[s].glow.material; var want = glowOn && (at.category === 'SPECIAL_MAGIC' || s === 'R') ? 0.18 + 0.08 * Math.sin(e.t * 20) : 0;   /* §8: the grains carry the energy; the soft glow is only a faint seat under them, never a smooth ball */ gm.opacity += (want - gm.opacity) * Math.min(1, dt * 12); gm.color.setHex(energyOf(e.fused && e.fused.classId)); }); });
      /* contact flash + floor ring at impact (from the phase change, not from any client timer deciding damage) */
      if (e.impactT >= 0 && e.t - e.impactT < 0.25) { var q = (e.t - e.impactT) / 0.25; e.strike.visible = true; e.strike.material.color.setHex(energyOf(e.fused && e.fused.classId)); e.floorRing.material.color.setHex(energyOf(e.fused && e.fused.classId)); var ss = 0.6 + 1.1 * q; e.strike.scale.set(ss, ss, 1); e.strike.material.opacity = 0.9 * (1 - q) * (1 - q); e.strike.position.set(0, 1.05, -0.8); e.floorRing.material.opacity = 0.45 * (1 - q); e.floorRing.scale.setScalar(0.6 + 1.2 * q); } else { e.strike.visible = false; e.floorRing.material.opacity = 0; }
      /* the guard SHEET (owner §15): visible while guarding, integrity from the host, a break burst when the host drops it at 0 */
      var SHE = e.sheet; var gOn = !!v.guard && !v.ko; var frac = v.guard_sheet && typeof v.guard_sheet.frac === 'number' ? v.guard_sheet.frac : 1; if (gOn && !SHE.built) buildSheet(e);
      if (SHE.prevGuard && !v.guard && (SHE.prevFrac <= 0.05 || (v.guard_sheet && v.guard_sheet.broken))) SHE.burstT = e.t;   /* the host broke it: the sheet shatters outward and fades */
      var burst = SHE.burstT >= 0 && e.t - SHE.burstT < 0.35 ? (e.t - SHE.burstT) / 0.35 : -1; var show = SHE.built && (gOn || burst >= 0); var shs = SHE.mat.userData.shader;
      if (show) { SHE.mat.emissive.setHex(v.guard === 'MAGICAL' || (burst >= 0 && SHE.prevGuard === 'MAGICAL') ? energyOf(e.fused && e.fused.classId) : 0xdfe6ee);   /* PHYSICAL = platinum, MAHGIC = the class energy (Athlete gold) */
        if (shs) { shs.uniforms.uT.value = e.t; if (burst >= 0) { shs.uniforms.uOffset.value = 0.03 + 0.3 * burst; shs.uniforms.uAlpha.value = 0.9 * (1 - burst); shs.uniforms.uFill.value = 0.12 * (1 - burst); } else { var flick = frac < 0.4 ? 0.8 + 0.2 * Math.sin(e.t * 34) : 1; shs.uniforms.uOffset.value = 0.03; shs.uniforms.uAlpha.value = (0.45 + 0.45 * frac) * flick; shs.uniforms.uFill.value = 0.05 + 0.06 * frac; } } }
      for (var si = 0; si < SHE.meshes.length; si++) SHE.meshes[si].visible = show; SHE.prevGuard = v.guard || null; SHE.prevFrac = gOn ? frac : SHE.prevFrac;
      var forcedNow = !!(v.flight && (v.flight.forced_landing || v.flight.forced)); e.glow.visible = !!(fly || forcedNow); if (e.glow.visible) { var f2 = v.flight; e.glow.material.color.setHex(forcedNow ? 0x8a8a8a : (f2.warning ? 0xffa620 : 0x66ccff)); e.glow.material.opacity = f2.warning ? 0.5 + 0.4 * Math.abs(Math.sin(e.t * 8)) : 0.7; e.glow.position.y = -e.cur.y + Math.max(0.05, (v.ground || 0) - e.cur.y + 0.05); }
      e.trail.visible = !!v.dash; if (v.dash) { var dirs = { FORWARD: 0, BACK: Math.PI, LEFT: Math.PI / 2, RIGHT: -Math.PI / 2 }; e.trail.rotation.y = dirs[v.dash.dir] || 0; e.trail.position.set(Math.sin(e.trail.rotation.y) * 0.9, 0.9, Math.cos(e.trail.rotation.y) * 0.9); }
      if (v.ko) { e.figure.rotation.x = -Math.PI / 2; e.figure.position.y = 0.3; }
      var ghost = v.invisible ? (v.self_view ? 0.35 : 0.08) : 1; e.figure.traverse(function (obj) { if (obj.isSprite || obj.isPoints || obj.isLine || (obj.userData && obj.userData.vfx)) return;   /* owner 2026-09-18 §6 (the 'yellow balls'): this loop is for the BODY materials only — it used to force every hand-glow sprite to opacity 1 / white each frame, so the class-energy hand glows never switched off and read as balls intersecting the body */ if (obj.material && obj.material.color && obj.material.type !== 'MeshBasicMaterial') { obj.material.transparent = ghost < 1; obj.material.opacity = ghost; if (v.ko) obj.material.color.setHex(0x555c66); else if (e.skinned) obj.material.color.setHex(0xffffff); else if (e.rigid && obj.material === e.fused.rig.material) obj.material.color.setHex(0x5c626c); } });
      e.shell.visible = !!v.immune; if (v.immune) e.shell.rotation.y += dt * 2; e.mark.visible = !!v.discord; if (v.discord) e.mark.position.y = 2.3 * (e.hk || 1) + 0.1 * Math.sin(e.t * 8);
      e.bar.visible = !!v.in_duel; if (v.in_duel) { var hh = Math.max(0, Math.min(1, v.health01 === undefined ? 1 : v.health01)); e.bar.scale.x = Math.max(0.02, hh); e.bar.material.color.setHex(hh > 0.5 ? 0x55ff88 : (hh > 0.25 ? 0xffd15e : 0xff5e5e)); if (o.camera) e.bar.quaternion.copy(o.camera.quaternion); }
    },
    /* phase B (owner interjection 2026-09-18 §3): the world-space tag under the name — LV n (free roam), LOCKED (+ behind cover / too far) in gold; the health bar (e.bar) shows with in_duel = practice / match */
    tag: function (id, t) { var e = ents[id]; if (!e || e.kind !== 'CHARACTER' || !t) return; var txt = (Number.isFinite(t.level) ? 'LV ' + t.level : '') + (t.lock ? (Number.isFinite(t.level) ? ' · ' : '') + 'LOCKED' + (t.lock.visible === false ? ' · behind cover' : (t.lock.out_of_range ? ' · too far' : '')) : '') + (t.combo ? ' · COMBO' : '') + (t.ko ? ' · KO' : ''); var key = txt + '|' + (t.lock ? 1 : 0) + (t.combo ? 'c' : ''); if (e.tagKey === key) return; e.tagKey = key; e.tagText = txt; if (e.lvl) { e.root.remove(e.lvl); if (e.lvl.userData.tex) e.lvl.userData.tex.dispose(); e.lvl.material.dispose(); e.lvl = null; } if (txt) { e.lvlColor = (t.lock || t.combo) ? '#ffd15e' : '#cfe0ff'; e.lvl = labelSprite(txt, e.lvlColor, 1.6); e.lvl.position.y = 2.34 * (e.hk || 1); e.lvl.visible = e.label ? e.label.visible : true; e.root.add(e.lvl); } },
    get: function (id) { return ents[id] || null; }, ids: function () { return Object.keys(ents); }, handWorld: function (id, bone, out) { var e = ents[id]; return e ? handWorld(e, bone || 'HAND_R', out) : null; }, socketWorld: function (id, bone, outPos, outQuat, outScale) { var e = ents[id]; return e ? socketWorld(e, bone || 'HAND_R', outPos, outQuat, outScale) : null; },   /* M2: equipment receives the animated socket's full world transform; the legacy position-only helper remains for VFX */ rigsAnimated: function (reset) { var n = rigsAnimated; if (reset) rigsAnimated = 0; return n; },
    turnConfig: function () { return TURN; }, workload: function () { var w = { entities: 0, rigs: 0, effects: 0, pooled: 0 }; Object.keys(ents).forEach(function (k) { var e = ents[k]; w.entities++; if (e.poolKey) w.effects++; else if (e.fused || (e.splitFigs && e.splitFigs.length)) w.rigs++; }); Object.keys(FX_POOL).forEach(function (k) { w.pooled += FX_POOL[k].length; }); return w; },   /* Control Lab: what the frame is actually carrying */
    dustUpdate: function (dt) { dust.update(dt); }, dustStats: function () { return dust.stats(); }, dustLive: function () { return dust.live(); },
    remove: function (id) { var e = ents[id]; if (!e) return; if (e.dustGather) { dust.stop(e.dustGather); e.dustGather = null; } if (e.dustGather2) { dust.stop(e.dustGather2); e.dustGather2 = null; } if (e.dustCurtain) { dust.stop(e.dustCurtain); e.dustCurtain = null; } if (beamFx) beamFx.remove(id); if (snd && snd.stopPropulsion) snd.stopPropulsion(id); if (e.poolKey) { scene.remove(e.root); if (releaseEffect(e)) { delete ents[id]; return; } } e.root.traverse(function (obj) { if (obj.geometry) obj.geometry.dispose(); if (obj.isSkinnedMesh && obj.skeleton && obj.skeleton.dispose && !obj.skeleton.userData_shared) { try { obj.skeleton.dispose(); } catch (e3) { } }   /* B8 leak fix: each cloned body owns its skeleton (SkeletonUtils.clone) whose bone DataTexture was never freed — 2 per NPC remount, ≈ 20 per building visit */ var mats = Array.isArray(obj.material) ? obj.material : (obj.material ? [obj.material] : []); mats.forEach(function (m) { Object.keys(m).forEach(function (k) { var v = m[k]; if (v && v.isTexture && v !== SOFT_TEX && v !== STREAK_TEX && !(v.userData && v.userData.shared)) { try { v.dispose(); } catch (e2) { } } }); m.dispose(); }); }); scene.remove(e.root);   /* B8 leak fix: a skinned body carries normal / roughness / emissive maps beyond `.map` — only `.map` was disposed, so every NPC remount on a room change left its other maps on the GPU (≈ 20 textures per building visit) */   /* the soft / streak textures are shared by every effect: disposing them forced a re-upload on the next mount */ if (e.shadow) { e.shadow.geometry.dispose(); e.shadow.material.dispose(); scene.remove(e.shadow); } delete ents[id]; },
    dispose: function () { Object.keys(ents).forEach(api.remove); if (beamFx) beamFx.dispose(); },
    beamDebug: function (id) { return beamFx ? beamFx.debug(id) : null; }, faceOf: function (id) { var e = ents[id]; return e ? e.face || null : null; }, formOf: function (id) { var e = ents[id]; return e ? e.form_state || null : null; }
  };
  return api;
}
