/* MAHWORLD PLAYABLE SAMPLE :: RULES 17–23 client LOGIC module (development view layer; never simulates, renders no DOM)
   Since the attack-dock pass the visible controls live in gameHud.js (one control tree, one selection function). This module keeps the
   aim hint (nearest eligible in front, a host-accepted lock wins, Tab cycles), the cast request builder, the team / fixture shortcuts and the
   entity presentation routing (other combatants, projectiles, zones, traps, impacts) through the SAME adapter. */
export function createRulesHud(deps) {
  var send = deps.send, log = deps.log, select = deps.select; var state = { aim: null, aimIdx: 0, allyConfirm: false, lastRules: null };
  function eligibleTargets(r, skOverride) { if (!r) return []; var me = r.me; var sk = skOverride || currentSkill(r); var wantAlly = sk && sk.targets && sk.targets.some(function (t) { return t === 'SELF' || t === 'ALLY' || t === 'EXPLICIT_ALLY'; }); var wantEnemy = !sk || !sk.targets || sk.targets.indexOf('ENEMY') >= 0; return r.others.filter(function (o) { return !o.ko && ((wantEnemy && o.enemy) || (wantAlly && o.ally)); }).map(function (o) { var dx = o.position.x - me.position.x, dz = o.position.z - me.position.z; var d = Math.hypot(dx, dz); var fx = Math.sin(me.facing), fz = -Math.cos(me.facing); var cos = d > 0 ? (fx * dx + fz * dz) / d : 1; return { o: o, d: d, front: cos > 0.5 }; }).sort(function (a, b) { return (a.front === b.front ? a.d - b.d : (a.front ? -1 : 1)); }); }
  function currentSkill(r) { if (!r) return null; var list = r.skills[r.me.category] || []; return list[r.me.selection[r.me.category] || 0] || null; }
  function aimId(r, skOverride) { var list = eligibleTargets(r, skOverride); if (!list.length) { state.aim = null; return null; } if (r.me.lock && list.some(function (x) { return x.o.id === r.me.lock.target; })) { state.aim = r.me.lock.target; return state.aim; }   /* a host-accepted lock is the aim whenever the move can target it */ if (state.aim && list.some(function (x) { return x.o.id === state.aim; })) return state.aim; state.aim = list[0].o.id; state.aimIdx = 0; return state.aim; }
  var api = {
    active: function () { return !!state.lastRules; }, currentAim: function () { return state.lastRules ? aimId(state.lastRules) : null; }, rules: function () { return state.lastRules; },
    update: function (p) { state.lastRules = p && p.rules ? p.rules : null; }, render: function (p) { api.update(p); },   /* render kept as an alias: nothing is drawn here */
    setAllyConfirm: function (on) { state.allyConfirm = !!on; },
    /* DIRECT EXECUTION (E/R/T/Y): cast slot N of the current category in ONE request — RULES_CAST {skill_id} — with the same aim logic the
       armed cast uses, computed for THAT skill. The armed selection is untouched (arming never fires; direct keys never arm). */
    /* PASS 3 MAHGIC: the first READY magic skill (special MAHGIC first, then physical MAHGIC) with the direct-slot aim logic; the current category is untouched */
    castMagic: function () { var r = state.lastRules; if (!r) return Promise.resolve({ accepted: false, reason: 'NO_RULES' }); var sk = null; ['SPECIAL_MAGIC', 'PHYSICAL_MAGIC'].forEach(function (k) { if (sk) return; sk = (r.skills[k] || []).filter(function (x) { return x && x.availability === 'READY'; })[0] || null; }); if (!sk) return Promise.resolve({ accepted: false, reason: 'NO_MAGIC_READY' }); var p = { skill_id: sk.id }; var aim = aimId(r, sk); if ((sk.targets || /SLOW|DISCORD|HEAL|ALLY_BUFF/.test(sk.effect)) && aim) p.aim_id = aim; if (sk.targets && sk.targets.indexOf('EXPLICIT_ALLY') >= 0 && state.allyConfirm) p.confirm_ally = true; if (/ZONE|TRAP|AIMED/.test(sk.effect + ' ' + (sk.mode || '')) && aim) { var t = r.others.filter(function (o) { return o.id === aim; })[0]; if (t) p.aim_point = { x: t.position.x, z: t.position.z }; } return send('RULES_CAST', p); },
    castSlot: function (slot) { var r = state.lastRules; if (!r) return Promise.resolve({ accepted: false, reason: 'NO_RULES' }); var list = r.skills[r.me.category] || []; var sk = list[slot]; if (!sk) return Promise.resolve({ accepted: false, reason: 'EMPTY_SLOT', slot: slot }); var p = { skill_id: sk.id }; var aim = aimId(r, sk); if ((sk.targets || /SLOW|DISCORD|HEAL|ALLY_BUFF/.test(sk.effect)) && aim) p.aim_id = aim; if (sk.targets && sk.targets.indexOf('EXPLICIT_ALLY') >= 0 && state.allyConfirm) p.confirm_ally = true; if (/ZONE|TRAP|AIMED/.test(sk.effect + ' ' + (sk.mode || '')) && aim) { var t = r.others.filter(function (o) { return o.id === aim; })[0]; if (t) p.aim_point = { x: t.position.x, z: t.position.z }; } return send('RULES_CAST', p); },
    slotSkill: function (slot) { var r = state.lastRules; if (!r) return null; return (r.skills[r.me.category] || [])[slot] || null; },
    cast: function (opts) { var r = state.lastRules; if (!r) return; var sk = currentSkill(r); var p = {}; var aim = aimId(r); if (sk && (sk.targets || /SLOW|DISCORD|HEAL|ALLY_BUFF/.test(sk.effect)) && aim) p.aim_id = aim; if (sk && sk.targets && sk.targets.indexOf('EXPLICIT_ALLY') >= 0 && (state.allyConfirm || (opts && opts.confirmAlly))) p.confirm_ally = true; if (sk && /ZONE|TRAP|AIMED/.test(sk.effect + ' ' + (sk.mode || '')) && aim) { var t = r.others.filter(function (o) { return o.id === aim; })[0]; if (t) p.aim_point = { x: t.position.x, z: t.position.z }; } return send('RULES_CAST', p); },
    select: function (cat, slot) { return select(cat, slot, 'rulesHud'); },   /* ONE shared selection function (gameHud.selectMove) */
    cycleAim: function () { var r = state.lastRules; var list = eligibleTargets(r); if (!list.length) return; state.aimIdx = (state.aimIdx + 1) % list.length; state.aim = list[state.aimIdx].o.id; log('aim → ' + state.aim); },
    key: function (code, ev) { var r = state.lastRules; if (!r) return false;
      switch (code) {
        case 'BracketRight': if (ev) ev.preventDefault(); api.cycleAim(); return true;   /* aim cycle moved off TAB (TAB = emotes) */
        case 'KeyN': send('RULES_NICHE', { on: !r.me.niche }); return true;
        case 'Digit9': api.quickMatch(1); return true;   /* moved off B (B = dash) */
        case 'KeyM': if (!(ev && ev.shiftKey)) return false; send('TEAM_MATCH', { op: 'END' }); return true;
        case 'Digit0': send('FIELD_ALLY', { op: r.others.some(function (o) { return o.id === 'PRACTICE_ALLY'; }) ? 'REMOVE' : 'SPAWN' }); return true;
        case 'KeyU': send('FIELD_INCOMING', { kind: 'MIXED' }); return true;
        default: return false;
      } },
    quickMatch: async function (size, passive) { var r = state.lastRules; if (r && r.match && r.match.state && r.match.state !== 'ENDED') { log('match exists — M ends it'); return; } if (r && r.match && r.match.state === 'ENDED') await send('TEAM_MATCH', { op: 'END' }); var s = await send('TEAM_MATCH', { op: 'START', size: size }); if (!s.accepted) return; return send('TEAM_MATCH', { op: 'BEGIN', passive_synthetics: !!passive }); },
    /* ---- entities + other combatants through the adapter ---- */
    renderEntities: function (p, adapter, dt, seen, meAccount) { var r = p.rules; if (!r) return; var npcIds = {}; (p.npcs || []).forEach(function (n) { npcIds['other:' + n.id] = true; }); (p.creatures || []).forEach(function (c) { npcIds['other:' + c.id] = true; }); (p.wildlife || []).forEach(function (w) { npcIds['other:' + w.id] = true; });   /* JOB B: forest creatures (p.creatures) are presented by lab/world/creatures.js and the wildlife (p.wildlife: fish / horse / phoenix) by lab/world/wildlife.js — the rules view must not mount them as class bodies (STABILITY 2026-09-20: every wild synthetic had become a hidden Athlete rig with its own animator — ~30 rigs, the phone regression) */ r.others.forEach(function (o) { var id = 'other:' + o.id; if (npcIds[id]) { seen[id] = true; return; } if (o.node) { seen[id] = true; return; }   /* B8 §14: a crystal-bush RESOURCE NODE is drawn by lab/world/gear.js (shards + hit proxy), never as a class body */ /* field NPCs are driven by play.js from p.npcs (class body, emotes, paired timeline); the rules view must not restart their clips */ seen[id] = true; if (!adapter.get(id)) adapter.mount(id, { kind: 'CHARACTER', self: false, class_id: o.class, label: o.id + ' (' + o.class + (o.team ? ' · ' + o.team : '') + ')' }); var hitAgo = Math.min(o.last_hit_ago_s === null || o.last_hit_ago_s === undefined ? 99 : o.last_hit_ago_s, o.last_touch_ago_s === null || o.last_touch_ago_s === undefined ? 99 : o.last_touch_ago_s); adapter.update(id, { position: { x: o.position.x, y: 0, z: o.position.z }, facing: o.facing, form: 'FUSED', mahloco: o.cast ? 'CAST' : 'IDLE', transforming: false, guard: o.guard, dash: null, flight: { powered: false }, attack: o.cast ? { attack_id: o.cast.skill, state: o.cast.phase === 'STARTUP' ? 'CONCENTRIC' : 'RECOVERY', category: o.cast.category, progress: o.cast.progress, profile: o.cast.presentation || null, strike: o.cast.strike || null } : null, emote: null, health01: o.max ? o.hp / o.max : 1, in_duel: r.context === 'MATCH' || r.context === 'PRACTICE', label: o.id, ko: o.ko, invisible: o.invisible, immune: o.immune, discord: o.discord, team: o.team, hit_ago_s: hitAgo, hit_dir: (function () { var h = o.last_hit_from; if (!h || !o.position) return 0; var ang = Math.atan2(h.x - o.position.x, -(h.z - o.position.z)); return Math.atan2(Math.sin(ang - (o.facing || 0)), Math.cos(ang - (o.facing || 0))); })(), status_text: o.statuses.map(function (s) { return s.kind; }).join(' ') }, dt); if (adapter.tag) adapter.tag(id, { level: o.level, lock: r.me.lock && r.me.lock.target === o.id ? r.me.lock : null, ko: o.ko, combo: o.statuses.some(function (s) { return s.kind === 'COMBO_LOCK'; }) }); });   /* owner interjection 2026-09-18 §3: level above the actor in free roam; level + health (the bar) in practice / match; the lock rides the tag — no LOCKED panel */
      r.entities.forEach(function (e) { if (e.type === 'IMPACT' && (e.cause === 'NEUTRAL' || e.cause === 'FREE_ROAM_TOUCH')) return;   /* owner 2026-09-18 §9.2: a neutral resident touched in free roam gets NO hit marker, flinch or burst — the entity exists for the host's record only */ var id = 'ent:' + e.id; seen[id] = true; if (!adapter.get(id)) adapter.mount(id, { kind: e.type === 'PROJECTILE' ? 'PROJECTILE' : (e.type === 'ZONE' ? 'ZONE' : (e.type === 'TRAP' ? 'TRAP' : 'IMPACT')), label: e.skill, radius: e.radius_m || 0.5, owner: e.owner, category: e.category, harmless: e.harmless, cause: e.cause || null, formation: e.formation || null, class_id: (e.owner === r.me.id ? r.me.class : (r.others.filter(function (o) { return o.id === e.owner; })[0] || {}).class) || r.me.class });   /* the emission carries its CASTER's class colour */ adapter.update(id, { position: { x: e.position.x, y: e.type === 'PROJECTILE' ? (e.y || 0) + 1.1 : 0, z: e.position.z }, heading: e.heading, remaining_s: e.remaining_s, active: true, formation: e.formation || null }, dt); }); }
  };
  return api;
}
