/* MAHWORLD :: FIELD STATIC COLLIDERS (development) — ONE authoritative collider set for player movement, dashes, flight,
   lock-on line of sight, melee visibility and projectiles. Pure functions over a versioned layout (rules_17_23.dev.json →
   _runtime_mapping.field_colliders, frozen with a match's ruleset). The client builds its visible structures FROM this same data,
   so every visible solid has a matching collider; the host never queries display geometry. Shapes: BOX {x1,z1,x2,z2,h,rounded?},
   CYLINDER {x,z,r,h}, RAMP {x1,z1,x2,z2,axis:'x'|'z',h0,h1} (walkable slope, never blocks). Swept capsule (circle in XZ) with sliding. */
export function createColliders(layout) {
  var L = layout || { version: 'none', shapes: [] }; var shapes = L.shapes || []; var R = L.body_radius_m || 0.4; var BODY_H = L.body_height_m || 1.7;
  /* S11 BROAD PHASE: district building proxies (hundreds of finite boxes each) are grouped under their building envelope; a query only walks a
     building's boxes when it is inside that envelope (+ body radius). Base plaza shapes are checked directly as before. */
  /* JOB B (2026-09-19) WORLD shapes (forest trunks, river kerbs, bridges, match hall, props — generated from lab/assets/world/world_registry_v1.json by
     deploy/jobb/build_world_colliders.mjs, tagged world:'JOBB' + zone) join the broad phase as zone groups and stay OUT of the per-snapshot base list: the client
     derives the same shapes from the same registry (lab/world/worldLayout.js) for its map / camera. `groups()` still lists the district buildings only. */
  function groupKey(s) { return s.district || (s.world && s.zone ? 'W:' + s.zone : null); }   /* a world shape without a zone (a room prop solid) stays in the base list */
  var base = shapes.filter(function (s) { return !groupKey(s); }); var groups = {}; shapes.forEach(function (s) { var gk = groupKey(s); if (!gk) return; var g = groups[gk] = groups[gk] || { id: gk, world: !!s.world, x1: 1e9, z1: 1e9, x2: -1e9, z2: -1e9, shapes: [] }; g.shapes.push(s); var bx1 = s.type === 'CYLINDER' ? s.x - s.r : s.x1, bx2 = s.type === 'CYLINDER' ? s.x + s.r : s.x2, bz1 = s.type === 'CYLINDER' ? s.z - s.r : s.z1, bz2 = s.type === 'CYLINDER' ? s.z + s.r : s.z2; g.x1 = Math.min(g.x1, bx1); g.z1 = Math.min(g.z1, bz1); g.x2 = Math.max(g.x2, bx2); g.z2 = Math.max(g.z2, bz2); }); var groupList = Object.keys(groups).map(function (k) { return groups[k]; }); var districtShapeN = 0, worldShapeN = 0; groupList.forEach(function (g) { if (g.world) worldShapeN += g.shapes.length; else districtShapeN += g.shapes.length; });
  function candidates(x, z, pad) { var out = base; groupList.forEach(function (g) { if (x >= g.x1 - pad && x <= g.x2 + pad && z >= g.z1 - pad && z <= g.z2 + pad) out = out.concat(g.shapes); }); return out; }
  function candidatesSeg(ax, az, bx, bz, pad) { var out = base; var minx = Math.min(ax, bx) - pad, maxx = Math.max(ax, bx) + pad, minz = Math.min(az, bz) - pad, maxz = Math.max(az, bz) + pad; groupList.forEach(function (g) { if (maxx >= g.x1 && minx <= g.x2 && maxz >= g.z1 && minz <= g.z2) out = out.concat(g.shapes); }); return out; }
  function inBoxXZ(s, x, z, pad) { return x >= s.x1 - pad && x <= s.x2 + pad && z >= s.z1 - pad && z <= s.z2 + pad; }
  function circleHitsShape(s, x, z, r) { if (s.type === 'BOX') { var cx = Math.max(s.x1, Math.min(s.x2, x)), cz = Math.max(s.z1, Math.min(s.z2, z)); return Math.hypot(x - cx, z - cz) < r; } if (s.type === 'CYLINDER') return Math.hypot(x - s.x, z - s.z) < r + s.r; return false; }
  function blocking(s, altitude, ground) { if (s.type === 'RAMP') return false; if (s.y0 !== undefined) return altitude < s.h - 0.2 && altitude + BODY_H > s.y0 + 0.05;   /* a finite-height piece (rim, deck slab, building storey): blocks a body whose height span overlaps it — under it or over it is free */ return (altitude - ground) < s.h - 0.2; }   /* y0: a raised guard (platform rim) that starts above the ground blocks only bodies at its level */   /* a body below the structure's top is blocked; flying over is allowed */
  function segHitsShape(s, ax, az, bx, bz, minHeight) { if (s.type === 'RAMP' || s.walkable || ((s.y0 || 0) + s.h) < minHeight || (s.y0 !== undefined && s.y0 > minHeight + 0.5)) return false;   /* B7 §2: the shape's TOP (base + height) vs the sight line — two bodies in the air see over everything below them */   /* a WALKABLE top (terrace, deck, platform) is ground, never a wall between two bodies standing on it (review 2026-09-20: the 2.6 m highland top blocked every line of sight on it) */ var steps = Math.max(2, Math.ceil(Math.hypot(bx - ax, bz - az) / 0.25)); for (var i = 0; i <= steps; i++) { var t = i / steps; if (circleHitsShape(s, ax + (bx - ax) * t, az + (bz - az) * t, 0.05)) return true; } return false; }
  var api = {
    version: L.version, shapes: shapes, baseShapes: base, bodyRadius: R, interactables: L.interactables || [], landmarks: L.landmarks || [],
    groundHeight: function (x, z, refY) { var g = 0, wg = null; candidates(x, z, 0).forEach(function (s) { if (s.water && s.walkable && s.type === 'BOX' && inBoxXZ(s, x, z, 0)) { wg = s.h; return; } if (s.water && s.type === 'RAMP' && inBoxXZ(s, x, z, 0)) { var tw = s.axis === 'x' ? (x - s.x1) / (s.x2 - s.x1) : (z - s.z1) / (s.z2 - s.z1); wg = s.h0 + (s.h1 - s.h0) * Math.max(0, Math.min(1, tw)); return; }   /* a beach slope: walkable ground that runs below zero into the water */   /* JOB B: the canal bed (wade floor) is ground below 0 — a bridge deck above it still wins */ if (s.type === 'RAMP' && inBoxXZ(s, x, z, 0)) { var t = s.axis === 'x' ? (x - s.x1) / (s.x2 - s.x1) : (z - s.z1) / (s.z2 - s.z1); var h = s.h0 + (s.h1 - s.h0) * Math.max(0, Math.min(1, t)); if (h > g) g = h; } if (s.type === 'BOX' && s.walkable && inBoxXZ(s, x, z, R * 0.9) && s.h > g && (refY === undefined || refY >= s.h - (s.low ? 1.7 : 0.8))) g = s.h; }); if (g === 0 && wg !== null) g = wg; return g; },   /* S11: support extends body-radius past a deck edge (no drop into the solid below); low ledges (≤ 1.6 m) are glided onto by the hovering body */   /* a raised walkable top is ground only for a body already near its level (never a lift for someone walking underneath) */
    blockedAt: function (x, z, altitude) { var ground = api.groundHeight(x, z); var list = candidates(x, z, R + 0.1); for (var i = 0; i < list.length; i++) { var s = list[i]; if (s.walkable) continue; if (blocking(s, altitude, ground) && circleHitsShape(s, x, z, R)) return s; } return null; },
    /* swept move with axis-separated sliding, sub-stepped so a dash or Lean sprint cannot tunnel */
    resolveMove: function (pos, dx, dz, altitude) { var out = { x: pos.x, z: pos.z, blocked: false, hit: null }; var len = Math.hypot(dx, dz); if (len < 1e-9) return out; var n = Math.max(1, Math.ceil(len / (R * 0.5))); var sx = dx / n, sz = dz / n; for (var i = 0; i < n; i++) { var nx = out.x + sx; if (!api.blockedAt(nx, out.z, altitude)) out.x = nx; else { out.blocked = true; out.hit = api.blockedAt(nx, out.z, altitude); } var nz = out.z + sz; if (!api.blockedAt(out.x, nz, altitude)) out.z = nz; else { out.blocked = true; out.hit = api.blockedAt(out.x, nz, altitude); } } return out; },
    lineOfSight: function (a, b, minHeight) { var mh = minHeight === undefined ? (L.los_min_height_m || 1.0) : minHeight; var list = candidatesSeg(a.x, a.z, b.x, b.z, 0.2); for (var i = 0; i < list.length; i++) if (segHitsShape(list[i], a.x, a.z, b.x, b.z, mh)) return { clear: false, blocker: list[i].id || list[i].type }; return { clear: true, blocker: null }; },
    /* first solid hit along a projectile segment at the given height; returns the impact point or null */
    projectileImpact: function (a, b, height) { var steps = Math.max(1, Math.ceil(Math.hypot(b.x - a.x, b.z - a.z) / 0.15)); for (var i = 1; i <= steps; i++) { var t = i / steps; var x = a.x + (b.x - a.x) * t, z = a.z + (b.z - a.z) * t; var list = candidatesSeg(a.x, a.z, b.x, b.z, 0.2); for (var k = 0; k < list.length; k++) { var s = list[k]; if (s.type === 'RAMP' || s.h < height || (s.y0 !== undefined && s.y0 > height)) continue; if (circleHitsShape(s, x, z, 0.1)) return { x: x, z: z, shape: s.id || s.type }; } } return null; },
    /* S11 vertical support: the solid piece a body at (x,z) would be inside at `altitude` (non-walkable), or null */
    solidAt: function (x, z, altitude) { var list = candidates(x, z, R); for (var i = 0; i < list.length; i++) { var s = list[i]; if (s.walkable || s.type === 'RAMP') continue; var y0 = s.y0 || 0; if (altitude >= y0 - 0.05 && altitude < s.h && circleHitsShape(s, x, z, R * 0.6)) return s; } return null; },
    /* the lowest slab / piece whose underside is above `altitude` within head clearance at (x,z) — flying up into a deck from below */
    ceilingAt: function (x, z, altitude) { var list = candidates(x, z, R); var best = null; for (var i = 0; i < list.length; i++) { var s = list[i]; if (s.type === 'RAMP') continue; var y0 = s.y0 || 0; if (y0 <= altitude + 0.1) continue; if (!circleHitsShape(s, x, z, R * 0.6)) continue; if (best === null || y0 < best) best = y0; } return best; },
    groups: function () { return groupList.filter(function (g) { return !g.world; }).map(function (g) { return { id: g.id, x1: g.x1, z1: g.z1, x2: g.x2, z2: g.z2, count: g.shapes.length }; }); },
    worldGroups: function () { return groupList.filter(function (g) { return g.world; }).map(function (g) { return { id: g.id, x1: +g.x1.toFixed(2), z1: +g.z1.toFixed(2), x2: +g.x2.toFixed(2), z2: +g.z2.toFixed(2), count: g.shapes.length }; }); },   /* JOB B world zones (read-out) */
    districtShapeCount: function () { return districtShapeN; },
    worldShapeCount: function () { return worldShapeN; },
    fingerprint: function () { return L.version + ':' + shapes.length; }
  };
  return api;
}
