/* MAHWORLD JOB B :: CLASS ARCHITECTURE (owner ARCHITECTURE add-on 2026-09-20 + next-pass §6/§7/§8/§16) — registry.architecture consumed as
   PLATINUM / CHROMIUM STRUCTURE + CLASS-COLOUR CRYSTAL + the SQUARE-DIAMOND world symbol + RESTRAINED ENERGY MOTION + VERTICALITY +
   GROUND INTEGRATION, over the shipped landmark derivatives (which stay untouched: this is an additive layer around them).
     ROOT SKIRT       the tree-base grammar at every building's ground contact: a platinum root wedge + a class crystal shard, leaning out
     ENERGY SEAMS     short vertical source-to-structure conduits (one merged mesh) plus a single low-cost arcane mist field
     SQUARE-DIAMOND   the one MAJOR animated identity feature per hero building: a hovering square bipyramid (platinum frame + crystal core)
                      with a slow spin + bob; ordinary buildings keep a smaller, slower crown; the match hall a platinum ring
     ENTRANCE         a platinum door frame + converging diamonds drifting toward the real door (secondary motion — never a barrier)
     ROOF DIAMONDS    the hero satellites pulsing in a slow rhythm (one InstancedMesh for all of them)
     CLASS HOUSES     LEAN spire house (three spires + crimson blades + a 22 m top platform), VISIONARY overlook (four supports, a slab,
                      a suspended amethyst core), TITAN gate (caps + a beam between the pillars) and ledge (slab on struts around the
                      mountain spire), BAGE basin rings (platinum frames + rose rim growth) — their colliders = worldLayout.architectureColliders
   Phone-first: transform / uniform animation only, ~20 draw calls total, motion frozen beyond MOTION_FAR_M, night = emissive up. */
import { groundYAt } from './worldLayout.js'; import { applySurface, applyCrystal } from './surfaceDetail.js'; import { showLevel, showForced, createFacadeKit } from './facadeKit.js';

var MOTION_FAR_M = 240; var SHOW_FORCED = showForced();

export function createArchitecture(ctx) {
  var THREE = ctx.THREE, log = ctx.log || function () { }; var reg = ctx.registry || {}; var A = reg.architecture || null; var FAM = reg.crystal_families || {};
  var group = null, own = [], night = !!ctx.night, clock = 0, FK = null; var crowns = [], seamMat = null, crystalMat = null, platMat = null, energyMats = [], entrance = null, sats = null, beams = [], aura = null, auraMat = null, auraAnchors = [];
  var info = { landmarks: 0, houses: 0, skirt_shards: 0, seams: 0, bands: 0, insets: 0, windows: 0, crowns: 0, entrance_diamonds: 0, roof_diamonds: 0, draw_calls: 0, tris: 0 };
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  function fam(id, key) { var f = FAM[id] || FAM.platinum || { color: '#dfe6ee', glow: '#ffffff', deep: '#7d8794' }; return new THREE.Color(f[key || 'color'] || '#dfe6ee').convertSRGBToLinear(); }
  function gy(x, z) { return groundYAt(reg, x, z); }
  var plat = [], crys = [], seams = [], stone = [];   /* merged buckets: platinum (no vertex colour), crystal (vertex colour), seams (vertex colour, band shader), graphite stone (world pivot PASS 3) */
  function pushColored(bucket, g, col, bright) { var ng = g.index ? g.toNonIndexed() : g; var n = ng.attributes.position.count; var cc = new Float32Array(n * 3); for (var i = 0; i < n; i++) { var b = bright ? bright(i) : 1; cc[i * 3] = col.r * b; cc[i * 3 + 1] = col.g * b; cc[i * 3 + 2] = col.b * b; } ng.setAttribute('color', new THREE.BufferAttribute(cc, 3)); bucket.push(ng); }
  function merge(list) { var pos = [], col = [], nor = [], hasC = list.length && !!list[0].attributes.color; list.forEach(function (g) { var ng = g.index ? g.toNonIndexed() : g; if (!ng.attributes.normal) ng.computeVertexNormals(); var p = ng.attributes.position, c = ng.attributes.color, nn = ng.attributes.normal; for (var i = 0; i < p.count; i++) { pos.push(p.getX(i), p.getY(i), p.getZ(i)); nor.push(nn.getX(i), nn.getY(i), nn.getZ(i)); if (hasC && c) col.push(c.getX(i), c.getY(i), c.getZ(i)); else if (hasC) col.push(1, 1, 1); } }); var out = new THREE.BufferGeometry(); out.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); out.setAttribute('normal', new THREE.Float32BufferAttribute(nor, 3)); if (hasC) out.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); return out; }
  function add(g, m, name) { var mesh = new THREE.Mesh(g, m); mesh.name = name; mesh.userData.noMerge = true; mesh.frustumCulled = true; mesh.castShadow = false; mesh.receiveShadow = false; group.add(mesh); info.draw_calls++; info.tris += Math.round(g.attributes.position.count / 3); return mesh; }
  /* --- the tree-base grammar: a platinum root wedge (a low tapered box) + a class crystal shard leaning outward --- */
  function rootShard(x, z, h, r, yaw, lean, family, seed) { var y0 = gy(x, z); var col = fam(family).lerp(fam(family, 'glow'), 0.2); var g = new THREE.OctahedronGeometry(1, 0); g.scale(r, h * 0.5, r * 0.8); g.rotateZ(lean); g.rotateY(yaw); g.translate(x, y0 + h * 0.42, z); var r1 = rnd(seed); pushColored(crys, g, col, function () { return 0.75 + 0.5 * r1(); }); var w = new THREE.BoxGeometry(r * 1.8, 0.28, r * 0.9); w.rotateY(yaw); w.translate(x, y0 + 0.14, z); plat.push(w); info.skirt_shards++; }
  var SKIRT_EX = null;   /* roads / forecourts / spurs / doors keep the root shards off them (review 2026-09-20) */
  function landmarkEntrances(L) { return L && L.entrances && L.entrances.length ? L.entrances : (L && L.entrance ? [L.entrance] : []); }
  function skirtExclusion() { if (SKIRT_EX) return SKIRT_EX; var PW = reg.paths || {}; var half = { CAUSEWAY: (PW.causeway_w || 20) / 2, REGIONAL: (PW.regional_w || 8) / 2, TRAIL: (PW.trail_w || 3) / 2 }; var segs = [], circles = []; (PW.list || []).forEach(function (P) { var hw = (half[P.tier] || 2) + 1.2; for (var i = 0; i < P.pts.length - 1; i++) segs.push({ a: P.pts[i], b: P.pts[i + 1], w: hw }); if (P.forecourt) circles.push({ x: P.forecourt.x, z: P.forecourt.z, r: (P.forecourt.r || 12) + 1.2 }); [P.spur, P.spur2].forEach(function (Sp) { if (Sp && Sp.to && P.forecourt) { segs.push({ a: [P.forecourt.x, P.forecourt.z], b: Sp.to, w: (PW.spur_w || 6) / 2 + 1.2 }); circles.push({ x: Sp.to[0], z: Sp.to[1], r: 4.5 }); } }); }); ((A && A.landmarks) || []).forEach(function (L) { landmarkEntrances(L).forEach(function (E) { circles.push({ x: E.x, z: E.z, r: (E.half_w_m || 4.2) + 2.5 }); }); }); (reg.field && reg.field.interactables || []).forEach(function (it) { circles.push({ x: it.x, z: it.z, r: 4 }); });
    SKIRT_EX = function (x, z) { for (var i = 0; i < circles.length; i++) { var c = circles[i]; if ((x - c.x) * (x - c.x) + (z - c.z) * (z - c.z) <= c.r * c.r) return true; } for (i = 0; i < segs.length; i++) { var s = segs[i]; var dx = s.b[0] - s.a[0], dz = s.b[1] - s.a[1]; var l2 = dx * dx + dz * dz || 1; var t = Math.max(0, Math.min(1, ((x - s.a[0]) * dx + (z - s.a[1]) * dz) / l2)); if (Math.hypot(x - (s.a[0] + dx * t), z - (s.a[1] + dz * t)) <= s.w) return true; } return false; }; return SKIRT_EX; }
  function skirtAround(env, S, family, seed) { var r0 = rnd(seed); var excl = skirtExclusion(); var cx = (env.x1 + env.x2) / 2, cz = (env.z1 + env.z2) / 2; var per = 2 * ((env.x2 - env.x1) + (env.z2 - env.z1)); for (var i = 0; i < S.count; i++) { var d = (i + r0() * 0.6) / S.count * per; var px, pz, nx, nz; var w = env.x2 - env.x1, dd = env.z2 - env.z1; if (d < w) { px = env.x1 + d; pz = env.z1; nx = 0; nz = -1; } else if (d < w + dd) { px = env.x2; pz = env.z1 + (d - w); nx = 1; nz = 0; } else if (d < 2 * w + dd) { px = env.x2 - (d - w - dd); pz = env.z2; nx = 0; nz = 1; } else { px = env.x1; pz = env.z2 - (d - 2 * w - dd); nx = -1; nz = 0; } var out = 0.6 + r0() * (S.r_out_m || 5); var h = S.h_m[0] + r0() * (S.h_m[1] - S.h_m[0]); var yaw = Math.atan2(nx, nz) + (r0() - 0.5) * 0.8; var sx = px + nx * out, sz = pz + nz * out; var tries = 0; while (excl(sx, sz) && tries < 6) { out = 0.6 + r0() * (S.r_out_m || 5); var dd2 = (r0() - 0.5) * 6; sx = px + nx * out + (nx === 0 ? dd2 : 0); sz = pz + nz * out + (nz === 0 ? dd2 : 0); tries++; } if (excl(sx, sz)) continue; rootShard(sx, sz, h, 0.22 + h * 0.13, yaw, -0.18 - r0() * 0.2, family, seed + i * 17); } }
  function seamAt(x, z, h, w, col) { var g = new THREE.BoxGeometry(w, h, w); g.translate(x, gy(x, z) + h / 2, z); pushColored(seams, g, col, function () { return 1; }); info.seams++; }
  var PROXY = {};   /* building id → its collider proxies (fetched once in build) */
  function facadeRadius(shapes, cx, cz, ang, y) { var ux = Math.cos(ang), uz = Math.sin(ang); var rMax = 60, last = 0; for (var r = 0; r <= rMax; r += 0.5) { var px = cx + ux * r, pz = cz + uz * r; var inside = false; for (var i = 0; i < shapes.length && !inside; i++) { var sh = shapes[i]; if ((sh.y0 || 0) > y || sh.h < y) continue; if (sh.type === 'BOX') inside = px >= sh.x1 && px <= sh.x2 && pz >= sh.z1 && pz <= sh.z2; else if (sh.type === 'CYLINDER') inside = (px - sh.x) * (px - sh.x) + (pz - sh.z) * (pz - sh.z) <= sh.r * sh.r; } if (inside) last = r; } return last; }
  /* owner B7 §6 / §7 (2026-09-20) — COLOUR WITH ARCHITECTURAL PURPOSE. The tall free-standing seam rods around every landmark are GONE (they
     pierced nothing, fed nothing, obscured the silhouettes). What replaces them is material-integrated and attached to the real façade
     (sampled from the district collider proxies at each height):
       · FOUNDATION CONDUITS (B energy function, A structural): short class-energy channels that rise from a crystal foot in the root skirt
         INTO the base mass — source = the ground crystal, destination = the building (the energy the crown draws up);
       · FAÇADE BANDS (E identity, B energy): two recessed horizontal energy seams hugging the façade at 1/3 and 2/3 height, the slow
         beam oscillation of the seam shader — a secondary motion, restrained;
       · CRYSTAL INSETS (E identity): a few class-crystal panes set INTO the façade between the bands, never on the door axis.
     Everything merges into the existing platinum / crystal / seam buckets (no new draw calls). */
  function facadeAt(lm, env, a, y, w) { var shapes = PROXY[lm.id] || null; var r = 0; if (shapes && shapes.length) { r = facadeRadius(shapes, lm.x, lm.z, a, y); if (r < 2) r = facadeRadius(shapes, lm.x, lm.z, a, Math.max(1.5, y * 0.5)); } if (!r || r < 2) { var hx = (env.x2 - env.x1) / 2, hz = (env.z2 - env.z1) / 2; r = Math.min(Math.abs(hx / Math.cos(a)) || 1e9, Math.abs(hz / Math.sin(a)) || 1e9); } return r; }
  function integratedFor(lm, env, S, family, entrance, hero) { var col = S.color ? new THREE.Color(S.color).convertSRGBToLinear() : fam(family, 'glow'); var H = env.height || 20; var cx = lm.x, cz = lm.z; var doorAng = entrance && entrance.outward ? Math.atan2(entrance.outward[1], entrance.outward[0]) : null; var offDoor = function (a) { return doorAng === null || Math.abs(Math.atan2(Math.sin(a - doorAng), Math.cos(a - doorAng))) > 0.42; };
    /* conduits: the diagonals (never the door axis), embedded half into the wall, a crystal foot at their base */
    var n = Math.min(S.count || 4, 6); var Hc = Math.min(9, Math.max(3.5, H * 0.22)); var w = 0.24;
    for (var i = 0; i < n; i++) { var a = Math.PI / 4 + i * (Math.PI * 2 / n); if (!offDoor(a)) a += 0.55; var r = facadeAt(lm, env, a, 1.5, w); var px = cx + Math.cos(a) * (r - w * 0.35), pz = cz + Math.sin(a) * (r - w * 0.35); seamAt(px, pz, Hc, w, col);
      var fx = cx + Math.cos(a) * (r + 0.55), fz = cz + Math.sin(a) * (r + 0.55); var fg = new THREE.OctahedronGeometry(1, 0); fg.scale(0.55, 1.05, 0.55); fg.rotateY(-a); fg.translate(fx, gy(fx, fz) + 0.75, fz); pushColored(crys, fg, fam(family).lerp(col, 0.35), function () { return 1.05; }); var cg = new THREE.BoxGeometry(1.3, 0.22, 0.9); cg.rotateY(-a); cg.translate(cx + Math.cos(a) * (r + 0.35), gy(fx, fz) + 0.11, cz + Math.sin(a) * (r + 0.35)); plat.push(cg); }
    /* M6: the old horizontal façade chord bands are intentionally gone.  Structure identity now comes from the inset crystals plus the
       slow arcane-leakage field built below; conduits remain attached to the façade and still explain where the energy enters. */
    /* crystal insets between the bands */
    var m = hero ? 8 : 5; for (var j = 0; j < m; j++) { var aj = j / m * Math.PI * 2 + 0.2 + (lm.x * 0.01); if (!offDoor(aj)) continue; var yj = H * (j % 2 ? 0.48 : 0.52) + (j % 3) * 0.6; var rj = facadeAt(lm, env, aj, yj, w); if (rj < 2) continue; var ig = new THREE.OctahedronGeometry(1, 0); ig.scale(0.7, 1.05, 0.26); ig.rotateY(Math.PI / 2 - aj); ig.translate(cx + Math.cos(aj) * (rj - 0.12), yj, cz + Math.sin(aj) * (rj - 0.12)); pushColored(crys, ig, fam(family).lerp(col, 0.45), function () { return 1.1; }); info.insets++; }
  }
  function auraTexture() { var c = document.createElement('canvas'); c.width = c.height = 96; var g = c.getContext('2d'), gr = g.createRadialGradient(48, 48, 3, 48, 48, 46); gr.addColorStop(0, 'rgba(255,255,255,0.72)'); gr.addColorStop(0.22, 'rgba(255,255,255,0.35)'); gr.addColorStop(0.62, 'rgba(255,255,255,0.11)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 96, 96); var t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; own.push(t); return t; }
  function buildAuras() { if (!auraAnchors.length) return; var pos = [], col = [], par = [], r0 = rnd(0xA11CE); auraAnchors.forEach(function (A) { var count = A.canopy ? 5 : (A.free ? 4 : (A.detail ? 7 : 18)), c = fam(A.family || 'platinum', 'glow'), dim = A.canopy ? 0.48 : (A.free ? 0.4 : (A.detail ? 0.72 : 1)); c.multiplyScalar(dim); for (var i = 0; i < count; i++) { pos.push(A.x, A.y, A.z); col.push(c.r, c.g, c.b); par.push(A.r * (0.62 + r0() * 0.42), r0(), A.h * (0.45 + r0() * 0.55), (A.canopy || A.free ? 0.009 : 0.018) + r0() * (A.canopy || A.free ? 0.009 : 0.018)); } }); var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); g.setAttribute('aAura', new THREE.Float32BufferAttribute(par, 4)); own.push(g); auraMat = new THREE.PointsMaterial({ map: auraTexture(), size: 1.65, sizeAttenuation: true, vertexColors: true, transparent: true, opacity: night ? 0.62 : 0.32, depthWrite: false, blending: THREE.AdditiveBlending, fog: true }); auraMat.onBeforeCompile = function (sh) { sh.uniforms.uT = { value: 0 }; auraMat.userData.shader = sh; sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nuniform float uT; attribute vec4 aAura; varying float vAuraFade;').replace('#include <begin_vertex>', 'float cyc = fract(aAura.y + uT * aAura.w); float ang = aAura.y * 6.2831853 + uT * aAura.w * 4.5; vec3 transformed = position; transformed.x += cos(ang) * aAura.x * (0.78 + 0.22 * sin(ang * 2.0)); transformed.z += sin(ang) * aAura.x; transformed.y += cyc * aAura.z + 0.16 * sin(ang * 1.7); vAuraFade = sin(cyc * 3.14159265);').replace('#include <color_vertex>', '#include <color_vertex>\nvColor.rgb *= 0.72 + 0.28 * vAuraFade;'); sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nvarying float vAuraFade;').replace('#include <map_particle_fragment>', '#include <map_particle_fragment>\ndiffuseColor.a *= smoothstep(0.0, 0.28, vAuraFade);'); }; auraMat.customProgramCacheKey = function () { return 'mahworld_arch_arcane_mist_v2'; }; own.push(auraMat); aura = new THREE.Points(g, auraMat); aura.name = 'ARCH_ARCANE_LEAKAGE'; aura.userData.noMerge = true; aura.frustumCulled = false; aura.renderOrder = 3; group.add(aura); info.aura_particles = pos.length / 3; info.aura_anchors = auraAnchors.length; info.draw_calls++; }
  function crown(x, y, z, C, family, hero) { var g = new THREE.Group(); g.position.set(x, y, z); var s = C.size_m || 4; var core, frame;
    if (C.kind === 'RING') { core = new THREE.Mesh(new THREE.TorusGeometry(s / 2, s * 0.05, 8, 40), platMat); core.rotation.x = Math.PI / 2; g.add(core); var em = energyMat(fam(family, 'glow'), 0.8); frame = new THREE.Mesh(new THREE.TorusGeometry(s / 2 - s * 0.09, s * 0.02, 6, 40), em); frame.rotation.x = Math.PI / 2; g.add(frame); info.draw_calls += 2; info.tris += 8 * 40 * 2 + 6 * 40 * 2; }
    else { var cg = new THREE.OctahedronGeometry(1, 0); cg.scale(s * 0.36, s * 0.5, s * 0.36); var cc = fam(family).lerp(fam(family, 'glow'), 0.3); var ccol = new Float32Array(cg.attributes.position.count * 3); for (var i = 0; i < cg.attributes.position.count; i++) { var b = 0.8 + 0.35 * ((i * 53) % 5) / 5; ccol[i * 3] = cc.r * b; ccol[i * 3 + 1] = cc.g * b; ccol[i * 3 + 2] = cc.b * b; } cg.setAttribute('color', new THREE.BufferAttribute(ccol, 3)); core = new THREE.Mesh(cg, crystalMat); g.add(core);
      var fr = []; var hw = s / 2, t = s * 0.045; [[0, hw], [hw, 0], [0, -hw], [-hw, 0]].forEach(function (p, k) { var bg = new THREE.BoxGeometry(k % 2 === 0 ? s : t, t, k % 2 === 0 ? t : s); bg.translate(p[0], 0, p[1]); fr.push(bg); }); frame = new THREE.Mesh(merge(fr), platMat); frame.rotation.y = Math.PI / 4;   /* the platinum square frame turned 45°: the SQUARE-DIAMOND symbol read from the ground and the sky */ g.add(frame); info.draw_calls += 2; info.tris += 8 + 48; }
    if (hero && C.kind !== 'RING') { var hw2 = (s / 2) * Math.SQRT2; var dcol = fam(family).lerp(fam(family, 'glow'), 0.5); [[hw2, 0], [0, hw2], [-hw2, 0], [0, -hw2]].forEach(function (pc, ci) { var dg = new THREE.OctahedronGeometry(1, 0); dg.scale(s * 0.09, s * 0.14, s * 0.09); var dcc = new Float32Array(dg.attributes.position.count * 3); for (var q = 0; q < dg.attributes.position.count; q++) { dcc[q * 3] = dcol.r; dcc[q * 3 + 1] = dcol.g; dcc[q * 3 + 2] = dcol.b; } dg.setAttribute('color', new THREE.BufferAttribute(dcc, 3)); var dm = new THREE.Mesh(dg, crystalMat); dm.position.set(pc[0], 0, pc[1]); g.add(dm); info.roof_diamonds++; info.draw_calls++; info.tris += 8; }); }   /* B7 §6: the hero's roof diamonds ride the crown frame corners (a hovering square-diamond rail) — attached, spinning with the crown */
    g.userData.noMerge = true; group.add(g); crowns.push({ g: g, y: y, spin: (C.spin_rps || 0.05) * Math.PI * 2, bob: C.bob_m || 0, phase: crowns.length * 1.7, hero: !!hero, frame: frame, core: core }); info.crowns++; return g; }
  function energyMat(col, op) { var m = new THREE.MeshBasicMaterial({ color: col, transparent: op < 1, opacity: op, depthWrite: op >= 1 }); m.userData.base = col.clone(); energyMats.push(m); own.push(m); return m; }
  function doorFrame(E, family) {
    var ox = E.outward[0], oz = E.outward[1], lx = -oz, lz = ox, col = fam(family, 'glow');
    var H = E.height_m || 6.4, W = E.half_w_m || 4.2;
    [-1, 1].forEach(function (sgn) { var px = E.x + lx * sgn * W + ox * 0.9, pz = E.z + lz * sgn * W + oz * 0.9; var g = new THREE.BoxGeometry(0.7, H, 0.7); g.translate(px, gy(px, pz) + H / 2, pz); plat.push(g); var sg = new THREE.BoxGeometry(0.16, H * 0.8, 0.16); sg.translate(px + ox * 0.45, gy(px, pz) + H * 0.45, pz + oz * 0.45); pushColored(seams, sg, col, function () { return 1; }); });
    var lg = new THREE.BoxGeometry(Math.abs(lx) * (2 * W + 0.7) + Math.abs(ox) * 0.7, 0.7, Math.abs(lz) * (2 * W + 0.7) + Math.abs(oz) * 0.7); lg.translate(E.x + ox * 0.9, gy(E.x, E.z) + H + 0.35, E.z + oz * 0.9); plat.push(lg);
    var dg = new THREE.OctahedronGeometry(1, 0); dg.scale(0.55, 0.8, 0.55); dg.translate(E.x + ox * 0.9, gy(E.x, E.z) + H + 1.4, E.z + oz * 0.9); pushColored(crys, dg, fam(family).lerp(col, 0.3), function () { return 1; });
    var sw = Math.abs(lx) * (2 * W) + Math.abs(ox) * 0.08, sd = Math.abs(lz) * (2 * W) + Math.abs(oz) * 0.08; var screen = new THREE.Mesh(new THREE.BoxGeometry(sw, H * 0.78, sd), energyMat(col, 0.16)); screen.name = 'ARCH_DOOR_SCREEN_' + (E.door || 'PORTAL'); screen.position.set(E.x + ox * 0.94, gy(E.x, E.z) + H * 0.39, E.z + oz * 0.94); screen.userData.noMerge = true; group.add(screen); info.draw_calls++; info.tris += 12;
  }
  /* WORLD PIVOT PASS 3 — premium dressing of the procedural class houses (reference: the futuristic building — structure first, light
     second). Everything is visual-only and host-safe: collars / capitals / fascias sit on or inside the existing supports and platform
     footprints, every free-standing piece (halo ring, suspended core, struts, needle tips) is above 3.4 m. Merged into the existing
     buckets + one graphite stone bucket, so the whole pass adds one draw call. */
  function lineBox(bucket, x1, y, z1, x2, z2, t, h, col) { var dx = x2 - x1, dz = z2 - z1; var g = new THREE.BoxGeometry(Math.abs(dx) || t, h, Math.abs(dz) || t); g.translate((x1 + x2) / 2, y, (z1 + z2) / 2); if (col) pushColored(bucket, g, col, function () { return 1; }); else bucket.push(g); }
  function fascia(P, top, glow) { var ins = 0.12; var e = [[P.x1 + ins, P.z1 + ins, P.x2 - ins, P.z1 + ins], [P.x2 - ins, P.z1 + ins, P.x2 - ins, P.z2 - ins], [P.x2 - ins, P.z2 - ins, P.x1 + ins, P.z2 - ins], [P.x1 + ins, P.z2 - ins, P.x1 + ins, P.z1 + ins]];
    e.forEach(function (q) { lineBox(stone, q[0], top - 0.95, q[1], q[2], q[3], 0.3, 0.9); lineBox(seams, q[0], top - 1.42, q[1], q[2], q[3], 0.08, 0.06, new THREE.Color(0xffffff)); });   /* graphite fascia band + a white light line under it */
    var cx = (P.x1 + P.x2) / 2, cz = (P.z1 + P.z2) / 2, r = Math.min(P.x2 - P.x1, P.z2 - P.z1) * 0.3; var dia = [[cx, cz - r], [cx + r, cz], [cx, cz + r], [cx - r, cz]]; for (var i = 0; i < 4; i++) { var a = dia[i], b = dia[(i + 1) % 4], L = Math.hypot(b[0] - a[0], b[1] - a[1]); var g = new THREE.BoxGeometry(L, 0.05, 0.1); g.rotateY(-Math.atan2(b[1] - a[1], b[0] - a[0])); g.translate((a[0] + b[0]) / 2, top - 1.03, (a[1] + b[1]) / 2); pushColored(seams, g, glow, function () { return 1; }); } }   /* the square-diamond light inlay on the soffit */
  function premiumHouse(H, base, famId, glow) { var P = H.platform, top = P ? base + P.h : 0;
    if (H.supports) { var R = H.ring_r || 7, SH = H.support_h || 14, sr = H.support_r || 0.55;
      for (var k = 0; k < H.supports; k++) { var a = Math.PI / 4 + k * Math.PI / 2, sx = H.x + Math.cos(a) * R, sz = H.z + Math.sin(a) * R;
        var col = new THREE.TorusGeometry(sr * 1.55, 0.12, 6, 20); col.rotateX(Math.PI / 2); col.translate(sx, base + 3.6, sz); plat.push(col);
        var drum = new THREE.CylinderGeometry(sr + 0.03, sr + 0.05, 1.0, 16); drum.translate(sx, base + 0.5, sz); stone.push(drum);   /* M11: a stone drum at the foot (≤ 5 cm proud) */
        for (var rvI = 0; rvI < 6; rvI++) { var rva = rvI / 6 * Math.PI * 2 + a, rvH = (P ? top - 2.3 : base + SH - 0.6) - (base + 1.1), rvg = new THREE.BoxGeometry(0.04, rvH, 0.03); rvg.rotateY(-rva); rvg.translate(sx + Math.cos(rva) * sr * 0.975, base + 1.1 + rvH / 2, sz + Math.sin(rva) * sr * 0.975); stone.push(rvg); }   /* M11: six graphite reveals up the shaft (inside its radius) */
        if (P) { var cap = new THREE.CylinderGeometry(1.3, sr * 1.05, 1.2, 10); cap.translate(sx, top - 1.6, sz); plat.push(cap); }   /* the capital flares into the soffit */
        var tipC = new THREE.ConeGeometry(sr * 0.9, 1.6, 8); tipC.translate(sx, base + SH + 0.8, sz); plat.push(tipC); }
      var halo = new THREE.TorusGeometry(R, 0.24, 8, 72); halo.rotateX(Math.PI / 2); halo.translate(H.x, base + SH - 0.3, H.z); plat.push(halo);
      var hl = new THREE.TorusGeometry(R - 0.34, 0.06, 5, 72); hl.rotateX(Math.PI / 2); hl.translate(H.x, base + SH - 0.3, H.z); pushColored(seams, hl, glow, function () { return 1; });   /* the cantilevered halo ring that ties the four supports */
      if (P) { var core = new THREE.OctahedronGeometry(1, 0); core.scale(1.15, 1.9, 1.15); core.translate(H.x, top - 1.05 - 1.9, H.z); pushColored(crys, core, fam(famId).lerp(glow, 0.3), function () { return 1.1; });   /* the suspended amethyst core under the soffit (lowest point ≥ 3.4 m) */
        for (var c = 0; c < 4; c++) { var ca = c / 4 * Math.PI * 2 + 0.4, sh = new THREE.OctahedronGeometry(1, 0); sh.scale(0.35, 0.8, 0.35); sh.translate(H.x + Math.cos(ca) * 2.3, top - 2.2 - (c % 2) * 0.6, H.z + Math.sin(ca) * 2.3); pushColored(crys, sh, fam(famId), function () { return 0.9; }); } } }
    if (H.spires) { H.spires.forEach(function (sp) { var x = H.x + sp.dx, z = H.z + sp.dz;
        for (var y = 4, n = 0; y < sp.h - 1.5; y += 4, n++) { var rr = sp.r - (sp.r - sp.r * 0.32) * (y / sp.h); var t = new THREE.TorusGeometry(rr + 0.05, n % 2 ? 0.05 : 0.09, 5, 20); t.rotateX(Math.PI / 2); t.translate(x, base + y, z); if (n % 2) pushColored(seams, t, glow, function () { return 1; }); else plat.push(t); }   /* platinum collars alternating with crimson light rings */
        var nd = new THREE.ConeGeometry(sp.r * 0.3, 3.4, 6); nd.translate(x, base + sp.h + 1.7, z); plat.push(nd); });   /* needle tips */
      if (P) { var cx = (P.x1 + P.x2) / 2, cz = (P.z1 + P.z2) / 2; H.spires.slice(1).forEach(function (sp) { var x = H.x + sp.dx, z = H.z + sp.dz, ty = base + sp.h - 1.2; var dx = x - cx, dz = z - cz, dy = ty - (top - 1.2); var L = Math.hypot(dx, dy, dz); var st = new THREE.CylinderGeometry(0.16, 0.22, L, 6); var q = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 1, 0), new THREE.Vector3(dx, dy, dz).normalize()); st.applyMatrix4(new THREE.Matrix4().compose(new THREE.Vector3(cx + dx / 2, top - 1.2 + dy / 2, cz + dz / 2), q, new THREE.Vector3(1, 1, 1))); plat.push(st); }); } }   /* struts from the top platform to the lower spires */
    if (P && (H.supports || H.spires)) fascia(P, top, glow); }
  async function build() {
    if (!A) { log('architecture: registry.architecture missing — nothing built'); return; }
    try { var col = await fetch(ctx.url('../play/rules1723/district_v1_colliders.json')).then(function (r) { return r.ok ? r.json() : null; }); var MAPID = { temple: 'LM_TEMPLE', gym: 'LM_GYM', tower: 'LM_TOWER', market: 'LM_MARKET' }; if (col && col.shapes) col.shapes.forEach(function (sh) { var id = MAPID[sh.district] || sh.district; (PROXY[id] = PROXY[id] || []).push(sh); }); } catch (e) { log('architecture: district proxies unavailable (' + (e && e.message) + ') → envelope seams'); }
    var hallA = (reg.artifacts || []).filter(function (a) { return a.id === 'MATCH_HALL'; })[0]; if (hallA && hallA.position && hallA.footprint) PROXY.MATCH_HALL = [{ type: 'BOX', x1: hallA.position[0] - hallA.footprint.w / 2, z1: hallA.position[2] - hallA.footprint.d / 2, x2: hallA.position[0] + hallA.footprint.w / 2, z2: hallA.position[2] + hallA.footprint.d / 2, y0: 0, h: hallA.footprint.h }];
    group = new THREE.Group(); group.name = 'MAHWORLD_ARCHITECTURE'; group.userData.noMerge = true; ctx.group.add(group); FK = createFacadeKit(THREE, { tier: (function () { try { return ctx.quality && ctx.quality.tier ? ctx.quality.tier() : 'HIGH'; } catch (e) { return 'HIGH'; } })(), night: night, show: SHOW_FORCED });   /* M8E: the facade kit (windows, frames, practical light) for the class houses */
    platMat = new THREE.MeshStandardMaterial({ color: 0xc4cbd5, roughness: 0.38, metalness: 0.7, envMapIntensity: 0.6 }); own.push(platMat);   /* WORLD PIVOT PASS 3: satin anodised platinum (was a near-white mirror under the daylight key), matching the civic buildings */
    var stoneMat = new THREE.MeshStandardMaterial({ color: 0x3a3f4a, roughness: 0.62, metalness: 0.3, envMapIntensity: 0.4 }); own.push(stoneMat);
    (function () { var tier = 'HIGH'; try { tier = ctx.quality && ctx.quality.tier ? ctx.quality.tier() : 'HIGH'; } catch (e) { } applySurface(THREE, platMat, 'STRUCTURE', tier); applySurface(THREE, stoneMat, 'STONE', tier); })();   /* M8: panelled structure + stone grain on the class houses / crowns / plinths */
    crystalMat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.12, metalness: 0.5, envMapIntensity: 0.7, transparent: true, opacity: 0.9, emissive: 0xffffff, emissiveIntensity: 0.08, flatShading: true }); crystalMat.onBeforeCompile = function (sh) { sh.fragmentShader = sh.fragmentShader.replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n\ttotalEmissiveRadiance = emissive * vColor.rgb;'); }; crystalMat.customProgramCacheKey = function () { return 'mahworld_arch_crystal'; }; (function () { var tier = 'HIGH'; try { tier = ctx.quality && ctx.quality.tier ? ctx.quality.tier() : 'HIGH'; } catch (e) { } applyCrystal(THREE, crystalMat, { tier: tier }); })(); own.push(crystalMat);   /* M8C: class crystal = cut stone (per-facet value, face-on depth, grazing rim, inclusion planes); the class hue stays the vertex colour */
    seamMat = new THREE.MeshBasicMaterial({ vertexColors: true, color: 0xffffff }); seamMat.onBeforeCompile = function (sh) { sh.uniforms.uT = { value: 0 }; sh.uniforms.uHi = { value: night ? 1.0 : 0.6 }; sh.uniforms.uShow = { value: 0 }; seamMat.userData.shader = sh;
      sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nvarying float vWy;').replace('#include <begin_vertex>', '#include <begin_vertex>\nvWy = position.y;');
      sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nuniform float uT; uniform float uHi; uniform float uShow; varying float vWy;').replace('#include <color_fragment>', '#include <color_fragment>\n{ float band = fract(vWy * 0.06 - uT * 0.22); float k = smoothstep(0.0, 0.18, band) * (1.0 - smoothstep(0.3, 0.55, band)); float beat = 0.5 + 0.5 * sin(6.2832 * uT * 0.45); diffuseColor.rgb *= uHi * mix(0.55 + 0.75 * k, 0.45 + 1.15 * beat, uShow); }'); };   /* M8E: in the plaza show every sanctuary pulses in its OWN colour on the shared beat */ seamMat.customProgramCacheKey = function () { return 'mahworld_arch_seam'; }; own.push(seamMat);
    var lms = {}; ((ctx.layout && ctx.layout.landmarks) || []).forEach(function (l) { lms[l.id] = l; });
    var hall = (reg.artifacts || []).filter(function (a) { return a.id === 'MATCH_HALL'; })[0]; if (hall && hall.position && hall.footprint) lms.MATCH_HALL = { id: 'MATCH_HALL', x: hall.position[0], z: hall.position[2], envelope: { x1: hall.position[0] - hall.footprint.w / 2, z1: hall.position[2] - hall.footprint.d / 2, x2: hall.position[0] + hall.footprint.w / 2, z2: hall.position[2] + hall.footprint.d / 2, height: hall.footprint.h }, height_m: hall.footprint.h };
    (A.landmarks || []).forEach(function (L, li) { var lm = lms[L.id]; if (!lm || !lm.envelope) { log('architecture: landmark ' + L.id + ' has no layout envelope → skipped'); return; } var env = lm.envelope; env.height = env.height || lm.height_m || 20; var famId = L.id === 'LM_GYM' ? 'blue' : (L.family || 'platinum'), entrances = landmarkEntrances(L);
      if (L.skirt) skirtAround(env, L.skirt, famId, 0xA5C1 + li * 977);
      if (L.seams) integratedFor(lm, env, L.seams, famId, L.entrance, L.hero);
      if (L.crown) crown(lm.x, env.height + (L.crown.hover_m || 4), lm.z, L.crown, famId, L.hero);
      entrances.forEach(function (E) { if (E.outward) doorFrame(E, famId); });
      auraAnchors.push({ x: lm.x, y: gy(lm.x, lm.z) + 0.25, z: lm.z, r: Math.max(env.x2 - env.x1, env.z2 - env.z1) * 0.56 + 2.5, h: Math.min(18, env.height * 0.62), family: famId });
      /* B7 §6: the four hero roof diamonds no longer float free around the spire — they ride the CROWN's square frame corners (crown()) */
      info.landmarks++; });
    /* --- CLASS HOUSES --- */
    (A.class_houses || []).forEach(function (H, hi) { var Tz = H.terrace ? ((reg.terraces && reg.terraces.list) || []).filter(function (t) { return t.id === H.terrace; })[0] : null; var base = Tz ? Tz.h : 0; var famId = H.family || 'platinum'; var glow = fam(famId, 'glow'); var r0 = rnd(0xC1A5 + hi * 311);
      (H.spires || []).forEach(function (sp, si) { var x = H.x + sp.dx, z = H.z + sp.dz; var g = new THREE.CylinderGeometry(sp.r * 0.32, sp.r, sp.h, 8); g.translate(x, base + sp.h / 2, z); plat.push(g); if (FK && sp.h >= 14) FK.addSpire({ id: H.id + '_S' + si, x: x, z: z, base: base, h: sp.h, r: sp.r, rTop: sp.r * 0.32, sides: 8, seed: 0x5E1 + hi * 97 + si, door: si === 0 ? Math.atan2(-x, -z) : undefined });   /* M8E: slots + a door — the spire house is lived in */ for (var b = 0; b < 5; b++) { var hy = base + sp.h * (0.18 + b * 0.16); var ang = r0() * Math.PI * 2; var bl = new THREE.OctahedronGeometry(1, 0); var bh = 1.2 + r0() * 1.6; bl.scale(0.28, bh * 0.5, 0.2); bl.rotateZ(-0.55); bl.rotateY(ang); bl.translate(x + Math.cos(ang) * sp.r * 0.9, hy, z - Math.sin(ang) * sp.r * 0.9); pushColored(crys, bl, fam(famId).lerp(glow, 0.25), function () { return 0.8 + 0.4 * r0(); }); } for (var s2 = 0; s2 < 6; s2++) { var a2 = s2 / 6 * Math.PI * 2 + r0() * 0.5; var d2 = sp.r + 0.6 + r0() * 2.2; rootShard(x + Math.cos(a2) * d2, z + Math.sin(a2) * d2, 1.0 + r0() * 2.2, 0.32 + r0() * 0.3, a2 + Math.PI / 2, -0.25, famId, 0xD1 + si * 7 + s2); } seamAt(x + sp.r * 0.8, z, sp.h * 0.8, 0.22, glow); });
      if (H.supports) { for (var k = 0; k < H.supports; k++) { var ang2 = Math.PI / 4 + k * Math.PI / 2; var sx = H.x + Math.cos(ang2) * (H.ring_r || 7), sz = H.z + Math.sin(ang2) * (H.ring_r || 7); var sg = new THREE.CylinderGeometry(H.support_r || 0.55, (H.support_r || 0.55) * 1.4, H.support_h || 14, 8); sg.translate(sx, base + (H.support_h || 14) / 2, sz); plat.push(sg); seamAt(sx + Math.cos(ang2) * 0.62, sz + Math.sin(ang2) * 0.62, (H.support_h || 14) * 0.9, 0.16, glow); for (var s3 = 0; s3 < 4; s3++) { var a3 = s3 / 4 * Math.PI * 2 + r0(); var d3 = 1.0 + r0() * 1.8; rootShard(sx + Math.cos(a3) * d3, sz + Math.sin(a3) * d3, 0.8 + r0() * 1.6, 0.26 + r0() * 0.2, a3 + Math.PI / 2, -0.25, famId, 0xE1 + k * 11 + s3); } } }
      if (H.platform) { var P = H.platform; var top = base + P.h; var pw = P.x2 - P.x1, pd = P.z2 - P.z1; var slab = new THREE.BoxGeometry(pw, 0.5, pd); slab.translate((P.x1 + P.x2) / 2, top - 0.25, (P.z1 + P.z2) / 2); plat.push(slab); var under = new THREE.BoxGeometry(pw - 1.2, 0.5, pd - 1.2); under.translate((P.x1 + P.x2) / 2, top - 0.75, (P.z1 + P.z2) / 2); pushColored(crys, under, fam(famId, 'deep'), function () { return 1; });
        [[P.x1, P.z1, P.x2, P.z1], [P.x2, P.z1, P.x2, P.z2], [P.x2, P.z2, P.x1, P.z2], [P.x1, P.z2, P.x1, P.z1]].forEach(function (e) { var dx = e[2] - e[0], dz = e[3] - e[1]; var eg = new THREE.BoxGeometry(Math.abs(dx) || 0.14, 0.12, Math.abs(dz) || 0.14); eg.translate((e[0] + e[2]) / 2, top + 0.06, (e[1] + e[3]) / 2); pushColored(seams, eg, glow, function () { return 1; }); });   /* the rim seam: the platform reads as a lit destination from the air */
        var ins = new THREE.CylinderGeometry(Math.min(pw, pd) * 0.28, Math.min(pw, pd) * 0.28, 0.06, 4); ins.rotateY(Math.PI / 4); ins.translate((P.x1 + P.x2) / 2, top + 0.03, (P.z1 + P.z2) / 2); pushColored(crys, ins, fam(famId).lerp(glow, 0.2), function () { return 1; });   /* the square-diamond inlay on the deck */
        if (H.kind === 'LEDGE') { var mo = (function () { var best = null; ((reg.regions && reg.regions.list) || []).forEach(function (R) { (R.monoliths || []).forEach(function (m) { if (m.x >= P.x1 && m.x <= P.x2 && m.z >= P.z1 && m.z <= P.z2) best = m; }); }); return best; })(); var ax = mo ? mo.x : (P.x1 + P.x2) / 2, az = mo ? mo.z : (P.z1 + P.z2) / 2; [[P.x1 + 1, P.z1 + 1], [P.x2 - 1, P.z1 + 1], [P.x2 - 1, P.z2 - 1], [P.x1 + 1, P.z2 - 1]].forEach(function (c) { var dx = ax - c[0], dz = az - c[1], dy = -(P.h - 1.0); var Ln = Math.hypot(dx, dy, dz); var st = new THREE.CylinderGeometry(0.22, 0.32, Ln, 6); var m4 = new THREE.Matrix4(); var q = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 1, 0), new THREE.Vector3(dx, dy, dz).normalize()); m4.compose(new THREE.Vector3(c[0] + dx / 2, top - 0.5 + dy / 2, c[1] + dz / 2), q, new THREE.Vector3(1, 1, 1)); st.applyMatrix4(m4); plat.push(st); }); } }
      (H.pillars || []).forEach(function (q, qi) { var ring = new THREE.CylinderGeometry(3.4, 3.8, 0.4, 12); ring.translate(q.x, gy(q.x, q.z) + 0.2, q.z); plat.push(ring); crown(q.x, gy(q.x, q.z) + 13.2, q.z, { kind: 'SQUARE_DIAMOND', size_m: 2.2, hover_m: 0, spin_rps: 0.03, bob_m: 0.15 }, famId, false); });
      if (H.kind === 'GATE' && H.pillars && H.pillars.length === 2) { var p0 = H.pillars[0], p1 = H.pillars[1]; var bx = (p0.x + p1.x) / 2, bz = (p0.z + p1.z) / 2; var bl2 = Math.hypot(p1.x - p0.x, p1.z - p0.z) - 4.8; var bg2 = new THREE.BoxGeometry(bl2, 0.18, 0.18); var beam = new THREE.Mesh(bg2, energyMat(glow, 0.85)); beam.position.set(bx, 10.6, bz); beam.rotation.y = -Math.atan2(p1.z - p0.z, p1.x - p0.x); beam.userData.noMerge = true; group.add(beam); beams.push({ m: beam, y: 10.6, ph: hi }); info.draw_calls++; info.tris += 12; }
      (H.rings || []).forEach(function (R, ri) { var hole = ((reg.water && reg.water.rivers) || []).filter(function (r) { return r.id === R.hole; })[0]; if (!hole) return; [[R.x1, R.z1, R.x2, hole.z1], [R.x1, hole.z2, R.x2, R.z2], [R.x1, hole.z1, hole.x1, hole.z2], [hole.x2, hole.z1, R.x2, hole.z2]].forEach(function (b) { if (b[2] - b[0] < 0.5 || b[3] - b[1] < 0.5) return; var bg = new THREE.BoxGeometry(b[2] - b[0], R.h, b[3] - b[1]); bg.translate((b[0] + b[2]) / 2, R.h / 2, (b[1] + b[3]) / 2); plat.push(bg); }); var rim = [[hole.x1, hole.z1, hole.x2, hole.z1], [hole.x2, hole.z1, hole.x2, hole.z2], [hole.x2, hole.z2, hole.x1, hole.z2], [hole.x1, hole.z2, hole.x1, hole.z1]]; rim.forEach(function (e) { var dx = e[2] - e[0], dz = e[3] - e[1]; var eg = new THREE.BoxGeometry(Math.abs(dx) || 0.14, 0.1, Math.abs(dz) || 0.14); eg.translate((e[0] + e[2]) / 2 - Math.sign(dx === 0 ? (e[0] - (hole.x1 + hole.x2) / 2) : 0) * 0.1, R.h + 0.05, (e[1] + e[3]) / 2 - Math.sign(dz === 0 ? (e[1] - (hole.z1 + hole.z2) / 2) : 0) * 0.1); pushColored(seams, eg, glow, function () { return 1; }); }); var per = 2 * ((hole.x2 - hole.x1) + (hole.z2 - hole.z1)); for (var g2 = 0; g2 < 22; g2++) { var d = (g2 + r0() * 0.7) / 22 * per; var w = hole.x2 - hole.x1, dd = hole.z2 - hole.z1, px, pz; if (d < w) { px = hole.x1 + d; pz = hole.z1 - 0.9; } else if (d < w + dd) { px = hole.x2 + 0.9; pz = hole.z1 + (d - w); } else if (d < 2 * w + dd) { px = hole.x2 - (d - w - dd); pz = hole.z2 + 0.9; } else { px = hole.x1 - 0.9; pz = hole.z2 - (d - 2 * w - dd); } var sh = new THREE.OctahedronGeometry(1, 0); var hh = 0.35 + r0() * 0.7; sh.scale(0.16 + hh * 0.15, hh * 0.5, 0.14); sh.rotateY(r0() * 3); sh.translate(px, R.h + hh * 0.42, pz); pushColored(crys, sh, fam(famId).lerp(glow, 0.3), function () { return 0.8 + 0.4 * r0(); }); info.skirt_shards++; } });
      premiumHouse(H, base, famId, glow);
      if (H.crown) { var cy = H.platform ? base + H.platform.h + (H.crown.hover_m || 3) : base + (H.crown.hover_m || 3); crown(H.x, cy, H.z, H.crown, famId, true); }
      auraAnchors.push({ x: H.x, y: Math.max(base, gy(H.x, H.z)) + 0.18, z: H.z, r: H.ring_r ? H.ring_r + 3 : 8.5, h: H.platform ? Math.min(15, H.platform.h * 0.7 + 4) : 11, family: famId });
      info.houses++; });
    if (FK) { try { FK.build(group); info.facade = FK.info(); } catch (e) { log('architecture: facade kit failed (' + (e && e.message) + ')'); } }
    /* --- ENTRANCE DIAMONDS (one InstancedMesh: 4 per entrance, drifting toward the door on the shared timeline) --- */
    var ents = []; (A.landmarks || []).forEach(function (L) { landmarkEntrances(L).forEach(function (E) { if (E.outward) ents.push({ E: E, fam: L.id === 'LM_GYM' ? 'blue' : (L.family || 'platinum') }); }); });
    if (ents.length) { var eg2 = new THREE.OctahedronGeometry(1, 0); eg2.scale(0.42, 0.62, 0.42); var em2 = new THREE.MeshStandardMaterial({ vertexColors: false, color: 0xffffff, roughness: 0.15, metalness: 0.4, transparent: true, opacity: 0.9, emissive: 0xffffff, emissiveIntensity: 0.5, flatShading: true }); em2.onBeforeCompile = function (sh) { sh.fragmentShader = sh.fragmentShader.replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n#ifdef USE_COLOR\n\ttotalEmissiveRadiance = emissive * vColor.rgb * 0.8;\n#endif'); }; em2.customProgramCacheKey = function () { return 'mahworld_arch_entrance'; }; own.push(em2); var im = new THREE.InstancedMesh(eg2, em2, ents.length * 4); im.name = 'ARCH_ENTRANCE_DIAMONDS'; im.userData.noMerge = true; im.frustumCulled = false; var col = new THREE.Color(); var items = []; ents.forEach(function (e, ei) { for (var k = 0; k < 4; k++) { var idx = ei * 4 + k; col.copy(fam(e.fam).lerp(fam(e.fam, 'glow'), 0.4)); im.setColorAt(idx, col); items.push({ E: e.E, k: k, idx: idx, y0: gy(e.E.x, e.E.z) + 3.4 }); } }); im.instanceColor.needsUpdate = true; group.add(im); entrance = { mesh: im, items: items, m4: new THREE.Matrix4(), q: new THREE.Quaternion(), e: new THREE.Euler(), v: new THREE.Vector3(), s: new THREE.Vector3() }; info.entrance_diamonds = items.length; info.draw_calls++; info.tris += 8 * items.length; }
    /* --- ROOF DIAMONDS (the hero satellites: one InstancedMesh, pulsing scale + a slow orbit-less bob) --- */
    function em2ish(sh) { sh.fragmentShader = sh.fragmentShader.replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n#ifdef USE_COLOR\n\ttotalEmissiveRadiance = emissive * vColor.rgb * 0.8;\n#endif'); }
    ((reg.resource_patches && reg.resource_patches.list) || []).forEach(function (P, i) { if (i % 3 === 0) auraAnchors.push({ x: P.x, y: gy(P.x, P.z) + 0.12, z: P.z, r: (P.r || 2.2) * 0.8, h: 1.8, family: P.family, detail: true }); });
    /* M6 closeout: a deliberately sparse canopy/free-floating extension of the SAME mist field. One selected existing tree per authored
       forest zone receives five dim points at its crown; every third selected crown also gets four still-dimmer motes above it. This is
       derived from the authoritative forest placements, adds no mesh/system/draw call, and cannot blanket the world. */
    var TP = ctx.forestPlacement || [], TZ = {}, TL = reg.tree_lock || {}, ZF = TL.zone_family || {}; TP.forEach(function (T) { (TZ[T.zone || 'UNZONED'] = TZ[T.zone || 'UNZONED'] || []).push(T); }); var canopySamples = [];
    Object.keys(TZ).sort().slice(0, 8).forEach(function (zone, zi) { var list = TZ[zone], T = list[Math.floor(list.length * 0.5)], sc = +T.scale || 1, th = Math.max(9, Math.min(15, 10.9 * sc)), family = ZF[zone] || 'platinum', cy = gy(T.x, T.z) + th * 0.72; auraAnchors.push({ x: T.x, y: cy, z: T.z, r: 1.45 + sc * 0.5, h: 1.45, family: family, canopy: true }); canopySamples.push({ id: T.id, zone: zone, family: family, x: +T.x.toFixed(2), y: +cy.toFixed(2), z: +T.z.toFixed(2) }); if (zi % 3 === 1) auraAnchors.push({ x: T.x + 0.8, y: cy + 2.2, z: T.z - 0.5, r: 1.1, h: 2.2, family: family, free: true }); }); info.canopy_aura_anchors = canopySamples.length; info.free_aura_anchors = Math.floor((canopySamples.length + 1) / 3); info.canopy_aura_samples = canopySamples;
    if (plat.length) add(merge(plat), platMat, 'ARCH_PLATINUM'); if (stone.length) add(merge(stone), stoneMat, 'ARCH_STONE'); if (crys.length) add(merge(crys), crystalMat, 'ARCH_CRYSTAL'); if (seams.length) add(merge(seams), seamMat, 'ARCH_SEAMS'); buildAuras();
    applyNight(night); log('architecture: ' + info.landmarks + ' landmarks + ' + info.houses + ' class houses → ' + info.skirt_shards + ' root shards, ' + info.seams + ' seams, ' + info.crowns + ' crowns, ' + info.entrance_diamonds + ' entrance diamonds, ' + info.roof_diamonds + ' roof diamonds, ' + info.draw_calls + ' draw calls, ' + info.tris + ' tris' + (Object.keys(PROXY).length ? ' (seams fitted to ' + Object.keys(PROXY).join('/') + ' proxies)' : ''));
  }
  function motionFar() { var T = null; try { T = ctx.quality && ctx.quality.get ? ctx.quality.get() : null; } catch (e) { T = null; } return T && T.lod_far_m > 0 ? Math.min(MOTION_FAR_M, T.lod_far_m) : MOTION_FAR_M; }   /* the quality tier caps the animated reach (LOW 120 m) */
  function tick(dt, t) { if (!group) return; clock = (typeof t === 'number' && isFinite(t)) ? t : clock + (dt || 0); if (FK) FK.tick(dt, clock); var sh = seamMat && seamMat.userData.shader; if (sh) { sh.uniforms.uT.value = clock; sh.uniforms.uShow.value = showLevel(clock, night, SHOW_FORCED); } var ash = auraMat && auraMat.userData.shader; if (ash) ash.uniforms.uT.value = clock; var cam = ctx.cameraPos(); var MOTION_FAR_M = motionFar();
    for (var i = 0; i < crowns.length; i++) { var c = crowns[i]; var d = Math.hypot(c.g.position.x - cam.x, c.g.position.z - cam.z); if (d > MOTION_FAR_M) continue; c.g.rotation.y = clock * c.spin + c.phase; c.g.position.y = c.y + Math.sin(clock * 0.45 + c.phase) * c.bob; if (c.hero && c.core) { var pu = 1 + 0.04 * Math.sin(clock * 1.1 + c.phase); c.core.scale.setScalar(pu); } }
    for (i = 0; i < beams.length; i++) { var b = beams[i]; b.m.position.y = b.y + Math.sin(clock * 0.7 + b.ph) * 0.25; b.m.material.opacity = 0.7 + 0.25 * Math.sin(clock * 1.6 + b.ph); }
    if (entrance) { var E = entrance; var any = false; for (i = 0; i < E.items.length; i++) { var it = E.items[i]; var dE = Math.hypot(it.E.x - cam.x, it.E.z - cam.z); if (dE > MOTION_FAR_M) continue; any = true; var ph = (clock * 0.11 + it.k * 0.25) % 1; var dist = 1.6 + (1 - ph) * 7.2; var side = (it.k % 2 ? 1 : -1) * (1.8 - ph * 1.4); var ox = it.E.outward[0], oz = it.E.outward[1]; var lx = -oz, lz = ox; E.v.set(it.E.x + ox * dist + lx * side, it.y0 + Math.sin(clock * 0.9 + it.k) * 0.18 + ph * 0.6, it.E.z + oz * dist + lz * side); E.e.set(0, clock * 0.8 + it.k, 0); E.q.setFromEuler(E.e); var sc = 0.5 + 0.5 * Math.sin(ph * Math.PI); E.s.setScalar(Math.max(0.05, sc)); E.m4.compose(E.v, E.q, E.s); E.mesh.setMatrixAt(it.idx, E.m4); } if (any) E.mesh.instanceMatrix.needsUpdate = true; }
  }
  function applyNight(n) { night = !!n; if (FK) FK.setNight(night); if (crystalMat) crystalMat.emissiveIntensity = night ? 0.4 : 0.08; if (auraMat) auraMat.opacity = night ? 0.62 : 0.32; var sh = seamMat && seamMat.userData.shader; if (sh) sh.uniforms.uHi.value = night ? 1.0 : 0.6; energyMats.forEach(function (m) { m.color.copy(m.userData.base).multiplyScalar(night ? 1.0 : 0.85); }); }
  function setNight(n) { applyNight(n); }
  function dispose() { if (FK) { FK.dispose(); FK = null; } if (group && group.parent) group.parent.remove(group); if (group) group.traverse(function (o) { if (o.isMesh && o.geometry) o.geometry.dispose(); }); own.forEach(function (m) { m.dispose(); }); own = []; crowns = []; beams = []; entrance = null; sats = null; group = null; }
  function debug() { return { landmarks: info.landmarks, houses: info.houses, skirt_shards: info.skirt_shards, seams: info.seams, bands: info.bands, insets: info.insets, crowns: info.crowns, aura_particles: info.aura_particles || 0, aura_anchors: info.aura_anchors || 0, canopy_aura_anchors: info.canopy_aura_anchors || 0, free_aura_anchors: info.free_aura_anchors || 0, canopy_aura_samples: info.canopy_aura_samples || [], aura_language: 'ARCANE_LEAKAGE_MIST', entrance_diamonds: info.entrance_diamonds, roof_diamonds: info.roof_diamonds, draw_calls: info.draw_calls, tris: info.tris, night: night, motion_far_m: motionFar() }; }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug };
}
