import { applyGeology } from './surfaceDetail.js'; import { skyWater } from './water.js'; import { ridgeReachBounds } from './ridgeLayout.js';
import { mergeVertices } from '../../vendor/three/BufferGeometryUtils.js'; import { rockBlock } from './ridgeCrags.js';
/* MAHWORLD JOB B :: COAST, SEA AND ISLANDS (owner note 2026-09-19: "we need multiple bodies of land — it's a vast world; where the water
   meets the land it must be very gradual, like a beach with waves").
   The mainland is ONE island: its floor ends at a rounded coast beyond the field walls (registry.coast.outline), a BEACH RING slopes from the
   floor edge (y 0) through the waterline down to beach_drop_m under the sea over beach_w (the dry → wet → deep shore gradient), and the SEA
   (a single cheap animated plane at sea_y with the water look, a hole under the mainland) runs to the horizon. Other LANDMASSES stand in the
   sea at 300–650 m: elliptical islands (beach ring + rising plateau + crystal spires + instanced sapphire tree silhouettes) — scenery beyond
   the walls, no colliders (the field walls stay the playable limit), hazed by the fog for depth. FOAM lines lap in and out along every
   waterline (≈ 5 s swing). Draw calls: coast 3 (floor edge ring, sea, foam) + islands 4 (land, spires, trees, island foam). No per-frame allocations. */
export function createCoast(ctx) {
  var THREE = ctx.THREE, M = ctx.M || {}, log = ctx.log || function () { };
  var group = null, meshes = [], own = [], sea = null, seaMat = null, townGlassMat = null, treeGlow = null, foam = [], clock = 0, night = !!ctx.night, C = null, info = { islands: 0, draw_calls: 0, tris: 0 };
  var DAY = { color: 0x2b4760, rough: 0.2, env: 0.85, opacity: 0.94 }, NIGHT = { color: 0x0e2a48, rough: 0.28, env: 0.7, opacity: 0.95 };   /* a sea that reads BLUE at grazing angles; WORLD PIVOT PASS 2: brighter azure by day, more sky reflection and sun glitter (M20: under the storm-light sky the azure #1f5fb0 read as a cheap saturated plane — a slate blue #2b4760, still BLUE, a sea under an overcast) */
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  /* rounded-rectangle outline sampled as N points with outward normals (perimeter order) */
  function outlinePoints(o, n) { var w = o.x2 - o.x1, d = o.z2 - o.z1, r = Math.min(o.corner_r || 0, w / 2, d / 2); var cx = (o.x1 + o.x2) / 2, cz = (o.z1 + o.z2) / 2; var pts = [];
    var segs = [[o.x1 + r, o.z1, o.x2 - r, o.z1, 0, -1], [o.x2, o.z1 + r, o.x2, o.z2 - r, 1, 0], [o.x2 - r, o.z2, o.x1 + r, o.z2, 0, 1], [o.x1, o.z2 - r, o.x1, o.z1 + r, -1, 0]];
    var corners = [[o.x2 - r, o.z1 + r, -Math.PI / 2, 0], [o.x2 - r, o.z2 - r, 0, Math.PI / 2], [o.x1 + r, o.z2 - r, Math.PI / 2, Math.PI], [o.x1 + r, o.z1 + r, Math.PI, Math.PI * 1.5]];
    var per = 2 * (w - 2 * r) + 2 * (d - 2 * r) + 2 * Math.PI * r; var step = per / n;
    for (var k = 0; k < 4; k++) { var s = segs[k]; var L = Math.hypot(s[2] - s[0], s[3] - s[1]); var m = Math.max(1, Math.round(L / step)); for (var i = 0; i < m; i++) { var t = i / m; pts.push({ x: s[0] + (s[2] - s[0]) * t, z: s[1] + (s[3] - s[1]) * t, nx: s[4], nz: s[5] }); }
      var c = corners[k]; var mc = Math.max(2, Math.round(Math.PI / 2 * r / step)); for (var j = 0; j < mc; j++) { var a = c[2] + (c[3] - c[2]) * j / mc; var nx = Math.cos(a), nz = Math.sin(a);   /* angle measured in the (x, z) plane */ pts.push({ x: c[0] + nx * r, z: c[1] + nz * r, nx: nx, nz: nz }); } }
    if (o.organic_m) pts.forEach(function (p) { p.off = coastOffset(o, p.x, p.z); });   /* WORLD PIVOT PASS 2: headlands + bays, outward only */
    return pts; }
  /* WORLD PIVOT PASS 2 (owner 2026-09-25: eliminate the "flat game plate"): the mainland coast breathes OUTWARD from the registry rounded
     rectangle by a smooth periodic profile (0 … organic_m) around its centre — headlands and bays instead of a machined slab edge. The field
     walls, colliders and every playable metre are untouched; the sea hole, the foam line and seaTest all use the same offset. */
  function coastOffset(o, x, z) { var A = +o.organic_m || 0; if (!A) return 0; var th = Math.atan2(z - (o.z1 + o.z2) / 2, x - (o.x1 + o.x2) / 2); var f = 0.5 + 0.28 * Math.sin(2 * th + 0.7) + 0.18 * Math.sin(5 * th + 1.9) + 0.1 * Math.sin(9 * th + 0.4) - 0.06 * Math.sin(13 * th + 2.2); return A * Math.max(0, Math.min(1, f)); }
  function ellipsePoints(cx, cz, rx, rz, n) { var pts = []; for (var i = 0; i < n; i++) { var a = i / n * Math.PI * 2; var nx = Math.cos(a) * rz, nz = Math.sin(a) * rx; var l = Math.hypot(nx, nz) || 1; pts.push({ x: cx + Math.cos(a) * rx, z: cz + Math.sin(a) * rz, nx: nx / l, nz: nz / l }); } return pts; }
  /* a band mesh from an outline: rings at distances ds[] along the normal, y from prof(d), uv (u along, v by ring) */
  function band(pts, ds, prof, vOf) { var n = pts.length, R = ds.length; var pos = [], uv = [], idx = []; for (var k = 0; k < R; k++) for (var i = 0; i < n; i++) { var p = pts[i]; var d = ds[k], dd = d + (d > 0 ? (p.off || 0) : 0); pos.push(p.x + p.nx * dd, prof(d, i), p.z + p.nz * dd); uv.push(i / 9, vOf(d)); }
    for (var k2 = 0; k2 < R - 1; k2++) for (var i2 = 0; i2 < n; i2++) { var a = k2 * n + i2, b = k2 * n + (i2 + 1) % n, c = (k2 + 1) * n + i2, e = (k2 + 1) * n + (i2 + 1) % n; idx.push(a, c, b, b, c, e); }
    var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2)); g.setIndex(idx); return faceUp(g); }
  /* every band / plateau must face UP whatever the outline's winding: flip the triangles when the mean normal points down */
  function faceUp(g) { g.computeVertexNormals(); var nn = g.attributes.normal, sy = 0; for (var i = 0; i < nn.count; i++) sy += nn.getY(i); if (sy < 0) { var ix = g.index; if (ix) { for (var k = 0; k < ix.count; k += 3) { var t = ix.getX(k + 1); ix.setX(k + 1, ix.getX(k + 2)); ix.setX(k + 2, t); } ix.needsUpdate = true; } else { var p = g.attributes.position; for (var k2 = 0; k2 < p.count; k2 += 3) { var x1 = p.getX(k2 + 1), y1 = p.getY(k2 + 1), z1 = p.getZ(k2 + 1); p.setXYZ(k2 + 1, p.getX(k2 + 2), p.getY(k2 + 2), p.getZ(k2 + 2)); p.setXYZ(k2 + 2, x1, y1, z1); } } g.computeVertexNormals(); } return g; }
  function shapeFrom(pts) { var sh = new THREE.Shape(); pts.forEach(function (p, i) { if (i === 0) sh.moveTo(p.x, -p.z); else sh.lineTo(p.x, -p.z); }); sh.closePath(); return sh; }   /* plane y = −world z (rotated −90° about x) */
  function add(geo, mat, name, order) { var m = new THREE.Mesh(geo, mat); m.name = name; m.userData.noMerge = true; m.frustumCulled = false; m.receiveShadow = false; m.castShadow = false; if (order !== undefined) m.renderOrder = order; group.add(m); meshes.push(m); info.draw_calls++; info.tris += Math.round((geo.index ? geo.index.count : geo.attributes.position.count) / 3); return m; }
  function foamTexture() { var c = document.createElement('canvas'); c.width = 256; c.height = 64; var g = c.getContext('2d'); g.clearRect(0, 0, 256, 64); var rr = rnd(77); for (var i = 0; i < 44; i++) { var x = rr() * 256, y = 12 + rr() * 40, r = 6 + rr() * 14; var gr = g.createRadialGradient(x, y, 0, x, y, r); gr.addColorStop(0, 'rgba(255,255,255,0.9)'); gr.addColorStop(0.5, 'rgba(255,255,255,0.35)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(x - r, y - r, 2 * r, 2 * r); } var t = new THREE.CanvasTexture(c); t.wrapS = THREE.RepeatWrapping; t.wrapT = THREE.ClampToEdgeWrapping; t.colorSpace = THREE.SRGBColorSpace; return t; }

  function build() {
    C = ctx.registry && ctx.registry.coast; if (!C || !C.outline) { log('coast: registry.coast missing — nothing built'); return; }
    group = new THREE.Group(); group.name = 'MAHWORLD_COAST'; group.userData.noMerge = true; ctx.group.add(group);
    var shoreMat = M.shore || M.sand || new THREE.MeshStandardMaterial({ color: 0xb8b3a8, roughness: 0.85 }); var BW = C.beach_w || 34, DROP = C.beach_drop_m || 1.6, WL = C.waterline_d || 8, SEA = C.sea_y !== undefined ? C.sea_y : -0.3;
    /* the beach profile: y 0 at the floor edge, gently down to the waterline (sea_y at d = WL), then on to −DROP at d = BW (a beach, never a wall) */
    var prof = function (d) { if (d <= WL) { var t = d / WL; return SEA * (t * t * (3 - 2 * t)); } var u = (d - WL) / (BW - WL); return SEA + (-DROP - SEA) * (u * u * (3 - 2 * u)); };
    var vOf = function (d) { return Math.min(1, d <= WL ? 0.17 * Math.pow(d / WL, 1.8) : 0.17 + 0.83 * Math.pow((d - WL) / (BW - WL), 0.8)); };   /* M9 (audit: the beach read as a dark moat from above): most of the dry side stays pale sand, damp then a narrow wet band at the waterline, then deep */
    /* 1. mainland beach ring */
    var pts = outlinePoints(C.outline, 240); var ds = [0, 0.01, 2.5, 5, WL, WL + 4, WL + 9, WL + 15, BW];   /* the 0.01 row carries the flat organic land out to the shifted beach */ add(band(pts, ds, prof, vOf), shoreMat, 'COAST_BEACH');
    /* 2. the sea: one big plane at sea_y with a hole under the mainland (the beach ring passes under the water at the waterline) */
    var seaSize = 1800; var seaShape = new THREE.Shape(); seaShape.moveTo(-seaSize / 2, -seaSize / 2); seaShape.lineTo(seaSize / 2, -seaSize / 2); seaShape.lineTo(seaSize / 2, seaSize / 2); seaShape.lineTo(-seaSize / 2, seaSize / 2); seaShape.closePath();
    var holePts = outlinePoints(C.outline, 120).map(function (p) { var dd = WL - 1.5 + (p.off || 0); return { x: p.x + p.nx * dd, z: p.z + p.nz * dd }; }); var hole = new THREE.Path(); holePts.forEach(function (p, i) { if (i === 0) hole.moveTo(p.x, -p.z); else hole.lineTo(p.x, -p.z); }); hole.closePath(); seaShape.holes.push(hole);
    var seaG = new THREE.ShapeGeometry(seaShape, 1); var sp = seaG.attributes.position, su = seaG.attributes.uv; for (var i = 0; i < sp.count; i++) su.setXY(i, sp.getX(i) / 13, sp.getY(i) / 13); su.needsUpdate = true; seaG.rotateX(-Math.PI / 2); seaG.translate(0, SEA, 0);
    seaMat = new THREE.MeshStandardMaterial({ color: DAY.color, roughness: DAY.rough, metalness: 0.3, transparent: true, opacity: DAY.opacity, envMapIntensity: DAY.env, side: THREE.FrontSide }); own.push(seaMat);
    if (ctx.waterNormalTex) { seaMat.normalMap = ctx.waterNormalTex; seaMat.normalScale = new THREE.Vector2(0.16, 0.16); }   /* the canal's drifting normal map (the same texture object: its offset animates both surfaces) */
    sea = add(seaG, seaMat, 'COAST_SEA', 1);
    /* the SEA as a ripple body: outside the mainland's rounded outline (+ waterline) and outside every island's ellipse (+ its waterline) */
    var O = C.outline, R = Math.min(O.corner_r || 0, (O.x2 - O.x1) / 2, (O.z2 - O.z1) / 2); var isl0 = C.islands || [];
    var seaTest = function (x, z) { var dx = Math.max(O.x1 + R - x, 0, x - (O.x2 - R)), dz = Math.max(O.z1 + R - z, 0, z - (O.z2 - R)); var d = Math.hypot(dx, dz) - R; if (d < WL - 1.5 + coastOffset(O, x, z)) return false; for (var i = 0; i < isl0.length; i++) { var I = isl0[i]; var bw = Math.max(16, Math.min(40, I.rx * 0.32)); var wl = bw * 0.28; var ex = (x - I.x) / (I.rx + wl), ez = (z - I.z) / (I.rz + wl); if (ex * ex + ez * ez < 1) return false; } return true; };
    ctx.seaTest = seaTest; ctx.seaY = SEA; if (ctx.ripples && ctx.ripples.setSea) { ctx.ripples.setSea(seaTest, SEA, seaMat); log('coast: sea registered as a ripple body (surface ' + SEA + ')'); }
    /* WORLD PIVOT PASS 2: break the visible prototype tiling — the drifting normal map is sampled twice (1× and 0.37× with an offset) and
       blended, so the 13 m repeat no longer reads as a regular diamond grid; PASS 2b: the ripple relief calms with view distance (90 → 650 m) so
       the far sea reads as reflected sky from the HALO and the overview instead of a woven texture. CHAINED after the ripple system's hole patch (which owns
       onBeforeCompile when enabled); guarded: if the chunk text ever changes, the plain map stays. */
    if (seaMat.normalMap) { var chunk = THREE.ShaderChunk && THREE.ShaderChunk.normal_fragment_maps, from = 'vec3 mapN = texture2D( normalMap, vNormalMapUv ).xyz * 2.0 - 1.0;';
      if (chunk && chunk.indexOf(from) >= 0) { var prevOBC = seaMat.onBeforeCompile, prevKey = seaMat.customProgramCacheKey;
        seaMat.onBeforeCompile = function (sh, r) { if (prevOBC) prevOBC.call(this, sh, r); sh.fragmentShader = sh.fragmentShader.replace('#include <normal_fragment_maps>', chunk.replace(from, 'vec3 mapN = normalize( ( texture2D( normalMap, vNormalMapUv ).xyz * 2.0 - 1.0 ) + ( texture2D( normalMap, vNormalMapUv * 0.37 + vec2( 0.31, 0.17 ) ).xyz * 2.0 - 1.0 ) * 0.85 ); mapN.xy *= 1.0 - 0.8 * smoothstep( 90.0, 650.0, length( vViewPosition ) );')); };
        seaMat.customProgramCacheKey = function () { return (prevKey ? prevKey.call(this) : '') + '|mahworld-sea-dual-normal'; }; seaMat.needsUpdate = true; } }
    /* M20: the sea as water — the sky it mirrors (Fresnel), a dark dielectric body, calm and wind-roughened patches, and translucent shallows
       clearing toward the mainland's waterline (water.js skyWater) */
    (function () { var O2 = C.outline, off = WL - 1.5, R2 = Math.min(O2.corner_r || 0, (O2.x2 - O2.x1) / 2, (O2.z2 - O2.z1) / 2); skyWater(THREE, seaMat, ctx, { shore: { rect: [O2.x1 - off, O2.z1 - off, O2.x2 + off, O2.z2 + off], r: R2 + off, islands: [] } }); })();   /* the mainland beach only: the islands' own shore band sits under the sea and read as a dark slab through clearing water */
    /* 3. islands: beach ring (sea_y − DROP → 0) + a rising plateau + crystal spires + tree silhouettes (instanced) */
    var LQ = ctx.quality && ctx.quality.tier ? String(ctx.quality.tier()).toUpperCase() : 'HIGH'; var landMat = new THREE.MeshStandardMaterial({ color: 0x585e6b, roughness: 0.88, metalness: 0.04, flatShading: LQ === 'LOW', envMapIntensity: 0.2 }); own.push(landMat); applyGeology(THREE, landMat, { strata: 1.6, ledge: 0.3, macro: 0.14, relief: [3.5, 12], tier: LQ, facets: LQ === 'HIGH' ? [16, 9, 0.22, 1400] : null, bend: 2.5, groundUV: true });   /* M20 round 2: the rock a step paler (#4b5366 → #585e6b, still a cool graphite): across the south sea the island read as one flat dark slab */   /* M20: smooth-shaded rock (the flat facets printed the mound's triangles) broken into fracture planes with soft creases and bent, broken beds — the same rock language as the ridges; LOW keeps the M18 island shader and its flat facets (applyGeology drops facets / bend on LOW). Review fix (an in-reach camera showed the crowns as a hard quilt of light / dark triangles: the geology's along-face axis switched x ↔ z per triangle on this gentle ground): groundUV — every island slope is under ≈ 30°, so the rock is mapped on the ground plane, continuous over the whole surface, and the crown planes tilt half as far; the planes on HIGH only (MED, a phone tier: smooth rock, bent beds, continuous mapping) */   /* M9: a step lighter (aerial perspective), macro relief like the ridges */   /* M8C: island rock (was a glossy dark-sapphire metal at metalness 0.35) */ var spireMat = (M.crystal || new THREE.MeshStandardMaterial({ color: 0xe8f4ff, roughness: 0.1, metalness: 0.6 })).clone(); spireMat.vertexColors = true; own.push(spireMat); var FAMS = ctx.registry && ctx.registry.crystal_families || {};   /* island spires carry their island's crystal family (owner redirect 2026-09-19: regions read from afar) */ var treeMat = M.sapphire || new THREE.MeshStandardMaterial({ color: 0x1c2a46 });
    var landGeos = [], spireGeos = [], treeMats = []; var treeCount = 0; var isl = C.islands || []; var foamPts = [];
    var townBody = [], townGlass = [], TQ = ctx.quality && ctx.quality.tier ? String(ctx.quality.tier()).toUpperCase() : 'HIGH';
    isl.forEach(function (I) { var rr = rnd(I.seed || 5); var n = 72; var ring = ellipsePoints(I.x, I.z, I.rx, I.rz, n); var bw = Math.max(16, Math.min(40, I.rx * 0.32)); var wl = bw * 0.28; var iprof = function (d) { if (d <= wl) { var t = d / wl; return SEA * (t * t * (3 - 2 * t)); } var u = (d - wl) / (bw - wl); return SEA + (-DROP - SEA) * (u * u * (3 - 2 * u)); }; var ivOf = function (d) { return Math.min(1, d <= wl ? 0.17 * Math.pow(d / wl, 1.8) : 0.17 + 0.83 * Math.pow((d - wl) / (bw - wl), 0.8)); };
      var beach = band(ring, [0, wl * 0.4, wl, wl + bw * 0.25, bw], iprof, ivOf); beach.computeVertexNormals(); landGeos.push({ g: beach, shore: true });
      /* plateau. M9 (audit: a dark low-poly mound straight off a thin beach): more rings, a profile that rises from a low sandy shelf into a
         rocky crown, smooth angular noise (headlands and coves, one steeper cliff side) instead of per-vertex jitter */ var RB0 = ridgeReachBounds(ctx.registry), outReach = I.x - I.rx > RB0.x2 || I.x + I.rx < RB0.x1 || I.z - I.rz > RB0.z2 || I.z + I.rz < RB0.z1, M20 = !I.reachable && TQ !== 'LOW' && outReach, K = M20 ? 12 : 9; (info.m20_islands = info.m20_islands || {})[I.id] = M20;   /* M20 lead fix — HOST SAFETY (hard rule 4, wave-2 re-review): the rock-island profile raised ISLE_SW's corner INSIDE the ±300 m reach square by 3–8 m (a flight landing there stands on the host's y 0) — only islands wholly outside the square get it; ISLE_SW keeps its M9 heights exactly */ var pos = [], idx = [], nrm = [];   /* M20: see the profile below (the reachable islets and LOW keep the M9 mound exactly) */ var centre = pos.length; var cliffA = rr() * Math.PI * 2, ph1 = rr() * 6.28, ph2 = rr() * 6.28;
      for (var k = 0; k <= K; k++) { var f = 1 - k / K; for (var i2 = 0; i2 < n; i2++) { var p = ring[i2], th = i2 / n * Math.PI * 2, cl = Math.pow(Math.max(0, Math.cos(th - cliffA)), 2);
          var ang = 1 + 0.07 * Math.sin(th * 3 + ph1) + 0.04 * Math.sin(th * 7 + ph2) - 0.05 * cl * (1 - f);   /* headlands / coves */
          var shelf = Math.min(1, (1 - f) / 0.22), rise = Math.pow(Math.max(0, (1 - f - 0.12) / 0.88), 0.7 + 0.5 * (1 - cl));   /* a low shelf, then the rise (steeper on the cliff side) */
          var yk = k === 0 ? 0 : I.h * (0.06 * shelf + 0.94 * rise) * (0.9 + 0.2 * Math.sin(th * 5 + ph2 + k));
          /* M20 (owner 2026-09-27, distant world: "cleaner silhouettes, fewer crude shapes"; islands read as blobs): a ROCK ISLAND profile — a
             low shelf, then a sea CLIFF band (steeper and higher on the cliff side) and a convex crown above it, instead of a dome rising to a
             point; the breakup fades toward the centre, so the top ring closes flat (the M9 mound met in a star of slivers at its summit). */
          if (M20 && k) { var uu = 1 - f, cw = 0.26 - 0.12 * cl, cf = Math.max(0, Math.min(1, (uu - 0.06) / cw)); cf = cf * cf * (3 - 2 * cf); yk = I.h * (0.05 * shelf + 0.95 * (0.56 * cf + 0.44 * (1 - Math.pow(Math.max(0, 1 - (uu - 0.06) / 0.94), 2.2)))) * (1 + (0.1 * Math.sin(th * 5 + ph2 + k) + 0.05 * Math.sin(th * 11 + ph1 - k * 1.7)) * Math.min(1, f * 3)); }
          pos.push(I.x + (p.x - I.x) * f * (k === 0 ? 1 : ang), yk, I.z + (p.z - I.z) * f * (k === 0 ? 1 : ang)); } }
      for (var k2 = 0; k2 < K; k2++) for (var i3 = 0; i3 < n; i3++) { var a = k2 * n + i3, b = k2 * n + (i3 + 1) % n, c2 = (k2 + 1) * n + i3, e = (k2 + 1) * n + (i3 + 1) % n; idx.push(a, b, c2, b, e, c2); }
      /* M20 round 2 (review: "the distant island reads as a flat dark slab"): the rock island's crown rises into two or three KNOLLS — soft summits up to
         ≈ 3 × its registry height, set on the side away from the mainland when it has a town (the village keeps its slope and the island a skyline
         behind it) — so each island shows a profile instead of a mesa. Wholly-outside-reach islands only (M20); a third stream (the seeded draws, the
         towns and the groves stay put; they sit on the new ground through gAt0). */
      var KN = []; if (M20) { var r3 = rnd((I.seed || 5) * 104729 + 7), aM = Math.atan2(-I.z, -I.x), nK = 2 + (r3() < 0.5 ? 1 : 0);
        for (var kn = 0; kn < nK; kn++) { var ka = I.town ? aM + Math.PI + (r3() - 0.5) * 2.4 : r3() * Math.PI * 2, kr = 0.1 + 0.32 * r3(), ks = 0.2 + 0.14 * r3(); KN.push([I.x + Math.cos(ka) * I.rx * kr, I.z + Math.sin(ka) * I.rz * kr, I.rx * ks * 1.35, I.rz * ks * 1.45, I.h * (kn ? 0.55 + 0.45 * r3() : 1.3 + 0.8 * r3())]); }
        for (var pv = n; pv < pos.length / 3; pv++) { var fk = Math.floor(pv / n) / K, wi = Math.max(0, Math.min(1, (fk - 0.12) / 0.33)), px = pos[pv * 3], pz = pos[pv * 3 + 2], add = 0; wi = wi * wi * (3 - 2 * wi);
          for (var kq = 0; kq < KN.length; kq++) { var dx = (px - KN[kq][0]) / KN[kq][2], dz = (pz - KN[kq][1]) / KN[kq][3]; add += KN[kq][4] * Math.exp(-(dx * dx + dz * dz)) * (1 + 0.12 * Math.sin(px * 0.11 + pz * 0.07 + kq)); }
          pos[pv * 3 + 1] += add * wi; } }
      var pg = new THREE.BufferGeometry(); pg.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); pg.setIndex(idx); faceUp(pg); landGeos.push({ g: pg.toNonIndexed(), shore: false });
      var gAt0 = function (x, z) { var b0 = [1e9, 0], b1 = [1e9, 0], b2 = [1e9, 0]; for (var q = 0; q < pos.length; q += 3) { var d = Math.hypot(pos[q] - x, pos[q + 2] - z); if (d < b0[0]) { b2 = b1; b1 = b0; b0 = [d, pos[q + 1]]; } else if (d < b1[0]) { b2 = b1; b1 = [d, pos[q + 1]]; } else if (d < b2[0]) b2 = [d, pos[q + 1]]; } var w0 = 1 / (b0[0] + 0.5), w1 = 1 / (b1[0] + 0.5), w2 = 1 / (b2[0] + 0.5); return (b0[1] * w0 + b1[1] * w1 + b2[1] * w2) / (w0 + w1 + w2); };   /* M20: the plateau height near (x, z) (the three nearest vertices) */
      var r2 = rnd((I.seed || 5) * 7919 + 13);   /* M20: a second stream, so the island's own draws (and its town) stay exactly as seeded */
      /* M20 round 2: ROCK OUTCROPS break the island's cliff lip and crown its knolls — the ridge crags' own rock bodies (ridgeCrags.rockBlock), rooted in the
         island, merged into ISLAND_LAND (its geology, no new draw); none on the town's arc. HIGH / MED (M20 islands only). */
      if (M20) { var rO = rnd((I.seed || 5) * 3571 + 29), rockC = new THREE.Color(0x4b5366), rkBody = function (x, z, a, hv, role) { var gy = gAt0(x, z), B = { x: x, y: gy + hv - (hv + a + 2) / 2, z: z, a: a, b: a * (0.7 + 0.5 * rO()), H: hv + a + 2, hv: hv, yaw: rO() * 6.28, lean: (rO() - 0.5) * 0.3, roll: (rO() - 0.5) * 0.2, taper: 0.15 + 0.2 * rO(), role: role, cuts: 3 + Math.floor(rO() * 3), sd: rO() * 1000 }, rb = rockBlock(THREE, B, TQ === 'HIGH' ? 1 : 0, rockC, rockC, 1e3), gg = new THREE.BufferGeometry(); gg.setAttribute('position', new THREE.Float32BufferAttribute(rb.pos, 3)); gg.setAttribute('normal', new THREE.Float32BufferAttribute(rb.nrm, 3)); landGeos.push({ g: gg, shore: false }); };
        var aM2 = Math.atan2(-I.z, -I.x), nL = 5 + Math.floor(rO() * 4), kl = Math.round(K * 0.3);
        for (var ol = 0; ol < nL; ol++) { var oa = (ol + rO() * 0.7) / nL * Math.PI * 2; if (I.town && Math.abs(Math.atan2(Math.sin(oa - aM2), Math.cos(oa - aM2))) < 0.95) continue; var oi = Math.round(oa / (Math.PI * 2) * n) % n, ox = pos[(kl * n + oi) * 3], oz = pos[(kl * n + oi) * 3 + 2];
          rkBody(ox, oz, I.h * (0.28 + 0.22 * rO()), I.h * (0.3 + 0.35 * rO()), 'crest'); }   /* on the cliff lip */
        KN.forEach(function (Q) { rkBody(Q[0] + (rO() - 0.5) * Q[2] * 0.4, Q[1] + (rO() - 0.5) * Q[3] * 0.4, I.h * (0.3 + 0.2 * rO()), I.h * (0.45 + 0.35 * rO()), 'summit'); }); }   /* a tor on each knoll */
      if (!M20) for (var s = 0; s < (I.spires || 0); s++) { var ang = rr() * Math.PI * 2, rad = rr() * 0.55; var sx = I.x + Math.cos(ang) * I.rx * rad, sz = I.z + Math.sin(ang) * I.rz * rad; var sh = I.h * (0.9 + rr() * 2.2), sr = 4 + rr() * 9; var og = new THREE.OctahedronGeometry(1, 0); og.scale(sr, sh, sr); og.rotateY(rr() * 3); og.translate(sx, I.h * 0.6 + sh * 0.55, sz); var fc = new THREE.Color(FAMS[I.family] && FAMS[I.family].color || '#e8f4ff').lerp(new THREE.Color(0xe8f4ff), 0.35); var cc = new Float32Array(og.attributes.position.count * 3); for (var ci = 0; ci < og.attributes.position.count; ci++) { var b = 0.85 + 0.3 * rr(); cc[ci * 3] = fc.r * b; cc[ci * 3 + 1] = fc.g * b; cc[ci * 3 + 2] = fc.b * b; } og.setAttribute('color', new THREE.BufferAttribute(cc, 3)); spireGeos.push(og); }
      /* M20 (owner: "fewer crude shapes"; crystals: "each must feel intentional … scale variety … grounding"): the island spire was a stretched
         octahedron standing on a point. It is a CRYSTAL CLUSTER now — a six-sided column with a pyramidal termination, rooted 2 m into the rock,
         and at most one shorter companion leaning out from its foot — at the same seeded place (a little lower and stockier than the diamond's tip), in the island's family
         (tips paler). The island's draws are consumed as before (the towns do not move); LOW keeps the octahedra. Review fix: the loop made 2–4
         columns per spire (≈ 140 pencils, against "remove repetitive crystal clutter"): 1–2 columns now (≈ 47 → ≈ 70), wider and shorter, with
         a blunter termination. */
      else for (var s = 0; s < (I.spires || 0); s++) { var ang = rr() * Math.PI * 2, rad = rr() * 0.55; var sx = I.x + Math.cos(ang) * I.rx * rad, sz = I.z + Math.sin(ang) * I.rz * rad; var sh = I.h * (0.9 + rr() * 2.2), sr = 4 + rr() * 9, yaw = rr() * 3; for (var ci = 0; ci < 24; ci++) rr();
        var gy = gAt0(sx, sz) - 2, top = I.h * 0.6 + sh * 0.95, fc = new THREE.Color(FAMS[I.family] && FAMS[I.family].color || '#e8f4ff').lerp(new THREE.Color(0xe8f4ff), 0.35), nC = r2() < 0.45 ? 0 : 1;
        for (var cc2 = 0; cc2 <= nC; cc2++) { var L = cc2 ? (top - gy) * (0.36 + 0.3 * r2()) : top - gy, rc = sr * (cc2 ? 0.34 + 0.1 * r2() : 0.62), tipL = rc * (1.5 + 0.6 * r2()), lean = cc2 ? 0.18 + 0.22 * r2() : 0.03, la = yaw + cc2 * 2.1 + r2(), col = new THREE.CylinderGeometry(rc * 0.92, rc, L - tipL, 6, 1, true), tip = new THREE.ConeGeometry(rc * 0.92, tipL, 6, 1, true);
          col.translate(0, (L - tipL) / 2, 0); tip.translate(0, L - tipL / 2, 0); [col, tip].forEach(function (G, gi) { var pa = G.attributes.position, cA = new Float32Array(pa.count * 3); for (var vi = 0; vi < pa.count; vi++) { var tt = pa.getY(vi) / L, bb = (0.78 + 0.16 * tt + (gi ? 0.18 : 0)) * (0.94 + 0.12 * ((vi * 0.618) % 1)); cA[vi * 3] = fc.r * bb; cA[vi * 3 + 1] = fc.g * bb; cA[vi * 3 + 2] = fc.b * bb; } G.setAttribute('color', new THREE.BufferAttribute(cA, 3));
            G.rotateY(la); G.rotateZ(lean); G.rotateY(-la + (r2() - 0.5)); G.translate(sx + (cc2 ? Math.cos(la) * sr * 0.35 : 0), gy, sz + (cc2 ? Math.sin(la) * sr * 0.35 : 0)); var Gn = G.index ? G.toNonIndexed() : G; if (Gn !== G) G.dispose(); spireGeos.push(Gn); }); } }
      /* M20 (owner: "islands are blobs with lollipop trees" → "believable distant vegetation masses"): the trees stand in GROVES — clumps of
         five or six crowns round a grove centre on the crown of the island (clear of the town's slope), each tree seated on the plateau surface;
         the island's own draws still place and size every tree within its grove. The reachable islets and LOW keep the M9 scatter. */
      var GV = []; if (M20) for (var gv = 0; gv < Math.ceil((I.trees || 0) / 6); gv++) { var ga = 0, grr = 0; for (var tries = 0; tries < 6; tries++) { ga = r2() * Math.PI * 2; grr = 0.12 + 0.5 * Math.sqrt(r2()); if (!I.town || Math.cos(ga) * -I.x + Math.sin(ga) * -I.z < 0.15 * Math.hypot(I.x, I.z)) break; } GV.push([ga, grr, 7 + r2() * 9]); }
      for (var t2 = 0; t2 < (I.trees || 0); t2++) { var ta = rr() * Math.PI * 2, tr = 0.3 + rr() * 0.6, tS = 6 + rr() * 8, tY = rr() * 3;
        if (!M20) { treeMats.push([I.x + Math.cos(ta) * I.rx * tr, I.h * (1 - Math.pow(tr, 1.6)) * 0.95, I.z + Math.sin(ta) * I.rz * tr, tS, tY, I.family, 0, I.reachable ? 1 : 0]); treeCount++; continue; }
        var G0 = GV[Math.floor(t2 / 6)], gx = I.x + Math.cos(G0[0]) * I.rx * G0[1] + Math.cos(ta) * G0[2] * (tr - 0.3) / 0.6, gz = I.z + Math.sin(G0[0]) * I.rz * G0[1] + Math.sin(ta) * G0[2] * (tr - 0.3) / 0.6;
        treeMats.push([gx, gAt0(gx, gz) - 0.6, gz, tS * (0.75 + 0.25 * r2()), tY, I.family, 1, 0]); treeCount++; }
      /* M15c DISTANT CIVILIZATION (owner 2026-09-27 world depth: foreground → midground → distant civilization → high terrain → celestial):
         an island with a registry `town` carries a small settlement on the slope facing the mainland — softened white houses on two terraced
         rows (rounded volumes, a lens roof, a ribbon of glass that glows warm at night) and, on the larger islands, a landmark tower with a lit
         band per level, a lens crown and a crystal finial in the island's family. Seen across the sea it reads as people living out there.
         Scenery beyond the field walls: no colliders. Two draws for every town (body, glass); the finials join the island spires. */
      if (I.town) { var TW = I.town, fx = -I.x, fz = -I.z, fl = Math.hypot(fx, fz) || 1; fx /= fl; fz /= fl; var tx = -fz, tz = fx, faceY = Math.atan2(fx, fz), Rf = 1 / Math.hypot(fx / I.rx, fz / I.rz), SG = TQ === 'LOW' ? 10 : 16;
        var gAt = function (x, z, r) { var lo = 1e9, hi = -1e9; for (var q = 0; q < pos.length; q += 3) { if (Math.hypot(pos[q] - x, pos[q + 2] - z) < r) { lo = Math.min(lo, pos[q + 1]); hi = Math.max(hi, pos[q + 1]); } } return hi > -1e8 ? [lo, hi] : [0, I.h * 0.5]; };
        var pill = function (list, w, h, d, x, y, z, yaw) { var r = d / 2, core = Math.max(0.05, w - d), b = new THREE.BoxGeometry(core, h, d), e1 = new THREE.CylinderGeometry(r, r, h, SG), e2 = e1.clone(); e1.translate(core / 2, 0, 0); e2.translate(-core / 2, 0, 0); [b, e1, e2].forEach(function (g) { g.rotateY(yaw); g.translate(x, y, z); list.push(g); }); };
        var lens = function (list, rx, rz, hT, hB, x, y, z, yaw) { var t = new THREE.SphereGeometry(1, SG + 4, 4, 0, Math.PI * 2, 0, Math.PI / 2), b = new THREE.SphereGeometry(1, SG + 4, 2, 0, Math.PI * 2, 0, Math.PI / 2); t.scale(rx, hT, rz); b.rotateX(Math.PI); b.scale(rx, hB, rz); [t, b].forEach(function (g) { g.rotateY(yaw); g.translate(x, y, z); list.push(g); }); };
        var rows = [[0.5, Math.ceil((TW.houses || 0) / 2)], [0.3, Math.floor((TW.houses || 0) / 2)]], nH = 0;
        rows.forEach(function (RW) { var n = RW[1], q = RW[0], cx = I.x + fx * Rf * q, cz = I.z + fz * Rf * q, half = 1 / Math.hypot(tx / I.rx, tz / I.rz) * Math.sqrt(Math.max(0, 1 - q * q)) * 0.7, sp = Math.min(19, n > 1 ? 2 * half / (n - 1) : 0);
          for (var hI = 0; hI < n; hI++) { var o = (hI - (n - 1) / 2) * sp + (rr() - 0.5) * 3, x = cx + tx * o, z = cz + tz * o, yaw = faceY + (rr() - 0.5) * 0.3, W = 10 + rr() * 3, D = 6.5, g = gAt(x, z, W * 0.6), y0 = g[1] + 0.2, f1 = [Math.sin(yaw) * 1.4, Math.cos(yaw) * 1.4];
            pill(townBody, W + 1.6, y0 - g[0] + 1.2, D + 1.8, x, (y0 + g[0]) / 2 - 0.6, z, yaw);   /* the terrace plinth, down into the slope */
            pill(townGlass, W - 1.2, 2.5, D - 0.8, x, y0 + 1.25, z, yaw); pill(townBody, W, 2.4, D, x + f1[0], y0 + 2.5 + 1.2, z + f1[1], yaw); pill(townGlass, W + 0.1, 0.8, D + 0.1, x + f1[0], y0 + 2.5 + 1.35, z + f1[1], yaw);
            lens(townBody, W / 2 + 2, D / 2 + 2, 0.8, 0.25, x + f1[0], y0 + 5.3, z + f1[1], yaw); nH++; } });
        if (TW.tower_h) { var TH = TW.tower_h, X = I.x + fx * Rf * 0.1, Z = I.z + fz * Rf * 0.1, g2 = gAt(X, Z, 9), y1 = g2[1];
          var sh = new THREE.CylinderGeometry(5.2, 7.2, TH + (y1 - g2[0]) + 1, SG + 4); sh.translate(X, (y1 + TH + g2[0] - 1) / 2, Z); townBody.push(sh);
          for (var lv = 1; lv <= 4; lv++) { var yb = y1 + TH * lv / 5, rb = 7.2 - 2.0 * lv / 5 + 0.08, lband = new THREE.CylinderGeometry(rb, rb + 0.05, 1.3, SG + 4, 1, true); lband.translate(X, yb, Z); townGlass.push(lband); }   /* a lit band per level */
          lens(townBody, 11, 11, 1.4, 0.5, X, y1 + TH + 0.6, Z, faceY);
          var fn = new THREE.OctahedronGeometry(1, 0); fn.scale(2.2, 6.5, 2.2); fn.translate(X, y1 + TH + 2.2 + 6.5, Z); var fcc = new THREE.Color(FAMS[I.family] && FAMS[I.family].color || '#e8f4ff').lerp(new THREE.Color(0xe8f4ff), 0.25), fcol = new Float32Array(fn.attributes.position.count * 3); for (var fi = 0; fi < fn.attributes.position.count; fi++) { fcol[fi * 3] = fcc.r; fcol[fi * 3 + 1] = fcc.g; fcol[fi * 3 + 2] = fcc.b; } fn.setAttribute('color', new THREE.BufferAttribute(fcol, 3)); spireGeos.push(fn); }
        info.towns = (info.towns || 0) + 1; info.town_houses = (info.town_houses || 0) + nH; }
      foamPts.push({ pts: ring, wl: wl, cx: I.x, cz: I.z }); info.islands++; });
    if (landGeos.length) { var shoreG = landGeos.filter(function (x) { return x.shore; }).map(function (x) { return x.g; }); var plateauG = landGeos.filter(function (x) { return !x.shore; }).map(function (x) { return x.g; }); if (shoreG.length) add(mergeList(shoreG), shoreMat, 'ISLAND_SHORES'); if (plateauG.length) add(mergeList(plateauG), landMat, 'ISLAND_LAND'); }
    if (spireGeos.length) add(mergeList(spireGeos), spireMat, 'ISLAND_SPIRES');
    if (townBody.length) { var townMat = new THREE.MeshStandardMaterial({ color: 0xe3e7ee, roughness: 0.42, metalness: 0.25, envMapIntensity: 0.5 }); townGlassMat = new THREE.MeshStandardMaterial({ color: 0x39404e, roughness: 0.1, metalness: 0.7, emissive: 0xfff1dc, emissiveIntensity: night ? 0.9 : 0.05, side: THREE.DoubleSide }); own.push(townMat, townGlassMat); add(mergeList(townBody), townMat, 'ISLAND_TOWNS'); if (townGlass.length) add(mergeList(townGlass), townGlassMat, 'ISLAND_TOWN_GLASS'); }   /* M15c: distant civilization */
    var TLO = TQ === 'LOW';
    if (treeCount && !TLO) {   /* M20 round 2 (the mountains review: "in V11 the distant island reads as a flat dark slab with small dark-maroon clumps, and the class-family read
         (pink) is weak from afar; the reachable-islet canopies (LU) are primitive blobs"): the island tree speaks the world's tree language — a pale platinum
         METAL trunk and boughs, a crown of crystal-leaf lobes in the island's class family, dark in its underside and core, lighter up top, its outer tips
         catching the family colour (normalised to its brightest channel: the hue never clips toward another class) and glowing faintly by night. Two
         builds of the same tree: the reachable islets (walk-up range, LU) carry five subdivided lobes and three boughs (≈ 1 700 tris × 18 trees on HIGH, ≈ 520 on MED); every
         other island a light three-lobe grove tree (≈ 80 tris; two lobes, ≈ 55, on MED). One material (one program), two instanced draws (the grove mesh is new: a close-range
         crown on 570 far trees would cost ≈ 250 k triangles). HOST SAFETY (hard rule 4, gameplay_world_m19_mountains 9): nothing of the crown or the
         boughs below local y 1.66 (≥ 4.9 m over the base at the smallest scale), and the trunk has no ring between local 1.0 and 2.0. LOW keeps the M9 crown. */
      var treeGeo = function (full) { var parts = [], rt = rnd(full ? 71 : 73), CR = [0, 2.42, 0];
        var tag = function (g, fn) { var p = g.attributes.position, n = g.attributes.normal, c = new Float32Array(p.count * 3); for (var vi = 0; vi < p.count; vi++) { var o = fn(p.getX(vi), p.getY(vi), p.getZ(vi), n.getX(vi), n.getY(vi), n.getZ(vi)); c[vi * 3] = o[0]; c[vi * 3 + 1] = o[1]; c[vi * 3 + 2] = o[2]; } g.setAttribute('color', new THREE.BufferAttribute(c, 3)); parts.push(g); };   /* colour = [value, crown mask, tip] (the shader turns it into metal / family colour) */
        var trunk = new THREE.CylinderGeometry(full ? 0.055 : 0.07, full ? 0.13 : 0.14, 2.0, full ? 6 : 5, 2, true); trunk.translate(0, 1, 0); (function (p) { for (var vi = 0; vi < p.count; vi++) { var yy = p.getY(vi); p.setX(vi, p.getX(vi) + 0.07 * Math.sin(yy * 1.6)); } })(trunk.attributes.position); trunk.computeVertexNormals();   /* a slight lean and sweep; rings at 0, 1 and 2 only */
        tag(trunk, function (x, y) { return [0.62 + 0.12 * y / 2, 0, 0]; });
        if (full) for (var bo = 0; bo < 3; bo++) { var ba = bo / 3 * Math.PI * 2 + rt() * 0.8, br = new THREE.CylinderGeometry(0.022, 0.045, 0.8, 4, 1, true); br.translate(0, 0.4, 0); br.rotateZ(0.55 + 0.35 * rt()); br.rotateY(ba); br.translate(0.07 * Math.sin(1.75 * 1.6), 1.74, 0); br.computeVertexNormals(); tag(br, function () { return [0.7, 0, 0]; }); }   /* boughs from the trunk head up into the lobes */
        var lobes = full ? [[0, 2.5, 0, 0.78, 0.78], [0.5, 2.22, 0.18, 0.56, 0.8], [-0.36, 2.28, 0.42, 0.52, 0.82], [-0.3, 2.3, -0.46, 0.55, 0.8], [0.12, 2.95, -0.06, 0.48, 0.86]] : [[0, 2.48, 0, 0.84, 0.78], [0.5, 2.24, 0.28, 0.58, 0.82], [-0.42, 2.3, -0.3, 0.6, 0.8]].slice(0, TQ === 'MED' ? 2 : 3);   /* MED (a phone tier): two lobes a grove tree */
        lobes.forEach(function (L, li) { var ic = new THREE.IcosahedronGeometry(1, full ? (TQ === 'HIGH' ? 2 : 1) : 0); ic.deleteAttribute('normal'); ic.deleteAttribute('uv'); var lg = mergeVertices(ic, 1e-4); ic.dispose(); var p = lg.attributes.position, o1 = rt() * 9, o2 = rt() * 9;
          for (var vi = 0; vi < p.count; vi++) { var x = p.getX(vi), y = p.getY(vi), z = p.getZ(vi), m = 1 + 0.12 * Math.sin(x * 3.1 + o1) * Math.sin(z * 2.7 + o2) + 0.06 * Math.sin(y * 4.3 + o2); p.setXYZ(vi, L[0] + x * L[3] * m, Math.max(1.66, L[1] + y * L[3] * L[4] * m), L[2] + z * L[3] * m); }   /* lumpy lobes, the crown's underside held at local 1.66 (host safety) */
          lg.computeVertexNormals(); tag(lg, function (x, y, z, nx, ny, nz) { var ox = x - CR[0], oy = y - CR[1], oz = z - CR[2], ol = Math.hypot(ox, oy, oz) || 1, out = Math.max(0, (ox * nx + oy * ny + oz * nz) / ol), up = Math.max(0, Math.min(1, (y - 1.66) / 1.5));
            return [0.3 + 0.52 * up * up * (3 - 2 * up) * (0.75 + 0.25 * out) + 0.06 * li / lobes.length, 1, Math.max(0, Math.min(1, (up - 0.45) / 0.5)) * (0.4 + 0.6 * out)]; }); });   /* dark in the underside and core, lit up top, the outer upper tips crystal */
        var m = mergeList(parts); parts.forEach(function (g) { g.dispose(); }); return m; };
      var tMat = new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.52, metalness: 0.22, vertexColors: true }); own.push(tMat); treeGlow = { value: night ? 0.32 : 0.04 };
      tMat.onBeforeCompile = function (sh) { sh.uniforms.uTreeGlow = treeGlow;
        sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nvarying float vTreeTip;').replace('#include <color_vertex>', '#include <color_vertex>\n#if defined( USE_COLOR ) && defined( USE_INSTANCING_COLOR )\n{ vec3 ic = instanceColor.xyz, tipC = ic / max(max(ic.r, ic.g), max(ic.b, 1e-3)) * 0.88; vColor.xyz = mix(mix(vec3(0.62, 0.63, 0.66), ic, color.g) * color.r, tipC, color.b * 0.5); vTreeTip = color.b; }\n#else\nvTreeTip = 0.0;\n#endif');   /* metal where the crown mask is 0, the family colour in the crown, the tips toward the family colour at its brightest */
        sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nvarying float vTreeTip; uniform float uTreeGlow;').replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\ntotalEmissiveRadiance += vColor.xyz * vTreeTip * uTreeGlow;'); };
      tMat.customProgramCacheKey = function () { return 'mahworld-isle-tree-m20r2'; };
      var near = treeMats.filter(function (t) { return t[7]; }), far = treeMats.filter(function (t) { return !t[7]; }), m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), v = new THREE.Vector3(), sc = new THREE.Vector3(), tcol = new THREE.Color();
      [[near, true, 'ISLAND_TREES'], [far, false, 'ISLAND_GROVES']].forEach(function (S) { if (!S[0].length) return; var tg = treeGeo(S[1]), trees = new THREE.InstancedMesh(tg, tMat, S[0].length); own.push(tg);
        S[0].forEach(function (t, i) { q.setFromAxisAngle(new THREE.Vector3(0, 1, 0), t[4]); v.set(t[0], t[1], t[2]); sc.set(t[3] * 0.45, t[3] * 0.5, t[3] * 0.45); m4.compose(v, q, sc); trees.setMatrixAt(i, m4); tcol.set(FAMS[t[5]] && FAMS[t[5]].color || '#8a93a6').lerp(new THREE.Color(FAMS[t[5]] && FAMS[t[5]].deep || '#2c3a58'), 0.18 + 0.3 * ((i * 0.6180339) % 1)); trees.setColorAt(i, tcol); });   /* the family colour, each tree a step toward its deep tone (the crown's value is in the mesh) */
        if (trees.instanceColor) trees.instanceColor.needsUpdate = true; trees.instanceMatrix.needsUpdate = true; trees.name = S[2]; trees.userData.noMerge = true; trees.frustumCulled = false; group.add(trees); meshes.push(trees); info.draw_calls++; info.tris += Math.round(tg.attributes.position.count / 3) * S[0].length; }); }
    if (treeCount && TLO) { var tg = (function () { var crown = new THREE.IcosahedronGeometry(1, 0); crown.scale(1.05, 0.95, 1.05); crown.translate(0, 2.45, 0); var trunk = new THREE.CylinderGeometry(0.1, 0.16, 1.7, 5); trunk.translate(0, 0.85, 0); var m = mergeList([crown, trunk]); crown.dispose(); trunk.dispose(); return m; })();   /* M9: a rounded crown on a trunk (the octahedron spikes read as a crystal fence) */ var tMat = new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.55, metalness: 0.3, flatShading: true }); own.push(tMat); var trees = new THREE.InstancedMesh(tg, tMat, treeCount); var tcol = new THREE.Color(); var m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), v = new THREE.Vector3(), sc = new THREE.Vector3(); treeMats.forEach(function (t, i) { q.setFromAxisAngle(new THREE.Vector3(0, 1, 0), t[4]); v.set(t[0], t[1], t[2]); sc.set(t[3] * 0.45, t[3] * 0.5, t[3] * 0.45); m4.compose(v, q, sc); trees.setMatrixAt(i, m4); tcol.set(FAMS[t[5]] && FAMS[t[5]].deep || '#2c3a58').lerp(new THREE.Color(FAMS[t[5]] && FAMS[t[5]].color || '#4a5a78'), 0.35 + 0.3 * ((i * 0.6180339) % 1)); trees.setColorAt(i, tcol); }); if (trees.instanceColor) trees.instanceColor.needsUpdate = true;   /* crowns in the island's class family, deep → body tone */ trees.instanceMatrix.needsUpdate = true; trees.name = 'ISLAND_TREES'; trees.userData.noMerge = true; trees.frustumCulled = false; group.add(trees); meshes.push(trees); info.draw_calls++; info.tris += 8 * treeCount; }
    /* 4. foam lines at every waterline (mainland + islands): bands that swing in / out along the normal */
    var fmat = new THREE.MeshBasicMaterial({ map: foamTexture(), transparent: true, opacity: 0.5, depthWrite: false, color: 0xf2f8ff }); own.push(fmat); var FW = C.foam_w || 1.6;
    var mkFoam = function (pts2, wl2, id, cx, cz) { var g = band(pts2, [wl2 - FW / 2, wl2 + FW / 2], function () { return SEA + 0.012; }, function (d) { return (d - (wl2 - FW / 2)) / FW; }); var fm = add(g, fmat, id, 2); fm.userData.foam = { cx: cx, cz: cz, phase: (cx + cz) * 0.013 }; foam.push(fm); };
    mkFoam(pts, WL, 'COAST_FOAM', 0, (C.outline.z1 + C.outline.z2) / 2); foamPts.forEach(function (f, i) { mkFoam(f.pts, f.wl, 'ISLAND_FOAM_' + i, f.cx, f.cz); });
    /* the legacy haze plain is replaced by the sea */ var hz = ctx.scene.getObjectByName ? ctx.scene.getObjectByName('HAZE_PLAIN') : null; if (hz) hz.visible = false;
    applyNight(night); log('coast: mainland beach ring + sea + ' + info.islands + ' islands, ' + info.draw_calls + ' draw calls, ' + info.tris + ' tris');
  }
  function mergeList(list) { var pos = [], nrm = [], uv = [], col = []; list.forEach(function (g) { var ng = g.index ? g.toNonIndexed() : g; var p = ng.attributes.position, nn = ng.attributes.normal, u = ng.attributes.uv, c = ng.attributes.color; for (var i = 0; i < p.count; i++) { pos.push(p.getX(i), p.getY(i), p.getZ(i)); if (nn) nrm.push(nn.getX(i), nn.getY(i), nn.getZ(i)); uv.push(u ? u.getX(i) : 0, u ? u.getY(i) : 0.62); if (c) col.push(c.getX(i), c.getY(i), c.getZ(i)); } }); var out = new THREE.BufferGeometry(); out.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); out.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2)); if (col.length === pos.length) out.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); if (nrm.length === pos.length) out.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3)); else out.computeVertexNormals(); return out; }
  function applyNight(n) { var P = n ? NIGHT : DAY; if (townGlassMat) townGlassMat.emissiveIntensity = n ? 0.9 : 0.05; if (treeGlow) treeGlow.value = n ? 0.32 : 0.04; if (seaMat) { seaMat.color.setHex(P.color); seaMat.roughness = P.rough; seaMat.envMapIntensity = P.env; seaMat.opacity = P.opacity; } }
  function tick(dt, t) { clock = (typeof t === 'number' && isFinite(t)) ? t : clock + (dt || 0); for (var i = 0; i < foam.length; i++) { var f = foam[i], fd = f.userData.foam; var ph = clock * (2 * Math.PI / (C && C.foam_period_s || 5.2)) + fd.phase; var sw = (C && C.foam_swing_m || 1.1) * (0.8 * Math.sin(ph) + 0.2 * Math.sin(ph * 2.1)); var k = 1 + sw / 200; f.scale.set(k, 1, k); f.position.set(fd.cx * (1 - k), 0, fd.cz * (1 - k)); f.material.opacity = 0.3 + 0.25 * (0.5 + 0.5 * Math.sin(ph + 1.1)); } }   /* a scale about the body's centre ≈ an in / out shift of the foam line along the shore normal */
  function setNight(n) { night = !!n; applyNight(night); }
  function dispose() { meshes.forEach(function (m) { if (m.parent) m.parent.remove(m); if (m.geometry) m.geometry.dispose(); }); meshes = []; own.forEach(function (m) { m.dispose(); }); own = []; if (group && group.parent) group.parent.remove(group); group = null; foam = []; }
  function debug() { return { m20_islands: info.m20_islands || {}, islands: info.islands, towns: info.towns || 0, town_houses: info.town_houses || 0, draw_calls: info.draw_calls, tris: info.tris, sea_y: C ? C.sea_y : null, beach_w: C ? C.beach_w : null, outline: C ? C.outline : null, foam_lines: foam.length, night: night }; }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug, outline: function () { return C ? C.outline : null; } };
}
