/* MAHWORLD JOB B :: COAST, SEA AND ISLANDS (owner note 2026-09-19: "we need multiple bodies of land — it's a vast world; where the water
   meets the land it must be very gradual, like a beach with waves").
   The mainland is ONE island: its floor ends at a rounded coast beyond the field walls (registry.coast.outline), a BEACH RING slopes from the
   floor edge (y 0) through the waterline down to beach_drop_m under the sea over beach_w (the dry → wet → deep shore gradient), and the SEA
   (a single cheap animated plane at sea_y with the water look, a hole under the mainland) runs to the horizon. Other LANDMASSES stand in the
   sea at 300–650 m: elliptical islands (beach ring + rising plateau + crystal spires + instanced sapphire tree silhouettes) — scenery beyond
   the walls, no colliders (the field walls stay the playable limit), hazed by the fog for depth. FOAM lines lap in and out along every
   waterline (≈ 5 s swing). Draw calls: coast 3 (floor edge ring, sea, foam) + islands 4 (land, spires, trees, island foam). No per-frame allocations. */
export function createCoast(ctx) {
  var THREE = ctx.THREE, M = ctx.M || {}, log = ctx.log || function () { };
  var group = null, meshes = [], own = [], sea = null, seaMat = null, foam = [], clock = 0, night = !!ctx.night, C = null, info = { islands: 0, draw_calls: 0, tris: 0 };
  var DAY = { color: 0x1f5fb0, rough: 0.2, env: 0.85, opacity: 0.94 }, NIGHT = { color: 0x0e2a48, rough: 0.28, env: 0.7, opacity: 0.95 };   /* a sea that reads BLUE at grazing angles; WORLD PIVOT PASS 2: brighter azure by day, more sky reflection and sun glitter */
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  /* rounded-rectangle outline sampled as N points with outward normals (perimeter order) */
  function outlinePoints(o, n) { var w = o.x2 - o.x1, d = o.z2 - o.z1, r = Math.min(o.corner_r || 0, w / 2, d / 2); var cx = (o.x1 + o.x2) / 2, cz = (o.z1 + o.z2) / 2; var pts = [];
    var segs = [[o.x1 + r, o.z1, o.x2 - r, o.z1, 0, -1], [o.x2, o.z1 + r, o.x2, o.z2 - r, 1, 0], [o.x2 - r, o.z2, o.x1 + r, o.z2, 0, 1], [o.x1, o.z2 - r, o.x1, o.z1 + r, -1, 0]];
    var corners = [[o.x2 - r, o.z1 + r, -Math.PI / 2, 0], [o.x2 - r, o.z2 - r, 0, Math.PI / 2], [o.x1 + r, o.z2 - r, Math.PI / 2, Math.PI], [o.x1 + r, o.z1 + r, Math.PI, Math.PI * 1.5]];
    var per = 2 * (w - 2 * r) + 2 * (d - 2 * r) + 2 * Math.PI * r; var step = per / n;
    for (var k = 0; k < 4; k++) { var s = segs[k]; var L = Math.hypot(s[2] - s[0], s[3] - s[1]); var m = Math.max(1, Math.round(L / step)); for (var i = 0; i < m; i++) { var t = i / m; pts.push({ x: s[0] + (s[2] - s[0]) * t, z: s[1] + (s[3] - s[1]) * t, nx: s[4], nz: s[5] }); }
      var c = corners[k]; var mc = Math.max(2, Math.round(Math.PI / 2 * r / step)); for (var j = 0; j < mc; j++) { var a = c[2] + (c[3] - c[2]) * j / mc; var nx = Math.cos(a), nz = Math.sin(a);   /* angle measured in the (x, z) plane */ pts.push({ x: c[0] + nx * r, z: c[1] + nz * r, nx: nx, nz: nz }); } }
    if (o.organic_m) pts.forEach(function (p) { p.off = coastOffset(o, p.x, p.z); });   /* WORLD PIVOT PASS 2: headlands + bays, outward only */
    return pts; }
  /* WORLD PIVOT PASS 2 (owner 2026-09-25: eliminate the "flat game plate"): the mainland coast breathes OUTWARD from the registry rounded
     rectangle by a smooth periodic profile (0 … organic_m) around its centre — headlands and bays instead of a machined slab edge. The field
     walls, colliders and every playable metre are untouched; the sea hole, the foam line and seaTest all use the same offset. */
  function coastOffset(o, x, z) { var A = +o.organic_m || 0; if (!A) return 0; var th = Math.atan2(z - (o.z1 + o.z2) / 2, x - (o.x1 + o.x2) / 2); var f = 0.5 + 0.28 * Math.sin(2 * th + 0.7) + 0.18 * Math.sin(5 * th + 1.9) + 0.1 * Math.sin(9 * th + 0.4) - 0.06 * Math.sin(13 * th + 2.2); return A * Math.max(0, Math.min(1, f)); }
  function ellipsePoints(cx, cz, rx, rz, n) { var pts = []; for (var i = 0; i < n; i++) { var a = i / n * Math.PI * 2; var nx = Math.cos(a) * rz, nz = Math.sin(a) * rx; var l = Math.hypot(nx, nz) || 1; pts.push({ x: cx + Math.cos(a) * rx, z: cz + Math.sin(a) * rz, nx: nx / l, nz: nz / l }); } return pts; }
  /* a band mesh from an outline: rings at distances ds[] along the normal, y from prof(d), uv (u along, v by ring) */
  function band(pts, ds, prof, vOf) { var n = pts.length, R = ds.length; var pos = [], uv = [], idx = []; for (var k = 0; k < R; k++) for (var i = 0; i < n; i++) { var p = pts[i]; var d = ds[k], dd = d + (d > 0 ? (p.off || 0) : 0); pos.push(p.x + p.nx * dd, prof(d, i), p.z + p.nz * dd); uv.push(i / 9, vOf(d)); }
    for (var k2 = 0; k2 < R - 1; k2++) for (var i2 = 0; i2 < n; i2++) { var a = k2 * n + i2, b = k2 * n + (i2 + 1) % n, c = (k2 + 1) * n + i2, e = (k2 + 1) * n + (i2 + 1) % n; idx.push(a, c, b, b, c, e); }
    var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2)); g.setIndex(idx); return faceUp(g); }
  /* every band / plateau must face UP whatever the outline's winding: flip the triangles when the mean normal points down */
  function faceUp(g) { g.computeVertexNormals(); var nn = g.attributes.normal, sy = 0; for (var i = 0; i < nn.count; i++) sy += nn.getY(i); if (sy < 0) { var ix = g.index; if (ix) { for (var k = 0; k < ix.count; k += 3) { var t = ix.getX(k + 1); ix.setX(k + 1, ix.getX(k + 2)); ix.setX(k + 2, t); } ix.needsUpdate = true; } else { var p = g.attributes.position; for (var k2 = 0; k2 < p.count; k2 += 3) { var x1 = p.getX(k2 + 1), y1 = p.getY(k2 + 1), z1 = p.getZ(k2 + 1); p.setXYZ(k2 + 1, p.getX(k2 + 2), p.getY(k2 + 2), p.getZ(k2 + 2)); p.setXYZ(k2 + 2, x1, y1, z1); } } g.computeVertexNormals(); } return g; }
  function shapeFrom(pts) { var sh = new THREE.Shape(); pts.forEach(function (p, i) { if (i === 0) sh.moveTo(p.x, -p.z); else sh.lineTo(p.x, -p.z); }); sh.closePath(); return sh; }   /* plane y = −world z (rotated −90° about x) */
  function add(geo, mat, name, order) { var m = new THREE.Mesh(geo, mat); m.name = name; m.userData.noMerge = true; m.frustumCulled = false; m.receiveShadow = false; m.castShadow = false; if (order !== undefined) m.renderOrder = order; group.add(m); meshes.push(m); info.draw_calls++; info.tris += Math.round((geo.index ? geo.index.count : geo.attributes.position.count) / 3); return m; }
  function foamTexture() { var c = document.createElement('canvas'); c.width = 256; c.height = 64; var g = c.getContext('2d'); g.clearRect(0, 0, 256, 64); var rr = rnd(77); for (var i = 0; i < 44; i++) { var x = rr() * 256, y = 12 + rr() * 40, r = 6 + rr() * 14; var gr = g.createRadialGradient(x, y, 0, x, y, r); gr.addColorStop(0, 'rgba(255,255,255,0.9)'); gr.addColorStop(0.5, 'rgba(255,255,255,0.35)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(x - r, y - r, 2 * r, 2 * r); } var t = new THREE.CanvasTexture(c); t.wrapS = THREE.RepeatWrapping; t.wrapT = THREE.ClampToEdgeWrapping; t.colorSpace = THREE.SRGBColorSpace; return t; }

  function build() {
    C = ctx.registry && ctx.registry.coast; if (!C || !C.outline) { log('coast: registry.coast missing — nothing built'); return; }
    group = new THREE.Group(); group.name = 'MAHWORLD_COAST'; group.userData.noMerge = true; ctx.group.add(group);
    var shoreMat = M.shore || M.sand || new THREE.MeshStandardMaterial({ color: 0xb8b3a8, roughness: 0.85 }); var BW = C.beach_w || 34, DROP = C.beach_drop_m || 1.6, WL = C.waterline_d || 8, SEA = C.sea_y !== undefined ? C.sea_y : -0.3;
    /* the beach profile: y 0 at the floor edge, gently down to the waterline (sea_y at d = WL), then on to −DROP at d = BW (a beach, never a wall) */
    var prof = function (d) { if (d <= WL) { var t = d / WL; return SEA * (t * t * (3 - 2 * t)); } var u = (d - WL) / (BW - WL); return SEA + (-DROP - SEA) * (u * u * (3 - 2 * u)); };
    var vOf = function (d) { return Math.min(1, d <= WL ? 0.28 * (d / WL) : 0.28 + 0.72 * ((d - WL) / (BW - WL))); };
    /* 1. mainland beach ring */
    var pts = outlinePoints(C.outline, 240); var ds = [0, 0.01, 2.5, 5, WL, WL + 4, WL + 9, WL + 15, BW];   /* the 0.01 row carries the flat organic land out to the shifted beach */ add(band(pts, ds, prof, vOf), shoreMat, 'COAST_BEACH');
    /* 2. the sea: one big plane at sea_y with a hole under the mainland (the beach ring passes under the water at the waterline) */
    var seaSize = 1800; var seaShape = new THREE.Shape(); seaShape.moveTo(-seaSize / 2, -seaSize / 2); seaShape.lineTo(seaSize / 2, -seaSize / 2); seaShape.lineTo(seaSize / 2, seaSize / 2); seaShape.lineTo(-seaSize / 2, seaSize / 2); seaShape.closePath();
    var holePts = outlinePoints(C.outline, 120).map(function (p) { var dd = WL - 1.5 + (p.off || 0); return { x: p.x + p.nx * dd, z: p.z + p.nz * dd }; }); var hole = new THREE.Path(); holePts.forEach(function (p, i) { if (i === 0) hole.moveTo(p.x, -p.z); else hole.lineTo(p.x, -p.z); }); hole.closePath(); seaShape.holes.push(hole);
    var seaG = new THREE.ShapeGeometry(seaShape, 1); var sp = seaG.attributes.position, su = seaG.attributes.uv; for (var i = 0; i < sp.count; i++) su.setXY(i, sp.getX(i) / 13, sp.getY(i) / 13); su.needsUpdate = true; seaG.rotateX(-Math.PI / 2); seaG.translate(0, SEA, 0);
    seaMat = new THREE.MeshStandardMaterial({ color: DAY.color, roughness: DAY.rough, metalness: 0.3, transparent: true, opacity: DAY.opacity, envMapIntensity: DAY.env, side: THREE.FrontSide }); own.push(seaMat);
    if (ctx.waterNormalTex) { seaMat.normalMap = ctx.waterNormalTex; seaMat.normalScale = new THREE.Vector2(0.16, 0.16); }   /* the canal's drifting normal map (the same texture object: its offset animates both surfaces) */
    sea = add(seaG, seaMat, 'COAST_SEA', 1);
    /* the SEA as a ripple body: outside the mainland's rounded outline (+ waterline) and outside every island's ellipse (+ its waterline) */
    var O = C.outline, R = Math.min(O.corner_r || 0, (O.x2 - O.x1) / 2, (O.z2 - O.z1) / 2); var isl0 = C.islands || [];
    var seaTest = function (x, z) { var dx = Math.max(O.x1 + R - x, 0, x - (O.x2 - R)), dz = Math.max(O.z1 + R - z, 0, z - (O.z2 - R)); var d = Math.hypot(dx, dz) - R; if (d < WL - 1.5 + coastOffset(O, x, z)) return false; for (var i = 0; i < isl0.length; i++) { var I = isl0[i]; var bw = Math.max(16, Math.min(40, I.rx * 0.32)); var wl = bw * 0.28; var ex = (x - I.x) / (I.rx + wl), ez = (z - I.z) / (I.rz + wl); if (ex * ex + ez * ez < 1) return false; } return true; };
    ctx.seaTest = seaTest; ctx.seaY = SEA; if (ctx.ripples && ctx.ripples.setSea) { ctx.ripples.setSea(seaTest, SEA, seaMat); log('coast: sea registered as a ripple body (surface ' + SEA + ')'); }
    /* WORLD PIVOT PASS 2: break the visible prototype tiling — the drifting normal map is sampled twice (1× and 0.37× with an offset) and
       blended, so the 13 m repeat no longer reads as a regular diamond grid. CHAINED after the ripple system's hole patch (which owns
       onBeforeCompile when enabled); guarded: if the chunk text ever changes, the plain map stays. */
    if (seaMat.normalMap) { var chunk = THREE.ShaderChunk && THREE.ShaderChunk.normal_fragment_maps, from = 'vec3 mapN = texture2D( normalMap, vNormalMapUv ).xyz * 2.0 - 1.0;';
      if (chunk && chunk.indexOf(from) >= 0) { var prevOBC = seaMat.onBeforeCompile, prevKey = seaMat.customProgramCacheKey;
        seaMat.onBeforeCompile = function (sh, r) { if (prevOBC) prevOBC.call(this, sh, r); sh.fragmentShader = sh.fragmentShader.replace('#include <normal_fragment_maps>', chunk.replace(from, 'vec3 mapN = normalize( ( texture2D( normalMap, vNormalMapUv ).xyz * 2.0 - 1.0 ) + ( texture2D( normalMap, vNormalMapUv * 0.37 + vec2( 0.31, 0.17 ) ).xyz * 2.0 - 1.0 ) * 0.85 );')); };
        seaMat.customProgramCacheKey = function () { return (prevKey ? prevKey.call(this) : '') + '|mahworld-sea-dual-normal'; }; seaMat.needsUpdate = true; } }
    /* 3. islands: beach ring (sea_y − DROP → 0) + a rising plateau + crystal spires + tree silhouettes (instanced) */
    var landMat = new THREE.MeshStandardMaterial({ color: 0x223048, roughness: 0.7, metalness: 0.35, flatShading: true }); own.push(landMat); var spireMat = (M.crystal || new THREE.MeshStandardMaterial({ color: 0xe8f4ff, roughness: 0.1, metalness: 0.6 })).clone(); spireMat.vertexColors = true; own.push(spireMat); var FAMS = ctx.registry && ctx.registry.crystal_families || {};   /* island spires carry their island's crystal family (owner redirect 2026-09-19: regions read from afar) */ var treeMat = M.sapphire || new THREE.MeshStandardMaterial({ color: 0x1c2a46 });
    var landGeos = [], spireGeos = [], treeMats = []; var treeCount = 0; var isl = C.islands || []; var foamPts = [];
    isl.forEach(function (I) { var rr = rnd(I.seed || 5); var n = 72; var ring = ellipsePoints(I.x, I.z, I.rx, I.rz, n); var bw = Math.max(16, Math.min(40, I.rx * 0.32)); var wl = bw * 0.28; var iprof = function (d) { if (d <= wl) { var t = d / wl; return SEA * (t * t * (3 - 2 * t)); } var u = (d - wl) / (bw - wl); return SEA + (-DROP - SEA) * (u * u * (3 - 2 * u)); }; var ivOf = function (d) { return Math.min(1, d <= wl ? 0.28 * (d / wl) : 0.28 + 0.72 * ((d - wl) / (bw - wl))); };
      var beach = band(ring, [0, wl * 0.4, wl, wl + bw * 0.25, bw], iprof, ivOf); beach.computeVertexNormals(); landGeos.push({ g: beach, shore: true });
      /* plateau: concentric rings rising to h with a soft dome; a few noisy bumps */ var K = 5; var pos = [], idx = [], nrm = []; var centre = pos.length; for (var k = 0; k <= K; k++) { var f = 1 - k / K; var yk = I.h * Math.pow(1 - Math.pow(1 - f, 1.6), 1.0); for (var i2 = 0; i2 < n; i2++) { var p = ring[i2]; var bump = 1 + (rr() - 0.5) * 0.12; pos.push(I.x + (p.x - I.x) * f * (k === 0 ? 1 : bump), k === 0 ? 0 : yk * (0.85 + 0.3 * rr()), I.z + (p.z - I.z) * f * (k === 0 ? 1 : bump)); } }
      for (var k2 = 0; k2 < K; k2++) for (var i3 = 0; i3 < n; i3++) { var a = k2 * n + i3, b = k2 * n + (i3 + 1) % n, c2 = (k2 + 1) * n + i3, e = (k2 + 1) * n + (i3 + 1) % n; idx.push(a, b, c2, b, e, c2); }
      var pg = new THREE.BufferGeometry(); pg.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); pg.setIndex(idx); faceUp(pg); landGeos.push({ g: pg.toNonIndexed(), shore: false });
      for (var s = 0; s < (I.spires || 0); s++) { var ang = rr() * Math.PI * 2, rad = rr() * 0.55; var sx = I.x + Math.cos(ang) * I.rx * rad, sz = I.z + Math.sin(ang) * I.rz * rad; var sh = I.h * (0.9 + rr() * 2.2), sr = 4 + rr() * 9; var og = new THREE.OctahedronGeometry(1, 0); og.scale(sr, sh, sr); og.rotateY(rr() * 3); og.translate(sx, I.h * 0.6 + sh * 0.55, sz); var fc = new THREE.Color(FAMS[I.family] && FAMS[I.family].color || '#e8f4ff').lerp(new THREE.Color(0xe8f4ff), 0.35); var cc = new Float32Array(og.attributes.position.count * 3); for (var ci = 0; ci < og.attributes.position.count; ci++) { var b = 0.85 + 0.3 * rr(); cc[ci * 3] = fc.r * b; cc[ci * 3 + 1] = fc.g * b; cc[ci * 3 + 2] = fc.b * b; } og.setAttribute('color', new THREE.BufferAttribute(cc, 3)); spireGeos.push(og); }
      for (var t2 = 0; t2 < (I.trees || 0); t2++) { var ta = rr() * Math.PI * 2, tr = 0.3 + rr() * 0.6; treeMats.push([I.x + Math.cos(ta) * I.rx * tr, I.h * (1 - Math.pow(tr, 1.6)) * 0.95, I.z + Math.sin(ta) * I.rz * tr, 6 + rr() * 8, rr() * 3]); treeCount++; }
      foamPts.push({ pts: ring, wl: wl, cx: I.x, cz: I.z }); info.islands++; });
    if (landGeos.length) { var shoreG = landGeos.filter(function (x) { return x.shore; }).map(function (x) { return x.g; }); var plateauG = landGeos.filter(function (x) { return !x.shore; }).map(function (x) { return x.g; }); if (shoreG.length) add(mergeList(shoreG), shoreMat, 'ISLAND_SHORES'); if (plateauG.length) add(mergeList(plateauG), landMat, 'ISLAND_LAND'); }
    if (spireGeos.length) add(mergeList(spireGeos), spireMat, 'ISLAND_SPIRES');
    if (treeCount) { var tg = new THREE.OctahedronGeometry(1, 0); tg.scale(1, 1.8, 1); tg.translate(0, 1.8, 0); var trees = new THREE.InstancedMesh(tg, treeMat, treeCount); var m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), v = new THREE.Vector3(), sc = new THREE.Vector3(); treeMats.forEach(function (t, i) { q.setFromAxisAngle(new THREE.Vector3(0, 1, 0), t[4]); v.set(t[0], t[1], t[2]); sc.set(t[3] * 0.45, t[3] * 0.5, t[3] * 0.45); m4.compose(v, q, sc); trees.setMatrixAt(i, m4); }); trees.instanceMatrix.needsUpdate = true; trees.name = 'ISLAND_TREES'; trees.userData.noMerge = true; trees.frustumCulled = false; group.add(trees); meshes.push(trees); info.draw_calls++; info.tris += 8 * treeCount; }
    /* 4. foam lines at every waterline (mainland + islands): bands that swing in / out along the normal */
    var fmat = new THREE.MeshBasicMaterial({ map: foamTexture(), transparent: true, opacity: 0.5, depthWrite: false, color: 0xf2f8ff }); own.push(fmat); var FW = C.foam_w || 1.6;
    var mkFoam = function (pts2, wl2, id, cx, cz) { var g = band(pts2, [wl2 - FW / 2, wl2 + FW / 2], function () { return SEA + 0.012; }, function (d) { return (d - (wl2 - FW / 2)) / FW; }); var fm = add(g, fmat, id, 2); fm.userData.foam = { cx: cx, cz: cz, phase: (cx + cz) * 0.013 }; foam.push(fm); };
    mkFoam(pts, WL, 'COAST_FOAM', 0, (C.outline.z1 + C.outline.z2) / 2); foamPts.forEach(function (f, i) { mkFoam(f.pts, f.wl, 'ISLAND_FOAM_' + i, f.cx, f.cz); });
    /* the legacy haze plain is replaced by the sea */ var hz = ctx.scene.getObjectByName ? ctx.scene.getObjectByName('HAZE_PLAIN') : null; if (hz) hz.visible = false;
    applyNight(night); log('coast: mainland beach ring + sea + ' + info.islands + ' islands, ' + info.draw_calls + ' draw calls, ' + info.tris + ' tris');
  }
  function mergeList(list) { var pos = [], nrm = [], uv = [], col = []; list.forEach(function (g) { var ng = g.index ? g.toNonIndexed() : g; var p = ng.attributes.position, nn = ng.attributes.normal, u = ng.attributes.uv, c = ng.attributes.color; for (var i = 0; i < p.count; i++) { pos.push(p.getX(i), p.getY(i), p.getZ(i)); if (nn) nrm.push(nn.getX(i), nn.getY(i), nn.getZ(i)); uv.push(u ? u.getX(i) : 0, u ? u.getY(i) : 0.62); if (c) col.push(c.getX(i), c.getY(i), c.getZ(i)); } }); var out = new THREE.BufferGeometry(); out.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); out.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2)); if (col.length === pos.length) out.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); if (nrm.length === pos.length) out.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3)); else out.computeVertexNormals(); return out; }
  function applyNight(n) { var P = n ? NIGHT : DAY; if (seaMat) { seaMat.color.setHex(P.color); seaMat.roughness = P.rough; seaMat.envMapIntensity = P.env; seaMat.opacity = P.opacity; } }
  function tick(dt, t) { clock = (typeof t === 'number' && isFinite(t)) ? t : clock + (dt || 0); for (var i = 0; i < foam.length; i++) { var f = foam[i], fd = f.userData.foam; var ph = clock * (2 * Math.PI / (C && C.foam_period_s || 5.2)) + fd.phase; var sw = (C && C.foam_swing_m || 1.1) * (0.8 * Math.sin(ph) + 0.2 * Math.sin(ph * 2.1)); var k = 1 + sw / 200; f.scale.set(k, 1, k); f.position.set(fd.cx * (1 - k), 0, fd.cz * (1 - k)); f.material.opacity = 0.3 + 0.25 * (0.5 + 0.5 * Math.sin(ph + 1.1)); } }   /* a scale about the body's centre ≈ an in / out shift of the foam line along the shore normal */
  function setNight(n) { night = !!n; applyNight(night); }
  function dispose() { meshes.forEach(function (m) { if (m.parent) m.parent.remove(m); if (m.geometry) m.geometry.dispose(); }); meshes = []; own.forEach(function (m) { m.dispose(); }); own = []; if (group && group.parent) group.parent.remove(group); group = null; foam = []; }
  function debug() { return { islands: info.islands, draw_calls: info.draw_calls, tris: info.tris, sea_y: C ? C.sea_y : null, beach_w: C ? C.beach_w : null, outline: C ? C.outline : null, foam_lines: foam.length, night: night }; }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug, outline: function () { return C ? C.outline : null; } };
}
