import { ridgeStations, ridgeFaceSegment } from './ridgeLayout.js';
import { applyGeology } from './surfaceDetail.js'; import { RIDGE_DIP, ridgeRowPlan } from './ridgeSculpt.js';
import { toCreasedNormals } from '../../vendor/three/BufferGeometryUtils.js'; import { plumeMaterial } from './formKit.js'; import { ridgeWarpField, sculptRidge } from './ridgeSculpt.js'; import { veilWaterMaterial, veilCurtainKeep } from './veilFalls.js';

/* JOB B world module — MACRO GEOGRAPHY (owner B8 §16–§18 "floor down, world up"). Data: registry.macro.
   MOUNTAINS: two ridge bands between the sanctuaries and the far massifs (NEAR 300–420 m, MID 470–560 m) — each ONE merged ribbon mesh
   (a closed arc of peaks with a seeded profile), lit + fogged so they step back in atmospheric falloff, graphite-blue rock with crystal
   accents on the peaks; REAL PASSES = the profile dips to a few metres at the bearings the routes leave the map (the crown terraces north,
   the west highland, the east range / lake, the two crown lookouts). The south stays the open sea.
   WATERFALLS: each has a SOURCE and a RECEIVER — TITAN_FALL drops from the mountain ledge (12 m) into the Titan lake (a scrolling sheet, a
   foam base, a mist cloud, a periodic ripple impulse at the contact point through water.js); NORTH_FALL pours off the north ridge notch
   into a plunge basin whose channel meets RIVER_N (macro scale, seen from the crown terraces).
   SKY ENERGY: three sparse vertical conduits, each from a real source — the Gold Temple crown, the Blue Tower crown and the north pass
   sanctuary beacon — additive gradient columns that pulse slowly (one InstancedMesh). Phone budget: 2 ridge meshes + 2 sheets + 2 foam +
   1 mist + 1 beam instanced mesh ≈ 8 draw calls, no per-frame allocation, LOW tier drops the mist. */
var NIGHT_SNOW = 0.16;   /* M19: moonlit snow glow at night (a shared uniform: the time switch never recompiles) */
var FAM = { gold: 0xe6c36a, blue: 0x2c62d8, red: 0xd8404a, purple: 0x8a5fd6, pink: 0xff5fb0, platinum: 0xdfe6ee, cyan: 0xdfe8ff };   /* colour law 2026-09-25: the civic 'cyan' key is neutral white light */
export function createMacro(ctx) {
  var THREE = ctx.THREE, log = ctx.log || function () { }; var group = null; var reg = null; var M = null; var own = []; var ridges = []; var falls = []; var beams = null; var clock = 0; var night = !!ctx.night; var beamMat = null, sheetMats = [], foamMats = [], mistSprites = [];
  function tier() { try { return ctx.quality && ctx.quality.tier ? ctx.quality.tier() : 'MED'; } catch (e) { return 'MED'; } }
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  /* ---- ridge ribbon: bearings around the map, profile height h(b) with passes; a fan of peaks (triangles) from a base ring to a crest ring ---- */
  function ridge(R, idx) { var N = R.segments || 160; var pos = [], col = [], nrm = []; var base = new THREE.Color(R.color_base), peak = new THREE.Color(R.color_peak), crystal = new THREE.Color(R.color_crystal);
    var stations = ridgeStations(R, idx), RP = ridgeRowPlan(R, tier()), tags = [];
    var rock = base.clone().lerp(peak, 0.2);   /* M19: the rock's own value — graphite, a step lighter than the registry base */
    var C = new THREE.Color(); function push(x, y, z, c, n) { pos.push(x, y, z); col.push(c.r, c.g, c.b); nrm.push(n.x, n.y, n.z); }
    for (var k = 0; k < N; k++) { var F = ridgeFaceSegment(stations, k), a = F.a, b2 = F.b; if (a.h < 2 && b2.h < 2) continue; var ox = F.ox, oz = F.oz;
      var crestA = F.crestA, crestB = F.crestB, inA = F.innerA, inB = F.innerB, outA = F.outerA, outB = F.outerB;
      var tA = Math.min(1, a.h / R.h_max), tB = Math.min(1, b2.h / R.h_max); var cA = rock.clone().lerp(peak, tA * tA * 0.3); var cB = rock.clone().lerp(peak, tB * tB * 0.3); if (tA > 0.9) cA.lerp(crystal, (tA - 0.9) / 0.1 * 0.12); if (tB > 0.9) cB.lerp(crystal, (tB - 0.9) / 0.1 * 0.12); var cBase = rock.clone().multiplyScalar(0.8);   /* M19: one rock body — the faces no longer bleach from graphite to paper-white with height; the shader's snow carries the altitude read */
      var nIn = new THREE.Vector3(-ox, 0.8, -oz).normalize(), nOut = new THREE.Vector3(ox, 0.7, oz).normalize();   /* inner face (toward the player) / outer face */
      var siA = { x: inA.x * 0.54 + crestA.x * 0.46, y: inA.y * 0.54 + crestA.y * 0.46, z: inA.z * 0.54 + crestA.z * 0.46 }, siB = { x: inB.x * 0.54 + crestB.x * 0.46, y: inB.y * 0.54 + crestB.y * 0.46, z: inB.z * 0.54 + crestB.z * 0.46 };
      var soA = { x: outA.x * 0.58 + crestA.x * 0.42, y: outA.y * 0.58 + crestA.y * 0.42, z: outA.z * 0.58 + crestA.z * 0.42 }, soB = { x: outB.x * 0.58 + crestB.x * 0.42, y: outB.y * 0.58 + crestB.y * 0.42, z: outB.z * 0.58 + crestB.z * 0.42 };
      var uiA = { x: inA.x * 0.24 + crestA.x * 0.76, y: inA.y * 0.24 + crestA.y * 0.76, z: inA.z * 0.24 + crestA.z * 0.76 }, uiB = { x: inB.x * 0.24 + crestB.x * 0.76, y: inB.y * 0.24 + crestB.y * 0.76, z: inB.z * 0.24 + crestB.z * 0.76 };
      var uoA = { x: outA.x * 0.28 + crestA.x * 0.72, y: outA.y * 0.28 + crestA.y * 0.72, z: outA.z * 0.28 + crestA.z * 0.72 }, uoB = { x: outB.x * 0.28 + crestB.x * 0.72, y: outB.y * 0.28 + crestB.y * 0.72, z: outB.z * 0.28 + crestB.z * 0.72 };
      /* WORLD PIVOT PASS 2 (corrected at checkpoint 5): only the OUTER face rows take the seeded rock displacement. The INNER face is the
         owner OP10 shared visible/collision surface (ridgeLayout → VISIBLE_RIDGE_INNER_FACE proxies), so its rows stay exactly on the proxy
         plane — pushing them into the body left invisible walls in front of the rock. The inner face gets its rock read from rockShader(). */
      var dsp = function (P, sx, sz, amp, sd) { var n = Math.sin(P.x * 0.061 + sd * 1.7) * 0.5 + Math.sin(P.z * 0.053 - sd * 0.9) * 0.35 + Math.sin((P.x + P.z) * 0.137 + sd) * 0.15; var m = Math.max(0, n * 0.5 + 0.5) * amp; return { x: P.x + sx * m, y: P.y + (n * 0.5) * amp * 0.35, z: P.z + sz * m }; };
      var hA = Math.max(2, a.h), hB = Math.max(2, b2.h), rA = Math.hypot(a.x, a.z) || 1, rB = Math.hypot(b2.x, b2.z) || 1;   /* M10: each station's own radial (not the segment average), so neighbouring segments share their outer-face rows exactly — no slivers */
      soA = dsp(soA, -a.x / rA, -a.z / rA, hA * 0.12, idx + 3); soB = dsp(soB, -b2.x / rB, -b2.z / rB, hB * 0.12, idx + 3); uoA = dsp(uoA, -a.x / rA, -a.z / rA, hA * 0.09, idx + 4); uoB = dsp(uoB, -b2.x / rB, -b2.z / rB, hB * 0.09, idx + 4);
      var ciA = cBase.clone().lerp(cA, 0.46), ciB = cBase.clone().lerp(cB, 0.46), coA = cBase.clone().lerp(cA, 0.38), coB = cBase.clone().lerp(cB, 0.38), cuiA = cBase.clone().lerp(cA, 0.76), cuiB = cBase.clone().lerp(cB, 0.76), cuoA = cBase.clone().lerp(cA, 0.7), cuoB = cBase.clone().lerp(cB, 0.7);
      push(inA.x, inA.y, inA.z, cBase, nIn); push(siB.x, siB.y, siB.z, ciB, nIn); push(siA.x, siA.y, siA.z, ciA, nIn); push(inA.x, inA.y, inA.z, cBase, nIn); push(inB.x, inB.y, inB.z, cBase, nIn); push(siB.x, siB.y, siB.z, ciB, nIn);
      push(siA.x, siA.y, siA.z, ciA, nIn); push(uiB.x, uiB.y, uiB.z, cuiB, nIn); push(uiA.x, uiA.y, uiA.z, cuiA, nIn); push(siA.x, siA.y, siA.z, ciA, nIn); push(siB.x, siB.y, siB.z, ciB, nIn); push(uiB.x, uiB.y, uiB.z, cuiB, nIn);
      push(uiA.x, uiA.y, uiA.z, cuiA, nIn); push(crestB.x, crestB.y, crestB.z, cB, nIn); push(crestA.x, crestA.y, crestA.z, cA, nIn); push(uiA.x, uiA.y, uiA.z, cuiA, nIn); push(uiB.x, uiB.y, uiB.z, cuiB, nIn); push(crestB.x, crestB.y, crestB.z, cB, nIn);
      push(outA.x, outA.y, outA.z, cBase, nOut); push(soA.x, soA.y, soA.z, coA, nOut); push(soB.x, soB.y, soB.z, coB, nOut); push(outA.x, outA.y, outA.z, cBase, nOut); push(soB.x, soB.y, soB.z, coB, nOut); push(outB.x, outB.y, outB.z, cBase, nOut);
      push(soA.x, soA.y, soA.z, coA, nOut); push(uoA.x, uoA.y, uoA.z, cuoA, nOut); push(uoB.x, uoB.y, uoB.z, cuoB, nOut); push(soA.x, soA.y, soA.z, coA, nOut); push(uoB.x, uoB.y, uoB.z, cuoB, nOut); push(soB.x, soB.y, soB.z, coB, nOut);
      push(uoA.x, uoA.y, uoA.z, cuoA, nOut); push(crestA.x, crestA.y, crestA.z, cA, nOut); push(crestB.x, crestB.y, crestB.z, cB, nOut); push(uoA.x, uoA.y, uoA.z, cuoA, nOut); push(crestB.x, crestB.y, crestB.z, cB, nOut); push(uoB.x, uoB.y, uoB.z, cuoB, nOut);
      tags.push([1, RP.inner[0]], [0, RP.inner[0]], [1, RP.inner[1]], [0, RP.inner[1]], [1, RP.inner[2]], [0, RP.inner[2]], [1, RP.outer[0]], [2, RP.outer[0]], [1, RP.outer[1]], [2, RP.outer[1]], [1, RP.outer[2]], [2, RP.outer[2]]); }   /* M19: each triangle's row edge + its band's strip count (ridgeSculpt strip mode) */
    /* M10 RIDGE SCULPT (lab/world/ridgeSculpt.js): beyond the reach square only — the fins eased into a continuous crest with secondary summits
       and saddles, rock shelves stepping the faces, fall-line gullies notching the crest. Inside 312 m every triangle is untouched, so the
       collision face and its proxies are exactly as authored. Waterfall lips on this ridge are held still.
       M19 (owner 2026-09-27: "mountains still not real enough … better large-scale silhouettes, geological continuity, erosion, ledges, strata,
       broken rock shelves, less polygon faceting, softer distant mountains, atmospheric depth — not fog"): the same shell, re-cut — shelves
       on ONE regional bedding (dip / fold / fault blocks shared with the rock shader), ~110 m spurs and couloirs instead of 34 m V-gullies
       (the crumpled-foil read), strip subdivision with real vertical resolution; the rock is one graphite body (no bleach to white with
       height) under alpine snow that follows ledges and relief benches, a scree apron, varnish streaks and height-thinned haze. The in-reach
       inner face (the collision plane) is unchanged: shader only there, exactly as before. */
    var sculptOn = true; try { sculptOn = !/[?&]ridgeSculpt=0/.test(location.search); } catch (e) { }
    var sc = null; if (sculptOn) { var keep = ((M && M.waterfalls) || []).filter(function (W) { return W.source_id === R.id; }).reduce(function (acc, W) { acc.push({ x: W.source.x, z: W.source.z, r: 28 }); (W.keep_line || []).forEach(function (K) { acc.push({ x: K[0], z: K[1], r: K[2] }); }); veilCurtainKeep(stations, W).forEach(function (K) { acc.push(K); }); return acc; }, []);   /* M12: a keep_line holds the whole face under a long fall still */
      sc = sculptRidge(pos, col, ridgeWarpField(R, stations, idx, keep), tier() === 'HIGH' ? 4 : tier() === 'LOW' ? 1 : 3, tags, RP.cols); pos = sc.pos; col = sc.col; nrm = sc.nrm; }
    /* M19 (found by the M19 mountains review, confirmed in a headless build: 98 % of the ribbon's triangles faced DOWN): the ribbon has been
       wound inside-out since M6. With a FrontSide material, from anywhere inside the ring the INNER face — the owner OP10 collision face — was
       back-face culled, and the eye saw the displaced OUTER face from behind, lit from below: dark, shelves reading as overhang undersides,
       and the visible rock standing behind the wall the host actually collides with. Every triangle is re-wound here (corners 1 and 2
       swapped, normals negated): the positions are untouched, so the collision face stays bit-identical (gameplay_world_m19_mountains 7). */
    for (var fw = 0; fw < pos.length; fw += 9) for (var fc = 0; fc < 3; fc++) { var ta = pos[fw + 3 + fc]; pos[fw + 3 + fc] = pos[fw + 6 + fc]; pos[fw + 6 + fc] = ta; ta = col[fw + 3 + fc]; col[fw + 3 + fc] = col[fw + 6 + fc]; col[fw + 6 + fc] = ta; ta = nrm[fw + 3 + fc]; nrm[fw + 3 + fc] = -nrm[fw + 6 + fc]; nrm[fw + 6 + fc] = -ta; nrm[fw + fc] = -nrm[fw + fc]; }
    var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); g.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3)); own.push(g);
    var softRock = true; try { softRock = !/[?&]rockSoft=0/.test(location.search); } catch (e) { }
    if (softRock) { var gs = toCreasedNormals(g, 55 * Math.PI / 180); if (gs !== g) { own.push(gs); g = gs; } }   /* DESIGN DNA: the rock flows — facet breaks under 55° shade smooth (the sculpt's subdivision seams, the small fins), real ledges and crest breaks stay crisp. ?rockSoft=0 for the A/B */
    var mat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.86, metalness: 0.04, flatShading: !softRock, envMapIntensity: 0.14 });   /* faceted rock that answers the Sun; M9: less sky ambient (the faces keep their dark mass) — an A/B showed smoothed normals wash the rock out pale */ own.push(mat);
    var geoLow = tier() === 'LOW'; applyGeology(THREE, mat, { snowY: R.h_max * 0.6, strata: 2.6, tier: tier(), relief: geoLow ? null : [8, 24], reliefPolar: [0, 0, R.dist_m || 400], polarUV: !geoLow, relief3: tier() === 'HIGH' ? [18, 80] : null, cavity: geoLow ? 0 : 0.3, varnish: geoLow ? 0 : 0.7, talus: geoLow ? null : [-3, 9], dip: RIDGE_DIP, alpine: 1, aerial: [14, 190, 0.42], nightSnow: mat.userData.nightSnow = { value: night ? NIGHT_SNOW : 0 } });   /* M19: regional bedding dip (shared with ridgeSculpt's shelves), snow on the flatter ground of the sculpted shell, a scree apron at the foot, value relief that reads in shadow, varnish streaks, height-thinned haze. Tier law (M19 review fix): LOW is the M18 shader minus its relief fbm (linear dip, plain M18 snow line, haze — applyGeology drops the alpine / fault / lithology terms on LOW), MED drops the second relief order, HIGH carries everything */   /* M9: MACRO RELIEF — fall-line gullies and buttress ribs cut across the facet planes, so the big faces read as rock mass instead of low-poly triangles (polar coordinates: the ridge is a ring, continuous across faces) */ var mesh = new THREE.Mesh(g, mat); mesh.name = 'MACRO_RIDGE_' + R.id; mesh.frustumCulled = false; mesh.receiveShadow = false; mesh.userData.noMerge = true; group.add(mesh); ridges.push({ R: R, mesh: mesh, tris: pos.length / 9, sculpted: sc ? sc.sculpted : 0 }); return mesh; }
  /* M8C: the ridge faces use the shared GEOLOGY pipeline (lab/world/surfaceDetail.js applyGeology — strata, ledges, fracture joints, clefts,
     macro / micro tone, a derivative bump so every feature catches the Sun, snow on shallow high faces). Shader-only: the inner face stays
     exactly on the owner OP10 collision plane. */
  /* ---- waterfalls ---- */
  function softTexture() { var c = document.createElement('canvas'); c.width = c.height = 64; var g = c.getContext('2d'); var gr = g.createRadialGradient(32, 32, 2, 32, 32, 32); gr.addColorStop(0, 'rgba(255,255,255,0.9)'); gr.addColorStop(0.5, 'rgba(255,255,255,0.35)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 64, 64); var t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; own.push(t); return t; }
  function waterfall(W, soft) { if (W.style === 'VEIL') return;   /* M12: the Veil Falls are drawn by veilFalls.js */
    var drop = W.source.y - W.receiver.y; var sheetG = new THREE.PlaneGeometry(W.width_m, drop, 1, 8); own.push(sheetG); var sm = veilWaterMaterial(THREE, { night: night, sx: Math.max(0.3, Math.min(1, W.width_m / 30)), flipV: true }); own.push(sm);   /* M12: the Veil water, scaled to this sheet */ var sheet = new THREE.Mesh(sheetG, sm); sheet.position.set(W.source.x, W.receiver.y + drop / 2, W.source.z); sheet.rotation.y = W.yaw_rad || 0; sheet.name = 'MACRO_FALL_' + W.id; sheet.renderOrder = 2; sheet.userData.noMerge = true; group.add(sheet); sheetMats.push(sm);
    var foamG = new THREE.CircleGeometry(W.width_m * 0.9, 20); foamG.rotateX(-Math.PI / 2); own.push(foamG); var fm = new THREE.MeshBasicMaterial({ map: soft, transparent: true, opacity: 0.55, depthWrite: false, color: 0xffffff, blending: THREE.AdditiveBlending }); own.push(fm); var foam = new THREE.Mesh(foamG, fm); foam.position.set(W.receiver.x, W.receiver.y + 0.05, W.receiver.z); foam.userData.noMerge = true; group.add(foam); foamMats.push(fm);
    var mists = []; if (tier() !== 'LOW') { for (var i = 0; i < 3; i++) { var sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: soft, transparent: true, opacity: 0.22, depthWrite: false, color: 0xe8f4ff })); own.push(sp.material); var s = W.width_m * (0.9 + i * 0.5); sp.scale.set(s, s * 0.7, 1); sp.position.set(W.receiver.x + (i - 1) * W.width_m * 0.35, W.receiver.y + 1.2 + i * 1.1, W.receiver.z); sp.userData.vfx = true; group.add(sp); mists.push(sp); mistSprites.push(sp); } }
    if (W.basin) { var bg = new THREE.CircleGeometry(W.basin.r, 24); bg.rotateX(-Math.PI / 2); own.push(bg); var bm = new THREE.MeshStandardMaterial({ color: 0x2d5f8a, roughness: 0.12, metalness: 0.55, transparent: true, opacity: 0.86 }); own.push(bm); var basin = new THREE.Mesh(bg, bm); basin.position.set(W.basin.x, W.basin.y, W.basin.z); basin.userData.noMerge = true; group.add(basin); if (W.basin.channel) { var ch = W.basin.channel; var cl = Math.hypot(ch.to[0] - W.basin.x, ch.to[1] - W.basin.z); var cg = new THREE.PlaneGeometry(ch.w, cl); cg.rotateX(-Math.PI / 2); own.push(cg); var channel = new THREE.Mesh(cg, bm); channel.position.set((W.basin.x + ch.to[0]) / 2, W.basin.y, (W.basin.z + ch.to[1]) / 2); channel.rotation.y = Math.atan2(ch.to[0] - W.basin.x, ch.to[1] - W.basin.z); channel.userData.noMerge = true; group.add(channel); } }
    if (ctx.auraRequests) { var ux = W.receiver.x - W.source.x, uz = W.receiver.z - W.source.z, ul = Math.hypot(ux, uz) || 1, wv = W.width_m; ux /= ul; uz /= ul;   /* M12 AURA: the older falls speak the Veil's language at their own scale (no new draw) */
      ctx.auraRequests.push({ x: (W.source.x + W.receiver.x) / 2 + ux * wv * 0.3, y: (W.source.y + W.receiver.y) / 2, z: (W.source.z + W.receiver.z) / 2 + uz * wv * 0.3, size: wv * 0.9, aspect: Math.max(1, drop / (1.8 * wv)), ring: 0, tint: 0x8c84c8, spectral: 0.55, intensity: 0.2, pull: wv * 0.5, phase: wv });   /* the glow hugging the sheet */
      ctx.auraRequests.push({ x: W.receiver.x + ux * wv * 0.5, y: W.receiver.y + wv * 0.4, z: W.receiver.z + uz * wv * 0.5, size: wv * 1.7, aspect: 0.55, ring: 0, tint: 0xeef4ff, spectral: 0.35, intensity: 0.3, pull: wv * 0.6, nightK: 0.55 });   /* the base mist bloom */
      if (drop > 30) ctx.auraRequests.push({ x: W.receiver.x + ux * wv * 1.8, y: W.receiver.y + 2.5, z: W.receiver.z + uz * wv * 1.8, size: wv * 2.4, aspect: 1, ring: 0.8, ringW: 0.07, arc: 1, breakup: 0.35, tint: 0x0c0c14, spectral: 1.0, intensity: 0.8, pull: wv * 0.4, phase: 0.8, nightK: 0.3 }); }   /* a mist-bow only where the drop makes spray */
    falls.push({ W: W, sheet: sheet, foam: foam, mists: mists, nextImpulse: 0.4 + Math.random() }); }
  /* ---- sky energy conduits ---- */
  function buildBeams(list) { if (!list.length) return; var g = new THREE.CylinderGeometry(0.34, 1, 1, 24, 1, true); g.translate(0, 0.5, 0); own.push(g);
    /* DESIGN DNA (owner: softer, more magical power — no harsh beams): each sky beam is a tapered light plume, the roster's energy-tip ramp
       turned skyward — white at the root, its class colour higher up — with a soft silhouette (the rim fades by facing ratio), soft bands
       drifting slowly upward and a slow breath. Same instanced draw, same placement. */
    beamMat = plumeMaterial(THREE, night ? 0.7 : 0.42);
    own.push(beamMat); beams = new THREE.InstancedMesh(g, beamMat, list.length); beams.name = 'MACRO_SKY_BEAMS'; beams.userData.noMerge = true; beams.frustumCulled = false; var m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), v = new THREE.Vector3(), s = new THREE.Vector3(), col = new THREE.Color(); list.forEach(function (B, i) { v.set(B.x, B.y, B.z); s.set(B.radius_m, B.height_m, B.radius_m); m4.compose(v, q, s); beams.setMatrixAt(i, m4); col.setHex(FAM[B.family] || FAM.cyan); beams.setColorAt(i, col); }); if (beams.instanceColor) beams.instanceColor.needsUpdate = true; group.add(beams); }
  function build() { group = new THREE.Group(); group.name = 'JOBB_MACRO'; group.userData.noMerge = true; ctx.group.add(group); reg = ctx.registry; M = reg && reg.macro; if (!M) { log('macro: registry.macro missing — nothing built'); return; }
    (M.mountains || []).forEach(ridge); var soft = softTexture(); (M.waterfalls || []).forEach(function (W) { waterfall(W, soft); }); buildBeams(M.sky_beams || []); applyNight(night);
    log('macro ready: ridges ' + ridges.map(function (r) { return r.R.id + ' ' + r.tris + ' tris'; }).join(', ') + '; waterfalls ' + falls.map(function (f) { return f.W.id; }).join(', ') + '; sky beams ' + ((M.sky_beams || []).length)); }
  function applyNight(n) { ridges.forEach(function (r) { if (r.mesh.material.userData.nightSnow) r.mesh.material.userData.nightSnow.value = n ? NIGHT_SNOW : 0; r.mesh.material.emissive = r.mesh.material.emissive || new THREE.Color(0); r.mesh.material.emissive.setHex(n ? 0x13243a : 0x000000); r.mesh.material.emissiveIntensity = n ? 0.78 : 0; r.mesh.material.color.setScalar(n ? 0.58 : 1); });   /* PASS 2b: the pale crystal caps must not read as lit white paper under the Moon */ if (beamMat) beamMat.uniforms.uOp.value = n ? 0.7 : 0.42; sheetMats.forEach(function (m) { m.uniforms.uNight.value = n ? 1 : 0; }); }
  function tick(dt, t) { clock = (typeof t === 'number' && isFinite(t)) ? t : clock + (dt || 0); if (!group) return; for (var i = 0; i < sheetMats.length; i++) { var f = falls[i]; var sp = (f && f.W.speed || 1); sheetMats[i].uniforms.uTime.value = clock * sp; } for (var k = 0; k < foamMats.length; k++) foamMats[k].opacity = 0.45 + 0.15 * Math.sin(clock * 4 + k); for (var m = 0; m < mistSprites.length; m++) { var msp = mistSprites[m]; msp.material.opacity = 0.16 + 0.1 * Math.sin(clock * 1.3 + m * 1.7); msp.material.rotation = Math.sin(clock * 0.4 + m) * 0.3; }
    if (beamMat) { beamMat.uniforms.uTime.value = clock; beamMat.uniforms.uOp.value = night ? 0.7 : 0.42; }
    /* contact disturbance: a ripple impulse where the fall meets a live water body (water.js), a few times a second per fall */ for (var q = 0; q < falls.length; q++) { var F = falls[q]; if (!F.W.ripple) continue; F.nextImpulse -= dt || 0; if (F.nextImpulse <= 0) { F.nextImpulse = 0.35 + Math.random() * 0.4; try { var wm = ctx.water; if (wm && wm.impulse) wm.impulse(F.W.receiver.x + (Math.random() - 0.5) * F.W.width_m * 0.6, F.W.receiver.z + (Math.random() - 0.5) * 1.2, 0.35, 1.6); } catch (e) { } } } }
  function setNight(n) { night = !!n; applyNight(night); }
  function debug() { return { ridges: ridges.map(function (r) { return { id: r.R.id, dist_m: r.R.dist_m, h: [r.R.h_min, r.R.h_max], passes: (r.R.passes || []).length, tris: r.tris, sculpted: r.sculpted }; }), waterfalls: falls.map(function (f) { return { id: f.W.id, drop_m: +(f.W.source.y - f.W.receiver.y).toFixed(1), source: f.W.source_id, receiver: f.W.receiver_id, ripple: !!f.W.ripple, mist: f.mists.length }; }), sky_beams: M && M.sky_beams ? M.sky_beams.map(function (b) { return b.id + '←' + b.source; }) : [], draw_calls: ridges.length + falls.length * 3 + mistSprites.length + (beams ? 1 : 0) }; }
  function dispose() { own.forEach(function (o) { try { o.dispose(); } catch (e) { } }); own = []; if (group && group.parent) group.parent.remove(group); }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug };
}
