import { ridgeStations, ridgeFaceSegment } from './ridgeLayout.js';

/* JOB B world module — MACRO GEOGRAPHY (owner B8 §16–§18 "floor down, world up"). Data: registry.macro.
   MOUNTAINS: two ridge bands between the sanctuaries and the far massifs (NEAR 300–420 m, MID 470–560 m) — each ONE merged ribbon mesh
   (a closed arc of peaks with a seeded profile), lit + fogged so they step back in atmospheric falloff, graphite-blue rock with crystal
   accents on the peaks; REAL PASSES = the profile dips to a few metres at the bearings the routes leave the map (the crown terraces north,
   the west highland, the east range / lake, the two crown lookouts). The south stays the open sea.
   WATERFALLS: each has a SOURCE and a RECEIVER — TITAN_FALL drops from the mountain ledge (12 m) into the Titan lake (a scrolling sheet, a
   foam base, a mist cloud, a periodic ripple impulse at the contact point through water.js); NORTH_FALL pours off the north ridge notch
   into a plunge basin whose channel meets RIVER_N (macro scale, seen from the crown terraces).
   SKY ENERGY: three sparse vertical conduits, each from a real source — the Gold Temple crown, the Blue Tower crown and the north pass
   sanctuary beacon — additive gradient columns that pulse slowly (one InstancedMesh). Phone budget: 2 ridge meshes + 2 sheets + 2 foam +
   1 mist + 1 beam instanced mesh ≈ 8 draw calls, no per-frame allocation, LOW tier drops the mist. */
var FAM = { gold: 0xe6c36a, blue: 0x2c62d8, red: 0xd8404a, purple: 0x8a5fd6, pink: 0xff5fb0, platinum: 0xdfe6ee, cyan: 0xdfe8ff };   /* colour law 2026-09-25: the civic 'cyan' key is neutral white light */
export function createMacro(ctx) {
  var THREE = ctx.THREE, log = ctx.log || function () { }; var group = null; var reg = null; var M = null; var own = []; var ridges = []; var falls = []; var beams = null; var clock = 0; var night = !!ctx.night; var beamMat = null, sheetMats = [], foamMats = [], mistSprites = [];
  function tier() { try { return ctx.quality && ctx.quality.tier ? ctx.quality.tier() : 'MED'; } catch (e) { return 'MED'; } }
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  /* ---- ridge ribbon: bearings around the map, profile height h(b) with passes; a fan of peaks (triangles) from a base ring to a crest ring ---- */
  function ridge(R, idx) { var N = R.segments || 160; var pos = [], col = [], nrm = []; var base = new THREE.Color(R.color_base), peak = new THREE.Color(R.color_peak), crystal = new THREE.Color(R.color_crystal);
    var stations = ridgeStations(R, idx);
    var C = new THREE.Color(); function push(x, y, z, c, n) { pos.push(x, y, z); col.push(c.r, c.g, c.b); nrm.push(n.x, n.y, n.z); }
    for (var k = 0; k < N; k++) { var F = ridgeFaceSegment(stations, k), a = F.a, b2 = F.b; if (a.h < 2 && b2.h < 2) continue; var ox = F.ox, oz = F.oz;
      var crestA = F.crestA, crestB = F.crestB, inA = F.innerA, inB = F.innerB, outA = F.outerA, outB = F.outerB;
      var tA = Math.min(1, a.h / R.h_max), tB = Math.min(1, b2.h / R.h_max); var cA = base.clone().lerp(peak, tA * tA); var cB = base.clone().lerp(peak, tB * tB); if (tA > 0.82) cA.lerp(crystal, (tA - 0.82) / 0.18 * 0.7); if (tB > 0.82) cB.lerp(crystal, (tB - 0.82) / 0.18 * 0.7); var cBase = base.clone().multiplyScalar(0.72);
      var nIn = new THREE.Vector3(-ox, 0.8, -oz).normalize(), nOut = new THREE.Vector3(ox, 0.7, oz).normalize();   /* inner face (toward the player) / outer face */
      var siA = { x: inA.x * 0.54 + crestA.x * 0.46, y: inA.y * 0.54 + crestA.y * 0.46, z: inA.z * 0.54 + crestA.z * 0.46 }, siB = { x: inB.x * 0.54 + crestB.x * 0.46, y: inB.y * 0.54 + crestB.y * 0.46, z: inB.z * 0.54 + crestB.z * 0.46 };
      var soA = { x: outA.x * 0.58 + crestA.x * 0.42, y: outA.y * 0.58 + crestA.y * 0.42, z: outA.z * 0.58 + crestA.z * 0.42 }, soB = { x: outB.x * 0.58 + crestB.x * 0.42, y: outB.y * 0.58 + crestB.y * 0.42, z: outB.z * 0.58 + crestB.z * 0.42 };
      var uiA = { x: inA.x * 0.24 + crestA.x * 0.76, y: inA.y * 0.24 + crestA.y * 0.76, z: inA.z * 0.24 + crestA.z * 0.76 }, uiB = { x: inB.x * 0.24 + crestB.x * 0.76, y: inB.y * 0.24 + crestB.y * 0.76, z: inB.z * 0.24 + crestB.z * 0.76 };
      var uoA = { x: outA.x * 0.28 + crestA.x * 0.72, y: outA.y * 0.28 + crestA.y * 0.72, z: outA.z * 0.28 + crestA.z * 0.72 }, uoB = { x: outB.x * 0.28 + crestB.x * 0.72, y: outB.y * 0.28 + crestB.y * 0.72, z: outB.z * 0.28 + crestB.z * 0.72 };
      /* WORLD PIVOT PASS 2 (corrected at checkpoint 5): only the OUTER face rows take the seeded rock displacement. The INNER face is the
         owner OP10 shared visible/collision surface (ridgeLayout → VISIBLE_RIDGE_INNER_FACE proxies), so its rows stay exactly on the proxy
         plane — pushing them into the body left invisible walls in front of the rock. The inner face gets its rock read from rockShader(). */
      var dsp = function (P, sx, sz, amp, sd) { var n = Math.sin(P.x * 0.061 + sd * 1.7) * 0.5 + Math.sin(P.z * 0.053 - sd * 0.9) * 0.35 + Math.sin((P.x + P.z) * 0.137 + sd) * 0.15; var m = Math.max(0, n * 0.5 + 0.5) * amp; return { x: P.x + sx * m, y: P.y + (n * 0.5) * amp * 0.35, z: P.z + sz * m }; };
      var hA = Math.max(2, a.h), hB = Math.max(2, b2.h);
      soA = dsp(soA, -ox, -oz, hA * 0.12, idx + 3); soB = dsp(soB, -ox, -oz, hB * 0.12, idx + 3); uoA = dsp(uoA, -ox, -oz, hA * 0.09, idx + 4); uoB = dsp(uoB, -ox, -oz, hB * 0.09, idx + 4);
      var ciA = cBase.clone().lerp(cA, 0.46), ciB = cBase.clone().lerp(cB, 0.46), coA = cBase.clone().lerp(cA, 0.38), coB = cBase.clone().lerp(cB, 0.38), cuiA = cBase.clone().lerp(cA, 0.76), cuiB = cBase.clone().lerp(cB, 0.76), cuoA = cBase.clone().lerp(cA, 0.7), cuoB = cBase.clone().lerp(cB, 0.7);
      push(inA.x, inA.y, inA.z, cBase, nIn); push(siB.x, siB.y, siB.z, ciB, nIn); push(siA.x, siA.y, siA.z, ciA, nIn); push(inA.x, inA.y, inA.z, cBase, nIn); push(inB.x, inB.y, inB.z, cBase, nIn); push(siB.x, siB.y, siB.z, ciB, nIn);
      push(siA.x, siA.y, siA.z, ciA, nIn); push(uiB.x, uiB.y, uiB.z, cuiB, nIn); push(uiA.x, uiA.y, uiA.z, cuiA, nIn); push(siA.x, siA.y, siA.z, ciA, nIn); push(siB.x, siB.y, siB.z, ciB, nIn); push(uiB.x, uiB.y, uiB.z, cuiB, nIn);
      push(uiA.x, uiA.y, uiA.z, cuiA, nIn); push(crestB.x, crestB.y, crestB.z, cB, nIn); push(crestA.x, crestA.y, crestA.z, cA, nIn); push(uiA.x, uiA.y, uiA.z, cuiA, nIn); push(uiB.x, uiB.y, uiB.z, cuiB, nIn); push(crestB.x, crestB.y, crestB.z, cB, nIn);
      push(outA.x, outA.y, outA.z, cBase, nOut); push(soA.x, soA.y, soA.z, coA, nOut); push(soB.x, soB.y, soB.z, coB, nOut); push(outA.x, outA.y, outA.z, cBase, nOut); push(soB.x, soB.y, soB.z, coB, nOut); push(outB.x, outB.y, outB.z, cBase, nOut);
      push(soA.x, soA.y, soA.z, coA, nOut); push(uoA.x, uoA.y, uoA.z, cuoA, nOut); push(uoB.x, uoB.y, uoB.z, cuoB, nOut); push(soA.x, soA.y, soA.z, coA, nOut); push(uoB.x, uoB.y, uoB.z, cuoB, nOut); push(soB.x, soB.y, soB.z, coB, nOut);
      push(uoA.x, uoA.y, uoA.z, cuoA, nOut); push(crestA.x, crestA.y, crestA.z, cA, nOut); push(crestB.x, crestB.y, crestB.z, cB, nOut); push(uoA.x, uoA.y, uoA.z, cuoA, nOut); push(crestB.x, crestB.y, crestB.z, cB, nOut); push(uoB.x, uoB.y, uoB.z, cuoB, nOut); }
    var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); g.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3)); own.push(g);
    var mat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.82, metalness: 0.08, flatShading: true, envMapIntensity: 0.28 });   /* pivot: faceted rock that answers the Sun */ own.push(mat);
    if (tier() !== 'LOW') rockShader(mat, R.h_max * 0.6); var mesh = new THREE.Mesh(g, mat); mesh.name = 'MACRO_RIDGE_' + R.id; mesh.frustumCulled = false; mesh.receiveShadow = false; mesh.userData.noMerge = true; group.add(mesh); ridges.push({ R: R, mesh: mesh, tris: pos.length / 9 }); return mesh; }
  /* WORLD PIVOT PASS 2b — procedural ROCK on the ridge faces (no texture, no extra draw): world-space value noise breaks every big facet
     into grain + sedimentary strata, and shallow faces above the snow line (with a noisy edge) take a cool white snow/crystal cover.
     Neutral stone / white only (colour law). Two noise lookups per fragment; the LOW tier keeps the plain faceted vertex colours. */
  function rockShader(mat, snowY) { mat.onBeforeCompile = function (sh) { sh.uniforms.uSnowY = { value: snowY };
      sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nvarying vec3 vRkW;').replace('#include <begin_vertex>', '#include <begin_vertex>\nvRkW = (modelMatrix * vec4(transformed, 1.0)).xyz;');
      sh.fragmentShader = sh.fragmentShader.replace('#include <common>', ['#include <common>', 'varying vec3 vRkW; uniform float uSnowY;',
        'float rkHash(vec3 p) { p = fract(p * 0.3183099 + 0.1); p *= 17.0; return fract(p.x * p.y * p.z * (p.x + p.y + p.z)); }',
        'float rkNoise(vec3 x) { vec3 i = floor(x), f = fract(x); f = f * f * (3.0 - 2.0 * f); return mix(mix(mix(rkHash(i), rkHash(i + vec3(1.0, 0.0, 0.0)), f.x), mix(rkHash(i + vec3(0.0, 1.0, 0.0)), rkHash(i + vec3(1.0, 1.0, 0.0)), f.x), f.y), mix(mix(rkHash(i + vec3(0.0, 0.0, 1.0)), rkHash(i + vec3(1.0, 0.0, 1.0)), f.x), mix(rkHash(i + vec3(0.0, 1.0, 1.0)), rkHash(i + vec3(1.0, 1.0, 1.0)), f.x), f.y), f.z); }'].join('\n'))
        .replace('#include <color_fragment>', ['#include <color_fragment>',
        'vec3 rkN = normalize(cross(dFdx(vRkW), dFdy(vRkW))); float rkUp = abs(rkN.y);',
        'float rkA = rkNoise(vRkW * 0.045), rkB = rkNoise(vRkW * vec3(0.21, 0.6, 0.21));',
        'float rkStrata = 0.5 + 0.5 * sin(vRkW.y * 0.62 + rkA * 6.0);',
        'diffuseColor.rgb *= 0.78 + 0.26 * rkB + 0.12 * rkStrata * (1.0 - rkUp);',
        'float rkSnow = smoothstep(0.52, 0.8, rkUp) * smoothstep(uSnowY - 18.0, uSnowY + 14.0, vRkW.y + (rkA - 0.5) * 36.0);',
        'diffuseColor.rgb = mix(diffuseColor.rgb, vec3(0.9, 0.93, 0.97) * diffuse, rkSnow * 0.88);'].join('\n')); };
    mat.customProgramCacheKey = function () { return 'mahworld-ridge-rock'; }; }
  /* ---- waterfalls ---- */
  function streakTexture() { var c = document.createElement('canvas'); c.width = 64; c.height = 256; var g = c.getContext('2d'); g.clearRect(0, 0, 64, 256); var r = rnd(0x77A); for (var i = 0; i < 26; i++) { var x = r() * 64, w = 2 + r() * 5, y0 = r() * 256, len = 40 + r() * 120; var gr = g.createLinearGradient(0, y0, 0, y0 + len); gr.addColorStop(0, 'rgba(255,255,255,0)'); gr.addColorStop(0.3, 'rgba(255,255,255,' + (0.35 + r() * 0.5) + ')'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(x - w / 2, y0, w, len); } var t = new THREE.CanvasTexture(c); t.wrapS = THREE.RepeatWrapping; t.wrapT = THREE.RepeatWrapping; t.colorSpace = THREE.SRGBColorSpace; own.push(t); return t; }
  function softTexture() { var c = document.createElement('canvas'); c.width = c.height = 64; var g = c.getContext('2d'); var gr = g.createRadialGradient(32, 32, 2, 32, 32, 32); gr.addColorStop(0, 'rgba(255,255,255,0.9)'); gr.addColorStop(0.5, 'rgba(255,255,255,0.35)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 64, 64); var t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; own.push(t); return t; }
  function waterfall(W, streak, soft) { var drop = W.source.y - W.receiver.y; var sheetG = new THREE.PlaneGeometry(W.width_m, drop, 1, 8); own.push(sheetG); var sm = new THREE.MeshBasicMaterial({ map: streak, transparent: true, opacity: 0.78, depthWrite: false, side: THREE.DoubleSide, color: 0xdff3ff, blending: THREE.AdditiveBlending }); sm.map = streak.clone(); sm.map.needsUpdate = true; sm.map.repeat.set(W.width_m / 3, drop / 12); own.push(sm.map); own.push(sm); var sheet = new THREE.Mesh(sheetG, sm); sheet.position.set(W.source.x, W.receiver.y + drop / 2, W.source.z); sheet.rotation.y = W.yaw_rad || 0; sheet.name = 'MACRO_FALL_' + W.id; sheet.userData.noMerge = true; group.add(sheet); sheetMats.push(sm);
    var back = new THREE.Mesh(sheetG, new THREE.MeshBasicMaterial({ color: 0x9fc9e8, transparent: true, opacity: 0.28, depthWrite: false, side: THREE.DoubleSide })); back.position.copy(sheet.position); back.position.y -= 0.02; back.rotation.y = sheet.rotation.y; back.renderOrder = 1; own.push(back.material); group.add(back);   /* the body of water behind the streaks */
    var foamG = new THREE.CircleGeometry(W.width_m * 0.9, 20); foamG.rotateX(-Math.PI / 2); own.push(foamG); var fm = new THREE.MeshBasicMaterial({ map: soft, transparent: true, opacity: 0.55, depthWrite: false, color: 0xffffff, blending: THREE.AdditiveBlending }); own.push(fm); var foam = new THREE.Mesh(foamG, fm); foam.position.set(W.receiver.x, W.receiver.y + 0.05, W.receiver.z); foam.userData.noMerge = true; group.add(foam); foamMats.push(fm);
    var mists = []; if (tier() !== 'LOW') { for (var i = 0; i < 3; i++) { var sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: soft, transparent: true, opacity: 0.22, depthWrite: false, color: 0xe8f4ff })); own.push(sp.material); var s = W.width_m * (0.9 + i * 0.5); sp.scale.set(s, s * 0.7, 1); sp.position.set(W.receiver.x + (i - 1) * W.width_m * 0.35, W.receiver.y + 1.2 + i * 1.1, W.receiver.z); sp.userData.vfx = true; group.add(sp); mists.push(sp); mistSprites.push(sp); } }
    if (W.basin) { var bg = new THREE.CircleGeometry(W.basin.r, 24); bg.rotateX(-Math.PI / 2); own.push(bg); var bm = new THREE.MeshStandardMaterial({ color: 0x2d5f8a, roughness: 0.12, metalness: 0.55, transparent: true, opacity: 0.86 }); own.push(bm); var basin = new THREE.Mesh(bg, bm); basin.position.set(W.basin.x, W.basin.y, W.basin.z); basin.userData.noMerge = true; group.add(basin); if (W.basin.channel) { var ch = W.basin.channel; var cl = Math.hypot(ch.to[0] - W.basin.x, ch.to[1] - W.basin.z); var cg = new THREE.PlaneGeometry(ch.w, cl); cg.rotateX(-Math.PI / 2); own.push(cg); var channel = new THREE.Mesh(cg, bm); channel.position.set((W.basin.x + ch.to[0]) / 2, W.basin.y, (W.basin.z + ch.to[1]) / 2); channel.rotation.y = Math.atan2(ch.to[0] - W.basin.x, ch.to[1] - W.basin.z); channel.userData.noMerge = true; group.add(channel); } }
    falls.push({ W: W, sheet: sheet, foam: foam, mists: mists, nextImpulse: 0.4 + Math.random() }); }
  /* ---- sky energy conduits ---- */
  function beamTexture() { var c = document.createElement('canvas'); c.width = 8; c.height = 128; var g = c.getContext('2d'); var gr = g.createLinearGradient(0, 0, 0, 128); gr.addColorStop(0, 'rgba(255,255,255,0)'); gr.addColorStop(0.15, 'rgba(255,255,255,0.55)'); gr.addColorStop(0.5, 'rgba(255,255,255,0.28)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 8, 128); var t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; own.push(t); return t; }
  function buildBeams(list) { if (!list.length) return; var g = new THREE.CylinderGeometry(1, 1, 1, 10, 1, true); g.translate(0, 0.5, 0); own.push(g); beamMat = new THREE.MeshBasicMaterial({ map: beamTexture(), transparent: true, opacity: 0.55, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide, vertexColors: false }); own.push(beamMat); beams = new THREE.InstancedMesh(g, beamMat, list.length); beams.name = 'MACRO_SKY_BEAMS'; beams.userData.noMerge = true; beams.frustumCulled = false; var m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), v = new THREE.Vector3(), s = new THREE.Vector3(), col = new THREE.Color(); list.forEach(function (B, i) { v.set(B.x, B.y, B.z); s.set(B.radius_m, B.height_m, B.radius_m); m4.compose(v, q, s); beams.setMatrixAt(i, m4); col.setHex(FAM[B.family] || FAM.cyan); beams.setColorAt(i, col); }); if (beams.instanceColor) beams.instanceColor.needsUpdate = true; group.add(beams); }
  function build() { group = new THREE.Group(); group.name = 'JOBB_MACRO'; group.userData.noMerge = true; ctx.group.add(group); reg = ctx.registry; M = reg && reg.macro; if (!M) { log('macro: registry.macro missing — nothing built'); return; }
    (M.mountains || []).forEach(ridge); var streak = streakTexture(), soft = softTexture(); (M.waterfalls || []).forEach(function (W) { waterfall(W, streak, soft); }); buildBeams(M.sky_beams || []); applyNight(night);
    log('macro ready: ridges ' + ridges.map(function (r) { return r.R.id + ' ' + r.tris + ' tris'; }).join(', ') + '; waterfalls ' + falls.map(function (f) { return f.W.id; }).join(', ') + '; sky beams ' + ((M.sky_beams || []).length)); }
  function applyNight(n) { ridges.forEach(function (r) { r.mesh.material.emissive = r.mesh.material.emissive || new THREE.Color(0); r.mesh.material.emissive.setHex(n ? 0x13243a : 0x000000); r.mesh.material.emissiveIntensity = n ? 0.78 : 0; r.mesh.material.color.setScalar(n ? 0.58 : 1); });   /* PASS 2b: the pale crystal caps must not read as lit white paper under the Moon */ if (beamMat) beamMat.opacity = n ? 0.8 : 0.5; sheetMats.forEach(function (m) { m.opacity = n ? 0.6 : 0.78; }); }
  function tick(dt, t) { clock = (typeof t === 'number' && isFinite(t)) ? t : clock + (dt || 0); if (!group) return; for (var i = 0; i < sheetMats.length; i++) { var f = falls[i]; var sp = (f && f.W.speed || 1); sheetMats[i].map.offset.y = -(clock * 0.9 * sp) % 1; } for (var k = 0; k < foamMats.length; k++) foamMats[k].opacity = 0.45 + 0.15 * Math.sin(clock * 4 + k); for (var m = 0; m < mistSprites.length; m++) { var msp = mistSprites[m]; msp.material.opacity = 0.16 + 0.1 * Math.sin(clock * 1.3 + m * 1.7); msp.material.rotation = Math.sin(clock * 0.4 + m) * 0.3; }
    if (beamMat) beamMat.opacity = (night ? 0.7 : 0.42) + 0.14 * Math.sin(clock * 0.8);
    /* contact disturbance: a ripple impulse where the fall meets a live water body (water.js), a few times a second per fall */ for (var q = 0; q < falls.length; q++) { var F = falls[q]; if (!F.W.ripple) continue; F.nextImpulse -= dt || 0; if (F.nextImpulse <= 0) { F.nextImpulse = 0.35 + Math.random() * 0.4; try { var wm = ctx.water; if (wm && wm.impulse) wm.impulse(F.W.receiver.x + (Math.random() - 0.5) * F.W.width_m * 0.6, F.W.receiver.z + (Math.random() - 0.5) * 1.2, 0.35, 1.6); } catch (e) { } } } }
  function setNight(n) { night = !!n; applyNight(night); }
  function debug() { return { ridges: ridges.map(function (r) { return { id: r.R.id, dist_m: r.R.dist_m, h: [r.R.h_min, r.R.h_max], passes: (r.R.passes || []).length, tris: r.tris }; }), waterfalls: falls.map(function (f) { return { id: f.W.id, drop_m: +(f.W.source.y - f.W.receiver.y).toFixed(1), source: f.W.source_id, receiver: f.W.receiver_id, ripple: !!f.W.ripple, mist: f.mists.length }; }), sky_beams: M && M.sky_beams ? M.sky_beams.map(function (b) { return b.id + '←' + b.source; }) : [], draw_calls: ridges.length + falls.length * 3 + mistSprites.length + (beams ? 1 : 0) }; }
  function dispose() { own.forEach(function (o) { try { o.dispose(); } catch (e) { } }); own = []; if (group && group.parent) group.parent.remove(group); }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug };
}
