/* MAHWORLD JOB B :: CRYSTAL MEADOW (owner next-pass 2026-09-20 §10) — the MAHWORLD equivalent of grassland: many small multifaceted crystal
   blades in the region's family tint, varied height and lean, densely repeated without noise, controlled highlights, a slight translucency,
   never a mirror. NEAR = real instanced geometry (one InstancedMesh per 30 m CHUNK, frustum-culled by its own bounding sphere and hidden
   beyond mid_m) · MID = the same chunks (their instance count is halved beyond near_m by a draw-range swap) · FAR = the region tint sheet
   (terrain.js). Placement is seeded per chunk and excluded from lanes / paths / plaza / landmarks / water / doors / spawn points (the same
   exclusion the trees and shards use). A subtle shimmer: the emissive breathes by instance hash × time in the vertex shader (no per-instance
   CPU work). Budget: registry ground_detail.meadow (density_per_m2, max_instances); tick() only toggles chunk visibility / counts every 0.25 s.
   M20 (owner 2026-09-27: "Prioritize removing: … ugly procedural clutter … weak repeated geometry … The final world can have FEWER elements
   and still look far richer"; the audit's close grove frames: ~15 500 identical octahedral spikes sown evenly over every grove floor — they
   read as caltrops / confetti, not growth): the meadow is re-planted as UNDERGROWTH round the grove trees. Tufts of three to five slender
   soft-crystal blades (three-sided, a darkened root, a tip that thins into the grove's glow) cluster in a ring 2.6–6.5 m round each trunk (just outside the root flare),
   denser near the roots, in the tree's own crystal family (tree_lock.zone_family — the grove and its undergrowth are one colour story);
   open ground between the trees stays open. ~4 000 blades in 50 m chunks (was ~15 500 in 58 chunks of 30 m); MED 75 %, LOW 45 %.
   M20 wave 3 (owner 2026-09-27: grass — "variation, maintained vs wild zones, no carpet of glowing blades"; the audit's grove frames: the
   tufts were small saturated family-coloured specks that glowed by day — confetti round every root): the undergrowth is ZONED. WILD ground
   (deep inside the grove, near the roots) grows full tufts of four to seven blades; MAINTAINED ground (the grove's edge toward the paving
   and the walks) keeps short, sparse, near-neutral tufts. Every blade is platinum-grey crystal with only a share of its family colour
   (more in the wild, the tuft's centre blade most), eased through an equal-channel grey (colour law); fewer tufts (× 0.82) so the fuller wild tufts
   add no blades — the grove's colour lives in the
   crowns, not in a lit carpet under them. The day glow drops to a trace (the tips still thin into light), the shimmer halves, and the blades
   shrink to their roots from ~55 % of the near reach to the near reach, so at range the grove floor is calm and the chunks beyond the near
   reach are no longer drawn.
   M20 surface polish (owner: "grass: maintained vs wild zones, tufts at edges"): the grove floor is a PLANTED BED now (surfaceDetail.bedEdge —
   stone edge course, raked gravel margin, soil). Blades grow on its soil only (never on the gravel, the edge course or the paving beside it —
   the old noise-feathered test let tufts stand on paving); a tuft that fell on the margin steps back to the soil's edge, so the bed's rim
   carries short, sparse, near-neutral tufts (maintained) and the full tufts stay deep in (wild, measured from the bed edge). */
import { forestExclusions, groundYAt } from './worldLayout.js'; import { combatZoneCircles } from './combatZones.js'; import { softCrystalGeometry } from './auraForms.js'; import { applyCrystal, bedEdge, BED } from './surfaceDetail.js';

export function createMeadow(ctx) {
  var THREE = ctx.THREE, log = ctx.log || function () { }; var reg = ctx.registry || {}; var GD = reg.ground_detail || {}; var MD = GD.meadow || null; var FAM = reg.crystal_families || {};
  var group = null, chunks = [], mat = null, geo = null, night = !!ctx.night, acc = 0, total = 0, info = { chunks: 0, instances: 0, visible_chunks: 0, draw_calls: 0 }, GLOW = { value: ctx.night ? 0.5 : 0.12 }, FADE = { value: new THREE.Vector2(38, 70) }, HALF = 35;   /* M20: GLOW = the blades' soft crystal light; HALF = a 50 m chunk's half-diagonal */
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  function inRect(x, z, r) { return x >= r.x1 && x <= r.x2 && z >= r.z1 && z <= r.z2; }
  function nearSeg(px, pz, a, b, w) { var ax = a[0], az = a[1], bx = b[0], bz = b[1]; var dx = bx - ax, dz = bz - az; var l2 = dx * dx + dz * dz || 1; var t = Math.max(0, Math.min(1, ((px - ax) * dx + (pz - az) * dz) / l2)); return Math.hypot(px - (ax + dx * t), pz - (az + dz * t)) <= w; }
  function inRegion(x, z, R) { var sh = R.shape || {}; if (sh.kind === 'CIRCLE') { var dx = x - sh.x, dz = z - sh.z; return dx * dx + dz * dz <= sh.r * sh.r; } var rs = sh.rects || []; for (var i = 0; i < rs.length; i++) if (inRect(x, z, rs[i])) return true; return false; }
  function build() {
    if (!MD) { log('meadow: registry ground_detail.meadow missing — nothing built'); return; }
    group = new THREE.Group(); group.name = 'MAHWORLD_MEADOW'; group.userData.noMerge = true; ctx.group.add(group);
    var lms = (ctx.layout && ctx.layout.landmarks || []).map(function (l) { return l.envelope || l; }); var ex = forestExclusions(reg, lms);
    var PW = reg.paths || {}; var widths = { CAUSEWAY: PW.causeway_w || 8, REGIONAL: PW.regional_w || 3.6, TRAIL: PW.trail_w || 1.8 }; var pathSegs = []; (PW.list || []).forEach(function (P) { var w = (widths[P.tier] || 3) / 2 + 1.2; for (var i = 0; i < P.pts.length - 1; i++) pathSegs.push({ a: P.pts[i], b: P.pts[i + 1], w: w }); if (P.forecourt) pathSegs.push({ a: [P.forecourt.x, P.forecourt.z], b: [P.forecourt.x, P.forecourt.z], w: (P.forecourt.r || 12) + 1 }); [P.spur, P.spur2].forEach(function (S) { if (S && S.to && P.forecourt) pathSegs.push({ a: [P.forecourt.x, P.forecourt.z], b: S.to, w: (PW.spur_w || 6) / 2 + 1 }); }); });
    var waters = ((reg.water && reg.water.rivers) || []).map(function (r) { return { x1: r.x1 - 1, z1: r.z1 - 1, x2: r.x2 + 1, z2: r.z2 + 1 }; }); var houses = ((reg.architecture && reg.architecture.class_houses) || []).map(function (h) { return { x: h.x, z: h.z, r: 12 }; });
    var allRects = ex.rects.concat(waters), allCircles = ex.circles.concat(houses, combatZoneCircles(reg, 1.5)), allSegs = ex.segs.concat(pathSegs);
    /* M9 (audit: crystal blades lay like confetti on the paved squares — temple forecourt, TITAN hex squares, the canal promenade): the
       district floors are PAVED (M8B zoned paving) and dissolve into natural ground only inside the FOREST / garden zones (M8C). A blade now
       grows only there: inside a natural zone, its edge feathered by value noise so the planting thins out toward the paving. */
    var natural = ((reg.zones) || []).filter(function (z) { return z.kind === 'FOREST' && (z.rect || z).x1 !== undefined; }).map(function (z) { return z.rect || z; });
    function hn(x, z) { var v = Math.sin(x * 12.9898 + z * 78.233) * 43758.5453; return v - Math.floor(v); }
    var BED_SOIL = BED.course_m + BED.margin_m[1] + 0.1;   /* M20: the grove's planted bed (surfaceDetail.bedEdge, the same edge the ground shader draws) — blades grow on its soil only, past the widest raked-gravel margin */
    function chunkFilter(x1, z1, x2, z2) { var R = allRects.filter(function (r) { return !(r.x2 < x1 || r.x1 > x2 || r.z2 < z1 || r.z1 > z2); }); var C = allCircles.filter(function (c) { return !(c.x + c.r < x1 || c.x - c.r > x2 || c.z + c.r < z1 || c.z - c.r > z2); }); var S = allSegs.filter(function (s) { var ax = Math.min(s.a[0], s.b[0]) - s.w, bx = Math.max(s.a[0], s.b[0]) + s.w, az = Math.min(s.a[1], s.b[1]) - s.w, bz = Math.max(s.a[1], s.b[1]) + s.w; return !(bx < x1 || ax > x2 || bz < z1 || az > z2); });
      return function (x, z) { for (var i = 0; i < R.length; i++) if (inRect(x, z, R[i])) return true; for (i = 0; i < C.length; i++) { var c = C[i]; if ((x - c.x) * (x - c.x) + (z - c.z) * (z - c.z) <= c.r * c.r) return true; } for (i = 0; i < S.length; i++) if (nearSeg(x, z, S[i].a, S[i].b, S[i].w)) return true; return false; }; }   /* per-chunk pre-filter: one bbox test per shape per chunk, not per blade */
    var LOWQ = false, TQ = 'HIGH'; try { TQ = ctx.quality && ctx.quality.tier ? String(ctx.quality.tier()).toUpperCase() : 'HIGH'; } catch (e) { } LOWQ = TQ === 'LOW';
    geo = softCrystalGeometry(THREE, { sides: 3, samples: 1, bevel: 0, ground: true, contact: 0.3, squash: 0.72, profile: [[-0.06, 1], [0.35, 0.82], [0.78, 0.32], [1.0, 0]] });   /* M20: a slender three-sided blade, 15 triangles (was an 8-triangle octahedral spike) */
    mat = new THREE.MeshStandardMaterial({ roughness: 0.34, metalness: 0.22, envMapIntensity: 0.45, transparent: true, opacity: MD.opacity || 0.86, emissive: 0xffffff, emissiveIntensity: 0.03, depthWrite: true });
    mat.onBeforeCompile = function (sh) { sh.uniforms.uT = { value: 0 }; sh.uniforms.uShim = { value: MD.shimmer || 0.05 }; sh.uniforms.uFade = FADE; mat.userData.shader = sh;
      sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nuniform float uT; uniform float uShim; uniform vec2 uFade; varying float vShim;').replace('#include <begin_vertex>', '#include <begin_vertex>\n#ifdef USE_INSTANCING\n{ float ph = instanceMatrix[3].x * 0.71 + instanceMatrix[3].z * 0.37; vShim = 0.5 + 0.5 * sin(uT * 0.8 + ph); float sway = sin(uT * 0.6 + ph) * 0.02 * clamp(position.y, 0.0, 1.0); transformed.x += sway; transformed *= 1.0 - smoothstep(uFade.x, uFade.y, distance((modelMatrix * vec4(instanceMatrix[3].xyz, 1.0)).xyz, cameraPosition)); }\n#else\nvShim = 0.5;\n#endif');
      sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nuniform float uShim; varying float vShim;').replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n#ifdef USE_COLOR\n totalEmissiveRadiance = emissive * vColor.rgb * (0.6 + uShim * 4.0 * vShim);\n#endif'); };
    mat.customProgramCacheKey = function () { return 'mahworld_meadow_m20_zoned'; };
    applyCrystal(THREE, mat, { tier: TQ, soft: true, glow: GLOW, facet: 0.22, depth: 0.2, rim: 0.3, veins: 0, refract: 0 });   /* the soft crystal path: darkened root, a tip that thins into the grove glow */
    var CH = MD.chunk_m_m20 || 50; var tuftK = MD.tufts_per_tree || 16, kT = LOWQ ? 0.45 : (TQ === 'MED' ? 0.75 : 1); var hR = MD.h_m || [0.05, 0.24], maxI = MD.max_instances || 14000; var m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), qy = new THREE.Quaternion(), ax = new THREE.Vector3(), up = new THREE.Vector3(0, 1, 0), v = new THREE.Vector3(), sc = new THREE.Vector3(); var col = new THREE.Color();
    var LOCK = reg.tree_lock || {}, ZF = LOCK.zone_family || {}, RG = (reg.regions && reg.regions.list) || [], TREES = ctx.forestPlacement || [], cells = {};
    function mdAt(x, z) { for (var i = 0; i < RG.length; i++) if ((RG[i].meadow || 0) > 0 && inRegion(x, z, RG[i])) return RG[i].meadow; return 0; }
    TREES.forEach(function (T, ti) { var md = mdAt(T.x, T.z); if (md <= 0) return; var famId = ZF[T.zone] || 'platinum', fam = FAM[famId] || FAM.platinum || {}; var base = new THREE.Color(fam.color || '#dfe6ee').convertSRGBToLinear(), glow = new THREE.Color(fam.glow || '#ffffff').convertSRGBToLinear(), grey = new THREE.Color(0.55, 0.55, 0.56); var r0 = rnd((0x3EAD + ti * 7919) >>> 0); var nT = Math.round(tuftK * 0.82 * md * kT * (0.7 + r0() * 0.6)), sc0 = T.scale || 1;
      for (var t = 0; t < nT; t++) { var a = r0() * Math.PI * 2, d = (2.6 + Math.pow(r0(), 1.4) * 3.9) * sc0,   /* outside the root flare (≈ 2.5 m) */ tx = T.x + Math.cos(a) * d, tz = T.z + Math.sin(a) * d; var be = bedEdge(natural, tx, tz), edgeTuft = false;
        if (be.d < BED_SOIL && be.d > BED_SOIL - 2.6) { var gx = bedEdge(natural, tx + 0.5, tz).d - bedEdge(natural, tx - 0.5, tz).d, gz = bedEdge(natural, tx, tz + 0.5).d - bedEdge(natural, tx, tz - 0.5).d, gl = Math.hypot(gx, gz) || 1, push = BED_SOIL + 0.1 + hn(tx, tz) * 0.5 - be.d; tx += gx / gl * push; tz += gz / gl * push; be = bedEdge(natural, tx, tz); edgeTuft = true; }   /* M20 TUFTS AT EDGES: a tuft that fell on the gravel margin / edge course / the paving beside it steps back to the soil's edge */
        var key = Math.floor(tx / CH) + ':' + Math.floor(tz / CH), cell = cells[key]; if (!cell) { var cx0 = Math.floor(tx / CH) * CH, cz0 = Math.floor(tz / CH) * CH; cell = cells[key] = { cx: cx0 + CH / 2, cz: cz0 + CH / 2, excluded: chunkFilter(cx0, cz0, cx0 + CH, cz0 + CH), items: [], name: famId + '_' + Math.round(cx0) + '_' + Math.round(cz0) }; }
        if (cell.excluded(tx, tz) || be.d < BED_SOIL || (edgeTuft && hn(tz, tx) < 0.3)) continue; var wild = Math.min(1, Math.max(0, (be.d - BED_SOIL - 0.6) / 7)) * (1 - 0.35 * (d / sc0 - 2.6) / 3.9);   /* 0 = maintained (the grove edge by the paving / walks) … 1 = wild (deep in the grove, by the roots) */
        if (wild < 0.3 && r0() < 0.4) continue; var hT = hR[0] + (hR[1] - hR[0]) * (0.55 + r0() * 0.45) * (1 - 0.3 * (d / sc0 - 2.6) / 3.9) * (0.5 + 0.5 * wild), nb = wild < 0.3 ? 3 + Math.floor(r0() * 2) : 4 + Math.floor(r0() * 4), tint = 0.2 + 0.45 * wild;   /* taller tufts near the roots; never above the registry's h_m (0.36 m) — in-reach ground cover no taller than before */
        for (var b = 0; b < nb; b++) { var ba = r0() * Math.PI * 2, bd = b ? 0.04 + r0() * 0.12 : 0, bx = tx + Math.cos(ba) * bd, bz = tz + Math.sin(ba) * bd, h = hT * (b ? 0.55 + r0() * 0.3 : 1); cell.items.push({ x: bx, z: bz, y: groundYAt(reg, bx, bz), h: h, rad: h * (0.28 + r0() * 0.08), yaw: r0() * Math.PI * 2, lean: b ? 0.18 + r0() * 0.3 : r0() * 0.1, la: b ? ba : r0() * Math.PI * 2, c: grey.clone().lerp(base.clone().lerp(glow, r0() * 0.35), Math.min(1, tint * (b ? 1 : 1.5))).multiplyScalar(0.8 + r0() * 0.35) }); } } });   /* platinum-grey crystal carrying a share of the family colour (the centre blade most) */   /* each tuft: a near-upright centre blade, companions leaning out of its root */
    Object.keys(cells).sort().forEach(function (key) { var cell = cells[key], items = cell.items; if (!items.length || total >= maxI) return; if (total + items.length > maxI) items.length = maxI - total; var im = new THREE.InstancedMesh(geo, mat, items.length); im.name = 'MEADOW_' + cell.name; im.userData.noMerge = true; im.frustumCulled = true; im.receiveShadow = false; im.castShadow = false;
      items.forEach(function (it, i) { qy.setFromAxisAngle(up, it.yaw); ax.set(Math.sin(it.la), 0, -Math.cos(it.la)); q.setFromAxisAngle(ax, it.lean).multiply(qy); v.set(it.x, it.y, it.z); sc.set(it.rad, it.h, it.rad); m4.compose(v, q, sc); im.setMatrixAt(i, m4); im.setColorAt(i, it.c); }); im.instanceMatrix.needsUpdate = true; im.instanceColor.needsUpdate = true; im.computeBoundingSphere();
      group.add(im); chunks.push({ mesh: im, cx: cell.cx, cz: cell.cz, n: items.length }); total += items.length; }); HALF = CH * 0.71;
    info.chunks = chunks.length; info.instances = total; log('meadow: ' + chunks.length + ' chunks / ' + total + ' crystal blades (near ' + (MD.near_m || 70) + ' m, mid ' + (MD.mid_m || 130) + ' m)');
  }
  function tick(dt, t) { if (!chunks.length) return; var sh = mat && mat.userData.shader; if (sh) sh.uniforms.uT.value = (typeof t === 'number' && isFinite(t)) ? t : (sh.uniforms.uT.value + (dt || 0)); acc += dt || 0; if (acc < 0.25) return; acc = 0; var cam = ctx.cameraPos(); var near = MD.near_m || 70, mid = MD.mid_m || 130; var T = null; try { T = ctx.quality && ctx.quality.get ? ctx.quality.get() : null; } catch (e) { T = null; } if (T && T.lod_far_m > 0) { var k = Math.min(1, T.lod_far_m / 220); near *= k; mid *= k; } FADE.value.set(near * 0.55, near);   /* the quality tier scales the meadow reach (LOW 120 / 220 → ×0.55, MED ×0.77, HIGH ×1) */ var vis = 0, dc = 0; for (var i = 0; i < chunks.length; i++) { var c = chunks[i]; var d = Math.hypot(c.cx - cam.x, c.cz - cam.z) - HALF; var show = d < near;   /* M20 wave 3: every blade has shrunk to its root by the near reach */ c.mesh.visible = show; if (show) { var cnt = d < near ? c.n : Math.max(1, Math.floor(c.n * 0.5)); if (c.mesh.count !== cnt) c.mesh.count = cnt; vis++; dc++; } } info.visible_chunks = vis; info.draw_calls = dc; }
  function setNight(n) { night = !!n; if (mat) mat.emissiveIntensity = night ? 0.18 : 0.03; GLOW.value = night ? 0.5 : 0.12; }
  function dispose() { chunks.forEach(function (c) { if (c.mesh.parent) c.mesh.parent.remove(c.mesh); c.mesh.dispose(); }); chunks = []; if (mat) mat.dispose(); if (geo) geo.dispose(); if (group && group.parent) group.parent.remove(group); group = null; }
  function debug() { var T = null; try { T = ctx.quality && ctx.quality.get ? ctx.quality.get() : null; } catch (e) { } var k = T && T.lod_far_m > 0 ? Math.min(1, T.lod_far_m / 220) : 1; return { chunks: info.chunks, instances: info.instances, visible_chunks: info.visible_chunks, draw_calls: info.draw_calls, tris_visible_max: info.instances * (geo && geo.index ? geo.index.count / 3 : 8), near_m: +((MD.near_m || 70) * k).toFixed(0), mid_m: +((MD.mid_m || 130) * k).toFixed(0), night: night, cfg: MD }; }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug };
}
