/* MAHWORLD JOB B :: CRYSTAL MEADOW (owner next-pass 2026-09-20 §10) — the MAHWORLD equivalent of grassland: many small multifaceted crystal
   blades in the region's family tint, varied height and lean, densely repeated without noise, controlled highlights, a slight translucency,
   never a mirror. NEAR = real instanced geometry (one InstancedMesh per 30 m CHUNK, frustum-culled by its own bounding sphere and hidden
   beyond mid_m) · MID = the same chunks (their instance count is halved beyond near_m by a draw-range swap) · FAR = the region tint sheet
   (terrain.js). Placement is seeded per chunk and excluded from lanes / paths / plaza / landmarks / water / doors / spawn points (the same
   exclusion the trees and shards use). A subtle shimmer: the emissive breathes by instance hash × time in the vertex shader (no per-instance
   CPU work). Budget: registry ground_detail.meadow (density_per_m2, max_instances); tick() only toggles chunk visibility / counts every 0.25 s. */
import { forestExclusions, groundYAt } from './worldLayout.js';

export function createMeadow(ctx) {
  var THREE = ctx.THREE, log = ctx.log || function () { }; var reg = ctx.registry || {}; var GD = reg.ground_detail || {}; var MD = GD.meadow || null; var FAM = reg.crystal_families || {};
  var group = null, chunks = [], mat = null, geo = null, night = !!ctx.night, acc = 0, total = 0, info = { chunks: 0, instances: 0, visible_chunks: 0, draw_calls: 0 };
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  function inRect(x, z, r) { return x >= r.x1 && x <= r.x2 && z >= r.z1 && z <= r.z2; }
  function nearSeg(px, pz, a, b, w) { var ax = a[0], az = a[1], bx = b[0], bz = b[1]; var dx = bx - ax, dz = bz - az; var l2 = dx * dx + dz * dz || 1; var t = Math.max(0, Math.min(1, ((px - ax) * dx + (pz - az) * dz) / l2)); return Math.hypot(px - (ax + dx * t), pz - (az + dz * t)) <= w; }
  function inRegion(x, z, R) { var sh = R.shape || {}; if (sh.kind === 'CIRCLE') { var dx = x - sh.x, dz = z - sh.z; return dx * dx + dz * dz <= sh.r * sh.r; } var rs = sh.rects || []; for (var i = 0; i < rs.length; i++) if (inRect(x, z, rs[i])) return true; return false; }
  function build() {
    if (!MD) { log('meadow: registry ground_detail.meadow missing — nothing built'); return; }
    group = new THREE.Group(); group.name = 'MAHWORLD_MEADOW'; group.userData.noMerge = true; ctx.group.add(group);
    var lms = (ctx.layout && ctx.layout.landmarks || []).map(function (l) { return l.envelope || l; }); var ex = forestExclusions(reg, lms);
    var PW = reg.paths || {}; var widths = { CAUSEWAY: PW.causeway_w || 8, REGIONAL: PW.regional_w || 3.6, TRAIL: PW.trail_w || 1.8 }; var pathSegs = []; (PW.list || []).forEach(function (P) { var w = (widths[P.tier] || 3) / 2 + 1.2; for (var i = 0; i < P.pts.length - 1; i++) pathSegs.push({ a: P.pts[i], b: P.pts[i + 1], w: w }); if (P.forecourt) pathSegs.push({ a: [P.forecourt.x, P.forecourt.z], b: [P.forecourt.x, P.forecourt.z], w: (P.forecourt.r || 12) + 1 }); [P.spur, P.spur2].forEach(function (S) { if (S && S.to && P.forecourt) pathSegs.push({ a: [P.forecourt.x, P.forecourt.z], b: S.to, w: (PW.spur_w || 6) / 2 + 1 }); }); });
    var waters = ((reg.water && reg.water.rivers) || []).map(function (r) { return { x1: r.x1 - 1, z1: r.z1 - 1, x2: r.x2 + 1, z2: r.z2 + 1 }; }); var houses = ((reg.architecture && reg.architecture.class_houses) || []).map(function (h) { return { x: h.x, z: h.z, r: 12 }; });
    var allRects = ex.rects.concat(waters), allCircles = ex.circles.concat(houses), allSegs = ex.segs.concat(pathSegs);
    function chunkFilter(x1, z1, x2, z2) { var R = allRects.filter(function (r) { return !(r.x2 < x1 || r.x1 > x2 || r.z2 < z1 || r.z1 > z2); }); var C = allCircles.filter(function (c) { return !(c.x + c.r < x1 || c.x - c.r > x2 || c.z + c.r < z1 || c.z - c.r > z2); }); var S = allSegs.filter(function (s) { var ax = Math.min(s.a[0], s.b[0]) - s.w, bx = Math.max(s.a[0], s.b[0]) + s.w, az = Math.min(s.a[1], s.b[1]) - s.w, bz = Math.max(s.a[1], s.b[1]) + s.w; return !(bx < x1 || ax > x2 || bz < z1 || az > z2); });
      return function (x, z) { for (var i = 0; i < R.length; i++) if (inRect(x, z, R[i])) return true; for (i = 0; i < C.length; i++) { var c = C[i]; if ((x - c.x) * (x - c.x) + (z - c.z) * (z - c.z) <= c.r * c.r) return true; } for (i = 0; i < S.length; i++) if (nearSeg(x, z, S[i].a, S[i].b, S[i].w)) return true; return false; }; }   /* per-chunk pre-filter: one bbox test per shape per chunk, not per blade */
    geo = new THREE.OctahedronGeometry(1, 0); geo.translate(0, 0.9, 0); geo.scale(1, 1.1, 0.55);   /* a blade: a tall thin facet standing on its tip's base */
    mat = new THREE.MeshStandardMaterial({ roughness: 0.34, metalness: 0.4, envMapIntensity: 0.45, transparent: true, opacity: MD.opacity || 0.86, emissive: 0xffffff, emissiveIntensity: 0.05, depthWrite: true });
    mat.onBeforeCompile = function (sh) { sh.uniforms.uT = { value: 0 }; sh.uniforms.uShim = { value: MD.shimmer || 0.05 }; mat.userData.shader = sh;
      sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nuniform float uT; uniform float uShim; varying float vShim;').replace('#include <begin_vertex>', '#include <begin_vertex>\n#ifdef USE_INSTANCING\n{ float ph = instanceMatrix[3].x * 0.71 + instanceMatrix[3].z * 0.37; vShim = 0.5 + 0.5 * sin(uT * 0.8 + ph); float sway = sin(uT * 0.6 + ph) * 0.02 * clamp(position.y, 0.0, 1.0); transformed.x += sway; }\n#else\nvShim = 0.5;\n#endif');
      sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nuniform float uShim; varying float vShim;').replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n#ifdef USE_COLOR\n totalEmissiveRadiance = emissive * vColor.rgb * (0.6 + uShim * 8.0 * vShim);\n#endif'); };
    mat.customProgramCacheKey = function () { return 'mahworld_meadow'; };
    var RG = (reg.regions && reg.regions.list) || []; var CH = MD.chunk_m || 30; var dens = MD.density_per_m2 || 0.09; var hR = MD.h_m || [0.05, 0.24], rR = MD.r_m || [0.04, 0.11]; var maxI = MD.max_instances || 14000; var m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), e = new THREE.Euler(), v = new THREE.Vector3(), sc = new THREE.Vector3(); var col = new THREE.Color();
    RG.forEach(function (R, ri) { var md = R.meadow || 0; if (md <= 0) return; var fam = FAM[R.family] || FAM.platinum || {}; var base = new THREE.Color(fam.color || '#dfe6ee').convertSRGBToLinear(), glow = new THREE.Color(fam.glow || '#ffffff').convertSRGBToLinear(); var rects = R.shape && R.shape.kind === 'CIRCLE' ? [{ x1: R.shape.x - R.shape.r, z1: R.shape.z - R.shape.r, x2: R.shape.x + R.shape.r, z2: R.shape.z + R.shape.r }] : (R.shape && R.shape.rects || []);
      rects.forEach(function (r, rci) { for (var cx = r.x1; cx < r.x2; cx += CH) for (var cz = r.z1; cz < r.z2; cz += CH) { if (total >= maxI) return; var x2 = Math.min(r.x2, cx + CH), z2 = Math.min(r.z2, cz + CH); var area = (x2 - cx) * (z2 - cz); var want = Math.round(area * dens * md); if (want < 4) continue; var excluded = chunkFilter(cx, cz, x2, z2); var r0 = rnd((0x3EAD + ri * 7919 + rci * 131 + Math.round(cx) * 17 + Math.round(cz)) >>> 0); var items = [];
          for (var t = 0; t < want * 2 && items.length < want; t++) { var x = cx + r0() * (x2 - cx), z = cz + r0() * (z2 - cz); if (!inRegion(x, z, R) || excluded(x, z)) continue; items.push({ x: x, z: z, y: groundYAt(reg, x, z), h: hR[0] + r0() * (hR[1] - hR[0]), rad: rR[0] + r0() * (rR[1] - rR[0]), yaw: r0() * Math.PI, lean: (r0() - 0.5) * 0.5, b: 0.6 + r0() * 0.7, g: r0() }); }
          if (!items.length) continue; if (total + items.length > maxI) items.length = maxI - total; var im = new THREE.InstancedMesh(geo, mat, items.length); im.name = 'MEADOW_' + R.id + '_' + Math.round(cx) + '_' + Math.round(cz); im.userData.noMerge = true; im.frustumCulled = true; im.receiveShadow = false; im.castShadow = false;
          items.forEach(function (it, i) { e.set(it.lean, it.yaw, 0); q.setFromEuler(e); v.set(it.x, it.y, it.z); sc.set(it.rad, it.h, it.rad); m4.compose(v, q, sc); im.setMatrixAt(i, m4); col.copy(base).lerp(glow, it.g * 0.5).multiplyScalar(it.b); im.setColorAt(i, col); }); im.instanceMatrix.needsUpdate = true; im.instanceColor.needsUpdate = true; im.computeBoundingSphere();
          group.add(im); chunks.push({ mesh: im, cx: (cx + x2) / 2, cz: (cz + z2) / 2, n: items.length }); total += items.length; } }); });
    info.chunks = chunks.length; info.instances = total; log('meadow: ' + chunks.length + ' chunks / ' + total + ' crystal blades (near ' + (MD.near_m || 70) + ' m, mid ' + (MD.mid_m || 130) + ' m)');
  }
  function tick(dt, t) { if (!chunks.length) return; var sh = mat && mat.userData.shader; if (sh) sh.uniforms.uT.value = (typeof t === 'number' && isFinite(t)) ? t : (sh.uniforms.uT.value + (dt || 0)); acc += dt || 0; if (acc < 0.25) return; acc = 0; var cam = ctx.cameraPos(); var near = MD.near_m || 70, mid = MD.mid_m || 130; var T = null; try { T = ctx.quality && ctx.quality.get ? ctx.quality.get() : null; } catch (e) { T = null; } if (T && T.lod_far_m > 0) { var k = Math.min(1, T.lod_far_m / 220); near *= k; mid *= k; }   /* the quality tier scales the meadow reach (LOW 120 / 220 → ×0.55, MED ×0.77, HIGH ×1) */ var vis = 0, dc = 0; for (var i = 0; i < chunks.length; i++) { var c = chunks[i]; var d = Math.hypot(c.cx - cam.x, c.cz - cam.z) - 21; var show = d < mid; c.mesh.visible = show; if (show) { var cnt = d < near ? c.n : Math.max(1, Math.floor(c.n * 0.5)); if (c.mesh.count !== cnt) c.mesh.count = cnt; vis++; dc++; } } info.visible_chunks = vis; info.draw_calls = dc; }
  function setNight(n) { night = !!n; if (mat) mat.emissiveIntensity = night ? 0.22 : 0.05; }
  function dispose() { chunks.forEach(function (c) { if (c.mesh.parent) c.mesh.parent.remove(c.mesh); c.mesh.dispose(); }); chunks = []; if (mat) mat.dispose(); if (geo) geo.dispose(); if (group && group.parent) group.parent.remove(group); group = null; }
  function debug() { var T = null; try { T = ctx.quality && ctx.quality.get ? ctx.quality.get() : null; } catch (e) { } var k = T && T.lod_far_m > 0 ? Math.min(1, T.lod_far_m / 220) : 1; return { chunks: info.chunks, instances: info.instances, visible_chunks: info.visible_chunks, draw_calls: info.draw_calls, tris_visible_max: info.instances * 8, near_m: +((MD.near_m || 70) * k).toFixed(0), mid_m: +((MD.mid_m || 130) * k).toFixed(0), night: night, cfg: MD }; }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug };
}
