/* JOB B world module — SIGNAGE (owner B8 §3 wayfinders · §19 building names). Data from the registry only (paths.wayfinders, buildings.list).
   WAYFINDER = the MAH square-diamond signpost at a fork: a dark-platinum post, a crown diamond in the widest leg's route colour, one flat
   BLADE per leg pointing down its route (stacked top → bottom in the label's order) and one proximity label listing "DESTINATION · distance"
   per leg in the route colour. BUILDING NAME = a proximity label above the real entrance (open-air structures: above their forecourt), never a
   skyline-wide sign. Phone budget: 2 InstancedMeshes (posts, blades) + 1 for crowns, ≤ 10 label sprites visible (nearest first, fade 30–48 m),
   canvases drawn once. */
import { groundYAt } from './worldLayout.js';
var FAMILY = { gold: '#e6c36a', blue: '#4f8cff', red: '#ff5a6a', purple: '#b08cff', pink: '#ff7fc4', platinum: '#dfe6ee', cyan: '#7fe4ff' };
var FAMILY_HEX = { gold: 0xe6c36a, blue: 0x2c62d8, red: 0xd8404a, purple: 0x8a5fd6, pink: 0xff5fb0, platinum: 0xdfe6ee, cyan: 0x39c5ff };
var POST_H = 2.7, BLADE_L = 1.05, BLADE_STEP = 0.2, LABEL_FADE = 30, LABEL_GONE = 48, LABEL_MAX = 10;
export function createSignage(ctx) {
  var THREE = ctx.THREE; var group = null; var reg = null; var labels = []; var stats = { wayfinders: 0, buildings: 0 };
  var M4 = new THREE.Matrix4(), Q = new THREE.Quaternion(), V = new THREE.Vector3(), S = new THREE.Vector3(), E = new THREE.Euler(); var col = new THREE.Color();
  function canvasLabel(lines, w, lineH) { var c = document.createElement('canvas'); var PX = w || 320, PY = 18 + lineH * lines.length; c.width = PX; c.height = PY; var g = c.getContext('2d'); g.clearRect(0, 0, PX, PY); g.fillStyle = 'rgba(14,18,24,0.78)'; g.strokeStyle = 'rgba(223,230,238,0.55)'; g.lineWidth = 2; rr(g, 2, 2, PX - 4, PY - 4, 10); g.fill(); g.stroke();
    lines.forEach(function (L, i) { var y = 9 + lineH * i + lineH / 2; g.fillStyle = L.color || '#eef4ff'; g.beginPath(); g.moveTo(18, y - 7); g.lineTo(25, y); g.lineTo(18, y + 7); g.lineTo(11, y); g.closePath(); g.fill();   /* the square-diamond bullet in the route colour */ g.font = (L.bold ? '800 ' : '700 ') + (L.size || 19) + 'px system-ui, sans-serif'; g.textBaseline = 'middle'; g.textAlign = 'left'; g.fillStyle = L.bold ? '#eef4ff' : (L.color || '#eef4ff'); g.fillText(L.text, 34, y); if (L.right) { g.textAlign = 'right'; g.fillStyle = 'rgba(238,244,255,0.85)'; g.font = '600 16px system-ui, sans-serif'; g.fillText(L.right, PX - 12, y); } });
    var tex = new THREE.CanvasTexture(c); tex.colorSpace = THREE.SRGBColorSpace; tex.minFilter = THREE.LinearFilter; tex.generateMipmaps = false; var mat = new THREE.SpriteMaterial({ map: tex, transparent: true, depthWrite: false, depthTest: true }); var sp = new THREE.Sprite(mat); var Wm = (w || 320) / 160; sp.scale.set(Wm, Wm * PY / PX, 1); sp.center.set(0.5, 0); sp.renderOrder = 4; sp.userData.vfx = true; return sp; }
  function rr(g, x, y, w, h, r) { g.beginPath(); g.moveTo(x + r, y); g.lineTo(x + w - r, y); g.quadraticCurveTo(x + w, y, x + w, y + r); g.lineTo(x + w, y + h - r); g.quadraticCurveTo(x + w, y + h, x + w - r, y + h); g.lineTo(x + r, y + h); g.quadraticCurveTo(x, y + h, x, y + h - r); g.lineTo(x, y + r); g.quadraticCurveTo(x, y, x + r, y); g.closePath(); }
  function groundY(x, z) { try { return groundYAt(reg, x, z); } catch (e) { return 0; } }
  function build() {
    group = new THREE.Group(); group.name = 'JOBB_SIGNAGE'; group.userData.noMerge = true; ctx.group.add(group); reg = ctx.registry; var WAY = (reg && reg.paths && reg.paths.wayfinders) || []; var BLD = (reg && reg.buildings && reg.buildings.list) || [];
    var legsTotal = WAY.reduce(function (n, w) { return n + w.legs.length; }, 0);
    if (WAY.length) {
      var postG = new THREE.CylinderGeometry(0.14, 0.18, POST_H, 8); postG.translate(0, POST_H / 2, 0); var postM = new THREE.MeshStandardMaterial({ color: 0x2a3038, roughness: 0.45, metalness: 0.85 }); var posts = new THREE.InstancedMesh(postG, postM, WAY.length); posts.name = 'WAYFINDER_POSTS'; posts.userData.noMerge = true; posts.castShadow = false; group.add(posts);
      var crownG = new THREE.OctahedronGeometry(0.3, 0); crownG.scale(1, 1.5, 1); var crownM = new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0xffffff, emissiveIntensity: 0.6, roughness: 0.15, metalness: 0.5, transparent: true, opacity: 0.92 }); var crowns = new THREE.InstancedMesh(crownG, crownM, WAY.length); crowns.name = 'WAYFINDER_CROWNS'; crowns.userData.noMerge = true; group.add(crowns);
      var bladeG = new THREE.BoxGeometry(BLADE_L, 0.16, 0.035); bladeG.translate(BLADE_L / 2 + 0.16, 0, 0); var bladeM = new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: 0x333333, emissiveIntensity: 0.8, roughness: 0.3, metalness: 0.7 }); var blades = new THREE.InstancedMesh(bladeG, bladeM, Math.max(1, legsTotal)); blades.name = 'WAYFINDER_BLADES'; blades.userData.noMerge = true; group.add(blades);
      var bi = 0; WAY.forEach(function (w, i) { var y = groundY(w.x, w.z); V.set(w.x, y, w.z); Q.identity(); S.set(1, 1, 1); M4.compose(V, Q, S); posts.setMatrixAt(i, M4); V.set(w.x, y + POST_H + 0.55, w.z); E.set(0, i * 0.7, 0); Q.setFromEuler(E); M4.compose(V, Q, S); crowns.setMatrixAt(i, M4); col.setHex(FAMILY_HEX[w.family] || FAMILY_HEX.platinum); crowns.setColorAt(i, col);
        w.legs.forEach(function (L, k) { V.set(w.x, y + POST_H - 0.25 - k * BLADE_STEP, w.z); E.set(0, -(L.dir_rad) + Math.PI / 2, 0); Q.setFromEuler(E);   /* the blade's +x points down the route: three.js yaw = −host bearing, rotated so +x (not −z) leads */ M4.compose(V, Q, S); blades.setMatrixAt(bi, M4); col.setHex(FAMILY_HEX[L.family] || FAMILY_HEX.platinum); blades.setColorAt(bi, col); bi++; });
        var lines = w.legs.map(function (L) { return { text: L.name, color: FAMILY[L.family] || FAMILY.platinum, right: L.dist_m + ' m' }; }); var sp = canvasLabel(lines, 300, 26); sp.position.set(w.x, y + POST_H + 1.05, w.z); sp.visible = false; group.add(sp); labels.push({ sp: sp, x: w.x, z: w.z, kind: 'WAYFINDER' }); });
      blades.count = bi; if (crowns.instanceColor) crowns.instanceColor.needsUpdate = true; if (blades.instanceColor) blades.instanceColor.needsUpdate = true; stats.wayfinders = WAY.length;
    }
    BLD.forEach(function (b) { var ax = b.entrance ? b.entrance.x : b.forecourt.x, az = b.entrance ? b.entrance.z : b.forecourt.z; var y = groundY(ax, az); var sub = b.open_air ? (b.type === 'GATE' ? 'walk through' : 'open-air · fly up') : (b.interior_kind === 'SHELL' ? 'enter · hall' : 'enter'); var sp = canvasLabel([{ text: b.name, color: FAMILY[b.theme] || FAMILY.platinum, bold: true, size: 22, right: sub }], 340, 34); sp.position.set(ax, y + (b.entrance ? 3.4 : 5.5), az); sp.visible = false; group.add(sp); labels.push({ sp: sp, x: ax, z: az, kind: 'BUILDING' }); });
    stats.buildings = BLD.length; ctx.log('signage ready (' + stats.wayfinders + ' wayfinders / ' + legsTotal + ' blades, ' + stats.buildings + ' building names; labels ≤ ' + LABEL_MAX + ' visible, fade ' + LABEL_FADE + '–' + LABEL_GONE + ' m)');
  }
  var acc = 0;
  function tick(dt, t) { if (!group) return; acc += dt || 0; if (acc < 0.2) return; acc = 0; var cam = ctx.cameraPos(); var near = []; for (var i = 0; i < labels.length; i++) { var L = labels[i]; var d = Math.hypot(L.x - cam.x, L.z - cam.z); L.d = d; if (d < LABEL_GONE) near.push(L); else L.sp.visible = false; } near.sort(function (a, b) { return a.d - b.d; }); for (var k = 0; k < near.length; k++) { var Ln = near[k]; if (k >= LABEL_MAX) { Ln.sp.visible = false; continue; } var a = Ln.d <= LABEL_FADE ? 1 : 1 - (Ln.d - LABEL_FADE) / (LABEL_GONE - LABEL_FADE); Ln.sp.material.opacity = a; Ln.sp.visible = a > 0.03; } }   /* 5 Hz: distance sort + fade, nothing per frame */
  function debug() { return { wayfinders: stats.wayfinders, buildings: stats.buildings, labels_visible: labels.filter(function (l) { return l.sp.visible; }).length, labels_total: labels.length }; }
  function dispose() { labels.forEach(function (l) { l.sp.material.map.dispose(); l.sp.material.dispose(); }); labels = []; if (group && group.parent) group.parent.remove(group); }
  return { build: build, tick: tick, debug: debug, dispose: dispose };
}
