/* MAHWORLD JOB B :: TERRAIN — regions, the path hierarchy and the ground's macro / meso / micro detail (owner redirect 2026-09-19 §B–§E).
   Reads registry.regions / paths / ground_detail / crystal_families and draws, on top of the platinum district floor:
     MACRO  one single-owner tessellated REGION TINT surface (the region's family colour at tint_alpha, y 0.012) — one merged
            vertex-coloured mesh (1 draw call); overlapping registry regions never stack translucent planes;
     PATHS  CROWN CAUSEWAYS (8 m: platinum frame + a pale crystalline core with a slow emissive breath) · REGIONAL PATHS (3.6 m: frame + the
            region family core) · DISCOVERY TRAILS (1.8 m: a continuous narrow family inlay with edge seams — B7 §10 C, no dashes) — flat inlays ≤ 0.02 m that follow the existing routes /
            corridors / bridges: they change no collider and no lane (2 draw calls: frames, cores);
     MESO   instanced CRYSTAL SHARD clusters in the region family (seeded, ≤ 0.42 m, excluded from every lane / path / plaza / landmark /
            door / spawn point through worldLayout.forestExclusions — decorative, never in the way; 1 draw call);
     MICRO  an additive CRYSTAL DUST point field per region (1 draw call, a slow twinkle);
     LANDMARKS  per-region crystal MONOLITHS / the CROWN SPIRES beyond the north wall (1 merged draw call; the three monoliths inside the
            walls have CYLINDER colliders generated from the registry — build_world_colliders.mjs, policy MONOLITH_CYLINDER).
   Night: the cores / shards / dust raise their emissive. No per-frame allocation.
   M20 (owner 2026-09-27, brutal visual audit): the MICRO dust is removed, the MESO shards are cut to a few composed clusters on natural
   ground only, and every region crystal (shard, monolith, crown spire, satellite) is a SOFT CRYSTAL (auraForms.softCrystalGeometry +
   the soft path of surfaceDetail.applyCrystal) that stands IN the ground — a column with its root sunk and darkened, not a spinning-top
   octahedron balanced on its point on a platinum plate.
   M20 SURFACE POLISH (owner 2026-09-27, priority 8: material realism, humanized transitions, lived-in variation): the roads are laid in
   real stone in ROAD SPACE — causeway edge courses, 1.2 × 0.6 m slab courses, transverse sett bands every 12 m, gully grates with a damp
   halo; class roads in their class stone as setts; trails resin-bound gravel; junctions in ring courses, bend corners fanned round the
   inner corner; honed-granite kerbs cut along the road (see ROAD STONE below). The region shards keep to the grove's planted-bed soil
   (surfaceDetail.bedEdge). Same draws, same triangles, nothing moves: shading on the existing flush ribbons only. LOW keeps the
   course layout only — straight courses, at the a330208 cost (no bend fan, grates, disc rings, grain, macro or relief: see the M20 review
   note at ROAD STONE); MED drops the fine aggregate, the damp mottling and the second macro octave. */
import { forestExclusions, groundYAt } from './worldLayout.js'; import { softCrystalGeometry } from './auraForms.js';
import { buildRoadNetwork } from './roadNetwork.js'; import { applySurface, applyCrystal, wearField, bedEdge, BED } from './surfaceDetail.js'; import { combatZoneCircles } from './combatZones.js';

export function createTerrain(ctx) {
  var THREE = ctx.THREE, M = ctx.M || {}, log = ctx.log || function () { }; var reg = ctx.registry || {};
  var group = null, meshes = [], own = [], night = !!ctx.night, clock = 0; var coreMat = null, shardMat = null, monoMat = null, seamMat = null; var info = { regions: 0, tint_sheets: 0, paths: { CAUSEWAY: 0, REGIONAL: 0, TRAIL: 0 }, shards: 0, dust: 0, monoliths: 0, draw_calls: 0, tris: 0 };
  function sdTier() { try { return ctx.quality && ctx.quality.tier ? ctx.quality.tier() : 'HIGH'; } catch (e) { return 'HIGH'; } }
  var FAM = reg.crystal_families || {}; var GD = reg.ground_detail || {}; var TINT_Y = GD.tint_y || 0.012, PATH_Y = GD.path_y || 0.016;
  function famColor(id, key) { var f = FAM[id] || FAM.platinum || { color: '#dfe6ee', glow: '#ffffff' }; return new THREE.Color(f[key || 'color'] || '#dfe6ee'); }
  /* M19 (owner 2026-09-27: ATHLETE gold, LEAN crimson and BAGE pink need eye-level presence; TITAN / VISIONARY not increased). The registry
     gold (#e6c36a) and rose (#f08ab8) are pastel: lit and tone-mapped they read as champagne / blush and never as class crystal, while the
     deep TITAN blue always does — the audit's blue lead was partly this chroma gap. The WARM region crystals (shards, monoliths / crown
     spires) take a deeper cut of their own hue (same family window, the colour law's gold 36–56° / crimson / rose); blue, violet and
     platinum crystals are untouched. */
  var WARM_CUT = { gold: 0xf2c43c, red: 0xe02a44, pink: 0xf74aa2 }; var AURA_WARM = { gold: '#ffe57c' };
  var CRYSTAL_GLOW = { value: night ? 0.38 : 0.15 };   /* M20: the soft crystal light (core, rim, tips) of the shards and monoliths — restrained by day, and held at 0.38 by night (stronger, ACES carried VISIONARY violet toward lilac-pink) */
  var WARM_NIGHT = { value: night ? 0.8 : 0 };   /* warm shards / monoliths glow 1.8x at night (red > blue in the crystal colour): the moon-blue night light leaves warm crystal near-black */
  function crystalColor(id, key, k) { var c = famColor(id, key); if (WARM_CUT[id]) c.lerp(new THREE.Color(WARM_CUT[id]), k === undefined ? 0.7 : k); return c; }
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  function add(geo, mat, name, order) { var m = new THREE.Mesh(geo, mat); m.name = name; m.userData.noMerge = true; m.frustumCulled = false; m.receiveShadow = false; m.castShadow = false; if (order !== undefined) m.renderOrder = order; group.add(m); meshes.push(m); info.draw_calls++; info.tris += Math.round((geo.index ? geo.index.count : geo.attributes.position.count) / 3); return m; }
  function feather() { var c = document.createElement('canvas'); c.width = 128; c.height = 128; var g = c.getContext('2d'); var im = g.createImageData(128, 128); for (var y = 0; y < 128; y++) for (var x = 0; x < 128; x++) { var u = x / 127, v = y / 127; var e = Math.min(u, 1 - u, v, 1 - v) * 2; var a = Math.min(1, e / 0.45); a = a * a * (3 - 2 * a); var i = (y * 128 + x) * 4; var av = Math.round(a * 255); im.data[i] = im.data[i + 1] = im.data[i + 2] = av; im.data[i + 3] = 255; } g.putImageData(im, 0, 0); var t = new THREE.CanvasTexture(c); t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping; return t; }

  /* ---- geometry helpers (all merged into few buffers; positions in FIELD metres, y up) ---- */
  function gy(x, z) { return groundYAt(reg, x, z); }
  function quadXZ(out, x1, z1, x2, z2, y, col, uvRect) { var b = out.pos.length / 3; out.pos.push(x1, y + gy(x1, z1), z1, x2, y + gy(x2, z1), z1, x2, y + gy(x2, z2), z2, x1, y + gy(x1, z2), z2); for (var k = 0; k < 4; k++) { out.col.push(col.r, col.g, col.b); } out.uv.push(0, 0, 1, 0, 1, 1, 0, 1); out.idx.push(b, b + 2, b + 1, b, b + 3, b + 2); }
  function stripSeg(out, ax, az, bx, bz, w, y, col, ext, off) { var dx = bx - ax, dz = bz - az, L = Math.hypot(dx, dz) || 1; var ux = dx / L, uz = dz / L; var nx = -uz * w / 2, nz = ux * w / 2; ax -= ux * ext; az -= uz * ext; bx += ux * ext; bz += uz * ext; if (off) { var ox = -uz * off, oz = ux * off; ax += ox; az += oz; bx += ox; bz += oz; } var b = out.pos.length / 3; out.pos.push(ax + nx, y + gy(ax + nx, az + nz), az + nz, ax - nx, y + gy(ax - nx, az - nz), az - nz, bx - nx, y + gy(bx - nx, bz - nz), bz - nz, bx + nx, y + gy(bx + nx, bz + nz), bz + nz); for (var k = 0; k < 4; k++) out.col.push(col.r, col.g, col.b); out.uv.push(0, 0, 1, 0, 1, 1, 0, 1); out.idx.push(b, b + 2, b + 1, b, b + 3, b + 2); }
  /* A ribbon whose end vertices lie on the owning junction circle.  Longitudinal rows carry a smoothstep colour blend in linear space, so
     regional road colours dissolve gradually while every junction endpoint still matches its single shared owner exactly. */
  function clippedStrip(out, ax, az, bx, bz, w, y, col, startR, endR, off, endCol) { var dx = bx - ax, dz = bz - az, L = Math.hypot(dx, dz); if (L < 0.001 || w <= 0) return; var ux = dx / L, uz = dz / L, nx = -uz, nz = ux, slices = Math.max(2, Math.ceil(w / 1.5)), longs = Math.max(1, Math.ceil(Math.max(1, L - (startR || 0) - (endR || 0)) / 12)), rows = longs + 1, base = out.pos.length / 3; off = off || 0; endCol = endCol || col; for (var i = 0; i <= slices; i++) { var lat = -w / 2 + w * i / slices, worldLat = lat + off; var s0 = startR ? Math.sqrt(Math.max(0, startR * startR - worldLat * worldLat)) : 0; var s1 = endR ? L - Math.sqrt(Math.max(0, endR * endR - worldLat * worldLat)) : L; if (s1 < s0) { var mid = (s0 + s1) * 0.5; s0 = s1 = mid; } for (var j = 0; j <= longs; j++) { var t = j / longs, e = t * t * (3 - 2 * t), ss = s0 + (s1 - s0) * t, xx = ax + ux * ss + nx * worldLat, zz = az + uz * ss + nz * worldLat; out.pos.push(xx, y + gy(xx, zz), zz); out.col.push(col.r + (endCol.r - col.r) * e, col.g + (endCol.g - col.g) * e, col.b + (endCol.b - col.b) * e); out.uv.push(i / slices, t); if (out.rd) { out.rd.push(worldLat, ss, w / 2, 0); out.ru.push(ux, uz); } } } for (i = 0; i < slices; i++) for (j = 0; j < longs; j++) { var a0 = base + i * rows + j, a1 = base + (i + 1) * rows + j; out.idx.push(a0, a1 + 1, a0 + 1, a0, a1, a1 + 1); } }
  /* The clipped ribbons terminate on a true circle.  A 20-gon joint left up to 12 cm of exposed
     ground between those endpoints and its inscribed chords on a 20 m causeway, visible as dark
     circular/angular fragments.  A shared 128-segment boundary brings that geometric gap below
     3.1 mm while keeping draw calls unchanged and adding only a small fixed vertex cost to this road graph. */
  var JUNCTION_SEGMENTS = 128, BEND_C = null;   /* M20: the inner corner of the bend being built (its paving fans round it) */
  function joint(out, x, z, w, y, col, nSeg) { var n = nSeg || JUNCTION_SEGMENTS, b = out.pos.length / 3; out.pos.push(x, y + gy(x, z), z); out.col.push(col.r, col.g, col.b); out.uv.push(0.5, 0.5); for (var i = 0; i < n; i++) { var a = i / n * Math.PI * 2, px = x + Math.cos(a) * w / 2, pz = z + Math.sin(a) * w / 2; out.pos.push(px, y + gy(px, pz), pz); out.col.push(col.r, col.g, col.b); out.uv.push(0.5 + 0.5 * Math.cos(a), 0.5 + 0.5 * Math.sin(a)); } if (out.rd) for (i = 0; i <= n; i++) { out.rd.push(x, z, w / 2, nSeg && BEND_C ? 2 : 1); out.ru.push(nSeg && BEND_C ? BEND_C[0] : 0, nSeg && BEND_C ? BEND_C[1] : 0); } for (i = 0; i < n; i++) out.idx.push(b, b + 1 + (i + 1) % n, b + 1 + i); }   /* M20: every disc vertex carries its centre + radius (aRoad.w = 1 a junction / forecourt: laid in rings round it; 2 a bend corner — only the bend corners pass nSeg — whose courses FAN round the bend's inner corner, aRoadU, so the road turns instead of wearing a bullseye) */
  function ring(out, x, z, r, w, y, col) { var n = JUNCTION_SEGMENTS, b = out.pos.length / 3, ro = r + w * 0.5, ri = Math.max(0.02, r - w * 0.5); for (var i = 0; i < n; i++) { var a = i / n * Math.PI * 2, ca = Math.cos(a), sa = Math.sin(a), xo = x + ca * ro, zo = z + sa * ro, xi = x + ca * ri, zi = z + sa * ri; out.pos.push(xo, y + gy(xo, zo), zo, xi, y + gy(xi, zi), zi); out.col.push(col.r, col.g, col.b, col.r, col.g, col.b); out.uv.push(i / n, 0, i / n, 1); } for (i = 0; i < n; i++) { var j = (i + 1) % n, a0 = b + i * 2, a1 = b + j * 2; out.idx.push(a0, a1 + 1, a0 + 1, a0, a1, a1 + 1); } }
  /* M11: an arc of the seam ring (a bend's outer seam), always swept counter-clockwise so it faces up like ring() */
  function arc(out, x, z, r, w, y, col, a0, a1) { var da = Math.atan2(Math.sin(a1 - a0), Math.cos(a1 - a0)); if (da < 0) { a0 += da; da = -da; } var n = Math.max(1, Math.ceil(da / (Math.PI * 2) * JUNCTION_SEGMENTS)), b = out.pos.length / 3, ro = r + w * 0.5, ri = Math.max(0.02, r - w * 0.5); for (var i = 0; i <= n; i++) { var a = a0 + da * i / n, ca = Math.cos(a), sa = Math.sin(a), xo = x + ca * ro, zo = z + sa * ro, xi = x + ca * ri, zi = z + sa * ri; out.pos.push(xo, y + gy(xo, zo), zo, xi, y + gy(xi, zi), zi); out.col.push(col.r, col.g, col.b, col.r, col.g, col.b); out.uv.push(i / n, 0, i / n, 1); } for (i = 0; i < n; i++) { var a0i = b + i * 2, a1i = a0i + 2; out.idx.push(a0i, a1i + 1, a0i + 1, a0i, a1i, a1i + 1); } }
  /* M20 (surface polish): the road frames / cores carry ROAD-SPACE coordinates — aRoad = (lateral m from the centreline, along m, half width,
     0) on a ribbon, (centre x, z, radius, 1 | 2) on a junction / forecourt | bend disc; aRoadU = the ribbon direction (a bend disc: its inner
     corner) — so their joints, edge
     courses, bands and gratings run with the road instead of with the world axes (the old world-grid pavers ran diagonally across the
     45° causeways and the kerb stones' joints did too). */
  function buf(road, noUv) { return { pos: [], col: [], uv: [], idx: [], alpha: [], rd: road ? [] : null, ru: road ? [] : null, noUv: !!noUv }; }
  function geom(o) { var g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(o.pos, 3)); g.setAttribute('color', new THREE.Float32BufferAttribute(o.col, 3)); if (!o.rd && !o.noUv) g.setAttribute('uv', new THREE.Float32BufferAttribute(o.uv, 2)); if (o.rd && o.rd.length) { if (sdTier() === 'LOW') g.setAttribute('aRoad', new THREE.Float32BufferAttribute(roadLow(o), 3)); else { g.setAttribute('aRoad', new THREE.Float32BufferAttribute(o.rd, 4)); g.setAttribute('aRoadU', new THREE.Float32BufferAttribute(o.ru, 2)); } } g.setIndex(o.idx); g.computeVertexNormals(); return g; }
  /* M20 review (LOW never heavier): the road frames / cores carry no uv (their materials read none: 2 floats a vertex back on every tier), and
     on LOW one vec3 only — (lateral, along, half width) on a ribbon; a disc vertex its offset from the centre (a bend corner's in its
     bisector frame, across / along) — with the kind packed over the half width (.z = half width + 32 × kind: 0 a ribbon, 1 a junction /
     forecourt, 2 a straight-through node — no kerb course —, 3 + 511 · tan / (1 + tan) a bend corner; half widths run 0.66–13 m), so LOW
     needs no aRoadU: its road vertices are 12 floats (position, normal, colour, aRoad) against the old 11 (position, normal, colour, uv),
     HIGH / MED 15. The SEAMS drop their uv too (an unlit MeshBasicMaterial with no map reads none: 11 → 9 floats; they keep their normals —
     a geometry without them is a different three.js program), so the three road layers' vertex data on LOW ends below a330208's. */
  function roadLow(o) { var n = o.rd.length / 4, out = new Array(n * 3); for (var v = 0; v < n; v++) { var x = o.rd[v * 4], y = o.rd[v * 4 + 1], hw = o.rd[v * 4 + 2], w = o.rd[v * 4 + 3], k = 0; if (w > 0.5) { var dx = o.pos[v * 3] - x, dz = o.pos[v * 3 + 2] - y; if (w > 1.5) { var ex = x - o.ru[v * 2], ez = y - o.ru[v * 2 + 1], dC = Math.max(Math.hypot(ex, ez), 1e-3), nx = ex / dC, nz = ez / dC, sh = Math.min(hw / dC, 0.999), tn = sh / Math.sqrt(1 - sh * sh); x = dx * nx + dz * nz; y = dx * nz - dz * nx; k = dC > 300 ? 2 : 3 + Math.round(tn / (1 + tn) * 511); } else { x = dx; y = dz; k = 1; } } out[v * 3] = x; out[v * 3 + 1] = y; out[v * 3 + 2] = Math.min(hw, 31.9) + 32 * k; } return out; }
  function inRect(x, z, r) { return x >= r.x1 && x <= r.x2 && z >= r.z1 && z <= r.z2; }
  /* a tint sheet with WATER HOLES: the rect is cut into cells (≈ 8 m) and the cells over a pond / river (+ its shore) are skipped; the uv stays the whole-rect fraction so the feather alphaMap is unchanged (owner 2026-09-20 §12: the sanctuary ponds sit inside their region rects) */
  function quadXZHoles(out, x1, z1, x2, z2, y, col, alpha, holes) { var nx = Math.max(1, Math.ceil((x2 - x1) / 8)), nz = Math.max(1, Math.ceil((z2 - z1) / 8)); var cw = (x2 - x1) / nx, cd = (z2 - z1) / nz; var n = 0; for (var i = 0; i < nx; i++) for (var j = 0; j < nz; j++) { var ax = x1 + i * cw, az = z1 + j * cd, bx = ax + cw, bz = az + cd; var mx = (ax + bx) / 2, mz = (az + bz) / 2; var hole = false; for (var h = 0; h < holes.length && !hole; h++) { var H = holes[h]; hole = bx > H.x1 && ax < H.x2 && bz > H.z1 && az < H.z2; } if (hole) continue;   /* a cell that touches the water at all is skipped (extent, not centre — review 2026-09-20) */ var b = out.pos.length / 3; out.pos.push(ax, y + gy(ax, az), az, bx, y + gy(bx, az), az, bx, y + gy(bx, bz), bz, ax, y + gy(ax, bz), bz); for (var k = 0; k < 4; k++) { out.col.push(col.r, col.g, col.b); out.alpha.push(alpha); } var u0 = (ax - x1) / (x2 - x1), u1 = (bx - x1) / (x2 - x1), v0 = (az - z1) / (z2 - z1), v1 = (bz - z1) / (z2 - z1); out.uv.push(u0, v0, u1, v0, u1, v1, u0, v1); out.idx.push(b, b + 2, b + 1, b, b + 3, b + 2); n++; } return n; }
  function regionRects(R) { var s = R.shape || {}; if (s.kind === 'CIRCLE') return [{ x1: s.x - s.r, z1: s.z - s.r, x2: s.x + s.r, z2: s.z + s.r, circle: s }]; return (s.rects || []).slice(); }
  function inRegion(x, z, R) { var s = R.shape || {}; if (s.kind === 'CIRCLE') { var dx = x - s.x, dz = z - s.z; return dx * dx + dz * dz <= s.r * s.r; } var rs = s.rects || []; for (var i = 0; i < rs.length; i++) if (inRect(x, z, rs[i])) return true; return false; }
  function nearSeg(px, pz, a, b, w) { var ax = a[0], az = a[1], bx = b[0], bz = b[1]; var dx = bx - ax, dz = bz - az; var l2 = dx * dx + dz * dz || 1; var t = Math.max(0, Math.min(1, ((px - ax) * dx + (pz - az) * dz) / l2)); return Math.hypot(px - (ax + dx * t), pz - (az + dz * t)) <= w; }

  function tierQ() { try { return ctx.quality && ctx.quality.tier ? ctx.quality.tier() : 'HIGH'; } catch (e) { return 'HIGH'; } }
  function build() {
    var RG = reg.regions && reg.regions.list || []; var PT = reg.paths && reg.paths.list || []; if (!RG.length && !PT.length) { log('terrain: registry has no regions / paths — nothing built'); return; }
    group = new THREE.Group(); group.name = 'MAHWORLD_TERRAIN'; group.userData.noMerge = true; ctx.group.add(group);
    var lms = (ctx.layout && ctx.layout.landmarks || []).map(function (l) { return l.envelope || l; }); var ex = forestExclusions(reg, lms);
    var PW = reg.paths || {}; var widths = { CAUSEWAY: PW.causeway_w || 8, REGIONAL: PW.regional_w || 3.6, TRAIL: PW.trail_w || 1.8 }; var plazaR = reg.field && reg.field.plaza_radius_m || 56;
    /* 0. MACRO elevation: the crown terraces — a satin platinum slab (top at h), sloped ramps on the declared sides, a heat-grey lip along the free edges */
    var TR = reg.terraces && reg.terraces.list || []; if (TR.length) { var slabMat = new THREE.MeshStandardMaterial({ color: 0x7e8792, roughness: 0.7, metalness: 0.6, envMapIntensity: 0.12 });   /* satin platinum, darker than the sky so the plateau reads as ground */ var lipMat = new THREE.MeshStandardMaterial({ color: 0x6e7680, roughness: 0.5, metalness: 0.8 }); own.push(slabMat); own.push(lipMat); applySurface(THREE, slabMat, 'CLADDING', tierQ());   /* M9 (audit V24: plain grey risers up close): honed stone courses on the risers, slabs on the tops */ var slabs = [], lips = [];
      TR.forEach(function (T) { var w = T.x2 - T.x1, d = T.z2 - T.z1; var sg = new THREE.BoxGeometry(w, T.h, d); sg.translate((T.x1 + T.x2) / 2, T.h / 2, (T.z1 + T.z2) / 2); slabs.push(sg); var sides = { S: false, N: false, W: false, E: false }; (T.ramps || []).forEach(function (r) { var rw = r.w || 6; var rg; var rx1 = r.x1 !== undefined ? r.x1 : T.x1, rx2 = r.x2 !== undefined ? r.x2 : T.x2, rz1 = r.z1 !== undefined ? r.z1 : T.z1, rz2 = r.z2 !== undefined ? r.z2 : T.z2; var full = (r.side === 'S' || r.side === 'N') ? (rx1 === T.x1 && rx2 === T.x2) : (rz1 === T.z1 && rz2 === T.z2); if (full) sides[r.side] = true; if (r.side === 'S' || r.side === 'N') { rg = new THREE.BoxGeometry(rx2 - rx1, 0.2, Math.hypot(rw, T.h)); rg.rotateX(r.side === 'S' ? Math.atan2(T.h, rw) : -Math.atan2(T.h, rw)); rg.translate((rx1 + rx2) / 2, T.h / 2 - 0.1 + 0.02, r.side === 'S' ? T.z1 - rw / 2 : T.z2 + rw / 2); } else { rg = new THREE.BoxGeometry(Math.hypot(rw, T.h), 0.2, rz2 - rz1); rg.rotateZ(r.side === 'W' ? -Math.atan2(T.h, rw) : Math.atan2(T.h, rw)); rg.translate(r.side === 'W' ? T.x1 - rw / 2 : T.x2 + rw / 2, T.h / 2 - 0.1 + 0.02, (rz1 + rz2) / 2); } slabs.push(rg); });   /* a partial ramp (range) keeps the lip on the rest of its side */
        [['S', T.x1, T.z1 - 0.15, T.x2, T.z1 + 0.15], ['N', T.x1, T.z2 - 0.15, T.x2, T.z2 + 0.15], ['W', T.x1 - 0.15, T.z1, T.x1 + 0.15, T.z2], ['E', T.x2 - 0.15, T.z1, T.x2 + 0.15, T.z2]].forEach(function (L) { if (sides[L[0]]) return; var lg = new THREE.BoxGeometry(L[3] - L[1], T.h + 0.06, L[4] - L[2]); lg.translate((L[1] + L[3]) / 2, (T.h + 0.06) / 2, (L[2] + L[4]) / 2); lips.push(lg); }); });
      add(mergeBoxes(slabs), slabMat, 'TERRAIN_TERRACES'); if (lips.length) add(mergeBoxes(lips), lipMat, 'TERRAIN_TERRACE_LIPS'); info.terraces = TR.length; }
    /* 1. MACRO region tint — one continuous vertex-gradient field.  The ownership grid still prevents stacked transparent slabs, but every
       corner samples all nearby sanctuary influences through a broad signed-distance feather.  Adjacent class colours therefore dissolve
       into one another instead of exposing the old 8 m checkerboard / hard rectangle edges. */
    var tints = buf(); var WATER = ((reg.water && reg.water.rivers) || []).map(function (w) { var sw = (w.shore_w || 0) * 0.4; return { x1: w.x1 + (w.pond ? sw : 0), z1: w.z1 + sw, x2: w.x2 - (w.pond ? sw : 0), z2: w.z2 - sw }; }); var walls = reg.field && reg.field.walls || { x1: -175, x2: 175, z1: -56.5, z2: 292 }; var cellM = 8, overlapCells = 0; info.regions = RG.length;
    function tintPriority(R) { return R.tint_priority !== undefined ? R.tint_priority : (R.class ? 20 : (R.id === 'NEXUS' ? 10 : 5)); }
    function sdRect(x, z, r) { var ox = Math.max(r.x1 - x, 0, x - r.x2), oz = Math.max(r.z1 - z, 0, z - r.z2); if (ox || oz) return -Math.hypot(ox, oz); return Math.min(x - r.x1, r.x2 - x, z - r.z1, r.z2 - z); }
    function regionDepth(x, z, R) { var s = R.shape || {}; if (s.kind === 'CIRCLE') return (+s.r || 0) - Math.hypot(x - (+s.x || 0), z - (+s.z || 0)); var best = -1e6, rs = s.rects || []; for (var i = 0; i < rs.length; i++) best = Math.max(best, sdRect(x, z, rs[i])); return best; }
    function smooth01(v) { v = Math.max(0, Math.min(1, v)); return v * v * (3 - 2 * v); }
    function tintSample(x, z) { var rr = 0, gg = 0, bb = 0, aa = 0, sum = 0, presence = 0; for (var i = 0; i < RG.length; i++) { var R = RG[i]; if (!R.ground_tint || !(R.tint_alpha > 0)) continue; var d = regionDepth(x, z, R), w = d >= 0 ? 0.7 + 0.3 * smooth01(d / 24) : 0.7 * (1 - smooth01(-d / 30)); if (!(w > 0)) continue; w *= 0.75 + 0.25 * Math.min(1, tintPriority(R) / 20); var c = famColor(R.family); c.set(R.ground_tint).convertSRGBToLinear(); rr += c.r * w; gg += c.g * w; bb += c.b * w; aa += R.tint_alpha * w; sum += w; presence = Math.max(presence, d >= 0 ? 1 : 1 - smooth01(-d / 30)); } if (!(sum > 0)) return null; var macro = 0.9 + 0.1 * Math.sin(x * 0.028 + z * 0.017) * Math.sin(z * 0.023 - x * 0.011), neutral = 0.14; return { r: (rr / sum * 0.76 + neutral * 0.24) * macro, g: (gg / sum * 0.76 + neutral * 0.24) * macro, b: (bb / sum * 0.76 + neutral * 0.24) * macro, a: aa / sum * 0.24 * presence }; }
    function tintQuad(out, ax, az, bx, bz, samples) { var b = out.pos.length / 3, pts = [[ax, az], [bx, az], [bx, bz], [ax, bz]]; for (var i = 0; i < 4; i++) { var p = pts[i], s = samples[i]; out.pos.push(p[0], TINT_Y + gy(p[0], p[1]), p[1]); out.col.push(s.r, s.g, s.b); out.alpha.push(s.a); } out.uv.push(0, 0, 1, 0, 1, 1, 0, 1); out.idx.push(b, b + 2, b + 1, b, b + 3, b + 2); }
    for (var gx = walls.x1; gx < walls.x2; gx += cellM) for (var gz = walls.z1; gz < walls.z2; gz += cellM) { var bx = Math.min(walls.x2, gx + cellM), bz = Math.min(walls.z2, gz + cellM), mx = (gx + bx) * 0.5, mz = (gz + bz) * 0.5, matches = 0; for (var ri = 0; ri < RG.length; ri++) if (RG[ri].ground_tint && RG[ri].tint_alpha > 0 && inRegion(mx, mz, RG[ri])) matches++; if (matches > 1) overlapCells++;
      var wet = false; for (var wi = 0; wi < WATER.length && !wet; wi++) { var WH = WATER[wi]; wet = bx > WH.x1 && gx < WH.x2 && bz > WH.z1 && gz < WH.z2; } if (wet) continue; var SS = [tintSample(gx, gz), tintSample(bx, gz), tintSample(bx, bz), tintSample(gx, bz)]; if (!SS[0] || !SS[1] || !SS[2] || !SS[3] || Math.max(SS[0].a, SS[1].a, SS[2].a, SS[3].a) < 0.002) continue; tintQuad(tints, gx, gz, bx, bz, SS); info.tint_cells = (info.tint_cells || 0) + 1; }
    info.tint_overlaps_prevented = overlapCells; info.tint_sheets = tints.pos.length ? 1 : 0;
    if (tints.pos.length) { var tg = geom(tints); var c4 = new Float32Array(tints.alpha.length * 4); for (var ti = 0; ti < tints.alpha.length; ti++) { c4[ti * 4] = tints.col[ti * 3]; c4[ti * 4 + 1] = tints.col[ti * 3 + 1]; c4[ti * 4 + 2] = tints.col[ti * 3 + 2]; c4[ti * 4 + 3] = tints.alpha[ti]; } tg.setAttribute('color', new THREE.BufferAttribute(c4, 4)); var tintMat = new THREE.MeshBasicMaterial({ vertexColors: true, transparent: true, opacity: 1, depthWrite: false, fog: true, polygonOffset: true, polygonOffsetFactor: -1, polygonOffsetUnits: -1 }); own.push(tintMat); add(tg, tintMat, 'TERRAIN_REGION_TINTS', 0); }   /* per-cell alpha rides in the 4-component colour attribute */
    /* 2. PATHS — one topology graph, one owner per junction. Ribbons terminate on a sampled circular boundary instead of extending coplanar quads through one another. */
    var frames = buf(true), cores = buf(true), seams = buf(false, true); var frameCol = new THREE.Color(0x6e7680).convertSRGBToLinear().multiplyScalar(0.9); var pathSegs = [], authoredRoads = [], explicitJunctions = [];
    /* M20 CLASS STONE (surface polish; the lead's review: V25 "a vast featureless blue-grey slab floor — a showroom floor", V05 / V16 the LEAN
       road a flat red carpet): the roads are laid in real stone. The causeways (shared, every class walks them) are a pale neutral granite
       (the pale-ice #cfe8ff core read blue-grey under the lavender sky); a class road is that class's stone — ATHLETE honey travertine, TITAN
       blue slate, LEAN red porphyry, VISIONARY purple slate, BAGE rose granite: the family colour eased through an equal-channel grey to 45 %
       of its chroma (hue kept — colour law; famColor is already linear: no second linearisation), at a stone value per family. The class
       still reads; the surface reads as material. */
    var STONE_LUM = { gold: 0.15, pink: 0.115, red: 0.07, blue: 0.068, purple: 0.07 };
    function roadStone(fam) { if (!fam || !STONE_LUM[fam]) return new THREE.Color(0.132, 0.13, 0.127); var c = famColor(fam), L = 0.2126 * c.r + 0.7152 * c.g + 0.0722 * c.b, k = 0.45; return new THREE.Color(L + (c.r - L) * k, L + (c.g - L) * k, L + (c.b - L) * k).multiplyScalar(STONE_LUM[fam] / Math.max(1e-4, L)); }
    function roadStyle(P, id, pts, fw, cw) { var trail = P.tier === 'TRAIL'; return { id: id, tier: P.tier, family: P.family, points: pts, frameW: fw, coreW: trail ? cw * 0.55 : cw, frameColor: trail ? frameCol.clone().multiplyScalar(0.55) : frameCol, coreColor: roadStone(P.tier === 'CAUSEWAY' ? null : P.family), seamColor: famColor(P.family, 'glow').convertSRGBToLinear(), seamW: trail ? 0.1 : 0.14 }; }
    PT.forEach(function (P) { var w = widths[P.tier] || 3, pts = (P.pts || []).map(function (p) { return [p[0], p[1]]; }); if (pts.length < 2) return; info.paths[P.tier] = (info.paths[P.tier] || 0) + 1;
      if (P.tier === 'CAUSEWAY') { if (Math.hypot(pts[0][0], pts[0][1]) < 1) { var d1 = Math.hypot(pts[1][0], pts[1][1]) || 1, k1 = (plazaR - 4) / d1; pts[0] = [pts[1][0] * k1, pts[1][1] * k1]; } var last = pts[pts.length - 1], prev = pts[pts.length - 2], isLm = lms.some(function (e) { return e && inRect(last[0], last[1], e); }); if (isLm && !P.forecourt) { var dl = Math.hypot(last[0] - prev[0], last[1] - prev[1]) || 1, trim = Math.min(14, dl * 0.5); pts[pts.length - 1] = [last[0] + (prev[0] - last[0]) * trim / dl, last[1] + (prev[1] - last[1]) * trim / dl]; } }
      var coreW = P.tier === 'CAUSEWAY' ? w - 1.6 : (P.tier === 'REGIONAL' ? w - 1.0 : w - 0.6), st = roadStyle(P, P.id, pts, w, coreW); authoredRoads.push(st);
      if (P.forecourt) { var FC = P.forecourt, fr = FC.r || (PW.forecourt_r || 12); explicitJunctions.push({ id: P.id + ':FORECOURT', kind: 'FORECOURT', x: FC.x, z: FC.z, radius: fr }); info.forecourts = (info.forecourts || 0) + 1; [P.spur, P.spur2].forEach(function (SPR, si) { if (!SPR || !SPR.to) return; var sw = PW.spur_w || 6, ss = roadStyle(P, P.id + ':SPUR' + si, [[FC.x, FC.z], [SPR.to[0], SPR.to[1]]], sw, sw - 1.2); authoredRoads.push(ss); info.spurs = (info.spurs || 0) + 1; }); }
    });
    var network = buildRoadNetwork(authoredRoads, explicitJunctions); info.road_topology = network.stats;
    function nodeColor(N, key) { var list = N && N.styles || []; if (!list.length) return N && N.owner ? N.owner[key] : frameCol; var c = new THREE.Color(0, 0, 0); for (var i = 0; i < list.length; i++) c.add(list[i][key]); return c.multiplyScalar(1 / list.length); }
    network.nodes.forEach(function (N) { var st = N.owner; if (!st) return; N.frameBlend = nodeColor(N, 'frameColor'); N.coreBlend = nodeColor(N, 'coreColor'); N.seamBlend = nodeColor(N, 'seamColor');
      var mixF = {}; (N.styles || []).forEach(function (S) { mixF[S.family] = 1; }); if (Object.keys(mixF).length > 1) { N.coreBlend = roadStone(null); N.seamBlend = new THREE.Color(0xf5f5f5).convertSRGBToLinear(); N.mixedFamilies = true; }   /* M17: where roads of DIFFERENT classes meet, the junction is neutral (averaging gold and pink gave a peach, off the colour law); the five-class rosette (hardscapeInlays.js) marks it */
      /* M11 BEND CORNERS: a turn inside one road gets a corner disc exactly the road's width (the kerb and core edges run tangent into it,
         so the outer corner is closed instead of leaving a notch of bare ground), its outer seam follows an arc, and its inner seams stop at
         their mitre point instead of crossing over the other leg. */
      if (N.bendOnly) { var legs = network.pieces.filter(function (P) { return P.aKey === N.key || P.bKey === N.key; }); if (legs.length === 2) {
          var lw = legs.map(function (P) { var dx = P.b[0] - P.a[0], dz = P.b[1] - P.a[1], L = Math.hypot(dx, dz) || 1, o = P.aKey === N.key ? 1 : -1; return [dx / L * o, dz / L * o]; }), bx = lw[0][0] + lw[1][0], bz = lw[0][1] + lw[1][1], bl = Math.hypot(bx, bz), half = Math.acos(Math.max(-1, Math.min(1, lw[0][0] * lw[1][0] + lw[0][1] * lw[1][1]))) / 2, cdist = Math.min(400, N.coreRadius / Math.max(1e-3, Math.sin(half)));
          if (bl < 1e-3) { bx = -lw[0][1]; bz = lw[0][0]; bl = 1; cdist = 400; } BEND_C = [N.x + bx / bl * cdist, N.z + bz / bl * cdist];   /* M20: the inner corner (the inner core edges meet on the bisector at r / sin(β/2)) */
          var nSeg = Math.max(24, Math.min(JUNCTION_SEGMENTS, Math.ceil(N.frameRadius * 12))); joint(frames, N.x, N.z, N.frameRadius * 2, PATH_Y, N.frameBlend, nSeg); joint(cores, N.x, N.z, N.coreRadius * 2, PATH_Y + 0.004, N.coreBlend, nSeg); BEND_C = null;
          var geo = legs.map(function (P) { var dx = P.b[0] - P.a[0], dz = P.b[1] - P.a[1], L = Math.hypot(dx, dz) || 1, ux = dx / L, uz = dz / L, out = P.aKey === N.key ? 1 : -1; return { P: P, L: L, nx: -uz, nz: ux, wx: ux * out, wz: uz * out }; });
          var so = Math.max(0, st.coreW / 2 - st.seamW * 0.85), cb = Math.max(-1, Math.min(1, geo[0].wx * geo[1].wx + geo[0].wz * geo[1].wz)), beta = Math.acos(cb);
          N.bendInfo = { inner: {}, dIn: Math.min(so / Math.max(0.05, Math.tan(beta / 2)), Math.min(geo[0].L, geo[1].L) * 0.5) }; var outA = [];
          geo.forEach(function (G, gi) { var O = geo[1 - gi], side = (G.nx * O.wx + G.nz * O.wz) >= 0 ? 1 : -1; N.bendInfo.inner[G.P.id] = side; outA.push(Math.atan2(-side * G.nz, -side * G.nx)); });
          arc(seams, N.x, N.z, so, st.seamW, PATH_Y + 0.008, N.seamBlend, outA[0], outA[1]); return; } }
      joint(frames, N.x, N.z, N.frameRadius * 2, PATH_Y, N.frameBlend); joint(cores, N.x, N.z, N.coreRadius * 2, PATH_Y + 0.004, N.coreBlend); ring(seams, N.x, N.z, Math.max(0.12, N.coreRadius - 0.12), st.seamW, PATH_Y + 0.008, N.seamBlend); });
    var gradientPieces = 0; network.pieces.forEach(function (P) { var st = P.style, A = P.aKey && network.nodeByKey[P.aKey], B = P.bKey && network.nodeByKey[P.bKey], arF = A ? A.frameRadius : 0, brF = B ? B.frameRadius : 0, arC = A ? A.coreRadius : 0, brC = B ? B.coreRadius : 0, ac = A && !A.mixedFamilies && A.coreBlend || st.coreColor, bc = B && !B.mixedFamilies && B.coreBlend || st.coreColor; if (Math.abs(ac.r - bc.r) + Math.abs(ac.g - bc.g) + Math.abs(ac.b - bc.b) > 0.004) gradientPieces++; clippedStrip(frames, P.a[0], P.a[1], P.b[0], P.b[1], st.frameW, PATH_Y, A && A.frameBlend || st.frameColor, arF, brF, 0, B && B.frameBlend || st.frameColor); clippedStrip(cores, P.a[0], P.a[1], P.b[0], P.b[1], st.coreW, PATH_Y + 0.004, ac, arC, brC, 0, bc); var so = Math.max(0, st.coreW / 2 - st.seamW * 0.85); [so, -so].forEach(function (off) { var ax = P.a[0], az = P.a[1], bx = P.b[0], bz = P.b[1], L = Math.hypot(bx - ax, bz - az) || 1, ux = (bx - ax) / L, uz = (bz - az) / L, sR = arC, eR = brC;
        /* M11: at a bend corner the outer seam runs to the node's perpendicular (tangent to the arc) and the inner seam stops at the mitre point */
        if (A && A.bendInfo) { var dA = A.bendInfo.inner[P.id] === Math.sign(off) ? A.bendInfo.dIn : 0; ax += ux * dA; az += uz * dA; sR = 0; }
        if (B && B.bendInfo) { var dB = B.bendInfo.inner[P.id] === Math.sign(off) ? B.bendInfo.dIn : 0; bx -= ux * dB; bz -= uz * dB; eR = 0; }
        clippedStrip(seams, ax, az, bx, bz, st.seamW, PATH_Y + 0.008, A && !A.mixedFamilies && A.seamBlend || st.seamColor, sR, eR, off, B && !B.mixedFamilies && B.seamBlend || st.seamColor);   /* M17: a road keeps its own seam colour up to a mixed-class junction; only the junction ring is neutral */ }); pathSegs.push({ a: P.a, b: P.b, w: st.frameW / 2 + 1.5 }); }); info.road_gradients = { mode: 'LINEAR_SPACE_SMOOTHSTEP_SHARED_ENDPOINTS', longitudinal_step_m: 12, transition_pieces: gradientPieces, junction_segments: JUNCTION_SEGMENTS };
    /* M19 (found in the M19 winding sweep that caught the Veil meadow and the ridge ribbon): 80 % of the road SEAM triangles faced down — the
       ring / arc / clipped-strip helpers wind their quads differently — so with a FrontSide material four seams in five were culled from
       above and the kerb lines broke up. Every flat decal triangle here is meant to face the sky: re-wind any that do not (index order only). */
    [seams, cores, frames].forEach(function (B) { var P = B.pos, I = B.idx; for (var t = 0; t < I.length; t += 3) { var a0 = I[t] * 3, a1 = I[t + 1] * 3, a2 = I[t + 2] * 3, ex = P[a1] - P[a0], ez = P[a1 + 2] - P[a0 + 2], fx = P[a2] - P[a0], fz = P[a2 + 2] - P[a0 + 2]; if (ez * fx - ex * fz < 0) { var sw = I[t + 1]; I[t + 1] = I[t + 2]; I[t + 2] = sw; } } });
    if (seams.pos.length) { seamMat = new THREE.MeshBasicMaterial({ vertexColors: true, transparent: true, opacity: 0.85, depthWrite: false, polygonOffset: true, polygonOffsetFactor: -3, polygonOffsetUnits: -6 }); seamMat.color.setScalar(0.5); own.push(seamMat); add(geom(seams), seamMat, 'TERRAIN_PATH_SEAMS', 3); }
    /* M20 ROAD STONE (surface polish; owner: "material breakup at three scales … joint patterns that follow use (large civic slabs, setts on
       paths, edge courses along kerbs) … kerbs, edge courses and drainage channels as flush detail"; the lead's review: V25 a showroom floor
       of 4 × 2 m world-grid tiles, V05 / V16 a red carpet). Laid in ROAD SPACE (aRoad), all flush shading on the existing ribbons:
         CAUSEWAY (core ≥ 10 m)  a 0.9 m EDGE COURSE of darker granite (two rows of 0.6 m setts, the class seam runs in its outer row), a
                                 field of 1.2 × 0.6 m slabs in stretcher courses across the road, a 0.6 m transverse BAND of square setts
                                 every 12 m (each 12 m bay from its own quarry lot), and a cast GULLY GRATE in the edge course every
                                 24 m (alternating sides) with a faint damp halo where the run-off gathers;
         CLASS ROADS / spurs     class-stone SETTS (0.5 × 0.25 m courses, each sett its own value and chroma — natural stone) inside a
                                 0.35 m granite edge course;
         TRAILS                  a resin-bound gravel (fine speckle, no joints) between their dark edging;
         JUNCTIONS / FORECOURTS  concentric sett / slab courses round a plain medallion (the five-class rosette sits there);
         BEND CORNERS            the courses FAN round the bend's inner corner, so the road visibly turns (rings there read as a
                                 bullseye in V25); the corner's edge course runs only along its outer kerb.
       Joints are 1–1.3 cm, filled darker, fading to their coverage before they can alias; a derivative bevel and a hair of per-stone tilt
       near the eye (not on LOW). The regular diagonal 'vein' stripes and sine grain of the old core are gone (they read as a print). The
       kerb FRAME is honed granite now (metalness 0.78 → 0.3: it mirrored the sky), cut into 1 m stones along the road (radial on a disc),
       its outer arris catching the light. Night: the stone takes the wet-night sheen of the district floor (metalness 0.12 → 0.3, roughness
       0.6 → 0.5) instead of the old blue-lit core. Cost: the same draws / triangles; the world-grid seams of PAVER / KERB are off (seamless). */
    /* (on a disc the along coordinate is the rim angle scaled to a whole multiple of 21 m — the 0.6 / 0.7 / 1 m stones then close round the
       circle without a short stone where the angle wraps) */
    /* (rdNoise hashes a 256-cell periodic lattice: a raw world lattice index at 20–50 /m runs out of float precision in the hash and beats
       into a dot moire. rdHK is the road's half-width snapped to 0.25 m: the interpolated varying differs from pixel to pixel in its last bit,
       and a hash keyed on it flipped a stone's tone and tilt into a 2 px speckle wherever the sum crossed a rounding step) */
    var RD_LOW = sdTier() === 'LOW', RD_MED = sdTier() === 'MED', RD_DECL = 'varying vec4 vRd; varying vec2 vRdU; varying vec3 vMahRoadWorld;\nfloat rdHash(vec2 p) { p = fract(p * vec2(123.34, 456.21)); p += dot(p, p + 45.32); return fract(p.x * p.y); }\nfloat rdNoise(vec2 p) { vec2 i = floor(p), f = fract(p); f = f * f * (3.0 - 2.0 * f); return mix(mix(rdHash(mod(i, 256.0)), rdHash(mod(i + vec2(1.0, 0.0), 256.0)), f.x), mix(rdHash(mod(i + vec2(0.0, 1.0), 256.0)), rdHash(mod(i + 1.0, 256.0)), f.x), f.y); }\nvec3 rdBump(vec3 sp, vec3 sn, float h) { vec3 sx = dFdx(sp), sy = dFdy(sp); vec3 r1 = cross(sy, sn), r2 = cross(sn, sx); float det = dot(sx, r1); vec3 grad = sign(det) * (dFdx(h) * r1 + dFdy(h) * r2); return normalize(abs(det) * sn - grad); }';
    var RD_FRAME = 'bool rdDisc = vRd.w > 0.5; float rdE, rdS, rdLat, rdAng = 0.0, rdHW = vRd.z, rdHK = floor(vRd.z * 4.0 + 0.5) * 0.25; if (rdDisc) { vec2 dv = vMahRoadWorld.xz - vRd.xy; float rr = max(length(dv), 1e-3); rdE = rdHW - rr; rdLat = rr; rdAng = atan(dv.y, dv.x); rdS = (rdAng + 3.14159265) / 6.2831853 * max(21.0, floor(6.2831853 * rdHK / 21.0 + 0.5) * 21.0); } else { rdE = rdHW - abs(vRd.x); rdLat = vRd.x; rdS = vRd.y; } float rdDist = length(cameraPosition - vMahRoadWorld), rdFp = rdDist * length(dFdx(normalize(vViewPosition))) / sqrt(max(abs(cameraPosition.y - vMahRoadWorld.y) / max(rdDist, 1e-3), 0.06));';   /* rdFp: the pixel footprint (m) — distance × the pixel's angle (the view ray's own derivative: smooth, resolution-aware) ÷ √(grazing cosine), between the across- and along-view footprints — every fade / coverage factor uses it (fwidth-based amplitude factors change per 2 x 2 quad and stitched joints and grain into dot patterns) */
    function roadVert(sh) { sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nattribute vec4 aRoad; attribute vec2 aRoadU; varying vec4 vRd; varying vec2 vRdU; varying vec3 vMahRoadWorld;').replace('#include <worldpos_vertex>', '#include <worldpos_vertex>\nvMahRoadWorld = (modelMatrix * vec4(transformed, 1.0)).xyz; vRd = aRoad; vRdU = aRoadU;'); }
    /* M20 review (LOW must never get heavier than a330208 — the old core was 5 sines + the wear fetch + the PAVER world grid, one fwidth and
       two hashes; the kerb the KERB grid): LOW lays the same stone in STRAIGHT courses with the road-space work moved to the vertex shader.
       Per vertex: the lateral / along coordinates (a ribbon's own; a junction disc's in world axes; a bend corner's across / along its
       bisector, so its courses run with the mean road direction instead of fanning — no atan anywhere), the distance to the kerb edge (on a
       disc the radius, interpolated across its 24–128-gon fan: exact at the fan's rim, i.e. measured to the polygon edge the kerb follows) and the class of road. Per pixel: one course layout for
       the edge course (rows along the kerb) and the field (slab / sett courses across the road, a sett band every 12 m on the causeways) by
       swapping the two axes, ONE fwidth, ONE hash, the wear fetch (R8 on LOW); no bend fan, grates, disc rings, medallion, per-stone
       chroma, damp edge, footprint term or relief. The kerb: its 1 m stones cut along the ribbons (a disc rim keeps only its arris
       and outer joint), one fwidth, one hash. PAVER / KERB are not applied on LOW (seamless there, their LOW body was dead code): the
       core carries 8 varying floats of its own (a330208: 9, two of them the same world position), the kerb 3 (was 6). The disc offsets / bend packing come from the geometry (roadLow above). */
    var RD_DECL_LOW = 'varying vec4 vRd; varying vec2 vRdU; varying vec2 vRdW;\nfloat rdHash(vec2 p) { p = fract(p * vec2(123.34, 456.21)); p += dot(p, p + 45.32); return fract(p.x * p.y); }';
    function roadVertLow(sh) { sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nattribute vec3 aRoad; varying vec4 vRd; varying vec2 vRdU; varying vec2 vRdW;').replace('#include <worldpos_vertex>', ['#include <worldpos_vertex>',
      '{ vRdW = (modelMatrix * vec4(transformed, 1.0)).xz; float rdK = floor(aRoad.z / 32.0), rdHW = aRoad.z - 32.0 * rdK, rdHK = floor(rdHW * 4.0 + 0.5) * 0.25, rdEC = rdHK >= 5.0 ? 0.9 : 0.35, rdZ = rdHK >= 5.0 ? 0.0 : (rdHK >= 1.5 ? 1.0 : 2.0), rdF = (rdK - 3.0) / 511.0;',   /* rdZ: 0 causeway · 1 class road / spur · 2 trail */
      '  if (rdK < 0.5) { vRd = vec4(aRoad.x, aRoad.y, rdHW - abs(aRoad.x), rdZ); vRdU = vec2(rdHW - rdEC, -2.0); }',
      '  else { vRd = vec4(aRoad.xy, rdK > 1.5 && rdK < 2.5 ? 1e3 : rdHW - length(aRoad.xy), rdZ); vRdU = vec2(rdHW - rdEC, rdK < 2.5 ? -1.0 : rdF / max(1.0 - rdF, 1e-3)); } }'].join('\n')); }   /* vRdU.y: a bend's tan of its half-angle (its kerb course runs only where |along| · tan ≤ lateral: the outer corner) · -1 a disc · -2 a ribbon */
    function kerbVertLow(sh) { sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\nattribute vec3 aRoad; varying vec3 vRk;').replace('#include <worldpos_vertex>', '#include <worldpos_vertex>\n{ float rdK = floor(aRoad.z / 32.0), rdHW = aRoad.z - 32.0 * rdK; if (rdK < 0.5) vRk = vec3(aRoad.y, rdHW - abs(aRoad.x), 0.0); else vRk = vec3(0.0, rdHW - length(aRoad.xy), 1.0); }'); }
    if (frames.pos.length) { var frameMat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.55, metalness: 0.3, envMapIntensity: 0.14, polygonOffset: true, polygonOffsetFactor: -1, polygonOffsetUnits: -2 }); own.push(frameMat);
      if (RD_LOW) frameMat.onBeforeCompile = function (sh) { kerbVertLow(sh); sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nvarying vec3 vRk;\nfloat rdHash(vec2 p) { p = fract(p * vec2(123.34, 456.21)); p += dot(p, p + 45.32); return fract(p.x * p.y); }').replace('#include <color_fragment>', ['#include <color_fragment>',
        'float rdDist = length(vViewPosition), kF = fract(vRk.x), kDb = vRk.z > 0.5 ? 1e3 : min(kF, 1.0 - kF), kAA = max(fwidth(min(kDb, vRk.y)), 1e-4) * 1.25, kNear = 1.0 - smoothstep(20.0, 90.0, rdDist);',
        'float kJ = max((1.0 - smoothstep(0.004, 0.004 + kAA, kDb)) * (1.0 - smoothstep(10.0, 32.0, rdDist)), 1.0 - smoothstep(0.004, 0.004 + kAA, vRk.y)) * clamp(0.008 / kAA, 0.0, 1.0) * kNear; float kH = rdHash(vec2(floor(vRk.x), vRk.z > 0.5 ? 5.0 : 1.0)), kArris = (1.0 - smoothstep(0.012, 0.05, vRk.y)) * kNear;',
        'diffuseColor.rgb *= (1.0 + (kH - 0.5) * 0.12) * (1.0 + 0.2 * kArris) * mix(1.0, 0.5, kJ);'].join('\n'))
        .replace('#include <roughnessmap_fragment>', '#include <roughnessmap_fragment>\nroughnessFactor = clamp(roughnessFactor * (1.0 + (kH - 0.5) * 0.2) * (1.0 - 0.25 * kArris), 0.05, 1.0);'); };
      else frameMat.onBeforeCompile = function (sh) { roadVert(sh); sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\n' + RD_DECL).replace('#include <color_fragment>', ['#include <color_fragment>', RD_FRAME,
        'float kG = rdS / 1.0, kF = fract(kG), kDb = min(kF, 1.0 - kF), kD = min(kDb, rdE), kAAb = max(fwidth(kDb), 1e-4) * 1.25, kAAe = max(fwidth(rdE), 1e-4) * 1.25, kNear = 1.0 - smoothstep(20.0, 90.0, rdDist);',
        'float kJ = max((1.0 - smoothstep(0.004, 0.004 + kAAb, kDb)) * clamp(0.008 / (rdFp * 1.25), 0.0, 1.0) * (1.0 - smoothstep(10.0, 32.0, rdDist)), (1.0 - smoothstep(0.004, 0.004 + kAAe, rdE)) * clamp(0.008 / (rdFp * 1.25), 0.0, 1.0)) * kNear; float kH = rdHash(vec2(floor(kG), rdDisc ? 5.0 : 1.0) + rdHK);',
        'float kArris = (1.0 - smoothstep(0.012, 0.05, rdE)) * kNear;',   /* the chamfered top edge of the kerb catches the sky */
        'diffuseColor.rgb *= (1.0 + (kH - 0.5) * 0.12) * (1.0 + 0.2 * kArris) * mix(1.0, 0.5, kJ) * (0.96 + 0.08 * rdNoise(vMahRoadWorld.xz * 0.35));'].join('\n'))
        .replace('#include <roughnessmap_fragment>', '#include <roughnessmap_fragment>\nroughnessFactor = clamp(roughnessFactor * (1.0 + (kH - 0.5) * 0.2) * (1.0 - 0.25 * kArris), 0.05, 1.0);');
        sh.fragmentShader = sh.fragmentShader.replace('#include <normal_fragment_maps>', '#include <normal_fragment_maps>\n{ float kN2 = 1.0 - smoothstep(5.0, 14.0, rdDist); normal = rdBump(-vViewPosition, normal, 0.005 * (smoothstep(0.0, 0.03, kD) - 1.0) * kN2 * clamp(0.015 / rdFp - 1.0, 0.0, 1.0)); }'   /* the chamfer is a dip at the joint (0 on the stone's face): the fades never tilt a flat face (their 2 x 2-quad derivative steps read as dots in the sky sheen) */); };
      frameMat.customProgramCacheKey = function () { return 'mahworld_path_kerb_m20r_' + (RD_LOW ? 'L' : 'H'); };
      if (!RD_LOW) applySurface(THREE, frameMat, 'KERB', sdTier());   /* M8: kerb stones along every path frame (M20: cut along the road here; KERB adds only its macro breakup and micro relief — no grain, no world grid; not on LOW, where it was a no-op) */ add(geom(frames), frameMat, 'TERRAIN_PATH_FRAMES', 1); }
    if (cores.pos.length) { coreMat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.6, metalness: 0.12, envMapIntensity: 0.26, emissive: 0xffffff, emissiveIntensity: 0.03, polygonOffset: true, polygonOffsetFactor: -2, polygonOffsetUnits: -4 }); var coreWear = wearField(THREE, reg, sdTier());
      if (RD_LOW) coreMat.onBeforeCompile = function (sh) { sh.uniforms.uMahWear = { value: coreWear.tex }; sh.uniforms.uMahWearB = { value: coreWear.bounds }; roadVertLow(sh);
        sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\n' + RD_DECL_LOW + '\nuniform sampler2D uMahWear; uniform vec4 uMahWearB;').replace('#include <color_fragment>', ['#include <color_fragment>',
          'float rdE = vRd.z; if (vRdU.y > -0.5 && abs(vRd.y) * vRdU.y > vRd.x) rdE = 1e3;',   /* a bend corner: the kerb course only round its outer corner */
          'float rdDist = length(vViewPosition), rdBig = 1.0 - step(0.5, vRd.w), rdTr = step(1.5, vRd.w), rdEC = mix(0.35, 0.9, rdBig); bool rdEdge = rdE < rdEC && rdTr < 0.5;',
          'float rdCl = rdEdge ? mix(0.35, 0.45, rdBig) : mix(0.25, 0.6, rdBig), rdU = rdEdge ? rdE : vRd.y, rdC = floor(rdU / rdCl), rdFc = rdU - rdC * rdCl, rdBand = rdEdge ? 0.0 : rdBig * step(mod(rdC, 20.0), 0.5);',   /* course lines: the edge course's rows along the kerb · the field's courses across the road (a band of square setts every 20th course = 12 m) */
          'float rdSw = rdEdge ? mix(0.7, 0.6, rdBig) : mix(0.5, mix(1.2, 0.6, rdBand), rdBig), rdG = (rdEdge ? vRd.y : vRd.x + vRdU.x) / rdSw + 0.5 * mod(rdC, 2.0) * (1.0 - rdBand), rdFg = fract(rdG);',   /* stones along the course, stretcher bond */
          'float rdDa = min(rdFc, rdCl - rdFc), rdDb = min(rdFg, 1.0 - rdFg) * rdSw; if (!rdEdge) rdDa = min(rdDa, rdE - rdEC); if (rdEdge && vRdU.y > -1.5) rdDb = 1e3;',   /* a disc keeps its edge course's rows only (straight cross joints would cut a ring askew) */
          'float rdH = rdHash(vec2(floor(rdG), rdC + (rdEdge ? 7.0 + step(vRd.x, 0.0) * 3.0 : 0.0))), rdTone = rdTr > 0.5 ? 0.92 : (1.0 + (rdH - 0.5) * mix(0.16, 0.1, rdBig)) * (rdEdge ? 0.8 : mix(1.0, 0.88, rdBand));',
          'float mahWear = texture2D(uMahWear, (vRdW - uMahWearB.xy) * uMahWearB.zw).r * 0.8;',   /* M14 LIVED-IN: the centre of the road is foot-polished */
          'float rdW = mix(0.01, 0.013, rdBig), rdAA = max(fwidth(min(rdDa, rdDb)), 1e-4) * 1.25, rdJ = max(1.0 - smoothstep(rdW * 0.5, rdW * 0.5 + rdAA, rdDa), (1.0 - smoothstep(rdW * 0.5, rdW * 0.5 + rdAA, rdDb)) * (1.0 - smoothstep(6.0, 22.0, rdDist))) * clamp(rdW / rdAA, 0.0, 1.0) * (1.0 - smoothstep(20.0, 90.0, rdDist)) * (1.0 - 0.45 * mahWear) * (1.0 - rdTr);',
          'diffuseColor.rgb *= rdTone * mix(1.0, 0.6, rdJ) * (1.0 - 0.05 * mahWear);'].join('\n'))   /* (no damp run-off edge on LOW: 3 % of value, not worth its smoothstep) */
          .replace('#include <roughnessmap_fragment>', '#include <roughnessmap_fragment>\nroughnessFactor *= (1.0 - 0.45 * mahWear) * (1.0 + (fract(rdH * 13.7 + 0.31) - 0.5) * 0.2); roughnessFactor = clamp(mix(roughnessFactor, max(roughnessFactor, 0.85), rdJ), 0.05, 1.0);')
          .replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n\ttotalEmissiveRadiance = emissive * vColor.rgb * 0.72 * rdTone * mix(1.0, 0.35, rdJ);'); };
      else coreMat.onBeforeCompile = function (sh) { sh.uniforms.uMahWear = { value: coreWear.tex }; sh.uniforms.uMahWearB = { value: coreWear.bounds }; roadVert(sh);
        sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\n' + RD_DECL + '\nuniform sampler2D uMahWear; uniform vec4 uMahWearB;').replace('#include <color_fragment>', ['#include <color_fragment>', RD_FRAME,
          'bool rdBend = vRd.w > 1.5; float rdSe = rdS; if (rdBend) { vec2 q = vMahRoadWorld.xz - vRdU, dn = normalize(vRd.xy - vRdU); float dC = length(vRd.xy - vRdU); rdLat = length(q) - dC; rdS = atan(dn.x * q.y - dn.y * q.x, dot(dn, q)) * dC + 600.0; float sh = clamp(rdHW / dC, 0.0, 1.0), ch = sqrt(1.0 - sh * sh); vec2 pb = vec2(dn.y, -dn.x), pn = vMahRoadWorld.xz - vRd.xy; if (dC > 300.0 || max(dot(pn, -dn * ch + pb * sh), dot(pn, -dn * ch - pb * sh)) > 0.0) rdE = 1e3; }',   /* a bend corner: road space fanned round its inner corner; the disc rim is a kerb only on the outer corner (between the legs it is road, where the legs join) */
          'float mahWear = texture2D(uMahWear, (vMahRoadWorld.xz - uMahWearB.xy) * uMahWearB.zw).r * (0.6 + 0.4 * rdNoise(vMahRoadWorld.xz * 0.09));',   /* M14 LIVED-IN: the centre of the road is foot-polished */
          'float rdBig = step(5.0, rdHK), rdSet = step(1.5, rdHK) * (1.0 - rdBig), rdEC = mix(0.35, 0.9, rdBig), rdDa = 1e3, rdDb = 1e3, rdZone = 0.0, rdDamp = 0.0, rdBar = 0.5, rdBw = fwidth(rdS / 0.06); vec2 rdId = vec2(0.0);',   /* rdDa: the long course lines · rdDb: the short cross joints (they fade sooner: at range they stitched the courses into dotted lines) */
          'if (rdBig + rdSet < 0.5) { rdZone = 4.0; }',
          'else if (rdE < rdEC) { float rw = mix(0.35, 0.45, rdBig), sl = mix(0.7, 0.6, rdBig), row = floor(rdE / rw), fe = rdE - row * rw, g = rdSe / sl + 0.5 * row, fg = fract(g); rdDa = min(fe, rw - fe); rdDb = min(fg, 1.0 - fg) * sl; rdId = vec2(floor(g), row + 7.0 + step(rdLat, 0.0) * 3.0); rdZone = 1.0;',
          '  if (rdBig > 0.5 && !rdDisc && row > 0.5) { float ga = mod(rdS + step(rdLat, 0.0) * 12.0, 24.0); if (ga > 6.0 && ga < 6.9) { rdZone = 3.0; rdDb = min(ga - 6.0, 6.9 - ga); float bq = rdS / 0.06, bw = rdBw; rdBar = mix(0.5, smoothstep(0.3 - bw, 0.3 + bw, fract(bq)) * (1.0 - smoothstep(0.7 - bw, 0.7 + bw, fract(bq))), clamp(1.0 - rdFp / 0.06 * 1.5, 0.0, 1.0)); } } }',   /* a cast gully grate: slots across the edge course */
          'else if (rdDisc && !rdBend) { float cw = mix(0.25, 0.6, rdBig), jl = mix(0.5, 1.2, rdBig), ri = rdHW - rdEC, q = (ri - rdLat) / cw, cI = floor(q), cf = q - cI, rc = max(ri - (cI + 0.5) * cw, 0.2), n = max(3.0, floor(6.2831853 * rc / jl)), a = (rdAng + 3.14159265) / 6.2831853 * n + 0.5 * mod(cI, 2.0), fa = fract(a); rdDa = min(cf, 1.0 - cf) * cw; rdDb = min(fa, 1.0 - fa) * 6.2831853 * max(rdLat, 0.2) / n; rdId = vec2(cI, floor(a));',
          '  float md = mix(0.6, 1.5, rdBig); if (rdLat < md && vRd.w < 1.5) { rdDa = md - rdLat; rdDb = 1e3; rdId = vec2(-3.0, 1.0); rdZone = 2.0; } }',   /* the plain medallion (the rosette / node gem sits on it); a bend corner has none */
          'else if (rdBig > 0.5) { float fw = rdHW - rdEC, bay = floor(rdS / 12.0), fa = rdS - bay * 12.0; if (fa < 0.6) { float g = (rdLat + fw) / 0.6, fg = fract(g); rdDa = min(fa, 0.6 - fa); rdDb = min(fg, 1.0 - fg) * 0.6; rdId = vec2(floor(g), bay * 7.0 + 900.0); rdZone = 2.0; }',
          '  else { float cr = floor((fa - 0.6) / 0.6), fc = fa - 0.6 - cr * 0.6, g = (rdLat + fw) / 1.2 + 0.5 * mod(cr, 2.0), fg = fract(g); rdDa = min(fc, 0.6 - fc); rdDb = min(fg, 1.0 - fg) * 1.2; rdId = vec2(floor(g), bay * 40.0 + cr); }',
          '  rdDa = min(rdDa, rdE - rdEC); float gd = mod(rdS + step(rdLat, 0.0) * 12.0, 24.0) - 6.45, ge = rdE - rdEC; rdDamp = rdDisc ? 0.0 : exp(-gd * gd / 4.0 - ge * ge / 0.6); }',   /* the damp halo round each grate, on its own side */
          'else { float fw = rdHW - rdEC, cr = floor(rdS / 0.25), fc = rdS - cr * 0.25, g = (rdLat + fw) / 0.5 + 0.5 * mod(cr, 2.0), fg = fract(g); rdDa = min(min(fc, 0.25 - fc), rdE - rdEC); rdDb = min(fg, 1.0 - fg) * 0.5; rdId = vec2(floor(g), cr); }',
          'float rdD = min(rdDa, rdDb), rdH1 = rdHash(rdId + 3.1 + rdHK), rdH2 = rdHash(rdId * 1.3 + 7.7);',
          'float rdTone = (1.0 + (rdH1 - 0.5) * mix(0.16, 0.1, rdBig)) * (rdZone > 0.5 && rdZone < 1.5 ? 0.8 : (rdZone > 1.5 && rdZone < 2.5 ? 0.88 : 1.0));',
          'if ((!rdDisc || rdBend) && rdBig > 0.5) rdTone *= 1.0 + (rdHash(vec2(floor(rdS / 12.0), rdHK)) - 0.5) * 0.08;',   /* each bay its own quarry lot */
          'if (rdZone > 2.5 && rdZone < 3.5) rdTone = mix(0.34, 0.8, rdBar);',
          RD_MED ? 'float rdGn = 0.0, rdGk = 0.0;' : 'float rdGn = (rdNoise(vMahRoadWorld.xz * 19.0) - 0.5) * 0.6 * (1.0 - smoothstep(0.25, 0.6, rdFp * 19.0)) + (rdNoise(vMahRoadWorld.xz * 47.0 + 3.3) - 0.5) * 0.4 * (1.0 - smoothstep(0.25, 0.6, rdFp * 47.0)), rdGk = 1.0;'   /* each octave fades out before it nears the pixel (at the Nyquist edge value noise beat into a dot moire) */,
          'if (rdZone > 3.5) rdTone = 0.92 * (1.0 + rdGn * 0.34 * (0.4 + 0.6 * rdGk)); else rdTone *= 1.0 + rdGn * 0.1 * rdGk;',   /* trails: resin-bound gravel; stone: a fine aggregate */
          'float rdL = dot(diffuseColor.rgb, vec3(0.2126, 0.7152, 0.0722)); diffuseColor.rgb = max(mix(vec3(rdL), diffuseColor.rgb, rdZone > 0.5 && rdZone < 1.5 ? 0.45 : mix(0.62, 1.12, rdH2)), 0.0);',   /* natural stone: every sett its own chroma; the edge course a greyer granite (eased through an equal-channel grey) */
          'float rdNear = 1.0 - smoothstep(20.0, 90.0, rdDist), rdW = mix(0.01, 0.013, rdBig), rdAAa = max(fwidth(rdDa), 1e-4) * 1.25, rdAAb = max(fwidth(rdDb), 1e-4) * 1.25;',
          'float rdJ = max((1.0 - smoothstep(rdW * 0.5, rdW * 0.5 + rdAAa, rdDa)) * clamp(rdW / (rdFp * 1.25), 0.0, 1.0), (1.0 - smoothstep(rdW * 0.5, rdW * 0.5 + rdAAb, rdDb)) * clamp(rdW / (rdFp * 1.25), 0.0, 1.0) * (1.0 - smoothstep(6.0, 22.0, rdDist))) * rdNear * (1.0 - 0.45 * mahWear) * (rdDisc && !rdBend ? 0.75 : 1.0);',
          'rdDamp = max(rdDamp, (1.0 - smoothstep(rdEC, rdEC + 1.4, rdE)) * 0.25 * rdBig)' + (RD_MED ? ' * 0.85;' : ' * (0.7 + 0.3 * rdNoise(vMahRoadWorld.xz * 0.6));'),   /* the run-off side of the field stays a touch damp */
          'diffuseColor.rgb *= rdTone * mix(1.0, 0.6, rdJ) * (1.0 - 0.12 * rdDamp) * (1.0 - 0.05 * mahWear)' + (RD_MED ? ' * (0.93 + 0.14 * rdNoise(vMahRoadWorld.xz * 0.07));' : ' * (0.9 + 0.14 * rdNoise(vMahRoadWorld.xz * 0.07) + 0.06 * rdNoise(vMahRoadWorld.xz * 0.23));')].join('\n'))
          .replace('#include <roughnessmap_fragment>', '#include <roughnessmap_fragment>\nroughnessFactor *= (1.0 - 0.45 * mahWear) * (1.0 + (rdH2 - 0.5) * 0.2) * (1.0 - 0.4 * rdDamp) * (rdZone > 2.5 && rdZone < 3.5 ? 0.7 : 1.0); roughnessFactor = clamp(mix(roughnessFactor, max(roughnessFactor, 0.85), rdJ), 0.05, 1.0);')
          .replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n\ttotalEmissiveRadiance = emissive * vColor.rgb * 0.72 * rdTone * mix(1.0, 0.35, rdJ);');
        sh.fragmentShader = sh.fragmentShader.replace('#include <normal_fragment_maps>', '#include <normal_fragment_maps>\n{ float rdN2 = 1.0 - smoothstep(6.0, 16.0, rdDist); normal = rdBump(-vViewPosition, normal, 0.004 * (smoothstep(0.0, 0.03, rdD) - 1.0) * rdN2 * step(rdZone, 3.5) * clamp(0.015 / rdFp - 1.0, 0.0, 1.0));   /* the 3 cm bevel only while it spans ≥ 2 px (at range its quad-derivative highlight stitched the joints into dotted lines) */ vec3 rdTl = vec3(rdH1 - 0.5, 0.0, rdH2 - 0.5) * 0.03 * rdN2 * step(rdZone, 2.5); normal = normalize(normal + (viewMatrix * vec4(rdTl, 0.0)).xyz); }'); };
      coreMat.customProgramCacheKey = function () { return 'mahworld_path_core_owned_v5_' + (RD_LOW ? 'L' : RD_MED ? 'M' : 'H'); }; own.push(coreMat); if (!RD_LOW) applySurface(THREE, coreMat, 'PAVER', sdTier());   /* M8: honed causeway (M20: stone laid in road space here; PAVER adds only its macro breakup — no grain, no micro relief, no world grid; not on LOW, where it was a no-op) */ add(geom(cores), coreMat, 'TERRAIN_PATH_CORES', 2); }   /* opaque owned cores: no stacked alpha at crossings */
    /* 3. MESO shards (seeded per region; excluded from lanes, paths, the plaza, landmarks, doors, water)
       M20 (owner 2026-09-27: "Prioritize removing: awkward repeated crystals, ugly procedural clutter … weak repeated geometry"; the audit
       frames: 961 identical octahedra strewn over every district floor — the temple forecourt, the TITAN squares, the rose basins — and
       2 661 additive dust points glittering on the ground): 4. MICRO dust is REMOVED (one draw, 2 661 points). The shards grow only where the
       ground is natural (inside a FOREST / garden zone, ≥ 2.5 m in from its edge — never on paving), at 45 % of the old density and ≥ 5.5 m
       apart, each a COMPOSED cluster: one hero crystal (0.29–0.42 m) and two or three small companions (0.12–0.23 m) leaning out of its
       root, all soft crystals sunk into the ground with a darkened root. Heights stay inside the old 0.12–0.42 m band. */
    var maxShards = Math.min(GD.max_shards || 900, 360); var hR = GD.shard_h_m || [0.12, 0.42]; var gap = 5.5; var shardList = []; var SHARD_DENSITY_K = tierQ() === 'LOW' ? 0.22 : 0.45, SHARD_NATURAL_IN = 2.5;   /* LOW: half the clusters (the soft shard costs 35 triangles there, the old octahedron 8 — LOW stays no heavier) */
    var natural = (reg.zones || []).filter(function (z) { return z.kind === 'FOREST' && (z.rect || z).x1 !== undefined; }).map(function (z) { return z.rect || z; });
    function naturalIn(x, z) { var best = -1e9; for (var i = 0; i < natural.length; i++) { var r = natural[i]; best = Math.max(best, Math.min(Math.min(x - r.x1, r.x2 - x), Math.min(z - r.z1, r.z2 - z))); } return best; }   /* metres inside the nearest natural zone */
    var czC = combatZoneCircles(reg, 1.5);   /* M15: no shards inside a combat zone's floor */
    var excluded = function (x, z) { for (var q = 0; q < czC.length; q++) if ((x - czC[q].x) * (x - czC[q].x) + (z - czC[q].z) * (z - czC[q].z) <= czC[q].r * czC[q].r) return true; for (var i = 0; i < ex.rects.length; i++) if (inRect(x, z, ex.rects[i])) return true; for (i = 0; i < ex.circles.length; i++) { var c = ex.circles[i]; if ((x - c.x) * (x - c.x) + (z - c.z) * (z - c.z) <= c.r * c.r) return true; } for (i = 0; i < ex.segs.length; i++) if (nearSeg(x, z, ex.segs[i].a, ex.segs[i].b, ex.segs[i].w)) return true; for (i = 0; i < pathSegs.length; i++) if (nearSeg(x, z, pathSegs[i].a, pathSegs[i].b, pathSegs[i].w)) return true; return false; };
    RG.forEach(function (R, ri) { var dens = (R.shard_density_per_100m2 || 0) * SHARD_DENSITY_K; var rects = regionRects(R); var r0 = rnd(0xC0DE + ri * 7919); var col = crystalColor(R.family), glow = crystalColor(R.family, 'glow');
      rects.forEach(function (r) { var area = (r.x2 - r.x1) * (r.z2 - r.z1); var want = Math.min(Math.floor((maxShards - shardList.length) / 3), Math.round(area / 100 * dens)); var placed = []; var tries = 0; while (placed.length < want && tries < want * 14) { tries++; var x = r.x1 + r0() * (r.x2 - r.x1), z = r.z1 + r0() * (r.z2 - r.z1); if (!inRegion(x, z, R) || excluded(x, z) || naturalIn(x, z) < SHARD_NATURAL_IN || bedEdge(natural, x, z).d < BED.course_m + BED.margin_m[1] + 0.4) continue;   /* M20: on the planted bed's soil, clear of its raked gravel margin */ var ok = true; for (var k = 0; k < placed.length; k++) if (Math.hypot(placed[k][0] - x, placed[k][1] - z) < gap) { ok = false; break; } if (!ok) continue; placed.push([x, z]); var n = 3 + Math.floor(r0() * 2);
          for (var c = 0; c < n; c++) { var ang = r0() * Math.PI * 2, dd = c ? 0.12 + r0() * 0.22 : 0, h = c ? hR[0] + r0() * (hR[1] * 0.55 - hR[0]) : hR[1] * 0.7 + r0() * hR[1] * 0.3; shardList.push({ x: x + Math.cos(ang) * dd, z: z + Math.sin(ang) * dd, r: h * (c ? 0.3 : 0.27), h: h, yaw: r0() * Math.PI, lean: c ? 0.22 + r0() * 0.3 : r0() * 0.08, leanAng: c ? ang : r0() * Math.PI * 2, col: col.clone().lerp(glow, r0() * 0.4).multiplyScalar(0.8 + r0() * 0.3) }); } } }); });   /* the hero stands near-upright; the companions lean out of its root */
    if (shardList.length) { var LOWS = tierQ() === 'LOW', sg = softCrystalGeometry(THREE, { sides: 5, samples: 1, bevel: 0, ground: true, contact: 0.15, squash: 0.85, profile: [[-0.12, 0.95], [0.15, 0.9], [0.6, 0.76], [0.9, 0.12], [1.0, 0]] });   /* small (≤ 0.42 m): smooth-normal corners and shoulders, the facet tone still reads the cut — 35 triangles */ shardMat = new THREE.MeshStandardMaterial({ roughness: 0.16, metalness: 0.3, envMapIntensity: 0.6, transparent: true, opacity: 0.92, emissive: 0xffffff, emissiveIntensity: 0.06 }); shardMat.onBeforeCompile = function (sh) { sh.uniforms.uWarmNight = WARM_NIGHT; sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nuniform float uWarmNight;').replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n#ifdef USE_COLOR\n\ttotalEmissiveRadiance = emissive * vColor.rgb * (1.0 + uWarmNight * step(vColor.b * 1.05 + 0.002, vColor.r));\n#endif'); }; shardMat.customProgramCacheKey = function () { return 'mahworld_shard'; }; applyCrystal(THREE, shardMat, { tier: tierQ(), soft: true, glow: CRYSTAL_GLOW, facet: 0.3, veins: 0 }); own.push(shardMat); own.push(sg);
      var im = new THREE.InstancedMesh(sg, shardMat, shardList.length); im.name = 'TERRAIN_SHARDS'; im.userData.noMerge = true; im.frustumCulled = false; var m4 = new THREE.Matrix4(), q = new THREE.Quaternion(), qy = new THREE.Quaternion(), ax = new THREE.Vector3(), up = new THREE.Vector3(0, 1, 0), v = new THREE.Vector3(), s = new THREE.Vector3(); shardList.forEach(function (S, i) { qy.setFromAxisAngle(up, S.yaw); ax.set(Math.sin(S.leanAng), 0, -Math.cos(S.leanAng)); q.setFromAxisAngle(ax, S.lean).multiply(qy); v.set(S.x, gy(S.x, S.z) - S.h * 0.04, S.z); s.set(S.r, S.h, S.r); m4.compose(v, q, s); im.setMatrixAt(i, m4); im.setColorAt(i, S.col); }); im.instanceMatrix.needsUpdate = true; im.instanceColor.needsUpdate = true; im.receiveShadow = true; group.add(im); meshes.push(im); info.shards = shardList.length; info.draw_calls++; info.tris += (sg.index.count / 3) * shardList.length; }   /* tilt axis = up × lean direction: the crystal leans toward leanAng */
    info.dust = 0;   /* M20: the MICRO dust field is removed (was one additive draw of ~2 661 points glittering on the paving) */
    /* 5. LANDMARKS: monoliths / crown spires — a main crystal + two satellites, family crystal.
       M20 (owner 2026-09-27: "Ground crystals must sit in the ground … grounding, scale variety … remove sharp objects and edges"; the audit:
       every monolith was an elongated octahedron balanced on its point on a platinum plate — a spinning top on a coaster): each crystal is now a
       SOFT CRYSTAL COLUMN — a six-sided prism with rounded edges rising out of the ground (its root sunk 8 % and darkened), a bevelled shoulder
       and a blunted termination that thins into the class glow (spires: a longer, slimmer termination). The main column stays inside its
       CYLINDER collider (widest 0.9 r at the root, 0.8 r at the shoulder, top 0.95 h — the collider was a full cylinder round a thin
       octahedron, so the visible crystal now fills the space it blocks); the satellites keep their proxies and lean a few degrees out of the
       cluster (lean capped so the shoulder stays inside the proxy); three small FOOT crystals (0.3 r tall) lean out of the main column's root
       inside its footprint. The platinum plate is replaced by a CONTACT APRON — a soft dark ground shadow fading out over 2.6 r (flush,
       1.8 cm, one draw as before). Cost (24 monoliths, one merged draw as before): HIGH ≈ 19 k triangles (rounded main edges, chamfered
       satellites), MED ≈ 12 k (chamfered main, plain satellites), LOW ≈ 4 k (plain corners, smooth shoulders, no foot crystals). */
    var LOWM = tierQ() === 'LOW', MEDM = tierQ() === 'MED', monoGeos = [], apron = { pos: [], col: [], idx: [] }, _lq = new THREE.Quaternion(), _la = new THREE.Vector3();
    var CRY = { COLUMN: softCrystalGeometry(THREE, { sides: 6, samples: LOWM ? 1 : (MEDM ? 2 : 3), round: 0.16, bevel: LOWM ? 0 : 0.03, ground: true, contact: 0.07, squash: 0.85, profile: [[-0.08, 0.9], [0.07, 0.88], [0.58, 0.8], [0.82, 0.26], [0.9, 0.08], [0.95, 0]] }),
      SPIRE: softCrystalGeometry(THREE, { sides: 6, samples: LOWM ? 1 : (MEDM ? 2 : 3), round: 0.16, bevel: LOWM ? 0 : 0.03, ground: true, contact: 0.06, squash: 0.85, profile: [[-0.06, 0.86], [0.06, 0.84], [0.5, 0.7], [0.85, 0.15], [0.915, 0.05], [0.95, 0]] }),
      COLUMN_SAT: softCrystalGeometry(THREE, { sides: 6, samples: LOWM || MEDM ? 1 : 2, round: 0.16, bevel: LOWM ? 0 : 0.03, ground: true, contact: 0.07, squash: 0.85, profile: [[-0.08, 0.9], [0.07, 0.88], [0.58, 0.8], [0.82, 0.26], [0.9, 0.08], [0.95, 0]] }),   /* satellites: chamfered edges (two samples a corner) */
      SPIRE_SAT: softCrystalGeometry(THREE, { sides: 6, samples: LOWM || MEDM ? 1 : 2, round: 0.16, bevel: LOWM ? 0 : 0.03, ground: true, contact: 0.06, squash: 0.85, profile: [[-0.06, 0.86], [0.06, 0.84], [0.5, 0.7], [0.85, 0.15], [0.915, 0.05], [0.95, 0]] }),
      FOOT: softCrystalGeometry(THREE, { sides: 5, samples: 1, bevel: 0, ground: true, contact: 0.18, squash: 0.9, profile: [[-0.1, 0.9], [0.5, 0.75], [0.88, 0.14], [1.0, 0]] }) };
    function mk(x, z, hh, rr, yaw, kind, lean, leanAng, col, shade) { var g = CRY[kind].clone(); g.scale(rr, hh, rr); g.rotateY(yaw); if (lean) { _la.set(Math.sin(leanAng), 0, -Math.cos(leanAng)); g.applyQuaternion(_lq.setFromAxisAngle(_la, lean)); } g.translate(x, gy(x, z), z); var cnt = g.attributes.position.count, cc = new Float32Array(cnt * 3); for (var i = 0; i < cnt; i++) { cc[i * 3] = col.r * shade; cc[i * 3 + 1] = col.g * shade; cc[i * 3 + 2] = col.b * shade; } g.setAttribute('color', new THREE.BufferAttribute(cc, 3)); monoGeos.push(g); }
    function satLean(rr, hh) { return Math.min(0.07, Math.asin(Math.min(1, 0.18 * rr / (0.6 * hh)))); }   /* the shoulder (0.8 r at 0.58 h) may move at most 0.18 r: the leaning crystal stays inside its proxy */
    function apronAt(x, z, r) { var n = 24, b = apron.pos.length / 3, y0 = 0.018, g0 = gy(x, z), i; apron.pos.push(x, g0 + y0, z); apron.col.push(0.014, 0.014, 0.014, 0.5); [[0.62, 0.4], [1, 0]].forEach(function (Rg) { for (var k = 0; k < n; k++) { var a = k / n * Math.PI * 2, px = x + Math.cos(a) * r * Rg[0], pz = z + Math.sin(a) * r * Rg[0]; apron.pos.push(px, Math.min(gy(px, pz), g0) + y0, pz); apron.col.push(0.014, 0.014, 0.014, Rg[1]); } }); for (i = 0; i < n; i++) { var j = (i + 1) % n, a0 = b + 1 + i, a1 = b + 1 + j; apron.idx.push(b, a1, a0, a0, a1, a1 + n, a0, a1 + n, a0 + n); } }   /* every triangle faces the sky (checked: centre fan and ring quads wound counter-clockwise from above); M20 review: a vertex over RISING ground stays at the monolith's own ground (it slips under the terrace instead of climbing its wall as a dark wedge — TITAN_MOON_PASS x 135 / 165 by the 2.8 m terrace, VISIONARY −120, 0); the shadow is an equal-channel near-black (was faintly blue) */
    RG.forEach(function (R, ri) { (R.monoliths || []).forEach(function (Mo, mi) { var r1 = rnd(0x5E1F + ri * 31 + mi * 7); var col = crystalColor(R.family).lerp(crystalColor(R.family, 'glow'), 0.1); var h = Mo.h || 6; var rad = Mo.spire ? h * 0.13 : h * 0.18, kind = Mo.spire ? 'SPIRE' : 'COLUMN';
      mk(Mo.x, Mo.z, h, rad, r1() * 3, kind, 0, 0, col, 1); var sA = [Mo.x + rad * 1.6, Mo.z + rad * 0.4, h * 0.45, rad * 0.55], sB = [Mo.x - rad * 1.2, Mo.z - rad * 0.9, h * 0.3, rad * 0.45];
      [[sA, 0.92], [sB, 1.06]].forEach(function (S) { var s = S[0]; mk(s[0], s[1], s[2], s[3], r1() * 3, kind + '_SAT', satLean(s[3], s[2]), Math.atan2(s[1] - Mo.z, s[0] - Mo.x), col, S[1]); });
      if (!LOWM) for (var fk = 0; fk < 3; fk++) { var fa = r1() * Math.PI * 2 / 3 + fk * Math.PI * 2 / 3; mk(Mo.x + Math.cos(fa) * rad * 0.88, Mo.z + Math.sin(fa) * rad * 0.88, rad * (0.24 + r1() * 0.08), rad * 0.07, r1() * 3, 'FOOT', 0.24, fa, col, 0.85); }   /* tip at ≤ 0.88 r + 0.32 r · sin 0.24 < 0.97 r: inside the main collider */
      apronAt(Mo.x, Mo.z, rad * 2.6); info.monoliths++;
      if (ctx.auraRequests && R.family !== 'platinum' && !Mo.m19) { var inDist = (R.monoliths || []).filter(function (m) { return !m.m19; }), lead = inDist.length > 0 && inDist.reduce(function (a, b) { return (b.h || 6) > (a.h || 6) ? b : a; }) === Mo;   /* M19 fix (review 2026-09-27): the warm crown spires beyond the walls (m19) are landmarks only — they never take the region's lead (the ringed halo and the dimensional aura stay over the reachable district crystal, as before M19) and carry no aura of their own (a rose / crimson halo over the blue night sky reads as a fake purple fringe) */ var gf = AURA_WARM[R.family] || (FAM[R.family] || {}).glow || (FAM[R.family] || {}).color || '#dfe6ee';   /* M19: the aura shader shows the tint's linear value — the registry gold glow displayed at hue 36° (amber); ATHLETE's crystal auras take a gold whose linear value is gold (hue 47°) */
        if (lead && ctx.auraForms) { var mg0 = gy(Mo.x, Mo.z), fs = Math.max(1.6, h * 0.3); ctx.auraForms.push({ x: Mo.x, y: mg0 + Math.max(h * 1.02 + fs * 0.95, 3.4 + fs * 0.98 + 0.2), z: Mo.z, size: fs, shape: Mo.spire ? 'DIAMOND' : 'CUBE', tint: parseInt(String(gf).replace('#', ''), 16), intensity: 0.42, ground: mg0, axis: [0.55, 1, 0.3], spin: 0.09, phase: (ri * 0.37 + 0.11) % 1 }); }   /* M14 DIMENSIONAL AURA: a turning light cube (a diamond over a spire) hovering above the region's lead crystal */
        ctx.auraRequests.push({ x: Mo.x, y: gy(Mo.x, Mo.z) + h * 0.48, z: Mo.z, size: h * 0.56, aspect: 1.35, ring: lead ? 0.72 : 0, ringW: 0.05, breakup: 0.75, tint: parseInt(String(gf).replace('#', ''), 16), spectral: 0.7, intensity: lead ? 0.28 : 0.16, pull: rad * 1.5, nightK: 1.5, phase: ri * 1.7 + mi * 0.6 }); }   /* M12 AURA: the class crystal monoliths carry the spectral language (one ringed halo for each region's tallest crystal, a soft bloom on the rest), in the one world aura draw */
    }); });
    Object.keys(CRY).forEach(function (k) { CRY[k].dispose(); });
    if (monoGeos.length) { var mg = mergeCrystal(monoGeos); monoMat = new THREE.MeshStandardMaterial({ vertexColors: true, roughness: 0.16, metalness: 0.6, envMapIntensity: 0.35, transparent: true, opacity: 0.93, emissive: 0xffffff, emissiveIntensity: 0.08 }); monoMat.onBeforeCompile = function (sh) { sh.uniforms.uWarmNight = WARM_NIGHT; sh.fragmentShader = sh.fragmentShader.replace('#include <common>', '#include <common>\nuniform float uWarmNight;').replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n\ttotalEmissiveRadiance = emissive * vColor.rgb * (1.0 + uWarmNight * step(vColor.b * 1.05 + 0.002, vColor.r));'); }; monoMat.customProgramCacheKey = function () { return 'mahworld_monolith'; }; applyCrystal(THREE, monoMat, { tier: tierQ(), soft: true, glow: CRYSTAL_GLOW, facet: 0.8, depth: 0.42, facetLight: 0.8, facetGlow: 0.7 });   /* M9 (audit V27: a flat blue plane at close range): the shared cut-crystal treatment (per-facet value, face-on depth, grazing rim, inclusions); M20: the soft crystal path (smooth columns: their vertical faces mirror the bright horizon, so the reflection is tinted — metalness 0.5 → 0.6, roughness 0.1 → 0.16 — the TITAN blue stays deep, never pale / washed; envMapIntensity is inert here: three r185 lights a material without its own envMap with scene.environmentIntensity). M20 review (mid range V04 / MX / CR: the columns read as flat, evenly saturated blue prisms — 'pencils'): the facet tone now also carries the sky reflection and the glow (facetLight / facetGlow), so the cut reads face to face at a distance */ own.push(monoMat); var mm = add(mg, monoMat, 'TERRAIN_MONOLITHS'); mm.frustumCulled = false;
      var ag = new THREE.BufferGeometry(); ag.setAttribute('position', new THREE.Float32BufferAttribute(apron.pos, 3)); ag.setAttribute('color', new THREE.Float32BufferAttribute(apron.col, 4)); ag.setIndex(apron.idx); var apMat = new THREE.MeshBasicMaterial({ vertexColors: true, transparent: true, depthWrite: false, fog: true, polygonOffset: true, polygonOffsetFactor: -2, polygonOffsetUnits: -2 }); own.push(apMat); add(ag, apMat, 'TERRAIN_MONOLITH_CONTACT', 1); }
    applyNight(night); log('terrain: ' + info.regions + ' regions (' + info.tint_sheets + ' tint sheets), paths ' + JSON.stringify(info.paths) + ', ' + info.shards + ' shards, ' + info.dust + ' dust points, ' + info.monoliths + ' monoliths, ' + info.draw_calls + ' draw calls, ' + info.tris + ' tris');
  }
  function mergeBoxes(list) { var pos = [], nrm = [], uv = []; list.forEach(function (g) { var ng = g.index ? g.toNonIndexed() : g; var p = ng.attributes.position, n = ng.attributes.normal, u = ng.attributes.uv; for (var i = 0; i < p.count; i++) { pos.push(p.getX(i), p.getY(i), p.getZ(i)); nrm.push(n.getX(i), n.getY(i), n.getZ(i)); uv.push(u ? u.getX(i) : 0, u ? u.getY(i) : 0); } }); var out = new THREE.BufferGeometry(); out.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); out.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3)); out.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2)); return out; }
  function mergeCrystal(list) { var pos = [], nrm = [], col = [], cry = [], idx = [], base = 0; list.forEach(function (g) { var p = g.attributes.position, n = g.attributes.normal, c = g.attributes.color, k = g.attributes.aCrys, ix = g.index; for (var i = 0; i < p.count; i++) { pos.push(p.getX(i), p.getY(i), p.getZ(i)); nrm.push(n.getX(i), n.getY(i), n.getZ(i)); col.push(c.getX(i), c.getY(i), c.getZ(i)); cry.push(k.getX(i), k.getY(i), k.getZ(i)); } for (i = 0; i < ix.count; i++) idx.push(ix.getX(i) + base); base += p.count; g.dispose(); }); var out = new THREE.BufferGeometry(); out.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3)); out.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3)); out.setAttribute('color', new THREE.Float32BufferAttribute(col, 3)); out.setAttribute('aCrys', new THREE.Float32BufferAttribute(cry, 3)); out.setIndex(idx); return out; }   /* M20: an indexed merge that keeps the soft crystals' analytic normals and aCrys (the old merge rebuilt flat normals) */
  function applyNight(n) { WARM_NIGHT.value = n ? 0.8 : 0; CRYSTAL_GLOW.value = n ? 0.38 : 0.15; if (seamMat) seamMat.color.setScalar(n ? 0.82 : 0.46); if (coreMat) { coreMat.emissiveIntensity = n ? 0.15 : 0.03; coreMat.metalness = n ? 0.3 : 0.12; coreMat.roughness = n ? 0.5 : 0.6; } if (shardMat) shardMat.emissiveIntensity = n ? 0.4 : 0.06; if (monoMat) monoMat.emissiveIntensity = n ? 0.32 : 0.08; }   /* M20: 0.5 → 0.32 at night — the smooth columns show far more lit face than the old octahedra (half their facets looked down), so the same glow read pale; the soft crystal light (tips, edges, core) carries the night */
  function tick(dt, t) { clock = (typeof t === 'number' && isFinite(t)) ? t : clock + (dt || 0); if (coreMat) coreMat.emissiveIntensity = (night ? 0.15 : 0.03) * (0.9 + 0.1 * Math.sin(clock * 0.9)); if (seamMat) seamMat.color.setScalar((night ? 0.82 : 0.46) * (0.9 + 0.1 * Math.sin(clock * 0.7))); }
  function setNight(n) { night = !!n; applyNight(night); }
  function dispose() { meshes.forEach(function (m) { if (m.parent) m.parent.remove(m); if (m.geometry) m.geometry.dispose(); }); meshes = []; own.forEach(function (o) { try { o.dispose(); } catch (e) { } }); own = []; if (group && group.parent) group.parent.remove(group); group = null; }
  function debug() { return { regions: info.regions, terraces: info.terraces || 0, forecourts: info.forecourts || 0, spurs: info.spurs || 0, tint_sheets: info.tint_sheets, tint_cells: info.tint_cells || 0, tint_overlaps_prevented: info.tint_overlaps_prevented || 0, tint_policy: 'SINGLE_SURFACE_SOFT_VERTEX_BLEND', paths: info.paths, road_gradients: info.road_gradients || null, shards: info.shards, dust: info.dust, monoliths: info.monoliths, draw_calls: info.draw_calls, tris: info.tris, night: night }; }
  /* region lookup for the other modules (wildlife habitats, the map) */
  function regionAt(x, z) { var RG = reg.regions && reg.regions.list || []; for (var i = 0; i < RG.length; i++) if (inRegion(x, z, RG[i])) return RG[i]; return null; }
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug, regionAt: regionAt, inRegion: inRegion, regionRects: regionRects };
}
