/* MAHWORLD JOB B :: WILDLIFE — the ambient creature ecology of the redirect (owner package 2026-09-19 §H): FISH (deep water beyond the
   beach ring: schools that cruise under the surface and BREACH), HORSE (the Prismatic Open Range: solitary, walk / trot / graze, never in
   a lane) and the GOLDEN PHOENIX (the aerial highlands near the flight ceiling: rare, a circuit over the crown spires with visits across
   the mainland). Everything is CLIENT-SIDE AMBIENT PRESENTATION driven by registry.ecology: bounded POOLS (figures are made once and
   re-used), no host state, no damage, no target lock, no collider, no payment UI (wild / pet metadata is data only — acquisition is an
   owner decision). The hostile Dogkie stays on the host (creatures.js).
   RIGS (measured, deploy/jobb/rig_view.mjs): the three Tripo exports have bones without node transforms; the horse and the phoenix are
   RIGID (every weight on the root bone), the fish is PARTIAL (fins + tail tip weighted, the body on a neutral bone). The fish's exported
   inverse-bind relationship already renders correctly in three.js; rebasing its zero-valued joint nodes explodes weighted vertices, so
   that source bind is preserved. Motion is root motion (position / heading / pitch / roll / bob) + a per-species VERTEX-SHADER deformation
   in model space (fish body undulation, horse tip-swing gait + head bob / graze, phoenix wing flap + tail). Mesh frames are measured from the geometry at load (the head end is
   the denser end of the long axis) and logged, never assumed.
   LOD: L0 / L1 / L2 derivatives share one skeleton per figure (like the Dogkie), switched by camera distance; nothing draws beyond
   visible_m. Draw calls: ≤ 12 fish + 2 horses + 1 phoenix + ≤ 6 splash pairs. No per-frame allocation. */
import { clone as skeletonClone } from '../../vendor/three/SkeletonUtils.js';
import { rebaseFromBind, classifyFish, makePoser } from './creatureRig.js';
import { createEntityStatus } from './entityStatus.js';

var G = 9.81, TWO_PI = Math.PI * 2;
function num(v, d) { return typeof v === 'number' && isFinite(v) ? v : d; }
function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }
function smooth(u) { u = clamp(u, 0, 1); return u * u * (3 - 2 * u); }
function wrapAngle(a) { return Math.atan2(Math.sin(a), Math.cos(a)); }
function nearSeg(px, pz, a, b, w) { var ax = a[0], az = a[1], bx = b[0], bz = b[1]; var dx = bx - ax, dz = bz - az; var l2 = dx * dx + dz * dz || 1; var t = clamp(((px - ax) * dx + (pz - az) * dz) / l2, 0, 1); return Math.hypot(px - (ax + dx * t), pz - (az + dz * t)) <= w; }
function findDerivative(reg, id) { var list = reg && reg.derivatives || []; for (var i = 0; i < list.length; i++) if (list[i] && list[i].id === id) return list[i]; return null; }

/* the mesh frame from the geometry: lateral = x (the symmetric axis), long axis = z, head = the denser z end (Tripo puts the detail there) */
function meshFrame(THREE, root) {
  var box = new THREE.Box3(); var np = 0, nn = 0; root.updateMatrixWorld(true);
  root.traverse(function (o) { if (o.isMesh && o.geometry && o.geometry.attributes.position) { if (!o.geometry.boundingBox) o.geometry.computeBoundingBox(); box.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld)); } });
  var size = box.getSize(new THREE.Vector3()); var z0 = box.min.z + size.z * 0.25, z1 = box.max.z - size.z * 0.25;
  root.traverse(function (o) { if (o.isMesh && o.geometry && o.geometry.attributes.position) { var p = o.geometry.attributes.position; var step = Math.max(1, Math.floor(p.count / 6000)); for (var i = 0; i < p.count; i += step) { var z = p.getZ(i); if (z > z1) np++; else if (z < z0) nn++; } } });
  return { box: box, size: size, fwdZ: np >= nn ? 1 : -1, head_verts: np, tail_verts: nn };
}

export function createWildlife(ctx) {
  var THREE = ctx.THREE, log = ctx.log || function () { }; var reg = ctx.registry || {}; var ECO = reg.ecology && reg.ecology.species || {}; var FAM = reg.crystal_families || {};
  var group = null, night = !!ctx.night, clock = 0, built = false; var SP = {}; var splashes = [], splashTex = null, ringMat = null, sprayMat = null; var stats = { fish: 0, horses: 0, phoenix: 0, breaches: 0, visits: 0, draw_calls: 0 };
  var setBone = makePoser(THREE);
  function tierK() { var T = null; try { T = ctx.quality && ctx.quality.get ? ctx.quality.get() : null; } catch (e) { T = null; } return T && T.lod_far_m > 0 ? Math.min(1, T.lod_far_m / 220) : 1; }   /* the quality tier scales the figure reach (LOW ×0.55 / MED ×0.77 / HIGH ×1) — STABILITY 2026-09-20 */
  var seaTest = function (x, z) { return ctx.seaTest ? ctx.seaTest(x, z) : false; }; var seaY = function () { return typeof ctx.seaY === 'number' ? ctx.seaY : -0.3; };
  function rnd(seed) { var s = (seed >>> 0) || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  var R = rnd(0xEC0);

  /* ---------- per-species vertex deformation (model space, after skinning) ---------- */
  var SHADER = {
    FISH: { uniforms: function () { return { uT: { value: 0 }, uPh: { value: 0 }, uAmp: { value: 0.09 }, uHz: { value: 1.4 }, uZ0: { value: 0 }, uZ1: { value: 1 }, uSwim: { value: 1 } }; },
      head: 'uniform float uT; uniform float uPh; uniform float uAmp; uniform float uHz; uniform float uZ0; uniform float uZ1; uniform float uSwim;',
      body: '{ float kz = clamp((uZ1 - transformed.z) / (uZ1 - uZ0), 0.0, 1.0); transformed.x += uAmp * uSwim * kz * kz * sin(uT * uHz * 6.2832 - kz * 2.8 + uPh); }' },
    /* owner B8 §8 (2026-09-20) — the horse FACE DUG INTO ITS NECK: inspected — the GLB is root-weighted (18 joints, every weight on the root, no clips), so the defect was OURS: the graze / snort pitch rotated a Y-masked region (everything above y 0.5 in the front half = the withers and the back too) about a pivot BEHIND the withers (z 0.14) by up to 0.55 rad, so the head arced back and down through the chest. Fixed at the source of the deformation: the region is the NECK + HEAD only (forward of the neck base z 0.18 → 0.34, above the chest y 0.36 → 0.5), the pivot is the neck base (z 0.22, y 0.56), the angle is capped at 0.42 rad. */
    HORSE: { uniforms: function () { return { uT: { value: 0 }, uPh: { value: 0 }, uGait: { value: 0 }, uGraze: { value: 0 }, uHy: { value: 0.42 }, uHead: { value: 0.5 } }; },
      head: 'uniform float uT; uniform float uPh; uniform float uGait; uniform float uGraze; uniform float uHy; uniform float uHead;',
      body: '{ float w = 1.0 - smoothstep(uHy - 0.3, uHy, transformed.y); float sg = transformed.z > 0.0 ? 1.0 : -1.0; float zc = sg * 0.24; float a = 0.34 * uGait * sg * sin(uPh) * w; float dz = transformed.z - zc, dy = transformed.y - uHy; float ca = cos(a), sa = sin(a); transformed.z = zc + dz * ca - dy * sa; transformed.y = uHy + dz * sa + dy * ca;\n  float hk = smoothstep(0.18, 0.34, transformed.z) * smoothstep(0.36, 0.5, transformed.y); float ga = -0.42 * uGraze * hk; float hz = 0.22, hy2 = 0.56; float dz2 = transformed.z - hz, dy2 = transformed.y - hy2; float cg = cos(ga), sgr = sin(ga); transformed.z = hz + dz2 * cg - dy2 * sgr; transformed.y = hy2 + dz2 * sgr + dy2 * cg + 0.012 * uGait * hk * sin(2.0 * uPh); }' },
    /* owner B8 §6: REAL flight language on a rigid-skinned bird (the GLB carries 26 joints, no clips, every weight on the root — inspected;
       so the wings move in the vertex shader about a hinge at the wing root): uStroke = the flap angle at the root (negative = downstroke),
       uTip = the tip lag / feather twist (the outer wing trails the root by a fraction of a cycle and pitches with the stroke), uSweep =
       the wings swept back along the body for a dive / pull-out, uSpread = tail spread. All driven per frame from the host state by
       updateFigure (cadence by speed, asymmetric down / up strokes, glide bouts, bank, climb, dive, recovery). */
    PHOENIX: { uniforms: function () { return { uT: { value: 0 }, uPh: { value: 0 }, uStroke: { value: 0.12 }, uTip: { value: 0 }, uSweep: { value: 0 }, uSpread: { value: 0 }, uHx: { value: 0.12 }, uHy: { value: 0.42 }, uSpan: { value: 0.49 } }; },
      head: 'uniform float uT; uniform float uPh; uniform float uStroke; uniform float uTip; uniform float uSweep; uniform float uSpread; uniform float uHx; uniform float uHy; uniform float uSpan;',
      body: '{ float ax = abs(transformed.x); if (ax > uHx) { float k = clamp((ax - uHx) / max(0.05, uSpan - uHx), 0.0, 1.0); float sg = transformed.x > 0.0 ? 1.0 : -1.0; float a = uStroke * (0.5 + 0.5 * k) + uTip * k * k; float dx = ax - uHx, dy = transformed.y - uHy; float ca = cos(a), sa = sin(a); float nx = uHx + dx * ca - dy * sa; float ny = uHy + dx * sa + dy * ca; float sw = uSweep * k; float cs = cos(sw), ss = sin(sw); float dz = transformed.z; float nx2 = uHx + (nx - uHx) * cs; float nz2 = dz - (nx - uHx) * ss; transformed.x = sg * nx2; transformed.y = ny + 0.06 * uTip * k * k; transformed.z = nz2; }\n  if (transformed.z < -0.2 && ax < 0.3) { float kt = clamp((-0.2 - transformed.z) / 0.25, 0.0, 1.0); transformed.y += 0.025 * kt * sin(uT * 2.2 + uPh); transformed.x *= 1.0 + 0.55 * uSpread * kt; } }' }
  };
  function injected(mat, sp, U) { var m = mat.clone(); m.envMapIntensity = 0.5; if (m.map) { m.emissiveMap = m.map; m.emissive = new THREE.Color(sp.glow || 0x3fb8ff); } m.emissiveIntensity = night ? (sp.nightGlow || 0.2) : (sp.dayGlow || 0); m.onBeforeCompile = function (sh) { Object.keys(U).forEach(function (k) { sh.uniforms[k] = U[k]; }); sh.vertexShader = sh.vertexShader.replace('#include <common>', '#include <common>\n' + SHADER[sp.id].head).replace('#include <skinning_vertex>', '#include <skinning_vertex>\n' + SHADER[sp.id].body); }; m.customProgramCacheKey = function () { return 'mahworld_wild_' + sp.id; }; m.needsUpdate = true; return m; }

  /* ---------- figures (pooled) ---------- */
  function makeFigure(sp, i) {
    var model = skeletonClone(sp.src.scene); var U = SHADER[sp.id].uniforms(); var mats = []; var sk0 = null; var bones = [];
    model.traverse(function (o) { if (o.isBone) bones.push(o); if (o.isMesh) { o.castShadow = false; o.receiveShadow = false; o.frustumCulled = true; if (o.isSkinnedMesh && !sk0) sk0 = o; if (Array.isArray(o.material)) o.material = o.material.map(function (m) { var k = injected(m, sp, U); mats.push(k); return k; }); else if (o.material) { var k2 = injected(o.material, sp, U); mats.push(k2); o.material = k2; } } });
    var lodMeshes = []; if (sk0) { lodMeshes.push(sk0); sp.lods.forEach(function (L) { var sm = new THREE.SkinnedMesh(L.geometry, (function () { var k = injected(L.material, sp, U); mats.push(k); return k; })()); sm.bindMode = sk0.bindMode; sm.bind(sk0.skeleton, sk0.bindMatrix); sm.position.copy(sk0.position); sm.quaternion.copy(sk0.quaternion); sm.scale.copy(sk0.scale); sm.frustumCulled = true; sm.visible = false; sm.name = sk0.name + '_L' + L.level; sk0.parent.add(sm); lodMeshes.push(sm); }); }
    var F = sp.frame; var pivot = new THREE.Group(); pivot.rotation.y = F.fwdZ > 0 ? Math.PI : 0;   /* the model's head (+z or −z) faces the client's −Z */ pivot.scale.setScalar(sp.scale); model.position.set(-(F.box.min.x + F.size.x / 2), sp.groundPivot ? -F.box.min.y : -(F.box.min.y + F.size.y / 2), -(F.box.min.z + F.size.z / 2)); pivot.add(model);
    var body = new THREE.Group(); body.add(pivot); var root = new THREE.Group(); root.name = sp.id + '_' + i; root.userData.noMerge = true; root.userData.wildlife = sp.id; root.visible = false; root.add(body); group.add(root);
    var fig = { id: sp.id + '_' + i, sp: sp, root: root, body: body, U: U, mats: mats, lodMeshes: lodMeshes, lod: 0, bones: bones, ph: R() * TWO_PI, active: false, x: 0, y: 0, z: 0, yaw: 0, pitch: 0, roll: 0, spd: 0, state: 'IDLE', t0: 0, data: {} }; root.visible = true;
    if (sp.id === 'FISH') { U.uZ0.value = F.box.min.z; U.uZ1.value = F.box.max.z; if (F.fwdZ < 0) { U.uZ0.value = F.box.max.z; U.uZ1.value = F.box.min.z; } }
    if (sp.id === 'HORSE') { U.uHy.value = F.box.min.y + F.size.y * 0.57; U.uHead.value = F.box.min.y + F.size.y * 0.66; }
    if (sp.id === 'PHOENIX') { U.uHx.value = F.size.x * 0.12; U.uHy.value = F.box.min.y + F.size.y * 0.57; U.uSpan.value = F.size.x / 2; }
    return fig;
  }
  function setLod(fig, d2) { var sp = fig.sp; if (fig.lodMeshes.length < 2) return; var lvl = d2 < sp.lod[0] * sp.lod[0] ? 0 : (d2 < sp.lod[1] * sp.lod[1] ? 1 : 2); if (lvl >= fig.lodMeshes.length) lvl = fig.lodMeshes.length - 1; if (lvl !== fig.lod) { for (var i = 0; i < fig.lodMeshes.length; i++) fig.lodMeshes[i].visible = i === lvl; fig.lod = lvl; } }
  function place(fig) { fig.root.position.set(fig.x, fig.y, fig.z); fig.root.rotation.set(0, fig.yaw, 0); fig.body.rotation.set(fig.pitch, 0, fig.roll); }

  /* ---------- splashes (pooled): an expanding foam ring on the surface + a rising spray sprite; ripple impulse into the sea body ---------- */
  function splashTexture() { var c = document.createElement('canvas'); c.width = 128; c.height = 128; var g = c.getContext('2d'); var gr = g.createRadialGradient(64, 64, 0, 64, 64, 64); gr.addColorStop(0, 'rgba(255,255,255,0.95)'); gr.addColorStop(0.4, 'rgba(240,248,255,0.55)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); g.fillStyle = gr; g.fillRect(0, 0, 128, 128); var t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; return t; }
  function makeSplashes(n) { splashTex = splashTexture(); ringMat = new THREE.MeshBasicMaterial({ color: 0xf4faff, transparent: true, opacity: 0.7, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide, fog: true }); sprayMat = new THREE.SpriteMaterial({ map: splashTex, color: 0xf4faff, transparent: true, opacity: 0.9, depthWrite: false, blending: THREE.AdditiveBlending, fog: true }); var rg = new THREE.RingGeometry(0.55, 1, 28); rg.rotateX(-Math.PI / 2);
    for (var i = 0; i < n; i++) { var ring = new THREE.Mesh(rg, ringMat.clone()); ring.visible = false; ring.renderOrder = 4; ring.userData.noMerge = true; var spray = new THREE.Sprite(sprayMat.clone()); spray.visible = false; spray.renderOrder = 5; group.add(ring); group.add(spray); splashes.push({ ring: ring, spray: spray, t0: -1, x: 0, z: 0, y: 0, a: 1 }); } }
  var splashI = 0; function splash(x, z, y, strength) { var s = splashes[splashI]; splashI = (splashI + 1) % splashes.length; s.t0 = clock; s.x = x; s.z = z; s.y = y; s.a = strength || 1; s.ring.visible = s.spray.visible = true; if (ctx.ripples && ctx.ripples.impulse) ctx.ripples.impulse(x, z, 0.55 * s.a, 1.6 * s.a); }
  function tickSplashes() { for (var i = 0; i < splashes.length; i++) { var s = splashes[i]; if (s.t0 < 0) continue; var u = (clock - s.t0) / 0.95; if (u >= 1) { s.t0 = -1; s.ring.visible = s.spray.visible = false; continue; } var k = s.a; s.ring.position.set(s.x, s.y + 0.03, s.z); var rs = (0.6 + 4.2 * smooth(u)) * k; s.ring.scale.set(rs, 1, rs); s.ring.material.opacity = 0.75 * (1 - u) * (1 - u); s.spray.position.set(s.x, s.y + 0.25 + 2.6 * u * (1 - u) * 2 * k, s.z); var ss = (0.9 + 2.2 * u) * k; s.spray.scale.set(ss, ss * 1.3, 1); s.spray.material.opacity = 0.9 * (1 - u); } }

  /* ---------- build ---------- */
  function loadSpecies(id, cfg, classify, groundPivot, glow) {
    var deriv = findDerivative(reg, cfg.derivative); var file = deriv && deriv.files && deriv.files.L0 && deriv.files.L0.runtime; if (!file) { log('wildlife ' + id + ': derivative ' + cfg.derivative + ' has no L0 — skipped'); return Promise.resolve(null); }
    return ctx.loadGlb(file).then(function (gltf) {
      var sp = { id: id, cfg: cfg, src: gltf, lods: [], figs: [], lod: cfg.lod_m || [30, 80], vis: num(cfg.visible_m, 260), groundPivot: groundPivot, glow: glow.color, dayGlow: glow.day, nightGlow: glow.night };
      /* The neutral raw/derivative proof confirms FISH is correct with its exported inverse bind matrices.
         Keep that bind and use shader undulation instead of mutating its partially weighted skeleton. */
      var sourceBind = id === 'FISH'; var rb = sourceBind ? { rebased: 0, skinned_meshes: 1, untouched: 1, reason: 'source inverse bind preserved' } : rebaseFromBind(THREE, gltf.scene);
      sp.frame = meshFrame(THREE, gltf.scene); var target = cfg.length_m ? cfg.length_m : (cfg.height_m || 1); sp.scale = target / (cfg.length_m ? sp.frame.size.z : sp.frame.size.y);
      sp.rig = !sourceBind && classify ? classify(THREE, gltf.scene, log) : null;
      log('wildlife ' + id + ': ' + cfg.derivative + ' L0 ready — rebase ' + JSON.stringify(rb) + ', mesh ' + sp.frame.size.x.toFixed(2) + '×' + sp.frame.size.y.toFixed(2) + '×' + sp.frame.size.z.toFixed(2) + ' m, head at ' + (sp.frame.fwdZ > 0 ? '+z' : '−z') + ' (' + sp.frame.head_verts + ' vs ' + sp.frame.tail_verts + ' verts), scale ' + sp.scale.toFixed(3) + (sp.rig ? '' : ', rigid (root-weighted) → shader deformation'));
      var lodJobs = ['L1', 'L2'].map(function (lv, li) { var f2 = deriv.files && deriv.files[lv] && deriv.files[lv].runtime; if (!f2) return Promise.resolve(); return ctx.loadGlb(f2).then(function (g2) { var sm2 = null; g2.scene.traverse(function (o) { if (o.isSkinnedMesh && !sm2) sm2 = o; }); if (!sm2) return; sp.lods.push({ level: li + 1, geometry: sm2.geometry, material: sm2.material }); sp.lods.sort(function (a, b) { return a.level - b.level; }); }).catch(function (e) { log('wildlife ' + id + ': ' + lv + ' failed (' + (e && e.message || e) + ')'); }); });
      return Promise.all(lodJobs).then(function () { return sp; });
    }).catch(function (e) { log('wildlife ' + id + ': load FAILED (' + (e && e.message || e) + ')'); return null; });
  }

  /* ---------- owner B7 §9 (2026-09-20): FISH POPULATION LOD — "way more visible fish" without more host rigs ----------
     NEAR / COMBAT = the host entities above (full rig, targetable, breach / hover / swirl / launch). MID = cheap client SCHOOL AGENTS:
     one InstancedMesh of a flat sapphire fish silhouette (8 tris each), each agent cruising an ellipse inside its water body under the
     surface with a tail wiggle, every so often one BREACHES (an arc through the surface with the established splash + ripple impulse at
     exit and re-entry). FAR / DEEP = a second InstancedMesh of small dark silhouettes scattered in the deep sea ring (static drift) plus
     occasional far surface events. Population from registry ecology.FISH.population_lod, scaled by the quality tier (LOW ×0.5 / MED
     ×0.75); agents beyond the reach are not updated. Ambient only: no host state, no damage, no target lock, no collider. Draw calls: 2. */
  var POP = { own: [], agents: [], schools: [], farItems: [], midMesh: null, farMesh: null, reach: 260, breaches: 0, built: false };
  function popTier() { var t = 1; try { var q = ctx.quality && ctx.quality.tier ? String(ctx.quality.tier()).toUpperCase() : 'HIGH'; t = q === 'LOW' ? 0.5 : (q === 'MED' ? 0.75 : 1); } catch (e) { } return t; }
  function fishSilhouette() { var g = new THREE.OctahedronGeometry(1, 0); g.scale(0.16, 0.24, 0.5);   /* nose +z: a slim lens, the tail at −z */ var pos = g.attributes.position; for (var i = 0; i < pos.count; i++) { var z = pos.getZ(i); if (z < -0.2) { pos.setY(i, pos.getY(i) * 1.9); pos.setX(i, pos.getX(i) * 0.5); } } g.computeVertexNormals(); return g; }
  function seaAnchor(bearing, out_m) { var cx = 0, cz = 118; var ux = Math.sin(bearing), uz = Math.cos(bearing); var r = 120, hit = -1; for (var k = 0; k < 90; k++) { r += 6; if (seaTest(cx + ux * r, cz + uz * r)) { hit = r; break; } } if (hit < 0) return null; return { x: cx + ux * (hit + out_m), z: cz + uz * (hit + out_m) }; }
  function buildPopulation() {
    var L = (ECO.FISH && ECO.FISH.population_lod) || null; if (!L) { log('wildlife: no population_lod data — the host fish only'); return; } var k = popTier(); var r0 = rnd(0xF15B7);
    var bodies = (ECO.FISH.habitat && ECO.FISH.habitat.bodies) || []; var sy = seaY();
    /* MID schools: every pond / canal + sea schools around the coast */
    bodies.forEach(function (b, bi) { var canal = (b.rx || 6) > 12; var n = Math.max(2, Math.round((canal ? (L.mid.per_canal || 16) : (L.mid.per_pond || 9)) * k)); POP.schools.push({ id: b.id, x: b.x, z: b.z, rx: (b.rx || 6) * 0.82, rz: (b.rz || 6) * 0.82, sy: b.surface_y !== undefined ? b.surface_y : sy, depth: canal ? 0.06 : 0.04, n: n, nextBreach: clock + 3 + r0() * 9, pond: true }); });
    var nSea = Math.max(2, Math.round((L.mid.sea_schools || 14) * k)); for (var i = 0; i < nSea; i++) { var a = seaAnchor(i / nSea * TWO_PI + r0() * 0.3, 18 + r0() * 38); if (!a) continue; POP.schools.push({ id: 'SEA_' + i, x: a.x, z: a.z, rx: 9 + r0() * 14, rz: 7 + r0() * 10, sy: sy, depth: 0.05 + r0() * 0.04, n: Math.max(3, Math.round((L.mid.per_sea_school || 10) * k)), nextBreach: clock + 4 + r0() * 12, pond: false }); }
    var total = 0; POP.schools.forEach(function (S) { total += S.n; }); if (!total) return;
    var geo = fishSilhouette(); var tint = new THREE.Color(ECO.FISH.look && ECO.FISH.look.body || '#3f79c8'); var mat = new THREE.MeshStandardMaterial({ color: tint, roughness: 0.35, metalness: 0.55, emissive: new THREE.Color('#5fc8ff'), emissiveIntensity: night ? 0.35 : (L.mid.surface_glow_day !== undefined ? L.mid.surface_glow_day : 0.08), flatShading: true });   /* B8 §5: a faint crystalline self-light by day so the shoal reads on the dark water */ POP.own.push(mat, geo);
    var mesh = new THREE.InstancedMesh(geo, mat, total); mesh.name = 'FISH_SCHOOL_AGENTS'; mesh.frustumCulled = false; mesh.userData.noMerge = true; mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage); group.add(mesh); POP.midMesh = mesh;
    var idx = 0; POP.schools.forEach(function (S, si) { for (var j = 0; j < S.n; j++) { var sz = (L.mid.size_m ? L.mid.size_m[0] : 0.7) + r0() * ((L.mid.size_m ? L.mid.size_m[1] : 1.3) - (L.mid.size_m ? L.mid.size_m[0] : 0.7)); POP.agents.push({ i: idx++, S: S, th: r0() * TWO_PI, w: (0.12 + r0() * 0.12) * (r0() < 0.5 ? 1 : -1), ra: 0.35 + r0() * 0.6, ph: r0() * TWO_PI, sz: sz, dz: 0.6 + r0() * 0.8, breach: null, x: S.x, y: S.sy - S.depth, z: S.z }); } });
    /* FAR: deep-water silhouettes, static drift */
    var nFar = Math.round((L.far.sea_silhouettes || 120) * k); if (nFar > 0) { var fgeo = fishSilhouette(); var fmat = new THREE.MeshBasicMaterial({ color: new THREE.Color('#1c355c'), transparent: true, opacity: 0.8, depthWrite: false, fog: true }); POP.own.push(fmat, fgeo); var fm = new THREE.InstancedMesh(fgeo, fmat, nFar); fm.name = 'FISH_FAR_SILHOUETTES'; fm.frustumCulled = false; fm.userData.noMerge = true; fm.instanceMatrix.setUsage(THREE.DynamicDrawUsage); group.add(fm); POP.farMesh = fm; var placed = 0, tries = 0; while (placed < nFar && tries < nFar * 12) { tries++; var a2 = seaAnchor(r0() * TWO_PI, 50 + r0() * 90); if (!a2) continue; POP.farItems.push({ i: placed++, x: a2.x, z: a2.z, y: sy - 0.02, yaw: r0() * TWO_PI, ph: r0() * TWO_PI, sz: 0.9 + r0() * 1.4 }); } for (var f2 = 0; f2 < POP.farItems.length; f2++) writeAgent(fm, POP.farItems[f2].i, POP.farItems[f2].x, POP.farItems[f2].y, POP.farItems[f2].z, POP.farItems[f2].yaw, 0, POP.farItems[f2].sz); fm.instanceMatrix.needsUpdate = true; }
    POP.reach = num(ECO.FISH.visible_m, 260) * tierK(); POP.built = true; log('wildlife: population LOD — ' + POP.schools.length + ' mid schools / ' + POP.agents.length + ' agents (' + bodies.length + ' bodies + ' + nSea + ' sea schools), ' + POP.farItems.length + ' far silhouettes (tier ×' + k + ')');
  }
  var _pm = new THREE.Matrix4(), _pq = new THREE.Quaternion(), _pe = new THREE.Euler(), _pv = new THREE.Vector3(), _ps = new THREE.Vector3();
  function writeAgent(mesh, i, x, y, z, yaw, pitch, sz) { _pv.set(x, y, z); _pe.set(pitch, yaw, 0); _pq.setFromEuler(_pe); _ps.set(sz, sz, sz); _pm.compose(_pv, _pq, _ps); mesh.setMatrixAt(i, _pm); }
  function tickPopulation(dt) {
    if (!POP.built || !POP.midMesh) return; var cam = ctx.cameraPos(); var R2 = POP.reach * POP.reach; var any = false;
    for (var s2 = 0; s2 < POP.schools.length; s2++) { var S = POP.schools[s2]; var dxs = S.x - cam.x, dzs = S.z - cam.z; S.near = dxs * dxs + dzs * dzs < R2; if (S.near && clock >= S.nextBreach) { var LB = (ECO.FISH && ECO.FISH.population_lod) || {}; var BE = (LB.mid && LB.mid.breach_every_s) || [7, 16]; S.nextBreach = clock + BE[0] + (BE[1] - BE[0]) * Math.random(); var cand = POP.agents.filter(function (ag) { return ag.S === S && !ag.breach; }); if (cand.length) { var ag0 = cand[Math.floor(Math.random() * cand.length)]; ag0.breach = { t0: clock, dur: 0.85, h: S.pond ? 1.4 : 2.2, splashed: false }; splash(ag0.x, ag0.z, S.sy, S.pond ? 0.6 : 0.9); POP.breaches++; } } }
    for (var i = 0; i < POP.agents.length; i++) { var ag = POP.agents[i]; var Sg = ag.S; if (!Sg.near) continue; any = true;
      ag.th += ag.w * dt; var cx = Sg.x + Math.cos(ag.th) * Sg.rx * ag.ra, cz = Sg.z + Math.sin(ag.th) * Sg.rz * ag.ra; var tx = -Math.sin(ag.th) * Sg.rx * ag.ra * ag.w, tz = Math.cos(ag.th) * Sg.rz * ag.ra * ag.w;   /* the tangent = the heading */ var yaw = Math.atan2(tx, tz); var y = Sg.sy - Sg.depth * ag.dz + 0.05 * Math.sin(clock * 0.9 + ag.ph);   /* the water reads opaque from the bank: the agents cruise AT the surface (backs and fins breaking it, a cruising shoal), never as invisible shadows below */ var pitch = 0; var wig = 0.18 * Math.sin(clock * 5.5 + ag.ph);
      if (ag.breach) { var u = (clock - ag.breach.t0) / ag.breach.dur; if (u >= 1) { ag.breach = null; splash(ag.x, ag.z, Sg.sy, Sg.pond ? 0.5 : 0.8); } else { y = Sg.sy - 0.1 + ag.breach.h * 4 * u * (1 - u); pitch = -(1 - 2 * u) * 0.9; wig = 0; } }
      ag.x = cx; ag.z = cz; ag.y = y; writeAgent(POP.midMesh, ag.i, cx, y, cz, yaw + wig, pitch, ag.sz); }
    if (any) POP.midMesh.instanceMatrix.needsUpdate = true;
  }
  function build() {
    if (built) return; built = true; if (!Object.keys(ECO).length) { log('wildlife: registry.ecology missing — inert'); return; }
    group = new THREE.Group(); group.name = 'MAHWORLD_WILDLIFE'; group.userData.noMerge = true; ctx.group.add(group); makeSplashes(6); try { buildPopulation(); } catch (e) { POP.error = String(e && e.stack || e).slice(0, 300); log('wildlife: population LOD failed ' + (e && e.message || e)); }
    var jobs = [];
    if (ECO.FISH) jobs.push(loadSpecies('FISH', ECO.FISH, classifyFish, false, { color: 0x6fd3ff, day: 0.04, night: 0.3 }).then(function (sp) { if (!sp) return; SP.FISH = sp; sp.hz = num(sp.cfg.motion && sp.cfg.motion.undulation_hz, 1.4); sp.tagLift = 0.9; sp.glowAttack = new THREE.Color(sp.cfg.combat && sp.cfg.combat.aura_attack || '#b8f0ff').getHex(); }));
    if (ECO.HORSE) jobs.push(loadSpecies('HORSE', ECO.HORSE, null, true, { color: 0xff6a7a, day: 0.03, night: 0.25 }).then(function (sp) { if (!sp) return; SP.HORSE = sp; sp.tagLift = 2.1; sp.glowAttack = new THREE.Color(sp.cfg.combat && sp.cfg.combat.aura_attack || '#ffb0b8').getHex(); }));
    if (ECO.PHOENIX) jobs.push(loadSpecies('PHOENIX', ECO.PHOENIX, null, false, { color: new THREE.Color(ECO.PHOENIX.look && ECO.PHOENIX.look.rim || '#ffd27a').getHex(), day: 0.12, night: num(ECO.PHOENIX.look && ECO.PHOENIX.look.night_glow, 0.55) }).then(function (sp) { if (!sp) return; SP.PHOENIX = sp; sp.flapHz = num(sp.cfg.motion && sp.cfg.motion.flap_hz, 1.1); sp.tagLift = 1.6; sp.glowAttack = new THREE.Color(sp.cfg.combat && sp.cfg.combat.aura_attack || '#fff0b0').getHex(); }));
    return Promise.all(jobs).then(function () { log('wildlife ready: ' + Object.keys(SP).join(', ') + ' — figures follow p.wildlife (host authority; payment UI: none — wild / pet metadata only)'); });
  }
  /* ---------- HOST-DRIVEN presentation (owner next-pass 2026-09-20): p.wildlife = the WildlifeManager's records; figures are pooled per id ---------- */
  var LAG_S = 0.12, SAMPLES = 8, CLOCK_FILTER = 0.15; var lastP = null, lastHT = null, curHT = 0, clockOff = null; var gen = 0; var byId = {}; var allFigs = [];
  var ATTACK_STATES = { SWIRL: 1, LAUNCH: 1, WINDUP: 1, DIVE: 1, AERIAL_PASS: 0.8, SNORT: 1, FEINT: 1, RISE: 0.5, RECOVER: 0.5, CLIMB: 0.3, HIT: 0.4 };
  var STATUS = createEntityStatus(THREE, { width_m: 1.2 }); var lockedId = null;   /* owner B7 §3: the shared overhead status (NAME · LV · HP) — always on for the active figures in view, not only while damaged */
  function nowS() { return (typeof performance !== 'undefined' && performance.now ? performance.now() : Date.now()) / 1000; }
  function hostTime(p) { var v = p.host_t; if (typeof v !== 'number' || !isFinite(v)) v = p.t; return typeof v === 'number' && isFinite(v) ? v : null; }
  function makeBuf() { var s = []; for (var i = 0; i < SAMPLES; i++) s.push({ t: 0, x: 0, y: 0, z: 0, f: 0 }); return { s: s, n: 0 }; }
  function pushSample(b, ht, x, y, z, f) { var s = b.s; if (b.n === s.length) { for (var i = 1; i < s.length; i++) { var a = s[i - 1], q = s[i]; a.t = q.t; a.x = q.x; a.y = q.y; a.z = q.z; a.f = q.f; } b.n--; } var o = s[b.n++]; o.t = ht; o.x = x; o.y = y; o.z = z; o.f = f; }
  var SAMP = { x: 0, y: 0, z: 0, f: 0 };
  function sampleAt(b, rt, out) { var s = b.s, n = b.n; if (!n) return false; var A, B; if (n === 1 || rt >= s[n - 1].t) { A = s[n - 1]; out.x = A.x; out.y = A.y; out.z = A.z; out.f = A.f; return true; } if (rt <= s[0].t) { A = s[0]; out.x = A.x; out.y = A.y; out.z = A.z; out.f = A.f; return true; } for (var i = n - 2; i >= 0; i--) { if (rt >= s[i].t) { A = s[i]; B = s[i + 1]; var u = (rt - A.t) / Math.max(1e-6, B.t - A.t); out.x = A.x + (B.x - A.x) * u; out.y = A.y + (B.y - A.y) * u; out.z = A.z + (B.z - A.z) * u; out.f = A.f + wrapAngle(B.f - A.f) * u; return true; } } A = s[0]; out.x = A.x; out.y = A.y; out.z = A.z; out.f = A.f; return true; }
  function rr(g, x, y, w, h, r) { g.beginPath(); g.moveTo(x + r, y); g.lineTo(x + w - r, y); g.quadraticCurveTo(x + w, y, x + w, y + r); g.lineTo(x + w, y + h - r); g.quadraticCurveTo(x + w, y + h, x + w - r, y + h); g.lineTo(x + r, y + h); g.quadraticCurveTo(x, y + h, x, y + h - r); g.lineTo(x, y + r); g.quadraticCurveTo(x, y, x + r, y); g.closePath(); }
  function figureFor(rec) { var sp = SP[rec.species]; if (!sp) return null; var f = byId[rec.id]; if (f) return f; f = makeFigure(sp, rec.id); f.id = rec.id; f.buf = makeBuf(); f.snap = true; f.prevState = null; f.prevY = null; f.vy = 0; f.yawRate = 0; f.lastYaw = 0; f.aura = 0; f.hitFlash = 0; f.opacity = 1; f.lastHitAgo = 99;
    var status = STATUS.make({ name: sp.id, level: Number.isFinite(sp.cfg.level) ? sp.cfg.level : 1, hp: 1, max: 1, tint: sp.cfg.combat && sp.cfg.combat.aura || '#4fd8ff', hostile: !!(sp.cfg.combat && sp.cfg.combat.hits_to_kill_player) }); if (status) { status.sprite.position.y = sp.tagLift; status.sprite.visible = false; f.root.add(status.sprite); } f.status = status;
    byId[rec.id] = f; allFigs.push(f); return f; }
  function removeFigure(f) { if (f.status) { STATUS.dispose(f.status); f.status = null; } if (f.root.parent) f.root.parent.remove(f.root); f.root.traverse(function (o) { if (o.isSkinnedMesh && o.skeleton && o.skeleton.dispose) o.skeleton.dispose(); }); for (var i = 0; i < f.mats.length; i++) { try { f.mats[i].dispose(); } catch (e) { } } delete byId[f.id]; }
  function setOpacity(f, op) { for (var i = 0; i < f.mats.length; i++) { var m = f.mats[i]; m.opacity = op; m.transparent = op < 0.999; } f.opacity = op; }
  function updateFigure(f, rec, isNew, dt, t, cam, rt) {
    var sp = f.sp; var U = f.U; var x = num(rec.position.x, 0), z = num(rec.position.z, 0), y = num(rec.y, 0), fc = num(rec.facing, 0); var st = rec.state || 'IDLE';
    if (isNew) { var b = f.buf; var last = b.n ? b.s[b.n - 1] : null; if (last && (Math.abs(last.x - x) + Math.abs(last.z - z) > 8)) { b.n = 0; last = null; f.snap = true; } if (!last || curHT > last.t + 1e-6) pushSample(b, curHT, x, y, z, fc); }
    var px = x, py = y, pz = z, pf = fc; if (sampleAt(f.buf, rt, SAMP)) { px = SAMP.x; py = SAMP.y; pz = SAMP.z; pf = SAMP.f; }
    var yawT = -pf; if (f.snap) { f.x = px; f.y = py; f.z = pz; f.yaw = yawT; f.vy = 0; f.yawRate = 0; f.snap = false; } else { var dyaw = wrapAngle(yawT - f.yaw); f.yawRate += (dyaw / Math.max(1e-3, dt) - f.yawRate) * Math.min(1, dt * 6); f.yaw += dyaw * Math.min(1, dt * 8); f.vy += (((py - f.y) / Math.max(1e-3, dt)) - f.vy) * Math.min(1, dt * 6); f.x = px; f.y = py; f.z = pz; }
    var spd = num(rec.speed_mps, 0); var attackW = ATTACK_STATES[st] || 0; var hitAgo = num(rec.hit_ago_s, 99); if (hitAgo < f.lastHitAgo - 1e-3 && hitAgo < 0.3) f.hitFlash = 1; f.lastHitAgo = hitAgo; f.hitFlash = Math.max(0, f.hitFlash - dt * 3);
    /* species pose */
    if (sp.id === 'FISH') { var swim = st === 'SWIM' || st === 'RETURN' ? 1 : (st === 'LAUNCH' ? 1.6 : (st === 'BREACH' || st === 'DIVE' ? 0.35 : 0.9)); U.uSwim.value += (swim - U.uSwim.value) * Math.min(1, dt * 4); U.uHz.value = sp.hz * (0.7 + 0.5 * Math.min(1.6, spd / 1.6)); f.pitch += ((-Math.atan2(f.vy, Math.max(1.5, spd))) - f.pitch) * Math.min(1, dt * 5); f.roll += ((0.18 * Math.sin(t * 0.9 + f.ph) - 0.6 * clamp(f.yawRate, -1, 1) * (st === 'SWIRL' ? 1 : 0.3)) - f.roll) * Math.min(1, dt * 4);
      if (sp.rig) { var fl = Math.sin(t * 5.5 + f.ph); for (var q = 0; q < sp.rig.fins.length; q++) { var fn = sp.rig.fins[q]; var sgn = fn.side === 'L' ? 1 : -1; for (var b2 = 0; b2 < fn.specs.length; b2++) { var spc = fn.specs[b2]; setBone(f.bones[sp.rig.bones.indexOf(spc.bone)], spc, 0.22 * fl * sgn, 0, 0.1 * fl); } } var n = sp.rig.spine.length; for (var b3 = Math.max(0, n - 2); b3 < n; b3++) { var sp3 = sp.rig.spine[b3]; setBone(f.bones[sp.rig.bones.indexOf(sp3.bone)], sp3, 0, 0.45 * Math.sin(t * U.uHz.value * TWO_PI - 2.8 + f.ph) * U.uSwim.value, 0); } }
      /* splashes at the surface crossings (exit + re-entry), both scenery and fight breaches */ var sy = typeof rec.surface_y === 'number' ? rec.surface_y : seaY(); if (f.prevY !== null) { if (f.prevY < sy && py >= sy) splash(px, pz, sy, 1); else if (f.prevY >= sy && py < sy && (st === 'DIVE' || st === 'RETURN' || st === 'KO')) splash(px, pz, sy, 0.8); } f.prevY = py; }
    else if (sp.id === 'HORSE') { var gait = spd > 0.2 ? Math.min(1, spd / 1.3) : 0; U.uGait.value += (gait - U.uGait.value) * Math.min(1, dt * 3); var graze = st === 'GRAZE' ? 1 : (st === 'SNORT' ? -0.45 : 0); U.uGraze.value += (graze - U.uGraze.value) * Math.min(1, dt * 1.8); var hz = 0.9 + 1.3 * Math.min(1.6, spd / 1.3); f.ph += TWO_PI * hz * dt * U.uGait.value; U.uPh.value = f.ph; var lift = st === 'FEINT' ? -0.12 : (st === 'SNORT' ? -0.08 : 0); f.pitch += ((0.03 * Math.sin(2 * f.ph) * U.uGait.value - 0.02 * Math.max(0, U.uGraze.value) + lift - 0.25 * f.hitFlash) - f.pitch) * Math.min(1, dt * 6); f.roll += ((-0.05 * clamp(f.yawRate, -2, 2)) - f.roll) * Math.min(1, dt * 4); f.y += 0.06 * Math.abs(Math.sin(f.ph)) * U.uGait.value; }
    else { /* B8 §6 flight language: power + cadence by state and speed; a GLIDE bout every 6–11 s in cruise (3–5 s, wings held in a dihedral
      with a faint tremor); the stroke is ASYMMETRIC (a fast deep downstroke, a slower recovery); the tip lags the root; a DIVE sweeps the wings back and the
      pull-out (CLIMB right after a dive) is a burst of deep strokes; AERIAL_PASS = shallow fast beats; WINDUP hover = deep slow beats (rare, motivated) */
      var power = st === 'WINDUP' ? 1.0 : (st === 'DIVE' ? 0 : (st === 'CLIMB' ? 1.0 : (st === 'AERIAL_PASS' ? 0.6 : 0.75))); var cad = st === 'WINDUP' ? 1.6 : (st === 'CLIMB' ? 1.9 : (st === 'AERIAL_PASS' ? 2.4 : 0.9 + Math.min(1.2, spd / 10)));
      if (st === 'PATROL' || st === 'TRAVEL') { if (f.glideUntil === undefined) { f.glideUntil = 0; f.glideNext = t + 4 + 6 * Math.random(); } if (t >= f.glideNext && t > f.glideUntil) { f.glideUntil = t + 3 + 2 * Math.random(); f.glideNext = f.glideUntil + 6 + 5 * Math.random(); } if (t < f.glideUntil) power = 0.06; }
      if (st === 'CLIMB' && f.prevState === 'DIVE') f.burstUntil = t + 1.4; if (f.burstUntil && t < f.burstUntil) { power = 1.15; cad = 2.2; }
      f.flapW = f.flapW === undefined ? power : f.flapW + (power - f.flapW) * Math.min(1, dt * 2.2); f.ph += TWO_PI * sp.flapHz * cad * dt; var cyc = (f.ph / TWO_PI) % 1; var wave = cyc < 0.38 ? -Math.sin(cyc / 0.38 * Math.PI) : Math.sin((cyc - 0.38) / 0.62 * Math.PI);   /* −1 at mid-downstroke (fast), +1 at mid-upstroke (slow) */
      var glideHold = 0.2 + 0.03 * Math.sin(t * 3.1 + f.ph * 0.1); var strokeAmp = 0.62 * f.flapW; var stroke = st === 'DIVE' ? -0.42 : glideHold * (1 - f.flapW) + strokeAmp * wave; U.uStroke.value = stroke; var tipLag = cyc < 0.38 ? -Math.sin(Math.max(0, cyc - 0.08) / 0.38 * Math.PI) : Math.sin(Math.max(0, cyc - 0.46) / 0.62 * Math.PI); U.uTip.value = 0.3 * f.flapW * (tipLag - wave) + (st === 'DIVE' ? -0.12 : 0);
      var sweepT = st === 'DIVE' ? 0.95 : (f.burstUntil && t < f.burstUntil ? 0.15 : 0); f.sweep = f.sweep === undefined ? sweepT : f.sweep + (sweepT - f.sweep) * Math.min(1, dt * 3); U.uSweep.value = f.sweep; U.uSpread.value = st === 'WINDUP' || (f.burstUntil && t < f.burstUntil) ? 1 : (st === 'DIVE' ? -0.4 : 0.25);
      f.pitch += ((-Math.atan2(f.vy, Math.max(4, spd)) * 1.15 + (st === 'WINDUP' ? -0.25 : 0)) - f.pitch) * Math.min(1, dt * 2.5); f.roll += ((-clamp(f.yawRate * 2.1, -0.9, 0.9)) - f.roll) * Math.min(1, dt * 2.2); }
    U.uT.value = t; if (sp.id !== 'HORSE') U.uPh.value = f.ph;
    /* aura: restrained idle, strong in the wind-up / attack states, a white flash when struck */ var auraT = (night ? 0.12 : 0.04) + 0.55 * attackW + 0.9 * f.hitFlash; f.aura += (auraT - f.aura) * Math.min(1, dt * 6); for (var m = 0; m < f.mats.length; m++) { var mat = f.mats[m]; mat.emissiveIntensity = f.aura; if (attackW > 0.6 || f.hitFlash > 0.5) mat.emissive.set(f.hitFlash > 0.5 ? 0xffffff : (rec.aura_attack || sp.glowAttack || 0xffffff)); else mat.emissive.set(rec.aura || sp.glow); }
    /* KO: dissolve — fade, shrink, sink (the host removes the record after its dissolve window) */ var koAgo = rec.ko ? num(rec.ko_ago_s, 0) : null; if (koAgo !== null) { var kq = clamp(koAgo / 2.4, 0, 1); setOpacity(f, 1 - kq); f.root.scale.setScalar(Math.max(0.05, 1 - 0.5 * kq)); f.y -= 0.4 * kq; f.pitch += (0.5 - f.pitch) * Math.min(1, dt * 3); } else if (f.opacity < 1) { setOpacity(f, 1); f.root.scale.setScalar(1); }
    place(f);
    /* overhead status (owner B7 §3): NAME · LV · HP for every active figure in view — distance fade, hidden through the KO dissolve, LOCKED when the player's lock is on it; the sprite sits above the figure whatever the KO shrink */
    if (f.status) { var mx = num(rec.max, 0), hp = num(rec.hp, mx); var kq2 = rec.ko ? clamp(num(rec.ko_ago_s, 0) / 2.4, 0, 1) : 0; var dS = Math.sqrt((f.x - cam.x) * (f.x - cam.x) + (f.y - cam.y) * (f.y - cam.y) + (f.z - cam.z) * (f.z - cam.z)); STATUS.update(f.status, { name: rec.name || sp.id, level: Number.isFinite(rec.level) ? rec.level : (Number.isFinite(sp.cfg.level) ? sp.cfg.level : 1), hp: hp, max: mx, ko: !!rec.ko, locked: lockedId === rec.id }, (f.root.visible && kq2 < 0.35) ? dS : 1e9); if (f.status.sprite.visible) { f.status.sprite.position.y = sp.tagLift / Math.max(0.05, f.root.scale.x); stats.tags = (stats.tags || 0) + 1; } }
    f.state = st; f.prevState = st;
  }
  function tick(dt, t) {
    clock = (typeof t === 'number' && isFinite(t)) ? t : clock + (dt || 0); dt = Math.min(0.1, Math.max(0, num(dt, 0))); if (!group) return; try { tickPopulation(dt); } catch (e) { } if (!Object.keys(SP).length) { tickSplashes(); return; } var p = ctx.snapshot(); var list = p && p.wildlife;
    if (!list || !list.length) { if (allFigs.length) { for (var r = allFigs.length - 1; r >= 0; r--) { removeFigure(allFigs[r]); } allFigs.length = 0; } tickSplashes(); stats.draw_calls = 0; return; }
    var wall = nowS(); var ht = hostTime(p); var isNew = p !== lastP || (ht !== null && ht !== lastHT);
    if (isNew) { lastP = p; var HT = ht === null ? wall : ht; var o = HT - wall; if (lastHT !== null && HT < lastHT - 1e-6) { for (var r2 = 0; r2 < allFigs.length; r2++) { allFigs[r2].buf.n = 0; allFigs[r2].snap = true; } clockOff = o; } else clockOff = clockOff === null ? o : clockOff + (o - clockOff) * CLOCK_FILTER; lastHT = HT; curHT = HT; }
    var rt = wall + (clockOff === null ? 0 : clockOff) - LAG_S; var cam = ctx.cameraPos(); gen++; var dc = 0; stats.tags = 0; lockedId = (p.rules && p.rules.me && p.rules.me.lock) ? p.rules.me.lock.target : null;
    for (var i = 0; i < list.length; i++) { var rec = list[i]; if (!rec || !rec.id || !rec.position) continue; var f = figureFor(rec); if (!f) continue; f.gen = gen; var sp = f.sp; var dx = rec.position.x - cam.x, dy = num(rec.y, 0) - cam.y, dz = rec.position.z - cam.z; var d2 = dx * dx + dy * dy + dz * dz; var visR = sp.vis * tierK(); var vis = d2 < visR * visR; f.root.visible = vis; f.active = true; if (vis) { setLod(f, d2); dc++; } updateFigure(f, rec, isNew, dt, clock, cam, rt); }
    for (var k = allFigs.length - 1; k >= 0; k--) if (allFigs[k].gen !== gen) { removeFigure(allFigs[k]); allFigs.splice(k, 1); }
    tickSplashes(); stats.draw_calls = dc; stats.fish = list.filter(function (x) { return x.species === 'FISH'; }).length; stats.horses = list.filter(function (x) { return x.species === 'HORSE'; }).length; stats.phoenix = list.filter(function (x) { return x.species === 'PHOENIX'; }).length;
  }
  function setNight(n) { night = !!n; if (POP.midMesh) { var LG = (ECO.FISH && ECO.FISH.population_lod && ECO.FISH.population_lod.mid) || {}; POP.midMesh.material.emissiveIntensity = night ? 0.35 : (LG.surface_glow_day !== undefined ? LG.surface_glow_day : 0.08); } }
  function dispose() { for (var r = allFigs.length - 1; r >= 0; r--) removeFigure(allFigs[r]); allFigs.length = 0; SP = {}; if (POP.midMesh && POP.midMesh.parent) POP.midMesh.parent.remove(POP.midMesh); if (POP.farMesh && POP.farMesh.parent) POP.farMesh.parent.remove(POP.farMesh); POP.own.forEach(function (o) { try { o.dispose(); } catch (e) { } }); POP.own = []; POP.agents = []; POP.schools = []; POP.farItems = []; POP.midMesh = POP.farMesh = null; POP.built = false; splashes.forEach(function (s) { group.remove(s.ring); group.remove(s.spray); }); splashes = []; if (splashTex) splashTex.dispose(); if (group && group.parent) group.parent.remove(group); group = null; }
  function debug() { var d = { authority: 'HOST (p.wildlife — play/world/WildlifeManager.js)', species: {}, stats: stats, night: night, payment_ui: false, figures: allFigs.length, population_lod: { built: !!POP.built, error: POP.error || null, mid_schools: POP.schools.length, mid_agents: POP.agents.length, far_silhouettes: POP.farItems.length, breaches: POP.breaches, reach_m: POP.reach, near_schools: POP.schools.filter(function (S) { return S.near; }).length, draw_calls: (POP.midMesh ? 1 : 0) + (POP.farMesh ? 1 : 0) } }; Object.keys(SP).forEach(function (k) { var sp = SP[k]; var figs = allFigs.filter(function (f) { return f.sp === sp; }); d.species[k] = { figures: figs.length, visible: figs.filter(function (f) { return f.root.visible; }).length, lods: 1 + sp.lods.length, scale: +sp.scale.toFixed(3), head: sp.frame.fwdZ > 0 ? '+z' : '-z', rig: sp.rig ? sp.rig.report : 'RIGID → shader', combat: sp.cfg.combat ? { hits_to_kill: sp.cfg.combat.hits_to_kill, hits_to_kill_player: sp.cfg.combat.hits_to_kill_player, aggression: sp.cfg.combat.aggression } : null, ownership: sp.cfg.ownership || null, states: figs.map(function (f) { return f.state; }), positions: figs.map(function (f) { return [Math.round(f.x), +f.y.toFixed(1), Math.round(f.z)]; }) }; }); return d; }
  /* dev diagnostics (intentional): the host owns the creatures — a summon is a host dev op (PLACE / WILDLIFE_SUMMON through MAHWORLD_PLAY.devPlay) */
  function summon(id) { log('wildlife: summon(' + id + ') is a HOST dev op now — use MAHWORLD_PLAY.devPlay("WILDLIFE_SUMMON", { species })'); return false; }
  function schools() { var out = {}; allFigs.forEach(function (f) { if (f.sp.id !== 'FISH') return; var k = (f.id.split('_')[2]) || '?'; var s = out[k] = out[k] || { id: k, n: 0, x: 0, z: 0 }; s.n++; s.x += f.x; s.z += f.z; }); return Object.keys(out).map(function (k) { var s = out[k]; return { id: s.id, x: Math.round(s.x / s.n), z: Math.round(s.z / s.n), n: s.n }; }); }
  function statusOf(id) { var f = byId[id]; if (!f || !f.status) return null; var st = f.status; return { id: id, species: f.sp.id, name: st.name, level: st.level, hp: st.hp, max: st.max, locked: st.locked, ko: st.ko, visible: !!st.sprite.visible, opacity: st.mat.opacity, position: { x: f.x, y: f.y, z: f.z }, head_y: f.y + f.sp.tagLift }; }   /* B7 §3 probe / HUD accessor */
  return { build: build, tick: tick, setNight: setNight, dispose: dispose, debug: debug, summon: summon, schools: schools, statusOf: statusOf, pickRoots: function () { var out = []; Object.keys(byId).forEach(function (k) { var f = byId[k]; if (f && f.root && f.root.visible) out.push({ id: k, root: f.root }); }); return out; }, figures: function () { var o = {}; allFigs.forEach(function (f) { (o[f.sp.id] = o[f.sp.id] || []).push(f); }); return o; } };
}
