/* B7 §2 — MONSTER TARGETING in the real runtime (static demo, headless Chrome): for each species the player is placed near a creature,
   faces it, and a real pointer tap is dispatched on the canvas at the creature's projected screen position → tapAt → entityAt → LOCK_TARGET;
   then slot 1 (PA_PUSH) is cast and the host journal must show damage on THAT id; then the lock must clear when the target dies / leaves
   range. Species: Dogkie (forest), fish (canal), horse (passive, Titan meadow), phoenix (aerial — lock from the ground / in flight).
   Also proves the entity status tags (LV / HP) exist on every nearby creature.   node deploy/joba/probe_targeting.mjs [out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var OUT = path.resolve((process.argv[2] && process.argv[2][0] !== '-') ? process.argv[2] : path.join(HERE, '..', 'probe_out', 'joba', 'targeting')); fs.mkdirSync(OUT, { recursive: true });
var MOBILE = process.argv.indexOf('--mobile') >= 0; var DIST = path.join(HERE, '..', 'static_dist'); var srv = await serveStatic(DIST); var pg = await launchChrome(MOBILE ? { width: 393, height: 852, dpr: 3, mobile: true, gpu: true } : { width: 1280, height: 800, gpu: true, unlockFps: true });
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; var H=window.MAHWORLD_STATIC_HOST; " + expr + " })()"); }
var report = { checks: [], console_errors: [] }; var pass = 0, fail = 0; function ok(id, cond, detail) { report.checks.push({ id: id, ok: !!cond, detail: detail }); if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + JSON.stringify(detail).slice(0, 700) : '')); } }
pg.on('Runtime.consoleAPICalled', function (p) { if (p.type !== 'error') return; var t = (p.args || []).map(function (a) { return a.value !== undefined ? String(a.value) : (a.description || ''); }).join(' '); if (/toNonIndexed/.test(t)) return; report.console_errors.push(t.slice(0, 300)); });
async function tapClient(x, y) { if (MOBILE) { await pg.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x, y: y, radiusX: 8, radiusY: 8, force: 1 }] }); await sleep(70); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); return; } await pg.cmd('Input.dispatchMouseEvent', { type: 'mousePressed', x: x, y: y, button: 'left', clickCount: 1 }); await sleep(40); await pg.cmd('Input.dispatchMouseEvent', { type: 'mouseReleased', x: x, y: y, button: 'left', clickCount: 1 }); }
async function me() { return await ev("var p=P.snap().play; return { pos: p.position, facing: p.facing, lock: p.rules && p.rules.me && p.rules.me.lock ? p.rules.me.lock.target : null, hp: p.rules && p.rules.me ? p.rules.me.hp : null, creatures: p.creatures||[], wildlife: p.wildlife||[], flight: p.flight };"); }
async function nearest(list, spec) { var m = await me(); var arr = (spec === 'DOGKIE' ? m.creatures : m.wildlife.filter(function (w) { return w.species === spec; })); var best = null, bd = 1e9; arr.forEach(function (c) { var d = Math.hypot(c.position.x - m.pos.x, c.position.z - m.pos.z); if (spec === 'DOGKIE' && c.ko) return; if (spec === 'DOGKIE' && arr.some(function (o) { return o !== c && !o.ko && Math.hypot(o.position.x - c.position.x, o.position.z - c.position.z) < 4; })) d += 1000;   /* B8 packs: prefer a Dogkie with no packmate inside 4 m so the finger point holds ONE body (an overlapping pair is a legitimate 'front-most wins' case, not a targeting fault) */ if (d < bd) { bd = d; best = c; } }); if (best && bd >= 1000) bd -= 1000; return best ? { c: best, d: bd } : null; }
async function project(id) { return await ev("var W=P.worldLayer(); var wl=W.wildlife && W.wildlife(); var cm=W.creatures && W.creatures(); var root=null; if (cm && cm.pickRoots) cm.pickRoots().forEach(function(r){ if (r.id==='" + id + "') root=r.root; }); if (!root && wl && wl.pickRoots) wl.pickRoots().forEach(function(r){ if (r.id==='" + id + "') root=r.root; }); if (!root) return { err: 'no pick root' }; var b=new P.THREE.Box3(); root.updateWorldMatrix(true, true); root.traverse(function(o){ if (o.isMesh && o.visible && o.geometry) { if (!o.geometry.boundingBox) o.geometry.computeBoundingBox(); var bb = o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld); b.union(bb); } }); if (b.isEmpty()) return { err: 'no mesh' }; var c=b.getCenter(new P.THREE.Vector3()); var s=P.worldToScreen(c.x, c.y, c.z); return s ? { x: s.x, y: s.y, cx: +c.x.toFixed(2), cy: +c.y.toFixed(2), cz: +c.z.toFixed(2), size: [+(b.max.x-b.min.x).toFixed(2), +(b.max.y-b.min.y).toFixed(2), +(b.max.z-b.min.z).toFixed(2)] } : { err: 'offscreen' };"); }
var VW = MOBILE ? 393 : 1280, VH = MOBILE ? 852 : 800;
async function lookToward(id) {
  /* the phone gesture: drag on open game space until the creature sits in the upper-middle of the frame (an aerial target needs the pitch) — through the real drag path (P.camDrag), gains measured, bounded */
  var gy = null, gp = null; for (var it = 0; it < 9; it++) { var scr = await project(id); if (!scr || scr.err) { await ev("P.camDrag(0.7, 0); return 1;"); await sleep(350); continue; }
    var ex = scr.x - VW / 2, ey = scr.y - VH * 0.36; if (Math.abs(ex) < VW * 0.14 && Math.abs(ey) < VH * 0.1) return scr;
    if (gy === null) { await ev("P.camDrag(0.2, 0); return 1;"); await sleep(300); var s2 = await project(id); if (s2 && !s2.err && Math.abs(s2.x - scr.x) > 2) gy = 0.2 / (s2.x - scr.x); else gy = -0.002; scr = s2 && !s2.err ? s2 : scr; ex = scr.x - VW / 2; }
    if (gp === null) { await ev("P.camDrag(0, 0.15); return 1;"); await sleep(300); var s3 = await project(id); if (s3 && !s3.err && Math.abs(s3.y - scr.y) > 2) gp = 0.15 / (s3.y - scr.y); else gp = 0.002; scr = s3 && !s3.err ? s3 : scr; ex = scr.x - VW / 2; ey = scr.y - VH * 0.36; }
    var dyaw = Math.max(-0.8, Math.min(0.8, -ex * gy)), dpitch = Math.max(-0.5, Math.min(0.5, -ey * gp)); await ev("P.camDrag(" + dyaw.toFixed(4) + ", " + dpitch.toFixed(4) + "); return 1;"); await sleep(350); }
  return await project(id);
}
async function hudSafe(x, y) { /* The touch build owns open world through [data-zone=world]; desktop intentionally hides that layer and the canvas itself owns clicks. */ return await ev("var el = document.elementFromPoint(" + x.toFixed(1) + ", " + y.toFixed(1) + "); if (!el) return false; var z = el.closest ? el.closest('[data-zone]') : null, world = " + (MOBILE ? "!!(z && z.getAttribute('data-zone') === 'world')" : "el.id === 'view'") + "; return !!(world && !(el.closest && el.closest('button, .gp, .gb, #ghud, #slots, #prompts, #menu')));"); }
function onScreen(scr) { return scr && !scr.err && scr.x > 8 && scr.x < VW - 8 && scr.y > VH * 0.06 && scr.y < VH * (MOBILE ? 0.62 : 0.9) && scr.safe !== false; }   /* the phone's lower ~38 % is the control island (joystick / slots) — a tap there is a control, never a world tap */
async function faceAndTap(id, spec) {
  /* face the creature (host yaw), wait a beat for the camera, then project its body point and tap it; when the projection lands off the
     playable screen (behind / below the camera, in the phone control island) step BACK from it (the owner's phone case: the creature was
     too close / below the frame) and retry — up to 3 steps */
  var scr = null, steps = 0, rec = null, m = null;
  for (var attempt = 0; attempt < (spec === 'PHOENIX' ? 1 : 4); attempt++) {
    m = await me(); rec = (spec === 'DOGKIE' ? m.creatures : m.wildlife).filter(function (c) { return c.id === id; })[0]; if (!rec) return { err: 'gone' };
    if (spec === 'PHOENIX') { scr = await project(id); break; }
    var yaw = Math.atan2(rec.position.x - m.pos.x, -(rec.position.z - m.pos.z)); await ev("P.send('MOVE', { forward: 0, strafe: 0, yaw: " + yaw.toFixed(3) + " }); return 1;"); await sleep(500); await ev("P.camReset && P.camReset('probe'); return 1;"); await sleep(1400);   /* the camera heading is independent of the facing (owner camera truth) — the one-shot reset reframes behind the character, which is what a player does before tapping something behind the camera */
    scr = await project(id); if (scr && !scr.err) scr.safe = await hudSafe(scr.x, scr.y); if (onScreen(scr)) break;
    if (spec === 'PHOENIX' || attempt >= 1) { scr = await lookToward(id); if (scr && !scr.err) scr.safe = await hudSafe(scr.x, scr.y); if (onScreen(scr)) break; /* an aerial target moves through the frame (hover → dive → climb): wait for a frame where its body sits on open game space */ for (var pf = 0; pf < 60; pf++) { await sleep(120); scr = await project(id); if (scr && !scr.err) { scr.safe = await hudSafe(scr.x, scr.y); if (onScreen(scr)) { var ea = await ev("var h=P.entityAt(" + scr.x.toFixed(1) + ", " + scr.y.toFixed(1) + "); return h ? h.id : null;"); if (ea === 'other:' + id) break; scr.safe = false; } } } if (onScreen(scr)) break; continue; }
    var dx = rec.position.x - m.pos.x, dz = rec.position.z - m.pos.z, d0 = Math.max(0.01, Math.hypot(dx, dz)); var tx = m.pos.x - dx / d0 * 3.5, tz = m.pos.z - dz / d0 * 3.5; await ev("return P.goTo(" + tx.toFixed(2) + ", " + tz.toFixed(2) + ", undefined, undefined, 12000);"); await sleep(500); steps++;
  }
  if (spec !== 'PHOENIX' && !onScreen(scr)) return { err: scr && scr.err ? scr.err : 'off playable screen', screen: scr, steps: steps };
  if (spec === 'FISH' || spec === 'PHOENIX') { var tp2 = null; for (var ti = 0; ti < 80; ti++) { if (spec === 'PHOENIX') { var dP = await dist3(id, spec); if (!dP || dP.d > 28) { await sleep(150); continue; } }   /* an aerial target is tapped while it is inside the 30 m rule, not after a scripted pause */ tp2 = await tapInPage(id); if (!tp2.err) break; if (tp2.err === 'offscreen' || tp2.err === 'not on world zone') { await lookToward(id); } await sleep(120); } if (!tp2) tp2 = { err: 'never inside the lock range while tapping' }; if (tp2.err) return { err: 'moving target never under the finger: ' + tp2.err, screen: tp2, steps: steps }; await sleep(600); var af2 = await me(); var resp2 = await ev("var t = P.touchState ? P.touchState() : null; return t ? { last_command: t.last_command, last_response: t.last_response, events: (t.events || []).map(function (e) { return e.kind; }) } : null;"); var mk2 = await ev("var mk = P.adapterGet ? P.adapterGet('lockmark') : null; return mk ? { target: mk.target, visible: !!(mk.root && mk.root.visible) } : null;"); return { screen: tp2, steps: steps, entityAt: { id: 'other:' + id }, lock: af2.lock, lockmark: mk2, touch: resp2, in_page: true }; }
  var hit = await ev("var h=P.entityAt(" + scr.x.toFixed(1) + ", " + scr.y.toFixed(1) + "); return h;"); var under = await ev("var el = document.elementFromPoint(" + scr.x.toFixed(1) + ", " + scr.y.toFixed(1) + "); if (!el) return null; var z = el.closest ? el.closest('[data-zone]') : null; return { tag: el.tagName, id: el.id, cls: String(el.className || '').slice(0, 60), zone: z ? z.getAttribute('data-zone') : null };"); await tapClient(scr.x, scr.y); var trace = []; for (var tp = 0; tp < 20; tp++) { await sleep(100); var tr = await ev("var p=P.snap().play; return [p.host_t, p.rules && p.rules.me && p.rules.me.lock ? p.rules.me.lock.target : null, p.rules && p.rules.me ? p.rules.me.ko : null, p.room];"); trace.push(tr); if (tr[1] === id) break; } var after = await me(); var tail = await ev("return (P.log ? P.log() : []).slice(-4).filter(function(l){ return /LOCK|lock/.test(l); });");   /* Mobile input and the host snapshot cross two animation/tick boundaries; observe the accepted real tap for up to 2 s instead of injecting a direct lock fallback that would weaken this proof. */
  var mark = await ev("var mk = P.adapterGet ? P.adapterGet('lockmark') : null; return mk ? { target: mk.target, visible: !!(mk.root && mk.root.visible) } : null;");
  var jl = await ev("return H.host.dev.log().filter(function(e){ return e.kind==='R1723_LOCK' || e.kind==='DEV_PLACE' || e.kind==='R1723_KO' || e.kind==='PLAYER_DEFEAT' || e.kind==='RESPAWN'; }).slice(-5).map(function(e){ return [e.kind, e.id, e.target, e.why, e.tick]; });"); var tst = await ev("var t = P.touchState ? P.touchState() : null; return t ? { last_gesture: t.last_gesture, last_command: t.last_command, last_response: t.last_response, fingers: t.fingers } : null;"); return { screen: scr, steps: steps, entityAt: hit, under: under, touch: tst, journal: jl, trace: trace, lock: after.lock, lockmark: mark, log: tail, direct: null };
}
/* a MOVING target (a launching fish, a diving phoenix) outruns the probe's CDP round trips (project → check → dispatch ≈ 150 ms ≈ 2 m at 13–16 m/s);
   a thumb taps what it sees with ~50 ms latency. So for the moving species the projection and the pointer events happen INSIDE the page in one
   go, through the same pointerdown / pointerup path of the touch layer (#tc, pointerType touch) — the ground species keep the real CDP touch. */
async function tapInPage(id) { return await ev("var W=P.worldLayer(); var wl=W.wildlife && W.wildlife(); var cm=W.creatures && W.creatures(); var root=null; if (cm && cm.pickRoots) cm.pickRoots().forEach(function(r){ if (r.id==='" + id + "') root=r.root; }); if (!root && wl && wl.pickRoots) wl.pickRoots().forEach(function(r){ if (r.id==='" + id + "') root=r.root; }); if (!root) return { err: 'no pick root' }; var b=new P.THREE.Box3(); root.updateWorldMatrix(true, true); root.traverse(function(o){ if (o.isMesh && o.visible && o.geometry) { if (!o.geometry.boundingBox) o.geometry.computeBoundingBox(); b.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld)); } }); if (b.isEmpty()) return { err: 'no mesh' }; var c=b.getCenter(new P.THREE.Vector3()); var sc=P.worldToScreen(c.x, c.y, c.z); if (!sc) return { err: 'offscreen' }; var el = document.elementFromPoint(sc.x, sc.y); var z = el && el.closest ? el.closest('[data-zone]') : null, mobile=" + (MOBILE ? "true" : "false") + ", world=mobile ? !!(z && z.getAttribute('data-zone') === 'world') : !!(el && el.id === 'view'); if (!world) return { err: mobile ? 'not on world zone' : 'not on canvas', x: sc.x, y: sc.y, under: el ? (el.id || el.className) : null }; var h = P.entityAt(sc.x, sc.y); if (!h || h.id !== 'other:" + id + "') return { err: 'entityAt miss', x: sc.x, y: sc.y, hit: h ? h.id : null }; if (mobile) { var mk = function (type) { return new PointerEvent(type, { clientX: sc.x, clientY: sc.y, pointerId: 77, pointerType: 'touch', isPrimary: true, bubbles: true, cancelable: true, button: 0, buttons: type === 'pointerup' ? 0 : 1 }); }; el.dispatchEvent(mk('pointerdown')); setTimeout(function () { el.dispatchEvent(mk('pointerup')); }, 60); } else { el.dispatchEvent(new MouseEvent('mousedown', { clientX: sc.x, clientY: sc.y, bubbles: true, cancelable: true, button: 0, buttons: 1 })); setTimeout(function () { el.dispatchEvent(new MouseEvent('mouseup', { clientX: sc.x, clientY: sc.y, bubbles: true, cancelable: true, button: 0, buttons: 0 })); }, 40); } return { x: sc.x, y: sc.y, cx: +c.x.toFixed(2), cy: +c.y.toFixed(2), cz: +c.z.toFixed(2), safe: true, in_page: true };"); }
async function dist3(id, spec) { var m = await me(); var rec = (spec === 'DOGKIE' ? m.creatures : m.wildlife).filter(function (c) { return c.id === id; })[0]; if (!rec) return null; var my = m.flight && typeof m.flight.altitude === 'number' ? m.flight.altitude : (m.pos.y || 0); return { d: Math.hypot(rec.position.x - m.pos.x, rec.position.z - m.pos.z, (rec.y || 0) - my), rec: rec, my_y: my }; }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(3000); await ev("P.hud.showGuide(false); P.hud.setDev && P.hud.setDev(false); return 1;");
  for (var i = 0; i < 240; i++) { var w = await ev("return P.world ? P.world().status : null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); } await sleep(2500);
  var LV = await ev("var r = P.worldLayer && P.worldLayer().registry ? P.worldLayer().registry() : null; return r && r.ecology && r.ecology.levels ? r.ecology.levels.computed : null;");
  var species = [
    { spec: 'DOGKIE', place: [-70, 0], label: 'Dogkie (west forest)', lv: 5 },
    { spec: 'FISH', place: [-94, 40], label: 'fish (the Visionary pool, from its south shore)', lv: 35 },
    { spec: 'HORSE', place: [128, 126], label: 'horse (Titan meadow, passive)', lv: 35 },
    { spec: 'PHOENIX', place: [-150, 20], label: 'phoenix (aerial, provoked → dives within lock range)', lv: 75 },
  ];
  for (var si = 0; si < species.length; si++) { var S = species[si];
    await ev("P.send('PRACTICE_RESET', {}); return 1;"); await sleep(400); await ev("return P.devPlay('PLACE', { x: " + S.place[0] + ", z: " + S.place[1] + " });"); await sleep(2500); var nr = null; for (var k = 0; k < 20 && !nr; k++) { nr = await nearest(null, S.spec); if (!nr) await sleep(500); }
    if (!nr) { ok(S.label + ': a creature is awake nearby', false, { creatures: (await me()).creatures.length }); continue; }
    if (S.spec === 'DOGKIE') { /* a pack (aggro cap 3) kills a standing scripted player in ~5 s — the real balance; so the probe arrives 6 m from the chosen Dogkie instead of strolling through the pack */ var mA = await me(); var dxA = nr.c.position.x - mA.pos.x, dzA = nr.c.position.z - mA.pos.z, dA = Math.max(0.01, Math.hypot(dxA, dzA)); await ev("return P.devPlay('PLACE', { x: " + (nr.c.position.x - dxA / dA * 6).toFixed(2) + ", z: " + (nr.c.position.z - dzA / dA * 6).toFixed(2) + " });"); await sleep(600); nr = await nearest(null, S.spec) || nr; }
    else if (S.spec !== 'PHOENIX') { /* walk to within lock range (30 m) but not on top of it */ var tries = 0; while ((nr.d > 9 || nr.d < 3.5) && tries < 4) { var m0 = await me(); var dx = nr.c.position.x - m0.pos.x, dz = nr.c.position.z - m0.pos.z; var d0 = Math.hypot(dx, dz); var tx = nr.c.position.x - dx / d0 * 6, tz = nr.c.position.z - dz / d0 * 6; await ev("return P.goTo(" + tx.toFixed(1) + ", " + tz.toFixed(1) + ", undefined, undefined, 20000);"); await sleep(400); nr = await nearest(null, S.spec) || nr; tries++; } }
    else { /* the phoenix patrols ~100 m up and engages FLYERS (≥ 30 m) inside its territory or whoever struck it: take off (hold-ascend) to ~36 m, provoke it (the dev summon = a hit on the nearest phoenix) and wait for its anticipation hover / dive to bring it inside the 30 m lock rule */
      await ev("P.send('FLIGHT', { op: 'ENTER' }); return 1;"); var alt = 0; for (var fa = 0; fa < 80; fa++) { await sleep(250); var mf = await me(); alt = mf.flight && typeof mf.flight.altitude === 'number' ? mf.flight.altitude : 0; if (alt >= 36) break; } await ev("P.send('FLIGHT', { op: 'HOVER' }); return 1;"); await sleep(600);
      ok(S.label + ': the player is airborne at ≥ 30 m for the aerial encounter (alt ' + alt.toFixed(1) + ' m)', alt >= 30, { alt: alt });
      /* the phoenixes fly broad patrol circuits at 9 m/s (leash 220 m): hover under the nearest one NOW (a player would fly there), then provoke it (the dev summon = a hit on the nearest phoenix) */ nr = await nearest(null, 'PHOENIX') || nr; await ev("return P.devPlay('PLACE', { x: " + nr.c.position.x.toFixed(1) + ", z: " + nr.c.position.z.toFixed(1) + " });"); await sleep(800);
      await ev("return P.devPlay('WILDLIFE_SUMMON', { species: 'PHOENIX' });"); var near = null; for (var pw = 0; pw < 100; pw++) { var dd3 = await dist3(nr.c.id, 'PHOENIX'); if (dd3 && dd3.d <= 27) { near = dd3; break; } await sleep(250); } ok(S.label + ': the provoked phoenix comes within the 30 m lock rule', !!near, { last: await dist3(nr.c.id, 'PHOENIX') }); }
    var tag = await ev("var W=P.worldLayer(); var wl=W.wildlife && W.wildlife(); var cm=W.creatures && W.creatures(); var st = (cm && cm.statusOf) ? cm.statusOf('" + nr.c.id + "') : null; if (!st && wl && wl.statusOf) st = wl.statusOf('" + nr.c.id + "'); return st;");
    var r = await faceAndTap(nr.c.id, S.spec);
    for (var side = 1; side <= 3 && S.spec === 'DOGKIE' && r && r.touch && /NO_LINE_OF_SIGHT|TOO_FAR/.test(r.touch.last_response || '') ; side++) { /* a crystal / trunk between: the lock rule refused (correct) — come around from another side, as a player would */ var mS = await me(); var recS = mS.creatures.filter(function (c) { return c.id === nr.c.id; })[0]; if (!recS) break; var ang = side * 2.1; await ev("return P.devPlay('PLACE', { x: " + (recS.position.x + Math.sin(ang) * 5).toFixed(2) + ", z: " + (recS.position.z + Math.cos(ang) * 5).toFixed(2) + " });"); await sleep(600); r = await faceAndTap(nr.c.id, S.spec); }
    var tapped = r && r.entityAt && r.entityAt.id ? r.entityAt.id.slice(6) : null; var tappedSpec = tapped ? ((await me()).wildlife.concat((await me()).creatures)).filter(function (c) { return c.id === tapped; })[0] : null;
    var lockedOk = r && !r.err && r.lock && r.lock === tapped && tappedSpec && (tappedSpec.species || 'DOGKIE') === S.spec; if (lockedOk && tapped !== nr.c.id) { nr = { c: tappedSpec, d: nr.d }; tag = await ev("var W=P.worldLayer(); var wl=W.wildlife && W.wildlife(); var cm=W.creatures && W.creatures(); var st = (cm && cm.statusOf) ? cm.statusOf('" + tapped + "') : null; if (!st && wl && wl.statusOf) st = wl.statusOf('" + tapped + "'); return st;"); }   /* two bodies overlap on the screen (a school): the finger locks the one it touched — that is the correct behaviour */
    ok(S.label + ': a real tap at its projected body locks THE TAPPED creature through LOCK_TARGET (entityAt → other:' + (tapped || nr.c.id) + ')', lockedOk, { r: r, d: +nr.d.toFixed(1), y: nr.c.y, level: nr.c.level });
    ok(S.label + ': the lock marker follows the locked creature figure', !!(lockedOk && r.lockmark && r.lockmark.target === 'other:' + nr.c.id && r.lockmark.visible), { lockmark: r && r.lockmark });
    ok(S.label + ': the entity status (name / LV ' + S.lv + ' / HP) is present and visible on its figure', !!(tag && tag.level === S.lv && tag.hp !== undefined && tag.max > 0 && tag.visible), { tag: tag, host_level: nr.c.level });
    if (lockedOk) {
      var before = await ev("return (H.host.dev.log().filter(function(e){ return e.kind==='R1723_DAMAGE' && e.on==='" + nr.c.id + "'; }).length);"); await ev("P.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); return 1;");
      if (S.spec !== 'PHOENIX') { var m1 = await me(); var rec1 = (S.spec === 'DOGKIE' ? m1.creatures : m1.wildlife).filter(function (c) { return c.id === nr.c.id; })[0]; if (rec1) { var dd = Math.hypot(rec1.position.x - m1.pos.x, rec1.position.z - m1.pos.z); if (dd > 1.8) await ev("return P.goTo(" + (rec1.position.x + (m1.pos.x - rec1.position.x) / dd * 1.3).toFixed(2) + ", " + (rec1.position.z + (m1.pos.z - rec1.position.z) / dd * 1.3).toFixed(2) + ", undefined, undefined, 15000);"); } }
      if (S.spec === 'FISH' || S.spec === 'PHOENIX') { /* the launching fish / the diving phoenix come THROUGH the player (a movement test, never a stationary target): poll the 3-D distance and cast the moment it is inside strike range, facing it — what a player does */ var t0r = Date.now(); var casts = 0; var lastEdge = 0; var minD = 1e9, statesSeen = {}; while (Date.now() - t0r < 60000 && casts < 12) { var d3 = await dist3(nr.c.id, S.spec); if (!d3 || (d3.rec && d3.rec.ko)) break; if (d3.d < minD) minD = d3.d; statesSeen[d3.rec.state] = (statesSeen[d3.rec.state] || 0) + 1; var d2d = Math.hypot(d3.rec.position.x - (await me()).pos.x, d3.rec.position.z - (await me()).pos.z); var dyv = Math.abs((d3.rec.y || 0) - d3.my_y);   /* BODY_STRIKE reaches ± 1.6 m of the striker's height: the phoenix is answerable in its SWEEP (dive → level pass), the fish in its swirl / recover */ if (S.spec === 'FISH' && d2d > 2.4 && Date.now() - lastEdge > 2000) { lastEdge = Date.now(); var mE = await me(); await ev("return P.goTo(" + d3.rec.position.x.toFixed(2) + ", " + d3.rec.position.z.toFixed(2) + ", undefined, undefined, 1500);"); }   /* to the water's edge toward it (the nav stops at the shore) */ if (d2d <= 2.4 && dyv <= 1.5) { var mr = await me(); var yr = Math.atan2(d3.rec.position.x - mr.pos.x, -(d3.rec.position.z - mr.pos.z)); await ev("P.send('MOVE', { forward: 0, strafe: 0, yaw: " + yr.toFixed(3) + " }); return 1;"); for (var fw = 0; fw < 6; fw++) { await sleep(50); var mf2 = await me(); var de = Math.atan2(Math.sin(yr - (mf2.facing || 0)), Math.cos(yr - (mf2.facing || 0))); if (Math.abs(de) < 0.35) break; }   /* the avatar turns at its real rate: cast once it faces the body (the cone rule) */ await ev("P.send('RULES_CAST', {}); return 1;"); casts++; await sleep(380); } else await sleep(90); } }
      else for (var c2 = 0; c2 < 8; c2++) { if (S.spec !== 'PHOENIX') { var mc = await me(); var rc = (S.spec === 'DOGKIE' ? mc.creatures : mc.wildlife).filter(function (c) { return c.id === nr.c.id; })[0]; if (rc && !rc.ko) { var dc = Math.hypot(rc.position.x - mc.pos.x, rc.position.z - mc.pos.z); if (dc > 2.1) { /* a moving target (the horse trots off, the fish swirls): step back into strike range first, as the player would */ await ev("return P.goTo(" + (rc.position.x + (mc.pos.x - rc.position.x) / dc * 1.3).toFixed(2) + ", " + (rc.position.z + (mc.pos.z - rc.position.z) / dc * 1.3).toFixed(2) + ", undefined, undefined, 8000);"); await sleep(300); } var mc2 = await me(); var rc2 = (S.spec === 'DOGKIE' ? mc2.creatures : mc2.wildlife).filter(function (c) { return c.id === nr.c.id; })[0] || rc; var yc = Math.atan2(rc2.position.x - mc2.pos.x, -(rc2.position.z - mc2.pos.z)); await ev("P.send('MOVE', { forward: 0, strafe: 0, yaw: " + yc.toFixed(3) + " }); return 1;"); await sleep(200); } } await ev("P.send('RULES_CAST', {}); return 1;"); await sleep(700); }   /* B8: the packs shuffle — a Dogkie that circled behind during its pounce is faced again before EVERY cast, as a player would */
      var after = await ev("return (H.host.dev.log().filter(function(e){ return e.kind==='R1723_DAMAGE' && e.on==='" + nr.c.id + "'; }).length);"); var miss = await ev("return H.host.dev.log().slice(-40).filter(function(e){ return e.kind==='R1723_MISS'; }).map(function(e){ return e.why || e.reason; }).slice(-3);");
      ok(S.label + ': attack slot 1 (PA_PUSH) damages THE LOCKED creature through the one combat authority (' + (after - before) + ' hits)', after > before, { hits: after - before, misses: miss, casts: typeof casts === 'number' ? casts : undefined, min_d: typeof minD === 'number' ? +minD.toFixed(2) : undefined, states: typeof statesSeen === 'object' ? statesSeen : undefined, note: S.spec === 'PHOENIX' ? 'aerial target: answered in its SWEEP pass at the player height (dive → level pass inside melee reach)' : undefined });
      var tag2 = await ev("var W=P.worldLayer(); var wl=W.wildlife && W.wildlife(); var cm=W.creatures && W.creatures(); var st = (cm && cm.statusOf) ? cm.statusOf('" + nr.c.id + "') : null; if (!st && wl && wl.statusOf) st = wl.statusOf('" + nr.c.id + "'); return st;");
      var gone2 = !tag2 && !((await me()).creatures.concat((await me()).wildlife)).some(function (c) { return c.id === nr.c.id && !c.ko; }); if (after > before) ok(S.label + ': the status HP bar reflects the damage (hp < max; LOCKED while the lock holds)', !!(tag2 && tag2.hp < tag2.max) || gone2, { tag: tag2, dissolved: gone2 });
    }
    await ev("P.send('LOCK_TARGET', { aim_id: null }); return 1;"); await sleep(300);
  }
  /* Lock lifecycle is intentionally isolated from the pointer proof above. The four species already passed through a real canvas tap; here a
     direct, host-validated lock removes camera / moving-body timing from the two cleanup assertions. A Dogkie pack is allowed to be lethal, so
     the probe reloads the same ATHLETE class before HP can reach zero (full HP only; the Dogkie keeps its real HP) and repositions at melee
     distance before each real PA_PUSH cast. That keeps pack balance intact while preventing PLAYER defeat from pre-empting TARGET_DOWN. */
  await ev("P.send('FLIGHT', { op: 'EXIT' }); return 1;"); for (var lw = 0; lw < 60; lw++) { await sleep(250); var ml = await me(); if (!ml.flight || !ml.flight.powered) break; }
  await ev("return P.send('RULES_CLASS', { class: 'ATHLETE' });"); await ev("return P.devPlay('PLACE', { x: -70, z: 0 });"); await sleep(2500);
  async function awakeDogkie(exclude) { var s = await me(), live = s.creatures.filter(function (c) { return !c.ko && c.id !== exclude; }); if (!live.length) return null; live.forEach(function (c) { c.clearance = 1e9; live.forEach(function (o) { if (o !== c) c.clearance = Math.min(c.clearance, Math.hypot(o.position.x - c.position.x, o.position.z - c.position.z)); }); }); live.sort(function (a, b) { return b.clearance - a.clearance; }); return live[0]; }
  async function placeAndLockDogkie(id, range) { var last = null; for (var a0 = 0; a0 < 8; a0++) { var s0 = await me(), c0 = s0.creatures.filter(function (c) { return c.id === id && !c.ko; })[0]; if (!c0) return { lock: null, err: 'target unavailable' }; var ang0 = a0 * Math.PI / 4, px0 = c0.position.x + Math.sin(ang0) * range, pz0 = c0.position.z + Math.cos(ang0) * range; await ev("return P.devPlay('PLACE', { x: " + px0.toFixed(2) + ", z: " + pz0.toFixed(2) + " });"); await sleep(100); var s1 = await me(), c1 = s1.creatures.filter(function (c) { return c.id === id && !c.ko; })[0]; if (!c1) return { lock: null, err: 'target unavailable after place' }; var yaw0 = Math.atan2(c1.position.x - s1.pos.x, -(c1.position.z - s1.pos.z)); await ev("P.send('MOVE', { forward: 0, strafe: 0, yaw: " + yaw0.toFixed(4) + " }); return 1;"); await sleep(100); last = await ev("return P.send('LOCK_TARGET', { aim_id: '" + id + "' });"); if (last && last.accepted) { var got = (await me()).lock; if (got === id) return { lock: got, response: last, angle: a0, position: { x: px0, z: pz0 } }; } } return { lock: (await me()).lock, response: last, err: last && last.reason || 'lock refused at every clear approach' }; }
  var dkC = await awakeDogkie(null), dk = dkC ? { c: dkC } : null;
  if (dk) { var r2 = await placeAndLockDogkie(dk.c.id, 1.25); await ev("P.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); return 1;"); var killStart = await ev("return H.host.dev.log().length;"); var casts3 = [], heals3 = 0, kod = false;
    for (var c3 = 0; c3 < 12 && !kod; c3++) { var stF = await me(); var recF = stF.creatures.filter(function (c) { return c.id === dk.c.id; })[0]; if (!recF || recF.ko) { kod = true; break; } if (stF.hp < 1200) { var heal3 = await ev("return P.send('RULES_CLASS', { class: 'ATHLETE' });"); if (heal3 && heal3.accepted) heals3++; await sleep(100); } var set3 = await placeAndLockDogkie(dk.c.id, 1.15); if (set3.lock !== dk.c.id) { casts3.push({ accepted: false, reason: set3.err || 'LOCK_FAILED' }); break; } var cast3 = await ev("return P.send('RULES_CAST', {});"); casts3.push(cast3 && { accepted: cast3.accepted, reason: cast3.reason, skill: cast3.skill }); for (var cw3 = 0; cw3 < 20; cw3++) { await sleep(50); var busy3 = await ev("var r=P.snap().play.rules; return !!(r && r.me && r.me.cast);"); if (!busy3) break; } var st3 = await me(); var rec3 = st3.creatures.filter(function (c) { return c.id === dk.c.id; })[0]; if (!rec3 || rec3.ko) kod = true; }
    for (var kw3 = 0; kw3 < 30; kw3++) { var end3 = await me(); var recEnd3 = end3.creatures.filter(function (c) { return c.id === dk.c.id; })[0]; kod = kod || !recEnd3 || !!recEnd3.ko; if (kod && end3.lock === null) break; await sleep(100); }
    var lk3 = (await me()).lock; var killDbg = await ev("var L = H.host.dev.log().slice(" + killStart + "); var out = { dmg_on: 0, damage_skills: [], dmg_me: 0, miss: [], ko: [], lock_clear: [], defeat: 0, respawn: 0, me_hp: (P.snap().play.rules && P.snap().play.rules.me) ? P.snap().play.rules.me.hp : null }; L.forEach(function (e) { if (e.kind === 'R1723_DAMAGE' && e.on === '" + dk.c.id + "') { out.dmg_on++; out.damage_skills.push(e.skill); } if (e.kind === 'R1723_DAMAGE' && e.on === 'PLAYER_A') out.dmg_me++; if (e.kind === 'R1723_MISS') out.miss.push(e.why); if (e.kind === 'R1723_KO') out.ko.push({ id: e.id || e.target, skill: e.skill }); if (e.kind === 'R1723_LOCK' && e.id === 'PLAYER_A' && e.target === null) out.lock_clear.push(e.why); if (e.kind === 'PLAYER_DEFEATED') out.defeat++; if (e.kind === 'PLAYER_RESPAWN') out.respawn++; }); out.miss = out.miss.slice(-4); return out;"); var paOnly = killDbg.dmg_on > 0 && killDbg.damage_skills.every(function (x) { return x === 'PA_PUSH'; }); var koByPush = killDbg.ko.some(function (x) { return x.id === dk.c.id && x.skill === 'PA_PUSH'; }); ok('lock cleanup: the locked Dogkie was killed with slot 1 PA_PUSH and TARGET_DOWN cleared the lock', r2.lock === dk.c.id && kod && lk3 === null && paOnly && koByPush && killDbg.lock_clear.indexOf('TARGET_DOWN') >= 0, { lock_after: lk3, locked_before: r2.lock, setup: r2, casts: casts3, hp_reloads: heals3, kill: killDbg });
    var dk2 = null; for (var k2 = 0; k2 < 20 && !dk2; k2++) { dk2 = await awakeDogkie(dk.c.id); if (!dk2) await sleep(250); }
    if (dk2) { var r4 = await placeAndLockDogkie(dk2.id, 5); var beforeRangeLog = await ev("return H.host.dev.log().length;"); var rangeOrigin = dk2.position; await ev("return P.devPlay('PLACE', { x: " + (rangeOrigin.x + 50).toFixed(2) + ", z: " + rangeOrigin.z.toFixed(2) + " });"); var lk4 = null, farDistance = null, rangeLive = null; for (var rw4 = 0; rw4 < 60; rw4++) { await sleep(100); var farState = await me(); lk4 = farState.lock; rangeLive = farState.creatures.filter(function (c) { return c.id === dk2.id && !c.ko; })[0] || rangeLive; if (rangeLive) farDistance = Math.hypot(rangeLive.position.x - farState.pos.x, rangeLive.position.z - farState.pos.z); if (lk4 === null) break; }   /* 50 m is beyond lock.max_m (34) but inside the Dogkie habitat's 110 m dormant radius: the creature stays host-owned and the lifecycle being measured can only end as TOO_FAR, not TARGET_REMOVED. */ var rangeWhy = await ev("return H.host.dev.log().slice(" + beforeRangeLog + ").filter(function(e){ return e.kind==='R1723_LOCK' && e.id==='PLAYER_A' && e.target===null; }).map(function(e){ return e.why; });"); ok('lock cleanup: leaving lock range (teleport 50 m away) clears the lock within the range grace', r4.lock === dk2.id && !!rangeLive && farDistance > 34 && lk4 === null && rangeWhy.indexOf('TOO_FAR') >= 0, { locked: r4.lock, target_alive: !!rangeLive, observed_distance_m: farDistance === null ? null : +farDistance.toFixed(2), after: lk4, clear_reasons: rangeWhy, setup: r4 }); }
    else ok('lock cleanup: a second awake Dogkie for the range-loss check', false, {});
  }
  report.levels = LV;
  report.errors = pg.errors.filter(function (e) { return !/404|favicon/.test(e); }).slice(0, 20); ok('no console errors', report.console_errors.length === 0, report.console_errors.slice(0, 3)); report.mobile = MOBILE;
} catch (e) { report.fatal = String(e && e.stack || e); console.error(e); } finally { report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'targeting.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT probe_targeting ' + pass + ' passed, ' + fail + ' failed' + (report.fatal ? ' FATAL' : ''));
