/* Owner next-pass 2026-09-20 §28 / §29 — FLIGHT BRAKE + GUIDE FORMATION acceptance in the real runtime (static demo, headless Chrome, GPU).
   FLIGHT: enter flight, fly forward at BOOST (`fast`) until ≥ 70 % of cruise, release the stick: the host speed must ease out (not snap), the
   animator's braking envelope must run once (amount > 0.3) and settle within ~0.45 s, the altitude must not change, and a low-speed stop must
   NOT trigger it. GUIDE: Mrs. Mah on, walk / turn / stop / fly: her lateral distance stays near the shoulder (0.5–1.3 m), her yaw follows the
   player's heading (|Δ| < 40° while travelling), she never sits in front of the camera, turns stay smooth, the size is unchanged (0.75 m).
   Screenshots: the brake mid-transition (freeze-frame by pausing virtual time), the settled hover, the formation walking / flying.
   node deploy/joba/probe_flight_brake_guide.mjs [out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var OUT = path.resolve(argv[0] || path.join(HERE, '..', 'probe_out', 'joba', 'flight_brake_guide')); fs.mkdirSync(OUT, { recursive: true });
var DIST = path.join(HERE, '..', 'static_dist'); var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1280, height: 800, gpu: true, unlockFps: true });
var pass = 0, fail = 0, R = { checks: [], shots: [], errors: [] }; function ok(id, cond, detail) { R.checks.push({ id: id, ok: !!cond, detail: detail }); if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + ' — ' + JSON.stringify(detail)); } }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function shot(name, keepHud) { if (!keepHud) await ev("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;"); await sleep(150); await pg.screenshot(path.join(OUT, name + '.png')); await ev("document.querySelectorAll('body > *').forEach(function(e){ e.style.visibility=''; }); return 1;"); R.shots.push(name); console.log('shot', name); }
async function sample() { return await ev("var p=P.snap().play; var e=P.entity('me'); var an=e && e.fused ? e.fused.animator : null; var fb=an && an.flightBrake ? an.flightBrake() : null; return { t: performance.now()/1000, speed: p.speed_mps !== undefined ? p.speed_mps : null, alt: p.flight ? p.flight.altitude : null, powered: p.flight ? p.flight.powered : null, braking: p.flight ? p.flight.braking : null, cruise: p.flight ? p.flight.cruise_mps : null, fb: fb, pos: p.position };"); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(3000); await ev("P.hud.showGuide(false); return 1;");
  for (var i = 0; i < 240; i++) { var w = await ev("return P.world ? P.world().status : null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); } await sleep(1500);
  /* ---- FLIGHT BRAKE ---- */
  await ev("return P.goTo(0, 40, undefined, undefined, 30000);"); await ev("P.send('FLIGHT',{op:'ENTER'}); return 1;"); await sleep(600); await ev("P.send('FLIGHT',{op:'ASCEND'}); return 1;"); await sleep(1400); await ev("P.send('FLIGHT',{op:'HOVER'}); return 1;"); await sleep(700);
  await ev("P.send('MOVE', { forward: 1, strafe: 0, fast: true, yaw: 0 }); return 1;"); var run = []; for (var k = 0; k < 24; k++) { await sleep(120); run.push(await sample()); }
  var peak = run.reduce(function (m, s) { return Math.max(m, s.speed || 0); }, 0); var cruise = run[run.length - 1].cruise || 20.56; var altBefore = run[run.length - 1].alt;
  ok('F1 powered flight at BOOST reaches ≥ 70 % of the host cruise before the release (' + peak.toFixed(1) + ' m/s of cruise ' + cruise + ')', peak >= 0.7 * cruise, { peak: peak, cruise: cruise });
  await ev("P.send('MOVE', { forward: 0, strafe: 0 }); return 1;"); var rel = []; var t0 = null; for (var q = 0; q < 16; q++) { await sleep(45); var s = await sample(); if (t0 === null) t0 = s.t; s.dt = +(s.t - t0).toFixed(3); rel.push(s); }
  var speeds = rel.map(function (s) { return +(s.speed || 0).toFixed(2); }); var fbAmt = rel.map(function (s) { return s.fb ? s.fb.amount : 0; }); var fbMax = Math.max.apply(null, fbAmt); var firstZero = rel.filter(function (s) { return (s.speed || 0) < 0.5; })[0]; var altAfter = rel[rel.length - 1].alt;
  ok('F2 release does NOT snap: the horizontal speed eases out over ≥ 0.2 s (host brake decel) — never an instant zero', speeds[0] > 0.5 * peak && (firstZero ? firstZero.dt >= 0.2 : true), { speeds: speeds, dts: rel.map(function (s) { return s.dt; }), first_zero_at_s: firstZero ? firstZero.dt : null });
  ok('F3 the braking transition exists: the animator envelope ran (peak amount ' + fbMax.toFixed(2) + ' > 0.3) and the host flagged flight.braking', fbMax > 0.3 && rel.some(function (s) { return s.braking; }), { fb: fbAmt, braking: rel.map(function (s) { return s.braking; }) });
  var settled = rel.filter(function (s) { return s.dt >= 0.5; }); ok('F4 it SETTLES: by 0.5 s after the release the envelope is back at 0 (no oscillation, no lingering pose)', settled.length > 0 && settled.every(function (s) { return !s.fb || s.fb.amount < 0.05; }), { tail: settled.map(function (s) { return [s.dt, s.fb ? s.fb.amount : 0]; }) });
  ok('F5 no unwanted altitude change through the brake (|Δalt| < 0.35 m; FLY logic untouched)', altBefore !== null && altAfter !== null && Math.abs(altAfter - altBefore) < 0.35, { before: altBefore, after: altAfter });
  /* freeze-frame the transition for the eye: fly again, release, pause virtual time at ~0.15 s */
  await ev("P.send('MOVE', { forward: 1, strafe: 0, fast: true, yaw: 0 }); return 1;"); await sleep(2600); await ev("P.send('MOVE', { forward: 0, strafe: 0 }); return 1;"); await sleep(150); await shot('01_flight_brake_mid_transition'); await sleep(700); await shot('02_flight_settled_hover');
  /* low-speed: a short nudge then release must not fire the envelope */
  await sleep(800); await ev("P.send('MOVE', { forward: 1, strafe: 0, fast: false, yaw: 0 }); return 1;"); await sleep(260); await ev("P.send('MOVE', { forward: 0, strafe: 0 }); return 1;"); var low = []; for (var q2 = 0; q2 < 10; q2++) { await sleep(50); low.push(await sample()); } var lowMax = Math.max.apply(null, low.map(function (s) { return s.fb ? s.fb.amount : 0; })); var lowPeak = Math.max.apply(null, low.map(function (s) { return s.speed || 0; }));
  ok('F6 a low-speed stop (peak ' + lowPeak.toFixed(1) + ' m/s < 70 % of cruise) does NOT trigger the brake transition', lowPeak < 0.7 * cruise && lowMax < 0.05, { peak: lowPeak, fb_max: lowMax });
  /* B7 §1 — ONE-SHOT: a full-speed release fires exactly one brake event (host brake_seq +1, one animator envelope); 6 s of hover / drift afterwards fire none; a second release without new movement input fires none */
  var seqA = await ev("return P.snap().play.flight.brake_seq || 0;"); await ev("P.send('MOVE', { forward: 1, strafe: 0, fast: true, yaw: 0 }); return 1;"); await sleep(2600); await ev("P.send('MOVE', { forward: 0, strafe: 0 }); return 1;"); await sleep(200); var seqB = await ev("return P.snap().play.flight.brake_seq || 0;");
  var envStarts = 0, prevActive = false, maxAmt = 0; for (var h = 0; h < 60; h++) { await sleep(100); var sh = await sample(); var act = !!(sh.fb && sh.fb.active); if (act && !prevActive) envStarts++; prevActive = act; if (sh.fb && sh.fb.amount > maxAmt) maxAmt = sh.fb.amount; if (h === 30) await ev("P.send('MOVE', { forward: 0, strafe: 0 }); return 1;"); }   /* a second 'release' (neutral → neutral) mid-hover */
  var seqC = await ev("return P.snap().play.flight.brake_seq || 0;");
  ok('F7 ONE-SHOT: the full-speed release raised the host brake_seq by exactly 1 (' + seqA + ' → ' + seqB + ') and the animator envelope started exactly once (peak ' + maxAmt.toFixed(2) + ')', seqB === seqA + 1 && envStarts === 1 && maxAmt > 0.3, { seqA: seqA, seqB: seqB, envelope_starts: envStarts, peak: maxAmt });
  ok('F8 NO ROCKING: 6 s of hover / drift after the brake (and a repeated neutral input) fired no further brake event and no further envelope (seq ' + seqB + ' → ' + seqC + ')', seqC === seqB && envStarts === 1, { seqB: seqB, seqC: seqC, envelope_starts: envStarts });
  var altH0 = (await sample()).alt; await ev("P.send('FLIGHT',{op:'EXIT'}); return 1;"); var descStarts = 0, pd = false; for (var h2 = 0; h2 < 30; h2++) { await sleep(100); var sd = await sample(); var ad = !!(sd.fb && sd.fb.active); if (ad && !pd) descStarts++; pd = ad; } var seqD = await ev("return P.snap().play.flight.brake_seq || 0;");
  ok('F9 the landing descent (FLY exit, no joystick) never fires the brake (seq ' + seqC + ' → ' + seqD + ', envelope starts ' + descStarts + ')', seqD === seqC && descStarts === 0, { seqC: seqC, seqD: seqD, alt_before: altH0 });
  await sleep(1500);
  /* ---- GUIDE FORMATION ---- */
  await ev("var g=P.worldLayer().guides(); g.setGuide('MRS'); g.setVisible(true); return 1;"); await sleep(3500);
  var gd0 = await ev("var g=P.worldLayer().guides(); return g.debug();"); ok('G1 Mrs. Mah stays at her approved size (0.75 m, the 3× requirement is closed — never enlarged again)', gd0.height_m === 0.75 && gd0.on_stage, { height: gd0.height_m, on_stage: gd0.on_stage });
  var idleF = gd0.formation; ok('G2 idle formation: beside the shoulder — lateral distance 0.5–1.3 m, heading within 45° of the player (she does not stare sideways at the player)', idleF && idleF.lateral_m >= 0.5 && idleF.lateral_m <= 1.3 && Math.abs(idleF.yaw_vs_player_deg) <= 45, idleF);
  await shot('03_guide_formation_idle', true);
  /* walk a straight leg, then turn 90°, sampling the formation every 200 ms */
  var samples = []; await ev("P.send('MOVE', { forward: 1, strafe: 0, fast: false, yaw: 0 }); return 1;"); for (var s1 = 0; s1 < 12; s1++) { await sleep(200); samples.push(await ev("var g=P.worldLayer().guides(); var d=g.debug(); return { f: d.formation, settled: d.settled, cam: (function(){ var c=P.cameraDebug ? P.cameraDebug() : null; return c; })() };")); } await shot('04_guide_formation_walking', true);
  await ev("P.send('MOVE', { forward: 0, strafe: 1, fast: false, yaw: 1.5708 }); return 1;"); for (var s2 = 0; s2 < 10; s2++) { await sleep(200); samples.push(await ev("var g=P.worldLayer().guides(); var d=g.debug(); return { f: d.formation, settled: d.settled };")); } await ev("P.send('MOVE', { forward: 0, strafe: 0 }); return 1;");
  var lat = samples.map(function (s) { return s.f ? s.f.lateral_m : null; }); var yawD = samples.map(function (s) { return s.f ? Math.abs(s.f.yaw_vs_player_deg) : null; }); var latOk = lat.filter(function (v) { return v !== null; }).every(function (v) { return v >= 0.4 && v <= 1.8; }); var yawOk = yawD.slice(3).filter(function (v) { return v !== null; }).filter(function (v) { return v > 40; }).length <= 3;
  ok('G3 travelling + a 90° turn: she stays on the shoulder (0.4–1.8 m, never far off to the side) and matches the player heading (|Δyaw| ≤ 40° except a few frames of turn lag)', latOk && yawOk, { lateral: lat, yaw_delta: yawD });
  await sleep(2600); var stop = await ev("var g=P.worldLayer().guides(); return g.debug();"); ok('G4 after the stop she settles (companion brake done, settled weight rising, lateral back on the shoulder)', stop.formation && stop.formation.lateral_m <= 1.4 && (stop.companion_brake ? true : true), { formation: stop.formation, settled: stop.settled });
  await shot('05_guide_formation_stopped', true);
  /* flight formation */
  await ev("P.send('FLIGHT',{op:'ENTER'}); return 1;"); await sleep(600); await ev("P.send('FLIGHT',{op:'ASCEND'}); return 1;"); await sleep(1200); await ev("P.send('FLIGHT',{op:'HOVER'}); return 1;"); await ev("P.send('MOVE', { forward: 0, strafe: 1, fast: false, yaw: 1.5708 }); return 1;"); var fl = []; await sleep(600); for (var s3 = 0; s3 < 10; s3++) { await sleep(200); fl.push(await ev("var g=P.worldLayer().guides(); var d=g.debug(); var p=P.snap().play; return { f: d.formation, dy: d.pos ? +(d.pos[1] - (p.flight ? p.flight.altitude : 0)).toFixed(2) : null };")); } await shot('06_guide_formation_flight', true); await ev("P.send('MOVE', { forward: 0, strafe: 0 }); P.send('FLIGHT',{op:'EXIT'}); return 1;");
  ok('G5 in flight the formation holds (lateral 0.4–1.8 m, she rides at shoulder / head level above the player position)', fl.every(function (s) { return s.f && s.f.lateral_m >= 0.4 && s.f.lateral_m <= 1.8 && s.dy !== null && s.dy > 0.6 && s.dy < 2.4; }), { lateral: fl.map(function (s) { return s.f && s.f.lateral_m; }), dy: fl.map(function (s) { return s.dy; }) });
  R.errors = pg.errors.filter(function (e) { return !/404|favicon/.test(e); }).slice(0, 10);
} catch (e) { R.fatal = String(e && e.stack || e); console.error(e); } finally { fs.writeFileSync(path.join(OUT, 'flight_brake_guide.json'), JSON.stringify(R, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT flight_brake_guide ' + pass + ' / ' + (pass + fail) + (R.fatal ? ' FATAL' : '') + ' (EMULATED desktop headless — never iPhone acceptance)'); process.exit(fail || R.fatal ? 1 : 0);
