/* ASTRA M2 rendered acceptance — real static page, authoritative host, production models.
   Proves separated-leg rigidity, exercise pose arcs, real hand-socket equipment, Dogkie surface glide, and Phoenix clearance.
   node 26_LOCAL_AUTHORITY/deploy/joba/probe_m2_motion.mjs [static_dist] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var ROOT = path.resolve(HERE, '..', '..', '..');
var DIST = process.argv[2] ? path.resolve(process.argv[2]) : path.join(ROOT, '26_LOCAL_AUTHORITY', 'deploy', 'static_dist');
var OUT = path.join(ROOT, '25_HANDOFF', 'JOB_A', 'evidence', 'astra_m2'); fs.mkdirSync(OUT, { recursive: true });
var REG = JSON.parse(fs.readFileSync(path.join(ROOT, '26_LOCAL_AUTHORITY', 'lab', 'assets', 'world', 'world_registry_v1.json'), 'utf8'));
var pass = 0, fail = 0, checks = []; function ok(id, cond, detail) { (cond ? pass++ : fail++); var row = { id: id, pass: !!cond, detail: detail }; checks.push(row); console.log((cond ? 'PASS ' : 'FAIL ') + id + (detail === undefined ? '' : ' — ' + JSON.stringify(detail).slice(0, 700))); }
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1100, height: 760, dpr: 1.5, gpu: true });
async function ev(src) { return await pg.evaluate("(async function(){ var P=window.MAHWORLD_PLAY; " + src + " })()"); }
async function shot(name) { var f = path.join(OUT, name + '.png'); await pg.screenshot(f); return f; }
async function legMetric() { return await ev("var e=P.entity('me'), B=e&&e.fused&&e.fused.rig&&e.fused.rig.bones, T=P.THREE; if(!B) return null; var w=function(b){var v=new T.Vector3(); B[b].getWorldPosition(v); return v;}, d=function(a,b){return +w(a).distanceTo(w(b)).toFixed(6);}, s=function(b){return [+B[b].scale.x.toFixed(6),+B[b].scale.y.toFixed(6),+B[b].scale.z.toFixed(6)];}; return { form:P.snap().play.form, L:{hip_knee:d('THIGH_L','SHIN_L'),knee_tip:d('SHIN_L','TIP_L'),thigh_scale:s('THIGH_L'),shin_scale:s('SHIN_L')}, R:{hip_knee:d('THIGH_R','SHIN_R'),knee_tip:d('SHIN_R','TIP_R'),thigh_scale:s('THIGH_R'),shin_scale:s('SHIN_R')}, pose:P.poseOf('me',['PELVIS','SPINE','CHEST','UPPERARM_L','UPPERARM_R','FOREARM_L','FOREARM_R','THIGH_L','THIGH_R','SHIN_L','SHIN_R'])};"); }
async function sampleLegs(ms, label, every) { var rows = []; for (var t = 0; t < ms; t += (every || 90)) { await sleep(every || 90); var m = await legMetric(); if (m) { m.label = label; rows.push(m); } } return rows; }
function spread(rows, side, key) { var a = rows.map(function (r) { return r[side][key]; }); return a.length ? Math.max.apply(null, a) - Math.min.apply(null, a) : Infinity; }
function scaleDev(rows, side, key) { var mx = 0; rows.forEach(function (r) { (r[side][key] || []).forEach(function (v) { mx = Math.max(mx, Math.abs(v - 1)); }); }); return mx; }
async function gearStates(ms, ids) { var states = {}, frames = []; ids.forEach(function (id) { states[id] = {}; }); for (var t = 0; t < ms; t += 75) { await sleep(75); var q = await ev("var p=P.snap().play, d=P.worldLayer().gear().debug(); return { equipment:p.equipment, cast:p.rules&&p.rules.me.cast, entities:p.rules&&p.rules.entities, debug:d, pose:P.poseOf('me',['CLAV_L','CLAV_R','UPPERARM_L','UPPERARM_R','FOREARM_L','FOREARM_R','HAND_L','HAND_R']) }; "); frames.push(q); ids.forEach(function (id) { var it = q.equipment.manifested.filter(function (x) { return x.id === id; })[0]; if (it) states[id][it.state] = (states[id][it.state] || 0) + 1; }); } return { states: states, frames: frames }; }
async function resetCombat() { return await ev("var H=window.MAHWORLD_STATIC_HOST, pi=H.host.dev.play_internals(), rf=pi.rulesField(), st=rf.state(), id=Object.keys(st.combatants).filter(function(k){return st.combatants[k].kind==='PLAYER';})[0], me=rf.combatant(id); me.cooldowns={}; me.pool.refund(1000); return id;"); }
var report = { generated_at: new Date().toISOString(), source: 'local static_dist (not packaged / not published)', checks: checks, motion: {}, equipment: {}, dogkie: {}, phoenix: {}, screenshots: [], console_errors: pg.errors };

try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(5000); await ev("P.hud.showGuide(false); P.hud.setDev&&P.hud.setDev(false); P.camFollow(false); P.timeOfDay('NIGHT'); return 1;");
  await ev("return P.devPlay('PLACE',{x:20,z:30});"); await sleep(700); await ev("return P.send('TRANSFORM',{to:'SPLIT'});"); await sleep(2800); await ev("P.cam(2.7,0.08,4.6,0.92); return 1;"); await sleep(500);
  var idle = await sampleLegs(500, 'split_idle'); await ev("return P.send('MOVE',{forward:1,strafe:0,run:true,yaw:0});"); var walk = await sampleLegs(1500, 'split_run'); await shot('01_split_run'); report.screenshots.push('01_split_run.png'); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(500);
  var hingeStart = await ev("return P.send('RULES_CAST',{skill_id:'PA_HINGE'});"); await sleep(260); var hingePose = await legMetric(); await shot('02_rdl_loaded'); report.screenshots.push('02_rdl_loaded.png'); var hinge = await sampleLegs(1000, 'rdl');
  await ev("return P.send('FLIGHT',{op:'ENTER'});"); await sleep(600); await ev("return P.send('MOVE',{forward:1,strafe:0,run:true,yaw:0});"); var flight = await sampleLegs(1100, 'flight'); await shot('03_split_flight'); report.screenshots.push('03_split_flight.png'); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); return P.send('FLIGHT',{op:'EXIT'});"); await sleep(2200);
  var allLegs = idle.concat(walk, hinge, flight); report.motion.leg_samples = allLegs; report.motion.segment_spread_m = { L_hip_knee: spread(allLegs, 'L', 'hip_knee'), L_knee_tip: spread(allLegs, 'L', 'knee_tip'), R_hip_knee: spread(allLegs, 'R', 'hip_knee'), R_knee_tip: spread(allLegs, 'R', 'knee_tip') }; report.motion.max_scale_deviation = Math.max(scaleDev(allLegs, 'L', 'thigh_scale'), scaleDev(allLegs, 'L', 'shin_scale'), scaleDev(allLegs, 'R', 'thigh_scale'), scaleDev(allLegs, 'R', 'shin_scale')); report.motion.hinge = { cast: hingeStart, pose: hingePose };
  ok('M2.1 separated legs retain hip→knee and knee→tip bone lengths through idle/run/RDL/flight (≤0.1 mm spread)', Object.values(report.motion.segment_spread_m).every(function (v) { return v <= 0.0001; }), report.motion.segment_spread_m);
  ok('M2.2 no thigh/shin scaling or rubberization is used (scale deviation ≤1e-6)', report.motion.max_scale_deviation <= 0.000001, report.motion.max_scale_deviation);
  ok('M2.3 RDL cast is accepted and the loaded pose simultaneously uses pelvis/hip hinge, soft knees, neutral spine and hanging arms', !!(hingeStart && (hingeStart.accepted || hingeStart.ok)) && hingePose && hingePose.pose && hingePose.pose.composed && Math.abs(hingePose.pose.composed.PELVIS[0]) > 0.15 && Math.abs(hingePose.pose.composed.SHIN_L[0]) > 0.1 && Math.abs(hingePose.pose.composed.UPPERARM_L[0]) > 0.2, hingePose && hingePose.pose && hingePose.pose.composed);

  /* Real dumbbell sockets + X-Wave. */
  await ev("return P.send('EQUIP_DISMISS',{});"); await sleep(900); var dm = await ev("return P.send('EQUIP_MANIFEST',{kind:'DUMBBELL',count:2});"); await sleep(1900); var dbIds = await ev("return P.snap().play.equipment.manifested.map(function(x){return x.id;});"); for (var di = 0; di < dbIds.length; di++) await ev("return P.send('EQUIP_PICKUP',{id:'" + dbIds[di] + "'});"); await sleep(600); var dbGrip = await ev("return P.worldLayer().gear().debug();"); await shot('04_true_dumbbell_grips'); report.screenshots.push('04_true_dumbbell_grips.png');
  var target = await ev("var o=P.snap().play.rules.others.filter(function(x){return x.id==='FIELD_DUMMY';})[0]; return o&&o.position;"); await ev("P.send('LOCK_TARGET',{aim_id:null}); return P.devPlay('PLACE',{x:0,z:140});"); await sleep(450); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:3.14159});");
  var xcast = await ev("return P.send('RULES_CAST',{skill_id:'ATHLETE_X_WAVE'});"); var xobs = await gearStates(1900, dbIds); var xFrame = xobs.frames.filter(function (f) { return f.cast && f.cast.phase === 'STARTUP' && f.cast.progress >= 0.4; })[0]; var xLoad = xFrame && xFrame.pose; await resetCombat(); if (target) { await ev("return P.devPlay('PLACE',{x:" + target.x + ",z:" + (target.z + 5) + "});"); await sleep(350); await ev("P.send('LOCK_TARGET',{aim_id:'FIELD_DUMMY'}); return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); } await ev("return P.send('RULES_CAST',{skill_id:'ATHLETE_X_WAVE'});"); await sleep(480); await shot('05_xwave_katana_load'); report.screenshots.push('05_xwave_katana_load.png'); await sleep(1200); report.equipment.dumbbells = { manifest: dm, ids: dbIds, grip: dbGrip.grips, cast: xcast, load_pose: xLoad, states: xobs.states };
  ok('M2.4 both dumbbell derivative handles are centered on live palm sockets (reported palm error 0)', dbIds.length === 2 && dbGrip.grips.length === 2 && dbGrip.grips.every(function (g) { return g.grip && g.grip.palm_error_m === 0; }), dbGrip.grips);
  ok('M2.5 rendered X-Wave uses those two ids through IN_SPECIAL/PROJECTILE/RETURNING and the Katana load has strongly flexed elbows', dbIds.every(function (id) { var s = xobs.states[id]; return s.IN_SPECIAL && s.PROJECTILE && s.RETURNING; }) && xLoad && Math.abs(xLoad.composed.FOREARM_L[0]) > 0.6 && Math.abs(xLoad.composed.FOREARM_R[0]) > 0.6, { states: xobs.states, pose: xLoad && xLoad.composed });

  /* Real two-palm barbell + true press throw. */
  await ev("return P.send('EQUIP_DISMISS',{});"); await sleep(1000); var bm = await ev("return P.send('EQUIP_MANIFEST',{kind:'BARBELL',count:1});"); await sleep(2200); var barId = await ev("return P.snap().play.equipment.manifested[0].id;"); await ev("return P.send('EQUIP_PICKUP',{id:'" + barId + "'});"); await sleep(600); var barGrip = await ev("return P.worldLayer().gear().debug();"); await shot('06_true_barbell_grip'); report.screenshots.push('06_true_barbell_grip.png');
  await ev("P.send('LOCK_TARGET',{aim_id:null}); return P.devPlay('PLACE',{x:0,z:-50});"); await sleep(400); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); var pcast = await ev("return P.send('RULES_CAST',{skill_id:'ATHLETE_BARBELL_PRESS_THROW'});"); var pobs = await gearStates(2200, [barId]); var rackFrame = pobs.frames.filter(function (f) { return f.cast && f.cast.phase === 'STARTUP' && f.cast.progress >= 0.5; })[0]; var releaseFrame = pobs.frames.filter(function (f) { return f.cast && f.cast.phase === 'RECOVERY' && f.cast.progress >= 0.25 && f.cast.progress <= 0.55; })[0]; var rackPose = rackFrame && rackFrame.pose, releasePose = releaseFrame && releaseFrame.pose; await resetCombat(); await ev("return P.send('RULES_CAST',{skill_id:'ATHLETE_BARBELL_PRESS_THROW'});"); await sleep(620); await shot('07_press_throw_rack'); report.screenshots.push('07_press_throw_rack.png'); await sleep(620); await shot('08_press_throw_release'); report.screenshots.push('08_press_throw_release.png'); await sleep(1000); report.equipment.barbell = { manifest: bm, id: barId, grip: barGrip.grips, cast: pcast, rack_pose: rackPose, release_pose: releasePose, states: pobs.states };
  var bg = barGrip.grips.filter(function (g) { return g.id === barId; })[0]; ok('M2.6 barbell shaft is solved from both live palms (two sockets, zero midpoint error, nonzero hand span)', bg && bg.grip.sockets.join('|') === 'HAND_L|HAND_R' && bg.grip.palm_mid_error_m === 0 && bg.grip.hand_span_m > 0.2, bg);
  ok('M2.7 rendered Press Throw shows rack → overhead elbow extension and the same bar enters PROJECTILE/RETURNING', pcast && (pcast.accepted || pcast.ok) && rackPose && releasePose && Math.abs(rackPose.composed.FOREARM_L[0]) > Math.abs(releasePose.composed.FOREARM_L[0]) + 0.2 && Math.abs(releasePose.composed.UPPERARM_L[0]) > Math.abs(rackPose.composed.UPPERARM_L[0]) + 0.25 && pobs.states[barId].PROJECTILE && pobs.states[barId].RETURNING, { rack: rackPose && rackPose.composed, release: releasePose && releasePose.composed, states: pobs.states[barId] });

  /* Dogkie: sample actual presentation diagnostics over roam/chase/attack. */
  await ev("return P.send('EQUIP_DISMISS',{});"); var pack = REG.creatures.DOGKIE.pack_territories[0]; await ev("return P.devPlay('PLACE',{x:" + (pack.x + 4) + ",z:" + pack.z + "});"); await sleep(2600); var dog = await ev("var a=P.snap().play.creatures||[]; return a[0]||null;"); if (dog) { await ev("return P.devPlay('PLACE',{x:" + (dog.position.x + 3.2) + ",z:" + dog.position.z + "});"); await sleep(500); }
  var dSamples = [], dAttack = null; for (var ds = 0; ds < 90; ds++) { await sleep(100); var dq = await ev("var W=P.worldLayer(), g=W&&W.creatures&&W.creatures(); return { host:P.snap().play.creatures, debug:g&&g.debug?g.debug():null };"); dSamples.push(dq); if (!dAttack && dq.host && dq.host.some(function (x) { return x.state === 'ATTACK'; })) { dAttack = dq; await shot('09_dogkie_attack_lift'); report.screenshots.push('09_dogkie_attack_lift.png'); } }
  var ddbg = dSamples.filter(function (x) { return x.debug; }).slice(-1)[0]; var nonAttackMax = 0, attackMax = 0, dogStates = {}; dSamples.forEach(function (q) { (q.debug && q.debug.motion || []).forEach(function (m) { dogStates[m.state] = true; if (m.state === 'ATTACK') attackMax = Math.max(attackMax, m.hover_m); else nonAttackMax = Math.max(nonAttackMax, m.hover_m); }); }); report.dogkie = { contract: ddbg && ddbg.debug.motion_contract, states: Object.keys(dogStates), non_attack_max_hover_m: nonAttackMax, attack_max_lift_m: attackMax, sample_count: dSamples.length };
  ok('M2.8 Dogkie declares and renders SURFACE_GLIDE with no step cycle; non-attack hover stays low and the larger lift appears only in ATTACK', report.dogkie.contract && report.dogkie.contract.mode === 'SURFACE_GLIDE' && report.dogkie.contract.step_cycle === false && nonAttackMax <= 0.105 && (!dogStates.ATTACK || attackMax > nonAttackMax + 0.04), report.dogkie);

  /* Phoenix: ground-provoked route still remains above the terrain-relative floor. */
  var anchor = REG.ecology.species.PHOENIX.habitat.anchors[0]; await ev("return P.devPlay('PLACE',{x:" + anchor.x + ",z:" + anchor.z + "});"); await sleep(2500); await ev("return P.devPlay('WILDLIFE_SUMMON',{species:'PHOENIX'});"); await ev("P.cam(2.8,0.42,18,4.5); return 1;"); var phStates = {}, minClear = 1e9, sawSweep = false, phShot = false, phSamples = []; for (var ps = 0; ps < 150; ps++) { await sleep(100); var pq = await ev("var a=(P.snap().play.wildlife||[]).filter(function(x){return x.species==='PHOENIX';}); var W=P.worldLayer(), w=W&&W.wildlife&&W.wildlife(); return { phoenix:a, debug:w&&w.debug?w.debug():null };"); phSamples.push(pq); (pq.phoenix || []).forEach(function (x) { phStates[x.state] = true; minClear = Math.min(minClear, x.terrain_clearance_m); if (x.state === 'SWEEP') sawSweep = true; if (!phShot && (x.state === 'DIVE' || x.state === 'AERIAL_PASS')) phShot = true; }); if (phShot && ps > 25 && !report.screenshots.includes('10_phoenix_airborne_pass.png')) { await shot('10_phoenix_airborne_pass'); report.screenshots.push('10_phoenix_airborne_pass.png'); } }
  report.phoenix = { states: Object.keys(phStates), min_terrain_clearance_m: minClear, configured_min_m: REG.ecology.species.PHOENIX.habitat.min_terrain_clearance_m, old_sweep_seen: sawSweep, samples: phSamples.length };
  ok('M2.9 Phoenix uses WINDUP/DIVE/AERIAL_PASS/CLIMB with no old SWEEP and never breaches its 10 m terrain-relative floor', phStates.WINDUP && phStates.DIVE && phStates.AERIAL_PASS && !sawSweep && minClear + 0.01 >= report.phoenix.configured_min_m, report.phoenix);
  var unexpectedErrors = pg.errors.filter(function (e) { return !/favicon\.ico|athlete_m_preview\/dev_0\.(?:1|2|3|4|5|6|7|9|10|11|12|13)\/manifest\.json/.test(e); }); report.expected_probe_404s = pg.errors.length - unexpectedErrors.length; ok('M2.10 rendered page reports no unexpected runtime/console errors (known optional avatar-manifest probes and favicon 404s excluded)', unexpectedErrors.length === 0, unexpectedErrors.slice(0, 8));
} catch (e) { ok('M2.probe_exception', false, String(e && e.stack || e)); }

report.pass = pass; report.fail = fail; report.checks = checks; report.console_errors = pg.errors.slice(); fs.writeFileSync(path.join(OUT, 'm2_motion_report.json'), JSON.stringify(report, null, 1));
console.log('M2 rendered probe: ' + pass + ' pass / ' + fail + ' fail → ' + OUT); await pg.close(); srv.close(); process.exit(fail ? 1 : 0);
