import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = path.resolve(process.argv[2] || path.join(HERE, '..', 'static_dist')); var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 393, height: 852, dpr: 3, mobile: true, gpu: true });
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
await pg.goto(srv.origin + PLAY_PATH + '?field=1'); await waitForGame(pg, 150000); for (var i = 0; i < 300; i++) { var w = await ev("return P.world ? P.world().status : null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); } await sleep(3000);
var c = await ev("var sc=P.sceneDebug(); var by={}, byType={}; var total=0; function top(o){ var p=o; var name=null; while (p && p!==sc) { if (p.name) name=p.name; if (p.parent===sc) break; p=p.parent; } return (p&&p!==sc? (p.name||p.type) : (o.name||o.type)); } sc.children.forEach(function(ch){ var n=0, m=0, sk=0, sp=0; ch.traverse(function(o){ n++; if (o.isMesh) m++; if (o.isSkinnedMesh) sk++; if (o.isSprite) sp++; }); by[(ch.name||ch.type)+'#'+ch.children.length]=n+' (meshes '+m+', skinned '+sk+', sprites '+sp+')'; total+=n; }); sc.traverse(function(o){ byType[o.type]=(byType[o.type]||0)+1; }); return { total: total, byType: byType, children: by };");
console.log('total', c.total); console.log('byType', JSON.stringify(c.byType)); var rows = Object.keys(c.children).map(function (k) { return [k, c.children[k]]; }).sort(function (a, b) { return parseInt(b[1]) - parseInt(a[1]); }).slice(0, 14); rows.forEach(function (r) { console.log('  ', r[0], '→', r[1]); });
var w2 = await ev("var sc=P.sceneDebug(); var g=null; sc.traverse(function(o){ if (o.name==='MAHWORLD_WORLD_B' || (o.userData && o.userData.worldB)) g=o; }); var wl=P.worldLayer(); var grp = wl && wl.group ? wl.group : null; if (!grp) return null; var by={}; grp.children.forEach(function(ch){ var n=0; ch.traverse(function(){ n++; }); by[ch.name||ch.type]=(by[ch.name||ch.type]||0)+n; }); return by;"); console.log('world layer children:', JSON.stringify(w2));
await pg.close(); srv.close();
