/* JOB A — SHIELD SHEET real-runtime proof (owner 2026-09-18 §15): in the static demo (headless Chrome, GPU) the guard is a body-silhouette
   SHEET on the character's own skinned meshes (no ring), platinum for PHYSICAL, the class energy for MAHGIC; its integrity follows the host
   guard_sheet (bounded durability through the real balance); a break shatters it outward. Shots: sheet on (rear camera + a side inspection
   camera), after guarded Dogkie bites (dimmer / flickering), the break burst, the MAGICAL sheet; the console is watched for shader errors.
   node deploy/joba/probe_guard_sheet.mjs [out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var OUT = path.resolve(argv[0] || path.join(HERE, '..', 'probe_out', 'joba', 'guard_sheet')); fs.mkdirSync(OUT, { recursive: true });
var DIST = path.join(HERE, '..', 'static_dist'); var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1280, height: 800, gpu: true, unlockFps: true });
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function freeCam(from, at, fov) { await ev("var THREE=P.THREE; var r=P.rendererDebug(); if(!r.__orig){ r.__orig=r.render.bind(r); r.render=function(sc,cam){ if(window.__freecam){ r.__orig(sc, window.__freecam); } else r.__orig(sc,cam); }; } var c=new THREE.PerspectiveCamera(" + (fov || 40) + ", 1280/800, 0.1, 2400); c.position.set(" + from.join(',') + "); c.lookAt(" + at.join(',') + "); c.updateProjectionMatrix(); window.__freecam=c; return 1;"); }
async function shot(name, keepHud) { if (!keepHud) await ev("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;"); await sleep(120); await pg.screenshot(path.join(OUT, name + '.png')); await ev("document.querySelectorAll('body > *').forEach(function(e){ e.style.visibility=''; }); return 1;"); report.shots.push(name); console.log('shot', name); }
var report = { shots: [], notes: [], console_errors: [], checks: [] }; var pass = 0, fail = 0; function ok(id, cond, detail) { report.checks.push({ id: id, ok: !!cond, detail: detail }); if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + JSON.stringify(detail) : '')); } }
pg.on('Runtime.consoleAPICalled', function (p) { if (p.type !== 'error') return; var t = (p.args || []).map(function (a) { return a.value !== undefined ? String(a.value) : (a.description || ''); }).join(' '); if (/toNonIndexed/.test(t)) return; report.console_errors.push(t.slice(0, 400)); });
async function me() { return await ev("var p=P.snap().play; var r=p.rules; return { pos: p.position, facing: p.facing, guard: p.guard, sheet: p.guard_sheet, hp: r && r.me ? r.me.hp : null, creatures: (p.creatures||[]).map(function(c){ return { id: c.id, x: c.position.x, z: c.position.z, state: c.state }; }) };"); }
async function faceNearest() { var m = await me(); if (!m.creatures.length) return null; var best = null, bd = 1e9; m.creatures.forEach(function (c) { var d = Math.hypot(c.x - m.pos.x, c.z - m.pos.z); if (d < bd) { bd = d; best = c; } }); var yaw = Math.atan2(best.x - m.pos.x, -(best.z - m.pos.z)); await ev("P.send('MOVE', { forward: 0, strafe: 0, yaw: " + yaw.toFixed(3) + " }); return 1;"); return { c: best, d: bd, yaw: yaw }; }
async function sheetInfo() { return await ev("var e=P.entity('me'); if(!e) return null; return { built: e.sheet && e.sheet.built, meshes: e.sheet ? e.sheet.meshes.length : 0, visible: e.sheet ? e.sheet.meshes.filter(function(m){ return m.visible; }).length : 0, prevFrac: e.sheet && e.sheet.prevFrac, burstT: e.sheet && e.sheet.burstT };"); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(3000); await ev("P.hud.showGuide(false); return 1;");
  for (var i = 0; i < 240; i++) { var w = await ev("return P.world ? P.world().status : null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); } await sleep(2000);
  /* 1. the sheet ON in the open (no creature yet): rear camera + a side inspection camera; PHYSICAL = platinum */
  await ev("return P.devPlay('PLACE', { x: -30, z: -30 });"); await sleep(1200); var g1 = await ev("return P.send('GUARD', { kind: 'PHYSICAL' });"); await sleep(600); var m1 = await me(); var si1 = await sheetInfo();
  ok('1. PHYSICAL guard accepted; the SHEET is built on the body meshes (≥ 1 SkinnedMesh child) and visible; guard_sheet frac 1', g1 && g1.accepted && m1.guard === 'PHYSICAL' && m1.sheet && m1.sheet.frac === 1 && si1 && si1.built && si1.meshes >= 1 && si1.visible === si1.meshes, { g: g1 && g1.accepted, m: m1.sheet, si: si1 });
  await shot('01_sheet_physical_rear_camera', true); await freeCam([m1.pos.x + 2.6, 1.5, m1.pos.z + 1.2], [m1.pos.x, 1.0, m1.pos.z], 38); await shot('02_sheet_physical_side'); await freeCam([m1.pos.x - 1.2, 1.4, m1.pos.z - 2.6], [m1.pos.x, 1.0, m1.pos.z], 38); await shot('03_sheet_physical_front_quarter');
  var ringLeft = await ev("var n=0; P.sceneDebug().traverse(function(o){ if (o.geometry && o.geometry.type === 'TorusGeometry' && o.parent && o.parent.parent && o.visible && Math.abs(o.geometry.parameters.radius - 0.8) < 1e-6) n++; }); return n;");
  ok('2. the old guard RING (torus r 0.8) is gone from the scene', ringLeft === 0, { torus_rings_visible: ringLeft });
  await ev("window.__freecam=null; return P.send('GUARD', { kind: 'NONE' });"); await sleep(300);
  /* 2. MAGICAL guard = the class energy (Athlete gold) */
  var g2 = await ev("return P.send('GUARD', { kind: 'MAGICAL' });"); await sleep(500); var m2 = await me(); ok('3. MAGICAL guard accepted — the sheet takes the class energy colour', g2 && g2.accepted && m2.guard === 'MAGICAL', m2.guard);
  await freeCam([m2.pos.x + 2.6, 1.5, m2.pos.z + 1.2], [m2.pos.x, 1.0, m2.pos.z], 38); await shot('04_sheet_magical_side'); await ev("window.__freecam=null; return P.send('GUARD', { kind: 'NONE' });"); await sleep(300);
  /* 3. durability in the real fight: stand beside a Dogkie, guard PHYSICAL, face it; the bites drain the sheet; capture the dim sheet and the break */
  await ev("return P.devPlay('PLACE', { x: -70, z: 0 });"); await sleep(1500); var fn0 = await faceNearest(); report.notes.push('nearest at arrival ' + JSON.stringify(fn0));
  if (fn0) { await ev("return P.goTo(" + (fn0.c.x + 2.0) + ", " + (fn0.c.z + 1.4) + ", undefined, undefined, 30000);"); await sleep(300); }
  var g3 = await ev("return P.send('GUARD', { kind: 'PHYSICAL' });"); var fracs = [], broke = null, dimShot = false, t0 = Date.now();
  while (Date.now() - t0 < 40000 && !broke) { await faceNearest(); await sleep(80); var mm = await me(); if (mm.sheet) { var f = mm.sheet.frac; if (!fracs.length || fracs[fracs.length - 1] !== f) fracs.push(f); if (!dimShot && f < 0.75 && f > 0.05 && mm.guard) { dimShot = true; await shot('05_sheet_after_guarded_bites_rear', true); } if (!mm.guard && mm.sheet.broken) { broke = mm; await shot('06_sheet_break_burst', true); } } if (!mm.guard && !broke && Date.now() - t0 > 3000) { var re = await ev("return P.send('GUARD', { kind: 'PHYSICAL' });"); if (re && !re.accepted) report.notes.push('re-guard refused: ' + re.reason); } }
  var si3 = await sheetInfo();
  ok('4. guarded Dogkie bites DRAIN the sheet (frac steps down) and the host BREAKS it (guard null + broken) within 2–3 meaningful hits; the client shows the burst', g3 && g3.accepted && !!broke && fracs.length >= 3 && fracs.every(function (v, k) { return k === 0 || v <= fracs[k - 1] + 1e-9 || v === 1; }), { fracs: fracs.slice(0, 10), broke: broke && broke.sheet, si: si3, notes: report.notes });
  await sleep(500); var after = await me(); var re2 = await ev("return P.send('GUARD', { kind: 'PHYSICAL' });"); ok('5. after the break: no sheet drawn while the guard is down; a re-guard inside the lock window is refused (GUARD_BROKEN) or, once it re-forms, accepted', (await sheetInfo()).visible === 0 || (re2 && re2.accepted), { re2: re2 && (re2.accepted ? 'accepted' : re2.reason), after: after.sheet });
  await ev("return P.devPlay('PLACE', { x: 0, z: -40 });"); await sleep(600);
  report.errors = pg.errors.filter(function (e) { return !/404|favicon/.test(e); }).slice(0, 20);
  ok('6. no shader / console errors (the sheet material compiled on the skinned + morphed body)', report.console_errors.length === 0, report.console_errors.slice(0, 2));
} catch (e) { report.fatal = String(e && e.stack || e); console.error(e); } finally { report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'guard_sheet.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT probe_guard_sheet ' + pass + ' passed, ' + fail + ' failed' + (report.fatal ? ' FATAL' : '') + ' console_errors ' + report.console_errors.length);
