/* JOB A phone controls probe (emulated touch, portrait 393 × 852 @2× — NEVER iPhone acceptance): the ONE FLY control state machine
   (hold = climb, release = hold altitude, tap = descend to the support = landing, tap while descending = stop, ground tap = lift + hover),
   the SEPARATE / FUSE corner button (replaces DASH), the category strip (arrows + horizontal swipe, no attack fired, camera yaw unchanged),
   the tiny MAH GUIDE toggle under Health, and the absence of DOWN / LAND / DASH elements. node deploy/joba/probe_phone_controls.mjs */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var OUT = path.join(HERE, '..', 'probe_out', 'joba', 'phone_controls'); fs.mkdirSync(OUT, { recursive: true });
var DIST = path.join(HERE, '..', 'static_dist'); var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 393, height: 852, gpu: true, unlockFps: true, mobile: true, dpr: 2 });
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
var checks = []; function ok(id, cond, detail) { checks.push({ id: id, pass: !!cond, detail: detail }); console.log((cond ? 'PASS ' : 'FAIL ') + id + (cond ? '' : ' — ' + JSON.stringify(detail))); }
async function rect(id) { return await ev("var e=document.getElementById('" + id + "'); if(!e) return null; var r=e.getBoundingClientRect(); return { x: r.left + r.width/2, y: r.top + r.height/2, w: r.width, h: r.height, display: getComputedStyle(e).display };"); }
async function touch(x, y, downMs) { await pg.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x, y: y, id: 1 }] }); await sleep(downMs); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); }
async function swipe(x, y, dx, ms) { await pg.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x, y: y, id: 1 }] }); var n = 6; for (var i = 1; i <= n; i++) { await sleep(ms / n); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + dx * i / n, y: y, id: 1 }] }); } await pg.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); }
async function fl() { return await ev("var p=P.snap().play; return { powered: p.flight.powered, alt: +p.flight.altitude.toFixed(2), intent: p.flight.intent, exiting: p.flight.exiting, landed: p.flight.landed_count, form: p.form, mode: p.rules ? p.rules.me.attack_mode : null, cast: p.rules && p.rules.me.cast ? 1 : 0 };"); }
async function shot(n) { await pg.screenshot(path.join(OUT, n + '.png')); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(3000); await ev("P.hud.showGuide(false); return 1;"); await sleep(500);
  var present = await ev("return { desc: !!document.getElementById('g-desc'), land: !!document.getElementById('g-land'), flyaux: !!document.getElementById('g-flyaux'), dash: !!document.getElementById('tc-dash'), form: !!document.getElementById('tc-form'), fly: !!document.getElementById('g-fly'), guide: !!document.getElementById('g-mahguide'), catlbl: !!document.getElementById('g-catlbl'), prev: !!document.querySelector('[data-do=\"cat-prev\"]'), next: !!document.querySelector('[data-do=\"cat-next\"]'), attack: !!document.getElementById('tc-attack') };");
  ok('1. elements: ONE FLY control, SEPARATE/FUSE in the corner, MAH GUIDE toggle, category arrows; NO DOWN / LAND / DASH / generic ATTACK', present.fly && present.form && present.guide && present.catlbl && present.prev && present.next && !present.desc && !present.land && !present.flyaux && !present.dash && !present.attack, present);
  await shot('01_island');
  var fb = await rect('g-fly'); var f0 = await fl();
  /* hold = climb */ await pg.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: fb.x, y: fb.y, id: 1 }] }); await sleep(1500); var fh = await fl(); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(900); var fr = await fl();
  ok('2. FLY hold = take off and climb; release = hold the attained altitude (powered, vz ≈ 0, altitude kept)', fh.powered && fh.alt > 0.8 && fr.powered && fr.intent === 0 && Math.abs(fr.alt - fh.alt) < 2.5, { hold: fh, release: fr });
  await sleep(600); var fr2 = await fl(); ok('2b. altitude holds after release (no drift)', fr2.powered && Math.abs(fr2.alt - fr.alt) < 0.3, { a: fr, b: fr2 });
  await shot('02_hover');
  /* tap = descend */ await touch(fb.x, fb.y, 90); await sleep(300); var fd = await fl();   /* B8: a shorter look before the stop tap — the READY-gated boot climbs higher during the hold, so the descent must not reach the floor first */ ok('3. FLY tap while hovering = DESCEND (intent −1, altitude falling)', fd.powered && fd.intent < 0 && fd.alt < fr2.alt, { tap: fd, before: fr2 });
  /* tap while descending = stop */ await touch(fb.x, fb.y, 90); await sleep(700); var fs2 = await fl(); ok('4. FLY tap while descending = stop and hold', fs2.powered && fs2.intent === 0, fs2);
  /* hold while descending = climb */ await touch(fb.x, fb.y, 90); await sleep(300); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: fb.x, y: fb.y, id: 1 }] }); await sleep(900); var fc = await fl(); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(400);
  ok('5. FLY hold while descending = climb again', fc.powered && fc.intent > 0, fc);
  /* tap → descend all the way: the descent completes as the landing */ await touch(fb.x, fb.y, 90); var landed = null; for (var i = 0; i < 60; i++) { await sleep(250); landed = await fl(); if (!landed.powered) break; }
  ok('6. descending to the support completes as the LANDING (powered false, landed_count +1) — no LAND button', landed && !landed.powered && landed.landed > f0.landed, { before: f0, after: landed });
  await shot('03_landed');
  /* ground tap = lift + hover */ await touch(fb.x, fb.y, 90); await sleep(1400); var fg = await fl(); ok('7. FLY tap on the ground = lift into a hover', fg.powered && fg.intent === 0 && fg.alt > 0.3, fg);
  await touch(fb.x, fb.y, 90); for (var j = 0; j < 60; j++) { await sleep(250); var l2 = await fl(); if (!l2.powered) break; }
  /* SEPARATE / FUSE corner button */ var tf = await rect('tc-form'); var fm0 = await fl(); await touch(tf.x, tf.y, 90); await sleep(3200); var fm1 = await fl(); var lab1 = await ev("return document.getElementById('tc-form').textContent;"); await touch(tf.x, tf.y, 90); await sleep(3200); var fm2 = await fl(); var lab2 = await ev("return document.getElementById('tc-form').textContent;");
  ok('8. SEPARATE / FUSE corner button: tap = the H transform (FUSED → SPLIT → FUSED), the label shows the next transition', fm0.form === 'FUSED' && fm1.form === 'SPLIT' && fm2.form === 'FUSED' && /FUSE/.test(lab1) && /SEPARATE/.test(lab2), { f0: fm0.form, f1: fm1.form, f2: fm2.form, lab1: lab1, lab2: lab2 });
  await shot('04_form');
  /* category strip: arrows + swipe; no attack fired; camera yaw unchanged */ var yaw0 = await ev("return P.camState ? P.camState().yaw : null;"); var m0 = (await fl()).mode; var nx = await rect('g-catlbl'); 
  var pill = await rect('g-catlbl'); var flyR = await rect('g-fly'); var arrowsHidden = await ev("var a=document.querySelector('[data-do=\"cat-next\"]'); return !a || getComputedStyle(a).display === 'none';");
  ok('9. owner B7 §5: the attack-MODE control is a compact PILL directly LEFT of FLY (same row, its right edge within one gap of FLY, ≤ 30 px tall, arrows hidden) — no longer the strip under the quick slots', !!(pill && flyR && Math.abs(pill.y - flyR.y) < 8 && (pill.x + pill.w / 2) <= flyR.x - flyR.w / 2 && (flyR.x - flyR.w / 2) - (pill.x + pill.w / 2) <= 14 && pill.h <= 30 && arrowsHidden), { pill: pill, fly: flyR, arrows_hidden: arrowsHidden });
  await touch(pill.x, pill.y, 80); await sleep(400); var m1 = (await fl()).mode; await touch(pill.x, pill.y, 80); await sleep(400); await touch(pill.x, pill.y, 80); await sleep(400); var m2 = (await fl()).mode;
  ok('9b. tapping the pill cycles the mode (3 taps = back to the start); a mode change never casts', m1 !== m0 && m2 === m0 && !(await fl()).cast, { m0: m0, m1: m1, m2: m2 });
  var cx = await ev("var e=document.getElementById('g-cattext'); var r=e.getBoundingClientRect(); return { x: r.left + r.width/2, y: r.top + r.height/2 };"); await swipe(cx.x - 20, cx.y, 60, 180); await sleep(400); var m3 = await fl(); var yaw1 = await ev("return P.camState ? P.camState().yaw : null;");
  ok('10. horizontal swipe on the category strip = next category; no attack fired, the camera yaw untouched', m3.mode !== m0 && !m3.cast && (yaw0 === null || Math.abs(yaw1 - yaw0) < 1e-6), { m0: m0, m3: m3.mode, cast: m3.cast, yaw0: yaw0, yaw1: yaw1 });
  await shot('05_category');
  /* MAH GUIDE toggle */ var gr = await rect('g-mahguide'); await touch(gr.x, gr.y, 80); await sleep(2500); var gs = await ev("var g=P.worldLayer() && P.worldLayer().guides(); var d=g ? g.debug() : null; return { vis: d && d.visible, cur: d && d.current, on: d && d.on_stage, label: document.getElementById('g-mahguide').textContent };");
  ok('11. the tiny MAH GUIDE toggle under Health shows Mrs. Mah (default) — the JOB B guide layer', gs.vis === true && gs.cur === 'MRS' && gs.on === true && /MRS/.test(gs.label), gs); await shot('06_guide');
  await touch(gr.x, gr.y, 80); await sleep(400); var gs2 = await ev("var g=P.worldLayer().guides(); var d=g.debug(); return { vis: d.visible, label: document.getElementById('g-mahguide').textContent };"); ok('12. toggle again = hidden', gs2.vis === false && /GUIDE/.test(gs2.label), gs2);
  var errs = pg.errors.filter(function (e) { return !/404|favicon/.test(e); }); ok('Z. zero page / console errors', errs.length === 0, errs.slice(0, 3));
} catch (e) { ok('X. probe completed without an exception', false, String(e && e.stack || e).slice(0, 400)); } finally { fs.writeFileSync(path.join(OUT, 'phone_controls.json'), JSON.stringify({ touch: 'EMULATED (never iPhone acceptance)', checks: checks }, null, 1)); await pg.close(); srv.close(); }
var passN = checks.filter(function (c) { return c.pass; }).length; console.log('RESULT phone controls: ' + passN + ' passed, ' + (checks.length - passN) + ' failed'); process.exit(passN === checks.length ? 0 : 1);
