/* FLOOR FLICKER measurement (owner §7 / §18): a low inspection camera creeps along the temple causeway (the platinum floor + the region
   tint sheet + the causeway frame / core / seams + the forecourt disc + meadow at 10–140 m) and consecutive frames are diffed pixel by
   pixel inside the ground band. Z-fighting shows as pixels that flip hard between two frames while the camera moved 1.5 cm; a stable
   surface changes smoothly. Reports the flip fraction per pair plus the depth-buffer bits the context gives. Runs the same route on any
   static root so builds can be compared.   node deploy/joba/probe_floor_flicker.mjs [--dist <root>] [--label X] [--mobile] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import zlib from 'node:zlib';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from '../probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; }
var DIST = path.resolve(arg('--dist', path.join(HERE, '..', 'static_dist'))); var LABEL = arg('--label', 'run'); var MOBILE = argv.indexOf('--mobile') >= 0; var OUT = path.join(HERE, '..', 'probe_out', 'joba', 'flicker', LABEL); fs.mkdirSync(OUT, { recursive: true });
var W = MOBILE ? 393 : 960, H = MOBILE ? 852 : 540; var srv = await serveStatic(DIST); var pg = await launchChrome({ width: W, height: H, dpr: 1, mobile: MOBILE, gpu: true });
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function freeCam(from, at, fov) { await ev("var THREE=P.THREE; var r=P.rendererDebug(); if(!r.__orig){ r.__orig=r.render.bind(r); r.render=function(sc,cam){ if(window.__freecam){ r.__orig(sc, window.__freecam); } else r.__orig(sc,cam); }; } var c=window.__freecam || new THREE.PerspectiveCamera(" + (fov || 50) + ", " + W + "/" + H + ", P.cameraDebug && P.cameraDebug().near ? P.cameraDebug().near : 0.4, 1400); c.aspect=" + W + "/" + H + "; c.position.set(" + from.join(',') + "); c.lookAt(" + at.join(',') + "); c.updateProjectionMatrix(); window.__freecam=c; return 1;"); }
/* minimal PNG decode (8-bit RGB / RGBA, non-interlaced) — enough for Chrome's screenshots */
function decodePng(buf) { var p = 8, chunks = [], w = 0, h = 0, ct = 0; while (p < buf.length) { var len = buf.readUInt32BE(p); var type = buf.toString('ascii', p + 4, p + 8); var data = buf.slice(p + 8, p + 8 + len); if (type === 'IHDR') { w = data.readUInt32BE(0); h = data.readUInt32BE(4); ct = data[9]; } else if (type === 'IDAT') chunks.push(data); p += 12 + len; } var raw = zlib.inflateSync(Buffer.concat(chunks)); var bpp = ct === 6 ? 4 : 3; var stride = w * bpp; var out = Buffer.alloc(w * h * bpp); var prev = Buffer.alloc(stride); for (var y = 0; y < h; y++) { var f = raw[y * (stride + 1)]; var line = raw.slice(y * (stride + 1) + 1, (y + 1) * (stride + 1)); var cur = Buffer.alloc(stride); for (var i = 0; i < stride; i++) { var a = i >= bpp ? cur[i - bpp] : 0, b = prev[i], c = i >= bpp ? prev[i - bpp] : 0, x = line[i]; var v; if (f === 0) v = x; else if (f === 1) v = x + a; else if (f === 2) v = x + b; else if (f === 3) v = x + ((a + b) >> 1); else { var pa = Math.abs(b - c), pb = Math.abs(a - c), pc = Math.abs(a + b - 2 * c); v = x + (pa <= pb && pa <= pc ? a : (pb <= pc ? b : c)); } cur[i] = v & 255; } cur.copy(out, y * stride); prev = cur; } return { w: w, h: h, bpp: bpp, data: out }; }
function lum(img, x, y) { var i = (y * img.w + x) * img.bpp; return 0.299 * img.data[i] + 0.587 * img.data[i + 1] + 0.114 * img.data[i + 2]; }
var report = { label: LABEL, dist: DIST, mobile: MOBILE, pairs: [], depth_bits: null };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1'); await waitForGame(pg, 150000); for (var i = 0; i < 300; i++) { var w = await ev("return P.world ? P.world().status : null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); } await sleep(3000); await ev("P.hud.showGuide(false); return 1;");
  report.depth_bits = await ev("var gl=P.rendererDebug().getContext(); return gl.getParameter(gl.DEPTH_BITS);"); report.camera_near = await ev("return P.cameraDebug && P.cameraDebug().near !== undefined ? P.cameraDebug().near : null;");
  await ev("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;");
  var routes = [ { id: 'causeway_north', from: [3, 1.7, 60], at: [0, 0.3, 200], step: [0, 0, 0.015] }, { id: 'plaza_edge_east', from: [-40, 1.6, 30], at: [80, 0.2, 40], step: [0.015, 0, 0] }, { id: 'forecourt_gym', from: [-60, 2.2, 96], at: [-90, 0.3, 112], step: [-0.012, 0, 0.008] } ];
  for (var r = 0; r < routes.length; r++) { var R = routes[r]; var frames = []; for (var k = 0; k < 6; k++) { var from = [R.from[0] + R.step[0] * k, R.from[1] + R.step[1] * k, R.from[2] + R.step[2] * k]; await freeCam(from, R.at, 50); await sleep(260); var file = path.join(OUT, R.id + '_' + k + '.png'); await pg.screenshot(file); frames.push(decodePng(fs.readFileSync(file))); if (k > 0) fs.unlinkSync(path.join(OUT, R.id + '_' + (k - 1) + '.png')); }
    var y0 = Math.floor(H * 0.55), y1 = Math.floor(H * 0.98); var flips = [], total = (y1 - y0) * frames[0].w; for (var k2 = 1; k2 < frames.length; k2++) { var n = 0; for (var y = y0; y < y1; y += 1) for (var x = 0; x < frames[0].w; x += 1) { if (Math.abs(lum(frames[k2], x, y) - lum(frames[k2 - 1], x, y)) > 40) n++; } flips.push(+(100 * n / total).toFixed(3)); }
    var rec = { route: R.id, flip_pct_per_pair: flips, max_flip_pct: Math.max.apply(null, flips), mean_flip_pct: +(flips.reduce(function (a, b) { return a + b; }, 0) / flips.length).toFixed(3) }; report.pairs.push(rec); console.log(R.id, JSON.stringify(rec)); }
} catch (e) { report.fatal = String(e && e.stack || e); console.error(e); } finally { fs.writeFileSync(path.join(OUT, 'flicker.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT flicker ' + LABEL + ' depth_bits ' + report.depth_bits + ' near ' + report.camera_near + ' · ' + report.pairs.map(function (p) { return p.route + ' max ' + p.max_flip_pct + '% mean ' + p.mean_flip_pct + '%'; }).join(' · ') + (report.fatal ? ' FATAL' : ''));
