/* MAHWORLD :: MOCAP CLIP I/O (Spec F, PASS 6) — shared by validate_clip.mjs and import_clip.mjs: read a clip (runtime JSON or a GLB whose animation targets MAH joint names) into Euler XYZ frames, quaternion helpers, the rig's rest skeleton for FK. No three.js. */
import fs from 'node:fs'; import path from 'node:path';
export function quatToEulerXYZ(q) { var x = q[0], y = q[1], z = q[2], w = q[3]; var m11 = 1 - 2 * (y * y + z * z), m12 = 2 * (x * y - z * w), m13 = 2 * (x * z + y * w), m22 = 1 - 2 * (x * x + z * z), m23 = 2 * (y * z - x * w), m32 = 2 * (y * z + x * w), m33 = 1 - 2 * (x * x + y * y);
  var ey = Math.asin(Math.max(-1, Math.min(1, m13))); var ex, ez; if (Math.abs(m13) < 0.9999999) { ex = Math.atan2(-m23, m33); ez = Math.atan2(-m12, m11); } else { ex = Math.atan2(m32, m22); ez = 0; } return [ex, ey, ez]; }
export function readGlbClip(file) {
  var b = fs.readFileSync(file); var jl = b.readUInt32LE(12); var json = JSON.parse(b.slice(20, 20 + jl).toString('utf8')); var bl = b.readUInt32LE(20 + jl); var bin = b.slice(28 + jl, 28 + jl + bl);
  var CT = { 5120: Int8Array, 5121: Uint8Array, 5122: Int16Array, 5123: Uint16Array, 5125: Uint32Array, 5126: Float32Array }; var NC = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4 };
  function acc(i) { var a = json.accessors[i]; var bv = json.bufferViews[a.bufferView]; var off = (bv.byteOffset || 0) + (a.byteOffset || 0); var T = CT[a.componentType]; var n = NC[a.type]; return new T(bin.buffer.slice(bin.byteOffset + off, bin.byteOffset + off + a.count * n * T.BYTES_PER_ELEMENT)); }
  var anim = (json.animations || [])[0]; if (!anim) throw new Error('the GLB has no animation'); var tracks = {}; var maxT = 0, minDt = Infinity;
  anim.channels.forEach(function (ch) { var s = anim.samplers[ch.sampler]; var node = json.nodes[ch.target.node]; var name = node.name; var times = acc(s.input), vals = acc(s.output); var n = { SCALAR: 1, VEC3: 3, VEC4: 4 }; if (ch.target.path !== 'rotation' && !(ch.target.path === 'translation' && name === 'ROOT')) return;
    var w = ch.target.path === 'rotation' ? 4 : 3; var keys = []; for (var i = 0; i < times.length; i++) { keys.push({ t: times[i], v: Array.from(vals.slice(i * w, i * w + w)) }); if (i) minDt = Math.min(minDt, times[i] - times[i - 1]); maxT = Math.max(maxT, times[i]); }
    tracks[name + (ch.target.path === 'translation' ? '_POS' : '')] = { path: ch.target.path, keys: keys }; });
  var fps = isFinite(minDt) && minDt > 0 ? Math.round(1 / minDt) : 30; var nFrames = Math.max(1, Math.round(maxT * fps) + 1); var frames = [];
  for (var f = 0; f < nFrames; f++) { var t = f / fps; var row = {}; Object.keys(tracks).forEach(function (name) { var tr = tracks[name]; var k = tr.keys; var j = 0; while (j < k.length - 1 && k[j + 1].t <= t) j++; var a = k[j], b2 = k[Math.min(k.length - 1, j + 1)]; var u = b2.t > a.t ? Math.max(0, Math.min(1, (t - a.t) / (b2.t - a.t))) : 0; var v = a.v.map(function (x, i) { return x + (b2.v[i] - x) * u; }); if (tr.path === 'rotation') { var l = Math.hypot(v[0], v[1], v[2], v[3]) || 1; row[name] = quatToEulerXYZ(v.map(function (x) { return x / l; })); } else row['ROOT_POS'] = v; }); frames.push(row); }
  return { meta: { fps: fps, frames: nFrames, duration_s: +(nFrames / fps).toFixed(3), source: path.basename(file), format: 'glb' }, frames: frames };
}
export function readClip(file) { return /\.glb$/i.test(file) ? readGlbClip(file) : JSON.parse(fs.readFileSync(file, 'utf8')); }
export function restSkeleton(file) { var b = fs.readFileSync(file); var jl = b.readUInt32LE(12); var json = JSON.parse(b.slice(20, 20 + jl).toString('utf8')); var byName = {}, parent = {}; json.nodes.forEach(function (n, i) { byName[n.name] = i; (n.children || []).forEach(function (c) { parent[c] = i; }); }); var scale = 1; try { scale = JSON.parse(fs.readFileSync(path.join(path.dirname(file), 'manifest.json'), 'utf8')).scale_to_metres || 1; } catch (e) { } return { nodes: json.nodes, byName: byName, parent: parent, scale: scale }; }
export function mulQ(a, b) { return [a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1], a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0], a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3], a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2]]; }
export function eulerToQ(e) { var c1 = Math.cos(e[0] / 2), c2 = Math.cos(e[1] / 2), c3 = Math.cos(e[2] / 2), s1 = Math.sin(e[0] / 2), s2 = Math.sin(e[1] / 2), s3 = Math.sin(e[2] / 2); return [s1 * c2 * c3 + c1 * s2 * s3, c1 * s2 * c3 - s1 * c2 * s3, c1 * c2 * s3 + s1 * s2 * c3, c1 * c2 * c3 - s1 * s2 * s3]; }
export function rotV(q, v) { var ix = q[3] * v[0] + q[1] * v[2] - q[2] * v[1], iy = q[3] * v[1] + q[2] * v[0] - q[0] * v[2], iz = q[3] * v[2] + q[0] * v[1] - q[1] * v[0], iw = -q[0] * v[0] - q[1] * v[1] - q[2] * v[2]; return [ix * q[3] + iw * -q[0] + iy * -q[2] - iz * -q[1], iy * q[3] + iw * -q[1] + iz * -q[0] - ix * -q[2], iz * q[3] + iw * -q[2] + ix * -q[1] - iy * -q[0]]; }
export function tipWorldY(rig, row, bone) { var chain = []; var i = rig.byName[bone]; while (i !== undefined) { chain.unshift(i); i = rig.parent[i]; } var q = [0, 0, 0, 1], p = [0, 0, 0]; chain.forEach(function (ni) { var n = rig.nodes[ni]; var t = (n.translation || [0, 0, 0]).map(function (x) { return x * rig.scale; }); var tw = rotV(q, t); p = [p[0] + tw[0], p[1] + tw[1], p[2] + tw[2]]; var e = row[n.name]; var lq = e ? eulerToQ(e) : (n.rotation || [0, 0, 0, 1]); q = mulQ(q, lq); }); return p[1] + (row.ROOT_POS ? row.ROOT_POS[1] : 0); }
