/* MAHWORLD JOB A :: EQUIPMENT MANIFESTATION + MAHGIC ECONOMY (owner B8 §10–§15, 2026-09-20) — HOST AUTHORITY, all numbers from
   cfg.dev('equipment'). Mrs. Mah (any guide variant) MANIFESTS equipment for the player: EQUIP_MANIFEST { kind: DUMBBELL | BARBELL | BAND,
   count } → the guide casts for cast_s (the client plays her focus / cast), the item(s) materialise MANIFESTED in front of the player
   (dumbbells float at the clavicle line and follow the player, the barbell lies charged on the ground where it was cast, the band hangs in
   front); EQUIP_PICKUP { id } (a tap on the object within tap_radius_m) → HELD (no extra cost); EQUIP_DISMISS reclaims everything cleanly
   (dissolve, no orphaned objects); walking > walk_away_m from a ground item or idle_s reclaims it. FLOATING dumbbells / barbell populate the
   gear SPECIAL layer (RulesField.skillsFor); a HELD dumbbell multiplies the applicable physical strikes (RulesField gearMultFor). GUIDE
   CHARGE (not a level, not XP) fills only from verified damage dealt through the gear specials (RulesField onDamage hook); full → the guide
   dispenses reward_refills MAHGIC REFILL collectibles near the player and the charge rolls over. Collectibles are picked up by proximity:
   Combat MAHGIC below max → +amount (the pool never regenerates on its own), else inventory (cap, an overflow stays on the ground);
   USE_REFILL consumes one stored item. Crystal-bush RESOURCE NODES (registry resource_patches) are passive team-NODE synthetics: locked,
   struck → broken (drops refills), respawn after respawn_s. Everything is journaled; the client only presents. */
var TWO_PI = Math.PI * 2;
function num(v, d) { return typeof v === 'number' && isFinite(v) ? v : d; }
function hash01(a, b, c) { var h = 2166136261; [a, b, c].forEach(function (v) { var s = String(v); for (var i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; } }); return (h >>> 8) / 16777216; }   /* FNV-1a → [0, 1): the host stays replay-deterministic */
export function createEquipmentManager(o) {
  var cfg = o.cfg, H = o.H, rec = o.rec || function () { }, rf = o.rulesField, reg = o.registry || null; var EQ = cfg.dev('equipment') || {}; var M = EQ.manifest || {};
  var seq = 0; var collectibles = []; var nodes = []; var nodesBuilt = false; var unhook = null; var stats = { manifests: 0, pickups: 0, dismissals: 0, refills_spawned: 0, refills_picked: 0, refills_used: 0, overflow_held: 0, overflow_drop_suppressed: 0, dispenses: 0, nodes_broken: 0 };
  function eqOf(a) { if (!a.equip) a.equip = { manifested: [], held: null, charge: 0, refills: 0, casting: null, lastAction: H.t }; return a.equip; }
  function affinity(a) { var cls = a.rc ? a.rc.classId : 'ATHLETE'; return num((EQ.class_magic_affinity || {})[cls], 1); }
  function pool(a) { return a.rc && a.rc.pool ? a.rc.pool : null; }
  function front(a, fwd, side) { var f = a.facing || 0; return { x: a.pos.x + Math.sin(f) * fwd + Math.cos(f) * (side || 0), z: a.pos.z - Math.cos(f) * fwd + Math.sin(f) * (side || 0) }; }
  function groundY(a) { return a.fl ? (a.fl.ground || 0) : 0; }
  /* ---- manifest ---- */
  function manifest(a, kind, count) {
    kind = String(kind || 'DUMBBELL').toUpperCase(); var K = M[kind]; if (!K) return { ok: false, reason: 'BAD_EQUIPMENT_KIND' }; var eq = eqOf(a); if (eq.casting) return { ok: false, reason: 'GUIDE_CASTING' }; if (a.fl && a.fl.powered) return { ok: false, reason: 'AIRBORNE' };
    var n = kind === 'DUMBBELL' ? Math.max(1, Math.min(K.count_max || 3, Math.round(num(count, 2)))) : 1; var have = eq.manifested.filter(function (it) { return it.kind === kind; }).length; if (kind === 'DUMBBELL' && have + n > (K.count_max || 3)) n = Math.max(0, (K.count_max || 3) - have); if (n <= 0) return { ok: false, reason: 'COUNT_MAX' };
    if (kind === 'DUMBBELL' && have + n >= 3 && affinity(a) < num(K.third_requires_magic_affinity, 2)) return { ok: false, reason: 'MAGIC_AFFINITY_GATE', detail: { third_dumbbell_needs: K.third_requires_magic_affinity, have: affinity(a) } };
    var cost = 0; if (kind === 'DUMBBELL') { for (var i = have; i < have + n; i++) cost += (K.cost_by_count || [20, 30, 42])[Math.min(i, (K.cost_by_count || [20, 30, 42]).length - 1)]; } else cost = num(K.cost, 20);
    var P = pool(a); if (!P) return { ok: false, reason: 'NO_COMBAT_POOL' }; var st = P.state(); if (st.current + 1e-9 < cost) return { ok: false, reason: 'INSUFFICIENT_COMBAT_ENERGY', needed: cost, have: +st.current.toFixed(1) };
    /* incompatible set → reclaim first (dumbbells vs barbell vs band never share the space in front of the player) */ var incompatible = eq.manifested.filter(function (it) { return it.kind !== kind; }); if (incompatible.length) { incompatible.forEach(function (it) { it.state = 'RECLAIMING'; it.t0 = H.t; }); rec('EQUIP_RECLAIM', { account: a.account_id, why: 'INCOMPATIBLE_MANIFEST', kinds: incompatible.map(function (it) { return it.kind; }) }); }
    P.spend(cost, 'EQUIP_MANIFEST'); eq.casting = { kind: kind, count: n, t0: H.t, until: H.t + num(K.cast_s, 1), cost: cost }; eq.lastAction = H.t; stats.manifests++; rec('EQUIP_MANIFEST', { account: a.account_id, equipment: kind, count: n, cost: cost, cast_s: num(K.cast_s, 1) }); return { ok: true, kind: kind, count: n, cost: cost, cast_s: num(K.cast_s, 1) }; }
  function materialise(a, kind, n) { var eq = eqOf(a); var K = M[kind]; var have = eq.manifested.filter(function (it) { return it.kind === kind && it.state !== 'RECLAIMING'; }).length; for (var i = 0; i < n; i++) { var idx = have + i; var id = 'EQ_' + kind + '_' + (++seq); var total = have + n; var side = kind === 'DUMBBELL' ? (total === 1 ? 0 : (total === 2 ? (idx === 0 ? -0.7 : 0.7) : (idx === 0 ? 0 : (idx === 1 ? 1.2 : -1.2)))) * num(K.spacing_m, 0.5) : 0;   /* a pair straddles the centre line (±0.35 m) so a target straight ahead stays tappable between them; a trio = centre + two wider wings */ var fp = front(a, num(K.forward_m, 1), side); eq.manifested.push({ id: id, kind: kind, state: 'MANIFESTED', idx: idx, x: fp.x, z: fp.z, y: groundY(a) + num(K.height_m, 1.2), side: side, t0: H.t, ground: !!K.ground, anchor_x: a.pos.x, anchor_z: a.pos.z }); } rec('EQUIP_MATERIALISED', { account: a.account_id, equipment: kind, count: n }); }
  /* ---- pickup / dismiss / use ---- */
  function pickup(a, id) { var eq = eqOf(a); var it = eq.manifested.filter(function (x) { return x.id === id; })[0]; if (!it) return { ok: false, reason: 'NO_SUCH_EQUIPMENT' }; if (it.state !== 'MANIFESTED') return { ok: false, reason: 'NOT_MANIFESTED', state: it.state }; var d = Math.hypot(it.x - a.pos.x, it.z - a.pos.z); if (d > num(EQ.pickup && EQ.pickup.tap_radius_m, 2.4)) return { ok: false, reason: 'TOO_FAR', distance_m: +d.toFixed(2) };
    if (eq.held && eq.held.kind !== it.kind) return { ok: false, reason: 'HANDS_FULL', held: eq.held.kind }; it.state = 'HELD'; eq.held = { kind: it.kind, count: (eq.held && eq.held.kind === it.kind ? eq.held.count : 0) + 1, ids: (eq.held && eq.held.ids || []).concat([it.id]) }; eq.lastAction = H.t; stats.pickups++; rec('EQUIP_PICKUP', { account: a.account_id, id: id, equipment: it.kind, held_count: eq.held.count, cost: 0 }); return { ok: true, id: id, kind: it.kind, held_count: eq.held.count, multiplier: it.kind === 'DUMBBELL' ? EQ.held_damage_multiplier : null }; }
  function dismiss(a, why) { var eq = eqOf(a); if (a.rc && a.rc.cast && a.rc.cast.skill && a.rc.cast.skill.gear) return { ok: false, reason: 'EQUIPMENT_IN_SPECIAL', cast_id: a.rc.cast.cast_id }; var n = 0; eq.manifested.forEach(function (it) { if (it.state !== 'RECLAIMING') { it.state = 'RECLAIMING'; it.t0 = H.t; it.special = null; n++; } }); eq.held = null; eq.casting = null; stats.dismissals++; rec('EQUIP_DISMISS', { account: a.account_id, why: why || 'PLAYER', reclaimed: n }); return { ok: true, reclaimed: n }; }
  function useRefill(a) { var eq = eqOf(a); if (eq.refills <= 0) return { ok: false, reason: 'NO_REFILLS' }; var P = pool(a); if (!P) return { ok: false, reason: 'NO_COMBAT_POOL' }; var st = P.state(); if (st.current >= st.max - 1e-9) return { ok: false, reason: 'MAHGIC_FULL' }; eq.refills--; var amt = num(EQ.refill && EQ.refill.amount, 60); P.refund(amt); stats.refills_used++; rec('REFILL_USED', { account: a.account_id, amount: amt, inventory: eq.refills, current: +P.state().current.toFixed(1) }); return { ok: true, amount: amt, inventory: eq.refills, current: +P.state().current.toFixed(1) }; }
  /* ---- collectibles ---- */
  function spawnRefill(x, z, y, why, source) { if (source) { var held = collectibles.filter(function (c) { return c.source === source && c.protected_overflow; })[0]; if (held) { stats.overflow_drop_suppressed++; rec('REFILL_DROP_SUPPRESSED', { source: source, why: 'PROTECTED_OVERFLOW_ALREADY_PRESENT', existing: held.id }); return held.id; } } var id = 'RF_' + (++seq); collectibles.push({ id: id, kind: 'MAHGIC_REFILL', x: x, z: z, y: y, born: H.t, why: why, source: source || null, protected_overflow: false }); stats.refills_spawned++; return id; }
  function dispense(a) { var eq = eqOf(a); var GC = EQ.guide_charge || {}; var n = num(GC.reward_refills, 3); var r = num(GC.dispense_radius_m, 1.6), spawned = 0; for (var i = 0; i < n; i++) { var ang = i / n * TWO_PI + (a.facing || 0), before = stats.refills_spawned; spawnRefill(a.pos.x + Math.sin(ang) * r, a.pos.z - Math.cos(ang) * r, groundY(a) + 0.5, 'GUIDE_CHARGE', 'GUIDE_' + a.account_id + '_' + i); if (stats.refills_spawned > before) spawned++; } eq.charge = Math.max(0, eq.charge - 1); eq.dispense_t = H.t; stats.dispenses++; rec('GUIDE_DISPENSE', { account: a.account_id, refills: spawned, requested: n, suppressed: n - spawned, charge_left: +eq.charge.toFixed(3) }); }
  function onDamage(ev) { if (!ev.gear_special || !ev.source || !ev.source.actor || ev.applied <= 0) return; var a = ev.source.actor; if (!a.account_id) return; var eq = eqOf(a); var GC = EQ.guide_charge || {}; eq.charge += ev.applied / Math.max(1, num(GC.full_at_damage, 1500)); eq.charge_hits = (eq.charge_hits || 0) + 1; if (eq.charge >= 1) dispense(a); }
  /* ---- resource nodes ---- */
  function buildNodes(players) { var f = rf(); if (!f || nodesBuilt) return; nodesBuilt = true; var patches = (reg && reg.resource_patches && reg.resource_patches.list) || []; var B = EQ.bush || {}; var base = f.baselineHit ? f.baselineHit(null) : null; var hp = base ? base.applied * num(B.hits_to_break, 2) : 168;
    patches.forEach(function (Pt, i) { var id = 'NODE_' + Pt.id; var c = f.spawnSynthetic(id, 'ATHLETE', 'NODE', { x: Pt.x, z: Pt.z }, { facing: 0, passive: true, respawn_s: null, hp_abs: hp, altitude: num(Pt.y, 0), node: { kind: 'CRYSTAL_BUSH', family: Pt.family || 'gold', patch: Pt.id, target_radius_m: num(Pt.r, 0) } }); c.altitude = num(Pt.y, 0); nodes.push({ id: id, patch: Pt, c: c, broken_t: null, respawn_at: null, hp_max: hp }); }); rec('RESOURCE_NODES_BUILT', { count: nodes.length, hp: +hp.toFixed(1) }); }
  function tickNodes() { var f = rf(); if (!f) return; var B = EQ.bush || {}; nodes.forEach(function (N) { var c = f.combatant(N.id); if (c && c.ko && N.broken_t === null) { N.broken_t = H.t; N.respawn_at = H.t + num(B.respawn_s, 90); var drops = B.drops || [2, 3]; var hb = hash01(N.id, stats.nodes_broken, H.tick || 0); var n = drops[0] + Math.floor(hb * (drops[1] - drops[0] + 1)), spawned = 0; for (var i = 0; i < n; i++) { var ang = (i / n) * TWO_PI + hb * TWO_PI, r = 0.8 + 0.5 * hash01(N.id, i, 'r'), before = stats.refills_spawned;   /* deterministic (replayable) count + an even fan around the patch, never Math.random */ spawnRefill(N.patch.x + Math.cos(ang) * r, N.patch.z + Math.sin(ang) * r, num(N.patch.y, 0) + 0.45, 'BUSH', N.id); if (stats.refills_spawned > before) spawned++; } stats.nodes_broken++; rec('RESOURCE_NODE_BROKEN', { id: N.id, by: c.last_hit_from ? 'player' : null, drops: spawned, requested: n, suppressed: n - spawned, respawn_s: num(B.respawn_s, 90) }); f.removeSynthetic(N.id); }
      if (N.broken_t !== null && H.t >= N.respawn_at) { var c2 = f.spawnSynthetic(N.id, 'ATHLETE', 'NODE', { x: N.patch.x, z: N.patch.z }, { facing: 0, passive: true, respawn_s: null, hp_abs: N.hp_max, altitude: num(N.patch.y, 0), node: { kind: 'CRYSTAL_BUSH', family: N.patch.family || 'gold', patch: N.patch.id, target_radius_m: num(N.patch.r, 0) } }); c2.altitude = num(N.patch.y, 0); N.c = c2; N.broken_t = null; N.respawn_at = null; rec('RESOURCE_NODE_RESPAWN', { id: N.id }); } }); }
  /* ---- tick ---- */
  function syncSpecial(a, eq) { var cast = a.rc && a.rc.cast && a.rc.cast.skill && a.rc.cast.skill.gear ? a.rc.cast : null; var active = {}; if (cast) (cast.equipment_ids || []).forEach(function (id) { active[id] = true; }); eq.manifested.forEach(function (it) {
      if (cast && active[it.id]) { if (!it.special || it.special.cast_id !== cast.cast_id) { var home = it.state === 'HELD' ? 'HELD' : 'MANIFESTED'; it.special = { cast_id: cast.cast_id, skill: cast.skill.id, equipment_id: it.id, return_state: home, started_t: H.t, projectile_seen: false, returning: false }; rec('EQUIP_SPECIAL_STATE', { account: a.account_id, cast_id: cast.cast_id, equipment_id: it.id, from: home, to: 'IN_SPECIAL', skill: cast.skill.id }); } it.special.phase = cast.phase; it.special.progress = +(cast.t / Math.max(0.01, cast.phase === 'STARTUP' ? cast.startup : cast.recovery || 1)).toFixed(3); var travels = /ATHLETE_X_WAVE|BARBELL_PRESS_THROW/.test(cast.skill.id); var field = rf(); var projectileAlive = !!(field && field.state && field.state().entities.some(function (e) { return e.type === 'PROJECTILE' && e.cast_id === cast.cast_id; })); if (projectileAlive) it.special.projectile_seen = true; if (travels && cast.phase === 'RECOVERY' && it.special.projectile_seen && !projectileAlive) it.special.returning = true; if (it.special.returning) { if (it.state !== 'RETURNING') { rec('EQUIP_SPECIAL_STATE', { account: a.account_id, cast_id: cast.cast_id, equipment_id: it.id, from: it.state, to: 'RETURNING', skill: cast.skill.id }); it.t0 = H.t; it.return_until = H.t + 0.28; } it.state = 'RETURNING'; return; } it.state = cast.phase === 'RECOVERY' && travels ? 'PROJECTILE' : 'IN_SPECIAL'; it.t0 = it.special.started_t; return; }
      if (!it.special) return; if (it.state !== 'RETURNING') { it.state = 'RETURNING'; it.t0 = H.t; it.return_until = H.t + 0.28; rec('EQUIP_SPECIAL_STATE', { account: a.account_id, cast_id: it.special.cast_id, equipment_id: it.id, from: 'IN_SPECIAL', to: 'RETURNING', skill: it.special.skill }); } if (H.t + 1e-9 >= it.return_until) { var restored = it.special.return_state === 'HELD' && eq.held && (eq.held.ids || []).indexOf(it.id) >= 0 ? 'HELD' : 'MANIFESTED'; rec('EQUIP_SPECIAL_STATE', { account: a.account_id, cast_id: it.special.cast_id, equipment_id: it.id, from: 'RETURNING', to: restored, skill: it.special.skill }); it.state = restored; it.special = null; it.return_until = null; it.t0 = H.t; }
    }); }
  function tick(dt, players) { var f = rf(); if (f && !unhook && f.onDamage) unhook = f.onDamage(onDamage); if (f && !nodesBuilt) buildNodes(players); if (nodesBuilt) tickNodes(); var RF = EQ.refill || {}; var DM = EQ.dismiss || {};
    (players || []).forEach(function (a) { var eq = a.equip; if (eq) {
      if (eq.casting && H.t >= eq.casting.until) { materialise(a, eq.casting.kind, eq.casting.count); eq.casting = null; eq.lastAction = H.t; }
      syncSpecial(a, eq);
      for (var i = eq.manifested.length - 1; i >= 0; i--) { var it = eq.manifested[i]; var K = M[it.kind] || {};
        if (it.state === 'RECLAIMING') { if (H.t - it.t0 > 0.7) eq.manifested.splice(i, 1); continue; }
        if (it.state === 'MANIFESTED' && !it.ground) { var fp = front(a, num(K.forward_m, 1), it.side || 0); var k = Math.min(1, dt * num(K.follow_mps, 3)); it.x += (fp.x - it.x) * k; it.z += (fp.z - it.z) * k; it.y = groundY(a) + num(K.height_m, 1.2) + num(K.hover_amp_m, 0.04) * Math.sin(H.t * 2.1 + (it.idx || 0) * 1.7); }
        if (it.state === 'HELD' || it.state === 'IN_SPECIAL' || it.state === 'PROJECTILE' || it.state === 'RETURNING') { it.x = a.pos.x; it.z = a.pos.z; it.y = groundY(a) + 1.0; }
        if (it.state === 'MANIFESTED' && it.ground && Math.hypot(a.pos.x - it.x, a.pos.z - it.z) > num(DM.walk_away_m, 14)) { it.state = 'RECLAIMING'; it.t0 = H.t; rec('EQUIP_RECLAIM', { account: a.account_id, id: it.id, why: 'WALKED_AWAY' }); }
        if (it.state === 'MANIFESTED' && H.t - eq.lastAction > num(DM.idle_s, 120)) { it.state = 'RECLAIMING'; it.t0 = H.t; rec('EQUIP_RECLAIM', { account: a.account_id, id: it.id, why: 'IDLE' }); } }
      if (eq.held && !eq.manifested.some(function (it) { return it.state === 'HELD' || (it.special && it.special.return_state === 'HELD'); })) eq.held = null; }
      /* collectible pickup by proximity */ for (var ci = collectibles.length - 1; ci >= 0; ci--) { var col = collectibles[ci]; if (Math.hypot(col.x - a.pos.x, col.z - a.pos.z) > num(RF.pickup_radius_m, 1.4) || (a.fl && a.fl.powered && (a.fl.altitude || 0) > 2.5)) continue; var eq2 = eqOf(a); var P = pool(a); if (!P) continue; var st = P.state(); if (st.current < st.max - 1e-9) { var amt = num(RF.amount, 60); var before = st.current; P.refund(amt); stats.refills_picked++; rec('REFILL_PICKED', { account: a.account_id, id: col.id, to: 'MAHGIC', amount: amt, before: +before.toFixed(1), after: +P.state().current.toFixed(1) }); collectibles.splice(ci, 1); } else if (eq2.refills < num(RF.inventory_cap, 999)) { eq2.refills++; stats.refills_picked++; rec('REFILL_PICKED', { account: a.account_id, id: col.id, to: 'INVENTORY', inventory: eq2.refills }); collectibles.splice(ci, 1); } else if (!col.protected_overflow) { col.protected_overflow = true; stats.overflow_held++; rec('REFILL_OVERFLOW_HELD', { account: a.account_id, id: col.id, drop_kind: col.why, source: col.source, inventory: eq2.refills, cap: num(RF.inventory_cap, 999) }); } /* payload must not overwrite rec()'s event kind; at full+cap every earned refill remains collectible and is explicitly journaled */ } });
    for (var cj = collectibles.length - 1; cj >= 0; cj--) if (!collectibles[cj].protected_overflow && H.t - collectibles[cj].born > num(RF.lifetime_s, 150)) collectibles.splice(cj, 1); }
  /* ---- views ---- */
  function viewFor(a) { var eq = eqOf(a); var P = pool(a); return { manifested: eq.manifested.map(function (it) { return { id: it.id, kind: it.kind, state: it.state, x: +it.x.toFixed(3), y: +it.y.toFixed(3), z: +it.z.toFixed(3), side: it.side || 0, idx: it.idx || 0, age_s: +(H.t - it.t0).toFixed(2), special: it.special ? { cast_id: it.special.cast_id, equipment_id: it.special.equipment_id, skill: it.special.skill, phase: it.special.phase, progress: it.special.progress, return_state: it.special.return_state } : null }; }), held: eq.held ? { kind: eq.held.kind, count: eq.held.count, ids: (eq.held.ids || []).slice(), multiplier: eq.held.kind === 'DUMBBELL' ? EQ.held_damage_multiplier : 1 } : null, casting: eq.casting ? { kind: eq.casting.kind, count: eq.casting.count, progress: +Math.min(1, (H.t - eq.casting.t0) / Math.max(0.01, eq.casting.until - eq.casting.t0)).toFixed(3) } : null, guide_charge: +Math.min(1, eq.charge).toFixed(3), guide_charge_hits: eq.charge_hits || 0, dispensed_at: eq.dispense_t || null, refills: eq.refills, refill_amount: num((EQ.refill || {}).amount, 60), inventory_cap: num((EQ.refill || {}).inventory_cap, 999), affinity: affinity(a), combat_mahgic: P ? { current: +P.state().current.toFixed(1), max: P.state().max } : null, costs: { DUMBBELL: (M.DUMBBELL || {}).cost_by_count, BARBELL: (M.BARBELL || {}).cost, BAND: (M.BAND || {}).cost } }; }
  function collectiblesView() { return collectibles.map(function (c) { return { id: c.id, kind: c.kind, x: +c.x.toFixed(2), y: +c.y.toFixed(2), z: +c.z.toFixed(2), age_s: +(H.t - c.born).toFixed(1), overflow_held: !!c.protected_overflow, source: c.source || null }; }); }
  function nodesView() { var f = rf(); return nodes.map(function (N) { var c = f ? f.combatant(N.id) : null; return { id: N.id, patch: N.patch.id, x: N.patch.x, z: N.patch.z, y: num(N.patch.y, 0), family: N.patch.family || 'gold', r: N.patch.r || 2.2, hp: c ? +c.hp.toFixed(1) : 0, max: N.hp_max, broken: N.broken_t !== null, respawn_in_s: N.respawn_at !== null ? +Math.max(0, N.respawn_at - H.t).toFixed(1) : null }; }); }
  function summary() { return { enabled: true, data: { held_multiplier: EQ.held_damage_multiplier, refill_amount: (EQ.refill || {}).amount, guide_full_at: (EQ.guide_charge || {}).full_at_damage, reward_refills: (EQ.guide_charge || {}).reward_refills }, nodes: nodes.length, collectibles: collectibles.length, stats: stats }; }
  return { enabled: true, manifest: manifest, pickup: pickup, dismiss: dismiss, useRefill: useRefill, tick: tick, viewFor: viewFor, collectibles: collectiblesView, nodes: nodesView, summary: summary, spawnRefill: spawnRefill, eqOf: eqOf };
}
