/* MAH HALO arcade volleyball — a compact host-owned activity layered onto the
   existing FIELD authority. It owns one ball and one bot, awards no combat or
   progression outcomes, and never opens a second movement/combat simulation. */
import { HALO_LAYOUT, HALO_PLAY_LAYOUT } from './haloLayout.js';

function clamp(v, a, b) { return Math.max(a, Math.min(b, v)); }
function distance3(a, b) { return Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z); }

export function createHaloSport(ctx) {
  var H = ctx.H, rec = ctx.rec, bump = ctx.bump, L = HALO_PLAY_LAYOUT, sessions = {};
  var gravity = -12.5, floorY = L.center.altitude_m + L.ball_radius_m;

  function session(a) { return a && sessions[a.account_id] || null; }
  function ballAtServe(a) { return { x: a.pos.x + 0.55, y: HALO_LAYOUT.arrival_height_m + 1.25, z: a.pos.z, vx: 0, vy: 0, vz: 0 }; }
  function insideCourt(x, z) { return Math.abs(x - L.center.x) <= L.half_length_m && Math.abs(z - L.center.z) <= L.half_width_m; }
  function targetById(id) { return L.targets.filter(function (t) { return t.id === id; })[0] || L.targets[1]; }
  function setServe(a, s) { s.rally_id++; s.phase = 'SERVE_READY'; s.point = null; s.phase_t = H.t; s.last_hitter = null; s.net_touched = false; s.ball = ballAtServe(a); s.bot.x = L.bot_start.x; s.bot.z = L.bot_start.z; s.bot.contact_t = -99; s.bot.style = null; }
  function sendBall(s, x, z, duration, style, who) { var b = s.ball, t = Math.max(0.55, duration); b.vx = (x - b.x) / t; b.vz = (z - b.z) / t; b.vy = (floorY - b.y - 0.5 * gravity * t * t) / t; s.last_hitter = who; s.net_touched = false; s.contact_seq++; s.last_contact = { seq: s.contact_seq, rally_id: s.rally_id, who: who, style: style, at_t: H.t, position: { x: +b.x.toFixed(3), y: +b.y.toFixed(3), z: +b.z.toFixed(3) } }; rec('HALO_SPORT_CONTACT', { account: s.account_id, mode: s.mode, who: who, style: style, rally_id: s.rally_id, contact_seq: s.contact_seq, position: s.last_contact.position }); }
  function finishVolley(s, winner, why, landing) { if (s.phase !== 'RALLY') return; s.score[winner]++; s.point = { rally_id: s.rally_id, winner: winner, why: why, landing: landing, at_t: H.t }; s.phase_t = H.t; if (s.score[winner] >= L.first_to) { s.phase = 'RESULT'; s.result = winner === 'PLAYER' ? 'PLAYER_WON' : 'BOT_WON'; rec('HALO_VOLLEY_RESULT', { account: s.account_id, rally_id: s.rally_id, score: s.score, result: s.result, no_rewards: true }); } else { s.phase = 'POINT'; rec('HALO_VOLLEY_POINT', { account: s.account_id, rally_id: s.rally_id, winner: winner, why: why, score: s.score }); } bump(); }
  function finishPractice(a, s, landing) { if (s.phase !== 'IN_FLIGHT') return; var target = targetById(s.target_id), d = Math.hypot(landing.x - target.x, landing.z - target.z), hit = insideCourt(landing.x, landing.z) && d <= target.radius_m; s.attempts++; if (hit) s.hits++; s.point = { winner: hit ? 'TARGET' : 'MISS', why: hit ? 'TARGET_HIT' : 'TARGET_MISSED', landing: landing, target: target.id, error_m: +d.toFixed(3), at_t: H.t }; s.phase_t = H.t; if (s.attempts >= L.practice_serves) { s.phase = 'RESULT'; s.result = s.hits >= 3 ? 'PRACTICE_COMPLETE' : 'PRACTICE_RETRY'; rec('HALO_PRACTICE_RESULT', { account: s.account_id, hits: s.hits, attempts: s.attempts, no_rewards: true }); } else { s.phase = 'POINT'; rec('HALO_PRACTICE_ATTEMPT', { account: s.account_id, hit: hit, target: target.id, error_m: +d.toFixed(3), attempt: s.attempts }); } bump(); }
  function start(a, mode) { mode = String(mode || '').toUpperCase(); if (mode !== 'VOLLEY' && mode !== 'PRACTICE') return { ok: false, reason: 'BAD_HALO_SPORT_MODE' }; if (!a || a.room !== 'FIELD' || a.domain !== 'HALO') return { ok: false, reason: 'HALO_ONLY' }; if (a.transit) return { ok: false, reason: 'TRANSIT_IN_PROGRESS' }; if (a.fl.powered || a.fl.altitude > HALO_LAYOUT.arrival_height_m + 0.05) return { ok: false, reason: 'LAND_FIRST' }; if (Math.hypot(a.pos.x - L.entry.x, a.pos.z - L.entry.z) > L.entry.range_m + 0.75) return { ok: false, reason: 'NOT_AT_HALO_COURT' }; if (session(a)) return { ok: false, reason: 'HALO_SPORT_ACTIVE' };
    var s = { account_id: a.account_id, mode: mode, phase: 'SERVE_READY', phase_t: H.t, started_t: H.t, score: { PLAYER: 0, BOT: 0 }, attempts: 0, hits: 0, target_id: 'CENTER', point: null, result: null, rally_id: 0, contact_seq: 0, last_contact: null, last_hitter: null, net_touched: false, saved: { x: a.pos.x, z: a.pos.z, facing: a.facing }, bot: { x: L.bot_start.x, z: L.bot_start.z, contact_t: -99, style: null }, ball: null };
    sessions[a.account_id] = s; a.pos.x = L.player_start.x; a.pos.z = L.player_start.z; a.facing = Math.PI / 2; a.moveVec = { forward: 0, strafe: 0, run: false, fast: false }; a.vel = { x: 0, z: 0 }; a.nav = null; a.guard = null; setServe(a, s); rec('HALO_SPORT_START', { account: a.account_id, mode: mode, no_rewards: true, equipment_stowed_visual_only: true }); bump(); return { ok: true, mode: mode, first_to: mode === 'VOLLEY' ? L.first_to : null, serves: mode === 'PRACTICE' ? L.practice_serves : null };
  }
  function hit(a, p) { var s = session(a); if (!s) return { ok: false, reason: 'NO_HALO_SPORT' }; if (s.phase === 'RESULT') return { ok: false, reason: 'ACTIVITY_COMPLETE' }; var style = String(p && p.style || 'LOFT').toUpperCase(); if (style !== 'LOFT' && style !== 'DRIVE') return { ok: false, reason: 'BAD_CONTACT_STYLE' }; if (s.phase === 'SERVE_READY') s.ball = ballAtServe(a); else if ((s.mode === 'VOLLEY' && s.phase !== 'RALLY') || (s.mode === 'PRACTICE' && s.phase !== 'IN_FLIGHT')) return { ok: false, reason: 'BALL_NOT_READY' };
    var reach = distance3({ x: a.pos.x, y: HALO_LAYOUT.arrival_height_m + 1.25, z: a.pos.z }, s.ball); if (reach > 2.45) return { ok: false, reason: 'BALL_OUT_OF_REACH', distance_m: +reach.toFixed(2) };
    if (s.mode === 'PRACTICE') { if (s.phase !== 'SERVE_READY') return { ok: false, reason: 'ONE_CONTACT_SERVE' }; s.target_id = targetById(p && p.zone).id; var pt = targetById(s.target_id); s.phase = 'IN_FLIGHT'; sendBall(s, pt.x, pt.z, style === 'DRIVE' ? 0.72 : 1.04, style, 'PLAYER'); }
    else { var lane = clamp(Number(p && p.lane || 0), -3.2, 3.2); s.phase = 'RALLY'; sendBall(s, L.center.x + 5.8, L.center.z + lane * 2.25, style === 'DRIVE' ? 0.74 : 1.03, style, 'PLAYER'); }
    bump(); return { ok: true, mode: s.mode, style: style, rally_id: s.rally_id, contact_seq: s.contact_seq, target: s.mode === 'PRACTICE' ? s.target_id : null };
  }
  function replay(a) { var s = session(a); if (!s) return { ok: false, reason: 'NO_HALO_SPORT' }; if (s.phase !== 'RESULT') return { ok: false, reason: 'ACTIVITY_NOT_COMPLETE' }; s.score = { PLAYER: 0, BOT: 0 }; s.attempts = 0; s.hits = 0; s.result = null; s.point = null; setServe(a, s); rec('HALO_SPORT_REPLAY', { account: a.account_id, mode: s.mode }); bump(); return { ok: true, mode: s.mode }; }
  function leave(a, why) { var s = session(a); if (!s) return { ok: false, reason: 'NO_HALO_SPORT' }; delete sessions[a.account_id]; a.pos.x = L.entry.x - 0.8; a.pos.z = L.entry.z; a.facing = Math.PI / 2; a.moveVec = { forward: 0, strafe: 0, run: false, fast: false }; a.vel = { x: 0, z: 0 }; rec('HALO_SPORT_EXIT', { account: a.account_id, mode: s.mode, phase: s.phase, why: why || 'PLAYER', score: s.score, attempts: s.attempts, hits: s.hits, no_rewards: true }); bump(); return { ok: true, mode: s.mode, safe_exit: { x: a.pos.x, z: a.pos.z, altitude_m: HALO_LAYOUT.arrival_height_m } }; }
  function tick(a, dt) { var s = session(a); if (!s) return; a.fl.powered = false; a.fl.forced = false; a.fl.vz = 0; a.fl.intent = 0; a.fl.ground = HALO_LAYOUT.arrival_height_m; a.fl.altitude = HALO_LAYOUT.arrival_height_m;
    a.pos.x = clamp(a.pos.x, L.center.x - L.half_length_m + 0.6, L.center.x - 0.7); a.pos.z = clamp(a.pos.z, L.center.z - L.half_width_m + 0.55, L.center.z + L.half_width_m - 0.55);
    if (s.phase === 'SERVE_READY') { s.ball = ballAtServe(a); return; }
    if (s.phase === 'POINT') { if (H.t - s.phase_t >= 0.9) setServe(a, s); return; }
    if (s.phase === 'RESULT') return;
    var remain = Math.min(0.25, Math.max(0, dt || 0)); while (remain > 1e-8) { var h = Math.min(1 / 120, remain), b = s.ball, oldX = b.x; b.vy += gravity * h; b.x += b.vx * h; b.y += b.vy * h; b.z += b.vz * h; remain -= h;
      if (!s.net_touched && ((oldX < L.center.x && b.x >= L.center.x) || (oldX > L.center.x && b.x <= L.center.x)) && b.y - L.ball_radius_m <= L.center.altitude_m + L.net_height_m) { s.net_touched = true; b.x = oldX; b.vx *= -0.22; b.vz *= 0.8; b.vy *= 0.55; rec('HALO_SPORT_NET_CONTACT', { account: a.account_id, mode: s.mode, rally_id: s.rally_id, contact_seq: s.contact_seq, last_hitter: s.last_hitter }); }
      if (s.mode === 'VOLLEY' && s.phase === 'RALLY') { var wantX = clamp(b.x, L.center.x + 2.4, L.center.x + 6.2), wantZ = clamp(b.z, L.center.z - 3.1, L.center.z + 3.1), dx = wantX - s.bot.x, dz = wantZ - s.bot.z, dl = Math.hypot(dx, dz), step = Math.min(dl, 4.8 * h); if (dl > 1e-6) { s.bot.x += dx / dl * step; s.bot.z += dz / dl * step; } if (s.last_hitter === 'PLAYER' && b.vx > 0 && b.y >= floorY + 0.25 && b.y <= floorY + 2.7 && Math.hypot(b.x - s.bot.x, b.z - s.bot.z) <= 1.72 && H.t - s.bot.contact_t > 0.35) { s.bot.contact_t = H.t; s.bot.style = b.y > floorY + 1.45 ? 'LOFT' : 'DRIVE'; sendBall(s, L.center.x - 5.6, clamp(a.pos.z, L.center.z - 2.7, L.center.z + 2.7), s.bot.style === 'DRIVE' ? 0.76 : 1.02, s.bot.style, 'BOT'); } }
      if (b.y <= floorY) { b.y = floorY; var landing = { x: +b.x.toFixed(3), y: +b.y.toFixed(3), z: +b.z.toFixed(3), in_bounds: insideCourt(b.x, b.z) }; if (s.mode === 'PRACTICE') finishPractice(a, s, landing); else { var winner = insideCourt(b.x, b.z) ? (b.x < L.center.x ? 'BOT' : 'PLAYER') : (s.last_hitter === 'PLAYER' ? 'BOT' : 'PLAYER'); finishVolley(s, winner, insideCourt(b.x, b.z) ? 'COURT_FLOOR' : 'OUT', landing); } break; }
      if (Math.abs(b.x - L.center.x) > L.half_length_m + 4 || Math.abs(b.z - L.center.z) > L.half_width_m + 4 || b.y > HALO_LAYOUT.arrival_height_m + 18) { var out = { x: +b.x.toFixed(3), y: +b.y.toFixed(3), z: +b.z.toFixed(3), in_bounds: false }; if (s.mode === 'PRACTICE') finishPractice(a, s, out); else finishVolley(s, s.last_hitter === 'PLAYER' ? 'BOT' : 'PLAYER', 'OUT', out); break; }
    }
  }
  function botView(a) { var s = session(a); if (!s) return null; var age = H.t - s.bot.contact_t; return { id: 'NPC_HALO_VOLLEY_BOT', class_id: 'ATHLETE', body_key: 'ATHLETE_F', display_class: 'HALO', tier: 'SPORT', position: { x: +s.bot.x.toFixed(3), z: +s.bot.z.toFixed(3) }, altitude: HALO_LAYOUT.arrival_height_m, facing: -Math.PI / 2, form: 'SPLIT', mahloco: Math.hypot(s.ball.x - s.bot.x, s.ball.z - s.bot.z) > 0.8 ? 'SPLIT_RUN' : 'SPLIT_IDLE', attack: age >= 0 && age < 0.6 ? { attack_id: s.bot.style === 'DRIVE' ? 'HALO_VOLLEY_PUSH' : 'HALO_VOLLEY_OVERHEAD', state: age < 0.34 ? 'CONCENTRIC' : 'RECOVERY', category: 'PHYSICAL', progress: clamp(age / 0.6, 0, 1), profile: 'QUICK' } : null, hp: null, max: null, ko: false };
  }
  function view(a) { var s = session(a); if (!s) return null; var age = s.last_contact && s.last_contact.who === 'PLAYER' ? H.t - s.last_contact.at_t : 99; return { active: true, contract: L.contract, mode: s.mode, phase: s.phase, elapsed_s: +(H.t - s.started_t).toFixed(2), rally_id: s.rally_id, score: { player: s.score.PLAYER, bot: s.score.BOT, first_to: L.first_to }, practice: { attempts: s.attempts, hits: s.hits, total: L.practice_serves, target: s.target_id }, result: s.result, point: s.point, gear_stowed: true, flight_disabled: true, exit_available: true, contact_seq: s.contact_seq, last_contact: s.last_contact, player_attack: age < 0.6 ? { attack_id: s.last_contact.style === 'DRIVE' ? 'HALO_VOLLEY_PUSH' : 'HALO_VOLLEY_OVERHEAD', state: age < 0.34 ? 'CONCENTRIC' : 'RECOVERY', category: 'PHYSICAL', progress: clamp(age / 0.6, 0, 1), profile: 'QUICK' } : null, ball: { x: +s.ball.x.toFixed(3), y: +s.ball.y.toFixed(3), z: +s.ball.z.toFixed(3), vx: +s.ball.vx.toFixed(3), vy: +s.ball.vy.toFixed(3), vz: +s.ball.vz.toFixed(3), radius_m: L.ball_radius_m }, bot: botView(a), court: L };
  }
  return { start: start, hit: hit, replay: replay, leave: leave, tick: tick, view: view, botView: botView, active: function (a) { return !!session(a); }, layout: L };
}
