/* MAHWORLD GAMEPLAY RUNTIME :: LIVING CHARACTER PASS (2026-09-15) — social emotes (catalog, directed, stop, paired) + three field NPCs
   Host-authority checks only (plain node, memory host + one sqlite replay in a disposable dir). Emotes are cosmetic: no XP, resources,
   casts or transformations; NPCs are deterministic functions of the host clock and never enter colliders.
   node 16_TESTS/gameplay_emotes_npc.test.mjs   (from CLAUDE_GAMEPLAY_RUNTIME) */
import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost, hostIdentity } from '../26_LOCAL_AUTHORITY/DuelHost.js';
import { createSqliteStore, loadSqlite } from '../26_LOCAL_AUTHORITY/DurableStore.js';
import { makeEnvelope, validateEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';
import { EMOTE_CAT } from '../26_LOCAL_AUTHORITY/play/PlayMode.js';

var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var data = await loadHeadlessData(); var cfg = data.cfg; var DT = cfg.dev('local_authority.tick_dt_s'); var LA = cfg.dev('local_authority');
var PD = JSON.parse(fs.readFileSync(new URL('../26_LOCAL_AUTHORITY/lab/presentation_defaults.json', import.meta.url), 'utf8')); var RANGE = PD.emotes.invite_range_m;
function newHost(o) { o = o || {}; var h = createDuelHost({ data: data, composeHeadless: composeHeadless, store: o.store, opened: o.opened, clock: o.clock }); (o.accounts || ['PLAYER_A', 'PLAYER_B']).forEach(function (id) { h.dev.createAccount(id, { classId: 'ATHLETE', sex: 'M' }); }); return h; }
function sess(h, account) { var c = h.connect({ client_id: 'c-' + account, account_id: account, token: h.dev.tokens()[account] }); if (!c.ok) throw new Error('connect ' + account + ' ' + c.reason); var seq = 0; return { sid: c.session_id, account: account, send: function (action, payload) { return h.submit(makeEnvelope({ session_id: c.session_id, client_id: 'c-' + account }, ++seq, action, payload || {})); }, snap: function () { return h.snapshot(c.session_id); }, play: function () { return h.snapshot(c.session_id).play; } }; }
function run(h, seconds) { var n = Math.round(seconds / DT); for (var i = 0; i < n; i++) h.tick(DT); }
function logs(h, re) { return h.dev.log().filter(function (e) { return re.test(e.kind); }); }
function goTo(h, s, x, z) { for (var p2 = 0; p2 < 3; p2++) { for (var i = 0; i < 500; i++) { var pos = s.play().position; var dx = x - pos.x, dz = z - pos.z; var d = Math.hypot(dx, dz); if (d < 0.5) break; s.send('MOVE', { forward: +(-dz / d).toFixed(3), strafe: +(dx / d).toFixed(3), run: false, fast: true, yaw: +Math.atan2(dx, -dz).toFixed(3) }); h.tick(DT); } s.send('MOVE', { forward: 0, strafe: 0 }); run(h, 0.6); var q = s.play().position; if (Math.hypot(x - q.x, z - q.z) < 1.0) break; } }
function npc(s, id) { return s.play().npcs.filter(function (n) { return n.id === id; })[0]; }
function progressState(s) { var p = s.play(); var r = p.rules; return JSON.stringify({ xp: p.character && p.character.xp, level: p.character && p.character.level, skills: p.skills, energy: r ? r.me.combat_energy.current : null, flight: p.flight_mahgic.current, hp: r ? r.me.hp : null, quests: p.quests_done, cast: r ? r.me.cast : null, form: p.form }); }

/* 1 · catalog: one canonical list, every entry registered, shapes */
var H = newHost(); var A = sess(H, 'PLAYER_A'); A.send('ENTER_ROOM', { room: 'FIELD' }); run(H, 0.2); var P0 = A.play();
var ids = EMOTE_CAT.emotes.map(function (e) { return e.id; });
ok('catalog: 20 starter emotes + READY are published in the snapshot with the required fields', P0.emote_catalog && P0.emote_catalog.length === EMOTE_CAT.emotes.length && EMOTE_CAT.emotes.length >= 21 && ['WAVE', 'NOD', 'APPLAUD', 'THUMBS_UP', 'BECKON', 'MAH_GROOVE', 'SIDE_GLIDE', 'UPRIGHT_ROW_DEMO', 'HORIZONTAL_PUSH_DEMO', 'HIP_HINGE_DEMO', 'SQUAT_DEMO', 'DOUBLE_BICEPS', 'FRONT_LAT_SPREAD', 'SIDE_CHEST', 'BACK_LAT_SPREAD', 'SHRUG', 'QUIET_LAUGH', 'FIST_BUMP', 'HIGH_FIVE', 'PAIRED_GROOVE', 'READY'].every(function (id) { return ids.indexOf(id) >= 0; }) && P0.emote_catalog.every(function (e) { return e.id && e.name && ['SOCIAL', 'DANCE', 'EXERCISE', 'FLEX', 'EXPRESSION', 'PARTNER'].indexOf(e.group) >= 0 && ['ANY', 'FUSED', 'SPLIT'].indexOf(e.form) >= 0 && typeof e.partner === 'boolean' && typeof e.directed === 'boolean' && typeof e.loop === 'boolean' && typeof e.duration_s === 'number' && e.icon && Array.isArray(e.reply_options); }), { n: P0.emote_catalog && P0.emote_catalog.length });
ok('every catalog emote is registered on the world emote system (every non-partner, form-ANY emote is accepted; unknown ids refused)', (function () { var bad = []; EMOTE_CAT.emotes.forEach(function (e) { if (e.partner || e.form !== 'ANY') return; var r = A.send('EMOTE', { emote_id: e.id }); if (!r.accepted) bad.push(e.id + ':' + r.reason); A.send('EMOTE_STOP'); run(H, 1.1); }); var unk = A.send('EMOTE', { emote_id: 'NOT_AN_EMOTE' }); return bad.length === 0 && !unk.accepted && unk.reason === 'UNKNOWN_EMOTE'; })(), logs(H, /^EMOTE$/).length);
ok('protocol: EMOTE_STOP / EMOTE_INVITE / EMOTE_JOIN validate their payloads', validateEnvelope(makeEnvelope({ session_id: 's', client_id: 'c' }, 1, 'EMOTE_INVITE', { emote_id: 'FIST_BUMP' }), LA).reason !== undefined && validateEnvelope(makeEnvelope({ session_id: 's', client_id: 'c' }, 1, 'EMOTE_JOIN', { from: 42 }), LA).ok === false && validateEnvelope(makeEnvelope({ session_id: 's', client_id: 'c' }, 1, 'EMOTE_STOP', {}), LA).ok === true);

/* 2 · form requirement, stop, directed range */
ok('SQUAT_DEMO while FUSED is refused FORM_REQUIRED (Separate first) and never transforms silently', (function () { var f0 = A.play().form; var r = A.send('EMOTE', { emote_id: 'SQUAT_DEMO' }); run(H, 0.3); return f0 === 'FUSED' && !r.accepted && r.reason === 'FORM_REQUIRED' && r.detail && r.detail.form === 'SPLIT' && A.play().form === 'FUSED' && !A.play().transforming; })());
ok('EMOTE_STOP clears the current cosmetic emote and touches nothing else', (function () { A.send('EMOTE', { emote_id: 'MAH_GROOVE' }); run(H, 0.5); var on = A.play().emote; var st = progressState(A); var r = A.send('EMOTE_STOP'); run(H, 0.1); return on === 'MAH_GROOVE' && r.accepted && r.stopped === 'MAH_GROOVE' && A.play().emote === null && progressState(A) === st; })());
run(H, 1.2); var npcs0 = A.play().npcs;
var groundNpcs = npcs0.filter(function (n) { return n.id !== 'NPC_HALO_GUIDE'; }), haloGuide = npcs0.filter(function (n) { return n.id === 'NPC_HALO_GUIDE'; })[0];
ok('the WORLD snapshot publishes exactly the nine ground residents and seals the HALO guide above the deck; the ground cast still covers every class/sex except player ATHLETE_M', npcs0.length === 9 && groundNpcs.length === 9 && !haloGuide && groundNpcs.map(function (n) { return n.body_key; }).sort().join(',') === 'ATHLETE_F,BAGE_F,BAGE_M,LEAN_F,LEAN_M,TITAN_F,TITAN_M,VISIONARY_F,VISIONARY_M' && groundNpcs.filter(function (n) { return n.tier === 'QUEST' && n.quest; }).length === 1 && npcs0.every(function (n) { return n.domain === 'WORLD' && typeof n.position.x === 'number' && typeof n.facing === 'number' && n.form === 'FUSED'; }) && groundNpcs[1].pending_owner_name && /Warlock/.test(groundNpcs[1].pending_owner_name), npcs0);
var bage = npcs0[1];
ok('directed emote to a far NPC is refused TARGET_OUT_OF_RANGE; BAD_TARGET for an unknown id', (function () { var r1 = A.send('EMOTE', { emote_id: 'WAVE', to: 'NPC_BAGE_F' }); var r2 = A.send('EMOTE', { emote_id: 'WAVE', to: 'NOBODY' }); return !r1.accepted && r1.reason === 'TARGET_OUT_OF_RANGE' && r1.detail && r1.detail.range_m === RANGE && !r2.accepted && r2.reason === 'BAD_TARGET'; })());
goTo(H, A, bage.position.x - 1.6, bage.position.z); run(H, 0.3); var dB = Math.hypot(A.play().position.x - npc(A, 'NPC_BAGE_F').position.x, A.play().position.z - npc(A, 'NPC_BAGE_F').position.z);
ok('a directed WAVE in range is accepted with the target published; the NPC replies after a deterministic delay with one of the reply options', (function () { var r = A.send('EMOTE', { emote_id: 'WAVE', to: 'NPC_BAGE_F' }); var t0 = A.play().emote_target; run(H, 3.0); var rep = logs(H, /^NPC_EMOTE_REPLY$/).filter(function (e) { return e.npc === 'NPC_BAGE_F'; }); var wave = EMOTE_CAT.emotes.filter(function (e) { return e.id === 'WAVE'; })[0]; return dB < RANGE && r.accepted && r.to === 'NPC_BAGE_F' && t0 === 'NPC_BAGE_F' && rep.length === 1 && wave.reply_options.indexOf(rep[0].emote) >= 0 && rep[0].to === 'PLAYER_A'; })(), { d: dB, replies: logs(H, /^NPC_EMOTE_REPLY$/) });
ok('reply cooldown: repeating the wave immediately gets no second reply; NPC replies never stack', (function () { run(H, 1.2); var n0 = logs(H, /^NPC_EMOTE_REPLY$/).length; A.send('EMOTE', { emote_id: 'WAVE', to: 'NPC_BAGE_F' }); run(H, 2.5); return logs(H, /^NPC_EMOTE_REPLY$/).length === n0; })());

/* 3 · exercise emotes are cosmetic */
ok('exercise / flex / dance emotes change no XP, skills, energy, flight pool, hp, quests, cast or form', (function () { run(H, 1.5); var before = progressState(A); ['UPRIGHT_ROW_DEMO', 'HORIZONTAL_PUSH_DEMO', 'HIP_HINGE_DEMO', 'DOUBLE_BICEPS', 'MAH_GROOVE'].forEach(function (id) { var r = A.send('EMOTE', { emote_id: id }); if (!r.accepted) throw new Error(id + ' ' + r.reason); run(H, 1.3); A.send('EMOTE_STOP'); run(H, 1.1); }); return progressState(A) === before && logs(H, /WORKOUT|SKILL_XP|REWARD|R1723_CAST/).length === 0; })(), progressState(A));

/* 4 · paired emote with an NPC: invite → deterministic accept → shared t0 → leave releases both */
ok('EMOTE_INVITE FIST_BUMP to the NPC in range → the NPC accepts on a deterministic delay; both publish the same paired timeline', (function () { var r = A.send('EMOTE_INVITE', { emote_id: 'FIST_BUMP', to: 'NPC_BAGE_F' }); var inv = r.accepted; var joined = null; for (var i = 0; i < 60 && !joined; i++) { H.tick(DT); var p = A.play(); if (p.paired) joined = { me: p.paired, npc: npc(A, 'NPC_BAGE_F').paired, t: p.t }; } var pr = logs(H, /^EMOTE_PAIRED$/).slice(-1)[0]; var dl = EMOTE_CAT.npc_accept_delay_s; return inv && joined && joined.me.id === 'FIST_BUMP' && joined.me.role === 'A' && joined.npc && joined.npc.role === 'B' && joined.me.t0 === joined.npc.t0 && joined.me.partner_id === 'NPC_BAGE_F' && joined.npc.partner_id === 'PLAYER_A' && pr && pr.t0 - r.expires_t + EMOTE_CAT.invite_expiry_s >= dl[0] - 1e-6 && pr.t0 - r.expires_t + EMOTE_CAT.invite_expiry_s <= dl[1] + 1e-6; })(), logs(H, /^EMOTE_(INVITE|PAIRED)$/));
ok('a deliberate movement by the initiator releases BOTH participants to solo idle (no permanent paired lock)', (function () { A.send('MOVE', { forward: 1, yaw: 0 }); run(H, 0.3); A.send('MOVE', { forward: 0 }); run(H, 0.2); var rel = logs(H, /^EMOTE_PAIR_RELEASED$/).slice(-1)[0]; return A.play().paired === null && A.play().emote === null && npc(A, 'NPC_BAGE_F').paired === null && rel && rel.emote === 'FIST_BUMP'; })());
ok('invite refusals: non-partner emote, unknown target, out of range', (function () { goTo(H, A, npc(A, 'NPC_BAGE_F').position.x - 1.6, npc(A, 'NPC_BAGE_F').position.z); var r1 = A.send('EMOTE_INVITE', { emote_id: 'WAVE', to: 'NPC_BAGE_F' }); var r2 = A.send('EMOTE_INVITE', { emote_id: 'FIST_BUMP', to: 'NOBODY' }); var r3 = A.send('EMOTE_INVITE', { emote_id: 'HIGH_FIVE', to: 'NPC_TITAN_M' }); return r1.reason === 'NOT_PARTNER_EMOTE' && r2.reason === 'BAD_TARGET' && r3.reason === 'TARGET_OUT_OF_RANGE'; })());
ok('partner emote through plain EMOTE is refused (PARTNER_EMOTE → use EMOTE_INVITE)', A.send('EMOTE', { emote_id: 'HIGH_FIVE' }).reason === 'PARTNER_EMOTE');

/* 5 · player ↔ player pairing needs explicit EMOTE_JOIN; an expired invitation cannot be joined */
var B = sess(H, 'PLAYER_B'); B.send('ENTER_ROOM', { room: 'FIELD' }); run(H, 0.3); var ap = A.play().position; goTo(H, B, ap.x + 1.2, ap.z); run(H, 0.3);
ok('player → player: the invitee sees the invitation; nothing pairs until EMOTE_JOIN; joining starts both on one shared t0', (function () { var r = A.send('EMOTE_INVITE', { emote_id: 'HIGH_FIVE', to: 'PLAYER_B' }); run(H, 0.5); var seen = B.play().invite; var notYet = A.play().paired === null && B.play().paired === null; var j = B.send('EMOTE_JOIN', { from: 'PLAYER_A' }); run(H, 0.1); var pa = A.play().paired, pb = B.play().paired; return r.accepted && seen && seen.from === 'PLAYER_A' && seen.emote_id === 'HIGH_FIVE' && notYet && j.accepted && pa && pb && pa.t0 === pb.t0 && pa.role === 'A' && pb.role === 'B' && pa.partner_id === 'PLAYER_B' && pb.partner_id === 'PLAYER_A'; })());
ok('EMOTE_STOP by one participant releases both; a stale EMOTE_JOIN afterwards is refused', (function () { var r = B.send('EMOTE_STOP'); run(H, 0.1); var again = B.send('EMOTE_JOIN', { from: 'PLAYER_A' }); return r.accepted && r.paired_released === true && A.play().paired === null && B.play().paired === null && !again.accepted; })());
ok('an invitation expires after invite_expiry_s (host clock) and cannot be joined', (function () { var r = A.send('EMOTE_INVITE', { emote_id: 'FIST_BUMP', to: 'PLAYER_B' }); run(H, EMOTE_CAT.invite_expiry_s + 0.5); var j = B.send('EMOTE_JOIN', { from: 'PLAYER_A' }); return r.accepted && !j.accepted && /EXPIRED|NO_INVITATION|WITHDRAWN/.test(j.reason) && A.play().paired === null && logs(H, /^EMOTE_INVITE_EXPIRED$/).length >= 1; })());

/* 6 · emotes never cancel committed combat actions; combat cancels emotes */
A.send('FIELD_PRACTICE', { on: true }); run(H, 0.3);
ok('a cosmetic emote is refused while a cast is in flight (emote system) and a cast started during an emote cancels the emote, never the cast', (function () { goTo(H, A, 0, 0.5); A.send('MOVE', { forward: 0, strafe: 0, yaw: Math.PI }); run(H, 0.3); A.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); A.send('EMOTE', { emote_id: 'SHRUG' }); run(H, 0.2); var emoteOn = A.play().emote === 'SHRUG'; var c = A.send('RULES_CAST'); run(H, 0.1); var castOn = !!A.play().rules.me.cast; var emoteGone = A.play().emote === null; var e2 = A.send('EMOTE', { emote_id: 'WAVE' }); run(H, 1.5); return emoteOn && c.accepted && castOn && emoteGone && !e2.accepted && e2.reason === 'CASTING'; })(), { cancel: logs(H, /^EMOTE_CANCEL$/).slice(-1) });
A.send('FIELD_PRACTICE', { on: false });

/* 7 · NPCs: wander stays out of colliders and away from the dummy; deterministic across replay */
ok('ground NPCs wander within their radius, never inside a collider, never within the dummy clearance, over 60 s of ticks', (function () { var rf = H.dev.play_internals().rulesField(); var col = rf.colliders(null); var bad = 0, moved = 0; var last = {}; for (var i = 0; i < Math.round(60 / DT); i++) { H.tick(DT); A.play().npcs.filter(function (n) { return n.id !== 'NPC_HALO_GUIDE'; }).forEach(function (n) { var inside = col.resolveMove({ x: n.position.x, z: n.position.z }, 0.001, 0, 0).blocked; if (inside) bad++; if (Math.hypot(n.position.x - 0, n.position.z + 2) < 6) bad++; if (last[n.id] && (last[n.id].x !== n.position.x || last[n.id].z !== n.position.z)) moved++; last[n.id] = n.position; }); } return bad === 0 && moved > 20; })());
var sqlite = await loadSqlite(); var TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'mahworld-5b-test-emote-')); var st = createSqliteStore(sqlite, { dir: TMP }); var op = st.open({ identity: hostIdentity(data) });
var H2 = createDuelHost({ data: data, composeHeadless: composeHeadless, store: st, opened: op }); H2.dev.createAccount('PLAYER_A', {}); var A2 = sess(H2, 'PLAYER_A'); A2.send('ENTER_ROOM', { room: 'FIELD' }); run(H2, 2); var n2 = A2.play().npcs; goTo(H2, A2, n2[1].position.x - 1.6, n2[1].position.z); A2.send('EMOTE', { emote_id: 'WAVE', to: 'NPC_BAGE_F' }); run(H2, 3); A2.send('EMOTE_INVITE', { emote_id: 'FIST_BUMP', to: 'NPC_BAGE_F' }); run(H2, 2); run(H2, 12); var before = JSON.stringify(A2.play().npcs.map(function (n) { return [n.id, n.position, n.facing, n.emote, n.paired]; })); var bp = A2.play().paired; st.simulateCrash();
var st2 = createSqliteStore(sqlite, { dir: TMP }); if (fs.existsSync(st.lockPath)) fs.unlinkSync(st.lockPath); var op2 = st2.open({ identity: hostIdentity(data) }); var poisoned = 0; var H3 = createDuelHost({ data: data, composeHeadless: composeHeadless, store: st2, opened: op2, clock: { kind: 'POISONED', now: function () { poisoned++; return 9e9; } } }); var rec = H3.recover(); var after = JSON.stringify(H3.snapshot(A2.sid).play.npcs.map(function (n) { return [n.id, n.position, n.facing, n.emote, n.paired]; }));
ok('crash + journal replay reproduces NPC positions, facing, emotes, replies and the paired timeline exactly (pure functions of the host clock; no fresh clock read)', rec.ok && rec.inconsistencies.length === 0 && before === after && poisoned === 0 && JSON.stringify(H3.snapshot(A2.sid).play.paired) === JSON.stringify(bp), { rec: rec.inconsistencies.slice(0, 2), before: before.slice(0, 200), after: after.slice(0, 200) }); st2.closeClean();

/* 8 · practice: NPCs as targets / incoming sources only in practice; friendly in free roam */
ok('free roam: NPC hp is untouched by a player attack (harmless context); practice: an NPC-launched incoming uses that NPC\'s own class skill', (function () { var H4 = newHost(); var A4 = sess(H4, 'PLAYER_A'); A4.send('ENTER_ROOM', { room: 'FIELD' }); run(H4, 0.3); var t = npc(A4, 'NPC_TITAN_M'); goTo(H4, A4, t.position.x + 1.5, t.position.z); A4.send('MOVE', { forward: 0, strafe: 0, yaw: +Math.atan2(t.position.x - A4.play().position.x, -(t.position.z - A4.play().position.z)).toFixed(3) }); run(H4, 0.3); A4.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); A4.send('RULES_CAST'); run(H4, 1.5); var hpFree = npc(A4, 'NPC_TITAN_M').hp; A4.send('FIELD_PRACTICE', { on: true }); run(H4, 0.2); var inc = A4.send('FIELD_INCOMING', { kind: 'PHYSICAL', from: 'NPC_TITAN_M' }); run(H4, 2.0); var h4 = logs(H4, /^R1723_DAMAGE$/).filter(function (d) { return d.by === 'NPC_TITAN_M'; }); return hpFree === t.max && inc.accepted && inc.from === 'NPC_TITAN_M' && h4.length >= 1; })());

/* 9 . S07 SPAR: in practice a hit NPC closes and strikes back with its own move on the real cast path; left alone it stands down */
ok('practice spar: an NPC hit by the player closes to range, casts its own PHYSICAL move (authoritative damage on the player), and stands down ~8 s after the last hit', (function () { var H5 = newHost(); var A5 = sess(H5, 'PLAYER_A'); A5.send('ENTER_ROOM', { room: 'FIELD' }); run(H5, 0.3); A5.send('FIELD_PRACTICE', { on: true }); run(H5, 0.2); var t = npc(A5, 'NPC_TITAN_M'); goTo(H5, A5, t.position.x + 1.5, t.position.z); A5.send('MOVE', { forward: 0, strafe: 0, yaw: +Math.atan2(t.position.x - A5.play().position.x, -(t.position.z - A5.play().position.z)).toFixed(3) }); run(H5, 0.3); A5.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); var hp0 = A5.play().rules.me.hp; var landed = 0; for (var k = 0; k < 6 && !landed; k++) { A5.send('RULES_CAST'); run(H5, 1.2); landed = logs(H5, /^R1723_DAMAGE$/).filter(function (d) { return d.on === 'NPC_TITAN_M'; }).length; } run(H5, 6); var begun = logs(H5, /^NPC_SPAR_BEGIN$/).length >= 1; var npcHits = logs(H5, /^R1723_DAMAGE$/).filter(function (d) { return d.by === 'NPC_TITAN_M' && d.on === 'PLAYER_A'; }).length; var hpNow = A5.play().rules.me.hp; run(H5, 9); var ended = logs(H5, /^NPC_SPAR_END$/).length >= 1; return landed >= 1 && begun && npcHits >= 1 && hpNow < hp0 && ended; })());
ok('free roam spar: a hit NPC only squares up (guard, faces the player) and never damages', (function () { var H6 = newHost(); var A6 = sess(H6, 'PLAYER_A'); A6.send('ENTER_ROOM', { room: 'FIELD' }); run(H6, 0.3); var t = npc(A6, 'NPC_LEAN_F'); goTo(H6, A6, t.position.x + 1.5, t.position.z); A6.send('MOVE', { forward: 0, strafe: 0, yaw: +Math.atan2(t.position.x - A6.play().position.x, -(t.position.z - A6.play().position.z)).toFixed(3) }); run(H6, 0.3); A6.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); for (var k = 0; k < 3; k++) { A6.send('RULES_CAST'); run(H6, 1.0); } run(H6, 2); var dmgOnMe = logs(H6, /^R1723_DAMAGE$/).filter(function (d) { return d.on === 'PLAYER_A'; }).length; var n6 = npc(A6, 'NPC_LEAN_F'); return dmgOnMe === 0 && n6.hp === n6.max; })());

console.log('\nRESULT emotes + NPCs: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
