/* M5 owner-playtest building correction gate: source-derived fidelity tiers, exact one-time scale,
   collision/portal truth, synchronized entrances, contained grand interiors, and repeatable host entry/exit. */
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import cp from 'node:child_process'; import { fileURLToPath } from 'node:url';
import { readGlb } from '../26_LOCAL_AUTHORITY/deploy/glb_read.mjs';
import { createColliders } from '../26_LOCAL_AUTHORITY/play/rules1723/Colliders.js';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost } from '../26_LOCAL_AUTHORITY/DuelHost.js'; import { makeEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';

var HERE = path.dirname(fileURLToPath(import.meta.url)), ROOT = path.resolve(HERE, '..'), LA = path.join(ROOT, '26_LOCAL_AUTHORITY');
var MAN = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'assets', 'buildings', 'district_v1.json'), 'utf8'));
var REG_RAW = fs.readFileSync(path.join(LA, 'lab', 'assets', 'world', 'world_registry_v1.json'), 'utf8'), REG = JSON.parse(REG_RAW);
var DIST = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'district_v1_colliders.json'), 'utf8'));
var WCOL = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'world_v1_colliders.json'), 'utf8'));
var RULES = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'rules_17_23.dev.json'), 'utf8'));
var TUNING = JSON.parse(fs.readFileSync(path.join(ROOT, '00_CORE', 'dev_tuning.dev.json'), 'utf8'));
var ROOMS = TUNING.local_authority.play.rooms;
var SHOPS = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'assets', 'shops', 'shops_v1.json'), 'utf8'));
var pass = 0, fail = 0; function ok(name, cond, detail) { if (cond) { pass++; console.log('PASS ' + name); } else { fail++; console.log('FAIL ' + name + (detail === undefined ? '' : ' — ' + JSON.stringify(detail))); } }
function sha(p) { return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'); }
function close(a, b, eps) { return Math.abs(a - b) <= eps; }
function building(id) { return MAN.buildings.filter(function (b) { return b.id === id; })[0]; }
function regBuilding(id) { return REG.buildings.list.filter(function (b) { return b.id === id; })[0]; }
function primitiveFacts(file) { var G = readGlb(file), J = G.json, tris = 0, verts = 0, attrs = true, maps = true; (J.meshes || []).forEach(function (m) { (m.primitives || []).forEach(function (p) { var a = p.attributes || {}; attrs = attrs && a.POSITION !== undefined && a.NORMAL !== undefined && a.TEXCOORD_0 !== undefined; verts += J.accessors[a.POSITION].count; if (p.indices !== undefined) tris += J.accessors[p.indices].count / 3; var mat = J.materials[p.material]; maps = maps && !!(mat && mat.pbrMetallicRoughness && mat.pbrMetallicRoughness.baseColorTexture && mat.normalTexture); }); }); return { G: G, J: J, tris: tris, verts: verts, attrs: attrs, maps: maps, jpeg: (J.images || []).every(function (im) { return im.mimeType === 'image/jpeg'; }), mip: (J.samplers || []).every(function (s) { return s.minFilter === 9987 || s.minFilter === 9985; }) }; }
function localBounds(J) { var mn = [Infinity, Infinity, Infinity], mx = [-Infinity, -Infinity, -Infinity]; (J.meshes || []).forEach(function (m) { (m.primitives || []).forEach(function (p) { var a = J.accessors[p.attributes.POSITION]; for (var q = 0; q < 3; q++) { mn[q] = Math.min(mn[q], a.min[q]); mx[q] = Math.max(mx[q], a.max[q]); } }); }); return { min: mn, max: mx }; }
function worldBounds(lb, b) { var sb = b.source_bounds, cx = sb.center_xz[0], cz = sb.center_xz[1], y0 = sb.base_y, yaw = (b.yaw_deg || 0) * Math.PI / 180, cy = Math.cos(yaw), sy = Math.sin(yaw), tx = b.position[0], tz = b.position[2], out = { min: [Infinity, Infinity, Infinity], max: [-Infinity, -Infinity, -Infinity] }; [lb.min[0], lb.max[0]].forEach(function (x) { [lb.min[1], lb.max[1]].forEach(function (y) { [lb.min[2], lb.max[2]].forEach(function (z) { var lx = (x - cx) * b.scale, ly = (y - y0) * b.scale, lz = (z - cz) * b.scale, w = [tx + lx * cy + lz * sy, ly, tz - lx * sy + lz * cy]; for (var q = 0; q < 3; q++) { out.min[q] = Math.min(out.min[q], w[q]); out.max[q] = Math.max(out.max[q], w[q]); } }); }); }); return out; }

var affected = MAN.buildings.filter(function (b) { return !!b.owner_m5_correction; }).map(function (b) { return b.id; }).sort(); var gym = building('gym');
ok('G03 affected imported-building set is exactly market/temple/tower and gym remains outside the correction', affected.join(',') === 'market,temple,tower' && !gym.owner_m5_correction && gym.scale === 49.258259 && gym.runtime === 'lab/assets/buildings/_decimated/gym_rt.glb', { affected: affected, gym: { scale: gym.scale, runtime: gym.runtime } });

var sideNames = { temple: 'TEMPLE_M5C.derivative.json', tower: 'TOWER_M5C.derivative.json', market: 'MARKET_M5C.derivative.json' }, allProvenance = true, allScale = true, allBounds = true;
affected.forEach(function (id) { var b = building(id), c = b.owner_m5_correction, side = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'assets', 'buildings', 'fidelity_m5c', sideNames[id]), 'utf8')), l0 = side.lods.filter(function (l) { return l.lod === 'L0'; })[0], l1 = side.lods.filter(function (l) { return l.lod === 'L1'; })[0], p0 = path.join(LA, b.runtime), p1 = path.join(LA, b.lod_runtime), f0 = primitiveFacts(p0), f1 = primitiveFacts(p1), srcExists = fs.existsSync(side.source.file), srcHash = srcExists ? sha(side.source.file) : null;
  var recipe = side.recipe && side.recipe.arguments || {};
  allProvenance = allProvenance && c.source_status === 'FOUND_IN_BOUNDED_KNOWN_FOLDER' && srcExists && srcHash === side.source.sha256 && side.source.sha256 === b.provenance.source_sha256 && sha(p0) === l0.sha256 && sha(p1) === l1.sha256 && c.near_runtime_sha256 === l0.sha256 && c.far_runtime_sha256 === l1.sha256 && b.provenance.runtime_sha256 === l0.sha256 && b.provenance.collider_runtime_sha256 === l1.sha256 && fs.statSync(p0).size === l0.bytes && fs.statSync(p1).size === l1.bytes && f0.tris === l0.triangles && f1.tris === l1.triangles && f0.verts === l0.vertices && f1.verts === l1.vertices && recipe.preserve_normals === true && recipe.preserve_border === true && recipe.attribute_representative === 'nearest' && recipe.agg === 3 && recipe.tex === 2048 && recipe.normal === 2048 && f0.attrs && f1.attrs && f0.maps && f1.maps && f0.jpeg && f1.jpeg && f0.mip && f1.mip;
  var wanted = +(c.baseline_scale * 0.6).toFixed(6), base = c.baseline_envelope_m, cur = b.envelope_m, baseCx = (base.x1 + base.x2) / 2, baseCz = (base.z1 + base.z2) / 2, curCx = (cur.x1 + cur.x2) / 2, curCz = (cur.z1 + cur.z2) / 2;
  allScale = allScale && c.application_id === 'M5_OWNER_OP02_SCALE_ONCE_20260923' && c.factor === 0.6 && b.target_scale === wanted && b.scale === wanted && close(b.actual_height_m, b.source_height * b.scale, 0.001) && close(cur.width, (base.x2 - base.x1) * 0.6, 0.11) && close(cur.depth, (base.z2 - base.z1) * 0.6, 0.11) && close(baseCx, curCx, 0.11) && close(baseCz, curCz, 0.11);
  var wb0 = worldBounds(localBounds(f0.J), b), wb1 = worldBounds(localBounds(f1.J), b), delta = Math.max.apply(null, [0, 1, 2].flatMap(function (q) { return [Math.abs(wb0.min[q] - wb1.min[q]), Math.abs(wb0.max[q] - wb1.max[q])]; })); allBounds = allBounds && delta <= 0.1;
});
ok('G03 source originals are currently present in the bounded known folder and every seam-preserving shipped L0/L1 hash, byte/triangle/vertex count, recipe flag, attribute and PBR map matches its derivative ledger', allProvenance);
ok('G04 one-time building scale is exactly reviewed M5 scale × 0.6 with centre preserved and envelope approximately ×0.6', allScale);
ok('G03 authored L0/L1 transformed bounds agree within 0.1 m under the shared L0 anchor', allBounds);

var colliderTruth = affected.every(function (id) { var b = building(id), ss = DIST.shapes.filter(function (s) { return s.district === id; }), cell = MAN.collider_cell_m, ycell = MAN.collider_ycell_m, e = b.envelope_m; return ss.length === b.collider_counts.solid_boxes + b.collider_counts.deck_slabs && ss.length > 0 && b.collider_counts.portal_boxes_removed > 0 && ss.every(function (s) { return [s.x1, s.x2, s.z1, s.z2, s.y0, s.h].every(Number.isFinite) && s.x1 >= e.x1 - cell - 0.11 && s.x2 <= e.x2 + cell + 0.11 && s.z1 >= e.z1 - cell - 0.11 && s.z2 <= e.z2 + cell + 0.11 && s.h <= b.actual_height_m + ycell + 0.2; }); });
ok('G04 source-sampled collision stays finite, nonempty and within one voxel of each resized visual envelope while preserving carved portals', colliderTruth);

var syncOk = true; [['26_LOCAL_AUTHORITY/deploy/sync_district_colliders.mjs', '--check'], ['26_LOCAL_AUTHORITY/deploy/jobb/build_world_colliders.mjs', '--check']].forEach(function (a) { try { cp.execFileSync(process.execPath, a, { cwd: ROOT, stdio: 'pipe' }); } catch (e) { syncOk = false; } });
ok('G03/G04 generated district/world mappings are synchronized and world collider record hashes the exact registry', syncOk && WCOL.registry_sha256 === crypto.createHash('sha256').update(REG_RAW).digest('hex') && JSON.stringify(RULES._runtime_mapping.field_colliders_district_v1.shapes.filter(function (s) { return !!s.district; })) === JSON.stringify(DIST.shapes));

var C = createColliders(RULES._runtime_mapping.field_colliders_district_v1), linksOk = true, approachOk = true, sweepsOk = true, sweepDiag = [];
affected.forEach(function (id) { var b = building(id), rid = 'LM_' + id.toUpperCase(), rb = regBuilding(rid), route = REG.paths.list.filter(function (p) { return p.id === rb.route; })[0], arch = REG.architecture.landmarks.filter(function (a) { return a.id === rid; })[0], map = REG.map.buildings.filter(function (m) { return m.id === rid; })[0];
  linksOk = linksOk && rb.contract && rb.contract.scale === b.scale && JSON.stringify(rb.contract.envelope_m) === JSON.stringify(b.envelope_m) && rb.contract.near_runtime_sha256 === b.owner_m5_correction.near_runtime_sha256 && rb.contract.far_runtime_sha256 === b.owner_m5_correction.far_runtime_sha256 && rb.contract.room_ids.every(function (room) { return !!ROOMS[room]; });
  b.portals.forEach(function (p) { var ent = id === 'market' ? rb.entrances.filter(function (e) { return e.door === p.id; })[0] : rb.entrance, it = RULES._runtime_mapping.field_colliders_district_v1.interactables.filter(function (x) { return x.id === p.id; })[0], roomId = p.id === 'TEMPLE_DOOR' ? 'TEMPLE_HALL' : p.id === 'TOWER_DOOR' ? 'TOWER_HALL' : p.id === 'CLOTHING_DOOR' ? 'CLOTHING_SHOP' : 'WEAPON_SHOP', room = ROOMS[roomId], spur = route.spur && route.spur.door === p.id ? route.spur : route.spur2, dx = rb.forecourt.x - p.world[0], dz = rb.forecourt.z - p.world[1], dl = Math.hypot(dx, dz), dot = (dx * p.outward[0] + dz * p.outward[1]) / dl;
    var archEntrances = arch.entrances && arch.entrances.length ? arch.entrances : [arch.entrance], archEnt = archEntrances.filter(function (e) { return e && e.door === p.id; })[0];
    linksOk = linksOk && ent && ent.x === p.world[0] && ent.z === p.world[1] && it && it.x === p.world[0] && it.z === p.world[1] && room.door.x === p.world[0] && room.door.z === p.world[1] && spur && spur.to[0] === p.world[0] && spur.to[1] === p.world[1] && map && (id === 'market' || (map.x === p.world[0] && map.z === p.world[1])) && archEnt && archEnt.x === p.world[0] && archEnt.z === p.world[1] && archEnt.half_w_m === p.half_width_m && archEnt.height_m === p.height_m && JSON.stringify(archEnt.outward) === JSON.stringify(p.outward);
    var yaw = (b.yaw_deg || 0) * Math.PI / 180, cy = Math.cos(yaw), sy = Math.sin(yaw), nx = p.local_normal[0] * cy + p.local_normal[2] * sy, nz = -p.local_normal[0] * sy + p.local_normal[2] * cy, ax = (p.local[0] - b.source_bounds.center_xz[0]) * b.scale, az = (p.local[2] - b.source_bounds.center_xz[1]) * b.scale, wx = b.position[0] + ax * cy + az * sy, wz = b.position[2] - ax * sy + az * cy;
    approachOk = approachOk && nx * p.outward[0] + nz * p.outward[1] > 0.999 && Math.hypot(wx - p.world[0], wz - p.world[1]) <= 0.4 && dot >= Math.cos(15 * Math.PI / 180);
    var outside = { x: p.world[0] + p.outward[0] * 1.1, z: p.world[1] + p.outward[1] * 1.1 }, inside = { x: p.world[0] - p.outward[0] * 2.0, z: p.world[1] - p.outward[1] * 2.0 }, inward = C.resolveMove(outside, inside.x - outside.x, inside.z - outside.z, 0), reverse = C.resolveMove(inside, outside.x - inside.x, outside.z - inside.z, 0), sweepOpen = !inward.blocked && !reverse.blocked && Math.hypot(inward.x - inside.x, inward.z - inside.z) < 0.05 && Math.hypot(reverse.x - outside.x, reverse.z - outside.z) < 0.05; sweepsOk = sweepsOk && sweepOpen; if (!sweepOpen) sweepDiag.push({ building: id, portal: p.id, outside: outside, inside: inside, inward: inward, reverse: reverse });
  });
});
ok('G05 every building/route/architecture/interactable/room/map consumer agrees with the manifest portal contract', linksOk);
ok('G05 transformed source-front portal points/normals match their thresholds and all approaches align within 15 degrees', approachOk);
ok('G05 real capsule sweeps cross all four carved portals in both directions without an invisible wall', sweepsOk, sweepDiag);

var market = building('market'), mp = market.portals.slice().sort(function (a, b) { return a.world[0] - b.world[0]; }), facadeOutsideZ = mp[0].world[1] - 1.2, facadeInsideZ = mp[0].world[1] + 2.8, centralX = (mp[0].world[0] + mp[1].world[0]) * 0.5, leftEdgeX = mp[0].world[0] - mp[0].half_width_m - 0.3, rightEdgeX = mp[1].world[0] + mp[1].half_width_m + 0.3;
var frontage = [centralX, leftEdgeX, rightEdgeX].map(function (x) { return { x: x, sweep: C.resolveMove({ x: x, z: facadeOutsideZ }, 0, facadeInsideZ - facadeOutsideZ, 0) }; });
ok('G05 exact portal subtraction preserves the visible market centre post and frontage beside both doors while the two declared thresholds stay open', frontage.every(function (q) { return q.sweep.blocked && q.sweep.hit && q.sweep.hit.district === 'market'; }), frontage);

var roomMap = { temple: ['TEMPLE_HALL'], tower: ['TOWER_HALL'], market: ['CLOTHING_SHOP', 'WEAPON_SHOP'] }, plans = [], interiorsOk = true;
affected.forEach(function (id) { var b = building(id); roomMap[id].forEach(function (roomId) { var r = ROOMS[roomId], p = r.interior_plan, half = r.size_m / 2; plans.push(p && p.plan_id); interiorsOk = interiorsOk && r.size_m <= Math.min(b.envelope_m.width, b.envelope_m.depth) + 0.1 && r.ceiling_m <= b.actual_height_m && r.ceiling_m >= 3 * 1.7 && r.flight_ceiling_m < r.ceiling_m && p && p.room_envelope_m.width === r.size_m && p.room_envelope_m.depth === r.size_m && p.ceiling_m === r.ceiling_m && p.feature_ids.length >= 3 && r.floor_levels.length >= 1 && Math.abs(r.spawn.x) < half && Math.abs(r.spawn.z) < half && Math.abs(r.exit.position.x) < half && Math.abs(r.exit.position.z) < half && (r.solids || []).every(function (s) { return s.x1 >= -half && s.x2 <= half && s.z1 >= -half && s.z2 <= half && s.h <= r.ceiling_m; }); }); });
ok('G06 temple, tower and both market wings are exterior-contained, ≥3-player-height grand volumes with distinct plan/style/features and synchronized visual/flight ceilings', interiorsOk && new Set(plans).size === 4 && ROOMS.TEMPLE_HALL.style_id !== ROOMS.TOWER_HALL.style_id, { plans: plans });
var zeroStock = [['CLOTHING_SHOP', 'SHOP_CLOTHING'], ['WEAPON_SHOP', 'SHOP_WEAPONS']].every(function (x) { var r = ROOMS[x[0]], sh = SHOPS.shops.filter(function (s) { return s.id === x[1]; })[0]; return r.interactables.length === 1 && r.interactables[0].kind === 'BROWSE' && r.interactables[0].shop === x[1] && sh.status === 'ZERO_STOCK' && sh.catalog.length === 0 && sh.purchase === 'DISABLED_NO_ECONOMY'; });
ok('G06 both finished market wings retain their honest zero-stock BROWSE contract with purchasing disabled', zeroStock);

var data = await loadHeadlessData(), H = createDuelHost({ data: data, composeHeadless: composeHeadless }); H.dev.createAccount('A', { classId: 'ATHLETE', sex: 'M' }); var con = H.connect({ client_id: 'm5-building', account_id: 'A', token: H.dev.tokens().A }), seq = 0;
function send(a, p) { return H.submit(makeEnvelope({ session_id: con.session_id, client_id: 'm5-building' }, ++seq, a, p || {})); } function tick(n) { for (var i = 0; i < n; i++) H.tick(data.cfg.dev('local_authority.tick_dt_s')); }
send('ENTER_ROOM', { room: 'FIELD' }); tick(2); var transactionsOk = true, txDiag = [];
  [['TEMPLE_DOOR', 'TEMPLE_HALL'], ['TOWER_DOOR', 'TOWER_HALL'], ['CLOTHING_DOOR', 'CLOTHING_SHOP'], ['WEAPON_DOOR', 'WEAPON_SHOP']].forEach(function (x) { var r = ROOMS[x[1]], yaw = r.door.facing || 0, ox = Math.sin(yaw), oz = -Math.cos(yaw), roomStyle = r.style_id || r.interior_plan.style_id, roomFeatures = r.feature_ids || r.interior_plan.feature_ids; for (var visit = 0; visit < 2; visit++) { H.dev.play('PLACE', { account_id: 'A', x: r.door.x + ox * 0.55, z: r.door.z + oz * 0.55 }); var before = H.snapshot(con.session_id).play, entryGround = before.flight.ground, en = send('ENTER_ROOM', { room: x[1] }); tick(2); var snap = H.snapshot(con.session_id).play; H.dev.play('PLACE', { account_id: 'A', x: r.exit.position.x, z: r.exit.position.z }); var out = send('ENTER_ROOM', { room: 'FIELD' }); tick(2); var field = H.snapshot(con.session_id).play, expectedX = r.door.x + ox * 0.55, expectedZ = r.door.z + oz * 0.55; var cycleOk = en.accepted && snap.room === x[1] && snap.ceiling_m === r.ceiling_m && snap.interior_plan && snap.interior_plan.plan_id === r.interior_plan.plan_id && snap.room_style_id === roomStyle && snap.floor_levels.length === r.floor_levels.length && snap.feature_ids.length === roomFeatures.length && snap.return_to && snap.return_to.door === x[0] && snap.return_to.clearance_m === 0.55 && out.accepted && out.returned_to_door === x[0] && Math.hypot(field.position.x - expectedX, field.position.z - expectedZ) < 0.01 && close(field.facing, yaw, 0.001) && close(field.flight.ground, entryGround, 0.001) && close(field.flight.altitude, entryGround, 0.001) && close(field.flight.height_above_ground, 0, 0.001); transactionsOk = transactionsOk && cycleOk; if (!cycleOk) txDiag.push({ door: x[0], room: x[1], visit: visit, enter: en, entry_ground: entryGround, snapshot: { room: snap.room, ceiling: snap.ceiling_m, plan: snap.interior_plan && snap.interior_plan.plan_id, style: snap.room_style_id, floors: snap.floor_levels && snap.floor_levels.length, features: snap.feature_ids && snap.feature_ids.length, return_to: snap.return_to }, exit: out, field: { position: field.position, facing: field.facing, flight: field.flight }, expected: { x: expectedX, z: expectedZ, facing: yaw, ground: entryGround } }); } });
  ok('G05/G06 every corrected entrance supports two complete host enter/inspect/exit cycles and returns 0.55 m outside the originating threshold on the same ground level with full plan metadata', transactionsOk, txDiag);

var staticSrc = fs.readFileSync(path.join(LA, 'deploy', 'build_static_demo.mjs'), 'utf8');
ok('G13 static packaging enumerates manifest runtime/lod/collider derivatives instead of copying only legacy _decimated files', /\['runtime', 'lod_runtime', 'collider_runtime'\]/.test(staticSrc) && /district derivative missing/.test(staticSrc));

console.log('RESULT M5 owner buildings: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
