/* Owner assignment 2026-09-18 §10 (lane E, host side): the TRAINING ROOM — GYM_DOOR / GYM_INTERIOR reused with a consistent label, a rules field OF ITS OWN
   (isolated from the FIELD: separate dummy, entities, practice state, colliders from the room's walls / benches / racks / cage), the dummy on the real
   eligible-target pipeline with damage / reset and no progression, casts blocked by the room's own walls, the exit returning to the door.
   node 16_TESTS/gameplay_training_room.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost } from '../26_LOCAL_AUTHORITY/DuelHost.js'; import { makeEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';
var HERE = path.dirname(fileURLToPath(import.meta.url));
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var data = await loadHeadlessData(); var cfg = data.cfg; var DT = cfg.dev('local_authority.tick_dt_s'); var ROOMS = cfg.dev('local_authority.play.rooms');
function newHost() { var h = createDuelHost({ data: data, composeHeadless: composeHeadless }); h.dev.createAccount('PLAYER_A', { classId: 'ATHLETE', sex: 'M' }); return h; }
function sess(h, account) { var c = h.connect({ client_id: 'c-' + account, account_id: account, token: h.dev.tokens()[account] }); if (!c.ok) throw new Error('connect ' + account + ' ' + c.reason); var seq = 0; return { send: function (action, payload) { return h.submit(makeEnvelope({ session_id: c.session_id, client_id: 'c-' + account }, ++seq, action, payload || {})); }, play: function () { return h.snapshot(c.session_id).play; }, rules: function () { return h.snapshot(c.session_id).play.rules; } }; }
function run(h, seconds) { var n = Math.round(seconds / DT); for (var i = 0; i < n; i++) h.tick(DT); }
function log(h, kind) { return h.dev.log().filter(function (e) { return e.kind === kind; }); }
function goTo(h, s, x, z, yawFace) { for (var p2 = 0; p2 < 4; p2++) { for (var i = 0; i < 2600; i++) { var p = s.play(); var pos = p.position; var dx = x - pos.x, dz = z - pos.z; var d = Math.hypot(dx, dz); if (d < 0.45) break; s.send('MOVE', { forward: +(-dz / d).toFixed(3), strafe: +(dx / d).toFixed(3), run: d > 4, fast: true, yaw: +Math.atan2(dx, -dz).toFixed(3) }); h.tick(DT); } s.send('MOVE', { forward: 0, strafe: 0, yaw: yawFace === undefined ? 0 : yawFace }); run(h, 0.6); var q = s.play().position; if (Math.hypot(x - q.x, z - q.z) < 0.9) break; } }
function dummyOf(s) { var r = s.rules(); return r ? r.others.filter(function (o) { return o.id === 'FIELD_DUMMY'; })[0] : null; }

var G = ROOMS.GYM_INTERIOR;
ok('data: GYM_INTERIOR is the TRAINING ROOM — label carries TRAINING ROOM, rules_17_23 on, a dummy position, racks + cage solids, three platforms, exit label consistent; ids GYM_INTERIOR / GYM_DOOR unchanged', /TRAINING ROOM/.test(G.label) && G.rules_17_23 === true && G.dummy_position && G.solids && G.solids.filter(function (x) { return !x.world; }).length === 7 && G.solids.length === 8 && G.platforms.length === 3   /* JOB B 2026-09-19: + the barbell prop solid (world:JOBB, generated from the world registry) */ && /TRAINING ROOM/.test(G.exit.label) && G.door.interactable === 'GYM_DOOR' && G.training && G.training.steps.length === 8, { label: G.label, solids: G.solids && G.solids.length });
var h = newHost(); var s = sess(h, 'PLAYER_A'); s.send('ENTER_ROOM', { room: 'FIELD' }); run(h, 0.5);
var col = s.rules().colliders; var door = col.interactables.filter(function (x) { return x.id === 'GYM_DOOR'; })[0];
ok('door: the exterior GYM_DOOR prompt reads TRAINING ROOM (the building keeps its MAH GYM identity)', !!door && /TRAINING ROOM/.test(door.label) && door.to.room === 'GYM_INTERIOR', door);
/* damage the FIELD dummy first so isolation can be shown */
s.send('FIELD_PRACTICE', { on: true }); run(h, 0.2); var fd0 = dummyOf(s); goTo(h, s, fd0.position.x, fd0.position.z + 2.0, 0); run(h, 0.4); s.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); s.send('RULES_CAST', {}); run(h, 2.0); var fieldHp = dummyOf(s).hp;
ok('field: the FIELD dummy took a hit before entering (hp ' + fieldHp + ' < ' + fd0.max + ')', fieldHp < fd0.max, fieldHp);
/* enter through the door */
h.dev.play('PLACE', { account_id: 'PLAYER_A', x: door.x + 1.2, z: door.z }); run(h, 0.3); s.send('MOVE', { forward: 0, strafe: 0, yaw: -Math.PI / 2 }); run(h, 0.3); var en = s.send('ENTER_ROOM', { room: 'GYM_INTERIOR' });   /* the walk across the plaza is the interior test's business (and the page probe's); here the dev PLACE fixture puts him at the door */ run(h, 0.3); var pin = s.play();
ok('entry: ENTER at the door is accepted; inside, the snapshot carries a RULES view of the room\'s OWN field (practice ON by default, its own dummy at the room dummy position, its own colliders version)', en.accepted && pin.room === 'GYM_INTERIOR' && pin.rules && pin.rules.practice === true && pin.rules.colliders && /GYM_INTERIOR/.test(pin.rules.colliders.version) && dummyOf(s) && Math.hypot(dummyOf(s).position.x - G.dummy_position.x, dummyOf(s).position.z - G.dummy_position.z) < 0.05, { en: en.reason || en.accepted, practice: pin.rules && pin.rules.practice, ver: pin.rules && pin.rules.colliders && pin.rules.colliders.version, dummy: dummyOf(s) && dummyOf(s).position });
var rd = dummyOf(s); ok('isolation: the room dummy is at full health (the FIELD dummy\'s damage did not follow), no residents in the room, no entities', rd.hp === rd.max && s.rules().others.length === 1 && s.rules().entities.length === 0, { hp: [rd.hp, rd.max], others: s.rules().others.map(function (o) { return o.id; }) });
ok('colliders: the room field lists the four walls, the lifting platform + two benches (walkable) and the racks / cage as solids; the ceiling is the room height', (function () { var sh = pin.rules.colliders.shapes; var walls = sh.filter(function (x) { return /_WALL_/.test(x.id); }).length, walk = sh.filter(function (x) { return x.walkable; }).length, racks = sh.filter(function (x) { return /RACK_|CAGE/.test(x.id); }).length, props = sh.filter(function (x) { return x.world; }).length; return walls === 4 && walk === 3 && racks === 7 && props === 1 && sh.every(function (x) { return x.h <= 3.2 + 1e-6 || x.walkable; }); })(), pin.rules.colliders.shapes.map(function (x) { return x.id; }));
/* practice on the room dummy: physical push, damage, reset, no progression */
goTo(h, s, rd.position.x, rd.position.z + 2.0, 0); run(h, 0.4); s.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); var c1 = s.send('RULES_CAST', {}); run(h, 2.0); var hp1 = dummyOf(s).hp; var lvl0 = s.play().level;
ok('practice: a PHYSICAL push at the room dummy lands (hp ' + rd.max + ' → ' + hp1 + '), the FIELD dummy is untouched by it, no XP / level change', c1.accepted && hp1 < rd.max && s.play().level === lvl0, { c1: c1.reason || c1.accepted, hp1: hp1, level: [lvl0, s.play().level] });
var pr = s.send('PRACTICE_RESET', {}); run(h, 0.3); var hpR = dummyOf(s).hp;
ok('reset: PRACTICE_RESET restores the room dummy to full health (' + hpR + ')', pr.accepted && hpR === rd.max, { pr: pr.reason || pr.accepted, hpR: hpR });
/* a projectile into the room wall: the room's own colliders stop it (WALL cause), no damage */
goTo(h, s, 6, 6, Math.PI / 2); run(h, 0.4); s.send('RULES_SELECT', { category: 'SPECIAL_MAGIC', slot: 0 }); var hpW0 = dummyOf(s).hp; var cw = s.send('RULES_CAST', { aim_yaw: Math.PI / 2 }); var wallImp = null; for (var i = 0; i < 60 && !wallImp; i++) { h.tick(DT); wallImp = s.rules().entities.filter(function (e) { return e.type === 'IMPACT' && e.cause === 'WALL'; })[0] || null; } run(h, 1.5);
ok('walls: a Vector Shot fired at the east wall ends at the wall (IMPACT cause WALL at x ≈ ' + (wallImp && wallImp.position.x) + ', the wall sits at x 14), no damage, the projectile does not leave the room', cw.accepted && !!wallImp && wallImp.position.x > 11 && wallImp.position.x <= 14.5 && dummyOf(s).hp === hpW0, { cw: cw.reason || cw.accepted, imp: wallImp && wallImp.position, hp: [hpW0, dummyOf(s).hp] });
/* flight inside: ceiling capped (already proven in the interior test) — cast in the air is accepted here too */
s.send('FLIGHT', { op: 'ENTER' }); run(h, 1.2); s.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); var fa = s.send('RULES_CAST', {}); run(h, 0.5); var pf = s.play(); s.send('FLIGHT', { op: 'EXIT' }); run(h, 3);
ok('flight inside: a cast while hovering under the 3.2 m ceiling is accepted (location-independent casting), the ceiling still caps the height', fa.accepted && pf.flight.altitude <= 3.3, { fa: fa.reason || fa.accepted, alt: pf.flight.altitude });
/* exit: back just outside the door, the FIELD field resumes with its own state. M5 keeps the 0.4 m actor capsule clear of the wall with a 0.55 m outward restore. */
goTo(h, s, G.exit.position.x, G.exit.position.z, 0); run(h, 0.4); var ex = s.send('ENTER_ROOM', { room: 'FIELD' }); run(h, 0.5); var pout = s.play();
var exitDx = pout.position.x - door.x, exitDz = pout.position.z - door.z, exitDistance = Math.hypot(exitDx, exitDz); var doorOut = { x: Math.sin(G.door.facing), z: -Math.cos(G.door.facing) }; var exitOutward = exitDx * doorOut.x + exitDz * doorOut.z;
ok('exit: EXIT lands 0.55 m outward from GYM_DOOR (clear of the wall); the FIELD rules view is back with ITS dummy still carrying the earlier damage (hp ' + (dummyOf(s) && dummyOf(s).hp) + ' = ' + fieldHp + ') — the two fields never mixed', ex.accepted && pout.room === 'FIELD' && Math.abs(exitDistance - 0.55) < 0.02 && exitOutward > 0.54 && dummyOf(s) && dummyOf(s).hp === fieldHp, { ex: ex.reason || ex.accepted, pos: pout.position, exit_distance_m: exitDistance, outward_m: exitOutward, fieldHp: [fieldHp, dummyOf(s) && dummyOf(s).hp] });
/* audit: room entry via the door, practice reset recorded */
var re = log(h, 'ROOM_ENTER'); ok('audit: ROOM_ENTER records via GYM_DOOR and the EXIT:GYM_DOOR return', re.some(function (e) { return e.room === 'GYM_INTERIOR' && e.via === 'GYM_DOOR'; }) && re.some(function (e) { return e.room === 'FIELD' && e.via === 'EXIT:GYM_DOOR'; }), re.slice(-3));
console.log('RESULT training room: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
