/* CONVERGENCE PASS 6 — SPEC F mocap pipeline (in-repository part): the clip manifest's fields and statuses, the validator on synthetic clips
   (what it PROVES: bone map / tracks / T-pose frames / contact frames / loop seams — and what it does not: motion quality), the import helper's
   refusal path, the generated capture checklist, and the Control Lab placeholder listing. node 16_TESTS/gameplay_mocap_pipeline.test.mjs */
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { fileURLToPath } from 'node:url';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.join(HERE, '..', '26_LOCAL_AUTHORITY'); var pass = 0, fail = 0;
function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var MF = path.join(LA, 'lab', 'mocap', 'clip_manifest.json'); var m = JSON.parse(fs.readFileSync(MF, 'utf8'));
/* ---- manifest fields (Spec F: state, pattern, tier, loop, root-motion flag, contact frames, cancel windows) + honest statuses ---- */
var FIELDS = ['id', 'state', 'mask', 'loop', 'root_motion', 'contact_frames', 'cancel_windows', 'status', 'min_duration_s', 'notes'];
ok('every clip entry carries the Spec F fields (state · pattern · tier · loop · root motion · contact frames · cancel windows) and a status', m.clips.length >= 20 && m.clips.every(function (c) { return FIELDS.every(function (f) { return c[f] !== undefined; }) && 'pattern' in c && 'tier' in c && /^(MISSING|PLACEHOLDER|VALIDATED|CAPTURED)$/.test(c.status); }), m.clips.filter(function (c) { return !FIELDS.every(function (f) { return c[f] !== undefined; }); }).map(function (c) { return c.id; }));
ok('no clip is marked CAPTURED (Claude Code never claims a capture exists) and every PLACEHOLDER names its source, its real required mask and is flagged for the Control Lab', m.clips.every(function (c) { return c.status !== 'CAPTURED'; }) && m.clips.filter(function (c) { return c.status === 'PLACEHOLDER'; }).every(function (c) { return c.placeholder && c.placeholder.source && c.placeholder.shown_in_control_lab === true && c.mask_required && c.file && fs.existsSync(path.join(LA, c.file)); }), m.clips.filter(function (c) { return c.status === 'PLACEHOLDER'; }).map(function (c) { return c.id; }));
var rigMf = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'assets', 'athlete_m_preview', 'dev_0.14', 'manifest.json'), 'utf8'));
ok('the manifest skeleton is the DISCOVERED rig: every listed joint exists in dev_0.14 and every mask uses listed joints', m.skeleton.joints.every(function (j) { return rigMf.joints.indexOf(j) >= 0; }) && Object.keys(m.skeleton.masks).every(function (k) { return m.skeleton.masks[k].every(function (j) { return m.skeleton.joints.indexOf(j) >= 0; }); }), { rig_joints: rigMf.joints.length, manifest_joints: m.skeleton.joints.length });
ok('the capture list covers Spec F v1 (idle · walk · jog · run · starts · stops · turns · six patterns × tiers · flight × 4 · guard · hits · knockdown · finish)', ['LOC_IDLE_CALM', 'LOC_WALK', 'LOC_JOG', 'LOC_RUN', 'LOC_START', 'LOC_STOP', 'LOC_TURN_IN_PLACE', 'LOC_QUICK_TURN', 'PAT_HORIZONTAL_PUSH', 'PAT_VERTICAL_PULL', 'PAT_HINGE', 'PAT_ROTATION', 'PAT_SQUAT', 'PAT_UPRIGHT_ROW', 'FLY_TAKEOFF', 'FLY_HOVER', 'FLY_CRUISE', 'FLY_LAND', 'GUARD', 'HIT_SMALL', 'HIT_BIG', 'KNOCKDOWN_GETUP', 'FINISH_TAUNT'].every(function (id) { return m.clips.some(function (c) { return c.id === id; }); }) && m.clips.filter(function (c) { return /^PAT_/.test(c.id); }).every(function (c) { return Array.isArray(c.tier) && c.tier.length === 3; }));
/* ---- the validator on synthetic clips ---- */
var tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'mah-mocap-')); var FULL = m.skeleton.masks.FULL_SPLIT.filter(function (b) { return b !== 'ROOT'; });
function synth(opts) { var fps = 30, n = Math.round((opts.seconds || 9) * fps) + 1; var frames = [];   /* + the repeat frame (last = first) that a loop clip carries */ for (var i = 0; i < n; i++) { var t = i / fps, ph = 2 * Math.PI * t * (opts.cadence_hz || 1); var row = {}; FULL.forEach(function (b) { row[b] = [0.05, 0.02, -0.03]; }); row.THIGH_L = [0.5 * Math.sin(ph), 0, 0.05]; row.THIGH_R = [-0.5 * Math.sin(ph), 0, -0.05]; row.SHIN_L = [0.3 + 0.3 * Math.max(0, -Math.sin(ph)), 0, 0]; row.SHIN_R = [0.3 + 0.3 * Math.max(0, Math.sin(ph)), 0, 0]; row.UPPERARM_L = [-0.3 * Math.sin(ph), 0, 0.1]; row.UPPERARM_R = [0.3 * Math.sin(ph), 0, -0.1]; if (opts.root) row.ROOT_POS = [0, 0.02 * Math.sin(2 * ph), -t * 1.2]; if (opts.tposeAt !== undefined && i === opts.tposeAt) FULL.forEach(function (b) { row[b] = [0, 0, 0]; }); if (opts.dropBone) delete row[opts.dropBone]; if (opts.nanAt !== undefined && i === opts.nanAt) row.CHEST = [NaN, 0, 0]; if (opts.seamBreak && i === n - 1) row.SPINE = [0.9, 0, 0]; frames.push(row); } return { meta: { fps: fps, frames: n, source: 'synthetic', clip: opts.id }, frames: frames }; }
function validate(clip, id) { var f = path.join(tmp, id + '_' + Math.random().toString(36).slice(2) + '.json'); fs.writeFileSync(f, JSON.stringify(clip)); var r = spawnSync(process.execPath, [path.join(LA, 'mocap', 'validate_clip.mjs'), f, '--id', id, '--json'], { encoding: 'utf8' }); try { return JSON.parse(r.stdout); } catch (e) { return { pass: false, error: r.stderr || r.stdout }; } }
var good = validate(synth({ id: 'LOC_WALK', root: true, seconds: 9 }), 'LOC_WALK');
ok('validator: a well-formed synthetic WALK loop passes every structural check (bone map, tracks, no T-pose frames, contacts on both tips, loop seam)', good.pass === true && good.measured && good.measured.contacts && good.measured.contacts.TIP_L.count >= 2, good.pass ? { contacts: good.measured.contacts && [good.measured.contacts.TIP_L.count, good.measured.contacts.TIP_R.count], seam: good.measured.loop_seam } : good);
var tp = validate(synth({ id: 'LOC_WALK', root: true, tposeAt: 40 }), 'LOC_WALK'); ok('validator: one T-pose frame fails the clip and is named', tp.pass === false && tp.measured.bind_frames.indexOf(40) >= 0, tp.measured && tp.measured.bind_frames);
var mb = validate(synth({ id: 'LOC_WALK', root: true, dropBone: 'SHIN_R' }), 'LOC_WALK'); ok('validator: a missing joint track fails the bone map and names the joint', mb.pass === false && mb.measured.missing_bones.indexOf('SHIN_R') >= 0, mb.measured && mb.measured.missing_bones);
var nn = validate(synth({ id: 'LOC_WALK', root: true, nanAt: 12 }), 'LOC_WALK'); ok('validator: a non-finite value on one frame fails the tracks check', nn.pass === false && nn.checks.some(function (c) { return /non-finite/.test(c.name) && !c.pass; }));
var sb = validate(synth({ id: 'LOC_WALK', root: true, seamBreak: true }), 'LOC_WALK'); ok('validator: a broken loop seam (last frame 0.9 rad off the first) fails the loop check', sb.pass === false && sb.measured.loop_seam && sb.measured.loop_seam.worst_rad > 0.5, sb.measured && sb.measured.loop_seam);
var nr = validate(synth({ id: 'LOC_WALK', root: false }), 'LOC_WALK'); ok('validator: a root-motion clip without a ROOT_POS track fails', nr.pass === false && nr.checks.some(function (c) { return /ROOT_POS/.test(c.name) && !c.pass; }));
var sh = validate(synth({ id: 'LOC_IDLE_CALM', seconds: 5 }), 'LOC_IDLE_CALM'); ok('validator: a clip shorter than the manifest minimum fails the duration check (5 s idle vs 60 s)', sh.pass === false && sh.checks.some(function (c) { return /duration/.test(c.name) && !c.pass; }));
ok('validator: the verdict text never claims motion quality', good.verdict && /structure only/.test(good.verdict));
/* ---- the real placeholders validate against their honest (donor) mask ---- */
var ph = m.clips.filter(function (c) { return c.status === 'PLACEHOLDER'; }); var phOk = ph.every(function (c) { var r = spawnSync(process.execPath, [path.join(LA, 'mocap', 'validate_clip.mjs'), path.join(LA, c.file), '--id', c.id, '--json'], { encoding: 'utf8' }); try { return JSON.parse(r.stdout).pass === true; } catch (e) { return false; } });
ok('the two Tripo placeholders pass the validator for the UPPER_DONOR mask they actually cover (and are marked as needing the full UPPER mask)', ph.length === 2 && phOk && ph.every(function (c) { return c.mask === 'UPPER_DONOR' && c.mask_required === 'UPPER'; }));
/* ---- import helper refuses a failing clip ---- */
var bad = path.join(tmp, 'bad.json'); fs.writeFileSync(bad, JSON.stringify(synth({ id: 'LOC_WALK', root: true, tposeAt: 3 }))); var imp = spawnSync(process.execPath, [path.join(LA, 'mocap', 'import_clip.mjs'), bad, '--id', 'LOC_WALK', '--out', path.join(tmp, 'out.json')], { encoding: 'utf8' });
ok('import helper: a clip that fails the validator is NOT written and the manifest is untouched', imp.status !== 0 && !fs.existsSync(path.join(tmp, 'out.json')) && JSON.stringify(JSON.parse(fs.readFileSync(MF, 'utf8'))) === JSON.stringify(m), { status: imp.status });
var goodF = path.join(tmp, 'good.json'); fs.writeFileSync(goodF, JSON.stringify(synth({ id: 'LOC_WALK', root: true }))); var imp2 = spawnSync(process.execPath, [path.join(LA, 'mocap', 'import_clip.mjs'), goodF, '--id', 'LOC_WALK', '--out', path.join(tmp, 'good_out.json')], { encoding: 'utf8' });
ok('import helper: a passing clip is written in the runtime clip shape (meta.fps, frames[i][BONE] = [x, y, z]) without touching the manifest (no --register)', imp2.status === 0 && (function () { var c = JSON.parse(fs.readFileSync(path.join(tmp, 'good_out.json'), 'utf8')); return c.meta && c.meta.fps === 30 && c.meta.clip === 'LOC_WALK' && Array.isArray(c.frames[0].THIGH_L) && c.frames[0].THIGH_L.length === 3; })() && JSON.stringify(JSON.parse(fs.readFileSync(MF, 'utf8'))) === JSON.stringify(m), imp2.stderr.slice(0, 200));
/* ---- checklist ---- */
var ck = spawnSync(process.execPath, [path.join(LA, 'mocap', 'make_checklist.mjs'), '--out', path.join(tmp, 'CHECK.md')], { encoding: 'utf8' }); var md = fs.existsSync(path.join(tmp, 'CHECK.md')) ? fs.readFileSync(path.join(tmp, 'CHECK.md'), 'utf8') : '';
ok('the capture checklist is generated from the manifest (every clip id present, placeholders named as placeholders, plain-words setup, no external account asked of Claude Code)', ck.status === 0 && m.clips.every(function (c) { return md.indexOf('**' + c.id + '**') >= 0; }) && /placeholder in the game \(not a recording\)/.test(md) && /whole body in frame/.test(md) && /does not judge the motion/.test(md));
var tracked = fs.readFileSync(path.join(LA, 'mocap', 'CAPTURE_CHECKLIST.md'), 'utf8'); ok('the tracked CAPTURE_CHECKLIST.md is the generator’s own output for the current manifest', tracked.replace(/\s+$/, '') === md.replace(/\s+$/, ''));
/* ---- Control Lab + build ---- */
var play = fs.readFileSync(path.join(LA, 'lab', 'play.js'), 'utf8'), build = fs.readFileSync(path.join(LA, 'deploy', 'build_static_demo.mjs'), 'utf8');
ok('the Control Lab lists the manifest’s PLACEHOLDER clips and the recorded / wanted counts (MOTION → "mocap clips"), and the static build ships the manifest', /lab\.bind\('MOTION', 'mocap clips', \{ kind: 'read'/.test(play) && /clip_manifest\.json/.test(play) && /copy\(path\.join\(LAB, 'mocap', 'clip_manifest\.json'\)\)/.test(build));
fs.rmSync(tmp, { recursive: true, force: true });
console.log('RESULT mocap pipeline: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
