/* OWNER INTERJECTION 2026-09-18 phase F: the ⚔ STATS / SKILLS surface as a UI + DATA CONTRACT — FORCE · POWER · ENGINE · CONTROL · RESILIENCE (0–999) from
   ONE canonical file, class baselines honestly SOURCE_NOT_FOUND (never invented), points per level OWNER_DECISION (3 or 4, one centralized entry),
   PREVIEW-only allocation, Q07 unresolved, branching progression with FUTURE / LOCKED nodes, and NO live rebalance (the host never reads the file).
   node 16_TESTS/gameplay_stats_phase_f.test.mjs */
import fs from 'node:fs';
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var RT = new URL('../', import.meta.url); function read(rel) { return fs.readFileSync(new URL(rel, RT), 'utf8'); }
var CS = JSON.parse(read('00_CORE/class_stats.dev.json')); var menu = read('26_LOCAL_AUTHORITY/lab/gameMenu.js'); var html = read('26_LOCAL_AUTHORITY/lab/play.html'); var build = read('26_LOCAL_AUTHORITY/deploy/build_static_demo.mjs');
var hostSrc = ['26_LOCAL_AUTHORITY/play/PlayMode.js', '26_LOCAL_AUTHORITY/play/rules1723/RulesField.js', '26_LOCAL_AUTHORITY/play/rules1723/RulesMath.js', '26_LOCAL_AUTHORITY/DuelHost.js', '00_CORE/config.js'].map(read).join('\n');
ok('§5.3 the canonical five-stat family, 0–999, in ONE file (00_CORE/class_stats.dev.json, EXPERIMENTAL): FORCE · POWER · ENGINE · CONTROL · RESILIENCE', CS.schema === 'mahworld.class_stats.v0' && CS.classification === 'EXPERIMENTAL' && JSON.stringify(CS.family) === '["FORCE","POWER","ENGINE","CONTROL","RESILIENCE"]' && CS.max === 999);
ok('§5.3 class baselines are NOT invented: every class is null with the status SOURCE_NOT_FOUND and the searched roots recorded; the identities are the canon\'s text sentences', CS.class_baselines._status === 'SOURCE_NOT_FOUND' && ['ATHLETE', 'TITAN', 'LEAN', 'BAGE', 'VISIONARY'].every(function (c) { return CS.class_baselines[c] === null && typeof CS.identities[c] === 'string'; }) && /Fitness Class Archetypes/.test(CS.class_baselines._doc) && /searched 2026-09-19/.test(CS.class_baselines._doc) && /MAHWORLD_GAMEPLAY_CANON\.md/.test(CS.class_baselines.identity_source));
ok('§5.3 points per level = ONE centralized OWNER_DECISION between 3 and 4 (value null, never hard-coded elsewhere); allocation is PREVIEW only (live false); Q07 competitive fairness UNRESOLVED', CS.points_per_level.value === null && JSON.stringify(CS.points_per_level.candidates) === '[3,4]' && CS.points_per_level.status === 'OWNER_DECISION' && CS.allocation.live === false && CS.allocation.preview_only === true && CS.competitive_fairness.question === 'Q07' && CS.competitive_fairness.status === 'UNRESOLVED' && !/points_per_level\s*[:=]\s*[34]\b/.test(menu + hostSrc));
ok('§5.2 branching progression: PHYSICAL / MAHGIC / HYBRID / CLASS branches declared FUTURE with no invented requirement', CS.progression.branches.length === 4 && CS.progression.branches.every(function (b) { return b.status === 'FUTURE' && (b.requirement === null || /future concepts/.test(b.requirement)); }) && CS.progression.branches.map(function (b) { return b.id; }).join() === 'PHYSICAL,MAHGIC,HYBRID,CLASS');
ok('no live rebalance: the HOST never reads class_stats (no reference in PlayMode / RulesField / RulesMath / DuelHost / config); only the ⚔ panel fetches it', !/class_stats/.test(hostSrc) && /fetch\('\.\/class_stats\.dev\.json'\)/.test(menu) && /fetch\('\.\.\/\.\.\/00_CORE\/class_stats\.dev\.json'\)/.test(menu));
ok('the ⚔ STATS card renders the five stats with "class baseline: source not found", the OWNER_DECISION line with both candidate totals, the PREVIEW budget / left / reset, the identity and Q07; +/− change only the panel\'s preview map', /function statsCard\(cls, lvl\)/.test(menu) && /class baseline: source not found/.test(menu) && /points per level: <b>OWNER_DECISION<\/b>/.test(menu) && /PREVIEW only \\u2014 nothing is awarded, saved or applied to combat/.test(menu) && /else if \(m === 'stat-plus' \|\| m === 'stat-minus'\) \{ var sk = b\.getAttribute\('data-stat'\); var cur = st\.preview\[sk\] \|\| 0;/.test(menu) && !/send\('[A-Z_]*STAT/.test(menu) && /#g-menu \.mstat \{ display: grid;/.test(html));
ok('the ⚔ SKILLS card renders the progression nodes from the REAL bands (FOUNDATION current, CLASS DEVELOPMENT from foundation_max_level + 1, "OPEN (never auto-selected)"), the FUTURE branches and the class future concepts from the ruleset; every non-current node says "not grantable"', /function progressionCard\(r\)/.test(menu) && /var cdLevel = fml !== null \? fml \+ 1 : null;/.test(menu) && /stack selection \/ branching: OPEN \(never auto-selected\)/.test(menu) && /not grantable here/.test(menu) && /future_concepts \|\| \[\]\)\.filter\(function \(f\) \{ return f\.class === cls; \}\)/.test(menu) && /#g-menu \.mnode\.future \{ border-style: dotted;/.test(html));
ok('the static build pre-bakes the file for the host map AND copies it next to the page for the panel', /'CLAUDE_GAMEPLAY_RUNTIME\/00_CORE\/class_stats\.dev\.json'/.test(build) && /LAB_REL \+ '\/class_stats\.dev\.json'/.test(build));
['portrait', 'desktop'].forEach(function (mode) { var rec = null; try { rec = JSON.parse(fs.readFileSync(new URL('../25_HANDOFF/CONVERGENCE/stats_f/probe_sword_stats_' + mode + '.json', import.meta.url), 'utf8')); } catch (e) { }
  ok('phase F page probe record exists and passed for ' + mode + (mode === 'portrait' ? ' (touch EMULATED)' : ''), !!rec && rec.fail === 0 && (mode === 'portrait' ? rec.touch_emulated === true : rec.touch_emulated === false), rec ? { pass: rec.pass, fail: rec.fail, fails: rec.checks.filter(function (l) { return /^FAIL/.test(l); }).slice(0, 3) } : 'missing'); });
console.log('RESULT STATS PHASE F: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
