/* P7 (master §14 / U06–U16) — MAHGIC TREE PROTOTYPE: geometry, scale, attachment, normals, registry safety and scope contracts in node (the
   vendored three.js builds the same BufferGeometries the page uses), plus the tracked page evidence (deploy/probe_botany.mjs → 25_HANDOFF/CONVERGENCE/botany).
   node 16_TESTS/gameplay_mahgic_tree.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { fileURLToPath } from 'node:url';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.join(HERE, '..', '26_LOCAL_AUTHORITY'); var LAB = path.join(LA, 'lab');
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var THREE = await import('file:///' + path.join(LA, 'vendor', 'three', 'three.module.min.js').replace(/\\/g, '/'));
var T = await import('file:///' + path.join(LAB, 'mahgicTree.js').replace(/\\/g, '/'));
var S = T.TREE_SPEC; var REG = JSON.parse(fs.readFileSync(path.join(LAB, 'assets', 'botany', 'prototype_v1.json'), 'utf8'));
var fam = T.createMahgicTreeFamily(THREE, {}); var V = fam.variants;
/* ---- scale (U06): the reference is measured from the rig, the crown is inside the hip band ---- */
ok('U06 the scale record names the reference body, the pose and the measured joint heights (pelvis 0.765 m, femoral head 0.835 m above the lowest point)', S.scale_reference && S.scale_reference.pelvis_joint_m === 0.765 && S.scale_reference.femoral_head_joint_m === 0.835 && /dev_0\.14/.test(S.scale_reference.body) && /grounded/.test(S.scale_reference.pose), S.scale_reference);
ok('U06 every variant crown top is authored inside the hip band (0.765–0.835 m) and measured on the built geometry (fit recorded)', V.every(function (v) { return v.stats.crown_top_m >= 0.765 && v.stats.crown_top_m <= 0.835 && Math.abs(v.stats.crown_top_m - v.box.max.y) < 1e-3 && v.stats.fit_scale > 0.7 && v.stats.fit_scale < 1.3; }), V.map(function (v) { return { seed: v.stats.seed, top: v.stats.crown_top_m, fit: v.stats.fit_scale }; }));
ok('U06 the base sits on the ground (lowest point within 2 mm of y = 0; no floating stalk)', V.every(function (v) { return v.box.min.y > -0.002 && v.box.min.y < 0.002; }), V.map(function (v) { return v.box.min.y; }));
/* ---- hierarchy (U07): rooted, trunk, primary, secondary, twigs; authored bounds ---- */
ok('U07 each variant is a 4-level authored hierarchy: 5 root lobes, 4–5 primaries, ≥ 2 secondaries per primary, ≥ 1 twig per secondary on average, bounded counts', V.every(function (v) { var s = v.stats; return s.roots === 5 && s.levels === 4 && s.primaries >= 4 && s.primaries <= 5 && s.secondaries >= 2 * s.primaries && s.secondaries <= 15 && s.twigs >= s.secondaries * 0.9 && s.twigs <= 20; }), V.map(function (v) { return v.stats; }));
ok('U07 the crown is wider than a rod: width ≥ 0.6 × height on every variant', V.every(function (v) { return v.stats.width_m >= 0.6 * v.stats.crown_top_m; }), V.map(function (v) { return [v.stats.width_m, v.stats.crown_top_m]; }));
/* ---- craft (U08): leaves attached, junction spheres present, geometry finite, normals unit and consistent with the winding ---- */
function positions(g) { return g.attributes.position.array; } function normals(g) { return g.attributes.normal.array; }
ok('U08 every leaf attachment point lies on a branch (within 2.5 cm of a branch vertex) — no floating leaves', V.every(function (v) { var bp = positions(v.branches); var n = bp.length / 3; return v.leafOrigins.every(function (o) { var best = 1e9; for (var i = 0; i < n; i++) { var dx = bp[i * 3] - o[0], dy = bp[i * 3 + 1] - o[1], dz = bp[i * 3 + 2] - o[2]; var d = dx * dx + dy * dy + dz * dz; if (d < best) best = d; } return Math.sqrt(best) <= 0.025; }); }), V.map(function (v) { return v.leafOrigins.length; }));
ok('U08 leaves are numerous, clustered and layered (60–150 per variant) and every variant has junction spheres at each branch origin (junctions ≥ secondaries)', V.every(function (v) { return v.stats.leaves >= 60 && v.stats.leaves <= 150 && v.stats.junctions >= v.stats.secondaries; }), V.map(function (v) { return [v.stats.leaves, v.stats.junctions]; }));
ok('U08 all positions and normals are finite and every normal is unit length (±1e-3)', V.every(function (v) { return ['branches', 'leaves', 'gems'].every(function (k) { var p = positions(v[k]), nn = normals(v[k]); for (var i = 0; i < p.length; i++) if (!isFinite(p[i])) return false; for (var j = 0; j < nn.length; j += 3) { var l = Math.hypot(nn[j], nn[j + 1], nn[j + 2]); if (!isFinite(l) || Math.abs(l - 1) > 1e-3) return false; } return true; }); }));
function windingAgreement(g) { var p = positions(g), nn = normals(g); var agree = 0, tot = 0; for (var i = 0; i < p.length; i += 9) { var ux = p[i + 3] - p[i], uy = p[i + 4] - p[i + 1], uz = p[i + 5] - p[i + 2], vx = p[i + 6] - p[i], vy = p[i + 7] - p[i + 1], vz = p[i + 8] - p[i + 2]; var fx = uy * vz - uz * vy, fy = uz * vx - ux * vz, fz = ux * vy - uy * vx; var d = fx * (nn[i] + nn[i + 3] + nn[i + 6]) + fy * (nn[i + 1] + nn[i + 4] + nn[i + 7]) + fz * (nn[i + 2] + nn[i + 5] + nn[i + 8]); tot++; if (d > 0) agree++; } return agree / tot; }
ok('U08 the face winding agrees with the stored normals on ≥ 99 % of triangles (branches / leaves / gems: outward, consistently wound)', V.every(function (v) { return ['branches', 'leaves', 'gems'].every(function (k) { return windingAgreement(v[k]) >= 0.99; }); }), V.map(function (v) { return ['branches', 'leaves', 'gems'].map(function (k) { return +windingAgreement(v[k]).toFixed(4); }); }));
function signedVolume(g) { var p = positions(g); var vol = 0; for (var i = 0; i < p.length; i += 9) { vol += (p[i] * (p[i + 4] * p[i + 8] - p[i + 5] * p[i + 7]) - p[i + 1] * (p[i + 3] * p[i + 8] - p[i + 5] * p[i + 6]) + p[i + 2] * (p[i + 3] * p[i + 7] - p[i + 4] * p[i + 6])) / 6; } return vol; }
ok('U08 the leaf and gem solids are closed with outward faces (positive signed volume)', V.every(function (v) { return signedVolume(v.leaves) > 0 && signedVolume(v.gems) > 0; }), V.map(function (v) { return [+signedVolume(v.leaves).toExponential(2), +signedVolume(v.gems).toExponential(2)]; }));
ok('U15 the geometry budget is authored and bounded: ≤ 9 000 triangles per variant, three materials, aGlow / color attributes present for the shared shaders', V.every(function (v) { return v.stats.tris.total <= 9000 && v.branches.attributes.aGlow && v.branches.attributes.color && v.leaves.attributes.color; }), V.map(function (v) { return v.stats.tris.total; }));
/* ---- determinism and idempotence (U14) ---- */
function hash(g) { return crypto.createHash('sha256').update(Buffer.from(positions(g).buffer)).digest('hex').slice(0, 16); }
var fam2 = T.createMahgicTreeFamily(THREE, {}); ok('U14 the family is deterministic: rebuilding gives byte-identical variant geometry (seeded, no Math.random)', V.every(function (v, i) { return hash(v.branches) === hash(fam2.variants[i].branches) && hash(v.leaves) === hash(fam2.variants[i].leaves); }), V.map(function (v) { return hash(v.branches); }));
var i1 = fam.place(REG.instances), i2 = fam.place(REG.instances); ok('U14 placing the registry twice does not accumulate: same instance count and draw calls, one mesh set in the group', i1.instances === REG.instances.length && i2.instances === i1.instances && i2.draw_calls === i1.draw_calls && fam.group.children.length === i1.draw_calls, { first: i1.instances, second: i2.instances, draws: i2.draw_calls, children: fam.group.children.length });
ok('U14 the read-out lists each placed instance with identity, position, yaw, scale and its own crown top and radius', i2.list.length === 7 && i2.list.every(function (e) { return e.id && typeof e.crown_top_m === 'number' && typeof e.radius_m === 'number'; }), i2.list.slice(0, 2));
/* ---- registry (U13 placement discipline for the prototype) ---- */
var ids = REG.instances.map(function (e) { return e.id; }); ok('U13 registry: 7 instances (1 specimen + 6 cluster), unique ids, PROTOTYPE status, scales within 0.97–1.03', REG.instances.length === 7 && new Set(ids).size === 7 && REG.instances.filter(function (e) { return e.role === 'specimen'; }).length === 1 && /PROTOTYPE/.test(REG.status) && REG.instances.every(function (e) { return e.scale >= 0.97 && e.scale <= 1.03; }), REG.status);
ok('U13 every placed crown top stays within 3 cm of the hip band after the instance scale', i2.list.every(function (e) { return e.crown_top_m >= 0.735 && e.crown_top_m <= 0.865; }), i2.list.map(function (e) { return e.crown_top_m; }));
function distToSeg(px, pz, ax, az, bx, bz) { var vx = bx - ax, vz = bz - az; var t = Math.max(0, Math.min(1, ((px - ax) * vx + (pz - az) * vz) / (vx * vx + vz * vz))); return Math.hypot(px - (ax + vx * t), pz - (az + vz * t)); }
var PATHS = [[-17, 0], [0, -19.5], [18, 0], [1, 20]].map(function (e) { var d = Math.hypot(e[0], e[1]); return [e[0] * 11 / d, e[1] * 11 / d, e[0], e[1]]; });   /* the four pathway inlays: plaza ring (r = 11 m) → entrance */
ok('U13 nothing sits on a pathway inlay (≥ 1.6 m from the four plaza → entrance lines), on the spawn (0,4) or on the practice dummy (0,−2) (≥ 2 m)', REG.instances.every(function (e) { return PATHS.every(function (p) { return distToSeg(e.x, e.z, p[0], p[1], p[2], p[3]) >= 1.6; }) && Math.hypot(e.x, e.z - 4) >= 2 && Math.hypot(e.x, e.z + 2) >= 2; }), REG.instances.map(function (e) { return [e.id, +Math.min.apply(null, PATHS.map(function (p) { return distToSeg(e.x, e.z, p[0], p[1], p[2], p[3]); })).toFixed(2)]; }));
ok('U13 the cluster is small and varied: 6 instances within a 3.5 m radius using all three variants and distinct yaws', (function () { var c = REG.instances.filter(function (e) { return e.role === 'cluster'; }); var cx = c.reduce(function (s, e) { return s + e.x; }, 0) / c.length, cz = c.reduce(function (s, e) { return s + e.z; }, 0) / c.length; return c.length === 6 && c.every(function (e) { return Math.hypot(e.x - cx, e.z - cz) <= 3.5; }) && new Set(c.map(function (e) { return e.variant; })).size === 3 && new Set(c.map(function (e) { return e.yaw_deg; })).size === 6; })());
/* ---- scope and policy (U12 / U16 / §14.6) ---- */
var fsrc = fs.readFileSync(path.join(LAB, 'fieldScene.js'), 'utf8'), csrc = fs.readFileSync(path.join(LAB, 'cityScene.js'), 'utf8'), tsrc = fs.readFileSync(path.join(LAB, 'mahgicTree.js'), 'utf8'), psrc = fs.readFileSync(path.join(LAB, 'play.js'), 'utf8');
ok('U12 the old laser-plant family and the TREE ELEVATOR are untouched (city.dress still draws the stalks + square-diamond leaves; the prototype is additive until Jah approves)', /city\.dress\(size\)/.test(fsrc) && /laser plants: instanced stalks/.test(csrc) && /treeElevator: function/.test(csrc) && /createMahgicTreeFamily\(THREE, \{ night: NIGHT \}\)/.test(fsrc));
ok('U16 the family has no interaction, collider or economy hooks (no host sends, no rules import, no INTERACT / heal / loot / harvest code; the spec records collision NONE and interaction NONE)', !/send\(|INTERACT|rules1723|PlayMode|fetch\(/.test(tsrc) && !/\b(heal|loot|harvest|craft)\w*\s*[:(=]/.test(tsrc) && /NONE/.test(S.collision) && /NONE/.test(S.interaction));
ok('§14.6 reversible and idempotent wiring: ?botany=0 disables the family, the rebuild path disposes it, the tick drives the shared shader clock, the VFX-off hook turns the energy off', /botany: params\.get\('botany'\) !== '0'/.test(psrc) && /botany\.dispose\(\)/.test(fsrc) && /botany\.tick\(dt, t\)/.test(fsrc) && /fieldScene\.botanyEnergy\(!VFX_OFF\)/.test(psrc));
ok('build: the family module, the spec and the prototype registry are shipped in the static build', ['lab/mahgicTree.js', 'lab/assets/botany/tree_spec.js', 'lab/assets/botany/prototype_v1.json'].every(function (f) { return fs.existsSync(path.join(LA, 'deploy', 'static_dist', 'CLAUDE_GAMEPLAY_RUNTIME', '26_LOCAL_AUTHORITY', f)); }));
/* ---- U15 definitions only (no scene change): the far LOD variant and the placement mask preview ---- */
V.forEach(function (v, i) { var f = T.buildTreeVariant(THREE, S, S.variant_seeds[i], { far: true }); ok('U15 far-LOD definition seed ' + S.variant_seeds[i] + ': ≤ 50 % of the near triangles, no twigs / gems, the same crown top (seed-aligned silhouette)', f.stats.tris.total <= 0.5 * v.stats.tris.total && f.stats.twigs === 0 && f.stats.gems === 0 && Math.abs(f.stats.crown_top_m - v.stats.crown_top_m) < 0.002 && f.stats.leaves >= 15, { near: v.stats.tris.total, far: f.stats.tris.total, leaves: f.stats.leaves }); });
var PLC = JSON.parse(fs.readFileSync(path.join(LAB, 'assets', 'botany', 'placement_v1.json'), 'utf8')); var cp = await import('node:child_process');
var prev = null; try { var outP = path.join(LA, 'deploy', 'probe_out', 'botany', 'placement_preview.json'); cp.execFileSync(process.execPath, [path.join(LA, 'deploy', 'botany_placement_preview.mjs'), '--out', outP], { stdio: 'pipe' }); prev = JSON.parse(fs.readFileSync(outP, 'utf8')); } catch (e) { }
ok('U13 placement DEFINITION (not placed): the mask excludes solids, landmark envelopes, pathways, streets, routes, clearances and the spawn→temple sightline; the seeded preview stays under the hard cap with every candidate outside every exclusion', /DEFINITION_ONLY/.test(PLC.status) && !!prev && prev.candidates <= PLC.distribution.hard_cap && prev.candidates > 20 && Object.keys(prev.exclusion_hits_by_kind).length >= 6 && prev.candidates_list.every(function (c) { return PLC.exclusions.clearances.every(function (cl) { return Math.hypot(c.x - cl.cx, c.z - cl.cz) > cl.r; }) && Math.hypot(c.x, c.z) >= 13.5; }), prev && { candidates: prev.candidates, clusters: prev.clusters, per_region: prev.per_region, area_m2: prev.eligible_area_m2 });
ok('U11 nothing in the runtime reads the placement definition yet (no scatter before the verdict): fieldScene places only prototype_v1.json', !/placement_v1/.test(fsrc) && /prototype_v1\.json/.test(fsrc));
/* ---- the tracked page evidence (deploy/probe_botany.mjs) ---- */
var EV = path.join(HERE, '..', '25_HANDOFF', 'CONVERGENCE', 'botany', 'probe_botany.json'); var r = null; try { r = JSON.parse(fs.readFileSync(EV, 'utf8')); } catch (e) { }
ok('page evidence: the botany probe record exists and passed (placement, hip band, silhouette, paired scale view, sway, camera boom inside the cluster, matched workload, phone framing, zero errors)', !!r && r.summary && r.summary.fail === 0 && r.summary.pass >= 11 && r.silhouette && r.sway && r.cam_inside && r.matched_workload, r && r.summary);
ok('page evidence: the MATCHED workload (same load, A B A B) accounts for the family exactly: Δ triangles ≈ placed + shadow-casting (within 500), Δ draw calls = the instanced draws of both passes', !!r && r.matched_workload && Math.abs(r.matched_workload.delta.triangles - r.matched_workload.delta.expected_triangles_main_plus_shadow) <= 500 && r.matched_workload.delta.calls >= 6 && r.matched_workload.delta.calls <= 16, r && r.matched_workload && r.matched_workload.delta);
ok('page evidence: the sway is gentle and grounded (< 6 % of the frame changed in 1.5 s, biased to the crown) and the boom kept its distance inside the cluster', !!r && r.sway.changed_pct < 6 && r.sway.upper_half >= r.sway.lower_half * 0.8 && Math.abs(r.cam_inside.applied - r.cam_inside.dist) < 0.05, r && { sway: r.sway, cam: r.cam_inside });
console.log('RESULT mahgic tree: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
