/* G37 (master §11.4) — the declared pointed contact and the world-space support hold: the animator's contract in node (defaults, rollback
   path, read-out shape, the pendulum untouched when the hold is off) plus the tracked page record (deploy/probe_motion_e.mjs → 25_HANDOFF/CONVERGENCE/motion_e/motion_e.json).
   node 16_TESTS/gameplay_g37_contact.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.join(HERE, '..', '26_LOCAL_AUTHORITY');
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var DEF = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'presentation_defaults.json'), 'utf8')); var G = DEF.gait;
ok('defaults: the world-space hold is ON by default with its four tunables and a declared-contact record; the PASS 5 drift tunables remain only as the rollback path', G.plant === true && G.plant_reach_frac > 0.9 && G.plant_reach_frac <= 1 && G.plant_hold_behind_m > 0.2 && G.plant_release_s > 0 && G.plant_engage_s > 0 && /world-fixed|WORLD-FIXED/.test(G._doc_plant) && /pointed end/i.test(G._doc_plant) && /rollback|A\/B/.test(G._doc_plant) && G.support_drift === 0.45, { plant: G.plant, reach: G.plant_reach_frac, behind: G.plant_hold_behind_m });
var src = fs.readFileSync(path.join(LA, 'lab', 'RigAnimator.js'), 'utf8');
ok('animator: the hold is solved AFTER the rate-filtered pose write (a post-write corrective), captures the pointed end in world space, and skips on stub bones (node) — the pendulum-frame hold is the explicit rollback branch', /plantPass\(v, Math\.min\(0\.5/.test(src) && /if \(PLANT_ON\(\)\) \{[^}]*rollback path/.test(src) && /plantReady\(\)/.test(src) && /applyMatrix4\(tp\.matrixWorld\)/.test(src) && /a\.w = 0; return; \}/.test(src));
ok('animator: the release blend is not contact (reported weight 0 from the release frame) and the engage ramp counts as contact only from weight ≥ 0.9 (the probe’s window)', /the reported hold weight is 0 from the release frame/.test(src) && /a\.w = wIn/.test(src));
/* the pendulum gait is untouched when the hold is off / in node: the FK owner-decision test (hover, no floor strike) still passes — checked by running the animator on stub bones */
var THREE = await import('file:///' + path.join(LA, 'vendor', 'three', 'three.module.min.js').replace(/\\/g, '/'));
var { createRigAnimator } = await import('file:///' + path.join(LA, 'lab', 'RigAnimator.js').replace(/\\/g, '/')); var AD = await import('file:///' + path.join(LA, 'lab', 'animData.js').replace(/\\/g, '/'));
var bones = {}; AD.BONES.forEach(function (k) { bones[k] = { name: k, position: { x: 0, y: -0.2, z: 0 }, quaternion: new THREE.Quaternion() }; });
var An = createRigAnimator(THREE, { bones: bones, seed: 0.3 }, { defaults: DEF, animData: AD, classId: 'ATHLETE', seed: 0.3, profile: null });
for (var i = 0; i < 120; i++) An.animate({ moving: true, speed01: 0.7, speed_mps: 3.5, form: 'SPLIT', yaw: 0 }, 1 / 60);
var gs = An.gaitState(); ok('read-out: gaitState().plant reports enabled / ready / tip_ext and both anchors (null on stub bones: the world-space hold needs a real hierarchy)', gs.plant && gs.plant.enabled === true && gs.plant.ready === false && gs.plant.L === null && gs.plant.R === null && gs.plant.tip_ext_local > 0.02 && gs.plant.tip_ext_local < 0.04, gs.plant);
/* the tracked page record */
var EV = path.join(HERE, '..', '25_HANDOFF', 'CONVERGENCE', 'motion_e', 'motion_e.json'); var r = null; try { r = JSON.parse(fs.readFileSync(EV, 'utf8')); } catch (e) { }
var w = r && r.walk_split_slides, ru = r && r.run_split_slides;
ok('page record: separated WALK — ≥ 4 declared contacts, pointed-end drift max ≤ 2 cm per contact (' + (w ? w.median_cm + ' median / ' + w.max_cm + ' max cm' : 'no record') + ')', !!w && (w.L.length + w.R.length) >= 4 && w.max_cm <= 2.0, w && { median: w.median_cm, max: w.max_cm, n: w.L.length + w.R.length });
ok('page record: separated RUN — ≥ 4 declared contacts, pointed-end drift max ≤ 2 cm per contact (' + (ru ? ru.median_cm + ' median / ' + ru.max_cm + ' max cm at ' + ru.speed_mps + ' m/s' : 'no record') + ')', !!ru && (ru.L.length + ru.R.length) >= 4 && ru.max_cm <= 2.0, ru && { median: ru.median_cm, max: ru.max_cm });
ok('page record: the PASS 5 measured point (TIP joint) is reported beside the declared point, and the rollback hold reproduces the PASS 5 class of drift (walk ≥ 35 cm, run ≥ 15 cm) — the old result is preserved, not erased', !!r && r.walk_split_joint_legacy && r.run_split_joint_legacy && r.rollback_hover_hold && r.rollback_hover_hold.walk.median_cm >= 35 && r.rollback_hover_hold.run.median_cm >= 15, r && { legacy_walk_joint: r.walk_split_joint_legacy, rollback: r.rollback_hover_hold });
ok('page record: the whole probe passed on this build (no bind frames, no spikes above the logged threshold, 20 s idle in both forms)', !!r && r.fail === 0 && r.pass >= 12, r && { pass: r.pass, fail: r.fail });
/* C2 review item 1 — the normal-speed appearance gate (deploy/probe_gait_sequence.mjs → motion_e/g37_sequence_record.json): the hold must not create knee flips, leg snapping, overextension or abrupt release elsewhere in idle → start → walk → turn → stop → run → brake → FUSE → SEPARATE */
var SQ = path.join(HERE, '..', '25_HANDOFF', 'CONVERGENCE', 'motion_e', 'g37_sequence_record.json'); var q = null; try { q = JSON.parse(fs.readFileSync(SQ, 'utf8')); } catch (e) { }
var qa = q && q.analysis; ok('sequence record: the separated sequence was traced at normal speed (≥ 300 split frames) and the leg length came from the LOCAL figure’s rig (hip → knee → pointed end; the scene holds ten class rigs with different knee heights)', !!q && q.frames > 300 && q.rig && q.rig.leg_m > 0.7 && q.rig.leg_m < 1.1 && q.rig.tip_ext_m > 0, q && { frames: q.frames, rig: q.rig });
ok('sequence record: no knee flip (min forward knee offset ≥ −1.5 cm), no overextension (max hip→end / leg ≤ 1.005), no leg snap above the logged threshold, no abrupt release (end speed after release ≤ 2.5 × body top speed), FUSE → SEPARATE with the hold inactive', !!qa && qa.L.knee_flips === 0 && qa.R.knee_flips === 0 && qa.L.overext_frames === 0 && qa.R.overext_frames === 0 && q.summary && q.summary.fail === 0 && q.summary.pass >= 7, qa && { knee_min_fwd_cm: [qa.L.knee_min_fwd_cm, qa.R.knee_min_fwd_cm], max_len_ratio: [qa.L.max_len_ratio, qa.R.max_len_ratio], threshold_rad_s: q.threshold_rad_s, summary: q.summary });
console.log('RESULT G37 contact: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
