/* MAHWORLD :: reusable character slot — manifest validation, visible fallback, disposal on switch (no DOM, no GPU, no assets).
   node 16_TESTS/gameplay_asset_slot.test.mjs */
import { validateManifest, createCharacterSlot, MANIFEST_SCHEMA } from '../26_LOCAL_AUTHORITY/lab/AssetSlot.js';
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + JSON.stringify(detail) : '')); } }
var good = { export_id: 'ATHLETE_M_GAME_TEST', version: 'GT_0.0.0-example', sha256: 'a'.repeat(64), owner_review_status: 'CANDIDATE', source_release: 'EXAMPLE (no real export exists)', units: 'metres', up_axis: '+Y', forward_axis: '-Z', root: 'ROOT', scale_to_metres: 1, forms: ['FUSED'], clips: { IDLE: 'idle', WALK: 'walk' }, sockets: { ROOT: 'root', HEAD: 'head' }, materials: { neutral_light: true }, files: ['athlete_m.glb'] };
var v = validateManifest(good); ok('a complete manifest validates and reports UNSUPPORTED forms / clips / sockets explicitly (never invents them)', v.ok && v.unsupported.forms.join() === 'SPLIT' && v.unsupported.clips.indexOf('DASH') >= 0 && v.unsupported.sockets.indexOf('CHEST') >= 0 && v.approved_final === false, v);
ok('missing required fields are listed', (function () { var m = Object.assign({}, good); delete m.sha256; delete m.owner_review_status; var r = validateManifest(m); return !r.ok && r.missing.join() === 'sha256,owner_review_status'; })());
ok('native sources and absolute / parent paths are refused as export files', !validateManifest(Object.assign({}, good, { files: ['model.blend'] })).ok && !validateManifest(Object.assign({}, good, { files: ['../x.glb'] })).ok && !validateManifest(Object.assign({}, good, { files: ['C:/x.glb'] })).ok);
ok('wrong axes / units / scale / hash / review status are problems', (function () { var r = validateManifest(Object.assign({}, good, { up_axis: '+Z', units: 'cm', scale_to_metres: 0, sha256: 'zz', owner_review_status: 'FINAL' })); return !r.ok && r.problems.length === 5; })());
var disposed = []; function fakeImpl(name) { return { mount: function () {}, update: function () {}, remove: function () {}, dispose: function () { disposed.push(name); } }; }
var slot = createCharacterSlot({ standIn: function () { return fakeImpl('STAND_IN'); } });
slot.register('ATHLETE_M_GAME_TEST', { manifest: good, create: async function () { return fakeImpl('ATHLETE_M_GAME_TEST'); } }).register('BROKEN', { manifest: good, create: async function () { throw new Error('GLB parse failed'); } }).register('BAD_MANIFEST', { manifest: { export_id: 'x' }, create: async function () { return fakeImpl('BAD'); } });
var c0 = await slot.select('STAND_IN'); ok('default selection is the stand-in with no fallback reason', c0.id === 'STAND_IN' && c0.fallback_reason === null);
var c1 = await slot.select('ATHLETE_M_GAME_TEST'); ok('a valid binding loads through the same slot, keeps version + review status in its label, and disposed the previous implementation', c1.id === 'ATHLETE_M_GAME_TEST' && /GT_0.0.0-example CANDIDATE/.test(c1.label_suffix) && disposed.join() === 'STAND_IN', { c1: c1.label_suffix, disposed: disposed });
var c2 = await slot.select('BROKEN'); ok('a loader failure falls back VISIBLY to the stand-in and disposed the previous asset', c2.id === 'STAND_IN' && /LOAD_FAILED GLB parse failed/.test(c2.fallback_reason) && /STAND-IN fallback/.test(c2.label_suffix) && disposed.slice(-1)[0] === 'ATHLETE_M_GAME_TEST', c2);
var c3 = await slot.select('BAD_MANIFEST'); ok('an invalid manifest never loads: visible MANIFEST_INVALID fallback', c3.id === 'STAND_IN' && /MANIFEST_INVALID missing/.test(c3.fallback_reason), c3);
var c4 = await slot.select('NOPE'); ok('an unknown binding falls back with UNKNOWN_BINDING', c4.id === 'STAND_IN' && /UNKNOWN_BINDING/.test(c4.fallback_reason));
ok('history records every switch; a candidate is never marked approved', slot.history().length === 5 && slot.history().every(function (h) { return h.approved !== true; }) && MANIFEST_SCHEMA.owner_review_status.indexOf('OWNER_APPROVED') >= 0);
slot.dispose(); ok('dispose releases the current implementation', disposed.slice(-1)[0] === 'STAND_IN' && slot.current() === null);
console.log('\n' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
