/* Astra M4 acceptance: preserve the M3 default, close the real mainland route graph, give all five sanctuaries a complete bounded gameplay contract,
   make the original civic façades truthful, and keep generated host geometry synchronized. No package or network. */
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { fileURLToPath } from 'node:url';
import { fixtureLayout, worldColliders } from '../26_LOCAL_AUTHORITY/lab/world/worldLayout.js';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost } from '../26_LOCAL_AUTHORITY/DuelHost.js'; import { makeEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';
var HERE = path.dirname(fileURLToPath(import.meta.url)), ROOT = path.join(HERE, '..'), LA = path.join(ROOT, '26_LOCAL_AUTHORITY');
var REG_PATH = path.join(LA, 'lab', 'assets', 'world', 'world_registry_v1.json'), RAW = fs.readFileSync(REG_PATH, 'utf8'), R = JSON.parse(RAW);
var COLL = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'world_v1_colliders.json'), 'utf8'));
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail === undefined ? '' : ' — ' + JSON.stringify(detail))); } }
var paths = new Map(R.paths.list.map(function (p) { return [p.id, p]; })), links = new Map((R.paths.links || []).map(function (l) { return [l.id, l]; }));

var m3 = R.quality_routes.list.filter(function (q) { return q.id === 'QR_MOONLIT_TITAN_CIRCUIT'; })[0], m4 = R.quality_routes.list.filter(function (q) { return q.id === R.quality_routes.review; })[0];
ok('1. M3 remains the unchanged default route while M4 is the separate NIGHT review circuit across all five sanctuary contracts', R.quality_routes.default === 'QR_MOONLIT_TITAN_CIRCUIT' && m3 && m3.path_ids.join('|') === 'CW_TOWER|RP_RANGE_LOOP|RP_FOREST_NE|RP_TITAN_WILDWAY|RP_RANGE_TO_PASS|RP_EAST_LINK|CW_MATCH' && m4 && m4.id === 'QR_FIVE_SANCTUARY_NIGHT_CIRCUIT' && m4.default_time === 'NIGHT' && m4.stages.filter(function (s) { return s.standard === 'SANCTUARY'; }).length === 5, { default: R.quality_routes.default, review: R.quality_routes.review });

function pointSeg(p, a, b) { var dx = b[0] - a[0], dz = b[1] - a[1], l2 = dx * dx + dz * dz || 1, t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dz) / l2)); return Math.hypot(p[0] - (a[0] + dx * t), p[1] - (a[1] + dz * t)); }
function near(A, B) { return A.pts.some(function (q) { return B.pts.slice(0, -1).some(function (a, i) { return pointSeg(q, a, B.pts[i + 1]) <= 3; }); }) || B.pts.some(function (q) { return A.pts.slice(0, -1).some(function (a, i) { return pointSeg(q, a, A.pts[i + 1]) <= 3; }); }); }
var adj = {}; R.paths.list.forEach(function (p) { adj[p.id] = new Set(); }); for (var i = 0; i < R.paths.list.length; i++) for (var j = i + 1; j < R.paths.list.length; j++) if (near(R.paths.list[i], R.paths.list[j])) { adj[R.paths.list[i].id].add(R.paths.list[j].id); adj[R.paths.list[j].id].add(R.paths.list[i].id); }
(R.paths.links || []).forEach(function (l) { if (adj[l.from_path] && adj[l.to_path]) { adj[l.from_path].add(l.to_path); adj[l.to_path].add(l.from_path); } }); var seen = new Set(), todo = [R.paths.list[0].id]; while (todo.length) { var id = todo.pop(); if (seen.has(id)) continue; seen.add(id); adj[id].forEach(function (n) { if (!seen.has(n)) todo.push(n); }); }
ok('2. the rendered mainland path hierarchy is one connected graph (surface joins within 3 m plus explicit physical bridge links)', seen.size === R.paths.list.length, R.paths.list.filter(function (p) { return !seen.has(p.id); }).map(function (p) { return p.id; }));

var generated = worldColliders(R, []), bridges = new Map(R.water.bridges.map(function (b) { return [b.id, b]; }));
ok('3. every graph bridge link names a real physical bridge whose collision-backed deck spans its two path landings', (R.paths.links || []).length === 3 && R.paths.links.every(function (l) { var b = bridges.get(l.physical); return b && l.kind === 'BRIDGE' && l.deck.x1 === b.x1 && l.deck.z1 === b.z1 && l.deck.x2 === b.x2 && l.deck.z2 === b.z2 && generated.some(function (s) { return s.id === b.id + '_DECK' && s.walkable && s.bridge; }); }), R.paths.links);

var regions = new Map(R.regions.list.map(function (x) { return [x.id, x]; })), waters = new Map(R.water.rivers.map(function (x) { return [x.id, x]; })), fish = new Map(R.ecology.species.FISH.habitat.bodies.map(function (x) { return [x.id, x]; })), packs = new Map(R.creatures.DOGKIE.pack_territories.map(function (x) { return [x.id, x]; })), zones = new Map(R.zones.map(function (x) { return [x.id, x]; })), resources = new Map(R.resource_patches.list.map(function (x) { return [x.id, x]; })), buildings = new Map(R.buildings.list.map(function (x) { return [x.id, x]; }));
var horses = R.ecology.species.HORSE.habitat.spots, phoenix = R.ecology.species.PHOENIX.habitat.anchors, terraces = new Set(R.terraces.list.map(function (x) { return x.id; })), beams = new Set((R.macro.sky_beams || []).map(function (x) { return x.id; }));
function exactSpot(list, q, sanctuary) { return list.some(function (x) { return x.x === q[0] && x.z === q[1] && (!sanctuary || String(x.sanctuary).indexOf(sanctuary.replace('_SANCTUARY', '')) >= 0); }); }
function contractValid(c) { var rg = regions.get(c.id); if (!rg || rg.class !== c.class || rg.family !== c.family || c.arrival_paths.length < 2 || !c.arrival_paths.every(function (id) { return paths.has(id); }) || !c.bridge_links.every(function (id) { return links.has(id); })) return false; if (!c.heart.length || !c.heart.every(function (id) { return buildings.has(id); }) || !c.water.length || !c.water.every(function (id) { return waters.has(id); }) || !c.fish_bodies.length || !c.fish_bodies.every(function (id) { return fish.has(id); })) return false; if (!c.dogkie_zones.length || !c.dogkie_zones.every(function (id) { var z = zones.get(id); return z && z.kind === 'FOREST' && z.habitat === 'DOGKIE'; }) || !c.dogkie_packs.length || !c.dogkie_packs.every(function (id) { var p = packs.get(id); return p && p.sanctuary === c.id; })) return false; if (c.horse_spots.length !== 2 || !c.horse_spots.every(function (q) { return exactSpot(horses, q, c.id); }) || !exactSpot(phoenix, c.phoenix_anchor, c.id)) return false; if (!c.resources.length || !c.resources.every(function (id) { return resources.has(id); }) || !c.vertical.length || !c.vertical.every(function (id) { return terraces.has(id) || buildings.has(id) || paths.has(id); })) return false; return c.night_landmarks.length > 0 && c.night_landmarks.every(function (id) { return beams.has(id) || buildings.has(id); }); }
var contracts = R.sanctuary_contracts && R.sanctuary_contracts.list || [];
ok('4. all five sanctuaries have valid arrival, heart, water/fish, Dogkie, two-horse, Phoenix, resources, verticality and night-identity references', contracts.length === 5 && contracts.every(contractValid), contracts.filter(function (c) { return !contractValid(c); }).map(function (c) { return c.id; }));

var seededBySanctuary = {}; R.creatures.DOGKIE.spawn_points.forEach(function (s) { seededBySanctuary[s.sanctuary] = (seededBySanctuary[s.sanctuary] || 0) + 1; });
ok('5. Dogkie coverage is a 54-record dormant pool, not 54 awake agents: global cap 24, per-sanctuary cap 12, every sanctuary seeded and Bage has its new 8-record garden population', R.creatures.DOGKIE.pool_size === 54 && R.creatures.DOGKIE.spawn_points.length === 54 && R.creatures.DOGKIE.max_active === 24 && R.creatures.DOGKIE.awake_cap_per_sanctuary === 12 && contracts.every(function (c) { return seededBySanctuary[c.id] > 0; }) && seededBySanctuary.BAGE_SANCTUARY === 8, seededBySanctuary);

var civicIds = ['BLD_TRAINING_HALL', 'BLD_ARENA_DOME', 'BLD_MENTOR_SPIRE', 'BLD_MAHGIC_EXCHANGE'], civicDoors = ['CIVIC_TRAINING_DOOR', 'CIVIC_ARENA_DOOR', 'CIVIC_MENTOR_DOOR', 'CIVIC_EXCHANGE_DOOR'];
ok('6. the four original plaza façades now have real ENTER doors and bounded shell rooms; the Exchange remains information-only with no economy schema', civicIds.every(function (id, n) { var b = buildings.get(id), d = R.interactables_added.filter(function (x) { return x.id === civicDoors[n]; })[0], room = b && R.rooms_added[b.interior]; return b && b.entrance.door === civicDoors[n] && d && d.kind === 'ENTER' && d.to.room === b.interior && room && room.interior && room.exit.to === 'FIELD' && !('shop' in b) && !('price' in b) && !('economy' in b); }) && buildings.get('BLD_MAHGIC_EXCHANGE').type === 'CIVIC_INFORMATION' && /no economy/.test(buildings.get('BLD_MAHGIC_EXCHANGE').note), civicIds.map(function (id) { return buildings.get(id); }));

var data = await loadHeadlessData(), cfg = data.cfg, DT = cfg.dev('local_authority.tick_dt_s'), host = createDuelHost({ data: data, composeHeadless: composeHeadless }); host.dev.createAccount('M4', { classId: 'ATHLETE', sex: 'M' }); var cc = host.connect({ client_id: 'm4', account_id: 'M4', token: host.dev.tokens().M4 }), seq = 0, send = function (a, p) { return host.submit(makeEnvelope({ session_id: cc.session_id, client_id: 'm4' }, ++seq, a, p || {})); }, snap = function () { return host.snapshot(cc.session_id).play; }, tick = function (s) { for (var q = 0; q < Math.round(s / DT); q++) host.tick(DT); };
send('ENTER_ROOM', { room: 'FIELD' }); tick(0.2); var entered = [];
for (i = 0; i < civicIds.length; i++) { var cb = buildings.get(civicIds[i]), cd = cb.entrance, cr = R.rooms_added[cb.interior]; host.dev.play('PLACE', { account_id: 'M4', x: cd.x, z: cd.z }); var en = send('ENTER_ROOM', { room: cb.interior }); tick(0.1); var inside = snap().room === cb.interior; host.dev.play('PLACE', { account_id: 'M4', x: cr.exit.position.x, z: cr.exit.position.z }); var ex = send('ENTER_ROOM', { room: 'FIELD' }); tick(0.1); entered.push(en.accepted && inside && ex.accepted && snap().room === 'FIELD'); }
ok('7. all four civic doors execute the authoritative FIELD → interior → FIELD transaction, not just registry labels', entered.every(Boolean), entered);

var fixtures = fixtureLayout(R), litPaths = R.paths.list.filter(function (p) { return p.lighting; });
ok('8. street fixtures follow every lighting-authorized real polyline and retain the plaza ring / physical bridge lights', litPaths.every(function (p) { return fixtures.some(function (f) { return f.route === p.id; }); }) && fixtures.filter(function (f) { return f.route === 'PLAZA_RING'; }).length === R.fixtures.plaza_ring_count && R.water.bridges.every(function (b) { return fixtures.filter(function (f) { return f.route === b.id; }).length === 4; }), { fixtures: fixtures.length, lit_paths: litPaths.length });

var menuSrc = fs.readFileSync(path.join(LA, 'lab', 'gameMenu.js'), 'utf8'), terrainSrc = fs.readFileSync(path.join(LA, 'lab', 'world', 'terrain.js'), 'utf8'), skySrc = fs.readFileSync(path.join(LA, 'lab', 'world', 'sky.js'), 'utf8');
var walls = R.field.walls, area = (walls.x2 - walls.x1) * (walls.z2 - walls.z1);
ok('9. the complete 121,975 m² mainland remains the real field; map bounds come from field.walls and region tint rendering uses one owner per field cell', area === 121975 && /WR\.field && WR\.field\.walls/.test(menuSrc) && /SINGLE_OWNER_FIELD_GRID/.test(terrainSrc) && /overlapping translucent region planes/.test(terrainSrc), { walls: walls, area_m2: area });

var cloud = R.sky.layers.filter(function (l) { return l.kind === 'CLOUD'; });
ok('10. the layered sky uses gray-blue low/mid cloud bodies with depth-writing occlusion while high cirrus remains a non-occluding veil', cloud.filter(function (l) { return l.occludes; }).length === 2 && cloud.some(function (l) { return l.id === 'CIRRUS_HIGH' && !l.occludes; }) && cloud.every(function (l) { return !/^#f{6}$/i.test(l.color); }) && /depthWrite: !!L\.occludes/.test(skySrc) && /alphaTest: L\.occludes/.test(skySrc), cloud);

var fall = R.macro.waterfalls.filter(function (w) { return w.id === 'NORTH_FALL'; })[0];
ok('11. the beyond-wall north waterfall is explicitly scenic-only and cannot masquerade as a reachable interaction', fall && fall.scenic_only && fall.reachable === false && fall.interaction === false, fall);

var sha = crypto.createHash('sha256').update(RAW).digest('hex');
ok('12. generated world collider authority is synchronized to this exact M4 registry', COLL.registry_sha256 === sha && COLL.shapes.length === generated.length && JSON.stringify(COLL.shapes) === JSON.stringify(generated), { expected: sha, actual: COLL.registry_sha256, shapes: [COLL.shapes.length, generated.length] });

console.log('RESULT M4 world expansion: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
