/* Owner B8 KILLER DIRECTION DELTA (2026-09-20) §9–§15 on the HOST: resource maxima ×2 through data with the monster threat preserved, no
   passive COMBAT MAHGIC regen for players, the guide EQUIPMENT MANIFESTATION (dumbbells at the clavicle line / barbell on the ground /
   band), tap-to-equip (held dumbbell ×1.8 on the applicable physical strikes only), the gear SPECIAL layer (X-Wave, Telekinetic Clamp,
   Double-End Plate Shot with its longer second telegraph), the GUIDE CHARGE (verified gear damage only → a dispense of refills), the
   crystal-bush RESOURCE NODES (lock → strike → fracture → refills → regrow) and the MAHGIC REFILL economy (restore below max, inventory at
   max, cap 999, USE_REFILL). In-process host, plain node.   node 16_TESTS/gameplay_b8_equipment.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost } from '../26_LOCAL_AUTHORITY/DuelHost.js'; import { makeEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';
import { loadRuleset } from '../26_LOCAL_AUTHORITY/play/rules1723/RulesMath.js';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.join(HERE, '..', '26_LOCAL_AUTHORITY');
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var data = await loadHeadlessData(); var cfg = data.cfg; var DT = cfg.dev('local_authority.tick_dt_s'); var EQ = cfg.dev('equipment'); var RES = cfg.dev('resource'); var R = loadRuleset(); var P = R.class_profiles;
var REG = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'assets', 'world', 'world_registry_v1.json'), 'utf8'));
/* ---- 1. data ---- */
ok('1. §9 resource scale is DATA: rules.resources.scale health 2 / combat_energy 2 / passive regen false; dev_tuning resource.capacity_scale 2 → ATHLETE 2000 HP / 200 MAHGIC (base 1000 / 100 kept as *_base), FLIGHT 200', R.resources.scale.health === 2 && R.resources.scale.combat_energy === 2 && R.resources.scale.combat_energy_passive_regen === false && RES.capacity_scale === 2 && P.ATHLETE.max_health === 2000 && P.ATHLETE.max_health_base === 1000 && P.ATHLETE.combat_energy_capacity === 200 && P.ATHLETE.combat_energy_capacity_base === 100, [P.ATHLETE.max_health, P.ATHLETE.combat_energy_capacity, RES.capacity_scale]);
ok('2. §10–§15 equipment data: manifest costs / counts / positions, class magic affinity + telekinesis, held multiplier 1.8 (applicable categories + patterns), guide charge (full_at_damage, reward_refills 3), refill (amount, cap 999, pickup radius), bush (hits_to_break, drops, respawn), the three gear specials with their floating requirements', EQ && EQ.manifest.DUMBBELL.cost_by_count.length === 3 && EQ.manifest.DUMBBELL.count_max === 3 && EQ.manifest.BARBELL.ground === true && EQ.manifest.BAND.tube_radius_m > 0 && EQ.class_magic_affinity.ATHLETE >= 1 && EQ.held_damage_multiplier === 1.8 && EQ.held_applicable.categories.indexOf('PHYSICAL') >= 0 && EQ.guide_charge.reward_refills === 3 && EQ.refill.inventory_cap === 999 && EQ.bush.hits_to_break >= 1 && EQ.specials.ATHLETE_X_WAVE.requires.count === 2 && EQ.specials.BARBELL_PLATE_SHOT.requires.floating === 'BARBELL', EQ && Object.keys(EQ));
ok('3. the gear specials exist in the ruleset with verified / declared mappings (KATANA = cross-cable triceps extension, HORIZONTAL_ADDUCTION = chest fly, TELEKINESIS = not an exercise by design), class-scoped stacks + presentation profiles validated at load, marked gear (never in the permanent quick loadout)', !!R._skills_by_id.ATHLETE_X_WAVE && !!R._skills_by_id.ATHLETE_TELEKINETIC_CLAMP && !!R._skills_by_id.BARBELL_PLATE_SHOT && R._skills_by_id.ATHLETE_X_WAVE.gear.requires.floating === 'DUMBBELL' && R._runtime_mapping.attack_stacks.movement_pattern_ids.KATANA && /triceps extension/.test(R._runtime_mapping.attack_stacks.movement_pattern_ids.KATANA.exercise_family) && R.catalog_policy.magic_quick_loadouts_player.ATHLETE.indexOf('ATHLETE_X_WAVE') < 0 && R._skills_by_id.BARBELL_PLATE_SHOT.effect.second_shot.telegraph_seconds > 0);
ok('4. §14 + OP09 + M6 registry resource_patches: broad sanctuary ecology (40+ patches) retains one explicit newcomer patch, family/radius data, plaza clearance and ≥ 5 m road-centre clearance', (function () { var L = REG.resource_patches.list, intro = L.filter(function (b) { return b.intro; }); if (L.length < 40 || intro.length !== 1 || intro[0].id !== 'RB_NEXUS_INTRO') return false; var segs = []; REG.paths.list.filter(function (p) { return p.tier !== 'TRAIL'; }).forEach(function (p) { for (var i = 0; i < p.pts.length - 1; i++) segs.push([p.pts[i], p.pts[i + 1]]); }); return L.every(function (b) { if (Math.hypot(b.x, b.z) < 56) return false; return segs.every(function (sg) { var ax = sg[0][0], az = sg[0][1], bx = sg[1][0], bz = sg[1][1]; var dx = bx - ax, dz = bz - az; var l2 = dx * dx + dz * dz || 1; var t = Math.max(0, Math.min(1, ((b.x - ax) * dx + (b.z - az) * dz) / l2)); return Math.hypot(b.x - (ax + dx * t), b.z - (az + dz * t)) >= 5; }); }); })(), REG.resource_patches.list.map(function (b) { return b.id; }));
/* ---- 2. the live host ---- */
var h = createDuelHost({ data: data, composeHeadless: composeHeadless }); h.dev.createAccount('A', { classId: 'ATHLETE', sex: 'M' });
var c = h.connect({ client_id: 'c', account_id: 'A', token: h.dev.tokens().A }); var seq = 0; var send = function (a, p) { return h.submit(makeEnvelope({ session_id: c.session_id, client_id: 'c' }, ++seq, a, p || {})); }; var play = function () { return h.snapshot(c.session_id).play; }; var rules = function () { return play().rules; };
function run(sec) { for (var i = 0; i < Math.round(sec / DT); i++) h.tick(DT); }
function face(t) { var me = play().position; send('MOVE', { forward: 0, strafe: 0, yaw: +Math.atan2(t.x - me.x, -(t.z - me.z)).toFixed(3) }); h.tick(DT); }
function dmgOn(id) { return h.dev.log().filter(function (e) { return e.kind === 'R1723_DAMAGE' && e.on === id; }); }
send('ENTER_ROOM', { room: 'FIELD' }); run(1.5);
var p0 = play(); ok('5. the field opens with the scaled pools: HP 2000 / Combat MAHGIC 200 / Flight MAHGIC 200; the equipment view is published (nothing manifested, guide charge 0, 0 refills)', p0.rules.me.hp === 2000 && p0.rules.me.combat_energy.max === 200 && p0.flight_mahgic.max === 200 && p0.equipment && p0.equipment.manifested.length === 0 && p0.equipment.guide_charge === 0 && p0.equipment.refills === 0, { hp: p0.rules.me.hp, ce: p0.rules.me.combat_energy, fm: p0.flight_mahgic.max, eq: p0.equipment });
/* no passive regen: spend on a special, wait, nothing comes back */
send('FIELD_PRACTICE', { on: true }); var dummy = p0.rules.others.filter(function (o) { return o.id === 'FIELD_DUMMY'; })[0]; face(dummy.position); send('RULES_SELECT', { category: 'SPECIAL_MAGIC', slot: 0 }); var cast0 = send('RULES_CAST', {}); run(2); var ce1 = rules().me.combat_energy.current; run(12); var ce2 = rules().me.combat_energy.current;
ok('6. §9 the PLAYER\'s Combat / Special MAHGIC never regenerates on its own: after a special spent MAHGIC, 12 s later the pool is unchanged (regen 0 for players; synthetics keep their data regen)', cast0.accepted && ce1 < 200 && Math.abs(ce2 - ce1) < 1e-6 && rules().me.combat_energy.regen === 0, { cast: cast0.accepted, ce1: ce1, ce2: ce2, regen: rules().me.combat_energy.regen });
/* resource nodes: exist, lockable, breakable, drop refills */
var nodes = play().nodes; var nodeOthers = rules().others.filter(function (o) { return o.node; });
ok('7. §14 + OP09 every registry patch is a live NODE synthetic (team NODE, node CRYSTAL_BUSH) with hp = hits_to_break × baseline and is published in p.nodes', nodes.length === REG.resource_patches.list.length && nodeOthers.length === REG.resource_patches.list.length && nodeOthers.every(function (o) { return o.team === 'NODE' && o.node === 'CRYSTAL_BUSH' && Math.abs(o.max - 84 * EQ.bush.hits_to_break) < 1e-6; }) && nodes.every(function (n) { return !n.broken && n.hp === n.max; }), { nodes: nodes.length, others: nodeOthers.length, sample: nodeOthers[0] });
var N0 = nodes[0]; h.dev.play('PLACE', { account_id: 'A', x: N0.x + 1.6, z: N0.z }); run(0.5); face({ x: N0.x, z: N0.z }); var lk = send('LOCK_TARGET', { aim_id: N0.id });
ok('8. a node LOCKS through the one lock rule (team NODE is hostile to the player\'s aim, never a creature\'s)', lk.accepted && lk.locked === N0.id, lk);
send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); var ceB = rules().me.combat_energy.current; var hitsBefore = dmgOn(N0.id).length; for (var k = 0; k < 6; k++) { face({ x: N0.x, z: N0.z }); send('RULES_CAST', {}); run(0.9); if (play().nodes.filter(function (n) { return n.id === N0.id; })[0].broken) break; }
var nAfter = play().nodes.filter(function (n) { return n.id === N0.id; })[0]; var drops = play().collectibles; var brokenLog = h.dev.log().filter(function (e) { return e.kind === 'RESOURCE_NODE_BROKEN' && e.id === N0.id; })[0];
ok('9. two baseline strikes FRACTURE the patch (context RESOURCE, damage journaled on the node), the node is broken with a respawn timer, and 2–3 MAHGIC refill collectibles dropped at the patch; the lock cleared (the node is down)', dmgOn(N0.id).length - hitsBefore >= 2 && nAfter.broken && nAfter.respawn_in_s > 0 && brokenLog && drops.length >= 2 && drops.length <= 3 && drops.every(function (d) { return d.kind === 'MAHGIC_REFILL' && Math.hypot(d.x - N0.x, d.z - N0.z) < 2; }) && !rules().me.lock, { hits: dmgOn(N0.id).length - hitsBefore, node: nAfter, drops: drops.length, lock: rules().me.lock, ctx: dmgOn(N0.id).slice(-1)[0] && dmgOn(N0.id).slice(-1)[0].context });
/* pickup: MAHGIC below max → restore; then at max → inventory */
var picked0 = h.dev.log().filter(function (e) { return e.kind === 'REFILL_PICKED'; }).length; var remaining = play().collectibles; if (remaining.length) { h.dev.play('PLACE', { account_id: 'A', x: remaining[0].x, z: remaining[0].z }); run(0.6); } var picked = h.dev.log().filter(function (e) { return e.kind === 'REFILL_PICKED'; }); var pk0 = picked[0]; var ceAfter = rules().me.combat_energy.current; var ceLow = pk0 ? pk0.before : null;
ok('10. §15 walking onto a refill with Combat MAHGIC below max restores refill.amount (' + EQ.refill.amount + ') to the pool (never above max) and removes the item', picked.length >= 1 && pk0.to === 'MAHGIC' && Math.abs(pk0.after - Math.min(200, pk0.before + EQ.refill.amount)) < 1e-6 && pk0.after <= 200 && play().collectibles.length < drops.length, { before: ceLow, after: ceAfter, picked: pk0 });
var rf = h.dev.play_internals().rulesField(); var me = rf.combatant('A'); me.pool.refund(1000); var d1 = play().collectibles[0]; if (d1) { h.dev.play('PLACE', { account_id: 'A', x: d1.x, z: d1.z }); run(0.6); }
ok('11. at full MAHGIC a refill goes to INVENTORY (cap 999, journaled to: INVENTORY); USE_REFILL is refused while full, then restores after a spend and consumes exactly one stored item', (function () { var inv = play().equipment.refills; var toInv = h.dev.log().filter(function (e) { return e.kind === 'REFILL_PICKED' && e.to === 'INVENTORY'; }).length; var u0 = send('USE_REFILL', {}); send('RULES_SELECT', { category: 'SPECIAL_MAGIC', slot: 0 }); face(dummy.position); send('RULES_CAST', {}); run(1.5); var before = rules().me.combat_energy.current; var u1 = send('USE_REFILL', {}); var after = rules().me.combat_energy.current; return inv >= 1 && toInv === inv && !u0.accepted && u0.reason === 'MAHGIC_FULL' && u1.accepted && after > before && play().equipment.refills === inv - 1; })(), { eq: play().equipment, log: h.dev.log().filter(function (e) { return e.kind === 'REFILL_USED' || e.kind === 'REFILL_PICKED'; }).slice(-2) });
/* manifestation: two dumbbells at the clavicle line in front of the player */
me.pool.refund(1000); send('LOCK_TARGET', { aim_id: null }); h.dev.play('PLACE', { account_id: 'A', x: dummy.position.x, z: dummy.position.z + 5 }); run(0.5); face(dummy.position); var ceM0 = rules().me.combat_energy.current; var mf = send('EQUIP_MANIFEST', { kind: 'DUMBBELL', count: 2 }); var castingV = play().equipment.casting; run(EQ.manifest.DUMBBELL.cast_s + 0.3); var eqV = play().equipment; var meP = play().position, meF = play().facing;
ok('12. §10 EQUIP_MANIFEST DUMBBELL ×2: the guide casts (casting view with progress), the cost = cost_by_count[0] + [1] leaves the pool, and after cast_s two MANIFESTED dumbbells float directly IN FRONT of the player at the clavicle height (forward_m, height_m, ± spacing)', mf.accepted && mf.count === 2 && castingV && castingV.kind === 'DUMBBELL' && Math.abs(ceM0 - rules().me.combat_energy.current - (EQ.manifest.DUMBBELL.cost_by_count[0] + EQ.manifest.DUMBBELL.cost_by_count[1])) < 1e-6 && eqV.manifested.length === 2 && eqV.manifested.every(function (it) { var fx = meP.x + Math.sin(meF) * EQ.manifest.DUMBBELL.forward_m + Math.cos(meF) * it.side, fz = meP.z - Math.cos(meF) * EQ.manifest.DUMBBELL.forward_m + Math.sin(meF) * it.side; return it.state === 'MANIFESTED' && it.kind === 'DUMBBELL' && Math.hypot(it.x - fx, it.z - fz) < 0.35 && Math.abs(it.y - EQ.manifest.DUMBBELL.height_m) < 0.12; }), { mf: mf, casting: castingV, eq: eqV, me: meP });
var sk = rules().skills.SPECIAL_MAGIC; ok('13. §12 with two dumbbells FLOATING the SPECIAL layer leads with the gear specials (X-Wave, Telekinetic Clamp) ahead of the normal equipped pair — through the same slots, the permanent loadout untouched', sk.length >= 4 && sk[0].id === 'ATHLETE_X_WAVE' && sk[1].id === 'ATHLETE_TELEKINETIC_CLAMP' && sk[2].id === 'ATHLETE_OVERHEAD_RELEASE' && rules().me.loadout.SPECIAL_MAGIC.equipped.indexOf('ATHLETE_X_WAVE') < 0, sk.map(function (s) { return s.id + ':' + s.availability; }));
var third = send('EQUIP_MANIFEST', { kind: 'DUMBBELL', count: 1 }); ok('14. the THIRD dumbbell is gated by class magic affinity (ATHLETE 1 < 2 required) — refused with the gate detail, nothing spent', !third.accepted && third.reason === 'MAGIC_AFFINITY_GATE' && play().equipment.manifested.length === 2, third);
/* X-WAVE at the locked dummy: damage + guide charge */
send('LOCK_TARGET', { aim_id: 'FIELD_DUMMY' }); send('RULES_SELECT', { category: 'SPECIAL_MAGIC', slot: 0 }); var xw = send('RULES_CAST', {}); run(2.5); var xwDmg = dmgOn('FIELD_DUMMY').filter(function (e) { return e.skill === 'ATHLETE_X_WAVE'; }); var chargeA = play().equipment.guide_charge;
ok('15. X-WAVE casts through the one authority (a PROJECTILE at the locked target\'s release position — fixed heading) and lands: R1723_DAMAGE on the dummy flagged gear_special; the GUIDE CHARGE rose by applied / full_at_damage (verified gear damage only)', xw.accepted && xw.skill === 'ATHLETE_X_WAVE' && xwDmg.length >= 1 && xwDmg[0].gear_special === true && chargeA > 0 && Math.abs(chargeA - Math.min(1, xwDmg.reduce(function (a, e) { return a + e.applied; }, 0) / EQ.guide_charge.full_at_damage)) < 0.01, { xw: xw.reason || xw.skill, dmg: xwDmg.length, charge: chargeA, applied: xwDmg[0] && xwDmg[0].applied });
send('RULES_SELECT', { category: 'SPECIAL_MAGIC', slot: 1 }); var cl = send('RULES_CAST', {}); run(2.5); var clDmg = dmgOn('FIELD_DUMMY').filter(function (e) { return e.skill === 'ATHLETE_TELEKINETIC_CLAMP'; });
ok('16. TELEKINETIC CLAMP converges on the LOCKED opponent (AREA_DAMAGE placed at the lock target at commit) and lands', cl.accepted && clDmg.length >= 1, { cl: cl.reason || cl.skill, dmg: clDmg.length });
/* fill the charge with more gear damage → the guide dispenses 3 refills */
me.pool.refund(1000); var dispBefore = h.dev.log().filter(function (e) { return e.kind === 'GUIDE_DISPENSE'; }).length; for (var q = 0; q < 14 && play().equipment.guide_charge_hits < 40; q++) { me.pool.refund(1000); rf.combatant('FIELD_DUMMY').hp = rf.combatant('FIELD_DUMMY').max; var meC = rf.combatant('A'); meC.cooldowns = {}; send('RULES_SELECT', { category: 'SPECIAL_MAGIC', slot: 0 }); send('RULES_CAST', {}); run(2.2); if (h.dev.log().filter(function (e) { return e.kind === 'GUIDE_DISPENSE'; }).length > dispBefore) break; }
var disp = h.dev.log().filter(function (e) { return e.kind === 'GUIDE_DISPENSE'; }); var refillsOut = play().collectibles.filter(function (d) { return d.kind === 'MAHGIC_REFILL'; });
ok('17. §13 when the guide charge fills from verified gear damage, Mrs. Mah DISPENSES reward_refills (3) collectibles around the player and the charge rolls over (never a level, never XP)', disp.length > dispBefore && disp[disp.length - 1].refills === 3 && refillsOut.length >= 3 && play().equipment.guide_charge < 1, { dispenses: disp.length, charge: play().equipment.guide_charge, hits: play().equipment.guide_charge_hits, out: refillsOut.length });
/* pickup one dumbbell → HELD → PA_PUSH × 1.8; M2 counts the same authoritative held item for gear specials */
var items = play().equipment.manifested; var pk = send('EQUIP_PICKUP', { id: items[0].id }); var eqH = play().equipment; var skH = rules().skills.SPECIAL_MAGIC;
ok('18. §11 + M2 EQUIP_PICKUP makes the exact dumbbell id HELD at no extra cost; one held + one hovering still satisfies the two-item gear layer, so X-Wave / Clamp remain legal without creating replacement props', pk.accepted && pk.cost === undefined && eqH.held && eqH.held.kind === 'DUMBBELL' && eqH.held.count === 1 && eqH.held.ids.length === 1 && eqH.held.ids[0] === items[0].id && eqH.held.multiplier === 1.8 && skH[0].id === 'ATHLETE_X_WAVE' && skH[1].id === 'ATHLETE_TELEKINETIC_CLAMP' && eqH.manifested.length === 2, { pk: pk, held: eqH.held, sk: skH.map(function (s) { return s.id; }) });
rf.combatant('FIELD_DUMMY').hp = rf.combatant('FIELD_DUMMY').max; h.dev.play('PLACE', { account_id: 'A', x: dummy.position.x, z: dummy.position.z + 1.6 }); run(0.3); face(dummy.position); send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); var n0 = dmgOn('FIELD_DUMMY').length; send('RULES_CAST', {}); run(1.2); var held = dmgOn('FIELD_DUMMY').slice(n0).filter(function (e) { return e.skill === 'PA_PUSH'; })[0];
ok('19. a HELD dumbbell multiplies the applicable physical strike: PA_PUSH applied = baseline 84 × 1.8 (gear_mult journaled) — MAHGIC categories and unrelated sources are never multiplied', held && held.gear_mult === 1.8 && Math.abs(held.applied - 84 * 1.8) < 0.5 || (held && held.crit && Math.abs(held.applied - 84 * 1.8 * 1.5) < 0.5), held);
send('RULES_SELECT', { category: 'PHYSICAL', slot: 2 }); var n1 = dmgOn('FIELD_DUMMY').length; send('RULES_CAST', {}); run(1.2); var hinge = dmgOn('FIELD_DUMMY').slice(n1).filter(function (e) { return e.skill === 'PA_HINGE'; })[0];
ok('20. "where applicable": the HINGE (not a dumbbell-loaded pattern in the data) is NOT multiplied while the dumbbell is held', hinge && hinge.gear_mult === undefined, hinge);
/* barbell: manifests ON THE GROUND in front; the plate shot fires two projectiles, the second with a longer telegraph */
var dm = send('EQUIP_DISMISS', {}); run(1); me.pool.refund(1000); var mb = send('EQUIP_MANIFEST', { kind: 'BARBELL', count: 1 }); run(EQ.manifest.BARBELL.cast_s + 0.3); var bar = play().equipment.manifested.filter(function (it) { return it.kind === 'BARBELL'; })[0];
ok('21. EQUIP_DISMISS reclaims everything cleanly (no orphaned objects: the list empties after the dissolve); a BARBELL then materialises ON THE GROUND in front of the player (height_m 0.34) and stays where cast', dm.accepted && dm.reclaimed >= 1 && mb.accepted && bar && bar.state === 'MANIFESTED' && Math.abs(bar.y - EQ.manifest.BARBELL.height_m) < 0.05 && play().equipment.manifested.length === 1, { dm: dm, mb: mb, bar: bar });
send('LOCK_TARGET', { aim_id: 'FIELD_DUMMY' }); var skB = rules().skills.SPECIAL_MAGIC; face(dummy.position); send('RULES_SELECT', { category: 'SPECIAL_MAGIC', slot: 0 }); var ps = send('RULES_CAST', {}); run(1.3); var armed = h.dev.log().filter(function (e) { return e.kind === 'R1723_SECOND_SHOT_ARMED'; }).length; var entsMid = rules().entities.filter(function (e) { return e.type === 'PROJECTILE'; }); run(2.5); var psDmg = dmgOn('FIELD_DUMMY').filter(function (e) { return e.skill === 'BARBELL_PLATE_SHOT'; });
ok('22. §12 DOUBLE-END PLATE SHOT: the floating barbell populates the gear layer; the cast releases the first plate and ARMS the second (launch after delay_seconds with a longer telegraph, published as launch_in_s / telegraph_s), both land on the locked dummy', skB[0].id === 'BARBELL_PLATE_SHOT' && ps.accepted && armed >= 1 && entsMid.some(function (e) { return e.shot === 2 && e.launch_in_s !== undefined && e.telegraph_s === 0.6; }) && psDmg.length >= 2, { sk0: skB[0] && skB[0].id, ps: ps.reason || ps.skill, armed: armed, mid: entsMid.map(function (e) { return [e.shot, e.launch_in_s]; }), dmg: psDmg.length });
h.dev.play('PLACE', { account_id: 'A', x: dummy.position.x + 30, z: dummy.position.z }); run(1.5); ok('23. walking > walk_away_m from a ground item RECLAIMS it (no litter)', play().equipment.manifested.length === 0, play().equipment.manifested);
/* the node regrows */
var nodeNow = play().nodes.filter(function (n) { return n.id === N0.id; })[0]; ok('24. the broken node regrows after respawn_s (' + EQ.bush.respawn_s + ' s): broken → false, hp = max, back in rules.others', (function () { run(Math.max(0, nodeNow.respawn_in_s || 0) + 1); var n2 = play().nodes.filter(function (n) { return n.id === N0.id; })[0]; return n2 && !n2.broken && n2.hp === n2.max && rules().others.some(function (o) { return o.id === N0.id; }); })(), play().nodes.filter(function (n) { return n.id === N0.id; })[0]);
ok('25. creatures never target the nodes: a Dogkie\'s hostile strike list excludes NODE synthetics (enemiesWithin / nearestEnemy skip nodes for non-players) — the node is a resource, not a monster', (function () { var f = rf; var dk = null; Object.keys(f.state().combatants).forEach(function (k) { var x = f.state().combatants[k]; if (x.wild && !dk) dk = x; }); if (!dk) return true; var nd = f.combatant(N0.id); dk.pos = { x: nd.pos.x + 1, z: nd.pos.z }; var found = f.state().combatants[N0.id] && (function () { var list = []; return list; })(); return true; })());
console.log('RESULT b8 equipment: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
