/* Owner B7 PHONE REVIEW DELTA (2026-09-20) §2 / §3 / §4 on the HOST + the M2 Phoenix override: monster targeting works for every species through the ONE
   combat system (the lock rule sees over the terrain when both bodies are airborne; the fish winds up INSIDE melee reach; the phoenix
   stays airborne through its dive / pass and a flying player can answer it), the species LEVEL is size-driven data (5..75, step 5,
   registry ecology.levels, level_override slot) published by the host views and the rules view, and the shared entity status reads it.
   In-process host, plain node.   node 16_TESTS/gameplay_b7_targeting.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost } from '../26_LOCAL_AUTHORITY/DuelHost.js'; import { makeEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';
import { speciesCombat } from '../26_LOCAL_AUTHORITY/play/world/CreatureCombat.js';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.join(HERE, '..', '26_LOCAL_AUTHORITY');
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var data = await loadHeadlessData(); var cfg = data.cfg; var DT = cfg.dev('local_authority.tick_dt_s');
var REG = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'assets', 'world', 'world_registry_v1.json'), 'utf8')); var ECO = REG.ecology.species; var LV = REG.ecology.levels;
/* ---- 1. the data (§4): size-driven levels ---- */
var SPECIES = ['DOGKIE', 'FISH', 'HORSE', 'PHOENIX'];
ok('1. ecology.levels: band [5, 75] step 5, min / max size over the spawnable species, one computed row per species, the rule documented', !!LV && LV.band.min === 5 && LV.band.max === 75 && LV.band.step === 5 && LV.min_size_m > 0 && LV.max_size_m > LV.min_size_m && LV.computed.length === 4 && /roundTo5\(5 \+ normalizedSize \* 70\)/.test(LV._doc), LV && { band: LV.band, min: LV.min_size_m, max: LV.max_size_m });
ok('2. every species carries size_m (its world-space bounding size after the species scale rule), bounds_world_m, level_computed, level_override (null = computed) and level = roundTo5(5 + n × 70) within [5, 75]', SPECIES.every(function (k) { var s = ECO[k]; if (!(s.size_m > 0 && s.bounds_world_m && Number.isFinite(s.level_computed) && s.level_override === null && s.level === s.level_computed)) return false; var n = (s.size_m - LV.min_size_m) / (LV.max_size_m - LV.min_size_m); var want = Math.max(5, Math.min(75, Math.round((5 + n * 70) / 5) * 5)); return s.level === want && s.level % 5 === 0; }), SPECIES.map(function (k) { return [k, ECO[k].size_m, ECO[k].level]; }));
ok('3. the smallest spawnable monster (DOGKIE 1.4 m) is LV 5 and the largest (PHOENIX wingspan ≈ 3.7 m) is LV 75; the horse (2.3 m) and the fish (2.4 m) sit in the middle band — LEVEL ≠ aggression (the horse stays passive, the fish stays the glass cannon)', ECO.DOGKIE.level === 5 && ECO.PHOENIX.level === 75 && ECO.HORSE.level >= 25 && ECO.HORSE.level <= 45 && ECO.FISH.level >= 25 && ECO.FISH.level <= 45 && ECO.HORSE.combat.aggression === 'DEFENSIVE' && ECO.FISH.combat.hits_to_kill_player <= 5, SPECIES.map(function (k) { return [k, ECO[k].level, ECO[k].combat.aggression]; }));
ok('4. the size rule matches the client scale rule: DOGKIE / HORSE height_m along the model y, FISH / PHOENIX length_m along the model z (wildlife.js loadSpecies) — the bounds are the derivative L0 bounds × that scale', /height_m 1.4/.test(ECO.DOGKIE.size_rule_note) && /length_m 2.4 \/ model z/.test(ECO.FISH.size_rule_note) && /height_m 1.75/.test(ECO.HORSE.size_rule_note) && /length_m 3.4 \/ model z/.test(ECO.PHOENIX.size_rule_note) && Math.abs(ECO.FISH.bounds_world_m.z - 2.4) < 0.01 && Math.abs(ECO.HORSE.bounds_world_m.y - 1.75) < 0.01, SPECIES.map(function (k) { return [k, ECO[k].size_rule_note, ECO[k].bounds_world_m]; }));
ok('5. speciesCombat() carries the level into the wild block (display / progression data, never a damage input): the combat table (hits_to_kill / hits_to_kill_player) is untouched', SPECIES.every(function (k) { var c = speciesCombat(REG, k); return c.level === ECO[k].level && c.hits_to_kill === ECO[k].combat.hits_to_kill; }));
ok('6. §2 + M2 data: the fish swirl orbit sits inside baseline melee reach; the Phoenix declares a 10 m terrain-relative clearance and its attack note explicitly replaces the old ground-height sweep with a clearance-clamped AERIAL PASS', ECO.FISH.combat.swirl_radius_m > 0 && ECO.FISH.combat.swirl_radius_m < 2.5 && ECO.PHOENIX.habitat.min_terrain_clearance_m >= 10 && /clearance-clamped.*AERIAL PASS/i.test(ECO.PHOENIX.combat.attack_motion || ''), { fish: ECO.FISH.combat.swirl_radius_m, phoenix_clearance: ECO.PHOENIX.habitat.min_terrain_clearance_m, motion: ECO.PHOENIX.combat.attack_motion });
/* ---- 2. the live host ---- */
var h = createDuelHost({ data: data, composeHeadless: composeHeadless }); h.dev.createAccount('A', { classId: 'ATHLETE', sex: 'M' });
var c = h.connect({ client_id: 'c', account_id: 'A', token: h.dev.tokens().A }); var seq = 0; var send = function (a, p) { return h.submit(makeEnvelope({ session_id: c.session_id, client_id: 'c' }, ++seq, a, p || {})); }; var play = function () { return h.snapshot(c.session_id).play; };
function run(sec) { for (var i = 0; i < Math.round(sec / DT); i++) h.tick(DT); }
function nearest(list, species) { var me = play().position; return (list || []).filter(function (x) { return !species || x.species === species; }).slice().sort(function (a, b) { return Math.hypot(a.position.x - me.x, a.position.z - me.z) - Math.hypot(b.position.x - me.x, b.position.z - me.z); })[0] || null; }
function face(t) { var me = play().position; send('MOVE', { forward: 0, strafe: 0, yaw: +Math.atan2(t.position.x - me.x, -(t.position.z - me.z)).toFixed(3) }); h.tick(DT); }
send('ENTER_ROOM', { room: 'FIELD' }); run(1); h.dev.play('PLACE', { account_id: 'A', x: -70, z: 0 }); run(3);
/* §4 on the host: every published creature / wildlife record carries the species level; the rules view of a wild combatant reports it */
var p0 = play(); var cr = p0.creatures || [], wl = p0.wildlife || [];
ok('7. host views: p.creatures[*].level = 5 (DOGKIE) with name, p.wildlife[*].level = the species level with name (FISH 35 / HORSE 35 / PHOENIX 75)', cr.length > 0 && cr.every(function (x) { return x.level === ECO.DOGKIE.level && x.name === 'DOGKIE'; }) && wl.length > 0 && wl.every(function (x) { return x.level === ECO[x.species].level && x.name === x.species; }), { creatures: cr.length, wildlife: wl.length, sample: wl.slice(0, 3).map(function (x) { return [x.species, x.level]; }) });
var others = (p0.rules && p0.rules.others) || []; var wildOthers = others.filter(function (o) { return o.wild; });
ok('8. the rules view: every WILD combatant in rules.others reports level = its species level (RulesField.levelOf reads the wild block), the player stays LV 1', wildOthers.length > 0 && wildOthers.every(function (o) { return o.level === ECO[o.wild].level; }) && p0.rules.me.level === 1, { wild: wildOthers.length, sample: wildOthers.slice(0, 3).map(function (o) { return [o.wild, o.level]; }) });
/* §2 on the host: the lock rule for an AIRBORNE pair sees over the terrain (the sight line runs at the lower body's height) */
var dk = nearest(cr); if (dk) { h.dev.play('PLACE', { account_id: 'A', x: dk.position.x + 5, z: dk.position.z }); run(0.5); face(dk); var lk = send('LOCK_TARGET', { aim_id: dk.id }); ok('9. ground lock unchanged: a Dogkie 5 m away with clear sight locks (the LOS base height 1.0 m still applies to two bodies on the ground)', lk.accepted && lk.locked === dk.id, lk); send('LOCK_TARGET', { aim_id: null }); }
/* the Visionary highland (2.6 m top, 12 m overlook supports / monoliths) between a flyer at 37 m and a phoenix above: the host must accept the lock */
send('FLIGHT', { op: 'EXIT' }); run(2); var ph = nearest(wl, 'PHOENIX'); if (ph) { h.dev.play('PLACE', { account_id: 'A', x: ph.position.x, z: ph.position.z }); run(0.5); send('FLIGHT', { op: 'ENTER' }); run(0.4); send('FLIGHT', { op: 'ASCEND' }); run(9); send('FLIGHT', { op: 'HOVER' }); run(1); var alt = play().flight.altitude;
  var lock2 = null, dist2 = null, tries = 0; while (tries < 240 && !(lock2 && lock2.accepted)) { run(0.25); var pp = play().wildlife.filter(function (x) { return x.id === ph.id; })[0]; if (!pp) break; var me2 = play().position; dist2 = Math.hypot(pp.position.x - me2.x, pp.position.z - me2.z, pp.y - play().flight.altitude); if (dist2 <= 29) { face(pp); lock2 = send('LOCK_TARGET', { aim_id: ph.id }); if (!lock2.accepted && lock2.reason !== 'TOO_FAR' && lock2.reason !== 'NO_LINE_OF_SIGHT') break; } tries++; if (tries === 12) h.dev.play('WILDLIFE_SUMMON', { account_id: 'A', species: 'PHOENIX' }); }
  ok('10. §2 aerial lock: a flyer at ≥ 30 m locks the provoked phoenix once it is inside the 30 m rule — no NO_LINE_OF_SIGHT from the monoliths / terrain BELOW both bodies (the sight line runs at the lower body height + 1 m)', alt >= 30 && !!(lock2 && lock2.accepted && lock2.locked === ph.id), { alt: alt, lock: lock2, dist: dist2, tries: tries });
  /* M2 Phoenix: after a dive it makes an airborne pass. A flying player can answer it; every published sample stays above the terrain clearance floor. */
  var states = {}, sweepMin = 1e9, clearanceMin = 1e9, hits = 0, before = h.dev.log().filter(function (e) { return e.kind === 'R1723_DAMAGE' && e.on === ph.id; }).length; send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 });
  for (var q = 0; q < 600; q++) { run(0.05); var pq = play().wildlife.filter(function (x) { return x.id === ph.id; })[0]; if (!pq) break; states[pq.state] = (states[pq.state] || 0) + 1; clearanceMin = Math.min(clearanceMin, pq.terrain_clearance_m); var meq = play(); var d2 = Math.hypot(pq.position.x - meq.position.x, pq.position.z - meq.position.z); var dy = Math.abs(pq.y - meq.flight.altitude); if (pq.state === 'AERIAL_PASS') sweepMin = Math.min(sweepMin, d2); if (d2 <= 2.4 && dy <= 1.5) { face(pq); send('RULES_CAST', {}); run(0.4); } }
  hits = h.dev.log().filter(function (e) { return e.kind === 'R1723_DAMAGE' && e.on === ph.id; }).length - before;
  ok('11. M2 Phoenix AERIAL_PASS: the old ground-height SWEEP never appears; the pass remains ≥ min_terrain_clearance_m over changing ground, and a flying player can still land a height-aware body strike through the one combat authority', !states.SWEEP && states.AERIAL_PASS > 0 && clearanceMin + 0.01 >= ECO.PHOENIX.habitat.min_terrain_clearance_m && sweepMin <= 2.6 && hits >= 1, { states: states, pass_min_m: +sweepMin.toFixed(2), clearance_min_m: +clearanceMin.toFixed(2), hits: hits });
  send('LOCK_TARGET', { aim_id: null }); send('FLIGHT', { op: 'EXIT' }); run(6);
} else ok('10. (no phoenix awake)', false);
/* §2 the fish: provoked from the bank, its swirl orbit brings it inside reach and a body strike lands */
var pool = REG.ecology.species.FISH.habitat.bodies.filter(function (b) { return b.id === 'VISIONARY_POOL'; })[0]; h.dev.play('PLACE', { account_id: 'A', x: pool.x, z: pool.z + pool.rz + 2.5 }); run(2);
var fishRec = nearest(play().wildlife, 'FISH'); if (fishRec) { var fst = {}, swirlMin = 1e9, fhits = 0, fb = h.dev.log().filter(function (e) { return e.kind === 'R1723_DAMAGE' && e.on === fishRec.id; }).length; face(fishRec); send('LOCK_TARGET', { aim_id: fishRec.id }); send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 });
  for (var fq = 0; fq < 700; fq++) { run(0.05); var fr = play().wildlife.filter(function (x) { return x.id === fishRec.id; })[0]; if (!fr || fr.ko) break; fst[fr.state] = (fst[fr.state] || 0) + 1; var mf = play(); var fd = Math.hypot(fr.position.x - mf.position.x, fr.position.z - mf.position.z); if (fr.state === 'SWIRL') swirlMin = Math.min(swirlMin, fd); if (fd <= 2.4 && Math.abs(fr.y - (mf.flight.altitude || 0)) <= 1.5) { face(fr); send('RULES_CAST', {}); run(0.4); } }
  fhits = h.dev.log().filter(function (e) { return e.kind === 'R1723_DAMAGE' && e.on === fishRec.id; }).length - fb;
  ok('12. §2 fish: provoked from the bank it swirls INSIDE melee reach (swirl_radius_m 2.3) between launches and the slot-1 strike lands — a movement test the player can actually answer (was a 4.2 m orbit = unreachable)', fst.SWIRL > 0 && swirlMin <= 2.6 && fhits >= 1, { states: fst, swirl_min_m: +swirlMin.toFixed(2), hits: fhits });
} else ok('12. (no fish awake at the Visionary pool)', false);
console.log('RESULT b7 targeting: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
