/* JOB B (owner directive 2026-09-19) — MAP / WORLD / ENVIRONMENT on the HOST: the registry-generated world colliders are in sync with the
   authority mapping + the room data (one registry, one placement); the north canal blocks wading but the bridges carry a walker and flight
   clears the kerbs; the MATCH HALL is a real enterable room (door, spawn, exit, no practice dummy, match-capable rules field); the forest
   creatures (Dogkie) activate / roam / go dormant through the existing rules field and only bite in PRACTICE; the AI-vs-AI spar scheduler
   runs bouts between free town NPCs. In-process host, plain node. node 16_TESTS/gameplay_world_jobb.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { spawnSync } from 'node:child_process';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost } from '../26_LOCAL_AUTHORITY/DuelHost.js'; import { makeEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';
import { createColliders } from '../26_LOCAL_AUTHORITY/play/rules1723/Colliders.js';
import { worldColliders, forestLayout, fixtureLayout, groundYAt } from '../26_LOCAL_AUTHORITY/lab/world/worldLayout.js';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.join(HERE, '..', '26_LOCAL_AUTHORITY');
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var data = await loadHeadlessData(); var cfg = data.cfg; var DT = cfg.dev('local_authority.tick_dt_s'); var ROOMS = cfg.dev('local_authority.play.rooms');
var REG = JSON.parse(fs.readFileSync(path.join(LA, 'lab', 'assets', 'world', 'world_registry_v1.json'), 'utf8'));
var RULES = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'rules_17_23.dev.json'), 'utf8')); var L = RULES._runtime_mapping.field_colliders_district_v1;
var WJ = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'world_v1_colliders.json'), 'utf8'));
/* ---- 1. registry → colliders → mapping / rooms are in sync (the generator's own --check) ---- */
var chk = spawnSync(process.execPath, [path.join(LA, 'deploy', 'jobb', 'build_world_colliders.mjs'), '--check'], { encoding: 'utf8' });
ok('1. deploy/jobb/build_world_colliders.mjs --check: the authority mapping, the room data and world_v1_colliders.json match the registry', chk.status === 0, (chk.stdout + chk.stderr).slice(-300));
var chk2 = spawnSync(process.execPath, [path.join(LA, 'deploy', 'sync_district_colliders.mjs'), '--check'], { encoding: 'utf8' });
ok('1b. deploy/sync_district_colliders.mjs --check still passes with the world shapes present (district + world coexist)', chk2.status === 0, (chk2.stdout + chk2.stderr).slice(-200));
var worldInMap = L.shapes.filter(function (s) { return s.world === 'JOBB'; }); var lms = (L.landmarks || []).map(function (l) { return l.envelope; }); var regen = worldColliders(REG, lms);
ok('2. the mapping carries exactly the registry-generated world shapes (' + regen.length + '), every one with a zone, after the district shapes; base plaza shapes stay 28', JSON.stringify(worldInMap) === JSON.stringify(regen) && worldInMap.every(function (s) { return !!s.zone; }) && L.shapes.filter(function (s) { return !s.district && !s.world; }).length === 28 && WJ.shapes.length === regen.length, { mapping: worldInMap.length, regen: regen.length, json: WJ.shapes.length });
var fl = forestLayout(REG, lms), fx = fixtureLayout(REG);
ok('3. seeded placement is deterministic and clears the landmarks / plaza: ' + fl.length + ' trees (no two closer than 4 m, none inside a landmark envelope or the 56 m plaza), ' + fx.length + ' fixtures', fl.length > 100 && fx.length > 40 && JSON.stringify(forestLayout(REG, lms)) === JSON.stringify(fl) && fl.every(function (t) { return Math.hypot(t.x, t.z) > 56 && !lms.some(function (e) { return t.x > e.x1 - 3 && t.x < e.x2 + 3 && t.z > e.z1 - 3 && t.z < e.z2 + 3; }); }) && (function () { for (var i = 0; i < fl.length; i++) for (var j = i + 1; j < fl.length; j++) if (Math.hypot(fl[i].x - fl[j].x, fl[i].z - fl[j].z) < 4) return false; return true; })(), { trees: fl.length, fixtures: fx.length });
/* ---- 2. the host collider set: canal, bridges, match hall, flight ---- */
var C = createColliders(L);
ok('4. broad phase: the world shapes are zone groups (not in the per-snapshot base list); groups() still lists the 4 district buildings only', C.baseShapes.length === 28 && C.groups().length === 4 && C.worldGroups().length >= 10 && C.worldShapeCount() === regen.length, { base: C.baseShapes.length, groups: C.groups().length, world_groups: C.worldGroups().length });
var river = REG.water.rivers[0], bridge = REG.water.bridges.filter(function (b) { return b.id === 'BRIDGE_MAIN'; })[0];
ok('5. the canal is a BEACH (owner 2026-09-19): no kerb — the ground slopes from 0 at the floor edge to wade_y over shore_w (walkable water ramps), the flat wade floor between, the bridge deck walkable at deck_y with ramps, the rails blocking the deck edges', Math.abs(C.groundHeight(-40, river.z1 - 0.2)) < 1e-6 && C.groundHeight(-40, river.z1 + 1.5) < -0.02 && C.groundHeight(-40, river.z1 + 1.5) > river.wade_y && Math.abs(C.groundHeight(-40, 226) - river.wade_y) < 1e-6 && !C.blockedAt(-40, river.z1 + 1.5, C.groundHeight(-40, river.z1 + 1.5)) && !C.blockedAt(-40, 226, river.wade_y) && !C.blockedAt(0, 226, C.groundHeight(0, 226)) && Math.abs(C.groundHeight(0, 226) - bridge.deck_y) < 1e-6 && C.groundHeight(0, 213.5) > 0 && C.groundHeight(0, 213.5) < bridge.deck_y && !!C.blockedAt(bridge.x1 + 0.15, 226, bridge.deck_y) && !L.shapes.some(function (x) { return x.rim && x.world; }), { ground_edge: C.groundHeight(-40, river.z1 - 0.2), ground_slope: C.groundHeight(-40, river.z1 + 1.5), ground_water: C.groundHeight(-40, 226), ground_deck: C.groundHeight(0, 226), ground_ramp: C.groundHeight(0, 213.5) });
ok('6. flight clears the water: at 2 m altitude nothing over the canal or the rails blocks', !C.blockedAt(-40, river.z1 - 0.2, 2) && !C.blockedAt(bridge.x1 + 0.15, 226, 2) && !C.blockedAt(-40, 226, 2));
var MH = REG.artifacts.filter(function (a) { return a.id === 'MATCH_HALL'; })[0]; var door = MH.door;
ok('7. MATCH HALL: the building box blocks, the doorway gap at the west face is open at body height and closed above the lintel; the court pylons are trunks', !!C.blockedAt(MH.position[0], MH.position[2], 0) && !C.blockedAt(door.x + 1.5, door.z, 0) && !!C.blockedAt(door.x + 1.5, door.z, door.height + 0.5) && !!C.blockedAt(128 + Math.cos(Math.PI / 4) * 17.7, 50 + Math.sin(Math.PI / 4) * 17.7, 0) && !C.blockedAt(128, 50, 0), { door: door });
/* ---- 3. the host: enter the MATCH HALL through its door, no dummy, match-capable, exit ---- */
var h = createDuelHost({ data: data, composeHeadless: composeHeadless }); h.dev.createAccount('A', { classId: 'ATHLETE', sex: 'M' });
var c = h.connect({ client_id: 'c', account_id: 'A', token: h.dev.tokens().A }); var seq = 0; var send = function (a, p) { return h.submit(makeEnvelope({ session_id: c.session_id, client_id: 'c' }, ++seq, a, p || {})); }; var play = function () { return h.snapshot(c.session_id).play; };
function run(sec) { for (var i = 0; i < Math.round(sec / DT); i++) h.tick(DT); }
function goTo(x, z) { for (var p2 = 0; p2 < 3; p2++) { for (var i = 0; i < 3000; i++) { var pos = play().position; var dx = x - pos.x, dz = z - pos.z; var d = Math.hypot(dx, dz); if (d < 0.45) break; send('MOVE', { forward: +(-dz / d).toFixed(3), strafe: +(dx / d).toFixed(3), run: d > 4, fast: true, yaw: +Math.atan2(dx, -dz).toFixed(3) }); h.tick(DT); } send('MOVE', { forward: 0, strafe: 0 }); run(0.4); var q = play().position; if (Math.hypot(x - q.x, z - q.z) < 1.0) return true; } return false; }
function navTo(x, z) { for (var leg = 0; leg < 12; leg++) { var pos = play().position; var d = Math.hypot(x - pos.x, z - pos.z); if (d < 1.2) return true; var f = Math.min(1, 26 / d); var r = send('NAV', { dest_x: pos.x + (x - pos.x) * f, dest_z: pos.z + (z - pos.z) * f, via: 'TAP' }); if (!r.accepted) { goTo(pos.x + (x - pos.x) * Math.min(1, 6 / d), pos.z + (z - pos.z) * Math.min(1, 6 / d)); continue; } for (var i = 0; i < 400; i++) { h.tick(DT); var pn = play(); if (!pn.nav) break; } } return Math.hypot(x - play().position.x, z - play().position.z) < 1.5; }   /* the owner's click-to-move (host navigator) — plans around trunks; a refused leg falls back to a short straight walk */
send('ENTER_ROOM', { room: 'FIELD' }); run(0.5);
var doors = play().rules.colliders.interactables.filter(function (i) { return i.kind === 'ENTER'; }); var md = doors.filter(function (d) { return d.id === 'MATCH_DOOR'; })[0];
ok('8. the FIELD publishes MATCH_DOOR (ENTER → MATCH_HALL) at the registry point beside the five existing / B8 doors and the four M4 honest civic-shell doors', !!md && md.to.room === 'MATCH_HALL' && doors.length === 10 && ['CIVIC_TRAINING_DOOR', 'CIVIC_ARENA_DOOR', 'CIVIC_MENTOR_DOOR', 'CIVIC_EXCHANGE_DOOR'].every(function (id) { return doors.some(function (d) { return d.id === id; }); }) && md.x === REG.interactables_added[0].x && md.z === REG.interactables_added[0].z, doors.map(function (d) { return d.id; }));
var far = send('ENTER_ROOM', { room: 'MATCH_HALL' }); ok('9. ENTER refused away from the door (NOT_AT_DOOR) — the hall is entered through its real doorway only', !far.accepted && far.reason === 'NOT_AT_DOOR', far);
goTo(0, -26); goTo(40, -26); goTo(60, 4); var reached = goTo(md.x - 0.6, md.z);   /* around the plaza's east building, then east along the match route */ var en = send('ENTER_ROOM', { room: 'MATCH_HALL' }); run(0.3); var pin = play();
ok('10. walked to the door (plaza → match district, no invisible wall) and entered: room MATCH_HALL, 44 m, interior, spawn in the aisle, exit gate at the doorway; NO practice dummy; practice OFF', reached && en.accepted && pin.room === 'MATCH_HALL' && pin.room_size_m === 44 && pin.room_interior && Math.abs(pin.position.x - ROOMS.MATCH_HALL.spawn.x) < 0.01 && pin.exit && pin.exit.to === 'FIELD' && pin.rules && !pin.rules.others.some(function (o) { return o.id === 'FIELD_DUMMY'; }) && pin.rules.practice === false && pin.npcs.length === 0, { reached: reached, en: en.accepted, room: pin.room, others: pin.rules && pin.rules.others.map(function (o) { return o.id; }), practice: pin.rules && pin.rules.practice });
var tiers = pin.rules.colliders.shapes.filter(function (s) { return /MATCH_TIER/.test(s.id); });
ok('11. the spectator tiers are walkable platforms of the room (10 boxes, two heights, doorway aisle open) — visual == collider', tiers.length === 10 && tiers.every(function (s) { return s.walkable; }) && tiers.some(function (s) { return s.h === 0.8; }) && tiers.some(function (s) { return s.h === 1.6; }) && !tiers.some(function (s) { return s.x1 < 0 && s.x2 > 0 && s.z1 > 10; }), tiers.map(function (s) { return s.id; }));
var mt = send('TEAM_MATCH', { op: 'START', size: 1 }); run(0.2); var st = play().rules.match;
ok('12. the existing match function (rules 17–23 TEAM_MATCH) works inside the hall: START → a FORMING match in this room (the official-match flows run here; the match UI / FORFEIT contract belongs to JOB A)', mt.accepted && st && st.state === 'FORMING', { mt: mt.accepted, reason: mt.reason, state: st && st.state });
if (mt.accepted) { send('TEAM_MATCH', { op: 'ABORT' }); run(0.2); }
goTo(ROOMS.MATCH_HALL.exit.position.x, ROOMS.MATCH_HALL.exit.position.z); var out = send('ENTER_ROOM', { room: 'FIELD' }); run(0.3); var pout = play();
ok('13. EXIT lands on MATCH_DOOR outside, back in the FIELD with the town NPCs listed again', out.accepted && pout.room === 'FIELD' && Math.abs(pout.position.x - md.x) < 0.01 && pout.npcs.length === 9, { out: out.accepted, pos: pout.position, npcs: pout.npcs.length });
/* ---- 4. Dogkie habitat + AI-vs-AI spars ---- */
ok('14. no creature is streamed near the plaza (all ' + REG.creatures.DOGKIE.spawn_points.length + ' seeded Dogkies are a dormant pool; global awake cap remains ' + REG.creatures.DOGKIE.max_active + ')', play().creatures.length === 0 && REG.creatures.DOGKIE.spawn_points.length === REG.creatures.DOGKIE.pool_size && REG.creatures.DOGKIE.pool_size > REG.creatures.DOGKIE.max_active, { streamed: play().creatures.length, seeded: REG.creatures.DOGKIE.spawn_points.length, max_active: REG.creatures.DOGKIE.max_active });
goTo(-40, 0); goTo(-70, 10); run(3); var p1 = play(); var act = p1.creatures.length;
ok('15. approaching the west forest activates the nearby Dogkies (host combatants WILD_DOGKIE_* (team WILD since the 2026-09-20 next-pass), species DOGKIE, published in p.creatures; none within 12 m of the player at activation)', act >= 3 && act <= 12 && p1.creatures.every(function (k) { return /^WILD_DOGKIE_\d\d$/.test(k.id) && k.species === 'DOGKIE' && k.active; }) && p1.rules.others.filter(function (o) { return /DOGKIE/.test(o.id); }).length === act, { active: act, ids: p1.creatures.map(function (k) { return k.id + ':' + k.state; }) });
run(25); var p2 = play(); var moved = p2.creatures.some(function (k) { return k.state === 'ROAM' || k.speed_mps > 0.2; }); var leashOk = p2.creatures.every(function (k) { var sp = REG.creatures.DOGKIE.spawn_points.filter(function (s) { return 'WILD_DOGKIE_' + (('0' + (REG.creatures.DOGKIE.spawn_points.indexOf(s) + 1)).slice(-2)) === k.id; })[0]; return sp ? Math.hypot(k.position.x - sp.x, k.position.z - sp.z) <= REG.creatures.DOGKIE.leash_m + 1 : true; });
ok('16. they ROAM inside their leash (seeded wander through the shared colliders) and stay in the forest bed', moved && leashOk, { states: p2.creatures.map(function (k) { return k.state; }) });
var hp0 = play().rules.me.hp; var near = p2.creatures.slice().sort(function (a, b) { return Math.hypot(a.position.x + 70, a.position.z - 10) - Math.hypot(b.position.x + 70, b.position.z - 10); })[0]; navTo(near.position.x + 2.5, near.position.z + 2.0); run(6); var pf = play();
ok('17. FREE roam (re-pinned to the owner next-pass 2026-09-20: the Dogkie is the baseline ENEMY): standing beside a Dogkie it chases / bites through the field cast path and the player loses HP in the WILD context (the 2026-09-19 alert-only rule is superseded; the full loop is gameplay_creature_combat.test.mjs)', pf.rules.me.hp < hp0 && h.dev.log().some(function (e) { return e.kind === 'DOGKIE_BITE'; }) && h.dev.log().some(function (e) { return e.kind === 'R1723_DAMAGE' && e.context === 'WILD' && e.on === 'A'; }), { hp: pf.rules.me.hp, hp0: hp0, state: pf.creatures.filter(function (k) { return k.id === near.id; }).map(function (k) { return k.state; }) });
var pr = send('FIELD_PRACTICE', { on: true }); var trace = []; for (var ti = 0; ti < 10; ti++) { var pt0 = play(); var kk0 = pt0.creatures.slice().sort(function (a, b) { return Math.hypot(a.position.x - pt0.position.x, a.position.z - pt0.position.z) - Math.hypot(b.position.x - pt0.position.x, b.position.z - pt0.position.z); })[0]; if (kk0 && Math.hypot(kk0.position.x - pt0.position.x, kk0.position.z - pt0.position.z) > 5) navTo(kk0.position.x + 2.2, kk0.position.z + 1.6);   /* the straight-line walker can snag a trunk: close in again on the nearest creature */ run(1); var pt = play(); var kk = kk0 ? pt.creatures.filter(function (k) { return k.id === kk0.id; })[0] : null; trace.push(kk ? kk.state + '@' + Math.hypot(kk.position.x - pt.position.x, kk.position.z - pt.position.z).toFixed(1) : 'gone'); } var pp = play(); if (process.env.JOBB_DEBUG) { var dbgP = play(); console.log('player', JSON.stringify(dbgP.position), 'nearest', JSON.stringify(dbgP.creatures.map(function (k) { return k.id + '@' + k.position.x.toFixed(1) + ',' + k.position.z.toFixed(1); })), 'blocked', JSON.stringify(C.blockedAt(dbgP.position.x, dbgP.position.z, 0)), 'fl', JSON.stringify(dbgP.flight)); } if (process.env.JOBB_DEBUG) console.log('practice ack', JSON.stringify(pr).slice(0, 200), 'ctx', pp.rules.context, 'trace', trace.join(' ')); var bites = h.dev.log().filter(function (e) { return e.kind === 'DOGKIE_BITE'; }).length;
ok('18. PRACTICE: the Dogkie chases and bites through the rules field cast path (real damage rules); the bites are journaled', bites >= 2 && pp.rules.me.hp < hp0 && h.dev.log().some(function (e) { return e.kind === 'R1723_DAMAGE'; }), { bites: bites, hp: pp.rules.me.hp });
send('FIELD_PRACTICE', { on: false }); goTo(-40, -30); goTo(0, -40); goTo(40, -30); goTo(60, 4); run(3); var pd = play();   /* 60 m east of the plaza: every west-forest home is > 110 m away */
ok('19. walking east of the plaza puts the creatures to sleep again (dormant beyond 110 m: combatants removed, nothing streamed)', pd.creatures.length === 0 && pd.rules.others.filter(function (o) { return /DOGKIE/.test(o.id); }).length === 0 && h.dev.log().some(function (e) { return e.kind === 'DOGKIE_DORMANT'; }), { creatures: pd.creatures.length });
run(420); var spars = h.dev.log().filter(function (e) { return e.kind === 'AI_SPAR_BEGIN'; }); var ends = h.dev.log().filter(function (e) { return e.kind === 'AI_SPAR_END'; });
ok('20. AI-vs-AI spars: within 7 minutes at least one scheduled bout began and ended (two free town NPCs, several real casts, harmless FREE context, cooldowns respected)', spars.length >= 1 && ends.length >= 1 && ends.some(function (e) { return e.casts >= 3; }) && spars.every(function (s) { return s.a !== s.b; }), { spars: spars.length, ends: ends.map(function (e) { return e.why + ':' + e.casts; }) });
/* ---- 5. JOB B OFFICIAL DEMO REDIRECT (owner package 2026-09-19): regions / paths / ground / tree lock / sky / ecology data + the monolith colliders ---- */
var RG = REG.regions && REG.regions.list || [], PT = REG.paths && REG.paths.list || [], ECO = REG.ecology && REG.ecology.species || {}, FAMS = REG.crystal_families || {};
var CLASS_FAM = { ATHLETE: 'gold', TITAN: 'blue', LEAN: 'red', VISIONARY: 'purple', BAGE: 'pink' }; var SANCT = RG.filter(function (r) { return r.class; });
ok('21. regions (re-pinned to the owner next-pass 2026-09-20 §6): 8 named regions — the NEXUS hub, FIVE CLASS SANCTUARIES (ATHLETE gold / TITAN blue / LEAN red / VISIONARY purple / BAGE pink, each family used by exactly one sanctuary), the coast and the match district — each with ONE dominant crystal family, surface tags and a landmark', RG.length === 8 && RG.every(function (r) { return FAMS[r.family] && r.surface && r.surface.macro && r.landmark; }) && SANCT.length === 5 && Object.keys(CLASS_FAM).every(function (k) { return SANCT.filter(function (r) { return r.class === k && r.family === CLASS_FAM[k]; }).length === 1; }) && RG.some(function (r) { return r.id === 'NEXUS'; }), RG.map(function (r) { return r.id + ':' + (r.class || '-') + ':' + r.family; }));
ok('22. redirect paths: the three tiers exist (crown causeways on the field routes, regional paths, discovery trails), every path names a family and a surface tag, and every path point stays inside the field walls', PT.filter(function (p) { return p.tier === 'CAUSEWAY'; }).length >= 5 && PT.filter(function (p) { return p.tier === 'REGIONAL'; }).length >= 6 && PT.filter(function (p) { return p.tier === 'TRAIL'; }).length >= 6 && PT.every(function (p) { return FAMS[p.family] && p.surface && p.pts.every(function (q) { return Math.abs(q[0]) <= 175 && q[1] >= -56.5 && q[1] <= 292; }); }), { causeway: PT.filter(function (p) { return p.tier === 'CAUSEWAY'; }).length, regional: PT.filter(function (p) { return p.tier === 'REGIONAL'; }).length, trail: PT.filter(function (p) { return p.tier === 'TRAIL'; }).length });
ok('23. redirect ecology: FISH / HORSE / PHOENIX derivatives exist with L0 / L1 / L2 runtime files on disk, bounded pools, habitats, and WILD / PET metadata with NO payment UI (payment_ui false everywhere, acquisition = an owner decision); the phoenix is ≈ 2× the player and flies under the 100 m ceiling', ['FISH', 'HORSE', 'PHOENIX'].every(function (k) { var sp = ECO[k]; var d = REG.derivatives.filter(function (x) { return x.id === sp.derivative; })[0]; return sp && d && ['L0', 'L1', 'L2'].every(function (lv) { return d.files[lv] && fs.existsSync(path.join(LA, d.files[lv].runtime)); }) && sp.pool && sp.habitat && sp.ownership && sp.ownership.wild === true && sp.ownership.payment_ui === false && /OWNER_DECISION/.test(sp.ownership.acquisition); }) && REG.ecology.payment_ui === false && ECO.PHOENIX.length_m >= 3.2 && ECO.PHOENIX.length_m <= 3.6 && ECO.PHOENIX.habitat.alt_m[1] < 100 && ECO.HORSE.pool.solitary === true && ECO.FISH.motion.breach_height_m > 0, Object.keys(ECO));
ok('24. redirect: no purchase / price / payment string anywhere in the registry or the world layer (the pet economy is an owner decision, not demo UI)', !/(buy now|checkout|paywall|add to cart|stripe)/i.test(JSON.stringify(REG)) && ['wildlife.js', 'creatures.js', 'guides.js', 'terrain.js'].every(function (f) { return !/(buy now|checkout|paywall|add to cart|stripe)/i.test(fs.readFileSync(path.join(LA, 'lab', 'world', f), 'utf8').replace(/no purchase[^\n]*/gi, '')); }));
var mono = regen.filter(function (s) { return s.monolith; });
var monoInside = RG.reduce(function (n, r) { return n + (r.monoliths || []).filter(function (m) { return Math.abs(m.x) < 175 && m.z > -56.5 && m.z < 292; }).length; }, 0);
ok('25. landmarks + OP10: every reachable registry monolith has one main and two local satellite CYLINDER proxies matching terrain.js; Moon Pass keeps four distinct flanks, the Visionary cluster blocks each visible crystal, and clearance between/above remains open', mono.length === monoInside * 3 && monoInside === 16 && ['TITAN_SANCTUARY_MONOLITH6', 'TITAN_SANCTUARY_MONOLITH7', 'TITAN_SANCTUARY_MONOLITH8', 'TITAN_SANCTUARY_MONOLITH9'].every(function (id) { return mono.some(function (m) { return m.id === id; }) && mono.some(function (m) { return m.id === id + '_SAT_A'; }) && mono.some(function (m) { return m.id === id + '_SAT_B'; }); }) && mono.every(function (m) { return worldInMap.some(function (s) { return s.id === m.id && s.type === 'CYLINDER'; }) && Math.abs(m.x) < 180 && m.z > -62 && m.z < 298; }) && C.blockedAt(-120, 0, 0.5) && C.blockedAt(-120 + 7 * 0.18 * 1.6, 7 * 0.18 * 0.4, 0.25) && !C.blockedAt(-120, 6, 0.5), mono.map(function (m) { return m.id + '@' + m.x + ',' + m.z + ' r' + m.r; }));
ok('26. redirect tree lock + sky + guide motion data: tree_lock maps every FOREST zone to a family with the trunk platinum / heat-grey and crystal only from the extremity band; sky has one wind vector and MIST / STRATUS / CUMULUS / CIRRUS layers (B7 §8: a third cheap cloud sheet for depth + the atmosphere data); guide_motion carries hover / drift / bank / settle; the map labels every region', REG.tree_lock && REG.zones.filter(function (z) { return z.kind === 'FOREST'; }).every(function (z) { return FAMS[REG.tree_lock.zone_family[z.id]]; }) && REG.tree_lock.crystal.extremity_start >= 0.5 && REG.sky && REG.sky.wind && REG.sky.layers.length === 4 && REG.sky.layers.some(function (L) { return L.id === 'STRATUS_LOW'; }) && REG.sky.atmosphere && REG.sky.atmosphere.day && REG.sky.atmosphere.day.fog && REG.guide_motion && REG.guide_motion.hover && REG.guide_motion.drift && REG.guide_motion.settle && REG.map && REG.map.labels.length === RG.length, { zone_family: REG.tree_lock && REG.tree_lock.zone_family });
var PONDZ = {}, HOUSEZ = {}, NEWZ = {}; (REG.water.rivers || []).forEach(function (r) { if (r.pond) { PONDZ[r.id] = 1; NEWZ[r.id] = 1; } }); (REG.architecture.class_houses || []).forEach(function (h) { HOUSEZ[h.id] = 1; NEWZ[h.id] = 1; });
ok('27. redirect coast: a land-rich archipelago (≥ 10 landmasses, each with a crystal family) including two flight-reachable islets inside the ±300 m room clamp and the CROWN highland; the walkable colliders of B2 did not change (the base 28 + district + the same world shapes) and the next-pass additions are exactly the pond and class-house shapes', REG.coast.islands.length >= 10 && REG.coast.islands.every(function (I) { return FAMS[I.family]; }) && REG.coast.islands.filter(function (I) { return I.reachable && Math.abs(I.x) + I.rx < 300 && Math.abs(I.z) + I.rz < 300; }).length === 2 && REG.coast.islands.some(function (I) { return I.crown; }) && regen.filter(function (s) { return !s.monolith && !s.terrace && !s.ridge && !NEWZ[s.zone]; }).length === regen.filter(function (s) { return s.tree; }).length + 28 && regen.filter(function (s) { return PONDZ[s.zone]; }).length === 20 && regen.filter(function (s) { return HOUSEZ[s.zone]; }).length === 18, { islands: REG.coast.islands.length, world_shapes: regen.length, ridge_shapes: regen.filter(function (s) { return s.ridge; }).length, pond_shapes: regen.filter(function (s) { return PONDZ[s.zone]; }).length, house_shapes: regen.filter(function (s) { return HOUSEZ[s.zone]; }).length });   /* 28 = the buildings / court / prop / canal / bridge shapes of B2; M5 ridge-face proxies are checked in gameplay_m5_ridge_collision.test.mjs and excluded from this legacy shape-class invariant; the next-pass adds 4 sanctuary PONDS (bed + 4 shores each) and 5 CLASS HOUSES (3 platforms, 3 spires, 4 supports, 8 basin ring frames — the 2 gate pillars ARE the region monoliths, one collider each) */
var terr = regen.filter(function (s) { return s.terrace; }); var T0 = REG.terraces.list[0];
var HL = REG.terraces.list.filter(function (t) { return t.id === 'HIGHLAND_W'; })[0];
ok('28. MACRO elevation (re-pinned 2026-09-20 + M3 Moon Pass): two CROWN TERRACES, the VISIONARY HIGHLAND and the walkable TITAN MOON PASS are in the host mapping; the legacy surfaces retain their exact ground behavior, all terrace shapes map to colliders, and every north-forest tree stands on its terrace', terr.length === 16 && HL && Math.abs(C.groundHeight(-152, 20) - HL.h) < 1e-6 && !C.blockedAt(-152, 20, HL.h) && Math.abs(C.groundHeight(-125.5, 0) - HL.h * 0.5) < 0.2 && Math.abs(C.groundHeight(-150, 44.5) - HL.h * 0.5) < 0.2 && Math.abs(C.groundHeight(-150, -44.5) - HL.h * 0.5) < 0.2 && C.blockedAt(-172.1, 0, 0) && !C.blockedAt(-160, 41.5, 0) && Math.abs(groundYAt(REG, -152, 20) - HL.h) < 1e-6 && terr.every(function (t) { return worldInMap.some(function (s) { return s.id === t.id; }); }) && ['TITAN_MOON_PASS_TOP', 'TITAN_MOON_PASS_LIP_W', 'TITAN_MOON_PASS_LIP_E', 'TITAN_MOON_PASS_RAMP_S', 'TITAN_MOON_PASS_RAMP_N'].every(function (id) { return terr.some(function (t) { return t.id === id; }); }) && Math.abs(C.groundHeight(150, 62) - 2.8) < 1e-6 && !C.blockedAt(150, 62, 2.8) && C.groundHeight(150, 43) > 0 && C.groundHeight(150, 43) < 2.8 && C.groundHeight(150, 47) > C.groundHeight(150, 43) && C.groundHeight(150, 47) < 2.8 && Math.abs(C.groundHeight(-112, 240.5)) < 0.05 && C.groundHeight(-112, 243) > 0.15 && C.groundHeight(-112, 243) < 0.35 && Math.abs(C.groundHeight(-112, 260) - T0.h) < 1e-6 && !C.blockedAt(-112, 260, T0.h) && Math.abs(C.groundHeight(0, 244)) < 1e-6 && Math.abs(C.groundHeight(-43, 280) - T0.h * 0.5) < 0.12 && Math.abs(C.groundHeight(-43, 260) - 0.5) < 1e-6 && !C.blockedAt(-43, 260, 0.5) &&   /* (-43, 260) is the BAGE basin ring W (0.5 m, level with the terrace edge, a walkable low ledge); the inner ramp is sampled north of it */ fl.filter(function (t) { return /FOREST_N_/.test(t.zone); }).every(function (t) { return Math.abs(groundYAt(REG, t.x, t.z) - C.groundHeight(t.x, t.z)) < 1e-6 && groundYAt(REG, t.x, t.z) === T0.h; }), { terrace_shapes: terr.map(function (t) { return t.id; }), g_pass_south: C.groundHeight(150, 43), g_pass_ramp: C.groundHeight(150, 47), g_pass_top: C.groundHeight(150, 62), g240: C.groundHeight(-112, 240.5), g243: C.groundHeight(-112, 243), g260: C.groundHeight(-112, 260), g_market: C.groundHeight(0, 244), g_inner_ramp: C.groundHeight(-43, 280), g_bage_ring: C.groundHeight(-43, 260), g_highland: C.groundHeight(-152, 20), g_highland_ramp: C.groundHeight(-125.5, 0) });
/* ---- owner B7 PHONE REVIEW DELTA (2026-09-20) §3 / §6 / §7 / §8 / §9 / §10 C — the client world layer (source-pinned; the runtime proof is deploy/joba/probe_targeting.mjs + deploy/jobb/arch_views.mjs) ---- */
var WSRC = function (f) { return fs.readFileSync(path.join(LA, 'lab', 'world', f), 'utf8'); }; var ARCH = WSRC('architecture.js'), CRE = WSRC('creatures.js'), WLD = WSRC('wildlife.js'), WB = WSRC('worldB.js'), TER = WSRC('terrain.js'), ATM = WSRC('atmosphere.js'), ENT = WSRC('entityStatus.js');
ok('29. §3 ONE reusable entity status (lab/world/entityStatus.js: NAME · LV · HP bar, billboard sprite, distance fade, LOCKED / KO states) used by BOTH creatures.js and wildlife.js, shown for every active nearby figure (no "only while damaged" rule left) with a statusOf(id) accessor', /export function createEntityStatus/.test(ENT) && /LV ' \+ st\.level/.test(ENT) && /createEntityStatus\(THREE/.test(CRE) && /createEntityStatus\(THREE/.test(WLD) && /statusOf: function \(id\)/.test(CRE) && /function statusOf\(id\)/.test(WLD) && !/hp < mx - 1e-6 && !ko; fig\.tag\.visible/.test(CRE) && !/hp < mx - 1e-6 && !rec\.ko; f\.tag\.visible/.test(WLD) && /locked: lockedId === c\.id/.test(CRE) && /locked: lockedId === rec\.id/.test(WLD));
ok('30. §6 / §7 + M6 architecture: free-standing seam rods and blunt façade bands are gone; colour stays material-integrated while structures, selected canopies and free accents share the faint arcane-leakage mist language', !/function seamsFor/.test(ARCH) && !/satList\.push/.test(ARCH) && /function integratedFor\(lm, env, S, family, entrance, hero\)/.test(ARCH) && /function facadeAt\(lm, env, a, y, w\)/.test(ARCH) && /function buildAuras\(\)/.test(ARCH) && /ARCANE_LEAKAGE_MIST/.test(ARCH) && /canopy_aura_anchors/.test(ARCH) && /free_aura_anchors/.test(ARCH) && /info\.insets\+\+/.test(ARCH) && /the hero's roof diamonds ride the crown frame corners/.test(ARCH));
ok('31. §8 atmosphere: worldB mounts lab/world/atmosphere.js after the sky (the scattering dome shader: Rayleigh-style optical depth, horizon haze warmed to the sun, Henyey-Greenstein Mie lobe, ground haze, LOW tier = Mie off; the fog takes the haze colour); the sky sheets use stable celestial-direction lighting + tiered counts; farWorld authors a depth hierarchy (never brighter than the horizon)', /\['atmosphere', createAtmosphere\]/.test(WB) && /uniform float uMie/.test(ATM) && /1\.0 - g \* g\) \/ pow\(1\.0 \+ g \* g - 2\.0 \* g \* mu, 1\.5\)/.test(ATM) && /scene\.fog\.color\.set\(P\('fog'\)\)/.test(ATM) && /tier\(\) === 'LOW' \? 0 : P\('mie'\)/.test(ATM) && /dirs\.sun = celestialDirection/.test(WSRC('sky.js')) && /im\.setColorAt\(i, _c\)/.test(WSRC('sky.js')) && /never brighter than the horizon sky/.test(fs.readFileSync(path.join(LA, 'lab', 'farWorld.js'), 'utf8')));
ok('32. §9 fish population LOD: registry ecology.FISH.population_lod (mid per pond / canal / sea schools, far silhouettes) → wildlife.js buildPopulation (two InstancedMeshes, agents cruise AT the surface, breaches through splash() + the ripple impulse, tier-scaled counts, nothing on the host); the host pool is unchanged (10 schools × 3)', REG.ecology.species.FISH.population_lod && REG.ecology.species.FISH.population_lod.mid.per_pond >= 6 && REG.ecology.species.FISH.population_lod.far.sea_silhouettes >= 60 && /function buildPopulation\(\)/.test(WLD) && /FISH_SCHOOL_AGENTS/.test(WLD) && /FISH_FAR_SILHOUETTES/.test(WLD) && /function tickPopulation\(dt\)/.test(WLD) && /splash\(ag0\.x, ag0\.z, S\.sy/.test(WLD) && REG.ecology.species.FISH.pool.schools === 10 && REG.ecology.species.FISH.pool.per_school === 3);
ok('33. §10 C + OP05/06 the discovery trails remain a continuous narrow class-crystal inlay on the dark base while every tier now passes through the one owned road graph and clipped junction boundaries (no dashed cores / overlapping extended strips)', !/var dash = 2\.4, gap = 1\.4/.test(TER) && /trail \? cw \* 0\.55 : cw/.test(TER) && /buildRoadNetwork\(authoredRoads, explicitJunctions\)/.test(TER) && /clippedStrip\(cores/.test(TER) && !/stripSeg\(cores, a\[0\]/.test(TER));
console.log('RESULT world jobb: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
