/* MAHWORLD GAMEPLAY RUNTIME :: OD-29 (PARTIAL OWNER DECISION 2026-09-14) — 10-second reconnect window, NO_CONTEST on expiry, no winner.
   Focused suite on the local authority host (in-process; one durable sqlite check in a disposable dir). Plain node, no GPU / DOM / Blender.
   node 16_TESTS/gameplay_od29_disconnect.test.mjs   (from CLAUDE_GAMEPLAY_RUNTIME) */
import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost, hostIdentity } from '../26_LOCAL_AUTHORITY/DuelHost.js';
import { createSqliteStore, loadSqlite } from '../26_LOCAL_AUTHORITY/DurableStore.js';
import { createLabClient, createInProcessTransport } from '../26_LOCAL_AUTHORITY/LabClient.js';
import { startLabServer } from '../26_LOCAL_AUTHORITY/lab_host_server.mjs';

var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var data = await loadHeadlessData(); var DT = data.cfg.dev('local_authority.tick_dt_s'); var WINDOW = data.cfg.dev('local_authority.reconnect_window_s');
function newHost(store, opened) { var h = createDuelHost({ data: data, composeHeadless: composeHeadless, store: store, opened: opened }); ['PLAYER_A', 'PLAYER_B', 'SPECTATOR_1'].forEach(function (id) { h.dev.createAccount(id, { sex: id === 'PLAYER_B' ? 'M' : 'F' }); }); var tok = h.dev.tokens(); var T = createInProcessTransport(h); return { host: h, A: createLabClient({ client_id: 'cA', account_id: 'PLAYER_A', token: tok.PLAYER_A, transport: T }), B: createLabClient({ client_id: 'cB', account_id: 'PLAYER_B', token: tok.PLAYER_B, transport: T }), S: createLabClient({ client_id: 'cS', account_id: 'SPECTATOR_1', token: tok.SPECTATOR_1, transport: T }), run: function (sec) { var n = Math.round(sec / DT); for (var i = 0; i < n; i++) h.tick(DT); }, runUntil: function (pred, max) { var t = 0; while (t < max) { h.tick(DT); t += DT; if (pred()) return t; } return null; } }; }
async function duelWithDamage(L) { await L.A.connect(); await L.B.connect(); await L.S.connect(); await L.A.send('JOIN_DUEL'); await L.B.send('JOIN_DUEL'); L.run(0.6); await L.S.send('SPECTATE'); await L.S.send('CALL_NEXT'); await L.A.send('SELECT_PATTERN', { pattern_id: 'VERTICAL_PULL' }); await L.A.send('ATTACK', { hint: 'HOLD' }); L.run(4.0); return L.host.snapshot(L.A.view().session_id); }
function state(h, sess) { var s = h.snapshot(sess); return { health: JSON.stringify(s.duel && s.duel.health), mahgic: s.me && s.me.mahgic, pattern: s.me && s.me.pattern, xp: s.me && s.me.xp, form: s.me && s.me.form, attack: s.me && s.me.attack && s.me.attack.state, duel: s.duel && s.duel.state, queue: JSON.stringify(s.queue) }; }
ok('single authoritative setting: local_authority.reconnect_window_s = 10 s, expiry outcome NO_CONTEST (from dev tuning, not code)', WINDOW === 10 && data.cfg.dev('local_authority.disconnect_expiry_outcome') === 'NO_CONTEST' && data.cfg.dev('local_authority.od29_status').approved_2026_09_14.length === 2);

/* 1. successful reconnect before expiry resumes the SAME committed state */
var L1 = newHost(); var pre1 = await duelWithDamage(L1); var sA1 = L1.A.view().session_id; var before = state(L1.host, sA1); var t0 = L1.host.time(); var dc = await L1.B.disconnect();
ok('disconnect: gameplay paused, deadline = host time + 10 s', dc.ok && dc.reconnect_deadline_t === +(t0 + WINDOW) && L1.host.snapshot(sA1).paused === true && pre1.duel.health.PLAYER_B < 100);
var wbus = L1.host.snapshot(sA1); L1.run(9.8); var during = state(L1.host, sA1);
ok('while paused no gameplay advances (health, MAHGIC, pattern, xp, attack, queue unchanged) although host time advanced 9.8 s', JSON.stringify(during) === JSON.stringify(before) && L1.host.time() > t0 + 9.7 && L1.host.snapshot(sA1).duel.state === 'ACTIVE');
var rc = await L1.B.reconnect(); L1.run(0.1); var after = state(L1.host, sA1);
ok('reconnect at 9.8 s: same committed duel state resumed (nothing reset), unpaused, duel still ACTIVE, no NO_CONTEST', rc.ok && rc.state === 'IN_DUEL' && after.health === before.health && after.mahgic >= before.mahgic && after.pattern === before.pattern && after.xp === before.xp && after.duel === 'ACTIVE' && !L1.host.snapshot(sA1).paused && L1.host.snapshot(sA1).no_contest === null);

/* 2 + 3. expiry at the full 10-second deadline while the duel is paused; the clock does not freeze */
var L2 = newHost(); await duelWithDamage(L2); var sA2 = L2.A.view().session_id; var t2 = L2.host.time(); var hb2 = L2.host.snapshot(sA2); await L2.B.disconnect(); var worldTimeAtPause = L2.host.snapshot(sA2).t;
var elapsed = L2.runUntil(function () { return L2.host.state().duel === null; }, 12); var snap2 = L2.host.snapshot(sA2);
ok('expiry fires at the full deadline (elapsed ' + (elapsed === null ? 'never' : elapsed.toFixed(2)) + ' s ≈ 10 s), not earlier, not later', elapsed !== null && elapsed >= WINDOW - 1e-6 && elapsed <= WINDOW + DT + 1e-6);
ok('the duel ended as NO_CONTEST: no winner, no terminal result, opponent NOT the winner, health unchanged since the pause', snap2.no_contest && snap2.no_contest.outcome === 'NO_CONTEST' && snap2.no_contest.winner === null && snap2.no_contest.fighter === 'PLAYER_B' && snap2.terminal === null && snap2.last_duel.result === 'NO_CONTEST' && snap2.duel === null && L2.host.dev.log().filter(function (e) { return e.kind === 'NO_CONTEST'; }).length === 1);
ok('no rewards / receipts / XP on NO_CONTEST (INTERIM development setting, labelled as such)', Object.keys(L2.host.dev.rewards()).length === 0 && L2.host.receipts.stats().issued === 0 && snap2.me === undefined || (snap2.me && snap2.me.xp === 0) && /INTERIM/.test(snap2.no_contest.rewards));
ok('no winner-based Call Next: ACCEPT_NEXT / DECLINE_NEXT refused with NO_CONTEST_NO_WINNER; queued spectator not matched; spectator released (no locks)', (await L2.A.send('ACCEPT_NEXT')).reason === 'NO_CONTEST_NO_WINNER' && (await L2.A.send('DECLINE_NEXT', { choice: 'A' })).reason === 'NO_CONTEST_NO_WINNER' && L2.host.state().sessions.filter(function (s) { return s.account_id === 'SPECTATOR_1'; })[0].role === 'LOBBY');
ok('opponent session released to READY, expired fighter session CLOSED and cannot reconnect (SESSION_EXPIRED)', L2.A.view().snapshot && L2.host.state().sessions.filter(function (s) { return s.account_id === 'PLAYER_A'; })[0].state === 'READY' && (await L2.B.reconnect()).reason === 'SESSION_EXPIRED');

/* 4. duplicate disconnect notifications do not extend the incident */
var L3 = newHost(); await duelWithDamage(L3); var sA3 = L3.A.view().session_id; var t3 = L3.host.time(); var d1 = await L3.B.disconnect(); L3.run(3.0); var d2 = await L3.B.disconnect(); var d3 = L3.host.disconnect(L3.B.view().session_id);
ok('second and third notifications for the same incident are acknowledged as already-in-progress with the ORIGINAL deadline', d1.ok && d2.ok && d2.already === true && d3.already === true && L3.host.snapshot(sA3).session && L3.host.snapshot(L3.B.view().session_id).session.reconnect_deadline_t === +(t3 + WINDOW));
var el3 = L3.runUntil(function () { return L3.host.state().duel === null; }, 12); ok('expiry still at the original deadline (' + (el3 === null ? 'never' : (el3 + 3.0).toFixed(2)) + ' s after the first notification), exactly one NO_CONTEST', el3 !== null && el3 + 3.0 >= WINDOW - 1e-6 && el3 + 3.0 <= WINDOW + DT + 1e-6 && L3.host.dev.log().filter(function (e) { return e.kind === 'NO_CONTEST'; }).length === 1);

/* 5. reconnect / expiry race resolves once */
var L4 = newHost(); await duelWithDamage(L4); var sA4 = L4.A.view().session_id; await L4.B.disconnect(); var n = Math.round(WINDOW / DT) - 1; for (var i = 0; i < n; i++) L4.host.tick(DT); var justBefore = await L4.B.reconnect(); L4.run(1.0);
ok('reconnect on the last tick before the deadline wins: duel continues, no NO_CONTEST', justBefore.ok && L4.host.state().duel === 'ACTIVE' && L4.host.snapshot(sA4).no_contest === null && L4.host.dev.log().filter(function (e) { return e.kind === 'NO_CONTEST'; }).length === 0);
var L5 = newHost(); await duelWithDamage(L5); var sA5 = L5.A.view().session_id; await L5.B.disconnect(); L5.run(WINDOW + DT); var late = await L5.B.reconnect(); var late2 = await L5.B.reconnect(); L5.run(1.0);
ok('reconnect after the deadline loses once: SESSION_EXPIRED twice, one NO_CONTEST, duel closed once, nothing reopened', !late.ok && late.reason === 'SESSION_EXPIRED' && !late2.ok && L5.host.dev.log().filter(function (e) { return e.kind === 'NO_CONTEST'; }).length === 1 && L5.host.dev.log().filter(function (e) { return e.kind === 'DUEL_CLOSED'; }).length === 1 && L5.host.state().duel === null);
ok('no duplicate damage / spending / result across the incident: one main impact, one spend, no receipts', L5.host.dev.log().filter(function (e) { return e.kind === 'ACTOR_EVENT' && e.name === 'ATTACK_MAIN_IMPACT'; }).length === 1 && L5.host.dev.log().filter(function (e) { return e.kind === 'ACTOR_EVENT' && e.name === 'RESOURCE_SPENT'; }).length === 1 && L5.host.receipts.stats().issued === 0);

/* 6. durable recovery reproduces the NO_CONTEST (host restart itself stays RECOVERY_HELD_DEV) */
var sqlite = await loadSqlite(); var dir = fs.mkdtempSync(path.join(os.tmpdir(), 'mahworld-5b-test-od29-')); var st = createSqliteStore(sqlite, { dir: dir }); var op = st.open({ identity: hostIdentity(data) }); var L6 = newHost(st, op); await duelWithDamage(L6); var sA6 = L6.A.view().session_id; await L6.B.disconnect(); L6.run(WINDOW + 0.5); var nc6 = L6.host.snapshot(sA6).no_contest; st.simulateCrash(); fs.unlinkSync(st.lockPath);
var st2 = createSqliteStore(sqlite, { dir: dir }); var op2 = st2.open({ identity: hostIdentity(data) }); var h2 = createDuelHost({ data: data, composeHeadless: composeHeadless, store: st2, opened: op2 }); var rec = h2.recover(); var s6 = h2.snapshot(sA6); var receiptRows6 = Object.keys(st2.receipts()).length; st2.closeClean();
ok('after a host restart the NO_CONTEST is recovered as committed history (held, no winner, no receipts), no inconsistencies', rec.ok && rec.inconsistencies.length === 0 && h2.lifecycle() === 'RECOVERY_HELD_DEV' && s6.no_contest && s6.no_contest.outcome === 'NO_CONTEST' && s6.no_contest.match_id === nc6.match_id && s6.terminal === null && receiptRows6 === 0);
var hostSrc = fs.readFileSync(path.join(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..', '26_LOCAL_AUTHORITY', 'DuelHost.js'), 'utf8').replace(/\/\*[\s\S]*?\*\//g, ''); ok('the window value reaches the host only through config: deadlines use LA.reconnect_window_s and no literal seconds window exists in DuelHost.js', hostSrc.indexOf('dnow() + LA.reconnect_window_s') >= 0 && !/reconnect_deadline = (H\.t|dnow\(\)) \+ \d/.test(hostSrc) && !/ 10 s/.test(hostSrc));

/* 7. TIMING: the deadline is measured on an injectable deadline clock, not on fixed simulation ticks */
function fakeHost() { var fake = { t: 0 }; var h = createDuelHost({ data: data, composeHeadless: composeHeadless, clock: { kind: 'FAKE_WALL', now: function () { return fake.t; } } }); ['PLAYER_A', 'PLAYER_B', 'SPECTATOR_1'].forEach(function (id) { h.dev.createAccount(id, { sex: id === 'PLAYER_B' ? 'M' : 'F' }); }); var tok = h.dev.tokens(); var T = createInProcessTransport(h); return { host: h, fake: fake, A: createLabClient({ client_id: 'cA', account_id: 'PLAYER_A', token: tok.PLAYER_A, transport: T }), B: createLabClient({ client_id: 'cB', account_id: 'PLAYER_B', token: tok.PLAYER_B, transport: T }), S: createLabClient({ client_id: 'cS', account_id: 'SPECTATOR_1', token: tok.SPECTATOR_1, transport: T }), run: function (sec) { var n = Math.round(sec / DT); for (var i = 0; i < n; i++) h.tick(DT); } }; }
var F1 = fakeHost(); await duelWithDamage(F1); F1.fake.t = 100; var fd = await F1.B.disconnect();
ok('deadline = deadline-clock now + 10 s (fake wall clock injected; host reports the clock kind)', fd.reconnect_deadline_t === 110 && fd.deadline_clock === 'FAKE_WALL' && fd.reconnect_window_s === 10);
F1.fake.t = 109.9; F1.run(20.0);   /* 400 fast simulation ticks while only 9.9 wall seconds passed */
ok('fast / many simulation ticks do NOT expire the window early (400 ticks, 9.9 s on the deadline clock → still waiting)', F1.host.state().duel === 'ACTIVE' && F1.host.snapshot(F1.A.view().session_id).paused === true && F1.host.snapshot(F1.B.view().session_id).session.reconnect_remaining_s === 0.1);
F1.fake.t = 110.2; F1.host.tick(DT);   /* delayed update: a single tick arrives after the deadline passed */
ok('delayed update: ONE tick after the deadline expires the window on the actual clock (no extra time granted)', F1.host.state().duel === null && F1.host.snapshot(F1.A.view().session_id).no_contest && F1.host.snapshot(F1.A.view().session_id).no_contest.outcome === 'NO_CONTEST');
var F2 = fakeHost(); await duelWithDamage(F2); F2.fake.t = 50; await F2.B.disconnect(); F2.fake.t = 54; var dup = await F2.B.disconnect(); F2.fake.t = 59.9; F2.host.tick(DT);
ok('duplicate notification at +4 s does not restart the window (deadline still 60), not expired at 59.9', dup.already === true && dup.reconnect_deadline_t === 60 && F2.host.state().duel === 'ACTIVE');
F2.fake.t = 60.0; F2.host.tick(DT); ok('expires exactly at the original deadline (60.0)', F2.host.state().duel === null && F2.host.dev.log().filter(function (e) { return e.kind === 'NO_CONTEST'; }).length === 1);
var F3 = fakeHost(); await duelWithDamage(F3); F3.fake.t = 0; await F3.B.disconnect(); var ticksAt = F3.host.state().tick; F3.fake.t = 10.5;   /* blocked loop: NO tick ran, the clock passed the deadline, then the reconnect request is processed */
var lateRc = await F3.B.reconnect();
ok('a late reconnect processed before any tick ran is refused on the actual deadline (SESSION_EXPIRED, expired_on_reconnect), NO_CONTEST recorded once, duel closed — no extra time because too few ticks ran', !lateRc.ok && lateRc.reason === 'SESSION_EXPIRED' && lateRc.expired_on_reconnect === true && F3.host.state().tick === ticksAt && F3.host.state().duel === null && F3.host.dev.log().filter(function (e) { return e.kind === 'NO_CONTEST'; }).length === 1 && Object.keys(F3.host.dev.rewards()).length === 0);
var F4 = fakeHost(); await duelWithDamage(F4); F4.fake.t = 0; await F4.B.disconnect(); F4.fake.t = 9.99; var inTime = await F4.B.reconnect(); F4.fake.t = 30; F4.run(1.0);
ok('a reconnect processed at 9.99 s is accepted and the duel continues even though the clock later passes 10 s', inTime.ok && inTime.state === 'IN_DUEL' && F4.host.state().duel === 'ACTIVE' && F4.host.snapshot(F4.A.view().session_id).no_contest === null);
/* 8. durable replay with an irregular deadline clock: journaled readings are replayed, no fresh clock is read */
var dirC = fs.mkdtempSync(path.join(os.tmpdir(), 'mahworld-5b-test-od29clock-')); var stC = createSqliteStore(sqlite, { dir: dirC }); var opC = stC.open({ identity: hostIdentity(data) }); var fakeC = { t: 1000 }; var hC = createDuelHost({ data: data, composeHeadless: composeHeadless, store: stC, opened: opC, clock: { kind: 'FAKE_WALL', now: function () { return fakeC.t; } } }); ['PLAYER_A', 'PLAYER_B', 'SPECTATOR_1'].forEach(function (id) { hC.dev.createAccount(id, { sex: id === 'PLAYER_B' ? 'M' : 'F' }); }); var tokC = hC.dev.tokens(); var TC = createInProcessTransport(hC); var LC = { host: hC, A: createLabClient({ client_id: 'cA', account_id: 'PLAYER_A', token: tokC.PLAYER_A, transport: TC }), B: createLabClient({ client_id: 'cB', account_id: 'PLAYER_B', token: tokC.PLAYER_B, transport: TC }), S: createLabClient({ client_id: 'cS', account_id: 'SPECTATOR_1', token: tokC.SPECTATOR_1, transport: TC }), run: function (sec) { var n = Math.round(sec / DT); for (var i = 0; i < n; i++) { fakeC.t += (i % 3 === 0 ? 0.3 : 0.01); hC.tick(DT); } } };
await duelWithDamage(LC); var sAC = LC.A.view().session_id; await LC.B.disconnect(); var dlC = hC.snapshot(LC.B.view().session_id).session.reconnect_deadline_t; var stepsC = 0; while (hC.state().duel !== null && stepsC < 500) { fakeC.t += 0.4; hC.tick(DT); stepsC++; }
var ncC = hC.snapshot(sAC).no_contest; stC.simulateCrash(); fs.unlinkSync(stC.lockPath);
var stC2 = createSqliteStore(sqlite, { dir: dirC }); var opC2 = stC2.open({ identity: hostIdentity(data) }); var freshReads = 0; var hC2 = createDuelHost({ data: data, composeHeadless: composeHeadless, store: stC2, opened: opC2, clock: { kind: 'FRESH_CLOCK_MUST_NOT_BE_READ', now: function () { freshReads++; return 999999; } } }); var recC = hC2.recover(); var sC2 = hC2.snapshot(sAC); stC2.closeClean();
ok('irregular deadline clock: expiry fired after ' + stepsC + ' ticks (≈ ' + (stepsC * 0.4).toFixed(1) + ' clock seconds), replay reproduced the NO_CONTEST from journaled readings with no inconsistencies and read the fresh clock 0 times during reconstruction', stepsC > 0 && stepsC * 0.4 >= 10 && ncC && recC.ok && recC.inconsistencies.length === 0 && sC2.no_contest && sC2.no_contest.match_id === ncC.match_id && freshReads === 0);
/* 9. the ACTUAL live server driver: real setInterval ticks + monotonic wall clock, with a 3 s synchronous event-loop stall */
var srv = await startLabServer({ port: 0, memory: true, devHooks: true }); var base = 'http://127.0.0.1:' + srv.port; var tk = (await fetch(base + '/api/tokens').then(function (r) { return r.json(); })).tokens;
async function post(p, b) { return fetch(base + p, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(b || {}) }).then(function (r) { return r.json(); }); }
var cA = await post('/api/connect', { client_id: 'wA', account_id: 'PLAYER_A', token: tk.PLAYER_A }); var cB = await post('/api/connect', { client_id: 'wB', account_id: 'PLAYER_B', token: tk.PLAYER_B }); await post('/api/command', makeEnvelopeW(cA, 0, 'JOIN_DUEL')); await post('/api/command', makeEnvelopeW(cB, 0, 'JOIN_DUEL')); await new Promise(function (r) { setTimeout(r, 300); });
var wall0 = performance.now(); var dW = await post('/api/disconnect', { session_id: cB.session_id }); var tick0 = srv.host.state().tick;
var sab = new Int32Array(new SharedArrayBuffer(4)); Atomics.wait(sab, 0, 0, 3000);   /* 3 s synchronous stall: the interval cannot fire, the wall clock keeps running */
var afterStall = await fetch(base + '/api/snapshot?session=' + cB.session_id).then(function (r) { return r.json(); }); var ticksDuringStall = srv.host.state().tick - tick0;
ok('live driver: after a 3 s stall the remaining window reflects real elapsed time (≈ 7 s left) although only ' + ticksDuringStall + ' fixed ticks ran (monotonic wall clock: ' + dW.deadline_clock + ')', dW.deadline_clock === 'MONOTONIC_WALL' && ticksDuringStall < 20 && afterStall.session.reconnect_remaining_s <= 7.2 && afterStall.session.reconnect_remaining_s >= 6.0, { remaining: afterStall.session.reconnect_remaining_s, ticks: ticksDuringStall });
await new Promise(function (r) { setTimeout(r, 7500); }); var lateW = await post('/api/reconnect', { client_id: 'wB', session_id: cB.session_id, token: tk.PLAYER_B }); var health = await fetch(base + '/api/health').then(function (r) { return r.json(); }); var wallElapsed = (performance.now() - wall0) / 1000;
ok('live driver: reconnect after ' + wallElapsed.toFixed(1) + ' real seconds is refused (SESSION_EXPIRED), duel closed NO_CONTEST with no winner, although host simulation time advanced only ' + (health.t).toFixed(1) + ' s', !lateW.ok && lateW.reason === 'SESSION_EXPIRED' && health.duel === null && wallElapsed >= 10 && health.t < wallElapsed);
await srv.close(true);
function makeEnvelopeW(c, seq, action, payload) { return { protocol: 'MAHWORLD_LAB_1', session_id: c.session_id, client_id: c.client_id, command_id: c.client_id + '-' + seq, seq: seq, action: action, payload: payload || {} }; }
console.log('\n' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
