/* MAHWORLD :: RIG v5 HARD GATES (master convergence pass, brief §6 / §9 / §43 / §45)
     1. every joint node is translation-only (no scale, no rotation, no matrix) — bone rotation can never scale the limb
     2. BONE-LENGTH INVARIANCE: glenohumeral→elbow, elbow→wrist and the total chain are identical (1e-6) through 0/30/60/90/120/150/170° of
        elevation driven THROUGH the animator (scapular rhythm, twist carriers, correctives all active)
     3. MESH-LENGTH INVARIANCE: the skinned upper-arm surface (ring of vertices near the shoulder vs near the elbow, linear blend skinning
        reproduced here from the GLB weights) keeps its length within ±7 % and its mid-belly girth within ±12 % across the same ladder
     4. the split legs are wound OUTWARD (every triangle normal points away from its ring centre) — the inside-out loft was the real
        'cut / hollow leg' defect
     5. the corrective library and muscle morphs exist on the asset and the runtime-facing manifest lists them
   node 16_TESTS/gameplay_rig_v5_gates.test.mjs [--asset <glb>] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { createRigAnimator } from '../26_LOCAL_AUTHORITY/lab/RigAnimator.js';
import * as AD from '../26_LOCAL_AUTHORITY/lab/animData.js';
import { restFromGlb } from './lib/rest_from_glb.mjs';
import { readGlb } from '../26_LOCAL_AUTHORITY/deploy/glb_read.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; }
var ASSET = arg('--asset', path.join(HERE, '..', '26_LOCAL_AUTHORITY', 'lab', 'assets', 'athlete_m_preview', 'dev_0.14', 'Mah_Athlete_M_am08_v6.glb'));   /* PASS 4B: the faithful-leg derivative is the default; --asset points at any earlier generation */
var PROFILE = JSON.parse(fs.readFileSync(path.join(HERE, '..', '26_LOCAL_AUTHORITY', 'lab', 'rig_profile.json'), 'utf8'));
var DEFAULTS = JSON.parse(fs.readFileSync(path.join(HERE, '..', '26_LOCAL_AUTHORITY', 'lab', 'presentation_defaults.json'), 'utf8'));
var passed = 0, failed = 0; function ok(name, cond, info) { if (cond) { passed++; console.log('PASS ' + name); } else { failed++; console.log('FAIL ' + name + (info !== undefined ? ' — ' + JSON.stringify(info) : '')); } }
/* ---- minimal quaternion math (x,y,z,w) ---- */
function qMul(a, b) { return [a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1], a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0], a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3], a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2]]; }
function qFromEuler(x, y, z) { var c1 = Math.cos(x / 2), c2 = Math.cos(y / 2), c3 = Math.cos(z / 2), s1 = Math.sin(x / 2), s2 = Math.sin(y / 2), s3 = Math.sin(z / 2); return [s1 * c2 * c3 + c1 * s2 * s3, c1 * s2 * c3 - s1 * c2 * s3, c1 * c2 * s3 + s1 * s2 * c3, c1 * c2 * c3 - s1 * s2 * s3]; }
function qRot(q, v) { var x = v[0], y = v[1], z = v[2], qx = q[0], qy = q[1], qz = q[2], qw = q[3]; var ix = qw * x + qy * z - qz * y, iy = qw * y + qz * x - qx * z, iz = qw * z + qx * y - qy * x, iw = -qx * x - qy * y - qz * z; return [ix * qw + iw * -qx + iy * -qz - iz * -qy, iy * qw + iw * -qy + iz * -qx - ix * -qz, iz * qw + iw * -qz + ix * -qy - iy * -qx]; }
function Euler() { this.x = 0; this.y = 0; this.z = 0; } Euler.prototype.set = function (x, y, z) { this.x = x; this.y = y; this.z = z; return this; }; Euler.prototype.setFromQuaternion = function (q) { /* three.js XYZ extraction (matrix based) */ var x = q.x, y = q.y, z = q.z, w = q.w; var x2 = x + x, y2 = y + y, z2 = z + z; var xx = x * x2, xy = x * y2, xz = x * z2, yy = y * y2, yz = y * z2, zz = z * z2, wx = w * x2, wy = w * y2, wz = w * z2; var m11 = 1 - (yy + zz), m12 = xy - wz, m13 = xz + wy, m22 = 1 - (xx + zz), m23 = yz - wx, m32 = yz + wx, m33 = 1 - (xx + yy); this.y = Math.asin(Math.max(-1, Math.min(1, m13))); if (Math.abs(m13) < 0.9999999) { this.x = Math.atan2(-m23, m33); this.z = Math.atan2(-m12, m11); } else { this.x = Math.atan2(m32, m22); this.z = 0; } return this; };
function Quat() { this.x = 0; this.y = 0; this.z = 0; this.w = 1; } Quat.prototype.setFromEuler = function (e) { var q = qFromEuler(e.x, e.y, e.z); this.x = q[0]; this.y = q[1]; this.z = q[2]; this.w = q[3]; return this; }; Quat.prototype.slerp = function (q, t) { this.x += (q.x - this.x) * t; this.y += (q.y - this.y) * t; this.z += (q.z - this.z) * t; this.w += (q.w - this.w) * t; var l = Math.hypot(this.x, this.y, this.z, this.w) || 1; this.x /= l; this.y /= l; this.z /= l; this.w /= l; return this; };
Quat.prototype.set = function (x, y, z, w) { this.x = x; this.y = y; this.z = z; this.w = w; return this; }; Quat.prototype.copy = function (q) { this.x = q.x; this.y = q.y; this.z = q.z; this.w = q.w; return this; }; Quat.prototype.invert = function () { this.x = -this.x; this.y = -this.y; this.z = -this.z; return this; }; Quat.prototype.multiply = function (b) { var a = this; var r = qMul([a.x, a.y, a.z, a.w], [b.x, b.y, b.z, b.w]); this.x = r[0]; this.y = r[1]; this.z = r[2]; this.w = r[3]; return this; };
var THREE = { Euler: Euler, Quaternion: Quat };
/* ---- asset ---- */
var G = readGlb(ASSET); var J = G.json; var REST = restFromGlb(ASSET); var scale = REST.scale;
var nodesUsed = J.skins[0].joints.map(function (ni) { return J.nodes[ni]; });
ok('1. every joint is translation-only (no scale / rotation / matrix): bone rotation cannot scale the limb', nodesUsed.every(function (n) { return !n.scale && !n.rotation && !n.matrix; }), nodesUsed.filter(function (n) { return n.scale || n.rotation || n.matrix; }).map(function (n) { return n.name; }));
/* ---- animator + FK ---- */
function makeRig() { var bones = {}; AD.BONES.forEach(function (k) { if (!REST.bones[k]) return; var p = REST.bones[k]; bones[k] = { name: k, position: { x: p[0], y: p[1], z: p[2] }, quaternion: new Quat() }; }); return { bones: bones, scale: scale, seed: 0.3 }; }
function fk(pose) { var out = {}, rot = {}; REST.order.forEach(function (name) { var par = REST.parent[name], off = REST.bones[name] || [0, 0, 0], e = pose[name] || [0, 0, 0]; var pPos = (par && out[par]) || [0, 0, 0], pRot = (par && rot[par]) || [0, 0, 0, 1]; var moved = qRot(pRot, off); out[name] = [pPos[0] + moved[0], pPos[1] + moved[1], pPos[2] + moved[2]]; rot[name] = qMul(pRot, qFromEuler(e[0], e[1], e[2])); }); return { pos: out, rot: rot }; }
var A = createRigAnimator(THREE, makeRig(), { defaults: DEFAULTS, animData: AD, classId: 'ATHLETE', seed: 0.3, profile: PROFILE });
var view = { speed01: 0, speed_mps: 0, moving: false, form: 'FUSED', yaw: 0, host_t: 0 };
var LADDER = [0, 30, 60, 90, 120, 150, 170]; var runs = [];
LADDER.forEach(function (deg) { A.setOverride({ UPPERARM_L: [-0.05, 0, -deg * Math.PI / 180], FOREARM_L: [-0.1, 0, 0] }); for (var i = 0; i < 60; i++) { view.host_t += 1 / 60; A.animate(view, 1 / 60); } var p = A.pose(); var f = fk(p); runs.push({ deg: deg, pose: p, fk: f }); });
A.setOverride(null);
function dist(a, b) { return Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]); }
var lens = runs.map(function (r) { return { deg: r.deg, upper: dist(r.fk.pos.UPPERARM_L, r.fk.pos.FOREARM_L), fore: dist(r.fk.pos.FOREARM_L, r.fk.pos.HAND_L), chain: dist(r.fk.pos.UPPERARM_L, r.fk.pos.HAND_L), scap: r.pose.SCAP_L ? +r.pose.SCAP_L[2].toFixed(3) : null, gh: r.pose.UPPERARM_L ? +r.pose.UPPERARM_L[2].toFixed(3) : null }; });
var u0 = lens[0].upper, f0 = lens[0].fore;
ok('2. bone lengths are invariant through 0-170° elevation (GH→elbow, elbow→wrist)', lens.every(function (l) { return Math.abs(l.upper - u0) < 1e-6 && Math.abs(l.fore - f0) < 1e-6; }), lens.map(function (l) { return l.deg + ':' + l.upper.toFixed(4) + '/' + l.fore.toFixed(4); }));
ok('2b. the scapula visibly carries a share of the elevation (scapular rotation grows with the arm, humerus keeps the rest)', lens[0].scap !== null && Math.abs(lens[6].scap) > 0.3 && Math.abs(lens[3].scap) > 0.1 && Math.abs(lens[3].gh) < 1.57, lens.map(function (l) { return l.deg + ': scap ' + l.scap + ' gh ' + l.gh; }));
/* ---- 3. mesh-length invariance by LBS ---- */
var mesh = J.meshes[0], pr = mesh.primitives[0]; var P = G.acc(pr.attributes.POSITION).data, JI = G.acc(pr.attributes.JOINTS_0).data, WT = G.acc(pr.attributes.WEIGHTS_0).data; var N = P.length / 3;
var jointNames = J.skins[0].joints.map(function (ni) { return J.nodes[ni].name; }); var restWorld = REST.world;   /* metres */
function skin(f, i) { var out = [0, 0, 0]; var v = [P[i * 3] * scale, P[i * 3 + 1] * scale, P[i * 3 + 2] * scale]; for (var k = 0; k < 4; k++) { var w = WT[i * 4 + k]; if (w <= 0) continue; var name = jointNames[JI[i * 4 + k]]; var rw = restWorld[name], pw = f.pos[name], q = f.rot[name]; if (!rw || !pw) continue; var local = [v[0] - rw[0], v[1] - rw[1], v[2] - rw[2]]; var r = qRot(q, local); out[0] += w * (pw[0] + r[0]); out[1] += w * (pw[1] + r[1]); out[2] += w * (pw[2] + r[2]); } return out; }
var ghRest = restWorld.UPPERARM_L, elRest = restWorld.FOREARM_L, armAxis = [elRest[0] - ghRest[0], elRest[1] - ghRest[1], elRest[2] - ghRest[2]]; var armLen = Math.hypot(armAxis[0], armAxis[1], armAxis[2]); armAxis = armAxis.map(function (c) { return c / armLen; });
var armT = 0.1126 * scale; var ringTop = [], ringBot = [], belly = [];
for (var i = 0; i < N; i++) { var x = P[i * 3] * scale; if (x > -armT) continue; var vv = [x - ghRest[0], P[i * 3 + 1] * scale - ghRest[1], P[i * 3 + 2] * scale - ghRest[2]]; var along = vv[0] * armAxis[0] + vv[1] * armAxis[1] + vv[2] * armAxis[2]; var t = along / armLen; var rad = Math.sqrt(Math.max(0, vv[0] * vv[0] + vv[1] * vv[1] + vv[2] * vv[2] - along * along)); if (rad > 0.11) continue; var armW = 0; for (var kk = 0; kk < 4; kk++) if (/^(UPPERARM|FOREARM|ARMTWIST)_L/.test(jointNames[JI[i * 4 + kk]])) armW += WT[i * 4 + kk]; if (armW < 0.5) continue;   /* S10: the arm's own rings — ribcage-shell verts inside the same radius (left with the trunk by the axilla guard) are not arm girth */   /* the arm column only (the pec / lat skin beside the armpit is not the arm) */ if (t > 0.22 && t < 0.32) ringTop.push(i); if (t > 0.78 && t < 0.88) ringBot.push(i); if (t > 0.45 && t < 0.6) belly.push(i); }
function mean(idx, f) { var s = [0, 0, 0]; idx.forEach(function (i) { var p = skin(f, i); s[0] += p[0]; s[1] += p[1]; s[2] += p[2]; }); return s.map(function (c) { return c / Math.max(1, idx.length); }); }
function girth(idx, f) { var c = mean(idx, f); var s = 0; idx.forEach(function (i) { var p = skin(f, i); s += Math.hypot(p[0] - c[0], p[1] - c[1], p[2] - c[2]); }); return s / Math.max(1, idx.length); }
var meshLens = runs.map(function (r) { return { deg: r.deg, len: dist(mean(ringTop, r.fk), mean(ringBot, r.fk)), girth: girth(belly, r.fk) }; });
var L0 = meshLens[0].len, G0 = meshLens[0].girth;
ok('3. the skinned upper-arm surface keeps its length within ±7 % through the ladder (no shrink / stretch)', ringTop.length > 20 && ringBot.length > 20 && meshLens.every(function (m) { return Math.abs(m.len - L0) / L0 < 0.07; }), meshLens.map(function (m) { return m.deg + ':' + (100 * (m.len - L0) / L0).toFixed(1) + '%'; }));
ok('3b. the upper-arm belly keeps its girth within ±12 % (muscle volume identity through elevation)', belly.length > 30 && meshLens.every(function (m) { return Math.abs(m.girth - G0) / G0 < 0.12; }), meshLens.map(function (m) { return m.deg + ':' + (100 * (m.girth - G0) / G0).toFixed(1) + '%'; }));
/* ---- 4. split legs wound outward ---- */
var legs = J.meshes.find(function (m) { return /SPLIT_LEGS/.test(m.name); }); var lp = legs.primitives[0]; var LP = G.acc(lp.attributes.POSITION).data, LI = G.acc(lp.indices).data; var outward = 0, inward = 0;
/* ring centres: mean of the vertices of the same side within ±3 mm of each y (the loft is a stack of rings) */
var ringC = {}; for (var vi = 0; vi < LP.length / 3; vi++) { var key = (LP[vi * 3] < 0 ? 'L' : 'R') + ':' + (Math.round(LP[vi * 3 + 1] / 0.003)); var rc = ringC[key] || (ringC[key] = [0, 0, 0, 0]); rc[0] += LP[vi * 3]; rc[1] += LP[vi * 3 + 1]; rc[2] += LP[vi * 3 + 2]; rc[3]++; }
var LEGCX = (function () { try { var mf = JSON.parse(fs.readFileSync(path.join(path.dirname(ASSET), 'manifest.json'), 'utf8')); return Math.abs((mf.split && mf.split.leg_centres_x || [0.0568])[0]); } catch (e) { return 0.0568; } })();   /* S13: the leg centre is the manifest's, not a constant */
function centreAt(x, y) { var rc = ringC[(x < 0 ? 'L' : 'R') + ':' + Math.round(y / 0.003)]; return rc ? [rc[0] / rc[3], rc[1] / rc[3], rc[2] / rc[3]] : [x < 0 ? -LEGCX : LEGCX, y, 0.01]; }
for (var t3 = 0; t3 < LI.length; t3 += 3) { var a = LI[t3], b = LI[t3 + 1], c = LI[t3 + 2]; var ax = LP[a * 3], ay = LP[a * 3 + 1], az = LP[a * 3 + 2], bx = LP[b * 3], by = LP[b * 3 + 1], bz = LP[b * 3 + 2], cx = LP[c * 3], cy = LP[c * 3 + 1], cz = LP[c * 3 + 2]; var ux = bx - ax, uy = by - ay, uz = bz - az, vx = cx - ax, vy = cy - ay, vz = cz - az; var nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx; var mx = (ax + bx + cx) / 3, my = (ay + by + cy) / 3, mz = (az + bz + cz) / 3; var cc = centreAt(mx, my); var dx = mx - cc[0], dz = mz - cc[2]; var d = Math.hypot(dx, dz) > 0.002 ? dx * nx + dz * nz : (my > 0.3 ? ny : -ny); if (d >= 0) outward++; else inward++; }
/* PASS 4B: the ring-centre heuristic assumed a loft; the faithful legs are the source's own triangles, so the gate now checks what actually matters for FrontSide rendering — the geometric winding agrees with the stored (outward) normals and each closed leg has a positive signed volume */
var LN = G.acc(lp.attributes.NORMAL).data; var agree = 0, disagree = 0, vol = 0; for (var t4 = 0; t4 < LI.length; t4 += 3) { var a4 = LI[t4], b4 = LI[t4 + 1], c4 = LI[t4 + 2]; var ux4 = LP[b4 * 3] - LP[a4 * 3], uy4 = LP[b4 * 3 + 1] - LP[a4 * 3 + 1], uz4 = LP[b4 * 3 + 2] - LP[a4 * 3 + 2], vx4 = LP[c4 * 3] - LP[a4 * 3], vy4 = LP[c4 * 3 + 1] - LP[a4 * 3 + 1], vz4 = LP[c4 * 3 + 2] - LP[a4 * 3 + 2]; var nx4 = uy4 * vz4 - uz4 * vy4, ny4 = uz4 * vx4 - ux4 * vz4, nz4 = ux4 * vy4 - uy4 * vx4; var sx = LN[a4 * 3] + LN[b4 * 3] + LN[c4 * 3], sy = LN[a4 * 3 + 1] + LN[b4 * 3 + 1] + LN[c4 * 3 + 1], sz = LN[a4 * 3 + 2] + LN[b4 * 3 + 2] + LN[c4 * 3 + 2]; if (nx4 * sx + ny4 * sy + nz4 * sz >= 0) agree++; else disagree++; vol += (LP[a4 * 3] * (LP[b4 * 3 + 1] * LP[c4 * 3 + 2] - LP[b4 * 3 + 2] * LP[c4 * 3 + 1]) - LP[a4 * 3 + 1] * (LP[b4 * 3] * LP[c4 * 3 + 2] - LP[b4 * 3 + 2] * LP[c4 * 3]) + LP[a4 * 3 + 2] * (LP[b4 * 3] * LP[c4 * 3 + 1] - LP[b4 * 3 + 1] * LP[c4 * 3])) / 6; }
ok('4. split legs are wound outward (FrontSide renders the near wall; no hollow / cut legs): geometric winding agrees with the stored outward normals on ≥ 98 % of triangles and the closed legs have a positive signed volume', agree / (agree + disagree) >= 0.98 && vol > 0, { agree: agree, disagree: disagree, signed_volume: +vol.toFixed(6), ring_heuristic: { outward: outward, inward: inward } });
/* ---- 5. morph library ---- */
var names = mesh.extras && mesh.extras.targetNames || []; var need = ['SH45_L', 'SH90_L', 'SH120_L', 'SH150_L', 'SH45_R', 'SH150_R', 'BICEPS_L', 'DELTOID_R', 'LAT_L', 'PEC_R', 'ABS', 'TRAP'];
ok('5. corrective library + muscle morphs exist on the asset', need.every(function (n) { return names.indexOf(n) >= 0; }), { missing: need.filter(function (n) { return names.indexOf(n) < 0; }), count: names.length });
var mf = JSON.parse(fs.readFileSync(path.join(path.dirname(ASSET), 'manifest.json'), 'utf8'));
ok('5b. manifest declares the v5 chain (SCAP / twist / LUMBAR / SPINE2) and the glenohumeral measurement', /SCAP/.test(mf.rig_chain || '') && mf.glenohumeral && mf.glenohumeral.L && mf.joints.indexOf('SCAP_L') >= 0 && mf.joints.indexOf('LUMBAR') >= 0, { chain: mf.rig_chain });
console.log('RESULT rig v5 gates: ' + passed + ' passed, ' + failed + ' failed'); process.exit(failed ? 1 : 0);
