/* Astra M3 acceptance: one real NIGHT-first route from the civic forecourt through the Titan road/forest/resource/pond/pass to MAH MATCH.
   Registry + shared world-layout checks; no browser, package, or publish.  node 16_TESTS/gameplay_m3_night_route.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { fileURLToPath } from 'node:url';
import { groundYAt, worldColliders } from '../26_LOCAL_AUTHORITY/lab/world/worldLayout.js';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var ROOT = path.join(HERE, '..');
var REG_PATH = path.join(ROOT, '26_LOCAL_AUTHORITY', 'lab', 'assets', 'world', 'world_registry_v1.json'); var RAW = fs.readFileSync(REG_PATH, 'utf8'); var R = JSON.parse(RAW);
var COLL = JSON.parse(fs.readFileSync(path.join(ROOT, '26_LOCAL_AUTHORITY', 'play', 'rules1723', 'world_v1_colliders.json'), 'utf8'));
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail === undefined ? '' : ' — ' + JSON.stringify(detail))); } }
var QR = R.quality_routes && R.quality_routes.list.filter(function (q) { return q.id === R.quality_routes.default; })[0]; var stage = function (id) { return QR && QR.stages.filter(function (s) { return s.id === id; })[0]; };

ok('1. first visit and route preview are NIGHT, while DAY/NIGHT are both declared for prewarm', R.sky.time_of_day.default === 'NIGHT' && R.sky.time_of_day.preview === 'NIGHT' && R.sky.time_of_day.states.join('|') === 'DAY|NIGHT' && R.sky.time_of_day.prewarm.join('|') === 'DAY|NIGHT', R.sky.time_of_day);
ok('2. the default quality route has the seven required standards in order and is not a replacement world', QR && QR.stages.map(function (s) { return s.standard; }).join('|') === 'FLOOR|ROAD|FOREST_RESOURCE|POND|MOUNTAIN|BUILDING|SKY' && /real rendered paths/.test(R.quality_routes._doc), QR && QR.stages);
var paths = new Map(R.paths.list.map(function (p) { return [p.id, p]; }));
ok('3. every route path id is a named, rendered registry road and the map overlay starts/ends at the real route endpoints', QR.path_ids.every(function (id) { var p = paths.get(id); return p && p.name && p.pts.length >= 2; }) && QR.map_polyline[0][0] === QR.start.x && QR.map_polyline[0][1] === QR.start.z && QR.map_polyline.slice(-1)[0][0] === QR.finish.x && QR.map_polyline.slice(-1)[0][1] === QR.finish.z, QR.path_ids);
var forest = R.zones.filter(function (z) { return z.id === stage('FOREST_RESOURCE').zone; })[0], bush = R.resource_patches.list.filter(function (b) { return b.id === stage('FOREST_RESOURCE').resource; })[0];
ok('4. the route forest stage is inside the live FOREST_NE habitat and its attackable resource patch is on the visible verge', forest && forest.kind === 'FOREST' && forest.habitat === 'DOGKIE' && bush && bush.family === 'blue' && Math.hypot(bush.x - stage('FOREST_RESOURCE').at[0], bush.z - stage('FOREST_RESOURCE').at[1]) < 14, { forest: forest && forest.id, bush: bush, stage: stage('FOREST_RESOURCE') });
var pond = R.water.rivers.filter(function (w) { return w.id === stage('POND').water; })[0], fishBody = R.ecology.species.FISH.habitat.bodies.filter(function (b) { return b.id === stage('POND').water; })[0];
ok('5. TITAN_LAKE is a four-shore walkable pond with a wade bed and fish population', pond && pond.pond && pond.shore_w >= 4 && pond.wade_y < pond.surface_y && fishBody && fishBody.sanctuary === 'TITAN_SANCTUARY', { pond: pond, fish: fishBody });
var T = R.terraces.list.filter(function (t) { return t.id === stage('MOUNTAIN_PASS').terrace; })[0], titan = R.regions.list.filter(function (q) { return q.id === 'TITAN_SANCTUARY'; })[0]; var walls = titan.monoliths.filter(function (m) { return m.pass_wall === 'TITAN_MOON_PASS'; });
ok('6. TITAN MOON PASS is real elevated ground with two walkable approaches and four collision-backed mountain walls', T && T.h === 2.8 && T.ramps.map(function (r) { return r.side; }).sort().join('|') === 'N|S' && walls.length === 4, { terrace: T, walls: walls });
ok('7. shared client/host ground math produces level pass top and monotonic north/south ramps', groundYAt(R, 150, 62) === 2.8 && groundYAt(R, 150, 43) > 0 && groundYAt(R, 150, 43) < 2.8 && groundYAt(R, 150, 79) > 0 && groundYAt(R, 150, 79) < 2.8 && groundYAt(R, 150, 36) === 0 && groundYAt(R, 150, 86) === 0, [groundYAt(R, 150, 43), groundYAt(R, 150, 62), groundYAt(R, 150, 79)]);
var generated = worldColliders(R, []), passShapes = generated.filter(function (s) { return s.zone === 'TITAN_MOON_PASS'; });
function blocks(s, x, z, rad) { if (s.walkable || s.type === 'RAMP') return false; if (s.type === 'CYLINDER') return Math.hypot(x - s.x, z - s.z) < s.r + rad; if (s.type === 'BOX') return x >= s.x1 - rad && x <= s.x2 + rad && z >= s.z1 - rad && z <= s.z2 + rad; return false; }
var centerClear = true; for (var z = 38; z <= 84; z += 0.5) if (generated.some(function (s) { return blocks(s, 150, z, 0.4); })) centerClear = false;
ok('8. generated host geometry has pass top/lips/ramps and a clear body-width road centre from approach to descent', passShapes.some(function (s) { return s.id === 'TITAN_MOON_PASS_TOP' && s.walkable; }) && passShapes.filter(function (s) { return s.type === 'RAMP'; }).length === 2 && passShapes.filter(function (s) { return /LIP/.test(s.id); }).length === 2 && centerClear, passShapes);
var B = R.buildings.list.filter(function (b) { return b.id === QR.finish.building; })[0], I = R.interactables_added.filter(function (i) { return i.id === QR.finish.door; })[0], room = R.rooms_added[QR.finish.interior];
ok('9. the route finishes at the named real MAH MATCH door and its bespoke enterable/exit-capable hall', B && B.name === 'MAH MATCH' && !B.open_air && B.interior === 'MATCH_HALL' && I && I.kind === 'ENTER' && I.to.room === 'MATCH_HALL' && room && room.interior && room.exit.to === 'FIELD', { building: B, interactable: I, room: room && room.label });
var sha = crypto.createHash('sha256').update(RAW).digest('hex');
ok('10. generated host world colliders are synchronized to this exact route registry', COLL.registry_sha256 === sha && COLL.shapes.some(function (s) { return s.id === 'TITAN_MOON_PASS_TOP'; }) && COLL.shapes.filter(function (s) { return /^TITAN_SANCTUARY_MONOLITH(?:6|7|8|9)$/.test(s.id); }).length === 4, { expected: sha, actual: COLL.registry_sha256, shapes: COLL.counts });
var fieldSrc = fs.readFileSync(path.join(ROOT, '26_LOCAL_AUTHORITY', 'lab', 'fieldScene.js'), 'utf8'), playSrc = fs.readFileSync(path.join(ROOT, '26_LOCAL_AUTHORITY', 'lab', 'play.js'), 'utf8');
ok('11. runtime first-visit fallback is NIGHT and the warm gate compiles DAY then NIGHT without persisting the transient switches', /return true; \}\)\(\);\s*\n\s*var TIME_STATE/.test(fieldSrc) && /\[false, true\]\.forEach/.test(fieldSrc) && /persist: false/.test(fieldSrc) && /prewarmTimeStates\(renderer, camera\)/.test(playSrc), null);
var way = R.paths.wayfinders || [];
ok('12. the new forest/lake and range/pass junctions are discoverable through generated wayfinders', way.some(function (w) { return w.legs.some(function (l) { return l.route === 'RP_TITAN_WILDWAY'; }); }) && way.some(function (w) { return w.legs.some(function (l) { return l.route === 'RP_RANGE_TO_PASS' || (l.route === 'RP_EAST_LINK' && l.name === 'MATCH DISTRICT'); }); }), way.map(function (w) { return w.legs.map(function (l) { return l.route + ':' + l.name; }); }));
ok('13. NIGHT-first boot still creates the DAY environment as PMREM/CubeUV so late materials do not compile a raw-cube shader on the first live switch', /pmremSky\(false\)/.test(fieldSrc) && !/!NIGHT\s*&&\s*RENDERER\s*&&\s*THREE\.PMREMGenerator/.test(fieldSrc), null);

console.log('RESULT M3 night route: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
