/* OWNER INTERJECTION 2026-09-18 phase D: the ONE speed-driven flight-lean curve (hover 6° → normal 24° → boost 40°, pelvis-led at boost, arms swept
   clear, legs / taper trailing, camera never coupled) and the HINGE reauthored as a surface-supported hip hinge (femurs ~45°, shins vertical, hips back
   through a planted-feet root offset, neutral spine, hip-drive release to chest height, MAHGIC hurled from the hip drive, airborne pike).
   Source contracts + the tracked page evidence (deploy/probe_hinge_flight.mjs).   node 16_TESTS/gameplay_motion_phase_d.test.mjs */
import fs from 'node:fs';
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var LA = new URL('../26_LOCAL_AUTHORITY/', import.meta.url); function read(rel) { return fs.readFileSync(new URL(rel, LA), 'utf8'); }
var anim = read('lab/RigAnimator.js'), adapter = read('lab/PresentationAdapter.js'), defs = JSON.parse(read('lab/presentation_defaults.json'));
var FL = defs.flight && defs.flight.lean; var HN = defs.hinge;
ok('§7 ONE centralized flight-lean curve in presentation_defaults over x = speed / the form\'s cruise speed: hover 6°, normal (x 1) 24°, boost (x 1.3) 40°; distributions, arm sweep, leg / taper trail and head counter live next to it — nothing numeric in code', !!FL && JSON.stringify(FL.curve_x_deg) === '[[0,6],[1,24],[1.3,40]]' && FL.cruise_mps_fallback && FL.cruise_mps_fallback.SPLIT === 7.71 && FL.cruise_mps_fallback.FUSED === 20.56 && FL.distribution_boost.PELVIS > FL.distribution_cruise.PELVIS && FL.arm_trail_rad[1] >= 0.6 && FL.arm_trail_rad[1] <= 0.70 && /shoulder table/.test(FL._arm_note || '') && FL.leg_trail_rad >= 0.5 && FL.tail2_rad[1] > FL.tail2_rad[0] && typeof FL.head_counter === 'number', FL);
ok('§7 the animator reads the curve through leanDeg / leanL and drives EVERY flight channel from it (inclination, pelvis-led distribution, arm sweep + outward opening, TAIL2, leg trail, knee shape, tuck fade); LEAN_FLIGHT is only the fallback', /function leanDeg\(s\) \{ var c = LEAN_CURVE;/.test(anim) && /function leanL\(s\) \{/.test(anim) && /var fxNow = fly \? flyX\(speedMps\) : 0;/.test(anim) && /if \(fly\) \{ var fx = fxNow; var fs = leanL\(fx\); var incl = leanDeg\(fx\) \* DEG;/.test(anim)   /* re-pinned 2026-09-20: the P2 flight brake hoists fx (fxNow) before the fly block so the brake envelope shares it — the lean still reads the ONE curve */ && /var flyX = function \(sMps\) \{ var cr = \(v\.fly_cruise && v\.fly_cruise > 0\.5\) \? v\.fly_cruise : \(\(\(FLN\.cruise_mps_fallback \|\| \{\}\)\[split \? 'SPLIT' : 'FUSED'\]\) \|\| 7\.71\); return sMps \/ cr; \};/.test(anim) && /set\('THIGH_L', 0\.16 \* \(1 - fs\) \+ legTrail, 0, 0\.04 \* fs\);/.test(anim) && /var shareOf = function \(k, dflt\)/.test(anim) && /var ATR = FLN\.arm_trail_rad \|\| \[TRAIL\[1\], TRAIL\[1\] \+ 0\.35\]; var fa = \(ATR\[0\] \+ \(ATR\[1\] - ATR\[0\]\) \* fs\) \* st\.flyArmK;/.test(anim) && /\(FLN\.arm_open_rad \|\| 0\.14\) - bank \* 0\.5/.test(anim) && /var T2R = FLN\.tail2_rad \|\| \[0\.05, 0\.15\]; set\('TAIL2', -\(T2R\[0\] \+ \(T2R\[1\] - T2R\[0\]\) \* fs\)\);/.test(anim) && /var legTrail = \(FLN\.leg_trail_rad \|\| DF\.leg_trail_rad \|\| 0\.42\) \* fs, kneeShape = \(FLN\.knee_shape_rad \|\| DF\.knee_shape_rad \|\| 0\.34\) \* fs;/.test(anim) && /var fsA = fly \? leanL\(flyX\(speedMps\)\) : 0;/.test(anim) && /flightLean: function \(s\)/.test(anim));
ok('§7 the camera is never coupled to the lean: no camera code reads the animator pose / lean (play.js camera follows the host position through its stable target)', !/flightLean|leanDeg|rootOffset/.test(read('lab/play.js')));
var host = read('play/PlayMode.js'); var tuning = JSON.parse(fs.readFileSync(new URL('../00_CORE/dev_tuning.dev.json', import.meta.url), 'utf8'));
ok('§7 host: `+` (fast) in POWERED flight = BOOST = cruise × boost_factor (dev_tuning flight.boost_factor 1.3, PROVISIONAL, one number); the snapshot publishes the form\'s cruise speed + the factor (the client normalizes its curve by it); ground travel unchanged', /if \(a\.fl\.powered\) spd = canonBand\.max \* \(T\.flight\.air_speed_factor \|\| 1\.15\) \* \(\(v\.run \|\| v\.fast\) \? \(T\.flight\.boost_factor \|\| 1\) : 1\);/.test(host) && /cruise_mps: \+\(cfg\.speedRangeMps\(a\.world\.loco\.form\(\), 'FORWARD'\)\.max \* \(T\.flight\.air_speed_factor \|\| 1\.15\)\)\.toFixed\(2\), boost_factor: T\.flight\.boost_factor \|\| 1,/.test(host) && tuning.local_authority.play.flight.boost_factor === 1.3 && /PROVISIONAL/.test(tuning.local_authority.play.flight._doc_boost) && /fly_cruise: v\.flight && v\.flight\.cruise_mps \? v\.flight\.cruise_mps : null,/.test(adapter));
ok('§8 hinge numbers centralized (presentation_defaults.hinge) — re-pinned to the owner JOB A decision of 2026-09-19 (checkpoint A2): split RDL torso 0.80 + femur 0.60 rad (the ~45° femur, hip table relaxed to 90°), neutral spine 0.05, arms hang 0.85, the FUSED trunk hinge keeps 0.66 / 0.60, release arm −1.25 (chest height, never overhead), airborne pike 0.95 flexion', !!HN && HN.femur_rad === 0.6 && HN.torso_rad === 0.8 && HN.femur_rad + HN.torso_rad <= 1.58 && HN.spine_neutral_rad === 0.05 && HN.arm_hang_rad === 0.85 && HN.torso_fused_rad === 0.66 && HN.arm_hang_fused_rad === 0.6 && HN.release_arm_rad === -1.25 && HN.airborne && HN.airborne.pike_thigh_flex_rad === 0.95 && /owner JOB A directive 2026-09-19/.test(HN._doc), HN);
ok('§8 the HINGE pose is the surface-supported hinge: exact targets divided by the exaggeration X, shins = femurs (vertical shins), a neutral spine, eyes forward, arms hanging; the release drives to a tall lockout with the arms to chest height; airborne = a pike, never a planted stance', /else if \(pat === 'HINGE'\) \{ var HN = \(D\.hinge \|\| \{\}\);/.test(anim) && /set\('THIGH_L', -\(\(fem \+ tor\) \/ X\) \* qh\); set\('THIGH_R', -\(\(fem \+ tor\) \/ X\) \* qh\); set\('SHIN_L', \(fem \/ X\) \* qh\); set\('SHIN_R', \(fem \/ X\) \* qh\);/.test(anim) && /set\('SPINE', \(spn \/ X\) \* qh\); set\('CHEST', \(spn \* 0\.6 \/ X\) \* qh\); set\('HEAD', -\(0\.36 \/ X\) \* qh\);/.test(anim) && /set\('UPPERARM_L', -\(hang \/ X\) \* qh, 0, 0\.16\)/.test(anim) && /set\('UPPERARM_L', \(relArm \/ X\) \* ra \* amp, 0, 0\.22 \* ra\)/.test(anim) && /var qh = startup \? qa : qa \* \(1 - whip\);/.test(anim) && /else \{ set\('PELVIS', \(\(HA\.pike_pelvis_rad \|\| 0\.55\) \/ X\) \* qh \* amp\);/.test(anim) && /set\('THIGH_L', -\(\(HA\.pike_thigh_flex_rad \|\| 0\.95\) \/ X\) \* qh\)/.test(anim) && !/set\('PELVIS', 0\.30 \* qa \* amp\); set\('SPINE', 0\.32 \* qa \* amp\)/.test(anim) && !/UPPERARM_L', -1\.70 \* ra \* amp/.test(anim));
ok('§8 planted feet: the animator computes the root offset from THIS rig\'s thigh / shin lengths and the composed hip / knee flexion (split, standing, grounded), exposes rootOffset(); the adapter moves the figure root (y down, z back) and drops its old settle-back for the split hinge; the fused hinge keeps the taper as the base', /var roT = \{ y: 0, z: 0 \}; if \(st\.showLegs && !st\.airborne && !st\.transformState && speed01 < 0\.15 && E\.PELVIS && E\.THIGH_L && E\.THIGH_R && E\.SHIN_L && E\.SHIN_R\) \{ var thR = -\(E\.PELVIS\.x \+ 0\.5 \* \(E\.THIGH_L\.x \+ E\.THIGH_R\.x\)\), shR = 0\.5 \* \(E\.SHIN_L\.x \+ E\.SHIN_R\.x\);/.test(anim) && /var LtP = SEG\.thigh \* SC, LsP = SEG\.shin \* SC, saP = thR - shR;/.test(anim) && /roT\.y = -Math\.max\(0, \(LtP \+ LsP \+ LtipM\) - LtP \* Math\.cos\(thR\) - LsP \* Math\.cos\(saP\) - LtipM \* Math\.cos\(tipA\)\); roT\.z = LtP \* Math\.sin\(thR\) \+ LsP \* Math\.sin\(saP\) \+ LtipM \* Math\.sin\(tipA\);/.test(anim) && /rootOffset: function \(\) \{ return st\.rootOff \|\| \{ y: 0, z: 0 \}; \}/.test(anim) && /var roF = f\.animator\.rootOffset \? f\.animator\.rootOffset\(\) : null; if \(roF && \(roF\.y \|\| roF\.z\)\) \{ f\.group\.position\.y \+= roF\.y; f\.group\.position\.z \+= roF\.z; \}/.test(adapter) && /var roA = f\.animator\.rootOffset \? f\.animator\.rootOffset\(\) : null; var pfH = \(roA && \(Math\.abs\(roA\.z\) > 0\.02 \|\| Math\.abs\(roA\.y\) > 0\.02\)\) \? 0 : 1;/.test(adapter) && /else if \(arc\.pat === 'HINGE'\) \{ dx = -0\.16 \* L \* pfH \+ 0\.30 \* R; dy2 = -0\.08 \* L \* pfH \+ 0\.14 \* R; \}/.test(adapter) && /else if \(arc\.pat === 'SQUAT'\) \{ dx = 0\.05 \* R; dy2 = -0\.26 \* L \* pfH \+ 0\.20 \* R; \}/.test(adapter) && /set\('THIGH_L', -0\.52 \* qa\); set\('THIGH_R', -0\.52 \* qa\); set\('SHIN_L', 0\.85 \* qa\)/.test(anim) && /set\('TAIL1', -\(tor \* 0\.75 \/ X\) \* qh\); set\('TAIL2', -\(tor \* 0\.25 \/ X\) \* qh\);/.test(anim));
ok('§8 MAHGIC hurled from the hip drive: the PHYSICAL-MAHGIC hinge gathers at the hips (PELVIS ↔ TAIL1) through the load and runs pelvis → hand on the drive; every other physical-MAHGIC strike keeps the hand → forearm gather', /var hingeG = \/HINGE\/\.test\(String\(at\.attack_id \|\| ''\)\), loadG = \/CONCENTRIC\|STARTUP\/\.test\(at\.state\); var hw = handWorld\(e, hingeG && loadG \? 'PELVIS' : 'HAND_R', DV1\), ew = handWorld\(e, hingeG \? \(loadG \? 'TAIL1' : 'PELVIS'\) : 'FOREARM_R', DV2\);/.test(adapter));
/* the numbers: the planted-feet geometry for the authored hinge (thigh 45°, shin vertical) — hips back ≈ thigh·sin45, down ≈ thigh·(1 − cos45): a real hinge, not a floating leg */
var th = 0.58, Lt = 0.44, Ls = 0.53; var back = Lt * Math.sin(th) + Ls * Math.sin(th - th), down = (Lt + Ls) - Lt * Math.cos(th) - Ls * Math.cos(0);
ok('§8 geometry check of the authored targets (thigh 0.44 m, shin 0.53 m, femur 0.58 rad forward in the world, shin vertical): hips ≈ 0.24 m back and ≈ 0.07 m down — the amount the root offset supplies', Math.abs(back - 0.241) < 0.01 && Math.abs(down - 0.073) < 0.01, { back: back, down: down });
/* tracked page evidence */
var rec = null; try { rec = JSON.parse(fs.readFileSync(new URL('../25_HANDOFF/CONVERGENCE/motion_d/probe_hinge_flight.json', import.meta.url), 'utf8')); } catch (e) { }
ok('phase D page probe record exists and passed (hinge fused / split / airborne, flight hover / normal / boost in both forms, hand clearance, camera decoupled)', !!rec && rec.fail === 0 && rec.pass >= 12, rec ? { pass: rec.pass, fail: rec.fail, fails: rec.checks.filter(function (l) { return /^FAIL/.test(l); }).slice(0, 3) } : 'missing');
if (rec && rec.flight && rec.flight.split) { var F = rec.flight.split; var DEG = Math.PI / 180; ok('phase D measured flight lean (split): hover ' + (F.hover && (F.hover.lean / DEG).toFixed(1)) + '°, normal ' + (F.cruise && (F.cruise.lean / DEG).toFixed(1)) + '° @ ' + (F.cruise && F.cruise.speed && F.cruise.speed.toFixed(1)) + ' m/s, boost ' + (F.boost && (F.boost.lean / DEG).toFixed(1)) + '° @ ' + (F.boost && F.boost.speed && F.boost.speed.toFixed(1)) + ' m/s — stronger than the old 8–18°', F.cruise && F.boost && F.cruise.lean / DEG > 18 && F.boost.lean / DEG > 30, F); }
console.log('RESULT MOTION PHASE D: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
