/* CONVERGENCE PASS 4B — FAITHFUL SEPARATED LEGS (O6 / G32–G35): provenance and identity contracts straight out of the GLBs, plus the runtime
   default and the tracked page evidence (deploy/probe_legs.mjs). node 16_TESTS/gameplay_legs_faithful.test.mjs [--asset <glb>] [--src <source glb>] */
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { fileURLToPath } from 'node:url';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; }
var ASSET = arg('--asset', path.join(HERE, '..', '26_LOCAL_AUTHORITY', 'lab', 'assets', 'athlete_m_preview', 'dev_0.14', 'Mah_Athlete_M_am08_v6.glb'));
var SRC = arg('--src', path.join(HERE, '..', '..', 'RAW_10_MODELS', 'Mah_Athlete_M.glb'));
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
function loadGlb(file) { var glb = fs.readFileSync(file); var jl = glb.readUInt32LE(12), j = JSON.parse(glb.slice(20, 20 + jl).toString('utf8')); var bin = glb.slice(28 + jl, 28 + jl + glb.readUInt32LE(20 + jl));
  function acc(ai) { var a = j.accessors[ai], bv = j.bufferViews[a.bufferView], off = (bv.byteOffset || 0) + (a.byteOffset || 0); var n = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4, MAT4: 16 }[a.type]; var C = { 5126: Float32Array, 5125: Uint32Array, 5123: Uint16Array, 5121: Uint8Array }[a.componentType]; return new C(bin.buffer.slice(bin.byteOffset + off, bin.byteOffset + off + a.count * n * C.BYTES_PER_ELEMENT)); }
  return { json: j, acc: acc, bytes: glb }; }
var S = loadGlb(SRC), D = loadGlb(ASSET); var sp = S.json.meshes[0].primitives[0]; var SP = S.acc(sp.attributes.POSITION), SUV = S.acc(sp.attributes.TEXCOORD_0), SI = S.acc(sp.indices); var SN = SP.length / 3;
var mf = JSON.parse(fs.readFileSync(path.join(path.dirname(ASSET), 'manifest.json'), 'utf8'));
/* ---- G32: the canonical fused geometry is unchanged — the body mesh's positions ARE the source's (plus one crotch-cap centroid) ---- */
var body = D.json.meshes[0]; var bp = body.primitives[0]; var BP = D.acc(bp.attributes.POSITION), BUV = D.acc(bp.attributes.TEXCOORD_0); var BN = BP.length / 3;
var maxDev = 0; for (var i = 0; i < SN; i++) { var d = Math.max(Math.abs(BP[i * 3] - SP[i * 3]), Math.abs(BP[i * 3 + 1] - SP[i * 3 + 1]), Math.abs(BP[i * 3 + 2] - SP[i * 3 + 2])); if (d > maxDev) maxDev = d; }
var uvDev = 0; for (var u = 0; u < SN; u++) { var du = Math.max(Math.abs(BUV[u * 2] - SUV[u * 2]), Math.abs(BUV[u * 2 + 1] - SUV[u * 2 + 1])); if (du > uvDev) uvDev = du; }
/* the derivative's extra body vertices are the S10 axilla unweld patches (inner-arm / lat lofts hidden 3–4 mm inside the surface, an earlier approved runtime-only step shared with dev_0.12 / dev_0.13) plus one crotch-cap centroid — none of them below the crotch line, i.e. the lower body that the legs derive from is exactly the source */
var crotchY = minY0() + (mf.split && mf.split.crotch_h || 0.4) * (maxY0() - minY0()); function minY0() { var m = Infinity; for (var q = 0; q < SN; q++) m = Math.min(m, SP[q * 3 + 1]); return m; } function maxY0() { var m = -Infinity; for (var q = 0; q < SN; q++) m = Math.max(m, SP[q * 3 + 1]); return m; }
var extraBelowCrotch = 0; for (var e0 = SN; e0 < BN; e0++) if (BP[e0 * 3 + 1] < crotchY - 1e-6) extraBelowCrotch++;
ok('G32 the fused body keeps the source geometry vertex-for-vertex (' + SN + ' source verts byte-identical: max |Δpos| = ' + maxDev.toExponential(2) + ', max |Δuv| = ' + uvDev.toExponential(2) + '); the ' + (BN - SN) + ' extra vertices are the S10 axilla patches + the crotch cap, none below the crotch line', maxDev < 1e-6 && uvDev < 1e-6 && extraBelowCrotch <= 1, { source_verts: SN, body_verts: BN, max_pos_dev: maxDev, max_uv_dev: uvDev, extra_below_crotch: extraBelowCrotch });
ok('G32 provenance: the manifest names the source file and its sha256, and the source on disk still has that hash', mf.source && mf.source.file === 'Mah_Athlete_M.glb' && /^[0-9a-f]{64}$/.test(mf.source.sha256) && crypto.createHash('sha256').update(S.bytes).digest('hex') === mf.source.sha256, mf.source);
/* ---- the split legs: lateral walls are the source's own triangles ---- */
var legs = D.json.meshes.filter(function (m) { return /SPLIT_LEGS/.test(m.name); })[0]; ok('the split-leg mesh exists with the PACKED morph and the six leg joints in the manifest', !!legs && legs.primitives[0].targets && legs.primitives[0].targets.length === 1 && mf.split && mf.split.packed_morph === 'PACKED' && mf.split.leg_bones.length === 6, mf.split && mf.split.leg_bones);
var lp = legs.primitives[0]; var LP = D.acc(lp.attributes.POSITION), LUV = D.acc(lp.attributes.TEXCOORD_0), LI = D.acc(lp.indices), LD = D.acc(lp.targets[0].POSITION); var LN = LP.length / 3;
ok('the manifest records the derivative identity honestly (FAITHFUL method, never a claim of the original mesh id)', /FAITHFUL/.test(mf.split.method) && /own triangles/i.test(mf.split.method) && legs.name !== S.json.meshes[0].name && /faithful/.test(mf.limitations.join(' ')), { legs_mesh: legs.name, method: (mf.split.method || '').slice(0, 120) });
/* packed = source: every leg vertex whose packed position (pos + delta) is off the sagittal plane must coincide with a source vertex or lie on a source edge cut by x = 0 */
var srcKey = new Map(); for (var s2 = 0; s2 < SN; s2++) srcKey.set(Math.round(SP[s2 * 3] * 1e5) + '_' + Math.round(SP[s2 * 3 + 1] * 1e5) + '_' + Math.round(SP[s2 * 3 + 2] * 1e5), s2);
var lateral = 0, onSource = 0, onSeam = 0, medial = 0, apex = 0, packedOffPlaneMedial = 0; var minY = Infinity, maxY = -Infinity; for (var q = 0; q < SN; q++) { minY = Math.min(minY, SP[q * 3 + 1]); maxY = Math.max(maxY, SP[q * 3 + 1]); } var H = maxY - minY;
for (var v = 0; v < LN; v++) { var px = LP[v * 3] + LD[v * 3], py = LP[v * 3 + 1] + LD[v * 3 + 1], pz = LP[v * 3 + 2] + LD[v * 3 + 2]; var key = Math.round(px * 1e5) + '_' + Math.round(py * 1e5) + '_' + Math.round(pz * 1e5);
  if (Math.abs(px) < 1e-6) { onSeam++; continue; }   /* seam vertices (cut at x = 0) and folded medial vertices both sit on the plane */
  if (srcKey.has(key)) { lateral++; onSource++; } else if ((py - minY) / H > (mf.split.crotch_h || 0.4) + 0.03) apex++; else packedOffPlaneMedial++; }
ok('G33 / G35 identity: every packed leg vertex off the sagittal plane is a SOURCE vertex (' + onSource + ' source-identical, ' + onSeam + ' on the cut plane / folded medial, ' + apex + ' hidden cone apex) — no vertex of the packed pair lies anywhere else', packedOffPlaneMedial === 0 && onSource > 1500 && apex <= 2, { on_source: onSource, on_plane: onSeam, apex: apex, elsewhere: packedOffPlaneMedial });
/* texture correspondence: every leg triangle's UV triple must be inside a single source triangle's UV triangle (the lateral walls reuse the source triangles; the medial walls mirror them) */
function uvOf(A, i) { return [A[i * 2], A[i * 2 + 1]]; }
var srcTriByUvKey = new Map(); for (var t = 0; t < SI.length; t += 3) { var ks = [SI[t], SI[t + 1], SI[t + 2]].map(function (i) { return Math.round(SUV[i * 2] * 1e5) + ':' + Math.round(SUV[i * 2 + 1] * 1e5); }).sort().join('|'); srcTriByUvKey.set(ks, t / 3); }
function inTri(p, a, b, c) { function sgn(p1, p2, p3) { return (p1[0] - p3[0]) * (p2[1] - p3[1]) - (p2[0] - p3[0]) * (p1[1] - p3[1]); } var d1 = sgn(p, a, b), d2 = sgn(p, b, c), d3 = sgn(p, c, a); var eps = 1e-6; return !((d1 < -eps || d2 < -eps || d3 < -eps) && (d1 > eps || d2 > eps || d3 > eps)); }
/* a leg triangle either matches a source UV triangle exactly (unclipped) or all three of its UVs lie inside one source UV triangle (a clipped piece) */
var srcUvTris = []; for (var t2 = 0; t2 < SI.length; t2 += 3) srcUvTris.push([uvOf(SUV, SI[t2]), uvOf(SUV, SI[t2 + 1]), uvOf(SUV, SI[t2 + 2])]);
var exact = 0, inside = 0, orphan = 0, checked = 0; var step = Math.max(1, Math.floor(LI.length / 3 / 600));   /* 600 sampled leg triangles: the search is O(source tris) each */
var apexY = minY + ((mf.split.crotch_h || 0.4) + 0.03) * H; function touchesApex(tri) { return tri.some(function (i) { return LP[i * 3 + 1] + LD[i * 3 + 1] > apexY; }); }   /* the hidden top cone (apex inside the pelvis) carries no meaningful UV */
for (var t3 = 0; t3 < LI.length; t3 += 3 * step) { var tri = [LI[t3], LI[t3 + 1], LI[t3 + 2]]; if (touchesApex(tri)) continue; checked++; var kk = tri.map(function (i) { return Math.round(LUV[i * 2] * 1e5) + ':' + Math.round(LUV[i * 2 + 1] * 1e5); }).sort().join('|'); if (srcTriByUvKey.has(kk)) { exact++; continue; }
  var uvs = tri.map(function (i) { return uvOf(LUV, i); }); var found = false; for (var st = 0; st < srcUvTris.length && !found; st++) { var T = srcUvTris[st]; if (inTri(uvs[0], T[0], T[1], T[2]) && inTri(uvs[1], T[0], T[1], T[2]) && inTri(uvs[2], T[0], T[1], T[2])) found = true; } if (found) inside++; else orphan++; }
ok('G33 texture correspondence: sampled leg triangles carry the source’s own UV triangles (' + exact + ' exact + ' + inside + ' clipped pieces inside one source triangle of ' + checked + ' sampled, the hidden top cone excluded; ' + orphan + ' orphans) — no resampled / nearest-vertex patchwork', orphan === 0 && exact > 0.6 * checked, { exact: exact, inside: inside, orphan: orphan, checked: checked });
/* each leg is closed and the pair is symmetric in count order: L block then R block */
ok('the leg vertex blocks are contiguous per side (L then R) as the generator promises', mf.measurements && mf.measurements.legs && mf.measurements.legs.L.verts + mf.measurements.legs.R.verts + 0 === LN, mf.measurements && mf.measurements.legs);
/* ---- runtime: V9 = dev_0.14 is the default, V8 stays registered for rollback; the build ships both ---- */
var play = fs.readFileSync(path.join(HERE, '..', '26_LOCAL_AUTHORITY', 'lab', 'play.js'), 'utf8'); var build = fs.readFileSync(path.join(HERE, '..', '26_LOCAL_AUTHORITY', 'deploy', 'build_static_demo.mjs'), 'utf8');
ok('runtime: ATHLETE_M_V11 (dev_0.16 = dev_0.15 + graded shoulder weights) is the default avatar; ATHLETE_M_V10 (dev_0.15, hip connection) and ATHLETE_M_V9 (dev_0.14, faithful legs) stay selectable for rollback; the static build ships all three', /\{ id: 'ATHLETE_M_V11', ver: 'dev_0\.16' \}, \{ id: 'ATHLETE_M_V10', ver: 'dev_0\.15' \}, \{ id: 'ATHLETE_M_V9', ver: 'dev_0\.14' \}/.test(play) && /indexOf\('ATHLETE_M_V11'\) >= 0 \? 'ATHLETE_M_V11'/.test(play) && /athlete_m_preview: \['dev_0\.16', 'dev_0\.15', 'dev_0\.14'\]/.test(build));
ok('runtime: the generator is the tracked v5 generator in faithful mode with the source-triangle leg builder', fs.existsSync(path.join(HERE, '..', '26_LOCAL_AUTHORITY', 'lab', 'assets', 'rig_legs_faithful.mjs')) && mf.rig_generator === 'make_class_rig_v5.mjs');
/* ---- tracked page evidence ---- */
var EV = path.join(HERE, '..', '25_HANDOFF', 'CONVERGENCE', 'legs', 'legs_default.json'); var r = null; try { r = JSON.parse(fs.readFileSync(EV, 'utf8')); } catch (e) { }
ok('PASS 4B page probe record exists and passed (fused → separate → walk → fuse → diff; VFX off / on; wireframe)', !!r && r.fail === 0 && r.pass >= 8 && r.refusion_diff && ['front', 'side', 'back'].every(function (k) { return r.refusion_diff[k] && r.refusion_diff[k].mean <= 3; }), r ? { pass: r.pass, fail: r.fail, diff: r.refusion_diff } : 'missing');
console.log('RESULT legs faithful: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
