/* OWNER INTERJECTION 2026-09-18 §3–§4 (phase B): the portrait HUD / control topology as ONE reversible semantic layout — source contracts, the host's
   level in the others view (world-space tags), and the tracked page evidence (deploy/probe_hud_portrait.mjs portrait / landscape / desktop, touch EMULATED).
   node 16_TESTS/gameplay_hud_phase_b.test.mjs */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { loadHeadlessData, composeHeadless } from '../00_CORE/bootstrap.js';
import { createDuelHost } from '../26_LOCAL_AUTHORITY/DuelHost.js'; import { makeEnvelope } from '../26_LOCAL_AUTHORITY/Protocol.js';
var pass = 0, fail = 0; function ok(id, cond, detail) { if (cond) { pass++; console.log('PASS ' + id); } else { fail++; console.log('FAIL ' + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : '')); } }
var LA = new URL('../26_LOCAL_AUTHORITY/', import.meta.url); function read(rel) { return fs.readFileSync(new URL(rel, LA), 'utf8'); }
var html = read('lab/play.html'), hud = read('lab/gameHud.js'), menu = read('lab/gameMenu.js'), play = read('lab/play.js'), rules = read('lab/rulesHud.js'), adapter = read('lab/PresentationAdapter.js'), touch = read('lab/touchControls.js'), field = read('play/rules1723/RulesField.js');
/* §3 bare bars, small state line, no category card, no LOCKED panel */
ok('§3.1 bare bars: HEALTH upper-left (#g-vitals, no .gp card; transparent, no blur, no border), COMBAT + FLIGHT MAHGIC upper-right (#g-vitals-r), LV in the HEALTH row, depleted / critical states', /'<div id="g-vitals">'/.test(hud) && !/id="g-vitals" class="gp"/.test(hud) && /'<div id="g-vitals-r">'/.test(hud) && /#g-vitals-r \{ position: absolute; top: calc\(var\(--sat\) \+ 6px\); right: calc\(var\(--sar\) \+ 8px\); width: 168px;/.test(html) && /\.gb\.hp\.low > i \{ background: var\(--bad\); \}/.test(html) && /classList\.toggle\('low', pct\(hp \|\| 0, hpMax\) <= 0\.25\)/.test(hud) && /#g-vitals \{ width: 168px; flex: 0 0 auto; padding: 0; background: none; border: 0; box-shadow: none; backdrop-filter: none;/.test(html) && /HEALTH<b id="g-lv"><\/b>/.test(hud) && /setHtml\(lvEl, r && r\.me\.level \? 'LV ' \+ r\.me\.level/.test(hud));
ok('§3 the state is a small line ("FREE ROAM" — since the 2026-09-20 next-pass "WILD ENCOUNTER · <species>" while a wild creature is on the player; 9 px, no pill) centred at the top, outside the vitals row', /#g-state \{ padding: 0; font-weight: 800; letter-spacing: 0\.16em; font-size: 9px;/.test(html) && /#g-state\.free \{ color: #a6f7cf; \}/.test(html) && /stText = 'FREE ROAM'/.test(hud) && /stText = 'WILD ENCOUNTER · ' \+ wildNear\.species/.test(hud) && /#g-center \{ position: absolute; left: 50%; top: calc\(var\(--sat\) \+ 8px\); transform: translateX\(-50%\);/.test(html) && /'<\/div>' \+\n      '<div id="g-center">/.test(hud) && hud.indexOf('<div id="g-vitals-r">') < hud.indexOf('<div id="g-center">'));
ok('§3 no top-right category card by default: the dock renders only in the rollback layout (DOCK), the category is a compact tappable PILL directly left of FLY (B7 §5; tap / swipe = next category, never a cast)', /var DOCK = !!\(document\.body && document\.body\.classList\.contains\('hud-dock'\)\);/.test(hud) && /if \(!DOCK \|\| !r\) \{ dock\.style\.display = 'none'; st\.key = null; return; \}/.test(hud) && /<div id="g-catlbl" style="display:none"><button class="gcat-arrow" data-do="cat-prev"/.test(hud) && /<button id="g-cattext" data-do="cat-cycle"/.test(hud) && /<button class="gcat-arrow" data-do="cat-next"/.test(hud) && /case 'cat-cycle': case 'cat-next': case 'cat-prev': \{ var rc = p && p\.rules; if \(rc\) \{ var lc = modes\(rc\);/.test(hud) && /st\.catSwipe = \{ id: e\.pointerId/.test(hud) && /api\.doButton\(cdx > 0 \? 'cat-next' : 'cat-prev'\)/.test(hud) &&   /* JOB A (owner 2026-09-19): category text with small arrows + a horizontal swipe on the strip (the strip owns its pointer: never a camera drag, never an attack) */ /body\.touch #g-catlbl \{ position: fixed; right: calc\(var\(--sar\) \+ 8px \+ var\(--q\) \* 2 \+ var\(--qg\) \* 2\); bottom: calc\(var\(--sab\) \+ 8px \+ var\(--q\) \+ var\(--qg\) \+ \(var\(--q\) - 26px\) \/ 2\); width: calc\(var\(--q\) \* 2 \+ var\(--qg\)\); height: 26px;/.test(html) && /body\.touch #g-catlbl \.gcat-arrow \{ display: none; \}/.test(html));   /* owner B7 §5 (2026-09-20): the mode control is a compact PILL directly LEFT of FLY (the FLY row), arrows hidden on touch; tap / swipe cycle the mode, never a cast */
ok('§3 no LOCKED panel: #g-target exists only in the rollback layout; the lock rides the target\'s world tag (adapter.tag: LV · LOCKED · behind cover / too far, gold) and ⚔ COMBAT lists it with UNLOCK', /\(DOCK \? '<div id="g-target" style="display:none">/.test(hud) && /if \(tg && lk\) \{/.test(hud) && /\} else if \(tg\) tg\.style\.display = 'none';/.test(hud) && /tag: function \(id, t\) \{ var e = ents\[id\]; if \(!e \|\| e\.kind !== 'CHARACTER' \|\| !t\) return;/.test(adapter) && /'LOCKED' \+ \(t\.lock\.visible === false \? ' · behind cover' : \(t\.lock\.out_of_range \? ' · too far' : ''\)\)/.test(adapter) && /e\.lvlColor = \(t\.lock \|\| t\.combo\) \? '#ffd15e' : '#cfe0ff'; e\.lvl = labelSprite\(txt, e\.lvlColor, 1\.6\)/.test(adapter) && /adapter\.tag\(id, \{ level: o\.level, lock: r\.me\.lock && r\.me\.lock\.target === o\.id \? r\.me\.lock : null, ko: o\.ko, combo: o\.statuses\.some\(function \(s\) \{ return s\.kind === 'COMBO_LOCK'; \}\) \}\)/.test(rules) && /<button data-m="unlock">UNLOCK<\/button>/.test(menu));
ok('§3 world-space health only in combat / practice: the bar follows in_duel = MATCH | PRACTICE (never in free roam); the level is in the host\'s others view', /in_duel: r\.context === 'MATCH' \|\| r\.context === 'PRACTICE', label: o\.id,/.test(rules) && /class: x\.classId, level: levelOf\(x\), team: teamOf\(x\)/.test(field) && /e\.bar\.visible = !!v\.in_duel;/.test(adapter));
/* §4 the control topology */
ok('§4 tokens: 42 px faces (0.83 × 50), 8 px gaps, 4 px hit halo — declared once on :root and applied as ::after halos to the island / arc controls only (never inside lists)', /--q: 42px; --qg: 8px; --hit: 4px;/.test(html) && /body\.touch #g-acts \.gbtn::after, body\.touch #g-erty-t \.gq::after, body\.touch #tc-dash::after \{ content: ""; position: absolute; inset: calc\(-1px - var\(--hit\)\); border-radius: inherit; \}/.test(html) && !/\.gbtn::after \{ content/.test(html.replace(/body\.touch #g-acts \.gbtn::after/g, '')));
ok('§4 left: MAP · SPEED · CAM as a shallow arc above the joystick (SPEED 6 px higher); the ring 124 px (landscape 108 px); the stick radius follows the styled ring', /body\.touch #g-utils \{ position: fixed; left: calc\(var\(--sal\) \+ 20px\); bottom: calc\(var\(--sab\) \+ 162px\);/.test(html) && /body\.touch #g-utils #g-speed \{ left: calc\(var\(--q\) \+ var\(--qg\)\); bottom: 6px; \}/.test(html) && /#tc-stick \{ position: absolute; left: calc\(var\(--sal\) \+ 26px\); bottom: calc\(var\(--sab\) \+ 26px\); width: 124px; height: 124px;/.test(html) && /#tc-stick \{ width: 108px; height: 108px;/.test(html) && /function stickR\(\) \{ var b = el\('tc-stick'\); var w = b \? b\.offsetWidth : 0; return w > 0 \? w \/ 2 : CFG\.stick_radius_px; \}/.test(touch) && /var R = stickR\(\);/.test(touch));
ok('§4 right island (+ owner hotfix 2026-09-19 §5 / §6 + JOB A 2026-09-19): GUARD in row D, SEPARATE / FUSE in the corner where the permanent DASH was, ONE FLY control direct above GUARD (no DOWN / LAND buttons), ≡ lower-right, NO generic ATTACK / PRIMARY button (row C\'s left cells stay empty), quick slots 1–4 as an arc on row B are the attack controls, ⚔ on row A', /body\.touch #g-cluster #g-guard \{ right: calc\(var\(--q\) \+ var\(--qg\)\); bottom: 0; \} body\.touch #g-cluster #g-fly \{ right: calc\(var\(--q\) \+ var\(--qg\)\); bottom: calc\(var\(--q\) \+ var\(--qg\)\); \}/.test(html) && /#tc-dash, #tc-form \{ left: auto; right: calc\(var\(--sar\) \+ 8px\); bottom: calc\(var\(--sab\) \+ 8px\); width: var\(--q\); height: var\(--q\);/.test(html) && /<button id="tc-form" data-tc="form">SEPARATE/.test(html) && !/<button id="tc-dash"/.test(html) && !/id="g-desc"/.test(hud) && !/id="g-land"/.test(hud) && !/id="g-flyaux"/.test(hud) && /act\.flyPress\(true\)/.test(hud) && /function flyPress\(down\)/.test(play) && /onForm: function \(\) \{ sound\.unlock\(\); send\('TRANSFORM'\); \}/.test(play) && !/id="tc-attack"/.test(html) && !/#tc-attack/.test(html) && !/g-cell-attack/.test(hud) && !/attackTap/.test(play) && !/act === 'attack'/.test(touch) && /body\.touch #g-acts #g-menubt \{ position: fixed; right: calc\(var\(--sar\) \+ 11px\); bottom: calc\(var\(--sab\) \+ 8px \+ var\(--q\) \+ var\(--qg\) \+ 3px\); width: 36px; height: 36px;/.test(html) && /body\.touch #g-acts #g-swordbt \{ position: fixed; right: calc\(var\(--sar\) \+ 11px\); bottom: calc\(var\(--sab\) \+ 182px\); width: 36px; height: 36px;/.test(html) && /body\.touch #g-erty-t \.gq:nth-child\(2\), body\.touch #g-erty-t \.gq:nth-child\(3\) \{ margin-bottom: 6px; \}/.test(html) && !/body\.touch #g-flyaux \{/.test(html) && /body\.touch #g-cluster #g-mahgic \{ display: none; \}/.test(html));
ok('owner hotfix 2026-09-19 §5: the quick slots dispatch their own attacks — tap = directAttack(slot), a swipe ≥ 24 px from the slot = directAttack(slot, \'swipe\', dir) checked against THAT move\'s gesture (WRONG SWIPE refusal), no hold-to-arm, no attack modifier in the touch layer; ⚔ opens COMBAT; the desktop keeps V / M / Z and its bottom bar', /st\.slotPress = \{ id: e\.pointerId, slot: parseInt\(dd\.slice\(7\), 10\), x: e\.clientX, y: e\.clientY, dir: null \};/.test(hud) && /act\.directAttack\(spx\.slot, 'swipe', spx\.dir\)/.test(hud) && !/st\.armLong/.test(hud) && /async function directAttack\(slot, source, dir\)/.test(play) && /reason: 'GESTURE_MISMATCH', expected: expD, got: dir/.test(play) && /case 'sword': if \(act\.menu\) act\.menu\('COMBAT'\); break;/.test(hud) && /id="g-swordbt"/.test(hud) && /case 'KeyM': if \(!e\.repeat\) castMahgic\('key'\)/.test(play) && /#g-desk \{ position: absolute; left: 50%;/.test(html));
ok('§5 ⚔ COMBAT surface: the three categories with equipped counts, the 8 equipped rows (4 / 2 / 2) with ARM through the ONE selection function, the lock + UNLOCK, practice; reconciliation line "8 equipped = … the quick slots 1–4 show the ARMED category and ARE the attack controls"', /\['COMBAT', 'STATS', 'SKILLS', 'LOADOUT', 'EMOTES', 'ACTIONS', 'INVENTORY', 'MAP', 'FRIENDS', 'DMS'\]/.test(menu) && /if \(st\.tab === 'COMBAT'\) \{/.test(menu) && /class="mmode' \+ \(r\.me\.attack_mode === md\.id \? ' on' : ''\) \+ '" data-m="mode"/.test(menu) && /<button data-m="arm" data-cat="' \+ esc\(md\.category\) \+ '" data-slot="' \+ i \+ '">ARM<\/button>/.test(menu) && /8 equipped = 4 PHYSICAL \+ 2 PHYS MAHGIC \+ 2 SPECIAL MAHGIC · the quick slots 1–4 show the ARMED category and ARE the attack controls/.test(menu) && /menuDeps\.select = function \(cat, slot\) \{ return hud\.selectMove\(cat, slot, 'menu'\); \};/.test(play) && /menuDeps\.selectMode = function \(mode\) \{ return hud\.selectMove\(mode, undefined, 'menu'\); \};/.test(play) && /else if \(m === 'arm'\) \{ if \(deps\.select\) deps\.select\(b\.getAttribute\('data-cat'\), parseInt\(b\.getAttribute\('data-slot'\), 10\)\); setTimeout\(render, 140\); \}/.test(menu));
ok('reversible: ?hud=dock (body.hud-dock) restores the PASS 3 cluster, dock, LOCKED panel and the 112 px stick on the same build — every old rule survives behind the class except the deleted generic ATTACK control (owner 2026-09-19)', /if \(params\.get\('hud'\) === 'dock'\) document\.body\.classList\.add\('hud-dock'\);/.test(play) && (html.match(/body\.touch\.hud-dock #/g) || []).length >= 12 && /body\.hud-dock #tc-dash \{ right: calc\(var\(--sar\) \+ 8px \+ 56px\);/.test(html) && /body\.hud-dock #tc-stick \{ width: 112px; height: 112px; \}/.test(html) && /layout: function \(\) \{ return DOCK \? 'dock' : 'island'; \}/.test(hud));
/* host: level in the others view (the tag's source), unchanged combat semantics */
var data = await loadHeadlessData(); var DT = data.cfg.dev('local_authority.tick_dt_s'); var h = createDuelHost({ data: data, composeHeadless: composeHeadless }); h.dev.createAccount('A', { classId: 'ATHLETE', sex: 'M' });
var c = h.connect({ client_id: 'c', account_id: 'A', token: h.dev.tokens().A }); var seq = 0; var send = function (a, p) { return h.submit(makeEnvelope({ session_id: c.session_id, client_id: 'c' }, ++seq, a, p || {})); }; var rulesOf = function () { return h.snapshot(c.session_id).play.rules; };
function run(sec) { for (var i = 0; i < Math.round(sec / DT); i++) h.tick(DT); }
send('ENTER_ROOM', { room: 'FIELD' }); run(0.5); var r = rulesOf(); var dummy = r.others.filter(function (o) { return o.id === 'FIELD_DUMMY'; })[0];
ok('host: every other in the rules view carries its level (the dummy: a synthetic at level 1) and the player view keeps its own level; context FREE_ROAM outside practice / match', !!dummy && dummy.level === 1 && r.others.every(function (o) { return Number.isInteger(o.level) && o.level >= 1; }) && Number.isInteger(r.me.level) && r.context !== 'MATCH' && r.context !== 'PRACTICE', { dummy_level: dummy && dummy.level, me: r.me.level, context: r.context });
send('FIELD_PRACTICE', { on: true }); run(0.2); var r2 = rulesOf(); ok('host: PRACTICE context flips the client\'s bar rule (in_duel = context is MATCH | PRACTICE); the others view is otherwise unchanged (hp / max / ko / lock fields)', r2.context === 'PRACTICE' && r2.others[0] && typeof r2.others[0].hp === 'number' && typeof r2.others[0].max === 'number' && 'ko' in r2.others[0], { context: r2.context });
/* tracked page evidence */
var EV = new URL('../25_HANDOFF/CONVERGENCE/hud_b/', import.meta.url);
['portrait', 'landscape', 'desktop'].forEach(function (mode) { var rec = null; try { rec = JSON.parse(fs.readFileSync(new URL('hud_b_' + mode + '.json', EV), 'utf8')); } catch (e) { }
  ok('phase B page probe record exists and passed for ' + mode + (mode === 'desktop' ? '' : ' (touch EMULATED)'), !!rec && rec.fail === 0 && (mode === 'desktop' ? rec.touch_emulated === false : rec.touch_emulated === true), rec ? { pass: rec.pass, fail: rec.fail, fails: rec.checks.filter(function (l) { return /^FAIL/.test(l); }).slice(0, 3) } : 'missing');
  if (rec && rec.halos && mode !== 'desktop') { var Hs = rec.halos; var keys = Object.keys(Hs); ok(mode + ': disclosed hit bounds — every island / arc control answers exactly 4 px outside its face left / right (faces 42 · 92 · 36 px → hits 50 · 100 · 44 px)', keys.length >= 9 && keys.every(function (k) { return Hs[k] && Hs[k].halo.l === 4 && Hs[k].halo.r === 4 && Hs[k].centre; }), keys.map(function (k) { return [k, Hs[k] && Hs[k].vis, Hs[k] && Hs[k].halo]; })); }
});
console.log('RESULT HUD PHASE B: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
