import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { createRigAnimator } from '../../26_LOCAL_AUTHORITY/lab/RigAnimator.js';
import * as AD from '../../26_LOCAL_AUTHORITY/lab/animData.js';
import { restFromGlb } from '../../16_TESTS/lib/rest_from_glb.mjs';
import { readGlb } from '../../26_LOCAL_AUTHORITY/deploy/glb_read.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; }
var ASSET = arg('--asset', path.join(HERE, '..', '..', '26_LOCAL_AUTHORITY', 'lab', 'assets', 'athlete_m_preview', 'dev_0.12', 'Mah_Athlete_M_am08_v5.glb'));
var PROFILE = JSON.parse(fs.readFileSync(path.join(HERE, '..', '..', '26_LOCAL_AUTHORITY', 'lab', 'rig_profile.json'), 'utf8'));
var DEFAULTS = JSON.parse(fs.readFileSync(path.join(HERE, '..', '..', '26_LOCAL_AUTHORITY', 'lab', 'presentation_defaults.json'), 'utf8'));
var passed = 0, failed = 0; function ok(name, cond, info) { if (cond) { passed++; console.log('PASS ' + name); } else { failed++; console.log('FAIL ' + name + (info !== undefined ? ' — ' + JSON.stringify(info) : '')); } }
/* ---- minimal quaternion math (x,y,z,w) ---- */
function qMul(a, b) { return [a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1], a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0], a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3], a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2]]; }
function qFromEuler(x, y, z) { var c1 = Math.cos(x / 2), c2 = Math.cos(y / 2), c3 = Math.cos(z / 2), s1 = Math.sin(x / 2), s2 = Math.sin(y / 2), s3 = Math.sin(z / 2); return [s1 * c2 * c3 + c1 * s2 * s3, c1 * s2 * c3 - s1 * c2 * s3, c1 * c2 * s3 + s1 * s2 * c3, c1 * c2 * c3 - s1 * s2 * s3]; }
function qRot(q, v) { var x = v[0], y = v[1], z = v[2], qx = q[0], qy = q[1], qz = q[2], qw = q[3]; var ix = qw * x + qy * z - qz * y, iy = qw * y + qz * x - qx * z, iz = qw * z + qx * y - qy * x, iw = -qx * x - qy * y - qz * z; return [ix * qw + iw * -qx + iy * -qz - iz * -qy, iy * qw + iw * -qy + iz * -qx - ix * -qz, iz * qw + iw * -qz + ix * -qy - iy * -qx]; }
function Euler() { this.x = 0; this.y = 0; this.z = 0; } Euler.prototype.set = function (x, y, z) { this.x = x; this.y = y; this.z = z; return this; }; Euler.prototype.setFromQuaternion = function (q) { /* three.js XYZ extraction (matrix based) */ var x = q.x, y = q.y, z = q.z, w = q.w; var x2 = x + x, y2 = y + y, z2 = z + z; var xx = x * x2, xy = x * y2, xz = x * z2, yy = y * y2, yz = y * z2, zz = z * z2, wx = w * x2, wy = w * y2, wz = w * z2; var m11 = 1 - (yy + zz), m12 = xy - wz, m13 = xz + wy, m22 = 1 - (xx + zz), m23 = yz - wx, m32 = yz + wx, m33 = 1 - (xx + yy); this.y = Math.asin(Math.max(-1, Math.min(1, m13))); if (Math.abs(m13) < 0.9999999) { this.x = Math.atan2(-m23, m33); this.z = Math.atan2(-m12, m11); } else { this.x = Math.atan2(m32, m22); this.z = 0; } return this; };
function Quat() { this.x = 0; this.y = 0; this.z = 0; this.w = 1; } Quat.prototype.setFromEuler = function (e) { var q = qFromEuler(e.x, e.y, e.z); this.x = q[0]; this.y = q[1]; this.z = q[2]; this.w = q[3]; return this; }; Quat.prototype.slerp = function (q, t) { this.x += (q.x - this.x) * t; this.y += (q.y - this.y) * t; this.z += (q.z - this.z) * t; this.w += (q.w - this.w) * t; var l = Math.hypot(this.x, this.y, this.z, this.w) || 1; this.x /= l; this.y /= l; this.z /= l; this.w /= l; return this; };
Quat.prototype.set = function (x, y, z, w) { this.x = x; this.y = y; this.z = z; this.w = w; return this; }; Quat.prototype.copy = function (q) { this.x = q.x; this.y = q.y; this.z = q.z; this.w = q.w; return this; }; Quat.prototype.invert = function () { this.x = -this.x; this.y = -this.y; this.z = -this.z; return this; }; Quat.prototype.multiply = function (b) { var a = this; var r = qMul([a.x, a.y, a.z, a.w], [b.x, b.y, b.z, b.w]); this.x = r[0]; this.y = r[1]; this.z = r[2]; this.w = r[3]; return this; };
var THREE = { Euler: Euler, Quaternion: Quat };
/* ---- asset ---- */
var G = readGlb(ASSET); var J = G.json; var REST = restFromGlb(ASSET); var scale = REST.scale;
var nodesUsed = J.skins[0].joints.map(function (ni) { return J.nodes[ni]; });
ok('1. every joint is translation-only (no scale / rotation / matrix): bone rotation cannot scale the limb', nodesUsed.every(function (n) { return !n.scale && !n.rotation && !n.matrix; }), nodesUsed.filter(function (n) { return n.scale || n.rotation || n.matrix; }).map(function (n) { return n.name; }));
/* ---- animator + FK ---- */
function makeRig() { var bones = {}; AD.BONES.forEach(function (k) { if (!REST.bones[k]) return; var p = REST.bones[k]; bones[k] = { name: k, position: { x: p[0], y: p[1], z: p[2] }, quaternion: new Quat() }; }); return { bones: bones, scale: scale, seed: 0.3 }; }
function fk(pose) { var out = {}, rot = {}; REST.order.forEach(function (name) { var par = REST.parent[name], off = REST.bones[name] || [0, 0, 0], e = pose[name] || [0, 0, 0]; var pPos = (par && out[par]) || [0, 0, 0], pRot = (par && rot[par]) || [0, 0, 0, 1]; var moved = qRot(pRot, off); out[name] = [pPos[0] + moved[0], pPos[1] + moved[1], pPos[2] + moved[2]]; rot[name] = qMul(pRot, qFromEuler(e[0], e[1], e[2])); }); return { pos: out, rot: rot }; }
var A = createRigAnimator(THREE, makeRig(), { defaults: DEFAULTS, animData: AD, classId: 'ATHLETE', seed: 0.3, profile: PROFILE });
var CAST = JSON.parse(fs.readFileSync(path.join(HERE, '..', 'lab', 'assets', 'retarget', 'tripo_cast_a_spell_upper_v1.json'), 'utf8'));
var restPose = {}; var r0 = fk(restPose);
[0, 24, 40, 60, 66, 100].forEach(function (i) { var fr = CAST.frames[i]; var pose = {}; Object.keys(fr).forEach(function (k) { pose[k] = fr[k]; }); var f = fk(pose); var hl = f.pos.HAND_L, hr = f.pos.HAND_R, ch = f.pos.CHEST; console.log('frame', i, 't', (i / 24).toFixed(2), 'HAND_L', hl.map(function (x) { return +x.toFixed(2); }), 'HAND_R', hr.map(function (x) { return +x.toFixed(2); }), 'CHEST', ch.map(function (x) { return +x.toFixed(2); }), 'UA_L', f.pos.UPPERARM_L.map(function (x) { return +x.toFixed(2); })); });
console.log('rest HAND_L', r0.pos.HAND_L.map(function (x) { return +x.toFixed(2); }), 'HAND_R', r0.pos.HAND_R.map(function (x) { return +x.toFixed(2); }), 'scale', scale);

var HIT = JSON.parse(fs.readFileSync(path.join(HERE, '..', 'lab', 'assets', 'retarget', 'tripo_hit_to_head_upper_v1.json'), 'utf8'));
var view = { speed01: 0, speed_mps: 0, moving: false, form: 'FUSED', yaw: 0, host_t: 0 }; A.setDonorClips({ CAST: CAST, HIT: HIT }, true); for (var w = 0; w < 60; w++) { view.host_t += 1 / 60; A.animate(view, 1 / 60); }
for (var i = 0; i <= 48; i += 4) { var pr = i / 48; view.host_t += 1 / 60; A.animate({ speed01: 0, speed_mps: 0, moving: false, form: 'FUSED', yaw: 0, host_t: view.host_t, attack: { attack_id: 'ATHLETE_VECTOR', state: 'STARTUP', category: 'SPECIAL_MAGIC', progress: pr } }, 1 / 60); var d = A.armDebug(); var ps = A.pose(); console.log('pr', pr.toFixed(2), 'clip t', (0.3 + 2.3 * pr).toFixed(2), 'R hand', JSON.stringify(d.R.hand), 'depthH', d.R.depthH, 'L hand', JSON.stringify(d.L.hand), 'depthH', d.L.depthH, 'fixes', d.fixes, 'UA_R', ps.UPPERARM_R.map(function (x) { return +x.toFixed(2); }), 'FA_R', ps.FOREARM_R.map(function (x) { return +x.toFixed(2); })); }
