import io
p = r'C:\Users\jahsu\Downloads\MAHWORLD_CHARACTERS\CLAUDE_GAMEPLAY_RUNTIME\26_LOCAL_AUTHORITY\lab\RigAnimator.js'
s = open(p, encoding='utf-8').read()
start = s.index("        if (pat === 'PUSH') {"); end = s.index("        else if (pat === 'UPRIGHT_ROW') {")
new_push_pull = """        /* -- PUSH = VERTICAL PUSH (overhead press). LOAD: a real dip - hips/knees (tail in fused) compress, both fists racked at the shoulders,
              elbows forward, eyes up. RELEASE: leg/hip drive to full extension, spine arches, both arms lock out overhead-forward, shoulders
              shrug up into the press; FOLLOW-THROUGH holds the lockout before the arms come down to guard. */
        if (pat === 'PUSH') { set('THIGH_L', 0.34 * qa); set('THIGH_R', 0.34 * qa); set('SHIN_L', 0.52 * qa); set('SHIN_R', 0.52 * qa); set('TAIL1', 0.30 * qa); set('TAIL2', 0.22 * qa); set('PELVIS', 0.10 * qa); set('SPINE', 0.12 * qa); set('CHEST', 0.06 * qa); set('HEAD', -0.16 * qa); set('CLAV_L', 0.06 * qa, 0, 0.10 * qa); set('CLAV_R', 0.06 * qa, 0, -0.10 * qa); set('UPPERARM_L', -1.05 * qa, 0, 0.42 * qa); set('UPPERARM_R', -1.05 * qa, 0, -0.42 * qa); set('FOREARM_L', -1.30 * qa); set('FOREARM_R', -1.30 * qa); hand('L', 'FIST', 1); hand('R', 'FIST', 1);
          set('THIGH_L', -0.16 * ra); set('THIGH_R', -0.16 * ra); set('SHIN_L', -0.12 * ra); set('SHIN_R', -0.12 * ra); set('TAIL1', -0.20 * ra); set('TAIL2', -0.12 * ra); set('PELVIS', -0.14 * ra * amp); set('SPINE', -0.20 * ra * amp); set('CHEST', -0.16 * ra * amp); set('HEAD', 0.10 * ra); set('CLAV_L', -0.10 * ra, 0, 0.34 * ra); set('CLAV_R', -0.10 * ra, 0, -0.34 * ra); set('UPPERARM_L', -1.55 * ra * amp, 0, 0.10 * ra); set('UPPERARM_R', -1.55 * ra * amp, 0, -0.10 * ra); set('FOREARM_L', 1.10 * ra); set('FOREARM_R', 1.10 * ra); set('HAND_L', -0.20 * ra); set('HAND_R', -0.20 * ra); }
        /* -- PULL = HORIZONTAL PULL (heavy row). LOAD: reach - torso hinges forward, both arms extended long and low, hands open, scapulae
              protracted. RELEASE: the hips fire and the torso snaps upright/back while both elbows rip past the ribs, scapulae retract hard,
              chest up, fists at the lower ribs; FOLLOW-THROUGH keeps the elbows high and back. */
        else if (pat === 'PULL') { set('PELVIS', 0.16 * qa); set('SPINE', 0.34 * qa * amp); set('CHEST', 0.14 * qa); set('HEAD', -0.18 * qa); set('THIGH_L', 0.18 * qa); set('THIGH_R', 0.18 * qa); set('SHIN_L', 0.22 * qa); set('SHIN_R', 0.22 * qa); set('TAIL1', 0.14 * qa); set('CLAV_L', 0.12 * qa, outSign('L') * -0.20 * qa, 0.16 * qa); set('CLAV_R', 0.12 * qa, outSign('R') * -0.20 * qa, -0.16 * qa); set('UPPERARM_L', -1.30 * qa * amp, 0, 0.20); set('UPPERARM_R', -1.30 * qa * amp, 0, -0.20); set('FOREARM_L', -0.12 * qa); set('FOREARM_R', -0.12 * qa); hand('L', 'OPEN', q); hand('R', 'OPEN', q);
          set('PELVIS', -0.22 * ra); set('SPINE', -0.30 * ra * amp); set('CHEST', -0.18 * ra * amp); set('HEAD', 0.20 * ra); set('THIGH_L', -0.10 * ra); set('THIGH_R', -0.10 * ra); set('TAIL1', -0.16 * ra); set('CLAV_L', -0.22 * ra, outSign('L') * 0.42 * ra, -0.14 * ra); set('CLAV_R', -0.22 * ra, outSign('R') * 0.42 * ra, 0.14 * ra);   /* retraction is a y rotation: the clavicle runs along x */ set('UPPERARM_L', 0.70 * ra * amp, 0, 0.34 * ra); set('UPPERARM_R', 0.70 * ra * amp, 0, -0.34 * ra); set('FOREARM_L', -1.30 * ra * amp); set('FOREARM_R', -1.30 * ra * amp); hand('L', 'FIST', rel); hand('R', 'FIST', rel); }
"""
s = s[:start] + new_push_pull + s[end:]
start = s.index("        else if (pat === 'HINGE') {"); end = s.index("        else if (pat === 'SQUAT') {")
new_hinge = """        /* -- HINGE = HIP-DOMINANT (kettlebell swing / deadlift snap). LOAD: hips ride far back, torso close to horizontal with a flat back,
              arms hanging long between the thighs, head neutral. RELEASE: violent hip snap to lockout, glutes through, torso upright and
              a touch behind vertical, both straight arms swing up to chest height in front; FOLLOW-THROUGH floats the arms before they fall. */
        else if (pat === 'HINGE') { set('PELVIS', 0.42 * qa * amp); set('SPINE', 0.40 * qa * amp); set('CHEST', 0.14 * qa); set('HEAD', -0.34 * qa); set('THIGH_L', 0.36 * qa); set('THIGH_R', 0.36 * qa); set('SHIN_L', 0.28 * qa); set('SHIN_R', 0.28 * qa); set('TAIL1', 0.26 * qa); set('TAIL2', 0.10 * qa); set('CLAV_L', 0.10 * qa); set('CLAV_R', 0.10 * qa); set('UPPERARM_L', 0.42 * qa, 0, 0.18); set('UPPERARM_R', 0.42 * qa, 0, -0.18); set('FOREARM_L', -0.06 * qa); set('FOREARM_R', -0.06 * qa); hand('L', 'FIST', 1); hand('R', 'FIST', 1);
          set('PELVIS', -0.30 * ra * amp); set('SPINE', -0.22 * ra * amp); set('CHEST', -0.12 * ra); set('HEAD', 0.22 * ra); set('THIGH_L', -0.18 * ra); set('THIGH_R', -0.18 * ra); set('SHIN_L', -0.10 * ra); set('SHIN_R', -0.10 * ra); set('TAIL1', -0.30 * ra); set('TAIL2', -0.10 * ra); set('CLAV_L', -0.12 * ra, 0, 0.14 * ra); set('CLAV_R', -0.12 * ra, 0, -0.14 * ra); set('UPPERARM_L', -1.70 * ra * amp, 0, 0.26 * ra); set('UPPERARM_R', -1.70 * ra * amp, 0, -0.26 * ra); set('FOREARM_L', -0.10 * ra); set('FOREARM_R', -0.10 * ra); hand('L', 'OPEN', rel); hand('R', 'OPEN', rel); }
"""
s = s[:start] + new_hinge + s[end:]
start = s.index("        else if (pat === 'ROTATION') {"); end = s.index("        else { set('UPPERARM_L', -1.25 * qa, 0, 0.34);")
new_rot = """        /* -- ROTATION = CORE / WOODCHOP. LOAD: a big wind-up away from the strike side - pelvis, spine, chest and head all coil, both arms
              carried high on the far side, weight loaded on the far leg. RELEASE: the pelvis leads, the spine and chest whip through past the
              strike line, both arms chop across and down at chest height; FOLLOW-THROUGH over-rotates before settling. */
        else if (pat === 'ROTATION') { set('PELVIS', 0.06 * qa, -0.34 * qa); set('SPINE', 0.08 * qa, -0.36 * qa * amp); set('CHEST', 0.04 * qa, -0.52 * qa * amp); set('HEAD', 0, -0.20 * qa); set('THIGH_L', 0.12 * qa); set('THIGH_R', 0.12 * qa); set('SHIN_L', 0.16 * qa); set('SHIN_R', 0.16 * qa); set('TAIL1', 0, -0.14 * qa); set('UPPERARM_R', -1.30 * qa, 0.30 * qa, -0.95 * qa); set('FOREARM_R', -0.95 * qa); hand('R', 'FIST', 1); set('UPPERARM_L', -0.95 * qa, 0, 0.50 * qa); set('FOREARM_L', -1.25 * qa); hand('L', 'FIST', 1);
          set('PELVIS', -0.06 * ra, 0.52 * ra * amp); set('SPINE', -0.04 * ra, 0.50 * ra * amp); set('CHEST', 0, 0.78 * ra * amp); set('HEAD', 0, 0.36 * ra); set('TAIL1', 0, 0.26 * ra); set('THIGH_R', 0, 0.16 * ra); set('THIGH_L', 0, 0.10 * ra); set('UPPERARM_R', -0.95 * ra, 0.55 * ra, -1.20 * ra * amp); set('FOREARM_R', -0.10 * ra); set('UPPERARM_L', -0.70 * ra, -0.30 * ra, 0.90 * ra); set('FOREARM_L', -0.20 * ra); }
"""
s = s[:start] + new_rot + s[end:]
open(p, 'w', encoding='utf-8').write(s); print('families rewritten')
