p='16_TESTS/gameplay_emotes_npc.test.mjs'; s=open(p,encoding='utf-8',newline='').read()
marker="console.log('\nRESULT emotes"
assert marker in s, 'marker'
new=r"""/* 9 . S07 SPAR: in practice a hit NPC closes and strikes back with its own move on the real cast path; left alone it stands down */
ok('practice spar: an NPC hit by the player closes to range, casts its own PHYSICAL move (authoritative damage on the player), and stands down ~8 s after the last hit', (function () { var H5 = newHost(); var A5 = sess(H5, 'PLAYER_A'); A5.send('ENTER_ROOM', { room: 'FIELD' }); run(H5, 0.3); A5.send('FIELD_PRACTICE', { on: true }); run(H5, 0.2); var t = npc(A5, 'NPC_TITAN_M'); goTo(H5, A5, t.position.x + 1.5, t.position.z); A5.send('MOVE', { forward: 0, strafe: 0, yaw: +Math.atan2(t.position.x - A5.play().position.x, -(t.position.z - A5.play().position.z)).toFixed(3) }); run(H5, 0.3); A5.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); var hp0 = A5.play().rules.me.hp; var landed = 0; for (var k = 0; k < 6 && !landed; k++) { A5.send('RULES_CAST'); run(H5, 1.2); landed = logs(H5, /^R1723_DAMAGE$/).filter(function (d) { return d.on === 'NPC_TITAN_M'; }).length; } run(H5, 6); var begun = logs(H5, /^NPC_SPAR_BEGIN$/).length >= 1; var npcHits = logs(H5, /^R1723_DAMAGE$/).filter(function (d) { return d.by === 'NPC_TITAN_M' && d.on === 'PLAYER_A'; }).length; var hpNow = A5.play().rules.me.hp; run(H5, 9); var ended = logs(H5, /^NPC_SPAR_END$/).length >= 1; return landed >= 1 && begun && npcHits >= 1 && hpNow < hp0 && ended; })());
ok('free roam spar: a hit NPC only squares up (guard, faces the player) and never damages', (function () { var H6 = newHost(); var A6 = sess(H6, 'PLAYER_A'); A6.send('ENTER_ROOM', { room: 'FIELD' }); run(H6, 0.3); var t = npc(A6, 'NPC_LEAN'); goTo(H6, A6, t.position.x + 1.5, t.position.z); A6.send('MOVE', { forward: 0, strafe: 0, yaw: +Math.atan2(t.position.x - A6.play().position.x, -(t.position.z - A6.play().position.z)).toFixed(3) }); run(H6, 0.3); A6.send('RULES_SELECT', { category: 'PHYSICAL', slot: 0 }); for (var k = 0; k < 3; k++) { A6.send('RULES_CAST'); run(H6, 1.0); } run(H6, 2); var dmgOnMe = logs(H6, /^R1723_DAMAGE$/).filter(function (d) { return d.on === 'PLAYER_A'; }).length; var n6 = npc(A6, 'NPC_LEAN'); return dmgOnMe === 0 && n6.hp === n6.max; })());

"""
s=s.replace(marker, new+marker); open(p,'w',encoding='utf-8').write(s); print('ok')
