/* MAHWORLD :: STATIC DEMO BUILD — one folder Netlify can serve as-is, the authority running in the page (deploy/static/static_host.js).
   Mirrors the source tree under the site root so every relative import and every path the host computes keeps working, pre-bakes the
   JSON files the host reads into shims/host_files.js, patches ONE page (play.html: import map + the in-page host), and writes
   netlify.toml. Nothing in the source tree is modified.  node 26_LOCAL_AUTHORITY/deploy/build_static_demo.mjs [--out <dir>] */
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { fileURLToPath } from 'node:url';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var LA = path.resolve(HERE, '..'); var RUNTIME = path.resolve(LA, '..'); var ROOT = path.resolve(RUNTIME, '..');
var argv = process.argv.slice(2); function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; }
var OUT = path.resolve(arg('--out', path.join(HERE, 'static_dist')));
var THREE_DIR = process.env.MAHWORLD_THREE_DIR || (fs.existsSync(path.join(LA, 'vendor', 'three', 'three.module.min.js')) ? path.join(LA, 'vendor', 'three') : 'C:/Users/jahsu/Documents/Codex/2026-09-06/mrs-mah/implementation/mrmah3d/vendor/three');   /* in-repo vendored copy first (self-contained build) */
function rel(p) { return path.relative(ROOT, p).split(path.sep).join('/'); }
function copy(src, dstRel) { var dst = path.join(OUT, dstRel || rel(src)); fs.mkdirSync(path.dirname(dst), { recursive: true }); fs.copyFileSync(src, dst); return dst; }
if (fs.existsSync(OUT)) fs.rmSync(OUT, { recursive: true, force: true }); fs.mkdirSync(OUT, { recursive: true });

/* 1 the host's module graph (traced with a node resolve hook; lab_host_server.mjs itself is NOT shipped) */
var HOST_MODULES = ['CLAUDE_GAMEPLAY_RUNTIME/00_CORE/bootstrap.js', 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/compose.js', 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/config.js', 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/config.node.js', 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/events.js', 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/policies.js',
  'CLAUDE_GAMEPLAY_RUNTIME/01_PROFILE/GameplayProfile.js', 'CLAUDE_GAMEPLAY_RUNTIME/02_MOVEMENT/FlightSession.js', 'CLAUDE_GAMEPLAY_RUNTIME/02_MOVEMENT/MahlocoAdapter.js', 'CLAUDE_GAMEPLAY_RUNTIME/02_MOVEMENT/MovementCapabilities.js', 'CLAUDE_GAMEPLAY_RUNTIME/03_RESOURCES/Resource.js', 'CLAUDE_GAMEPLAY_RUNTIME/04_COMBAT/AttackModel.js',
  'CLAUDE_GAMEPLAY_RUNTIME/05_ECCENTRIC/EccentricRuntime.js', 'CLAUDE_GAMEPLAY_RUNTIME/06_INPUT/InputActions.js', 'CLAUDE_GAMEPLAY_RUNTIME/07_DUEL/DuelSession.js', 'CLAUDE_GAMEPLAY_RUNTIME/08_SPECTATOR/SpectatorSystem.js', 'CLAUDE_GAMEPLAY_RUNTIME/10_RAIDS/RaidParty.js', 'CLAUDE_GAMEPLAY_RUNTIME/12_PROGRESSION/Progression.js',
  'CLAUDE_GAMEPLAY_RUNTIME/13_EMOTES/IdleAndEmotes.js', 'CLAUDE_GAMEPLAY_RUNTIME/14_TELEMETRY/Telemetry.js', 'CLAUDE_GAMEPLAY_RUNTIME/22_DEBUG_BOT/DuelBot.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/DuelHost.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/DurableStore.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/Protocol.js',
  'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/RewardReceipts.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/PlayMode.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/Navigation.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/world/DogkieManager.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/world/SparScheduler.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/EquipmentManager.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/world/WildlifeManager.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/world/CreatureCombat.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/lab/dustFx.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/rules1723/Colliders.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/rules1723/RulesField.js', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/rules1723/RulesMath.js',
  'CLAUDE_RUNTIME_FOUNDATION/10_RUNTIME_LOADER/ClassIdentityConfig.js', 'CLAUDE_RUNTIME_FOUNDATION/10_RUNTIME_LOADER/characterRegistry.js', 'CLAUDE_RUNTIME_FOUNDATION/10_RUNTIME_LOADER/jsonSource.js', 'CLAUDE_RUNTIME_FOUNDATION/12_ANIMATION_RUNTIME/AnimationStateController.js'];
/* the JSON the host reads (traced with an fs hook) + the ruleset RulesMath loads lazily */
var HOST_JSON = ['CLAUDE_DUAL_LOCOMOTION/15_RUNTIME_DESIGN/config/runtime_config.default.json', 'CLAUDE_GAMEPLAY_FOUNDATION/02_MOVEMENT/PLAYER_MOVEMENT_DEFAULTS.json', 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/dev_tuning.dev.json', 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/class_stats.dev.json', 'CLAUDE_GAMEPLAY_RUNTIME/04_COMBAT/data/attacks.dev.json', 'CLAUDE_GAMEPLAY_RUNTIME/04_COMBAT/data/class_loadouts.dev.json',
  'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/lab/presentation_defaults.json', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/emote_catalog.dev.json', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/play/rules1723/rules_17_23.dev.json', 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/lab/assets/world/world_registry_v1.json', 'CLAUDE_RUNTIME_FOUNDATION/01_CHARACTER_MANIFEST/CHARACTER_MASTER_MANIFEST.json', 'CLAUDE_RUNTIME_FOUNDATION/02_MATERIAL_CONTRACT/material_zones.json',
  'CLAUDE_RUNTIME_FOUNDATION/03_CHARACTER_CREATOR/CHARACTER_VARIANT_SCHEMA.json', 'CLAUDE_RUNTIME_FOUNDATION/05_ANIMATION_CONTRACT/animation_set.json'];
var missing = HOST_MODULES.concat(HOST_JSON).filter(function (r) { return !fs.existsSync(path.join(ROOT, r)); }); if (missing.length) throw new Error('missing: ' + missing.join(', '));
HOST_MODULES.forEach(function (r) { copy(path.join(ROOT, r)); });
var FILES = {}; HOST_JSON.forEach(function (r) { FILES[('/' + r).toLowerCase()] = fs.readFileSync(path.join(ROOT, r), 'utf8'); });   /* lowercase keys: the site host lowercases URLs */

/* 2 the page, its modules, the client modules the server used to alias into /lab/, and the assets play.js registers */
var LAB = path.join(LA, 'lab'); var LAB_REL = 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/lab';
fs.readdirSync(LAB).forEach(function (f) { if (/\.(js|json|css)$/.test(f)) copy(path.join(LAB, f)); });
copy(path.join(LA, 'LabClient.js'), LAB_REL + '/LabClient.js'); copy(path.join(LA, 'Protocol.js'), LAB_REL + '/Protocol.js'); copy(path.join(ROOT, 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/class_stats.dev.json'), LAB_REL + '/class_stats.dev.json'); copy(path.join(LA, 'play', 'rules1723', 'rules_17_23.dev.json'), LAB_REL + '/rules_17_23.dev.json');   /* phase F / G: the ⚔ SKILLS tab reads the ruleset's future concepts + catalog status table from a static copy next to the page */ (function () { var tun = JSON.parse(fs.readFileSync(path.join(ROOT, 'CLAUDE_GAMEPLAY_RUNTIME/00_CORE/dev_tuning.dev.json'), 'utf8')); var rooms = tun.local_authority.play.rooms; var slim = {}; Object.keys(rooms).forEach(function (k) { slim[k] = { label: rooms[k].label, training: rooms[k].training || null }; }); fs.mkdirSync(path.join(OUT, LAB_REL), { recursive: true }); fs.writeFileSync(path.join(OUT, LAB_REL, 'rooms.dev.json'), JSON.stringify(slim)); })();   /* lane E client: the rooms' labels + training steps next to the page (no host data beyond that) */   /* phase F: the canonical stats contract, fetched by the ⚔ panel next to presentation_defaults (the 00_CORE JSON is only pre-baked into the host's file map) */
var ASSET_VERSIONS = { athlete_m_preview: ['dev_0.16', 'dev_0.15', 'dev_0.14'], titan_m_preview: ['dev_0.5'], bage_f_preview: ['dev_0.5'], lean_f_preview: ['dev_0.5'], athlete_f_preview: ['dev_0.2'], bage_m_preview: ['dev_0.2'], lean_m_preview: ['dev_0.2'], titan_f_preview: ['dev_0.2'], visionary_m_preview: ['dev_0.2'], visionary_f_preview: ['dev_0.2'] };
/* S11/M5 owner correction: ship exactly the enabled district manifest's visible + authored far/collider derivatives. Source originals are never served. */
(function () { var manifestPath = path.join(LAB, 'assets', 'buildings', 'district_v1.json'); var district = JSON.parse(fs.readFileSync(manifestPath, 'utf8')); copy(manifestPath); var refs = new Set(); (district.buildings || []).forEach(function (b) { if (b.enabled === false) return; ['runtime', 'lod_runtime', 'collider_runtime'].forEach(function (k) { if (b[k]) refs.add(b[k]); }); }); var shipped = 0, bytes = 0; refs.forEach(function (rt) { var norm = String(rt).replace(/\\/g, '/'); if (norm.indexOf('lab/assets/buildings/') !== 0 || norm.indexOf('..') >= 0) throw new Error('unsafe district derivative path: ' + rt); var src = path.join(LA, norm); if (!fs.existsSync(src)) throw new Error('district derivative missing: ' + rt); copy(src); shipped++; bytes += fs.statSync(src).size; }); console.log('district derivatives shipped: ' + shipped + ' files, ' + (bytes / 1048576).toFixed(1) + ' MB'); })(); copy(path.join(LA, 'play', 'rules1723', 'district_v1_colliders.json'));
/* JOB B (2026-09-19): the world layer modules + registry + the optimized derivatives it references (never the GLB_PHASE_AB sources); play/rules1723/world_v1_colliders.json ships as the generated collider record */ fs.readdirSync(path.join(LAB, 'world')).forEach(function (f) { if (/\.js$/.test(f)) copy(path.join(LAB, 'world', f)); }); copy(path.join(LAB, 'assets', 'world', 'world_registry_v1.json')); copy(path.join(LA, 'play', 'rules1723', 'world_v1_colliders.json'));
(function () { var reg = JSON.parse(fs.readFileSync(path.join(LAB, 'assets', 'world', 'world_registry_v1.json'), 'utf8')); var shipped = 0, bytes = 0; (reg.derivatives || []).forEach(function (d) { Object.keys(d.files || {}).forEach(function (k) { var rt = d.files[k].runtime; var src = path.join(LA, rt); if (!fs.existsSync(src)) throw new Error('world derivative missing: ' + rt); copy(src); shipped++; bytes += fs.statSync(src).size; }); }); console.log('world derivatives shipped: ' + shipped + ' files, ' + (bytes / 1048576).toFixed(1) + ' MB'); })();
fs.readdirSync(path.join(LAB, 'assets', 'retarget')).forEach(function (f) { if (/_upper_v\d+\.json$/.test(f)) copy(path.join(LAB, 'assets', 'retarget', f)); });   /* S10: baked donor upper-body clips (~50 KB) */
copy(path.join(LAB, 'mocap', 'clip_manifest.json'));   /* PASS 6 (Spec F): the clip manifest — the Control Lab lists its PLACEHOLDER clips */
copy(path.join(LAB, 'assets', 'botany', 'tree_spec.js')); copy(path.join(LAB, 'assets', 'botany', 'prototype_v1.json')); copy(path.join(LAB, 'assets', 'shops', 'shops_v1.json'));   /* P8: the zero-stock shop registry */   /* P7 (master §14): the MAHGIC tree family definition + the prototype placement registry */
Object.keys(ASSET_VERSIONS).forEach(function (cls) { ASSET_VERSIONS[cls].forEach(function (v) { var d = path.join(LAB, 'assets', cls, v); fs.readdirSync(d).forEach(function (f) { if (/\.(glb|json)$/.test(f)) copy(path.join(d, f)); }); }); });
['three.module.min.js', 'three.core.min.js', 'GLTFLoader.js', 'SkeletonUtils.js', 'BufferGeometryUtils.js'].forEach(function (f) { var src = path.join(THREE_DIR, f); if (fs.existsSync(src)) copy(src, 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/vendor/three/' + f); });
/* 3 shims + in-page host + pre-baked JSON */
var SH = 'CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/shims';
['node_fs.js', 'node_path.js', 'node_url.js'].forEach(function (f) { copy(path.join(HERE, 'static', 'shims', f), SH + '/' + f); });
fs.writeFileSync(path.join(OUT, SH, 'host_files.js'), '/* generated by build_static_demo.mjs — the JSON the in-page host reads, keyed by site path */\nexport var FILES = ' + JSON.stringify(FILES) + ';\n');
copy(path.join(HERE, 'static', 'static_host.js'), LAB_REL + '/static_host.js');
/* 4 play.html: import map for the node shims + the in-page host before play.js (the only edit, made on the copy) */
var html = fs.readFileSync(path.join(LAB, 'play.html'), 'utf8');
var importMap = '<script type="importmap">' + JSON.stringify({ imports: { 'node:fs': '../shims/node_fs.js', 'node:path': '../shims/node_path.js', 'node:url': '../shims/node_url.js' } }) + '</script>\n';
if (html.indexOf('<script type="module" src="./play.js">') < 0) throw new Error('play.html: module script tag not found');
html = html.replace('<script type="module" src="./play.js">', '<script type="module" src="./static_host.js"></script>\n<script type="module" src="./play.js">');
html = html.replace(/<head>/i, '<head>\n' + importMap);
fs.writeFileSync(path.join(OUT, LAB_REL, 'play.html'), html);
/* 5 Netlify: the ACCESS GATE edge function (deploy/static/edge/gate.js) runs on every path (password page, signed session, logout,
   rate limit — secrets only in the site's environment variables); netlify.toml declares it explicitly. The static redirects / headers
   below stay for paths the gate passes through (custom headers do not apply on edge-served paths, so the gate sets cache headers itself). */
fs.mkdirSync(path.join(OUT, 'netlify', 'edge-functions'), { recursive: true }); copy(path.join(HERE, 'static', 'edge', 'gate.js'), 'netlify/edge-functions/gate.js');
fs.writeFileSync(path.join(OUT, 'netlify.toml'), [
  '[build]', '  publish = "."', '  edge_functions = "netlify/edge-functions"', '',
  '[[edge_functions]]', '  path = "/*"', '  function = "gate"', '',
  '[[redirects]]', '  from = "/.netlify/images"', '  to = "/404"', '  status = 404', '  force = true', '',
  '[[headers]]', '  for = "/*.glb"', '  [headers.values]', '    Content-Type = "model/gltf-binary"', '    Cache-Control = "public, max-age=31536000, immutable"', '',
  '[[headers]]', '  for = "/*.js"', '  [headers.values]', '    Cache-Control = "public, max-age=0, must-revalidate"', '',
  '[[headers]]', '  for = "/*.html"', '  [headers.values]', '    Cache-Control = "public, max-age=0, must-revalidate"', '',
  '[[headers]]', '  for = "/*.json"', '  [headers.values]', '    Cache-Control = "public, max-age=0, must-revalidate"', ''].join('\n'));
fs.writeFileSync(path.join(OUT, 'index.html'), '<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=' + LAB_REL.toLowerCase() + '/play?field=1"><title>MAHWORLD</title><a href="' + LAB_REL.toLowerCase() + '/play?field=1">MAHWORLD demo</a>'); /* relative, so it also works under a proxy prefix (the gate answers / itself) */
/* 6 private-content scan + manifest */
var bad = []; function walk(d) { fs.readdirSync(d).forEach(function (f) { var p = path.join(d, f); if (fs.statSync(p).isDirectory()) return walk(p); if (/\.(js|json|html|toml)$/.test(f)) { var t = fs.readFileSync(p, 'utf8'); if (/MAHWORLD_DEMO_PASSWORD=|C:\\Users\\jahsu|jackedjah/i.test(t) && !/build_static_demo/.test(f)) bad.push(rel(p)); } }); } walk(OUT);
var count = 0, bytes = 0; (function tally(d) { fs.readdirSync(d).forEach(function (f) { var p = path.join(d, f); if (fs.statSync(p).isDirectory()) return tally(p); count++; bytes += fs.statSync(p).size; }); })(OUT);
var BUILD_WORLD_REGISTRY = JSON.parse(fs.readFileSync(path.join(LAB, 'assets', 'world', 'world_registry_v1.json'), 'utf8'));
var BUILD_WORLD_SHA = crypto.createHash('sha256').update(fs.readFileSync(path.join(LAB, 'assets', 'world', 'world_registry_v1.json'))).digest('hex');
var BUILD_DISTRICT = JSON.parse(fs.readFileSync(path.join(LAB, 'assets', 'buildings', 'district_v1.json'), 'utf8'));
var BUILD_DISTRICT_COLLIDERS = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'district_v1_colliders.json'), 'utf8'));
var BUILD_WORLD_COLLIDERS = JSON.parse(fs.readFileSync(path.join(LA, 'play', 'rules1723', 'world_v1_colliders.json'), 'utf8'));
var BUILD_CORRECTED = BUILD_DISTRICT.buildings.filter(function (b) { return !!b.owner_m5_correction; }).map(function (b) { return { id: b.id, scale: b.scale, baseline_scale: b.owner_m5_correction.baseline_scale, correction_factor: b.owner_m5_correction.factor, runtime: b.runtime, runtime_triangles: b.runtime_triangles, lod_runtime: b.lod_runtime, lod_runtime_triangles: b.lod_runtime_triangles, lod_switch_m: b.lod_switch_m, portals: b.portals.map(function (p) { return { id: p.id, world: p.world, outward: p.outward }; }) }; });
var BUILD_MOON = (BUILD_WORLD_REGISTRY.derivatives || []).filter(function (d) { return d.id === 'MAHWORLD_OVERSIZED_MOON'; })[0] || null;
var BUILD_MOON_SOURCE = (BUILD_WORLD_REGISTRY.sources || []).filter(function (s) { return s.id === 'MAHWORLD_OVERSIZED_MOON_SOURCE'; })[0] || null;
var BUILD_INFO = { built: new Date().toISOString(), athlete: ASSET_VERSIONS.athlete_m_preview[0] + ' (ATHLETE_M_V11: dev_0.15 + graded shoulder skin weights — owner hotfix 2026-09-19 intactness: the 0.4 UPPERARM weight step across one deltoid / armpit edge is smoothed over ~2–3 cm, weights only, rollback ?avatar=ATHLETE_M_V10; V10 = dev_0.14 + hip connection — the pelvis shell follows the thighs, the leg tops stay with the pelvis (weights only; rollback ?avatar=ATHLETE_M_V9); V9 = faithful separated legs (O6) — the fused lower body’s own triangles + inferred medial walls; V8 dev_0.13 (surgical loft) kept for rollback via ?avatar=ATHLETE_M_V8)', npcs: 'nine residents (v4)', world: 'M5 OWNER-CORRECTED WORLD_REGISTRY_V1 — preserved 121,975 m² mainland and M1–M5 gameplay; owned road junction topology; structural ridge/monolith collision; discoverable crystal-bush refills; corrected source-traced imported buildings, doors and grand interiors; actual owner Moon derivative with coherent moving-cloud light; continuous-color tree LODs; DAY/NIGHT and the preserved Moonlit Titan circuit', owner_corrections: { schema: 'M5C_20260923', buildings: BUILD_CORRECTED, moon: BUILD_MOON && BUILD_MOON.files ? { derivative: BUILD_MOON.id, source: BUILD_MOON.source, runtime: BUILD_MOON.files.L0.runtime, runtime_sha256: BUILD_MOON.files.L0.sha256, source_sha256: BUILD_MOON_SOURCE && BUILD_MOON_SOURCE.sha256, distance_m: BUILD_WORLD_REGISTRY.celestial.moon.distance_m, apparent_deg: BUILD_WORLD_REGISTRY.celestial.moon.apparent_deg } : null, tree_lod_color_continuity: true, road_topology_owner: 'lab/world/roadNetwork.js', collision_shapes: { district: BUILD_DISTRICT_COLLIDERS.shapes.length, world: BUILD_WORLD_COLLIDERS.shapes.length } }, world_registry_sha256: BUILD_WORLD_SHA, world_counts: { sanctuaries: BUILD_WORLD_REGISTRY.sanctuary_contracts && BUILD_WORLD_REGISTRY.sanctuary_contracts.list ? BUILD_WORLD_REGISTRY.sanctuary_contracts.list.length : 0, paths: BUILD_WORLD_REGISTRY.paths && BUILD_WORLD_REGISTRY.paths.list ? BUILD_WORLD_REGISTRY.paths.list.length : 0, bridge_links: BUILD_WORLD_REGISTRY.paths && BUILD_WORLD_REGISTRY.paths.links ? BUILD_WORLD_REGISTRY.paths.links.length : 0, buildings: BUILD_WORLD_REGISTRY.buildings && BUILD_WORLD_REGISTRY.buildings.list ? BUILD_WORLD_REGISTRY.buildings.list.length : 0, dogkie_pool: BUILD_WORLD_REGISTRY.creatures && BUILD_WORLD_REGISTRY.creatures.DOGKIE ? BUILD_WORLD_REGISTRY.creatures.DOGKIE.pool_size : 0 }, files: count, bytes: bytes, mode: 'static site, in-page authority, memory store' };
fs.writeFileSync(path.join(OUT, 'BUILD_INFO.json'), JSON.stringify(BUILD_INFO, null, 1));
console.log('static demo →', OUT, count, 'files', (bytes / 1048576).toFixed(1), 'MB', bad.length ? 'PRIVATE CONTENT: ' + bad.join(', ') : 'private-content scan clean');
