/* fob.systems/mahdemo — add the two proxy rules to the MAIN site WITHOUT its source tree, as a verifiable DRAFT first.
   The main site (Netlify da939c11…, 54 functions, 93 redirects) was deployed from a zip that is not on this machine. Netlify's deploy API
   accepts a deploy described by file digests + function digests: every existing file and function is referenced by the digest Netlify already
   stores, so nothing is re-uploaded or lost, and ONLY a new `_redirects` (our three rules first, then the existing rules if a _redirects exists)
   is uploaded. The deploy is created as a DRAFT (its own permalink), verified, and published only with --publish. Rollback = restore the
   previous deploy id printed at the start.
   Needs NETLIFY_AUTH_TOKEN (or a `netlify login` on this machine: %APPDATA%/netlify/Config/config.json). Never prints the token.
   node deploy/fob_add_mahdemo_route.mjs [--dry] [--publish <deployId>] [--rollback <deployId>] */
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
var SITE = 'da939c11-2915-43e5-9d61-a4b617eb7a5e', DEMO = 'https://mahworld-test-preview.netlify.app'; var API = 'https://api.netlify.com/api/v1';
var argv = process.argv.slice(2); function arg(k) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : null; } var DRY = argv.indexOf('--dry') >= 0;
function token() { if (process.env.NETLIFY_AUTH_TOKEN) return process.env.NETLIFY_AUTH_TOKEN; try { var cfg = JSON.parse(fs.readFileSync(path.join(process.env.APPDATA || '', 'netlify', 'Config', 'config.json'), 'utf8')); var uid = cfg.userId; var u = cfg.users && cfg.users[uid]; var t = u && u.auth && u.auth.token; if (t) return t; } catch (e) { } return null; }
var TOKEN = token(); if (!TOKEN) { console.error('no Netlify credentials: set NETLIFY_AUTH_TOKEN or run `npx netlify-cli login` on this machine (browser authorisation), then rerun'); process.exit(2); }
async function api(method, p, body, raw) { var r = await fetch(API + p, { method: method, headers: Object.assign({ Authorization: 'Bearer ' + TOKEN }, raw ? { Accept: 'application/vnd.bitballoon.v1.raw' } : { 'Content-Type': 'application/json' }), body: body === undefined ? undefined : (typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body)) }); if (!r.ok) throw new Error(method + ' ' + p + ' → ' + r.status + ' ' + (await r.text()).slice(0, 300)); return raw ? Buffer.from(await r.arrayBuffer()) : r.json(); }
var DEEP = '/mahdemo/claude_gameplay_runtime/26_local_authority/lab/play?field=1';
var RULES = ['# MAHWORLD demo (added ' + new Date().toISOString().slice(0, 10) + '): the playable demo lives on its own Netlify project behind an edge-function password gate. The bare entries REDIRECT (302) to the deep URL so every relative reference (login redirect, scripts, GLBs, logout) resolves under /mahdemo/...; the splat is the only proxy. Keep these ahead of any catch-all.', '/mahdemo  ' + DEEP + '  302', '/mahdemo/  ' + DEEP + '  302', '/mahdemo/*  ' + DEMO + '/:splat  200!', ''].join('\n');
var site = await api('GET', '/sites/' + SITE); var cur = site.published_deploy; console.log('site', site.name, 'current deploy', cur.id, 'published', cur.published_at, '· ROLLBACK: node deploy/fob_add_mahdemo_route.mjs --rollback ' + cur.id);
if (arg('--rollback')) { var rb = await api('POST', '/sites/' + SITE + '/deploys/' + arg('--rollback') + '/restore'); console.log('restored', rb.id, rb.state); process.exit(0); }
if (arg('--publish')) { var pub = await api('POST', '/sites/' + SITE + '/deploys/' + arg('--publish') + '/restore'); console.log('published', pub.id, pub.state, pub.ssl_url); process.exit(0); }
var deploy = await api('GET', '/deploys/' + cur.id); var files = await api('GET', '/sites/' + SITE + '/files?deploy_id=' + cur.id + '&per_page=5000');
console.log('files', files.length, '· functions', (deploy.available_functions || []).length, '· schedules', JSON.stringify(deploy.function_schedules || []));
var fileMap = {}; files.forEach(function (f) { fileMap[f.path] = f.sha; }); var hasRedirects = !!fileMap['/_redirects'], hasToml = !!fileMap['/netlify.toml'];
console.log('_redirects in deploy:', hasRedirects, '· netlify.toml in deploy:', hasToml, '· 404.html:', !!fileMap['/404.html'], '· index.html:', !!fileMap['/index.html']);
var existing = ''; if (hasRedirects) { existing = (await api('GET', '/sites/' + SITE + '/files/_redirects?deploy_id=' + cur.id, undefined, true)).toString('utf8'); console.log('existing _redirects:', existing.split('\n').length, 'lines; first:', existing.split('\n').slice(0, 3).join(' | ').slice(0, 200)); if (/^\/mahdemo/m.test(existing)) { console.log('mahdemo rules already present — nothing to do'); process.exit(0); } }
/* SAFETY (S13 finding): this deploy's 93 redirect rules + 21 header rules were compiled from a netlify.toml in the BUILD SOURCE (a zip that is not
   on this machine) — they are NOT files of the deploy, so a digest clone would ship only OUR three lines and drop every rule the main website
   depends on (its pages are served through those rules). Refuse unless the rules exist as files, or the owner passes --i-know-the-rules-are-files. */
var msgs = ((deploy.summary && deploy.summary.messages) || []).map(function (m) { return m.title || ''; }); var ruleMsg = msgs.filter(function (t) { return /redirect rule/i.test(t); })[0] || ''; var ruleCount = parseInt((ruleMsg.match(/(\d+) redirect/) || [0, 0])[1], 10);
if (ruleCount > 0 && !hasRedirects && !hasToml && argv.indexOf('--i-know-the-rules-are-files') < 0) { console.error('ABORT: the published deploy carries ' + ruleCount + ' redirect rules (' + ruleMsg + ') that are NOT files of the deploy (no _redirects, no netlify.toml): they come from the build source. A digest-clone deploy would DROP them and break the main website. Needed instead: the site\'s project folder / zip (MAHFITT v399: netlify.toml + netlify/functions) on this laptop, add the three lines to its netlify.toml or _redirects, then `netlify deploy` (draft) -> verify -> `netlify deploy --prod`.'); process.exit(7); }
var newRedirects = RULES + '\n' + existing; var sha = crypto.createHash('sha1').update(newRedirects).digest('hex');
var functions = {}; (deploy.available_functions || []).forEach(function (f) { functions[f.n] = f.d; });
var body = { files: Object.assign({}, fileMap, { '/_redirects': sha }), functions: functions, function_schedules: deploy.function_schedules || [], draft: true, title: 'mahdemo proxy rules (digest clone of ' + cur.id + ')', framework: deploy.framework || undefined };
if (DRY) { console.log('DRY: would create a draft deploy referencing', Object.keys(body.files).length, 'files and', Object.keys(functions).length, 'functions; new _redirects sha1', sha); process.exit(0); }
var d = await api('POST', '/sites/' + SITE + '/deploys', body); console.log('draft deploy', d.id, 'state', d.state, '· required uploads', (d.required || []).length, '· required functions', (d.required_functions || []).length);
if ((d.required_functions || []).length) { console.error('ABORT: Netlify asks for function bundles it no longer has:', d.required_functions.slice(0, 5)); await api('POST', '/deploys/' + d.id + '/cancel'); process.exit(3); }
var missing = (d.required || []).filter(function (s) { return s !== sha; }); if (missing.length) { console.error('ABORT: Netlify asks for', missing.length, 'existing file(s) it no longer has (cannot re-upload without the source)'); await api('POST', '/deploys/' + d.id + '/cancel'); process.exit(3); }
if ((d.required || []).indexOf(sha) >= 0) { var up = await fetch(API + '/deploys/' + d.id + '/files/_redirects', { method: 'PUT', headers: { Authorization: 'Bearer ' + TOKEN, 'Content-Type': 'application/octet-stream' }, body: newRedirects }); console.log('uploaded _redirects', up.status); }
for (var i = 0; i < 60; i++) { await new Promise(function (r) { setTimeout(r, 3000); }); var st = await api('GET', '/deploys/' + d.id); if (st.state === 'ready') { console.log('DRAFT READY', st.id, st.deploy_ssl_url, '· functions', (st.available_functions || []).length, '· summary', JSON.stringify((st.summary && st.summary.messages || []).map(function (m) { return m.title; }))); console.log('verify: ' + st.deploy_ssl_url + '/mahdemo  then  node deploy/fob_add_mahdemo_route.mjs --publish ' + st.id); process.exit(0); } if (st.state === 'error') { console.error('draft failed', st.error_message); process.exit(4); } }
console.error('timeout waiting for the draft');
