/* OWNER INTERJECTION 2026-09-18 §3–§4 (phase B) — the portrait control topology in the real page: bare bars, no category card, no LOCKED panel,
   the world-space level / health tag, the left MAP · SPEED · CAM arc over a slightly larger joystick, the right combat island (quick slots 1–4 as an arc,
   PRIMARY two slots wide with the category label above it, FLY direct, GUARD · DASH in the former 3 / 4 spots, ≡ lower-right, ⚔ SWORD → COMBAT),
   0.83× faces with measured hit halos. Touch = EMULATED (headless Chrome mobile emulation); the iPhone check is Jah's.
   node deploy/probe_hud_portrait.mjs [portrait|landscape|desktop] [static_dist] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2);
var MODE = argv.filter(function (a) { return /^(portrait|desktop|landscape)$/.test(a); })[0] || 'portrait'; var DIST = argv.filter(function (a) { return !/^(portrait|desktop|landscape)$/.test(a) && !a.startsWith('--'); })[0]; DIST = DIST ? path.resolve(DIST) : path.join(HERE, 'static_dist');
var OUT = path.join(HERE, 'probe_out', 'hud_b'); fs.mkdirSync(OUT, { recursive: true }); var TOUCH = MODE !== 'desktop'; var VP = MODE === 'portrait' ? [390, 844] : (MODE === 'landscape' ? [844, 390] : [1200, 750]);
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, unlockFps: true, mobile: TOUCH }); var pass = 0, fail = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 900)); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function ptr(type, el, id, x, y) { await pg.evaluate("(function(){ var t=document.getElementById('" + el + "'); if(!t) return 0; t.dispatchEvent(new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'" + (TOUCH ? 'touch' : 'mouse') + "',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true,button:0})); })(); 1"); }
async function tapEl(id, pid) { var r = await rect(id); if (!r || !r.shown) return null; await ptr('pointerdown', id, pid || 7, r.cx, r.cy); await sleep(50); await ptr('pointerup', id, pid || 7, r.cx, r.cy); await sleep(150); return r; }
async function holdEl(id, pid, ms) { var r = await rect(id); if (!r || !r.shown) return null; await ptr('pointerdown', id, pid || 7, r.cx, r.cy); await sleep(ms); await ptr('pointerup', id, pid || 7, r.cx, r.cy); await sleep(150); return r; }
async function rect(id) { return await pg.evaluate("(function(){ var e=document.getElementById('" + id + "'); if(!e) return null; var r=e.getBoundingClientRect(); var cs=getComputedStyle(e); return {id:'" + id + "',x:r.left,y:r.top,w:r.width,h:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2,shown:r.width>0&&r.height>0&&cs.display!=='none'&&cs.visibility!=='hidden',text:(e.textContent||'').trim().slice(0,40)}; })()"); }
async function halo(id) { return await pg.evaluate("(function(){ var e=document.getElementById('" + id + "'); if(!e) return null; var r=e.getBoundingClientRect(); function hit(x,y){ var u=document.elementFromPoint(x,y); return !!(u && (u===e || e.contains(u))); } function reach(dx,dy){ var n=0; for(var k=1;k<=9;k++){ var x=dx<0?Math.round(r.left)-k:(dx>0?Math.round(r.right)+k-1:Math.round(r.left+r.width/2)), y=dy<0?Math.round(r.top)-k:(dy>0?Math.round(r.bottom)+k-1:Math.round(r.top+r.height/2)); if(hit(x,y)) n=k; else break; } return n; } return {id:'" + id + "',vis:[Math.round(r.width),Math.round(r.height)],halo:{l:reach(-1,0),r:reach(1,0),t:reach(0,-1),b:reach(0,1)},centre:hit(r.left+r.width/2,r.top+r.height/2)}; })()"); }
async function vw() { return await pg.evaluate("({w:innerWidth,h:innerHeight})"); }
function ovArea(a, b) { if (!a || !b || !a.shown || !b.shown) return 0; var w = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x), h = Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y); return w > 0 && h > 0 ? w * h : 0; }
function grow(r, k) { return r ? { x: r.x - k, y: r.y - k, w: r.w + 2 * k, h: r.h + 2 * k, shown: r.shown } : r; }
async function rules() { return await ev("var s=P.snap(); return s&&s.play?s.play.rules:null;"); }
var report = { mode: MODE, viewport: VP, touch_emulated: TOUCH, checks: lines, rects: {}, halos: {} };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(6000); await ev("P.hud.showGuide(false); return 1;");
  await ev("return P.goTo(20, 30, undefined, undefined, 60000);"); await sleep(800); var v = await vw();
  var layout = await ev("return P.hud.layout ? P.hud.layout() : null;"); var r0 = await rules();
  /* ── B1 the semantic changes: island layout, no dock, no LOCKED panel, no touch MAHGIC button, bare bars, small state line ── */
  var dock = await rect('g-dock'), tgt = await rect('g-target'), mah = await rect('g-mahgic'), vit = await rect('g-vitals'), stt = await rect('g-state');
  var vitCs = await pg.evaluate("(function(){ var e=document.getElementById('g-vitals'); var cs=getComputedStyle(e); var s=getComputedStyle(document.getElementById('g-state')); var lv=document.getElementById('g-lv'); return {bg:cs.backgroundColor, bf:cs.backdropFilter||cs.webkitBackdropFilter, border:cs.borderTopWidth, state_font:parseFloat(s.fontSize), state_bg:s.backgroundColor, state_text:document.getElementById('g-state').textContent, lv:lv?lv.textContent:null, bars:document.querySelectorAll('#g-vitals .gb, #g-vitals-r .gb').length, right:(function(){ var q=document.getElementById('g-vitals-r'); if(!q) return null; var rr=q.getBoundingClientRect(); return {x:rr.left,w:rr.width,right:rr.right}; })()}; })()");
  ok('B1 island layout: no top-right category card, no LOCKED panel in the DOM, ' + (TOUCH ? 'no separate MAHGIC touch button, ' : '') + 'HEALTH upper-left with LV, COMBAT + FLIGHT MAHGIC upper-right (three bare bars: transparent, no blur, no border), the state a small line (' + vitCs.state_font + ' px, no pill): "' + vitCs.state_text + '"', layout === 'island' && (!dock || !dock.shown) && !tgt && (!TOUCH || !mah || !mah.shown) && vit && vit.shown && /rgba\(0, 0, 0, 0\)|transparent/.test(vitCs.bg) && /none/.test(vitCs.bf || 'none') && vitCs.border === '0px' && vitCs.bars === 3 && vitCs.right && vitCs.right.right >= v.w - 12 && vitCs.right.x > vit.x + vit.w && /^LV \d+/.test(vitCs.lv || '') && vitCs.state_font <= 10 && /rgba\(0, 0, 0, 0\)|transparent/.test(vitCs.state_bg) && /FREE ROAM · HARMLESS/.test(vitCs.state_text), { layout: layout, dock: dock, target: tgt, mahgic: mah, vitals: vitCs });
  var ids = ['g-mapbt', 'g-speed', 'g-camreset', 'g-fly', 'g-guard', 'g-menubt', 'g-swordbt', 'g-catlbl', 'tc-dash', 'tc-stickzone', 'tc-stick', 'g-erty-t', 'g-vitals', 'g-state', 'g-ctx', 'g-desk']; var R = {}; for (var id of ids) R[id] = await rect(id); report.rects.ground = R;
  var slots = await pg.evaluate("Array.prototype.map.call(document.querySelectorAll('#g-erty-t .gq'), function(e){ var r=e.getBoundingClientRect(); return {x:r.left,y:r.top,w:r.width,h:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2,shown:r.width>0,text:e.textContent.trim(),small:(e.querySelector('small')||{}).textContent, overflow:(function(s){ return s? s.scrollWidth>s.clientWidth+1 : false; })(e.querySelector('small'))}; })"); report.rects.slots = slots;
  if (TOUCH) {
    var noAtt = await pg.evaluate("(function(){ return !document.getElementById('tc-attack') && !document.querySelector('[data-tc=\"attack\"]') && !document.getElementById('g-cell-attack'); })()"); var dash = R['tc-dash'], guard = R['g-guard'], fly = R['g-fly'], menu = R['g-menubt'], sword = R['g-swordbt'], cat = R['g-catlbl'], map = R['g-mapbt'], spd = R['g-speed'], cam = R['g-camreset'], stick = R['tc-stick'], sz = R['tc-stickzone'];
    /* ── B2 the island geometry (rows from the bottom) ── */
    var q = 42;
    var freeSpot = fly ? { x: fly.x - 8 - 2 * q - 8, y: fly.y, w: 2 * q + 8, h: q, cx: fly.x - 8 - q - 4, cy: fly.cy } : null; var freeHit = freeSpot ? await pg.evaluate("(function(){ var u=document.elementFromPoint(" + freeSpot.cx + "," + freeSpot.cy + "); return u ? (u.id || u.tagName) : null; })()") : null;
    ok('B2 island (owner hotfix 2026-09-19 §5 / §6): NO generic ATTACK control in the DOM; DASH in the bottom-right corner, GUARD directly left of it; FLY directly above GUARD; ≡ above DASH; the two cells left of FLY are EMPTY (the point there hits ' + freeHit + ' = open world); the category label under the slots spans the 4-slot arc; the four quick slots as an arc (2 · 3 higher than 1 · 4) are the attack controls; ⚔ above slot 4',
      noAtt && dash && dash.x + dash.w >= v.w - 12 && dash.y + dash.h >= v.h - 12 && guard && Math.abs(guard.y - dash.y) < 1.5 && Math.abs((guard.x + guard.w) - dash.x + 8) < 1.5 && fly && Math.abs(fly.x - guard.x) < 1.5 && Math.abs((fly.y + fly.h) - guard.y + 8) < 1.5 && menu && Math.abs(menu.cx - dash.cx) < 2 && menu.y + menu.h < dash.y && freeHit && /tc-world|CANVAS|BODY|tc-cam/i.test(freeHit) && cat && cat.shown && Math.abs(cat.w - (4 * q + 24)) < 2 && slots.length === 4 && slots.every(function (s) { return s.shown && s.y + s.h <= cat.y + 0.5; }) && slots[1].y < slots[0].y - 4 && slots[2].y < slots[3].y - 4 && Math.abs(slots[0].y - slots[3].y) < 1.5 && sword && Math.abs(sword.cx - slots[3].cx) < 3 && sword.y + sword.h <= slots[3].y + 0.5,
      { no_generic_attack: noAtt, dash: dash, guard: guard, fly: fly, menu: menu, free_cells: freeSpot, free_hit: freeHit, cat: cat, slots: slots.map(function (s) { return [Math.round(s.x), Math.round(s.y), Math.round(s.w), Math.round(s.h)]; }), sword: sword });
    /* ── B3 visible faces vs hit bounds (measured by elementFromPoint outward from each edge) ── */
    var H = {}; for (var hid of ['g-mapbt', 'g-speed', 'g-camreset', 'g-fly', 'g-guard', 'g-menubt', 'g-swordbt', 'tc-dash']) H[hid] = await halo(hid); var sh = await pg.evaluate("(function(){ var e=document.querySelector('#g-erty-t .gq'); if(!e) return null; var r=e.getBoundingClientRect(); function hit(x,y){ var u=document.elementFromPoint(x,y); return !!(u && (u===e || e.contains(u))); } function reach(dx,dy){ var n=0; for(var k=1;k<=9;k++){ var x=dx<0?Math.round(r.left)-k:(dx>0?Math.round(r.right)+k-1:Math.round(r.left+r.width/2)), y=dy<0?Math.round(r.top)-k:(dy>0?Math.round(r.bottom)+k-1:Math.round(r.top+r.height/2)); if(hit(x,y)) n=k; else break; } return n; } return {id:'slot1',vis:[Math.round(r.width),Math.round(r.height)],halo:{l:reach(-1,0),r:reach(1,0),t:reach(0,-1),b:reach(0,1)},centre:hit(r.left+r.width/2,r.top+r.height/2)}; })()"); H.slot1 = sh; report.halos = H;
    var faces42 = ['g-mapbt', 'g-speed', 'g-camreset', 'g-fly', 'g-guard', 'tc-dash'].every(function (k) { return H[k] && H[k].vis[0] >= 41 && H[k].vis[0] <= 43 && H[k].vis[1] >= 41 && H[k].vis[1] <= 43; }); var face36 = ['g-menubt', 'g-swordbt'].every(function (k) { return H[k] && H[k].vis[0] >= 35 && H[k].vis[0] <= 37; });
    var halos4 = Object.keys(H).every(function (k) { var hh = H[k] && H[k].halo; return hh && hh.l === 4 && hh.r === 4 && hh.t === 4 && hh.b === 4 && H[k].centre; });   /* the disclosed halo: 4 px each side (left / right exact; top / bottom ≥ 3 where a neighbour's halo touches) */
    ok('B3 visible faces 42 px (cells), 36 px (≡ · ⚔); HIT bounds = face + a 4 px halo on every side (measured: every control answers 4 px outside its face, never more) → cells 50 × 50, ≡ / ⚔ 44 × 44', faces42 && face36 && halos4 && sh && sh.vis[0] >= 41 && sh.vis[0] <= 43, H);
    /* ── B4 hit halos of neighbours touch but never overlap; no control overlaps another's face ── */
    var ctl = { map: map, spd: spd, cam: cam, fly: fly, guard: guard, menu: menu, sword: sword, dash: dash, cat: cat }; slots.forEach(function (s, i) { ctl['slot' + (i + 1)] = s; }); var ks = Object.keys(ctl); var faceOv = [], haloOv = [];
    for (var i = 0; i < ks.length; i++) for (var j = i + 1; j < ks.length; j++) { var a1 = ovArea(ctl[ks[i]], ctl[ks[j]]); if (a1 > 0.5) faceOv.push(ks[i] + '×' + ks[j] + ':' + Math.round(a1)); var a2 = ovArea(grow(ctl[ks[i]], ks[i] === 'cat' ? 0 : 4), grow(ctl[ks[j]], ks[j] === 'cat' ? 0 : 4)); if (a2 > 0.5) haloOv.push(ks[i] + '×' + ks[j] + ':' + Math.round(a2)); }
    ok('B4 no control face overlaps another and no two hit halos overlap (8 px gaps: halos touch at most)', faceOv.length === 0 && haloOv.length === 0, { faces: faceOv, halos: haloOv });
    /* ── B5 the left arc over the joystick; the stick slightly larger; the arc wins its taps over the stick zone ── */
    var mapHit = await pg.evaluate("(function(){ var e=document.getElementById('g-mapbt'); var r=e.getBoundingClientRect(); var u=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2); return u? (u.id||u.tagName):null; })()");
    ok('B5 left arc: MAP · SPEED · CAM sit above the joystick ring (SPEED 6 px higher = the shallow arc, mirrored), all left of the island, MAP answers its own tap inside the stick zone; the ring is ' + (stick ? Math.round(stick.w) : '?') + ' px (' + (MODE === 'portrait' ? '124' : '108') + ' expected, was 112 / 96)', map && spd && cam && stick && Math.min(map.y + map.h, spd.y + spd.h, cam.y + cam.h) <= stick.y + 2 && spd.y < map.y - 4 && Math.abs(map.y - cam.y) < 1.5 && Math.max(map.x + map.w, spd.x + spd.w, cam.x + cam.w) < Math.min(fly.x, slots[0].x) - 8 && mapHit === 'g-mapbt' && Math.abs(stick.w - (MODE === 'portrait' ? 124 : 108)) < 1.5, { map: map, spd: spd, cam: cam, stick: stick, map_hit: mapHit });
    ok('B6 the four quick-slot labels are the authored short forms and none overflows a 42 px face', slots.length === 4 && slots.every(function (s) { return !s.overflow; }), slots.map(function (s) { return [s.small, s.overflow]; }));
    /* ── B7 functions: tap slot 1 executes; hold slot 2 arms it; the label cycles the category; ⚔ opens COMBAT ── */
    var before = await ev("var r=P.snap().play.rules; return (r.skills[r.me.category]||[]).map(function(s){ return s.availability; });"); await pg.evaluate("(function(){ var e=document.querySelector('#g-erty-t .gq'); var r=e.getBoundingClientRect(); ['pointerdown','pointerup'].forEach(function(t){ e.dispatchEvent(new PointerEvent(t,{pointerId:7,pointerType:'touch',isPrimary:true,clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true,cancelable:true,button:0})); }); return 1; })()"); var after = null, castSeen = null; for (var pw = 0; pw < 30; pw++) { await sleep(40); var obs = await ev("var r=P.snap().play.rules; return { av: (r.skills[r.me.category]||[]).map(function(s){ return s.availability; }), cast: r.me.cast ? r.me.cast.skill + ':' + r.me.cast.phase : null };"); if (obs.cast || obs.av[0] !== 'READY') { after = obs.av; castSeen = obs.cast; break; } }   /* the PHYSICAL push is back to READY within ~0.7 s (startup 0.22 + recovery 0.38 + cooldown 0.1): observe the cast itself */
    ok('B7a a TAP on quick slot 1 executes it (the cast is observed: ' + castSeen + ')', before[0] === 'READY' && !!(castSeen || (after && after[0] !== 'READY')), { before: before, after: after, cast: castSeen }); await sleep(900);
    await sleep(2200); var sk2 = await ev("var r=P.snap().play.rules; var s=(r.skills[r.me.category]||[])[1]; return s ? { id: s.id, gesture: s.gesture || null, av: s.availability } : null;"); var expDir = sk2 && sk2.gesture && /^(UP|DOWN|LEFT|RIGHT)$/.test(sk2.gesture) ? sk2.gesture : 'DOWN'; var wrongDir = expDir === 'DOWN' ? 'UP' : 'DOWN'; var DV = { UP: [0, -60], DOWN: [0, 60], LEFT: [-60, 0], RIGHT: [60, 0] };
    async function swipeSlot(idx, dir) { var d = DV[dir]; return await pg.evaluate("(function(){ var e=document.querySelectorAll('#g-erty-t .gq')[" + idx + "]; var r=e.getBoundingClientRect(); var cx=r.left+r.width/2, cy=r.top+r.height/2; function ev(t,x,y){ e.dispatchEvent(new PointerEvent(t,{pointerId:9,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,bubbles:true,cancelable:true,button:0})); } ev('pointerdown',cx,cy); ev('pointermove',cx+" + d[0] * 0.5 + ",cy+" + d[1] * 0.5 + "); ev('pointermove',cx+" + d[0] + ",cy+" + d[1] + "); ev('pointerup',cx+" + d[0] + ",cy+" + d[1] + "); return 1; })()"); }
    var wrongRes = sk2 && sk2.gesture && /^(UP|DOWN|LEFT|RIGHT)$/.test(sk2.gesture) ? (await swipeSlot(1, wrongDir), await sleep(250), await ev("var r=P.snap().play.rules; return { cast: r.me.cast ? r.me.cast.skill : null, av: (r.skills[r.me.category]||[])[1].availability, g: P.gesture() };")) : null; await sleep(300);
    await swipeSlot(1, expDir); var cast2 = null; for (var pw2 = 0; pw2 < 30; pw2++) { await sleep(40); var o2 = await ev("var r=P.snap().play.rules; return { cast: r.me.cast ? r.me.cast.skill + ':' + r.me.cast.phase : null, av: (r.skills[r.me.category]||[])[1].availability, g: P.gesture() };"); if (o2.cast || o2.av !== 'READY') { cast2 = o2; break; } }
    ok('B7b a SWIPE from quick slot 2 (' + expDir + ' = its own arrow) executes slot 2 through the one dispatcher (cast observed: ' + (cast2 && cast2.cast) + ', gesture matched)' + (wrongRes ? '; a WRONG swipe (' + wrongDir + ') was refused without a cast' : '; slot 2 accepts any direction'), !!sk2 && !!(cast2 && cast2.cast && /^(PA_|ATHLETE_|PM_)/.test(cast2.cast) && cast2.g && cast2.g.matched === true) && (!wrongRes || (!wrongRes.cast && wrongRes.g && wrongRes.g.matched === false)), { slot2: sk2, expected: expDir, wrong: wrongRes, cast: cast2 }); await sleep(1500);
    var mode0 = await ev("return P.snap().play.rules.me.attack_mode;"); await tapEl('g-catlbl', 7); await sleep(400); var mode1 = await ev("return P.snap().play.rules.me.attack_mode;"); var catTxt = (await rect('g-catlbl')).text; var slotTxt = (await rect('g-erty-t')).text; await tapEl('g-catlbl', 7); await sleep(300); await tapEl('g-catlbl', 7); await sleep(400); var mode3 = await ev("return P.snap().play.rules.me.attack_mode;");
    ok('B7c a tap on the category label cycles the armed category (' + mode0 + ' → ' + mode1 + '), the label and the four slot identities follow (' + catTxt + '); three taps return to ' + mode0, mode1 !== mode0 && mode3 === mode0 && /MAHGIC/.test(catTxt) && slotTxt.length > 0, { modes: [mode0, mode1, mode3], label: catTxt, slots: slotTxt });
    await tapEl('g-swordbt', 7); await sleep(400); var mst = await ev("return P.menu.state();"); var combat = await pg.evaluate("(function(){ var b=document.getElementById('g-menu-body'); if(!b) return null; return {modes:b.querySelectorAll('.mmode').length, rows:b.querySelectorAll('.mrow').length, arm:b.querySelectorAll('[data-m=\"arm\"]').length, armed:b.querySelectorAll('.mrow.armed').length, practice:!!b.querySelector('[data-m=\"practice\"]')}; })()");
    var armBtn = await pg.evaluate("(function(){ var b=document.querySelector('#g-menu-body [data-m=\"arm\"][data-cat=\"PHYSICAL\"]'); if(!b) return null; b.click(); return b.getAttribute('data-slot'); })()"); await sleep(400); var selArm = await ev("var r=P.snap().play.rules; return [r.me.attack_mode, r.me.selection.PHYSICAL];");
    ok('B7d ⚔ opens the menu on COMBAT: the three categories (' + (combat && combat.modes) + '), the 8 equipped rows (' + (combat && combat.rows) + ' rows incl. PRACTICE), ARM buttons, one ARMED row; ARM on a PHYSICAL slot arms it through the one selection function', mst.open && mst.tab === 'COMBAT' && combat && combat.modes === 3 && combat.rows >= 9 && combat.arm >= 6 && combat.armed === 1 && combat.practice && armBtn !== null && selArm[1] === parseInt(armBtn, 10), { menu: mst, combat: combat, arm: armBtn, sel: selArm });
    await pg.screenshot(path.join(OUT, 'hud_b_' + MODE + '_sword.png')); await ev("P.menu.close('probe'); return 1;"); await sleep(300); await ev("P.hud.selectMove('PHYSICAL', 0, 'probe'); return 1;"); await sleep(300);
  } else {
    ok('B2 desktop keeps its bottom bar (E R T Y · MAHGIC · DASH · LOCK, keyboard / mouse bindings) and the right column gains ⚔ beside ≡; the category label sits above the bar', R['g-desk'] && R['g-desk'].shown && R['g-swordbt'] && R['g-swordbt'].shown && R['g-menubt'] && R['g-menubt'].shown && R['g-catlbl'] && R['g-catlbl'].shown && R['g-catlbl'].y + R['g-catlbl'].h <= R['g-desk'].y + 1, { desk: R['g-desk'], sword: R['g-swordbt'], cat: R['g-catlbl'] });
    await pg.evaluate("(function(){ var e=document.getElementById('g-swordbt'); var r=e.getBoundingClientRect(); ['pointerdown','pointerup'].forEach(function(t){ e.dispatchEvent(new PointerEvent(t,{pointerId:9,pointerType:'mouse',isPrimary:true,clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true,cancelable:true,button:0})); }); return 1; })()"); await sleep(400); var mst2 = await ev("return P.menu.state();"); var combat2 = await pg.evaluate("(function(){ var b=document.getElementById('g-menu-body'); return b?{modes:b.querySelectorAll('.mmode').length, arm:b.querySelectorAll('[data-m=\"arm\"]').length}:null; })()");
    ok('B7d ⚔ opens the menu on COMBAT with the three categories and ARM buttons (desktop)', mst2.open && mst2.tab === 'COMBAT' && combat2 && combat2.modes === 3 && combat2.arm >= 6, { menu: mst2, combat: combat2 }); await pg.screenshot(path.join(OUT, 'hud_b_' + MODE + '_sword.png')); await ev("P.menu.close('probe'); return 1;"); await sleep(300);
  }
  /* ── B8 world-space tag: LV above the dummy in free roam; LV + LOCKED (gold) + the health bar in practice; the bar hides again in free roam ── */
  var dummy = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){ return o.id==='FIELD_DUMMY'; })[0] || null;");
  await ev("return P.goTo(" + dummy.position.x + ", " + (dummy.position.z + 3.2) + ", undefined, undefined, 60000);"); await sleep(400); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); return 1;"); await sleep(500); await ev("return P.camReset('probe');"); await sleep(900);
  var tagFree = await ev("var e=P.entity('other:FIELD_DUMMY'); return e?{lvl:!!(e.lvl&&e.lvl.visible), text:e.tagText||null, bar:!!(e.bar&&e.bar.visible), name:!!(e.label&&e.label.visible)}:null;");
  await ev("P.send('FIELD_PRACTICE',{on:true}); return 1;"); await sleep(300); await ev("return P.send('LOCK_TARGET',{aim_id:'FIELD_DUMMY'});"); await sleep(500); var tagLock = await ev("var e=P.entity('other:FIELD_DUMMY'); return e?{lvl:!!(e.lvl&&e.lvl.visible), text:e.tagText||null, bar:!!(e.bar&&e.bar.visible), gold:e.lvlColor||null}:null;"); var lockPanel = await rect('g-target'); var st2 = (await rect('g-state')).text;
  await pg.screenshot(path.join(OUT, 'hud_b_' + MODE + '_lock.png'));
  await ev("P.send('LOCK_TARGET',{aim_id:null}); P.send('FIELD_PRACTICE',{on:false}); return 1;"); await sleep(500); var tagAfter = await ev("var e=P.entity('other:FIELD_DUMMY'); return e?{lvl:!!(e.lvl&&e.lvl.visible), text:e.tagText||null, bar:!!(e.bar&&e.bar.visible)}:null;");
  ok('B8 world-space tag on the dummy: free roam = "' + (tagFree && tagFree.text) + '" without a bar; PRACTICE + lock = "' + (tagLock && tagLock.text) + '" in gold WITH the health bar and the state line "' + st2 + '"; no LOCKED panel anywhere; unlock + practice off = "' + (tagAfter && tagAfter.text) + '" without a bar', tagFree && tagFree.lvl && /^LV \d+$/.test(tagFree.text) && !tagFree.bar && tagFree.name && tagLock && /^LV \d+ · LOCKED/.test(tagLock.text) && tagLock.bar && tagLock.gold === '#ffd15e' && !lockPanel && /PRACTICE/.test(st2) && tagAfter && /^LV \d+$/.test(tagAfter.text) && !tagAfter.bar, { free: tagFree, lock: tagLock, after: tagAfter, panel: lockPanel, state: st2 });
  await ev("return P.goTo(20, 30, undefined, undefined, 60000);"); await sleep(600); await ev("return P.camReset('probe');"); await sleep(600);
  if (TOUCH) {
    /* ── B9 DASH from the corner; FLY (hold) from its cell; DOWN · LAND take the free row-D cells; LAND lands ── */
    var d0 = await ev("var p=P.snap().play; return [p.position.x, p.position.z];"); await tapEl('tc-dash', 5); await sleep(900); var d1 = await ev("var p=P.snap().play; return [p.position.x, p.position.z];"); var dashed = Math.hypot(d1[0] - d0[0], d1[1] - d0[1]);
    var f0 = await ev("return P.snap().play.flight;"); var fr = await rect('g-fly'); await ptr('pointerdown', 'g-fly', 3, fr.cx, fr.cy); await sleep(1500); await ptr('pointerup', 'g-fly', 3, fr.cx, fr.cy); await sleep(1500); var f1 = await ev("return P.snap().play.flight;"); var land = await rect('g-land'); var desc = await rect('g-desc'); var guardNow = await rect('g-guard'); var flyNow = await rect('g-fly');
    await pg.screenshot(path.join(OUT, 'hud_b_' + MODE + '_air.png'));
    ok('B9 DASH tap from the corner moves him (' + dashed.toFixed(2) + ' m); hold FLY climbs and the release holds (> 2 m); airborne, DOWN · LAND fill row D\'s free cells left of GUARD (same row, 42 px), FLY never moves', dashed > 1.5 && !f0.powered && f1.powered && f1.altitude > 2 && land && land.shown && desc && desc.shown && Math.abs(land.cy - guardNow.cy) < 1.5 && land.x + land.w <= guardNow.x - 6 && desc.x + desc.w <= land.x && land.h >= 41 && Math.abs(flyNow.cx - fr.cx) < 1, { dash_m: +dashed.toFixed(2), f1: f1, land: land, desc: desc, guard: guardNow });
    await tapEl('g-land', 8); for (var qq = 0; qq < 40; qq++) { var fq = await ev("return P.snap().play.flight;"); if (!fq.powered) break; await sleep(250); } await sleep(500); var f2 = await ev("return P.snap().play.flight;"); var landGone = await rect('g-land'); ok('B9b LAND lands; DOWN · LAND hide again', !f2.powered && (!landGone || !landGone.shown), { f2: f2 });
    /* ── B10 his framed body vs the thumb groups; the contextual prompt at the tree elevator ── */
    await sleep(400); var meBox = await ev("var b=P.screenBox(); return b?{x:b.left,y:b.top,w:b.right-b.left,h:b.bottom-b.top,shown:true}:null;"); var over = []; ['g-fly', 'g-guard', 'tc-dash', 'g-catlbl', 'g-mapbt', 'g-speed', 'g-camreset', 'tc-stick'].forEach(function (k) { var a = ovArea(meBox, R[k]); if (a > 0.5) over.push(k + ':' + Math.round(a)); }); var slotOver = slots.map(function (s, i) { var a = ovArea(meBox, s); return a > 0.5 ? 'slot' + (i + 1) + ':' + Math.round(a) : null; }).filter(Boolean);
    ok('B10 the framed character (rear view, standing) is not under the island or the left arc — reported, not forced: overlaps ' + JSON.stringify(over.concat(slotOver)), !!meBox && over.length === 0 && slotOver.length === 0, { him: meBox, overlaps: over.concat(slotOver) });
    await ev("return P.goTo(26.6, 41.3, undefined, undefined, 60000);"); var ctx = null; for (var w2 = 0; w2 < 30; w2++) { ctx = await rect('g-ctx'); if (ctx && ctx.shown) break; await sleep(100); } var ctxOv = []; if (ctx && ctx.shown) { Object.keys(ctl).forEach(function (k) { var a = ovArea(ctx, ctl[k]); if (a > 0.5) ctxOv.push(k); }); } await sleep(500); var meBox2 = await ev("var b=P.screenBox(); return b?{x:b.left,y:b.top,w:b.right-b.left,h:b.bottom-b.top,shown:true}:null;");
    ok('B11 at the tree elevator the contextual prompt (' + (ctx && ctx.text) + ') appears inside the viewport, ≥ 44 px, over neither thumb group nor the framed character', ctx && ctx.shown && /LIFT/.test(ctx.text) && ctx.h >= 44 && ctx.x >= 0 && ctx.x + ctx.w <= v.w && ctxOv.length === 0 && ovArea(ctx, meBox2) < 0.5, { ctx: ctx, over: ctxOv, him: meBox2 });
    await ev("return P.goTo(20, 30, undefined, undefined, 60000);"); await sleep(600); await ev("return P.camReset('probe');"); await sleep(700);
  }
  await pg.screenshot(path.join(OUT, 'hud_b_' + MODE + '_ground.png'));
  /* ── B12 rollback: ?hud=dock restores the PASS 3 cluster / dock / LOCKED panel (same build) ── */
  if (TOUCH) { await pg.goto(srv.origin + PLAY_PATH + '?field=1&touch=1&hud=dock'); await waitForGame(pg, 120000); await sleep(5000); await ev("P.hud.showGuide(false); return 1;"); var lay2 = await ev("return P.hud.layout();"); var dock2 = await rect('g-dock'); var cl2 = await pg.evaluate("(function(){ var e=document.getElementById('g-cluster'); return getComputedStyle(e).display; })()"); var stick2 = await rect('tc-stick'); var cat2 = await rect('g-catlbl'); await pg.screenshot(path.join(OUT, 'hud_b_' + MODE + '_rollback.png'));
    ok('B12 rollback ?hud=dock: the PASS 3 layout returns (dock shown, cluster grid, 112 px stick, no category label) on the same build', lay2 === 'dock' && dock2 && dock2.shown && cl2 === 'grid' && stick2 && Math.abs(stick2.w - (MODE === 'portrait' ? 112 : 96)) < 1.5 && (!cat2 || !cat2.shown), { layout: lay2, dock: dock2, cluster: cl2, stick: stick2 }); }
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'hud_b_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT HUD PHASE B ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
