/* OWNER HOTFIX 2026-09-19 §2 / §4 — CHARACTER INTACTNESS diagnostic matrix. For each pose the animator is FROZEN (holdPose) at its representative
   frame and shot from FRONT / SIDE / REAR-¾ / REAR in the modes the owner asked for: A production material + VFX · B VFX off · C neutral opaque
   material · E wireframe (topology) · F joints (the shoulder chain's bone world positions drawn as markers, listed in the record). The stills are
   evidence for a human eye (the sheet); the record also carries per-pose numbers: hand / elbow / shoulder world positions, the elbow-to-torso axis
   clearance, and the diagnostics the page exposes. No pass / fail is claimed from a screenshot alone — the classification is written by hand in
   the report after inspection.   node deploy/probe_intactness.mjs [static_dist] [--only pose,pose] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') ? path.resolve(argv[0]) : path.join(HERE, 'static_dist'); var OUT = path.join(HERE, 'probe_out', 'intact'); fs.mkdirSync(OUT, { recursive: true });
var ONLY = argv.indexOf('--only') >= 0 ? argv[argv.indexOf('--only') + 1].split(',') : null;
var srv = await serveStatic(DIST); var USE_GPU = argv.indexOf('--soft') < 0; var pg = await launchChrome({ width: 760, height: 760, gpu: USE_GPU, unlockFps: true });   /* GPU by default (~10 min for the matrix); --soft = SwiftShader (~5 min per pose, immune to the GPU-process crashes that blanked 198 frames on 2026-09-19 while another project's headless soak shared the GPU); every shot is checked for a blank frame and retried */ var report = { poses: {} }; var shots = [];
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
var blanks = []; async function waitFrames(n, ms) { var f0 = await ev("if (window.__fc === undefined) { window.__fc = 0; (function loop(){ window.__fc++; requestAnimationFrame(loop); })(); } return window.__fc;"); var t0 = Date.now(); while (Date.now() - t0 < (ms || 8000)) { await sleep(60); var f1 = await ev("return window.__fc;"); if (f1 - f0 >= n) return true; } return false; }   /* the camera / material change must be RENDERED before the screenshot (software frames can take hundreds of ms) */
async function shot(tag) { var f = path.join(OUT, tag + '.png'); await pg.screenshot(f); for (var rt = 0; rt < 6 && fs.statSync(f).size < 12000; rt++) { await sleep(1000); await waitFrames(2, 3000); await pg.screenshot(f); } if (fs.statSync(f).size < 12000) { blanks.push(tag); console.log('BLANK frame', tag, fs.statSync(f).size, 'bytes after 6 retries (a lost GPU context renders only the clear colour) — reshoot with --only or --soft'); } shots.push({ tag: tag, f: f }); return f; }   /* 2026-09-19: one full run went blank from a pose onward while another project's headless soak ran on the same GPU */
var ANGLES = { front: [Math.PI, 0.06], side: [Math.PI / 2, 0.05], rear34: [Math.PI * 0.25, 0.12], rear: [0, 0.08] };
async function hideHud(on) { await ev("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='" + (on ? 'hidden' : '') + "'; }); return 1;"); }
async function geo() { return await ev("var W={}; ['CLAV_L','CLAV_R','SCAP_L','SCAP_R','UPPERARM_L','UPPERARM_R','ARMTWIST_L','ARMTWIST_R','FOREARM_L','FOREARM_R','HAND_L','HAND_R','CHEST','SPINE','PELVIS','HEAD'].forEach(function(k){ W[k]=P.boneWorld(k); }); function dseg(p,a,b){ var ab=[b[0]-a[0],b[1]-a[1],b[2]-a[2]], ap=[p[0]-a[0],p[1]-a[1],p[2]-a[2]]; var l2=ab[0]*ab[0]+ab[1]*ab[1]+ab[2]*ab[2]; var t=l2>0?Math.max(0,Math.min(1,(ap[0]*ab[0]+ap[1]*ab[1]+ap[2]*ab[2])/l2)):0; return Math.hypot(a[0]+ab[0]*t-p[0], a[1]+ab[1]*t-p[1], a[2]+ab[2]*t-p[2]); } var out={W:W}; if (W.PELVIS&&W.HEAD) { out.elbowL_axis = W.FOREARM_L? +dseg(W.FOREARM_L,W.PELVIS,W.HEAD).toFixed(3):null; out.elbowR_axis = W.FOREARM_R? +dseg(W.FOREARM_R,W.PELVIS,W.HEAD).toFixed(3):null; out.handL_axis = W.HAND_L? +dseg(W.HAND_L,W.PELVIS,W.HEAD).toFixed(3):null; out.handR_axis = W.HAND_R? +dseg(W.HAND_R,W.PELVIS,W.HEAD).toFixed(3):null; out.upperarm_len_L = (W.UPPERARM_L&&W.FOREARM_L)? +Math.hypot(W.UPPERARM_L[0]-W.FOREARM_L[0],W.UPPERARM_L[1]-W.FOREARM_L[1],W.UPPERARM_L[2]-W.FOREARM_L[2]).toFixed(3):null; out.upperarm_len_R = (W.UPPERARM_R&&W.FOREARM_R)? +Math.hypot(W.UPPERARM_R[0]-W.FOREARM_R[0],W.UPPERARM_R[1]-W.FOREARM_R[1],W.UPPERARM_R[2]-W.FOREARM_R[2]).toFixed(3):null; out.shoulder_gap = (W.UPPERARM_L&&W.UPPERARM_R)? +Math.hypot(W.UPPERARM_L[0]-W.UPPERARM_R[0],W.UPPERARM_L[1]-W.UPPERARM_R[1],W.UPPERARM_L[2]-W.UPPERARM_R[2]).toFixed(3):null; } var e=P.entity('me'); var an=e&&e.fused&&e.fused.animator; if (an) { var pz=an.pose(); out.pose={}; ['CLAV_L','SCAP_L','UPPERARM_L','ARMTWIST_L','FOREARM_L','CLAV_R','SCAP_R','UPPERARM_R','ARMTWIST_R','FOREARM_R','CHEST','SPINE'].forEach(function(k){ if (pz[k]) out.pose[k]=pz[k].map(function(v){return +v.toFixed(2);}); }); if (an.alive) out.clearance_fixes = an.alive().clearance_fixes; if (an.armDebug) out.arm = an.armDebug(); } return out;"); }
var NANWATCH = argv.indexOf('--nanwatch') >= 0; async function nanCheck(where) { if (!NANWATCH) return; var rows = await ev("var r=window.__nan||[]; window.__nan=[]; return r;"); var bad = -1; for (var i = 0; i < rows.length; i++) { var r = rows[i]; if (r.err || !Number.isFinite(r.ry) || !Number.isFinite(r.cam) || !Number.isFinite(r.cx) || (r.gp && (!Number.isFinite(r.gp[0]) || !Number.isFinite(r.gp[1])))) { bad = i; break; } } if (bad >= 0) { console.log('NAN at', where, 'row', bad, 'of', rows.length); for (var k = Math.max(0, bad - 5); k < Math.min(rows.length, bad + 3); k++) console.log('  ', k, JSON.stringify(rows[k]).slice(0, 600)); } else console.log('nan-ok', where, rows.length, 'rows'); }
async function matrix(tag, modes) { var yaw0 = (await ev("return P.mePose().root_yaw;")) || 0; if (NANWATCH) console.log('matrix', tag, 'yaw0', yaw0, 'cam', JSON.stringify(await ev("var c=P.camState(); return [c.yaw,c.pitch,c.applied];"))); var rec = { shots: {}, geo: await geo() }; await hideHud(true);
  for (var mode of modes) { if (mode === 'A') { await ev("P.vfx(true); P.shadeMode('production'); return 1;"); } else if (mode === 'B') { await ev("P.vfx(false); P.shadeMode('production'); return 1;"); } else if (mode === 'C') { await ev("P.vfx(false); P.shadeMode('neutral'); return 1;"); } else if (mode === 'E') { await ev("P.vfx(false); P.shadeMode('wire'); return 1;"); } await waitFrames(2, 8000);
    for (var an of Object.keys(ANGLES)) { await ev("P.cam(" + (yaw0 + ANGLES[an][0]) + ", " + ANGLES[an][1] + ", 2.6, 1.15); return 1;"); await waitFrames(3, 8000); rec.shots[mode + '_' + an] = path.basename(await shot(tag + '_' + mode + '_' + an)); rec.cam = rec.cam || {}; rec.cam[mode + '_' + an] = await ev("var c=P.camState(); var r=P.meRoot(); var e=P.entity('me'); var g=e&&e.fused&&e.fused.group; return { applied: +c.applied.toFixed(2), dist: c.dist, obstructed: c.obstructed, fade: c.fade, yaw: +c.yaw.toFixed(2), pitch: c.pitch, root: r ? [+r.position.x.toFixed(2), +r.position.y.toFixed(2), +r.position.z.toFixed(2)] : null, grp_vis: g ? g.visible : null, grp_scale: g ? +g.scale.x.toFixed(3) : null, hold: !!(e && e.holdPose) };   /* never P.holdPose('me') here: the setter form with `on` undefined RELEASES the hold */"); }
    /* the shoulder CLOSE-UPS (owner §2: clavicle / deltoid / armpit / pec boundary): a 1.5 m boom on the shoulder line, production + neutral, three angles */
    if (mode === 'A' || mode === 'C') for (var an2 of ['front', 'side', 'rear34']) { await ev("P.cam(" + (yaw0 + ANGLES[an2][0]) + ", " + (ANGLES[an2][1] - 0.02) + ", 1.9, 1.38); return 1;"); await waitFrames(3, 8000); rec.shots[mode + '_close_' + an2] = path.basename(await shot(tag + '_' + mode + '_close_' + an2)); } }
  await ev("P.vfx(true); P.shadeMode('production'); return 1;"); await hideHud(false); report.poses[tag] = rec; await nanCheck('after ' + tag); console.log('pose', tag, 'shoulder chain', JSON.stringify({ elbowL_axis: rec.geo.elbowL_axis, elbowR_axis: rec.geo.elbowR_axis, handL_axis: rec.geo.handL_axis, handR_axis: rec.geo.handR_axis, ua_len: [rec.geo.upperarm_len_L, rec.geo.upperarm_len_R], fixes: rec.geo.clearance_fixes })); }
async function freezeAt(setup, ms) { await setup(); await sleep(ms); await ev("P.holdPose('me', true); return 1;"); await sleep(120); }
async function release() { await ev("P.holdPose('me', false); return 1;"); await sleep(1500); }
async function castSlot(cat, slot) { await ev("P.send('RULES_SELECT',{category:'" + cat + "',slot:" + slot + "}); return 1;"); await sleep(100); return await ev("return P.send('RULES_CAST',{});"); }
var MODES = ['A', 'B', 'C', 'E'];
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(4500); await ev("P.hud.showGuide(false); P.hud.setDev && P.hud.setDev(false); if (P.camFollow) P.camFollow(false); return 1;");
  for (var w0 = 0; w0 < 120; w0++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); }
  if (NANWATCH) await ev("window.__nan = []; window.__nanT0 = performance.now(); (function loop(){ try { var e=P.entity('me'); var c=P.camState(); var pl=P.snap().play; var cp=P.camPos?P.camPos():null; window.__nan.push({ t: +(performance.now()-window.__nanT0).toFixed(0), ry: e?e.root.rotation.y:null, yv: e?e.yawVel:null, facing: pl.facing, cam: c?c.yaw:null, cx: c?c.applied:null, hold: e?!!e.holdPose:null, cast: pl.rules&&pl.rules.me.cast?pl.rules.me.cast.skill+':'+pl.rules.me.cast.phase:null, gp: e?[e.fused.group.position.y, e.fused.group.position.z]:null, fixed: c && c.fixed ? JSON.stringify(c.fixed) : null }); } catch(err) { window.__nan.push({ err: String(err) }); } if (window.__nan.length < 20000) requestAnimationFrame(loop); })(); return 1;");
  await ev("P.send('FIELD_PRACTICE',{on:true}); return 1;"); var dummy = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0];");
  async function face(dz) { await ev("return P.goTo(" + dummy.position.x + ", " + (dummy.position.z + dz) + ", undefined, undefined, 40000);"); await sleep(250); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); return 1;"); await sleep(800); }
  await ev("return P.send('RULES_LOADOUT',{category:'SPECIAL_MAGIC',slot:1,skill_id:'ATHLETE_OVERHEAD_RELEASE'});"); await ev("return P.send('RULES_LOADOUT',{category:'PHYSICAL_MAGIC',slot:1,skill_id:'PM_CURL_BARRAGE'});");
  var want = function (k) { return !ONLY || ONLY.indexOf(k) >= 0; };
  await face(2.2);
  if (want('idle')) { await freezeAt(async function () { }, 400); await matrix('idle', MODES); await release(); }
  if (want('push_release')) { await freezeAt(async function () { await castSlot('PHYSICAL', 0); }, 560); await matrix('push_release', MODES); await release(); await sleep(1200); }   /* PA_PUSH: startup 0.22 → the release whip ≈ 0.22 + 0.12 delay + ~0.2 */
  if (want('push_load')) { await freezeAt(async function () { await castSlot('PHYSICAL', 0); }, 300); await matrix('push_load', MODES); await release(); await sleep(1200); }
  if (want('pull_release')) { await freezeAt(async function () { await castSlot('PHYSICAL', 1); }, 560); await matrix('pull_release', MODES); await release(); await sleep(1200); }
  if (want('hinge_load')) { await freezeAt(async function () { await castSlot('PHYSICAL', 2); }, 380); await matrix('hinge_load', MODES); await release(); await sleep(1200); }
  if (want('rotation_release')) { await freezeAt(async function () { await castSlot('PHYSICAL', 3); }, 560); await matrix('rotation_release', MODES); await release(); await sleep(1200); }
  if (want('overhead_load')) { await face(4.0); await freezeAt(async function () { await castSlot('SPECIAL_MAGIC', 1); }, 700); await matrix('overhead_load', MODES); await release(); await sleep(1400); }
  if (want('overhead_release')) { await freezeAt(async function () { await castSlot('SPECIAL_MAGIC', 1); }, 1120); await matrix('overhead_release', MODES); await release(); await sleep(4200); }
  await ev("return P.send('RULES_LOADOUT',{category:'SPECIAL_MAGIC',slot:1,skill_id:'ATHLETE_CHEST_FLY_CLAP'});"); await sleep(300);
  if (want('fly_load')) { await freezeAt(async function () { await castSlot('SPECIAL_MAGIC', 1); }, 800); await matrix('chestfly_load', MODES); await release(); await sleep(1400); }
  if (want('fly_clap')) { await freezeAt(async function () { await castSlot('SPECIAL_MAGIC', 1); }, 1220); await matrix('chestfly_clap', MODES); await release(); await sleep(4500); }
  if (want('curl')) { await face(2.2); await freezeAt(async function () { await castSlot('PHYSICAL_MAGIC', 1); }, 760); await matrix('curl_strike', MODES); await release(); await sleep(1500); }
  if (want('guard')) { await freezeAt(async function () { await ev("P.send('GUARD',{kind:'PHYSICAL'}); return 1;"); }, 500); await matrix('guard', MODES); await release(); await ev("P.send('GUARD',{kind:'NONE'}); return 1;"); await sleep(500); }
  if (want('dash')) { await freezeAt(async function () { await ev("P.send('DASH',{dir:'FORWARD'}); return 1;"); }, 120); await matrix('dash', MODES); await release(); await sleep(1200); }
  if (want('emote')) { await freezeAt(async function () { await ev("P.send('EMOTE',{emote_id:'DOUBLE_BICEPS'}); return 1;"); }, 900); await matrix('emote_double_biceps', MODES); await release(); await ev("P.send('EMOTE_STOP',{}); return 1;"); await sleep(800); }
  if (want('flight')) { await ev("P.send('FLIGHT',{op:'ENTER'}); return 1;"); await sleep(1800); await ev("P.send('FLIGHT',{op:'HOVER'}); return 1;"); await sleep(600); await ev("P.send('MOVE',{forward:1,strafe:0,run:false,fast:false,yaw:0}); return 1;"); await freezeAt(async function () { }, 1600); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,fast:false,yaw:0}); return 1;"); await matrix('flight_cruise', MODES); await release(); await ev("P.send('MOVE',{forward:1,strafe:0,run:false,fast:true,yaw:0}); return 1;"); await freezeAt(async function () { }, 1400); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,fast:false,yaw:0}); return 1;"); await matrix('flight_boost', MODES); await release(); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); P.send('FLIGHT',{op:'EXIT'}); return 1;"); await sleep(3000); }
  if (want('split')) { await ev("return P.goTo(60, -45, undefined, undefined, 60000);"); await sleep(300); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-1.5708}); return 1;"); await sleep(900);   /* the open strip north of the plaza: the walk leg never meets a wall (the practice spot's leg walked into the hall) */ await ev("return P.send('TRANSFORM',{to:'SPLIT'});"); await sleep(1300); await freezeAt(async function () { }, 0); await matrix('split_mid', MODES); await release(); await sleep(1600); await ev("P.send('MOVE',{forward:1,strafe:0,run:false,yaw:-1.5708}); return 1;"); await freezeAt(async function () { }, 1400); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-1.5708}); return 1;"); await matrix('split_walk', MODES);   /* the pose is frozen in the animator; the host stops so the 40 s matrix never walks him into a wall (the boom collapsed inside the body) */ await release(); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); return 1;"); await sleep(600); await ev("return P.send('TRANSFORM',{to:'FUSED'});"); await sleep(2600); }
  report.errors = pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 5); report.blank_frames = blanks; report.webgl = await ev("var c=document.querySelector('canvas'); var gl=c&&(c.getContext('webgl2')||c.getContext('webgl')); return gl ? { lost: gl.isContextLost() } : null;");
} catch (e) { report.exception = String(e && e.stack || e); console.error(e); }
finally { await pg.close(); srv.close(); }
try { var pg2 = await launchChrome({ width: 2200, height: 1800, gpu: false }); var poses = Object.keys(report.poses); var pages = []; poses.forEach(function (pz) { var html = '<html><body style="margin:0;background:#0b0f16;color:#eef;font:600 13px system-ui"><div style="padding:6px 10px">INTACTNESS · ' + pz + ' · rows: A production + VFX · B VFX off · C neutral opaque · E wireframe · columns: front · side · rear-¾ · rear · frozen frame, MANUAL LOOK</div>' + MODES.map(function (m) { return '<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:3px;padding:3px">' + Object.keys(ANGLES).map(function (an) { var f = report.poses[pz].shots[m + '_' + an]; return f ? '<div><div style="padding:2px 4px;color:#fd9">' + m + ' ' + an + '</div><img src="file:///' + path.join(OUT, f).replace(/\\/g, '/') + '" style="width:100%"></div>' : ''; }).join('') + '</div>'; }).join('') + '<div style="display:grid;grid-template-columns:repeat(6,1fr);gap:3px;padding:3px">' + ['A', 'C'].map(function (m) { return ['front', 'side', 'rear34'].map(function (an) { var f = report.poses[pz].shots[m + '_close_' + an]; return f ? '<div><div style="padding:2px 4px;color:#9fd">' + m + ' CLOSE ' + an + '</div><img src="file:///' + path.join(OUT, f).replace(/\\/g, '/') + '" style="width:100%"></div>' : ''; }).join(''); }).join('') + '</div></body></html>'; var hp = path.join(OUT, '_sheet_' + pz + '.html'); fs.writeFileSync(hp, html); pages.push([pz, hp]); });
  for (var pp of pages) { await pg2.goto('file:///' + pp[1].replace(/\\/g, '/')); await sleep(900); await pg2.screenshot(path.join(OUT, 'sheet_intact_' + pp[0] + '.png')); } await pg2.close(); console.log('sheets', pages.length); } catch (e) { console.log('sheet failed', e.message); }
if (ONLY) { try { var prev = JSON.parse(fs.readFileSync(path.join(OUT, 'probe_intactness.json'), 'utf8')); Object.keys(report.poses).forEach(function (k) { prev.poses[k] = report.poses[k]; }); prev.blank_frames = (prev.blank_frames || []).filter(function (b) { return !Object.keys(report.poses).some(function (k) { return b.indexOf(k + '_') === 0; }); }).concat(report.blank_frames || []); prev.errors = report.errors; report = prev; } catch (e) { } }   /* --only merges into the existing record */
fs.writeFileSync(path.join(OUT, 'probe_intactness.json'), JSON.stringify(report, null, 1)); console.log('RESULT INTACTNESS matrix recorded: ' + Object.keys(report.poses).length + ' poses × ' + MODES.length + ' modes × 4 angles (+ close-ups) · blank frames: ' + ((report.blank_frames || []).length));
