/* CONVERGENCE PASS 3 — class-authored compact HUD (O3 / O4 / O9) in the real page.
   Layout (touch): right-thumb cluster of 50 px bevelled cells above the 1–4 row — GUARD · DASH · FLY / ATTACK · MAHGIC · – / (air) – · DOWN · LAND / MAP · + · CAM;
   no permanent USE (a contextual prompt only for a world interaction in reach); class tokens follow the LOCAL player’s class; `+` = sustained faster travel
   toggle; MAP one tap; one utility sheet (≡ menu tabs EMOTES / LOADOUT / SETTINGS); no keyboard hints on touch; a distinct state matrix.
   node deploy/probe_hud_pass3.mjs [static_dist] [desktop|portrait|landscape]   Touch = EMULATED. */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') && !/^(desktop|portrait|landscape)$/.test(argv[0]) ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
var MODE = argv.filter(function (a) { return /^(portrait|desktop|landscape)$/.test(a); })[0] || 'portrait'; var OUT = path.join(HERE, 'probe_out', 'hud'); fs.mkdirSync(OUT, { recursive: true }); var TOUCH = MODE !== 'desktop'; var VP = MODE === 'portrait' ? [390, 844] : (MODE === 'landscape' ? [844, 390] : [1200, 750]);
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, unlockFps: true, mobile: TOUCH }); var pass = 0, fail = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 700)); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function ptr(type, el, id, x, y) { await pg.evaluate("(function(){ var t=document.getElementById('" + el + "'); if(!t) return 0; var e=new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'touch',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true}); t.dispatchEvent(e); })(); 1"); }
async function tapEl(id, pid) { var r = await rect(id); if (!r || !r.shown) return null; await ptr('pointerdown', id, pid || 7, r.cx, r.cy); await sleep(50); await ptr('pointerup', id, pid || 7, r.cx, r.cy); await sleep(150); return r; }
async function clickEl(id) { return await pg.evaluate("(function(){ var e=document.getElementById('" + id + "'); if(!e) return null; var r=e.getBoundingClientRect(); ['pointerdown','pointerup'].forEach(function(t){ e.dispatchEvent(new PointerEvent(t,{pointerId:9,pointerType:'mouse',isPrimary:true,clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true,cancelable:true,button:0})); }); return 1; })()"); }
async function rect(id) { return await pg.evaluate("(function(){ var e=document.getElementById('" + id + "'); if(!e) return null; var r=e.getBoundingClientRect(); var cs=getComputedStyle(e); return {id:'" + id + "',x:r.left,y:r.top,w:r.width,h:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2,shown:r.width>0&&r.height>0&&cs.display!=='none'&&cs.visibility!=='hidden'}; })()"); }
async function vw() { return await pg.evaluate("({w:innerWidth,h:innerHeight})"); }
function overlap(a, b) { return a && b && a.shown && b.shown && a.x < b.x + b.w - 0.5 && b.x < a.x + a.w - 0.5 && a.y < b.y + b.h - 0.5 && b.y < a.y + a.h - 0.5; }
async function pos() { return await ev("var p=P.snap().play; return [p.position.x, p.position.z];"); }
var report = { mode: MODE, viewport: VP, touch_emulated: TOUCH, checks: lines, rects: {} };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(6000); await ev("P.hud.showGuide(false); return 1;");
  await ev("return P.goTo(20, 30, undefined, undefined, 60000);"); await sleep(800); var v = await vw();
  var ids = ['g-menubt', 'g-mapbt', 'g-speed', 'g-camreset', 'g-fly', 'g-guard', 'g-mahgic', 'g-land', 'g-desc', 'g-ctx', 'tc-attack', 'tc-dash', 'tc-stickzone', 'g-erty-t', 'g-vitals', 'g-dock']; var R = {}; for (var id of ids) R[id] = await rect(id); report.rects.ground = R;
  var controls = ['g-menubt', 'g-mapbt', 'g-speed', 'g-camreset', 'g-fly', 'g-guard', 'g-mahgic'].concat(TOUCH ? ['tc-attack', 'tc-dash'] : []);
  /* ── L1 layout: every control present, ≥ 44 px, inside the viewport, no overlaps (controls vs controls, vs the stick zone, vs the 1–4 row, vs the vitals / dock) ── */
  var missing = controls.filter(function (k) { return !R[k] || !R[k].shown; }); var small = controls.filter(function (k) { return R[k] && R[k].shown && (R[k].w < 44 || R[k].h < 44); }); var outside = controls.filter(function (k) { var r = R[k]; return r && r.shown && (r.x < -0.5 || r.y < -0.5 || r.x + r.w > v.w + 0.5 || r.y + r.h > v.h + 0.5); });
  var clashes = []; var all = controls.concat(['tc-stickzone', 'g-erty-t', 'g-vitals', 'g-dock']); var byDesign = { 'g-menubt×tc-stickzone': 1, 'g-menubt×g-erty-t': 1, 'tc-stickzone×g-erty-t': 1 };   /* the owner's layout puts the ≡ menu and the 1–4 row at the very bottom INSIDE the stick zone's rectangle; HUD controls win the touch (z 7 > 4) and the row's padding reserves the ≡ spot — checked separately below */ for (var i = 0; i < all.length; i++) for (var j = i + 1; j < all.length; j++) if (overlap(R[all[i]], R[all[j]]) && !byDesign[all[i] + '×' + all[j]]) clashes.push(all[i] + '×' + all[j]);
  var rowBtns = await pg.evaluate("Array.prototype.map.call(document.querySelectorAll('#g-erty-t .gq'), function(e){ var r=e.getBoundingClientRect(); return {x:r.left,y:r.top,w:r.width,h:r.height,shown:r.width>0}; })"); var rowClash = rowBtns.filter(function (b) { return overlap(b, R['g-menubt']); }).length; if (TOUCH) ok('L1a the four power buttons never overlap the ≡ menu (the row pads its left end)', rowBtns.length === 4 && rowClash === 0, { row_buttons: rowBtns.length, clashes_with_menu: rowClash });
  ok('L1 every control exists, ≥ 44 px, inside the viewport, and nothing overlaps (controls · stick zone · 1–4 row · vitals · dock)', missing.length === 0 && small.length === 0 && outside.length === 0 && clashes.length === 0, { missing: missing, small: small, outside: outside, clashes: clashes });
  if (TOUCH) {
    var fly = R['g-fly'], guard = R['g-guard'], mahgic = R['g-mahgic'], att = R['tc-attack'], dash = R['tc-dash'], map = R['g-mapbt'], spd = R['g-speed'], cam = R['g-camreset'], row = R['g-erty-t'], sz = R['tc-stickzone'];
    ok('L1b touch geometry: FLY is the lower-right cell (former USE spot) above the 1–4 row; GUARD · DASH · FLY share the bottom cluster row; ATTACK sits directly above GUARD, MAHGIC above DASH; MAP · + · CAM are one row at the right edge above them; the cluster is right of the stick zone', fly.x + fly.w >= v.w - 12 && fly.y + fly.h <= row.y - 4 && Math.abs(guard.y - fly.y) < 2 && Math.abs(dash.y - fly.y) < 2 && Math.abs(att.x - guard.x) < 2 && att.y < guard.y && Math.abs(mahgic.x - dash.x) < 2 && mahgic.y < dash.y && Math.abs(map.y - spd.y) < 2 && Math.abs(spd.y - cam.y) < 2 && cam.x + cam.w >= v.w - 12 && map.y + map.h <= att.y + 2 && map.x > sz.x + sz.w, { fly: fly, guard: guard, dash: dash, attack: att, mahgic: mahgic, map: map, speed: spd, cam: cam, row: row });
    ok('L1c compact visible faces: cluster cells are 50 px (≥ 44 px logical targets, not oversized plates), the 1–4 row ≥ 44 px tall', [fly, guard, mahgic, att, dash, map, spd, cam].every(function (r) { return r.w >= 44 && r.w <= 58 && r.h >= 44 && r.h <= 58; }) && row.h >= 44, { sizes: [fly.w, guard.w, mahgic.w, att.w, dash.w, map.w, spd.w, cam.w], row_h: row.h });
    ok('L8 no keyboard hints on touch (every .gbtn small.key hidden)', await pg.evaluate("Array.prototype.every.call(document.querySelectorAll('.gbtn small.key'), function(e){ return getComputedStyle(e).display==='none'; })"));
  } else ok('L8 desktop keeps its key hints (V · M · B · Q visible)', await pg.evaluate("Array.prototype.some.call(document.querySelectorAll('.gbtn small.key'), function(e){ return getComputedStyle(e).display!=='none'; })"));
  /* L1d (PASS 3 review): the dock with its drawer OPEN (a category tapped, chips listed) never covers a cluster control — measured, not the collapsed dock only */
  var modeIds = await pg.evaluate("Array.prototype.map.call(document.querySelectorAll('#g-dock button.gmode'), function(b){ return b.getAttribute('data-mode'); })"); var openedMode = null;
  for (var mi = 0; mi < modeIds.length && !openedMode; mi++) { await ev("P.hud.tapMode('" + modeIds[mi] + "', 'probe'); return 1;"); await sleep(350); var dr = await rect('g-drawer'); if (dr && dr.shown && dr.h > 20) openedMode = modeIds[mi]; }
  var dockOpen = await rect('g-dock'); var drawerR = await rect('g-drawer'); var clusterNow = {}; for (var cid of ['g-mapbt', 'g-speed', 'g-camreset', 'g-fly', 'g-guard', 'g-mahgic'].concat(TOUCH ? ['tc-attack', 'tc-dash'] : [])) clusterNow[cid] = await rect(cid);
  var dockClash = Object.keys(clusterNow).filter(function (k) { return overlap(dockOpen, clusterNow[k]); }); report.rects.dock_open = { dock: dockOpen, drawer: drawerR, mode: openedMode };
  await pg.screenshot(path.join(OUT, 'hud_' + MODE + '_dock_open.png')); var chipsOpen = await pg.evaluate("Array.prototype.map.call(document.querySelectorAll('#g-chips .gkey'), function(e){ return e.textContent.trim(); })");
  ok('L1d the dock with its drawer open (' + (openedMode || 'no category opened') + ') stays out of the cluster: no control covered', !!openedMode && drawerR && drawerR.shown && dockClash.length === 0 && dockOpen.y + dockOpen.h <= v.h, { dock: dockOpen, drawer_h: drawerR && drawerR.h, clashes: dockClash });
  await ev("P.hud.closePanels('probe'); return 1;"); await sleep(300);
  /* L8b (P0 reconciliation, G20): no truncated ability names — every 1–4 / E R T Y label is the ruleset's authored short form (hud_label), fits its button (no overflow), and the drawer chips carry slot numbers on touch (letters only on desktop) */
  var labels = await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; var sn=P.snap?P.snap():null; var r=sn&&sn.play?sn.play.rules:null; var out={labels:[], overflow:[], chips:[]}; Array.prototype.forEach.call(document.querySelectorAll('#g-erty-t .gq small, #g-erty .gq small'), function(e){ var t=e.textContent.trim(); out.labels.push(t); if(e.scrollWidth>e.clientWidth+1) out.overflow.push(t); }); Array.prototype.forEach.call(document.querySelectorAll('#g-chips .gkey'), function(e){ out.chips.push(e.textContent.trim()); }); out.authored = r&&r.skills&&r.me?(r.skills[r.me.category]||[]).map(function(s){ return s?(s.pattern_label||s.pattern_name||s.name):'—'; }):null; return out; })()");
  ok('L8b no truncated ability names: the 1–4 / E R T Y labels equal the authored short forms and none overflows its button' + (TOUCH ? '; drawer chips are slot numbers on touch' : ''), labels && labels.labels.length >= 4 && labels.overflow.length === 0 && labels.authored && labels.labels.slice(0, 4).every(function (t, i) { return t === labels.authored[i]; }) && labels.labels.every(function (t) { return !/^Horizonta$/.test(t); }) && (!TOUCH || (chipsOpen.length >= 1 && chipsOpen.every(function (c) { return /^[1-4]$/.test(c); }))) && (TOUCH || chipsOpen.every(function (c) { return /^[ERTY]$/.test(c); })), { labels: labels, chips_with_drawer_open: chipsOpen });
  /* ── L2 no permanent USE ── */
  ok('L2 no permanent USE: the contextual prompt is hidden at an ordinary spot (the practice-reset / incoming fixtures never make a button)', !R['g-ctx'] || !R['g-ctx'].shown, R['g-ctx']);
  await ev("return P.goTo(26.6, 41.3, undefined, undefined, 60000);"); var ctx = null; for (var w2 = 0; w2 < 30; w2++) { ctx = await rect('g-ctx'); if (ctx && ctx.shown) break; await sleep(100); } var ctxText = await pg.evaluate("(function(){ var e=document.getElementById('g-ctx'); return e?e.textContent.trim():''; })()");
  ok('L2b at the tree elevator the contextual prompt appears with its verb (LIFT), inside the viewport, ≥ 44 px', ctx && ctx.shown && /LIFT/.test(ctxText) && ctx.h >= 44 && ctx.x >= 0 && ctx.x + ctx.w <= v.w, { ctx: ctx, text: ctxText });
  await sleep(600); var meBox = await ev("var b=P.screenBox(); return b?{x:b.left,y:b.top,w:b.right-b.left,h:b.bottom-b.top,shown:true}:null;"); var ctxOnHim = overlap(ctx, meBox);
  ok('L2c the contextual prompt never sits on the framed character (his screen box vs the prompt rect)', !!meBox && !ctxOnHim, { prompt: ctx, him: meBox });
  await ev("return P.goTo(20, 30, undefined, undefined, 60000);"); await sleep(600);
  /* ── L3 class tokens follow the local class; five families distinct ── */
  var cls = await pg.evaluate("document.body.dataset.class"); var me = await ev("var r=P.snap().play.rules; return r?r.me.class:null;");
  var fam = await pg.evaluate("(function(){ var out={}; ['ATHLETE','TITAN','LEAN','VISIONARY','BAGE'].forEach(function(c){ var was=document.body.dataset.class; document.body.dataset.class=c; var cs=getComputedStyle(document.body); out[c]={rim:cs.getPropertyValue('--c-rim').trim(), accent:cs.getPropertyValue('--c-accent').trim(), face:cs.getPropertyValue('--c-face-lo').trim()}; document.body.dataset.class=was; }); return out; })()");
  var rims = Object.keys(fam).map(function (k) { return fam[k].rim; }); ok('L3 the HUD theme follows the LOCAL player’s class (' + me + ') and the five class families resolve to distinct token sets', cls === me && new Set(rims).size === 5 && rims.every(Boolean), { body_class: cls, me: me, families: fam });
  /* ── L9 state matrix: distinct computed looks ── */
  var states = await pg.evaluate("(function(){ var b=document.getElementById('g-guard'); if(!b) return null; var keep=b.className; var out={}; ['','selected','disabled','unavailable','cooldown','pressed'].forEach(function(s){ b.className=keep.replace(/\\b(selected|disabled|unavailable|cooldown|pressed|on|off)\\b/g,'').trim()+(s?' '+s:''); var cs=getComputedStyle(b); out[s||'ready']=[cs.borderColor, cs.borderStyle, cs.opacity, cs.boxShadow.slice(0,60), cs.filter, cs.transform]; }); b.className=keep; return out; })()");
  var sigs = states ? Object.keys(states).map(function (k) { return states[k].join('|'); }) : []; ok('L9 state matrix: ready · selected · disabled · unavailable · cooldown · pressed render distinctly', states && new Set(sigs).size === 6, states);
  /* ── L4 `+` faster travel: toggle with a selected state, measurably faster, not a dash ── */
  await ev("return P.goTo(60, -45, undefined, undefined, 60000);"); await sleep(300); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-1.5708});"); await sleep(1200); await ev("return P.camReset('probe');"); await sleep(800);   /* the open strip north of the plaza structures (z −45): 50 m of clear floor westward for two straight legs */
  var p0 = await pos(); if (TOUCH) { var sz2 = R['tc-stickzone']; var sx = sz2.x + sz2.w * 0.5, sy = sz2.y + sz2.h * 0.55; await ptr('pointerdown', 'tc-stickzone', 1, sx, sy); for (var k = 1; k <= 4; k++) { await ptr('pointermove', 'tc-stickzone', 1, sx, sy - 30 * k); await sleep(30); } await sleep(2000); await ptr('pointerup', 'tc-stickzone', 1, sx, sy - 120); } else { await key('KeyW', true); await sleep(2000); await key('KeyW', false); }
  await sleep(300); var p1 = await pos(); var slow = Math.hypot(p1[0] - p0[0], p1[1] - p0[1]) / 2;
  if (TOUCH) await tapEl('g-speed', 7); else await clickEl('g-speed'); await sleep(300); var selOn = await pg.evaluate("document.getElementById('g-speed').classList.contains('selected')"); var p2 = await pos();
  if (TOUCH) { await ptr('pointerdown', 'tc-stickzone', 1, sx, sy); for (var k2 = 1; k2 <= 4; k2++) { await ptr('pointermove', 'tc-stickzone', 1, sx, sy - 30 * k2); await sleep(30); } await sleep(2000); await ptr('pointerup', 'tc-stickzone', 1, sx, sy - 120); } else { await key('KeyW', true); await sleep(2000); await key('KeyW', false); }
  await sleep(300); var p3 = await pos(); var fast = Math.hypot(p3[0] - p2[0], p3[1] - p2[1]) / 2; if (TOUCH) await tapEl('g-speed', 7); else await clickEl('g-speed'); await sleep(200); var selOff = await pg.evaluate("document.getElementById('g-speed').classList.contains('selected')");
  ok('L4 `+` faster travel: a tap toggles a clear selected state and sustained travel is faster (' + fast.toFixed(2) + ' vs ' + slow.toFixed(2) + ' m/s ≥ 1.25×); a second tap turns it off', selOn && !selOff && slow > 0.5 && fast >= slow * 1.25, { slow_mps: +slow.toFixed(2), fast_mps: +fast.toFixed(2), selected_on: selOn, selected_off: selOff });
  /* ── L5 MAP one tap; L6 one utility sheet with EMOTES / LOADOUT / SETTINGS ── */
  if (TOUCH) await tapEl('g-mapbt', 7); else await clickEl('g-mapbt'); await sleep(300); var mst = await ev("return P.menu.state();"); ok('L5 MAP is one tap away: the menu opens directly on its MAP tab', mst.open && mst.tab === 'MAP', mst); await ev("P.menu.close('probe'); return 1;"); await sleep(200);
  if (TOUCH) await tapEl('g-menubt', 7); else await clickEl('g-menubt'); await sleep(300); var tabs = await pg.evaluate("Array.prototype.map.call(document.querySelectorAll('#g-menu .mtab'), function(b){ return b.getAttribute('data-tab'); })"); var noMore = await pg.evaluate("!document.getElementById('g-morebtn')");
  await ev("P.menu.tab('EMOTES'); return 1;"); await sleep(300); var emotesIn = await pg.evaluate("(function(){ var b=document.querySelector('#g-menu-body #g-emotes'); return b?b.querySelectorAll('[data-do=\"emote\"]').length:0; })()");
  await ev("P.menu.tab('ACTIONS'); return 1;"); await sleep(300); var settingsIn = await pg.evaluate("(function(){ var b=document.querySelector('#g-menu-body #g-moreacts'); return b?b.textContent:''; })()"); await ev("P.menu.tab('LOADOUT'); return 1;"); await sleep(300); var loadoutIn = await pg.evaluate("!!document.querySelector('#g-menu-body #g-loadout')");
  ok('L6 one utility sheet: the ≡ menu carries EMOTES / LOADOUT / SETTINGS (+ STATS · SKILLS · INVENTORY · MAP · FRIENDS · DMs); EMOTES lists the catalogue (open sheet + one tap), SETTINGS holds practice / help / guide; no MORE button exists', tabs.indexOf('EMOTES') >= 0 && tabs.indexOf('LOADOUT') >= 0 && tabs.indexOf('ACTIONS') >= 0 && tabs.indexOf('MAP') >= 0 && emotesIn > 5 && /PRACTICE/.test(settingsIn) && /HELP/.test(settingsIn) && loadoutIn && noMore, { tabs: tabs, emotes: emotesIn, loadout: loadoutIn, no_more_button: noMore });
  /* L6c (PASS 3 review BLOCKER): the mounted bodies must ACT from inside the menu — one emote tapped in the EMOTES tab plays; PRACTICE tapped in SETTINGS toggles the host's practice flag (the menu lives outside #ghud and stops propagation, so the HUD's delegation is bound to the menu body) */
  await ev("P.menu.tab('EMOTES'); return 1;"); await sleep(300); var emoteBefore = await ev("var p=P.snap().play; return p ? (p.emote || null) : null;");
  var tappedEmote = await pg.evaluate("(function(){ var b=document.querySelector('#g-menu-body #g-emotes [data-do=\"emote\"]:not(.off):not(.disabled):not(.unavailable)'); if(!b) return null; var r=b.getBoundingClientRect(); ['pointerdown','pointerup'].forEach(function(t){ b.dispatchEvent(new PointerEvent(t,{pointerId:7,pointerType:'" + (TOUCH ? 'touch' : 'mouse') + "',isPrimary:true,clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true,cancelable:true,button:0})); }); return b.getAttribute('data-emote'); })()"); await sleep(700);
  var emoteAfter = await ev("var p=P.snap().play; return p ? (p.emote || null) : null;"); var emoteId = emoteAfter && typeof emoteAfter === 'object' ? (emoteAfter.id || emoteAfter.emote_id || JSON.stringify(emoteAfter)) : emoteAfter;
  ok('L6c an emote tapped INSIDE the mounted EMOTES tab actually plays (the menu-hosted bodies are live, not dead)', !!tappedEmote && !!emoteAfter && JSON.stringify(emoteAfter) !== JSON.stringify(emoteBefore), { tapped: tappedEmote, before: emoteBefore, after: emoteId });
  await ev("P.menu.tab('ACTIONS'); return 1;"); await sleep(300); var prBefore = await ev("var p=P.snap().play; return !!(p && p.rules && p.rules.practice);");
  await pg.evaluate("(function(){ var b=document.querySelector('#g-menu-body #g-moreacts [data-do=\"practice\"]'); if(!b) return null; var r=b.getBoundingClientRect(); ['pointerdown','pointerup'].forEach(function(t){ b.dispatchEvent(new PointerEvent(t,{pointerId:7,pointerType:'" + (TOUCH ? 'touch' : 'mouse') + "',isPrimary:true,clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true,cancelable:true,button:0})); }); return 1; })()"); await sleep(700);
  var prAfter = await ev("var p=P.snap().play; return !!(p && p.rules && p.rules.practice);"); ok('L6d PRACTICE tapped INSIDE the mounted SETTINGS tab toggles the host practice flag', prAfter !== prBefore, { before: prBefore, after: prAfter });
  if (prAfter !== prBefore) { await ev("return P.send('FIELD_PRACTICE', { on: " + (prBefore ? 'true' : 'false') + " });"); await sleep(300); }
  if (emoteAfter) { await ev("return P.send('EMOTE_STOP', {});"); await sleep(300); }
  await ev("P.menu.close('probe'); return 1;"); await sleep(300); var sheetRestored = await pg.evaluate("!!document.querySelector('#g-more #g-emotes') && !document.querySelector('#g-menu-body #g-emotes')"); ok('L6b closing the sheet returns the tab bodies to their home (nothing left mounted, no leaked panel)', sheetRestored && !(await ev("return P.hud.panelOpen();")), { restored: sheetRestored });
  /* ── L7 MAHGIC casts a ready magic skill ── */
  var before = await ev("var r=P.snap().play.rules; return ['SPECIAL_MAGIC','PHYSICAL_MAGIC'].map(function(k){ return (r.skills[k]||[]).map(function(s){ return s.availability; }); });"); if (TOUCH) await tapEl('g-mahgic', 7); else await clickEl('g-mahgic'); await sleep(1500); var after = await ev("var r=P.snap().play.rules; return ['SPECIAL_MAGIC','PHYSICAL_MAGIC'].map(function(k){ return (r.skills[k]||[]).map(function(s){ return s.availability; }); });"); var lastCast = await ev("return P.hud && P.hud.lastCast ? P.hud.lastCast() : null;");
  var castHappened = JSON.stringify(before) !== JSON.stringify(after) || (lastCast && lastCast.accepted); ok('L7 MAHGIC (tap / M) casts the first READY magic skill: a magic slot leaves READY (cooldown / casting) after the tap', castHappened, { before: before, after: after, last: lastCast });
  await sleep(2500);
  /* ── L10 hold-FLY from the new cell still climbs and holds; LAND lands (touch) ── */
  if (TOUCH) { var f0 = await ev("return P.snap().play.flight;"); var fr = await rect('g-fly'); await ptr('pointerdown', 'g-fly', 3, fr.cx, fr.cy); await sleep(1500); await ptr('pointerup', 'g-fly', 3, fr.cx, fr.cy); await sleep(1500); var f1 = await ev("return P.snap().play.flight;"); var land = await rect('g-land'); var desc = await rect('g-desc'); var flyNow = await rect('g-fly');
    ok('L10 hold FLY from its cell: take-off + climb, release holds (powered, intent 0, > 2 m); airborne row shows DOWN · LAND above FLY’s column (LAND in FLY’s column, both ≥ 44 px), FLY did not move', !f0.powered && f1.powered && f1.intent === 0 && f1.altitude > 2 && land && land.shown && desc && desc.shown && Math.abs(land.cx - fr.cx) < 2 && land.y < fr.y && desc.x < land.x && land.h >= 44 && Math.abs(flyNow.cx - fr.cx) < 1, { f1: f1, land: land, desc: desc });
    await pg.screenshot(path.join(OUT, 'hud_' + MODE + '_air.png')); await tapEl('g-land', 8); for (var q = 0; q < 40; q++) { var fq = await ev("return P.snap().play.flight;"); if (!fq.powered) break; await sleep(250); } await sleep(500); var f2 = await ev("return P.snap().play.flight;"); var landGone = await rect('g-land'); ok('L10b LAND lands and the airborne row hides again', !f2.powered && (!landGone || !landGone.shown), { f2: f2 }); }
  await pg.screenshot(path.join(OUT, 'hud_' + MODE + '_ground.png'));
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'hud_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT HUD PASS 3 ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
