/* Owner assignment 2026-09-18 §3 + §4 — CAMERA HEADING INDEPENDENCE and NEARBY CLICK / TAP-TO-MOVE on the built demo (headless Chrome, GPU).
   Real input paths: desktop clicks through CDP Input.dispatchMouseEvent on the canvas, portrait taps through CDP Input.dispatchTouchEvent (touch emulated —
   never a physical phone). Checks: N1 spawn rear view then FREE; N2 heading unchanged through cardinal / diagonal / backward travel and turns; N3 a drag chooses,
   release keeps; N4 RESET = one reframe, then independent again; N5 click → ONE destination through the ordinary walker; N6 pointer-down alone / a drag never
   moves; N7 out-of-range feedback; N8 sky = no destination; N9 stick takeover; N10 a camera drag preserves the path; N11 flight = horizontal at the held altitude,
   the altitude control cancels; N12 map tap through the map's transform; N13 room navigation + a room change cancels; M1–M3 portrait real-touch tap / drag /
   landscape; Z zero errors.   node 26_LOCAL_AUTHORITY/deploy/probe_nav.mjs [--out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = path.resolve(HERE, 'static_dist'); var argv = process.argv.slice(2);
function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; } var OUT = path.resolve(arg('--out', path.join(HERE, 'probe_out', 'nav'))); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pass = 0, fail = 0, lines = []; var report = { checks: lines, out: OUT, desktop: {}, portrait: {} };
function ok(id, cond, detail) { var line = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(line); console.log(line.length > 900 ? line.slice(0, 900) + '…' : line); if (cond) pass++; else fail++; }
function mk(pg) { return { ev: async function (expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }, shot: async function (tag) { var f = path.join(OUT, tag + '.png'); await pg.screenshot(f); return f; } }; }
async function boot(pg, M, extra) { await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (extra || '')); await waitForGame(pg, 120000); await sleep(4500); await M.ev("P.hud.showGuide(false); return 1;"); for (var w0 = 0; w0 < 120; w0++) { var dl = await M.ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); } await sleep(800); }
/* a FREE ground point `fwd` metres along the camera's forward and `right` metres to its right (camera-relative, so it is on screen whatever the heading), on the canvas, with no actor under the pointer and real ground under it; a few lateral alternatives are tried so a resident standing in the ray never turns a destination test into a lock-on test */
async function groundPx(M, fwd, right) { var alts = [[0, 0], [0, 2.5], [0, -2.5], [0, 5], [-2, 0], [0, -5], [-4, 0], [-4, 3], [-6, 0], [-6, -3]]; var fwdTry = fwd; for (var i = 0; i < alts.length; i++) { var r = await M.ev("var me=P.meRoot('me'); if(!me) return null; var b=P.camForward(); var f=(" + fwd + ")+(" + alts[i][0] + "), rr=(" + right + ")+(" + alts[i][1] + "); var wx=me.position.x+b.fx*f+b.rx*rr, wz=me.position.z+b.fz*f+b.rz*rr; var s=P.worldToScreen(wx, 0.02, wz); if(!s || s.x<4 || s.y<4 || s.x>innerWidth-4 || s.y>innerHeight-4) return null; var el=document.elementFromPoint(s.x, s.y); var actor=P.entityAt(s.x, s.y); var pick=P.pickWorld(s.x, s.y); return { x:s.x, y:s.y, wx:wx, wz:wz, el: el ? (el.id||el.tagName) : null, actor: actor, pick: pick };"); if (r && (r.el === 'view' || r.el === 'tc-world') && !r.actor && r.pick && Math.abs(r.pick.y) < 0.6) return r; } return null; }
async function skyPx(M) { var ys = [6, 20, 40, 70], xs = [600, 300, 900, 150, 1050]; for (var i = 0; i < ys.length; i++) for (var k = 0; k < xs.length; k++) { var d = await diag(M, xs[k], ys[i]); if (d.el === 'view' && !d.actor && !d.pick) return { x: xs[k], y: ys[i], diag: d }; } return null; }
async function diag(M, x, y) { return await M.ev("var el=document.elementFromPoint(" + x + "," + y + "); return { el: el ? (el.id || el.tagName) : null, actor: P.entityAt(" + x + "," + y + "), pick: P.pickWorld(" + x + "," + y + "), suppressed: P.hud.suppressed(), panel: P.hud.panelOpen(), guide: P.hud.guideOpen() };"); }
async function mouseClick(pg, x, y) { await pg.cmd('Input.dispatchMouseEvent', { type: 'mouseMoved', x: x, y: y }); await pg.cmd('Input.dispatchMouseEvent', { type: 'mousePressed', x: x, y: y, button: 'left', clickCount: 1 }); await sleep(60); await pg.cmd('Input.dispatchMouseEvent', { type: 'mouseReleased', x: x, y: y, button: 'left', clickCount: 1 }); }
async function touchTap(pg, x, y) { await pg.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x, y: y, id: 1 }] }); await sleep(70); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); }
async function touchDrag(pg, x, y, dx, steps) { await pg.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x, y: y, id: 1 }] }); for (var i = 1; i <= steps; i++) { await sleep(25); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + dx * i / steps, y: y, id: 1 }] }); } await sleep(40); await pg.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); }
function degDiff(a, b) { var d = (a - b) % (Math.PI * 2); if (d > Math.PI) d -= Math.PI * 2; if (d < -Math.PI) d += Math.PI * 2; return Math.abs(d) * 180 / Math.PI; }
async function waitNav(M, maxMs) { var t0 = Date.now(); var moved = false; while (Date.now() - t0 < (maxMs || 15000)) { var st = await M.ev("var p=P.snap()&&P.snap().play; return { nav: p?p.nav:null, speed: p?p.speed_mps:0, pos: p?p.position:null, mark: !!P.entity('navmark') };"); if (st.speed > 0.5) moved = true; if (!st.nav) return { done: true, moved: moved, ms: Date.now() - t0, pos: st.pos, mark: st.mark }; await sleep(80); } return { done: false, moved: moved, ms: Date.now() - t0 }; }

/* ═══════════ DESKTOP (mouse) ═══════════ */
var pg = await launchChrome({ width: 1200, height: 750, gpu: true }); var D = mk(pg);
try {
  await boot(pg, D); var s0 = await D.ev("return P.camState();"); var yaw0 = s0.yaw;
  ok('N1 spawn: the first view is ONE rear view of his spawn facing (err ' + s0.err_deg + '°) and the mode is FREE — not a re-armed rear follow', s0.state === 'FREE' && Math.abs(s0.err_deg) < 2, { state: s0.state, err: s0.err_deg, mode: s0.mode });
  /* N2: cardinal / diagonal / backward travel + turns — the heading never chases his back */
  var seq = [[1, 0], [0, 1], [-1, 0], [0, -1], [0.7, 0.7], [-0.7, -0.7]]; var maxDev = 0, facings = []; for (var i = 0; i < seq.length; i++) { await D.ev("P.send('MOVE',{forward:" + seq[i][0] + ",strafe:" + seq[i][1] + ",run:false,yaw:" + Math.atan2(seq[i][1], seq[i][0]).toFixed(3) + "}); return 1;"); await sleep(900); var cs = await D.ev("var c=P.camState(); var p=P.snap().play; return { yaw:c.yaw, state:c.state, facing:p.facing, backDot:c.back_dot };"); maxDev = Math.max(maxDev, degDiff(cs.yaw, yaw0)); facings.push(+cs.facing.toFixed(2)); if (i === 1) await D.shot('n2_side_travel_free_heading'); if (i === 2) await D.shot('n2_front_travel_free_heading'); } await D.ev("P.send('MOVE',{forward:0,strafe:0,run:false}); return 1;"); await sleep(600);
  var facingSpread = Math.max.apply(null, facings) - Math.min.apply(null, facings);
  ok('N2 heading independence: through forward / right / backward / left / diagonal travel (his facing turned through ' + facingSpread.toFixed(2) + ' rad) the camera yaw moved ' + maxDev.toFixed(2) + '° (≤ 0.5°) — side and front views during ordinary travel are the intended result', maxDev <= 0.5 && facingSpread > 2.5, { maxDev: maxDev, facings: facings });
  /* N3: a drag chooses, release keeps, travel afterwards keeps it */
  await D.ev("P.camOrbit(0.9, 0.08); return 1;"); await sleep(300); var s3 = await D.ev("return P.camState();"); await D.ev("P.send('MOVE',{forward:1,strafe:0,run:false,yaw:0}); return 1;"); await sleep(1200); var s3b = await D.ev("return P.camState();"); await D.ev("P.send('MOVE',{forward:0,strafe:0,run:false}); return 1;"); await sleep(400);
  ok('N3 drag → ORBIT: the dragged heading (yaw ' + s3.yaw.toFixed(3) + ') is kept on release and through the next travel (yaw ' + s3b.yaw.toFixed(3) + '), no return', s3.state === 'ORBIT' && s3b.state === 'ORBIT' && degDiff(s3.yaw, s3b.yaw) < 0.3 && degDiff(s3.yaw, yaw0) > 40, { s3: s3.state, s3b: s3b.state });
  /* N4: reset = one smooth reframe, then free again */
  await D.ev("P.camReset('probe'); return 1;"); await sleep(120); var s4a = await D.ev("return P.camState();"); await sleep(900); var s4 = await D.ev("return P.camState();"); var y4 = s4.yaw; await D.ev("P.send('MOVE',{forward:0,strafe:1,run:false,yaw:1.5708}); return 1;"); await sleep(1000); var s4b = await D.ev("return P.camState();"); await D.ev("P.send('MOVE',{forward:0,strafe:0,run:false}); return 1;"); await sleep(400);
  ok('N4 RESET: a smooth one-time reframe (RESET during the glide, then FREE with err ' + s4.err_deg + '°) and the heading is independent again — sideways travel afterwards moved the yaw ' + degDiff(s4b.yaw, y4).toFixed(2) + '°', s4a.state === 'RESET' && s4.state === 'FREE' && Math.abs(s4.err_deg) < 2 && degDiff(s4b.yaw, y4) < 0.5, { during: s4a.state, after: s4.state, err: s4.err_deg });
  await D.ev("P.camReset('probe'); return 1;"); await sleep(900);
  /* N5: click on the ground 8 m ahead → ONE destination → the ordinary walker → arrival, marker gone */
  var g5 = await groundPx(D, 8, 0); var camY5 = (await D.ev("return P.camState();")).yaw; var d5 = await diag(D, g5.x, g5.y); report.desktop.d5 = d5; await mouseClick(pg, g5.x, g5.y); await sleep(250); var n5 = await D.ev("var st=P.navState(); return { nav: st.nav, last: st.ui.last, mark: !!P.entity('navmark') };"); await D.shot('n5_click_destination_marker');
  var w5 = await waitNav(D, 12000); var camY5b = (await D.ev("return P.camState();")).yaw;
  ok('N5 click-to-move (real mouse click on the canvas): ONE destination accepted (' + (n5.nav && n5.nav.mode) + ', ' + (n5.last && n5.last.waypoints) + ' wp), the class-styled marker shown at the ACCEPTED point, the walker travelled and arrived within 0.5 m in ' + w5.ms + ' ms, marker removed; the camera heading did not move (' + degDiff(camY5, camY5b).toFixed(2) + '°)', !!n5.nav && n5.mark && w5.done && w5.moved && Math.hypot(w5.pos.x - n5.nav.target.x, w5.pos.z - n5.nav.target.z) < 0.5 && !w5.mark && degDiff(camY5, camY5b) < 0.5, { nav: n5.nav, arrived: w5, diag: d5, px: g5 });
  report.desktop.n5 = { nav: n5, arrived: w5 };
  /* N6: pointer-down alone never moves; a drag never moves on release */
  var g6 = await groundPx(D, 6, 3); await pg.cmd('Input.dispatchMouseEvent', { type: 'mousePressed', x: g6.x, y: g6.y, button: 'left', clickCount: 1 }); await sleep(450); var n6a = await D.ev("return P.navState().nav;"); for (var k = 1; k <= 8; k++) { await pg.cmd('Input.dispatchMouseEvent', { type: 'mouseMoved', x: g6.x + k * 15, y: g6.y, button: 'left', buttons: 1 }); await sleep(20); } await pg.cmd('Input.dispatchMouseEvent', { type: 'mouseReleased', x: g6.x + 120, y: g6.y, button: 'left', clickCount: 1 }); await sleep(250); var n6b = await D.ev("return { nav: P.navState().nav, cam: P.camState().state };");
  ok('N6 pointer-down alone does not move (450 ms held: no destination); once the gesture became a LOOK (drag > threshold) the release emitted no move — the camera orbited instead', !n6a && !n6b.nav && n6b.cam === 'ORBIT', { down: n6a, afterDrag: n6b });
  await D.ev("P.camReset('probe'); return 1;"); await sleep(900);
  /* N7: out of range → concise feedback, no marker */
  var g7 = await groundPx(D, 45, 0); var d7 = g7 ? { el: g7.el, pick: g7.pick } : null; if (g7) { await mouseClick(pg, g7.x, g7.y); await sleep(300); } else { var r7 = await D.ev("return P.nav(P.snap().play.position.x, P.snap().play.position.z - 45, 'DEV');"); await sleep(200); } var n7 = await D.ev("var st=P.navState(); return { nav: st.nav, refused: st.ui.refused,  mark: !!P.entity('navmark'), range: st.range_m };");
  ok('N7 a click 45 m away is refused OUT_OF_RANGE (range ' + n7.range + ' m from the player) with a concise toast and no marker', !n7.nav && n7.refused && n7.refused.reason === 'OUT_OF_RANGE' && !n7.mark, { n7: n7, diag: d7, px: g7 });
  /* N8: the sky is not a destination */
  await D.ev("P.camOrbit(0, -0.9); return 1;"); await sleep(400); var sk8 = await skyPx(D); var d8 = sk8 ? sk8.diag : null; if (sk8) { await mouseClick(pg, sk8.x, sk8.y); await sleep(300); } var n8 = await D.ev("var st=P.navState(); return { nav: st.nav, refused: st.ui.refused, mark: !!P.entity('navmark') };"); n8.diag = d8; n8.px = sk8 && { x: sk8.x, y: sk8.y }; await D.ev("P.camReset('probe'); return 1;"); await sleep(900);
  ok('N8 a click on the sky (camera pitched up, no world geometry under the pointer) has no destination (refused NO_PICK, never guessed at a distance), no marker', !!sk8 && !n8.nav && n8.refused && n8.refused.reason === 'NO_PICK' && !n8.mark, n8);
  /* N8b: a building FACADE is not a ground destination (the picked height sits above the support there) */
  var fac = await D.ev("var me=P.meRoot('me'); var b=P.camForward(); var best=null; for (var f=6; f<=26 && !best; f+=2) for (var rr=-10; rr<=10 && !best; rr+=2) { var wx=me.position.x+b.fx*f+b.rx*rr, wz=me.position.z+b.fz*f+b.rz*rr; for (var h=3; h<=9 && !best; h+=2) { var s=P.worldToScreen(wx, h, wz); if(!s||s.x<4||s.y<4||s.x>innerWidth-4||s.y>innerHeight-4) continue; var el=document.elementFromPoint(s.x,s.y); if(!el||el.id!=='view') continue; var pk=P.pickWorld(s.x,s.y); if(pk && pk.y>2.5 && pk.distance<40 && !P.entityAt(s.x,s.y)) best={x:s.x,y:s.y,pick:pk}; } } return best;"); if (fac) { await mouseClick(pg, fac.x, fac.y); await sleep(300); } var n8b = await D.ev("var st=P.navState(); return { nav: st.nav, refused: st.ui.refused, mark: !!P.entity('navmark') };");
  ok('N8b a click on a building facade / storey (picked height ' + (fac && fac.pick.y) + ' m) is refused TARGET_BLOCKED (ELEVATED) — not snapped to the ground beside the wall, no marker', !fac || (!n8b.nav && n8b.refused && n8b.refused.reason === 'TARGET_BLOCKED' && !n8b.mark), { fac: fac && fac.pick, n8b: n8b, skipped: !fac });
  /* N9: stick / keyboard takeover */
  var g9 = await groundPx(D, 15, 0) || await groundPx(D, 9, 0); await mouseClick(pg, g9.x, g9.y); await sleep(500); var n9a = await D.ev("return P.navState().nav;"); if (!n9a) { report.desktop.n9_first_refused = await D.ev("return P.navState().ui.refused;"); var g9b = await groundPx(D, 9, 3) || await groundPx(D, 6, -3); if (g9b) { await mouseClick(pg, g9b.x, g9b.y); await sleep(500); n9a = await D.ev("return P.navState().nav;"); } } await D.ev("P.send('MOVE',{forward:0,strafe:1,run:false,yaw:1.5708}); return 1;"); await sleep(150); var n9b = await D.ev("return { nav: P.navState().nav, mark: !!P.entity('navmark') };"); await D.ev("P.send('MOVE',{forward:0,strafe:0,run:false}); return 1;"); await sleep(400); var n9c = await D.ev("return P.navState().nav;");
  ok('N9 takeover: direct input (MOVE with a stick vector) cleared the destination at once and removed the marker; lifting the stick did not resume it', !!n9a && !n9b.nav && !n9b.mark && !n9c, { before: !!n9a, after: n9b, lifted: !!n9c });
  /* N10: a camera drag during the journey preserves the path and the world-fixed target */
  var g10 = await groundPx(D, 10, -6) || await groundPx(D, 7, 4); await mouseClick(pg, g10.x, g10.y); await sleep(400); var t10 = await D.ev("return P.navState().nav && P.navState().nav.target;"); await D.ev("P.camOrbit(1.4, 0.05); return 1;"); await sleep(500); var n10 = await D.ev("return P.navState().nav;"); var w10 = await waitNav(D, 15000);
  ok('N10 a camera drag alone preserves an otherwise valid path: the destination stayed the same world point (' + (t10 && t10.x) + ', ' + (t10 && t10.z) + ') and was reached', !!t10 && !!n10 && n10.target.x === t10.x && n10.target.z === t10.z && w10.done && Math.hypot(w10.pos.x - t10.x, w10.pos.z - t10.z) < 0.5, { t10: t10, w10: w10 });
  await D.ev("P.camReset('probe'); return 1;"); await sleep(900);
  /* N11: flight — horizontal destination at the held altitude; the ascent control cancels */
  await D.ev("P.send('FLIGHT',{op:'ENTER'}); return 1;"); await sleep(1400); await D.ev("P.send('FLIGHT',{op:'HOVER'}); return 1;"); await sleep(900); var alt0 = await D.ev("return P.snap().play.flight.altitude;");
  var g11 = await groundPx(D, 10, 0) || await groundPx(D, 7, 0); await mouseClick(pg, g11.x, g11.y); await sleep(300); var n11 = await D.ev("var st=P.navState(); var m=P.entity('navmark'); return { nav: st.nav, markY: m ? m.root.position.y : null, plumb: m ? m.plumb.visible : null };"); await D.shot('n11_flight_waypoint_marker');
  var altMin = 1e9, altMax = -1e9; var t0 = Date.now(); var w11 = null; while (Date.now() - t0 < 12000) { var st11 = await D.ev("var p=P.snap().play; return { nav:p.nav, alt:p.flight.altitude, powered:p.flight.powered, pos:p.position };"); altMin = Math.min(altMin, st11.alt); altMax = Math.max(altMax, st11.alt); if (!st11.nav) { w11 = st11; break; } await sleep(80); }
  ok('N11 flight: a ground click while flying became an AIR waypoint at the held altitude (marker at y ' + (n11.markY && n11.markY.toFixed(2)) + ' with the plumb line), reached horizontally with the altitude held (Δ ' + (altMax - altMin).toFixed(2) + ' m ≤ 0.6), still powered — never a silent landing', !!n11.nav && n11.nav.mode === 'AIR' && n11.markY > 1 && n11.plumb === true && !!w11 && w11.powered && (altMax - altMin) < 0.6 && Math.hypot(w11.pos.x - n11.nav.target.x, w11.pos.z - n11.nav.target.z) < 0.6, { nav: n11.nav, altMin: altMin, altMax: altMax, w11: w11 });
  var g11b = await groundPx(D, 8, 6); if (g11b) { await mouseClick(pg, g11b.x, g11b.y); await sleep(300); } var n11b = await D.ev("return P.navState().nav;"); await D.ev("P.send('FLIGHT',{op:'ASCEND'}); return 1;"); await sleep(200); var n11c = await D.ev("return P.navState().nav;"); await D.ev("P.send('FLIGHT',{op:'HOVER'}); return 1;"); await sleep(300); await D.ev("P.send('FLIGHT',{op:'EXIT'}); return 1;"); await sleep(5000);
  ok('N11b holding FLY (ASCEND = direct altitude control) cancels the aerial destination', !!n11b && !n11c, { before: !!n11b, after: !!n11c });
  /* N12: the map — a tap through the map's real world transform */
  await D.ev("P.menu.open('MAP'); return 1;"); await sleep(700); var mp = await D.ev("var cv=document.getElementById('g-map'); if(!cv||!cv.__toWorld) return null; var r=cv.getBoundingClientRect(); var me=P.snap().play.position; var W=cv.width,H=cv.height; var LM=P.snap().play.rules.colliders.landmarks||[]; var range=LM.length?160:46, ox=0, oz=LM.length?100:0; function sx(x){return W/2+(x-ox)/range*(W/2);} function sz(z){return H/2+(z-oz)/range*(H/2);} var tx=me.x+10, tz=me.z-6; var px=sx(tx), py=sz(tz); return { cx: r.left+px*(r.width/W), cy: r.top+py*(r.height/H), tx:tx, tz:tz, far: { cx: r.left+sx(me.x+80)*(r.width/W), cy: r.top+sz(me.z)*(r.height/H) } };");
  if (mp) { await pg.cmd('Input.dispatchMouseEvent', { type: 'mousePressed', x: mp.cx, y: mp.cy, button: 'left', clickCount: 1 }); await sleep(60); await pg.cmd('Input.dispatchMouseEvent', { type: 'mouseReleased', x: mp.cx, y: mp.cy, button: 'left', clickCount: 1 }); await sleep(400); } var n12 = await D.ev("return P.navState().nav;"); await D.shot('n12_map_tap_destination');
  if (mp) { await pg.cmd('Input.dispatchMouseEvent', { type: 'mousePressed', x: mp.far.cx, y: mp.far.cy, button: 'left', clickCount: 1 }); await sleep(60); await pg.cmd('Input.dispatchMouseEvent', { type: 'mouseReleased', x: mp.far.cx, y: mp.far.cy, button: 'left', clickCount: 1 }); await sleep(400); } var n12b = await D.ev("var st=P.navState(); return { nav: st.nav, refused: st.ui.refused };"); await D.shot('n12b_map_tap_out_of_range'); await D.ev("P.menu.close('probe'); return 1;"); await sleep(300); var w12 = await waitNav(D, 15000);
  ok('N12 MAP: a tap on the map canvas becomes the same NAV command through the map\'s world transform (via MAP, target within 1.5 m of the tapped world point: ' + (mp && mp.tx.toFixed(1)) + ', ' + (mp && mp.tz.toFixed(1)) + '); a tap outside the range ring is refused OUT_OF_RANGE; the accepted one was walked', !!mp && !!n12 && n12.via === 'MAP' && Math.hypot(n12.target.x - mp.tx, n12.target.z - mp.tz) < 1.5 && n12b.refused && n12b.refused.reason === 'OUT_OF_RANGE' && w12.done, { n12: n12, n12b: n12b, w12: w12 });
  /* N13: inside a room (gym hall): navigation within the room; a room change cancels */
  await D.ev("return P.goTo(-84.4, 110, undefined, undefined, 90000);"); await sleep(400); var eP = D.ev("return P.interact();"); await sleep(350); await D.ev("P.confirmAnswer(true); return 1;"); await eP; await sleep(900); var room13 = await D.ev("return P.snap().play.room;");
  var g13 = await groundPx(D, 6, 0); report.desktop.g13 = g13; if (g13) { await mouseClick(pg, g13.x, g13.y); await sleep(300); } var n13 = await D.ev("return P.navState().nav;"); if (!n13) report.desktop.n13_refused = await D.ev("return P.navState().ui.refused;"); var w13 = await waitNav(D, 12000); await D.shot('n13_room_navigation');
  var far13 = await D.ev("return P.nav(0, 40, 'DEV');"); await D.ev("return P.goTo(0, 11.6, undefined, undefined, 20000);"); await sleep(300); await D.ev("P.nav(-8, 4, 'DEV'); return 1;"); await sleep(200); var n13c = await D.ev("return P.navState().nav;"); var xP = D.ev("return P.interact();"); await sleep(350); await D.ev("P.confirmAnswer(true); return 1;"); await xP; await sleep(900); var n13d = await D.ev("return { nav: P.navState().nav, room: P.snap().play.room, mark: !!P.entity('navmark') };");
  ok('N13 room: inside ' + room13 + ' a click walks him across the hall (arrived: ' + w13.done + '); a point outside the room is OUT_OF_ROOM; a destination pending at the doorway is cancelled by the room change (no stale path outside, no marker)', room13 === 'GYM_INTERIOR' && !!n13 && w13.done && !far13.accepted && far13.reason === 'OUT_OF_ROOM' && !!n13c && n13d.room === 'FIELD' && !n13d.nav && !n13d.mark, { n13: !!n13, refused: report.desktop.n13_refused, g13: g13 && { wx: g13.wx, wz: g13.wz, pick: g13.pick }, w13: w13, far13: far13.reason, n13c: !!n13c, after: n13d });
  var errs = pg.errors.filter(function (x) { return !/404/.test(x); }); ok('Z1 zero page / console errors (desktop)', errs.length === 0, errs.slice(0, 3));
} catch (e) { ok('desktop probe ran to completion', false, String(e && e.stack || e)); } finally { await pg.close(); }

/* ═══════════ PORTRAIT (touch emulated, real CDP touch events) ═══════════ */
var pm = await launchChrome({ width: 390, height: 844, dpr: 2, mobile: true, gpu: true }); var M = mk(pm);
try {
  await boot(pm, M, '&touch=1'); var m0 = await M.ev("return P.camState();");
  var gm1 = await groundPx(M, 7, 0) || await groundPx(M, 5, 0); var dm1 = await diag(M, gm1.x, gm1.y); report.portrait.dm1 = dm1; await touchTap(pm, gm1.x, gm1.y); await sleep(300); var m1 = await M.ev("var st=P.navState(); return { nav: st.nav, mark: !!P.entity('navmark') };"); await M.shot('m1_portrait_tap_destination'); var wm1 = await waitNav(M, 12000);
  ok('M1 portrait (touch emulated): a real touch tap on empty ground submits ONE destination (' + (m1.nav && m1.nav.mode) + '), the marker shows the accepted point, he walked there and stopped', m0.state === 'FREE' && !!m1.nav && m1.mark && wm1.done && wm1.moved && Math.hypot(wm1.pos.x - m1.nav.target.x, wm1.pos.z - m1.nav.target.z) < 0.5, { m1: m1, wm1: wm1, diag: dm1, px: gm1 });
  var gm2 = await groundPx(M, 7, 2); var cy0 = (await M.ev("return P.camState();")).yaw; await touchDrag(pm, gm2.x, gm2.y, 120, 6); await sleep(300); var m2 = await M.ev("var st=P.navState(); return { nav: st.nav, cam: P.camState() };");
  ok('M2 portrait: a touch drag on the world is a LOOK (camera ORBIT, yaw moved ' + degDiff(m2.cam.yaw, cy0).toFixed(1) + '°) and its release emitted no destination', !m2.nav && m2.cam.state === 'ORBIT' && degDiff(m2.cam.yaw, cy0) > 5, { nav: m2.nav, cam: m2.cam.state });
  await M.ev("P.camReset('probe'); return 1;"); await sleep(900);
  var stick = await M.ev("var z=document.getElementById('tc-stickzone'); var r=z.getBoundingClientRect(); return { x: r.left + r.width/2, y: r.top + r.height/2 };");
  await pm.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: stick.x, y: stick.y, id: 1 }] }); await sleep(60); await pm.cmd('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: stick.x, y: stick.y - 45, id: 1 }] }); await sleep(500); var gm3 = await groundPx(M, 6, 3); await pm.cmd('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: stick.x, y: stick.y - 45, id: 1 }, { x: gm3.x, y: gm3.y, id: 2 }] }); await sleep(70); await pm.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [{ x: gm3.x, y: gm3.y, id: 2 }] }); await sleep(250);   /* CDP: touchEnd lists the points being RELEASED — the tap finger lifts, the stick finger stays */ var m3 = await M.ev("var st=P.navState(); return { nav: st.nav, nav_end: st.nav_end, last: st.ui.last, refused: st.ui.refused, speed: P.snap().play.speed_mps, touch: P.touchState() };"); m3.px = gm3 && { x: gm3.x, y: gm3.y, el: gm3.el }; await pm.cmd('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(500);
  ok('M3 portrait: with the stick finger steering (STICK role, mag ' + (m3.touch && m3.touch.stick.mag) + '), a second finger\'s tap is its own gesture (independent pointer ids: ' + JSON.stringify(m3.touch && m3.touch.fingers) + ') and is REFUSED while direct input is active (' + (m3.refused && m3.refused.reason) + ') — the stick keeps steering (speed ' + m3.speed + '), no destination hijacks it', !!m3.touch && m3.touch.stick.active && m3.touch.stick.mag > 0.5 && m3.refused && m3.refused.reason === 'DIRECT_INPUT_ACTIVE' && m3.speed > 0.3 && !m3.nav, { refused: m3.refused, speed: m3.speed, touch: m3.touch && { stick: m3.touch.stick, fingers: m3.touch.fingers } });
  await pm.cmd('Emulation.setDeviceMetricsOverride', { width: 844, height: 390, deviceScaleFactor: 2, mobile: true }); await sleep(900); var gm4 = await groundPx(M, 7, 0) || await groundPx(M, 5, 0); await touchTap(pm, gm4.x, gm4.y); await sleep(300); var m4 = await M.ev("return P.navState().nav;"); await M.shot('m4_landscape_tap_destination'); var wm4 = await waitNav(M, 12000);
  ok('M4 landscape (touch emulated): the same tap works after rotation and is walked', !!m4 && wm4.done && Math.hypot(wm4.pos.x - m4.target.x, wm4.pos.z - m4.target.z) < 0.5, { m4: !!m4, wm4: wm4 });
  var errsM = pm.errors.filter(function (x) { return !/404/.test(x); }); ok('Z2 zero page / console errors (portrait)', errsM.length === 0, errsM.slice(0, 3));
} catch (e) { ok('portrait probe ran to completion', false, String(e && e.stack || e)); } finally { await pm.close(); }
srv.close(); report.summary = { pass: pass, fail: fail }; fs.writeFileSync(path.join(OUT, 'probe_nav.json'), JSON.stringify(report, null, 1)); console.log('PASS ' + pass + ' FAIL ' + fail + ' → ' + OUT); process.exit(fail ? 1 : 0);
