/* OWNER INTERJECTION 2026-09-18 phase E — the three owner-authorized Athlete attacks in the real page: OVERHEAD EXTENSION RELEASE (arc + LANCE rod),
   CHEST FLY CLAP RELEASE (arc + CLAP ring, both hands gather), EIGHT-STRIKE CURL BARRAGE (approach, eight alternating curls on the host schedule,
   the lock on the dummy's world tag, per-strike bursts). Stills = side + front-¾ MANUAL LOOK at normal speed; frame stalls measured during the
   barrage and separated from the host state delay. Desktop GPU Chrome; no phone claim.   node deploy/probe_attacks_phase_e.mjs [static_dist] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') ? path.resolve(argv[0]) : path.join(HERE, 'static_dist'); var OUT = path.join(HERE, 'probe_out', 'attacks_e'); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 900, height: 620, gpu: true, unlockFps: true }); var pass = 0, fail = 0, lines = []; var shots = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 900)); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function shot(tag) { var f = path.join(OUT, tag + '.png'); await pg.screenshot(f); shots.push({ tag: tag, f: f }); }
var DEG = Math.PI / 180; var report = { checks: lines };
async function recStart(ms) { await ev("window.__rec = []; window.__recT0 = performance.now(); window.__frames = []; var last = performance.now(); var e=P.entity('me'); var an=e.fused.animator; window.__recIv = setInterval(function(){ try { var nowT = performance.now(); window.__frames.push(nowT - last); last = nowT; var pl=P.snap().play; var cast = pl.rules && pl.rules.me.cast ? pl.rules.me.cast : null; var pose=an.pose(); var cs = an.curlStrike ? an.curlStrike() : null; var dm = pl.rules ? pl.rules.others.filter(function(o){ return o.id==='FIELD_DUMMY'; })[0] : null; var W = {}; ['HAND_L','HAND_R','HEAD','CHEST','PELVIS'].forEach(function(k){ W[k]=P.boneWorld(k); }); window.__rec.push({ ms: nowT - window.__recT0, phase: cast ? cast.phase : null, facing: pl.facing, W: W, strike: cast && cast.strike ? cast.strike.done : null, locked: cast && cast.strike ? cast.strike.locked : null, curl: cs ? cs.arm + cs.k : null, fl: +pose.FOREARM_L[0].toFixed(2), fr: +pose.FOREARM_R[0].toFixed(2), ul: +pose.UPPERARM_L[0].toFixed(2), uz: +pose.UPPERARM_L[2].toFixed(2), sp: +pose.SPINE[0].toFixed(2), dummy_hp: dm ? dm.hp : null, dummy_lock: dm ? dm.statuses.some(function(s){ return s.kind==='COMBO_LOCK'; }) : null, tag: (function(){ var d=P.entity('other:FIELD_DUMMY'); return d ? d.tagText : null; })() }); } catch (err) { window.__rec.push({ ms: performance.now()-window.__recT0, err: String(err) }); } if (performance.now()-window.__recT0 > " + ms + ") clearInterval(window.__recIv); }, 16); return 1;"); }
async function recRows() { return await ev("return { rows: window.__rec || [], frames: window.__frames || [] };"); }
function p95(a) { if (!a.length) return null; var s = a.slice().sort(function (x, y) { return x - y; }); return s[Math.min(s.length - 1, Math.floor(s.length * 0.95))]; }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(4500); await ev("P.hud.showGuide(false); P.hud.setDev && P.hud.setDev(false); if (P.camFollow) P.camFollow(false); return 1;");
  for (var w0 = 0; w0 < 120; w0++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); }
  await ev("P.send('FIELD_PRACTICE',{on:true}); return 1;"); await sleep(300); var dummy = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0];");
  async function face(dz) { await ev("return P.goTo(" + dummy.position.x + ", " + (dummy.position.z + dz) + ", undefined, undefined, 40000);"); await sleep(250); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); return 1;"); await sleep(700); }
  async function sideCam(dist) { var yw = await ev("return P.mePose().root_yaw;"); await ev("P.cam(" + (yw + Math.PI / 2) + ", 0.05, " + (dist || 3.4) + ", 1.05); return 1;"); await sleep(250); }
  async function frontCam(dist) { var yw = await ev("return P.mePose().root_yaw;"); await ev("P.cam(" + (yw + Math.PI + 0.7) + ", 0.08, " + (dist || 3.4) + ", 1.05); return 1;"); await sleep(250); }
  /* ── Special #1: OVERHEAD EXTENSION RELEASE ── */
  await ev("return P.send('RULES_LOADOUT',{category:'SPECIAL_MAGIC',slot:1,skill_id:'ATHLETE_OVERHEAD_RELEASE'});"); await face(6.0); await sideCam(3.6); await ev("P.send('RULES_SELECT',{category:'SPECIAL_MAGIC',slot:1}); return 1;"); await sleep(120);
  await recStart(1900); var c1 = await ev("return P.send('RULES_CAST',{});"); for (var i = 0; i < 8; i++) { await sleep(i === 0 ? 420 : 125); await shot('overhead_side_' + i); } await sleep(700); var r1 = await recRows(); var rows1 = r1.rows.filter(function (r) { return !r.err; });
  function geo(r) { var f = { x: Math.sin(r.facing || 0), z: -Math.cos(r.facing || 0) }; var W = r.W || {}; if (!W.HAND_L || !W.HAND_R || !W.HEAD || !W.CHEST) return null; var fwd = function (pt) { return (pt[0] - W.CHEST[0]) * f.x + (pt[2] - W.CHEST[2]) * f.z; }; var lat = function (pt) { return (pt[0] - W.CHEST[0]) * (-f.z) + (pt[2] - W.CHEST[2]) * f.x; }; return { hy: Math.min(W.HAND_L[1], W.HAND_R[1]), hyMax: Math.max(W.HAND_L[1], W.HAND_R[1]), head: W.HEAD[1], chest: W.CHEST[1], fwdL: fwd(W.HAND_L), fwdR: fwd(W.HAND_R), latL: lat(W.HAND_L), latR: lat(W.HAND_R), gap: Math.hypot(W.HAND_L[0] - W.HAND_R[0], W.HAND_L[1] - W.HAND_R[1], W.HAND_L[2] - W.HAND_R[2]) }; }
  var stO = rows1.filter(function (r) { return r.phase === 'STARTUP' && geo(r); }); var rcO = rows1.filter(function (r) { return r.phase === 'RECOVERY' && geo(r); }); var loadO = stO.length ? geo(stO.sort(function (a, b) { return geo(b).hy - geo(a).hy; })[0]) : null; var relO = rcO.length ? geo(rcO.sort(function (a, b) { return (geo(b).fwdL + geo(b).fwdR) - (geo(a).fwdL + geo(a).fwdR); })[0]) : null;
  ok('E1 OVERHEAD arc (hand WORLD positions): the load carries BOTH hands up to head height (' + (loadO && (loadO.hy - loadO.head).toFixed(2)) + ' m vs the head bone — the declared shoulder table softens flexion to ≈ 80°, so head height IS the overhead of this rig) over the chest line, elbows bent; the release extends them forward of the chest (≥ 0.30 m ahead, at chest height, elbows straight) — an overhead extension, never a lunge', c1 && c1.accepted && loadO && loadO.hy >= loadO.head - 0.08 && Math.abs(loadO.fwdL) <= 0.2 && Math.abs(loadO.fwdR) <= 0.2 && relO && Math.min(relO.fwdL, relO.fwdR) >= 0.30 && relO.hy >= relO.chest - 0.12, { cast: c1 && (c1.reason || c1.accepted), load: loadO, release: relO, samples: rows1.length });
  var dmgO = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0].hp;");
  ok('E1b the LANCE projectile hit the dummy once (hp ' + dummy.hp + ' → ' + dmgO + ')', dmgO < dummy.hp, { hp: [dummy.hp, dmgO] });
  await sleep(3500);
  /* ── Special #2: CHEST FLY CLAP RELEASE ── */
  await ev("return P.send('RULES_LOADOUT',{category:'SPECIAL_MAGIC',slot:1,skill_id:'ATHLETE_CHEST_FLY_CLAP'});"); await face(5.0); await frontCam(3.6); await ev("P.send('RULES_SELECT',{category:'SPECIAL_MAGIC',slot:1}); return 1;"); await sleep(120); var hpF0 = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0].hp;");
  await recStart(2000); var c2 = await ev("return P.send('RULES_CAST',{});"); var g2 = null; for (var i2 = 0; i2 < 8; i2++) { await sleep(i2 === 0 ? 500 : 125); await shot('chestfly_front_' + i2); if (i2 === 0) g2 = await ev("var e=P.entity('me'); return { g1: !!e.dustGather, g2: !!e.dustGather2 };"); } await sleep(700); var r2 = await recRows(); var rows2 = r2.rows.filter(function (r) { return !r.err; });
  var stF = rows2.filter(function (r) { return r.phase === 'STARTUP' && geo(r); }); var rcF = rows2.filter(function (r) { return r.phase === 'RECOVERY' && geo(r); }); var loadF = stF.length ? geo(stF.sort(function (a, b) { return geo(b).gap - geo(a).gap; })[0]) : null; var relF = rcF.length ? geo(rcF.sort(function (a, b) { return geo(a).gap - geo(b).gap; })[0]) : null;
  ok('E2 CHEST FLY arc (hand WORLD positions): the load opens the hands WIDE at shoulder height (' + (loadF && loadF.gap.toFixed(2)) + ' m apart, within 0.55 m of the chest bone = shoulder height), the release ADDUCTS them to the clap in front of the chest (' + (relF && relF.gap.toFixed(2)) + ' m apart, ≥ 0.25 m ahead); the second hand carried its own gather', c2 && c2.accepted && loadF && loadF.gap >= 1.0 && Math.abs((loadF.hy + loadF.hyMax) / 2 - loadF.chest) <= 0.55 && relF && relF.gap <= 0.42 && Math.min(relF.fwdL, relF.fwdR) >= 0.25 && g2 && g2.g2, { cast: c2 && (c2.reason || c2.accepted), load: loadF, release: relF, gathers: g2, samples: rows2.length });
  var hpF1 = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0].hp;");
  ok('E2b the CLAP projectile hit the dummy once (hp ' + hpF0 + ' → ' + hpF1 + ')', hpF1 < hpF0, { hp: [hpF0, hpF1] });
  await sleep(4500);
  /* ── the barrage ── */
  await ev("return P.send('RULES_LOADOUT',{category:'PHYSICAL_MAGIC',slot:1,skill_id:'PM_CURL_BARRAGE'});"); await face(2.3); await sideCam(3.2); await ev("P.send('RULES_SELECT',{category:'PHYSICAL_MAGIC',slot:1}); return 1;"); await sleep(120);
  var pos0 = await ev("var p=P.snap().play.position; return [p.x, p.z];"); var hpB0 = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0].hp;");
  await recStart(2300); var c3 = await ev("return P.send('RULES_CAST',{});"); for (var i3 = 0; i3 < 9; i3++) { await sleep(i3 === 0 ? 420 : 110); await shot('barrage_side_' + i3); } await sleep(900); var r3 = await recRows(); var rows3 = r3.rows.filter(function (r) { return !r.err; });
  var pos1 = await ev("var p=P.snap().play.position; return [p.x, p.z];"); var hpB1 = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0].hp;"); var moved = Math.hypot(pos1[0] - pos0[0], pos1[1] - pos0[1]);
  var maxStrike = rows3.reduce(function (m, r) { return Math.max(m, r.strike || 0); }, 0); var hpDrops = []; (function () { var prev = null; rows3.forEach(function (r) { if (r.dummy_hp === null || r.dummy_hp === undefined) return; if (prev !== null && r.dummy_hp < prev - 1e-6) hpDrops.push(+(prev - r.dummy_hp).toFixed(2)); prev = r.dummy_hp; }); })(); var perStrike = hpDrops.length ? Math.min.apply(null, hpDrops) : 0; var strikesByDamage = perStrike > 0 ? Math.round((hpB0 - hpB1) / perStrike) : 0;   /* the view's done counter can miss the final tick when the cast ends in the same host tick (20 Hz poll aliasing); the dummy's total damage ÷ one strike's damage is the host's own count */ var lockRows = rows3.filter(function (r) { return r.dummy_lock; }); var lockTag = rows3.some(function (r) { return /LOCK|COMBO/.test(String(r.tag || '')); }); var curlSeq = []; rows3.forEach(function (r) { if (r.phase === 'RECOVERY' && r.curl && (!curlSeq.length || curlSeq[curlSeq.length - 1] !== r.curl)) curlSeq.push(r.curl); });
  var alternates = curlSeq.length >= 6 && curlSeq.every(function (c, i) { return i === 0 || c[0] !== curlSeq[i - 1][0]; }); var curlDepth = rows3.filter(function (r) { return r.phase === 'RECOVERY'; }).reduce(function (m, r) { return Math.min(m, Math.min(r.fl, r.fr)); }, 0);
  ok('E3 BARRAGE: the approach slid him from 2.3 m to reach (' + moved.toFixed(2) + ' m, never a teleport), the host counted 8 strikes (view max ' + maxStrike + ', by damage ' + strikesByDamage + ' × ' + perStrike + ' hp), the dummy lost health eight times (hp ' + hpB0 + ' → ' + hpB1 + ')', c3 && c3.accepted && moved >= 0.5 && moved <= 2.6 && (maxStrike === 8 || (maxStrike >= 7 && strikesByDamage === 8)) && hpB1 < hpB0 && (hpB0 - hpB1) > 8 * 5, { cast: c3 && (c3.reason || c3.accepted), moved: moved, strikes: maxStrike, strikes_by_damage: strikesByDamage, per_strike_hp: perStrike, hp_drops: hpDrops, hp: [hpB0, hpB1] });
  ok('E3b the eight curls ALTERNATE arms on the host schedule (' + curlSeq.join(' ') + '), each a real elbow flexion (FOREARM reaches ≤ −0.8 rad = a curl to the shoulder, elbows pinned)', alternates && curlDepth <= -0.8, { seq: curlSeq, depth: curlDepth });
  ok('E3c the combo-lock shows on the dummy (status COMBO_LOCK for ' + lockRows.length + ' samples, ≤ 1.35 s) and on its world tag', lockRows.length >= 3 && (lockRows[lockRows.length - 1].ms - lockRows[0].ms) <= 1350 && lockTag, { lock_samples: lockRows.length, span_ms: lockRows.length ? lockRows[lockRows.length - 1].ms - lockRows[0].ms : null, tag_seen: lockTag, tags: rows3.map(function (r) { return r.tag; }).filter(function (t, i, a) { return a.indexOf(t) === i; }) });
  var fr = r3.frames.slice(3); var p95v = p95(fr), stalls = fr.filter(function (x) { return x > 100; }).length;
  ok('E4 performance during the barrage (page timer, desktop GPU Chrome): sampler p95 ' + (p95v !== null ? p95v.toFixed(1) : '?') + ' ms, long stalls (> 100 ms) ' + stalls + ' of ' + fr.length + ' — no freeze, no constant shake; host state delay is the 120 ms presentation lag, unchanged', p95v !== null && p95v <= 80 && stalls <= 2, { p95: p95v, stalls: stalls, n: fr.length });
  await sleep(1200); await ev("P.send('RULES_LOADOUT',{category:'SPECIAL_MAGIC',slot:1,skill_id:'ATHLETE_TRACK'}); P.send('RULES_LOADOUT',{category:'PHYSICAL_MAGIC',slot:1,skill_id:'PM_PULL'}); P.send('FIELD_PRACTICE',{on:false}); return 1;"); await sleep(300);
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
try { var pg2 = await launchChrome({ width: 1800, height: 1500, gpu: false }); var groups = ['overhead_side', 'chestfly_front', 'barrage_side']; var html = '<html><body style="margin:0;background:#0b0f16;color:#eef;font:600 13px system-ui"><div style="padding:6px 10px">PHASE E — OVERHEAD EXTENSION RELEASE (side) · CHEST FLY CLAP RELEASE (front-¾) · EIGHT-STRIKE CURL BARRAGE (side) · MANUAL LOOK · normal speed · frames ≈ 110–120 ms apart · desktop GPU Chrome</div>' + groups.map(function (g) { var list = shots.filter(function (s) { return s.tag.indexOf(g) === 0; }); if (!list.length) return ''; return '<div style="display:grid;grid-template-columns:repeat(' + Math.min(9, Math.max(3, list.length)) + ',1fr);gap:3px;padding:3px">' + list.map(function (s) { return '<div><div style="padding:2px 4px;color:#fd9">' + s.tag + '</div><img src="file:///' + s.f.replace(/\\/g, '/') + '" style="width:100%"></div>'; }).join('') + '</div>'; }).join('') + '</body></html>'; var hp = path.join(OUT, '_sheet.html'); fs.writeFileSync(hp, html); await pg2.goto('file:///' + hp.replace(/\\/g, '/')); await sleep(1500); await pg2.screenshot(path.join(OUT, 'sheet_phase_e.png')); await pg2.close(); console.log('sheet ok', shots.length); } catch (e) { console.log('sheet failed', e.message); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'probe_attacks_phase_e.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT PHASE E attacks: ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
