/* MAHWORLD :: CONVERGENCE PASS 2 CAMERA PROBE — O2 both-side drag, obstruction recovery (F02), fade restore (F03), in the real page.
   node deploy/probe_camera_pass2.mjs [static_dist] [desktop|portrait|landscape]     Touch = EMULATED (synthetic pointer events). */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') && !/^(desktop|portrait|landscape)$/.test(argv[0]) ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
var MODE = argv.filter(function (a) { return /^(portrait|desktop|landscape)$/.test(a); })[0] || 'desktop'; var OUT = path.join(HERE, 'probe_out', 'camera'); fs.mkdirSync(OUT, { recursive: true }); var TOUCH = MODE !== 'desktop'; var VP = MODE === 'portrait' ? [390, 844] : (MODE === 'landscape' ? [844, 390] : [1200, 750]);
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, unlockFps: true, mobile: TOUCH }); var pass = 0, fail = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 700)); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(40); await key(code, false); }
async function ptr(type, el, id, x, y) { await pg.evaluate("(function(){ var t=document.getElementById('" + el + "'); if(!t) return 0; var e=new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'touch',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true}); t.dispatchEvent(e); })(); 1"); }
async function ptrAt(type, id, x, y) { await pg.evaluate("(function(){ var t=document.elementFromPoint(" + x + "," + y + "); if(!t) return 0; var e=new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'touch',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true}); t.dispatchEvent(e); })(); 1"); }
async function rect(id) { return await pg.evaluate("(function(){ var e=document.getElementById('" + id + "'); if(!e) return null; var r=e.getBoundingClientRect(); return {x:r.left,y:r.top,w:r.width,h:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2,shown:r.width>0&&r.height>0&&getComputedStyle(e).display!=='none'}; })()"); }
async function vw() { return await pg.evaluate("({w:innerWidth,h:innerHeight})"); }
async function cs() { return await ev("var c=P.camState(); var p=P.snap().play; return {yaw:c.yaw, pitch:c.pitch, mode:c.mode, state:c.state, err:c.err_deg, applied:c.applied, dist:c.dist, readable:c.readable, zoom:c.zoom, fade:c.fade, bias:c.pitch_bias, obstructed:c.obstructed, inside:!!c.inside, pos:[+p.position.x.toFixed(2),+p.position.z.toFixed(2)], alt:p.flight.altitude, powered:p.flight.powered};"); }
function wrapDeg(r) { var d = r * 180 / Math.PI; while (d > 180) d -= 360; while (d < -180) d += 360; return d; }
async function dragFromTo(id, x0, y0, dx, dy, ms) { await ptrAt('pointerdown', id, x0, y0); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await ptr('pointermove', 'tc-world', id, x0 + dx * i / n, y0 + dy * i / n); await sleep(40); } return { x: x0 + dx, y: y0 + dy }; }
async function mouseDrag(dx, dy, ms) { var v = await vw(); var x = v.w * 0.6, y = v.h * 0.5; await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + x + ",clientY:" + y + ",bubbles:true})); 1"); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + (x + dx * i / n) + ",clientY:" + (y + dy * i / n) + ",bubbles:true})); 1"); await sleep(40); } await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + (x + dx) + ",clientY:" + (y + dy) + ",bubbles:true})); 1"); }
async function worldPoint(x, y) { /* the nearest point at / below (x, y) whose top element is the world drag layer */ for (var k = 0; k < 12; k++) { var id = await pg.evaluate("(function(){ var e=document.elementFromPoint(" + x + "," + (y + k * 20) + "); return e?e.id:null; })()"); if (id === 'tc-world') return { x: x, y: y + k * 20 }; } return null; }
async function leftWorldPoint(v, sz) { /* empty LEFT-half game space: above the stick zone when there is room (portrait), else beside it (landscape) */ var cands = [[v.w * 0.15, sz.y - 70], [sz.x + sz.w + 40, v.h * 0.6], [v.w * 0.3, v.h * 0.5], [v.w * 0.4, v.h * 0.4]]; for (var i = 0; i < cands.length; i++) { var c = cands[i]; if (c[0] >= v.w / 2 || c[1] < 0) continue; var id = await pg.evaluate("(function(){ var e=document.elementFromPoint(" + c[0] + "," + c[1] + "); return e?e.id:null; })()"); if (id === 'tc-world') return { x: c[0], y: c[1] }; } return null; }
async function sampleFor(ms) { var out = []; var end = Date.now() + ms; while (Date.now() < end) { out.push(await cs()); await sleep(80); } return out; }
var report = { mode: MODE, viewport: VP, touch_emulated: TOUCH, checks: lines, samples: {} };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(6000); await ev("P.hud.showGuide(false); return 1;");
  for (var w = 0; w < 120; w++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); }
  await ev("return P.goTo(20, 20, undefined, undefined, 60000);"); await sleep(800); var cfg = await ev("return P.camState().cfg;");
  if (TOUCH) {
    /* ── O2: a drag on the LEFT side of the empty game space orbits (above the stick zone) ── */
    var v = await vw(); var sz = await rect('tc-stickzone'); var c0 = await cs(); var wp = await leftWorldPoint(v, sz); var lx = wp ? wp.x : v.w * 0.15, ly = wp ? wp.y : sz.y - 60;
    var pL = await dragFromTo(2, lx, ly, 140, 0, 400); await ptr('pointerup', 'tc-world', 2, pL.x, pL.y); await sleep(300); var c1 = await cs();
    ok('O2a a drag starting in empty LEFT-half game space (above or beside the joystick zone, never on it) orbits the camera (|Δ yaw| > 20°, mode orbit)', Math.abs(wrapDeg(c1.yaw - c0.yaw)) > 20 && c1.mode === 'orbit', { d_yaw: +wrapDeg(c1.yaw - c0.yaw).toFixed(1), mode: c1.mode, start: [Math.round(lx), Math.round(ly)], stick_top: Math.round(sz.y) });
    await ev("return P.camReset('probe');"); await sleep(cfg.reset_time_s * 1000 + 600); var c2 = await cs();
    /* ── O2: a drag INSIDE the joystick zone moves him and never orbits ── */
    var sx = sz.x + sz.w * 0.5, sy = sz.y + sz.h * 0.55; var p0 = c2.pos; await ptr('pointerdown', 'tc-stickzone', 1, sx, sy); for (var i = 1; i <= 4; i++) { await ptr('pointermove', 'tc-stickzone', 1, sx, sy - 30 * i); await sleep(30); } await sleep(1200); var c3 = await cs(); await ptr('pointerup', 'tc-stickzone', 1, sx, sy - 120); await sleep(600);
    ok('O2b a drag inside the joystick zone moves him (> 1.5 m) and leaves the camera in follow mode (no orbit)', Math.hypot(c3.pos[0] - p0[0], c3.pos[1] - p0[1]) > 1.5 && c3.mode === 'follow', { moved_m: +Math.hypot(c3.pos[0] - p0[0], c3.pos[1] - p0[1]).toFixed(2), mode: c3.mode });
    /* ── O2: an empty-space drag that crosses FLY never becomes a press (no take-off), and a touch that STARTS on FLY is a hold ── */
    var fly = await rect('g-fly'); var f0 = await cs(); var wp2 = await worldPoint(fly.cx - 160, Math.max(80, fly.cy - 140)); var pX = await dragFromTo(3, wp2 ? wp2.x : fly.cx - 160, wp2 ? wp2.y : fly.cy - 140, 160, fly.cy - (wp2 ? wp2.y : fly.cy - 140), 500); await sleep(100); await ptr('pointerup', 'tc-world', 3, pX.x, pX.y); await sleep(800); var f1 = await cs();
    ok('O2c an empty-space drag that ends on top of FLY is a camera drag only: no take-off, the camera orbited', !f1.powered && Math.abs(wrapDeg(f1.yaw - f0.yaw)) > 5, { powered: f1.powered, d_yaw: +wrapDeg(f1.yaw - f0.yaw).toFixed(1) });
    await ptr('pointerdown', 'g-fly', 4, fly.cx, fly.cy); await sleep(700); var f2 = await cs(); await ptr('pointerup', 'g-fly', 4, fly.cx, fly.cy); await sleep(300); ok('O2d a touch that starts ON FLY is a flight hold (powered) and does not orbit the camera', f2.powered && Math.abs(wrapDeg(f2.yaw - f1.yaw)) < 2, { powered: f2.powered, d_yaw: +wrapDeg(f2.yaw - f1.yaw).toFixed(1) });
    await ev("return P.send('FLIGHT',{op:'EXIT'});"); await sleep(3000); await ev("return P.camReset('probe');"); await sleep(cfg.reset_time_s * 1000 + 400);
    /* ── the ⟲ CAM reset control: right side, inside the viewport, ≥ 44 px, above the 2×2 cluster, not overlapping anything ── */
    var rb = await rect('g-camreset'); var others = {}; for (var id of ['g-fly', 'g-guard', 'g-morebtn', 'g-menubt', 'tc-attack', 'tc-dash', 'g-erty-t', 'tc-stickzone', 'g-flyaux']) others[id] = await rect(id);
    var clash = Object.keys(others).filter(function (k) { var o = others[k]; return o && o.shown && rb && rb.x < o.x + o.w && o.x < rb.x + rb.w && rb.y < o.y + o.h && o.y < rb.y + rb.h; });
    ok('R1 the ⟲ CAM reset control is on the RIGHT side, ≥ 44 px, inside the viewport, above the 2×2 cluster, overlapping nothing', rb && rb.shown && rb.w >= 44 && rb.h >= 44 && rb.x >= v.w * 0.6 && rb.x + rb.w <= v.w + 0.5 && rb.y >= 0 && (others['g-fly'] ? rb.y + rb.h <= others['g-fly'].y + 1 : true) && clash.length === 0, { reset: rb, clash: clash });
    await pg.screenshot(path.join(OUT, 'pass2_' + MODE + '_reset_control.png'));
  }
  /* ── F02: obstruction recovery — his back to the gym's east WALL (GYM_S384, 22 m tall) at 3.2 m, in the air: the boom must not collapse below min_readable; it pitches UP instead ── */
  await ev("return P.goTo(-60, 100, undefined, undefined, 60000);"); await sleep(400); await ev("return P.goTo(-89.3, 98.75, undefined, undefined, 60000);"); await sleep(400);   /* 3.2 m east of the gym's east wall GYM_S384 (x −92.5, 22.25 m tall), in its recess */
  await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:1.5708});"); await sleep(300); await ev("return P.send('FLIGHT',{op:'ENTER'});"); await sleep(2600); await ev("return P.send('FLIGHT',{op:'HOVER'});"); await sleep(700); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:1.5708});"); await sleep(1500);
  var sF = await sampleFor(2500); var minApplied = Math.min.apply(null, sF.map(function (x) { return x.applied; })); var maxBias = Math.max.apply(null, sF.map(function (x) { return x.bias; })); var insideN = sF.filter(function (x) { return x.inside; }).length; var last = sF[sF.length - 1]; report.samples.facade = sF;
  var readableN = last.readable !== undefined && last.readable !== null ? last.readable : cfg.min_readable_m; ok('F02a back to the wall (3.2 m, airborne, facing away): the boom stays at or above the runtime\'s readable distance (' + readableN.toFixed(2) + ' m = max(min_readable, readable_frac × preferred), −0.05 tolerance) — by pitching up when a plain shortening would go below it, zero frames inside geometry', minApplied >= readableN - 0.05 && (maxBias > 0.1 || minApplied >= readableN) && insideN === 0, { min_applied: +minApplied.toFixed(2), readable: readableN, preferred: +last.dist.toFixed(2), max_pitch_bias: +maxBias.toFixed(2), inside_frames: insideN, pos: last.pos, alt: last.alt, obstructed: last.obstructed });
  await pg.screenshot(path.join(OUT, 'pass2_' + MODE + '_facade_pitchup.png'));
  /* move away (east) → the bias unwinds and the preferred distance comes back; he is fully restored (no transparency, nothing hidden) */
  await ev("return P.send('MOVE',{forward:0,strafe:1,run:false,yaw:1.5708});"); await sleep(2500); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:1.5708});"); await sleep(3000); var cA = await cs(); var mats = await ev("return P.meMaterials();");
  ok('F02b 12 m away from the facade: pitch bias unwound (< 0.05 rad), boom back at the preferred distance (≥ 95 %), fade 1, materials restored (none transparent, no mesh hidden)', cA.bias < 0.05 && cA.applied >= cA.dist * 0.95 && cA.fade >= 0.99 && mats && mats.materials.filter(function (m) { return !m.base_transparent; }).every(function (m) { return m.transparent === false && Math.abs(m.opacity - m.base_opacity) < 1e-3; }) && mats.meshes_hidden === 0, { bias: cA.bias, applied: +cA.applied.toFixed(2), dist: +cA.dist.toFixed(2), fade: cA.fade, hidden: mats && mats.meshes_hidden, mats: mats && mats.materials.length });
  /* ── F02c overhang / niche: fly into the blue tower's recessed storeys at ~17 m (decks above, walls behind): the camera may collapse but never sits inside geometry
       and never shows a half-visible close-up (applied < 1.3 m ⇒ faded / hidden); moving out restores the preferred boom ── */
  await ev("return P.send('FLIGHT',{op:'EXIT'});"); await sleep(3500); await ev("return P.goTo(60, 60, undefined, undefined, 60000);"); await sleep(300); await ev("return P.send('FLIGHT',{op:'ENTER'});"); await sleep(2600); await ev("return P.send('FLIGHT',{op:'HOVER'});"); await sleep(400);
  for (var q = 0; q < 50; q++) { var tq = await cs(); var dq = Math.hypot(104.6 - tq.pos[0], 104.6 - tq.pos[1]); if (dq < 1.0) break; await ev("return P.send('MOVE',{forward:" + (-(104.6 - tq.pos[1]) / dq).toFixed(3) + ",strafe:" + ((104.6 - tq.pos[0]) / dq).toFixed(3) + ",run:false,yaw:" + Math.atan2(104.6 - tq.pos[0], -(104.6 - tq.pos[1])).toFixed(3) + "});"); await sleep(200); }
  await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-0.785});"); await sleep(1600); var sN = await sampleFor(2000);   /* face south-west (out of the recess): the camera behind him goes INTO the tower's storeys */ var insideNi = sN.filter(function (x) { return x.inside; }).length; var badClose = sN.filter(function (x) { return x.applied < 1.3 && x.fade >= 0.99; }).length; var minNi = Math.min.apply(null, sN.map(function (x) { return x.applied; })); var lastN = sN[sN.length - 1]; report.samples.niche = sN;
  var obstructedN = sN.filter(function (x) { return x.obstructed || x.applied < x.dist - 0.3; }).length; ok('F02c in the tower niche with the camera INTO the recess (walls behind, decks above): the boom really is obstructed (applied < preferred in ≥ 1 frame), zero frames inside geometry, no half-visible close-up (every applied < 1.3 m frame is faded / hidden), boom ≥ 0.5 m', obstructedN > 0 && insideNi === 0 && badClose === 0 && minNi >= 0.5, { obstructed_frames: obstructedN, inside_frames: insideNi, half_visible_close_frames: badClose, min_applied: +minNi.toFixed(2), preferred: +lastN.dist.toFixed(2), pos: lastN.pos, alt: lastN.alt, bias: lastN.bias });
  await pg.screenshot(path.join(OUT, 'pass2_' + MODE + '_niche.png'));
  await ev("return P.send('MOVE',{forward:1,strafe:-1,run:false,yaw:0});"); await sleep(2500); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(3000); var cN2 = await cs(); var matsN = await ev("return P.meMaterials();");
  ok('F02d out of the niche: boom back at ≥ 95 % of preferred, fade 1, bias unwound (< 0.05), nothing hidden', cN2.applied >= cN2.dist * 0.95 && cN2.fade >= 0.99 && cN2.bias < 0.05 && matsN && matsN.meshes_hidden === 0, { applied: +cN2.applied.toFixed(2), dist: +cN2.dist.toFixed(2), fade: cN2.fade, bias: cN2.bias, pos: cN2.pos });
  await ev("return P.send('FLIGHT',{op:'EXIT'});"); await sleep(4000);
  /* ── F03: a forced collapse (back 0.4 m from the temple's south wall on the ground: no pitch clears it) fades / hides him with NO half-transparent frames below 35 %, and restores exactly when clear ── */
  await ev("return P.goTo(0, 150, undefined, undefined, 60000);"); await sleep(300); await ev("return P.send('MOVE',{forward:-1,strafe:0,run:false,yaw:0});"); await sleep(4500); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1800);   /* walk +z into the temple's south wall (TEMPLE_S65/S89/S161/S182 at z 162.5, 21–23 m tall, x −10..10): the body stops at its radius; facing 0 = −z, so the camera behind him is INSIDE the wall — no pitch within the limit clears it */ var sC = await sampleFor(1200); var minA2 = Math.min.apply(null, sC.map(function (x) { return x.applied; })); var matsC = await ev("return P.meMaterials();"); var fadeC = sC[sC.length - 1].fade; var insideC = sC.filter(function (x) { return x.inside; }).length;
  ok('F03a back 0.4 m from the temple wall on the ground: the boom collapses (applied < 1.6 m), zero frames inside geometry, and the body is HIDDEN (fade below 30 % → every visible-by-design mesh hidden), never a half-transparent close-up', minA2 < 1.6 && fadeC < 0.30 && insideC === 0 && matsC && matsC.meshes_hidden > 0 && matsC.materials.filter(function (m) { return !m.base_transparent; }).every(function (m) { return m.opacity >= 0.35 * m.base_opacity - 1e-3; }), { min_applied: +minA2.toFixed(2), fade: fadeC, hidden: matsC && matsC.meshes_hidden + '/' + matsC.meshes, inside: insideC, pos: sC[sC.length - 1].pos, bias: sC[sC.length - 1].bias });
  await pg.screenshot(path.join(OUT, 'pass2_' + MODE + '_collapse.png'));
  /* ── R2: an explicit reset from a front view while his back is 0.4 m from the temple wall: the 0.5 s glide sweeps the camera through the wall's half-space — zero inside frames ── */
  var pRW = TOUCH ? await (async function () { var v3 = await vw(); var wp3 = await worldPoint(v3.w * 0.72, v3.h * 0.45); var p = await dragFromTo(5, wp3 ? wp3.x : v3.w * 0.72, wp3 ? wp3.y : v3.h * 0.45, -260, 0, 500); await ptr('pointerup', 'tc-world', 5, p.x, p.y); return p; })() : await mouseDrag(-420, 0, 600); await sleep(500); var cW0 = await cs();
  await pg.evaluate("window.__rw=[]; window.__rwOn=true; (function loop(){ if(!window.__rwOn) return; requestAnimationFrame(loop); var c=window.MAHWORLD_PLAY.camState(); window.__rw.push([c.mode, c.inside?1:0, +c.applied.toFixed(2), +c.err_deg.toFixed(1)]); })(); 1"); await ev("return P.camReset('probe-wall');"); await sleep(cfg.reset_time_s * 1000 + 700); var rw = await pg.evaluate("window.__rwOn=false; window.__rw"); var cW1 = await cs();
  ok('R2 reset at the wall (from |error| ' + Math.abs(cW0.err).toFixed(0) + '°): the glide never puts the camera inside geometry (0 inside frames over ' + rw.length + ' frames), ends behind him in follow mode', Math.abs(cW0.err) > 25 && rw.length > 10 && !rw.some(function (r) { return r[1]; }) && cW1.mode === 'follow' && Math.abs(cW1.err) < 8, { before: { err: cW0.err, mode: cW0.mode }, after: { err: cW1.err, mode: cW1.mode, applied: cW1.applied }, inside_frames: rw.filter(function (r) { return r[1]; }).length, min_applied_during: Math.min.apply(null, rw.map(function (r) { return r[2]; })) });

  await ev("return P.send('MOVE',{forward:1,strafe:0,run:false,yaw:0});"); await sleep(2200); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(2500); var cR = await cs(); var matsR = await ev("return P.meMaterials();");
  ok('F03b walked clear: fade 1, every material back to its base (transparent flag, opacity, depthWrite), no hidden mesh, boom ≥ 95 % of preferred', cR.fade >= 0.99 && matsR && matsR.meshes_hidden === 0 && matsR.materials.filter(function (m) { return !m.base_transparent; }).every(function (m) { return m.transparent === false && Math.abs(m.opacity - m.base_opacity) < 1e-3; }) && cR.applied >= cR.dist * 0.95,   /* base-opaque materials only: the aura / glow materials animate their own opacity by design */ { fade: cR.fade, applied: +cR.applied.toFixed(2), dist: +cR.dist.toFixed(2), hidden: matsR && matsR.meshes_hidden, pos: cR.pos, mismatch: matsR ? matsR.materials.filter(function (m) { return !m.base_transparent && !(m.transparent === false && Math.abs(m.opacity - m.base_opacity) < 1e-3); }) : 'no mats', terms: [cR.fade >= 0.99, !!matsR, matsR && matsR.meshes_hidden === 0, cR.applied >= cR.dist * 0.95] });
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'pass2_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT PASS2 camera ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
