/* P7 (master §14.5 / §14.7) — MAHGIC TREE PROTOTYPE EVIDENCE, in the real page (headless Chrome, GPU): the placed prototype read-out, a solid
   silhouette view (the tree in a flat unlit magenta override: its physical outline alone), front / side / three-quarter / back material views with
   the energy ON and OFF, the player-relative scale view (the reference body in its bind pose beside the specimen), the in-world rear-view framing
   walking up to and through the cluster (the boom distance is read, not assumed), the sway measured as a pixel change over 1.5 s inside the tree
   box, the render cost with and without the family, and a phone-portrait framing. Nothing here approves the tree — Jah's verdict does (U11).
   node deploy/probe_botany.mjs [static_dist] [--out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; } var OUT = path.resolve(arg('--out', path.join(HERE, 'probe_out', 'botany'))); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pass = 0, fail = 0, lines = []; var report = { checks: lines, out: OUT };
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 900)); }
var SPEC = { x: 3.0, z: 0.4 }; var CLUSTER = { x: -8.0, z: -7.3 };   /* from lab/assets/botany/prototype_v1.json */
async function session(pg, tag, phone) {
  async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
  async function shot(name) { var f = path.join(OUT, 'bot_' + tag + '_' + name + '.png'); await pg.screenshot(f); return f; }
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (phone ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(5000); await ev("P.hud.showGuide(false); return 1;");
  for (var w = 0; w < 120; w++) { var dl = await ev("var d=P.district?P.district():null; var b=P.botany?P.botany():null; return (d?d.loaded.length:-1) + (b&&b.status==='PLACED'?100:0);"); if (dl >= 104) break; await sleep(500); } await sleep(1000);
  var info = await ev("return P.botany();"); return { ev: ev, shot: shot, info: info };
}
try {
  /* ───── desktop session: the inspection set ───── */
  var pg = await launchChrome({ width: 1280, height: 800, gpu: true }); var S = await session(pg, 'desk', false); var ev = S.ev, shot = S.shot; var info = S.info; report.botany = info;
  ok('P1 the prototype registry is placed: 7 instances (1 specimen + 6 cluster), 9 instanced draw calls, 3 variants', !!info && info.status === 'PLACED' && info.instances === 7 && info.draw_calls === 9 && info.variants.length === 3, info && { status: info.status, instances: info.instances, draws: info.draw_calls, tris: info.tris_placed });
  var tops = info ? info.list.map(function (i) { return i.crown_top_m; }) : []; var band = info ? info.scale_reference : null;
  ok('P2 every placed crown top is within the hip band of the reference body (pelvis ' + (band && band.pelvis_joint_m) + ' m … femoral head ' + (band && band.femoral_head_joint_m) + ' m, ±3 cm for the authored scale variation)', tops.length && tops.every(function (t) { return t >= band.pelvis_joint_m - 0.03 && t <= band.femoral_head_joint_m + 0.03; }), tops);
  ok('P3 each variant is a rooted 4-level hierarchy with attached leaves and a few gem nodes (authored bounds: 4–5 primaries, ≤ 15 secondaries, ≤ 20 twigs, 60–150 leaves, ≤ 9000 tris)', info && info.variants.every(function (v) { return v.roots === 5 && v.levels === 4 && v.primaries >= 4 && v.primaries <= 5 && v.secondaries <= 15 && v.twigs <= 20 && v.leaves >= 60 && v.leaves <= 150 && v.tris.total <= 9000; }), info && info.variants.map(function (v) { return { seed: v.seed, top: v.crown_top_m, pri: v.primaries, sec: v.secondaries, twigs: v.twigs, leaves: v.leaves, gems: v.gems, tris: v.tris.total }; }));
  /* the reference body beside the specimen, bind pose, held */
  await ev("return P.goTo(" + (SPEC.x - 1.15) + ", " + SPEC.z + ", undefined, undefined, 60000);"); await sleep(600); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1500);
  await ev("P.holdPose('me', true); P.camFollow(false); return P.restPose('me');"); await sleep(200);   /* the inspection views are MANUAL-LOOK framings: the rear follow is off until the in-world pass */
  var me = await ev("var e=P.adapter?P.adapter.get('me'):null; var r=P.meRoot?P.meRoot('me'):null; return r?{x:r.x,y:r.y,z:r.z}:null;"); report.me_root = me;
  /* inspection views around the specimen (fixed dev camera pivoting on the tree) */
  var VIEWS = [{ n: 'front', yaw: 0 }, { n: 'threequarter', yaw: 2.356 }, { n: 'side', yaw: 1.5708 }, { n: 'back', yaw: 3.1416 }];
  async function look(yaw, pitch, dist, at) { await ev("P.cam(" + yaw + ", " + pitch + ", " + dist + ", 1.0); P.camAt(" + at.x + ", " + at.y + ", " + at.z + "); P.camCfg('fade_below_m', 0); return 1;"); await sleep(500); }
  var AT = { x: SPEC.x, y: 0.42, z: SPEC.z };
  for (var vi = 0; vi < VIEWS.length; vi++) { var v = VIEWS[vi]; await look(v.yaw, 0.12, 2.3, AT); await ev("P.vfx(true); return 1;"); await sleep(250); await shot('spec_' + v.n + '_energy_on'); await ev("P.vfx(false); return 1;"); await sleep(250); await shot('spec_' + v.n + '_energy_off'); }
  await ev("P.vfx(true); return 1;");
  /* close craft view (junctions, taper, leaf attachment) */
  await look(2.0, 0.28, 1.25, { x: SPEC.x, y: 0.55, z: SPEC.z }); await shot('spec_close_crown'); await look(2.6, -0.05, 1.1, { x: SPEC.x, y: 0.12, z: SPEC.z }); await shot('spec_close_base');
  /* solid silhouette: the tree meshes alone in a flat unlit magenta override (an exact colour nothing else in the world uses) */
  await look(1.5708, 0.06, 2.3, AT);
  var sil = await ev("var sc=P.sceneDebug(); var mat=new P.THREE.MeshBasicMaterial({color:0xff00ff, fog:false, toneMapped:false}); var saved=[]; sc.traverse(function(o){ if(o.isInstancedMesh && o.userData.botany){ saved.push([o,o.material]); o.material=mat; } }); P.renderOnce(); window.__botSil=saved; return saved.length;");
  await sleep(300); await shot('spec_silhouette_side'); await look(0, 0.06, 2.3, AT); await sleep(250); await shot('spec_silhouette_front');
  /* silhouette metrics from the drawing buffer: bounding box of the magenta pixels + fill ratio (a rod-and-diamond would be a thin column; a crown reads wide) */
  var silM = await ev("var c=document.getElementById('view'); var gl=c.getContext('webgl2')||c.getContext('webgl'); var w=gl.drawingBufferWidth, h=gl.drawingBufferHeight; var k=w/innerWidth; var cs=[]; [[-0.45,0,-0.45],[0.45,0,-0.45],[-0.45,0,0.45],[0.45,0,0.45],[-0.45,0.95,-0.45],[0.45,0.95,-0.45],[-0.45,0.95,0.45],[0.45,0.95,0.45]].forEach(function(d){ var q=P.projectPoint(" + SPEC.x + "+d[0], d[1], " + SPEC.z + "+d[2]); cs.push([q.sx*k, (innerHeight-q.sy)*k]); }); var RX0=Math.max(0,Math.floor(Math.min.apply(null,cs.map(function(c){return c[0];})))), RX1=Math.min(w-1,Math.ceil(Math.max.apply(null,cs.map(function(c){return c[0];})))), RY0=Math.max(0,Math.floor(Math.min.apply(null,cs.map(function(c){return c[1];})))), RY1=Math.min(h-1,Math.ceil(Math.max.apply(null,cs.map(function(c){return c[1];})))); P.renderOnce(); var px=new Uint8Array(w*h*4); gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px); var x0=w,x1=-1,y0=h,y1=-1,n=0; for(var y=RY0;y<=RY1;y++) for(var x=RX0;x<=RX1;x++){ var i=(y*w+x)*4; if(px[i]>200&&px[i+1]<80&&px[i+2]>200){ n++; if(x<x0)x0=x; if(x>x1)x1=x; if(y<y0)y0=y; if(y>y1)y1=y; } } if(n===0) return null; var bw=x1-x0+1, bh=y1-y0+1; var rows=[]; for(var yy=y0; yy<=y1; yy+=Math.max(1,Math.floor(bh/8))){ var cnt=0; for(var xx=x0; xx<=x1; xx++){ var j=(yy*w+xx)*4; if(px[j]>200&&px[j+1]<80&&px[j+2]>200) cnt++; } rows.push(cnt); } return {region:[RX0,RY0,RX1,RY1], pixels:n, box:[bw,bh], fill:+(n/(bw*bh)).toFixed(3), aspect:+(bw/bh).toFixed(2), width_by_row_top_to_bottom: rows};");
  report.silhouette = silM; ok('S1 the solid silhouette (front, the specimen own screen region) is a crown on a trunk, not a rod: width/height between 0.55 and 1.6, and the widest sampled row lies in the upper 70 % of the box', !!silM && silM.aspect >= 0.55 && silM.aspect <= 1.6 && (function (r) { var m = 0; for (var i = 1; i < r.length; i++) if (r[i] > r[m]) m = i; return m < r.length * 0.7; })(silM.width_by_row_top_to_bottom), silM);
  await ev("(window.__botSil||[]).forEach(function(s){ s[0].material=s[1]; }); window.__botSil=null; return 1;");
  /* player-relative scale view: the reference body (bind pose) and the specimen side by side */
  await look(1.5708, 0.08, 3.4, { x: SPEC.x - 0.55, y: 0.85, z: SPEC.z }); await shot('scale_side_by_side'); await look(0, 0.1, 3.6, { x: SPEC.x - 0.55, y: 0.85, z: SPEC.z }); await shot('scale_front_pair');
  /* hip line check in screen space: project the pelvis height and the crown top at the specimen's position */
  var proj = await ev("var a=P.projectPoint(" + SPEC.x + ", " + info.list[0].crown_top_m + ", " + SPEC.z + "); var b=P.projectPoint(" + (SPEC.x - 1.15) + ", 0.765, " + SPEC.z + "); var c=P.projectPoint(" + (SPEC.x - 1.15) + ", 0.835, " + SPEC.z + "); return {crown:a, pelvis:b, femoral:c};"); report.hip_projection = proj;
  ok('S2 in the paired view the specimen crown projects between the pelvis and femoral-head screen heights of the body beside it (±12 px)', !!proj && proj.crown && proj.pelvis && proj.crown.sy <= proj.pelvis.sy + 12 && proj.crown.sy >= proj.femoral.sy - 12, proj);
  /* sway: pixel change inside the specimen box over 1.5 s with the camera fixed and the body held (branches + leaves move gently, the trunk is grounded) */
  await look(0.6, 0.1, 2.3, AT); await sleep(400);
  var swayExpr = function (slot) { return "var c=document.getElementById('view'); var gl=c.getContext('webgl2')||c.getContext('webgl'); var w=gl.drawingBufferWidth, h=gl.drawingBufferHeight; P.renderOnce(); var px=new Uint8Array(w*h*4); gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px); window.__sw=window.__sw||{}; window.__sw['" + slot + "']={w:w,h:h,px:px}; return [w,h];"; };
  await ev(swayExpr('a')); await sleep(1500); await ev(swayExpr('b'));
  var sway = await ev("var a=window.__sw.a, b=window.__sw.b; var w=a.w,h=a.h; var changed=0, tot=0; var ys=[]; for(var y=0;y<h;y++){ var rowc=0; for(var x=0;x<w;x++){ var i=(y*w+x)*4; var d=Math.abs(a.px[i]-b.px[i])+Math.abs(a.px[i+1]-b.px[i+1])+Math.abs(a.px[i+2]-b.px[i+2]); tot++; if(d>24){ changed++; rowc++; } } ys.push(rowc); } var top=0,bot=0; for(var k=0;k<h;k++){ if(k>=h*0.5) top+=ys[k]; else bot+=ys[k]; } window.__sw=null; return {changed_pct:+(100*changed/tot).toFixed(3), upper_half:top, lower_half:bot};");
  report.sway = sway; ok('L1 gentle life: some pixels change over 1.5 s with a fixed camera and a held body (crown sway + pulse), the change is small (< 6 % of the frame) and biased toward the crown (upper half ≥ 0.8 × lower half: the trunk stays grounded)', !!sway && sway.changed_pct > 0.02 && sway.changed_pct < 6 && sway.upper_half >= sway.lower_half * 0.8, sway);
  await ev("P.holdPose('me', false); P.camFollow(true); P.cam(null); P.camAt(null); P.camCfg('fade_below_m', 1.3); return 1;");
  /* ───── in-world: the default rear view walking up to the cluster, then through it (no collider: the boom must not collapse) ───── */
  await ev("return P.goTo(-3.5, -2.5, undefined, undefined, 60000);"); await sleep(600); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:" + Math.atan2(-(CLUSTER.x + 3.5), -(CLUSTER.z + 2.5)) + "});"); await sleep(1800);
  var camA = await ev("var c=P.cam(); return {dist:c.dist, applied:c.applied, mode:c.mode, yaw:c.yaw};"); await shot('world_rear_approach'); report.cam_approach = camA;
  await ev("return P.goTo(" + CLUSTER.x + ", " + CLUSTER.z + ", undefined, undefined, 60000);"); await sleep(600); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0.9});"); await sleep(1800);
  var camB = await ev("var c=P.cam(); return {dist:c.dist, applied:c.applied, mode:c.mode, yaw:c.yaw};"); await shot('world_rear_inside_cluster'); report.cam_inside = camB;
  ok('W1 standing inside the cluster the rear camera keeps its preferred boom (foliage is decorative: no collider, no camera shove)', !!camB && (camB.applied === undefined || camB.applied === null || camB.applied >= (camB.dist || 0) - 0.05), { approach: camA, inside: camB });
  await ev("P.vfx(false); return 1;"); await sleep(250); await shot('world_rear_inside_cluster_energy_off'); await ev("P.vfx(true); return 1;"); await sleep(250);
  /* wider composition: the cluster from a manual-look angle (labelled MANUAL LOOK), effects on */
  await ev("P.cam(2.3, 0.22, 6.5, 0.9); P.camAt(" + CLUSTER.x + ", 0.5, " + CLUSTER.z + "); return 1;"); await sleep(500); await shot('world_cluster_wide_MANUAL_LOOK');
  /* MATCHED WORKLOAD in ONE page load: the family hidden vs shown at the same camera (the cluster in view from the rear-follow spot), renderer draw calls /
     triangles per frame (main pass + the sun-shadow pass), and the mean frame interval over 120 rendered frames each, alternated twice (A B A B) */
  await ev("P.cam(null); P.camAt(null); return 1;"); await sleep(300);
  var meas = async function (on) { await ev("P.botanyVisible(" + on + "); return 1;"); await sleep(250); return await ev("return new Promise(function(res){ var n=0, t0=performance.now(), rs=[]; function f(){ n++; var p=P.perf(); rs.push(p.render_ms||0); if(n>=120){ var r=P.renderInfo(); var s=rs.slice(20).sort(function(a,b){return a-b;}); res({calls:r.calls, triangles:r.triangles, frame_ms_mean:+((performance.now()-t0)/n).toFixed(3), render_ms_p50:+s[Math.floor(s.length/2)].toFixed(3), render_ms_p95:+s[Math.floor(s.length*0.95)].toFixed(3)}); } else requestAnimationFrame(f); } requestAnimationFrame(f); });"); };
  var mOff1 = await meas(false), mOn1 = await meas(true), mOff2 = await meas(false), mOn2 = await meas(true); await ev("P.botanyVisible(true); return 1;");
  report.matched_workload = { off: [mOff1, mOff2], on: [mOn1, mOn2], placed: { tris: info.tris_placed, by_part: info.tris_placed_by_part, shadow_casting: info.shadow_casting_tris, draws: info.draw_calls, instances: info.instances } };
  var dTri = ((mOn1.triangles + mOn2.triangles) - (mOff1.triangles + mOff2.triangles)) / 2, dCalls = ((mOn1.calls + mOn2.calls) - (mOff1.calls + mOff2.calls)) / 2, dMs = ((mOn1.frame_ms_mean + mOn2.frame_ms_mean) - (mOff1.frame_ms_mean + mOff2.frame_ms_mean)) / 2;
  report.matched_workload.delta = { triangles: dTri, calls: dCalls, frame_ms_mean: +dMs.toFixed(3), expected_triangles_main_plus_shadow: info.tris_placed + info.shadow_casting_tris };
  ok('C0 matched workload (same load, same camera, A B A B): the family adds ' + dCalls + ' draw calls and ' + dTri + ' renderer triangles per frame (placed ' + info.tris_placed + ' + shadow-casting ' + info.shadow_casting_tris + ' = ' + (info.tris_placed + info.shadow_casting_tris) + ' expected when every instanced draw is in view in both passes) and ' + dMs.toFixed(2) + ' ms of mean frame interval (desktop, uncapped)', dCalls >= 6 && dCalls <= 16 && dTri > 0 && dTri <= info.tris_placed + info.shadow_casting_tris + 500, report.matched_workload);   /* 9 instanced draws in the main pass + up to 6 in the sun-shadow pass (gems do not cast) */
  var ri = { calls: mOn2.calls, triangles: mOn2.triangles, render_ms: mOn2.render_ms_p50 }; report.render_with = ri;
  await pg.close();
  var pg2 = await launchChrome({ width: 1280, height: 800, gpu: true }); async function ev2(expr) { return await pg2.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
  await pg2.goto(srv.origin + PLAY_PATH + '?field=1&dev=1&botany=0'); await waitForGame(pg2, 120000); await sleep(5000); await ev2("P.hud.showGuide(false); return 1;"); for (var w2 = 0; w2 < 120; w2++) { var dl2 = await ev2("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl2 >= 4) break; await sleep(500); } await sleep(1000);
  await ev2("return P.goTo(" + CLUSTER.x + ", " + CLUSTER.z + ", undefined, undefined, 60000);"); await sleep(600); await ev2("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0.9});"); await sleep(1800);
  var ri0 = await ev2("var r=P.renderInfo(); var p=P.perf(); var b=P.botany(); return {calls:r.calls, triangles:r.triangles, render_ms:p.render_ms, botany:b&&b.status};"); report.render_without = ri0; await pg2.screenshot(path.join(OUT, 'bot_desk_world_rear_inside_cluster_BOTANY_OFF.png')); await pg2.close();
  ok('C1 cost of the whole prototype (7 instances, ~44 k placed tris, drawn again in the sun-shadow pass) at the same spot: +draw calls ≤ 12 and +triangles ≤ 100 000 versus ?botany=0 (the call count also moves with LOD / culling between two page loads: read the delta as indicative)', !!ri && !!ri0 && (ri.calls - ri0.calls) <= 12 && (ri.triangles - ri0.triangles) <= 100000, { with: ri, without: ri0, delta_calls: ri && ri0 ? ri.calls - ri0.calls : null, delta_tris: ri && ri0 ? ri.triangles - ri0.triangles : null });
  /* ───── phone portrait: ordinary gameplay framing (emulated device, not a physical phone) ───── */
  var pg3 = await launchChrome({ width: 390, height: 844, gpu: true, mobile: true, dpr: 2 }); var S3 = await session(pg3, 'phone', true);
  await S3.ev("return P.goTo(-4.2, -3.2, undefined, undefined, 60000);"); await sleep(600); await S3.ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:" + Math.atan2(-(CLUSTER.x + 4.2), -(CLUSTER.z + 3.2)) + "});"); await sleep(1800); await S3.shot('world_rear_approach_portrait');
  await S3.ev("return P.goTo(" + (SPEC.x - 2.2) + ", " + (SPEC.z + 1.6) + ", undefined, undefined, 60000);"); await sleep(600); await S3.ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:" + Math.atan2(-2.2, 1.6) + "});"); await sleep(1800); await S3.shot('world_specimen_portrait');
  var measP = async function (on) { await S3.ev("P.botanyVisible(" + on + "); return 1;"); await sleep(250); return await S3.ev("return new Promise(function(res){ var n=0, t0=performance.now(), rs=[]; function f(){ n++; var p=P.perf(); rs.push(p.render_ms||0); if(n>=120){ var r=P.renderInfo(); var s=rs.slice(20).sort(function(a,b){return a-b;}); res({calls:r.calls, triangles:r.triangles, frame_ms_mean:+((performance.now()-t0)/n).toFixed(3), render_ms_p50:+s[Math.floor(s.length/2)].toFixed(3), render_ms_p95:+s[Math.floor(s.length*0.95)].toFixed(3)}); } else requestAnimationFrame(f); } requestAnimationFrame(f); });"); };
  await S3.ev("return P.goTo(-4.2, -3.2, undefined, undefined, 60000);"); await sleep(500); await S3.ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:" + Math.atan2(-(CLUSTER.x + 4.2), -(CLUSTER.z + 3.2)) + "});"); await sleep(1500);
  var pOff1 = await measP(false), pOn1 = await measP(true), pOff2 = await measP(false), pOn2 = await measP(true); await S3.ev("P.botanyVisible(true); return 1;");
  report.phone_matched_workload = { off: [pOff1, pOff2], on: [pOn1, pOn2], delta: { triangles: ((pOn1.triangles + pOn2.triangles) - (pOff1.triangles + pOff2.triangles)) / 2, calls: ((pOn1.calls + pOn2.calls) - (pOff1.calls + pOff2.calls)) / 2, frame_ms_mean: +(((pOn1.frame_ms_mean + pOn2.frame_ms_mean) - (pOff1.frame_ms_mean + pOff2.frame_ms_mean)) / 2).toFixed(3) } };
  ok('M2 phone-portrait matched workload (EMULATED 390x844 @ DPR 2, same load, A B A B): +' + report.phone_matched_workload.delta.calls + ' calls, +' + report.phone_matched_workload.delta.triangles + ' triangles, ' + report.phone_matched_workload.delta.frame_ms_mean + ' ms mean frame interval', true, report.phone_matched_workload);
  var ph = { calls: pOn2.calls, triangles: pOn2.triangles, render_ms: pOn2.render_ms_p50 }; report.phone_render = ph; await pg3.close();
  ok('M1 phone-portrait framing captured (EMULATED DEVICE: 390×844 @ DPR 2) with the family placed', !!ph, ph);
  var errs = pg3.errors.concat(pg2.errors || []).filter(function (x) { return !/404/.test(x); }); ok('Z zero page / console errors with the family placed (the shader hooks compiled)', errs.length === 0, errs.slice(0, 3));
} catch (e) { ok('X probe ran to the end', false, String(e && e.stack || e)); }
finally { try { srv.close(); } catch (e) { } }
report.summary = { pass: pass, fail: fail }; fs.writeFileSync(path.join(OUT, 'probe_botany.json'), JSON.stringify(report, null, 1)); console.log('PASS ' + pass + ' FAIL ' + fail + ' → ' + OUT); process.exit(fail ? 1 : 0);
