/* O1 (convergence 2026-09-17): a released drag PERSISTS as a manual orbit — every former "returns behind him" expectation is SUPERSEDED — O1;
   the audit now asserts the gesture ownership itself (one DRAG session, no stuck DRAG, keys released, modal ownership, lock cleanliness) and that the
   orbit persists (mode ORBIT, dragging false); an explicit reset (dev API) restores FOLLOW between cases so each case starts from the rear view.
   MAHWORLD :: SECTION 2 GESTURE AUDIT — the control paths PASS 2 touched (look drag / swipe, joystick latch, flight keys), ONE GESTURE =
   ONE INTENDED RESULT. One line per specified case; a case this harness cannot exercise is reported NOT EXERCISED (never PASS).
   Touch = EMULATED (synthetic pointer events on the real zones). node deploy/probe_spec_b_gestures.mjs [static_dist] [portrait|desktop] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !/^(portrait|desktop)$/.test(argv[0]) ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
var MODE = argv.filter(function (a) { return /^(portrait|desktop)$/.test(a); })[0] || 'portrait'; var OUT = path.join(HERE, 'probe_out', 'spec_b'); fs.mkdirSync(OUT, { recursive: true }); var TOUCH = MODE === 'portrait'; var VP = TOUCH ? [390, 844] : [1200, 750];
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, unlockFps: true }); var pass = 0, fail = 0, na = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l); }
function notExercised(id, why) { na++; var l = 'NOT EXERCISED ' + id + ' — ' + why; lines.push(l); console.log(l); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(40); await key(code, false); }
async function ptr(type, el, id, x, y) { await pg.evaluate("(function(){ var t=document.getElementById('" + el + "'); if(!t) return; var e=new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'touch',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true}); t.dispatchEvent(e); })(); 1"); }
async function vw() { return await ev("return {w:innerWidth,h:innerHeight};"); }
async function lookDown(id, dx) { var v = await vw(); var x = v.w * 0.72, y = v.h * 0.45; await ptr('pointerdown', 'tc-world', id, x, y); for (var i = 1; i <= 6; i++) { await ptr('pointermove', 'tc-world', id, x + dx * i / 6, y); await sleep(35); } return { x: x + dx, y: y }; }
async function mouseDown(dx) { var v = await vw(); var x = v.w * 0.6, y = v.h * 0.5; await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + x + ",clientY:" + y + ",bubbles:true})); 1"); for (var i = 1; i <= 6; i++) { await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + (x + dx * i / 6) + ",clientY:" + y + ",bubbles:true})); 1"); await sleep(35); } return { x: x + dx, y: y }; }
async function up(p, id) { if (TOUCH) await ptr('pointerup', 'tc-world', id || 2, p.x, p.y); else await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + p.x + ",clientY:" + p.y + ",bubbles:true})); 1"); }
async function resetCam() { await ev("return P.camReset('gesture-audit');"); await sleep(900); }
async function st() { return await ev("var c=P.camState(); return {state:c.state, err:c.err_deg, yaw:+c.yaw.toFixed(3), dragging:c.dragging};"); }
var report = { mode: MODE, viewport: VP, touch_emulated: TOUCH, lines: lines };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(6000); await ev("P.hud.showGuide(false); return 1;"); await sleep(1500);
  /* tap vs swipe: a tap inside the look zone must not orbit */
  var y0 = await st(); if (TOUCH) { var v = await vw(); await ptr('pointerdown', 'tc-world', 2, v.w * 0.7, v.h * 0.45); await sleep(60); await ptr('pointerup', 'tc-world', 2, v.w * 0.7 + 3, v.h * 0.45); } else { var v2 = await vw(); await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + (v2.w * 0.6) + ",clientY:" + (v2.h * 0.5) + ",bubbles:true})); 1"); await sleep(60); await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + (v2.w * 0.6 + 3) + ",clientY:" + (v2.h * 0.5) + ",bubbles:true})); 1"); }
  await sleep(300); var y1 = await st(); ok('tap/swipe conflict: a tap (3 px) in the look area never orbits the camera and never leaves DRAG state', Math.abs(y1.yaw - y0.yaw) < 0.01 && y1.state !== 'DRAG', { before: y0, after: y1 });
  /* double fire: one swipe = one drag session (state DRAG once, exactly one release → one return) */
  var p1 = TOUCH ? await lookDown(2, -120) : await mouseDown(-160); var s1 = await st(); await up(p1); await sleep(80); var s2 = await st(); await sleep(1400); var s3 = await st();
  ok('double fire: one swipe → one DRAG session → the orbit PERSISTS after release (ORBIT, not dragging, yaw unchanged: no second orbit, no return) — SUPERSEDED — O1: the old one-return expectation', s1.state === 'DRAG' && s2.state === 'ORBIT' && !s2.dragging && s3.state === 'ORBIT' && Math.abs(s3.yaw - s2.yaw) < 0.01, { during: s1, after_release: s2, settled: s3 }); await resetCam();
  /* interrupted drag: the finger is cancelled (pointercancel) mid-drag → the drag ends cleanly, the return runs */
  if (TOUCH) { var p2 = await lookDown(2, -100); await ptr('pointercancel', 'tc-world', 2, p2.x, p2.y); await sleep(1400); var s4 = await st(); ok('interrupted drag (pointercancel mid-swipe): no stuck DRAG (orbit persists per O1; the explicit reset then returns behind him)', s4.state !== 'DRAG' && !s4.dragging, s4); await resetCam(); var s4r = await st(); ok('interrupted drag → explicit reset returns behind him (|err| < 5°)', s4r.state === 'FOLLOW' && Math.abs(s4r.err) < 5, s4r); }
  else { var p2 = await mouseDown(-120); await pg.evaluate("dispatchEvent(new Event('blur')); 1"); await sleep(1400); var s4 = await st(); ok('interrupted drag (window blur mid-drag): no stuck DRAG (orbit persists per O1; the explicit reset then returns behind him)', s4.state !== 'DRAG' && !s4.dragging, s4); await resetCam(); var s4r = await st(); ok('interrupted drag → explicit reset returns behind him (|err| < 5°)', s4r.state === 'FOLLOW' && Math.abs(s4r.err) < 5, s4r); }
  /* background → foreground: visibility hidden mid-drag AND mid-move releases everything (no stuck pressed state, flight → HOVER) */
  var p3 = TOUCH ? await lookDown(2, -90) : await mouseDown(-120); await key('KeyW', true); await sleep(200);
  await pg.evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:function(){return true;}}); document.dispatchEvent(new Event('visibilitychange')); 1"); await sleep(300); var s5 = await st(); var mv = await ev("return {f:P.camState().move_f, in_fwd:P.camState().in_fwd};");
  await pg.evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:function(){return false;}}); document.dispatchEvent(new Event('visibilitychange')); 1"); await sleep(1400); var s6 = await st();
  ok('background → foreground: hidden mid-drag + mid-move releases the drag and the keys (no stuck pressed state); back in front the view is where the finger left it (ORBIT, not dragging) — SUPERSEDED — O1: the old return-behind expectation', s5.state !== 'DRAG' && mv.in_fwd === 0 && Math.abs(mv.f) < 0.01 && s6.state !== 'DRAG' && !s6.dragging, { hidden: s5, move: mv, back: s6 }); await resetCam();
  await key('KeyW', false); if (TOUCH) await ptr('pointerup', 'tc-world', 2, p3.x, p3.y); else await up(p3);
  /* rapid drag / release / drag: a new swipe during the glide cancels the glide (no fight between the glide and the finger) */
  var p4 = TOUCH ? await lookDown(2, -120) : await mouseDown(-160); await up(p4); await sleep(600); var p5 = TOUCH ? await lookDown(2, 60) : await mouseDown(80); var s7 = await st(); await sleep(120); var s7b = await st(); await up(p5); await sleep(1500); var s8 = await st();
  ok('rapid release/re-drag: the second swipe takes over at once (DRAG, nothing fights the finger), then the orbit persists (ORBIT) — SUPERSEDED — O1: the old single-return expectation', s7.state === 'DRAG' && s7b.state === 'DRAG' && Math.abs(s7b.yaw - s7.yaw) < 0.01 && s8.state === 'ORBIT' && !s8.dragging, { re_drag: s7, held: s7b, settled: s8 }); await resetCam();
  /* modal race: menu opened while the finger is down → the drag ends, no orbit while the menu owns input, clean state after */
  var p6 = TOUCH ? await lookDown(2, -80) : await mouseDown(-100); await tap('KeyQ'); await sleep(200); var open = await ev("return P.menu.isOpen();"); var yA = (await st()).yaw; if (TOUCH) { await ptr('pointermove', 'tc-world', 2, p6.x - 80, p6.y); } else { await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + (p6.x - 80) + ",clientY:" + p6.y + ",bubbles:true})); 1"); } await sleep(100); var yB = (await st()).yaw; await up(p6); await tap('KeyQ'); await sleep(1400); var s9 = await st();
  ok('modal race: the menu opened mid-drag owns input (no orbit from further movement), release + close leaves no DRAG and the menu closed — SUPERSEDED — O1: the old FOLLOW-behind expectation', open === true && Math.abs(yB - yA) < 0.01 && s9.state !== 'DRAG' && !s9.dragging && !(await ev("return P.menu.isOpen();")), { menu_open: open, yaw_before: yA, yaw_after_move: yB, settled: s9 }); await resetCam();
  /* click-through: a drag that starts on a control never moves the camera (touch: pointerdown on the FLY button then a swipe) */
  if (TOUCH) { var yc0 = (await st()).yaw; var r = await ev("var b=document.getElementById('g-fly'); var rc=b.getBoundingClientRect(); return {x:rc.left+rc.width/2,y:rc.top+rc.height/2};"); await pg.evaluate("(function(){ var b=document.getElementById('g-fly'); var e=new PointerEvent('pointerdown',{pointerId:3,pointerType:'touch',clientX:" + r.x + ",clientY:" + r.y + ",bubbles:true,cancelable:true}); b.dispatchEvent(e); })(); 1"); for (var i = 1; i <= 5; i++) { await pg.evaluate("(function(){ var e=new PointerEvent('pointermove',{pointerId:3,pointerType:'touch',clientX:" + (r.x - 30 * i) + ",clientY:" + r.y + ",bubbles:true,cancelable:true}); document.elementFromPoint(" + (r.x - 30 * i) + "," + r.y + ").dispatchEvent(e); })(); 1"); await sleep(30); } await pg.evaluate("(function(){ var e=new PointerEvent('pointerup',{pointerId:3,pointerType:'touch',clientX:" + (r.x - 150) + ",clientY:" + r.y + ",bubbles:true,cancelable:true}); document.elementFromPoint(" + (r.x - 150) + "," + r.y + ").dispatchEvent(e); })(); 1"); await sleep(300); var yc1 = (await st()).yaw; var flying = await ev("return !!P.snap().play.flight.powered;"); ok('click-through: a drag that starts on the FLY button never moves the camera', Math.abs(yc1 - yc0) < 0.01, { yaw0: yc0, yaw1: yc1, flight_started: flying }); if (flying) { await tap('KeyF'); await sleep(4000); } }
  else notExercised('click-through: drag starting on a control', 'desktop has no touch buttons on the look path; the mouse handlers only start a drag on the canvas (#view)');
  /* lock → unlock: locked, the camera sits on the target line; unlocked, it returns behind his facing */
  var tgt = await ev("var p=P.snap().play; var o=(p.rules&&p.rules.others||[]).filter(function(x){return !x.ally;}); return o[0]?o[0].id:null;");
  if (tgt) { await ev("return P.send('LOCK_TARGET',{aim_id:" + JSON.stringify(tgt) + "});"); await sleep(2000); var lkOn = await ev("return !!(P.snap().play.rules&&P.snap().play.rules.me.lock);"); await ev("return P.send('LOCK_TARGET',{aim_id:null});"); await sleep(2000); var s10 = await st(); ok('lock → unlock: lock-on engaged and released cleanly; after unlock the camera (in FOLLOW after the reset) is behind his facing again', lkOn && s10.state === 'FOLLOW' && Math.abs(s10.err) < 5, { locked: lkOn, after: s10 }); }
  else notExercised('lock → unlock', 'no non-ally target in the practice field snapshot');
  /* stuck pressed state: a drag whose pointerup lands OUTSIDE the zone (finger slid off the screen edge) still ends */
  if (TOUCH) { var p7 = await lookDown(2, -100); await pg.evaluate("(function(){ var e=new PointerEvent('pointerup',{pointerId:2,pointerType:'touch',clientX:-5,clientY:" + p7.y + ",bubbles:true,cancelable:true}); document.dispatchEvent(e); })(); 1"); await sleep(1500); var s11 = await st(); ok('stuck pressed state: pointerup outside the look zone (finger slid off) still ends the drag (no DRAG, orbit persists per O1)', s11.state !== 'DRAG' && !s11.dragging, s11); await resetCam(); }
  else { var p7 = await mouseDown(-100); await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:-5,clientY:" + p7.y + ",bubbles:true})); 1"); await sleep(1500); var s11 = await st(); ok('stuck pressed state: mouseup outside the canvas still ends the drag (no DRAG, orbit persists per O1)', s11.state !== 'DRAG' && !s11.dragging, s11); await resetCam(); }
  /* duplicate / stale listeners: the number of drag sessions equals the number of swipes (counted through the camera state transitions) */
  var trans = 0; await pg.evaluate("window.__gs={n:0,last:null}; (function loop(){ requestAnimationFrame(loop); var s=window.MAHWORLD_PLAY.camState().state; if (s==='DRAG' && window.__gs.last!=='DRAG') window.__gs.n++; window.__gs.last=s; })(); 1"); for (var k = 0; k < 3; k++) { var pk = TOUCH ? await lookDown(2, -60) : await mouseDown(-80); await up(pk); await sleep(1300); } trans = await pg.evaluate("window.__gs.n");
  ok('duplicate / stale listeners: 3 swipes → exactly 3 DRAG sessions', trans === 3, { drag_sessions: trans });
  notExercised('swipe/slider conflict', 'no slider lives on the look path (the Control Lab overlay stops pointer propagation at its root — inspected, not exercised here)');
  notExercised('duplicated audio', 'the camera path plays no audio');
  notExercised('network loss', 'the demo authority is in-page; no network on the camera path');
  notExercised('async results landing after UI ownership changed', 'no async result feeds the camera (the follow reads the live root yaw each frame)');
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.slice(0, 3));
} catch (e) { ok('X audit completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; report.not_exercised = na; fs.writeFileSync(path.join(OUT, 'spec_b_gestures_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT gesture audit ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed, ' + na + ' not exercised'); process.exit(fail ? 1 : 0);
