/* MAHWORLD :: SPEC B EXTRA CHECKS (PASS 2) — the rules the acceptance line does not name but Spec B states:
     E1 flight: forward flies where the camera looks, pitch included (camera pitched below home while flying forward → altitude rises; pitched well above → falls)
     E2 lock-on: his back stays to the camera and the camera sits on the target → him line (yaw error to that line < 5° after settling), distance extends to frame both
     E3 movement frame: a stick / key swing under the re-latch angle keeps the latched camera yaw; a larger swing re-latches; lifting clears the latch
     E4 speed feel: FOV widens and the boom lengthens gradually at run speed, both return at rest
     E5 collision ease: the boom shortens against a wall and eases OUT slowly afterwards (no snap); the per-frame pull-in is asserted by the Spec B probe's B1 (zero frames inside)
   Touch = EMULATED (synthetic pointer events). node deploy/probe_spec_b_extra.mjs [static_dist] [desktop|portrait] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !/^(portrait|desktop)$/.test(argv[0]) ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
var MODE = argv.filter(function (a) { return /^(portrait|desktop)$/.test(a); })[0] || 'desktop'; var OUT = path.join(HERE, 'probe_out', 'spec_b'); fs.mkdirSync(OUT, { recursive: true }); var TOUCH = MODE === 'portrait'; var VP = TOUCH ? [390, 844] : [1200, 750];
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, unlockFps: true }); var pass = 0, fail = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(40); await key(code, false); }
async function ptr(type, el, id, x, y) { await pg.evaluate("(function(){ var t=document.getElementById('" + el + "'); var e=new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'touch',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true}); t.dispatchEvent(e); })(); 1"); }
async function vw() { return await ev("return {w:innerWidth,h:innerHeight};"); }
async function lookDrag(dx, dy, ms) { var v = await vw(); var x = v.w * 0.72, y = v.h * 0.45; await ptr('pointerdown', 'tc-world', 2, x, y); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await ptr('pointermove', 'tc-world', 2, x + dx * i / n, y + dy * i / n); await sleep(40); } return { x: x + dx, y: y + dy }; }
async function lookRelease(p) { await ptr('pointerup', 'tc-world', 2, p.x, p.y); }
async function mouseDrag(dx, dy, ms) { var v = await vw(); var x = v.w * 0.6, y = v.h * 0.5; await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + x + ",clientY:" + y + ",bubbles:true})); 1"); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + (x + dx * i / n) + ",clientY:" + (y + dy * i / n) + ",bubbles:true})); 1"); await sleep(40); } return { x: x + dx, y: y + dy }; }
async function mouseUp(p) { await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + p.x + ",clientY:" + p.y + ",bubbles:true})); 1"); }
async function stickTo(id, x0, y0, dx, dy) { for (var i = 1; i <= 4; i++) { await ptr('pointermove', 'tc-stickzone', id, x0 + dx * i / 4, y0 + dy * i / 4); await sleep(25); } }
var report = { mode: MODE, viewport: VP, touch_emulated: TOUCH, checks: lines };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(6000); await ev("P.hud.showGuide(false); return 1;");
  for (var w = 0; w < 120; w++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); } await sleep(1000);
  /* E4 speed feel (desktop: Shift+W; touch: stick pushed past the ring) */
  var f0 = await ev("var c=P.camState(); return {fov:c.fov, dist:c.dist, k:c.speedK};");
  if (TOUCH) { var v = await vw(); var sx = v.w * 0.2, sy = v.h * 0.72; await ptr('pointerdown', 'tc-stickzone', 1, sx, sy); await stickTo(1, sx, sy, 0, -140); await sleep(2500); var f1 = await ev("var c=P.camState(); return {fov:c.fov, dist:c.dist, k:c.speedK};"); await ptr('pointerup', 'tc-stickzone', 1, sx, sy - 140); }
  else { await key('ShiftLeft', true); await key('KeyW', true); await sleep(2500); var f1 = await ev("var c=P.camState(); return {fov:c.fov, dist:c.dist, k:c.speedK};"); await key('KeyW', false); await key('ShiftLeft', false); }
  await sleep(2500); var f2 = await ev("var c=P.camState(); return {fov:c.fov, dist:c.dist, k:c.speedK};");
  var cfgE = await ev("return P.camCfg();"); if (cfgE.speed_fov_deg > 0 || cfgE.speed_pullback > 0) ok('E4 speed feel: at run speed the FOV widens and the boom lengthens (k → 1), both return at rest', f1.k > 0.9 && f1.fov > f0.fov + 3 && f1.dist > f0.dist * 1.05 && f2.k < 0.1 && Math.abs(f2.fov - f0.fov) < 0.5, { rest: f0, run: f1, back: f2 });
  else ok('E4 (owner rule: nothing but a drag moves the view): at run speed the FOV and the boom do NOT change', Math.abs(f1.fov - f0.fov) < 0.01 && Math.abs(f1.dist - f0.dist) < 0.01 && Math.abs(f2.fov - f0.fov) < 0.01, { rest: f0, run: f1, back: f2 });
  /* E3 movement frame: latch + re-latch */
  if (TOUCH) { var v2 = await vw(); var x0 = v2.w * 0.2, y0 = v2.h * 0.72; await ptr('pointerdown', 'tc-stickzone', 1, x0, y0); await stickTo(1, x0, y0, 0, -80); await sleep(400); var L0 = await ev("var c=P.camState(); return c.latch;"); await stickTo(1, x0, y0, 40, -70); await sleep(300); var L1 = await ev("var c=P.camState(); return c.latch;"); await stickTo(1, x0, y0, 80, 0); await sleep(300); var L2 = await ev("var c=P.camState(); return c.latch;"); await ptr('pointerup', 'tc-stickzone', 1, x0 + 80, y0); await sleep(300); var L3 = await ev("var c=P.camState(); return c.latch;"); }
  else { await key('KeyW', true); await sleep(400); var L0 = await ev("var c=P.camState(); return c.latch;"); await key('KeyD', true); await sleep(300); var L1 = await ev("var c=P.camState(); return c.latch;"); await key('KeyW', false); await sleep(300); var L2 = await ev("var c=P.camState(); return c.latch;"); await key('KeyD', false); await sleep(300); var L3 = await ev("var c=P.camState(); return c.latch;"); }
  ok('E3 movement frame: a swing under 45° keeps the latch (forward → forward-right = 45°: ' + (TOUCH ? '~30°' : 'exactly 45°, kept') + '); a 90° swing re-latches; lifting clears it', !!L0 && !!L1 && Math.abs(L1.ang - L0.ang) < 1e-6 && !!L2 && Math.abs(L2.ang - L0.ang) > 0.5 && L3 === null, { L0: L0, L1: L1, L2: L2, L3: L3 });
  await sleep(1500);
  /* E2 lock-on (an open spot so the boom is not collapsed by a wall) */
  await ev("return P.goTo(20, 20, undefined, undefined, 60000);"); await sleep(800);   /* an open spot (boom clear in all directions), a target ~10 m away */
  var tgt = await ev("var p=P.snap().play; var o=(p.rules&&p.rules.others||[]).filter(function(x){return !x.ally;}); o.sort(function(a,b){ return Math.hypot(a.position.x-p.position.x,a.position.z-p.position.z)-Math.hypot(b.position.x-p.position.x,b.position.z-p.position.z); }); return o[0]?{id:o[0].id,pos:o[0].position}:null;");
  if (tgt) { await ev("var p=P.snap().play.position; var t=" + JSON.stringify(tgt.pos) + "; var yaw=Math.atan2(t.x-p.x, -(t.z-p.z)); return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:yaw});"); await sleep(1500);   /* face the target first (a player locks what is in front of them) */ await ev("return P.send('LOCK_TARGET',{aim_id:" + JSON.stringify(tgt.id) + "});"); await sleep(2500); var lk = await ev("var p=P.snap().play; var me=p.position; var c=P.camState(); var t=" + JSON.stringify(tgt.pos) + "; var lineYaw=Math.atan2(-(t.x-me.x), -(t.z-me.z)); var err=Math.atan2(Math.sin(lineYaw-c.yaw),Math.cos(lineYaw-c.yaw))*180/Math.PI; var tp=P.projectPoint(t.x, 1.0, t.z); var bx=P.screenBox(); return {locked:!!(p.rules&&p.rules.me.lock), err_line_deg:+err.toFixed(2), dist:c.dist, applied:c.applied, tdist:Math.hypot(t.x-me.x,t.z-me.z), target_on_screen:tp.on_screen, target_px:[tp.sx,tp.sy], him_on_screen: bx.left>0 && bx.right<bx.w && bx.top>0 && bx.bottom<bx.h};");
    var base = await ev("var me=P.snap().play; return P.camState().cfg;"); await pg.screenshot(path.join(OUT, 'spec_b_extra_' + MODE + '_lock.png')); ok('E2 lock-on (owner rule: the camera stays on HIS back; a locked player faces the target): locked, camera on the target → him line (|error| < 5°), both on screen', lk.locked && Math.abs(lk.err_line_deg) < 5 && lk.target_on_screen && lk.him_on_screen, lk); await ev("return P.send('LOCK_TARGET',{aim_id:null});"); await sleep(800); }
  else ok('E2 lock-on: a non-ally target exists in the practice field', false, 'no target');
  /* E1 flight pitch — SUPERSEDED — O4 (convergence 2026-09-17): looking up / down never changes altitude; the camera-pitch → vertical rule was removed.
     Replacement: deploy/probe_flight_o4.mjs (A2 desktop / T4 touch) + 16_TESTS/gameplay_flight_f01.test.mjs. Kept here as a labelled marker, not a check. */
  console.log('SUPERSEDED — O4: E1 flight pitch → vertical (replaced by probe_flight_o4 A2 / T4)'); lines.push('SUPERSEDED — O4: E1 flight pitch → vertical');
  /* E5 collision ease: walk backwards into the arena wall, then away — the boom pulls in at once and eases out */
  var tz = await ev("var d=P.district(); var t=d&&d.loaded.filter(function(x){return x.id==='temple';})[0]; return t?1:0;"); var wallZ = await ev("return fetch('assets/buildings/district_v1.json').then(function(r){return r.json();}).then(function(m){ var t=m.buildings.filter(function(b){return b.id==='temple';})[0]; return t.envelope_m.z1; });"); await ev("return P.goTo(0, " + (wallZ - 3.5).toFixed(1) + ", undefined, undefined, 60000);"); await sleep(600);   /* 3.5 m before the temple's south face (from the live manifest: the landmarks are 0.67× now) */ await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1500);
  await ev("return P.send('MOVE',{forward:-1,strafe:0,run:false,yaw:0});"); var ap = []; for (var i = 0; i < 40; i++) { ap.push(await ev("var c=P.camState(); return +c.applied.toFixed(2);")); await sleep(100); } await ev("return P.send('MOVE',{forward:0,strafe:0,run:false});"); await sleep(300);
  var minA = Math.min.apply(null, ap); await ev("return P.send('MOVE',{forward:1,strafe:0,run:false});"); var out = []; for (var j = 0; j < 40; j++) { out.push(await ev("var c=P.camState(); return +c.applied.toFixed(2);")); await sleep(100); } await ev("return P.send('MOVE',{forward:0,strafe:0,run:false});");
  var maxStepOut = 0; for (var k = 1; k < out.length; k++) maxStepOut = Math.max(maxStepOut, out[k] - out[k - 1]); var full = await ev("return P.camState().dist;");
  ok('E5 collision: the boom shortened against a wall (min applied < 0.75 × full) and eased back out (no single 100 ms step > 35 % of the full boom)', minA < 0.75 * full && maxStepOut < 0.35 * full && out[out.length - 1] > minA, { min_applied: minA, full: +full.toFixed(2), max_step_out_per_100ms: +maxStepOut.toFixed(2), end: out[out.length - 1] });
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'spec_b_extra_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT spec B extra ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
