/* OWNER INTERJECTION 2026-09-18 phase F — the ⚔ STATS / SKILLS surface in the real page: the five-stat family (FORCE · POWER · ENGINE · CONTROL ·
   RESILIENCE, 0–999), class baselines honestly 'source not found', points per level OWNER_DECISION (3 or 4), PREVIEW allocation that never touches
   the host, the branching PROGRESSION nodes (FOUNDATION now, CLASS DEVELOPMENT locked at the ruleset level, FUTURE branches, class concepts).
   Portrait (touch EMULATED) + desktop stills.   node deploy/probe_sword_stats.mjs [portrait|desktop] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var MODE = argv.filter(function (a) { return /^(portrait|desktop)$/.test(a); })[0] || 'portrait'; var DIST = path.join(HERE, 'static_dist'); var OUT = path.join(HERE, 'probe_out', 'stats_f'); fs.mkdirSync(OUT, { recursive: true });
var TOUCH = MODE === 'portrait'; var VP = TOUCH ? [390, 844] : [1200, 750]; var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, mobile: TOUCH }); var pass = 0, fail = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 900)); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function click(sel) { return await pg.evaluate("(function(){ var b=document.querySelector('" + sel + "'); if(!b) return null; b.click(); return 1; })()"); }
var report = { mode: MODE, touch_emulated: TOUCH, checks: lines };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(5000); await ev("P.hud.showGuide(false); return 1;");
  var prof0 = await ev("var r=P.snap().play.rules; return JSON.stringify(r.me.profile);");
  await ev("P.menu.open('STATS'); return 1;"); await sleep(900);
  var S = await pg.evaluate("(function(){ var b=document.getElementById('g-menu-body'); if(!b) return null; var stats=Array.prototype.map.call(b.querySelectorAll('.mstat b'), function(e){ return e.textContent.trim(); }); var txt=b.textContent; return { stats: stats, source_not_found: (txt.match(/class baseline: source not found/g)||[]).length, owner_decision: /OWNER_DECISION/.test(txt) && /3 or 4/.test(txt), preview_only: /PREVIEW only/.test(txt), q07: /Q07[^A-Z]*UNRESOLVED/i.test(txt), plus: b.querySelectorAll('[data-m=\"stat-plus\"]').length, identity: /class identity:/.test(txt) }; })()");
  ok('F1 STATS tab: the five canonical stats in order (' + (S && S.stats.join(' · ')) + '), every baseline reads "class baseline: source not found" (5×, nothing invented), points per level = OWNER_DECISION (3 or 4), PREVIEW-only allocation, Q07 fairness UNRESOLVED, the class identity from the canon', S && S.stats.join() === 'FORCE,POWER,ENGINE,CONTROL,RESILIENCE' && S.source_not_found === 5 && S.owner_decision && S.preview_only && S.q07 && S.plus === 5 && S.identity, S);
  await pg.screenshot(path.join(OUT, 'stats_' + MODE + '_before.png'));
  for (var i = 0; i < 3; i++) { await click('#g-menu-body [data-m="stat-plus"][data-stat="POWER"]'); await sleep(120); } await click('#g-menu-body [data-m="stat-plus"][data-stat="CONTROL"]'); await sleep(200);
  var S2 = await pg.evaluate("(function(){ var b=document.getElementById('g-menu-body'); var txt=b.textContent; var m=txt.match(/(\\d+) left/); return { power_preview: /\\+3 preview/.test(txt), control_preview: /\\+1 preview/.test(txt), left: m?+m[1]:null, reset: !!b.querySelector('[data-m=\"stat-reset\"]:not([disabled])') }; })()");
  var prof1 = await ev("var r=P.snap().play.rules; return JSON.stringify(r.me.profile);"); var snapStats = await ev("var s=P.snap(); return JSON.stringify(s.play.character||{}).indexOf('FORCE') >= 0 || JSON.stringify(s.play.rules.me).indexOf('FORCE') >= 0;");
  ok('F2 PREVIEW allocation works in the panel (POWER +3, CONTROL +1, ' + (S2 && S2.left) + ' of the labelled test budget left, reset enabled) and touches NOTHING on the host: the rules profile is byte-identical and no stat reaches the snapshot', S2 && S2.power_preview && S2.control_preview && S2.left === 8 && S2.reset && prof0 === prof1 && !snapStats, { preview: S2, profile_same: prof0 === prof1, snapshot_has_stats: snapStats });
  await pg.screenshot(path.join(OUT, 'stats_' + MODE + '_preview.png')); await click('#g-menu-body [data-m="stat-reset"]'); await sleep(150);
  await ev("P.menu.tab('SKILLS'); return 1;"); for (var wk = 0; wk < 30; wk++) { await sleep(150); var loadingK = await pg.evaluate("(function(){ var b=document.getElementById('g-menu-body'); return b ? /loading the ruleset/.test(b.textContent) : true; })()"); if (!loadingK) break; }   /* the ruleset copy loads lazily; wait for the class-concept node */
  var K = await pg.evaluate("(function(){ var b=document.getElementById('g-menu-body'); var nodes=Array.prototype.map.call(b.querySelectorAll('.mnode'), function(n){ return { cls: n.className, b: n.querySelector('b').textContent.trim(), s: n.querySelector('span').textContent.trim() }; }); return { n: nodes.length, now: nodes.filter(function(x){ return /now/.test(x.cls); }).length, locked: nodes.filter(function(x){ return /locked/.test(x.cls); }).length, future: nodes.filter(function(x){ return /future/.test(x.cls); }).length, texts: nodes.map(function(x){ return x.b + ' | ' + x.s.slice(0,70); }) }; })()");
  ok('F3 SKILLS tab: the branching PROGRESSION — FOUNDATION PROTOCOL current (levels 1–12), CLASS DEVELOPMENT locked from level 13 (the ruleset band, no invented requirement), the PHYSICAL / MAHGIC / HYBRID / CLASS branches as FUTURE nodes, the class concepts from the ruleset (Athlete: none recorded) — every non-current node says it is not grantable', K && K.now === 1 && K.locked === 1 && K.future >= 5 && K.texts.some(function (t) { return /CLASS DEVELOPMENT \| from level 13/.test(t); }) && K.texts.some(function (t) { return /FOUNDATION PROTOCOL \| levels 1–12/.test(t); }) && K.texts.some(function (t) { return /none recorded/.test(t); }), K);
  await pg.screenshot(path.join(OUT, 'skills_' + MODE + '.png')); await ev("P.menu.close('probe'); return 1;"); await sleep(200);
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'probe_sword_stats_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT STATS PHASE F ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
