/* G37 appearance gate (owner C2 review §1) — the separated form through idle → start → walk → turn → stop → run → brake → FUSE → SEPARATE at NORMAL speed, traced per rendered
   frame, with the leg-geometry checks the world-space hold could break: KNEE FLIP (the knee behind the hip→end line, i.e. bending backward), LEG SNAP (angular-velocity spike of
   thigh / shin above the logged steady threshold, incl. the hold engage / release frames), OVEREXTENSION (hip→end distance beyond the leg's length), ABRUPT RELEASE (the pointed end's
   world speed jumping above the body's travel + swing bound in the frames right after a hold ends). Labels: this is the hovered pointed-end / virtual-support gait — no floor contact.
   Also writes a normal-speed side strip (100 ms) of the whole sequence. node deploy/probe_gait_sequence.mjs [static_dist] [--out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; } var OUT = path.resolve(arg('--out', path.join(HERE, 'probe_out', 'gait_sequence'))); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1100, height: 620, gpu: true }); var pass = 0, fail = 0, lines = []; var report = { checks: lines, out: OUT, segments: {} };
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 900)); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
var BONES = ['THIGH_L', 'SHIN_L', 'TIP_L', 'THIGH_R', 'SHIN_R', 'TIP_R', 'PELVIS'];
function qAngle(a, b) { var d = Math.abs(a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3]); return 2 * Math.acos(Math.min(1, d)); }
function pct(a, q) { if (!a.length) return null; var s = a.slice().sort(function (x, y) { return x - y; }); return s[Math.min(s.length - 1, Math.floor(q * (s.length - 1)))]; }
function sub(a, b) { return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]; } function len(a) { return Math.hypot(a[0], a[1], a[2]); } function dot(a, b) { return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]; }
/* per-frame leg geometry for one side: knee-forward signed distance, hip→end length, per-frame angular velocity of thigh / shin */
function analyse(rows, S, LEG_M) { var out = { frames: 0, knee_min_fwd_cm: 1e9, knee_flips: 0, overext_frames: 0, max_len_ratio: 0, ang: [], releases: [], end_speed_after_release: [] };
  for (var i = 1; i < rows.length; i++) { var r = rows[i], r0 = rows[i - 1]; var dt = (r.t - r0.t) / 1000; if (dt <= 0.002 || !r.w || !r0.w) continue; var hip = r.w['THIGH_' + S], knee = r.w['SHIN_' + S], end = r['end' + S]; if (!hip || !knee || !end) continue; out.frames++;
    /* forward = the body's displayed facing (root yaw): fwd = (sin yaw, 0, -cos yaw) in world — knee-forward = signed distance of the knee from the hip→end line along fwd */
    var fwd = [Math.sin(-r.yaw), 0, -Math.cos(-r.yaw)]; var he = sub(end, hip), L = len(he); if (L > 1e-6) { var t = dot(sub(knee, hip), he) / (L * L); var foot = [hip[0] + he[0] * t, hip[1] + he[1] * t, hip[2] + he[2] * t]; var kf = dot(sub(knee, foot), fwd) * 100; if (kf < out.knee_min_fwd_cm) out.knee_min_fwd_cm = kf; if (kf < -1.5) out.knee_flips++; }
    var ratio = L / LEG_M; if (ratio > out.max_len_ratio) { out.max_len_ratio = ratio; out.max_frame = { t: r.t, hip: hip, knee: knee, end: end, hip_knee: +len(sub(knee, hip)).toFixed(4), knee_end: +len(sub(end, knee)).toFixed(4), hip_end: +L.toFixed(4), hold: r['hold' + S], sup: r['sup' + S], hv: r.hv }; } if (ratio > 1.005) out.overext_frames++;
    ['THIGH_', 'SHIN_'].forEach(function (b) { if (r.q[b + S] && r0.q[b + S]) out.ang.push({ t: r.t, bone: b + S, w: qAngle(r.q[b + S], r0.q[b + S]) / dt, hold: r['hold' + S] ? r['hold' + S][1] : 0, hold0: r0['hold' + S] ? r0['hold' + S][1] : 0 }); });
    var h1 = r['hold' + S] ? r['hold' + S][1] : 0, h0 = r0['hold' + S] ? r0['hold' + S][1] : 0; if (h0 >= 0.9 && h1 < 0.9) { out.releases.push(r.t); var e0 = r0['end' + S]; var v = len(sub(end, e0)) / dt; out.end_speed_after_release.push(+v.toFixed(2)); } }
  out.knee_min_fwd_cm = +out.knee_min_fwd_cm.toFixed(1); out.max_len_ratio = +out.max_len_ratio.toFixed(3); return out; }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(5000); await ev("P.hud.showGuide(false); return 1;");
  for (var w0 = 0; w0 < 120; w0++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); }
  /* the leg length hip joint → pointed end in metres, from the rig itself (bone rest offsets × scale) */
  var RIG = await ev("return P.rigInfo('me');"); var LEG_M = RIG ? RIG.leg_m : null; report.rig = RIG;   /* the local figure's own leg: hip joint → knee → pointed END (TIP joint + the measured extension below it), in metres — the same END the hold and the trace use */
  await ev("return P.goTo(60, -45, undefined, undefined, 60000);"); await sleep(300);
  for (var k = 0; k < 20; k++) { await ev("P.send('TRANSFORM',{}); return 1;"); await sleep(400); var f = await ev("return P.snap()&&P.snap().play?P.snap().play.form:null;"); if (f === 'SPLIT') break; } await sleep(2500);
  await ev("P.camFollow(false); P.cam(0, 0.04, 3.4, 0.9); P.camCfg('fade_below_m', 0); return 1;"); await sleep(300);
  /* the sequence with a side camera: idle 2 s → start → walk 3 s → turn 180° while walking → walk 2 s → stop 1.5 s → run 3 s → brake 1.5 s → FUSE → 2 s → SEPARATE → 2 s */
  var shots = []; async function snap(tag) { var f = path.join(OUT, 'seq_' + String(shots.length).padStart(2, '0') + '_' + tag + '.png'); await pg.screenshot(f); shots.push(f); }
  await ev("return P.motionTrace('start', " + JSON.stringify(BONES) + ");"); var T0 = await ev("return performance.now();");
  var marks = {}; async function mark(n) { marks[n] = await ev("return performance.now();"); }
  await mark('idle'); await sleep(1500); await snap('idle');
  await mark('start'); await ev("P.send('MOVE',{forward:0,strafe:-1,run:false,yaw:-1.5708}); return 1;"); await sleep(600); await snap('start'); await mark('walk'); await sleep(1400); await snap('walk_a'); await sleep(1000); await snap('walk_b');
  await mark('turn'); await ev("P.send('MOVE',{forward:0,strafe:1,run:false,yaw:-1.5708}); return 1;"); await sleep(500); await snap('turn'); await sleep(1500); await snap('walk_back');
  await mark('stop'); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-1.5708}); return 1;"); await sleep(500); await snap('stop'); await sleep(1000);
  await mark('run'); await ev("P.send('MOVE',{forward:0,strafe:-1,run:true,fast:true,yaw:-1.5708}); return 1;"); await sleep(1200); await snap('run_a'); await sleep(1300); await snap('run_b');
  await mark('brake'); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-1.5708}); return 1;"); await sleep(400); await snap('brake'); await sleep(1100);
  await mark('fuse'); for (var k2 = 0; k2 < 10; k2++) { await ev("P.send('TRANSFORM',{}); return 1;"); await sleep(400); var f2 = await ev("return P.snap()&&P.snap().play?P.snap().play.form:null;"); if (f2 === 'FUSED') break; } await sleep(600); await snap('fused');
  await mark('separate'); for (var k3 = 0; k3 < 10; k3++) { await ev("P.send('TRANSFORM',{}); return 1;"); await sleep(400); var f3 = await ev("return P.snap()&&P.snap().play?P.snap().play.form:null;"); if (f3 === 'SPLIT') break; } await sleep(1500); await snap('separated');
  var tr = await ev("return P.motionTrace('stop');"); var rows = tr.rows || tr; await ev("P.camFollow(true); P.cam(null); P.camCfg('fade_below_m', 1.3); return 1;");
  report.frames = rows.length; report.marks = marks; fs.writeFileSync(path.join(OUT, 'trace_rows.json'), JSON.stringify(rows));
  var order = ['idle', 'start', 'walk', 'turn', 'stop', 'run', 'brake', 'fuse', 'separate']; var segs = {}; order.forEach(function (n, i) { var t0 = marks[n], t1 = i + 1 < order.length ? marks[order[i + 1]] : 1e12; segs[n] = rows.filter(function (r) { return r.t >= t0 && r.t < t1; }); });
  /* the split segments only (fuse / separate are the transformation beats, logged separately) */
  var splitRows = rows.filter(function (r) { return r.t >= marks.idle && r.t < marks.fuse && r.form === 'SPLIT'; });
  var A = { L: analyse(splitRows, 'L', LEG_M), R: analyse(splitRows, 'R', LEG_M) }; report.analysis = A;
  var steady = A.L.ang.concat(A.R.ang).filter(function (x) { var w = segs.walk; return w.length && x.t >= w[0].t + 800 && x.t <= w[w.length - 1].t; }).map(function (x) { return x.w; }); var thr = steady.length ? +(2.5 * pct(steady, 0.99)).toFixed(2) : null; report.threshold_rad_s = thr; report.steady_p99 = steady.length ? +pct(steady, 0.99).toFixed(2) : null;
  var spikes = A.L.ang.concat(A.R.ang).filter(function (x) { return thr !== null && x.w > thr; }); var spikesAtHold = spikes.filter(function (x) { return (x.hold >= 0.9) !== (x.hold0 >= 0.9); });
  var speedSplit = splitRows.filter(function (r) { return r.hv !== null; }).map(function (r) { return r.hv; }); var vmax = speedSplit.length ? Math.max.apply(null, speedSplit) : 0;
  var relSpeeds = A.L.end_speed_after_release.concat(A.R.end_speed_after_release); var relMax = relSpeeds.length ? Math.max.apply(null, relSpeeds) : 0;
  ok('S0 the sequence was traced at normal speed in the separated form: ' + splitRows.length + ' frames over idle → start → walk → turn → stop → run → brake (' + rows.length + ' incl. FUSE / SEPARATE); leg length hip→knee→pointed end ' + (LEG_M && LEG_M.toFixed(3)) + ' m from the local rig (thigh ' + (RIG && RIG.thigh_m) + ' + knee→end ' + (RIG && RIG.shin_to_end_m) + ' m; pointed end ' + (RIG && RIG.tip_ext_m) + ' m below the TIP joint)', splitRows.length > 300 && LEG_M > 0.7 && LEG_M < 1.1, { split_frames: splitRows.length, all: rows.length, leg_m: LEG_M });
  ok('S1 no KNEE FLIP: through every split frame the knee stays on the forward side of the hip→end line (min forward offset L ' + A.L.knee_min_fwd_cm + ' cm / R ' + A.R.knee_min_fwd_cm + ' cm ≥ −1.5 cm; flips 0)', A.L.knee_flips === 0 && A.R.knee_flips === 0, { L: A.L.knee_min_fwd_cm, R: A.R.knee_min_fwd_cm, flips: [A.L.knee_flips, A.R.knee_flips] });
  ok('S2 no OVEREXTENSION: the hip→pointed-end distance never exceeds the leg (max ratio L ' + A.L.max_len_ratio + ' / R ' + A.R.max_len_ratio + ' ≤ 1.005; frames over 0)', A.L.overext_frames === 0 && A.R.overext_frames === 0, { L: A.L.max_len_ratio, R: A.R.max_len_ratio });
  ok('S3 no LEG SNAP: thigh / shin angular velocity never exceeds the logged threshold (steady-walk p99 ' + report.steady_p99 + ' × 2.5 = ' + thr + ' rad/s) anywhere in the split sequence, including the ' + (A.L.releases.length + A.R.releases.length) + ' hold engage / release frames', thr !== null && spikes.length === 0, { spikes: spikes.slice(0, 5).map(function (x) { return { t: x.t, bone: x.bone, w: +x.w.toFixed(1), at_hold_edge: (x.hold >= 0.9) !== (x.hold0 >= 0.9) }; }), at_hold_edges: spikesAtHold.length });
  ok('S4 no ABRUPT RELEASE: in the frame after each hold ends the pointed end moves at most 2.5 × the body\'s top speed (max ' + relMax.toFixed(2) + ' m/s vs body ' + vmax.toFixed(2) + ' m/s; ' + relSpeeds.length + ' releases)', relSpeeds.length >= 4 && relMax <= 2.5 * Math.max(1, vmax), { release_speeds: relSpeeds, body_vmax: vmax });
  /* the transformation beats: logged, not enforced (authored bursts) */
  var tf = rows.filter(function (r) { return r.t >= marks.fuse; }); var tfAng = []; for (var i2 = 1; i2 < tf.length; i2++) { var dt2 = (tf[i2].t - tf[i2 - 1].t) / 1000; if (dt2 <= 0.002) continue; BONES.forEach(function (b) { if (tf[i2].q[b] && tf[i2 - 1].q[b]) tfAng.push(qAngle(tf[i2].q[b], tf[i2 - 1].q[b]) / dt2); }); }
  report.transformation = { frames: tf.length, max_rad_s: tfAng.length ? +Math.max.apply(null, tfAng).toFixed(2) : null, forms: Array.from(new Set(tf.map(function (r) { return r.form; }))) };
  ok('S5 FUSE → SEPARATE completed with the hold inactive during the transformation (no anchor recorded while transforming) and both forms reached', report.transformation.forms.indexOf('FUSED') >= 0 && report.transformation.forms.indexOf('SPLIT') >= 0 && !tf.some(function (r) { return r.form === 'FUSED' && r.plant && (r.plant.L || r.plant.R); }), report.transformation);
  /* the normal-speed strip: the 12 snapshots side by side (labelled) */
  var imgs = shots.map(function (f) { return { b: fs.readFileSync(f).toString('base64'), l: path.basename(f).replace(/^seq_\d+_|\.png$/g, '') }; });
  var sheet = await pg.evaluate("(async function(){ var items=" + JSON.stringify(imgs) + "; var ims=[]; for (var it of items) ims.push(await new Promise(function(r){ var i=new Image(); i.onload=function(){ r(i); }; i.src='data:image/png;base64,'+it.b; })); var cw=250, ch=Math.round(cw*ims[0].height/(ims[0].width*0.42)); var cols=6; var c=document.createElement('canvas'); c.width=cols*cw; c.height=Math.ceil(ims.length/cols)*(ch+18)+24; var g=c.getContext('2d'); g.fillStyle='#111'; g.fillRect(0,0,c.width,c.height); g.fillStyle='#fff'; g.font='bold 13px sans-serif'; g.fillText('SEPARATED SEQUENCE at normal speed — idle · start · walk · turn · stop · run · brake · FUSE · SEPARATE (side MANUAL LOOK; hovered pointed-end / virtual-support gait, no floor contact)', 6, 16); for (var i=0;i<ims.length;i++){ var sx=Math.round(ims[i].width*0.29), sw=Math.round(ims[i].width*0.42); var x0=(i%cols)*cw, y0=24+Math.floor(i/cols)*(ch+18); g.drawImage(ims[i], sx, 0, sw, ims[i].height, x0, y0+16, cw, ch); g.fillStyle='#dff3ff'; g.font='12px sans-serif'; g.fillText(items[i].l, x0+4, y0+12); } return c.toDataURL('image/png').split(',')[1]; })()");
  fs.writeFileSync(path.join(OUT, 'sequence_strip.png'), Buffer.from(sheet, 'base64'));
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 3));
} catch (e) { ok('X probe ran to the end', false, String(e && e.stack || e)); }
finally { try { await pg.close(); } catch (e) { } try { srv.close(); } catch (e) { } }
report.summary = { pass: pass, fail: fail }; fs.writeFileSync(path.join(OUT, 'probe_gait_sequence.json'), JSON.stringify(report, null, 1)); console.log('PASS ' + pass + ' FAIL ' + fail + ' → ' + OUT); process.exit(fail ? 1 : 0);
