/* SPEC A TEST ROUTE (Spec A/B/E/G regression metric): spawn → walk 10 s → fly 20 s → land → full attack combo (E R T Y + special).
   Drives the EXISTING static build (deploy/static_dist) in headless Chromium through the runtime's own key events and dev hooks; samples
   per-frame intervals with an in-page requestAnimationFrame sampler (measurement only, nothing in the repository is edited).
   Reports p50 / p95 / p99 / max, the runtime's own 'over_50ms' counter, and the share of intervals above 25 / 33.4 / 50 ms (the project has
   no dropped-frame definition yet — these are candidates, not a claim).
   node deploy/probe_route.mjs [static_dist dir] [label] [viewport WxH] [extra query e.g. quality=low] */
import path from 'node:path'; import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = path.resolve(process.argv[2] && !process.argv[2].startsWith('-') ? process.argv[2] : path.join(HERE, 'static_dist')); var label = process.argv[3] || 'route'; var vp = (process.argv[4] || '1120x700').split('x').map(Number); var extra = process.argv[5] || ''; var OUT = path.join(HERE, 'probe_out'); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: vp[0], height: vp[1], gpu: true, unlockFps: process.env.ROUTE_VSYNC !== '1', dpr: +(process.env.ROUTE_DPR || 1) || 1, mobile: process.env.ROUTE_MOBILE === '1' });   /* ROUTE_DPR=2|3 + ROUTE_MOBILE=1: phone-like device pixels (PASS 4 render-scale cost) */   /* headless Chromium paces requestAnimationFrame at 30 Hz by default; unlocked, the interval follows the real frame work (ROUTE_VSYNC=1 keeps the pacing) */
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(60); await key(code, false); }
async function P(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
function pct(a, q) { if (!a.length) return null; var s = a.slice().sort(function (x, y) { return x - y; }); return s[Math.min(s.length - 1, Math.floor(q * (s.length - 1)))]; }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (extra ? '&' + extra : '')); await waitForGame(pg, 120000); await sleep(5000); await P("P.hud.showGuide(false); return 1;");
  for (var w = 0; w < 120; w++) { var dl = await P("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); }
  await sleep(2000); var ri0 = await P("return P.renderInfo();"); var quality = await P("return { tier: P.quality ? P.quality().tier : null, pixelRatio: P.rendererDebug().getPixelRatio(), dpr: devicePixelRatio, fx: new URLSearchParams(location.search).get('fx'), w: innerWidth, h: innerHeight, sky: (P.sceneDebug().background.getHex()===0x9fc4e4?'DAY':'other'), avatar: P.slot().id };");
  /* in-page frame sampler: one interval per animation frame, tagged by route phase */
  await pg.evaluate("window.__rt={phase:'idle',samples:[],prev:0}; (function loop(t){ requestAnimationFrame(loop); if (window.__rt.prev) window.__rt.samples.push([window.__rt.phase, t-window.__rt.prev]); window.__rt.prev=t; })(performance.now()); 1");
  var setPhase = function (p) { return pg.evaluate("window.__rt.phase=" + JSON.stringify(p) + "; 1"); };
  /* frame-work breakdown sampled from the runtime's PERF every 250 ms (entities+animators / render / in-page host tick / rigs animated) */
  await pg.evaluate("window.__bd=[]; window.__bdT=setInterval(function(){ var P=window.MAHWORLD_PLAY; if(!P||!P.perf) return; var s=P.perf(); window.__bd.push([window.__rt.phase, s.ents_ms||0, s.render_ms||0, s.sim_ms||0, s.rigs||0, s.poll_ms||0, s.snap_ms||0, s.hud_ms||0]); }, 250); 1");
  await P("return P.perfReset ? P.perfReset() : null;"); var perf0 = await P("return P.perf();");
  await setPhase('walk'); await key('KeyW', true); await sleep(10000); await key('KeyW', false); await sleep(300);
  await setPhase('fly'); await tap('KeyF'); await sleep(400); await key('Space', true); await sleep(2500); await key('Space', false); await P("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:1.5708});"); await sleep(600); await key('KeyW', true); await sleep(7000); await key('KeyW', false); await sleep(9400);   /* climb, turn east (stays inside the district), cruise 7 s, hover */
  await setPhase('land'); await tap('KeyF'); await sleep(6000);
  await setPhase('combo'); await P("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:3.1416});"); await sleep(300); for (var c of ['KeyE', 'KeyR', 'KeyT', 'KeyY']) { await tap(c); await sleep(1400); } await P("return P.send('RULES_SELECT',{category:'SPECIAL_MAGIC'});"); await sleep(200); var w1 = await P("return P.perf().worst;"); await tap('KeyE'); await sleep(2500); var w2 = await P("return P.perf().worst;"); await tap('KeyE'); await sleep(2500); var w3 = await P("return P.perf().worst;"); console.log('worst before special', JSON.stringify(w1)); console.log('worst after 1st special', JSON.stringify(w2)); console.log('worst after 2nd special', JSON.stringify(w3)); await P("return P.send('RULES_SELECT',{category:'PHYSICAL'});");
  await setPhase('done');
  var samples = await pg.evaluate("window.__rt.samples"); var bd = await pg.evaluate("clearInterval(window.__bdT); window.__bd"); var breakdown = {}; bd.forEach(function (b) { if (b[0] === 'idle' || b[0] === 'done') return; var o = breakdown[b[0]] = breakdown[b[0]] || { n: 0, ents: 0, render: 0, sim: 0, rigs: 0, poll: 0 }; o.n++; o.ents += b[1]; o.render += b[2]; o.sim += b[3]; o.rigs += b[4]; o.poll += b[5] || 0; o.snap = (o.snap || 0) + (b[6] || 0); o.hud = (o.hud || 0) + (b[7] || 0); }); Object.keys(breakdown).forEach(function (k) { var o = breakdown[k]; breakdown[k] = { samples: o.n, ents_ms: +(o.ents / o.n).toFixed(2), render_ms: +(o.render / o.n).toFixed(2), host_tick_ms: +(o.sim / o.n).toFixed(2), poll_wall_ms: +(o.poll / o.n).toFixed(2), snapshot_ms: +(o.snap / o.n).toFixed(2), hud_ms_per_100ms: +(o.hud / o.n).toFixed(2), rigs_per_frame: +(o.rigs / o.n).toFixed(1) }; }); var labStats = await P("return P.lab ? P.lab().stats : null;"); var lodInfo = await P("var d=P.district?P.district():null; return d?d.loaded.map(function(b){return b.lod||null;}):null;"); var perf1 = await P("return P.perf();"); var slowList = perf1.slow_list || []; var ri1 = await P("return P.renderInfo();"); var pos = await P("return P.snap().play.position;");
  var phases = {}; samples.forEach(function (s) { if (s[0] === 'idle' || s[0] === 'done') return; (phases[s[0]] = phases[s[0]] || []).push(s[1]); (phases.route = phases.route || []).push(s[1]); });
  var report = { label: label, build: DIST, viewport: vp, quality: quality, control_lab_last600: labStats, lod: lodInfo, breakdown_ms: breakdown, render: { calls: ri1.calls, triangles: ri1.triangles }, runtime_perf_counter: { frames: perf1.frames - perf0.frames, over_50ms: perf1.over_50ms - perf0.over_50ms, max_ms: perf1.max_ms }, end_position: pos, slow_frames: slowList, worst_frame: perf1.worst || null, phases: {} };
  Object.keys(phases).forEach(function (k) { var a = phases[k]; report.phases[k] = { frames: a.length, seconds: +(a.reduce(function (x, y) { return x + y; }, 0) / 1000).toFixed(1), p50_ms: +pct(a, 0.5).toFixed(1), p95_ms: +pct(a, 0.95).toFixed(1), p99_ms: +pct(a, 0.99).toFixed(1), max_ms: +Math.max.apply(null, a).toFixed(1), over_25ms_pct: +(100 * a.filter(function (x) { return x > 25; }).length / a.length).toFixed(1), over_33ms_pct: +(100 * a.filter(function (x) { return x > 33.4; }).length / a.length).toFixed(1), over_50ms_pct: +(100 * a.filter(function (x) { return x > 50; }).length / a.length).toFixed(1) }; });
  console.log(JSON.stringify(report, null, 1)); fs.writeFileSync(path.join(OUT, 'route_' + label + '.json'), JSON.stringify(report, null, 1));
  console.log('errors', pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 4));
} finally { await pg.close(); srv.close(); }
