/* P8 (master §16 / §17; G52 / G53 / EXT-20 … EXT-28 / U17 / U18) — THE FIRST ENTRANCE TRANSACTION, in the real page (headless Chrome, GPU; touch EMULATED where stated):
   MAH GYM door prompt → refusal away from the door → explicit confirm (cancel, then accept) → fade out → host entry → readiness → fade in → interior → the doorway prompt
   inside → confirm → exit lands on the same doorway facing away → repeat entry → duplicate entry refused mid-transaction → flight capped by the hall ceiling → the camera
   boom against the interior wall → a scene-build FAILURE (fault injection ?fail_room=) recovers to the doorway with no stuck curtain → the SLOW readiness path (?slow_room=)
   shows the stage line and clears → the clothing shop: enter, BROWSE the zero-stock catalog (0 items, no purchase control), exit. Every transaction step is read from the
   client's transaction log (P.transaction()) and the host snapshot, not assumed. Screenshots: deploy/probe_out/interior/. node deploy/probe_interior.mjs [static_dist] [--out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var ROOT = path.resolve(HERE, '..', '..'); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
function arg(k, d) { var i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; } var OUT = path.resolve(arg('--out', path.join(HERE, 'probe_out', 'interior'))); fs.mkdirSync(OUT, { recursive: true });
function candidateDataPath(parts) { var packed = path.join.apply(path, [DIST, 'CLAUDE_GAMEPLAY_RUNTIME'].concat(parts)); return fs.existsSync(packed) ? packed : path.join.apply(path, [ROOT].concat(parts)); }
var DISTRICT_PATH = candidateDataPath(['26_LOCAL_AUTHORITY', 'lab', 'assets', 'buildings', 'district_v1.json']); var TUNING_PATH = candidateDataPath(['00_CORE', 'dev_tuning.dev.json']);
var DISTRICT = JSON.parse(fs.readFileSync(DISTRICT_PATH, 'utf8')); var TUNING = JSON.parse(fs.readFileSync(TUNING_PATH, 'utf8')); var ROOMS = TUNING.local_authority.play.rooms;
function portalRecord(id) { var found = null; (DISTRICT.buildings || []).some(function (building) { return (building.portals || []).some(function (portal) { if (portal.id !== id) return false; found = { building: building.id, portal: portal }; return true; }); }); if (!found || !found.portal.world || !found.portal.outward) throw new Error('interior probe: missing district portal ' + id + ' in ' + DISTRICT_PATH); return found; }
function roomSpec(name, door, room) { var found = portalRecord(door), cfg = ROOMS[room], exit = cfg && cfg.exit && cfg.exit.position; if (!exit) throw new Error('interior probe: missing room config ' + room + ' in ' + TUNING_PATH); return { name: name, building: found.building, door: door, room: room, doorAt: found.portal.world.slice(), outward: found.portal.outward.slice(), exit: [exit.x, exit.z], expectedFacing: cfg.door.facing, plan: cfg.interior_plan || null, ceiling_m: cfg.ceiling_m || cfg.flight_ceiling_m || null }; }
function approachPoint(spec, metres) { metres = metres === undefined ? 0.8 : metres; return [spec.doorAt[0] + spec.outward[0] * metres, spec.doorAt[1] + spec.outward[1] * metres]; }
var RETURN_CLEARANCE_M = 0.55, RETURN_EPS_M = 0.08, RETURN_GROUND_EPS_M = 0.02, OWNERSHIP_POLL_MS = 150, OWNERSHIP_STABLE_SAMPLES = 3, OWNERSHIP_TIMEOUT_MS = 5000, WARM_PREP_MAX_MS = 1200, WARM_TOTAL_MAX_MS = 2000;
function fieldReturnPoint(room) { var yaw = room.door.facing || 0; return [room.door.x + Math.sin(yaw) * RETURN_CLEARANCE_M, room.door.z - Math.cos(yaw) * RETURN_CLEARANCE_M]; }
function pointError(pos, expected) { return pos && expected ? Math.hypot(pos.x - expected[0], pos.z - expected[1]) : Infinity; }
function groundReturnProof(outside, entryGround) { var flight = outside && outside.flight || {}, entry = Number(entryGround), ground = Number(flight.ground), altitude = Number(flight.altitude), height = Number(flight.height_above_ground), finite = [entry, ground, altitude, height].every(Number.isFinite); return { entry_ground_m: entry, exit_ground_m: ground, exit_altitude_m: altitude, exit_height_above_ground_m: height, exit_powered: flight.powered, ground_error_m: finite ? +Math.abs(ground - entry).toFixed(4) : null, altitude_error_m: finite ? +Math.abs(altitude - entry).toFixed(4) : null, pass: finite && Math.abs(ground - entry) <= RETURN_GROUND_EPS_M && Math.abs(altitude - entry) <= RETURN_GROUND_EPS_M && Math.abs(height) <= RETURN_GROUND_EPS_M }; }
function sameCensus(a, b) { return !!(a && b && ['objects', 'meshes', 'geometries', 'materials', 'textures', 'skeletons'].every(function (k) { return a[k] === b[k]; })); }
var GRAND = { temple: roomSpec('gold_temple', 'TEMPLE_DOOR', 'TEMPLE_HALL'), tower: roomSpec('blue_tower', 'TOWER_DOOR', 'TOWER_HALL'), clothing: roomSpec('clothing_shop', 'CLOTHING_DOOR', 'CLOTHING_SHOP'), weapon: roomSpec('weapon_shop', 'WEAPON_DOOR', 'WEAPON_SHOP') };
var GYM_ROOM = ROOMS.GYM_INTERIOR; var GYM = { x: GYM_ROOM.door.x, z: GYM_ROOM.door.z, exit: [GYM_ROOM.exit.position.x, GYM_ROOM.exit.position.z], returnAt: fieldReturnPoint(GYM_ROOM) };
var srv = await serveStatic(DIST); var pass = 0, fail = 0, lines = []; var report = { checks: lines, out: OUT, transactions: [], grand_rooms: [], proof_sources: { district_manifest: DISTRICT_PATH, room_tuning: TUNING_PATH } };
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 900)); }
async function session(query, w, h, mobile) { var pg = await launchChrome({ width: w || 1200, height: h || 750, gpu: true, mobile: !!mobile, dpr: mobile ? 2 : 1 });
  var ev = async function (expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); };
  var shot = async function (name) { var f = path.join(OUT, 'int_' + name + '.png'); await pg.screenshot(f); return f; };
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (mobile ? '&touch=1' : '') + (query || '')); await waitForGame(pg, 120000); await sleep(4000); await ev("P.hud.showGuide(false); return 1;");
  for (var w0 = 0; w0 < 120; w0++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); } await sleep(500);
  return { pg: pg, ev: ev, shot: shot }; }
async function state(ev) { return await ev("var p=P.snap()&&P.snap().play; var t=P.transaction(); var f=document.getElementById('g-fade'),ri=P.rendererDebug().info; return {room:p?p.room:null, interior:p?p.room_interior:null, pos:p?p.position:null, facing:p?p.facing:null, flight:p&&p.flight?{ground:p.flight.ground,altitude:p.flight.altitude,height_above_ground:p.flight.height_above_ground,powered:p.flight.powered}:null, prompts:p?p.prompts.map(function(x){ return {intent:x.intent,id:x.id,to:x.to,label:x.label,eligible:x.eligible}; }):[], return_to:p?p.return_to:null, interior_plan:p?p.interior_plan:null, room_style_id:p?p.room_style_id:null, material_family:p?p.material_family:null, feature_ids:p?p.feature_ids:null, ceiling_m:p?p.ceiling_m:null, floor_levels:p?p.floor_levels:null, room_solids:p?p.room_solids:null, trx:t.state.phase, log_tail:t.log.slice(-8).map(function(r){ return r.ev+(r.reason?':'+r.reason:'')+(r.accepted!==undefined?':'+r.accepted:''); }), build_error:t.room_build.error, room_build:t.room_build, room_resources:t.room_resources, last_room_clear:t.last_room_clear, fade_on:f?f.classList.contains('on'):null, fade_opacity:f?getComputedStyle(f).opacity:null, confirm_open:P.hud.confirmOpen?P.hud.confirmOpen():null, catalog_open:P.hud.catalogOpen?P.hud.catalogOpen():null, boom:t.boom_shapes, memory:{geometries:ri.memory.geometries,textures:ri.memory.textures,programs:ri.programs?ri.programs.length:null}, meshes:(function(){ var n=0; function vis(o){ while(o){ if(!o.visible) return false; o=o.parent; } return true; } P.sceneDebug().traverse(function(o){ if(o.isMesh && vis(o)) n++; }); return n; })()};"); }
async function waitCameraState(ev, wanted, timeoutMs) { var until = Date.now() + (timeoutMs || 3500), last = null; while (Date.now() < until) { last = await ev("return P.camState();"); if (last && last.state === wanted) return last; await sleep(50); } return last; }
async function waitStableOwnership(ev, wantedRoom, timeoutMs) { var started = Date.now(), timeout = timeoutMs || OWNERSHIP_TIMEOUT_MS, last = null, current = null, consecutive = 0, samples = []; while (Date.now() - started <= timeout) { current = await state(ev); var census = current && current.room === wantedRoom ? current.room_resources : null; consecutive = census ? (last && sameCensus(census, last) ? consecutive + 1 : 1) : 0; samples.push({ t_ms: Date.now() - started, room: current && current.room, census: census }); if (samples.length > 8) samples.shift(); if (consecutive >= OWNERSHIP_STABLE_SAMPLES) return { stable: true, consecutive: consecutive, elapsed_ms: Date.now() - started, census: census, samples: samples, state: current }; last = census; await sleep(OWNERSHIP_POLL_MS); } return { stable: false, consecutive: consecutive, elapsed_ms: Date.now() - started, census: current && current.room_resources, samples: samples, state: current }; }
async function visitGrand(S, spec, tag) {
  var approach = approachPoint(spec), stage = approachPoint(spec, 3.5);
  await S.ev("P.camFollow(true); P.cam(null); return P.devPlay('PLACE',{x:" + stage[0] + ",z:" + stage[1] + "});"); await sleep(350);
  var walked = await S.ev("return P.goTo(" + approach[0] + "," + approach[1] + ",undefined,undefined,30000);"); await sleep(350); var before = await state(S.ev);
  var prompt = before.prompts.filter(function (x) { return x.intent === 'ENTER' && x.id === spec.door && x.to === spec.room && x.eligible; })[0] || null;
  var enterP = S.ev("return P.interact();"); await sleep(350); var confirmIn = await S.ev("return {open:P.hud.confirmOpen(),answered:P.confirmAnswer(true)};"); var enter = await enterP; await sleep(450); var inside = await state(S.ev);
  await S.shot(tag + '_spawn'); await S.ev("return P.goTo(0,0,undefined,undefined,20000);"); await sleep(300); await S.ev("P.camFollow(false); P.cam(2.4,0.38," + Math.min(10, Math.max(6, (ROOMS[spec.room].size_m || 10) * 0.55)) + ",3.4); return 1;"); await sleep(500); await S.shot(tag + '_grand_volume'); await S.ev("P.camFollow(true); P.cam(null); return 1;");
  var exitWalk = await S.ev("return P.goTo(" + spec.exit[0] + "," + spec.exit[1] + ",undefined,undefined,30000);"); await sleep(300); var beforeExit = await state(S.ev); var exitPrompt = beforeExit.prompts.filter(function (x) { return x.intent === 'ENTER_ROOM' && x.to === 'FIELD' && x.eligible; })[0] || null;
  var exitP = S.ev("return P.interact();"); await sleep(350); var confirmOut = await S.ev("return {open:P.hud.confirmOpen(),answered:P.confirmAnswer(true)};"); var exit = await exitP; await sleep(450); var outside = await state(S.ev); var expectedReturn = approachPoint(spec, RETURN_CLEARANCE_M), returnM = Math.hypot(outside.pos.x - spec.doorAt[0], outside.pos.z - spec.doorAt[1]), returnError = pointError(outside.pos, expectedReturn), groundReturn = groundReturnProof(outside, before.flight && before.flight.ground);
  var planOk = !!(spec.plan && inside.interior_plan && inside.interior_plan.plan_id === spec.plan.plan_id && inside.room_style_id === spec.plan.style_id && inside.material_family === spec.plan.material_family && Math.abs(inside.ceiling_m - spec.ceiling_m) < 0.01 && (inside.feature_ids || []).length === (spec.plan.feature_ids || []).length);
  var row = { name: spec.name, building: spec.building, door: spec.door, room: spec.room, manifest_portal: { world: spec.doorAt, outward: spec.outward }, approach: approach, expected_return: expectedReturn, walked: walked, before: before, prompt: prompt, confirm_in: confirmIn, enter: enter, inside: inside, exit_walk: exitWalk, before_exit: beforeExit, exit_prompt: exitPrompt, confirm_out: confirmOut, exit: exit, outside: outside, return_distance_m: +returnM.toFixed(3), return_error_m: +returnError.toFixed(3), ground_return: groundReturn, plan_ok: planOk };
  row.pass = !!(walked && walked.reached && prompt && confirmIn.open && confirmIn.answered && enter && enter.accepted && inside.room === spec.room && inside.interior && inside.room_build && inside.room_build.room === spec.room && !inside.build_error && planOk && exitWalk && exitWalk.reached && exitPrompt && confirmOut.open && confirmOut.answered && exit && exit.accepted && outside.room === 'FIELD' && Math.abs(returnM - RETURN_CLEARANCE_M) <= RETURN_EPS_M && returnError <= RETURN_EPS_M && groundReturn.pass && Math.abs(outside.facing - spec.expectedFacing) < 0.06);
  report.grand_rooms.push(row); report.transactions.push({ name: spec.name + '_grand', enter: enter, exit: exit, room_build: inside.room_build }); return row;
}
try {
  var S = await session('&cam_follow=1', 1200, 750, false); var ev = S.ev, shot = S.shot, pg = S.pg;
  await ev("P.camFollow(true); P.cam(null); return 1;"); var followSetup = await waitCameraState(ev, 'FOLLOW', 3500); report.camera_setup = { query: 'cam_follow=1', initial: followSetup };
  /* ── refusal away from the door ── */
  var r0 = await ev("return P.send('ENTER_ROOM',{room:'GYM_INTERIOR'});"); ok('H1 the host refuses the gym interior away from its door (NOT_AT_DOOR) — no teleport into interiors', !!r0 && !r0.accepted && r0.reason === 'NOT_AT_DOOR', r0);
  /* ── walk to the door: the ENTER prompt appears inside the threshold pad ── */
  var gt = await ev("return P.goTo(" + (GYM.x + 1.6) + ", " + GYM.z + ", undefined, undefined, 90000);"); await sleep(800); var s1 = await state(ev);
  var doorPrompt = s1.prompts.filter(function (x) { return x.intent === 'ENTER' && x.id === 'GYM_DOOR'; })[0]; report.door_prompt = doorPrompt; await shot('01_door_prompt');
  ok('E1 at the MAH GYM door the contextual prompt is ENTER (id GYM_DOOR, eligible) and the field draws the threshold pad', !!doorPrompt && doorPrompt.eligible && doorPrompt.to === 'GYM_INTERIOR', { prompt: doorPrompt, pos: s1.pos, reached: gt && gt.reached });
  /* ── CANCEL at the explicit confirm ── */
  var cancelP = ev("return P.interact();"); await sleep(400); var sC = await state(ev); await shot('02_confirm_sheet'); await ev("P.confirmAnswer(false); return 1;"); var cancelRes = await cancelP; await sleep(300); var sC2 = await state(ev);
  ok('E2 CANCEL: the confirm sheet opened (it owns input), CANCEL leaves the player at the door in FIELD with no fade and a CANCEL log entry', sC.confirm_open === true && cancelRes && cancelRes.reason === 'CANCELLED' && sC2.room === 'FIELD' && sC2.fade_on === false && sC2.confirm_open === false && sC2.log_tail.indexOf('CANCEL') >= 0, { during: sC.confirm_open, after: sC2.room, res: cancelRes, log: sC2.log_tail });
  /* ── ENTER: confirm → fade → host → readiness → fade in ── */
  var t0 = Date.now(); var enterP = ev("return P.interact();"); await sleep(350); await ev("P.confirmAnswer(true); return 1;"); await sleep(120); var sMid = await state(ev); await shot('03_fade_out_mid'); var enterRes = await enterP; var firstOwnership = await waitStableOwnership(ev, 'GYM_INTERIOR'), sIn = firstOwnership.state; await sleep(400); await shot('04_gym_interior_rear');
  report.transactions.push({ name: 'gym_enter', res: enterRes, log: sIn.log_tail, wall_ms: Date.now() - t0 });
  ok('E3 ENTER accepted: the curtain was up while the host switched rooms (fade_on during), the transaction log runs START → HOST_ACK:true → END:ok, the player stands in GYM_INTERIOR at its spawn with the curtain cleared (opacity 0)', !!enterRes && enterRes.accepted && sMid.fade_on === true && sIn.room === 'GYM_INTERIOR' && sIn.interior === true && sIn.fade_on === false && +sIn.fade_opacity === 0 && sIn.log_tail.indexOf('HOST_ACK:true') >= 0 && sIn.log_tail.indexOf('END') >= 0 && Math.hypot(sIn.pos.x - 0, sIn.pos.z - 9.5) < 0.3, { res: enterRes, mid_fade: sMid.fade_on, in: { room: sIn.room, pos: sIn.pos, fade: sIn.fade_opacity }, log: sIn.log_tail });
  var phases = await ev("var L=P.transaction().log,start=-1; for(var i=L.length-1;i>=0;i--){if(L[i].ev==='START'){start=i;break;}} var rows=start>=0?L.slice(start):[],out={events:rows.map(function(r){return r.ev;}),slow_stage_shown:rows.some(function(r){return r.ev==='SLOW_STAGE_SHOWN';}),ready_timeout:rows.some(function(r){return r.ev==='READY_TIMEOUT';})}; rows.forEach(function(r){if(r.ev==='FADE_OUT_DONE')out.fade_out_ms=r.fade_ms;if(r.ev==='HOST_ACK')out.host_ms=r.host_ms;if(r.ev==='READY'){out.prepare_ms=r.prepare_ms;out.scene_build_ms=r.scene_build_ms;out.room_seen_after_ms=r.room_seen_after_ms;out.polls=r.polls;}if(r.ev==='END'){out.fade_in_ms=r.fade_in_ms;out.total_ms=r.total_ms;}}); return out;"); report.enter_phases = phases;
  var warmOrder = ['START', 'FADE_OUT_DONE', 'HOST_ACK', 'READY', 'END'];
  ok('E4 warm entry adds no loading card: the complete transaction is START → FADE_OUT_DONE → HOST_ACK → READY → END with no SLOW_STAGE_SHOWN/timeout; the two 220 ms fades remain fixed and preparation/total stay below bounded warm-path budgets (' + WARM_PREP_MAX_MS + '/' + WARM_TOTAL_MAX_MS + ' ms)', !!enterRes && enterRes.accepted && phases.events.join('|') === warmOrder.join('|') && phases.slow_stage_shown === false && phases.ready_timeout === false && phases.fade_out_ms === 220 && phases.fade_in_ms === 220 && Number.isFinite(phases.host_ms) && phases.host_ms < 750 && Number.isFinite(phases.scene_build_ms) && phases.scene_build_ms < 500 && Number.isFinite(phases.prepare_ms) && phases.prepare_ms < WARM_PREP_MAX_MS && Number.isFinite(phases.total_ms) && phases.total_ms < WARM_TOTAL_MAX_MS, phases);
  ok('E5 the interior is the ONE visible scene: no build error, the wall solids feed the camera probe, the field is hidden (visible mesh count is the hall, not the district)', sIn.build_error === null && sIn.boom === true && sIn.meshes < 400, { error: sIn.build_error, boom: sIn.boom, visible_meshes: sIn.meshes });
  /* ordinary gameplay views inside the hall: the rear-follow camera while walking to the platform and past the racks (not the doorway) */
  await ev("return P.goTo(0, -2, undefined, undefined, 20000);"); await sleep(400); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(900); await shot('04b_gym_gameplay_platform'); await ev("return P.goTo(-9, 3, undefined, undefined, 20000);"); await sleep(300); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:1.2});"); await sleep(900); await shot('04c_gym_gameplay_racks');
  /* ── inside: flight capped by the ceiling, the boom shortens against a wall ── */
  var flA = await ev("return P.send('FLIGHT',{op:'ENTER'});"); await ev("P.send('FLIGHT',{op:'ASCEND'}); return 1;"); await sleep(2500); var fl = await ev("var p=P.snap().play; return {powered:p.flight.powered, altitude:p.flight.altitude, height:p.flight.height_above_ground};"); await ev("P.send('FLIGHT',{op:'EXIT'}); return 1;"); await sleep(2500); var fl2 = await ev("var p=P.snap().play; return {powered:p.flight.powered, height:p.flight.height_above_ground};");
  ok('E6 flight inside is allowed but capped by the hall ceiling (3.2 m): powered after ENTER + ASCEND, height above ground ≤ 3.3 m after 2.5 s; EXIT lands', !!flA && flA.accepted && !!fl && fl.powered && fl.height <= 3.3 && fl.height > 0.5 && !!fl2 && !fl2.powered, { enter: flA && flA.accepted, fly: fl, after_exit: fl2 });
  await ev("return P.goTo(0, 12.6, undefined, undefined, 20000);"); await sleep(300); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(500);
  var boomSetup = await ev("P.cam(0); var o=P.camOrbit(0,0); return {orbit:o,camera:P.camState(),play:P.snap().play};"), camW = null;
  for (var bw = 0; bw < 50; bw++) { camW = await ev("var c=P.camState(),p=P.snap().play; return {state:c.state,yaw:c.yaw,dist:c.dist,applied:c.applied,obstructed:c.obstructed,inside:c.inside,pos:p.position,facing:p.facing};"); if (camW && camW.state === 'ORBIT' && camW.applied < camW.dist - 0.3) break; await sleep(50); }
  await shot('05_boom_against_wall'); await ev("P.camFollow(true); P.camReset('interior-probe-boom-restore'); return 1;"); var boomRestored = await waitCameraState(ev, 'FOLLOW', 3500); report.boom_probe = { setup: boomSetup, blocked: camW, restored: boomRestored };
  ok('E7 at the doorway wall, a deterministic rear manual view (yaw 0, ORBIT disables automatic pitch escape) is shortened by the interior wall; the camera remains outside the solid, then explicit reset restores FOLLOW before the exit transaction', !!camW && camW.state === 'ORBIT' && Math.abs(Math.atan2(Math.sin(camW.facing), Math.cos(camW.facing))) < 0.08 && camW.applied < camW.dist - 0.3 && camW.inside === null && !!boomRestored && boomRestored.state === 'FOLLOW', { setup: boomSetup, blocked: camW, restored: boomRestored && { state: boomRestored.state, dist: boomRestored.dist, applied: boomRestored.applied } });
  /* ── the exit prompt inside → confirm → back on the doorway outside, facing away ── */
  var sX = await state(ev); var exitPrompt = sX.prompts.filter(function (x) { return x.intent === 'ENTER_ROOM' && x.to === 'FIELD'; })[0];
  ok('E8 at the hall doorway the prompt is the labelled EXIT (ENTER_ROOM → FIELD)', !!exitPrompt && exitPrompt.eligible && /EXIT/.test(exitPrompt.label), exitPrompt);
  var exitP = ev("return P.interact();"); await sleep(350); await ev("P.confirmAnswer(true); return 1;"); await sleep(90); var dup = await ev("return P.enterRoom('FIELD','ENTER_ROOM');"); var exitRes = await exitP;   /* the duplicate is issued DURING the fade-out of the real transaction */ var sOut = await state(ev); await sleep(500); await shot('06_back_at_doorway');
  report.transactions.push({ name: 'gym_exit', res: exitRes, dup: dup, log: sOut.log_tail }); var gymGroundReturn = groundReturnProof(sOut, s1.flight && s1.flight.ground);
  ok('E9 EXIT returns to the SAME doorway at its authored 0.55 m exterior clearance and entry ground level, facing away from the building (+x), curtain cleared, district rebuilt', !!exitRes && exitRes.accepted && sOut.room === 'FIELD' && pointError(sOut.pos, GYM.returnAt) <= RETURN_EPS_M && Math.abs(Math.hypot(sOut.pos.x - GYM.x, sOut.pos.z - GYM.z) - RETURN_CLEARANCE_M) <= RETURN_EPS_M && gymGroundReturn.pass && Math.abs(sOut.facing - 1.5708) < 0.05 && sOut.fade_on === false, { res: exitRes, pos: sOut.pos, expected_return: GYM.returnAt, error_m: pointError(sOut.pos, GYM.returnAt), ground_return: gymGroundReturn, facing: sOut.facing, door: GYM });
  ok('E10 a second room change issued during the running transaction was refused (TRANSACTION_IN_PROGRESS) — no duplicate scene or double transaction', !!dup && !dup.accepted && dup.reason === 'TRANSACTION_IN_PROGRESS', dup);
  /* ── repeat entry (idempotent scene) ── */
  var repeatBefore = await state(ev), m1 = repeatBefore.meshes; var reP = ev("return P.interact();"); await sleep(300); await ev("P.confirmAnswer(true); return 1;"); var reRes = await reP; var repeatOwnership = await waitStableOwnership(ev, 'GYM_INTERIOR'), sRe = repeatOwnership.state; var exP2 = ev("return P.interact();"); await sleep(300); await ev("P.confirmAnswer(true); return 1;"); var exRes2 = await exP2; var sOut2 = await state(ev), repeatGroundReturn = groundReturnProof(sOut2, repeatBefore.flight && repeatBefore.flight.ground); await sleep(300);
  report.gym_ownership_census = { first: { stable: firstOwnership.stable, consecutive: firstOwnership.consecutive, elapsed_ms: firstOwnership.elapsed_ms, census: firstOwnership.census, samples: firstOwnership.samples }, repeat: { stable: repeatOwnership.stable, consecutive: repeatOwnership.consecutive, elapsed_ms: repeatOwnership.elapsed_ms, census: repeatOwnership.census, samples: repeatOwnership.samples } };
  ok('E11 REPEAT: enter and exit again — both accepted, both ownership censuses settled across three consecutive samples and are exactly identical, the repeated interior has the same visible count, its room group is empty after exit, and the authored 0.55 m doorway/entry-ground return is exact again', firstOwnership.stable && repeatOwnership.stable && !!reRes && reRes.accepted && sRe.room === 'GYM_INTERIOR' && sRe.meshes === sIn.meshes && sameCensus(repeatOwnership.census, firstOwnership.census) && !!exRes2 && exRes2.accepted && sOut2.room === 'FIELD' && pointError(sOut2.pos, GYM.returnAt) <= RETURN_EPS_M && repeatGroundReturn.pass && sOut2.room_resources && sOut2.room_resources.objects === 0 && sOut2.last_room_clear && sOut2.last_room_clear.remaining && sOut2.last_room_clear.remaining.objects === 0 && sOut2.room_build && sOut2.room_build.room === 'FIELD' && !sOut2.boom, { enter: reRes && reRes.accepted, ownership_stability: report.gym_ownership_census, meshes_first: sIn.meshes, meshes_repeat: sRe.meshes, owned_first: firstOwnership.census, owned_repeat: repeatOwnership.census, exact_same_census: sameCensus(repeatOwnership.census, firstOwnership.census), out: sOut2.pos, expected_return: GYM.returnAt, ground_return: repeatGroundReturn, field_owned: sOut2.room_resources, visible_field_meshes_diagnostic: [m1, sOut2.meshes] });   /* renderer-wide field mesh totals move with async LOD; the ownership-scoped room census proves no duplicate hall remains */
  /* ── CAMERA OWNERSHIP through a room change (owner camera truth): once from REAR FOLLOW, once from a MANUAL ORBIT — the selected mode must survive entry and exit; a manual angle keeps its relation to his back; nothing recenters ── */
  ok('K1 rollback rear-follow entry / exit: ?cam_follow=1 was observed as FOLLOW before the first transaction, restored after the isolated boom setup, and remained FOLLOW before entry, after reveal and after exit', !!followSetup && followSetup.state === 'FOLLOW' && !!boomRestored && boomRestored.state === 'FOLLOW' && !!enterRes && enterRes.camera_before && enterRes.camera_before.state === 'FOLLOW' && enterRes.camera_after.state === 'FOLLOW' && exitRes && exitRes.camera_before && exitRes.camera_before.state === 'FOLLOW' && exitRes.camera_after && exitRes.camera_after.state === 'FOLLOW' && enterRes.camera_change && enterRes.camera_change.mode_before === 'follow' && enterRes.camera_change.mode_after === 'follow', { setup: followSetup && { state: followSetup.state, mode: followSetup.mode }, enter: { before: enterRes && enterRes.camera_before, after: enterRes && enterRes.camera_after }, boom_restore: boomRestored && { state: boomRestored.state, mode: boomRestored.mode }, exit: exitRes && { before: exitRes.camera_before, after: exitRes.camera_after } });
  var orb0 = await ev("var o=P.camOrbit(1.2, 0.05); return {mode:o.mode, yaw:o.yaw, state:P.camState().state, err_deg:P.camState().err_deg};"); await sleep(600); var orbBefore = await ev("return P.camState();"); await shot('12_manual_orbit_before_entry');
  var oP = ev("return P.interact();"); await sleep(350); await ev("P.confirmAnswer(true); return 1;"); var oRes = await oP; await sleep(700); var orbIn = await ev("return P.camState();"); await shot('13_manual_orbit_inside_kept');
  await ev("return P.goTo(0, 11.6, undefined, undefined, 20000);"); await sleep(600); var orbAtExit = await ev("return P.camState();");   /* he turned round to reach the doorway: in ORBIT the camera angle stays where the finger left it (O1), so the angle relative to his back is different here — the room change must preserve THIS one */ var oxP = ev("return P.interact();"); await sleep(350); await ev("P.confirmAnswer(true); return 1;"); var oxRes = await oxP; await sleep(700); var orbOut = await ev("return P.camState();"); await shot('14_manual_orbit_after_exit_kept');
  report.transactions.push({ name: 'gym_enter_orbit', res: oRes, before: orbBefore, inside: orbIn, at_exit: orbAtExit, exit: oxRes, out: orbOut });
  ok('K2 manual-orbit entry: the mode was ORBIT before entry and is still ORBIT after the reveal — the dragged angle relative to his back is preserved (' + (orbBefore && orbBefore.err_deg) + ' deg before, ' + (orbIn && orbIn.err_deg) + ' deg inside), no recenter', orb0.mode === 'orbit' && orbBefore.state === 'ORBIT' && !!oRes && oRes.accepted && oRes.camera_before.state === 'ORBIT' && oRes.camera_after.state === 'ORBIT' && orbIn.state === 'ORBIT' && Math.abs(Math.abs(orbIn.err_deg) - Math.abs(orbBefore.err_deg)) < 6, { before: orbBefore && { state: orbBefore.state, err_deg: orbBefore.err_deg }, inside: orbIn && { state: orbIn.state, err_deg: orbIn.err_deg }, change: oRes && oRes.camera_change });
  ok('K3 manual-orbit exit: still ORBIT after the exit, and the angle relative to his back that he had at the doorway (' + (orbAtExit && orbAtExit.err_deg) + ' deg — it differs from the entry value because he turned round inside while the orbit stayed put, O1) is the angle after the exit (' + (orbOut && orbOut.err_deg) + ' deg); the manual mode was never erased or recentred by a room change', !!oxRes && oxRes.accepted && oxRes.camera_after.state === 'ORBIT' && orbOut.state === 'ORBIT' && Math.abs(Math.abs(orbOut.err_deg) - Math.abs(orbAtExit.err_deg)) < 6, { at_exit: orbAtExit && { state: orbAtExit.state, err_deg: orbAtExit.err_deg }, out: orbOut && { state: orbOut.state, err_deg: orbOut.err_deg } });
  await ev("P.camReset('probe'); return 1;"); await sleep(900);
  /* Manifest-driven threshold exercise for every M5 grand room. The later phone
     shop pass still proves BROWSE; these rows prove each portal, volume and exit. */
  var grandCases = [
    { id: 'G1', spec: GRAND.temple, tag: '17_temple' },
    { id: 'G2', spec: GRAND.tower, tag: '18_tower' },
    { id: 'G3', spec: GRAND.clothing, tag: '19_clothing' },
    { id: 'G4', spec: GRAND.weapon, tag: '20_weapon' }
  ];
  for (var gi = 0; gi < grandCases.length; gi++) {
    var gc = grandCases[gi], gr = await visitGrand(S, gc.spec, gc.tag);
    ok(gc.id + ' ' + gc.spec.room + ' uses its district_v1 portal and exposes the authored grand-room plan, ceiling, material/features, prompt transaction and exact exterior position/entry-ground return', gr.pass, { door: gr.manifest_portal, prompt: gr.prompt, room: gr.inside.room, plan: gr.inside.interior_plan && gr.inside.interior_plan.plan_id, style: gr.inside.room_style_id, ceiling_m: gr.inside.ceiling_m, features: gr.inside.feature_ids, return_m: gr.return_distance_m, ground_return: gr.ground_return, facing: gr.outside.facing });
  }
  ok('Z1 zero page / console errors through the gym and grand-room transactions', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 3));
  await pg.close();
  /* ── FAILURE: the interior build throws (fault injection) → return to the doorway, no stuck curtain ── */
  var F = await session('&fail_room=GYM_INTERIOR', 1200, 750, false); await F.ev("return P.goTo(" + (GYM.x + 1.6) + ", " + GYM.z + ", undefined, undefined, 90000);"); await sleep(600);
  var fP = F.ev("return P.interact();"); await sleep(350); await F.ev("P.confirmAnswer(true); return 1;"); var fRes = await fP; var sF = await state(F.ev); await sleep(400); await F.shot('07_failure_recovered'); report.transactions.push({ name: 'gym_enter_failure', res: fRes, log: sF.log_tail });
  ok('F1 FAILURE path: the interior build failed (injected), reported SCENE_FAILED and recovered to FIELD at the authored 0.55 m exterior return, with curtain cleared and field rebuilt', !!fRes && !fRes.accepted && fRes.reason === 'SCENE_FAILED' && fRes.recovered_to === 'FIELD' && sF.room === 'FIELD' && sF.fade_on === false && pointError(sF.pos, GYM.returnAt) <= RETURN_EPS_M && sF.log_tail.indexOf('SCENE_FAILED') >= 0 && sF.log_tail.indexOf('RECOVER_ACK:true') >= 0 && sF.build_error === null, { res: fRes, state: { room: sF.room, pos: sF.pos, expected_return: GYM.returnAt, error_m: pointError(sF.pos, GYM.returnAt), fade: sF.fade_on, build_error: sF.build_error }, log: sF.log_tail });
  await F.pg.close();
  /* ── SLOW readiness: the stage line appears (no invented percentage) and clears ── */
  var SL = await session('&slow_room=1500', 1200, 750, false); await SL.ev("return P.goTo(" + (GYM.x + 1.6) + ", " + GYM.z + ", undefined, undefined, 90000);"); await sleep(600);
  var sP = SL.ev("return P.interact();"); await sleep(350); await SL.ev("P.confirmAnswer(true); return 1;"); await sleep(1100); var stageTxt = await SL.ev("return {title:document.getElementById('g-fade-title').textContent, stage:document.getElementById('g-fade-stage').textContent, on:document.getElementById('g-fade').classList.contains('on')};"); await SL.shot('08_slow_stage_line'); var sRes = await sP; var sS = await state(SL.ev); report.transactions.push({ name: 'gym_enter_slow', res: sRes, stage: stageTxt, log: sS.log_tail });
  ok('S1 SLOW path (1.5 s injected): the curtain shows the room name and a real stage line ("preparing the hall · N s", no percentage), the entry still completes and the curtain clears', stageTxt.on === true && /preparing the hall/.test(stageTxt.stage) && !/%/.test(stageTxt.stage) && /MAH GYM/i.test(stageTxt.title) && !!sRes && sRes.accepted && sRes.total_ms >= 1500 && sS.fade_on === false && sS.log_tail.indexOf('SLOW_STAGE_SHOWN') >= 0, { stage: stageTxt, res: sRes, log: sS.log_tail });
  await SL.pg.close();
  /* ── the clothing shop: enter, BROWSE the zero-stock catalog, exit (touch-emulated portrait for the packet) ── */
  var clothApproach = approachPoint(GRAND.clothing), weaponApproach = approachPoint(GRAND.weapon), clothOutwardStage = approachPoint(GRAND.clothing, 6.2), weaponOutwardStage = approachPoint(GRAND.weapon, 6.2);
  var M = await session('', 390, 844, true); await M.ev("return P.goTo(" + clothApproach[0] + ", " + clothApproach[1] + ", undefined, undefined, 120000);"); await sleep(600); var sM0 = await state(M.ev); var shopPrompt = sM0.prompts.filter(function (x) { return x.intent === 'ENTER' && x.id === GRAND.clothing.door; })[0];
  var mP = M.ev("return P.interact();"); await sleep(350); await M.shot('09_shop_confirm_portrait'); await M.ev("P.confirmAnswer(true); return 1;"); var mRes = await mP; var sM1 = await state(M.ev); await sleep(400); await M.shot('10_clothing_shop_interior_portrait');
  await M.ev("return P.goTo(-3, 0, undefined, undefined, 20000);"); await sleep(300); await M.ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0.5});"); await sleep(900); await M.shot('10b_clothing_shop_gameplay_portrait');
  await M.ev("return P.goTo(0, -3.6, undefined, undefined, 20000);"); await sleep(600); var sM2 = await state(M.ev); var browse = sM2.prompts.filter(function (x) { return x.intent === 'BROWSE'; })[0]; var bRes = await M.ev("return P.interact();"); await sleep(300); var cat = await M.ev("var c=document.getElementById('g-catalog'); return {open:c.classList.contains('on'), text:c.textContent.replace(/\\s+/g,' ').trim(), buttons:Array.prototype.map.call(c.querySelectorAll('button'), function(b){ return b.textContent.trim(); })};"); await M.shot('11_zero_stock_catalog_portrait'); await M.ev("P.hud.catalogClose(); return 1;");
  report.shop = { door_prompt: shopPrompt, enter: mRes, browse_prompt: browse, catalog: cat, registry: await M.ev("return P.shops();") };
  ok('C1 CLOTHING SHOP: the door prompt (CLOTHING_DOOR) enters the finished interior (touch-emulated portrait), the counter prompt is BROWSE, the catalog panel is the registry’s empty state — 0 items, "NO STOCK YET", status ZERO_STOCK, the only control is CLOSE (no purchase, no price, no item)', !!shopPrompt && !!mRes && mRes.accepted && sM1.room === 'CLOTHING_SHOP' && !!browse && !!bRes && bRes.browse === 'SHOP_CLOTHING' && cat.open && /NO STOCK YET/.test(cat.text) && /0 items/.test(cat.text) && /zero_stock/i.test(cat.text) && cat.buttons.length === 1 && cat.buttons[0] === 'CLOSE' && !/\$|price|buy now|purchase now/i.test(cat.text), { prompt: shopPrompt, enter: mRes && mRes.accepted, browse: browse, catalog: cat });
  await M.ev("return P.goTo(" + GRAND.clothing.exit[0] + ", " + GRAND.clothing.exit[1] + ", undefined, undefined, 20000);"); await sleep(400); var xP = M.ev("return P.interact();"); await sleep(350); await M.ev("P.confirmAnswer(true); return 1;"); var xRes = await xP; var sM3 = await state(M.ev); await sleep(300);
  var clothingReturn = approachPoint(GRAND.clothing, RETURN_CLEARANCE_M), clothingGroundReturn = groundReturnProof(sM3, sM0.flight && sM0.flight.ground);
  ok('C2 the shop EXIT lands at the manifest clothing door’s authored 0.55 m exterior return and entry ground level, facing away', !!xRes && xRes.accepted && sM3.room === 'FIELD' && pointError(sM3.pos, clothingReturn) <= RETURN_EPS_M && clothingGroundReturn.pass && Math.abs(sM3.facing - GRAND.clothing.expectedFacing) < 0.05, { res: xRes, pos: sM3.pos, expected_return: clothingReturn, error_m: pointError(sM3.pos, clothingReturn), ground_return: clothingGroundReturn, facing: sM3.facing, manifest_door: GRAND.clothing.doorAt });
  var weaponRouteOut = await M.ev("return P.goTo(" + clothOutwardStage[0] + ", " + clothOutwardStage[1] + ", undefined, undefined, 30000);"); var weaponRouteAcross = await M.ev("return P.goTo(" + weaponOutwardStage[0] + ", " + weaponOutwardStage[1] + ", undefined, undefined, 30000);"); var weaponRouteIn = await M.ev("return P.goTo(" + weaponApproach[0] + ", " + weaponApproach[1] + ", undefined, undefined, 30000);"); await sleep(500); var sW0 = await state(M.ev); var weaponPrompt = sW0.prompts.filter(function (x) { return x.intent === 'ENTER' && x.id === GRAND.weapon.door && x.to === GRAND.weapon.room && x.eligible; })[0] || null; report.shop.weapon_route = { clothing_outward_stage: clothOutwardStage, weapon_outward_stage: weaponOutwardStage, weapon_approach: weaponApproach, out: weaponRouteOut, across: weaponRouteAcross, in: weaponRouteIn, prompt: weaponPrompt, state: { room: sW0.room, pos: sW0.pos } }; var wRes = { accepted: false, reason: 'WEAPON_PROMPT_MISSING' }, weaponConfirm = { open: false, answered: false }; if (weaponPrompt) { var wP = M.ev("return P.interact();"); await sleep(350); weaponConfirm = await M.ev("return {open:P.hud.confirmOpen(),answered:P.confirmAnswer(true)};"); wRes = await wP; } await sleep(400); var sW1 = await state(M.ev); await M.ev("return P.goTo(2.5, -1, undefined, undefined, 20000);"); await sleep(300); await M.ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-0.6});"); await sleep(900); await M.shot('15_weapon_shop_gameplay_portrait'); await M.ev("return P.goTo(0, -3.6, undefined, undefined, 20000);"); await sleep(500); var wB = await M.ev("return P.interact();"); await sleep(300); var wCat = await M.ev("var c=document.getElementById('g-catalog'); return {open:c.classList.contains('on'), text:c.textContent.replace(/\\s+/g,' ').trim()};"); await M.shot('16_weapon_zero_stock_catalog_portrait'); await M.ev("P.hud.catalogClose(); return 1;"); await M.ev("return P.goTo(" + GRAND.weapon.exit[0] + ", " + GRAND.weapon.exit[1] + ", undefined, undefined, 20000);"); await sleep(400); var wxP = M.ev("return P.interact();"); await sleep(350); await M.ev("P.confirmAnswer(true); return 1;"); var wxRes = await wxP; var sW = await state(M.ev);
  var weaponReturn = approachPoint(GRAND.weapon, RETURN_CLEARANCE_M), weaponGroundReturn = groundReturnProof(sW, sW0.flight && sW0.flight.ground);
  ok('C3 WEAPON SHOP: the phone route clears the Market facade through manifest-derived 6.2 m outward stages, reaches the weapon door head-on, proves the eligible WEAPON_DOOR prompt before interaction, enters WEAPON_SHOP, captures gameplay/zero-stock BROWSE, and exits at the authored position and entry ground level', !!weaponRouteOut && weaponRouteOut.reached && !!weaponRouteAcross && weaponRouteAcross.reached && !!weaponRouteIn && weaponRouteIn.reached && !!weaponPrompt && weaponConfirm.open && weaponConfirm.answered && !!wRes && wRes.accepted && sW1.room === GRAND.weapon.room && !!wB && wB.browse === 'SHOP_WEAPONS' && wCat.open && /NO STOCK YET/.test(wCat.text) && /0 items/.test(wCat.text) && !!wxRes && wxRes.accepted && sW.room === 'FIELD' && pointError(sW.pos, weaponReturn) <= RETURN_EPS_M && weaponGroundReturn.pass, { route: report.shop.weapon_route, confirm: weaponConfirm, enter: wRes && wRes.accepted, entered_room: sW1.room, browse: wB, catalog: wCat, out: sW.pos, expected_return: weaponReturn, error_m: pointError(sW.pos, weaponReturn), ground_return: weaponGroundReturn, manifest_door: GRAND.weapon.doorAt });
  ok('Z2 zero page / console errors through the shop transaction (portrait, touch emulated)', M.pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, M.pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 3));
  await M.pg.close();
} catch (e) { ok('X probe ran to the end', false, String(e && e.stack || e)); }
finally { try { srv.close(); } catch (e) { } }
report.summary = { pass: pass, fail: fail }; fs.writeFileSync(path.join(OUT, 'probe_interior.json'), JSON.stringify(report, null, 1)); console.log('PASS ' + pass + ' FAIL ' + fail + ' → ' + OUT); process.exit(fail ? 1 : 0);
