/* MAHWORLD :: SPEC B ACCEPTANCE PROBE (PASS 2) — the real runtime in headless Chrome, driven through its own input paths.
   Touch = EMULATED (synthetic pointer events on the look / stick zones), never a physical phone. Desktop = mouse + keyboard events.
     A  swipe release: after a look drag is released, the yaw error to "behind" is < 5° within return_delay + return_time (+ one frame), sampled every frame
     B  zero frames with the camera inside geometry on the test route (spawn → walk 10 s → fly 20 s → land → combo) + a wall-hug segment
     C  hold-back (3 s): he ends facing away from the initial camera direction, camera behind him, no oscillation (facing velocity sign changes ≤ 1
        after the turn, last-second facing drift < 2°)
     D  his screen box never overlaps a HUD / control rect in portrait or landscape (idle / run / fly / combo)
   node deploy/probe_spec_b.mjs [static_dist] [portrait|landscape|desktop] [--out dir] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') && !/^(portrait|landscape|desktop)$/.test(argv[0]) ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
var MODE = argv.filter(function (a) { return /^(portrait|landscape|desktop)$/.test(a); })[0] || 'portrait'; var OUT = argv.indexOf('--out') >= 0 ? argv[argv.indexOf('--out') + 1] : path.join(HERE, 'probe_out', 'spec_b'); fs.mkdirSync(OUT, { recursive: true });
var TOUCH = MODE !== 'desktop'; var VP = MODE === 'portrait' ? [390, 844] : (MODE === 'landscape' ? [844, 390] : [1200, 750]);
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, unlockFps: true }); var pass = 0, fail = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(40); await key(code, false); }
async function ptr(type, el, id, x, y) { await pg.evaluate("(function(){ var t=document.getElementById('" + el + "'); var e=new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'touch',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true}); t.dispatchEvent(e); })(); 1"); }
async function vw() { return await ev("return {w:innerWidth,h:innerHeight};"); }
async function lookDrag(dx, dy, ms) { var v = await vw(); var x = v.w * 0.72, y = v.h * 0.45; await ptr('pointerdown', 'tc-world', 2, x, y); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await ptr('pointermove', 'tc-world', 2, x + dx * i / n, y + dy * i / n); await sleep(40); } return { x: x + dx, y: y + dy }; }
async function lookRelease(p) { await ptr('pointerup', 'tc-world', 2, p.x, p.y); }
async function mouseDrag(dx, dy, ms) { var v = await vw(); var x = v.w * 0.6, y = v.h * 0.5; await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + x + ",clientY:" + y + ",bubbles:true})); 1"); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + (x + dx * i / n) + ",clientY:" + (y + dy * i / n) + ",bubbles:true})); 1"); await sleep(40); } return { x: x + dx, y: y + dy }; }
async function mouseUp(p) { await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + p.x + ",clientY:" + p.y + ",bubbles:true})); 1"); }
async function stickHold(dirx, diry) { var v = await vw(); var x = v.w * 0.2, y = v.h * 0.72; await ptr('pointerdown', 'tc-stickzone', 1, x, y); for (var i = 1; i <= 4; i++) { await ptr('pointermove', 'tc-stickzone', 1, x + dirx * 22 * i, y + diry * 22 * i); await sleep(30); } return { x: x + dirx * 88, y: y + diry * 88 }; }
async function stickRelease(p) { await ptr('pointerup', 'tc-stickzone', 1, p.x, p.y); }
/* in-page per-frame sampler of the camera state (installed once; phases are labelled from here) */
async function startSampler() { await pg.evaluate("window.__sb={phase:'idle',rows:[],detail:[]}; (function loop(t){ requestAnimationFrame(loop); var P=window.MAHWORLD_PLAY; try { var c=P.camState(); window.__sb.rows.push([window.__sb.phase, performance.now(), c.err_deg, c.state, c.inside?1:0, c.below_ground?1:0, c.facing_deg, c.applied, c.fade]); if (c.inside && window.__sb.detail.length < 6) window.__sb.detail.push({ phase: window.__sb.phase, t: performance.now(), inside: c.inside, pos: c.position, applied: c.applied, dist: c.dist, me: P.snap().play.position, alt: P.snap().play.flight.altitude }); } catch(e){} })(performance.now()); 1"); }
async function setPhase(p) { await pg.evaluate("window.__sb.phase=" + JSON.stringify(p) + "; 1"); }
async function rows(phase) { var all = await pg.evaluate("window.__sb.rows"); return all.filter(function (r) { return !phase || r[0] === phase; }); }
function overlaps(a, b) { return !(a.right <= b.left || a.left >= b.right || a.bottom <= b.top || a.top >= b.bottom); }
function wrapDeg(r) { var d = r * 180 / Math.PI; while (d > 180) d -= 360; while (d < -180) d += 360; return d; }
var report = { mode: MODE, viewport: VP, touch_emulated: TOUCH, checks: lines, samples: {} };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(6000); await ev("P.hud.showGuide(false); return 1;");
  for (var w = 0; w < 120; w++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); }
  var isT = await ev("return document.body.classList.contains('touch');"); ok('0 mode ' + MODE + (TOUCH ? ' (touch EMULATED: synthetic pointer events)' : ' (keyboard + mouse events)') + ' ' + VP.join('x'), isT === TOUCH);
  var cfg = await ev("return P.camCfg();"); await startSampler(); await sleep(1500);
  /* ── A. swipe release ── */
  var cs0 = await ev("return P.camState();"); ok('A0 at rest the camera is behind him (|yaw error| < 5°)', Math.abs(cs0.err_deg) < 5, cs0.err_deg);
  /* convention-free back check at four host headings: the camera's forward must point the way his FACE points (dot > cos 5°) — and stills at ±90° */
  var backs = []; for (var hy of [1.5708, 3.1416, -1.5708, 0]) { await ev("return P.send('MOVE',{forward:1,strafe:0,run:false,yaw:" + hy + "});"); await sleep(700); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:" + hy + "});"); await sleep(1600); var cb = await ev("var c=P.camState(); return {heading:" + hy + ", back_err_deg:c.back_err_deg, err_deg:c.err_deg, facing_deg:c.facing_deg};"); backs.push(cb); if (Math.abs(hy) > 1.5 && Math.abs(hy) < 1.6) await pg.screenshot(path.join(OUT, 'spec_b_' + MODE + '_back_' + (hy > 0 ? 'east' : 'west') + '.png')); }
  ok('A0b convention-free: at host headings +90° / 180° / −90° / 0° the camera forward points the way his face points (back error < 5°) — stills spec_b_' + MODE + '_back_east/west.png', backs.every(function (b) { return b.back_err_deg !== null && b.back_err_deg < 5; }), backs); report.samples.back_check = backs;
  await setPhase('swipe'); var pA = TOUCH ? await lookDrag(-170, 0, 500) : await mouseDrag(-260, 0, 500); await sleep(120); var csD = await ev("return P.camState();");
  ok('A1 while the finger / button is down the camera orbits freely (state DRAG, |error| > 25°)', csD.state === 'DRAG' && Math.abs(csD.err_deg) > 25, { state: csD.state, err: csD.err_deg });
  var tRel = await pg.evaluate("performance.now()"); if (TOUCH) await lookRelease(pA); else await mouseUp(pA); await setPhase('release');
  /* A2–A4 (Spec B release → automatic return) — SUPERSEDED — O1 (convergence 2026-09-17): "after release, retain the chosen orbit heading and pitch around the
     moving avatar; do not automatically rotate back behind him on release, after a timer, when movement begins/ends, after attacking, or when flight changes".
     Replacement checks A2o–A4o below; the < 5° rear-yaw check now applies to the EXPLICIT reset (A3o) with the documented reset_time_s. */
  console.log('SUPERSEDED — O1: A2 (release hold) · A3 (return within delay + return time) · A4 (stays behind after the automatic return)'); lines.push('SUPERSEDED — O1: A2 / A3 / A4 (automatic return on release)');
  await sleep(2000); var rel = await rows('release'); var errRel = rel.length ? rel[0][2] : null; var errLate = rel.length ? rel[rel.length - 1][2] : null; var csRel = await ev("return P.camState();");
  ok('A2o release: the manual orbit PERSISTS — 2 s after the release the camera is still where the finger left it (|Δ yaw error| < 3°, mode orbit, |error| > 25°)', rel.length > 5 && errRel !== null && Math.abs(errLate - errRel) < 3 && csRel.mode === 'orbit' && Math.abs(csRel.err_deg) > 25, { first_err: errRel, last_err: errLate, mode: csRel.mode });
  report.samples.release = rel.map(function (r) { return { t: +(r[1] - tRel).toFixed(0), err: r[2], state: r[3] }; });
  /* movement / attack / flight do NOT reset the orbit */
  var yawO = csRel.yaw; if (TOUCH) { var sp = await stickHold(0, -1); await sleep(900); await stickRelease(sp); } else { await key('KeyW', true); await sleep(900); await key('KeyW', false); } await sleep(700); var csMv = await ev("return P.camState();");
  await tap('KeyE'); await sleep(1200); var csAt = await ev("return P.camState();"); await tap('KeyF'); await sleep(1200); var csFl = await ev("return P.camState();"); await tap('KeyF'); await sleep(2500);
  ok('A2p moving, attacking and taking flight leave the orbit heading alone (|Δ yaw| < 3° each, mode orbit throughout)', Math.abs(wrapDeg(csMv.yaw - yawO)) < 3 && Math.abs(wrapDeg(csAt.yaw - yawO)) < 3 && Math.abs(wrapDeg(csFl.yaw - yawO)) < 3 && csMv.mode === 'orbit' && csAt.mode === 'orbit' && csFl.mode === 'orbit', { after_move: +wrapDeg(csMv.yaw - yawO).toFixed(2), after_attack: +wrapDeg(csAt.yaw - yawO).toFixed(2), after_flight: +wrapDeg(csFl.yaw - yawO).toFixed(2), modes: [csMv.mode, csAt.mode, csFl.mode] });
  /* the EXPLICIT reset: Backspace (desktop) / the ⟲ CAM button (touch) — from a REAL orbit offset (re-drag first: walking in A2p turned his back to the static orbit), collision-safe glide of reset_time_s, then rear follow */
  var pR = TOUCH ? await lookDrag(-170, 0, 500) : await mouseDrag(-260, 0, 500); await sleep(120); if (TOUCH) await lookRelease(pR); else await mouseUp(pR); await sleep(400); var csPre = await ev("return P.camState();"); ok('A3o- before the reset the camera is at a real orbit offset (|error| > 25°, mode orbit)', Math.abs(csPre.err_deg) > 25 && csPre.mode === 'orbit', { err: csPre.err_deg, mode: csPre.mode });
  var tReset = await pg.evaluate("performance.now()"); await setPhase('reset'); if (TOUCH) { var rb = await pg.evaluate("(function(){ var e=document.getElementById('g-camreset'); if(!e) return null; var r=e.getBoundingClientRect(); return {cx:r.left+r.width/2, cy:r.top+r.height/2, w:r.width, h:r.height}; })()"); if (rb) { await ptr('pointerdown', 'g-camreset', 6, rb.cx, rb.cy); await sleep(50); await ptr('pointerup', 'g-camreset', 6, rb.cx, rb.cy); } } else await tap('Backspace');
  var resetBudget = cfg.reset_time_s * 1000 + 40; await sleep(resetBudget + 500); var rs = await rows('reset'); var atR = rs.filter(function (r) { return r[1] - tReset >= resetBudget; })[0]; var afterR = rs.filter(function (r) { return r[1] - tReset >= resetBudget; }); var afterRMax = afterR.length ? Math.max.apply(null, afterR.map(function (r) { return Math.abs(r[2]); })) : 999; var csR = await ev("return P.camState();");
  ok('A3o explicit reset (' + (TOUCH ? '⟲ CAM button' : 'Backspace key') + '): |yaw error to behind| < 5° within reset_time_s (' + cfg.reset_time_s + ' s + 1 frame), mode back to follow', !!atR && Math.abs(atR[2]) < 5 && csR.mode === 'follow', atR ? { t_ms: +(atR[1] - tReset).toFixed(0), err_deg: atR[2], mode: csR.mode } : 'no sample');
  ok('A4o after the reset the camera stays behind (max |error| < 5° over the next 0.5 s, no rubber band) and no frame of the whole reset phase was inside geometry', afterR.length > 5 && afterRMax < 5 && !rs.some(function (r) { return r[4]; }), { samples: afterR.length, max_err: +afterRMax.toFixed(2), reset_frames: rs.length, inside_frames: rs.filter(function (r) { return r[4]; }).length });
  report.samples.reset = rs.map(function (r) { return { t: +(r[1] - tReset).toFixed(0), err: r[2], state: r[3] }; });
  ok('A5o (was A5 return-when-idle) SUPERSEDED — O1: there is no automatic return setting any more; the orbit persists by design (checked by A2o)', true);
  ok('A6o movement in FOLLOW mode keeps the camera behind (|error| < 8° after a short move + settle)', (await (async function () { if (TOUCH) { var sp2 = await stickHold(0, -1); await sleep(900); await stickRelease(sp2); } else { await key('KeyW', true); await sleep(900); await key('KeyW', false); } await sleep(1200); var c6 = await ev("return P.camState();"); return Math.abs(c6.err_deg) < 8; })()), 'see camState');
  /* ── C. hold-back (3 s): he turns around once, the camera swings behind, no oscillation ── */
  await setPhase('holdback'); var f0 = (await ev("return P.camState();")); var tHB = await pg.evaluate("performance.now()");
  if (TOUCH) { var sb = await stickHold(0, 1); await sleep(3000); await stickRelease(sb); } else { await key('KeyS', true); await sleep(3000); await key('KeyS', false); }
  await sleep(900); var hb = await rows('holdback'); var facing = hb.map(function (r) { return r[6]; }); var turned = Math.abs((((facing[facing.length - 1] - f0.facing_deg) % 360) + 540) % 360 - 180);   /* |wrapped facing change| (180 = turned around) */
  var vel = []; for (var i = 1; i < facing.length; i++) { var d = ((facing[i] - facing[i - 1] + 540) % 360) - 180; vel.push(d); }
  var settledFrom = -1; for (var j = 0; j < vel.length; j++) { if (Math.abs(vel[j]) > 0.05) settledFrom = j; }
  var signChanges = 0; var lastSign = 0; vel.forEach(function (v) { if (Math.abs(v) < 0.15) return; var sg = v > 0 ? 1 : -1; if (lastSign && sg !== lastSign) signChanges++; lastSign = sg; });
  var lastSec = hb.filter(function (r) { return r[1] > hb[hb.length - 1][1] - 1000; }); var drift = lastSec.length ? Math.max.apply(null, lastSec.map(function (r) { return Math.abs(((r[6] - lastSec[0][6] + 540) % 360) - 180); })) : 99;
  var csHB = await ev("return P.camState();");
  ok('C1 hold-back 3 s: he ends facing AWAY from the initial camera direction (|facing change| within 12° of 180°)', Math.abs(180 - turned) < 12, { turned_deg: +turned.toFixed(1), facing0: f0.facing_deg, facing1: facing[facing.length - 1] });
  ok('C2 hold-back: no oscillation (facing velocity sign changes ≤ 1 over the hold, last-second drift < 2°)', signChanges <= 1 && drift < 2, { sign_changes: signChanges, last_second_drift_deg: +drift.toFixed(2), samples: hb.length });
  ok('C3 hold-back: the camera ends behind him (|yaw error| < 5°)', Math.abs(csHB.err_deg) < 5, csHB.err_deg);
  report.samples.holdback = hb.map(function (r) { return { t: +(r[1] - tHB).toFixed(0), facing: r[6], err: r[2] }; });
  /* ── D. screen box vs HUD / control rects: idle, run, fly, combo ── */
  async function boxCheck(label) { var box = await ev("return P.screenBox();"); var rects = await ev("return P.hudRects();"); var camNow = await ev("var c=P.camState(); var p=P.snap().play; return {mode:c.mode, applied:+c.applied.toFixed(2), dist:+c.dist.toFixed(2), pitch:+c.pitch.toFixed(2), bias:c.pitch_bias, obstructed:c.obstructed, pos:[+p.position.x.toFixed(1),+p.position.z.toFixed(1)], alt:p.flight.altitude};"); var hits = rects.filter(function (rc) { return overlaps(box, rc); }); var mid = box.top > box.h * 0.10 && box.bottom < box.h * 0.90;   /* working definition of the middle band: his (conservative, cuboid) screen box within 10–90 % of the height */ var ids = rects.map(function (r) { return r.id; }); var covered = rects.length > 20 && (!TOUCH || (ids.indexOf('tc-stickzone') >= 0 && ids.indexOf('g-fly') >= 0));   /* never vacuous: the thumb-landing zone and the right cluster must be in the rect set on touch */ ok('D ' + label + ': his screen box overlaps no HUD / control rect (incl. the thumb-landing zone) and sits in the middle band', hits.length === 0 && mid && covered, { box: box, cam: camNow, hits: hits.slice(0, 4).map(function (h) { return h.id; }), rects: rects.length, covered: covered }); return { box: box, hits: hits, rects: rects }; }
  await setPhase('box'); await sleep(800); report.samples.box_idle = await boxCheck('idle');
  if (TOUCH) { var sr = await stickHold(0, -1); await sleep(1500); report.samples.box_run = await boxCheck('run'); await stickRelease(sr); } else { await key('ShiftLeft', true); await key('KeyW', true); await sleep(1500); report.samples.box_run = await boxCheck('run'); await key('KeyW', false); await key('ShiftLeft', false); }
  await sleep(800);
  /* ── B. the test route with the camera-inside sampler + a wall hug ── */
  await setPhase('route'); var tR = await pg.evaluate("performance.now()");
  await tap('Equal'); await sleep(150);   /* PASS 4b: the fused ground travel is harmonized to the separated walk (3.58 m/s); `+` (6.71 m/s) keeps this timed route long enough that the flight leg lands on the open plaza floor instead of at the Mentor Spire’s corner (a wall-backed landing collapses the boom legitimately, but that is not the framing this check measures) */
  await key('KeyW', true); await sleep(10000); await key('KeyW', false); await sleep(300); await tap('Equal'); await sleep(150);
  await tap('KeyF'); await sleep(400); await key('Space', true); await sleep(2500); await key('Space', false); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1200); await key('KeyW', true); await sleep(7000);   /* fly SOUTH over open plaza (heading 0 = −z): with the 0.67× host colliders in sync the old north-east heading reached the blue tower's recesses in 7 s (a niche is a legitimate collapse, not a framing test) */ await key('KeyW', false); await sleep(1500); report.samples.box_fly = await boxCheck('fly'); await sleep(7900);
  await tap('KeyF'); await sleep(6000);
  await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:3.1416});"); await sleep(300); for (var c of ['KeyE', 'KeyR', 'KeyT', 'KeyY']) { await tap(c); await sleep(1400); } report.samples.box_combo = await boxCheck('combo'); await ev("return P.send('RULES_SELECT',{category:'SPECIAL_MAGIC'});"); await sleep(200); await tap('KeyE'); await sleep(2500); await ev("return P.send('RULES_SELECT',{category:'PHYSICAL'});");
  /* wall hug: walk into the nearest landmark wall and orbit the camera around him there */
  await setPhase('wallhug'); var gym = await ev("var d=P.district(); var g=d&&d.loaded.filter(function(x){return x.id==='gym';})[0]; var s=P.snap().play; return {me:s.position};"); await ev("return P.send('MOVE',{forward:1,strafe:0,run:true,yaw:3.1416});"); await sleep(6000); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false});"); await sleep(400);
  for (var o = 0; o < 4; o++) { var pw = TOUCH ? await lookDrag(120, 20, 300) : await mouseDrag(200, 30, 300); await sleep(200); if (TOUCH) await lookRelease(pw); else await mouseUp(pw); await sleep(700); }
  await sleep(500); var routeRows = (await rows('route')).concat(await rows('wallhug')); var inside = routeRows.filter(function (r) { return r[4] === 1; }); var below = routeRows.filter(function (r) { return r[5] === 1; });
  var insideDetail = await pg.evaluate("window.__sb.detail"); report.samples.inside_detail = insideDetail;
  ok('B1 zero frames with the camera inside geometry on the test route + wall hug (' + routeRows.length + ' frames sampled)', routeRows.length > 500 && inside.length === 0, { frames: routeRows.length, inside_frames: inside.length, first_inside_t: inside.length ? +(inside[0][1] - tR).toFixed(0) : null, detail: insideDetail.slice(0, 2) });
  ok('B2 zero frames with the camera below the ground it stands over', below.length === 0, { below_frames: below.length });
  var fades = routeRows.filter(function (r) { return r[8] < 0.999; }); ok('B3 (info) frames with the mesh faded because the boom was shorter than fade_below_m: ' + fades.length, true, { faded_frames: fades.length, min_applied: +Math.min.apply(null, routeRows.map(function (r) { return r[7]; })).toFixed(2) });
  await pg.screenshot(path.join(OUT, 'spec_b_' + MODE + '_end.png'));
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'spec_b_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT spec B ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed · ' + path.join(OUT, 'spec_b_' + MODE + '.json')); process.exit(fail ? 1 : 0);
