/* Follow-up for two facts only: exact zero-pool ordinary return ride and the
   selected Titan-lake fish/resource tranche. It waits for live prompts after
   dev placement so stale client snapshots cannot select the court. */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)), DIST = path.join(HERE, 'static_dist'), OUT = path.join(HERE, 'probe_out', 'halo_return_map_followup'); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST), pg = await launchChrome({ width: 960, height: 720, gpu: true, unlockFps: true, cmdTimeoutMs: 120000 }), report = { generated_at: new Date().toISOString(), shots: [], checks: {}, console_errors: [] };
async function ev(src) { return await pg.evaluate("(async function(){var P=window.MAHWORLD_PLAY,H=window.MAHWORLD_STATIC_HOST;" + src + "})()"); }
async function snap() { return await ev("return P.snap().play;"); }
async function tapEnter() { var p = { code: 'Enter', key: 'Enter', windowsVirtualKeyCode: 13, nativeVirtualKeyCode: 13 }; await pg.cmd('Input.dispatchKeyEvent', Object.assign({ type: 'rawKeyDown' }, p)); await sleep(70); await pg.cmd('Input.dispatchKeyEvent', Object.assign({ type: 'keyUp' }, p)); }
async function shot(name, canvasOnly) { if (canvasOnly) await ev("document.querySelectorAll('body > *').forEach(function(e){if(e.tagName!=='CANVAS')e.style.visibility='hidden';});return 1;"); await sleep(240); var f = path.join(OUT, name + '.png'); await pg.screenshot(f); report.shots.push(name + '.png'); if (canvasOnly) await ev("document.querySelectorAll('body > *').forEach(function(e){e.style.visibility='';});return 1;"); console.log('SHOT ' + name); }
async function freeCam(from, at, follow) { return await ev("var THREE=P.THREE,r=P.rendererDebug();if(!r.__hrmfOrig){r.__hrmfOrig=r.render.bind(r);r.render=function(sc,cam){var c=window.__hrmfCam;if(c&&window.__hrmfFollow){var p=P.snap().play,t=p&&p.transit,q=t&&(t.carrier_pose||t.rider_pose);if(q){c.position.set(q.x-7,q.y+3.8,q.z+7);c.lookAt(q.x,q.y+1.25,q.z);c.updateProjectionMatrix();}}r.__hrmfOrig(sc,c||cam);};}var c=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,0.2,2400);c.position.set(" + from.join(',') + ");c.lookAt(" + at.join(',') + ");c.updateProjectionMatrix();window.__hrmfCam=c;window.__hrmfFollow=" + (follow ? 'true' : 'false') + ";return 1;"); }
async function waitFor(fn, timeout, label) { var end = Date.now() + timeout, p; while (Date.now() < end) { p = await snap(); if (fn(p)) return p; await sleep(80); } throw new Error(label + ': ' + JSON.stringify(p && { domain: p.spatial_domain, pos: p.position, prompts: p.prompts, transit: p.transit, sport: p.sport })); }
async function placeAndPrompt(x, z, id) { await ev("return await P.devPlay('PLACE',{x:" + x + ",z:" + z + "});"); return await waitFor(function (p) { return Math.hypot(p.position.x - x, p.position.z - z) < 0.15 && p.prompts.some(function (q) { return q.id === id && q.eligible; }); }, 5000, 'prompt ' + id); }
async function rideSamples(direction) { var out = [], shotDone = false, end = Date.now() + 24000; while (Date.now() < end) { var p = await snap(), v = await ev("var m=P.mePose(),t=P.treeAscentInfo&&P.treeAscentInfo();return {root_y:m&&m.root_y,cabin_y:t&&t.cabin_y};"); var tr = p.transit; out.push({ phase: tr && tr.phase, progress: tr && tr.progress, carrier: tr && tr.carrier_pose, rider: tr && tr.rider_pose, host_drift_m: tr && tr.relative_drift_m, visual_drift_y_m: tr && v ? +Math.abs(v.root_y - v.cabin_y).toFixed(3) : null, clearance: tr && tr.clearance, flight: p.flight_mahgic.current, held: p.equipment.held }); if (!shotDone && tr && tr.phase === 'OCCUPIED_TRAVEL' && tr.travel_progress > 0.42) { shotDone = true; await shot(direction === 'UP' ? '01_zero_pool_up_inside' : '02_zero_pool_down_inside', false); } if (!tr && p.spatial_domain === (direction === 'UP' ? 'HALO' : 'WORLD')) return { samples: out, after: p }; await sleep(360); } throw new Error(direction + ' ride timed out'); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1&tier=high'); await waitForGame(pg, 120000); await sleep(1500); await ev("P.hud.showGuide(false);return 1;"); for (var i = 0; i < 240; i++) { var w = await ev("return P.world?P.world().status:null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); }
  await ev("P.send('EQUIP_DISMISS',{});return 1;"); await sleep(700); await ev("return P.send('EQUIP_MANIFEST',{kind:'BARBELL',count:1});"); await sleep(1800); var barId = await ev("var b=(P.snap().play.equipment.manifested||[]).filter(function(x){return x.kind==='BARBELL';})[0];return b&&b.id;"); if (barId) await ev("return P.send('EQUIP_PICKUP',{id:'" + barId + "'});"); await sleep(300);
  var upPrompt = await placeAndPrompt(22.7, 40, 'ELEVATOR_UP'); await freeCam([15.7, 3.8, 47], [22.7, 1.2, 40], true); var upZero = await ev("var a=H.host.dev.play_internals().actorOf('PLAYER_A'),s=a.flightRes.state();if(s.current>0)a.flightRes.spend(s.current,'ZERO_AT_UP_INPUT');return {host:a.flightRes.state(),prompt:P.snap().play.prompts};"); await tapEnter(); var upStarted = await waitFor(function (p) { return p.transit && p.transit.id === 'ELEVATOR_UP'; }, 2500, 'ordinary up input'); var upRide = await rideSamples('UP');
  var downPrompt = await placeAndPrompt(22.7, 40, 'ELEVATOR_DOWN'); await freeCam([15.7, 243.8, 47], [22.7, 241.2, 40], true); var downZero = await ev("var a=H.host.dev.play_internals().actorOf('PLAYER_A'),s=a.flightRes.state();if(s.current>0)a.flightRes.spend(s.current,'ZERO_AT_DOWN_INPUT');return {host:a.flightRes.state(),prompt:P.snap().play.prompts};"); await tapEnter(); var downStarted = await waitFor(function (p) { return p.transit && p.transit.id === 'ELEVATOR_DOWN'; }, 2500, 'ordinary down input'); var downRide = await rideSamples('DOWN'); await ev("window.__hrmfCam=null;window.__hrmfFollow=false;return 1;");
  report.checks.rides = { held_id: barId, up_prompt: upPrompt.prompts.filter(function(q){return q.id==='ELEVATOR_UP';}), up_zero_at_input: upZero, up_started: upStarted.transit, up: upRide, down_prompt: downPrompt.prompts.filter(function(q){return q.id==='ELEVATOR_DOWN';}), down_zero_at_input: downZero, down_started: downStarted.transit, down: downRide };

  /* Mainland selected correction plus an affected equipment/resource route. */
  await ev("return await P.devPlay('PLACE',{x:119.7,z:108});"); await waitFor(function (p) { return p.spatial_domain === 'WORLD' && Math.hypot(p.position.x - 119.7, p.position.z - 108) < 0.2; }, 5000, 'Titan resource placement'); await sleep(700);
  var mapStart = await ev("var I=H.host.dev.play_internals(),rf=I.rulesField(),me=rf.combatant('PLAYER_A'),st=me.pool.state();if(st.current>st.max-120)me.pool.spend(st.current-(st.max-120),'MAP_REFILL_FIXTURE');var j=H.host.dev.log().length;var lk=P.send('LOCK_TARGET',{aim_id:'NODE_RB_TITAN_LAKE'});return {j:j,lock:lk,combat:me.pool.state(),held:P.snap().play.equipment.held};");
  for (var h = 0; h < 7; h++) { await ev("var I=H.host.dev.play_internals(),me=I.rulesField().combatant('PLAYER_A');me.cooldowns={};P.send('RULES_SELECT',{category:'PHYSICAL',slot:0});return P.send('RULES_CAST',{skill_id:'PA_PUSH'});"); await sleep(800); var broken = await ev("return H.host.dev.log().slice(" + mapStart.j + ").some(function(e){return e.kind==='RESOURCE_NODE_BROKEN'&&e.id==='NODE_RB_TITAN_LAKE';});"); if (broken) break; }
  await ev("return await P.devPlay('PLACE',{x:122,z:108});"); await waitFor(function (p) { return Math.hypot(p.position.x - 122, p.position.z - 108) < 0.2; }, 4000, 'refill pickup placement'); await sleep(1100);
  report.checks.mainland = await ev("var s=P.snap().play,L=H.host.dev.log().slice(" + mapStart.j + ");return {start:" + JSON.stringify(mapStart) + ",domain:s.spatial_domain,held:s.equipment.held,combat_after:s.combat_mahgic.current,refills:s.equipment.refills,node_broken:L.filter(function(e){return e.kind==='RESOURCE_NODE_BROKEN';}),refill_events:L.filter(function(e){return e.kind==='REFILL_PICKED'||e.kind==='REFILL_USED';}),gear:P.worldLayer().gear().debug(),wildlife:P.worldLayer().wildlife().debug()};");
  await freeCam([128, 7.2, 87], [149, 0, 104], false); await sleep(1200); await shot('03_titan_lake_finned_fish', true); await freeCam([116, 4.2, 114], [122, 0.9, 108], false); await shot('04_titan_resource_refill_route', false); report.checks.final = await ev("return {render:P.renderInfo(),perf:P.perf(),world:P.world()};"); report.console_errors = pg.errors.filter(function (e) { return !/404|favicon/.test(e); });
} catch (e) { report.fatal = String(e && e.stack || e); console.error(report.fatal); }
finally { fs.writeFileSync(path.join(OUT, 'report.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT HALO return/map follow-up shots ' + report.shots.length + ' errors ' + report.console_errors.length + (report.fatal ? ' FATAL' : ' OK') + ' -> ' + OUT); process.exit(report.fatal || report.console_errors.length ? 1 : 0);
