/* OWNER HOTFIX 2026-09-19 §2 — MESH-LEVEL diagnosis of the shoulder / armpit tearing: at a frozen runtime pose, every skinned mesh of the fused
   Athlete is re-skinned on the CPU (SkinnedMesh.applyBoneTransform) and each triangle edge's POSED length is compared with its BIND length.
   Edges that stretch > 2× are the tears the eye sees; each tear is attributed to the bone pair its two vertices follow, with their weights.
     hard 0 / 1 weights across the edge with a small bind length  → SKIN WEIGHTING (an abrupt weight boundary)
     both vertices ≈ coincident at bind but different meshes / shells → GEOMETRY / TOPOLOGY (an unwelded seam between shells)
     one vertex with NO bone influence (weights sum 0) → BIND / WEIGHT NORMALISATION
   Also lists, per mesh, the shells (material groups), the vertex counts and the coincident-vertex seams.   node deploy/probe_mesh_stretch.mjs [static_dist] */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') ? path.resolve(argv[0]) : path.join(HERE, 'static_dist'); var OUT = path.join(HERE, 'probe_out', 'intact'); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 640, height: 640, gpu: argv.indexOf('--soft') < 0, unlockFps: true }); var report = { poses: {} };
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
var ANALYSE = "var THREE=P.THREE; var e=P.entity('me'); var g=e.fused.group; var out={ meshes: [] }; g.updateMatrixWorld(true);" +
  "g.traverse(function(m){ if(!m.isSkinnedMesh) return; var geo=m.geometry, pos=geo.attributes.position, si=geo.attributes.skinIndex, sw=geo.attributes.skinWeight, n=pos.count; var bones=m.skeleton.bones; var v=new THREE.Vector3(); var posed=new Float32Array(n*3);" +
  " for(var i=0;i<n;i++){ v.fromBufferAttribute(pos,i); m.applyBoneTransform(i,v); posed[i*3]=v.x; posed[i*3+1]=v.y; posed[i*3+2]=v.z; }" +
  " function dom(i){ var best=-1,bw=-1,sum=0; for(var k=0;k<4;k++){ var w=sw.getComponent(i,k); sum+=w; if(w>bw){bw=w;best=si.getComponent(i,k);} } return { bone: best>=0&&bones[best]?bones[best].name:'?', w:+bw.toFixed(2), sum:+sum.toFixed(2) }; }" +
  " var idx=geo.index; var tris=idx?idx.count/3:n/3; var edges=[]; var seen={};" +
  " function edge(a,b){ var key=a<b?a+'_'+b:b+'_'+a; if(seen[key]) return; seen[key]=1; var bx=pos.getX(a)-pos.getX(b), by=pos.getY(a)-pos.getY(b), bz=pos.getZ(a)-pos.getZ(b); var bl=Math.sqrt(bx*bx+by*by+bz*bz); var px=posed[a*3]-posed[b*3], py=posed[a*3+1]-posed[b*3+1], pz=posed[a*3+2]-posed[b*3+2]; var pl=Math.sqrt(px*px+py*py+pz*pz); var r=bl>1e-6?pl/bl:(pl>1e-3?999:1); if(r>2.0||(bl<1e-5&&pl>0.005)) edges.push({ a:a, b:b, bind:+bl.toFixed(4), posed:+pl.toFixed(4), ratio:+r.toFixed(2), A:dom(a), B:dom(b), pa:[+posed[a*3].toFixed(3),+posed[a*3+1].toFixed(3),+posed[a*3+2].toFixed(3)] }); }" +
  " for(var t=0;t<tris;t++){ var a=idx?idx.getX(t*3):t*3, b=idx?idx.getX(t*3+1):t*3+1, c=idx?idx.getX(t*3+2):t*3+2; edge(a,b); edge(b,c); edge(c,a); }" +
  " var comp=new Int32Array(n); for(var ci=0;ci<n;ci++) comp[ci]=ci; function cf(a){ while(comp[a]!==a){ comp[a]=comp[comp[a]]; a=comp[a]; } return a; } for(var ct=0;ct<tris;ct++){ var ca=idx?idx.getX(ct*3):ct*3, cb=idx?idx.getX(ct*3+1):ct*3+1, cc=idx?idx.getX(ct*3+2):ct*3+2; var ra=cf(ca), rb=cf(cb), rc=cf(cc); if(ra!==rb) comp[ra]=rb; rb=cf(cb); if(rb!==rc) comp[rb]=rc; }" +
  " var cell=0.004; var hash={}; for(var hi=0;hi<n;hi++){ var hk=Math.floor(pos.getX(hi)/cell)+','+Math.floor(pos.getY(hi)/cell)+','+Math.floor(pos.getZ(hi)/cell); (hash[hk]||(hash[hk]=[])).push(hi); }" +
  " var shellPairs=0, open=0, maxSep=0, opens=[]; for(var pi=0;pi<n;pi++){ var px0=pos.getX(pi), py0=pos.getY(pi), pz0=pos.getZ(pi); var bx0=Math.floor(px0/cell), by0=Math.floor(py0/cell), bz0=Math.floor(pz0/cell); var rp=cf(pi); for(var dx=-1;dx<=1;dx++) for(var dy=-1;dy<=1;dy++) for(var dz=-1;dz<=1;dz++){ var lst=hash[(bx0+dx)+','+(by0+dy)+','+(bz0+dz)]; if(!lst) continue; for(var li=0;li<lst.length;li++){ var qj=lst[li]; if(qj<=pi) continue; if(cf(qj)===rp) continue; var bd=Math.hypot(pos.getX(qj)-px0, pos.getY(qj)-py0, pos.getZ(qj)-pz0); if(bd>cell) continue; shellPairs++; var pd=Math.hypot(posed[qj*3]-posed[pi*3], posed[qj*3+1]-posed[pi*3+1], posed[qj*3+2]-posed[pi*3+2]); var sep=pd-bd; if(sep>maxSep) maxSep=sep; if(sep>0.012){ open++; if(opens.length<10) opens.push({ sep:+sep.toFixed(3), a:dom(pi), b:dom(qj), at:[+posed[pi*3].toFixed(3),+posed[pi*3+1].toFixed(3),+posed[pi*3+2].toFixed(3)] }); } } } }" +
  " var nrmA=geo.attributes.normal; var bm=m.skeleton.boneMatrices, binv=m.skeleton.boneInverses; var M=new THREE.Matrix4(), M3=new THREE.Matrix3(), tmpN=new THREE.Vector3(), accN=new THREE.Vector3(); var skN=new Float32Array(n*3); for(var ni=0;ni<n;ni++){ accN.set(0,0,0); for(var kk=0;kk<4;kk++){ var w=sw.getComponent(ni,kk); if(w<1e-6) continue; var bi=si.getComponent(ni,kk); M.fromArray(bm, bi*16); M3.setFromMatrix4(M); tmpN.fromBufferAttribute(nrmA,ni).applyMatrix3(M3).multiplyScalar(w); accN.add(tmpN); } accN.normalize(); skN[ni*3]=accN.x; skN[ni*3+1]=accN.y; skN[ni*3+2]=accN.z; }" +
  " var flipped=0, flippedHands=0, flipBones={}, flipSamples=[], fa=new THREE.Vector3(), fb=new THREE.Vector3(), fc=new THREE.Vector3(), e1=new THREE.Vector3(), e2=new THREE.Vector3(), fn=new THREE.Vector3(); for(var ft=0;ft<tris;ft++){ var ia=idx?idx.getX(ft*3):ft*3, ib=idx?idx.getX(ft*3+1):ft*3+1, ic=idx?idx.getX(ft*3+2):ft*3+2; fa.set(posed[ia*3],posed[ia*3+1],posed[ia*3+2]); fb.set(posed[ib*3],posed[ib*3+1],posed[ib*3+2]); fc.set(posed[ic*3],posed[ic*3+1],posed[ic*3+2]); e1.subVectors(fb,fa); e2.subVectors(fc,fa); fn.crossVectors(e1,e2); if(fn.lengthSq()<1e-14) continue; fn.normalize(); var vn=[(skN[ia*3]+skN[ib*3]+skN[ic*3])/3,(skN[ia*3+1]+skN[ib*3+1]+skN[ic*3+1])/3,(skN[ia*3+2]+skN[ib*3+2]+skN[ic*3+2])/3]; var dotF=fn.x*vn[0]+fn.y*vn[1]+fn.z*vn[2]; if(!window.__dotSign) window.__dotSign={}; var dsk=m.name; if(!window.__dotSign[dsk]) window.__dotSign[dsk]=new Int8Array(tris); var s0=window.__dotSign[dsk]; if(s0[ft]===0) s0[ft]=dotF>=0?1:-1; if(dotF*s0[ft]<-0.2*Math.abs(dotF)&&Math.abs(dotF)>0.2){ var dA=dom(ia); if(/FINGERS|HAND|BROW|CHEEK|JAW/.test(dA.bone)) { flippedHands++; continue; } flipped++; flipBones[dA.bone]=(flipBones[dA.bone]||0)+1; if(flipSamples.length<8) flipSamples.push({ dot:+dotF.toFixed(2), a:dA, at:[+fa.x.toFixed(3),+fa.y.toFixed(3),+fa.z.toFixed(3)] }); } }" +
  " edges.sort(function(x,y){ return y.ratio-x.ratio; }); var pairs={}; edges.forEach(function(ed){ var k=[ed.A.bone,ed.B.bone].sort().join(' ↔ '); var p=pairs[k]||(pairs[k]={ n:0, max:0, hard:0, zero:0, coincident:0, sample:null }); p.n++; p.max=Math.max(p.max,ed.ratio); if(ed.A.w>=0.99&&ed.B.w>=0.99&&ed.A.bone!==ed.B.bone) p.hard++; if(ed.A.sum<0.5||ed.B.sum<0.5) p.zero++; if(ed.bind<1e-5) p.coincident++; if(!p.sample) p.sample=ed; });" +
  " var mats=(Array.isArray(m.material)?m.material:[m.material]).map(function(mm){ return { name: mm.name, side: mm.side, transparent: mm.transparent, opacity: mm.opacity, visible: mm.visible }; });" +
  " var noInfl=0; for(var q=0;q<n;q++){ var s=0; for(var k2=0;k2<4;k2++) s+=sw.getComponent(q,k2); if(s<0.5) noInfl++; }" +
  " out.meshes.push({ _flip_metric_note:'EXPERIMENTAL, NOT A RESULT: the face-normal vs skinned-normal sign test flags a plain trunk tilt (hinge load: 667 CHEST triangles) — the skinned normal path does not match applyBoneTransform; do not read these numbers', flipped_triangles:flipped, flipped_hand_face_triangles:flippedHands, flip_by_bone:flipBones, flip_samples:flipSamples, shell_pairs:shellPairs, shell_pairs_open_gt_12mm:open, shell_max_separation_m:+maxSep.toFixed(3), shell_open_samples:opens, name:m.name, verts:n, tris:tris, groups:(geo.groups||[]).map(function(gr){ return { start:gr.start, count:gr.count, mat:gr.materialIndex }; }), materials:mats, no_influence_verts:noInfl, stretched_edges:edges.length, pairs:pairs, top:edges.slice(0,12) }); });" +
  " return out;";
async function freeze(setup, ms) { await setup(); await sleep(ms); await ev("P.holdPose('me', true); return 1;"); await sleep(120); }
async function release() { await ev("P.holdPose('me', false); return 1;"); await sleep(1500); }
async function castSlot(cat, slot) { await ev("P.send('RULES_SELECT',{category:'" + cat + "',slot:" + slot + "}); return 1;"); await sleep(100); return await ev("return P.send('RULES_CAST',{});"); }
async function analyse(tag) { var r = await ev(ANALYSE); report.poses[tag] = r; r.meshes.forEach(function (m) { var pk = Object.keys(m.pairs).sort(function (a, b) { return m.pairs[b].n - m.pairs[a].n; }).slice(0, 6); console.log('pose', tag, '·', m.name, 'verts', m.verts, 'no-influence', m.no_influence_verts, 'stretched edges', m.stretched_edges, '| GAPS open > 12 mm', m.shell_pairs_open_gt_12mm, 'max', m.shell_max_separation_m, 'm →', pk.map(function (k) { var p = m.pairs[k]; return k + ' n' + p.n + ' max' + p.max + ' hard' + p.hard + ' zero' + p.zero + ' coinc' + p.coincident; }).join(' · ')); }); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(4500); await ev("P.hud.showGuide(false); P.hud.setDev && P.hud.setDev(false); if (P.camFollow) P.camFollow(false); return 1;");
  for (var w0 = 0; w0 < 120; w0++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); }
  await ev("P.send('FIELD_PRACTICE',{on:true}); return 1;"); var dummy = await ev("var r=P.snap().play.rules; return r.others.filter(function(o){return o.id==='FIELD_DUMMY';})[0];");
  await ev("return P.goTo(" + dummy.position.x + ", " + (dummy.position.z + 2.2) + ", undefined, undefined, 40000);"); await sleep(250); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); return 1;"); await sleep(800);
  await ev("return P.send('RULES_LOADOUT',{category:'SPECIAL_MAGIC',slot:1,skill_id:'ATHLETE_OVERHEAD_RELEASE'});");
  await freeze(async function () { }, 300); await analyse('idle'); await release();
  await freeze(async function () { await castSlot('PHYSICAL', 0); }, 300); await analyse('push_load'); await release(); await sleep(1000);
  await freeze(async function () { await castSlot('PHYSICAL', 3); }, 560); await analyse('rotation_release'); await release(); await sleep(1000);
  await freeze(async function () { await castSlot('PHYSICAL', 2); }, 380); await analyse('hinge_load'); await release(); await sleep(1000);
  await freeze(async function () { await castSlot('PHYSICAL', 1); }, 560); await analyse('pull_release'); await release(); await sleep(1000);
  await ev("return P.goTo(" + dummy.position.x + ", " + (dummy.position.z + 4.0) + ", undefined, undefined, 40000);"); await sleep(250); await ev("P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0}); return 1;"); await sleep(800);
  await freeze(async function () { await castSlot('SPECIAL_MAGIC', 1); }, 700); await analyse('overhead_load'); await release(); await sleep(4000);
  await ev("return P.send('RULES_LOADOUT',{category:'SPECIAL_MAGIC',slot:1,skill_id:'ATHLETE_CHEST_FLY_CLAP'});"); await sleep(300);
  await freeze(async function () { await castSlot('SPECIAL_MAGIC', 1); }, 800); await analyse('chestfly_load'); await release(); await sleep(4000);
  await ev("P.send('EMOTE',{emote_id:'DOUBLE_BICEPS'}); return 1;"); await freeze(async function () { }, 900); await analyse('emote_double_biceps'); await release(); await ev("P.send('EMOTE_STOP',{}); return 1;");
  report.errors = pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 5);
} catch (e) { report.exception = String(e && e.stack || e); console.error(e); }
finally { await pg.close(); srv.close(); }
fs.writeFileSync(path.join(OUT, 'mesh_stretch.json'), JSON.stringify(report, null, 1)); console.log('RESULT MESH STRETCH recorded for ' + Object.keys(report.poses).length + ' poses');
