/* M7 REFERENCE-LOCK compact rendered check — one desktop runtime, seven reused views:
   full-world composition, NEXUS/ASCENT/HALO approach + branch/dome join, one live ride and upper realm,
   Phoenix cruise, and true-grip barbell PA_PUSH. This is deliberately not a regression suite. */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = path.join(HERE, 'static_dist'); var OUT = path.join(HERE, 'probe_out', 'm7_reference_lock'); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1440, height: 900, gpu: true, unlockFps: true });
var report = { generated_at: new Date().toISOString(), source: DIST, shots: [], checks: {}, console_errors: [] };
async function ev(src) { return await pg.evaluate("(async function(){var P=window.MAHWORLD_PLAY,H=window.MAHWORLD_STATIC_HOST;" + src + "})()"); }
async function freeCam(from, at, fov) { return await ev("var THREE=P.THREE,r=P.rendererDebug();if(!r.__m7orig){r.__m7orig=r.render.bind(r);r.render=function(sc,cam){r.__m7orig(sc,window.__m7cam||cam);};}var c=new THREE.PerspectiveCamera(" + (fov || 48) + ",1440/900,0.1,2400);c.position.set(" + from.join(',') + ");c.lookAt(" + at.join(',') + ");c.updateProjectionMatrix();window.__m7cam=c;return 1;"); }
async function shot(name) { await ev("document.querySelectorAll('body > *').forEach(function(e){if(e.tagName!=='CANVAS')e.style.visibility='hidden';});return 1;"); await sleep(220); var f = path.join(OUT, name + '.png'); await pg.screenshot(f); report.shots.push(name + '.png'); await ev("document.querySelectorAll('body > *').forEach(function(e){e.style.visibility='';});return 1;"); console.log('SHOT ' + name); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(2500); await ev("P.hud.showGuide(false);return 1;");
  for (var i = 0; i < 240; i++) { var w = await ev("return P.world?P.world().status:null;"); if (w === 'READY' || w === 'FAILED') break; await sleep(500); }
  for (var j = 0; j < 120; j++) { var d = await ev("var q=P.district?P.district():null;return q?q.loaded.length:-1;"); if (d >= 4) break; await sleep(500); } await sleep(1800);
  report.checks.boot = await ev("return {world:P.world(),tree:P.treeAscentInfo&&P.treeAscentInfo(),render:P.renderInfo(),build:window.MAHWORLD_BUILD_INFO||null};");
  await freeCam([-250, 170, -260], [0, 2, 130], 55); await shot('01_five_region_world');
  await freeCam([6, 4.2, 12], [30, 13, 40], 49); await shot('02_tree_approach');
  await freeCam([3, 20, 45], [30, 23, 40], 45); await shot('03_tree_branches_dome');
  await ev("window.__m7cam=null;return P.goTo(26.6,40,undefined,undefined,30000);"); await sleep(600); var before = await ev("var s=P.snap().play;return {flight:s.flight_mahgic.current,cam:P.cam()};"); var up = await ev("return P.send('TRANSIT',{id:'ELEVATOR_UP'});"); await sleep(1800); await ev("P.camLook(0.48,-0.05);return 1;"); var lookDuring = await ev("return P.cam();"); await freeCam([10, 19, 51], [30, 13, 40], 49); await shot('04_ascent_live'); await sleep(3900);
  await freeCam([13, 30, 54], [30, 25, 40], 47); await shot('05_halo_upper_realm');
  var upper = await ev("var s=P.snap().play;return {ground:s.flight.ground,flight:s.flight_mahgic.current,transit:s.transit,prompts:s.prompts,tree:P.treeAscentInfo&&P.treeAscentInfo()};");
  await ev("window.__m7cam=null;return P.goTo(24.4,45.4,undefined,undefined,12000);"); await sleep(500); var talk = await ev("return P.send('NPC_TALK',{npc:'NPC_HALO_GUIDE'});"); await ev("return P.goTo(22.7,40,undefined,undefined,12000);"); var down = await ev("return P.send('TRANSIT',{id:'ELEVATOR_DOWN'});"); await sleep(5700); var lower = await ev("var s=P.snap().play;return {ground:s.flight.ground,flight:s.flight_mahgic.current,transit:s.transit};"); report.checks.ascent = { before: before, up: up, look_during: lookDuring, upper: upper, guide_talk: talk, down: down, lower: lower };
  var anchor = await ev("var r=P.worldLayer().ctx.registry;return r.ecology.species.PHOENIX.habitat.anchors[0];"); await ev("P.devPlay('PLACE',{x:" + 60 + ",z:" + 330 + "});return P.devPlay('WILDLIFE_SUMMON',{species:'PHOENIX'});"); await sleep(2400); var ph = await ev("return (P.snap().play.wildlife||[]).filter(function(x){return x.species==='PHOENIX';})[0]||null;"); if (ph) { await freeCam([ph.position.x + 16, ph.y - 5, ph.position.z + 14], [ph.position.x, ph.y, ph.position.z], 44); await shot('06_phoenix_high_cruise'); } report.checks.phoenix = ph;
  await ev("window.__m7cam=null;P.devPlay('PRACTICE_RESET',{});P.devPlay('PLACE',{x:0,z:-48});return P.send('EQUIP_DISMISS',{});"); await sleep(700); var manifest = await ev("return P.send('EQUIP_MANIFEST',{kind:'BARBELL',count:1});"); await sleep(1800); var barId = await ev("var e=P.snap().play.equipment;var b=(e.manifested||[]).filter(function(x){return x.kind==='BARBELL';})[0];return b&&b.id;"); var pickup = barId ? await ev("return P.send('EQUIP_PICKUP',{id:'" + barId + "'});") : null; await sleep(550); var grip = await ev("return P.worldLayer().gear().debug();"); await ev("P.send('LOCK_TARGET',{aim_id:'FIELD_DUMMY'});P.send('RULES_SELECT',{category:'PHYSICAL',slot:0});return P.send('RULES_CAST',{skill_id:'PA_PUSH'});"); await sleep(150); await freeCam([3.8, 1.9, -53.2], [0, 1.15, -48], 48); await shot('07_barbell_pa_push_load'); await sleep(210); await shot('08_barbell_pa_push_release'); report.checks.barbell = { manifest: manifest, pickup: pickup, id: barId, grip: grip, cast: await ev("return P.snap().play.rules.me.cast;") };
  report.checks.final_render = await ev("return {render:P.renderInfo(),perf:P.perf(),world:P.world()};"); report.console_errors = pg.errors.filter(function (e) { return !/404|favicon/.test(e); });
} catch (e) { report.fatal = String(e && e.stack || e); console.error(report.fatal); }
finally { fs.writeFileSync(path.join(OUT, 'report.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT M7 probe shots ' + report.shots.length + ' errors ' + report.console_errors.length + (report.fatal ? ' FATAL' : ' OK') + ' → ' + OUT); process.exit(report.fatal || report.console_errors.length ? 1 : 0);
