/* CONVERGENCE PASS 2b — PRESENTATION PIVOT PROBE (owner addendum 2026-09-17), in the real page.
   1 stable readable scale: his screen-space box height is a stable fraction of the image height per orientation (target band from the addendum text:
     roughly a quarter to a third in landscape; portrait keeps him readable) — no continuous zoom / size pumping while walking straight.
   2 independent viewpoint: a held movement gesture (stick / W) is NOT steered by a camera orbit performed during it; no feedback spin.
   3 world depth: the far world exists (far massifs, mid walkways, haze plain), draws in ≤ 3 calls, sits inside the camera far plane and outside the room;
     a wide environmental still + a gameplay still are saved for the near / mid / far comparison.
   node deploy/probe_pivot.mjs [static_dist] [desktop|portrait|landscape]   Touch = EMULATED. */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var argv = process.argv.slice(2); var DIST = argv[0] && !argv[0].startsWith('--') && !/^(desktop|portrait|landscape)$/.test(argv[0]) ? path.resolve(argv[0]) : path.join(HERE, 'static_dist');
var MODE = argv.filter(function (a) { return /^(portrait|desktop|landscape)$/.test(a); })[0] || 'desktop'; var OUT = path.join(HERE, 'probe_out', 'pivot'); fs.mkdirSync(OUT, { recursive: true }); var TOUCH = MODE !== 'desktop'; var VP = MODE === 'portrait' ? [390, 844] : (MODE === 'landscape' ? [844, 390] : [1200, 750]);
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true, unlockFps: true, mobile: TOUCH }); var pass = 0, fail = 0, lines = [];
function ok(id, cond, detail) { (cond ? pass++ : fail++); var l = (cond ? 'PASS ' : 'FAIL ') + id + (detail !== undefined ? ' — ' + (typeof detail === 'string' ? detail : JSON.stringify(detail)) : ''); lines.push(l); console.log(l.slice(0, 700)); }
async function ev(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function ptr(type, el, id, x, y) { await pg.evaluate("(function(){ var t=document.getElementById('" + el + "'); if(!t) return 0; var e=new PointerEvent('" + type + "',{pointerId:" + id + ",pointerType:'touch',isPrimary:" + (id === 1) + ",clientX:" + x + ",clientY:" + y + ",bubbles:true,cancelable:true}); t.dispatchEvent(e); })(); 1"); }
async function rect(id) { return await pg.evaluate("(function(){ var e=document.getElementById('" + id + "'); if(!e) return null; var r=e.getBoundingClientRect(); return {x:r.left,y:r.top,w:r.width,h:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2}; })()"); }
async function vw() { return await pg.evaluate("({w:innerWidth,h:innerHeight})"); }
async function box() { return await ev("var b=P.screenBox(); var c=P.camState(); var p=P.snap().play; return {frac:b?(b.bottom-b.top)/innerHeight:null, wfrac:b?(b.right-b.left)/innerWidth:null, top:b?b.top/innerHeight:null, applied:c.applied, dist:c.dist, mode:c.mode, yaw:c.yaw, pos:[+p.position.x.toFixed(2),+p.position.z.toFixed(2)], facing:p.facing};"); }
async function lookDrag(dx, dy, ms) { var v = await vw(); var x = v.w * 0.72, y = v.h * 0.45; await ptr('pointerdown', 'tc-world', 2, x, y); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await ptr('pointermove', 'tc-world', 2, x + dx * i / n, y + dy * i / n); await sleep(40); } await ptr('pointerup', 'tc-world', 2, x + dx, y + dy); }
async function mouseDrag(dx, dy, ms) { var v = await vw(); var x = v.w * 0.6, y = v.h * 0.5; await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + x + ",clientY:" + y + ",bubbles:true})); 1"); var n = Math.max(4, Math.round(ms / 40)); for (var i = 1; i <= n; i++) { await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + (x + dx * i / n) + ",clientY:" + (y + dy * i / n) + ",bubbles:true})); 1"); await sleep(40); } await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + (x + dx) + ",clientY:" + (y + dy) + ",bubbles:true})); 1"); }
var report = { mode: MODE, viewport: VP, touch_emulated: TOUCH, checks: lines, samples: {} };
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1' + (TOUCH ? '&touch=1' : '')); await waitForGame(pg, 120000); await sleep(6000); await ev("P.hud.showGuide(false); return 1;");
  for (var w = 0; w < 120; w++) { var dl = await ev("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); } await sleep(800);
  await ev("return P.goTo(20, 30, undefined, undefined, 60000);"); await sleep(600); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1500);
  /* ── 1 stable readable scale ── */
  var b0 = await box(); var band = MODE === 'portrait' ? [0.20, 0.36] : [0.22, 0.36];
  ok('S1 idle framing: his screen box is ' + (b0.frac * 100).toFixed(1) + ' % of the image height (band ' + band[0] * 100 + '–' + band[1] * 100 + ' %, addendum: roughly a quarter to a third; a composition target, not a mandated percentage)', b0.frac >= band[0] && b0.frac <= band[1], { frac: +b0.frac.toFixed(3), wfrac: +b0.wfrac.toFixed(3), dist: +b0.dist.toFixed(2), applied: +b0.applied.toFixed(2) });
  ok('S1b he is anchored in the lower-middle band (box top between 25 % and 70 % of the height), never pinned to an edge', b0.top >= 0.25 && b0.top + b0.frac <= 0.97 && b0.top <= 0.70, { top: +b0.top.toFixed(3), bottom: +(b0.top + b0.frac).toFixed(3) });
  var walk = []; if (TOUCH) { var sz = await rect('tc-stickzone'); var sx = sz.x + sz.w * 0.5, sy = sz.y + sz.h * 0.55; await ptr('pointerdown', 'tc-stickzone', 1, sx, sy); for (var i = 1; i <= 4; i++) { await ptr('pointermove', 'tc-stickzone', 1, sx, sy - 30 * i); await sleep(30); } for (var k = 0; k < 25; k++) { walk.push(await box()); await sleep(100); } await ptr('pointerup', 'tc-stickzone', 1, sx, sy - 120); } else { await key('KeyW', true); for (var k2 = 0; k2 < 25; k2++) { walk.push(await box()); await sleep(100); } await key('KeyW', false); }
  var fr = walk.map(function (x) { return x.frac; }).filter(function (x) { return x !== null; }); var fMin = Math.min.apply(null, fr), fMax = Math.max.apply(null, fr); var pump = (fMax - fMin) / Math.max(1e-6, (fMax + fMin) / 2); var dd = walk.map(function (x) { return x.dist; }), aa = walk.map(function (x) { return x.applied; }); var dVar = (Math.max.apply(null, dd) - Math.min.apply(null, dd)) / Math.max(1e-6, dd[0]); var aVar = (Math.max.apply(null, aa) - Math.min.apply(null, aa)) / Math.max(1e-6, aa[0]); report.samples.walk_frac = fr; report.samples.walk_dist = dd;
  ok('S2 no size pumping while walking straight 2.5 s: the preferred boom is constant (Δ ≤ 1 %), the applied boom does not breathe (Δ ≤ 3 %), and the box height varies only with the pose (≤ 25 %)', fr.length > 15 && dVar <= 0.01 && aVar <= 0.03 && pump <= 0.25, { box_min: +fMin.toFixed(3), box_max: +fMax.toFixed(3), box_variation: +(pump * 100).toFixed(1) + ' %', preferred_variation: +(dVar * 100).toFixed(2) + ' %', applied_variation: +(aVar * 100).toFixed(2) + ' %' });
  await sleep(1500);
  /* ── 2 independent viewpoint: a held movement gesture is not steered by an orbit performed during it ── */
  await ev("return P.goTo(-30, -20, undefined, undefined, 60000);"); await sleep(400); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:3.1416});"); await sleep(1500); await ev("return P.camReset('probe');"); await sleep(800);   /* open plaza, facing +z: room to travel straight for 2 s */
  var cA = await box(); var travel0 = cA.pos; if (TOUCH) { var sz2 = await rect('tc-stickzone'); var sx2 = sz2.x + sz2.w * 0.5, sy2 = sz2.y + sz2.h * 0.55; await ptr('pointerdown', 'tc-stickzone', 1, sx2, sy2); for (var i2 = 1; i2 <= 4; i2++) { await ptr('pointermove', 'tc-stickzone', 1, sx2, sy2 - 30 * i2); await sleep(30); } } else await key('KeyW', true);
  await sleep(900); var cB = await box(); var dir0 = Math.atan2(cB.pos[0] - travel0[0], -(cB.pos[1] - travel0[1]));   /* travel heading before the orbit (host convention: forward = −z) */
  if (TOUCH) await lookDrag(-220, 0, 500); else await mouseDrag(-320, 0, 500); await sleep(900); var cC = await box(); var dir1 = Math.atan2(cC.pos[0] - cB.pos[0], -(cC.pos[1] - cB.pos[1])); var dYaw = Math.abs(((cC.yaw - cB.yaw) * 180 / Math.PI + 540) % 360 - 180); var dDir = Math.abs(((dir1 - dir0) * 180 / Math.PI + 540) % 360 - 180);
  if (TOUCH) await ptr('pointerup', 'tc-stickzone', 1, sx2, sy2 - 120); else await key('KeyW', false); await sleep(600);
  var moved1 = Math.hypot(cB.pos[0] - travel0[0], cB.pos[1] - travel0[1]), moved2 = Math.hypot(cC.pos[0] - cB.pos[0], cC.pos[1] - cB.pos[1]);
  ok('V1 a camera orbit of ' + dYaw.toFixed(0) + '° performed DURING a held forward gesture does not steer the travel (heading change ' + dDir.toFixed(1) + '° ≤ 8° over ' + moved2.toFixed(1) + ' m): the movement frame stays latched, no feedback spin', dYaw > 25 && dDir <= 8 && moved1 > 1 && moved2 > 1, { orbit_deg: +dYaw.toFixed(1), travel_change_deg: +dDir.toFixed(1), moved_before_m: +moved1.toFixed(2), moved_after_m: +moved2.toFixed(2), before: cB.pos, after: cC.pos, mode: cC.mode });
  await ev("return P.camReset('probe');"); await sleep(900);
  /* ── 2b connected turn: a 180° turn (S = walk backwards → the body turns around) accelerates in and eases out: no snap, no overshoot, settles in 0.25–0.7 s ── */
  await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:3.1416});"); await sleep(1500); await pg.evaluate("window.__turn=[]; window.__turnOn=true; (function loop(t){ if(!window.__turnOn) return; requestAnimationFrame(loop); var c=window.MAHWORLD_PLAY.camState(); window.__turn.push([t, c.behind]); })(0); 1");
  if (TOUCH) { var sz3 = await rect('tc-stickzone'); var sx3 = sz3.x + sz3.w * 0.5, sy3 = sz3.y + sz3.h * 0.45; await ptr('pointerdown', 'tc-stickzone', 1, sx3, sy3); for (var i3 = 1; i3 <= 4; i3++) { await ptr('pointermove', 'tc-stickzone', 1, sx3, sy3 + 30 * i3); await sleep(30); } await sleep(1300); await ptr('pointerup', 'tc-stickzone', 1, sx3, sy3 + 120); } else { await key('KeyS', true); await sleep(1300); await key('KeyS', false); }
  var tr = await pg.evaluate("window.__turnOn=false; window.__turn"); var y0 = tr[0][1]; var un = []; var acc = 0, prev = y0; tr.forEach(function (r) { var d = Math.atan2(Math.sin(r[1] - prev), Math.cos(r[1] - prev)); acc += d; prev = r[1]; un.push([r[0] - tr[0][0], acc]); });
  var total = un[un.length - 1][1]; var sign = total >= 0 ? 1 : -1; var t5 = null, t95 = null, tEnd = null, overshoot = 0, maxRate = 0; for (var q = 1; q < un.length; q++) { var f = un[q][1] * sign / Math.max(1e-6, Math.abs(total)); if (t5 === null && f >= 0.05) t5 = un[q][0]; if (t95 === null && f >= 0.95) t95 = un[q][0]; if (f > 1) overshoot = Math.max(overshoot, (f - 1) * Math.abs(total)); var dtq = (un[q][0] - un[q - 1][0]) / 1000; if (dtq > 0) maxRate = Math.max(maxRate, Math.abs(un[q][1] - un[q - 1][1]) / dtq); }
  var turnDeg = Math.abs(total) * 180 / Math.PI; var dur = t5 !== null && t95 !== null ? (t95 - t5) / 1000 : null; report.samples.turn = { deg: +turnDeg.toFixed(1), t5_ms: t5, t95_ms: t95, overshoot_deg: +(overshoot * 180 / Math.PI).toFixed(2), max_rate_dps: +(maxRate * 180 / Math.PI).toFixed(0) };
  ok('M1 connected turn: a ' + turnDeg.toFixed(0) + '° turn-around takes ' + (dur !== null ? dur.toFixed(2) : '?') + ' s from 5 % to 95 % (0.20–0.70 s: neither a snap nor sluggish), overshoot ≤ 3°, peak rate ≤ 780 °/s (spring-shaped, below the 800 cap)', turnDeg > 150 && dur !== null && dur >= 0.2 && dur <= 0.7 && overshoot * 180 / Math.PI <= 3 && maxRate * 180 / Math.PI <= 780, report.samples.turn);
  await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1200); await ev("return P.camReset('probe');"); await sleep(900);
  /* ── 3 world depth ── */
  var camFar = await ev("return P.cameraDebug ? P.cameraDebug().far : null;"); var fw = await ev("var s=P.sceneDebug(); var g=s.getObjectByName('MAHWORLD_FAR_WORLD'); if(!g) return null; var names=[]; g.traverse(function(o){ if(o.isMesh) names.push(o.name); }); var info=g.userData.info||null; var far=g.getObjectByName('FAR_MASSIFS'); var bs=far&&far.geometry.boundingSphere; return {names:names, info:info, far_radius:bs?+bs.radius.toFixed(0):null, far_center:bs?[+bs.center.x.toFixed(0),+bs.center.z.toFixed(0)]:null};");
  ok('W1 the far world exists: far massifs + mid walkways + haze plain, 3 meshes (≤ 3 draw calls); the far geometry\'s bounding sphere (centre near the origin) sits ≥ 620 m out and inside the camera far plane even from the room\'s far corners (+300 m)', !!fw && fw.names.length === 3 && fw.names.indexOf('FAR_MASSIFS') >= 0 && fw.names.indexOf('MID_WALKWAYS') >= 0 && fw.names.indexOf('HAZE_PLAIN') >= 0 && fw.far_radius >= 620 && fw.far_radius + 300 <= (camFar || 1400) && Math.hypot(fw.far_center[0], fw.far_center[1]) < 60, Object.assign({ camera_far: camFar }, fw));
  var dome = await ev("var d=P.fieldDebug?P.fieldDebug():null; return d?{dome:d.dome, sky_children:d.sky_children, fog:d.fog}:null;");
  var skyAt = await ev("var s=P.sceneDebug(); var g=s.getObjectByName('MAHWORLD_SKY'); var p=P.snap().play.position; return g?{dx:+(g.position.x-p.x).toFixed(1), dz:+(g.position.z-p.z).toFixed(1)}:null;"); ok('W2 the sky rides with the viewer (dome centre within 12 m of him) so it never clips off-centre; the fog leaves the far layer readable (far / haze materials ignore fog)', !!dome && !!skyAt && Math.abs(skyAt.dx) < 12 && Math.abs(skyAt.dz) < 12 && (!dome.fog || dome.fog.far <= (camFar || 1400)), { dome: dome, sky_offset: skyAt, camera_far: camFar });
  /* W3 far corner: from (240, −240) looking back across the whole district (the room's far diagonal) the sky must not clip — sample the sky column above the horizon */
  await ev("return P.goTo(240, -240, undefined, undefined, 60000);"); await sleep(400); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:-2.356});"); await sleep(1500); if (TOUCH) await lookDrag(0, -150, 500); else await mouseDrag(0, -220, 500); await sleep(700);
  var sky = await ev("P.renderOnce(); var c=document.getElementById('view'); var gl=c.getContext('webgl2')||c.getContext('webgl'); if(!gl) return null; var w=gl.drawingBufferWidth, h=gl.drawingBufferHeight; var px=new Uint8Array(4); var out=[]; [0.05,0.15,0.25,0.35].forEach(function(f){ gl.readPixels(Math.floor(w*0.5), Math.floor(h*(1-f)), 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, px); out.push([px[0],px[1],px[2]]); }); return out;");   /* read right after a synchronous render (the drawing buffer is not preserved between frames) */
  var flatBg = sky && sky.every(function (c) { return Math.abs(c[0] - 0x9f) < 4 && Math.abs(c[1] - 0xc4) < 4 && Math.abs(c[2] - 0xe4) < 4; }); var black = sky && sky.every(function (c) { return c[0] + c[1] + c[2] < 12; });
  ok('W3 from the room\'s far corner looking back across the district the sky column is a real gradient (never the flat clear colour #9fc4e4 = a clipped dome)', sky !== null && !flatBg && !black && new Set(sky.map(function (c) { return c.join(','); })).size >= 2, { samples: sky }); await pg.screenshot(path.join(OUT, 'pivot_' + MODE + '_far_corner_manual_look.png')); await ev("return P.camReset('probe');"); await sleep(900);
  /* stills: a gameplay view and a wide environmental view (a labelled manual look up toward the horizon, then reset) */
  await pg.screenshot(path.join(OUT, 'pivot_' + MODE + '_gameplay.png'));
  /* the wide environmental view: at the plaza's south edge facing out (−z), a labelled MANUAL LOOK that lowers the camera toward the horizon (drag up) — then a reset */
  await ev("return P.goTo(0, -48, undefined, undefined, 60000);"); await sleep(400); await ev("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1500); await pg.screenshot(path.join(OUT, 'pivot_' + MODE + '_gameplay_south.png'));
  if (TOUCH) await lookDrag(0, -150, 500); else await mouseDrag(0, -220, 500); await sleep(800); await pg.screenshot(path.join(OUT, 'pivot_' + MODE + '_wide_manual_look.png')); await ev("return P.camReset('probe');"); await sleep(900);
  ok('Z zero page / console errors', pg.errors.filter(function (x) { return !/404/.test(x); }).length === 0, pg.errors.slice(0, 3));
} catch (e) { ok('X probe completed without an exception', false, String(e && e.stack || e)); }
finally { await pg.close(); srv.close(); }
report.pass = pass; report.fail = fail; fs.writeFileSync(path.join(OUT, 'pivot_' + MODE + '.json'), JSON.stringify(report, null, 1));
console.log('\nRESULT pivot ' + MODE + ': ' + pass + ' passed, ' + fail + ' failed'); process.exit(fail ? 1 : 0);
