/* CONVERGENCE PASS 2b — PRESENTATION PIVOT CAPTURE (matched current / candidate).
   One scripted slice, identical inputs on both builds: idle → turn → short walk → stop → settle → manual orbit / release (persists) → obstacle recovery
   (walk with the facade behind him) → explicit reset → brief flight / landing. Real key / mouse events; the gameplay camera is never overridden.
   Per-frame telemetry sampled in-page: his screen-space box (height fraction), camera preferred vs applied distance, pitch bias, mode, frame interval.
   node deploy/record_pivot.mjs <tag> [static_dist] [WxH]   → deploy/review/<tag>/pivot_<tag>.webm + marks.json + telemetry.json + stills */
import path from 'node:path'; import fs from 'node:fs'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var tag = process.argv[2] || 'pivot'; var DIST = process.argv[3] ? path.resolve(process.argv[3]) : path.join(HERE, 'static_dist'); var VP = (process.argv[4] || '1120x700').split('x').map(Number); var OUT = path.join(HERE, 'review', tag); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: VP[0], height: VP[1], gpu: true }); var frames = [], marks = [], t0 = 0;
function mark(l) { var tt = (performance.now() - t0) / 1000; marks.push({ t: +tt.toFixed(2), label: l }); console.log(tt.toFixed(1) + 's  ' + l); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(50); await key(code, false); }
async function hold(code, ms) { await key(code, true); await sleep(ms); await key(code, false); }
async function P(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function cap(text, sub) { await pg.evaluate("(function(){ var c=document.getElementById('pvcap'); c.innerHTML=" + JSON.stringify('<b>' + text + '</b>' + (sub ? '<span>' + sub + '</span>' : '')) + "; c.style.opacity=1; })(); 1"); mark(text); }
var dragPos = null; async function lookStart() { var vw = await P("return {w:innerWidth,h:innerHeight};"); dragPos = { x: vw.w * 0.55, y: vw.h * 0.5 }; await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + dragPos.x + ",clientY:" + dragPos.y + ",bubbles:true})); 1"); }
async function lookBy(dx, dy, ms) { var n = Math.max(6, Math.round(ms / 33)); for (var i = 1; i <= n; i++) { var x = dragPos.x + dx * i / n, y = dragPos.y + dy * i / n; await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + x + ",clientY:" + y + ",bubbles:true})); 1"); await sleep(33); } dragPos = { x: dragPos.x + dx, y: dragPos.y + dy }; }
async function lookEnd() { await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + dragPos.x + ",clientY:" + dragPos.y + ",bubbles:true})); 1"); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(6000); await P("P.hud.showGuide(false); return 1;");
  for (var w = 0; w < 120; w++) { var dl = await P("var d=P.district?P.district():null; return d?d.loaded.length:-1;"); if (dl >= 4) break; await sleep(500); } await sleep(1500);
  await pg.evaluate("(function(){ var s=document.createElement('style'); s.textContent='#pvcap{position:fixed;left:50%;top:112px;transform:translateX(-50%);max-width:62vw;background:rgba(5,8,15,.72);color:#eef4ff;font:600 18px/1.2 system-ui,sans-serif;padding:8px 14px;border-radius:10px;z-index:99999;opacity:0;transition:opacity .3s;pointer-events:none;text-align:center}#pvcap span{display:block;font:400 13px/1.3 system-ui,sans-serif;color:#cfd8e6;margin-top:3px}#dev{display:none!important}'; document.head.appendChild(s); var c=document.createElement('div'); c.id='pvcap'; document.body.appendChild(c); })(); 1");
  /* in-page telemetry sampler: every frame → box height fraction, boom, bias, mode, interval */
  await pg.evaluate("window.__pv={rows:[],phase:'start'}; (function loop(t){ requestAnimationFrame(loop); try { var P=window.MAHWORLD_PLAY; var c=P.camState(); var b=P.screenBox(); var p=P.snap().play; var prev=window.__pv.last||t; window.__pv.last=t; window.__pv.rows.push([window.__pv.phase, +((t)/1000).toFixed(3), +(t-prev).toFixed(1), b?+( (b.bottom-b.top)/innerHeight ).toFixed(3):null, +c.applied.toFixed(2), +c.dist.toFixed(2), +(c.pitch_bias||0).toFixed(2), c.mode||c.state, c.inside?1:0, +p.position.x.toFixed(2), +p.position.z.toFixed(2), +p.flight.altitude.toFixed(2)]); } catch(e){} })(0); 1");
  async function phase(p) { await pg.evaluate("window.__pv.phase=" + JSON.stringify(p) + "; 1"); }
  await P("return P.goTo(20, 30, undefined, undefined, 60000);"); await sleep(600); await P("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(1200);
  pg.on('Page.screencastFrame', function (p) { frames.push({ t: performance.now() - t0, data: p.data }); pg.cmd('Page.screencastFrameAck', { sessionId: p.sessionId }).catch(function () { }); });
  t0 = performance.now(); await pg.cmd('Page.startScreencast', { format: 'jpeg', quality: 72, maxWidth: VP[0], maxHeight: VP[1], everyNthFrame: 2 });
  await phase('idle'); await cap('1 · IDLE', 'rear follow, no input — build: ' + tag); await sleep(3000);
  await phase('turn'); await cap('2 · TURN', 'A tap then D tap: the body turns, the camera follows the displayed facing'); await hold('KeyA', 450); await sleep(900); await hold('KeyD', 450); await sleep(1200);
  await phase('walk'); await cap('3 · SHORT WALK', 'W held 2.5 s'); await hold('KeyW', 2500);
  await phase('stop'); await cap('4 · STOP → SETTLE', 'release: the body settles, the camera settles'); await sleep(3000);
  await phase('orbit'); await cap('5 · MANUAL ORBIT (mouse drag)', 'deliberate drag past the tap threshold'); await lookStart(); await lookBy(-300, 40, 1400); await sleep(400);
  await phase('release'); await cap('6 · RELEASE', 'O1: the orbit persists — no automatic return; W: he walks, the view stays'); await lookEnd(); await sleep(1500); await hold('KeyW', 1500); await sleep(1500);
  await phase('reset'); var hasReset = await P("return !!(P.camReset);"); await cap('7 · EXPLICIT RESET (Backspace)', hasReset ? 'smooth glide back behind him (0.5 s), rear follow resumes' : 'NO reset control exists on this build (owner round: the camera auto-returned) — Backspace is a no-op here'); await tap('Backspace'); await sleep(2500);
  await phase('obstacle'); await cap('8 · OBSTACLE RECOVERY', 'walking north into the temple, back to the wall: the boom pitches up / shortens, never sideways, never inside (owner-round build: its invisible S11-size collider stops him ~10 m before the visible wall — F09)'); await P("return P.goTo(0, 120, undefined, undefined, 60000);"); await P("return P.send('MOVE',{forward:-1,strafe:0,run:false,yaw:0});"); await sleep(9000); await P("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:0});"); await sleep(2500);
  await cap('8b · WALK CLEAR', 'the boom returns to its preferred distance'); await hold('KeyW', 2200); await sleep(2000);
  await phase('flight'); await cap('9 · BRIEF FLIGHT (Space held) → HOLD → LAND (F)', 'our own flight rules: hold = climb, release = altitude held, F = deliberate landing'); await key('Space', true); await sleep(1800); await key('Space', false); await sleep(2200); await hold('KeyW', 1500); await sleep(800); await tap('KeyF'); await sleep(4500);
  await phase('end'); await cap('END', 'touch: not exercised in this capture (desktop inputs) · iPhone: NOT tested'); await sleep(1500);
  await pg.cmd('Page.stopScreencast'); var dur = frames.length ? (frames[frames.length - 1].t - frames[0].t) / 1000 : 0; console.log('frames', frames.length, 'seconds', dur.toFixed(1));
  var tele = await pg.evaluate("window.__pv.rows"); var byPhase = {}; tele.forEach(function (r) { var b = byPhase[r[0]] = byPhase[r[0]] || { n: 0, frac: [], applied: [], dist: [], bias: [], inside: 0, dt: [] }; b.n++; if (r[3] !== null) b.frac.push(r[3]); b.applied.push(r[4]); b.dist.push(r[5]); b.bias.push(r[6]); b.inside += r[8]; b.dt.push(r[2]); });
  function pct(a, q) { if (!a.length) return null; var s = a.slice().sort(function (x, y) { return x - y; }); return s[Math.min(s.length - 1, Math.floor(q * (s.length - 1)))]; }
  var summary = {}; Object.keys(byPhase).forEach(function (k) { var b = byPhase[k]; summary[k] = { frames: b.n, box_height_frac: { p50: pct(b.frac, 0.5), min: pct(b.frac, 0), max: pct(b.frac, 1) }, applied_m: { min: pct(b.applied, 0), p50: pct(b.applied, 0.5) }, preferred_m: pct(b.dist, 0.5), pitch_bias_max: pct(b.bias, 1), inside_frames: b.inside, interval_ms: { p50: pct(b.dt, 0.5), p95: pct(b.dt, 0.95), p99: pct(b.dt, 0.99) } }; });
  fs.writeFileSync(path.join(OUT, 'telemetry.json'), JSON.stringify({ tag: tag, build: DIST, viewport: VP, summary: summary, rows: tele }, null, 1)); console.log(JSON.stringify(summary));
  fs.writeFileSync(path.join(OUT, 'marks.json'), JSON.stringify({ marks: marks, frames: frames.length, seconds: +dur.toFixed(1), build: DIST, viewport: VP }, null, 1));
  marks.forEach(function (mk, i) { var fi = frames.findIndex(function (f) { return f.t / 1000 >= mk.t + 1.4; }); if (fi >= 0) fs.writeFileSync(path.join(OUT, 'still_' + String(i).padStart(2, '0') + '_' + mk.label.replace(/[^a-z0-9]+/gi, '_').slice(0, 40) + '.jpg'), Buffer.from(frames[fi].data, 'base64')); });
  var t2 = await pg.cmd('Target.createTarget', { url: 'about:blank' }); var list = await (await fetch('http://127.0.0.1:' + pg.port + '/json/list')).json(); var helper = list.filter(function (x) { return x.id === t2.targetId; })[0]; var ws = new WebSocket(helper.webSocketDebuggerUrl); await new Promise(function (r, j) { ws.onopen = r; ws.onerror = j; });
  var mid = 0, pend = {}; ws.onmessage = function (m) { var d = JSON.parse(typeof m.data === 'string' ? m.data : String(m.data)); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id]; } }; function c2(method, params) { return new Promise(function (r, j) { var id = ++mid; pend[id] = function (d) { d.error ? j(new Error(JSON.stringify(d.error))) : r(d.result); }; ws.send(JSON.stringify({ id: id, method: method, params: params || {} })); }); }
  await c2('Runtime.enable'); var ev2 = async function (expr) { var r = await c2('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error('eval2: ' + JSON.stringify(r.exceptionDetails).slice(0, 300)); return r.result.value; };
  await ev2('window.__F = []; window.__T = []; 1'); for (var c0 = 0; c0 < frames.length; c0 += 40) { var chunk = frames.slice(c0, c0 + 40); await ev2('(function(){var d=' + JSON.stringify(chunk.map(function (f) { return f.data; })) + ';var t=' + JSON.stringify(chunk.map(function (f) { return Math.round(f.t - frames[0].t); })) + ';for(var i=0;i<d.length;i++){window.__F.push(d[i]);window.__T.push(t[i]);} return window.__F.length;})()'); }
  var webm = await ev2('(async function(){ var F=window.__F, T=window.__T; var load=function(i){ return new Promise(function(res){ var im=new Image(); im.onload=function(){res(im)}; im.onerror=function(){res(null)}; im.src="data:image/jpeg;base64,"+F[i]; }); }; var first=await load(0); var w=first.width, h=first.height; var cv=document.createElement("canvas"); cv.width=w; cv.height=h; document.body.appendChild(cv); var ctx=cv.getContext("2d"); ctx.drawImage(first,0,0); var stream=cv.captureStream(30); var mime=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].filter(function(m){return MediaRecorder.isTypeSupported(m)})[0]; var rec=new MediaRecorder(stream,{mimeType:mime, videoBitsPerSecond: 3500000}); var chunks=[]; rec.ondataavailable=function(e){ if(e.data && e.data.size) chunks.push(e.data); }; var done=new Promise(function(res){ rec.onstop=res; }); rec.start(250); var start=performance.now(); for (var i=1;i<F.length;i++){ var im=await load(i); F[i]=null; while(performance.now()-start<T[i]) await new Promise(function(r){ requestAnimationFrame(r); }); if (im) ctx.drawImage(im,0,0); } await new Promise(function(r){ setTimeout(r,300); }); rec.stop(); await done; var blob=new Blob(chunks,{type:mime}); var b64=await new Promise(function(res){ var fr=new FileReader(); fr.onload=function(){res(fr.result.split(",")[1])}; fr.readAsDataURL(blob); }); return {mime:mime, bytes:blob.size, b64:b64}; })()');
  var vpath = path.join(OUT, 'pivot_' + tag + '.webm'); fs.writeFileSync(vpath, Buffer.from(webm.b64, 'base64')); console.log('VIDEO FILE ' + vpath + ' ' + webm.bytes + ' bytes ' + dur.toFixed(1) + 's'); ws.close();
  console.log('errors', pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 6));
} finally { await pg.close(); srv.close(); }
