/* S11 DISTRICT REVIEW (~80 s): skyline arrival, each landmark + sign, walk/dash/fly into facades (blocked), fly above, land on the gym roof, perch,
   tower deck with the gap, dark platinum floor, tree transit. node deploy/record_district.mjs [tag] -> deploy/review/<tag>/mahworld_district_review.webm */
import path from 'node:path'; import fs from 'node:fs'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = path.join(HERE, 'static_dist'); var tag = process.argv[2] || 'district'; var OUT = path.join(HERE, 'review', tag); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 960, height: 720, gpu: true }); var frames = [], marks = [], t0 = 0;
var pausedTotalRef = function () { return 0; }; function mark(l) { var tt = (performance.now() - t0 - pausedTotalRef()) / 1000; marks.push({ t: +tt.toFixed(2), label: l }); console.log(tt.toFixed(1) + 's  ' + l); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(40); await key(code, false); }
async function cam(y, p, d, pv) { await pg.evaluate("window.MAHWORLD_PLAY.cam(" + y + "," + p + "," + d + "," + (pv === undefined ? 'null' : pv) + ")"); }
async function yawOf() { return await pg.evaluate("window.MAHWORLD_PLAY.mePose().root_yaw"); }
async function P(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 90000); await sleep(7000);
  await P("P.hud.showGuide(false); return 1;"); var hide = function () { return P("document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;"); }; var show = function () { return P("document.querySelectorAll('body > *').forEach(function(e){ e.style.visibility=''; }); return 1;"); };
  var paused = false, pausedAt = 0, pausedTotal = 0; pausedTotalRef = function () { return pausedTotal; }; async function pause() { if (paused) return; paused = true; pausedAt = performance.now(); await pg.cmd('Page.stopScreencast'); } async function resume() { if (!paused) return; pausedTotal += performance.now() - pausedAt; paused = false; await pg.cmd('Page.startScreencast', { format: 'jpeg', quality: 70, maxWidth: 960, maxHeight: 720, everyNthFrame: 2 }); }
  pg.on('Page.screencastFrame', function (p) { if (paused) return; frames.push({ t: performance.now() - t0 - pausedTotal, data: p.data }); pg.cmd('Page.screencastFrameAck', { sessionId: p.sessionId }).catch(function () { }); });
  var fly = function (op) { return P("return P.send('FLIGHT',{op:'" + op + "'})"); }; var pos = function () { return P("return JSON.stringify(P.snap().play.position)"); }; var alt = function () { return P("return P.snap().play.flight.altitude"); }; var ground = function () { return P("return P.snap().play.flight.ground"); };
  var move = function (f, s, run, yaw) { return P("P.send('MOVE',{forward:" + f + ",strafe:" + s + ",run:" + (run ? 'true' : 'false') + ",yaw:" + yaw + "}); return 1;"); }; var stop = function () { return P("P.send('MOVE',{forward:0,strafe:0}); return 1;"); };
  t0 = performance.now(); await pg.cmd('Page.startScreencast', { format: 'jpeg', quality: 70, maxWidth: 960, maxHeight: 720, everyNthFrame: 2 });
  /* 1 arrival */
  await P("P.camFollow(true); return 1;"); await cam(Math.PI, 0.10, 9, 1.8); mark('1 ARRIVAL: from the spawn toward the GOLD TEMPLE (80 m, centre), MAH GYM (72) left, BLUE TOWER (72) right - player for scale'); await key('KeyW', true); await key('ShiftLeft', true); await sleep(7000); await key('ShiftLeft', false); await key('KeyW', false); await sleep(600);
  await P("P.camFollow(false); return 1;"); await hide();
  /* 2-5 each landmark */
  await pause(); await P("return P.goTo(0, 112)"); await resume(); await cam(3.14, 0.16, 62, 22); mark('2 GOLD TEMPLE - central, tallest (80 m); front toward the plaza approach'); await sleep(3200);
  await pause(); await P("return P.goTo(-60, 110)"); await resume(); await cam(1.57, 0.15, 80, 25); mark('3 MAH GYM - 72 m, sign readable, natural width kept (uniform scale)'); await sleep(3200);
  await pause(); await P("return P.goTo(60, 110)"); await resume(); await cam(-1.57, 0.15, 80, 25); mark('4 BLUE TOWER - 72 m, projecting circular decks (real landing surfaces)'); await sleep(3200);
  await pause(); await P("return P.goTo(50, 130)"); await resume(); await pause(); await P("return P.goTo(40, 232)"); await resume(); await cam(2.6, 0.15, 60, 20); mark('5 MAH MARKET - 64 m, narrower by nature, own forecourt behind the temple ring'); await sleep(3200);
  /* 6 walk + dash into the gym facade */
  await show(); await pause(); await P("return P.goTo(50, 130)"); await resume(); await pause(); await P("return P.goTo(-70, 110)"); await resume(); await cam(1.2, 0.12, 7, 1.5); mark('6 WALK then DASH into the MAH GYM facade: blocked (finite-height fitted proxies, no invisible giant box)');
  await move(0, -1, true, -1.5708); await sleep(2200); await stop(); await sleep(300); await P("return P.send('DASH',{dir:'FORWARD'})"); await sleep(1200); console.log('after dash', await pos());
  /* 7 fly against the temple facade */
  await pause(); await P("return P.goTo(0, 125)"); await resume(); await cam(3.14, 0.1, 9, 2); mark('7 FLY against the TEMPLE facade at ~12 m: blocked; the wall is solid in the air too'); await fly('ENTER'); await sleep(300); await fly('ASCEND'); await sleep(2400); await fly('HOVER'); await move(-1, 0, true, 3.1416); await sleep(2200); await stop(); console.log('fly-into-facade', await pos(), 'alt', await alt());
  /* 8 fly above the gym, land on the roof, perch, take off */
  await move(1, 0, true, 0); await sleep(1500); await stop(); await fly('ASCEND'); mark('8 CLIMB above the MAH GYM roof (72 m) and LAND on the real terrace'); await sleep(2500); await cam(1.57, 0.35, 40, 40); await move(0, -1, true, -1.5708); await sleep(9000); await stop();
  console.log('over gym alt', await alt(), await pos()); await fly('HOVER'); await pause(); await P("return P.goTo(-112, 110, -112, 100, 12000)"); await resume(); await cam(0.9, 0.25, 8, 1.6); await fly('EXIT'); await sleep(6500); console.log('landed', await pos(), 'ground', await ground());
  mark('9 ON THE ROOF: supported (see ground read-out), walk, then PERCH (Tab emotes -> Perch): a settled hover-perch on real support'); await move(0, -1, false, -1.5708); await sleep(1500); await stop(); await sleep(300); console.log('perch', await P("return P.send('EMOTE',{emote_id:'PERCH'}).then(function(r){ return JSON.stringify(r); })")); await sleep(4000);
  await cam(2.2, 0.15, 6, 1.4); mark('10 TAKE OFF from the roof, descend to the plaza (elevated-to-ground return)'); await fly('ENTER'); await sleep(300); await fly('ASCEND'); await sleep(1500); await fly('HOVER'); await cam(1.57, 0.4, 60, 30); await move(0, 1, true, 1.5708); await sleep(7000); await stop(); await fly('EXIT'); await sleep(9000); console.log('back down', await pos(), 'ground', await ground());
  /* 11 tower deck with gap */
  await pause(); await P("return P.goTo(60, 110)"); await resume(); await fly('ENTER'); await sleep(300); await fly('ASCEND'); mark('11 BLUE TOWER: climb to a 57 m deck, land on it - the air gap under the deck stays open'); await sleep(11000); await fly('HOVER'); await cam(-1.57, 0.2, 40, 50); await pause(); await P("return P.goTo(106, 121, 112, 110, 12000)"); await resume(); await fly('EXIT'); await sleep(6000); console.log('tower deck', await pos(), 'ground', await ground());
  await cam(-2.0, -0.35, 26, 40); await sleep(2500);
  /* 12 floor */
  await fly('ENTER'); await sleep(300); await fly('ASCEND'); await sleep(1200); await fly('HOVER'); await pause(); await P("return P.goTo(60, 110, 60, 100, 12000)"); await resume(); await fly('EXIT'); await sleep(8000); await pause(); await P("return P.goTo(20, 135)"); await resume(); await cam(3.14, 0.6, 26, 2); mark('12 BLACK PLATINUM GROUND: graphite base, silver grain, soft reflections, curved route inlays - no grid'); await sleep(3000);
  /* 13 tree transit */
  await show(); await pause(); await P("return P.goTo(26.6, 40)"); await resume(); await cam(-2.0, 0.12, 8, 1.4); mark('13 TREE ELEVATOR still works (Enter -> ride to the 9 m platform); NPC routes untouched'); await sleep(400); await tap('Enter'); await sleep(4200); await cam(-1.2, 0.3, 14, 9.5); await sleep(1800);
  await pg.cmd('Page.stopScreencast'); var dur = frames.length ? (frames[frames.length - 1].t - frames[0].t) / 1000 : 0; console.log('frames', frames.length, 'seconds', dur.toFixed(1));
  fs.writeFileSync(path.join(OUT, 'marks.json'), JSON.stringify({ marks: marks, frames: frames.length, seconds: +dur.toFixed(1) }, null, 1));
  marks.forEach(function (mk, i) { var fi = frames.findIndex(function (f) { return f.t / 1000 >= mk.t + 0.9; }); if (fi >= 0) fs.writeFileSync(path.join(OUT, 'still_' + String(i).padStart(2, '0') + '_' + mk.label.replace(/[^a-z0-9]+/gi, '_').slice(0, 40) + '.png'), Buffer.from(frames[fi].data, 'base64')); });
  var t2 = await pg.cmd('Target.createTarget', { url: 'about:blank' }); var list = await (await fetch('http://127.0.0.1:' + pg.port + '/json/list')).json(); var helper = list.filter(function (x) { return x.id === t2.targetId; })[0]; var ws = new WebSocket(helper.webSocketDebuggerUrl); await new Promise(function (r, j) { ws.onopen = r; ws.onerror = j; });
  var mid = 0, pend = {}; ws.onmessage = function (m) { var d = JSON.parse(typeof m.data === 'string' ? m.data : String(m.data)); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id]; } }; function c2(method, params) { return new Promise(function (r, j) { var id = ++mid; pend[id] = function (d) { d.error ? j(new Error(JSON.stringify(d.error))) : r(d.result); }; ws.send(JSON.stringify({ id: id, method: method, params: params || {} })); }); }
  await c2('Runtime.enable'); var ev2 = async function (expr) { var r = await c2('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error('eval2: ' + JSON.stringify(r.exceptionDetails).slice(0, 300)); return r.result.value; };
  await ev2('window.__F = []; window.__T = []; 1'); for (var c0 = 0; c0 < frames.length; c0 += 40) { var chunk = frames.slice(c0, c0 + 40); await ev2('(function(){var d=' + JSON.stringify(chunk.map(function (f) { return f.data; })) + ';var t=' + JSON.stringify(chunk.map(function (f) { return Math.round(f.t - frames[0].t); })) + ';for(var i=0;i<d.length;i++){window.__F.push(d[i]);window.__T.push(t[i]);} return window.__F.length;})()'); }
  var webm = await ev2('(async function(){ var F=window.__F, T=window.__T; var load=function(i){ return new Promise(function(res){ var im=new Image(); im.onload=function(){res(im)}; im.onerror=function(){res(null)}; im.src="data:image/jpeg;base64,"+F[i]; }); }; var first=await load(0); var w=first.width, h=first.height; var cv=document.createElement("canvas"); cv.width=w; cv.height=h; document.body.appendChild(cv); var ctx=cv.getContext("2d"); ctx.drawImage(first,0,0); var stream=cv.captureStream(30); var mime=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].filter(function(m){return MediaRecorder.isTypeSupported(m)})[0]; var rec=new MediaRecorder(stream,{mimeType:mime, videoBitsPerSecond: 3000000}); var chunks=[]; rec.ondataavailable=function(e){ if(e.data && e.data.size) chunks.push(e.data); }; var done=new Promise(function(res){ rec.onstop=res; }); rec.start(250); var start=performance.now(); for (var i=1;i<F.length;i++){ var im=await load(i); F[i]=null; while(performance.now()-start<T[i]) await new Promise(function(r){ requestAnimationFrame(r); }); if (im) ctx.drawImage(im,0,0); } await new Promise(function(r){ setTimeout(r,300); }); rec.stop(); await done; var blob=new Blob(chunks,{type:mime}); var b64=await new Promise(function(res){ var fr=new FileReader(); fr.onload=function(){res(fr.result.split(",")[1])}; fr.readAsDataURL(blob); }); return {mime:mime, bytes:blob.size, b64:b64}; })()');   /* frames decoded one at a time and released (no 7k-bitmap pile-up) */
  var vpath = path.join(OUT, 'mahworld_district_review.webm'); fs.writeFileSync(vpath, Buffer.from(webm.b64, 'base64')); console.log('VIDEO FILE ' + vpath + ' ' + webm.bytes + ' bytes ' + dur.toFixed(1) + 's'); ws.close();
  console.log('errors', pg.errors.filter(function (x) { return !/404/.test(x); }));
} finally { await pg.close(); srv.close(); }
