/* S13 REVIEW (~3 min): environment, locomotion (fused / split, rear-follow camera), flight, emotes (endpoints), attacks (exercise patterns),
   hit reaction (donor), UI / menu / controls, buildings, camera chapter (W/A/S/D with no look input, then MANUAL LOOK), final sweep.
   Every front / side inspection is a deliberate manual drag and is labelled "MANUAL LOOK"; the gameplay camera is never overridden except
   for the two labelled distant establishing shots. Inputs are real key / mouse events. Touch: EMULATED only (stated on the end card).
   node deploy/record_s13.mjs [tag] -> deploy/review/<tag>/mahworld_s13_review.webm + marks.json + stills */
import path from 'node:path'; import fs from 'node:fs'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = path.join(HERE, 'static_dist'); var tag = process.argv[2] || 's13'; var OUT = path.join(HERE, 'review', tag); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 1120, height: 700, gpu: true }); var frames = [], marks = [], t0 = 0;
var pausedTotalRef = function () { return 0; }; function mark(l) { var tt = (performance.now() - t0 - pausedTotalRef()) / 1000; marks.push({ t: +tt.toFixed(2), label: l }); console.log(tt.toFixed(1) + 's  ' + l); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(50); await key(code, false); }
async function hold(code, ms) { await key(code, true); await sleep(ms); await key(code, false); }
async function P(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
async function cap(text, sub) { await pg.evaluate("(function(){ var c=document.getElementById('s13cap'); c.innerHTML=" + JSON.stringify('<b>' + text + '</b>' + (sub ? '<span>' + sub + '</span>' : '')) + "; c.style.opacity=1; })(); 1"); mark(text + (sub ? ' — ' + sub : '')); }
async function chip(text, on) { await pg.evaluate("(function(){ var c=document.getElementById('s13chip'); c.textContent=" + JSON.stringify(text) + "; c.className=" + JSON.stringify(on ? 'on' : '') + "; })(); 1"); }
/* MANUAL LOOK = a real mouse drag on the view (deliberate, past the tap threshold); release = the camera returns behind the body */
var dragPos = null; async function lookStart() { var vw = await P("return {w:innerWidth,h:innerHeight};"); dragPos = { x: vw.w * 0.55, y: vw.h * 0.5 }; await pg.evaluate("document.getElementById('view').dispatchEvent(new MouseEvent('mousedown',{clientX:" + dragPos.x + ",clientY:" + dragPos.y + ",bubbles:true})); 1"); await chip('MANUAL LOOK (mouse drag held)', true); }
async function lookBy(dx, dy, ms) { var n = Math.max(6, Math.round(ms / 33)); for (var i = 1; i <= n; i++) { var x = dragPos.x + dx * i / n, y = dragPos.y + dy * i / n; await pg.evaluate("dispatchEvent(new MouseEvent('mousemove',{clientX:" + x + ",clientY:" + y + ",bubbles:true})); 1"); await sleep(33); } dragPos = { x: dragPos.x + dx, y: dragPos.y + dy }; }
async function lookEnd() { await pg.evaluate("dispatchEvent(new MouseEvent('mouseup',{clientX:" + dragPos.x + ",clientY:" + dragPos.y + ",bubbles:true})); 1"); await chip('REAR FOLLOW (returning)', false); }
async function faceYaw(yaw) { await P("return P.send('MOVE',{forward:0,strafe:0,run:false,yaw:" + yaw + "})"); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1'); await waitForGame(pg, 120000); await sleep(6000);
  await P("P.hud.showGuide(false); return 1;");
  await pg.evaluate("(function(){ var s=document.createElement('style'); s.textContent='#s13cap{position:fixed;left:50%;top:112px;transform:translateX(-50%);max-width:62vw;background:rgba(5,8,15,.72);color:#eef4ff;font:600 19px/1.2 system-ui,Segoe UI,sans-serif;padding:12px 20px;border-radius:12px;border:1px solid rgba(190,220,255,.25);z-index:99999;pointer-events:none;text-align:center;opacity:0;transition:opacity .25s}#s13cap span{display:block;font:400 13px/1.3 system-ui,Segoe UI,sans-serif;color:rgba(205,225,255,.85);margin-top:4px}#s13chip{position:fixed;left:16px;top:118px;background:rgba(5,8,15,.6);color:#9fe8ff;font:600 13px/1 system-ui,Segoe UI,sans-serif;letter-spacing:.08em;padding:8px 12px;border-radius:8px;border:1px solid rgba(159,232,255,.35);z-index:99999;pointer-events:none}#s13chip.on{color:#ffd27a;border-color:rgba(255,210,122,.6)}'; document.head.appendChild(s); var c=document.createElement('div'); c.id='s13cap'; document.body.appendChild(c); var k=document.createElement('div'); k.id='s13chip'; k.textContent='REAR FOLLOW'; document.body.appendChild(k); })(); 1");
  var paused = false, pausedAt = 0, pausedTotal = 0; pausedTotalRef = function () { return pausedTotal; }; async function pause() { if (paused) return; paused = true; pausedAt = performance.now(); await pg.cmd('Page.stopScreencast'); } async function resume() { if (!paused) return; pausedTotal += performance.now() - pausedAt; paused = false; await pg.cmd('Page.startScreencast', { format: 'jpeg', quality: 72, maxWidth: 1120, maxHeight: 700, everyNthFrame: 2 }); }
  pg.on('Page.screencastFrame', function (p) { if (paused) return; frames.push({ t: performance.now() - t0 - pausedTotal, data: p.data }); pg.cmd('Page.screencastFrameAck', { sessionId: p.sessionId }).catch(function () { }); });
  var fly = function (op) { return P("return P.send('FLIGHT',{op:'" + op + "'})"); }; var pos = function () { return P("return JSON.stringify(P.snap().play.position)"); };
  async function goTo(x, z) { await pause(); var r = await P("return P.goTo(" + x + ", " + z + ", undefined, undefined, 60000)"); console.log("goTo", x, z, JSON.stringify(r), await pos()); await sleep(200); await resume(); }
  t0 = performance.now(); await pg.cmd('Page.startScreencast', { format: 'jpeg', quality: 72, maxWidth: 1120, maxHeight: 700, everyNthFrame: 2 });
  /* ───── 1 INTRO / ENVIRONMENT ───── */
  await cap('1 · MAHWORLD DISTRICT — daytime', 'cool sky, clouds, black platinum floor · S13 build (ATHLETE_M_V8, surgical split legs) · gameplay camera: centred rear follow'); await sleep(3500);
  await lookStart(); await cap('MANUAL LOOK', 'deliberate mouse drag: skyline sweep — Gold Temple (80 m), MAH GYM (72 m), Blue Tower (72 m)'); await lookBy(-420, -60, 2600); await sleep(900); await lookBy(720, 0, 3200); await sleep(700); await lookEnd(); await cap('release', 'the camera eases back behind the body on its own'); await sleep(1800);
  /* ───── 2 CAMERA CHAPTER: W / A / S / D with NO look input ───── */
  await cap('2 · CAMERA — W / A / S / D, hands off the mouse', 'direct rear view throughout: the camera follows the displayed facing, never the travel vector'); await chip('REAR FOLLOW — no look input', false);
  await hold('KeyW', 2600); await sleep(300); await cap('A (strafe left) — still from directly behind'); await hold('KeyA', 2200); await sleep(300); await cap('S (backward) — the body turns, the camera swings behind it, no front view'); await hold('KeyS', 2400); await sleep(300); await cap('D (strafe right)'); await hold('KeyD', 2200); await sleep(400);
  await cap('move + MANUAL LOOK at the same time', 'W held while dragging: free look around the running body, then release → smooth return'); await key('KeyW', true); await sleep(400); await lookStart(); await lookBy(-360, 30, 1400); await sleep(900); await lookBy(120, 0, 600); await sleep(600); await lookEnd(); await sleep(1600); await key('KeyW', false); await sleep(600);
  /* ───── 3 LOCOMOTION: fused → split (H) ───── */
  await cap('3 · LOCOMOTION — fused taper', 'run: the fused lower body bends through its tail chain'); await key('ShiftLeft', true); await hold('KeyW', 2600); await key('ShiftLeft', false); await sleep(400);
  await cap('H = SEPARATE', 'the split legs are derived from the fused anatomy: outer surface = the taper’s own cross-section, inner surface inferred from it'); await tap('KeyH'); await sleep(3400);
  await lookStart(); await cap('MANUAL LOOK', 'split legs from the front: real hip, no invented shorts pelvis, two limbs flush with the pelvis shell'); await lookBy(-560, 40, 1800); await sleep(1400); await lookEnd(); await sleep(1400);
  await cap('split gait', 'walk / run: thigh and shin from the hip pivots (rear view)'); await hold('KeyW', 2200); await key('ShiftLeft', true); await hold('KeyW', 2000); await key('ShiftLeft', false); await sleep(300);
  await cap('H = FUSE'); await tap('KeyH'); await sleep(3400);
  /* ───── 4 FLIGHT ───── */
  await cap('4 · FLIGHT — F take-off, Space ascend', 'rear view in the air; no flight trick is shipped (an unconvincing loop is omitted on purpose)'); await tap('KeyF'); await sleep(500); await key('Space', true); await sleep(2400); await key('Space', false); await sleep(300);
  await cap('travel toward the MAH GYM roof (72 m)'); await faceYaw(-1.5708); await sleep(300); await key('ShiftLeft', true); await key('KeyW', true); await key('Space', true); await sleep(9000); await key('Space', false); await sleep(2500); await key('KeyW', false); await key('ShiftLeft', false);
  await cap('landing on the roof', 'F = land; the roof is real support'); await goTo(-112, 100); await tap('KeyF'); await sleep(5000); console.log('roof', await pos(), 'ground', await P("return P.snap().play.flight.ground"));
  await cap('PERCH on the roof edge (Tab → Perch)'); await P("return P.send('EMOTE',{emote_id:'PERCH'})"); await sleep(3500); await lookStart(); await cap('MANUAL LOOK', 'perch from the side'); await lookBy(-300, 60, 1200); await sleep(1200); await lookEnd(); await sleep(1200); await P("return P.send('EMOTE_STOP')"); await sleep(600);
  await cap('take off, back to the plaza'); await tap('KeyF'); await sleep(400); await key('Space', true); await sleep(1200); await key('Space', false); await faceYaw(1.5708); await sleep(200); await key('ShiftLeft', true); await key('KeyW', true); await sleep(5000); await key('KeyW', false); await key('ShiftLeft', false); await tap('KeyF'); await sleep(4500);
  /* ───── 5 EMOTES — endpoint precision ───── */
  await goTo(0, 40); await faceYaw(0); await sleep(600);
  await cap('5 · EMOTES — exact endpoints', 'each key names a wrist target; a 2-bone solve on the live shoulder puts the hand THERE (0.0 cm error on the real skeleton)');
  await lookStart(); await lookBy(-560, 60, 1500); await chip('MANUAL LOOK (held for the emote chapter)', true);
  await cap('WAVE', 'hand beside the head at ear height, palm forward — clear of the crown'); await tap('KeyX'); await sleep(3600);
  await cap('FRONT LAT SPREAD', 'fists ON the waist, elbows flared, chest lifted'); await P("return P.send('EMOTE',{emote_id:'FRONT_LAT_SPREAD'})"); await sleep(3800);
  await cap('DOUBLE BICEPS', 'fists beside the ears, upper arms level and wide'); await P("return P.send('EMOTE',{emote_id:'DOUBLE_BICEPS'})"); await sleep(3800);
  await cap('THUMBS UP', 'thumb in front of the chest line'); await P("return P.send('EMOTE',{emote_id:'THUMBS_UP'})"); await sleep(2600);
  await cap('APPLAUD', 'the wrists part and meet 9 cm apart in front of the chest — the palms touch'); await P("return P.send('EMOTE',{emote_id:'APPLAUD'})"); await sleep(3200);
  await cap('BACK LAT SPREAD', 'thumbs hooked into the waist behind the turned trunk (targets ride the chest frame)'); await P("return P.send('EMOTE',{emote_id:'BACK_LAT_SPREAD'})"); await sleep(3600);
  await lookEnd(); await sleep(1200);
  /* ───── 6 ATTACKS — exercise patterns ───── */
  await goTo(0, 4); await faceYaw(3.1416); await sleep(500); console.log('lock', JSON.stringify(await P("return P.send('LOCK_TARGET',{aim_id:'FIELD_DUMMY'})"))); await sleep(300);
  await cap('6 · ATTACKS — E / R / T / Y = movement-pattern slots', 'rear view; the aim is the locked dummy');
  await lookStart(); await lookBy(-330, 20, 1200); await chip('MANUAL LOOK (side view for the pattern read)', true);
  await cap('E · HORIZONTAL PUSH', 'retracted setup → humeri to horizontal, elbows lock out, scapulae protract; a restrained trunk drive — no forward lean'); await tap('KeyE'); await sleep(2600);
  await cap('R · VERTICAL PULL', 'reach up wide → elbows drive down and back to the ribs, scapular depression, chest up'); await tap('KeyR'); await sleep(2600);
  await cap('T · HIP HINGE', 'hips back, flat back → explosive hip extension'); await tap('KeyT'); await sleep(2600);
  await cap('Y · ROTATION', 'trunk rotation strike'); await tap('KeyY'); await sleep(2600);
  await lookEnd(); await sleep(800);
  await cap('SPECIAL MAHGIC (gold only)', 'Athlete Vector — the donor cast staging drives the upper body, MAHWORLD keeps the lower body'); await P("return P.send('RULES_SELECT',{category:'SPECIAL_MAGIC'})"); await sleep(400); await tap('KeyE'); await sleep(3200); await P("return P.send('RULES_SELECT',{category:'PHYSICAL'})"); await sleep(400);
  /* ───── 7 HIT REACTION ───── */
  await cap('7 · HIT REACTION — practice battle on', 'the dummy takes damage and plays the donor-informed reaction (Tripo hit_to_head, upper body only, mirrored / turned toward the blow)'); await P("return P.send('FIELD_PRACTICE',{on:true})"); await sleep(600);
  await lookStart(); await lookBy(-190, 20, 900); await chip('MANUAL LOOK (watch the dummy)', true); await sleep(300);
  await tap('KeyE'); await sleep(2200); await tap('KeyR'); await sleep(2200); await tap('KeyE'); await sleep(2400);
  await lookEnd(); await sleep(600); await P("return P.send('FIELD_PRACTICE',{on:false})"); await P("return P.send('LOCK_TARGET',{aim_id:null})");
  /* ───── 8 UI / MENU / CONTROLS ───── */
  await cap('8 · UI — TAB opens the emote radial'); await tap('Tab'); await sleep(2200); await tap('Escape'); await sleep(500);
  await cap('Q = universal menu', 'stats · skills · inventory · map · friends · DMs (stubs where not live)'); await tap('KeyQ'); await sleep(2600); await P("return P.menu && P.menu.tab ? P.menu.tab('MAP') : null"); await sleep(1600); await tap('KeyQ'); await sleep(500);
  await cap('controls help', 'H = separate / fuse · E R T Y attacks · G / Shift+G guards · F fly · Tab emotes · Q menu'); await tap('Escape'); await sleep(2600); await tap('Escape'); await sleep(500);
  /* ───── 9 BUILDINGS ───── */
  await cap('9 · BUILDINGS — the uploaded GLBs, their own materials, in daylight', 'fly to the Gold Temple');
  await goTo(0, 118); await faceYaw(3.1416); await sleep(400); await tap('KeyF'); await sleep(400); await key('Space', true); await sleep(2200); await key('Space', false); await sleep(600);
  await lookStart(); await cap('MANUAL LOOK', 'Gold Temple 80 m — central landmark, its own gold / silver materials'); await lookBy(-380, -140, 1800); await sleep(1800); await lookEnd(); await sleep(1400);
  await cap('Blue Tower deck (57 m) — land on it'); await goTo(60, 110); await key('Space', true); await sleep(9000); await key('Space', false); await goTo(106, 121); await tap('KeyF'); await sleep(5000); console.log('tower deck', await pos(), 'ground', await P("return P.snap().play.flight.ground"));
  await lookStart(); await cap('MANUAL LOOK', 'Blue Tower + MAH MARKET (emerald, 64 m) from the deck'); await lookBy(-500, 80, 2000); await sleep(1800); await lookEnd(); await sleep(1200);
  /* ───── 10 FINAL SWEEP ───── */
  await cap('10 · FINAL SWEEP', 'take off from the deck, rear-follow flight back to the plaza'); await tap('KeyF'); await sleep(400); await faceYaw(1.5708); await sleep(200); await key('ShiftLeft', true); await key('KeyW', true); await sleep(2000); await key('KeyC', true); await sleep(6000); await key('KeyC', false); await key('KeyW', false); await key('ShiftLeft', false); await tap('KeyF'); await sleep(3500);
  await cap('S13 review — end', 'touch input paths: EMULATED (synthetic pointer events on the look / stick zones), no physical device · public demo: gate live on the demo project; fob.systems/mahdemo needs the main-site rule (owner credentials)'); await sleep(4500);
  await pg.cmd('Page.stopScreencast'); var dur = frames.length ? (frames[frames.length - 1].t - frames[0].t) / 1000 : 0; console.log('frames', frames.length, 'seconds', dur.toFixed(1));
  fs.writeFileSync(path.join(OUT, 'marks.json'), JSON.stringify({ marks: marks, frames: frames.length, seconds: +dur.toFixed(1) }, null, 1));
  marks.forEach(function (mk, i) { var fi = frames.findIndex(function (f) { return f.t / 1000 >= mk.t + 1.2; }); if (fi >= 0) fs.writeFileSync(path.join(OUT, 'still_' + String(i).padStart(2, '0') + '_' + mk.label.replace(/[^a-z0-9]+/gi, '_').slice(0, 40) + '.jpg'), Buffer.from(frames[fi].data, 'base64')); });
  var t2 = await pg.cmd('Target.createTarget', { url: 'about:blank' }); var list = await (await fetch('http://127.0.0.1:' + pg.port + '/json/list')).json(); var helper = list.filter(function (x) { return x.id === t2.targetId; })[0]; var ws = new WebSocket(helper.webSocketDebuggerUrl); await new Promise(function (r, j) { ws.onopen = r; ws.onerror = j; });
  var mid = 0, pend = {}; ws.onmessage = function (m) { var d = JSON.parse(typeof m.data === 'string' ? m.data : String(m.data)); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id]; } }; function c2(method, params) { return new Promise(function (r, j) { var id = ++mid; pend[id] = function (d) { d.error ? j(new Error(JSON.stringify(d.error))) : r(d.result); }; ws.send(JSON.stringify({ id: id, method: method, params: params || {} })); }); }
  await c2('Runtime.enable'); var ev2 = async function (expr) { var r = await c2('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error('eval2: ' + JSON.stringify(r.exceptionDetails).slice(0, 300)); return r.result.value; };
  await ev2('window.__F = []; window.__T = []; 1'); for (var c0 = 0; c0 < frames.length; c0 += 40) { var chunk = frames.slice(c0, c0 + 40); await ev2('(function(){var d=' + JSON.stringify(chunk.map(function (f) { return f.data; })) + ';var t=' + JSON.stringify(chunk.map(function (f) { return Math.round(f.t - frames[0].t); })) + ';for(var i=0;i<d.length;i++){window.__F.push(d[i]);window.__T.push(t[i]);} return window.__F.length;})()'); }
  var webm = await ev2('(async function(){ var F=window.__F, T=window.__T; var load=function(i){ return new Promise(function(res){ var im=new Image(); im.onload=function(){res(im)}; im.onerror=function(){res(null)}; im.src="data:image/jpeg;base64,"+F[i]; }); }; var first=await load(0); var w=first.width, h=first.height; var cv=document.createElement("canvas"); cv.width=w; cv.height=h; document.body.appendChild(cv); var ctx=cv.getContext("2d"); ctx.drawImage(first,0,0); var stream=cv.captureStream(30); var mime=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].filter(function(m){return MediaRecorder.isTypeSupported(m)})[0]; var rec=new MediaRecorder(stream,{mimeType:mime, videoBitsPerSecond: 3500000}); var chunks=[]; rec.ondataavailable=function(e){ if(e.data && e.data.size) chunks.push(e.data); }; var done=new Promise(function(res){ rec.onstop=res; }); rec.start(250); var start=performance.now(); for (var i=1;i<F.length;i++){ var im=await load(i); F[i]=null; while(performance.now()-start<T[i]) await new Promise(function(r){ requestAnimationFrame(r); }); if (im) ctx.drawImage(im,0,0); } await new Promise(function(r){ setTimeout(r,300); }); rec.stop(); await done; var blob=new Blob(chunks,{type:mime}); var b64=await new Promise(function(res){ var fr=new FileReader(); fr.onload=function(){res(fr.result.split(",")[1])}; fr.readAsDataURL(blob); }); return {mime:mime, bytes:blob.size, b64:b64}; })()');
  var vpath = path.join(OUT, 'mahworld_s13_review.webm'); fs.writeFileSync(vpath, Buffer.from(webm.b64, 'base64')); console.log('VIDEO FILE ' + vpath + ' ' + webm.bytes + ' bytes ' + dur.toFixed(1) + 's'); ws.close();
  console.log('errors', pg.errors.filter(function (x) { return !/404/.test(x); }).slice(0, 6));
} finally { await pg.close(); srv.close(); }
