/* One bounded current-runtime motion capture for the two playable HALO sports.
   Dev placement only reaches the existing entry; every serve/hit/replay/leave is
   sent through the real keyboard route and the host remains score authority. */
import fs from 'node:fs'; import path from 'node:path'; import { performance } from 'node:perf_hooks'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';

var HERE = path.dirname(fileURLToPath(import.meta.url)), DIST = path.join(HERE, 'static_dist'), OUT = path.join(HERE, 'probe_out', 'halo_sport_motion'); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST), pg = await launchChrome({ width: 960, height: 720, gpu: true, unlockFps: true, cmdTimeoutMs: 120000 }), frames = [], started = 0;
var report = { generated_at: new Date().toISOString(), source: DIST, input: 'real keyboard events', checks: {}, console_errors: [] };
async function ev(src) { return pg.evaluate("(async function(){var P=window.MAHWORLD_PLAY,H=window.MAHWORLD_STATIC_HOST;" + src + "})()"); }
async function snap() { return ev('return P.snap().play;'); }
var KEY = { Escape: 27, KeyV: 86, KeyP: 80, KeyR: 82, Digit1: 49, Digit2: 50, Digit3: 51 };
async function tap(code) { var key = code === 'Escape' ? 'Escape' : code.startsWith('Key') ? code.slice(3).toLowerCase() : code.slice(5); var p = { code: code, key: key, windowsVirtualKeyCode: KEY[code], nativeVirtualKeyCode: KEY[code] }; await pg.cmd('Input.dispatchKeyEvent', Object.assign({ type: 'rawKeyDown' }, p)); await sleep(70); await pg.cmd('Input.dispatchKeyEvent', Object.assign({ type: 'keyUp' }, p)); }
async function waitFor(fn, ms) { var end = Date.now() + ms, p; while (Date.now() < end) { p = await snap(); if (fn(p.sport, p)) return p; await sleep(70); } throw new Error('sport wait timeout: ' + JSON.stringify(p && p.sport)); }
pg.on('Page.screencastFrame', function (p) { if (started) frames.push({ t: performance.now() - started, data: p.data }); pg.cmd('Page.screencastFrameAck', { sessionId: p.sessionId }).catch(function () { }); });
async function encode() {
  if (!frames.length) throw new Error('no sports screencast frames'); var times = frames.map(function (f) { return Math.round(f.t - frames[0].t); });
  var tg = await pg.cmd('Target.createTarget', { url: 'about:blank' }), tabs = await (await fetch('http://127.0.0.1:' + pg.port + '/json/list')).json(), helper = tabs.filter(function (x) { return x.id === tg.targetId; })[0], ws = new WebSocket(helper.webSocketDebuggerUrl); await new Promise(function (r, j) { ws.onopen = r; ws.onerror = j; }); var mid = 0, pend = {};
  ws.onmessage = function (m) { var d = JSON.parse(typeof m.data === 'string' ? m.data : String(m.data)); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id]; } }; function cmd(method, params) { return new Promise(function (r, j) { var id = ++mid; pend[id] = function (d) { d.error ? j(new Error(JSON.stringify(d.error))) : r(d.result); }; ws.send(JSON.stringify({ id: id, method: method, params: params || {} })); }); }
  await cmd('Runtime.enable'); async function heval(expr) { var r = await cmd('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error('clip helper failed'); return r.result.value; }
  await heval('window.__F=[];window.__T=[];1'); for (var i = 0; i < frames.length; i += 35) { var ch = frames.slice(i, i + 35); await heval('(function(){var f=' + JSON.stringify(ch.map(function (x) { return x.data; })) + ',t=' + JSON.stringify(times.slice(i, i + 35)) + ';for(var i=0;i<f.length;i++){__F.push(f[i]);__T.push(t[i]);}return __F.length;})()'); }
  var out = await heval('(async function(){var F=__F,T=__T,I=[];for(var i=0;i<F.length;i++)I.push(await new Promise(function(res){var x=new Image();x.onload=function(){res(x)};x.onerror=function(){res(null)};x.src="data:image/jpeg;base64,"+F[i]}));var cv=document.createElement("canvas");cv.width=I[0].width;cv.height=I[0].height;var c=cv.getContext("2d"),st,rec,chunks=[],done=new Promise(function(r){st=r});c.drawImage(I[0],0,0);var stream=cv.captureStream(30),mime=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].filter(function(m){return MediaRecorder.isTypeSupported(m)})[0];rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2400000});rec.ondataavailable=function(e){if(e.data&&e.data.size)chunks.push(e.data)};rec.onstop=st;rec.start(200);var t0=performance.now(),n=0;await new Promise(function(res){function tick(){var e=performance.now()-t0;while(n<F.length&&T[n]<=e){if(I[n])c.drawImage(I[n],0,0);n++}if(n>=F.length){setTimeout(res,250);return}requestAnimationFrame(tick)}tick()});rec.stop();await done;var b=new Blob(chunks,{type:mime}),b64=await new Promise(function(res){var f=new FileReader();f.onload=function(){res(f.result.split(",")[1])};f.readAsDataURL(b)});return {mime:mime,bytes:b.size,b64:b64};})()');
  var file = path.join(OUT, 'halo_volley_and_practice.webm'); fs.writeFileSync(file, Buffer.from(out.b64, 'base64')); ws.close(); report.clip = { file: file, duration_s: +(times[times.length - 1] / 1000).toFixed(2), frames: frames.length, bytes: out.bytes, mime: out.mime };
}

try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1&tier=high'); await waitForGame(pg, 120000); await sleep(1800); await ev("P.hud.showGuide(false);P.devPlay('PLACE',{x:22.7,z:40});return P.send('TRANSIT',{id:'ELEVATOR_UP'});");
  var docked = Date.now() + 24000; while (Date.now() < docked) { var p0 = await snap(); if (!p0.transit && p0.spatial_domain === 'HALO') break; await sleep(180); }
  await ev("P.devPlay('PLACE',{x:42.2,z:40});var THREE=P.THREE,r=P.rendererDebug();if(!r.__sportOrig){r.__sportOrig=r.render.bind(r);r.render=function(sc,cam){var c=window.__sportCam;c.aspect=innerWidth/innerHeight;c.updateProjectionMatrix();r.__sportOrig(sc,c)}}var c=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.2,2400);c.position.set(38,247.5,51);c.lookAt(51,241.2,40);window.__sportCam=c;return 1;"); await waitFor(function (s, p) { return !s && p.prompts.some(function (x) { return x.intent === 'HALO_PLAY'; }); }, 4000);
  started = performance.now(); await pg.cmd('Page.startScreencast', { format: 'jpeg', quality: 68, maxWidth: 960, maxHeight: 720, everyNthFrame: 2 }); await tap('KeyV'); await waitFor(function (s) { return s && s.mode === 'VOLLEY' && s.phase === 'SERVE_READY'; }, 3000);
  var points = [], returned = false, seen = {}; for (var rally = 0; rally < 16; rally++) { var ready = await waitFor(function (s) { return s && (s.phase === 'SERVE_READY' || s.phase === 'RESULT'); }, 6500); if (ready.sport.phase === 'RESULT') break; await tap(rally === 0 ? 'Digit3' : rally === 1 ? 'KeyR' : 'KeyV'); var end = Date.now() + 5600; while (Date.now() < end) { var live = await snap(), sp = live.sport; if (sp.last_contact && sp.last_contact.who === 'BOT') { var d = Math.hypot(sp.ball.x - live.position.x, sp.ball.y - 241.25, sp.ball.z - live.position.z); if (!returned && d <= 2.3) { await tap('KeyV'); returned = true; } } if (sp.point && !seen[sp.point.rally_id]) { seen[sp.point.rally_id] = true; points.push(sp.point); } if (sp.phase === 'POINT' || sp.phase === 'RESULT') break; await sleep(65); } }
  var vr = await waitFor(function (s) { return s && s.phase === 'RESULT'; }, 8000); await sleep(500); await tap('KeyP'); var replay = await waitFor(function (s) { return s && s.phase === 'SERVE_READY' && s.score.player === 0 && s.score.bot === 0; }, 2500); await tap('Escape'); await waitFor(function (s) { return !s; }, 2500);
  await ev("P.devPlay('PLACE',{x:42.2,z:40});return 1;"); await sleep(220); await tap('KeyP'); await waitFor(function (s) { return s && s.mode === 'PRACTICE' && s.phase === 'SERVE_READY'; }, 2500); var zones = ['Digit1', 'Digit2', 'Digit3', 'Digit1', 'Digit2']; for (var z = 0; z < zones.length; z++) { await tap(zones[z]); await waitFor(function (s) { return s && (s.phase === 'POINT' || s.phase === 'RESULT'); }, 3500); if (z < 4) await waitFor(function (s) { return s && s.phase === 'SERVE_READY'; }, 2500); } var pr = await snap(); await sleep(600); await tap('Escape'); var left = await waitFor(function (s) { return !s; }, 2500); await sleep(350);
  await pg.cmd('Page.stopScreencast'); started = 0; await sleep(250); await encode(); report.checks = { volley: { points: points, result: vr.sport.result, score: vr.sport.score, player_return_contact: returned }, replay: { phase: replay.sport.phase, score: replay.sport.score }, practice: { result: pr.sport.result, attempts: pr.sport.practice.attempts, hits: pr.sport.practice.hits }, exit: { sport: left.sport, domain: left.spatial_domain } }; report.console_errors = pg.errors.filter(function (e) { return !/favicon|athlete_m_preview.*manifest\.json/i.test(e); });
} catch (e) { report.fatal = String(e && e.stack || e); console.error(report.fatal); }
finally { try { if (started) await pg.cmd('Page.stopScreencast'); } catch (e) { } fs.writeFileSync(path.join(OUT, 'report.json'), JSON.stringify(report, null, 1)); await pg.close(); srv.close(); }
console.log('RESULT HALO sport motion ' + (report.fatal ? 'FAIL' : 'PASS') + ' frames ' + frames.length + ' -> ' + OUT); process.exit(report.fatal || report.console_errors.length ? 1 : 0);
