/* S10 OWNER REVIEW CLIP (~55 s) — ATHLETE_M_V7 (dev_0.12 axilla unweld) vs V6 at the overhead extremes, split-transition and hip extremes,
   hover gait; UI hidden, effects off. node deploy/record_s10.mjs [tag] → deploy/review/<tag>/mahworld_s10_review.webm */
import path from 'node:path'; import fs from 'node:fs'; import { fileURLToPath } from 'node:url';
import { serveStatic, launchChrome, waitForGame, sleep, PLAY_PATH } from './probe_lib.mjs';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = path.join(HERE, 'static_dist'); var tag = process.argv[2] || 's10'; var OUT = path.join(HERE, 'review', tag); fs.mkdirSync(OUT, { recursive: true });
var srv = await serveStatic(DIST); var pg = await launchChrome({ width: 960, height: 720, gpu: true }); var frames = [], marks = [], t0 = 0;
function mark(l) { marks.push({ t: +((performance.now() - t0) / 1000).toFixed(2), label: l }); console.log(((performance.now() - t0) / 1000).toFixed(1) + 's  ' + l); }
async function key(code, down) { await pg.evaluate("document.dispatchEvent(new KeyboardEvent('" + (down ? 'keydown' : 'keyup') + "',{code:'" + code + "',key:'" + (code.startsWith('Key') ? code.slice(3).toLowerCase() : code) + "',bubbles:true})); 1"); }
async function tap(code) { await key(code, true); await sleep(40); await key(code, false); }
async function cam(y, p, d, pv) { await pg.evaluate("window.MAHWORLD_PLAY.cam(" + y + "," + p + "," + d + "," + (pv === undefined ? 'null' : pv) + ")"); }
async function yawOf() { return await pg.evaluate("window.MAHWORLD_PLAY.mePose().root_yaw"); }
async function P(expr) { return await pg.evaluate("(function(){ var P=window.MAHWORLD_PLAY; " + expr + " })()"); }
try {
  await pg.goto(srv.origin + PLAY_PATH + '?field=1&dev=1&avatar=ATHLETE_M_V7'); await waitForGame(pg, 90000); await sleep(4000);
  await P("P.hud.showGuide(false); if (P.camFollow) P.camFollow(false); document.querySelectorAll('body > *').forEach(function(e){ if (e.tagName!=='CANVAS') e.style.visibility='hidden'; }); return 1;");
  pg.on('Page.screencastFrame', function (p) { frames.push({ t: performance.now() - t0, data: p.data }); pg.cmd('Page.screencastFrameAck', { sessionId: p.sessionId }).catch(function () { }); });
  await P("return P.goTo(-3, -13, -3, -8)"); await sleep(500); var y0 = await yawOf();
  t0 = performance.now(); await pg.cmd('Page.startScreencast', { format: 'jpeg', quality: 72, maxWidth: 960, maxHeight: 720, everyNthFrame: 2 });
  await cam(y0 + Math.PI + 0.5, 0.05, 2.6, 1.05); mark('1 V7 dev_0.12 REST (axilla unweld: bridging triangles removed, inner-arm + lat patches) — front 3/4'); await sleep(2600);
  await cam(y0 + Math.PI - 0.55, 0.05, 1.9, 1.25); mark('2 SHOULDER LADDER 45 / 90 / 120 / 150 / 165 abduction — front 3/4 (no plates)');
  var ladder = [45, 90, 120, 150, 165]; for (var li = 0; li < ladder.length; li++) { var z = ladder[li] * Math.PI / 180; await P("P.poseOverride('me', { UPPERARM_L: [-0.05, 0, " + (-z) + "], UPPERARM_R: [-0.05, 0, " + z + "], FOREARM_L: [-0.1, 0, 0], FOREARM_R: [-0.1, 0, 0] })"); await sleep(1500); }
  await cam(y0 + Math.PI / 2, 0.02, 2.0, 1.25); mark('3 165 abduction — side (lat / armpit region)'); await sleep(2200); await cam(y0, 0.02, 2.0, 1.25); mark('4 165 abduction — rear'); await sleep(2200);
  mark('5 OVERHEAD FLEXION 150 — front 3/4 then side'); await P("P.poseOverride('me', { UPPERARM_L: [-2.6, 0, -0.25], UPPERARM_R: [-2.6, 0, 0.25], FOREARM_L: [-0.1, 0, 0], FOREARM_R: [-0.1, 0, 0] })"); await cam(y0 + Math.PI - 0.55, 0.05, 2.0, 1.25); await sleep(2200); await cam(y0 + Math.PI / 2, 0.02, 2.0, 1.25); await sleep(2000);
  await P("P.poseOverride('me', null)"); await sleep(600);
  await cam(y0 + Math.PI + 0.55, 0.06, 3.4, 0.95); mark('6 SPLIT TRANSITION packed -> X-gather -> split (hip / knee extremes), front 3/4'); await P("return P.send('TRANSFORM',{to:'SPLIT'})"); await sleep(3600);
  await cam(y0 + Math.PI / 2, 0.02, 3.0, 0.8); mark('7 SPLIT at rest — side (hip origin, thigh, knee, shin, tip)'); await sleep(2200);
  await P("return P.goTo(-18, -10)"); await cam(-Math.PI / 2, 0.42, 6.5); await sleep(200); await key('KeyW', true); await sleep(1100); var y1 = await yawOf();
  await cam(y1 + Math.PI + Math.PI / 2, 0.02, 3.4, 0.8); mark('8 HOVER GAIT — side (support tip ahead, hover phase, trail)'); await sleep(3200); await cam(y1, 0.05, 3.6, 0.8); mark('9 HOVER GAIT — rear'); await sleep(2600); await key('KeyW', false); await sleep(400);
  await P("return P.send('TRANSFORM',{to:'FUSED'})"); await cam(y1 + Math.PI + 0.55, 0.06, 3.4, 0.95); mark('10 split -> packed (fuse), then rest'); await sleep(3400);
  await pg.cmd('Page.stopScreencast'); var dur = frames.length ? (frames[frames.length - 1].t - frames[0].t) / 1000 : 0; console.log('frames', frames.length, 'seconds', dur.toFixed(1));
  fs.writeFileSync(path.join(OUT, 'marks.json'), JSON.stringify({ marks: marks, frames: frames.length, seconds: +dur.toFixed(1) }, null, 1));
  marks.forEach(function (mk, i) { var fi = frames.findIndex(function (f) { return f.t / 1000 >= mk.t + 0.9; }); if (fi >= 0) fs.writeFileSync(path.join(OUT, 'still_' + String(i).padStart(2, '0') + '_' + mk.label.replace(/[^a-z0-9]+/gi, '_').slice(0, 40) + '.png'), Buffer.from(frames[fi].data, 'base64')); });
  var t2 = await pg.cmd('Target.createTarget', { url: 'about:blank' }); var list = await (await fetch('http://127.0.0.1:' + pg.port + '/json/list')).json(); var helper = list.filter(function (x) { return x.id === t2.targetId; })[0]; var ws = new WebSocket(helper.webSocketDebuggerUrl); await new Promise(function (r, j) { ws.onopen = r; ws.onerror = j; });
  var mid = 0, pend = {}; ws.onmessage = function (m) { var d = JSON.parse(typeof m.data === 'string' ? m.data : String(m.data)); if (d.id && pend[d.id]) { pend[d.id](d); delete pend[d.id]; } }; function c2(method, params) { return new Promise(function (r, j) { var id = ++mid; pend[id] = function (d) { d.error ? j(new Error(JSON.stringify(d.error))) : r(d.result); }; ws.send(JSON.stringify({ id: id, method: method, params: params || {} })); }); }
  await c2('Runtime.enable'); var ev2 = async function (expr) { var r = await c2('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error('eval2: ' + JSON.stringify(r.exceptionDetails).slice(0, 300)); return r.result.value; };
  await ev2('window.__F = []; window.__T = []; 1'); for (var c0 = 0; c0 < frames.length; c0 += 40) { var chunk = frames.slice(c0, c0 + 40); await ev2('(function(){var d=' + JSON.stringify(chunk.map(function (f) { return f.data; })) + ';var t=' + JSON.stringify(chunk.map(function (f) { return Math.round(f.t - frames[0].t); })) + ';for(var i=0;i<d.length;i++){window.__F.push(d[i]);window.__T.push(t[i]);} return window.__F.length;})()'); }
  var webm = await ev2('(async function(){ var F=window.__F, T=window.__T; var load=function(i){ return new Promise(function(res){ var im=new Image(); im.onload=function(){res(im)}; im.onerror=function(){res(null)}; im.src="data:image/jpeg;base64,"+F[i]; }); }; var first=await load(0); var w=first.width, h=first.height; var cv=document.createElement("canvas"); cv.width=w; cv.height=h; document.body.appendChild(cv); var ctx=cv.getContext("2d"); ctx.drawImage(first,0,0); var stream=cv.captureStream(30); var mime=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"].filter(function(m){return MediaRecorder.isTypeSupported(m)})[0]; var rec=new MediaRecorder(stream,{mimeType:mime, videoBitsPerSecond: 3000000}); var chunks=[]; rec.ondataavailable=function(e){ if(e.data && e.data.size) chunks.push(e.data); }; var done=new Promise(function(res){ rec.onstop=res; }); rec.start(250); var start=performance.now(); for (var i=1;i<F.length;i++){ var im=await load(i); F[i]=null; while(performance.now()-start<T[i]) await new Promise(function(r){ requestAnimationFrame(r); }); if (im) ctx.drawImage(im,0,0); } await new Promise(function(r){ setTimeout(r,300); }); rec.stop(); await done; var blob=new Blob(chunks,{type:mime}); var b64=await new Promise(function(res){ var fr=new FileReader(); fr.onload=function(){res(fr.result.split(",")[1])}; fr.readAsDataURL(blob); }); return {mime:mime, bytes:blob.size, b64:b64}; })()');   /* frames decoded one at a time and released (no 7k-bitmap pile-up) */
  var vpath = path.join(OUT, 'mahworld_s10_review.webm'); fs.writeFileSync(vpath, Buffer.from(webm.b64, 'base64')); console.log('VIDEO FILE ' + vpath + ' ' + webm.bytes + ' bytes ' + dur.toFixed(1) + 's'); ws.close();
  console.log('errors', pg.errors.filter(function (x) { return !/404/.test(x); }));
} finally { await pg.close(); srv.close(); }
