/* MAHWORLD :: Spec A route SERIES — interleaved before/after runs of the test route (spawn → walk 10 s → fly 20 s → land → full attack
   combo) so a comparison is not one run at exact equality: N runs per build per viewport, alternating A/B, medians + spread per phase.
   Writes deploy/probe_out/route_series_<label>.json and a copy under 25_HANDOFF/PASSES/perf/ (tracked evidence).
       node deploy/route_series.mjs <label> <distA> <distB> [runs=3] [viewports=1120x700,390x844] [extra query]
   A = the "before" build, B = the "after" build. Same harness for both (headless Chrome, unlocked frame pacing unless ROUTE_VSYNC=1). */
import fs from 'node:fs'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { fileURLToPath } from 'node:url';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var OUT = path.join(HERE, 'probe_out'); var EVID = path.resolve(HERE, '..', '..', '25_HANDOFF', 'PASSES', 'perf');
var label = process.argv[2], A = path.resolve(process.argv[3] || ''), B = path.resolve(process.argv[4] || ''); var runs = +(process.argv[5] || 3); var vps = (process.argv[6] || '1120x700,390x844').split(','); var extra = process.argv[7] || '';
if (!label || !fs.existsSync(A) || !fs.existsSync(B)) { console.error('usage: node deploy/route_series.mjs <label> <distA> <distB> [runs] [viewports] [extra query]'); process.exit(2); }
function med(a) { var s = a.slice().sort(function (x, y) { return x - y; }); var n = s.length; return n ? (n % 2 ? s[(n - 1) / 2] : (s[n / 2 - 1] + s[n / 2]) / 2) : null; }
function spread(a) { return a.length ? +(Math.max.apply(null, a) - Math.min.apply(null, a)).toFixed(1) : null; }
var series = { label: label, started: new Date().toISOString(), builds: { A: A, B: B }, runs: runs, viewports: vps, harness: { pacing: process.env.ROUTE_VSYNC === '1' ? 'vsync' : 'unlocked', gpu: true }, results: {} };
vps.forEach(function (vp) { series.results[vp] = { A: [], B: [] }; });
for (var i = 0; i < runs; i++) vps.forEach(function (vp) { ['A', 'B'].forEach(function (side) { var dist = side === 'A' ? A : B; var lab = label + '_' + vp + '_' + side + i; var t0 = Date.now(); var r = spawnSync(process.execPath, [path.join(HERE, 'probe_route.mjs'), dist, lab, vp].concat(extra ? [extra] : []), { encoding: 'utf8', timeout: 900000, maxBuffer: 64 * 1024 * 1024 }); var f = path.join(OUT, 'route_' + lab + '.json'); var rep = fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : null; if (!rep) { console.log('run ' + lab + ' FAILED (' + (r.stderr || '').slice(-200) + ')'); series.results[vp][side].push({ run: i, failed: true }); return; } var ok = rep.end_position && Math.hypot(rep.end_position.x, rep.end_position.z + 300) > 5; series.results[vp][side].push({ run: i, file: path.basename(f), seconds: +((Date.now() - t0) / 1000).toFixed(0), route_valid: ok, end_position: rep.end_position, phases: rep.phases, tris: rep.render.triangles, calls: rep.render.calls, pixel_ratio: rep.quality.pixelRatio, tier: rep.quality.tier || null, lab: rep.control_lab_last600 || null }); console.log('run ' + lab + ': route p50 ' + rep.phases.route.p50_ms + ' p95 ' + rep.phases.route.p95_ms + ' p99 ' + rep.phases.route.p99_ms + ' max ' + rep.phases.route.max_ms + (ok ? '' : '  ROUTE INVALID (character did not move)')); }); });
series.summary = {}; vps.forEach(function (vp) { series.summary[vp] = {}; ['A', 'B'].forEach(function (side) { var rs = series.results[vp][side].filter(function (x) { return !x.failed && x.route_valid; }); var S = { valid_runs: rs.length, phases: {} }; ['route', 'walk', 'fly', 'land', 'combo'].forEach(function (ph) { var P = {}; ['p50_ms', 'p95_ms', 'p99_ms', 'max_ms', 'over_25ms_pct', 'over_33ms_pct', 'over_50ms_pct'].forEach(function (k) { var vals = rs.map(function (x) { return x.phases[ph][k]; }); P[k] = { median: med(vals), spread: spread(vals), runs: vals }; }); S.phases[ph] = P; }); S.tris_median = med(rs.map(function (x) { return x.tris; })); S.dropped_pct_proposed_median = med(rs.map(function (x) { return x.lab ? x.lab.dropped_pct : null; }).filter(function (v) { return v !== null; })); series.summary[vp][side] = S; });
  var a = series.summary[vp].A.phases.route, b = series.summary[vp].B.phases.route; series.summary[vp].delta_route = { p95_ms: +(b.p95_ms.median - a.p95_ms.median).toFixed(1), p99_ms: +(b.p99_ms.median - a.p99_ms.median).toFixed(1), max_ms: +(b.max_ms.median - a.max_ms.median).toFixed(1), over_25ms_pct: +(b.over_25ms_pct.median - a.over_25ms_pct.median).toFixed(2), tolerance_ms: +Math.max(0.5, a.p95_ms.spread || 0).toFixed(1), regressed: b.p95_ms.median > a.p95_ms.median + Math.max(0.5, a.p95_ms.spread || 0) };
  console.log('\n' + vp + '  A route p95 ' + a.p95_ms.median + ' (±' + a.p95_ms.spread + ')  B route p95 ' + b.p95_ms.median + ' (±' + b.p95_ms.spread + ')  Δ ' + series.summary[vp].delta_route.p95_ms + ' ms  tolerance ' + series.summary[vp].delta_route.tolerance_ms + '  → ' + (series.summary[vp].delta_route.regressed ? 'REGRESSED' : 'no regression') + '   max A ' + a.max_ms.median + ' → B ' + b.max_ms.median); });
series.finished = new Date().toISOString(); fs.writeFileSync(path.join(OUT, 'route_series_' + label + '.json'), JSON.stringify(series, null, 1)); fs.mkdirSync(EVID, { recursive: true }); fs.writeFileSync(path.join(EVID, 'route_series_' + label + '.json'), JSON.stringify(series, null, 1)); console.log('\nseries → ' + path.join(EVID, 'route_series_' + label + '.json'));
