/* MAHWORLD :: STATIC DEMO SMOKE TEST — serves deploy/static_dist with a dumb static file server (NO api routes, exactly like Netlify),
   opens the page in headless Chrome, and checks the in-page host boots, the game connects, the character loads, movement and a
   transformation go through the authority, and the page reports zero errors.  node 26_LOCAL_AUTHORITY/deploy/test_static_demo.mjs */
import fs from 'node:fs'; import path from 'node:path'; import os from 'node:os'; import net from 'node:net'; import http from 'node:http'; import { spawn } from 'node:child_process'; import { fileURLToPath } from 'node:url';
var HERE = path.dirname(fileURLToPath(import.meta.url)); var DIST = process.argv[2] ? path.resolve(process.argv[2]) : path.join(HERE, 'static_dist');   /* optional: a fresh extraction of the package (Section 2 packaging reruns this from there) */ var OUT = path.join(HERE, 'static_test'); fs.mkdirSync(OUT, { recursive: true });
var MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.json': 'application/json; charset=utf-8', '.glb': 'model/gltf-binary', '.toml': 'text/plain' };
var srv = http.createServer(function (req, res) { var p = decodeURIComponent(new URL(req.url, 'http://x').pathname); if (p === '/') p = '/index.html'; var f = path.join(DIST, p); if (!f.startsWith(DIST) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); return res.end('nf'); } var b = fs.readFileSync(f); res.writeHead(200, { 'content-type': MIME[path.extname(f)] || 'application/octet-stream', 'content-length': b.length }); res.end(b); });
await new Promise(function (r) { srv.listen(0, '127.0.0.1', r); }); var port0 = srv.address().port;
var LIVE = process.argv.indexOf('--live') >= 0 ? process.argv[process.argv.indexOf('--live') + 1] : null;
var url = LIVE ? LIVE : 'http://127.0.0.1:' + port0 + '/CLAUDE_GAMEPLAY_RUNTIME/26_LOCAL_AUTHORITY/lab/play.html?field=1';
function wait(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }
function freePort() { return new Promise(function (res) { var s = net.createServer(); s.listen(0, '127.0.0.1', function () { var p = s.address().port; s.close(function () { res(p); }); }); }); }
var CHROME = process.env.MAHWORLD_CHROME || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
var port = await freePort(); var udd = fs.mkdtempSync(path.join(os.tmpdir(), 'mahworld-static-'));
var chrome = spawn(CHROME, ['--headless=new', '--disable-gpu', '--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--no-first-run', '--no-default-browser-check', '--disable-extensions', '--hide-scrollbars', '--mute-audio', '--remote-debugging-port=' + port, '--user-data-dir=' + udd, 'about:blank'], { stdio: 'ignore' });
var wsUrl = null; for (var i = 0; i < 120 && !wsUrl; i++) { await wait(200); try { var v = await (await fetch('http://127.0.0.1:' + port + '/json/version')).json(); wsUrl = v.webSocketDebuggerUrl; } catch (e) { } }
var ws = new WebSocket(wsUrl); await new Promise(function (r, j) { ws.onopen = r; ws.onerror = j; }); var msgId = 0, pending = {}, sessionId = null, errors = [], logs = [];
ws.onmessage = function (e2) { var m = JSON.parse(e2.data); if (m.id && pending[m.id]) { pending[m.id](m); delete pending[m.id]; } else if (m.method === 'Runtime.exceptionThrown') errors.push(String((m.params.exceptionDetails.exception && m.params.exceptionDetails.exception.description) || m.params.exceptionDetails.text).slice(0, 300)); else if (m.method === 'Runtime.consoleAPICalled' && m.params.type === 'error') logs.push((m.params.args || []).map(function (a) { return a.value || a.description || ''; }).join(' ').slice(0, 200)); };
function cdp(method, params) { return new Promise(function (res, rej) { var id = ++msgId; pending[id] = function (m) { if (m.error) rej(new Error(method + ': ' + JSON.stringify(m.error))); else res(m.result); }; var msg = { id: id, method: method, params: params || {} }; if (sessionId) msg.sessionId = sessionId; ws.send(JSON.stringify(msg)); }); }
var t = await cdp('Target.createTarget', { url: 'about:blank' }); var at = await cdp('Target.attachToTarget', { targetId: t.targetId, flatten: true }); sessionId = at.sessionId;
await cdp('Page.enable'); await cdp('Runtime.enable'); await cdp('Network.enable'); var failedReq = []; ws.addEventListener('message', function (e3) { var m = JSON.parse(e3.data); if (m.method === 'Network.loadingFailed') failedReq.push(m.params.errorText); if (m.method === 'Network.responseReceived' && m.params.response.status >= 400) failedReq.push(m.params.response.status + ' ' + m.params.response.url.slice(-80)); }); await cdp('Emulation.setDeviceMetricsOverride', { width: 430, height: 932, deviceScaleFactor: 1, mobile: true });
await cdp('Page.navigate', { url: url }); await wait(3000);
async function ev(expr) { var r = await cdp('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error('eval: ' + JSON.stringify(r.exceptionDetails).slice(0, 300)); return r.result.value; }
var pass = 0, fail = 0; function ok(c, m, x) { if (c) { pass++; console.log('  PASS ' + m + (x ? ' — ' + x : '')); } else { fail++; console.log('  FAIL ' + m + (x ? ' — ' + x : '')); } }
await ev('1'); console.log('page at', await ev('location.href'));
var hostUp = false; for (var k = 0; k < 40 && !hostUp; k++) { hostUp = await ev('!!(window.MAHWORLD_STATIC_HOST && window.MAHWORLD_STATIC_HOST.host)'); if (!hostUp) await wait(500); }
ok(hostUp, 'in-page authority booted (data + host + tick loop)'); if (!hostUp) { console.log('ERRORS', JSON.stringify(errors.slice(0, 5), null, 1)); console.log('CONSOLE', JSON.stringify(logs.slice(0, 5), null, 1)); }
var playUp = false; for (var k2 = 0; k2 < 60 && !playUp; k2++) { playUp = await ev('!!(window.MAHWORLD_PLAY && window.MAHWORLD_PLAY.snap() && window.MAHWORLD_PLAY.snap().play && window.MAHWORLD_PLAY.snap().play.room)'); if (!playUp) await wait(500); }
ok(playUp, 'the game connected through the in-page /api and entered the field'); if (!playUp) { console.log('ERRORS', JSON.stringify(errors.slice(0, 6), null, 1)); console.log('CONSOLE', JSON.stringify(logs.slice(0, 6), null, 1)); console.log('NET', JSON.stringify(failedReq.slice(0, 12), null, 1)); var sn = await ev('JSON.stringify((function(){ var s = window.MAHWORLD_PLAY && window.MAHWORLD_PLAY.snap(); return s ? { keys: Object.keys(s), play: s.play ? Object.keys(s.play) : null, state: s.state || null, log: (window.MAHWORLD_PLAY.log ? window.MAHWORLD_PLAY.log() : null) } : null; })())'); console.log('SNAP', String(sn).slice(0, 900)); var txt = await ev('document.body.innerText.slice(0, 1500)'); console.log('BODY', JSON.stringify(txt)); var r0 = await cdp('Page.captureScreenshot', { format: 'png' }); fs.writeFileSync(path.join(OUT, 'static_fail.png'), Buffer.from(r0.data, 'base64')); process.exit(1); }
var health = JSON.parse(await ev('fetch(location.pathname.replace(/\\/lab\\/[^/]*$/, "") + "/api/health").then(function (r) { return r.text(); })'));
ok(health.ok && health.static_host === true && health.dev_hooks === false, '/api/health answered by the page host (no dev hooks)', 'lifecycle ' + health.lifecycle + ' tick ' + health.tick);
var slot = await ev('JSON.stringify(window.MAHWORLD_PLAY.slot ? window.MAHWORLD_PLAY.slot() : (window.MAHWORLD_PLAY.snap().listeners || {}))');
var expectAvatar = (function () { try { return JSON.parse(fs.readFileSync(path.join(DIST, 'BUILD_INFO.json'), 'utf8')).athlete.match(/ATHLETE_M_V\d+/)[0]; } catch (e) { return 'ATHLETE_M_V8'; } })();   /* the build stamps the shipped default; the smoke test follows it instead of a hard-coded generation */
ok(new RegExp('"id":"' + expectAvatar + '"').test(slot) && !/"fallback_reason":"[^"]/.test(slot), 'the current character (' + expectAvatar + ') loaded from static files with no fallback', slot.slice(0, 80));
var p0 = JSON.parse(await ev('JSON.stringify(window.MAHWORLD_PLAY.snap().play.position)'));
await ev('window.MAHWORLD_PLAY.send("MOVE",{forward:1,strafe:0,run:true,yaw:0})'); await wait(1800); await ev('window.MAHWORLD_PLAY.send("MOVE",{forward:0,strafe:0,run:false,yaw:0})'); await wait(400);
var p1 = JSON.parse(await ev('JSON.stringify(window.MAHWORLD_PLAY.snap().play.position)'));
var moved = Math.hypot(p1.x - p0.x, p1.z - p0.z); ok(moved > 1, 'movement is authoritative through the page host', moved.toFixed(2) + ' m');
await ev('window.MAHWORLD_PLAY.send("TRANSFORM",{to:"SPLIT"})'); await wait(2600);
var form = await ev('window.MAHWORLD_PLAY.snap().play.form'); ok(form === 'SPLIT', 'SEPARATE goes through the host', 'form ' + form);
var r = await cdp('Page.captureScreenshot', { format: 'png' }); fs.writeFileSync(path.join(OUT, 'static_phone.png'), Buffer.from(r.data, 'base64'));
ok(errors.length === 0 && logs.length === 0, 'zero page errors / console errors', JSON.stringify(errors.concat(logs).slice(0, 3)));
console.log('\n' + pass + ' passed, ' + fail + ' failed · screenshot ' + path.join(OUT, 'static_phone.png'));
try { await cdp('Target.closeTarget', { targetId: t.targetId }); } catch (e) { } ws.close(); chrome.kill(); srv.close(); await wait(300); try { fs.rmSync(udd, { recursive: true, force: true }); } catch (e) { }
process.exit(fail ? 1 : 0);
