/* MAHWORLD JOB B :: WILDLIFE MANAGER (owner next-pass 2026-09-20 §11–§19) — the HOST authority for the FISH, HORSE and GOLDEN PHOENIX:
   placement / population from registry.ecology (habitats), kinematics on the host clock (the client only presents what is published as
   p.wildlife), and COMBAT through the ONE rules field (CreatureCombat.spawnWild → team WILD synthetic combatants; strikes are the field's
   own body-strike cast on the authoritative path; damage / HP / crits / locks are the field's). Species language:
     FISH   — schools cruise under the surface (a seeded loop around the school anchor, depth from data); every so often one BREACHES
              (rise → arc → re-entry) as scenery. PROVOKED (struck, or a player inside aggro_radius_m while the fish is near the surface):
              SWIM → BREACH → HOVER (hover_y_m over the water, circling the player = SWIRL / orient, the wind-up) → LAUNCH (a fast body
              throw through the player, the strike cast when in reach) → RECOVER (a short hover) → LAUNCH again … → RETURN (dive back)
              when the player is beyond the leash or after the fight; glass cannon by data (hits_to_kill 3, kills in ~4.5).
     HORSE  — solitary wander / graze near the class house; DEFENSIVE by data: never initiates; when struck it turns to the threat,
              snorts (state SNORT) and performs a slow threatening FEINT (a lunge that stops short — no cast, no damage), then resumes;
              extremely durable (hits_to_kill 35); it does not flee.
     PHOENIX — a high patrol circuit (alt band from data) over the crown anchor with visits; HOSTILE_AERIAL by data: engages a player
              flying above aggro_min_player_altitude_m inside aggro_radius_m, or whoever struck it: WINDUP (holds ~12 m above the target
              with the aura flaring for windup_s — the visible anticipation) → DIVE (descends through an AERIAL target; the strike cast when
              reach and height both agree) → AERIAL_PASS → CLIMB. A terrain-relative clearance floor is invariant: no ground-height sweep.
              40 s; durable (hits_to_kill 18), kills in ~10.
   Population: bounded by data (active_population), dormant when no player is inside the activation radius (combatant removed, positions
   frozen), KO → dissolve → removed → respawn after respawn_s + seeded jitter (staggered, never a pop-in on the same spot while watched).
   Deterministic: seeded hash of the host clock, no Math.random. Nothing here touches the player controller / HUD / camera. */
import { speciesCombat, spawnWild } from './CreatureCombat.js';
var TWO_PI = Math.PI * 2, G = 9.81;
function hash01(a, b, c) { var h = 2166136261; [a, b, c].forEach(function (v) { var s = String(v); for (var i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; } h ^= 0x9e3779b9; h = Math.imul(h ^ (h >>> 15), 2246822507) >>> 0; }); return (h >>> 8) / 16777216; }
function dist(a, b) { return Math.hypot(a.x - b.x, a.z - b.z); }
function turn(cur, want, k) { var diff = Math.atan2(Math.sin(want - cur), Math.cos(want - cur)); return cur + diff * Math.min(1, k); }
function num(v, d) { return typeof v === 'number' && isFinite(v) ? v : d; }
function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }
function smooth(u) { u = clamp(u, 0, 1); return u * u * (3 - 2 * u); }

/* o = { registry, H, rec, rulesField(), colliders(), players(), strikeSkill } */
export function createWildlifeManager(o) {
  var reg = o.registry; var ECO = reg && reg.ecology && reg.ecology.species || {}; var H = o.H; var rec = o.rec || function () { };
  var COAST = reg && reg.coast || {}; var O = COAST.outline || { x1: -203, z1: -86, x2: 203, z2: 322 }; var WL = COAST.waterline_d || 8; var SEA_Y = COAST.sea_y !== undefined ? COAST.sea_y : -0.3;
  var CB = { FISH: speciesCombat(reg, 'FISH'), HORSE: speciesCombat(reg, 'HORSE'), PHOENIX: speciesCombat(reg, 'PHOENIX') };
  var list = [];   /* every creature record */
  function rf() { return o.rulesField(); } function col() { return o.colliders(); }
  function terrainY(x, z) { var t = 0; ((reg.terraces && reg.terraces.list) || []).forEach(function (T) { if (x >= T.x1 && x <= T.x2 && z >= T.z1 && z <= T.z2 && T.h > t) t = T.h; }); return t; }
  function groundAt(x, z, refY) { var CP = col(); return CP && CP.groundHeight ? CP.groundHeight(x, z, refY === undefined ? terrainY(x, z) : refY) : 0; }
  function nearestPlayer(p) { var best = null, bd = 1e9; (o.players() || []).forEach(function (a) { var d = dist(a.pos, p); if (d < bd) { bd = d; best = a; } }); return { a: best, d: bd }; }
  function playerY(a) { return a && a.fl ? (a.fl.altitude || 0) : 0; }
  function strikeOf(f, cb) { var own = f.skillsFor ? f.skillsFor(cb) : null; var first = own && own.PHYSICAL ? own.PHYSICAL.filter(Boolean)[0] : null; return first ? first.id : (o.strikeSkill || 'PA_PUSH'); }

  /* ---------- placement from the registry (habitats) ---------- */
  function fishSchools() {
    var sp = ECO.FISH || {}; var Hb = sp.habitat || {}; var d0 = num(Hb.from_waterline_m, 14), d1 = num(Hb.to_waterline_m, 70); var mid = (d0 + d1) / 2 + WL; var out = [];
    var anchors = [{ id: 'S', x: 0, z: O.z1 - mid }, { id: 'E', x: O.x2 + mid, z: 40 }, { id: 'W', x: O.x1 - mid, z: 170 }, { id: 'N', x: 60, z: O.z2 + mid }];
    (Hb.bodies || []).forEach(function (b) { anchors.push({ id: b.id, x: b.x, z: b.z, rx: b.rx, rz: b.rz, surface_y: b.surface_y, depth_m: b.depth_m || null, pond: true }); });   /* sanctuary water bodies (registry water bodies with fish) */
    var nS = Math.max(1, num(sp.pool && sp.pool.schools, 3)), per = Math.max(1, num(sp.pool && sp.pool.per_school, 4)); var M = sp.motion || {}; var depth = M.depth_m || [-0.9, -2.2];
    for (var s = 0; s < Math.min(nS, anchors.length); s++) { var A = anchors[s]; out.push({ id: A.id, cx: A.x, cz: A.z, rx: A.rx || (22 + 14 * hash01('S', s, 'rx')), rz: A.rz || (16 + 12 * hash01('S', s, 'rz')), period: 70 + 30 * hash01('S', s, 'p'), ph: TWO_PI * hash01('S', s, 'ph'), surface_y: A.surface_y !== undefined ? A.surface_y : SEA_Y, depth: A.depth_m || depth, per: per, nextBreach: 8 + 8 * hash01('S', s, 'b'), pond: !!A.pond }); }
    return out;
  }
  function build() {
    if (ECO.FISH) fishSchools().forEach(function (S, si) { for (var i = 0; i < S.per; i++) { var id = 'WILD_FISH_' + S.id + '_' + (i + 1); list.push({ id: id, species: 'FISH', school: S, idx: i, seed: 0xF15 + si * 131 + i * 17, pos: { x: S.cx, z: S.cz }, y: S.depth[0], facing: 0, speed: 0, state: 'DORMANT', active: false, combatant: null, actor: null, koAt: null, respawnAt: 0, off: [(i - (S.per - 1) / 2) * 1.6 * (i % 2 ? 1 : -1) + 0.5, -i * 2.6 - 1.2, TWO_PI * hash01(id, 0, 'o')], depth: S.depth[0] + (S.depth[1] - S.depth[0]) * hash01(id, 1, 'd'), breach: null, fight: null, home: { x: S.cx, z: S.cz } }); } });
    if (ECO.HORSE) { var HB = ECO.HORSE.habitat || {}; var RG = reg.regions && reg.regions.list || []; var spots = HB.spots || null; if (!spots) { var region = RG.filter(function (r) { return r.id === HB.region; })[0]; var rects = region && region.shape && region.shape.rects ? region.shape.rects : []; spots = rects.map(function (r, ri) { var cx = (r.x1 + r.x2) / 2, cz = (r.z1 + r.z2) / 2; var C0 = col(); var free = function (x, z) { if (!C0 || !C0.blockedAt) return true; if (C0.blockedAt(x, z, 0)) return false; for (var a = 0; a < 8; a++) { if (C0.blockedAt(x + Math.cos(a * Math.PI / 4) * 6, z + Math.sin(a * Math.PI / 4) * 6, 0)) return false; } return true; }; var x = cx, z = cz; if (!free(x, z)) { for (var t = 0; t < 40; t++) { var qx = r.x1 + 6 + hash01('HS', ri, t) * (r.x2 - r.x1 - 12), qz = r.z1 + 6 + hash01('HS', ri, t + 100) * (r.z2 - r.z1 - 12); if (free(qx, qz)) { x = qx; z = qz; break; } } } return { x: x, z: z, r: Math.min(r.x2 - r.x1, r.z2 - r.z1) / 2 - 4, rect: r }; }); }   /* never inside a landmark: the spot must be clear of colliders (6 m all round) */
      var maxH = num(ECO.HORSE.pool && ECO.HORSE.pool.max_active, 2); spots.slice(0, Math.max(maxH, spots.length)).forEach(function (sp, i) { var id = 'WILD_HORSE_' + (i + 1); list.push({ id: id, species: 'HORSE', seed: 0x40 + i * 977, pos: { x: sp.x, z: sp.z }, y: groundAt(sp.x, sp.z), facing: TWO_PI * hash01(id, 0, 'f'), speed: 0, state: 'DORMANT', active: false, combatant: null, actor: null, koAt: null, respawnAt: 0, home: { x: sp.x, z: sp.z }, range: sp.r || 26, rect: sp.rect || null, goal: null, goalK: -1, grazeUntil: 0, reactUntil: 0, feint: null, threat: null }); }); }
    if (ECO.PHOENIX) { var PH = ECO.PHOENIX.habitat || {}; var anchors = PH.anchors || [PH.anchor || { x: 60, z: 330, r: 120 }]; var maxP = num(ECO.PHOENIX.pool && ECO.PHOENIX.pool.max_active, 1); anchors.slice(0, Math.max(1, maxP)).forEach(function (A, i) { var id = 'WILD_PHOENIX_' + (i + 1); var alt = PH.alt_m || [80, 96]; list.push({ id: id, species: 'PHOENIX', seed: 0x9E0 + i * 313, pos: { x: A.x + A.r, z: A.z }, y: alt[1] - 2, facing: 0, speed: 0, state: 'DORMANT', active: false, combatant: null, actor: null, koAt: null, respawnAt: 0, anchor: A, alt: alt, visits: PH.visits || [], leg: 0, orbitA: 0, lastA: null, legT: 0, fight: null, home: { x: A.x, z: A.z } }); }); }
    rec('WILDLIFE_BUILD', { fish: list.filter(function (c) { return c.species === 'FISH'; }).length, horses: list.filter(function (c) { return c.species === 'HORSE'; }).length, phoenix: list.filter(function (c) { return c.species === 'PHOENIX'; }).length });
  }
  build();

  /* ---------- activation (combatant on / off) ---------- */
  var ACT = { FISH: 260, HORSE: 200, PHOENIX: 700 }, DORM = { FISH: 320, HORSE: 260, PHOENIX: 900 };
  function activate(c) { var f = rf(); if (!f || f.combatant(c.id)) return; var cb = CB[c.species]; c.actor = { pos: c.pos, facing: c.facing, guard: null, fl: null, dash: null, wildlife: c.species }; c.combatant = spawnWild(f, c.id, 'ATHLETE', c.pos, cb, { facing: c.facing, strike_skill: o.strikeSkill || 'PA_PUSH', altitude: c.y }); c.combatant.actor = c.actor; c.combatant.creature = c.species; c.active = true; c.koAt = null; c.state = c.species === 'FISH' ? 'SWIM' : (c.species === 'HORSE' ? 'GRAZE' : 'PATROL'); rec('WILDLIFE_ACTIVATE', { id: c.id, hp: c.combatant.max, damage_mult: c.combatant.balance.damage_mult }); }
  function deactivate(c, why) { var f = rf(); if (f && f.combatant(c.id)) f.removeSynthetic(c.id); c.combatant = null; c.actor = null; c.active = false; c.state = 'DORMANT'; c.speed = 0; c.fight = null; c.breach = null; c.feint = null; c.koAt = null; rec('WILDLIFE_DORMANT', { id: c.id, why: why }); }
  function koHandling(c, cb) { if (!cb.ko) return false; var cbx = CB[c.species]; if (c.koAt === null) { c.koAt = H.t; c.fight = null; c.breach = null; rec('WILDLIFE_DEFEATED', { id: c.id, species: c.species }); } c.state = 'KO'; c.speed = 0; if (H.t - c.koAt >= 2.6) { c.respawnAt = H.t + cbx.respawn_s + cbx.respawn_jitter_s * hash01(c.seed, Math.floor(H.t), 'rj'); c.pos.x = c.home.x; c.pos.z = c.home.z; if (c.species === 'FISH') c.y = c.depth; if (c.species === 'PHOENIX') c.y = c.alt[1] - 2; deactivate(c, 'DEFEATED'); rec('WILDLIFE_RESPAWN_SCHEDULED', { id: c.id, in_s: +(c.respawnAt - H.t).toFixed(1) }); } return true; }
  function moveXZ(c, tx, tz, speed, dt, useColliders) { var dx = tx - c.pos.x, dz = tz - c.pos.z; var d = Math.hypot(dx, dz); if (d < 1e-6) { c.speed = 0; return true; } var step = Math.min(speed * dt, d); var nx = c.pos.x + dx / d * step, nz = c.pos.z + dz / d * step; if (useColliders) { var mv = col().resolveMove(c.pos, dx / d * step, dz / d * step, 0); nx = mv.x; nz = mv.z; } var moved = Math.hypot(nx - c.pos.x, nz - c.pos.z); c.pos.x = nx; c.pos.z = nz; c.speed = dt > 0 ? moved / dt : 0; c.facing = turn(c.facing, Math.atan2(dx, -dz), dt * 6); if (c.actor) c.actor.facing = c.facing; return d - step < 0.05; }
  function tryStrike(c, f, cb, pl) { var r = f.cast(cb, { skill_id: strikeOf(f, cb) }); if (r.ok) rec('WILDLIFE_STRIKE', { id: c.id, species: c.species, at: pl ? (pl.account_id || null) : null }); return r.ok; }

  /* ---------- FISH ---------- */
  function schoolPos(S, t, out) { var a = t * TWO_PI / S.period + S.ph; out.x = S.cx + Math.cos(a) * S.rx; out.z = S.cz + Math.sin(a) * S.rz; out.hx = -Math.sin(a) * S.rx; out.hz = Math.cos(a) * S.rz; var l = Math.hypot(out.hx, out.hz) || 1; out.hx /= l; out.hz /= l; }
  var SP = { x: 0, z: 0, hx: 0, hz: 1 };
  function fishTick(c, dt, f) {
    var cb = c.combatant; var S = c.school; var K = CB.FISH; var np = nearestPlayer(c.pos); var pl = np.a; var sy = S.surface_y; var hitAgo = cb.last_hit_t === undefined ? 99 : H.t - cb.last_hit_t;
    var M = ECO.FISH.motion || {}; var cruise = num(K.speed_mps.swim, 1.6), hoverSpd = num(K.speed_mps.hover, 4.5), launchSpd = num(K.speed_mps.launch, 13); var hoverY = sy + num(K.hover_y_m, 1.3);
    /* provocation: struck, or a player wading / flying low inside the aggro radius */
    var provoked = hitAgo < 12 || (pl && np.d < K.aggro_radius_m && playerY(pl) < sy + 6 && K.aggression !== 'PASSIVE');
    if (c.fight) { var Fg = c.fight; var fromHome = dist(c.pos, c.home);
      if (!pl || np.d > K.leash_m || fromHome > K.leash_m + 10 || (H.t - Fg.t0 > 45 && hitAgo > 12)) { c.fight = null; c.state = 'RETURN'; c.breach = null; c.noEngageUntil = H.t + 8; rec('WILDLIFE_DISENGAGE', { id: c.id }); }
      else {
        var ty = hoverY; var dxp = pl.pos.x - c.pos.x, dzp = pl.pos.z - c.pos.z; var dp = Math.hypot(dxp, dzp);
        if (Fg.phase === 'RISE') { c.y += (sy + 0.6 - c.y) * Math.min(1, dt * 4); c.speed = 0; c.facing = turn(c.facing, Math.atan2(dxp, -dzp), dt * 5); if (c.y > sy + 0.3) { Fg.phase = 'HOVER'; Fg.t1 = H.t; c.state = 'BREACH'; rec('WILDLIFE_BREACH', { id: c.id, fight: true }); } }
        else if (Fg.phase === 'HOVER') { c.y += (ty - c.y) * Math.min(1, dt * 3); /* SWIRL: orbit the player inside melee reach (combat.swirl_radius_m, B7 §2) while the wind-up runs */ var swR = num(K.swirl_radius_m, 2.3); var ang = Math.atan2(c.pos.z - pl.pos.z, c.pos.x - pl.pos.x) + dt * 1.6; var ox = pl.pos.x + Math.cos(ang) * swR, oz = pl.pos.z + Math.sin(ang) * swR; moveXZ(c, ox, oz, hoverSpd, dt, false); c.facing = turn(c.facing, Math.atan2(dxp, -dzp), dt * 6); c.state = 'SWIRL'; if (H.t - Fg.t1 >= K.windup_s && H.t >= Fg.nextLaunch) { Fg.phase = 'LAUNCH'; Fg.t1 = H.t; Fg.lx = dxp / (dp || 1); Fg.lz = dzp / (dp || 1); Fg.hit = false; rec('WILDLIFE_WINDUP_DONE', { id: c.id }); } }
        else if (Fg.phase === 'LAUNCH') { c.state = 'LAUNCH'; var st = launchSpd * dt; c.pos.x += Fg.lx * st; c.pos.z += Fg.lz * st; c.speed = launchSpd; c.facing = Math.atan2(Fg.lx, -Fg.lz); c.y += ((playerY(pl) + 0.9) - c.y) * Math.min(1, dt * 6); var dNow = dist(c.pos, pl.pos); if (!Fg.hit && dNow < 2.4 && Math.abs(c.y - playerY(pl)) < 1.6) { Fg.hit = tryStrike(c, f, cb, pl); } if (H.t - Fg.t1 > 0.75 || (Fg.hit && dNow > 3)) { Fg.phase = 'RECOVER'; Fg.t1 = H.t; Fg.nextLaunch = H.t + K.attack_cooldown_s; Fg.launches++; } }
        else if (Fg.phase === 'RECOVER') { c.state = 'RECOVER'; c.y += (ty + 0.4 - c.y) * Math.min(1, dt * 3); c.speed *= 0.8; c.facing = turn(c.facing, Math.atan2(dxp, -dzp), dt * 4); if (H.t - Fg.t1 > 0.9) { Fg.phase = 'HOVER'; Fg.t1 = H.t - K.windup_s * 0.5; } }
        cb.altitude = c.y; c.actor.facing = c.facing; return; } }
    if (provoked && pl && !c.fight && K.hits_to_kill_player && np.d < K.leash_m && H.t >= (c.noEngageUntil || 0)) { c.fight = { t0: H.t, phase: 'RISE', t1: H.t, nextLaunch: 0, launches: 0, target: pl }; c.breach = null; c.state = 'RISE'; rec('WILDLIFE_ENGAGE', { id: c.id, species: 'FISH', why: hitAgo < 12 ? 'STRUCK' : 'PROVOKED' }); cb.altitude = c.y; return; }
    if (c.state === 'RETURN') { moveXZ(c, c.home.x, c.home.z, cruise * 1.6, dt, false); c.y += (c.depth - c.y) * Math.min(1, dt * 2); if (dist(c.pos, c.home) < S.rx * 0.8 && c.y < Math.max(c.depth + 0.05, sy - Math.min(0.5, (sy - c.depth) * 0.6))) c.state = 'SWIM';   /* review 2026-09-20: a shallow pond school (depth −0.3) can never be 0.5 m under its surface — the exit is relative to its own depth */ cb.altitude = c.y; return; }
    /* scenery: the school loop + a breach now and then */
    schoolPos(S, H.t, SP); var lat = c.off[0], back = c.off[1]; var tx = SP.x + SP.hx * back - SP.hz * lat, tz = SP.z + SP.hz * back + SP.hx * lat;
    if (c.breach) { var B = c.breach; var u = H.t - B.t0; var rise = 0.8, vz0 = Math.sqrt(2 * G * num(M.breach_height_m, 2.4)), air = 2 * vz0 / G, dive = 0.7, vh = num(M.breach_speed_mps, 6.5) * 0.55;
      if (u < rise) { var k = smooth(u / rise); c.pos.x = B.x + B.hx * vh * u * 0.5; c.pos.z = B.z + B.hz * vh * u * 0.5; c.y = B.y0 + (sy - B.y0) * k; c.state = 'RISE'; }
      else if (u < rise + air) { var ta = u - rise; c.pos.x = B.x + B.hx * (vh * rise * 0.5 + vh * ta); c.pos.z = B.z + B.hz * (vh * rise * 0.5 + vh * ta); c.y = sy + vz0 * ta - 0.5 * G * ta * ta; c.state = 'BREACH'; }
      else if (u < rise + air + dive) { var td = (u - rise - air) / dive; c.pos.x += B.hx * vh * 0.6 * dt; c.pos.z += B.hz * vh * 0.6 * dt; c.y = sy + (c.depth - sy) * smooth(td); c.state = 'DIVE'; }
      else { c.breach = null; c.state = 'SWIM'; }
      c.speed = vh; c.facing = Math.atan2(B.hx, -B.hz); cb.altitude = c.y; c.actor.facing = c.facing; return; }
    var k2 = Math.min(1, dt * 1.4); var nx = c.pos.x + (tx - c.pos.x) * k2, nz = c.pos.z + (tz - c.pos.z) * k2; var vx = (nx - c.pos.x) / Math.max(1e-3, dt), vz = (nz - c.pos.z) / Math.max(1e-3, dt); var spd = Math.hypot(vx, vz); if (spd > 0.05) c.facing = turn(c.facing, Math.atan2(vx, -vz), dt * 3); c.pos.x = nx; c.pos.z = nz; c.speed = spd; var bobA = S.pond ? 0.03 : 0.25; var yTarget = c.depth + bobA * Math.sin(H.t * 0.6 + c.off[2]); if (S.pond) yTarget = Math.min(sy - 0.08, yTarget); c.y += (yTarget - c.y) * Math.min(1, dt * 1.2); c.state = 'SWIM';   /* a pond school bobs inside its 0.3 m column, never through the surface (review 2026-09-20) */
    if (S.breacher === undefined) S.breacher = null; S.nextBreach -= dt / S.per; if (S.nextBreach <= 0 && S.breacher === null && c.idx === Math.floor(hash01(S.id, Math.floor(H.t / 7), 'w') * S.per)) { S.breacher = c.id; S.nextBreach = 9 + 13 * hash01(S.id, Math.floor(H.t), 'nb'); c.breach = { t0: H.t, x: c.pos.x, z: c.pos.z, hx: -Math.sin(c.facing), hz: -Math.cos(c.facing), y0: c.y }; rec('WILDLIFE_BREACH', { id: c.id, fight: false }); }
    if (S.breacher === c.id && !c.breach) S.breacher = null;
    cb.altitude = c.y; c.actor.facing = c.facing;
  }

  /* ---------- HORSE ---------- */
  function horseTick(c, dt, f) {
    var cb = c.combatant; var K = CB.HORSE; var np = nearestPlayer(c.pos); var pl = np.a; var hitAgo = cb.last_hit_t === undefined ? 99 : H.t - cb.last_hit_t; var walk = num(K.speed_mps.walk, 1.3), trot = num(K.speed_mps.trot, 3.4), feintSpd = num(K.speed_mps.feint, 6);
    if (hitAgo < 0.3 && c.state !== 'FEINT') { c.state = 'HIT'; c.speed = 0; c.threat = cb.last_hit_from ? { x: cb.last_hit_from.x, z: cb.last_hit_from.z } : (pl ? { x: pl.pos.x, z: pl.pos.z } : null); c.reactUntil = H.t + 6; if (c.threat && H.t >= (c.nextFeint || 0)) { c.feint = { t0: H.t + num(K.windup_s, 0.8), start: { x: c.pos.x, z: c.pos.z } }; c.nextFeint = H.t + K.attack_cooldown_s; rec('WILDLIFE_REACT', { id: c.id, species: 'HORSE', motion: 'SNORT_FEINT' }); } return; }
    if (c.feint) { var Fe = c.feint; var thr = pl ? pl.pos : c.threat; if (!thr) { c.feint = null; } else { var want = Math.atan2(thr.x - c.pos.x, -(thr.z - c.pos.z)); c.facing = turn(c.facing, want, dt * 6); c.actor.facing = c.facing;
      if (H.t < Fe.t0) { c.state = 'SNORT'; c.speed = 0; return; }   /* the wind-up: faces the threat, snorts */
      var dT = dist(c.pos, thr); var stopAt = 1.6; if (dT > stopAt && H.t - Fe.t0 < 0.7) { moveXZ(c, thr.x, thr.z, feintSpd, dt, true); c.state = 'FEINT'; return; }
      c.feint = null; c.state = 'HOLD'; c.speed = 0; c.holdUntil = H.t + 1.2; return; } }
    if (c.holdUntil && H.t < c.holdUntil) { c.state = 'HOLD'; c.speed = 0; if (pl) { c.facing = turn(c.facing, Math.atan2(pl.pos.x - c.pos.x, -(pl.pos.z - c.pos.z)), dt * 4); c.actor.facing = c.facing; } return; }
    if (H.t < c.reactUntil && pl && np.d < 14) { c.state = 'WATCH'; c.speed = 0; c.facing = turn(c.facing, Math.atan2(pl.pos.x - c.pos.x, -(pl.pos.z - c.pos.z)), dt * 3); c.actor.facing = c.facing; return; }   /* confident: stands and watches the threat */
    /* wander / graze */
    if (H.t < c.grazeUntil) { c.state = 'GRAZE'; c.speed = 0; return; }
    var k = Math.floor(H.t / 14); if (k !== c.goalK) { c.goalK = k; var rr = c.range * (0.35 + 0.65 * hash01(c.seed, k, 'r')); var th = TWO_PI * hash01(c.seed, k, 'a'); var gx = c.home.x + Math.cos(th) * rr, gz = c.home.z + Math.sin(th) * rr; if (c.rect) { gx = clamp(gx, c.rect.x1 + 4, c.rect.x2 - 4); gz = clamp(gz, c.rect.z1 + 4, c.rect.z2 - 4); } c.goal = { x: gx, z: gz }; c.trot = hash01(c.seed, k, 't') < 0.25; }
    if (c.goal && dist(c.pos, c.goal) > 1.2) { var blocked = moveXZ(c, c.goal.x, c.goal.z, c.trot ? trot : walk, dt, true); if (blocked === true || c.speed < 0.05) { c.goal = null; c.grazeUntil = H.t + 3; } c.state = c.trot ? 'TROT' : 'WALK'; }
    else { c.goal = null; c.grazeUntil = H.t + 4 + 5 * hash01(c.seed, k, 'g'); c.state = 'GRAZE'; c.speed = 0; }
  }

  /* ---------- PHOENIX ---------- */
  /* owner B8 §6: BUILDING CLEARANCE — the giant wings never scrape a façade. Before every aerial move the path ahead (12 / 24 / 36 m, the
     wing width ± 6 m, from 10 m below the body to 2 m above) is probed against the solid colliders; a hit steers the heading around the
     obstacle on a remembered side and adds a climb boost that decays. A body already inside a column (the temple spires reach 106 m) climbs hard. */
  function steerClear(c, tx, tz, dt) { var C = col(); if (!C || !C.solidAt) return [tx, tz]; var dx = tx - c.pos.x, dz = tz - c.pos.z; var d = Math.hypot(dx, dz) || 1; var ux = dx / d, uz = dz / d; var lx = -uz, lz = ux; var blocked = false; var inside = !!(C.solidAt(c.pos.x, c.pos.z, c.y - 10) || C.solidAt(c.pos.x, c.pos.z, c.y - 4));
    for (var sIdx = 1; sIdx <= 3 && !blocked; sIdx++) { for (var w = -1; w <= 1 && !blocked; w++) { var px = c.pos.x + ux * 12 * sIdx + lx * 6 * w, pz = c.pos.z + uz * 12 * sIdx + lz * 6 * w; if (C.solidAt(px, pz, c.y - 10) || C.solidAt(px, pz, c.y - 4) || C.solidAt(px, pz, c.y + 2)) blocked = true; } }
    if (inside) { c.climbBoost = 16; c.clearanceHits = (c.clearanceHits || 0) + 1; }
    if (!blocked && !inside) { c.steer = c.steer ? c.steer * Math.max(0, 1 - dt * 0.9) : 0; return [tx, tz]; }
    if (blocked) { c.clearanceHits = (c.clearanceHits || 0) + 1; if (!c.steerSide) c.steerSide = hash01(c.id, 3, 'side') < 0.5 ? 1 : -1; c.steer = Math.min(1.35, (c.steer || 0) + dt * 1.8); c.climbBoost = Math.max(c.climbBoost || 0, 10); }
    var ang = (c.steerSide || 1) * (c.steer || 0.6); var rx = ux * Math.cos(ang) - uz * Math.sin(ang), rz = ux * Math.sin(ang) + uz * Math.cos(ang); return [c.pos.x + rx * 36, c.pos.z + rz * 36]; }
  function phoenixTick(c, dt, f) {
    var cb = c.combatant; var K = CB.PHOENIX; var np = nearestPlayer(c.pos); var pl = np.a; var hitAgo = cb.last_hit_t === undefined ? 99 : H.t - cb.last_hit_t; var cruise = num(K.speed_mps.cruise, 9), diveSpd = num(K.speed_mps.dive, 16), climbSpd = num(K.speed_mps.climb, 7);
    var minClear = num(ECO.PHOENIX.habitat && ECO.PHOENIX.habitat.min_terrain_clearance_m, 10); var ownFloor = groundAt(c.pos.x, c.pos.z, c.y) + minClear; if (c.y < ownFloor) { c.y = ownFloor; c.climbBoost = Math.max(c.climbBoost || 0, minClear); c.clearanceHits = (c.clearanceHits || 0) + 1; }
    var engage = pl && K.hits_to_kill_player && np.d < K.leash_m && H.t >= (c.noEngageUntil || 0) && (hitAgo < 15 || (np.d < K.aggro_radius_m && playerY(pl) >= num(K.aggro_min_player_altitude_m, 30)));
    if (!c.fight && engage) { c.fight = { t0: H.t, phase: 'WINDUP', t1: H.t, next: 0, dives: 0 }; rec('WILDLIFE_ENGAGE', { id: c.id, species: 'PHOENIX', why: hitAgo < 15 ? 'STRUCK' : 'FLYER_IN_TERRITORY' }); }
    if (c.fight) { var Fg = c.fight; var far = !pl || np.d > K.leash_m || (H.t - Fg.t0 > 40 && hitAgo > 15);
      if (far) { c.fight = null; c.state = 'CLIMB'; c.noEngageUntil = H.t + 12; rec('WILDLIFE_DISENGAGE', { id: c.id }); }
      else { var py = playerY(pl); var dxp = pl.pos.x - c.pos.x, dzp = pl.pos.z - c.pos.z; var dp = Math.hypot(dxp, dzp);
        if (Fg.phase === 'WINDUP') { c.state = 'WINDUP'; var targetFloor = groundAt(pl.pos.x, pl.pos.z, py) + minClear; var ty = Math.max(py + 12, targetFloor + 4); c.y += (ty - c.y) * Math.min(1, dt * 1.5); var ang = Math.atan2(c.pos.z - pl.pos.z, c.pos.x - pl.pos.x) + dt * 0.9; var stW = steerClear(c, pl.pos.x + Math.cos(ang) * 6, pl.pos.z + Math.sin(ang) * 6, dt); moveXZ(c, stW[0], stW[1], cruise * 0.7, dt, false); c.facing = turn(c.facing, Math.atan2(dxp, -dzp), dt * 4); if (H.t - Fg.t1 >= K.windup_s && H.t >= Fg.next) { Fg.phase = 'DIVE'; Fg.t1 = H.t; Fg.hit = false; Fg.dx = dxp / (dp || 1); Fg.dz = dzp / (dp || 1); Fg.ty = Math.max(py + 0.6, targetFloor); rec('WILDLIFE_WINDUP_DONE', { id: c.id, target_y: +Fg.ty.toFixed(2), clearance_m: minClear }); } }
        else if (Fg.phase === 'DIVE') { c.state = 'DIVE'; var dx = pl.pos.x - c.pos.x, dz = pl.pos.z - c.pos.z, targetGround = groundAt(pl.pos.x, pl.pos.z, py), targetY = Math.max(py + 0.6, targetGround + minClear), dy = targetY - c.y; var L = Math.hypot(dx, dz, dy) || 1; var st = diveSpd * dt; c.pos.x += dx / L * st; c.pos.z += dz / L * st; c.y = Math.max(c.y + dy / L * st, groundAt(c.pos.x, c.pos.z, c.y) + minClear); c.speed = diveSpd; c.facing = turn(c.facing, Math.atan2(dx, -dz), dt * 7); var dNow = dist(c.pos, pl.pos); if (!Fg.hit && dNow < 3 && Math.abs(c.y - py) < 1.6) Fg.hit = tryStrike(c, f, cb, pl); if (Fg.hit || H.t - Fg.t1 > 2.2 || (dNow < 1.5)) { Fg.phase = 'AERIAL_PASS'; Fg.t1 = H.t; Fg.next = H.t + K.attack_cooldown_s; Fg.dives++; Fg.sweepAng = Math.atan2(c.pos.z - pl.pos.z, c.pos.x - pl.pos.x); } }
        else if (Fg.phase === 'AERIAL_PASS') { /* latest master direction: the recovery arc stays AIRBORNE. A grounded player sees the pass overhead and must answer with ranged combat or flight; it never drops into a ground-height melee sweep. */ c.state = 'AERIAL_PASS'; var swR2 = num(K.sweep_radius_m, 2.2); Fg.sweepAng += dt * 1.4; var sx = pl.pos.x + Math.cos(Fg.sweepAng) * swR2, sz = pl.pos.z + Math.sin(Fg.sweepAng) * swR2; var stS = steerClear(c, sx, sz, dt); moveXZ(c, stS[0], stS[1], cruise * 0.75, dt, false); var passY = Math.max(py + 0.4, groundAt(c.pos.x, c.pos.z, c.y) + minClear); c.y += (passY - c.y) * Math.min(1, dt * 5); c.facing = turn(c.facing, Math.atan2(pl.pos.x - c.pos.x, -(pl.pos.z - c.pos.z)), dt * 5); if (H.t - Fg.t1 > num(K.sweep_s, 1.4)) { Fg.phase = 'CLIMB'; Fg.t1 = H.t; } }
        else { c.state = 'CLIMB'; var tyc = Math.max(py + 14, c.alt[0] - 20); c.y += Math.sign(tyc - c.y) * Math.min(Math.abs(tyc - c.y), climbSpd * dt); var stC = steerClear(c, pl.pos.x + Fg.dx * 18, pl.pos.z + Fg.dz * 18, dt); moveXZ(c, stC[0], stC[1], cruise, dt, false); if (H.t - Fg.t1 > 1.6 && Math.abs(c.y - tyc) < 3) { Fg.phase = 'WINDUP'; Fg.t1 = H.t; } }
        c.y = Math.max(c.y, groundAt(c.pos.x, c.pos.z, c.y) + minClear); cb.altitude = c.y; c.actor.facing = c.facing; return; } }
    /* patrol: the anchor circuit with visits, at the altitude band */
    var A = c.anchor; var legs = [{ c: A, laps: 1.5, alt: c.alt[1] - 2 }].concat((c.visits || []).map(function (v, i) { return { c: v, laps: i === 0 ? 0.75 : 1, alt: c.alt[0] + 4 + i * 3 }; })); var cur = legs[c.leg % legs.length]; var C0 = cur.c; var dxa = c.pos.x - C0.x, dza = c.pos.z - C0.z; var rr = Math.hypot(dxa, dza); var a = Math.atan2(dza, dxa); var tx, tz;
    if (rr > C0.r * 1.25) { tx = C0.x + Math.cos(a) * C0.r; tz = C0.z + Math.sin(a) * C0.r; c.state = 'TRAVEL'; } else { var a2 = a + 0.35; tx = C0.x + Math.cos(a2) * C0.r; tz = C0.z + Math.sin(a2) * C0.r; if (c.lastA !== null) c.orbitA += Math.atan2(Math.sin(a - c.lastA), Math.cos(a - c.lastA)); c.lastA = a; c.state = 'PATROL'; if (Math.abs(c.orbitA) > cur.laps * TWO_PI) { c.leg = (c.leg + 1) % legs.length; c.orbitA = 0; c.lastA = null; } }
    var stp = steerClear(c, tx, tz, dt); moveXZ(c, stp[0], stp[1], cruise, dt, false); var altT = cur.alt + (c.climbBoost || 0); c.climbBoost = (c.climbBoost || 0) * Math.max(0, 1 - dt * 0.5); c.y += clamp((Math.min(num(ECO.PHOENIX.habitat && ECO.PHOENIX.habitat.ceiling_m, 100) + 8, altT) - c.y) * 0.4, -3, 4) * dt; c.y = Math.max(c.y, groundAt(c.pos.x, c.pos.z, c.y) + minClear); cb.altitude = c.y; c.actor.facing = c.facing;
  }

  function tick(dt) { var f = rf(); if (!f) return;
    for (var i = 0; i < list.length; i++) { var c = list[i]; var np = nearestPlayer(c.pos); var act = ACT[c.species], dorm = DORM[c.species];
      if (!c.active) { if (np.a && np.d < act && H.t >= c.respawnAt && (c.species !== 'HORSE' || np.d > 12)) activate(c); continue; }
      var cb = c.combatant = f.combatant(c.id); if (!cb) { c.active = false; c.state = 'DORMANT'; continue; }
      if (!np.a || np.d > dorm) { deactivate(c, np.a ? 'FAR' : 'NO_PLAYER'); continue; }
      if (koHandling(c, cb)) continue;
      if (c.species === 'FISH') fishTick(c, dt, f); else if (c.species === 'HORSE') { horseTick(c, dt, f); var CPh = col(); if (CPh && CPh.groundHeight) { c.y = groundAt(c.pos.x, c.pos.z, c.y || 0); if (c.combatant) c.combatant.altitude = c.y; } } else phoenixTick(c, dt, f); }   /* the horse stands on the collider ground (terraces / the highland) — review finding 2026-09-20 */
  }
  function view() { var out = []; for (var i = 0; i < list.length; i++) { var c = list[i]; if (!c.active || !c.combatant) continue; var cb = c.combatant; var K = CB[c.species]; var terrainY = c.species === 'PHOENIX' ? groundAt(c.pos.x, c.pos.z, c.y) : undefined; out.push({ id: c.id, species: c.species, wild: true, school: c.school ? c.school.id : undefined, surface_y: c.school ? c.school.surface_y : undefined, position: { x: +c.pos.x.toFixed(3), z: +c.pos.z.toFixed(3) }, y: +c.y.toFixed(3), terrain_y: terrainY === undefined ? undefined : +terrainY.toFixed(3), terrain_clearance_m: terrainY === undefined ? undefined : +(c.y - terrainY).toFixed(3), facing: +c.facing.toFixed(3), state: c.state, speed_mps: +c.speed.toFixed(2), hp: +cb.hp.toFixed(1), max: cb.max, ko: !!cb.ko, ko_ago_s: c.koAt === null ? null : +(H.t - c.koAt).toFixed(2), attack_t: cb.cast ? (cb.cast.phase === 'STARTUP' ? Math.min(1, cb.cast.t / Math.max(0.01, cb.cast.startup)) * 0.6 : 0.6 + 0.4 * Math.min(1, cb.cast.t / Math.max(0.01, cb.cast.recovery || 1))) : null, level: cb.wild && cb.wild.level || (K && K.level) || 1, name: c.species, hit_ago_s: cb.last_hit_t === undefined ? null : +(H.t - cb.last_hit_t).toFixed(2), fight: !!(c.fight || c.feint), aura: K.aura, aura_attack: K.aura_attack, active: true }); } return out; }
  function summary() { var by = {}; list.forEach(function (c) { var s = by[c.species] = by[c.species] || { total: 0, active: 0, fighting: 0 }; s.total++; if (c.active) s.active++; if (c.fight || c.feint) s.fighting++; if (c.species === 'PHOENIX') { s.clearance_hits = (s.clearance_hits || 0) + (c.clearanceHits || 0); s.steering = (s.steering || 0) + ((c.steer || 0) > 0.05 ? 1 : 0); } }); return { enabled: true, species: by, combat: { FISH: { hits_to_kill: CB.FISH.hits_to_kill, hits_to_kill_player: CB.FISH.hits_to_kill_player }, HORSE: { hits_to_kill: CB.HORSE.hits_to_kill, hits_to_kill_player: CB.HORSE.hits_to_kill_player }, PHOENIX: { hits_to_kill: CB.PHOENIX.hits_to_kill, hits_to_kill_player: CB.PHOENIX.hits_to_kill_player } } }; }
  /* dev diagnostics (intentional): force a scenery breach in the school nearest a point; force the phoenix to engage */
  function summon(species, p) { if (species === 'FISH') { var best = null, bd = 1e12; list.forEach(function (c) { if (c.species !== 'FISH' || !c.active) return; var d = dist(c.pos, p || { x: 0, z: 0 }); if (d < bd) { bd = d; best = c; } }); if (best && !best.breach && !best.fight) { best.breach = { t0: H.t, x: best.pos.x, z: best.pos.z, hx: -Math.sin(best.facing), hz: -Math.cos(best.facing), y0: best.y }; best.school.breacher = best.id; return true; } return false; } if (species === 'PHOENIX') { var ph = null, pd = 1e12; list.forEach(function (c) { if (c.species !== 'PHOENIX' || !c.active || !c.combatant) return; var d = dist(c.pos, p || { x: 0, z: 0 }); if (d < pd) { pd = d; ph = c; } }); if (ph) { ph.combatant.last_hit_t = H.t; return true; } } return false; }
  return { enabled: true, tick: tick, view: view, summary: summary, creatures: function () { return list; }, summon: summon, CB: CB };
}
